planning/motion_velocity_smoother/src/smoother/analytical_jerk_constrained_smoother/analytical_jerk_constrained_smoother.cpp

This is a fix for the issue of the process dying in the behavior_velocity_planner.
Checked in the planner won't die in the several map with an intersection, crosswalk traffic light scenes.

fix(motion_velocity_smoother): resample making empty path

---

launch/tier4_perception_launch/launch/obstacle_segmentation/ground_segmentation/ground_segmentation.launch.py

Signed-off-by: badai-nguyen <dai.nguyen@tier4.jp>
There is no any node publishes /perception/obstacle_segmentation output_topic when [both use_time_series_filter and use_single_frame_filter set to false](https://github.com/autowarefoundation/autoware_launch/blob/2f45d819777096eb41de51f9612df6ef6da933f8/autoware_launch/config/perception/obstacle_segmentation/ground_segmentation/ground_segmentation.param.yaml#L6) …

fix(ground_segmentation): fix unuse_time_series_filter bug

---

planning/freespace_planning_algorithms/package.xml

Added dependency nlohmann-json3-dev, used in https://github.com/autowarefoundation/autoware.universe/blob/main/planning/freespace_planning_algorithms/src/rrtstar_core.cpp#L17

build(freespace_planning_algorithms): add nlohmann-json-dev dependency

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_utils.cpp

brief explanation about the method to expand.

feat(behavior_path_planner): deal with non rectangle object avoidance

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_utils.cpp

When backward path is long enough for avoidance, the front point of the drivable area line string is weird.
Fixed the bug in this PR.
Please check the behavior when the front point of drivable area line string is close to the object.
**before**
[Screencast from 2023年02月08日 00時19分12秒.webm](https://user-images.githubusercontent.com/20228327/217285899-39dc2a6d-a333-4a13-be71-78c5d29f41bb.webm)
**after**
[Screencast from 2023年02月08日 00時14分03秒.webm](https://user-images.githubusercontent.com/20228327/217285149-a99298df-8994-4c83-b928-4fe7567e59d7.webm)
FYI: The parameter diff I changed to check if PR works well. …

fix(behavior_path_planner): fix drivable area for long backawrd avoidance path

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module_data.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

add option to disable path update
When the flag is set true

feat(behavior_path_planner): add option to disable path update

---

planning/behavior_path_planner/src/scene_module/lane_change/util.cpp

Currently, the generated lane change points lane ids are not properly sorted.
Ideally the lane ids should be sorted as follow
This PR aims to solve this by properly having a sorted lane ids.
#2836 
Test lane change function and it is expected that it behave as usual.

fix(lane_change): get sorted lane ids

---

planning/behavior_path_planner/src/scene_module/lane_change/util.cpp

Signed-off-by: Muhammad Zulfaqar Azmi <zulfaqar.azmi@tier4.jp>
Up until now, we confirm the whole lane change path via is in lanelet, which include prepare phase and lane changing phase. But because prepare phase originally doesn't divert from the current lane, and it is guarantee to be feasible, therefore we can actually ignore them from the check. 
This PR aims to fix the check by only check the shifted path. …

fix(lane_change): checks only shifted path for isInLanelet check

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_utils.cpp

When the object is extracted from the drivable area, its z is set wrong.
**before**
**after**

feat(behavior_path_planner): fix z of extracted drivable area

---

control/operation_mode_transition_manager/src/node.cpp
control/operation_mode_transition_manager/src/state.cpp

In operation_mode_transition_manager node,  if `transition_timeout` is less than or equal to `stable_check.duration`, Autoware never succeeds to engage. 
I added a function to forcibly rewrite `transition_timeout`  parameter if such a parameter is set, 
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contri …

feat(operation_mode_transition_manager): add guard to invalid parameter

---

simulator/simple_planning_simulator/include/simple_planning_simulator/simple_planning_simulator_core.hpp
simulator/simple_planning_simulator/launch/simple_planning_simulator.launch.py
simulator/simple_planning_simulator/package.xml
simulator/simple_planning_simulator/src/simple_planning_simulator/simple_planning_simulator_core.cpp

Add imu publisher in the `simple_planning_simulator` so that the planning modules using imu info can run.
Run psim and check if the imu topic is published:
```
ros2 topic echo /sensing/imu/imu_data
```

feat(simple_planning_sim): publish sensing interface imu data

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

The drivable area expansion algorithm I modified should be applied not only to intersection but also outside the intersection as follows.
before
after

fix(behavior_path_planner): fix drivable area expansion method outside intersection

---

planning/behavior_path_planner/src/utilities.cpp

Currently, the overlapping checker in the `generateDrivableLane` has a serious issue, that is, it cannot add extended goal lanelets when the goal lanelet has adjacent lanes. In this PR, I fixed this issue to enable it to add extended goal lane.
- Before this PR (It failed to extend the goal lanelet, and obstacle_avoidance_planner inserts zero_velocity)
- After this PR …

fix(behavior_path_planner): fix overlapping checker

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

The reason for unavoidance was set wrong.

fix(behavior_path_planner): fix the reason of behind threshold

---

planning/behavior_velocity_planner/src/scene_module/detection_area/scene.cpp

Signed-off-by: veqcc <ryuta.kambe@tier4.jp>
Currently, the module `detection_area` needs a lot of computational cost for searching witch point is included in a detection_area by `bg::within`. This is too heavy function and the size of points (pointCloud) is often over 10,000.
Thus, I introduce using the minimum enclosing circle of a detection_area. If a point is NOT included in the circle, then of course the point don't to be checked by `bg::within`, witch would reduce the latency.
The following graph shows how the detection_area is optimized by this method. The red graph is the original latency, and the blue one is my proposal.
- Could you check the algorithm carefully? This is somewhat complicated.
- I heard this kind of implementaion should not be in behavior_velocity module, but in …

perf(detection_area): point and polygon inclusion check by minimum enclosing circle

---

planning/behavior_path_planner/src/scene_module/lane_change/util.cpp

Signed-off-by: Fumiya Watanabe <rej55.g@gmail.com>
Before this change, external request lane change module outputs improper path.
In this change, I fixed the validation logic of lane change path.
Note:
`lane_change_required_distance` is equal to 0 in lane change module.
So, this change effects to external request lane change module only.
Tested by planning simulator.
Before
After
[pull request …

fix(behavior_path_planner): fix lane change path validation logic

---

planning/behavior_velocity_planner/config/intersection.param.yaml
planning/behavior_velocity_planner/include/scene_module/intersection/scene_intersection.hpp
planning/behavior_velocity_planner/src/scene_module/intersection/manager.cpp
planning/behavior_velocity_planner/src/scene_module/intersection/scene_intersection.cpp

This PR reverts part of #2719 to continue collision checking after pass judge line.
- In case ego speed is slower than expected due to the later deceleration/control
- In small intersection lane
parameter PR(awf): https://github.com/autowarefoundation/autoware_launch/pull/203
parameter PR(tier4): https://github.com/tier4/autoware_launch/pull/769
CI result is OK
https://evaluation.tier4.jp/evaluation/reports/f76d27e4-ef8a-5036-ae27-0b2574cbb0d1?project_id=prd_jt …

fix(behavior_velocity_planner): continue collision checking after pass judge

---

planning/behavior_velocity_planner/include/scene_module/intersection/manager.hpp
planning/behavior_velocity_planner/src/scene_module/intersection/manager.cpp

Additional fix for following PRs. I restricted the condition for keeping the existing intersection module to check if the turn_direction is identical.
- https://github.com/autowarefoundation/autoware.universe/pull/2720
- https://github.com/autowarefoundation/autoware.universe/pull/2790
Checked by changing the left-turn route by placing a checkpoint.
After changing the path from a left-turn route to straight one, the intersection module for left-turn lane was still running.
The intersection module for left-turn lane is not running, and the one for straight lane is running instead.
- We may need a mechanism to reset the planning module when the route is changed externally.
- For merge_from_private module, LC is not considered
- intersection module needs additional change for generating stop …

fix(behavior_velocity_planner): keep intersection module for lanes with same parent and same direction

---

perception/lidar_centerpoint/package.xml

This uses the APT version of the dependency (instead of from PyPI), see https://github.com/ros/rosdistro/pull/36052

build(lidar_centerpoint): use APT version of python3-open3d as dependency

---

planning/mission_planner/src/mission_planner/arrival_checker.cpp
planning/mission_planner/src/mission_planner/arrival_checker.hpp
planning/mission_planner/src/mission_planner/mission_planner.cpp

Add random id to route. It's random id instead of uuid for now.

feat(mission_planner): add random id to route

---

perception/map_based_prediction/src/path_generator.cpp

Signed-off-by: veqcc <ryuta.kambe@tier4.jp>
The node `map_based_prediction` is too slow to publish `/perception/object_recognition/objects` topic when there are a lot of vehicles around the ego. This is due to the inefficient implementation of `interpolateReferencePath`, especially the calculation of the length of paths with `calcSignedArcLength`. It calls the `calcSignedArcLength` function for EVERY index of the path. This can be optimized with the idea cumulative sum, in which the path length of 0 to i-th index can be easily calculated with the value of 0 to (i-1)th.
The following figure shows how latencies are optimized with the idea. The red graph is the original latency, and the blue graph is the latency of the proposed implementation.

perf(map_based_prediction): performance improvement of interpolateReferencePath with cumulative sum

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

bug: R(L) Avoid rtc status remain on FOA even after the avoidance module revert the avoidance path.
resolution: remove rtc status when the ego is in YIELD maneuver.
set this flat `true`
https://github.com/autowarefoundation/autoware_launch/blob/1a52b77d9eaf140039f939cbc6777899f1f487ec/autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml#L18-L19
Remove approved R Avoid from FOA after the ego is in YIELD maneuver.
https://user-images.githubusercontent.com/44889564/218607813-cb509eaf-f73a-48b2-8e33-861c90a7b1b2.mp4
The …

fix(avoidance): remove rtc status when the ego is in YIELD maneuver

---

perception/crosswalk_traffic_light_estimator/README.md
perception/crosswalk_traffic_light_estimator/include/crosswalk_traffic_light_estimator/node.hpp
perception/crosswalk_traffic_light_estimator/src/node.cpp

estimate the corresponding pedestrian traffic light as red when the vehicle traffic light is not only green but also amber.
(TierIV Intenal Link: https://star4.slack.com/archives/C4P0NSMB5/p1675914220312339 ) 
I checked that there was no degradation on traffic light recognition functionusing psim/lsim.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributi …

feat(crosswalk_traffic_light_estimator): estimate the corresponding pedestrian traffic light as red also when the vehicle traffic light is amber

---

planning/planning_debug_tools/scripts/trajectory_visualizer.py

Temporally fix. Without this code, subscriber won't work due to the callback being stuck.

fix(trajectory_visualizer): fix topic callback

---

planning/behavior_path_planner/src/utilities.cpp

Signed-off-by: Muhammad Zulfaqar Azmi <zulfaqar.azmi@tier4.jp>
The logic to get the path with maximum confidence is incorrect, so the PR aims to fix this by changing the sign of the maximum check.
Also, the code is slightly refactored.

fix(lane_change): fix object predicted path getter logic

---

planning/obstacle_stop_planner/config/obstacle_stop_planner.param.yaml
planning/obstacle_stop_planner/include/obstacle_stop_planner/debug_marker.hpp
planning/obstacle_stop_planner/include/obstacle_stop_planner/node.hpp
planning/obstacle_stop_planner/include/obstacle_stop_planner/planner_data.hpp
planning/obstacle_stop_planner/include/obstacle_stop_planner/planner_utils.hpp
planning/obstacle_stop_planner/src/debug_marker.cpp
planning/obstacle_stop_planner/src/node.cpp
planning/obstacle_stop_planner/src/planner_utils.cpp

Fixes: #2222
Before this PR, [#140](https://github.com/autowarefoundation/autoware_launch/pull/140) needs to merge
The Reviewers **must** check the checkboxes below before approval.

feat(obstacle_stop_planner): add configurable lateral_distance for different target objects

---

perception/map_based_prediction/src/map_based_prediction_node.cpp

Signed-off-by: veqcc [ryuta.kambe@tier4.jp](mailto:ryuta.kambe@tier4.jp)
The motivation to improve the latency of map_based_prediction node is the same as https://github.com/autowarefoundation/autoware.universe/pull/2883 .
How I optimized `getPredictedReferencePath` is to remove the `getLanletAngle` function calls. In `getLanletAngle`, we search which segment is the closest to the point in parameter, where the segments are created from two adjacent centerline points in lanelet. These points in parameter, however, are exactly the points of centerline in lanelet (as seen in `convertPathType`). Thus, we don't have to walk through the lanelet centerline points again and to calculate the yaw from the previous point is enough.
The following figure shows how latencies are optimized with the …

perf(map_based_prediction): calculate yaw without calling getLaneletAngle

---

control/pure_pursuit/src/pure_pursuit/pure_pursuit_lateral_controller.cpp

When candidate point for the curvature calculation isn't found, 0 is returned to avoid unnecessary warnings.
But there is a still space to solve this probelem by 
- shifting closest point so that enough distance can be gotten.
- changing distane from the closest point between forward direction and backward direction. …

fix(pure_pursuit): return zero curvature when neighboring idx isn't found

---

common/path_distance_calculator/src/path_distance_calculator.cpp

Do not calculate distance when too short path is subscribed to avoid process-death by invalid access here
```
const double distance =
motion_utils::calcSignedArcLength(path->points, pose->pose.position, path->points.size() - 1);
```
[TERIV Internal](https://star4.slack.com/archives/C017VB9UG1L/p1676457271165259)
I confirmed that the path_distance_calculator node works normally using the planning simulator.
$ros2 launch path_distance_calculator path_distance_calculator.launch.xml 
(But I didn't test that the node didn't die when a too short path is subscribed.) …

fix(path_distance_calculator): do not calculate distance when too short path is subscribed

---

perception/map_based_prediction/config/map_based_prediction.param.yaml
perception/map_based_prediction/include/map_based_prediction/map_based_prediction_node.hpp
perception/map_based_prediction/src/map_based_prediction_node.cpp

Signed-off-by: yoshiri <yoshiyoshidetteiu@gmail.com>
Try to update lane change decision logic.
New logic uses following information as decision threshold.
1. distance from left/right boundary
2. predicted time to reach left/right boundary = distance / lateral speed
Actual LC decision fires when:
- bounding box center is close enough to reach left/right boundary 
- predicted arrival time is shorter than threshold
- (vehicle is approaching to boundary)
- [TIER IV Internal link 1](https://tier4.atlassian.net/wiki/spaces/~62d0f5dcafe495359d9e364c/pages/2687699394/LaneChange+LC)
- [TIER IV Internal link 2](https://tier4.atlassian.net/wiki/spaces/~62d0f5dcafe495359d9e364c/pages/2660729607/prediction#:~:text=pdf/1912.11676.pdf-,Action1%3A%20%E3%83%AC%E3%83%BC%E3%83%B3%E3%83%81%E3%82%A7%E3%83%B3%E …

feat(map_based_prediction): update lane change decision logic

---

common/motion_utils/include/motion_utils/trajectory/interpolation.hpp
common/motion_utils/src/trajectory/interpolation.cpp
common/motion_utils/test/src/trajectory/test_interpolation.cpp

Added calcInterpolatedPoint for PathWithLaneId

feat(motion_utils): add calc interpolated point for path with lane id

---

common/motion_utils/include/motion_utils/trajectory/interpolation.hpp
common/motion_utils/src/trajectory/interpolation.cpp
common/motion_utils/test/src/trajectory/test_interpolation.cpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

Considering avoidance by motion where the ego moves to the next lane, I changed the method to find the ego's narest lanelet in behavior's avoidance module.
TIER IV internal link
https://star4.slack.com/archives/C03QW0GU6P7/p1675941447846799?thread_ts=1675932511.759409&cid=C03QW0GU6P7
NOTE: The current motion does not yet support the obstacle avoidance function.
**Test**
During avoidance by behavior, I put the ego pose on the next lanelet. Nothing wrong happened. …

feat(behavior_path_planner): unshifted pose as closest previous path

---

planning/surround_obstacle_checker/src/node.cpp

There was a problem that errors were not given by giving default_value in the declare_parameter function. 
Therefore, the declare parameter in the surround_obstacle_checker module was removed.
[delete_param.webm](https://user-images.githubusercontent.com/100691117/218953940-2bf14cef-727b-4e17-a183-b4c657f92ffd.webm)
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/m …

fix(surround_obstacle_checker): delete default param

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

The module outputs previous path when the avoidance path generation is failed.

fix(avoidance): use previous output when the avoidance path generation is failed

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/util.hpp
planning/behavior_path_planner/src/scene_module/lane_change/external_request_lane_change_module.cpp
planning/behavior_path_planner/src/scene_module/lane_change/lane_change_module.cpp
planning/behavior_path_planner/src/scene_module/lane_change/util.cpp
planning/route_handler/include/route_handler/route_handler.hpp
planning/route_handler/src/route_handler.cpp

The range for safety check for target lane is currently depends on the registered target lane.
When an object is out of the registered lane, safety check will not be performed on the object.
In the following video, because the target lane is short, when ego move past the short lane, the last target lane is removed, therefore, even if there is an object in that lane, it will be totally ignored.
https://user-images.githubusercontent.com/93502286/215367019-fdbc342a-8f68-4165-82b1-84408aae1277.mp4
This PR aims fix this by extending the target lane during collision checking.
After all …

fix(lane_change): extend target lane range in safety check

---

perception/tensorrt_yolox/include/tensorrt_yolox/tensorrt_yolox_node.hpp
perception/tensorrt_yolox/package.xml
perception/tensorrt_yolox/src/tensorrt_yolox_node.cpp

Signed-off-by: yukke42 <yusuke.muramatsu@tier4.jp>
- fix to use `existence_probability` as the object confidence
- use perception_utils to set classification

fix(tensorrt_yolox): set existence_probability

---

planning/behavior_path_planner/include/behavior_path_planner/behavior_path_planner_node.hpp
planning/behavior_path_planner/include/behavior_path_planner/behavior_tree_manager.hpp
planning/behavior_path_planner/include/behavior_path_planner/data_manager.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/behavior_tree_manager.cpp

remove unused callback and member arg in `planner_data`.

fix(behavior_path_planner): remove unused callback functions

---

planning/behavior_path_planner/src/scene_module/pull_over/pull_over_module.cpp

Fix the sudden stop in pull over.
When the goal is at the edge of goal search area, the deceleration point can not be calculated with geometric pull over because the search area start point is after the first partial path. And set deceleration velocity to all path points including the current position. This causes 0 velocity at the current position with motion velocity smoother.
In this PR, use the full path to calculate the search area start.
https://user-images.githubusercontent.com/39142679/219312964-b9065207-a006-46ce-bf1e-2f19ce9aa026.mp4
psim, 
scenario test (tier4 internal https://evaluation.tier4.jp/evaluation/reports/12d7c886-0d45-5103-995d-bdabc35acf92?project_id=prd_jt) …

fix(behavior_path_planner): fix pull over deceleration before search area start

---

launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.py
launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/compare_map.launch.py
launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/vector_map_inside_area_filter.launch.py
planning/behavior_velocity_planner/CMakeLists.txt
planning/behavior_velocity_planner/config/run_out.param.yaml
planning/behavior_velocity_planner/include/scene_module/run_out/debug.hpp
planning/behavior_velocity_planner/include/scene_module/run_out/dynamic_obstacle.hpp
planning/behavior_velocity_planner/include/scene_module/run_out/manager.hpp
planning/behavior_velocity_planner/include/scene_module/run_out/scene.hpp
planning/behavior_velocity_planner/include/scene_module/run_out/utils.hpp
planning/behavior_velocity_planner/package.xml
planning/behavior_velocity_planner/src/scene_module/run_out/debug.cpp
planning/behavior_velocity_planner/src/scene_module/run_out/dynamic_obstacle.cpp
planning/behavior_velocity_planner/src/scene_module/run_out/manager.cpp
planning/behavior_velocity_planner/src/scene_module/run_out/scene.cpp
planning/behavior_velocity_planner/src/scene_module/run_out/utils.cpp

Currently, if you use pointcloud as an input for run_out, points in the `no_obstacle_segmentation_area` are ignored.
But it would not be safe if `no_obstacle_segmentation_area` is so close to the ego vehicle and there is an obstacle in that area like the image below.
So I added `mandatory_detection_area` that the obstacle in this area is not ignored even if it is in the `no_obstacle_segmentation_area` to ensure safety.
The obstacle in the `no_obstacle_segmentation_area` is ignored.
The obstacle in the `mandatory_detection_area` is detected even if it is in the `no_obstacle_segmentation_area`.
- parameter change for launch
- (awf/launch)
- https://github.com/autowarefoundation/autoware_launch/pull/205
- (tier4)
- https://github.com/tier4/autoware_launch/pull/770 …

feat(behavior_velocity): add mandatory detection area for run out module

---

control/vehicle_cmd_gate/config/vehicle_cmd_gate.param.yaml
control/vehicle_cmd_gate/src/vehicle_cmd_gate.cpp
control/vehicle_cmd_gate/src/vehicle_cmd_gate.hpp
launch/tier4_control_launch/launch/control.launch.py

In manual mode, the filter must consider the current status (e.g. current steering angle) to prevent sudden movement when switching from manual to autonomous.
The current implementation only checks for the previous commands, which makes a large difference between the actual status and command, then results in the sudden movement of the steering and acceleration.
This PR only focuses on the steering behavior because longitudinal information can not be changed easily for other modules.
https://github.com/tier4/autoware_launch/pull/733
https://github.com/autowarefoundation/autoware_launch/pull/189 …

feat(vehicle_cmd_gate): enable filter with actual steer in manual mode

---

planning/behavior_path_planner/include/behavior_path_planner/behavior_path_planner_node.hpp
planning/behavior_path_planner/include/behavior_path_planner/data_manager.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_interface.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
planning/behavior_path_planner/src/scene_module/lane_following/lane_following_module.cpp
planning/behavior_path_planner/src/scene_module/pull_over/pull_over_module.cpp
planning/behavior_path_planner/src/scene_module/side_shift/side_shift_module.cpp

move duplicated function (findEgoIndex, findEgoSegmentIndex) to planner data

fix(behavior_path_planner): move findEgoIndex & findEgoSegmentIndex to planner data

---

planning/behavior_velocity_planner/include/scene_module/intersection/manager.hpp
planning/behavior_velocity_planner/include/scene_module/intersection/scene_intersection.hpp
planning/behavior_velocity_planner/include/scene_module/intersection/scene_merge_from_private_road.hpp
planning/behavior_velocity_planner/include/scene_module/intersection/util.hpp
planning/behavior_velocity_planner/include/utilization/util.hpp
planning/behavior_velocity_planner/src/scene_module/intersection/debug.cpp
planning/behavior_velocity_planner/src/scene_module/intersection/manager.cpp
planning/behavior_velocity_planner/src/scene_module/intersection/scene_intersection.cpp
planning/behavior_velocity_planner/src/scene_module/intersection/scene_merge_from_private_road.cpp
planning/behavior_velocity_planner/src/scene_module/intersection/util.cpp
planning/behavior_velocity_planner/src/utilization/util.cpp

Changed collision checking and some of the area generation based on the path, not the lane considering lane changing before  / inside intersection.
Internal JIRA link: https://tier4.atlassian.net/browse/T4PB-25079
working as before because `ego_lane` polygon(the orange polygon) is also generated from the path.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/co …

feat(intersection): consider lane change in intersection based on associative ids

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/lane_change_module_data.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/util.hpp
planning/behavior_path_planner/src/scene_module/lane_change/external_request_lane_change_module.cpp
planning/behavior_path_planner/src/scene_module/lane_change/lane_change_module.cpp
planning/behavior_path_planner/src/scene_module/lane_change/util.cpp

This PR is related to lane change performance improvement.
As the effort to reduce computation, the PR aims to fix two things
1. getting dynamic object indices for collision check. 
Since we can expect that across all candidate path, the relation between the path and objects are fairly same, therefore, we only need to compute the path once.
2. return once both valid and safe path is found.
Since we don't really need to compute all the candidate path at all time, this will safe time by a little.
[TIER IV internal link](https://tier4.atlassian.net/browse/T4PB-25681)
Use the rosbag in the [TIER IV internal link](https://tier4.atlassian.net/browse/T4PB-25681) and compare before and after. It is expected that the computation time is reduced.
Degradation test performed. No issues with the …

refactor(lane_change): compute obj indices return if safe path found

---

planning/behavior_path_planner/include/behavior_path_planner/data_manager.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_interface.hpp
planning/behavior_path_planner/include/behavior_path_planner/turn_signal_decider.hpp

[DIFF]
move following struct definition to data_manager.hpp
- TurnSignalInfo
- BehaviorModuleOutput
- CandidateOutput
[BACKGROUND]
I plan to add new framework and **another scene_module_interface.hpp** that supports new framework. Then, I avoid to define same struct in both of old and new scene_module_interface.hpp. Therefore, I want to move those definition from scene_module_interface.hpp.
[pull …

fix(behavior_path_planner): move module output interface definition

---

perception/detected_object_validation/include/obstacle_pointcloud_based_validator/obstacle_pointcloud_based_validator.hpp
perception/detected_object_validation/obstacle-pointcloud-based-validator.md
perception/detected_object_validation/src/obstacle_pointcloud_based_validator.cpp
perception/map_based_prediction/src/path_generator.cpp

Because the validator used fixed values, the point cloud density was lower for distant obstacles, and obstacles were removed.
In this PR, the value is changed so that it changes according to the distance.
However, the parameters are not tuned and remain the same as before.
A similar approach is used in the following package.
https://github.com/autowarefoundation/autoware.universe/blob/main/perception/occupancy_grid_map_outlier_filter/include/occupancy_grid_map_outlier_filter/occupancy_grid_map_outlier_filter_nodelet.hpp#L63-L65 …

feat(detected_object_validation): add dynamic min pointcloud num

---

planning/behavior_path_planner/src/utilities.cpp

In the cause of the video, lanes and the path are cut with `cutOverlappedLanes` and the vehicle gets stuck.
The cause of this is that when a lane intersects at even a single point, that lane and path point are removed.
In this PR, lanes with a single point of intersection are kept.
https://user-images.githubusercontent.com/39142679/220060499-923caf96-91da-4718-aefe-fd8117fdf22f.mp4
--------- 
NOTES:
After discussion with @purewater0901 @TakaHoribe, it is better to keep lanes that share a linestring too and remove only lanes that completely overlap, but the former requires modifying `generateDrivableArea`, so it is left removed in this PR.
todo: support `generateDrivableArea` for lanes sharing a linestring
psim
[tier iv internal scenario …

fix(behavior_path_planner): fix cutOverlappedLanes

---

control/lane_departure_checker/config/lane_departure_checker.param.yaml
control/lane_departure_checker/include/lane_departure_checker/lane_departure_checker_node.hpp
control/lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker_node.cpp

Signed-off-by: Berkay Karaman <brkay54@gmail.com>
In current implementation, `lane_departure_checker` is only checking the vehicle's current lane. However, in some conditions, vehicle can be driven in other lanes. For example, because bus is large vehicle, it can not fit in lanes especially in sharp turns and `lane_departure_checker` publishes emergency then make vehicle stop. But, user should define the borders of drivable area for `lane_departure_checker`. To do this, I added some options about which lanes should be included to drivable area borders.
cc. @kyoichi-sugahara 
It is little urgent change, we need to merge this before BusODD.
The PR …

feat(lane_departure_checker): include neighbor lanelets as optional

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_interface.hpp
planning/behavior_velocity_planner/include/scene_module/scene_module_interface.hpp

replace generateUUID() with tier4_autoware_utils's function

refactor(behavior_planning): replace generateUUID() with tier4_autoware_utils's function

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module_data.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_utils.hpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_utils.cpp

**when disable_path_update  is true**
All the target_objects are removed from the drivable area
**when disable_path_update is false**
A part of the target_objects, whose `is_avoidable` is false, are removed from the drivable area

feat(behavior_path_planner): check if object is avoidable for drivable area generation

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module_data.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_utils.hpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_utils.cpp

This includes the change of https://github.com/autowarefoundation/autoware.universe/pull/2850
Added a dynamic margin when extracting objects from the drivable area.
The margin is calculated by the rule-based avoidance algorithm.
I attached some figures with different margins below. A bit hard to see the difference of margins by figures though.
When the margin is 1.7m
When the margin is 1.2m
When the margin is 0.9m
**NOTE**
must be merged after the following PR.
https://github.com/autowarefoundation/autoware.universe/pull/2850 …

feat(behavior_path_planner): drivable area with dynamic margin for static obstacles

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_utils.hpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_utils.cpp

This includes the change of https://github.com/autowarefoundation/autoware.universe/pull/2852
dealt with complicated static obstacles
rough sketch of the algorithm on this PR.
**case1**
before
after
**case2**
before
after
**case3**
before
after

fix(behavior_path_planner): drivable area with static obstacles

---

planning/obstacle_stop_planner/src/adaptive_cruise_control.cpp
planning/obstacle_stop_planner/src/node.cpp

https://github.com/autowarefoundation/autoware_launch/pull/222
[obstacle_stop_planner_delete_param.webm](https://user-images.githubusercontent.com/100691117/220527206-1addf774-cdbc-4623-8d61-2504aec54c14.webm) …

fix(obstacle_stop_planner): delete default values

---

launch/tier4_map_launch/launch/map.launch.xml
map/map_loader/launch/lanelet2_map_loader.launch.xml

Signed-off-by: melike tanrikulu <melike@leodrive.ai>
This PR aims to provide the ability to change lanelet2 map configurations from within tier4_map_launch.
At the same time, the following PR has been created in order to make changes to the config file in autoware_launch.
Related PR: https://github.com/autowarefoundation/autoware_launch/pull/169 …

chore(tier4_map_launch): add lanelet2 config files to tier4_map_launch

---

launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml

This PR to remove `clustering/detected_object_feature_remover`  from detection architecture since it becomes unnecessary after PR #2845 is merged.

fix(tier4_perception_launch): remove unnecessary node

---

common/signal_processing/package.xml

This makes sure that downstream packages have the correct dependencies (e.g. they can include `boost/optional.hpp`)

build(signal_processing): add Boost to build_export_depend

---

planning/external_velocity_limit_selector/src/external_velocity_limit_selector_node.cpp

[external_velocity_limit_selector_delte_param.webm](https://user-images.githubusercontent.com/100691117/220572944-9692a14e-8d83-4d10-b3e8-5bf35e49f423.webm)

fix(external_velocity_limit_selector): delete default values

---

control/shift_decider/src/shift_decider.cpp

[shift_decider_delete_param.webm](https://user-images.githubusercontent.com/100691117/221151774-d0c33d41-34c1-4cdb-98ea-05b50e73f5bc.webm)

refactor(shift_decider): delete default values

---

control/obstacle_collision_checker/src/obstacle_collision_checker_node/obstacle_collision_checker_node.cpp

[obstacle_collision_checker_delete_param.webm](https://user-images.githubusercontent.com/100691117/221145444-a14a3547-31d8-42ba-aa84-5374407451b8.webm)

refactor(obstacle_collision_checker): delete default values

---

control/control_performance_analysis/src/control_performance_analysis_node.cpp

[controller_performance_analysis_delete_param.webm](https://user-images.githubusercontent.com/100691117/221135283-d6985907-c211-4fce-a7d8-6090941f644a.webm)

refactor(control_performance_analysis): delete default values

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp

The avoidance module outputs customized (stop/decel point inserted) reference path in waiting approval phase, but for now, the  node don't output the avoidance's customized path.
In this PR, it is able to output customized reference path even if it is in waiting approval phase.
**NOTE: pull out/over is fixed in following PR.**
https://github.com/autowarefoundation/autoware.universe/pull/2577
[pull …

fix(avoidance): output stop point inserted reference path

---

control/joy_controller/src/joy_controller/joy_controller_node.cpp

[joy_controller_delete_param.webm](https://user-images.githubusercontent.com/100691117/221124471-7514dd81-59a1-449c-ba2e-d84b4f3bc8be.webm)

refactor(joy_controller): delete default values

---

planning/motion_velocity_smoother/src/motion_velocity_smoother_node.cpp
planning/motion_velocity_smoother/src/smoother/analytical_jerk_constrained_smoother/analytical_jerk_constrained_smoother.cpp
planning/motion_velocity_smoother/src/smoother/jerk_filtered_smoother.cpp
planning/motion_velocity_smoother/src/smoother/l2_pseudo_jerk_smoother.cpp
planning/motion_velocity_smoother/src/smoother/linf_pseudo_jerk_smoother.cpp
planning/motion_velocity_smoother/src/smoother/smoother_base.cpp

[motion_velocity_smoother_delete_param.webm](https://user-images.githubusercontent.com/100691117/220579197-a4b1ce0e-4f49-4afc-81af-1ce2283ec912.webm)

refactor(motion_velocity_smoother): delete default values

---

planning/obstacle_stop_planner/README.md
planning/obstacle_stop_planner/config/obstacle_stop_planner.param.yaml
planning/obstacle_stop_planner/include/obstacle_stop_planner/node.hpp
planning/obstacle_stop_planner/include/obstacle_stop_planner/planner_data.hpp
planning/obstacle_stop_planner/src/node.cpp

Add margin for the obstacle behind the goal.
https://user-images.githubusercontent.com/39142679/221567808-deae4b13-b1e1-4200-87d3-b8bf44f439de.mp4
- psim
- [tier4 internal scenario test](https://evaluation.tier4.jp/evaluation/reports/bcb5ece4-8953-57cb-95e0-d0b58beb845c?project_id=prd_jt) 811/814
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pul …

feat(obstacle_stop_planner): add margin behind goal

---

planning/behavior_path_planner/include/behavior_path_planner/utilities.hpp
planning/behavior_path_planner/src/util/lane_change/util.cpp
planning/behavior_path_planner/src/utilities.cpp

Related to increasing performance of lane change module.
At the moment, ego pose and polyon is interpolated against its predicted path during safety check, together with target object. but this is unnecessary, as ego path can be interpolated only once.
To solve this, I have extracted ego pose and polygon computation so that it only computed once.
#2825  …

perf(lane_change): only compute interpolate ego once

---

planning/motion_velocity_smoother/src/smoother/jerk_filtered_smoother.cpp

Remove unnecessary constant values in the jerk-filtered optimization method.

feat(motion_velocity_smoother): improve velocity planning around stop point 

---

planning/behavior_path_planner/CMakeLists.txt
planning/behavior_path_planner/include/behavior_path_planner/behavior_path_planner_node.hpp
planning/behavior_path_planner/include/behavior_path_planner/data_manager.hpp
planning/behavior_path_planner/include/behavior_path_planner/parameters.hpp
planning/behavior_path_planner/include/behavior_path_planner/planner_manager.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module_v2/scene_module_interface.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module_v2/scene_module_manager_interface.hpp
planning/behavior_path_planner/include/behavior_path_planner/utilities.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/planner_manager.cpp
planning/behavior_path_planner/src/scene_module/scene_module_visitor.cpp
planning/behavior_path_planner/src/utilities.cpp

:arrow_down: This must merge before this PR.
https://github.com/autowarefoundation/autoware_launch/pull/218
In this PR, I add new manager that doesn't depend on behavior tree library. The manager is implemented based on the new architecture on [this](https://github.com/orgs/autowarefoundation/discussions/3097) discussion.
- Conventional manager that based on BT library still remains, and that manager is activated by default.
- Change manager in CMakelist.
- The new manager is not compatible with the old one. We have to add the new scene modules that support new manager.
- In this PR, there is no scene modules that support new manager. The new manager can only execute lane following.
- The new scene modules will be added in the other PRs.
- …

feat(behavior_path_planner): add new manager independent from behavior tree

---

planning/behavior_path_planner/CMakeLists.txt
planning/behavior_path_planner/include/behavior_path_planner/behavior_path_planner_node.hpp
planning/behavior_path_planner/include/behavior_path_planner/module_status.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_interface.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp

rename macro that is used for switching new/old framework.
before: `USE_BEHAVIOR_TREE`
after: `USE_OLD_ARCHITECTURE`

fix(behavior_path_planner): rename macro

---

planning/motion_velocity_smoother/src/smoother/jerk_filtered_smoother.cpp

Before this PR, motion velocity smoother computes optimal velocity with the terminal velocity = 0.1[m/s] even though we set the terminal velocity as 0.0[m/s]. This is caused by a inappropriate terminal velocity approximation in the optimization setting. In this PR, I fixed it by ignoring the terminal decision variable when the v_max is less than 0.01[m/s].
- Before the PR
```
[motion_velocity_smoother-26] v[0]: 0.25
[motion_velocity_smoother-26] v[1]: 0.287228
[motion_velocity_smoother-26] v[2]: 0.409081
[motion_velocity_smoother-26] v[3]: 0.544225
[motion_velocity_smoother-26] v[4]: 0.676198
[motion_velocity_smoother-26] v[5]: 0.802665
[motion_velocity_smoother-26] v[6]: 0.918985
[motion_velocity_smoother-26] v[7]: 1.02216
[motion_velocity_smoother-26] v[8]: 1.11583 …
```

fix(motion_velocity_smoother): fix terminal velocity optimization

---

sensing/pointcloud_preprocessor/src/crop_box_filter/crop_box_filter_nodelet.cpp

Fix bug in https://github.com/autowarefoundation/autoware.universe/pull/2908.
Resolve https://github.com/autowarefoundation/autoware.universe/issues/2970.

fix(crop_box_filter): fix bug

---

common/tier4_planning_rviz_plugin/include/path/display.hpp
common/tier4_planning_rviz_plugin/include/path/display_base.hpp

Fix a problem that the old visualized path remains in Rviz.

fix(tier4_rviz_planning_plugin): clear objects before return

---

planning/behavior_path_planner/include/behavior_path_planner/behavior_path_planner_node.hpp
planning/behavior_path_planner/include/behavior_path_planner/parameters.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_interface.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_manager_interface.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/side_shift/side_shift_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/util/side_shift/side_shift_parameters.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp

- remove unnecessary macros
- move `SideShiftParameters` definition to new header file `side_shift_parameters.hpp`

refactor(behavior_path_planner): remove unnecessary macros

---

control/pid_longitudinal_controller/src/pid_longitudinal_controller.cpp
perception/multi_object_tracker/src/tracker/model/big_vehicle_tracker.cpp
planning/behavior_velocity_planner/config/intersection.param.yaml
planning/behavior_velocity_planner/include/scene_module/intersection/scene_intersection.hpp
planning/behavior_velocity_planner/include/utilization/util.hpp
vehicle/accel_brake_map_calibrator/accel_brake_map_calibrator/include/accel_brake_map_calibrator/accel_brake_map_calibrator_node.hpp
vehicle/accel_brake_map_calibrator/accel_brake_map_calibrator/src/accel_brake_map_calibrator_node.cpp

Fix typos in source code comments
This pull request is a part of #2841 

chore(typo): fix typos in comment

---

control/lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker_node.cpp

[lane_departure_checker_delete_param.webm](https://user-images.githubusercontent.com/100691117/222089548-f6a7258f-a137-405f-995c-fa627cb701eb.webm)

refactor(lane_departure_checker): delete default values

---

perception/probabilistic_occupancy_grid_map/README.md
perception/probabilistic_occupancy_grid_map/config/laserscan_based_occupancy_grid_map.param.yaml
perception/probabilistic_occupancy_grid_map/config/pointcloud_based_occupancy_grid_map.param.yaml
perception/probabilistic_occupancy_grid_map/include/laserscan_based_occupancy_grid_map/laserscan_based_occupancy_grid_map_node.hpp
perception/probabilistic_occupancy_grid_map/include/pointcloud_based_occupancy_grid_map/occupancy_grid_map.hpp
perception/probabilistic_occupancy_grid_map/include/pointcloud_based_occupancy_grid_map/pointcloud_based_occupancy_grid_map_node.hpp
perception/probabilistic_occupancy_grid_map/launch/laserscan_based_occupancy_grid_map.launch.py
perception/probabilistic_occupancy_grid_map/launch/pointcloud_based_occupancy_grid_map.launch.py
perception/probabilistic_occupancy_grid_map/src/laserscan_based_occupancy_grid_map/laserscan_based_occupancy_grid_map_node.cpp
perception/probabilistic_occupancy_grid_map/src/pointcloud_based_occupancy_grid_map/occupancy_grid_map.cpp
perception/probabilistic_occupancy_grid_map/src/pointcloud_based_occupancy_grid_map/pointcloud_based_occupancy_grid_map_node.cpp

According to https://github.com/autowarefoundation/autoware.universe/issues/2906, grid map origin should be mutable depending on the use-case.
This PR tries to provide variable-frame-orientated grid map. (Called plan A in above issue)
TODO:
- Not using specific frame name (currently I set `velodyne_top` ), using main LiDAR message header to represent target frame should be better
[pull request …

feat(probablistic_occupancy_grid_map): add alternative to gridmap origin frame

---

planning/behavior_path_planner/behavior_path_planner_drivable_area_design.md

Fix the document where I change the `platuml` to `cpp`

fix(behavior_path_planner): fix drivable area document

---

perception/traffic_light_classifier/README.md
perception/traffic_light_classifier/src/cnn_classifier.cpp

- the option to build tensorrt engine without inference is required for test on cloud

feat(traffic_light_classifier): add build only option for tensort engine

---

sensing/pointcloud_preprocessor/src/crop_box_filter/crop_box_filter_nodelet.cpp

- if `!tf_input_frame_.empty()` :  whether `transform_info.need_transform == true` or not, the frame_id during the computation phase should be `tf_input_frame_`.
- if `!tf_input_frame_.empty()` : `transform_info.need_transform == false` in this case, so we should assign `input->header.frame_id` as is, which means `tf_input_orig_frame_`. …

fix(crop_box_filter): deal with case when frame_id parameter is not set

---

perception/compare_map_segmentation/src/voxel_distance_based_compare_map_filter_nodelet.cpp

radiusSearch is faster than nearestKSearch as the search stops once no neighbor within the given radius is found (which is what we want to know here).
See https://pointclouds.org/documentation/classpcl_1_1search_1_1_search.html#af803bbb855706159fa2cd36e4e8f0c58

perf(compare_map_segmentation): replace nearestKSearch by radiusSearch

---

sensing/pointcloud_preprocessor/src/crop_box_filter/crop_box_filter_nodelet.cpp

See https://github.com/autowarefoundation/autoware.universe/issues/2974#issuecomment-1451169556
For example, crop box filters in euclidian cluster container would crash early before https://github.com/autowarefoundation/autoware.universe/pull/2979 fix:
```
[ERROR 1677724830.546998321] [perception.object_recognition.detection.clustering.euclidean_cluster_container]: Component constructor threw an exception: Crop box requires non-empty input_frame (on_load_node() at ./src/component_manager.cpp:278)
``` …

fix(pointcloud_preprocessor): throw error if crop box input frame is missing

---

common/tier4_state_rviz_plugin/src/autoware_state_panel.cpp

The reference variable for fail safe behavior was incorrect and has been corrected.

fix(autoware_state_panel): change variable for fail safe behavior

---

perception/tensorrt_yolox/README.md
perception/tensorrt_yolox/launch/yolox.launch.xml
perception/tensorrt_yolox/package.xml
perception/tensorrt_yolox/src/tensorrt_yolox_node.cpp

- the option to build tensorrt engine without inference is required for test on cloud
- add depend package
- fix documentation

feat(tensorrt_yolox): add build only option for tensorrt engine

---

planning/behavior_path_planner/include/behavior_path_planner/behavior_path_planner_node.hpp
planning/behavior_path_planner/include/behavior_path_planner/planner_manager.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_following/lane_following_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/util/lane_following/module_data.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/planner_manager.cpp
planning/behavior_path_planner/src/scene_module/lane_following/lane_following_module.cpp

Sinse the lane following planning logic is built in planner manager on the new framework, the lane following module is no longer needed to launch. In this PR, it is able to use same lane following parameters in planner manager. 

fix(behavior_path_planner): use lane following params in new framework

---

planning/freespace_planning_algorithms/include/freespace_planning_algorithms/abstract_algorithm.hpp
planning/freespace_planning_algorithms/src/rrtstar.cpp
planning/freespace_planning_algorithms/test/src/test_freespace_planning_algorithms.cpp

https://github.com/autowarefoundation/autoware/actions/runs/4335928129/jobs/7570862841#logs
```
[ 62%] Building CXX object CMakeFiles/freespace_planning_algorithms.dir/src/rrtstar.cpp.o
In file included from /__w/autoware/autoware/src/universe/autoware.universe/planning/freespace_planning_algorithms/include/freespace_planning_algorithms/rrtstar.hpp:18,
from /__w/autoware/autoware/src/universe/autoware.universe/planning/freespace_planning_algorithms/src/rrtstar.cpp:15:
In constructor ‘freespace_planning_algorithms::AbstractPlanningAlgorithm::AbstractPlanningAlgorithm(const freespace_planning_algorithms::PlannerCommonParam&, const freespace_planning_algorithms::VehicleShape&)’,
inlined from ‘freespace_planning_algorithms::RRTStar::RRTStar(const …
```

fix(freespace_planning_algorithms): fix uninitialized build error for self-hosted 

---

planning/behavior_path_planner/src/behavior_path_planner_node.cpp

Removing default values for lane change parameters.

refactor(lane change): delete default values

---

launch/tier4_planning_launch/launch/planning.launch.xml
planning/mission_planner/CMakeLists.txt
planning/mission_planner/README.md
planning/mission_planner/config/mission_planner.param.yaml
planning/mission_planner/launch/mission_planner.launch.xml
planning/mission_planner/src/lanelet2_plugins/default_planner.cpp
planning/mission_planner/src/lanelet2_plugins/default_planner.hpp
planning/mission_planner/src/lanelet2_plugins/utility_functions.cpp
planning/mission_planner/src/lanelet2_plugins/utility_functions.hpp

This PR adds config file to mission_planner and  parameter for refining goal pose in order to skip goal validation step. If added parameter is set to true, then given goal is refined according to the closest lane orientation.
autoware_launch PR (must be merged with this PR): https://github.com/autowarefoundation/autoware_launch/pull/225
https://user-images.githubusercontent.com/56237550/212691970-35c7803d-7609-4d29-886b-e0a08274dc06.mp4 …

feat(mission_planner): refine goal pose with parameter and add config file

---

planning/behavior_velocity_planner/src/scene_module/run_out/dynamic_obstacle.cpp

Detected points are sometimes unintentionally deleted because the place of `obstacle_points_map_filtered_.clear()` was inappropriate.
I confirmed this works with Planning Simulator.

fix(run_out): place of clearing points

---

launch/tier4_autoware_api_launch/launch/autoware_api.launch.xml

The same PR as following for rtc_controller
https://github.com/autowarefoundation/autoware.universe/pull/3011
The following message will be suppressed.
```[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/default_ad_api/node/fail_safe' in container '/default_ad_api/container'
[component_container_mt-37] [INFO 1678149779.194335670] [autoware_api.external.rtc_controller.container]: Found class: rclcpp_components::NodeFactoryTemplate<external_api::CalibrationStatus> (create_component_factory():127)
[component_container_mt-37] [INFO 1678149779.194393475] [autoware_api.external.rtc_controller.container]: Found class: rclcpp_components::NodeFactoryTemplate<external_api::CpuUsage> (create_component_factory():127)
[component_container_mt-37] [INFO 1678149779.194413434] …
```

feat(tier4_autoware_api_launch): suppress rtc_controller's info

---

planning/rtc_interface/include/rtc_interface/rtc_interface.hpp
planning/rtc_interface/src/rtc_interface.cpp

Before this change, if `rtc_interface` receives an auto mode service, it changes initial auto mode.
This is not expected behavior.
Correct behavior is that initial auto mode will not be changed if rtc_interface` receives an auto mode service.
So, in this PR, I changed the code.
Furthermore, as the minor change, to clarify the meaning of `is_auto_mode_`, I change the name to `is_auto_mode_init_`.
TIER IV internal test was passed.
882/882 …

fix(rtc_interface): fix initial auto mode

---

planning/behavior_path_planner/CMakeLists.txt
planning/behavior_path_planner/include/behavior_path_planner/behavior_path_planner_node.hpp
planning/behavior_path_planner/include/behavior_path_planner/parameters.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/lane_change_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/manager.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/scene_module/lane_change/lane_change_module.cpp
planning/behavior_path_planner/src/scene_module/lane_change/manager.cpp

⬇️  This must be merged before this PR.
https://github.com/autowarefoundation/autoware_launch/pull/239
- https://github.com/autowarefoundation/autoware.universe/pull/2919
- https://github.com/autowarefoundation/autoware_launch/pull/239
Before perfoming test, please comment out module names which haven't supported new framework yet in [rtc_auto_mode_manager.param.yaml](https://github.com/autowarefoundation/autoware_launch/blob/feat/support-new-framework-pull-over/autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/rtc_auto_mode_manager/rtc_auto_mode_manager.param.yaml). -->
```yaml
/**:
module_list:
- "blind_spot"
- "crosswalk"
- "detection_area"
- "intersection"
- "no_stopping_area"
- "traffic_light"
- "lane_change_left"
- "lane_change_right" …
```

feat(lane_change): support new framework

---

perception/traffic_light_classifier/README.md

Currently, in autoware, we recommend to use [open-mmlab/mmclassification](https://github.com/open-mmlab/mmclassification.git) for re-training CNN classifier.
Therefore I updated documents to train CNN models and apply  them to traffic light cnn classifier node.
After this PR is merged, I will add the link of this document to the Autoware documentaion, as disscussed in [this PR](https://github.com/autowarefoundation/autoware-documentation/pull/318). …

docs(traffic_ligtht_classifier): update document for CNN model customization

---

planning/behavior_path_planner/CMakeLists.txt
planning/behavior_path_planner/include/behavior_path_planner/behavior_path_planner_node.hpp
planning/behavior_path_planner/include/behavior_path_planner/parameters.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/manager.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/pull_over_module.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/scene_module/pull_over/manager.cpp
planning/behavior_path_planner/src/scene_module/pull_over/pull_over_module.cpp

https://github.com/autowarefoundation/autoware_launch/pull/237
It is able to build avoidance module on new framework (added in https://github.com/autowarefoundation/autoware.universe/pull/2919).
Checkout your branch of autoware_launch to `feat/support-new-framework-pull-over`.
https://github.com/autowarefoundation/autoware_launch/tree/feat/support-new-framework-pull-over
In addtion, we may have to comment out module names which haven't supported new framework yet in [rtc_auto_mode_manager.param.yaml](https://github.com/autowarefoundation/autoware_launch/blob/feat/support-new-framework-pull-over/autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/rtc_auto_mode_manager/rtc_auto_mode_manager.param.yaml).
```yaml …
```

feat(pull_over): support new framework

---

planning/behavior_path_planner/include/behavior_path_planner/planner_manager.hpp

In new manager, `updateData()` is called both of  inside and outside of `run()` function.
1
https://github.com/autowarefoundation/autoware.universe/blob/279e43430510781ea182973d4cf3fe32443af09a/planning/behavior_path_planner/include/behavior_path_planner/planner_manager.hpp#L134-L138
2
https://github.com/autowarefoundation/autoware.universe/blob/2a64ea607940eb3e354f33f7d962e7bf0d1f4be0/planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_interface.hpp#L135-L153
In this PR, I remove the former one. …

fix(behavior_path_planner): remove duplicated process updateData() in new manager

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module.hpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

Avoidance module decides that which RTC approval (right or left) status should be output based on the relative lateral offset between shift line start and end, and the module doesn't output RTC for straight shift line whose relative lateral offset is less than threshold (< 0.01). However the module should output RTC status in following situation even if the relative lateral offset is small.
So, in this PR, I use the relative lateral offset between shift line end and current output path for decision of RTC outputs.
```c++
double AvoidanceModule::getRelativeLengthFromPath(const AvoidLine & avoid_line) const
{
if (prev_reference_.points.size() != prev_linear_shift_path_.path.points.size()) {
throw std::logic_error("prev_reference_ and prev_linear_shift_path_ must have same size.");
}
const …
```

fix(avoidance): fix logic for RTC output decision

---

planning/obstacle_avoidance_planner/CMakeLists.txt

Removed `-march=native` option in cmake since the building on CI sometimes fails maybe due to this option.
https://github.com/autowarefoundation/autoware.universe/actions/runs/4363535826/jobs/7629737397
I confirmed that the calculation time and accuracy did not change with this PR.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guide …

fix(obstacle_avoidance_planner): remove the option march=native

---

planning/behavior_path_planner/include/behavior_path_planner/util/avoidance/avoidance_module_data.hpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

In current logic, only when the front (nearest) target object should be avoid and the avoidance path is unsafe, the module executes YIELD maneuver. But, it should execute YIELD maneuver in following scenarios, too.
- Ego doesn't have to avoid the front object (passable without avoidance path).
- Ego has to avoid the behind object.
- Avoidance path is unsafe.
I found two bugs in the avoidance module:
1. The module never execute YILED maneuver if the front object is **NOT** `avoid_require = true`.
2. The module never cancel approved avoidance path if the front object is **NOT** `avoid_require = true`.
:arrow_down: Ego collides with NPC because of above bugs.
https://user-images.githubusercontent.com/44889564/223875419-f575247a-d020-40aa-843b-98c1dfb2d974.mp4
---
> The module never execute …

fix(avoidance): fix unexpected behavior in yield scenario

---

control/mpc_lateral_controller/src/mpc.cpp

MPC optimization sometimes failed when it receives a steering status larger than `mpc_steering_limit`. It is due to the break of the optimization constraint.
This PR fixes the `prev_steering_value` considering the steering limit.
TIERIV COMPANY INTERNAL LINK: https://tier4.atlassian.net/browse/T4PB-26780
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contribu …

fix(mpc): optimization failure due to steer limit

---

common/tier4_planning_rviz_plugin/include/path/display.hpp

Without this PR, the following warning message is shown on the terminal when launching autoware.launch.xml or turning on the visualization of the path marker.
```
[rviz2-38] QObject::connect: No such slot rviz_common::_RosTopicDisplay::updateVisualization()
[rviz2-38] QObject::connect:  (sender name:   'View Drivable Area')
[rviz2-38] QObject::connect: No such slot rviz_common::_RosTopicDisplay::updateVisualization()
[rviz2-38] QObject::connect:  (sender name:   'Alpha')
[rviz2-38] QObject::connect: No such slot rviz_common::_RosTopicDisplay::updateVisualization()
[rviz2-38] QObject::connect:  (sender name:   'Color')
[rviz2-38] QObject::connect: No such slot rviz_common::_RosTopicDisplay::updateVisualization()
[rviz2-38] QObject::connect:  (sender name:   'Width')
[rviz2-38] …
```

fix(tier4_planning_rviz_plugin): supress initial warning message

---

planning/behavior_path_planner/config/pull_over/pull_over.param.yaml
planning/behavior_path_planner/include/behavior_path_planner/util/pull_over/freespace_pull_over.hpp
planning/behavior_path_planner/include/behavior_path_planner/util/pull_over/pull_over_parameters.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/util/pull_over/freespace_pull_over.cpp

https://github.com/autowarefoundation/autoware_launch/pull/246
- move parameter declaration to outside of scene module
- remove default params

refactor(pull_over): move parameter declare pull over

---

planning/behavior_path_planner/include/behavior_path_planner/utilities.hpp
planning/behavior_path_planner/src/scene_module/lane_change/lane_change_module.cpp
planning/behavior_path_planner/src/utilities.cpp

In this PR, I added new function `util::getCurrentLanesFromPath` to get current lanelet from not current pose but previous module output.
```c++
#ifdef USE_OLD_ARCHITECTURE
const auto current_lanes = util::getCurrentLanes(planner_data_);
#else
const auto current_lanes =
util::getCurrentLanesFromPath(*getPreviousModuleOutput().reference_path, planner_data_);
#endif
```
Additionaly, I added `util::getCenterLinePathFromRootLanelet` to output reference path that is used in next module.
```c++
#ifdef USE_OLD_ARCHITECTURE
path_reference_ = getPreviousModuleOutput().reference_path;
prev_approved_path_ = path;
#else
const auto reference_path =
util::getCenterLinePathFromRootLanelet(status_.lane_change_lanes.front(), planner_data_);
output.reference_path = …
```

fix(lane_change): use previous module output

---

common/motion_utils/src/resample/resample.cpp
planning/behavior_path_planner/include/behavior_path_planner/parameters.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/utilities.cpp

Applied akima spline for xy only first when getting centerline from lanelet.
**TODO**

feat(behavior_path_planner): use akima spline for xy only first

---

planning/behavior_path_planner/src/scene_module/lane_change/lane_change_module.cpp

**Bug: Lane change module change it's output path without approval, and it is an unexpected behavior.**
https://user-images.githubusercontent.com/44889564/224465019-d7a9971f-333d-41ab-8a52-0ad03c81529a.mp4
---
In this PR, it set `waitApproval()` in onEntry() in order to block `plan()` execution at first time in following `run()` function.
https://github.com/autowarefoundation/autoware.universe/blob/e4bcc868b09d6d465d0f4fa4fc62b30b2de36413/planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_interface.hpp#L135-L153
1.set option `COMPILE_WITH_OLD_ARCHITECTURE` to `FALSE`
https://github.com/autowarefoundation/autoware.universe/blob/2ace0d2b030cabf19ff037b56328cff07c2fb245/planning/behavior_path_planner/CMakeLists.txt#L10
2.disable rtc auto mode
```yaml
/**: …
```

fix(lane_change): lane change module changes output path intentionally without approval

---

system/system_error_monitor/src/system_error_monitor_core.cpp

Suppress initial warning "input data is timeout" before initializing the ego pose.

chore(system_error_monitor): supress initial warning

---

control/mpc_lateral_controller/include/mpc_lateral_controller/mpc.hpp
control/mpc_lateral_controller/src/mpc.cpp
control/mpc_lateral_controller/src/mpc_lateral_controller.cpp

**Before**
The previous steering value in MPC is updated with the actual steering only when `getData()` failed.
-> when `calculateMPC()` is failed for any reason other than `getData()` , the previous steering value is not updated, which is unexpected.
**After**
The previous steering value in MPC is updated with the actual steering whenever `calculateMPC()` failed.
TIERIV'S INTERNAL LINK: https://tier4.atlassian.net/browse/T4PB-26780
Run psim in several paths. …

fix(mpc): reset prev value when mpc failed

---

planning/behavior_path_planner/include/behavior_path_planner/util/lane_change/util.hpp
planning/behavior_path_planner/src/scene_module/lane_change/lane_change_module.cpp
planning/behavior_path_planner/src/util/lane_change/util.cpp

add new lane change utils function to generate prepare segment from previous module output.
```c++
PathWithLaneId getLaneChangePathPrepareSegment(
const PathWithLaneId & original_path, const lanelet::ConstLanelets & original_lanelets,
const Pose & current_pose, const double backward_path_length, const double prepare_distance,
const double prepare_speed);
``` …

fix(lane_change): use previous output

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

use previous module output in new manager

fix(avoidance): use previous module output

---

planning/behavior_path_planner/src/scene_module/lane_change/lane_change_module.cpp

Previously, the `updateLaneChnageStatus()` is called in onEntry() at once, and is never called again in new manager.
In this PR, I added `updateLaneChnageStatus()` to `planWaitingApproval()` in order to update `status_` every planning cycle.

fix(lane_change): update lane change status in planWaitingApproval()

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

Since the new manager can execute multiple modules simlutaneously, it limits avoidance execution only when modules run on the old manager.

fix(avoidance): be able to execute lc + avoidance simlutaneously

---

perception/tensorrt_yolox/src/tensorrt_yolox_node.cpp

Currently, `tensorrt_yolox` assigns `unknown` for all detected objects.
After this PR, it seems correct labels are assigned.
Before
https://user-images.githubusercontent.com/60615504/224645966-1a624ea3-1b29-4ae5-811c-a544e7ff07ff.mp4
After
https://user-images.githubusercontent.com/60615504/224646007-9b4a1dd7-8212-450a-ad58-e18ac20e6794.mp4 …

fix(tensorrt_yolox): resolve all output labels become unknown

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

Fix shift line merging logic. Before this PR, at `start_idx` and `end_idx`, the shift length is same value as `start_idx - 1` and `end_idx - 1` because the flag `has_object` is set `true` only between `start_idx + 1` and `end_idx - 1`. Then, the total shift line may not include edge of the raw shift line. …

fix(avoidance): fix shift line merging logic

---

planning/behavior_path_planner/src/scene_module/lane_change/lane_change_module.cpp

use previous module turn signal in waiting approval.

fix(lane_change): use previous module turn signal in waiting approval

---

evaluator/planning_evaluator/include/planning_evaluator/metrics/deviation_metrics.hpp
evaluator/planning_evaluator/include/planning_evaluator/metrics/metric.hpp
evaluator/planning_evaluator/include/planning_evaluator/metrics_calculator.hpp
evaluator/planning_evaluator/include/planning_evaluator/planning_evaluator_node.hpp
evaluator/planning_evaluator/launch/planning_evaluator.launch.xml
evaluator/planning_evaluator/package.xml
evaluator/planning_evaluator/param/planning_evaluator.defaults.yaml
evaluator/planning_evaluator/src/metrics/deviation_metrics.cpp
evaluator/planning_evaluator/src/metrics_calculator.cpp
evaluator/planning_evaluator/src/motion_evaluator_node.cpp
evaluator/planning_evaluator/src/planning_evaluator_node.cpp
evaluator/planning_evaluator/test/test_planning_evaluator_node.cpp

Add metrics of deviation from the modified goal pose
[
TIER IV internal scenario test](https://evaluation.tier4.jp/evaluation/reports/1a8b80d6-d0e3-5cd0-bf50-fe525dda5e81/tests/cb1630f0-dd61-5401-9011-8943a1b1ead9/55aa61e1-cec9-5db5-81d7-201d1de5e859?project_id=prd_jt)

feat(planning_evaluator): add modified goal deviation

---

perception/lidar_centerpoint/README.md
perception/lidar_centerpoint/include/lidar_centerpoint/centerpoint_trt.hpp
perception/lidar_centerpoint/include/lidar_centerpoint/network/network_trt.hpp
perception/lidar_centerpoint/include/lidar_centerpoint/network/tensorrt_wrapper.hpp
perception/lidar_centerpoint/launch/lidar_centerpoint.launch.xml
perception/lidar_centerpoint/lib/centerpoint_trt.cpp
perception/lidar_centerpoint/lib/network/network_trt.cpp
perception/lidar_centerpoint/lib/network/tensorrt_wrapper.cpp
perception/lidar_centerpoint/package.xml
perception/lidar_centerpoint/src/node.cpp

Signed-off-by: yukke42 <yusuke.muramatsu@tier4.jp>
Add a new feature to build onnx files to tensorrt engine files without inference for CI/CD requirements.

feat(lidar_centerpoint): add build only option for tensorrt engine

---

planning/behavior_path_planner/CMakeLists.txt
planning/behavior_path_planner/include/behavior_path_planner/parameters.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/lane_change_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/manager.hpp
planning/behavior_path_planner/include/behavior_path_planner/util/lane_change/lane_change_module_data.hpp
planning/behavior_path_planner/include/behavior_path_planner/util/lane_change/util.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/planner_manager.cpp
planning/behavior_path_planner/src/scene_module/lane_change/lane_change_module.cpp
planning/behavior_path_planner/src/scene_module/lane_change/manager.cpp
planning/behavior_path_planner/src/util/lane_change/util.cpp
planning/route_handler/include/route_handler/route_handler.hpp
planning/route_handler/src/route_handler.cpp

refactor lane change class so that it is more resemble to scene module manager
⬇️ This launcher needs to be merge first
https://github.com/autowarefoundation/autoware_launch/pull/248

refactor(lane change): lane change class rework

---

launch/tier4_perception_launch/launch/occupancy_grid_map/laserscan_based_occupancy_grid_map.launch.py
launch/tier4_perception_launch/launch/occupancy_grid_map/pointcloud_based_occupancy_grid_map.launch.py
launch/tier4_perception_launch/launch/perception.launch.xml
perception/probabilistic_occupancy_grid_map/CMakeLists.txt
perception/probabilistic_occupancy_grid_map/README.md
perception/probabilistic_occupancy_grid_map/config/laserscan_based_occupancy_grid_map.param.yaml
perception/probabilistic_occupancy_grid_map/config/pointcloud_based_occupancy_grid_map.param.yaml
perception/probabilistic_occupancy_grid_map/image/gridmap_frame_settings.drawio.svg
perception/probabilistic_occupancy_grid_map/include/laserscan_based_occupancy_grid_map/laserscan_based_occupancy_grid_map_node.hpp
perception/probabilistic_occupancy_grid_map/include/pointcloud_based_occupancy_grid_map/occupancy_grid_map.hpp
perception/probabilistic_occupancy_grid_map/include/pointcloud_based_occupancy_grid_map/pointcloud_based_occupancy_grid_map_node.hpp
perception/probabilistic_occupancy_grid_map/launch/laserscan_based_occupancy_grid_map.launch.py
perception/probabilistic_occupancy_grid_map/launch/pointcloud_based_occupancy_grid_map.launch.py
perception/probabilistic_occupancy_grid_map/src/laserscan_based_occupancy_grid_map/laserscan_based_occupancy_grid_map_node.cpp
perception/probabilistic_occupancy_grid_map/src/pointcloud_based_occupancy_grid_map/occupancy_grid_map.cpp
perception/probabilistic_occupancy_grid_map/src/pointcloud_based_occupancy_grid_map/pointcloud_based_occupancy_grid_map_node.cpp

In last PR https://github.com/autowarefoundation/autoware.universe/pull/2939, we set option for choosing occupancy grid map.  
This PR tries to add another option that enables to separate gridmap origin frame and scan sensor frame. (See figure below)
This change will be useful in asymmetric range sensor such as Hokuyo Lidar or stereo camera, and multiple-sensor-based grid map fusion.
fixed some bags that prevents this PR working. …

feat(probablisitic_occupancy_grid_map): add scan_frame option for gridmap generation

---

control/trajectory_follower_node/CMakeLists.txt

refactor(trajectory_follower_node): remove unnecessary cmake code

---

control/lane_departure_checker/include/lane_departure_checker/lane_departure_checker.hpp
control/lane_departure_checker/include/lane_departure_checker/lane_departure_checker_node.hpp
control/lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker.cpp
control/lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker_node.cpp

Use kinematic state for ego pose instead of tf.

fix(lane_departure_checker): use kinematic state for ego pose

---

common/tier4_autoware_utils/include/tier4_autoware_utils/geometry/boost_polygon_utils.hpp
common/tier4_autoware_utils/src/geometry/boost_polygon_utils.cpp
common/tier4_autoware_utils/test/src/geometry/test_boost_polygon_utils.cpp
planning/behavior_path_planner/src/util/avoidance/util.cpp

move `expandPolygon` used in the behavior_path_planner package to `common/`.

feat(tier4_autoware_utils): add expandPolygon function

---

launch/tier4_perception_launch/launch/occupancy_grid_map/laserscan_based_occupancy_grid_map.launch.py
launch/tier4_simulator_launch/launch/simulator.launch.xml

Due to the following PR's change to the config path of pointcloud_based_occupancy_grid_map , currently, the planning simulator does not work.
https://github.com/autowarefoundation/autoware.universe/pull/3032
I fixed the config path for occupancy grid map. Not all the bug was fixed with this PR.
NOTE: occupancy grid map is launched from not only tier4_perception_launch but also tier4_simulator_launch for planning simulator. …

fix(tier4_perception_launch): fix config path

---

launch/tier4_perception_launch/launch/occupancy_grid_map/laserscan_based_occupancy_grid_map.launch.py
launch/tier4_simulator_launch/launch/simulator.launch.xml
perception/probabilistic_occupancy_grid_map/config/laserscan_based_occupancy_grid_map.param.yaml
perception/probabilistic_occupancy_grid_map/launch/laserscan_based_occupancy_grid_map.launch.py

**Problem**
occupancy grid map is not generated in latest changes.
This is due to:
- psim should not use pointcloud based method since pointcloud based method yields both raw and obstacle pointclouds
- fixed args in laserscan based launch.py due to unintended bugs
**Changes**
- use laserscan-based method instead of pointcloud
- fix some args to fit psim environment
- fix laserscan based launch.py to make bool args changable …

fix(tier4_simulator_launch): fix occupancy grid map not appearing problem in psim 

---

planning/behavior_path_planner/include/behavior_path_planner/util/lane_change/util.hpp
planning/behavior_path_planner/src/util/lane_change/util.cpp

Fix the end of the longitudinal distance of the reference target lane segment.
Scenario Results 822/822
[Internal Link](https://evaluation.tier4.jp/evaluation/reports/fbdf480d-cda9-5a78-9949-9255dd487365?project_id=prd_jt)

fix(behavior_path_planner): fix lane changing segment s_end

---

planning/behavior_path_planner/include/behavior_path_planner/utilities.hpp
planning/behavior_path_planner/src/util/lane_change/util.cpp
planning/behavior_path_planner/src/utilities.cpp

Use lanelet utils for lateral distance calculation in the lane change module

feat(behavior_path_planner): use lanelet utils for lateral calculation

---

localization/pose_initializer/launch/pose_initializer.launch.xml

fix(pose_initializer): fix launch file

---

planning/behavior_path_planner/src/scene_module/pull_over/pull_over_module.cpp

Fix the problem that modified goal is not published when receiving new route  before modifying the goal

fix(behavior_path_planner): reset modified goal id

---

perception/lidar_centerpoint/config/centerpoint_tiny.param.yaml

When I uploaded the centerpoint tiny v2 I missed uploading the updated config file, which caused errors and an unnecessary bad performance.
The new file was tested in the environments in which the error arose

fix(lidar_centerpoint): updated the config file for the centerpoint tiny v2

---

planning/behavior_path_planner/src/util/lane_change/util.cpp

Since `[[maybe_unused]]` was removed in https://github.com/autowarefoundation/autoware.universe/pull/3083, build error are shown when it sets following flag to `FALSE`.
https://github.com/autowarefoundation/autoware.universe/blob/2a23a4bf9c74fa321f1483bbabe566f1c6246db9/planning/behavior_path_planner/CMakeLists.txt#L10
```
--- stderr: behavior_path_planner                                                                                                                                                                            
/home/satoshi/pilot-auto/src/autoware/universe/planning/behavior_path_planner/src/util/lane_change/util.cpp: In function 'std::pair<bool, bool> behavior_path_planner::lane_change_utils::getLaneChangePaths(const PathWithLaneId&, const route_handler::RouteHandler&, …
```

fix(lane_change): fix build error

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

Previously, the vehicle stopped in front of the vehicle in not only Scenario A but B. However I think it is better that the avoidance module shonldn't insert stopping velocity, and obstacle stop/cruise planner should do it instead in Scenario B, because the avoidance module never execute avoidance maneuver. In this PR, I update behavior decision logic, and the vehicle stops only when there is enough space to avoid (Scenario A). 
|  | Scenario A | Scenerio B |
|:------------:|:------------:|:------------:|
| there is enough space to avoid | YES (`is_avoidanble = true`) | NO (`is_avoidanble = false`) |
| there is enough lateral margin | NO (< `lateral_passable_safety_buffer`) | NO (< `lateral_passable_safety_buffer`) |
| behavior | stop in front of the target object | **NOT** stop in front …

fix(avoidance): stop only when there is enough space to avoid

---

system/system_error_monitor/src/system_error_monitor_core.cpp

Currently, system_error_monitor died with the following error due to the time resource is different.
`what(): can't subtract times with different time sources [1 != 2]`
related discussion: https://answers.ros.org/question/380328/robot_localization-cant-subtract-times-with-different-time-sources/ …

fix(system_error_monitor): fix dying node

---

control/autonomous_emergency_braking/CMakeLists.txt

**Related link**: https://github.com/autowarefoundation/autoware.universe/issues/1219
Suppress build error.
```
In file included from /usr/include/pcl-1.12/pcl/point_types.h:354,                                                                                                                                                                                                                                                                                                                                                              
from /usr/include/pcl-1.12/pcl/common/transforms.h:43, …
```

fix(AEB): suppress build error (-Werror=pedantic)

---

perception/ground_segmentation/docs/scan-ground-filter.md
perception/ground_segmentation/include/ground_segmentation/scan_ground_filter_nodelet.hpp
perception/ground_segmentation/src/scan_ground_filter_nodelet.cpp

This PR to add param to enable/off recheck ground cluster in scan_ground_filter_nodelet
[TIERIV COMPANY INTERNAL LINK](https://star4.slack.com/archives/CRUE57C30/p1679011743529499?thread_ts=1678861138.096609&cid=CRUE57C30)
https://github.com/autowarefoundation/autoware_launch/pull/259
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-gu …

chore(ground_segmentation): add recheck ground cluster option param

---

planning/surround_obstacle_checker/include/surround_obstacle_checker/node.hpp

As in the title, remove unused include for the trajectory msg.

fix(surround_obstacle_checker): remove unused include

---

common/motion_utils/include/motion_utils/trajectory/trajectory.hpp

Signed-off-by: Taiga Takano [taiga.takano@tier4.jp](mailto:taiga.takano@tier4.jp)
One of the major bottlenecks of this function is the execution of the atan function called within the calcYawDeviation function. Therefore, the order of execution of the conditional expressions is changed to reduce the likelihood that the calcYawDeviation function will be called.
This change speeds up the process as shown in the table below.
findNearestIndex callback latency
|  PERCENTILE  |  BEFORE (us)  |  AFTER (us)  |
| ---- | ---- | ---- |
|  99%  |  5.85  |  3.83  |
|  90%  |  3.81  |  3.36  |
|  50%  |  3.64  |  1.91  |

perf(motion_utils): improve performance of findNearestIndex

---

planning/behavior_path_planner/include/behavior_path_planner/marker_util/avoidance/debug.hpp
planning/behavior_path_planner/src/marker_util/avoidance/debug.cpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

visualize unavoidable target objects as red.
- green: other_objects
- yellow: target_objects, which can be avoidable by behavior
- red: target_objects, which cannot be avoidable by behavior but can be avoidable by motion.

feat(behavior_path_planner): visualize unavoidable target object

---

planning/planning_debug_tools/CMakeLists.txt

Install for perception_reproducer.py is missing.

fix(planning_debug_tools): install perception_reproducer.py

---

planning/static_centerline_optimizer/include/static_centerline_optimizer/static_centerline_optimizer_node.hpp
planning/static_centerline_optimizer/src/static_centerline_optimizer_node.cpp

In the static_centerline_optimizer node, when the plan_route() is executed twice, the node dies with below error. I fixed it.
```
what():  parameter 'ego_nearest_dist_threshold' has already been declared
```
I confirmed that ```Plan Route``` can be executed many times from vector_map_builder. …

fix(static_centerline_optimizer): avoid to call declear_parameter twice

---

vehicle/accel_brake_map_calibrator/accel_brake_map_calibrator/README.md
vehicle/accel_brake_map_calibrator/accel_brake_map_calibrator/config/accel_brake_map_calibrator.param.yaml
vehicle/accel_brake_map_calibrator/accel_brake_map_calibrator/include/accel_brake_map_calibrator/accel_brake_map_calibrator_node.hpp
vehicle/accel_brake_map_calibrator/accel_brake_map_calibrator/launch/accel_brake_map_calibrator.launch.xml
vehicle/accel_brake_map_calibrator/accel_brake_map_calibrator/src/accel_brake_map_calibrator_node.cpp

Add option to use actuation_cmd as the value of the accel/brake pedal for calibration.
This is an option for vehicles for which actuation_status is not available for some reason.
I confirmed that the calibration is performed both of when accel_brake_value_source is "status" and "command".
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-reques …

feat(accel_brake_map_calibrator): add option to use actuation_cmd

---

planning/obstacle_avoidance_planner/src/debug_marker.cpp

visualize road bounds considered in obstacle_avoidance_planner
The bounds in obstacle_avoidance_planner and behavior_path_planner may be a bit different due to some changes like https://github.com/autowarefoundation/autoware.universe/pull/3086

feat(obstacle_avoidance_planner): visualize bounds

---

planning/behavior_path_planner/CMakeLists.txt
planning/behavior_path_planner/include/behavior_path_planner/parameters.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/external_request_lane_change_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/lane_change_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/manager.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_visitor.hpp
planning/behavior_path_planner/include/behavior_path_planner/util/lane_change/lane_change_module_data.hpp
planning/behavior_path_planner/include/behavior_path_planner/util/lane_change/util.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/scene_module/lane_change/external_request_lane_change_module.cpp
planning/behavior_path_planner/src/scene_module/lane_change/lane_change_module.cpp
planning/behavior_path_planner/src/scene_module/lane_change/manager.cpp
planning/behavior_path_planner/src/util/lane_change/util.cpp
planning/route_handler/include/route_handler/route_handler.hpp
planning/route_handler/src/route_handler.cpp

Use lane change module to generate external lane change.
Also support lane change new framework.
⬇️ modified parameter to disable by default.
https://github.com/autowarefoundation/autoware.universe/pull/3068
Please set following flag to `FALSE`, and confirm to pass all build.
https://github.com/autowarefoundation/autoware.universe/blob/ad5595389a629346476ee06391260ffea53159ef/planning/behavior_path_planner/CMakeLists.txt#L10
At the moment, external lane change still couldn't be executed simultaneously. …

feat(lane change): support new framework external request

---

evaluator/diagnostic_converter/src/converter_node.cpp

Removed the unit and the blank if they exist in the value of diagnostics.
I confirmed that diagnostics with the unit works well with the scenario simulator v2 via diagnostic_converter.

feat(diagnostic_converter): remove unit and blank in the value

---

launch/tier4_control_launch/launch/control.launch.py

add check_external_emergency_heartbeat option to designate it at runtime.

feat(tier4_control_launch): add check_external_emergency_heartbeat option

---

planning/behavior_velocity_planner/include/scene_module/intersection/scene_intersection.hpp
planning/behavior_velocity_planner/src/scene_module/intersection/debug.cpp
planning/behavior_velocity_planner/src/scene_module/intersection/scene_intersection.cpp

Fixed the problem that the intersection module displays a stop line at the origin when there is no need to stop. 

chore(intersection): display intersection marker only when stopped

---

planning/obstacle_avoidance_planner/config/obstacle_avoidance_planner.param.yaml
planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/mpt_optimizer.hpp
planning/obstacle_avoidance_planner/src/mpt_optimizer.cpp

When the behavior's path is outside the drivable area, sometimes the motion planner cannot fully make the trajectory inside the drivable area.
I fixed the issue by modifying the boundary's calculation in obstacle_avoidance_planner.
The following figures are NOT that different
before
after
The difference is here.
After one tends to be inside the drivable area because of the boundary's calculation algorithm. …

feat(obstacle_avoidance_planner): consider behavior's drivable area violation

---

launch/tier4_simulator_launch/launch/simulator.launch.xml

convert `/diagnostics_err` to UserDefinedValue so that scenario_simulator_v2 can watch it.
FYI, I chose `/diagnostics_err` instead of `/diagnostics` to suppress the number of topics.
We can change to `/diagnostics` if the diagnostics we want to check are not contained in  `/diagnostics_err` (= system_error_monitor does not monitor them).
I confirmed that scenario simulation works well with this PR.
https://evaluation.tier4.jp/evaluation/reports/9eb5bb67-ce26-5665-8bef-8da802e9e384?project_id=prd_jt …

feat(tier4_simulator_launch): convert /diagnostics_err

---

control/mpc_lateral_controller/include/mpc_lateral_controller/mpc.hpp
control/mpc_lateral_controller/include/mpc_lateral_controller/mpc_utils.hpp
control/mpc_lateral_controller/package.xml
control/mpc_lateral_controller/src/mpc.cpp
control/mpc_lateral_controller/src/mpc_utils.cpp

remove old autoware_auto dependency

refactor(mpc): remove old library dependency

---

planning/behavior_path_planner/include/behavior_path_planner/data_manager.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/util/lane_change/util.hpp
planning/behavior_path_planner/src/planner_manager.cpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
planning/behavior_path_planner/src/scene_module/lane_change/lane_change_module.cpp
planning/behavior_path_planner/src/util/lane_change/util.cpp

In the new manager, multiple modules run simultaneously in series. (e.g. avoidance -> lane change) But, the drivable area which the previous module generated is always overwritten by next module. As a result, the output drivable area is inconsistent.
In the following scene, the avoidance module's drivable area is overwritten by lane change module at the moment of lane change execution.
In this PR, I fixed lane change drivable generation logic to use previous module's drivable lanes.
- https://user-images.githubusercontent.com/44889564/225811909-855f6556-df6a-4667-8882-dc766a8de68c.mp4
**NOTE: For now, I fixed only lane change and avoidance module because the other modules are not able to execute simlutaneouly now.**
Please set following flag to `FALSE`, and confirm to pass all build. …

fix(lane_change): use previous module drivable lanes in drivable are generation

---

launch/tier4_perception_launch/launch/object_recognition/detection/pointcloud_map_filter.launch.py
launch/tier4_sensing_launch/launch/sensing.launch.xml
perception/compare_map_segmentation/CMakeLists.txt
perception/compare_map_segmentation/README.md
perception/compare_map_segmentation/include/compare_map_segmentation/multi_voxel_grid_map_update.hpp
perception/compare_map_segmentation/include/compare_map_segmentation/voxel_based_compare_map_filter_nodelet.hpp
perception/compare_map_segmentation/include/compare_map_segmentation/voxel_grid_map_loader.hpp
perception/compare_map_segmentation/launch/voxel_based_compare_map_filter.launch.xml
perception/compare_map_segmentation/package.xml
perception/compare_map_segmentation/src/multi_voxel_grid_map_update.cpp
perception/compare_map_segmentation/src/voxel_based_compare_map_filter_nodelet.cpp
perception/compare_map_segmentation/src/voxel_grid_map_loader.cpp

This PR to solve this issue [3085](https://github.com/autowarefoundation/autoware.universe/issues/3085)  for voxel_based_compare_map_filter nodelete.
The PR utilize the dynamic map loading interface to update current utilize pointcloud map cells. 
[TIERIV COMPANY INTERNAL LINK](https://tier4.atlassian.net/browse/T4PB-26400)
https://github.com/autowarefoundation/autoware_launch/pull/257
I tested on sample rosbag from Autoware tutorial using split map here: [sample-map-rosbag_split.zip](https://github.com/autowarefoundation/autoware.universe/files/10349104/sample-map-rosbag_split.zip)
- I have comfirmed that the performance is the same as current Autoware when `use_dynamic_map_loading` is set as `false`
- I have confirmed that when `use_dynamic_map_loading` is set as `true`: the performance …

feat(compare_map_segmentation): add dynamic map loading for voxel_based_compare_map_filter

---

planning/behavior_velocity_planner/include/scene_module/intersection/scene_intersection.hpp
planning/behavior_velocity_planner/src/scene_module/intersection/debug.cpp
planning/behavior_velocity_planner/src/scene_module/intersection/scene_intersection.cpp

Due to recent changes when intersection is interrupted by RTC and set to STOP, the virtual wall does not appear and `distance` was not properly set.

fix(behavior_velocity_planner::intersection): show virtual wall when interrupted by RTC

---

control/autonomous_emergency_braking/src/node.cpp

fix(autonomous_emergency_braking): fix typo

---

planning/behavior_velocity_planner/src/scene_module/intersection/scene_intersection.cpp

Without this PR, the behavior_velocity_planner dies due to invalid access in the intersection module.

fix(behavior_velocity_planner): fix invalid access

---

map/map_loader/test/test_pointcloud_map_loader_module.cpp

Some people got the following error. Although not everyone encounters this error, I would like to address this by small modification.
```
/home/.../pilot-auto/src/autoware/universe/map/map_loader/test/test_pointcloud_map_loader_module.cpp:84:81:   required from here
/opt/ros/humble/include/rclcpp/rclcpp/any_subscription_callback.hpp:391:21: error: 'void rclcpp::AnySubscriptionCallback<MessageT, AllocatorT>::set_deprecated(std::function<void(std::shared_ptr<_Yp>)>) [with SetT = sensor_msgs::msg::PointCloud2_<std::allocator<void> >; MessageT = sensor_msgs::msg::PointCloud2_<std::allocator<void> >; AllocatorT = std::allocator<void>]' is deprecated: use 'void(std::shared_ptr<const MessageT>)' instead [-Werror=deprecated-declarations]
391 |       set_deprecated(static_cast<typename …
```

fix(map_loader): address deprecated warning for some environment

---

planning/behavior_path_planner/src/utilities.cpp

Resampled path_with_lane_id is supposed to be used, but actually not used.

fix(behavior_path_planner): resample path in the route

---

evaluator/planning_evaluator/src/planning_evaluator_node.cpp

Only save output data when the output path is defined, in order to prevent memory leaks.
(default outpuf path defined config file is empty)

feat(planning_evaluator): push back metric only when output_file_str is defined

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

Fix bug in searching nearest target object that satisfies following two conditions:
1. should be avoid (otherwise, vehicle will collide with it.)
2. is avoidable (there is enough space to avoid.)
Before this PR, the `stop_target_object` is overwitten unintentionally by bihind object since the loop never breaks.
```c++
for (const auto & o : data.target_objects) {
if (o.avoid_required && o.is_avoidable) {
data.avoid_required = true;
data.stop_target_object = o;
break; // ADD THIS LINE
}
}
```
NOTE: `target_objects` is sorted by `object.longitudinal`, so `target_objects.front()` is the nearest object in `target_objects`.
Before this PR.
Since only one object is detected, the stop point is inserted in front of the object.
At the moment of detection behind object, the stop point moves to in …

fix(avoidance): get nearest target object

---

planning/behavior_path_planner/include/behavior_path_planner/util/avoidance/avoidance_module_data.hpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

After the trimSharpReturn process, sometimes there are shift lines that all have similar gradient. It maybe cause jerk value to be calculated larger than expected.
$$
Jerk \propto \frac{length}{longidudinal^3}
$$
https://github.com/autowarefoundation/autoware.universe/blob/319577a9caeac1ca899dbf3ec15490e97910f6a9/planning/behavior_path_planner/src/util/path_shifter/path_shifter.cpp#L514-L522
In this PR, I add `trimSimilarGradShiftLine` filter at the end of trimShiftLine.
```c++
// - Combine avoid points that have almost same gradient (again)
{
const auto CHANGE_SHIFT_THRESHOLD = 0.2;
trimSimilarGradShiftLine(sl_array_trimmed, CHANGE_SHIFT_THRESHOLD);
debug.trim_similar_grad_shift_third = sl_array_trimmed;
printShiftLines(sl_array_trimmed, "after trim_similar_grad_shift_second");
}
```
The …

feat(avoidance): add another same grad filter

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

The avoidance module check adjacent lane to find target object that should be avoid. On the other hand, the ego often don't have to shift even if the target object is not empty because there is enough lateral margin between the ego and that object.
In this PR, I added a new condition to `isExecutionRequested()`, and prevent module execution in scenario where the ego don't have to shift anymore.
NOTE: This modification only works on the new manager for now. …

fix(avoidance): not run avoidance module when the shift line is empty

---

launch/tier4_perception_launch/launch/object_recognition/detection/pointcloud_map_filter.launch.py

Fix pointcloud_map_filter.launch.py.
(Currently, pointcloud_map_filter does not launch when use_down_sample_filter is true. )
https://github.com/autowarefoundation/autoware.universe/pull/3087
I comfirmed that the VoxelBasedCompareMapFilterComponent did not cause error when use_down_sample_filter is true.  …

fix(tier4_perception_launch): add required parameter for voxel based compare map filter

---

planning/behavior_path_planner/include/behavior_path_planner/util/lane_change/util.hpp
planning/behavior_path_planner/src/util/lane_change/util.cpp

Currently, lane change distance check calculation is incorrect, and I fixed the problem in this PR.
In order to safely navigate the ego vehicle while doing lane change, it has to cancel the lane change if it satisfies the following condition
```
prepare_distance + lane_changing_distance > dist_to_end_of_current_lane
```
This equation suggests that the entire lane change length will exceed the length to the end of the current lane.
Scenario Test Result
[Internal Link](https://evaluation.tier4.jp/evaluation/reports/6433a3aa-df91-5820-9e29-f1117a1f7d5a?project_id=prd_jt) 
1194/1199
After …

fix(behavior_path_planner): fix lane change distance check

---

common/motion_utils/src/resample/resample.cpp

Fixed lane_ids resampling method so that the joint of different lane_ids (= the point which has multiple lane_ids) does not change.

fix(motion_utils): change lane_id resampling method

---

planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/path_utilities.cpp
planning/behavior_path_planner/src/scene_module/lane_following/lane_following_module.cpp

use motion_utils::cropPoints instead of clipPathLength.
motion_utils::cropPoints considers the argument's position precisely for cropping.
See this. https://github.com/autowarefoundation/autoware.universe/pull/3176

fix(behavior_path_planner): use cropPoints

---

planning/behavior_path_planner/include/behavior_path_planner/util/lane_change/util.hpp
planning/behavior_path_planner/src/util/lane_change/util.cpp

Change some variable names in the lane change module to improve the readability.

refactor(behavior_path_planner): change variable names

---

control/trajectory_follower_node/src/controller_node.cpp
control/trajectory_follower_node/src/simple_trajectory_follower.cpp

[trajectory_follower_node_delete_param.webm](https://user-images.githubusercontent.com/100691117/225812672-b6a31751-1a32-4c6d-a8dc-0f03a7b117be.webm)

refactor(trajectory_follower_node): delete default values

---

perception/traffic_light_map_based_detector/config/traffic_light_map_based_detector.param.yaml

Improve the accuracy of yellow signal recognition in AWSIM.
- [TIER IV INTERNAL TICKET](https://tier4.atlassian.net/browse/AJD-594)
- https://github.com/tier4/AWSIM/pull/60
- https://github.com/tier4/AWSIM/issues/10
With this PR, the AWSIM ego vehicle is more likely to stop yellow light. 
[Tested video](https://user-images.githubusercontent.com/42209144/228204472-127b49b1-f4ab-4311-9da5-59731aff7278.webm)
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributin …

feat(traffic_light_map_based_detector): change the vibration parameter of the Traffic Light Detector

---

planning/rtc_auto_mode_manager/src/node.cpp

[rtc_auto_mode_manager_delete_param.webm](https://user-images.githubusercontent.com/100691117/226099750-d44ae6ff-97c3-47c0-9a55-f31a61436efb.webm)

refactor(rtc_auto_mode_manager): delete default values

---

planning/planning_debug_tools/src/trajectory_analyzer.cpp

[planning_debug_tools_delete_param.webm](https://user-images.githubusercontent.com/100691117/226542260-a74e1c08-15f2-4540-9822-02ff9c5c46b4.webm)

refactor(planning_debug_tools): delete default values

---

planning/freespace_planner/src/freespace_planner/freespace_planner_node.cpp

[freespace_planner_delete_param.webm](https://user-images.githubusercontent.com/100691117/226558540-313929a8-3c76-43f7-ae6a-305defb638ee.webm)

refactor(freespace_planner): delete default values

---

launch/tier4_map_launch/launch/map.launch.py
map/map_loader/CMakeLists.txt
map/map_loader/README.md
map/map_loader/launch/pointcloud_map_loader.launch.xml
map/map_loader/package.xml
map/map_loader/src/pointcloud_map_loader/differential_map_loader_module.cpp
map/map_loader/src/pointcloud_map_loader/partial_map_loader_module.cpp
map/map_loader/src/pointcloud_map_loader/pointcloud_map_loader_node.cpp
map/map_loader/src/pointcloud_map_loader/pointcloud_map_loader_node.hpp
map/map_loader/src/pointcloud_map_loader/utils.cpp
map/map_loader/src/pointcloud_map_loader/utils.hpp
map/map_loader/test/test_load_pcd_metadata.cpp
map/map_loader/test/test_pointcloud_map_loader_module.cpp
map/map_loader/test/test_replace_with_absolute_path.cpp

Please see https://github.com/orgs/autowarefoundation/discussions/3328 for the detail
You can use https://github.com/MapIV/pointcloud_divider for dividing pointcloud map into grids
Please find a how-to in [updated readme](https://github.com/kminoda/autoware.universe/tree/feat/add_grid_coordinates_in_map_msg/map/map_loader)
Should be merged after:
- https://github.com/autowarefoundation/autoware_msgs/pull/52
- Generate a divided pointcloud map with a given tool
- Load the pointcloud map and its metadata with logging_simulator …

feat(map_loader): add grid coordinates for partial/differential map load

---

common/motion_utils/src/distance/distance.cpp

remove noisy error message of `validCheckDecelPlan`

chore(motion_utils): remove validCheckDecelPlan error message

---

launch/tier4_control_launch/launch/control.launch.py
planning/behavior_path_planner/src/util/lane_change/util.cpp

Since the current code does not consider the maximum acceleration values correctly, I recalculated the maximum deceleration values using the minimum lane changing speed and current speed. Moreover, I fixed the prepared distance by adding the minimum velocity of the lane changing speed.
Scenario Test 1198/1199
[Tier4 Internal Link](https://evaluation.tier4.jp/evaluation/reports/73b5d228-56ec-505d-ae31-682bfee9a812?project_id=prd_jt) …

feat(behavior_path_planner): fix minimum prepare speed

---

sensing/pointcloud_preprocessor/src/crop_box_filter/crop_box_filter_nodelet.cpp

`bool negative` parameter was incorrectly converted from `bool` to `float`, then implicitly to `bool` again.

fix(crop_box_filter): invalid bool -> float -> bool conversion

---

launch/tier4_perception_launch/launch/object_recognition/detection/pointcloud_map_filter.launch.py

Fix pointcloud_map_filter.launch.py.
(Currently, pointcloud_map_filter does not launch when use_down_sample_filter is true. )
https://github.com/autowarefoundation/autoware.universe/pull/3087
I comfirmed that the VoxelBasedCompareMapFilterComponent did not cause error when use_down_sample_filter is true.  …

fix(tier4_perception_launch): add missing parameter for voxel based compare map filter

---

control/autonomous_emergency_braking/src/node.cpp

publish debug marker on base_link frame to avoid when transform map to base_link is failed
I confirmed the marker visualizes on base_link frame

fix(autonomous_emergency_braking): publish debug marker on base_link frame

---

planning/behavior_path_planner/src/planner_manager.cpp
planning/behavior_path_planner/src/scene_module/lane_change/lane_change_module.cpp

Fix bug in planner manager.
The new manager updates current lanelet info and uses it as next module's input even when the lane change module exit with `ModuleStatus::FAILURE`, but I suppose that it should do that process only when the lane change module exit with `ModuleStatus::SUCCESS`.
WIP (running evaluator now...) …

fix(planner_manager): don't use failure module output

---

planning/behavior_path_planner/src/util/lane_change/util.cpp

The lane change start pose must **NOT** be in front of the `target_lanelets.front()`, and this is check in here.
https://github.com/autowarefoundation/autoware.universe/blob/90ed30d63748fbef9a42c264c83ed7f084701d4f/planning/behavior_path_planner/src/util/lane_change/util.cpp#L350-L352
On the other hand, this guard doesn't support new architecture that can run multiple modules simultaneously.
If the lane change module uses avoidance path as input path, the start pose is generated on that path. In this case, there is a possibility that the start pose is in front of the `target_lanelets.front()` even if the above condition is satisfied.
So, I added another condition so that distance (orange line) between lc start pose and target lane's front pose does not have a positive value.
The PR author …

fix(lane_change): guard invalid lc start point

---

planning/behavior_path_planner/src/util/lane_change/util.cpp
planning/behavior_path_planner/src/utilities.cpp

Use `toPolygon2d` function in the behavior path planner module

refactor(behavior_path_planner): use to polygon2d function

---

planning/behavior_path_planner/src/util/lane_change/util.cpp

clean the code of common drivable area generation

refactor(behavior_path_planner): clean the code of common drivable area generation

---

launch/tier4_control_launch/launch/control.launch.py
planning/behavior_path_planner/src/util/lane_change/util.cpp

Use actual acceleration values when computing prepare distance and safety check.
Internal Sceneario Test 1198/1199
[Link](https://evaluation.tier4.jp/evaluation/reports/ff75d86d-c8a2-5604-81e4-c53d0a0960bc?project_id=prd_jt)

fix(behavior_path_planner): use computed acceleration rather than sampled acceleration

---

planning/behavior_path_planner/src/util/geometric_parallel_parking/geometric_parallel_parking.cpp

Fix remover overlapping function usage in geometric parking

fix(behavior_path_planner): fix overlapping function usage in parking

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/manager.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/lane_change_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/manager.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_out/manager.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_out/pull_out_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/manager.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/pull_over_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_interface.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_manager_interface.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/side_shift/manager.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/side_shift/side_shift_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/utilities.hpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
planning/behavior_path_planner/src/scene_module/avoidance/manager.cpp
planning/behavior_path_planner/src/scene_module/lane_change/external_request_lane_change_module.cpp
planning/behavior_path_planner/src/scene_module/lane_change/lane_change_module.cpp
planning/behavior_path_planner/src/scene_module/lane_change/manager.cpp
planning/behavior_path_planner/src/scene_module/lane_following/lane_following_module.cpp
planning/behavior_path_planner/src/scene_module/pull_out/manager.cpp
planning/behavior_path_planner/src/scene_module/pull_out/pull_out_module.cpp
planning/behavior_path_planner/src/scene_module/pull_over/manager.cpp
planning/behavior_path_planner/src/scene_module/pull_over/pull_over_module.cpp
planning/behavior_path_planner/src/scene_module/side_shift/manager.cpp
planning/behavior_path_planner/src/scene_module/side_shift/side_shift_module.cpp
planning/behavior_path_planner/src/utilities.cpp

Currently, by default, SceneModuleInterface has `rtc_interface_ptr_` and its related functions such as lock/unlockRTCCommand.
However, some derived classes from SceneModuleInterface like avoidance have `rtc_interface_ptr_left/right_` though they still have `rtc_interface_ptr_`, which makes the developers confused.
In addition, lock/unlockRTCCommand functions have to be modified following an implicit rule depending on the types of `rtc_interface_ptr_` (e.g. only one rtc_interface_ptr, or left and right rtc_interface_ptrs)
To remove the implicit rule and redundant implementation for higher maintainability,
- I unified rtc_interface (and its uuid) as an unordered_map.
- I removed functions related to `rtc_interface_ptr_`  in detailed modules since they can be removed thanks to the above …

refactor(behavior_path_planner): unify rtc_interface_ptr in SceneModuleInterface

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/external_request_lane_change_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/lane_change_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_following/lane_following_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_out/pull_out_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/pull_over_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_interface.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/side_shift/side_shift_module.hpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
planning/behavior_path_planner/src/scene_module/lane_change/external_request_lane_change_module.cpp
planning/behavior_path_planner/src/scene_module/lane_change/lane_change_module.cpp
planning/behavior_path_planner/src/scene_module/lane_following/lane_following_module.cpp
planning/behavior_path_planner/src/scene_module/pull_out/pull_out_module.cpp
planning/behavior_path_planner/src/scene_module/pull_over/pull_over_module.cpp
planning/behavior_path_planner/src/scene_module/side_shift/side_shift_module.cpp

With the current implementation of SceneModuleInterface, we have to follow an implicit rule with redundant implementation when implementing `onEntry` and `onExit` in detailed modules
Also the most part of the implicit rule is common which calls
- clearWaitingApproval
- removeRTCStatus
- unlockNewModuleLaunch
- etc.
As a refactoring, I split `onEntry` into new `onEntry` and `processOnEntry` where new `onEntry` has the above rule's implementation so that in detailed modules we just implement extra process in `processOnEntry`.
The same change was done to `onExit`.
This refactoring helps developers with creating a new module in the behavior_path_planner by removing the implicit rule and redundant implementation.
- TODO
- baseline: 1198/1199
- baseline: 1187/1199 …

refactor(behavior_path_planner): unify onEntry/Exit function

---

planning/route_handler/src/route_handler.cpp

Add route loop check to `getLaneletSequenceAfter` and `getLaneletSequenceUpTo` for solving endless while loop when the route is a loop.
ex) 
if the route is following, `getLaneletSequence(current_lane)` can't end. 
```
[component_container_mt-27] current_lanelet: 174, next_lanelet: 190162
[component_container_mt-27] current_lanelet: 190162, next_lanelet: 143
[component_container_mt-27] current_lanelet: 143, next_lanelet: 146
[component_container_mt-27] current_lanelet: 146, next_lanelet: 1003
[component_container_mt-27] current_lanelet: 1003, next_lanelet: 1506
[component_container_mt-27] current_lanelet: 1506, next_lanelet: 176321
[component_container_mt-27] current_lanelet: 176321, next_lanelet: 1520
[component_container_mt-27] current_lanelet: 1520, next_lanelet: 1509 …
```

fix(mission_planner): add route loop check

---

planning/behavior_path_planner/src/util/pull_over/goal_searcher.cpp

Considering the curved lane, the pose moved laterally should have the same longitudinal distance as the original pose.
psim

fix(behavior_path_planner): fix distance from original goal of goal search

---

planning/behavior_path_planner/include/behavior_path_planner/utilities.hpp
planning/behavior_path_planner/src/util/geometric_parallel_parking/geometric_parallel_parking.cpp
planning/behavior_path_planner/src/utilities.cpp
planning/behavior_path_planner/test/test_utilities.cpp

Remove unnecessary functions from utilities file in the behavior path planner

refactor(behavior_path_planner): remove unnecessary functions

---

common/motion_utils/include/motion_utils/trajectory/trajectory.hpp
common/motion_utils/test/src/trajectory/test_trajectory.cpp

Add a new `insertStopPoint` function to the motion utils package. This new function takes a distance, which is from the front point of the path to the designated place, as one of its arguments.
Unit Tests

feat(motion_utils): add new insert stop point function

---

planning/behavior_path_planner/CMakeLists.txt
planning/behavior_path_planner/include/behavior_path_planner/util/lane_change/util.hpp
planning/behavior_path_planner/src/scene_module/lane_change/lane_change_module.cpp
planning/behavior_path_planner/src/util/lane_change/util.cpp

We have to combine drivable lanes from the multiple modules when the number of running modules is larger than 1.
I separated the implementation into generateDrivableLanes which depends on each module and combineDrivableLanes which can be used for any module.
In the near future, I will move combineDrivableLanes outside the module so that there will be no conflict of drivable area generation with any pairs of modules.
- TODO
with BT: https://evaluation.tier4.jp/evaluation/reports/fb9bd427-c48a-5203-92fa-7723d1ca0aa4?project_id=prd_jt
without BT: planning simulator works well with avoidance/lane change. …

feat(behavior_path_planner): change method to combine drivable lanes

---

planning/behavior_path_planner/include/behavior_path_planner/utilities.hpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
planning/behavior_path_planner/src/util/avoidance/util.cpp
planning/behavior_path_planner/src/utilities.cpp

Remove `toPolygon` functions from utils and avoidance module in the behavior path planner.

refactor(behavior_path_planner): remove toPolygon functions

---

common/tier4_autoware_utils/include/tier4_autoware_utils/geometry/boost_polygon_utils.hpp
common/tier4_autoware_utils/src/geometry/boost_polygon_utils.cpp
common/tier4_autoware_utils/test/src/geometry/test_boost_polygon_utils.cpp

Add a function that convert to bounding box (polygon2d) from base_link pose and some necessary informatino.
Unit Test

feat(tier4_autoware_utils): add toBoundingBox function

---

planning/obstacle_stop_planner/src/node.cpp

When the obstacle is `max_longitudinal_margin_behind_goal` behind the goal, `stop_point.index` becomes `output.size()` and this causes the following error.
`"Segment index is invalid."`  in 
https://github.com/autowarefoundation/autoware.universe/blob/main/common/motion_utils/include/motion_utils/trajectory/trajectory.hpp#L308-L315
psim …

fix(obstacle_stop_planner): obstacle after goal

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

The avoidance module remove conflict current shift line when new shift lines are added.
$$
INDEX_{start, new} <= INDEX_{start, current}
$$
https://github.com/autowarefoundation/autoware.universe/blob/d2a348bcc0af688d2e7ae8630f65dda63db3a18a/planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp#L3285-L3293
---
On the other hand, the any current shift line will **NOT** be removed in the following scene. And, the shift line behind the ego will be removed in order. Then, the **GREEN** shift line will be removed thirdly as a result and `base_offset_` will be updated. However the gap between **TRANSLUCENT ORANGE** shift length and **GREEN** shift is huge, so this causes significant aviodance path change.
https://github.com/autowarefoundation/autoware.universe/blob/d2a348 …

fix(avoidance): remove unnecessary shift line

---

launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.py
planning/behavior_path_planner/CMakeLists.txt
planning/behavior_path_planner/config/avoidance_by_lc/avoidance_by_lc.param.yaml
planning/behavior_path_planner/config/scene_module_manager.param.yaml
planning/behavior_path_planner/include/behavior_path_planner/behavior_path_planner_node.hpp
planning/behavior_path_planner/include/behavior_path_planner/parameters.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance_by_lc/manager.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance_by_lc/module.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_visitor.hpp
planning/behavior_path_planner/include/behavior_path_planner/util/avoidance_by_lc/module_data.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/scene_module/avoidance_by_lc/manager.cpp
planning/behavior_path_planner/src/scene_module/avoidance_by_lc/module.cpp
planning/rtc_interface/src/rtc_interface.cpp

:arrow_down: These PRs must be merged before this PR.
https://github.com/tier4/tier4_autoware_msgs/pull/71
https://github.com/autowarefoundation/autoware_launch/pull/261
Add new module `avoidance_by_lc`.
This module execute lane change maneuver when there are obstacles on ego's driving lane.
The obstacle filtering logic and path generation logic are almost the same to the `avoidance` and `lane_change` module. 
(TODO: remove duplicated functions.)
```yaml
/**:
avoidance_by_lane_change:
execute_object_num: 1               
execute_object_longitudinal_margin: 0.0
execute_only_when_lane_change_finish_before_object: true
```
- `execute_object_num`
This module execute lane change maneuver only when the target number is larger than `execute_object_num`. (If the condition is …

feat(avoidance_by_lc): add new module to avoid obstacle by lane change

---

planning/behavior_path_planner/src/behavior_path_planner_node.cpp

Also, some additional parameters are needed.
:arrow_down: This PR must be merged before this PR.
https://github.com/autowarefoundation/autoware_launch/pull/272

refactor(behavior_path_planner): delete default values

---

planning/behavior_velocity_planner/config/intersection.param.yaml
planning/behavior_velocity_planner/include/behavior_velocity_planner/planner_data.hpp
planning/behavior_velocity_planner/include/scene_module/scene_module_interface.hpp
planning/behavior_velocity_planner/src/node.cpp
planning/behavior_velocity_planner/src/scene_module/blind_spot/manager.cpp
planning/behavior_velocity_planner/src/scene_module/crosswalk/manager.cpp
planning/behavior_velocity_planner/src/scene_module/detection_area/manager.cpp
planning/behavior_velocity_planner/src/scene_module/intersection/manager.cpp
planning/behavior_velocity_planner/src/scene_module/no_stopping_area/manager.cpp
planning/behavior_velocity_planner/src/scene_module/occlusion_spot/manager.cpp
planning/behavior_velocity_planner/src/scene_module/run_out/manager.cpp
planning/behavior_velocity_planner/src/scene_module/speed_bump/manager.cpp
planning/behavior_velocity_planner/src/scene_module/stop_line/manager.cpp
planning/behavior_velocity_planner/src/scene_module/traffic_light/manager.cpp
planning/behavior_velocity_planner/src/scene_module/virtual_traffic_light/manager.cpp

The following parameters need to be added
stop_line_extend_length: 5.0
detection_area.hold_stop_margin_distance: 2.0
intersection.walkway.external_input_timeout: 1.0
intersection.merge_from_private.merge_from_private_area.stop_duration_sec: 1.0
stop_line.hold_stop_margin_distance: 2.0
stop_line.use_initialization_stop_line_state: false
stop_line.debug.show_stopline_collision_check: false
virtual_traffic_light.hold_stop_margin_distance: 0.0
[Behavior velocity planner delete param.webm](https://user-images.githubusercontent.com/100691117/228428215-b434ba12-89bf-464c-b4ce-27766487bd62.webm)
:arrow_down: This PR must be merged before this PR.
https://github.com/autowarefoundation/autoware_launch/pull/272 …

refactor(behavior_velocity_planner): delete default values

---

planning/behavior_path_planner/src/planner_manager.cpp

Before this PR, the manager registers the highest priority module as candidate moduls even if the module **FAILs** to generate path. This causes following un/register loop, and some chattering happen.
- run request module (fails to generate path)
- register the request module pointer to `candidate_module_opt_`
https://github.com/autowarefoundation/autoware.universe/blob/b78b17d6be85611e0686b1c319f3ae0ffe7bd890/planning/behavior_path_planner/src/planner_manager.cpp#L88
- request module return ModuleStatus::FAILURE in `getCandidateModule()`
- unregister the module
- return First cycle
https://github.com/autowarefoundation/autoware.universe/blob/b78b17d6be85611e0686b1c319f3ae0ffe7bd890/planning/behavior_path_planner/src/planner_manager.cpp#L186-L191
Then, I fixed it in order to break the …

fix(planner_manager): break while loop when the candidate module fails to generate valid path

---

localization/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp

An initial pose in `NDTScanMatcher::callback_initial_pose` is transformed to `map` frame with `tf2::doTransform` which uses the `transform` time stamp instead of the received message time stamp [LINK](https://github.com/ros2/geometry2/blob/d508d9c312e8cfa69e81bf5e53af38849f2bc870/tf2_geometry_msgs/include/tf2_geometry_msgs/tf2_geometry_msgs.hpp#L639).
I my scenario I am using `map->odom->base_link` structure. In my current implementation 'map->odom' is a static identity transform, hence time stamp for `TF_pose_to_map_ptr` is 0.
This problem is still valid in case of non-static `map->odom` tranform, but with different frequency than `odom->base_link`. For example `map->odom` publishes 1Hz, while `odom->base_link` publishes 30Hz, in such a case messaeges in `initial_pose_msg_ptr_array_` …

fix(ndt_scan_matcher): fix initial pose timestamp for NDT algorithm

---

perception/lidar_centerpoint/include/lidar_centerpoint/cuda_utils.hpp
perception/tensorrt_yolo/lib/include/cuda_utils.hpp

Fix the compile error `namespace cuda::std ...` for `.cu` files 
The source files can be still compiled using nvcc == 11.6 on my local machine too.

chore(perception): workaround for nvcc > 11.6

---

common/motion_utils/CMakeLists.txt
common/motion_utils/include/motion_utils/trajectory/path_with_lane_id.hpp
common/motion_utils/include/motion_utils/trajectory/trajectory.hpp
common/motion_utils/src/trajectory/path_with_lane_id.cpp
common/motion_utils/test/src/trajectory/test_path_with_lane_id.cpp
planning/behavior_path_planner/include/behavior_path_planner/parameters.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/utilities.cpp

No behavior change with default parameters
Added a option where the CoG instead of back wheel center will follow the centerline, which is false by default.
**Logic**
**Result**
before
after
Nothing due to no behavior change.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidel …

feat(behavior_path_planner): cog centered path shape planning

---

planning/behavior_path_planner/include/behavior_path_planner/behavior_path_planner_node.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp

use `tier4_autoware_utils::updateParam` instead of `update_param`
Planning module works well in Psim.

refactor(behavior_path_planner): use tier4_autoware_utils::updateParam

---

planning/behavior_path_planner/include/behavior_path_planner/util/avoidance/util.hpp
planning/behavior_path_planner/include/behavior_path_planner/utilities.hpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
planning/behavior_path_planner/src/scene_module/avoidance_by_lc/module.cpp
planning/behavior_path_planner/src/util/avoidance/util.cpp
planning/behavior_path_planner/src/util/lane_change/util.cpp
planning/behavior_path_planner/src/utilities.cpp

use `tier4_autoware_utils::toHexString` instead of `getUuidStr()`
I confirmed avoidance module works well in Psim.

refactor(behavior_path_planner): use tier4_autoware_utils::toHexString

---

planning/behavior_path_planner/include/behavior_path_planner/util/avoidance/util.hpp
planning/behavior_path_planner/include/behavior_path_planner/utilities.hpp
planning/behavior_path_planner/src/marker_util/avoidance/debug.cpp
planning/behavior_path_planner/src/marker_util/debug_utilities.cpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
planning/behavior_path_planner/src/scene_module/side_shift/side_shift_module.cpp
planning/behavior_path_planner/src/util/avoidance/util.cpp
planning/behavior_path_planner/src/utilities.cpp

- remove unused utils
- use `tier4_autoware_utils::calcOffsetPos`e instead of `shiftPose`

refactor(avoidance): remove unused utils

---

control/autonomous_emergency_braking/config/autonomous_emergency_braking.param.yaml
control/autonomous_emergency_braking/include/autonomous_emergency_braking/node.hpp
control/autonomous_emergency_braking/src/node.cpp

- Keep collision information for user specified seconds
- add class `CollisionDataKeeper` 
- add parameter `collision_keeping_sec`, default is 0.0
- add RSS and distance to objects to diag information
- publish marker for Collision decided Point
- rearrange codes
- publish marker for ObjectData
I confirmed it works in my environment.
green point: ObjectData
red point: Collision decided Point
https://user-images.githubusercontent.com/9547070/230254191-00cfe377-d48e-4aa3-bffe-19658f8d1d09.mp4
[contribution …

feat(autonomous_emergency_braking): keep collision information for user specified seconds

---

planning/mission_planner/README.md
planning/mission_planner/include/mission_planner/mission_planner_interface.hpp
planning/mission_planner/src/mission_planner/arrival_checker.cpp
planning/mission_planner/src/mission_planner/arrival_checker.hpp
planning/mission_planner/src/mission_planner/mission_planner.cpp
planning/mission_planner/src/mission_planner/mission_planner.hpp

Move callback to allow reroute when modified_route is received.
https://github.com/autowarefoundation/autoware/issues/3406
Check `/api/routing/state` will be ARRIVED when the goal is changed by pull over.

feat(mission_planner): move modified goal callback for reroute

---

planning/behavior_velocity_planner/src/scene_module/run_out/manager.cpp

The `run_out` module in the `behavior_velocity_planner` node is currently broken and crashes if turned on.
The issue comes from the declaration of some parameters that are (i) incorrectly named (leading dot `.`) and (ii) already declared (for `normal.min_jerk` and `normal.min_acc`).
This issue was previously hidden by default parameters which were recently removed (https://github.com/autowarefoundation/autoware.universe/pull/3201).
Start the `simple_planning_simulator` after setting `launch_run_out: true` (https://github.com/autowarefoundation/autoware_launch/blob/main/autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/behavior_velocity_planner.param.yaml#L12).
- Without this PR: crash.
- With this PR: no crash.
The …

fix(behavior_velocity_planner): properly get common params in 'run_out'

---

planning/behavior_velocity_planner/src/scene_module/intersection/util.cpp

In tier4's autoware.universe of version v0.6.0, stop line module did not work well due to the intersection modules' improper point insertion.
- before this PR, point insertion was using not only the velocity from prior point (zero order hold), but also the lane ids
- after this PR, only velocity is zero order holded.
See test result
Internal JIRA link: https://tier4.atlassian.net/browse/RT1-480
Before this PR (left), the point added by the intersection module is copying the lane ids from prior point. After this PR, the lane ids is that of the nearest point.
the vehicle does not completely stop at the stop line.
https://user-images.githubusercontent.com/28677420/230830038-0549a0d2-bed3-4f09-b5c6-0b0b5d712a51.mp4
it completely stops and the stop line does not chatter. …

fix(behavior_velocity_planner::intersection): only zero hold velocity

---

planning/mission_planner/src/lanelet2_plugins/default_planner.cpp
planning/static_centerline_optimizer/test/test_static_centerline_optimizer.test.py

[mission_planner_delete_param.webm](https://user-images.githubusercontent.com/100691117/226554272-90b2e7d7-88c7-4d98-80b3-31e1a2183107.webm)

refactor(mission_planner): delete default values

---

launch/tier4_simulator_launch/launch/simulator.launch.xml

It has to update `tier4_simulator_launch` for this PR https://github.com/autowarefoundation/autoware.universe/pull/3058.
I confirmed simualtor works well in my local env.

fix(tier4_simulator_launch): fix launch package name

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_interface.hpp

Related PR: https://github.com/autowarefoundation/autoware_launch/pull/289
Fix debug topic name and use `snake_case`. (e.g. `~/debug/pullover` -> `~/debug/pull_over`)

fix(behavior_path_planner): use snake case for debug marker

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

avoidance path already be sampled here.
https://github.com/autowarefoundation/autoware.universe/blob/6e3dbacad5ae6fc6343eb01c0d9a0757603e47ab/planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp#L214-L215
output reference path from avoidance module.
Translucent violet path shows the reference path of avidance module. …

perf(avoidance): remove unnecessary sampling

---

planning/behavior_path_planner/src/planner_manager.cpp

There are some modules that return `ModuleStatus::SUCCESS` before approval (e.g. pull over, avoidance), but `planner_manager` doesn't remove such a expired candidate module for now. Thus, these modules are never removed and next new module can't be launch depending on `max_module_size` value (all module set this param to 1 by default). As a result , an unexpected bahevior happend like this :arrow_down: 
In this PR, the planner_manager removes not only `ModuleStatus::FAILURE` modules but also `ModuleStatus::SUCCESS` candidate modules.
https://user-images.githubusercontent.com/44889564/231032552-9703cc1d-75c5-47b9-937b-c09c5f4a30fa.mp4
```
webauto ci scenario run --project-id prd_jt --scenario-id f112364c-1b55-4c48-bebd-8a68b0e52122 --runtime-path /$HOME/pilot-auto --scenario-parameters …
```

fix(planner_manager): remove succeeded candidate module

---

planning/behavior_path_planner/src/scene_module/lane_change/lane_change_module.cpp

Since the current lane change turn signal decider does not provide desired start point properly, I fixed the problem with this PR.
The problem is that it does not compute the necessary length correctly, and gives time instead of length to the function.
Scenario Test 1197/1200
[Tier4 Internal Link](https://evaluation.tier4.jp/evaluation/reports/86350e07-f09f-5ca7-9297-956435949cdd?project_id=prd_jt)
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/co …

fix(behavior_path_planner): fix lane change turn signal

---

planning/behavior_path_planner/config/lane_following/lane_following.param.yaml
planning/behavior_path_planner/include/behavior_path_planner/util/lane_following/module_data.hpp
planning/behavior_path_planner/include/behavior_path_planner/util/utils.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/scene_module/lane_following/lane_following_module.cpp
planning/behavior_path_planner/src/util/utils.cpp
planning/route_handler/include/route_handler/route_handler.hpp
planning/route_handler/src/route_handler.cpp

Signed-off-by: Mehmet Dogru <42mehmetdogru42@gmail.com>
closes #2125 
- ~~Please check out also:~~
- ~~https://github.com/autowarefoundation/autoware_common/pull/148~~ 
- ~~https://github.com/autowarefoundation/autoware_launch/pull/250~~
- Make sure you use a large vehicle like isuzu bus
- Any map with narrow turns for a bus is testable
- Make sure you expand the drivable area:
```xml
dynamic_expansion:
enabled: true
.
.
.
expansion:
method: lanelet # method used to expand the drivable area. Either 'lanelet' or 'polygon'.
```
https://user-images.githubusercontent.com/48479081/224922073-39c61828-bc56-43eb-a316-716376280d13.mp4
https://user-images.githubusercontent.com/48479081/224922227-50333421-63e4-4152-b9ea-3d5d7a9f1b5f.mp4 …

feat(route_handler-bpp): consider lane-ego angle diff in lane following module

---

planning/static_centerline_optimizer/launch/static_centerline_optimizer.launch.xml

static_centerline_optimizer cannot be launched from autoware_launch due to the following change.
https://github.com/autowarefoundation/autoware.universe/pull/3127
I added mission_planner's param when launching static_centerline_optimizer from launch.
FYI: The test to launch static_centerline_optimizer (not from autoware_launch) passed since mission_planner's parameter is given in this case.
https://github.com/autowarefoundation/autoware.universe/blob/59650ed5e5dbe40357aa2f883776d4c48f50fa89/planning/static_centerline_optimizer/test/test_static_centerline_optimizer.test.py#L46-L50
launch test passed. …

fix(static_centerline_optimizer): add mission_planner's param for launch

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance_by_lc/module.hpp
planning/behavior_path_planner/include/behavior_path_planner/util/avoidance/avoidance_module_data.hpp
planning/behavior_path_planner/include/behavior_path_planner/util/avoidance/util.hpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
planning/behavior_path_planner/src/scene_module/avoidance_by_lc/module.cpp
planning/behavior_path_planner/src/util/avoidance/util.cpp

`avoidance` and `avoidance_by_lc` module have several same functions.
https://github.com/autowarefoundation/autoware.universe/blob/5b6b5ad27fd8318f8a726f7ac05324472be62945/planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module.hpp#L180-L185
https://github.com/autowarefoundation/autoware.universe/blob/5b6b5ad27fd8318f8a726f7ac05324472be62945/planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance_by_lc/module.hpp#L173-L179 …

refactor(avoidance): remove duplicated utils function

---

launch/tier4_perception_launch/launch/obstacle_segmentation/ground_segmentation/ground_segmentation.launch.py
perception/elevation_map_loader/README.md
perception/elevation_map_loader/include/elevation_map_loader/elevation_map_loader_node.hpp
perception/elevation_map_loader/launch/elevation_map_loader.launch.xml
perception/elevation_map_loader/package.xml
perception/elevation_map_loader/src/elevation_map_loader_node.cpp

Signed-off-by: Shin-kyoto <58775300+Shin-kyoto@users.noreply.github.com>
These PRs must be merged before this PR.
- https://github.com/autowarefoundation/autoware.universe/pull/3286
- https://github.com/autowarefoundation/autoware_launch/pull/285
- https://github.com/autowarefoundation/autoware_msgs/pull/57
- add new service and msg
- When you use large pointcloud map, map_loader cannot publish large map as one topic because of the limit size determined by [the default value in cyclonedds](https://github.com/eclipse-cyclonedds/cyclonedds/blob/09a02f5b2b9ba856d7d4c616510252cf9e508ec2/docs/manual/config/config_file_reference.rst#cycloneddsdomaininternalmaxsamplesize).
- So I want to add sequential map loading mode to `elevation_map_loader`. It is helpful to avoid exeeding the limit by using …

feat(elevation_map_loader): add support for seleceted_map_loader

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

I used util::clipPathLength in avoidance module, and `forward` and `backward` are revered by mistake. As a result, the avoidance candidate path is not shown correctly.
https://github.com/autowarefoundation/autoware.universe/blob/334e0663622cfeb04d3e3eda763762049fb59848/planning/behavior_path_planner/src/util/path_utils.cpp#L174-L188 …

fix(avoidance): fix clip forward length and backward length

---

planning/route_handler/include/route_handler/route_handler.hpp
planning/route_handler/src/route_handler.cpp

Add an interval calculation function to the route handler. In this function, it computes each lateral interval to the preferred lane from the given lane.

feat(route_handler): add lateral intervals calculator

---

perception/lidar_apollo_instance_segmentation/.gitignore

```
Untracked files:                                                                                                                                                                                                                                                                                                                                                                                                                
(use "git add <file>..." to include in what will be committed) …
```

chore(lidar_apollo_instance_segmentation): add ignore directory

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

Fix two bugs in yield judgement logic.
The avoidance module executes yield (and stop) maneuver only when there is enough space to avoid. 
Now, there are several factor thats make avoidance impossible, and even when the one of the following factor is satisfied, the ego don't yield for target object.
- `INSUFFICIENT_LATERAL_MARGIN`
- `SAME_DIRECTION_SHIFT`
- `REMAINING_DISTANCE_LESS_THAN_ZERO`
- `TOO_LARGE_JERK`
But, in `TOO_LARGE_JERK`, the module also should embed stop point so that ego avoid the object. For now, the ego doesn't stop at avoidable position and close to obstacle stop position. This is an unexpected behavior.
- https://user-images.githubusercontent.com/44889564/230867633-711311c7-ea2c-4c0d-998d-836799d52dc2.mp4
---
The avoidance module generate shift line for all avoidable …

fix(avoidance): fix bug in yield judge logic

---

control/pure_pursuit/src/pure_pursuit/pure_pursuit_lateral_controller.cpp
control/pure_pursuit/src/pure_pursuit/pure_pursuit_node.cpp

[pure_pursuit_delete_param.webm](https://user-images.githubusercontent.com/100691117/221121979-38205d20-efd1-423e-99cb-a30edee56465.webm)

refactor(pure_pursuit): delete default values

---

planning/behavior_path_planner/src/behavior_path_planner_node.cpp

Refactor code in `behavior_path_planner_node.cpp` to use a lambda function for scene module manager parameters. This simplifies the code, avoids repetition, and makes it easier to add new modules.

refactor(behavior_path_planner): unify module manager param getter

---

system/default_ad_api_helpers/ad_api_adaptors/README.md
system/default_ad_api_helpers/ad_api_adaptors/launch/rviz_adaptors.launch.xml
system/default_ad_api_helpers/ad_api_adaptors/src/routing_adaptor.cpp
system/default_ad_api_helpers/ad_api_adaptors/src/routing_adaptor.hpp

Add new goal pose topic with goal modification for rviz.
https://github.com/autowarefoundation/autoware/issues/3406
Check allow_goal_modification value using `/service_log` topic.
- False by default
- True if change the rviz goal topic to `/rviz/routing/rough_goal`
None

feat(default_ad_api_helpers): support goal modification for rviz

---

common/component_interface_specs/include/component_interface_specs/planning.hpp
planning/mission_planner/README.md
planning/mission_planner/src/mission_planner/mission_planner.cpp
planning/mission_planner/src/mission_planner/mission_planner.hpp

Add reroute interface for api.
https://github.com/autowarefoundation/autoware/issues/3406

feat(mission_planner): add reroute interface for api

---

launch/tier4_planning_launch/package.xml

Add ```exec_depend``` of tier4_planning_launch to planning_evaluator.
The planning evaluator is called [here](https://github.com/autowarefoundation/autoware.universe/blob/main/launch/tier4_planning_launch/launch/planning.launch.xml#L92)

chore(planning_evaluator): add dependency

---

planning/behavior_velocity_planner/CMakeLists.txt

PR #2775 causes runtime error in latest environment so should be reverted ASAP.
Psim launches and runs properly.
None
None

fix(behavior_velocity_planner): revert pr #2775

---

planning/behavior_velocity_planner/config/crosswalk.param.yaml
planning/behavior_velocity_planner/config/intersection.param.yaml
planning/behavior_velocity_planner/config/traffic_light.param.yaml
planning/behavior_velocity_planner/include/behavior_velocity_planner/node.hpp
planning/behavior_velocity_planner/include/behavior_velocity_planner/planner_data.hpp
planning/behavior_velocity_planner/include/scene_module/crosswalk/scene_crosswalk.hpp
planning/behavior_velocity_planner/include/scene_module/crosswalk/scene_walkway.hpp
planning/behavior_velocity_planner/include/scene_module/intersection/scene_intersection.hpp
planning/behavior_velocity_planner/include/scene_module/traffic_light/scene.hpp
planning/behavior_velocity_planner/launch/behavior_velocity_planner.launch.xml
planning/behavior_velocity_planner/src/node.cpp
planning/behavior_velocity_planner/src/scene_module/crosswalk/manager.cpp
planning/behavior_velocity_planner/src/scene_module/crosswalk/scene_crosswalk.cpp
planning/behavior_velocity_planner/src/scene_module/intersection/manager.cpp
planning/behavior_velocity_planner/src/scene_module/intersection/scene_intersection.cpp
planning/behavior_velocity_planner/src/scene_module/traffic_light/manager.cpp
planning/behavior_velocity_planner/src/scene_module/traffic_light/scene.cpp
planning/behavior_velocity_planner/traffic-light-design.md

launcher PR: https://github.com/autowarefoundation/autoware_launch/pull/296
In Psim
Removed deprecated topic `~/input/external_{intersection, crosswalk, traffic_light}_status`.
No influence on current system configuration

refactor(behavior_velocity_planner): removed external input from behavior_velocity

---

planning/planning_test_utils/include/planning_interface_test_manager/planning_interface_test_manager_utils.hpp

fix build error
```
/home/satoshi/pilot-auto/src/autoware/universe/planning/planning_test_utils/src/planning_interface_test_manager.cpp:317:28:   required from here
/opt/ros/humble/include/rclcpp/rclcpp/any_subscription_callback.hpp:391:21: error: 'void rclcpp::AnySubscriptionCallback<MessageT, AllocatorT>::set_deprecated(std::function<void(std::shared_ptr<_Yp>)>) [with SetT = autoware_auto_planning_msgs::msg::Path_<std::allocator<void> >; MessageT = autoware_auto_planning_msgs::msg::Path_<std::allocator<void> >; AllocatorT = std::allocator<void>]' is deprecated: use 'void(std::shared_ptr<const MessageT>)' instead [-Werror=deprecated-declarations]
391 |       set_deprecated(static_cast<typename scbth::callback_type>(callback));
| …
```

fix(planning_test_utils): fix build error

---

sensing/pointcloud_preprocessor/src/crop_box_filter/crop_box_filter_nodelet.cpp

`if (a && b, c)` is the same as `if (c)` not `if (a && b && c)` !!
Comma `,` inside if is meant to assign values, not to evaluate condition. For example:
```
if (y=f(x), y*y > 0) {
// ...
}
// is same as
{
auto y = f(x)
if (y*y > 0) {
// ...
}
}
```
See:
https://stackoverflow.com/questions/16475032/comma-operator-in-if-condition …

fix(pointcloud_preprocessor): fix broken logic

---

sensing/pointcloud_preprocessor/src/crop_box_filter/crop_box_filter_nodelet.cpp

tf_input_frame_ can't be empty in crop box filter.

refactor(crop_box_filter): remove always true condition

---

planning/behavior_path_planner/src/behavior_path_planner_node.cpp

When the ego-position is located far from the target trajectory, behavior_path_planner dies.
This PR adds a guard for an empty path. 
tested on Psim and confirmed the node does not die.

fix(behavior_path_planner): process died for empty path

---

planning/obstacle_cruise_planner/config/obstacle_cruise_planner.param.yaml
planning/obstacle_cruise_planner/include/obstacle_cruise_planner/common_structs.hpp
planning/obstacle_cruise_planner/include/obstacle_cruise_planner/node.hpp
planning/obstacle_cruise_planner/include/obstacle_cruise_planner/pid_based_planner/pid_based_planner.hpp
planning/obstacle_cruise_planner/include/obstacle_cruise_planner/planner_interface.hpp
planning/obstacle_cruise_planner/src/node.cpp
planning/obstacle_cruise_planner/src/pid_based_planner/pid_based_planner.cpp
planning/obstacle_cruise_planner/src/planner_interface.cpp

Implemented slow down planner, inserting slow down point in the trajectory where the point is close to the dynamic/static obstacles.
launcher PR: https://github.com/autowarefoundation/autoware_launch/pull/288
Planning simulator works well.
- TODO

feat(obstacle_cruise_planner): implement slow down planner

---

planning/obstacle_cruise_planner/docs/debug.md

- In pre-commit optional, wrong paths occur error below. So I fixed wrong path.
```
FILE: planning/obstacle_cruise_planner/docs/debug.md
[✖] ./image/detection_area.png
[✖] ./image/collision_point.png
[✖] ./image/obstacle_to_cruise.png
[✖] ./image/obstacle_to_stop.png
4 links checked.
ERROR: 4 dead links found!
[✖] ./image/detection_area.png → Status: 400
[✖] ./image/collision_point.png → Status: 400
[✖] ./image/obstacle_to_cruise.png → Status: 400
[✖] ./image/obstacle_to_stop.png → Status: 400
``` …

docs(obstacle_cruise_planner): fix wrong path

---

planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/test/test_behavior_path_planner_node_interface.cpp

Two updates in this PR
- add a guard for the empty route
- enable test for the empty route
- pass a unit test
- run psim successfully

feat(behavior_path_planner): add guard for empty route and enable test

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_interface.hpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
planning/behavior_path_planner/src/scene_module/avoidance_by_lc/module.cpp
planning/behavior_path_planner/src/scene_module/lane_change/external_request_lane_change_module.cpp
planning/behavior_path_planner/src/scene_module/lane_change/lane_change_module.cpp
planning/behavior_path_planner/src/scene_module/lane_following/lane_following_module.cpp
planning/behavior_path_planner/src/scene_module/pull_out/pull_out_module.cpp
planning/behavior_path_planner/src/scene_module/pull_over/pull_over_module.cpp
planning/behavior_path_planner/src/scene_module/side_shift/side_shift_module.cpp

Removed redundant implementation of steering_factor_interface definition by moving it to the abstract class.
planning simulator worked well with

refactor(behavior_path_planner): move steering_factor_interface to abstract class

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance_by_lc/module.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/external_request_lane_change_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/lane_change_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_interface.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/side_shift/side_shift_module.hpp
planning/behavior_path_planner/src/scene_module/avoidance_by_lc/module.cpp
planning/behavior_path_planner/src/scene_module/lane_change/external_request_lane_change_module.cpp
planning/behavior_path_planner/src/scene_module/lane_change/lane_change_module.cpp

move getter functions of ego's data (pose, position, twist, speed) to abstract class.
Confirmed that build just passed since this is not a big change.

refactor(behavior_path_planner): move ego data getters to abstract class

---

perception/lidar_centerpoint/README.md
perception/lidar_centerpoint_tvm/README.md

I changed `Pointpillars` to `PointPillars` because the official notation is PointPillars.
Please check [the paper published in CVPR 2019](https://openaccess.thecvf.com/content_CVPR_2019/papers/Lang_PointPillars_Fast_Encoders_for_Object_Detection_From_Point_Clouds_CVPR_2019_paper.pdf).
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/m …

docs(lidar_centerpoint): fix typo

---

perception/compare_map_segmentation/include/compare_map_segmentation/multi_voxel_grid_map_update.hpp

**Fixed syntax error in multi_voxel_grid_map_update header:**
Namespace block should not end with semicolon as stated in cpp reference: 
https://en.cppreference.com/w/cpp/language/namespace 
This error breaks the build with some c++ compiler versions
Built on aarch64 and x86 platforms.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-g …

fix(compare_map_segmentation): fix namespace block syntax error

---

common/component_interface_specs/include/component_interface_specs/planning.hpp
planning/mission_planner/README.md
planning/mission_planner/src/mission_planner/mission_planner.cpp
system/default_ad_api/src/routing.cpp
system/default_ad_api/src/routing.hpp
system/default_ad_api/src/utils/route_conversion.cpp
system/default_ad_api/src/utils/route_conversion.hpp

From this comment: https://github.com/autowarefoundation/autoware.universe/pull/3396#issuecomment-1506993820. When we were using HADMapRoute, there was a type conversion problem, but now it is unified with LaneletRoute. So remove unnecessary services.
Check if the route can be set in the simple planning simulator.
None. …

refactor(mission_planner): merge set route service

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

To be consistent between invalid index guard and target vector.
```c++
if (prev_reference_.points.size() != prev_linear_shift_path_.shift_length.size()) {
throw std::logic_error("prev_reference_ and prev_linear_shift_path_ must have same size.");
}
...
const auto current_shift = prev_linear_shift_path_.shift_length.at(
findNearestIndex(prev_reference_.points, candidate.end.position));
```
WIP
Nothing. …

fix(avoidance): fix guard condition

---

localization/ndt_scan_matcher/README.md
localization/pose_initializer/README.md
perception/bytetrack/README.md
perception/image_projection_based_fusion/README.md
perception/lidar_centerpoint/launch/centerpoint_vs_centerpoint-tiny/README.md
perception/probabilistic_occupancy_grid_map/README.md
planning/behavior_velocity_planner/out-of-lane-design.md
planning/freespace_planning_algorithms/README.md
planning/obstacle_avoidance_planner/docs/debug.md
planning/obstacle_avoidance_planner/docs/mpt.md
vehicle/accel_brake_map_calibrator/accel_brake_map_calibrator/README.md

- I checked autoware.universe by cspell and got the result below
```
/home/autoware.universe/localization/ndt_scan_matcher/README.md:231:4 - Unknown word (splitted)
/home/autoware.universe/localization/ndt_scan_matcher/README.md:232:4 - Unknown word (splitted)
/home/autoware.universe/localization/ndt_scan_matcher/README.md:233:4 - Unknown word (splitted)
/home/autoware.universe/localization/pose_initializer/README.md:18:47 - Unknown word (localizar)
/home/autoware.universe/perception/bytetrack/README.md:15:3 - Unknown word (Yifu)
/home/autoware.universe/perception/bytetrack/README.md:15:15 - Unknown word (Peize)
/home/autoware.universe/perception/bytetrack/README.md:15:29 - Unknown word (Jiang)
/home/autoware.universe/perception/bytetrack/README.md:15:36 - Unknown word (Dongdong) …
```

docs: remove typos and add cspell ignore

---

planning/motion_velocity_smoother/CMakeLists.txt
planning/motion_velocity_smoother/src/motion_velocity_smoother_node.cpp
planning/motion_velocity_smoother/test/test_motion_velocity_smoother_node_interface.cpp

Two updates:
- add remove-overlap-points function at the top of the process
- enable a test for the invalid trajectory checking if the node won't die when the invalid trajectory is published
- pass the unit test
- run psim (go and stop)

feat(motion_velocity_smoother): add guard for duplicated points and enable tests

---

launch/tier4_planning_launch/launch/planning.launch.xml
launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.py
launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.xml
planning/behavior_path_planner/config/behavior_path_planner.param.yaml
planning/behavior_path_planner/config/drivable_area_expansion.param.yaml
planning/behavior_path_planner/config/lane_change/lane_change.param.yaml
planning/behavior_path_planner/config/lane_following/lane_following.param.yaml
planning/behavior_path_planner/include/behavior_path_planner/behavior_path_planner_node.hpp
planning/behavior_path_planner/include/behavior_path_planner/parameters.hpp
planning/behavior_path_planner/include/behavior_path_planner/planner_manager.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_following/lane_following_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/utils.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/planner_manager.cpp
planning/behavior_path_planner/src/scene_module/lane_following/lane_following_module.cpp
planning/behavior_path_planner/src/utils/utils.cpp
planning/behavior_path_planner/test/test_behavior_path_planner_node_interface.cpp

move lane_following_params to behavior path common params
this is not just refactor, some parameter values of lane following will be changed,
- lane_change_prepare_duration: 2.0 -> 4.0
- distance_threshold: 5.0 # [m] -> ego_nearest_dist_threshold: 3.0 # [m]
- yaw_threshold: 0.79 # [rad] -> ego_nearest_yaw_threshold: 1.046 # [rad] = 60 [deg]
threshold params is similar to https://github.com/autowarefoundation/autoware.universe/blob/main/planning/static_centerline_optimizer/config/nearest_search.param.yaml, so use it 
https://github.com/autowarefoundation/autoware_launch/pull/302
- psim
- [tier4 internal scenario test
](https://evaluation.tier4.jp/evaluation/reports/e0669c7b-f72b-5207-8007-10adb00a68d7?project_id=prd_jt) 1324/1330 -> 1324/1330 …

feat(behavior_path_planner): move lane_following_params to behavior path params

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/side_shift/side_shift_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/path_utils.hpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
planning/behavior_path_planner/src/scene_module/side_shift/side_shift_module.cpp
planning/behavior_path_planner/src/utils/path_utils.cpp

move `getUnshiftedEgoPose` and `calcCenterLinePath` defined in side_shift and avoidance to utils.
Planning simulator works well with

refactor(behavior_path_planner): move common functions of side_shift and avoidance to utils

---

planning/behavior_path_planner/test/test_behavior_path_planner_node_interface.cpp
planning/planning_test_utils/include/planning_interface_test_manager/planning_interface_test_manager.hpp
planning/planning_test_utils/src/planning_interface_test_manager.cpp

Add a test in the `behavior_path_planner` to check that the node will not die when the ego pose is located far from the target route
pass the unit test

test(planning_test_utils, behavior_path_planner): add test for off-track ego pose

---

.github/CODEOWNERS
launch/tier4_perception_launch/launch/occupancy_grid_map/probabilistic_occupancy_grid_map.launch.xml
launch/tier4_perception_launch/launch/perception.launch.xml
launch/tier4_perception_launch/package.xml
launch/tier4_simulator_launch/launch/simulator.launch.xml

Just like other packages I changed the auoware_launch to refer to launcher param file.
depend on launcher PR: https://github.com/autowarefoundation/autoware_launch/pull/294.
launcher PR: https://github.com/autowarefoundation/autoware_launch/pull/294
Psim works as before.
None
None
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidel …

refactor(occupancy_grid_map): add occupancy_grid_map method/param var to launcher

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

The avoidance module doesn't make a request to path modification when there is no new shift line.
On the other hand, sometimes shift lines are not generated for object that should be avoid, for example the ego speed is too high to avoid it.
Therefore, the avoidance module doesn't make a request and do anything for the object. However it is unexpected behavior. The avoidance module should make a request and insert decel point to path for object whose unavoidable reason is `TOO_LARGE_JERK`.
:arrow_down: The avoidance module do nothing, and the ego is stopped by obstacle stop planner. As a result, there isn't enough distance to avoid between ego and object.
https://user-images.githubusercontent.com/44889564/232629359-feccfe20-e96b-43ce-b880-9e7964eda3e8.mp4
In this PR, I fix request logic, …

fix(avoidance): request avoidance manauver when there is object that should be avoid

---

planning/behavior_path_planner/src/planner_manager.cpp

The planner manager doesn't control the order of removing expired modules from approved modules but I'm sure that it is better to define removing policy.
Since the last added module's output path is generated from first added module's output, perhaps the last added module's output changes greatly if it removes the first added module at first. And I think that it is safer to remove modules based on Last In First Out rule. 
In this PR, I use Last In First Out policy in unregistering logic.
On the other hand, when the lane change module finishes with `ModuleStatus::SUCCESS`, root lanelet and the input of first added module (module A in following fig) will be updated.
This also causes large path change, so the manager waits for all module success, only when it removes lane change module. …

fix(planner_manager): use LIFO policy in approved modules unregistering

---

planning/behavior_path_planner/CMakeLists.txt
planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/base_class.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/normal.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/utils.hpp
planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp
planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
planning/behavior_path_planner/src/utils/lane_change/utils.cpp

In order to minimize the amount of changes when the base class in inherited by the codes in the OLD ARCHITECTURE, some function is moved from `utils::lane_change` to `normal.cpp`. For the codes that required to be compiled with `COMPILE_WITH_OLD_ARCHITECTURE`, it is extracted into a proxy function, and the proxy function will be used in the main function. This is so that the main function will not be override when they are inherited later.
#3452 should be merged AFTER this PR.
#3452 should be merged AFTER this PR.
No changes to the main interface as this code only affect the module level.
No effects to the main system as this is refactoring PR.
The …

refactor(lane_change): unify the functions for old/new architecture

---

perception/map_based_prediction/src/map_based_prediction_node.cpp

Sometimes unintended prediction is created by crosswalk prediction module.
This is because non-crosswalk users(motor cycle) sometimes mistaken as crosswalk users(cyclist, pedestrian).
- path generation for crosswalk users 
- unintended prediction example
Instead of using the Label for Tracking directly, a label for Prediction should be assigned according to the situation of the object.
In Prediction, pedestrians and cyclists are affected by CrossWalk when generating paths, so depending on the situation, they are temporarily assigned other labels and paths are generated.
The table below shows the correspondence between these processes.
| tracking label\ prediction label | Motorcycle                      | Unknown                                                               | Cyclist     | …

fix(map_based_prediction): prevent unintended prediction generation for crosswalk users 

---

planning/behavior_path_planner/src/scene_module/avoidance_by_lc/module.cpp

Use minimum lane changing length computed from shift length and lateral jerk and acceleration.
Lane change buffer will be larger when using avoidance by lane change module

feat(behavior_path_planner): use dynamic minimum lane changing length

---

planning/behavior_path_planner/include/behavior_path_planner/utils/utils.hpp
planning/behavior_path_planner/src/scene_module/avoidance_by_lc/module.cpp
planning/behavior_path_planner/src/scene_module/lane_change/bt_normal.cpp
planning/behavior_path_planner/src/scene_module/lane_change/external_request_lane_change_module.cpp
planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
planning/behavior_path_planner/src/utils/lane_change/utils.cpp
planning/behavior_path_planner/src/utils/utils.cpp

Remove `calcLaneChangeBuffer` function as the lane change module can computes minimum lane changing length dynamically.
Already confirm that the new architecture can build this new code successfully.
1322/1330
[Scenario Result Link (TIER4 INTERNAL LINK)](https://evaluation.tier4.jp/evaluation/reports/dc6f217a-f287-51b8-9a36-5af8b7cb32d6?project_id=prd_jt)
Minimum lane changing length will be variable depend on shift length. …

feat(behavior_path_planner): remove calcLaneChangeBuffer function

---

common/tier4_perception_rviz_plugin/src/tools/car_pose.cpp
common/tier4_perception_rviz_plugin/src/tools/pedestrian_pose.cpp
common/tier4_perception_rviz_plugin/src/tools/unknown_pose.cpp

While testing in planning simulator, we sometimes need to set obstacle in negative side of z axis. Also, dummy vehicle's dimensions can not be negative.

feat(tier4_perception_rviz_plugin): use negative z pose and positive dimension values

---

planning/rtc_auto_mode_manager/src/rtc_auto_mode_manager_interface.cpp

Register new module `avoidance_by_lane_change_right/left` to rtc auto mode manager.
Related PR: https://github.com/tier4/tier4_autoware_msgs/pull/71
I can change rtc mode via rtc manager rviz plugin.
This PR make it possible to change `avoidance_by_lane_change` module rtc mode.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guideline …

feat(rtc_auto_mode_manager): add new module

---

launch/tier4_simulator_launch/launch/simulator.launch.xml
simulator/dummy_perception_publisher/README.md
simulator/dummy_perception_publisher/include/dummy_perception_publisher/node.hpp
simulator/dummy_perception_publisher/launch/dummy_perception_publisher.launch.xml
simulator/dummy_perception_publisher/src/node.cpp

In current implementation of autoware, dummy_perception_publisher always uses the baselink z position while publishing dummy object. Object's Z position can not be arranged from rviz plugin. I added a parameter to make it configurable. Default value of the parameter is true.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contri …

fix(dummy_perception_publisher): add parameter to configure z pose of dummy object

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

In `addReturnShiftLineFromEgo()`, perhaps wrong pose set to `last_sl.end` by mistake. As a result, unexpected shift line are shown in rviz.
**NOTE** Apart from rviz visualization, I think that this bug doesn't cause any problem but it is better to fix.
Unexpected shif line was removed.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-g …

fix(avoidance): return shift end pose

---

common/tier4_planning_rviz_plugin/include/path/display.hpp
common/tier4_planning_rviz_plugin/include/path/display_base.hpp
common/tier4_planning_rviz_plugin/src/path/display.cpp

By the recent refactoring of tier4_planning_rviz_plugin, the following function that update the vehicle_info by global parameters are removed by mistake.
https://github.com/autowarefoundation/autoware.universe/blob/ecc577457c5b7c92eb46f2fe33d5183ab4b44bf0/common/tier4_planning_rviz_plugin/src/path_footprint/display.cpp#L91-L103
This function can be implemented in the class which has Q_Object class.
Therefore, it cannot be implemented the base class since it does not have Q_Object due to its template abstraction.
So I implemented this function in each derived class redundantly.
When visualizing footprint of the **small** robot,
**with this PR**
(correct vehicle size)
**without this PR**
(not correct vehicle size)
On rviz, vehicle's size is used for footprint …

fix(tier4_planning_rviz_plugin): update vehicle info by global parameters

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/side_shift/side_shift_module.hpp
planning/behavior_path_planner/src/scene_module/side_shift/side_shift_module.cpp

Currently, with new architecture, the side shift module does not work well. 
This is because the following line will called every time after receiving a lateral offset.
https://github.com/autowarefoundation/autoware.universe/blob/79f7dc4106dc0c1f57070c01b119ae072a224a81/planning/behavior_path_planner/src/scene_module/side_shift/side_shift_module.cpp#L231
planning simulator worked well.
Without this PR, the sideshift module does not work well at all. …

fix(behavior_path_planner): fix side shift with new architecture

---

planning/obstacle_avoidance_planner/config/obstacle_avoidance_planner.param.yaml
planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/mpt_optimizer.hpp
planning/obstacle_avoidance_planner/src/mpt_optimizer.cpp

When avoiding obstacles by motion_planner, if the drivable area in front of the ego changes, the sudden steering will occur to make the trajectory inside the changed drivable area with optimization.
To suppress this behavior, the drivable area close to the ego can be fixed with the previous one.
launcher PR: https://github.com/autowarefoundation/autoware_launch/pull/311 …

feat(obstacle_avoidance_planner): fix reference points' boundary width

---

planning/obstacle_avoidance_planner/config/obstacle_avoidance_planner.param.yaml
planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/replan_checker.hpp
planning/obstacle_avoidance_planner/src/node.cpp
planning/obstacle_avoidance_planner/src/replan_checker.cpp

When the behavior's path shape changes like lane_change or avoidance, in the worst cases it takes 1 second to plan a path with optimization by obstacle_avoidance_planner.
With this PR, if the behavior's path shape changes, the optimization will work in this planning cycle.
launcher PR: https://github.com/autowarefoundation/autoware_launch/pull/309
planning simulator works well.
Optimization path planning will work right after the behavior's path shape changes. …

feat(obstacle_avoidance_planner): replan when forward path shape changes

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

The avoidance module calls heavy processing `calcAvoidancePlanningData` two or three times in one planning cycle, and it is redundant.
In this PR, I removed unnucessary function calling, and the processing time becomes half ~ one third on the new manager.
Faster the avoidance module processing.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull- …

perf(avoidance): remove redundant calculation process

---

planning/behavior_path_planner/config/drivable_area_expansion.param.yaml
planning/behavior_path_planner/include/behavior_path_planner/parameters.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_interface.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/avoidance_module_data.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/drivable_area_expansion/parameters.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/lane_change_module_data.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/lane_following/module_data.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/pull_out/pull_out_parameters.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/pull_over/pull_over_parameters.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/side_shift/side_shift_parameters.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
planning/behavior_path_planner/src/scene_module/avoidance_by_lc/module.cpp
planning/behavior_path_planner/src/scene_module/lane_change/bt_normal.cpp
planning/behavior_path_planner/src/scene_module/lane_change/external_request_lane_change_module.cpp
planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
planning/behavior_path_planner/src/scene_module/pull_out/pull_out_module.cpp
planning/behavior_path_planner/src/scene_module/pull_over/pull_over_module.cpp
planning/behavior_path_planner/src/scene_module/side_shift/side_shift_module.cpp
planning/behavior_path_planner/src/utils/pull_out/shift_pull_out.cpp
planning/behavior_path_planner/src/utils/pull_over/shift_pull_over.cpp
planning/behavior_path_planner/src/utils/utils.cpp

Currently, we have different drivable area expansion parameters for each module (lane change, avoidance, ...).
However, since with a new behavior_path_planner architecture, multiple modules are launched simultaneously, it's hard to expand the drivable area with different module's expansion parameters when multiple modules are launched.
Therefore, I changed the logic to have ONE set of parameters for all modules so that drivable area expansion future works well when multiple modules are launched.
planning simulator worked well.
Nothing. (With this PR, we cannot expand the drivable area statically with each module's different parameters)
The PR author …

feat(behavior_path_planner): make drivable area expansion parameters common

---

perception/lidar_centerpoint_tvm/CMakeLists.txt
perception/lidar_centerpoint_tvm/include/lidar_centerpoint_tvm/single_inference_node.hpp
perception/lidar_centerpoint_tvm/launch/lidar_centerpoint_tvm.launch.xml
perception/lidar_centerpoint_tvm/launch/single_inference_lidar_centerpoint_tvm.launch.xml
perception/lidar_centerpoint_tvm/lib/preprocess/pointcloud_densification.cpp
perception/lidar_centerpoint_tvm/scripts/lidar_centerpoint_visualizer.py
perception/lidar_centerpoint_tvm/src/single_inference_node.cpp

I add single inference lidar centerpoint node to lidar_centerpoint_tvm.

feat(lidar_centerpoint_tvm): single inference lidar centerpoint node

---

planning/behavior_velocity_planner/config/intersection.param.yaml
planning/behavior_velocity_planner/include/scene_module/intersection/scene_intersection.hpp
planning/behavior_velocity_planner/src/scene_module/intersection/manager.cpp
planning/behavior_velocity_planner/src/scene_module/intersection/scene_intersection.cpp

If intersection occlusion is enabled, the creep velocity for intersection occlusion will not be used.
If intersection occlusion is enabled, the creep velocity for intersection occlusion will not be used.

feat(intersection): add flag to enable creep towards intersection occlusion

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/base_class.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/external_request_lane_change_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/normal.hpp
planning/behavior_path_planner/src/scene_module/lane_change/external_request_lane_change_module.cpp
planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp
planning/behavior_path_planner/src/scene_module/lane_change/lane_change_module.cpp
planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp

For the following PR with which each module's output for drivable area will be drivable area information like drivable_lanes instead of drivable area line strings, the lane change module's output (generatePlannedPath's output) was changed from `Path` to `BehavioModuleOutput`.
https://github.com/tier4/autoware.universe/pull/373
planning simulator works well.
Nothing …

chore(lane_change): use BehaviorModuleOuput as output of generatePlannedPath

---

planning/behavior_velocity_planner/include/scene_module/intersection/scene_intersection.hpp
planning/behavior_velocity_planner/package.xml
planning/behavior_velocity_planner/src/scene_module/intersection/debug.cpp
planning/behavior_velocity_planner/src/scene_module/intersection/manager.cpp
planning/behavior_velocity_planner/src/scene_module/intersection/scene_intersection.cpp

Always send two intersection cooperate status:
- when occlusion is not detected:
- default intersection and (safe, -inf) intersection_occlusion status
- when occlusion is detected
- before `first stop line`:
- intersection_occlusion and intersection(for first stop line)
- after `first stop line`:
- intersection_occlusion and default intersection(for collision checking)
https://tier4.atlassian.net/browse/RT1-2166
When occlusion is not detected:
When occlusion is not detected:
This should be stress tested with FOA.
For each intersection, there will always be `intersection` and `intersection_occlusion` rtc status.
For each intersection, there will always be `intersection` and `intersection_occlusion` rtc status.
The PR …

feat(intersection): send intersection/intersection_occlusion rtc status

---

launch/tier4_perception_launch/launch/object_recognition/detection/pointcloud_map_filter.launch.py
perception/compare_map_segmentation/README.md
perception/compare_map_segmentation/include/compare_map_segmentation/distance_based_compare_map_filter_nodelet.hpp
perception/compare_map_segmentation/include/compare_map_segmentation/voxel_based_approximate_compare_map_filter_nodelet.hpp
perception/compare_map_segmentation/include/compare_map_segmentation/voxel_distance_based_compare_map_filter_nodelet.hpp
perception/compare_map_segmentation/include/compare_map_segmentation/voxel_grid_map_loader.hpp
perception/compare_map_segmentation/package.xml
perception/compare_map_segmentation/src/distance_based_compare_map_filter_nodelet.cpp
perception/compare_map_segmentation/src/voxel_based_approximate_compare_map_filter_nodelet.cpp
perception/compare_map_segmentation/src/voxel_distance_based_compare_map_filter_nodelet.cpp
perception/compare_map_segmentation/src/voxel_grid_map_loader.cpp

This PR update voxel_based_approximate_compare_map_filter, voxel_distance_based_compare_map_filter and distance_based_compare_map_filter to support dynamic map loader interface to solve the issue described at https://github.com/autowarefoundation/autoware.universe/issues/3085 
[TIERIV COMPANY INTERNAL LINK](https://tier4.atlassian.net/browse/RT1-70)
I have confirmed by logging simulator the performance of both static and dynamic map loader as similar as before the PR.
| - | Before | After: static map loader | After: dynamic map loader |
|---|---|---|---|
|   distance_based compare_map_filter |  ![image](https://user-images.githubusercontent.com/94814556/233335251-da4f605f-1e52-4943-bafb-c9f2ac65dc5d.png) | ![image](https://user-images.githubusercontent.com/94814556/233335287-3c504a90-08ca- …

fix(compare_map_segmentation): update remaining compare map filters for dynamic map loader

---

planning/behavior_velocity_planner/src/scene_module/intersection/manager.cpp

A additional PR for #3511, which I merged WIP status by mistake.
With this PR #3511 's result is available.
same as #3511

feat(intersection): send intersection/intersection_occlusion rtc status(fix #3511)

---

planning/behavior_path_planner/include/behavior_path_planner/marker_util/avoidance/debug.hpp
planning/behavior_path_planner/src/marker_util/avoidance/debug.cpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

separate debug marker namespace for each ignore reason in order to show only objects which we want to see.
Psim
Nothing.

feat(avoidance): separate debug marker namespace for each ignore reason

---

planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/avoidance_module_data.hpp
planning/behavior_path_planner/src/marker_util/avoidance/debug.cpp
planning/behavior_path_planner/src/utils/avoidance/util.cpp
planning/behavior_path_planner/src/utils/utils.cpp

- use infinity instead of max to show that next traffic light doesn't exist explicitly
Before this PR, debug marker shows huge FINITE number even when there is no traffic light within route.
After this PR, debug marker shows INF at such a situation.
Psim
System behavior doesn't change.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-g …

fix(avoidance): use infinity to show that next traffic light doesn't exist explicitly

---

planning/behavior_path_planner/include/behavior_path_planner/utils/utils.hpp
planning/behavior_path_planner/src/utils/pull_over/freespace_pull_over.cpp
planning/behavior_path_planner/src/utils/utils.cpp

In pull over's drivable area generation
- ~use different offsets for right and left offsets~
- margin is incorpolated into offset
working good
Nothing

feat(pull_over): minor change with drivable area expansion

---

planning/behavior_path_planner/CMakeLists.txt
planning/behavior_path_planner/include/behavior_path_planner/behavior_path_planner_node.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/pull_over_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/pull_over/default_fixed_goal_planner.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/pull_over/fixed_goal_planner_base.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/scene_module/pull_over/pull_over_module.cpp
planning/behavior_path_planner/src/utils/pull_over/default_fixed_goal_planner.cpp

Make pull_over execute when the vehicle is approaching the goal. (within `minimum_request_length`)
put goal in `road`
- `2D Goal Pose` in `road` 
-  `modifyPathForSmoothGoalConnection` (same as current lane following arrival path)
- `2D Rough Goal Pose` in `Road` 
-  pull over to the modified goal in `road` or `road_shoulder` with the select policy (e.g. parking left_side, right side)
check `2D Goal Pose` and `2D Rough Goal Pose`
https://user-images.githubusercontent.com/39142679/232829485-b9adcb85-c112-4ba1-972b-8440974c1e17.mp4
check planning to the fixed goal within `minimum_request_length`
https://user-images.githubusercontent.com/39142679/232829800-fdaf2e3c-ce74-483b-beb7-9b780d9b540f.mp4
lane_change ->goal planner
https://user-images.githubusercontent.com/39142679/232833424-ef5fcad0- …

feat(behavior_path_planner): add goal planner

---

planning/behavior_velocity_planner/src/scene_module/intersection/scene_intersection.cpp

Without the PR, the intersection module dies due to std::optional access.
Nothing

fix(intersection): fix node dying by optional access

---

launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.py
launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.xml
planning/behavior_path_planner/config/lane_change/lane_change.param.yaml
planning/behavior_path_planner/docs/behavior_path_planner_lane_change_design.md
planning/behavior_path_planner/include/behavior_path_planner/parameters.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/lane_change_module_data.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
planning/behavior_path_planner/src/utils/lane_change/utils.cpp

Use minimum acceleration from common params for the lane change module.
[Related PR](https://github.com/autowarefoundation/autoware_launch/pull/317)
PSim
No effects on system behavior. Just remove the redundant parameters.

refactor(behavior_path_planeer): use common.params for lane change

---

planning/behavior_velocity_planner/config/intersection.param.yaml
planning/behavior_velocity_planner/include/scene_module/intersection/scene_intersection.hpp
planning/behavior_velocity_planner/include/scene_module/intersection/util.hpp
planning/behavior_velocity_planner/src/scene_module/intersection/manager.cpp
planning/behavior_velocity_planner/src/scene_module/intersection/scene_intersection.cpp
planning/behavior_velocity_planner/src/scene_module/intersection/util.cpp

I fixed the peeking position calculation by checking the collision of each footprint position on the path and detection area.
parameter PR: https://github.com/autowarefoundation/autoware_launch/pull/320
https://tier4.atlassian.net/browse/RT1-2238
The peeking position is just at beginning of detection area.
Not applicable
Not applicable …

feat(behavior_velocity_planner::intersection): add parameter for occlusion peeking offset

---

planning/behavior_velocity_planner/src/scene_module/intersection/scene_intersection.cpp

Without this PR, the virtual wall pose is an offset ahead from the actual wall pose.
Nothing

fix(intersection): fix virtual wall pose

---

planning/behavior_velocity_planner/src/node.cpp

Added a guard of occupancy grid map initialization.
Without this PR, the intersection sometimes dies due to null pointer access.
Nothing

fix(intersection): add a guard of occupancy grid map initialization

---

planning/behavior_velocity_planner/src/scene_module/intersection/scene_intersection.cpp

Tighten the condition for first phase stop timeout by starting waiting when vehicle get stopped.
https://tier4.atlassian.net/browse/RT1-2240
The vehicle does not wait for 1sec exaclty.
https://user-images.githubusercontent.com/28677420/234219918-82f93848-7866-41d0-b08f-920f0b4e7b23.mp4
The vehicle waits for 1sec.
https://user-images.githubusercontent.com/28677420/234218075-5c6a2e56-11e9-4e6c-802d-ef3c6bdd34c8.mp4
Not applicable
Not applicable
The vehicle will wait for exactly specified time
[contribution …

fix(behavior_velocity_planner::intersection): strictly wait at 1st stop line when occlusion is detected

---

planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/avoidance_module_data.hpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
planning/behavior_path_planner/src/scene_module/avoidance_by_lc/module.cpp
planning/behavior_path_planner/src/utils/avoidance/util.cpp

This PR contains following perf improvement:
- use pre-resampled path for avoidance target filtering instead of fine resampled path. this change makes the `calcSignArcLength` faster.
- remove redundant closest lanelet calculation.
Make the avoidance process faster.

perf(avoidance): remove redundant process

---

common/autoware_auto_perception_rviz_plugin/include/object_detection/object_polygon_display_base.hpp

Fix following warnings.
```
[rviz2-39] QObject::connect: No such slot rviz_common::_RosTopicDisplay::updatePalette()
[rviz2-39] QObject::connect:  (sender name:   'Polygon Type')
[rviz2-39] QObject::connect: No such slot rviz_common::_RosTopicDisplay::updatePalette()
[rviz2-39] QObject::connect:  (sender name:   'Visualization Type')
[rviz2-39] QObject::connect: No such slot rviz_common::_RosTopicDisplay::updatePalette()
[rviz2-39] QObject::connect:  (sender name:   'Polygon Type')
[rviz2-39] QObject::connect: No such slot rviz_common::_RosTopicDisplay::updatePalette()
[rviz2-39] QObject::connect:  (sender name:   'Visualization Type')
[rviz2-39] QObject::connect: No such slot rviz_common::_RosTopicDisplay::updatePalette()
[rviz2-39] QObject::connect:  (sender name:   'Polygon Type') …
```

fix: rviz warning of updatePalette

---

common/rtc_manager_rviz_plugin/src/rtc_manager_panel.cpp

Fix chattering in RTC status visualization.
Before
[rtc_before.webm](https://user-images.githubusercontent.com/59680180/233992043-6331d589-19bd-4043-85e5-bbfd32e77308.webm)
Affter
[rtc_after.webm](https://user-images.githubusercontent.com/59680180/234456766-e338f3e3-0906-4c69-9e62-0a86fc195d09.webm) …

fix(rtc_manager_rviz_plugin): update panel visualization properly

---

planning/obstacle_stop_planner/CMakeLists.txt
planning/obstacle_stop_planner/include/obstacle_stop_planner/debug_marker.hpp
planning/obstacle_stop_planner/include/obstacle_stop_planner/node.hpp
planning/obstacle_stop_planner/include/obstacle_stop_planner/planner_utils.hpp
planning/obstacle_stop_planner/package.xml
planning/obstacle_stop_planner/src/debug_marker.cpp
planning/obstacle_stop_planner/src/node.cpp
planning/obstacle_stop_planner/src/planner_utils.cpp

If the use_predicted_objects true there was a bug. If the obstacle left of the trajectory, stop planner founds an intersection and send stop. To fix this, I changed polygon creating method, and also it removes the opencv lib dependency.
In the picture, as you can see that although obstacle is outside of the trajectory, obstacle_stop_planner assumes there is an obstacle on the path. While using predicted_objects, node checks there is intersection between vehicle footprint and obstacle polygon. Before this PR, while creating polygon, checking polygon direction is unobserved. Because the direction is not determined, bg::intersects returns false positive while obstacle is left of the trajectory. 
https://user-images.githubusercontent.com/45468306/234491580-463cc71e-4e9b-4cce-ac39-94737125b07c. …

fix(obstacle_stop_planner): change polygon creating method

---

planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp

fix executing goal_planner when goal is before ego by considering negative `self_to_goal_arc_length`  value.
psim 
goal_planner is not executed and avoidance can be run.
no
can set goal before ego

fix(behavior_path_planner): fix executing goal_planner when goal is before ego

---

planning/behavior_path_planner/config/behavior_path_planner.param.yaml
planning/behavior_path_planner/include/behavior_path_planner/parameters.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/lane_change_module_data.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/scene_module/avoidance_by_lc/module.cpp
planning/behavior_path_planner/src/scene_module/lane_change/bt_normal.cpp
planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
planning/behavior_path_planner/src/utils/lane_change/utils.cpp

Remove duplicated lane change parameter. i.e. `lane_change_prepare_duration`.
[Related PR](https://github.com/autowarefoundation/autoware_launch/pull/328)

refactor(behavior_path_planner): remove dupliated lane change parameters

---

planning/motion_velocity_smoother/src/motion_velocity_smoother_node.cpp

In the current implementation, when applying the external velocity limit, the velocity of the points on the trajectory are being overwritten. However, this implementation has an issue where the inserting position of the external velocity limit is further away than expected and ego vehicle sometimes can't stop at the desired position (see the video below).
In this PR, I have resolved this problem by inserting the point of the external velocity limit.
https://user-images.githubusercontent.com/11865769/233629346-72330fa1-61b0-4bc8-91a6-513f12e440f9.mp4
I confirmed this works with simple planning simulator.
https://user-images.githubusercontent.com/11865769/233630064-8d7fbd16-4cd8-4257-9bb3-7d38d27f1176.mp4 …

fix(motion_velocity_smoother): insert the point when applying external velocity limit

---

planning/behavior_velocity_planner/include/scene_module/intersection/scene_intersection.hpp
planning/behavior_velocity_planner/src/scene_module/intersection/manager.cpp
planning/behavior_velocity_planner/src/scene_module/intersection/scene_intersection.cpp

Always send proper RTC distance for intersection_occlusion
When all modules are approved and there is no occlusion: 
- intersection(default): distance is finite
- intersection(occlusion): distance is -inf because occlusion does not exist
When all modules are disapproved:
- intersection(default): distance is finite
- intersection(occlusion): distance is finite
When all modules are disapprove,d the car will wait at the first stop line even if it waited for more than the specified time of 2 phase stop.
rtc distance is properly set for FOA
rtc distance is properly set for FOA
After all …

fix(intersection): fix occlusion rtc distance

---

common/tier4_planning_rviz_plugin/include/path/display.hpp

Remove z offset from the left and right bound to clean the visualization.

feat(tier4_planning_rviz_plugin): remove z offset from the bound

---

planning/behavior_velocity_planner/src/scene_module/intersection/scene_intersection.cpp

Without this PR, in some cases, the intersection module dies due to nullpointer access.
Nothing

fix(intersection): fix dying node

---

planning/behavior_velocity_planner/include/scene_module/intersection/scene_intersection.hpp
planning/behavior_velocity_planner/src/scene_module/intersection/scene_intersection.cpp

Fixed costmap generation to clear cost on adjacent_lanes
https://tier4.atlassian.net/browse/RT1-2170
cost is generated on ego lane
cost is not generated on ego lane
Not applicable
Not applicable

feat(intersection): clear costmap on adjacent lanes

---

planning/behavior_velocity_planner/src/scene_module/intersection/scene_intersection.cpp

Prior this PR, ego vehicle keeps stopping at the peeking stop line after occlusion gets cleared.
RTC works as before.
ego stucks
https://user-images.githubusercontent.com/28677420/234611335-7c5fa991-b2af-47cd-b375-c6c20f05c94b.mp4
https://user-images.githubusercontent.com/28677420/234610279-09d2bdf0-b587-45f5-8639-d392631b5557.mp4
ego restarts after occlusion is cleared.
ego restarts after occlusion is cleared. …

fix(intersection): fixed to restart after occlusion is cleared

---

planning/behavior_path_planner/include/behavior_path_planner/utils/utils.hpp
planning/behavior_path_planner/package.xml
planning/behavior_path_planner/test/input.cpp

Currently, the behavior path planner does not depend on OpenCV.
I removed the dependency from the code.
Nothing

chore(behavior_path_planner): remove open cv dependency

---

planning/behavior_path_planner/src/utils/utils.cpp

the `current_lanes` is not used and unnecessary. I remove it.
Psim&Evalautor
Psim

refactor(utils): remove unnecessary variable

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/side_shift/side_shift_module.hpp
planning/behavior_path_planner/src/scene_module/side_shift/side_shift_module.cpp

Without this PR, in some cases which I'm not sure, the generated drivable area is weird as follows.
This is because during side shift calculation, the path front point is not close to the ego but far away from the ego, and the result of the nearest search from the path front point to something for drivable area calculation is wrong.
In this PR, I crop the path close to the ego before drivable area generation and after the path calculation. …

fix(side_shift): fix drivable area generation

---

planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/utils.hpp
planning/behavior_path_planner/src/scene_module/avoidance_by_lc/module.cpp
planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
planning/behavior_path_planner/src/utils/lane_change/utils.cpp

Use lanelets instead of lanelet to get backward lanelets for collision check of the lane change module. I also changed the function name to `getBackwardLanelets` to make it easy to understand.
Scenario Result 1326/1330
[TIER IV Internal Link](https://evaluation.tier4.jp/evaluation/reports/d9a08f72-9553-5fcc-a67a-db9d538fc87f?project_id=prd_jt)
When there are several lanes adjacent to current lanelets, the computation can be much more accurate than before. …

feat(behavior_path_planner): use lanelets for getting backward lanelets

---

perception/lidar_centerpoint/README.md

The description related to how lidar_centerpoint was trained had a typo in which the number of samples between nuscenes and argoverse2 were swapped
:bow: 

fix(lidar_centerpoint): fixed a typo in the documentation related to centerpoint's training

---

planning/behavior_velocity_planner/src/utilization/util.cpp

Considering the new feature of `pull_over`,  `lane_ids` may contain the ids of `intersection && road_shoulder` lanes that are before/after the goal `road_shoulder`
https://tier4.atlassian.net/browse/RT1-2267
https://user-images.githubusercontent.com/28677420/235067850-fe153ab5-344a-4e91-99e8-95cdd1954078.mp4
Before this PR the intersection module for `lane 11` repeatedly registered and deleted in every iteration in the case shown in the above video. After this PR it does not happen.
The consideration for Lane change is still OK (the ID of active intersection modules does not change in the below video).
https://user-images.githubusercontent.com/28677420/235068539-67bb7ab9-ee61-44b6-a97d-fa71843f0be2.mp4
RTC/FOA for intersection does not chatter.
RTC/FOA for intersection does not chatter. …

feat(behavior_velocity_planner::intersection): modify module deletion condition

---

planning/behavior_velocity_planner/src/scene_module/intersection/manager.cpp
planning/behavior_velocity_planner/src/scene_module/intersection/scene_intersection.cpp

always set the distance to default occlusion peeking stop line for RTC
The distance is finite when not occluded or approved.
approval process of `intersection_occlusion` in RTC
approval process of `intersection_occlusion` in RTC

fix(intersection): always send finite distance to occlusion peeking stop line in RTC

---

launch/tier4_planning_launch/launch/planning.launch.xml
launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.py
planning/behavior_path_planner/CMakeLists.txt
planning/behavior_path_planner/config/dynamic_avoidance/dynamic_avoidance.param.yaml
planning/behavior_path_planner/config/scene_module_manager.param.yaml
planning/behavior_path_planner/docs/behavior_path_planner_dynamic_avoidance_design.md
planning/behavior_path_planner/include/behavior_path_planner/behavior_path_planner_node.hpp
planning/behavior_path_planner/include/behavior_path_planner/data_manager.hpp
planning/behavior_path_planner/include/behavior_path_planner/parameters.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/dynamic_avoidance/dynamic_avoidance_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/dynamic_avoidance/manager.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_manager_interface.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp
planning/behavior_path_planner/src/scene_module/dynamic_avoidance/manager.cpp
planning/behavior_path_planner/test/test_behavior_path_planner_node_interface.cpp

**This feature is under development, and disabled by default.**
NOTE:
- This module is supposed to be used with a new behavior_path_planner architecture
- The following parameter should be false since the trajectory may be outside the drivable area in some cases.
https://github.com/autowarefoundation/autoware_launch/blob/5910b08f7742d78ac5f1ade182d470032e40e398/autoware_launch/config/planning/scenario_planning/lane_driving/motion_planning/obstacle_avoidance_planner/obstacle_avoidance_planner.param.yaml#L7
- This module does not require RTC's approval to execute.
Added a dynamic avoidance module for avoiding dynamic obstacles which are running on the road.
In the current implementation, by extracting the dynamic obstacles to avoid from the drivable area, the motion planner plans the …

feat(behavior_path_planner): add dynamic obstacle avoidance module

---

common/tier4_planning_rviz_plugin/src/path/display.cpp

Issue is from the TIER IV internal slack https://star4.slack.com/archives/CEV8XMJBV/p1682650776731999?thread_ts=1682581409.075349&cid=CEV8XMJBV
When launching rviz with some tier4_planning_rviz_plugin visualization not from `autoware_launch`, since the global parameters are not loaded, the following warning is output every 5 seconds.
`[rviz2-5] [WARN] [1682649532.332513253] [foa_rviz]: Failed to get vehicle_info: parameter 'wheel_radius' is not initialized`
I suppressed this warning. This warning will be output only first with this PR.
launch rviz manually
Nothing …

fix(tier4_planning_rviz_plugin): suppress warning

---

common/motion_utils/include/motion_utils/trajectory/trajectory.hpp
common/motion_utils/test/src/trajectory/test_trajectory.cpp

support negative length for the following insertTargetPoint function.
```cpp
template <class T>
inline boost::optional<size_t> insertTargetPoint(
const size_t src_segment_idx, const double insert_point_length, T & points,
const double overlap_threshold = 1e-3)
```
Unit test
Nothing
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guide …

feat(motion_utils): insertTargetPoint with negative length

---

planning/behavior_path_planner/include/behavior_path_planner/data_manager.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/utils.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/utils.hpp
planning/behavior_path_planner/src/planner_manager.cpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp
planning/behavior_path_planner/src/utils/avoidance/utils.cpp
planning/behavior_path_planner/src/utils/utils.cpp

When extracting the object's polygon from the drivable area, left or right drivable area's line string is selected for extraction according to the CoM (center of mass) of the polygon.
However, this logic cannot deal with the case on a curve.
Therefore,  I changed the logic of selecting left or right drivable area's line string by using the object pose instead of CoM as follows.
**without this PR**
The object is extracted from the left drivable line string by mistake.
**with this PR**
The object is extracted from the right drivable line string correctly. …

fix(behavior_path_planner): use object pose when extracting drivable area

---

planning/behavior_path_planner/config/dynamic_avoidance/dynamic_avoidance.param.yaml
planning/behavior_path_planner/docs/behavior_path_planner_dynamic_avoidance_design.md
planning/behavior_path_planner/include/behavior_path_planner/scene_module/dynamic_avoidance/dynamic_avoidance_module.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp

With this PR, oncoming vehicles can be avoided as follows.
NOTE: The parameters are tuned for the video to show how this works easily to understand.
[Screencast from 2023年04月29日 00時58分05秒.webm](https://user-images.githubusercontent.com/20228327/235197189-fba5f009-6eec-4b31-9e47-1dea4bd244f1.webm)
When testing like the above movie,
- incorpolate https://github.com/autowarefoundation/autoware.universe/pull/3583 and https://github.com/autowarefoundation/autoware.universe/pull/3579 (This has launcher's change)
- add change in autoware.universe
```bash
$ git diff
diff --git a/planning/behavior_path_planner/CMakeLists.txt b/planning/behavior_path_planner/CMakeLists.txt
index 78383f6146..710f287175 100644
--- a/planning/behavior_path_planner/CMakeLists.txt
+++ …
```

feat(dynamic_avoidance): avoid oncoming vehicles

---

planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/scene_module/avoidance/manager.cpp

the planner manager supports dynamic reconfigure. (+ add some params in updateModuleParams in avoidance manager.)
https://user-images.githubusercontent.com/44889564/235178747-d94ca960-49b9-45e8-8116-6a93a71acded.mp4
Psim
Nothing.

feat(behavior_path_planner): support dynamic reconfigure on new manager

---

planning/obstacle_avoidance_planner/config/obstacle_avoidance_planner.param.yaml
planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/mpt_optimizer.hpp
planning/obstacle_avoidance_planner/src/mpt_optimizer.cpp

When obstacles are extracted from the drivable area for static avoidance or dynamic avoidance by the motion planner, in some cases, the drivable area width is too narrow and it's infeasible to drive inside the drivable area as shown in the following figures.
In this case, without the PR, the trajectory optimization failed due to infeasible drivability.
To deal with this case, the obstacle avoidance planner expands the drivable area if it's infeasible to drive.
This feature of keeping the feasible drivable area width should be considered when the drivable area is created in the behavior_path_planner.
The reason I put this feature into not the behavior_path_planner but the obstacle_avoidance_planner is to add less implementation for this feature.
The obstacle_avoidance_planner already …

feat(obstacle_avoidance_planner): deal with infeasible drivable area

---

planning/behavior_path_planner/include/behavior_path_planner/planner_manager.hpp

Planner manager update closest lanelet in each planning cycle while the ego is **NOT** in Autonomouls mode.
In this PR, planner manager uses distance & yaw constraints for closest lanelet search so that planner manager finds proper lanelet.
The planner manager gets unproper lanelet at loop section.
https://user-images.githubusercontent.com/44889564/234433794-11d47b1c-5e08-4979-bfb9-19947bdd43a1.mp4
The planner manager can find proper lanelet even if the ego position is **NOT** on the path.
https://user-images.githubusercontent.com/44889564/234434025-2b0a7cec-d424-4704-bdd9-7afb4755bf63.mp4
Psim
Supports loop path. …

feat(planner_manager): use distance & yaw constraints for closest lanelet search

---

planning/behavior_path_planner/include/behavior_path_planner/behavior_tree_manager.hpp
planning/behavior_path_planner/include/behavior_path_planner/data_manager.hpp
planning/behavior_path_planner/include/behavior_path_planner/planner_manager.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/utils.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/behavior_tree_manager.cpp
planning/behavior_path_planner/src/planner_manager.cpp
planning/behavior_path_planner/src/utils/utils.cpp

Before this change, behavior_path_planner outputs an improper path if the ego vehicle is out of route.
To fix it, I add the feature to output shorten path such a situation.
https://user-images.githubusercontent.com/10190493/226199820-d6693759-2bf2-485a-8a82-9a10dab81a36.mp4
TIER IV internal test result 882/882 …

feat(behavior_path_planner): output shorten path if ego vehicle is out of route

---

planning/behavior_path_planner/include/behavior_path_planner/behavior_path_planner_node.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp

moved `modifyPathForSmoothGoalConnection` to `goal_planner` in https://github.com/autowarefoundation/autoware.universe/pull/3454, so `behavior_path_planner_node`'s one is not used now.
https://github.com/autowarefoundation/autoware.universe/pull/3454
build
no
no

refactor(behavior_path_planner): remove unnecessary modifyPathForSmoothGoalConnection

---

planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp

Fix the bug that `goal_planner` canceled when backward parking.
This bug was caused by https://github.com/autowarefoundation/autoware.universe/pull/3541
[Screencast from 2023年04月27日 14時51分24秒.webm](https://user-images.githubusercontent.com/39142679/235457412-7e5ef23d-6423-4533-bfe9-94aa893aa99b.webm)
[tier4 internal slack](https://star4.slack.com/archives/CEV8XMJBV/p1682574760315699?thread_ts=1682493975.605229&cid=CEV8XMJBV)
[tier4 internal ticket](https://tier4.atlassian.net/browse/RT1-2277)
psim
- backward pull over can be done
https://user-images.githubusercontent.com/39142679/235457653-bd5caced-54b4-4b8b-b5df-79fb46ba037d.mp4
- the goal can be put before the ego in the previous lane 
- can not put in the same lane (this is current planning limitation not just for goal_planner) …

fix(behavior_path_planner): fix goal planner backward parking

---

planning/behavior_path_planner/include/behavior_path_planner/planner_manager.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_interface.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_manager_interface.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/behavior_tree_manager.cpp

show module's important markers as default. 
add anothre publisher.
(I'm working on implementation so that avoidance module outputs info markers.)
- https://github.com/autowarefoundation/autoware_launch/pull/333
Psim
Nothing.

feat(behavior): add interface in order to publish marker that is always shown in rviz

---

planning/behavior_path_planner/src/planner_manager.cpp

Fix build error on new manager.
- https://github.com/autowarefoundation/autoware.universe/pull/3605
```
--- stderr: behavior_path_planner                                                                                                                                                                                                                                                                                                                                                                                               
CMake Warning at CMakeLists.txt:78 (message): …
```

fix(planner_manager): fix build error

---

planning/behavior_path_planner/config/goal_planner/goal_planner.param.yaml
planning/behavior_path_planner/docs/behavior_path_planner_goal_planner_design.md
planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_out/pull_out_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/geometric_parallel_parking/geometric_parallel_parking.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/goal_planner/geometric_pull_over.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/goal_planner/goal_planner_parameters.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/pull_out/geometric_pull_out.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/pull_out/pull_out_parameters.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
planning/behavior_path_planner/src/scene_module/pull_out/pull_out_module.cpp
planning/behavior_path_planner/src/utils/geometric_parallel_parking/geometric_parallel_parking.cpp
planning/behavior_path_planner/src/utils/goal_planner/freespace_pull_over.cpp
planning/behavior_path_planner/src/utils/goal_planner/geometric_pull_over.cpp
planning/behavior_path_planner/src/utils/goal_planner/shift_pull_over.cpp
planning/behavior_path_planner/src/utils/pull_out/geometric_pull_out.cpp

refactoring `goal_planner` and `pull_out` related params
https://github.com/autowarefoundation/autoware_launch/pull/338
psim
[tier4 internal scenario tets
](https://evaluation.tier4.jp/evaluation/reports/68cb483b-db53-5e85-84d9-9d540996b419?project_id=prd_jt) 1328/1350
[5/3 daily](https://evaluation.tier4.jp/evaluation/reports/d97bfaf8-d6b3-5e92-bc6c-68a26e1527dd?project_id=prd_jt) 1323/1350 
nothing
nothing
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contribu …

refactor(behavior_path_planner): refactoring goal_planner and pull_out params

---

planning/planning_test_utils/include/planning_interface_test_manager/planning_interface_test_manager.hpp
planning/planning_test_utils/include/planning_interface_test_manager/planning_interface_test_manager_utils.hpp
planning/planning_test_utils/src/planning_interface_test_manager.cpp

Add util functions to check the node will not die when the ego-vehicle pose is located far from the target trajectory.
None
None. (tested in each package)
None

feat(planning_test_utils): add off-track test for path and trajectory

---

planning/freespace_planner/test/test_freespace_planner_node_interface.cpp

test(freespace_planner): add off-track test

---

planning/behavior_path_planner/src/planner_manager.cpp

- check existance of the running candidate module
- https://github.com/autowarefoundation/autoware.universe/pull/3611
Nothing.

fix(planner_manager): check existance of running candidate module

---

common/tier4_state_rviz_plugin/src/velocity_steering_factors_panel.cpp
common/tier4_traffic_light_rviz_plugin/src/traffic_light_publish_panel.cpp

resolve https://github.com/autowarefoundation/autoware.universe/issues/2923
fix panel view of table widgets
by psim
Add velocity and steering factor panel and traffic light publish panel

fix(rviz_plugin): fx traffic light and velocity factor rviz plugin

---

planning/behavior_path_planner/include/behavior_path_planner/marker_util/avoidance/debug.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module.hpp
planning/behavior_path_planner/src/marker_util/avoidance/debug.cpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

- add another markers that contains important information about the avoidance module.
- the avoidance module outputs `avoidable_target_objects` and `unavoidable_target_objects` marker as important information.
- these markers are always shown in Rviz by default.
- https://github.com/autowarefoundation/autoware_launch/pull/339
Psim
- RED Cube -> Target objects that is **NOT** avoidable.
- YELLOW Cube -> Target objects that is avoidable.
Nothing. …

feat(avoidance): output avoidance target marker that are always shown in rviz

---

planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/utils.hpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
planning/behavior_path_planner/src/utils/avoidance/utils.cpp

In following two patern, the ego doesn't need to shift any more.
- the object is on **RIGHT** of the ego' path, and the shift length is **LESS** than zero.
- the object is on **LEFT** of the ego' path, and the shift length is **MORE** than zero.
Currently, since avoidance module doesn't check these condition explicitly, those objects are shown as `IsSameDirectionShift`.
In this PR, I added a funciton to check above condition and push back those objects in other objects (not target objects) as `NotNeedAvoidance`.
Nothing. …

fix(avoidance): fix visualization bug

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_interface.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_manager_interface.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/goal_planner/default_fixed_goal_planner.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/goal_planner/fixed_goal_planner_base.hpp
planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
planning/behavior_path_planner/src/utils/goal_planner/default_fixed_goal_planner.cpp

enable running `goal_planner` with other modules **ONLY** when goal is fixed.
https://user-images.githubusercontent.com/39142679/235111350-eabee7ff-90ad-4e56-b4be-9e76b560be82.mp4
TODO: 
if goal is allowed modification, `goal_planner` (pull_over) can not be run with other modules.
we need to deal with this in the future.
https://user-images.githubusercontent.com/39142679/235111515-3cdf87e0-db60-48cf-9df6-c79bc836e6ae.mp4
psim
wip tier4 internal scenario test
- beahvior path old archi https://evaluation.tier4.jp/evaluation/reports/9345fb71-57b0-55c7-9fc5-63e2a526ea18/?project_id=prd_jt 1325/1350
- behavior path new archi https://evaluation.tier4.jp/evaluation/reports/603cb665-4cd0-52fc-8144-8f1a5dcbb1d3/?project_id=prd_jt 1326/1350
no
`goal_planner` can run with other modules simutaneously …

feat(behavior_path_planner): run fixed_goal_planner with other modules simutaneously

---

planning/obstacle_stop_planner/test/test_obstacle_stop_planner_node_interface.cpp

test(obstacle_stop_planner): add off-track test

---

planning/scenario_selector/test/test_scenario_selector_node_interface.cpp

test(scenario_selector): add off-track test

---

planning/obstacle_cruise_planner/test/test_obstacle_cruise_planner_node_interface.cpp

test(obstacle_cruise_planner): add off-track test

---

planning/behavior_path_planner/src/turn_signal_decider.cpp

Fix turn signal decider to terminate the turn signal when there is intersection turn signal information.
1336/1350
[TIER4 Internal Link](https://evaluation.tier4.jp/evaluation/reports/effd4595-050a-53c6-bac1-e772c287e57f?project_id=prd_jt)
Turn signal ends properly when it reaches at the required end point. …

fix(behavior_path_planner): terminate turn signal when it passes end point

---

planning/behavior_velocity_planner/src/scene_module/intersection/debug.cpp

When there are multiple intersection module running and each of them is publishing virtual walls, there ids were duplicate and some walls were not displayed.
https://tier4.atlassian.net/browse/RT1-2283
Psim
only intersection walls farthest from ego are displayed.
Multiple intersection wall marker appears properly when all modules are disapproved.
Multiple intersection wall marker appears properly when all modules are disapproved. …

fix(intersection): fixed virtual wall marker id duplication

---

planning/behavior_path_planner/config/avoidance/avoidance.param.yaml
planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/avoidance_module_data.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
planning/behavior_path_planner/src/scene_module/avoidance/manager.cpp

- remove hard coded parameters
- add parameters
- https://github.com/autowarefoundation/autoware_launch/pull/341

refactor(avoidance): remove hard code params

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/base_class.hpp
planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp
planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp

previous drivable_lanes is held in LC to keep the information when generating the current drivable_lanes.
Additionally, drivable_area_info itself has to be kept as well when generating the current drivable_area_info to keep other variables in DrivableAreaInfo other than drivable_lanes (e.g. obstacles to extract from the drivable area).
With this PR, previous drivable_area_info is held in LC.
Nothing
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/mai …

feat(behavior_path_planner): hold previous drivable area info in LC

---

planning/behavior_path_planner/include/behavior_path_planner/behavior_path_planner_node.hpp
planning/behavior_path_planner/include/behavior_path_planner/data_manager.hpp
planning/behavior_path_planner/include/behavior_path_planner/turn_signal_decider.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/turn_signal_decider.cpp

Currently, last added scene module over writes turn signal info, and previous module's signal is always ignored.
In this PR, I added new function to resolve multiple modules' turn signal info based on [**THIS**](https://github.com/autowarefoundation/autoware.universe/blob/main/planning/behavior_path_planner/docs/behavior_path_planner_turn_signal_design.md) algorithm.
](https://evaluation.tier4.jp/evaluation/reports/4432f4e5-8ebd-5dad-bb21-518412f0d610?project_id=prd_jt)
Nothing. (Just adding new function.) …

feat(behavior_path_planner): resolve multiple modules turn signal info

---

map/map_loader/src/lanelet2_map_loader/lanelet2_map_visualization_node.cpp

visualize hatched road markings area in LL2.
Discussion for introducing hatched road markings area.
https://github.com/orgs/autowarefoundation/discussions/3414
can visualize the area with planning simulator

feat(map_loader): visualize hatched road markings

---

perception/tensorrt_yolo/lib/src/plugins/nms_plugin.cpp
perception/tensorrt_yolo/lib/src/plugins/yolo_layer_plugin.cpp
sensing/pointcloud_preprocessor/src/crop_box_filter/crop_box_filter_nodelet.cpp
system/system_monitor/reader/hdd_reader/hdd_reader.cpp

see https://github.com/autowarefoundation/autoware.universe/issues/3215
Replace misc UB `reinterpret_cast` with the `memcpy` equivalent.

fix(perception): remove UB reinterpret_cast

---

planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp

Consider previous module turn signal info.
Improve turn signal behavior.

feat(goal_planner): consider previous module's turn signal

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/base_class.hpp
planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp
planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp

- consider previous module's turn signal in lane change module.
- https://github.com/autowarefoundation/autoware.universe/pull/3634
Improve turn signal behavior.

feat(lane_change): consider previous module's turn signal

---

planning/obstacle_stop_planner/README.md
planning/obstacle_stop_planner/include/obstacle_stop_planner/adaptive_cruise_control.hpp
planning/obstacle_stop_planner/include/obstacle_stop_planner/node.hpp
planning/obstacle_stop_planner/include/obstacle_stop_planner/planner_data.hpp
planning/obstacle_stop_planner/include/obstacle_stop_planner/planner_utils.hpp
planning/obstacle_stop_planner/src/adaptive_cruise_control.cpp
planning/obstacle_stop_planner/src/node.cpp
planning/obstacle_stop_planner/src/planner_utils.cpp

In obstacle_stop_planner, use_predicted_object option was added but it does not work as we wanted. Firstly, there are some bugs while checking the obstacle. For example, it uses the last collision footprint to set collision point.
Also, it checks only intersected points while checking collision, however, corner points also need to be checked.
Also I needed make some changes in adaptive_cruise_planner while using predicted objects, because perception side is estimating obstacle velocity, adaptive_cruise_control does not need to estimate the velocity.
For Z-Axis-Filtering: 
Stop test: 
https://user-images.githubusercontent.com/45468306/234703822-f77bb994-44c5-4cea-91b1-fb4b973e74b0.mp4
Vehicle following:
https://user-images.githubusercontent.com/45468306/234703863-45086564-16a7-4bf9-82fb-0c5 …

fix(obstacle_stop_planner): fix the issues when use_predicted_objects true

---

sensing/pointcloud_preprocessor/docs/ring-outlier-filter.md
sensing/pointcloud_preprocessor/include/pointcloud_preprocessor/outlier_filter/ring_outlier_filter_nodelet.hpp
sensing/pointcloud_preprocessor/src/filter.cpp
sensing/pointcloud_preprocessor/src/outlier_filter/ring_outlier_filter_nodelet.cpp

This PR makes `ring_outlier_filter` faster without changing the logical output. The tail latency of the `ring_outlier_filter` node gets about x3 faster with the introduction of the TLSF allocator (see [this Autoware Discussion](https://github.com/autowarefoundation/autoware/discussions/3274)) and this PR merged.
Measurement Condition
- Ubuntu22.04 + ROS2 Humble + [Autoware Universe rosbag simulation](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/rosbag-replay-simulation/)
- Core Isolated
- Core Frequency Fixed (2.6GHz)
- L3 Cache: 12MB
- [Introduction of a library for the replacement of heap allocation in Autoware (Autoware Discussion)](https://github.com/autowarefoundation/autoware/discussions/3274)
- [Background, Implementation Detail and …

perf(ring_outlier_filter): performance tuning

---

launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml

This PR fixes the duplicated name topics which are used in camera_lidar_radar_fusion mode.

fix(tier4_perception_launch): fix duplicated topic name

---

perception/multi_object_tracker/src/tracker/model/big_vehicle_tracker.cpp
perception/multi_object_tracker/src/tracker/model/normal_vehicle_tracker.cpp

- Due to uninitialized `Eigen::Vector2d` vectors, initial pose and velocity estimation sometimes have small error
- Fixed this issue by properly initialize `tracking_offset_` vector, which handles position relationship between anchor point and Bounding Box center. 
Tested in TIER IV scenario.
See [internal ticket](https://tier4.atlassian.net/browse/RT1-2197).
- before
- after 
Vehicle tracking result will be slightly changed. …

fix(multi_object_tracker): fix unintended perturbation in tracking estimation via non initialized eigen vector

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

Consider previoius module's turn signal info based on **[THIS](https://autowarefoundation.github.io/autoware.universe/main/planning/behavior_path_planner/docs/behavior_path_planner_turn_signal_design/)** algorithm.
Improve turn signal decision making.

feat(avoidance): consider previous module's turn signal

---

planning/behavior_path_planner/CMakeLists.txt
planning/behavior_path_planner/src/utils/safety_check.cpp
planning/behavior_path_planner/test/test_safety_check.cpp

Use `std::numeric_limits<double>::lowest` instead of `std::numeric_limits<double>::min()` for the lateral cauclation. Also, I fixed the initial value for the minimum distance.
Add several unit tests to check the distance calculation function works properly.
Scenario Test 1324/1350
[TIER IV Internal](https://evaluation.tier4.jp/evaluation/reports/145fd6ea-c8b2-5507-b46c-d370afca0f31?project_id=prd_jt)
Safety check for the lane change path can be more strict. …

fix(behavior_path_planner): fix lateral distance calculation

---

planning/behavior_path_planner/include/behavior_path_planner/data_manager.hpp
planning/behavior_path_planner/src/utils/utils.cpp

With old architecture, the drivable_lanes is empty for some reason.
We do not have to consider drivable_lanes with old architecture, so I commented out.
Planning simulator worked well locally.
Ran scenario test.
https://evaluation.tier4.jp/evaluation/reports/82f6a97b-f2fc-5a7c-aa51-0be7518eb5f3?project_id=prd_jt …

fix(behavior_path_planner): deal with empty drivable_lanes with old archi

---

planning/behavior_path_planner/src/planner_manager.cpp

When one of the module in approved modules stack is back to WAITING APPROVAL, the subsequent approved modules should be removed.
In current implementation, the subsequent modules is just removed from approved modules stack and is **NOT** unregisterd from its manager.
In this PR, it do not only erase waiting approved module from `approved_modules_ptrs_` but also unregister the subsequet modules from its manager.
```c++
std::for_each(
std::next(itr), approved_module_ptrs_.end(), [this](auto & m) { deleteExpiredModules(m); });
```
](https://evaluation.tier4.jp/evaluation/reports/6ca23166-cc0d-5e22-b46c-08ecf3c70713?project_id=prd_jt)
Improve simultaneous execution on new manager. …

fix(planner_manager): delete subsequent approved modules

---

planning/behavior_velocity_planner/include/scene_module/intersection/util.hpp
planning/behavior_velocity_planner/src/scene_module/intersection/scene_intersection.cpp
planning/behavior_velocity_planner/src/scene_module/intersection/scene_merge_from_private_road.cpp
planning/behavior_velocity_planner/src/scene_module/intersection/util.cpp

In some cases detection area contains ego_lane and the previous lanes. So lanelets on path should be explicitly removed  from detection area.
There are two intersection lanelets around the goal, so the detection area is generated on the path, which is not reasonable.
detection area is not generated on the lanelets on path.
For other topologies shown below, detection area is valid as before.
Merging into straight lanes
Right turn with traffic light
Left turn with traffic light …

feat(intersection): remove lanelets on path from detection area

---

planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp

This can be used by using new behavior_path_planner architecture and enabling dynamic_avoidance module.
Added a marker of objects to avoid in dynamic_avoidance module (pink rectangular)
Can visualize dynamic objects to avoid

feat(behavior_path_planner): add dynamic avoidance debug marker

---

planning/obstacle_stop_planner/README.md
planning/obstacle_stop_planner/config/obstacle_stop_planner.param.yaml
planning/obstacle_stop_planner/include/obstacle_stop_planner/node.hpp
planning/obstacle_stop_planner/include/obstacle_stop_planner/planner_data.hpp
planning/obstacle_stop_planner/include/obstacle_stop_planner/planner_utils.hpp
planning/obstacle_stop_planner/src/node.cpp
planning/obstacle_stop_planner/src/planner_utils.cpp

Note: https://github.com/autowarefoundation/autoware.universe/pull/3556
This should be merged before this PR.
Because there are a lot of predicted objects in real environment, we need to filter it before collision and slowdown checking. It is filtering with respect to following rules.
* Ignore object if it is not front of vehicle
* Ignore object if it's longitudinal distance is far away from trajectory's last point
* Ignore object if lateral distance is high
PR for launch file: https://github.com/autowarefoundation/autoware_launch/pull/330
Tested in planning simulator:
As you can see, it ignores high lateral distance objects.
There is no behavior change, it only increases node performance by using filtering.
The PR …

feat(obstacle_stop_planner): add filtering feature for predicted objects

---

planning/behavior_path_planner/config/avoidance/avoidance.param.yaml
planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/avoidance_module_data.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
planning/behavior_path_planner/src/scene_module/avoidance/manager.cpp
planning/behavior_path_planner/src/scene_module/lane_change/avoidance_by_lane_change.cpp

- rename `avoidance_execution_lateral_threshold` -> `lateral_execution_threshold`.
- remove `lateral_passable_safety_buffer` and use each objects' `safety_buffer_lateral` instead.
- This PR must be merged after https://github.com/autowarefoundation/autoware_launch/pull/340.
The `lateral_passable_safety_buffer`  is a param that used for judgement whether ego should avoid, and all objects (car, pedestrian, motorcycle...) used the same value. On the other hand, I already added `safety_buffer_lateral`  for each classes in https://github.com/autowarefoundation/autoware.universe/pull/3002 and I want to use it instead of `lateral_passable_safety_buffer`  so that we can set the param independently.
NOTE: This PR doesn't depend on the difference between architecuture.
Nothing. (Just refactoring.) …

refactor(avoidance): remove redundant parameters

---

planning/obstacle_stop_planner/include/obstacle_stop_planner/planner_data.hpp
planning/obstacle_stop_planner/include/obstacle_stop_planner/planner_utils.hpp
planning/obstacle_stop_planner/src/adaptive_cruise_control.cpp
planning/obstacle_stop_planner/src/node.cpp
planning/obstacle_stop_planner/src/planner_utils.cpp

In obstacle_stop_planner, I removed the unused function and variables. Also in some parts, pushPolygon function is called unnecessarily. Also to increase code efficiency, some changes made.
This should be merged after following PRs merged.
https://github.com/autowarefoundation/autoware.universe/pull/3556
https://github.com/autowarefoundation/autoware.universe/pull/3558
Tested in planning simulator and worked well. …

refactor(obstacle_stop_planner): remove unnecessary variables and functions, improve code performance

---

launch/tier4_perception_launch/launch/traffic_light_recognition/traffic_light.launch.xml
launch/tier4_perception_launch/launch/traffic_light_recognition/traffic_light_node_container.launch.py
perception/traffic_light_ssd_fine_detector/CMakeLists.txt
perception/traffic_light_ssd_fine_detector/README.md
perception/traffic_light_ssd_fine_detector/include/traffic_light_ssd_fine_detector/nodelet.hpp
perception/traffic_light_ssd_fine_detector/launch/traffic_light_ssd_fine_detector.launch.xml
perception/traffic_light_ssd_fine_detector/lib/include/cuda_utils.hpp
perception/traffic_light_ssd_fine_detector/lib/include/gather_topk.hpp
perception/traffic_light_ssd_fine_detector/lib/include/gather_topk_kernel.hpp
perception/traffic_light_ssd_fine_detector/lib/include/grid_priors.hpp
perception/traffic_light_ssd_fine_detector/lib/include/grid_priors_kernel.hpp
perception/traffic_light_ssd_fine_detector/lib/include/trt_plugin_helper.hpp
perception/traffic_light_ssd_fine_detector/lib/include/trt_serialize.hpp
perception/traffic_light_ssd_fine_detector/lib/include/trt_ssd.hpp
perception/traffic_light_ssd_fine_detector/lib/src/plugins/gather_topk.cpp
perception/traffic_light_ssd_fine_detector/lib/src/plugins/gather_topk_kernel.cu
perception/traffic_light_ssd_fine_detector/lib/src/plugins/grid_priors.cpp
perception/traffic_light_ssd_fine_detector/lib/src/plugins/grid_priors_kernel.cu
perception/traffic_light_ssd_fine_detector/lib/src/trt_ssd.cpp
perception/traffic_light_ssd_fine_detector/src/nodelet.cpp

Add support of applying SSD trained by [open-mmlab/mmdetection](https://github.com/open-mmlab/mmdetection) to Autoware.
- Add support of output is no particular order.
- ~~Get binding dimensions with the flag named `is_box_first`.~~
- Detcides DNN output order (boxes, scores order or not) and operation (re-scalle with image size) by specifing DNN toolbox name pytorch or mmdetection
- Add TensorRT custom plugins defined in [open-mmlab/mmdeploy](https://github.com/open-mmlab/mmdeploy).
- GatherTopK
- GridPriors
I confirmed that both before and after PR got same score with current default model in [tier4/driving_log_replayer](https://github.com/tier4/driving_log_replayer).
- Before PR
```
[traffic_light_evaluator_node.py-68] Frame:
[traffic_light_evaluator_node.py-68]  Total Num: 6 …
```

feat(traffic_light_ssd_fine_detector): add support of ssd trained by mmdetection

---

planning/motion_velocity_smoother/src/smoother/jerk_filtered_smoother.cpp

suppress `[motion_velocity_smoother-26] [WARN 1683770836.671243586] [smoother.jerk_filtered_smoother]: osqp polish process failed : unsuccessful. The result may be inaccurate (apply():332)`
planning simualtor

feat(motion_velocity_smoother): suppress warning

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

- set waiting approval in `onProcessEntry()`.
- don't clear waiting approval if there is unavoidable objects even when no shift line is generated.
Nothing.

fix(avoidance): clear waiting approval only when all target module are unavoidable

---

planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp

In goal_planner_module, when planner->plan() failes and it returns a null object, the invalid access for ```pull_over_path``` causes with the next line. 
```
auto pull_over_path = planner->plan(goal_candidate.goal_pose);
pull_over_path->goal_id = goal_candidate.id;
```
This issue can be easily reproduced by moving the vehicle near the goal after setting the goal in the planning simulator.
I fixed it 
I confirmed that the issue no longer reproduces.
None
None …

fix(behavior_path_planner): fix invalid access in goal_planner module

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_interface.hpp
planning/behavior_path_planner/src/scene_module/lane_following/lane_following_module.cpp
planning/behavior_path_planner/src/scene_module/side_shift/manager.cpp
planning/behavior_path_planner/src/scene_module/side_shift/side_shift_module.cpp

return FALSE when the uuid is not found.
```c++
bool isActivated()
{
for (auto itr = rtc_interface_ptr_map_.begin(); itr != rtc_interface_ptr_map_.end(); ++itr) {
if (itr->second->isRegistered(uuid_map_.at(itr->first))) {
return itr->second->isActivated(uuid_map_.at(itr->first));
} else {
return false;
}
}
return true;
}
```
Psim
https://github.com/autowarefoundation/autoware.universe/assets/44889564/517ae0af-e813-4140-b5f2-6111fb680d7d …

fix(behavior_path_planner): return FALSE when the uuid is not found

---

control/pid_longitudinal_controller/README.md

Update readme for the usage of the slope compensation
None
None

docs(longitudinal_controller): add notation for slope compensation usage

---

planning/behavior_velocity_planner/include/scene_module/intersection/scene_intersection.hpp
planning/behavior_velocity_planner/src/scene_module/intersection/debug.cpp
planning/behavior_velocity_planner/src/scene_module/intersection/manager.cpp
planning/behavior_velocity_planner/src/scene_module/intersection/scene_intersection.cpp

The temporal stop at the default stopline when occlusion is detected can be activated/deactivated by the RTC with this PR.
To simplify the logic, I removed the uuid for this temporal stop.
If both intersection/intersection_occlusion is set to manual mode, there will be two intersection walls. One is "intersection" and the other is "intersection_occlusion". The "intersection" wall will disappear when deactivated.
https://github.com/autowarefoundation/autoware.universe/assets/28677420/a024ea7d-3f3c-4abe-aed0-bb49547b9b0e
intersection_occlusion works as before.
https://github.com/autowarefoundation/autoware.universe/assets/28677420/0cf4d071-06db-47e7-bd40-78fab6f1c233
The temporal "intersection" wall will disappear when deactivated. …

feat(intersection): switch default/occlusion_first_stop when occlusion appeared/disappeared or approved/disapproved

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/base_class.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/interface.hpp
planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp
planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp

Lane change safety check supposedly still working despite `enable_cancel_lane_change` is `false`, but currently it is not working.
[TIER IV internal link](https://star4.slack.com/archives/CEV8XMJBV/p1683871399526129?thread_ts=1683848999.981809&cid=CEV8XMJBV)
1. set `enable_cancel_lane_change: false`
2. run planning simulator
3. set RTC approval to manual
4. place an dangerous object
5. observe that candidate path is red.
When using planning simulator, it is still possible to approve the unsafe lane change path.
None
None …

fix(lane_change): safety check not working when cancel disabled

---

perception/bytetrack/include/bytetrack/bytetrack_node.hpp
perception/bytetrack/src/bytetrack_visualizer_node.cpp
perception/image_projection_based_fusion/src/debugger.cpp
perception/tensorrt_yolo/include/tensorrt_yolo/nodelet.hpp
perception/tensorrt_yolox/include/tensorrt_yolox/tensorrt_yolox_node.hpp
perception/traffic_light_classifier/include/traffic_light_classifier/cnn_classifier.hpp
perception/traffic_light_classifier/include/traffic_light_classifier/color_classifier.hpp
perception/traffic_light_classifier/include/traffic_light_classifier/nodelet.hpp
perception/traffic_light_map_based_detector/include/traffic_light_map_based_detector/node.hpp
perception/traffic_light_ssd_fine_detector/include/traffic_light_ssd_fine_detector/nodelet.hpp
perception/traffic_light_visualization/include/traffic_light_roi_visualizer/nodelet.hpp
planning/behavior_velocity_planner/src/scene_module/intersection/scene_intersection.cpp
sensing/image_diagnostics/include/image_diagnostics/image_diagnostics_node.hpp
sensing/image_transport_decompressor/src/image_transport_decompressor.cpp
sensing/pointcloud_preprocessor/include/pointcloud_preprocessor/blockage_diag/blockage_diag_nodelet.hpp
sensing/pointcloud_preprocessor/include/pointcloud_preprocessor/outlier_filter/dual_return_outlier_filter_nodelet.hpp

.h header in image common is deprecated at iron.
I added workaround to avoid deprecated warning when building on iron.

build(iron): add workaround for image common header

---

common/tier4_planning_rviz_plugin/include/path/display.hpp

In some cases, the drivable area's width is not constant as follows.

fix(tier4_planning_rviz_plugin): fix drivable area width

---

planning/obstacle_avoidance_planner/src/mpt_optimizer.cpp

The logic to modify the optimization constraint in the case where the drivable area's width is smaller than the vehicle's width (e.g. dynamic obstacle is extracted from the drivable area) is wrong.
Optimization will become easier to be solved in the case where the drivable area's width is smaller than the vehicle's width (e.g. dynamic obstacle is extracted from the drivable area) …

fix(obstacle_avoidance_planner): fix optimization constraint for narrow-road driving

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
planning/behavior_path_planner/src/utils/avoidance/utils.cpp
planning/route_handler/include/route_handler/route_handler.hpp

Currently, avoidance module checks the distance between the object and closest lanelet's most left (or right) linestring.
However, the `distance2d` function returns unexpected value for avoidance module in the following case.
It is better to check not only closest lanelet's most left linestring but also next & previous linestring so that `distance2d` function return exact distance between the object and road shoulder.
Improve avoidance path generation. …

feat(avoidance): check next & previous road shoulder linestring

---

planning/behavior_path_planner/CMakeLists.txt
planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/interface.hpp
planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp

In new architecture, when `current_state_` returns `ModuleStatus::FAILURE`, planner manager delete the module, and it caused lane change candidate path to be removed each time path is unsafe.
This PR aims to improve the state in when using planner_manager. 
[TIER IV internal link](https://star4.slack.com/archives/CEV8XMJBV/p1683871399526129?thread_ts=1683848999.981809&cid=CEV8XMJBV)
Compile with `USE_OLD_ARCHITECTURE FALSE`.
Then test lane change cancel scenario.
https://github.com/autowarefoundation/autoware.universe/assets/93502286/5c06c5eb-6e2e-4a1a-a2bc-9d454bcb2811
Behavior Tree's updateState is separated for now.
None
None
The PR author …

fix(lane_change): not remove unsafe candidate in new architecture

---

planning/surround_obstacle_checker/src/node.cpp

skip pcd transform when pcd is empty in surround_obstacle_checker.
This PR solves the annoying warning in psim.
run psim.

chore(surround_obstacle_checker): skip pcd transform when pcd is empty

---

planning/behavior_path_planner/src/utils/utils.cpp

Before this change, `isEgoOutOfRoute()` does not work properly if the route is overlapped.
In this change, it checks the direction of the ego and goal lane.
Nothing.
Nothing.

fix(behavior_path_planner): handle overlap lane in isEgoOutOfRoute()

---

planning/behavior_path_planner/src/utils/utils.cpp

In the following case, the boundary's nearest index search is calculated wrong.
I fixed this issue by calculating the minimum distance from each segment on bound and the target point (ego pose in this case).
This issue happens when avoiding objects with the motion planner by extracting objects from the drivable area.
No change behavior …

fix(behavior_path_planner): boundary's nearest search

---

planning/behavior_path_planner/src/utils/utils.cpp

Backward obstacle extraction from the drivable area is wrong in a case with a specific map.
with this PR

fix(behavior_path_planner): extract backward obstacles correctly

---

control/pid_longitudinal_controller/src/pid_longitudinal_controller.cpp

In the current implementation of `pid_longitudinal_controller`, if the operation mode is changed, the state will be the same. In this situation, if the goal is set, controller enters into `DRIVE` state until the vehicle reaches the goal. However, if the operation mode is changed while driving and set autonomous again, controller state stays in `DRIVE` and the controller does not check the `keep_stopped_condition`. So vehicle starts to driving without checking steering converged or not.
Tested in planning simulator, worked well. …

refactor(pid_longitudinal_controller): set stopped state if ego is not in autonomous mode

---

planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp

With this PR, in the case as follows, the ego does not avoid the obstacle since TTC (time to collision) is negative.
Unnecessary dynamic obstacles are not extracted from the drivable area considering TTC.

feat(dynamic_avoidance): consider TTC for predicted path extraction from drivable area

---

planning/behavior_path_planner/test/test_behavior_path_planner_node_interface.cpp
planning/behavior_velocity_planner/test/src/test_behavior_velocity_planner_node_interface.cpp
planning/freespace_planner/test/test_freespace_planner_node_interface.cpp
planning/obstacle_avoidance_planner/test/test_obstacle_avoidance_planner_node_interface.cpp
planning/obstacle_cruise_planner/test/test_obstacle_cruise_planner_node_interface.cpp
planning/obstacle_stop_planner/test/test_obstacle_stop_planner_node_interface.cpp
planning/planning_test_utils/include/planning_interface_test_manager/planning_interface_test_manager.hpp
planning/planning_test_utils/include/planning_interface_test_manager/planning_interface_test_manager_utils.hpp

since ASSERT_NO_THROW in gtest masks the exception message, I redefine it with error message.
Before
```
3: /home/horibe/workspace/pilot-auto.latest/src/autoware/universe/planning/behavior_velocity_planner/test/src/test_behavior_velocity_planner_node_interface.cpp:169: Failure
3: Expected: test_manager->testOffTrackFromPathWithLaneId(test_target_node) doesn't throw an exception.
3: Actual: it throws. 
```
After
```
3: /home/horibe/workspace/pilot-auto.latest/src/autoware/universe/planning/behavior_velocity_planner/test/src/test_behavior_velocity_planner_node_interface.cpp:153: Failure
3: Failed
3: Expected: test_manager->testOffTrackFromPathWithLaneId(test_target_node) doesn't throw an exception.
3: Actual: it throws. Error message: Topic name for N8nav_msgs3msg9Odometry_ISaIvEEE is empty …
```

test(planning_test_utils): add ASSART_NO_THROW_WITH_ERROR_MSG macro

---

planning/behavior_path_planner/src/utils/geometric_parallel_parking/geometric_parallel_parking.cpp

Fix for the process die due to the empty path.
run psim
None

fix(geometric_parallel_parking): add check for empty path

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/base_class.hpp
planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp
planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp

Since there are multiple lane change type, it might be difficult to debug if the logger didn't specifically mention which module is running.
Therefore, the PR aims to add module type to the logger.
Test abort scenario with PSIM.
Ensure that the logger show's the module's type. …

refactor(lane_change): adding module's type to logger

---

planning/behavior_path_planner/include/behavior_path_planner/utils/utils.hpp
planning/behavior_path_planner/src/utils/utils.cpp

Introducing following PR, the error message `there are no lanelets close enough!` is shown in console many times.
https://github.com/autowarefoundation/autoware.universe/pull/3715
To fix it, I add `isInLaneletWithYawThreshold()` into `behavior_path_planner`.
Tested in planning_simulator.
Nothing.
Nothing. …

fix(behavior_path_planner): add isInLaneletWithYawThreshold()

---

control/vehicle_cmd_gate/launch/vehicle_cmd_gate.launch.xml
control/vehicle_cmd_gate/src/vehicle_cmd_gate.cpp
control/vehicle_cmd_gate/src/vehicle_cmd_gate.hpp
launch/tier4_control_launch/launch/control.launch.py

This reverts commit be3138545d6814a684a314a7dbf1ffb450f90970.
Signed-off-by: Berkay Karaman <brkay54@gmail.com>
For the issue: https://github.com/autowarefoundation/autoware.universe/issues/2052 I made some changes in the PR (https://github.com/autowarefoundation/autoware.universe/pull/2555). However, it causes the issue: https://github.com/autowarefoundation/autoware.universe/issues/3526
To close the issue, I will make the changes in the `shift_decider` PR link: https://github.com/autowarefoundation/autoware.universe/pull/3684
So I want to revert these changes.
Tested in planning_simulator, and worked well. …

feat(vehicle_cmd_gate):  do not send current gear if autoware is not engaged

---

control/shift_decider/include/shift_decider/shift_decider.hpp
control/shift_decider/src/shift_decider.cpp
launch/tier4_control_launch/launch/control.launch.py

Closes: https://github.com/autowarefoundation/autoware.universe/issues/3526
Related PR: https://github.com/autowarefoundation/autoware.universe/pull/3683

feat(shift_decider): send current gear if the autoware state is not driving

---

planning/behavior_path_planner/src/planner_manager.cpp

```
[component_container_mt-27] [INFO] [1684297570.183024344] [planning.scenario_planning.lane_driving.behavior_planning.behavior_path_planner.planner_manager]: 
[component_container_mt-27] ***********************************************************
[component_container_mt-27]                   planner manager status              
[component_container_mt-27] -----------------------------------------------------------
[component_container_mt-27] registered modules: [pull_out][goal_planner][side_shift][lane_change_left][lane_change_right][avoidance][avoidance_by_lane_change]
[component_container_mt-27] approved modules  : [avoidance(RUNNING)]->[lane_change_right(RUNNING)]->
[component_container_mt-27] candidate module  : …
```

feat(planner_manager): output module status

---

perception/compare_map_segmentation/README.md
perception/compare_map_segmentation/include/compare_map_segmentation/voxel_grid_map_loader.hpp
perception/compare_map_segmentation/src/voxel_grid_map_loader.cpp

This PR to fix pointcloud_container died bug when [use_dynamic_map_loading = True](https://github.com/autowarefoundation/autoware_launch/blob/a26a82134e041c22ea32a4077e85a6219c3a8257/autoware_launch/config/perception/object_recognition/detection/pointcloud_map_filter.param.yaml#L16) but no-split map is used.
[TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT1-2391)
[TIER IV INTERNAL LINK 2](https://star4.slack.com/archives/C03S84LDJGG/p1684237947381389)
Confirmed by logging_simulator. …

fix(compare_map_segmentation): fix bug when set dynamic map loader for no split map

---

system/system_error_monitor/src/system_error_monitor_core.cpp

- Fix time type in the contractor to fix the following error message:
```
[system_error_monitor-16] [ERROR 1684318632.789706285] [system.system_error_monitor] operator()(): clock type is different...:(L421)
```
- Change log level from warn to info for the first time when the diag is not received.  …

fix(system_error_monitor): time type mismatch error

---

planning/behavior_path_planner/config/lane_change/lane_change.param.yaml
planning/behavior_path_planner/docs/behavior_path_planner_lane_change_design.md
planning/behavior_path_planner/include/behavior_path_planner/parameters.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/lane_change_module_data.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/utils.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/utils.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
planning/behavior_path_planner/src/utils/lane_change/utils.cpp
planning/behavior_path_planner/src/utils/utils.cpp
planning/behavior_path_planner/test/test_lane_change_utils.cpp

Currently, lane change can only use a single lateral acceleration value to calculate the length of lane change length. However, we can handle many more scenarios by extending the lateral acceleration values, we add a lateral acceleration map for the lane change module. This enables the lane change module to dynamically change its lateral acceleration depending on ego vehicle velocity.
[Launch PR](https://github.com/autowarefoundation/autoware_launch/pull/352)
Unit Tests
Scenario Test 1301/1350
[TIER IV Internal Link](https://evaluation.tier4.jp/evaluation/reports/53a42baf-34ac-5ed1-b30f-d4e930486989?project_id=prd_jt)
There is no interface change caused by this PR.
Lateral acceleration of the lane change module will be changed based on the situation. For example, if the lane change module …

feat(lane_change): add dynamic lateral acc lc

---

planning/planning_debug_tools/scripts/trajectory_visualizer.py

In trajectory_visualizer, the y lim is calculated from the min/max of behavior_velocity_planner.
If the path is long, the behavior_path_planner's output (which is cut 200[m] by default for plotting) does not contain lower velocity which is contained in motion_velocity_planner's output.
In this PR, min y lim is calculated from not behavior_path_planner's output but motion_velocity_smoother's output.
with this PR
NO behavior change …

fix(planning_debug_tools): fix y lim of trajectory_visualizer

---

planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp

Since previous module's drivable area info is not passed to next module, the planner manager doesn't crop drivable area bounds correctry.
Psim
Fix drivable area generation bug.

fix(lane_change): copy drivable area info

---

planning/behavior_path_planner/src/utils/utils.cpp

In the scenario where dynamic avoidance and avoidance are launching, without this PR, the following obstacle's extraction from the drivable area is ignored since there is no intersection between the obstacle and the bound.
Dynamic avoidance can be used with avoidance/lane change module.
There seems to be some corner cases though. …

fix(behavior_path_planner): extract obstacles from drivable area without intersection

---

planning/behavior_path_planner/src/utils/utils.cpp

In ```generateDrivableArea``` function, the invalid access for a left/right bound occurs at ```findNearestSegmentIndexFromLateralDistance``` when left_bound or right_bound is empty.
I fixed it 
(TIERIV Internal Link: [Scenario](https://evaluation.tier4.jp/evaluation/reports/79acc1ed-151a-5237-9b4b-d31132d41f18/tests/f1f4939f-a33f-5cd9-a6b7-57e03fdc7258/fdcee682-aad0-5bd4-8bf1-616587b96f8c/91396479-ccb3-59f6-9e0a-6d5a31613117?project_id=prd_jt) )
I confirmed that the behavior_path_planner becomes not to die when the above rosbag played.
no
no
The behavior_path_planner becomes not to die when the bounds of drivable area are empty.
The PR author …

fix(behavior_path_planner): fix invalid access for null drivable area bound

---

planning/behavior_path_planner/src/utils/lane_change/utils.cpp

With new behavior path planner architecture, the vehicle does not accelerate after lane change if the goal is near.
To fix this problem, I remove setting maximum velocity after lane change.
Before:
https://github.com/autowarefoundation/autoware.universe/assets/10190493/589f66b9-89e1-4201-b12b-975def66d72d
After:
https://github.com/autowarefoundation/autoware.universe/assets/10190493/9971286a-543c-4d69-9661-fab93d8347d6
Nothing.
Nothing. …

fix(behavior_path_planner): remove setting maximum velocity after lane change

---

perception/lidar_centerpoint/launch/centerpoint_vs_centerpoint-tiny/README.md

- Link in `lidar_centerpoint` is determined to be broken. So I want to change link path.
- I uploaded this image file to github, and I got the link below; https://github.com/autowarefoundation/autoware.universe/assets/58775300/2a89063a-8e0e-4f59-8d48-f339d4f7c0ff
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull- …

docs(lidar_centerpoint): fix path of image

---

planning/obstacle_stop_planner/src/planner_utils.cpp

In obstacle_stop_planner, extendTrajectory function causes Nan positions so it causes issue: https://github.com/autowarefoundation/autoware.universe/issues/3666
Closes: https://github.com/autowarefoundation/autoware.universe/issues/3666
Tested in planning_simulator and it solves the issue.
Nothing. …

fix(obstacle_stop_planner): extendTrajectory function causes NaN poses

---

planning/behavior_velocity_planner/config/intersection.param.yaml
planning/behavior_velocity_planner/include/scene_module/intersection/scene_intersection.hpp
planning/behavior_velocity_planner/src/scene_module/intersection/manager.cpp
planning/behavior_velocity_planner/src/scene_module/intersection/scene_intersection.cpp

Apply morphology opening process to remove small occlusion from the occupancy grid.
parameter PR: https://github.com/autowarefoundation/autoware_launch/pull/361
kernel size = 1.0m
kernel size = 3.0m:
with this PR and kernel_size = 2.5m, noisey occlusion does not appear. …

feat(intersection): denoise occlusion by morphology open process

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_interface.hpp

The initial state shoulder be `IDLE` in the new architecture but it is`SUCCESS` before `onEntry().
psim
not applicable
not applicable

fix(behavior_path_planner): fix initial scene module state for new architecture

---

planning/obstacle_cruise_planner/config/obstacle_cruise_planner.param.yaml
planning/obstacle_cruise_planner/include/obstacle_cruise_planner/node.hpp
planning/obstacle_cruise_planner/src/node.cpp

We set the detection area to select slow down obstacles.
When the obstacle is on the longitudinal edge of the detection area with some noises, the slow down decision flickers.
To avoid this, this PR uses hysteresis condition to check if the object is inside the detection area or not.
No flickering of slow down obstacle decision. …

feat(obstacle_cruise_planner): hysteresis for slow down decision

---

planning/obstacle_cruise_planner/config/obstacle_cruise_planner.param.yaml
planning/obstacle_cruise_planner/include/obstacle_cruise_planner/planner_interface.hpp
planning/obstacle_cruise_planner/src/planner_interface.cpp

add time margin before slow down.
slow down is applied a bit faster against close obstacles.

feat(obstacle_cruise_planner): add margin time for slow down

---

planning/behavior_path_planner/config/lane_change/lane_change.param.yaml
planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/base_class.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/normal.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/utils.hpp
planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
planning/behavior_path_planner/src/utils/lane_change/utils.cpp

Currently, the lane change module cannot accelerate while it performs lane change even when the ego vehicle is on the prepare segment. In this PR, I add several functions that enable it to accelerate the ego vehicle when `current_velocity` is lower than the current position `maximum_velocity`. 
Here is the new video (After the PR)
[Screencast from 2023年05月18日 15時26分59秒.webm](https://github.com/autowarefoundation/autoware.universe/assets/43805014/ccff0101-71ab-40e7-a93d-aab8ec4f6b17)
Before this PR
[Screencast from 2023年05月18日 15時39分10秒.webm](https://github.com/autowarefoundation/autoware.universe/assets/43805014/0bff326c-74a4-4e41-8b30-07cc9970d810)
[Launch PR](https://github.com/autowarefoundation/autoware_launch/pull/358)
PSim
Scenario Test 1310/1372
[TEIR IV Internal …

feat(lane_change): enable prepare segment acceleration

---

planning/behavior_path_planner/config/avoidance/avoidance.param.yaml
planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/avoidance_module_data.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/utils/avoidance/utils.cpp

- ignore objects around crosswalk in avoidance module. (now, ignore only objects that are stopping for traffic light.)
- https://github.com/autowarefoundation/autoware_launch/pull/362
Psim
Nothing.

feat(avoidance): don't avoid objects around crosswalks

---

planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/utils/trajectory_utils.hpp
planning/obstacle_avoidance_planner/src/node.cpp

The trajectory optimization is applied to the first 100 meters.
The optimized trajectory's end point and the input path are connected smoothly by spline interpolation with the joint length = 5 meters.
In some cases, 5 meters is too short and the jointed trajectory's curvature is high, resulting in slow down by motion_velocity_smoother.
This PR changes the method of the connection.
No change behvavior.
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/m …

fix(obstacle_avoidance_planner): smooth path connection after optimization

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
planning/behavior_path_planner/src/utils/avoidance/utils.cpp

The avoidance module has the parameter `lateral_execution_threshold`, and it never throws RTC request for shift lines that are less than this threshold.
On the other hand, the module doesn't ignore object whose shift line is smaller than threshold and keeps stopping in front of it until the RTC request is approved. It is inconsistent and causes stuck.
In this PR, the module ignore objects whose shift length is less than `avoidance_execution_lateral_threshold` explicitly.
Nothing. …

fix(avoidance): ignore objects less than execution threshold

---

planning/behavior_path_planner/include/behavior_path_planner/utils/path_shifter/path_shifter.hpp
planning/behavior_path_planner/src/utils/path_shifter/path_shifter.cpp

Before this PR, the path shifter can only handle the situation where the ego vehicle travels at a constant speed. This makes it difficult to generate a path when the ego vehicle travels at a constant acceleration. In this PR, I extended the path shifter to enable it to generate a path even when the ego vehicle travels at a constant positive acceleration. Note that we only consider positive acceleration in this PR.
Scenario Test 1311/1372
[TIER IV Internal Link](https://evaluation.tier4.jp/evaluation/reports/ea85360b-0756-59ba-af48-93cf5d991dc2?project_id=prd_jt)
After …

feat(behavior_path_planner): add longitudinal acc to path shifter

---

common/motion_utils/src/distance/distance.cpp
common/motion_utils/test/src/distance/test_distance.cpp

- Fixed the logic to calculate deceleration distance with jerk/acc constraints
- Variable names are hard to understand. Changed to the names which are easy to understand the meaning.
Almost no behavior change

fix(motion_utils): fix logic to calculate decel distantace

---

planning/obstacle_cruise_planner/config/obstacle_cruise_planner.param.yaml
planning/obstacle_cruise_planner/include/obstacle_cruise_planner/planner_interface.hpp
planning/obstacle_cruise_planner/src/planner_interface.cpp

Regarding the slow down feature against close obstacles, the slow down point is calculated only considering the initial velocity and acceleration constraint.
In this PR, the initial acceleration and jerk constraints are considered as well to calculate a precise slow down point.
Also min_acceleration in common.param.yaml is used for this calculation instead of having a parameter in the obstacle_cruise_planner package.
No large deceleration by the slow down feature
[contribution …

fix(obstacle_cruise_planner): insert slow down with precise constraints

---

common/signal_processing/include/signal_processing/lowpass_filter_1d.hpp
common/signal_processing/src/lowpass_filter_1d.cpp

Add a function of low-pass filter.
With this, no need to create an instance for low-pass filter in the application side.
unit test

feat(signal_processing): add a function of low-pass filter

---

planning/obstacle_cruise_planner/config/obstacle_cruise_planner.param.yaml
planning/obstacle_cruise_planner/include/obstacle_cruise_planner/planner_interface.hpp
planning/obstacle_cruise_planner/src/node.cpp
planning/obstacle_cruise_planner/src/planner_interface.cpp

- added a lower-pass filter for
- lateral distance from obstacle to the path
- slow down start distance
- slow down velocity
- calculate slow down velocity from the distance constraints using behavior_velocity_planner's util function.
- without this PR: https://evaluation.tier4.jp/evaluation/reports/fc75b567-170a-5d09-8e6a-26088cf2ff8f?project_id=prd_jt (1692/1722 pass)
- with this PR: https://evaluation.tier4.jp/evaluation/reports/534ac908-f7c4-52d6-ab98-bb2813475ddc?project_id=prd_jt (1697/1722 pass)
Stabler slow down planning against close obstacles. …

feat(obstacle_cruise_planner): stabler slow down

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/dynamic_avoidance/dynamic_avoidance_module.hpp
planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp

The implementation of filtering obstacles for dynamic avoidance by their label is missing.

fix(dynamic_avoidance): ignore obstacles with non target label

---

planning/behavior_path_planner/src/utils/utils.cpp

Remove lane change specific code. This PR make it possible to get crosswalk distance correctry even if there is lane chagne tag.
```
webauto ci scenario run --project-id prd_jt --scenario-id 1e21c061-5169-4000-b487-23b9abdfc01d --runtime-path /$HOME/pilot-auto --scenario-parameters __tier4_modifier_ego_speed=8.3333
```
https://github.com/autowarefoundation/autoware.universe/assets/44889564/7570d45b-aa8d-456e-9706-8ba137e2f089
Don't avoid objects around crosswalk. …

fix(utils): remove lane chagne specific code

---

perception/map_based_prediction/config/map_based_prediction.param.yaml
perception/map_based_prediction/include/map_based_prediction/map_based_prediction_node.hpp
perception/map_based_prediction/src/map_based_prediction_node.cpp

Revert the old logic of the lane change detection deleted by the following PR
https://github.com/autowarefoundation/autoware.universe/pull/2822
Lane change detection's behavior in prediction may change a bit.

feat(map_based_prediction): revert old logic

---

planning/planning_debug_tools/Readme.md
planning/planning_debug_tools/scripts/perception_reproducer.py

- Perception reproducer can publish detected/tracked objects instead of predicted objects
- Add a document about how to use the script.
Just a change to the tool.

feat(perception_reproducer): deal with detected/tracked objects

---

control/control_performance_analysis/config/control_performance_analysis.param.yaml
control/control_performance_analysis/include/control_performance_analysis/control_performance_analysis_core.hpp
control/control_performance_analysis/include/control_performance_analysis/control_performance_analysis_node.hpp
control/control_performance_analysis/include/control_performance_analysis/control_performance_analysis_utils.hpp
control/control_performance_analysis/package.xml
control/control_performance_analysis/scripts/control_performance_plot.py
control/control_performance_analysis/src/control_performance_analysis_core.cpp
control/control_performance_analysis/src/control_performance_analysis_node.cpp
control/control_performance_analysis/src/control_performance_analysis_utils.cpp

The `control_performance_analysis` stops calculation when the ego vehicle is located far from the trajectory. It is ok, but the calculation will never restart after the vehicle comes back to the trajectory. It is due to the closest_idx calculation handling.
This PR refactors the code structure to fix the above issue.
Also, this PR includes some refactors, mainly replacing the duplicated implementation with util packages (motion_utils, autoware_utils, etc.) and adds python script to plot the tracking error.
Run psim and check the performance check …

refactor(control_performance_analysis): refactor structure

---

planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp

when setting `left_side_parking_` and the fixed goal is put in the right lane of the current lanes, goal_planner is executed. This blocks other modules to run in the old behavior_path_planner architecture.
e.g.) right LC can not be executed when putting the fixed goal right of current lanes, and the goal is close to the ego-vehicle.
https://github.com/autowarefoundation/autoware.universe/assets/39142679/333c1b85-dfa6-4815-85ba-0f906fe1eef2
and this PR also fix the problem lane change can not be done when approved at the path terminal.
[tier4 internal ticket](https://tier4.atlassian.net/browse/RT1-2382)
[tier4 internal ticket](https://tier4.atlassian.net/browse/RT1-2382)
psim
not applicable
not applicable
The PR …

fix(behavior_path_planner): do not execute goal_planner when the fixed goal is not in current lanes

---

planning/route_handler/include/route_handler/route_handler.hpp
planning/route_handler/src/route_handler.cpp

Add a function to check if the given lanelet is in the preferred lanelets. 

feat(route_handler): add isPreferredLane function

---

planning/behavior_path_planner/CMakeLists.txt
planning/behavior_path_planner/src/utils/lane_change/utils.cpp

When the lane change target length is shorter than forward paths, the resultant lane change path will be extended until the end of the target lane, as following image.
This is not expected behavior.
The expected behavior is some buffer is available to allow ego vehicle to return to the original lane properly.
After this PR
[TIER IV internal link](https://tier4.atlassian.net/jira/software/c/projects/RT0/boards/438?modal=detail&selectedIssue=RT1-2378&quickFilter=772)
1. Enable external lane change module.
2. Set lane change goal at the start of intersection lanelet.
None
None
None
After …

fix(lane_change): fix external lane change target lane lengths

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module.hpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

The avoidance module clears RTC status when it reverts avoidance path in yield situation. But it seems not to be cleared correctly in current implementation and invalid shift line is remaining.
Improve RTC operation.

fix(avoidance): reset rtc status in yield status

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp
planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp

when the parking space is occupied and the ego-vehicle waits for the other vehicle, then the other vehicle goes away the ego-vehicle is required to restart parking again in that space.
But if the ego vehicle exceeds the stop_line or is close to the pull over start pose, it keeps stopping.
To fix this problem, in this PR,  
- add buffer to stop_pose 
- add buffer to search start pose
- check `distance_to_restart` only when the path is separated (e.g. geometric parallel parking)
[tier4 internal ticket](https://tier4.atlassian.net/jira/software/c/projects/RT1/boards/501?modal=detail&selectedIssue=RT1-2291&assignee=5e7857f83c888c0c29805978)
psim
https://github.com/autowarefoundation/autoware.universe/assets/39142679/1c5edc73-15fb-4eba-b60e-277319afcaa5
[tier4 internal scneario …

fix(goal_planner): add buffer to stop_pose for restarting

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

- fix bugs in another PR https://github.com/autowarefoundation/autoware.universe/pull/3798
- don't init rtc status at `onProcessEntry()`
](https://evaluation.tier4.jp/evaluation/reports/d26c3910-6532-570f-adbb-310a762fc69c?project_id=prd_jt)
Nothing.

fix(avoidance): not init rtc status at onProcessEntry

---

perception/map_based_prediction/src/map_based_prediction_node.cpp

- problem: Lane change was not properly predicted with objects on unconnected lanelet
|before|after|
|--|--|
|Lane change not detected due to this bug. ![image](https://github.com/autowarefoundation/autoware.universe/assets/20086766/de3fbaec-0c79-4b0e-90ce-975ad0d23c3d)| Lane change successfully detected with this PR. ![image](https://github.com/autowarefoundation/autoware.universe/assets/20086766/0646eaca-799e-4939-af3d-9aededf58f67)|
Disable delay compensation in LC decision for stability.
There are following reasons:
- While the time is corrected at the time of LC decision and the decision is made at the current time, the output prediction is still the timestamp of the detection and the pose is not corrected.
- CompensateTimeDelay is unnecessary because it is sufficient to know whether …

feat(map_based_prediction): disable time delay compensation

---

planning/behavior_path_planner/src/utils/path_utils.cpp

If the difference between `s` and `s_end` was exactly `epsilon`, that point would be missing, but modified to keep it.
https://github.com/autowarefoundation/autoware.universe/pull/3720
psim
not applicable 
not applicable

fix(behavior_path_planner): fix keeping terminal point

---

control/autonomous_emergency_braking/include/autonomous_emergency_braking/node.hpp
control/autonomous_emergency_braking/src/node.cpp

This node uses original IMU value, so trajectory made by odometry is opposite direction when IMU is located upside down.
I'll fix it to use tranform.
In addition, I do transform only angular velocity because other informartion is not used.
https://tier4.atlassian.net/browse/AEAP-557
I confirmed frajectory is right direction by below rosbag.
https://drive.google.com/file/d/1LdELkVLbqb8twDXPr-cU538EZVscSX5j/view?usp=sharing
This rosbag has necesarry information only. …

fix(autonomous_emergency_braking): fix imu tranform to base_link

---

sensing/pointcloud_preprocessor/src/concatenate_data/concatenate_data_nodelet.cpp

- add error handling when sensor points are empty
TIERIV INTERNAL LINK: https://star4.slack.com/archives/C4P0NSMB5/p1684487463523999
I confirmed concat is running when empty sensor points is inserted by rqt.

fix(concatedate_date): add error handling when sensor points is empty

---

planning/mission_planner/src/mission_planner/mission_planner.cpp
planning/mission_planner/src/mission_planner/mission_planner.hpp

Add rerouting functions for MRM. This enables autoware to generate a new route when it is in a danger.
Planning Simulator
There are no interface changes.
No effects on system behavior unless the ego vehicle requires to generate a new path in a mrm state

feat(mission_planner): add mrm reroute

---

planning/behavior_velocity_occlusion_spot_module/src/debug.cpp

Related with https://github.com/autowarefoundation/autoware.universe/issues/3769
There are two types of scene module exist in `behavior_velocity_planner`.
- multiple module can be launched
- only one module can be launched
And `occlusion_spot_module` is the type of only one module can be launched.
So prefix of namespace is unnecesary. Thi PR delete arg used for prefix. …

fix(behavior_velocity_occlusion_spot_module): delete unnecessary arg from member function of VirtualWallMarkerCreator

---

planning/behavior_path_planner/include/behavior_path_planner/marker_util/lane_change/debug.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/interface.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_interface.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_manager_interface.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/lane_change_path.hpp
planning/behavior_path_planner/src/marker_util/lane_change/debug.cpp
planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp
planning/behavior_path_planner/src/utils/lane_change/utils.cpp

With the addition of https://github.com/autowarefoundation/autoware.universe/pull/3566, the flow of lane change states has been changed, and lane changing process will only be cancelled if ego vehicle **is in prepare phase**. 
However, it is difficult to distinguish prepare phase and lane changing phase. Therefore, the aim of this PR is to add virtual marker that will enable see where lane changing is starting.
After PR is merged, we expect the result to be as follows.
1. Test lane change scenario in planning simulator.
2. add virtual wall debug marker from ```/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/virtual_wall/lane_change```
None
No changes to interface
No changes to system behavior …

feat(lane_change): lane change virtual wall marker

---

planning/behavior_velocity_no_stopping_area_module/src/debug.cpp

Related with https://github.com/autowarefoundation/autoware.universe/issues/3769
Namespace prefix necessary because multiple module can be launched.
Module_id_ derived from lane_id_ is unique(because it is obtained from reguratory element id of lanelet).
Add this module_id_ as arg of `createVitualWallMarker`. …

fix(behavior_velocity_no_stopping_area_module): add arg for namespace prefix

---

planning/behavior_velocity_stop_line_module/src/debug.cpp

Fixed stopline module to use module_id_ for virtual wall marker creator.
The first stopline virtual wall on the path is not visualized due to the error

fix(stopline): fix virtual wall marker id duplication

---

common/tier4_planning_rviz_plugin/include/path/display_base.hpp
common/tier4_planning_rviz_plugin/src/path/display.cpp

Before this PR the plugin crashes frequently.
https://github.com/autowarefoundation/autoware.universe/issues/3819
After this PR I do not encounter any crashes anymore when visualizing lane_ids on Rviz.

fix(tier4_planning_rviz_plugin): fix plugin crash

---

planning/behavior_velocity_virtual_traffic_light_module/src/debug.cpp

Ensure a single call to the `VirtualWallMarkerCreator` and set a unique namespace, even if multiple modules run in parallel.

fix(behavior_velocity_virtual_traffic_light_module): properly use the VirtualWallMarkerCreator and set unique namespace

---

vehicle/accel_brake_map_calibrator/accel_brake_map_calibrator/scripts/calc_utils.py
vehicle/accel_brake_map_calibrator/accel_brake_map_calibrator/scripts/plotter.py

I fixed view_statistics.py script in the accel_brake_map_calibrator package.
After:
Before:
The script causes the following error.
After:
The script can output matplot image
It does not affect autonomous driving behavior.

fix(accel_brake_map_calibrator): fix view_statistics script

---

planning/behavior_velocity_intersection_module/src/manager.cpp
planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
planning/behavior_velocity_intersection_module/src/scene_intersection.hpp
planning/behavior_velocity_planner/config/intersection.param.yaml

Add the option to publish intersection_occlusion grid when intersection_occlusion feature is enabled.
launcher PR: https://github.com/autowarefoundation/autoware_launch/pull/372
On Psim

fix(intersection): add the flag for intersection_occlusion grid publication

---

planning/behavior_velocity_traffic_light_module/src/debug.cpp
planning/behavior_velocity_traffic_light_module/src/scene.hpp

Related with https://github.com/autowarefoundation/autoware.universe/issues/3769
Use `VirtualWallMarkerCreator` for create/delete virtual wall marker as other scene modules.
And namespace prefix necessary because multiple module can be launched.
But `module_id_` derived from lane_id_ is unique(because it is obtained from reguratory element id of lanelet).
So adding this module_id_ as arg of `createVitualWallMarker`. …

fix(behavior_velocity_traffic_light_module): use VirtualWallMarkerCreator for create/delete virtual wall marker

---

control/pid_longitudinal_controller/include/pid_longitudinal_controller/debug_values.hpp
control/pid_longitudinal_controller/src/pid_longitudinal_controller.cpp

Feedforward acceleration term is in the FF_SCALE, which is wrong.
run psim

fix(velocity_controller): debug value for feedforward

---

.github/sync-files.yaml
docs/assets/js/mathjax.js
docs/js/mathjax.js
mkdocs.yaml

~I fixed the rendering error mathjax equations of the autoware.universe documentation. (like this page: https://autowarefoundation.github.io/autoware.universe/main/planning/obstacle_avoidance_planner/docs/eb/)~
~It looks like the page should be reloaded on some environments (like mobile Firefox, google chrome desktop).~
Currently, autoware-documentation and autoware.universe documentation do not seem to support `instant loading` of math equations.
related: https://github.com/squidfunk/mkdocs-material/issues/2530
When you open the [home page of obstacle_avoidance_planner](https://autowarefoundation.github.io/autoware.universe/main/planning/obstacle_avoidance_planner/) and then go to the details of `getEBTrajectory` part by clicking the link on `here`, you are likely to see the math …

docs(mkdocs): enable instant loading of mathjax equations

---

sensing/pointcloud_preprocessor/src/distortion_corrector/distortion_corrector.cpp

Deal with the bug reported on[ this ticket (TIER IV internal)](https://tier4.atlassian.net/browse/RT1-2334).
Fixed a situation where if `angular_velocity_queue_` is empty, the iterator for that deque is referenced in an uninitialized state.
The bug reported on [ this ticket (TIER IV internal)](https://tier4.atlassian.net/browse/RT1-2334) is fixed. …

fix(distortion_corrector_node): fix dereference of uninitialized iterator

---

planning/mission_planner/src/mission_planner/mission_planner.cpp
planning/mission_planner/src/mission_planner/mission_planner.hpp

Add several guards for reroute in the mission planner to prevent it from not transitioning to SET state.

feat(mission_planner): add guard for reroute

---

map/map_loader/src/lanelet2_map_loader/lanelet2_map_loader_node.cpp

resolves: https://github.com/autowarefoundation/autoware.universe/issues/3774
This PR will add the [code required](https://github.com/autowarefoundation/autoware_common/blob/05d31f4655fd0901b7b1b694a1178b65b8fb611f/tmp/lanelet2_extension/lib/autoware_osm_parser.cpp#L36-L43) for "local" projection that was missed out when "local" projection feature was moved from lanelet2_extension to map_loader in https://github.com/autowarefoundation/autoware_common/pull/174.
**Detailed explanation**
When lanelet2 map is loaded from a file, it will look for the orientation of a lanelet borders to register it as either normal linestring or inverted linestring by looking at the geometrical relationship of the borders. Since "local" projection will overwrite the coordinates of loaded points with local_x and …

fix(map_loader): re-align lanelet borders after overwriting coordinates

---

simulator/dummy_perception_publisher/README.md
simulator/dummy_perception_publisher/include/dummy_perception_publisher/node.hpp
simulator/dummy_perception_publisher/launch/dummy_perception_publisher.launch.xml
simulator/dummy_perception_publisher/src/node.cpp

Dummy detections are generated by removing undetected parts from the ground truth with a certain probability, and then adding appropriate noise.
- This PR added option to
- Publish ground truth as a TrackedObjects
- Enable to fix the random seed used in noise generation.
Tested in Psim.
- pink bounding box: ground truth
- blue bounding box: dummy detection …

feat(dummy_perception_publisher): publish ground truth object in option

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/interface.hpp
planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp

Before this change, if the lane change module returns `FAILURE`, other running modules also killed in new architecture.
To fix this problem, I change the lane change module status not to return `FAILURE` in new architecture.
https://github.com/autowarefoundation/autoware.universe/assets/10190493/95cb08c3-d2a2-42d7-bccb-6337fe3b107d
Nothing.
Nothing.
[pull request …

fix(behavior_path_planner): do not return FAILURE in lane change module if it uses new architecture

---

planning/behavior_path_planner/config/lane_change/lane_change.param.yaml
planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/lane_change_module_data.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/scene_module/lane_change/manager.cpp
planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp

Current implementation, lane change module checks only traveling distance to judge the lane change maneuver is finished.
In this PR, I add lateral offset condition to the judgement. The module judges lc is finished only when the lateral offset between the ego and target lane is less than `finish_judge_lateral_threshold` (default: 0.2 [m]).
This PR must be merged after :arrow_down: 
https://github.com/autowarefoundation/autoware_launch/pull/375 …

feat(lane_change): check lateral offset at lc finish judgement

---

planning/behavior_path_planner/include/behavior_path_planner/behavior_path_planner_node.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp

In the node test, getter function will be necessary to confirm which scene module is waitinng approval.
I implemented getter function for old architecutre and new architecture.

feat(behavior_path_planner): add getter function to confirm which module is waitinng approval

---

control/mpc_lateral_controller/include/mpc_lateral_controller/lowpass_filter.hpp
control/mpc_lateral_controller/src/lowpass_filter.cpp
control/mpc_lateral_controller/test/test_lowpass_filter.cpp

The coefficient calculation in the Butterworth filter was wrong (just `tan` was not considered for the `fc/fs`). This PR corrects them and a unit test was added. The filtering behavior does not change that much as in the attached plots (the overshoot is slightly improved).
- Fix Butterworth coefficient calculation
- Add unit test to check the Butterworth coefficients
None
**Before**
**After**
None
None
Almost none
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/co …

fix(mpc_lateral_controller): butterworth coeffs calculation

---

planning/planning_test_utils/include/planning_interface_test_manager/planning_interface_test_manager.hpp
planning/planning_test_utils/include/planning_interface_test_manager/planning_interface_test_manager_utils.hpp
planning/planning_test_utils/package.xml
planning/planning_test_utils/src/planning_interface_test_manager.cpp
planning/planning_test_utils/test_map/lanelet2_map.osm

Related with https://github.com/autowarefoundation/autoware.universe/issues/3723
create odometry from lane_id and make route from start pose and goal pose which derived from lane_id.
In this PR, route for pull put is implemented.
And shoulder lane is added for the map.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing …

test(planning_test_utils): create route and odometry from lane_id

---

simulator/dummy_perception_publisher/src/node.cpp

fix runtime error
- https://github.com/autowarefoundation/autoware.universe/pull/3731
died `dummy_percption_publisher`
```
[ERROR] [dummy_perception_publisher_node-40]: process has died [pid 1836737, exit code -6, cmd '/home/satoshi/pilot-auto/install/dummy_perception_publisher/lib/dummy_perception_publisher/dummy_perception_publisher_node --ros-args -r __node:=dummy_perception_publisher -r __ns:=/simulation -p use_sim_time:=False -p wheel_radius:=0.383 -p wheel_width:=0.235 -p wheel_base:=2.79 -p wheel_tread:=1.64 -p front_overhang:
=1.0 -p rear_overhang:=1.1 -p left_overhang:=0.128 -p right_overhang:=0.128 -p vehicle_height:=2.5 -p max_steer_angle:=0.7 --params-file /tmp/launch_params_beil9v60 --params-file /tmp/launch_params_dprqtbiu --params-file /tmp/launch_params_9298ceju …
```

fix(dummy_perception_publisher): fix runtime error

---

sensing/gnss_poser/include/gnss_poser/convert.hpp
sensing/gnss_poser/include/gnss_poser/gnss_poser_core.hpp
sensing/gnss_poser/launch/gnss_poser.launch.xml
sensing/gnss_poser/src/gnss_poser_core.cpp

* Added to gnss_poser package as an option to convert ellipsoid height to orthometric height. 
* Added a height_system parameter to gnss_poser.launch and user can select whether use ellipsoid to orthometric height conversion.
* Output always will be orthometric height.  
Closes: https://github.com/autowarefoundation/autoware.universe/issues/3693
Tested using bag collected from YTU Davutpasa campus with Robione robot.
Will be tested on vehicle too.  …

feat(gnss_poser): add orthometric height as a option

---

planning/behavior_path_planner/config/pull_out/pull_out.param.yaml
planning/behavior_path_planner/docs/behavior_path_planner_pull_out_design.md
planning/behavior_path_planner/include/behavior_path_planner/data_manager.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_out/pull_out_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/goal_planner/goal_planner_parameters.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/pull_out/pull_out_parameters.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/pull_out/pull_out_path.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/scene_module/pull_out/pull_out_module.cpp
planning/behavior_path_planner/src/utils/pull_out/shift_pull_out.cpp
planning/behavior_path_planner/src/utils/pull_out/util.cpp

- pull out from the road lane not just `road_shoulder`
- always execute pull out when a new route is received and ego-vehicle is stopped.
- disable the blinker if the lateral shift offset is smaller than `th_blinker_on_lateral_offset: 1.0`
red arrow: pull out start point
yellow arrow: pull out end point
psim
[tier4 internal scenario test](https://evaluation.tier4.jp/evaluation/reports/0c03e577-97a3-5601-a357-b2e10296126b?project_id=prd_jt) 1339/1372
(baseline
https://evaluation.tier4.jp/evaluation/reports/90dcdc1b-b5b3-58d8-85ad-0c28654b65a0?project_id=prd_jt
1330/1372)
new archi
https://evaluation.tier4.jp/evaluation/reports/a62d2285-9947-57fa-b673-7dd30854accc?project_id=prd_jt
1302/1372
not degrated
not applicable  
not applicable …

feat(pull_out): support pull out normal lane

---

planning/behavior_path_planner/src/utils/avoidance/utils.cpp
planning/route_handler/include/route_handler/route_handler.hpp
planning/route_handler/src/route_handler.cpp

Add option to get same root (=`previous lanelet`) right/left lanelet from `current lanelet`.
Before this PR. It is **NOT** possible to get right lanelet from turn left lanelet. As a result, the ego can't avoid object because of the avoidable bounds.
Avoidable area bounds (pink bold line) is expanded correctly.
Improve avoidance maneuver. …

feat(avoidance): use same root adjacent lane boundary for avoidable margin calculation

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module.hpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp

Since the avoidance module always update only reference path but not update shift line, it applies shift lines to wrong reference path when the previous module output reference path is changed. Therefore, sometimes invalid path will be generated like this :arrow_down: 
https://github.com/autowarefoundation/autoware.universe/assets/44889564/7b90e461-2598-4dba-87d9-8ec045945fd6
In this PR, the avoidance module always check the ego's drivng lane and exit as SUCCESS when the driving lane is updated.
https://github.com/autowarefoundation/autoware.universe/assets/44889564/edae0190-7bb8-4bd2-be70-22666df1f4a9 …

fix(avoidance): reset avoidance module when the driving lane update is updated

---

sensing/pointcloud_preprocessor/docs/concatenate-data.md
sensing/pointcloud_preprocessor/include/pointcloud_preprocessor/concatenate_data/concatenate_data_nodelet.hpp
sensing/pointcloud_preprocessor/package.xml
sensing/pointcloud_preprocessor/src/concatenate_data/concatenate_data_nodelet.cpp

Even the ego vehicle twist topic is changed to `/sensing/vehicle_velocity_converter/twist_with_covariance` in https://github.com/autowarefoundation/autoware.universe/pull/1120, concatenate data node still uses `/vehicle/status/velocity_status`.
Since the velocity in `vehicle_velocity_converter/twist_with_covariance` is different from `velocity_status` after https://github.com/autowarefoundation/autoware.universe/pull/2641, the velocity used in the sensing stack should be only twist_with_covariance
https://github.com/autowarefoundation/sample_sensor_kit_launch/pull/59
[TIER IV INTERNAL LINK](https://star4.slack.com/archives/C057JDFS5M2/p1685504865398939)
Sensing module internal topic change.
Change input topic of concatenate_data from velocoty_report to twist_with_covariance
point clouds …

fix(pointcloud_preprocessor): change velocoty_report to twist_with_covariance

---

planning/planning_debug_tools/scripts/perception_reproducer.py

The `bag` argument for the bag directory of perception_reproducer did not work.
Nothing

fix(planning_debug_tools): bag directory designation of perception reproducer

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

Bug in https://github.com/autowarefoundation/autoware.universe/pull/3871. `prev_driving_lanes_` must be filled at first cycle.
Nothing.

fix(avoidance): fill prev driving lanes at first time

---

perception/crosswalk_traffic_light_estimator/include/crosswalk_traffic_light_estimator/node.hpp
perception/crosswalk_traffic_light_estimator/src/node.cpp

The crosswalk module in behavior_velocity uses the pedestrian signal color estimated by crosswalk_traffic_light_estimator.
In the current implementation, the signal for vehicular traffic may be out of the angle of view of the camera and  the pedestrian signal becomes not to be estimated before passing the crosswalk, and  it causes a sudden stop at the crosswalk.
This PR improves the above issue by holding the traffic signal color for a short time.
[Screencast from 2023年05月26日 13時45分16秒.webm](https://github.com/autowarefoundation/autoware.universe/assets/59680180/7b70d48f-dadb-407f-bf7f-3860c7021099)
I tested using rosbag.
none
none
The issue of sudden stops at crosswalks will be improved …

feat: add parameter for holding last detected traffic-signal color

---

common/motion_utils/src/vehicle/vehicle_state_checker.cpp
common/motion_utils/test/src/vehicle/test_vehicle_state_checker.cpp

In the current implementation, node will die if the data that has old timestamp is passed to the VehicleStopChecker.
This can happen when traffic load increases and message subscribe is delayed.
This is the same issue as [this PR](https://github.com/autowarefoundation/autoware.universe/pull/1980).
I added the test and confirmed the program will not die.
```
$ ./build/motion_utils/test_motion_utils --gtest_filter="vehicle_stop_checker*"
Note: Google Test filter = vehicle_stop_checker*
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from vehicle_stop_checker
[ RUN      ] vehicle_stop_checker.isVehicleStopped
fish: Job 1, './build/motion_utils/test_motio…' terminated by signal SIGSEGV (Address boundary error)
```
```
$ …
```

fix(motion_utils): check if the buffer is empty

---

control/mpc_lateral_controller/README.md
control/mpc_lateral_controller/include/mpc_lateral_controller/mpc_lateral_controller.hpp
control/mpc_lateral_controller/param/lateral_controller_defaults.param.yaml
control/mpc_lateral_controller/src/mpc_lateral_controller.cpp

Signed-off-by: Berkay Karaman <brkay54@gmail.com>
Closes: https://github.com/autowarefoundation/autoware.universe/issues/1543
In current Autoware.universe, mpc_follower sends is_steer_converged data "true" to longitudinal controller without reaching the desired steering angle value.
The problem is that when reinitialize the vehicle under low steering angle rate limit, solver can not solve the problem and sends the previous command to vehicle rather than the target value.
Like before reinitialize previous cmd = 30.0 degree,
After we reinitialize vehicle, previous_cmd still 30.0 degree but target_value is maybe 0.0 degree ideally but because steering_angle_rate_limit so small, mpc can not solve the problem and sends 30.0 degree again and vehicle starts moving (because before re …

fix(trajectory_follower_nodes): mpc_follower does not send proper converged data under low steering rate limit

---

planning/behavior_velocity_intersection_module/src/debug.cpp

Fix the issue that the virtul wall of the merge_from_private_road module does not visualize in RViz.
Before:
After:
Not applicable. (It affects for only visualization)

fix(behavior_velocity_intersection_module): visualize virtuall wall of merge_from_private_road

---

planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp

Fix goal planner execution.
goal arc coordinates can not be calculated correctly if the goal pose is not in current_lanes.
This causes executing `goal_planner` at inappropriate timing
```
component_container_mt-28] isExecutionRequested: 303, backward_goal_search_length : 20
[component_container_mt-28] isExecutionRequested: 304, request_length : 100
[component_container_mt-28] isExecutionRequested: 305, self_to_goal_arc_length : -0.518109 
```
```
[component_container_mt-28] isExecutionRequested: 303, backward_goal_search_length : 20
[component_container_mt-28] isExecutionRequested: 304, request_length : 100
[component_container_mt-28] isExecutionRequested: 305, self_to_goal_arc_length : 99.2417
```
[
tier4 internal ticket](https://tier4.atlassian.net/browse/RT1-2650)
psim
[ tier4 internal …

fix(goal_planner): fix goal planner execution

---

planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp

Disable default lane change virtual wall publisher
Run lane change scenario
On another terminal, execute
```
ros2 param set /planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner lane_change.publish_debug_marker true
```
the marker should appear
Run 
```
ros2 param set /planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner lane_change.publish_debug_marker false
```
to disable
[Screencast from 2023年06月02日 18時46分52秒.webm](https://github.com/autowarefoundation/autoware.universe/assets/93502286/aca56db7-038f-4841-a94b-06e41d6ba39e) …

fix(lane_change): disable virtual wall by default

---

planning/behavior_path_planner/include/behavior_path_planner/parameters.hpp

Double was used for enable flags by mistake
Nothing

fix(behavior_path_planner): use bool type for enable flag

---

planning/behavior_path_planner/src/utils/utils.cpp

Fix a minor bug of drivable area expansion considering hatched road markings.
**Without this PR**
Upper bound is weird in both cases.
**With this PR**
Nothing

fix(behavior_path_planner): drivable area expansion for hatched road markings

---

planning/obstacle_cruise_planner/include/obstacle_cruise_planner/planner_interface.hpp
planning/obstacle_cruise_planner/src/planner_interface.cpp

Currently, a slow-down velocity which is feasible based on initial velocity/acceleration with acceleration/jerk constraints is calculated every time.
However, depending on the controllability, the feasible slow-down velocity increased little by little.
To suppress this increase, the first slow-down velocity is memorized and use it to ignore the effect of controllability.
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contribu …

fix(obstacle_cruise_planner): stick to feasible slow down velocity

---

planning/obstacle_cruise_planner/config/obstacle_cruise_planner.param.yaml
planning/obstacle_cruise_planner/include/obstacle_cruise_planner/node.hpp
planning/obstacle_cruise_planner/src/node.cpp
planning/obstacle_cruise_planner/src/planner_interface.cpp

suppress flickering of slow down entry/exit
planning simulator & real vehicle
Nothing

feat(obstacle_cruise_planner): suppress flickering to entry slow down

---

planning/motion_velocity_smoother/test/test_motion_velocity_smoother_node_interface.cpp

test(motion_velocity_smoother): add off-track test

---

common/autoware_auto_perception_rviz_plugin/include/object_detection/object_polygon_display_base.hpp

In the object visualization plugin in the autoware_auto_perception_rviz_plugin, the options for computational cost reduction (```Polygon Type```, ```Visualization Type```) is unavailable now. I fixed it.
Before:
After:
Not applicable. (It affects only RViz. )

feat: enable some options for object visualization

---

planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp

pull out finish causes avoidance to cancel.
https://github.com/autowarefoundation/autoware.universe/assets/39142679/68c4270a-0159-47a8-89cf-8f51bf2d4696
In this PR, change the deviation threshold for finishing pull out, the value referred to lane change https://github.com/autowarefoundation/autoware.universe/pull/3861
[tier4 internal ticket](https://tier4.atlassian.net/browse/RT1-2666)
psim
not applicable
not applicable
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/m …

feat(pull_out): change pull out finish deviation threshold

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/avoidance_module_data.hpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

Improve shift line pre-process logic so that the module outputs small shift avoidance path. 
- Grid: 0.5 x 0.5 m
- Green Path: original path
- Red Path: candidate path
This PR includes following modifications:
- add fill gap process before the merge process in order to remove noisy shift line.
- add one more small longitudinal shift line trimmer in order to remove noisy shift line.
- fix shift line start/end shift length based on previous linear shift line to remove noisy shift line.
- check shift gradient sign (positive or negative) in similar gradient shift line merger function in order to prevent vanishing of small shift line.
(Before this PR) huge gaps exist in merged shift lines.
(After this PR) merged shift lines are connected smoothly.
Make it possible to output small shift …

feat(avoidance): make it possible to output small shift avoidance path

---

perception/compare_map_segmentation/src/voxel_grid_map_loader.cpp

Currently, the variable ```timer_callback_group_``` is used before initialization.
In this case map_update_timer_ may be assigned to the default callback group.
I fixed it.
x
TO DO
x
none
none (TODO)

fix(compare_map_segmentation): initialize timer_callback_group_

---

planning/behavior_path_planner/src/planner_manager.cpp

During manual driving or automatic driving of vehicles with large control errors, the behavior_path_planner node will die if Lane_Change is activated in a situation where the vehicle speed is higher than expected. 
This is due to accessing the null output.path, so I fixed it.
I tested on planning_simulator.
none
As the description. (Almost no effect on automatic driving ) …

fix(behavior_path_planner): avoid invalid access

---

map/map_loader/README.md
map/map_loader/src/pointcloud_map_loader/pointcloud_map_loader_node.cpp

The previous implementation did not consider a case where `enable_partial_load` and `enable_differential_load` is set false but `enable_selected_load` is set true. 
None
Launch with following config before and after PR, and confirmed that the selected node client launches successfully after the PR while not before.
```
/**:
enable_whole_load: true
enable_downsampled_whole_load: false
enable_partial_load: false
enable_differential_load: false
enable_selected_load: true
leaf_size: 3.0 # downsample leaf size [m]
```
None
None …

fix(map_loader): handle enable_selected_load correctly

---

planning/obstacle_cruise_planner/src/node.cpp
planning/obstacle_cruise_planner/src/pid_based_planner/pid_based_planner.cpp

The color of cruise was almost red, which is very close to the color of stop.
I changed the cruise color to pink.
Nothing

chore(obstacle_cruise_planner): change cruise color

---

planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp

Since the color of cruise became pink in the following PR, the color of dynamic avoidance debug marker was changed from pink to purple.
https://github.com/autowarefoundation/autoware.universe/pull/3925
Nothing

chore(dynamic_avoidance): change debug marker's color

---

planning/obstacle_avoidance_planner/src/mpt_optimizer.cpp

Currently, min_drivable_area does not consider the curvature, resulting in the tight constraint for trajectory optimization in narrow and curve roads.
Nothing

feat(obstacle_avoidance_planner): consider curvature for min_drivable_width

---

planning/mission_planner/README.md

Removes [duplicated param from mission_planner readme](https://github.com/autowarefoundation/autoware.universe/blob/main/planning/mission_planner/README.md#:~:text=for%20goal%20approve-,enable_correct_goal_pose,Enabling%20correction%20of%20goal%20pose%20according%20to%20the%20closest%20lanelet%20orientation,-reroute_time_threshold)
No need
Nothing …

docs(mission_planner): remove duplicated param from readme

---

perception/image_projection_based_fusion/src/roi_detected_object_fusion/node.cpp

- `roi_probability_threshold` should be double according to [README](https://github.com/autowarefoundation/autoware.universe/blob/e9f2f4fb4bd1b1dc105d5fd3964565028d426c1b/perception/image_projection_based_fusion/docs/roi-detected-object-fusion.md?plain=1#L51).
- However, in code, the type of `roi_probability_threshold` is wrong. So I fix this.
I checked this PR with logging_simulator.
I have confirmed that the Autoware performs the same as the current Autoware. …

fix(image_projection_based_fusion): fix type of roi_probability_threshold

---

planning/behavior_velocity_stop_line_module/src/debug.cpp

A minor fix to display virtual wall when stop pose is available
The wall is visualized.

fix(stop_line): fixed stop line module to pub virtual wall when stop_pose is not null

---

planning/behavior_velocity_speed_bump_module/src/debug.cpp

closes #3927 
Results for [slow_start_margin](https://github.com/autowarefoundation/autoware_launch/blob/65884add50a684ddf8674e6e065ea5eb97888f81/autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/speed_bump.param.yaml#LL4C7-L4C24) : `0.0`
**Before:** 
---
**After:** …

fix(behavior_velocity_speed_bump_module): fix virtual wall base_link2front offset

---

planning/mission_planner/src/mission_planner/mission_planner.cpp

keep uuid when rerouting with modified goal
psim
not applicable
not applicable

fix(mission_planner): keep uuid when rerouting with modified goal

---

planning/behavior_path_planner/src/utils/utils.cpp

Unable to fix lane boundary for avoid bug.
Fix bug is a future work.
[TIER IV INTERNAL LINK](https://evaluation.tier4.jp/evaluation/reports/2d2de800-29c5-565e-82f1-99429adc320c?project_id=prd_jt)

fix(behavior_path_planner): unable to fix bound

---

planning/behavior_path_planner/CMakeLists.txt
planning/behavior_path_planner/config/lane_change/lane_change.param.yaml
planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/base_class.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/interface.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/lane_change_module_data.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp

Currently, the lane change module cannot activate turn signal when the ego vehicle approaches at the end of current path. In this PR, it can fire the signal even when the approved lane change path is not available.
launch: https://github.com/autowarefoundation/autoware_launch/pull/397
[Screencast from 2023年06月11日 01時34分35秒.webm](https://github.com/autowarefoundation/autoware.universe/assets/43805014/f37b7ac5-3cc8-47f8-a5b3-3e19e0b866e0)
PSim …

feat(behavior_path_planner): enable lane change to activate turn signal when stopping

---

planning/behavior_path_planner/src/behavior_path_planner_node.cpp

fix goal_planner activation chattering.
the route uuid is same when rerouting with modified_goal, in that case, we do not need to reset modules.
psim
not applicable
not applicable

fix(behavior_path_planner): not rest modules when new route with same uuid is recived

---

map/map_loader/src/lanelet2_map_loader/lanelet2_map_visualization_node.cpp
planning/behavior_velocity_crosswalk_module/src/manager.cpp
planning/behavior_velocity_crosswalk_module/src/manager.hpp
planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp
planning/behavior_velocity_crosswalk_module/src/scene_walkway.cpp
planning/behavior_velocity_crosswalk_module/src/scene_walkway.hpp
planning/behavior_velocity_crosswalk_module/src/util.cpp
planning/behavior_velocity_crosswalk_module/src/util.hpp

Crosswalk module supports regulatory element.
See https://github.com/orgs/autowarefoundation/discussions/3036
:arrow_down: This PR must be merged before this PR.
https://github.com/autowarefoundation/autoware_common/pull/187
Crosswalk module checks the existence of regulatory elements.
Nothing.
Nothing.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contribut …

feat(crosswalk): support crosswalk regulatory element

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp
planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp

fix reset goal planner twice.
currently when receiving new route reset scene modules in https://github.com/autowarefoundation/autoware.universe/blob/fix/not_reset_goal_planner/planning/behavior_path_planner/src/behavior_path_planner_node.cpp#L1232
so, no need to reset in goal_planner
note that, in old architecture still reset twice.
psim
none
none  …

fix(goal_planenr): not reset when receving new route

---

planning/behavior_velocity_no_drivable_lane_module/README.md

To be able to sync the README file under behavior_velocity_no_drivable_lane_module with github.io, this PR renames and relocates the README file for `behavior_velocity_no_drivable_lane_module`

refactor(behavior_velocity_no_drivable_lane_module): relocate README file

---

planning/behavior_path_planner/docs/behavior_path_planner_lane_change_design.md

Update the lane change document by adding an explanation about the dynamic lateral acceleration decider.

docs(behavior_path_planner): add explanation for dynamic lateral acceleration

---

planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp

Fix https://github.com/autowarefoundation/autoware.universe/issues/3951.
In this PR, do not run start_planner if the ego vehicle is close to the goal.
https://github.com/autowarefoundation/autoware.universe/issues/3951
[tier4 internal slack](https://star4.slack.com/archives/C03QW0GU6P7/p1686719454465849?thread_ts=1686709718.085519&cid=C03QW0GU6P7)
psim
https://github.com/autowarefoundation/autoware.universe/assets/39142679/805c610b-ad6b-42c2-937b-9c82ed6496f5
none
none …

fix(start_planner): fix start planner pendulum

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module.hpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

Don't reset registered shift linew if the base offset is **NOT** zero.
Otherwise, the current path will be updated suddenly like this.
[Screencast from 2023年06月13日 17時14分43秒.webm](https://github.com/autowarefoundation/autoware.universe/assets/44889564/050096a5-b006-4ca7-90c5-c0321ca14106)
[[TIER IV INTERNAL LINK]](https://tier4.atlassian.net/browse/RT1-2739?atlOrigin=eyJpIjoiZGM0Yzg1NWQ1NjdmNDM1ZTlhMzZiZTg1MzBjODFhNDAiLCJwIjoiamlyYS1zbGFjay1pbnQifQ) …

fix(avoidance): don't reset registered shift lines if the base offset is not zero

---

simulator/simple_planning_simulator/launch/simple_planning_simulator.launch.py

Fix old-style arg for static_tf_publisher to remove the following error:
```
[static_transform_publisher-48] [WARN 1684291838.681769706] [] parse_args(): Old-style arguments are deprecated; see --help for new-style arguments:(L258)
```

fix(simple_planning_simulator): old style arg for static_tf_publisher

---

launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_radar_fusion_based_detection.launch.xml
launch/tier4_perception_launch/launch/object_recognition/detection/radar_based_detection.launch.xml

Correcting a few errors of the topic remapping in the `camera_lidar_radar_fusion` mode.
- Launched `logging_simulator` and checked the information of the related nodes.
```
$ ros2 launch autoware_launch logging_simulator.launch.xml vehicle_model:=sample_vehicle sensor_model:=sample_sensor_kit perception_mode:=camera_lidar_radar_fusion map_path:=... 
```
```
$ ros2 node info /perception/object_recognition/detection/radar/radar_tracks_msgs_converter
/perception/object_recognition/detection/radar/radar_tracks_msgs_converter
Subscribers:
/clock: rosgraph_msgs/msg/Clock
/localization/kinematic_state: nav_msgs/msg/Odometry
/parameter_events: rcl_interfaces/msg/ParameterEvent
/sensing/radar/front_center/objects_raw: radar_msgs/msg/RadarTracks
Publishers:
/parameter_events: …
```

fix(tier4_perception_launch): fix camera_lidar_radar_fusion_based_detection

---

planning/motion_velocity_smoother/config/default_motion_velocity_smoother.param.yaml
planning/motion_velocity_smoother/include/motion_velocity_smoother/motion_velocity_smoother_node.hpp
planning/motion_velocity_smoother/launch/motion_velocity_smoother.launch.xml
planning/motion_velocity_smoother/src/motion_velocity_smoother_node.cpp
planning/motion_velocity_smoother/test/test_motion_velocity_smoother_node_interface.cpp

**Summary:**
The `motion_velocity_smoother` calculates the velocity based on the ego-velocity and ego-acceleration when driving on manual mode.
Needs to merge with https://github.com/autowarefoundation/autoware_launch/pull/396
**Background:**
The current velocity planning intentionally relies on the previously planned trajectory's vehicle speed rather than the actual vehicle speed. This separation between the uncertain motion of the vehicle and the ideal planning is crucial for effective design. However, when the planned velocity and the actual vehicle velocity significantly differ, such as during manual driving, enabling Autoware control during manual driving can sometimes lead to adverse effects (e.g., strong brake) due to the disconnect between the planned value and the actual value. …

feat(velocity_smoother): plan from ego velocity on manual mode

---

planning/behavior_velocity_intersection_module/src/scene_intersection.cpp

If the parameter `occlusion.enable` is set to `false`, this module makes no reaction to `INTERSECION_OCCLUSION` RTC.
[COMPANY INTERNAL LINK](https://tier4.atlassian.net/browse/RT1-2752)
with `occlusion.enable = false`, intersection_occlusion wall appears when disapproved.
with `occlusion.enable = false`, intersection_occlusion wall does not appear.
if the flag is false, this module does not respond to intersection_occlusion RTC anymore.
if the flag is false, this module does not respond to intersection_occlusion RTC anymore. …

fix(intersection): do not react to rtc for occlusion anymore if occlusion.enable is false

---

control/mpc_lateral_controller/include/mpc_lateral_controller/mpc.hpp

Add default parameter value to fix the test in mpc
pass test on CI
None

chore(mpc): add default value

---

planning/behavior_path_planner/config/avoidance/avoidance.param.yaml
planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/avoidance_module_data.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/utils.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
planning/behavior_path_planner/src/scene_module/avoidance/manager.cpp
planning/behavior_path_planner/src/scene_module/lane_change/avoidance_by_lane_change.cpp
planning/behavior_path_planner/src/utils/avoidance/utils.cpp

**Assumption**: Perception results for far objects have larger detection error than the result for near one.
Sometimes, the avoidance module changes the judgement whether the ego should avoid or not after the ego gets quite a bit closer to the object because of the detection error. The judgement chattering causes unexpected sudden deceleration so that the module keeps avoidable distance to object.
In this PR, it is able to set `max_expand_ratio > 0`, and the avoidance module expands objects `envelope_polygon_buffer` and `safety_buffer_lateral` based on the distance between the ego and object so that far objects are judged to be avoided more frequently than nearby objects. As a result, it prevents a sudden change from "not need to avoid" to "should avoid" after approaching it.
:arrow_down: …

feat(avoidance): additional buffer for perception noise

---

planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/utils.hpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
planning/behavior_path_planner/src/scene_module/lane_change/avoidance_by_lane_change.cpp
planning/behavior_path_planner/src/utils/avoidance/utils.cpp

Add hysteresis factor to judge whether the ego should avoid the object or not to prevent chattering of results.
Nothing.

feat(avoidance): add hysteresis to avoidance necessity check

---

planning/behavior_path_planner/config/lane_change/lane_change.param.yaml
planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/lane_change_module_data.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp

Add a new parameter for tuning the position of the end of the turn signal of the lane change.
[autoware launch PR](https://github.com/autowarefoundation/autoware_launch/pull/398)
PSim 
[Screencast from 2023年06月15日 15時57分03秒.webm](https://github.com/autowarefoundation/autoware.universe/assets/43805014/654fb722-023e-4265-9818-ef56b04ff6da) …

feat(behavior_path_planner): add a length ratio parameter for lane change turn signal deactivation

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/avoidance_module_data.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/helper.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/utils.hpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
planning/behavior_path_planner/src/utils/avoidance/utils.cpp

The avoidance module has option `use_constraints_for_decel` to decelerate within decel/jerk constrains but sometimes the ego doesn't stop at expected position even if stop distance is feasible because of the control error.
https://github.com/autowarefoundation/autoware.universe/assets/44889564/9cb2e91f-a2dd-483d-82ac-2d607d2a0fec
So, in this PR, I added latch logic to judge whether the ego can stop at the expected position or not.
- Once the module judges the ego can stop within constraints, keep that decision forever. (above movie)
- When the ego is NOT stoppable, the module try decelerating as hard as it can within constraints. (below movie)
https://github.com/autowarefoundation/autoware.universe/assets/44889564/643344c8-76a1-4ece-8be2-0f28f8738192 …

feat(avoidance): improve stop behavior under decel/jerk constraints option

---

planning/behavior_path_planner/src/utils/geometric_parallel_parking/geometric_parallel_parking.cpp
planning/behavior_path_planner/src/utils/start_planner/geometric_pull_out.cpp

fix geometric pull out stop point.
related to https://github.com/autowarefoundation/autoware.universe/pull/3873, need to set stop point end of the first arc path if path is devided.
psim
- divide_pull_out_path: false
- divide_pull_out_path: true
none
none

fix(start_planner): fix geometric pull out stop point

---

.pre-commit-config.yaml

Use check-jsonschema from https://github.com/python-jsonschema/check-jsonschema to validate the JSON Schema files against their meta-schema. It is a CLI wrapper around the python library from https://github.com/python-jsonschema/jsonschema/
Relates to https://github.com/autowarefoundation/autoware-github-actions/issues/232
Ran pre-commit locally on both a compliant and non-compliant .json schema file (currently only a single file under perception/lidar_apollo_segmentation_tvm_nodes/schema/lidar_apollo_segmentation_tvm_nodes.schema.json).
Fails pre-commit if a schema file does not respect its meta-schema format. …

ci(pre-commit): add check-jsonschema

---

planning/behavior_path_planner/src/planner_manager.cpp

fix root next lanelets check
- `root_lanelet_`  is previous one
- `root_lanelet` is current one which is calulated from current self pose.
so, need to check `root_lanelet` is next lanes of `root_lanelet`
psim
[tier4_internal_scnenario_tests](https://evaluation.tier4.jp/evaluation/reports/5a310287-a1ad-57c8-8047-1298b83d547b/?project_id=prd_jt) 1331/1372
none
none …

fix(behavior_path_planner): fix root next lanelets check

---

planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/planner_manager.cpp

reset root lanelet of planner manager when rerouting.
[tier4 internal ticket](https://tier4.atlassian.net/browse/RT1-2775)
psim
[tier4 internal scenario test](https://evaluation.tier4.jp/evaluation/reports/6ca7ede0-a2fd-5ba9-8738-f3e40f6c19c4/?project_id=prd_jt)
1305/1372 ->1368/1372
none
none
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-r …

fix(behavior_path_planner): reset root lane when rerouting

---

planning/behavior_path_planner/config/avoidance/avoidance.param.yaml
planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/avoidance_module_data.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/scene_module/avoidance/manager.cpp
planning/behavior_path_planner/src/utils/avoidance/utils.cpp

- https://github.com/autowarefoundation/autoware_launch/pull/399
The avoidance module has flags whether avoid or not for each object class. In this PR, I added following threshold to judge the object is moveing or not for each object class.
- `stopped_speed_threshold`
- `moving_time_threshold`
```
// if following condition are satisfied, ignored the objects as moving objects.
// 1. speed is higher than threshold.
// 2. keep that speed longer than the time threshold.
```
](https://evaluation.tier4.jp/evaluation/reports/cf241f36-047d-52fc-8636-73d3c00a51e3?project_id=prd_jt) …

feat(avoidance): can set stop/move judge threshold for each object class

---

planning/behavior_path_planner/include/behavior_path_planner/planner_manager.hpp
planning/behavior_path_planner/src/planner_manager.cpp

Output update module infomation.
```
[component_container_mt-27] [INFO 1687144000.732573134] [planning.scenario_planning.lane_driving.behavior_planning.behavior_path_planner.planner_manager]:                                                                                                                                                                                                                                                                      
[component_container_mt-27] *********************************************************** …
```

feat(planner_manager): output module add/delete infomation

---

planning/behavior_path_planner/src/scene_module/side_shift/side_shift_module.cpp

prevent side_shift from ding when the previous reference path is empty.
psim
none
none

fix(side_shift): add guard to side shift reference path

---

planning/motion_velocity_smoother/src/motion_velocity_smoother_node.cpp

Autonomous driving mode check was wrong. Fix for this PR: https://github.com/autowarefoundation/autoware.universe/pull/3948
Psim

fix(smoother): autonomous driving mode check

---

planning/motion_velocity_smoother/src/motion_velocity_smoother_node.cpp

Take the velocity limit in the velocity planning when manual mode. 
related to https://github.com/autowarefoundation/autoware.universe/pull/3948
None
None
Behavior in "engage on manual driving" will slightly change

feat(motion_velocity_smoother): consider velocity limit on manual driving

---

planning/behavior_path_planner/include/behavior_path_planner/planner_manager.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_interface.hpp
planning/behavior_path_planner/src/planner_manager.cpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp
planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp
planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp

when the approved module turns SUCCESS, clear candidate_modules.
ex) avoidance module is once approved as left_avoid(at this time avoidance module is still in candidate_modules), but if other approved module turn SUCCESS, cancel the left_avoid
For this problem, in this PR, 
use
- IDLE before approval
- RUNNING after approval
- keeping the status if approved once.
And, even if the approved module turns SUCCESS keep the RUNNING candidate modules.
[tier4 internal slack](https://star4.slack.com/archives/C03QW0GU6P7/p1686203920001089)
psim
https://github.com/autowarefoundation/autoware.universe/assets/39142679/87662994-0ade-426b-9c01-1c99ca07b665
tier4 internal sceneario test
- old archi https://evaluation.tier4.jp/evaluation/reports/fbd639d3-080a-5f66-8701-559bb1b770f2?project_id=prd_jt 1332 …

feat(behavior_path_planner): use module status idle before approval and keep candiate running module when approved module succeed

---

planning/behavior_path_planner/src/behavior_path_planner_node.cpp

remove SUCCESS module candidate path
https://github.com/autowarefoundation/autoware.universe/pull/3928
psim
https://github.com/autowarefoundation/autoware.universe/assets/39142679/9b407189-01c8-4364-8b57-78756ac769ea
not applicable
not applicable

feat(behavior_path_planner): remove SUCCESS module candidate path

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

Sometimes, `safe_new_sl` size will be zero even when the avoidance target object is exists since the module ignores shift line whose lateral offset is less than threshold.
In that situation, the avoidance module clears waiting approval, and avoidance module is registered as `approved_module_stack` in planner manager. But it is an unexpected behavior because the modue doesn't recieve any approval and inserts any shift lines.
https://github.com/autowarefoundation/autoware.universe/assets/44889564/d92be9f1-063f-44db-90ad-61a560b4c586
In this PR, the avoidance module clears waiting approval only when there is no raw shift lines. (Basically, raw shift lines will be generated for all of the avoidance target.)
https://github.com/autowarefoundation/autoware.universe/assets/44889564/372b7ce1-a94b-4 …

fix(avoidance): don't clear waiting approval if raw shift line exists

---

planning/behavior_path_planner/config/start_planner/start_planner.param.yaml
planning/behavior_path_planner/include/behavior_path_planner/utils/start_planner/start_planner_parameters.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/utils/start_planner/shift_pull_out.cpp

start_planner generate path with acceleration.
psim
tier4 internal scenario test
- new archi
- 1365/1372 https://evaluation.tier4.jp/evaluation/reports/011d3a39-fddd-547c-be7e-c5ae3366f2b5?project_id=prd_jt 
- old archi
- 1332/1372 https://evaluation.tier4.jp/evaluation/reports/3af21625-2573-5eef-8d8a-1dbfe79d9bda?project_id=prd_jt
- base line
- 1331/1372([2023/06/19](https://evaluation.tier4.jp/evaluation/reports/df9038aa-d030-5376-9015-f4c1d5dc5419/?project_id=prd_jt)) 
none
none
[contribution …

feat(start_planner): start with acceleration

---

perception/detected_object_validation/include/detected_object_filter/object_lanelet_filter.hpp
perception/detected_object_validation/object-lanelet-filter.md
perception/detected_object_validation/src/object_lanelet_filter.cpp

For now, the lanelet filter handle only POLYGON shape type.
So this PR adapt to BOUNDING_BOX shape type.
This change can be used for radar detection.
Tested by rosbag.
Purple objects is input objects and red objects is filtered objects.
This PR doesn't effect to POLYGON type, so doesn't effect to system behavior.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main …

feat(detected_object_validation): add BOUNDING_BOX interface to lanelet filter

---

planning/behavior_path_planner/config/start_planner/start_planner.param.yaml
planning/behavior_path_planner/docs/behavior_path_planner_start_planner_design.md
planning/behavior_path_planner/include/behavior_path_planner/utils/start_planner/start_planner_parameters.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp

add `length_ratio_for_turn_signal_deactivation_near_intersection` to offset requreid end pose of start planner if vehicle is near intersection.
This is to give priority to that signal near intersections.
https://github.com/autowarefoundation/autoware.universe/assets/39142679/d49538f1-b32d-4426-84e7-414c26088480
[tier4 internal slack](https://star4.slack.com/archives/C03QW0GU6P7/p1687251155639739)
psim
none
none
none
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/ …

feat(start_planner): add length_ratio_for_turn_signal_deactivation_near_intersection

---

planning/behavior_velocity_intersection_module/config/intersection.param.yaml
planning/behavior_velocity_intersection_module/src/manager.cpp
planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
planning/behavior_velocity_intersection_module/src/scene_intersection.hpp

If a stuck vehicle is detected in private intersection lane, cancel the stop decision after a specified period.
parameter PR: https://github.com/autowarefoundation/autoware_launch/pull/406
https://tier4.atlassian.net/browse/RT1-2647
In Psim

feat(intersection): timeout stuck vehicle stop in private area

---

localization/ndt_scan_matcher/src/debug.cpp

Set lifetime for MonteCarlo particles marker in ndt_scan_matcher so that it won't last so long.
N/A
N/A
N/A
None
None

fix(ndt_scan_matcher): set lifetime for MonteCarlo particles marker

---

planning/behavior_path_planner/src/scene_module/side_shift/side_shift_module.cpp

skip unnecessary process in updateDate() when module_status is not RUNNING.
But `requested_lateral_offset_` should be updated to judge whether execution is excecuted.
So the part of retriving `requested_lateral_offset_` is kept.
confirmed with psim …

fix(behavior_path_planner): skip unnecessary process in updateDate() when module_status is not RUNNING

---

planning/behavior_path_planner/src/turn_signal_decider.cpp

Disable the turn signal from the each behavior module when the ego vehicle is right in front of the intersection.
PSim
[Screencast from 2023年06月22日 12時34分44秒.webm](https://github.com/autowarefoundation/autoware.universe/assets/43805014/dad5b299-8a94-48a8-bd9e-ce8af506f745)
No effects on the system. …

feat(behavior_path_planner): disable behavior turn signal before the intersection

---

planning/behavior_path_planner/CMakeLists.txt
planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/base_class.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/normal.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/utils.hpp
planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp
planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
planning/behavior_path_planner/src/utils/utils.cpp

During lane change, when path is not approved until the very end, the centerline is cut, so that ego vehicle stop. 
But now, instead of cut the centerline, we would like to add stop point.
PSIM
Note
1. Due to some not yet known issue regarding vehicle stopping in cut path case and insert stop point case, which affects lane change candidate path generation, in this PR, as a temporary solution, the stop point is hard coded with additional `1 meter` buffer.
None
None …

fix(lane_change): dont cut centerline but insert stop

---

planning/behavior_path_planner/config/behavior_path_planner.param.yaml

Changed parameter to be less likely to cancel based on the speed of vehicles in adjacent lanes.
Related PR: https://github.com/autowarefoundation/autoware_launch/pull/410
With real vehicle
No

feat(behavior_path_planner): relax longitudinal_velocity_delta_time

---

control/trajectory_follower_node/param/lateral/mpc.param.yaml

The MPC fails for small steering rate limits as reported in https://github.com/autowarefoundation/autoware.universe/issues/4015. 
The steering limit parameter was changed in the [recent PR](https://github.com/autowarefoundation/autoware.universe/pull/3810). This PR fixes the value to the old one as a temporal fix for the issue. The potential cause of the failure must be investigated later.
This should be merged with https://github.com/autowarefoundation/autoware_launch/pull/405
Run Psim …

fix(mpc): relax steering rate limit

---

sensing/pointcloud_preprocessor/launch/preprocessor.launch.py

Fix bug where a single topic input was unused
Ran the following snippet:
```xml
<include file="$(find-pkg-share pointcloud_preprocessor)/launch/preprocessor.launch.xml" >
<arg name="input_points_raw_list" value="['/top_lidar/pointcloud']" />
</include>
```
It subscribed to `/top_lidar/pointcloud` instead of `/input_points_raw0`. …

fix(points_preprocessor): single input topic should be first element

---

planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/utils.hpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
planning/behavior_path_planner/src/utils/avoidance/utils.cpp

I would like to enable avoidance behavior for non car-like objects. (e.g. pedestrian, bicycle)
But if I set the flag true, in following situation, the module executes avoidance maneuver for pedestrian that are stopping in front of the crosswalk. I think it is little bit a strange behavior, and it is better not avoid objects around crosswalk.
- https://github.com/autowarefoundation/autoware_launch/pull/408
https://github.com/autowarefoundation/autoware.universe/assets/44889564/25df57b6-74bf-442e-afa3-d590b156e7b4
In this PR, the module doesn't avoid crosswalk user (PEDESTRIAN, BICYCLE) arround the crosswalk lanelet.
https://github.com/autowarefoundation/autoware.universe/assets/44889564/d79467ae-7322-4685-9a79-1af6544f12f0 …

feat(avoidance): improve avoidance judgement logic for pedestrian & bicycle

---

planning/behavior_path_planner/CMakeLists.txt

We TIER IV would like to develop new sub-module manager without BehaviorTree.
https://github.com/orgs/autowarefoundation/discussions/3097
Now, we confirmed that basically the new manager can be avhieve all of the scenarios in awf and TIER IV internal.
Therefore, I would like to transit the default manager from old one to new one.
And, the new manager design is [here](https://autowarefoundation.github.io/autoware.universe/main/planning/behavior_path_planner/docs/behavior_path_planner_manager_design/).
- https://github.com/orgs/autowarefoundation/discussions/3097
- https://github.com/orgs/autowarefoundation/discussions/3600
- https://autowarefoundation.github.io/autoware.universe/main/planning/behavior_path_planner/docs/behavior_path_planner_manager_design/ …

feat(behavior_path_planner): use new framework

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/dynamic_avoidance/dynamic_avoidance_module.hpp
planning/behavior_path_planner/package.xml
planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp

add a low-pass filter to lateral offset to avoid
Stabler dynamic avoidance

feat(dynamic_avoidance): apply LPF to shift length, and positive relative velocity

---

planning/behavior_velocity_traffic_light_module/src/scene.cpp

Add traffic light ids information in the warning of not found traffic light.
```
[component_container_mt-27] [WARN 1687442666.245190345] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner.traffic_light_module]: cannot find traffic light lamp state (391,393,395,397,399) due to TrafficSignalNotFound. (getHighestConfidenceTrafficSignal():451)
```
Nothing …

feat(behavior_velocity_traffic_light_module): print not found traffic ids for warning

---

planning/behavior_path_planner/config/dynamic_avoidance/dynamic_avoidance.param.yaml
planning/behavior_path_planner/include/behavior_path_planner/scene_module/dynamic_avoidance/dynamic_avoidance_module.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp
planning/behavior_path_planner/src/scene_module/dynamic_avoidance/manager.cpp

suppress the chattering dynamic avoidance to launch
Stabler dynamic avoidance

feat(dynamic_avoidance): suppress flickering of dynamic avoidance launching

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

I fixed the logic to keep waiting approval even when the avoidance target is removed in #4012 .
- https://github.com/autowarefoundation/autoware.universe/pull/4012
But my solution seems to be not so good, and the avoidance module still remains as candidate modules even when all of the RTC request are approved. As a result, lane change module can't be launch as candidate module.
https://github.com/autowarefoundation/autoware.universe/assets/44889564/37b782f4-fc7a-44d6-98f2-028f9b16f857
In this PR, I re-fixed the logic. And, the avoidance module is moved to approved modules correctly after the approval.
https://github.com/autowarefoundation/autoware.universe/assets/44889564/e8d8c4c9-f0b1-4644-b440-b3e1e52f64d1
Nothing. …

fix(avoidance): update logic to keep waiting approval

---

planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp

Fix lane change debug now showing.
Test via PSIM
Add lane change debug marker
```
/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/debug/lane_change_left
/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/debug/lane_change_right
```
Run the following command
```
ros2 param set
/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner lane_change.publish_debug_marker true
``` …

fix(lane_change): fix debug visualization now showing

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/dynamic_avoidance/dynamic_avoidance_module.hpp
planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp

depends on
https://github.com/autowarefoundation/autoware.universe/pull/4047
https://github.com/autowarefoundation/autoware.universe/pull/4048
ignore dynamic avoidance for cut-out vehicle
Not avoid cut-out vehicle

feat(dynamic_avoidance): ignore cut-out vehicle

---

planning/behavior_path_planner/config/behavior_path_planner.param.yaml

Reverts autowarefoundation/autoware.universe#4039 because of scenario test fails

revert: "feat(behavior_path_planner): relax longitudinal_velocity_delta_time"

---

planning/behavior_path_planner/include/behavior_path_planner/behavior_path_planner_node.hpp
planning/behavior_path_planner/include/behavior_path_planner/data_manager.hpp
planning/behavior_path_planner/include/behavior_path_planner/turn_signal_decider.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/turn_signal_decider.cpp

Add turn signal info debug data publisher.

feat(behavior_path_planner): add turn signal debug marker

---

planning/behavior_path_planner/package.xml

This PR adds `opencv-dev` as a depdency in `package.xml`

build: fix opencv dependency

---

planning/obstacle_cruise_planner/src/node.cpp
planning/obstacle_cruise_planner/src/pid_based_planner/pid_based_planner.cpp

The color of cruise was almost red, which is very close to the color of stop.
I changed the cruise color to orange.
Test with real vehicle
Nothing

feat(obstacle_cruise_planner): change cruise color to orange

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/normal.hpp
planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp

Refactor, defining a common logger.
build success
None

refactor(lane_change): use common logger

---

planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp

Since `stop_point_with_factor` is `boost::optional` type, it is better to add early return if the variable is `boost::none`.
Evaluator
Nothing.

fix(crosswalk): return if the stop point with factor is boost::none

---

planning/behavior_path_planner/config/avoidance/avoidance.param.yaml
planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/avoidance_module_data.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
planning/behavior_path_planner/src/scene_module/avoidance/manager.cpp
planning/behavior_path_planner/src/utils/avoidance/utils.cpp

Avoidance shift length can be set independently for each object classes.
Please approve :arrow_down: before this PR.
- https://github.com/autowarefoundation/autoware_launch/pull/412
Nothing.

feat(avoidance): set additional buffer margin independently

---

planning/behavior_path_planner/src/marker_util/lane_change/debug.cpp

Add z-pos in debug marker.
Check in the Psim
None

chore(lane_change): add z-pos in debug marker

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/base_class.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/normal.hpp
planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp
planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp

Before this change, redundant safety check is included in lane change module.
In this PR, I remove redundant safety check.
[TIER IV INTERNAL TEST](https://evaluation.tier4.jp/evaluation/reports/167d89ac-06c7-5cc4-8ac8-55dd12581c5e?project_id=prd_jt)
1 cycle elapsed time (3 obstacles)
- Before 75 ~ 90 ms
- After 20 ~ 35 ms
Nothing.
Nothing. …

feat(behavior_path_planner): remove redundant process

---

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

When avoiding near the goal, the avoidance module occasionally dies with the following error when the path length changes
```
[component_container_mt-28] terminate called after throwing an instance of 'std::out_of_range'
[component_container_mt-28]   what():  vector::_M_range_check: __n (which is 209) >= this->size() (which is 86)
[ERROR] [component_container_mt-28]: process has died [pid 1028191, exit code -6, cmd '/opt/ros/humble/lib/rclcpp_components/component_container_mt --ros-args -r __node:=behavior_planning_container -r __ns:=/planning/scenario_planning/lane_driving/behavior_planning -p use_sim_time:=False -p wheel_radius:=0.31 -p wheel_width:=0.18 -p wheel_base:=2.75 -p wheel_tread:=1.485 -p front_overhang:=0.8 -p rear_overhang:=0.85 -p left_overhang:=0.105 -p …
```

fix(behavior_path_planner): fix invalid access in avoidance module

---

planning/mission_planner/src/mission_planner/mission_planner.cpp
planning/mission_planner/src/mission_planner/mission_planner.hpp

Use lower case for the reroute safety check function

refactor(mission_planner): use lower case

---

control/vehicle_cmd_gate/config/vehicle_cmd_gate.param.yaml
control/vehicle_cmd_gate/package.xml
control/vehicle_cmd_gate/src/vehicle_cmd_gate.cpp
control/vehicle_cmd_gate/src/vehicle_cmd_gate.hpp

For vehicles that cannot acquire the vehicle speed in the low speed range, it may be incorrectly judged to be stopped 
in the vehicle_cmd_gate node.
To prevent this, we use ```vehicle_stop-checker``` for stop judgment
https://github.com/autowarefoundation/autoware_launch/pull/417
TODO 
none
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-requ …

feat: use vehicle_stop_checker for  judging vehicle stop vehicle_cmd_gate

---

planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp

fix https://github.com/autowarefoundation/autoware.universe/pull/4026
should calculate length from current pose to judge near intersection.
psim
none
none

fix(start_planner): fix winker near intersection

---

planning/behavior_velocity_intersection_module/src/util.cpp

The relationship between the parameter ```use_stuck_stopline``` and corresponding behavior of Autoware  was reversed. I fixed it.
I confirmed that the position of the intersection stop_line changes for stuck vehicles when ```use_stuck_stopline``` is true

fix(behavior_velocity_intersection_module): fix condition of use_stuck_stopline

---

planning/behavior_velocity_intersection_module/src/scene_intersection.cpp

If ego vehicle is already in the middle of the intersection, do not generate stop line at the beginning of the path.
[FOO COMPANY INTERNAL LINK](https://tier4.atlassian.net/browse/RT1-2847)

fix(intersection): do not plan if detection area is not empty and stop line idx is 0

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/base_class.hpp
planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/normal.hpp
planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp

When lc path is extended, the drivable area isn’t extending and it caused ego vehicle to decelerate unexpectedly (0m:23s)
https://github.com/autowarefoundation/autoware.universe/assets/93502286/58feb8f7-eb55-47dc-95c2-f922d284d2b0
This is because as the `combineDrivableLanes` combines drivable lane without using any `route_handler`'s api is prematurely called, for example 
therefore, the function couldn't deduce that the lanes in adjacent to each other, which results in drivable lanes is concatenated to each other (C3, C4, T3, T4) in the image.
the `DrivableLanes` overlap checker will remove the overlap and it cause issues to lane change behavior. 
In this PR, the `combineDrivableLanes` is removed, and some refactoring is performed.
None
1. Set …

fix(lane_change): do not prematurely combine lane change lanes 

---

perception/tensorrt_yolox/src/tensorrt_yolox_node.cpp

- replace motorbike with motorcycle in the label map, so that it is consistent with autoware's classes.
https://tier4.atlassian.net/wiki/spaces/~459732634/pages/2806087707/20230630#tensorrt_yolox%E3%81%AEclass%E4%BF%AE%E6%AD%A3

fix(replace motorbike with motorcycle): fix yolox's labelmap

---

planning/behavior_path_planner/include/behavior_path_planner/utils/utils.hpp
planning/behavior_path_planner/src/utils/utils.cpp

add `getCurrentLanes` with backward/forward length args
psim
none
none

feat(behavior_path_planner): add getCurrentLanes with length args

---

planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
planning/behavior_path_planner/src/utils/start_planner/geometric_pull_out.cpp
planning/behavior_path_planner/src/utils/start_planner/shift_pull_out.cpp

Putting goal in after U-turn cut the path.
This is because current lanes is up to forward length and does not include the goal lane.
In this PR get curent lanes with max length to include goal lane.
[tier4 internal ticket](https://tier4.atlassian.net/browse/RT1-2885)
https://github.com/autowarefoundation/autoware.universe/pull/4108
psim
none
none …

fix(start_planner): fix path cut by U turn goal

---

planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/lane_change_module_data.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/lane_change_path.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/utils.hpp
planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
planning/behavior_path_planner/src/utils/lane_change/utils.cpp

Due to the wrong arguments for the path safety check, the lane change decision chatters.
This PR fixes the arguments, then fixes the oscillation.
**Before**
https://github.com/autowarefoundation/autoware.universe/assets/21360593/043fe53d-d0af-435b-91e6-b022cad5083f
**After**
https://github.com/autowarefoundation/autoware.universe/assets/21360593/b0c4991b-6622-4652-9d21-4f293241e3d7
[TIERIV internal scenario testing result](https://evaluation.tier4.jp/evaluation/reports/5f60bea1-b3fe-50b1-b0e3-6c9c3c7b7d7d?project_id=prd_jt)
Psim as in the video
Please check the code carefully
None
Lane change behavior will change in a better way
The PR author …

fix(lane_change): safety check chattering

---

launch/tier4_planning_launch/launch/scenario_planning/lane_driving/motion_planning/motion_planning.launch.py

Remove a hardcoded parameter in the motion planning launch file.
This prevented setting the parameter through its parameter file.
Tested in Psim.
Parameters of the obstacle_velocity_limiter are correctly set from its parameter file.

fix(obstacle_velocity_limiter): remove hardcoded parameter

---

planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp

Before this change, multiple lane change module can be registered.
To fix this, use `prev_module_path_` to get current lane instead of `prev_module_reference_path_`.
[TIER IV INTERNAL TEST](https://evaluation.tier4.jp/evaluation/reports/befc0b2e-b5a9-56af-8851-7ef1be256a15?project_id=prd_jt)
Nothing.
Nothing. …

fix(behavior_path_planner): use previous path for get current lane

---

system/default_ad_api_helpers/ad_api_adaptors/README.md

Fix readme to remove unused service.

docs(ad_api_adaptors): fix readme to remove unused service

---

planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp

In this PR, I fixed the issue that lane change does not activate turn signal at the end of the current lanes. 
[Screencast from 06-29-2023 02:02:34 PM.webm](https://github.com/autowarefoundation/autoware.universe/assets/43805014/da2ef4a4-588f-4eef-b21c-934908a6eed3)
PSim
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request- …

fix(lane_change): fix termianl lane chagne turn signal

---

planning/motion_velocity_smoother/src/motion_velocity_smoother_node.cpp

Add an acceleration limit to enable "engage on manual driving when accelerating". 
Run psim, and real vehicle experiment
enable "engage on manual driving when accelerating". 

fix(velocity_smoother): add acc limit on manual driving

---

planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp

If the lateral shift is too small and end pose is same to the current pose, start planner is finished before engage.
To prevent the module from finishing add offset.
[tier4_internal_slack](https://star4.slack.com/archives/CBX6XHKA4/p1687774550403939)
psim
none
none
none

feat(start_planner): add offset to not finish before engage

---

planning/behavior_path_planner/src/utils/drivable_area_expansion/drivable_area_expansion.cpp

When the drivable area is dynamically expanded, the z values were set to 0.
This PR fixes this issue by copying the z values from the original drivable area.
Tested in Psim
None

fix(behavior_path_planner): copy z in dynamic drivable area expansion

---

.github/workflows/update-codeowners-from-packages.yaml

Remove global codeowners. The repository rules now allows admins to bypass.
https://github.com/orgs/community/discussions/46626#discussioncomment-5731948

ci: remove global codeowners

---

localization/yabloc/yabloc_pose_initializer/download.cmake

Other packages that use artifacts, have a `DOWNLOAD_ARTIFACTS` option, so that they can be built without access to the internet (e.g. when built with Debian's `sbuild`). This PR adds such option and defaults it to `off`.
See https://github.com/autowarefoundation/autoware-deb-packages/issues/18 …

fix(yabloc_pose_initializer): disable downloading artifacts by default

---

planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp

if path is invalid, the lane change debug's visualization may not convey the proper information.
In this PR, it is fixed by updating the visualization before invalid path check.

fix(lane_change): fix visualization when path is invalid

---

planning/planning_validator/README.md

docs(planning_validator): add unit

---

control/control_performance_analysis/config/controller_monitor.xml
control/control_performance_analysis/config/error_rqt_multiplot.xml
control/pure_pursuit/config/pure_pursuit_lateral_controller_plotjuggler_debug.xml
control/trajectory_follower_node/config/plot_juggler_trajectory_follower.xml
planning/obstacle_cruise_planner/config/plot_juggler_obstacle_cruise_planner.xml
planning/obstacle_stop_planner/config/plot_juggler_adaptive_cruise.xml
planning/obstacle_stop_planner/config/plot_juggler_slow_down.xml
planning/planning_validator/config/planning_validator_plotjugler_config.xml
sensing/pointcloud_preprocessor/config/processing_time_ms.xml

Fixed typos in PlotJuggler config files.
Since I was not sure about the impact, I split the PR.
Related: https://github.com/autowarefoundation/autoware.universe/pull/3617

style: fix typos in PlotJuggler config files

---

.github/workflows/json-schema-check.yaml

Follow up to https://github.com/autowarefoundation/autoware-github-actions/pull/240
Leverage the [json-schema-check](https://github.com/autowarefoundation/autoware-github-actions/blob/main/json-schema-check/README.md) action from the autoware-github-actions repository.
Relates to https://github.com/autowarefoundation/autoware.universe/issues/2652
Made sure it ran fine and could fail on wrong files with: https://github.com/ambroise-arm/autoware.universe/actions/runs/5411918092
Will trigger the action on changes to schema and parameter files. …

ci: add JSON Schema validation

---

perception/radar_tracks_msgs_converter/README.md
perception/radar_tracks_msgs_converter/include/radar_tracks_msgs_converter/radar_tracks_msgs_converter_node.hpp
perception/radar_tracks_msgs_converter/src/radar_tracks_msgs_converter_node/radar_tracks_msgs_converter_node.cpp

I add the object orientation estimation from twist with ego vehicle motion compensation in `radar_tracks_msg_converter`.
And I solved wrong twist direction problem with orientation estimation.
According to this change, I refactor msg conversion function to prevent degradation from fixing.
Tests by rosbag. …

fix(radar_tracks_msg_converter): fix twist conversion

---

planning/behavior_path_planner/config/start_planner/start_planner.param.yaml
planning/behavior_path_planner/docs/behavior_path_planner_start_planner_design.md
planning/behavior_path_planner/include/behavior_path_planner/utils/start_planner/start_planner_parameters.hpp
planning/behavior_path_planner/src/scene_module/start_planner/manager.cpp
planning/behavior_path_planner/src/utils/start_planner/shift_pull_out.cpp

add option for lane departure
this PR deal with the issue that the path from the current pose is out of lane so backward driving unnaturally
psim
none
none

feat(start_planner): add option for lane departure

---

control/shift_decider/src/shift_decider.cpp

In the [current implementation](https://github.com/autowarefoundation/autoware.universe/blob/2424d6b770d9623e9ddadbeae32e6e8d32a67348/control/shift_decider/src/shift_decider.cpp#L89_L93) of shift_decider, the Autoware sends parking gear command only when the ```autoware_state``` is ```ARRIVED_GOAL```, then sends gear command according to current gear state.
However, in the case of using a vehicle that takes time to transition the gear state, the vehicle cannot complete a gear transition while the  ```autoware_state``` is ```ARRIVED_GOAL```. In such a case, the Autoware switches the gear command to ```DRIVING``` before the vehicle gear switches to parking.
As this would cause incorrect gear transition, I changed the gear command to keep the Parking after ```autoware_state``` switches from …

feat(shift_decider): keep parking gear command after the state transitions from arrived_goal

---

planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp

fix typo and remove unnecessary comment in goal_planner and start_planner
none
none
none
none

chore(behavior_path_planner): fix typo and remove unnecessary comment

---

planning/behavior_path_planner/include/behavior_path_planner/utils/utils.hpp
planning/behavior_path_planner/src/utils/utils.cpp

Add utils function to extend lanes with specific length
```
lanelet::ConstLanelets getExtendedCurrentLanes(
const std::shared_ptr<const PlannerData> & planner_data, const double backward_length,
const double forward_length);
```
psim
none
none

feat(behavior_path_planner): add getExtendedCurrentLanes with length args

---

perception/traffic_light_multi_camera_fusion/README.md

replace old msg type with new traffic signal type `autoware_perception_msgs::msg::TrafficSignalArray` in traffic_light_multi_camera_fusion/README.md
ref
- https://github.com/autowarefoundation/autoware.universe/blob/main/perception/traffic_light_multi_camera_fusion/src/node.cpp#L179
- https://github.com/autowarefoundation/autoware.universe/blob/main/perception/traffic_light_multi_camera_fusion/include/traffic_light_multi_camera_fusion/node.hpp#L77 …

docs: fix msg type in traffic_light_multi_camera_fusion/README.md

---

perception/traffic_light_arbiter/README.md

Fixed the incorrect datatype in README.md.
The correct datatype shoud be `TrafficSignalArray`.
https://github.com/autowarefoundation/autoware.universe/blob/main/perception/traffic_light_arbiter/src/traffic_light_arbiter.cpp#L58-L64

docs(traffic_light_arbiter): fix the datatype of input topics

---

common/tier4_autoware_utils/include/tier4_autoware_utils/geometry/boost_geometry.hpp
planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp
planning/behavior_velocity_crosswalk_module/src/scene_walkway.cpp
planning/behavior_velocity_crosswalk_module/src/scene_walkway.hpp
planning/behavior_velocity_crosswalk_module/src/util.cpp
planning/behavior_velocity_crosswalk_module/src/util.hpp

clean up the code of behavior_velocity_crosswalk_module
scenario simulator: https://evaluation.tier4.jp/evaluation/reports/3b6abef0-995f-5e5a-8cf2-83cfd5ec5289?project_id=prd_jt (no degradation)
nothing

refactor(behavior_velocity_crosswalk_module): clean up the code

---

planning/behavior_path_planner/config/dynamic_avoidance/dynamic_avoidance.param.yaml
planning/behavior_path_planner/include/behavior_path_planner/scene_module/dynamic_avoidance/dynamic_avoidance_module.hpp
planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp
planning/behavior_path_planner/src/scene_module/dynamic_avoidance/manager.cpp

Does not avoid objects by the dynamic avoidance module on the target lane of the ego's lane changing
does not avoid objects on the target lane of ego's lane changing

fix(dynamic_avoidance): ignore objects on LC target lane

---

perception/elevation_map_loader/src/elevation_map_loader_node.cpp

- The error occurs if there are appropriate .db3 files in directory for elevation map.
- I want to add error-handling code for this. After this PR, if the appropriate .db3 files are not found in the directory, `elevation_map_loader` removes directory and creates elevation map.
[TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/AEAP-655)
[TIER IV INTERNAL LINK2](https://star4.slack.com/archives/C4P0NSMB5/p1688621424237299?thread_ts=1688531806.996739&cid=C4P0NSMB5)
- Normal situations
```bash
❯ ros2 launch elevation_map_loader elevation_map_loader.launch.xml
[INFO] [launch]: All log files can be found below /autoware/.ros/log/2023-07-06-10-18-10-560789-dpc2006001-398871
[INFO] [elevation_map_loader-1]: process started with …
```

feat(elevation_map_loader): add error handling for std::runtime_error

---

launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.py
planning/behavior_path_planner/src/utils/drivable_area_expansion/drivable_area_expansion.cpp
planning/behavior_path_planner/src/utils/drivable_area_expansion/expansion.cpp
planning/behavior_path_planner/test/test_drivable_area_expansion.cpp

This PR reduces the cost of running the dynamic drivable area expansion.
Currently, the calculations are very heavy and do not scale well with the number of "uncrossable lines".
This PR improves the performances but do not completely solve the scaling issue.
Tested in Psim.
Running the dynamic drivable area expansion is less expensive, but the precision is reduced and the drivable area may  slightly cross some lines we do not want to cross (e.g., road borders). …

perf(behavior_path_planner): simplify calculateDistanceLimit for dynamic drivable area expansion

---

planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp

Fix mistake in get abort path function.

fix(behavior_path_planner): fix aborting duration

---

planning/behavior_path_planner/include/behavior_path_planner/utils/geometric_parallel_parking/geometric_parallel_parking.hpp
planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
planning/behavior_path_planner/src/utils/geometric_parallel_parking/geometric_parallel_parking.cpp
planning/behavior_path_planner/src/utils/goal_planner/geometric_pull_over.cpp
planning/behavior_path_planner/src/utils/goal_planner/goal_searcher.cpp
planning/behavior_path_planner/src/utils/goal_planner/shift_pull_over.cpp

Can not plan pull over path following lanes over next lanes because use only one next lane of current lanes for reference path.
In this PR extend current lanes by goal search length
https://github.com/autowarefoundation/autoware.universe/assets/39142679/9e64ec74-ca15-45aa-92f1-bf834c78f992
need https://github.com/autowarefoundation/autoware.universe/pull/4166
tie4_interl_sceneario_test
https://evaluation.tier4.jp/evaluation/reports/8d967fb3-de5c-5844-9a08-865792cc1c79?project_id=prd_jt
1575/1579
base line 1572/1579([2023/07/03](https://evaluation.tier4.jp/evaluation/reports/0ba7036a-3c90-5acf-92f2-ccbac699014f/?project_id=prd_jt))
psim 
https://github.com/autowarefoundation/autoware.universe/assets/39142679/864bb413-07fd-40e3-abbc-c1e1f7398419
none
none …

fix(goal_planner): support following lanes over the next lane

---

planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
planning/behavior_velocity_intersection_module/src/util.cpp
planning/behavior_velocity_intersection_module/src/util.hpp

https://github.com/autowarefoundation/autoware.universe/pull/3947
Sometimes `conflicting_lanelets` can be empty so can not calculate `adjacent_followings`  and `behavior_velocity_intersection_module` dies.

fix(behavior_velocity_intersection_module): behavior_velocity_intersection_module dies due empty conflicting_lanelets

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module.hpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

Improve avoidance module. It outputs avoidance path even when the path is judged as unsafe so that operator can execute it forcibly.
Nothing.

feat(avoidance): output avoidance path with unsafe flag when the yield is necessary

---

perception/image_projection_based_fusion/launch/roi_cluster_fusion.launch.xml
perception/image_projection_based_fusion/src/roi_cluster_fusion/node.cpp

update default value of `only_allow_inside_cluster` is `true` in `image_projection_based_fusion/roi_cluster_fusion`

feat(roi_cluster_fusion): update default value of `only_allow_inside_cluster` is `true`

---

planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp
planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp

Before this change, the stop point is inserted by lane change module if the lane change is required.
However, the section to lane change is too short, it is not able to insert stop point because the lane change module does not run.
To fix this problem, I changed to run lane change module if the ego vehicle is not in preferred lane.
[TIER IV INTERNAL TEST](https://evaluation.tier4.jp/evaluation/reports/44cb4bbf-cfcd-5da6-9c87-7bb75b9a03b7?project_id=prd_jt)
Nothing.
Nothing. …

fix(behavior_path_planner): fix execution request condition

---

control/shift_decider/include/shift_decider/shift_decider.hpp
control/shift_decider/src/shift_decider.cpp

If the target speed is around 0.01(```vel_threshold```) when Autoware engages, gear command may chatter on DRIVE and PARKING ( = ```current_gear_ptr_->report```).
Such gear command chattering can adversely affect hardware, so this PR prevents chattering by sending the same gear command as last time when the target speed is low.
no tests
none
none
This PR prevents chattering of gear command.
[pull …

fix(shift_decider): prevent chattering of gear command when target speed is near 0

---

planning/behavior_path_planner/src/utils/start_planner/shift_pull_out.cpp

While `Shift Pull Out` module in the start planner is planning for path, the path shifter's generation fails because the lateral shift distance is small during the start-up from the central line, resulting in the start_idx and end_idx being the same.
This PR aims to fix this by inserting non_shifted_path during the `start_idx - end_idx <= 1` situation.
None
In the start planner's param file, set `enable_back: false`
place ego pose as follows
```
position x: 61444.953125 
position y: 56224.13671875
orientation z: -0.0680803539122891
orientation w: 0.997679841137014
```
and goal pose as follows
``` 
position x: 61396.
position y: 56226.2
orientation z: 0.27939585430954345
orientation w: 0.9601760029258388
```
And confirm that `Shift Pull Out` module is running. 
Also the behavior path …

fix(start_planner): use non shifted path is shift line idx invalid

---

planning/behavior_path_planner/src/utils/path_utils.cpp

This PR improves the path resampling applied at the end of the `behavior_path_planner`. It considers the path end point for resampling to remove annoying resampling warn message:
```
[component_container_mt-27] The number of resampling intervals is less than 2
[component_container_mt-27] The number of resampling intervals is less than 2
[component_container_mt-27] The number of resampling intervals is less than 2
[component_container_mt-27] The number of resampling intervals is less than 2
[component_container_mt-27] The number of resampling intervals is less than 2
[component_container_mt-27] The number of resampling intervals is less than 2
``` …

fix(behavior_path_planner): fix sampling warning

---

common/autoware_ad_api_specs/README.md
common/component_interface_specs/README.md
common/component_interface_tools/README.md
common/tier4_api_utils/README.md
system/component_state_monitor/README.md

Add readme for packages without it.

docs: add readme for interface packages

---

common/autoware_auto_common/package.xml
common/autoware_auto_tf2/package.xml
common/autoware_testing/package.xml
common/fake_test_node/package.xml
common/time_utils/package.xml
evaluator/kinematic_evaluator/package.xml
evaluator/localization_evaluator/package.xml
planning/behavior_velocity_no_drivable_lane_module/package.xml
tools/simulator_test/simulator_compatibility_test/package.xml

Extract packages there is no TIER IV internal maintainer by following command.
`find ./ -name "package.xml" | xargs grep -L "maintainer.*@tier4.jp"`
Nothing.
Nothing.

chore: add maintainer

---

planning/obstacle_avoidance_planner/src/mpt_optimizer.cpp

fixes: https://github.com/autowarefoundation/autoware.universe/issues/4230
`vehicle_circles_bicycle_model_front_radius_ratio` and `vehicle_circles_bicycle_model_rear_radius_ratio` are given to `calcVehicleCirclesByBicycleModel` function in the wrong order.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request …

fix(obstacle_avoidance_planner): replace rear and front circle_radius_rate

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/start_planner/start_planner_module.hpp
planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp

The path is not well calculated when the goal is set behind from ego.
before:
Now since the plan for a backward direction is not supported, add a function in the start_planner to skip planning when the ego is behind from ego with a warning message.
after:
[TIERIV internal link](https://evaluation.tier4.jp/evaluation/reports/a478c75f-2615-544b-9a02-0a80a460aed4?project_id=prd_jt)
run psim
[Link for scenario test in TIERIV ](https://evaluation.tier4.jp/evaluation/reports/a478c75f-2615-544b-9a02-0a80a460aed4?project_id=prd_jt)
None
None
None …

fix(start_planner): publish stop path when goal is behind from ego

---

planning/behavior_velocity_planner_common/include/behavior_velocity_planner_common/utilization/arc_lane_util.hpp
planning/behavior_velocity_planner_common/package.xml

Add dependency for inline functions, which I removed in https://github.com/autowarefoundation/autoware.universe/pull/4229 by mistake.
Without this PR, some behavior_velocity_planner modules die.
Run psim

fix(behavior_velocity_planner_common): add depend for inline functions

---

planning/behavior_path_planner/src/scene_module/lane_change/avoidance_by_lane_change.cpp

For now, avoidance by lane change module doesn't work correctly so I fixed it.
It needs to set `direction_` properly to activate this module.
Psim
enable avoidance by lc module. ([here](https://github.com/autowarefoundation/autoware_launch/blob/518116062c2a49904bfa6d94c8aa0b32e905bc26/autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/scene_module_manager.param.yaml#L72))
```yaml
avoidance_by_lc:
enable_module: true
...
```
Nothing.
[contribution …

fix(avoidance_by_lc): fix execution requesting logic

---

planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/utils.hpp
planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
planning/behavior_path_planner/src/utils/lane_change/utils.cpp

Before this PR, `passParkedObject` function only activates when there is no candidate path. So in this PR, I changed the activation condition for the function.
[TIER IV INTERNAL LINK](https://evaluation.tier4.jp/evaluation/reports/2ead60e8-9840-5c60-a54a-3a902aa50099?project_id=prd_jt)
1562/1580 …

fix(lane_change): fix activation timing of the  passParkedObject funtion

---

planning/behavior_path_planner/src/utils/avoidance/utils.cpp

Fix invalid vector access. :pray: 
Psim
Nothing.

fix(avoidance): fix invalid vector access

---

planning/mission_planner/src/lanelet2_plugins/default_planner.cpp
planning/route_handler/src/route_handler.cpp

Add a warning message when the route plan is failed. Now it sometimes fails without any information nor warnings.

chore(route_handler): improve warning message

---

planning/behavior_path_planner/include/behavior_path_planner/utils/path_shifter/path_shifter.hpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
planning/behavior_path_planner/src/utils/path_shifter/path_shifter.cpp

Currently, avoidance module outputs avoidance path only when there is the sufficient longitudinal distance. But this limitation maybe cause stuck because the ego stopped at obstacle stop position in worst case.
In this PR, I improve the logic so that it outputs feasible shift path if the longitudinal distance between ego and object is **NOT** enough to shift target lateral length.
https://github.com/autowarefoundation/autoware.universe/assets/44889564/b6697e91-f9dd-4ea3-90e3-a1be9b38fa7e
Improve avoidance behavior …

feat(avoidance): output feasible avoidance path

---

planning/route_handler/src/route_handler.cpp

Fix for https://github.com/autowarefoundation/autoware.universe/issues/4254.
Modify the code in the route_handler to enable route plan when the ego is located out of the road_lanelet (e.g. road shoulder).
https://github.com/autowarefoundation/autoware.universe/issues/4254
- Run psim
- [TIERIV internal scenario test](https://evaluation.tier4.jp/evaluation/reports/a4ecc514-e90d-5f6b-b7ec-1bc4c50e31c5?project_id=prd_jt)
None
None
The route planning behavior changes. …

fix(route_handler): route plan failed when ego is on the road shoulder

---

planning/behavior_velocity_run_out_module/src/debug.cpp

Virtual wall marker of run out module didn't disappear because the deletion of stop pose was removed here.
https://github.com/autowarefoundation/autoware.universe/pull/3851/files#diff-530cf815b1cfc7b84fa40747b0dff416310bfd62b2c2530483b190a122fb9456L186
https://github.com/autowarefoundation/autoware.universe/assets/11865769/ec4ba12f-6e4d-4133-9493-66500e5e4846
I tested on a simple planning simulator.
https://github.com/autowarefoundation/autoware.universe/assets/11865769/06d5bdb4-429a-4f58-8721-f16737b020b7 …

fix(run_out): clear stop pose to prevent virtual wall from remaining

---

common/cuda_utils/README.md
common/object_recognition_utils/README.md
common/perception_utils/README.md
common/perception_utils/package.xml
common/tensorrt_common/README.md
common/traffic_light_utils/README.md
common/trtexec_vendor/README.md

Add README to the following packages
* perception_utils
* object_recognition_utils
* traffic_light_utils
* cuda_utils
* tensorrt_common
* trtexec_vendor

docs: add readme to perception related utils

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module.hpp
planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp

Close https://github.com/autowarefoundation/autoware.universe/issues/4178?notification_referrer_id=NT_kwDOAqz13LM2OTcyODU5NTcyOjQ0ODg5NTY0
If it fails to generate avoidance path, module doesn't update any previous data.
Nothing.

fix(avoidance): fix previous data inconsistency

---

common/motion_utils/src/vehicle/vehicle_state_checker.cpp
common/motion_utils/test/src/vehicle/test_vehicle_state_checker.cpp

Backport https://github.com/autowarefoundation/autoware.universe/pull/3883 to the `awsim-stable` branch to resolve the same issue.
Please refer to https://github.com/autowarefoundation/autoware.universe/pull/3883

chore: backport fix PR to awsim-stable branch

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/normal.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/utils.hpp
planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
planning/behavior_path_planner/src/utils/lane_change/utils.cpp

In order to reduce the arguments in the `getPrepareSegment`, `hasEnoughLength` and `getTargetObjects`, I moved them to the `NormalLaneChange` class. Therefore, it has two less arguments than before. Moreover, I removed a single `maybe unused` flag to clean the code.
1577/1588
[TIER IV Internal Link](https://evaluation.tier4.jp/evaluation/reports/aeee5948-c143-52b5-be1a-584ac0d2c446?project_id=prd_jt)
No effects.
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/cont …

refactor(lane_change): move several functions from lane change utils to NormalLaneChange

---

map/map_loader/test/test_pointcloud_map_loader_module.cpp

Fix spell-check
N/A
N/A
N/A
N/A
N/A

fix(map_loader): fix spell-check

---

planning/behavior_velocity_crosswalk_module/config/crosswalk.param.yaml
planning/behavior_velocity_crosswalk_module/src/debug.cpp
planning/behavior_velocity_crosswalk_module/src/manager.cpp
planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp
planning/behavior_velocity_crosswalk_module/src/util.hpp

NOTE: The behavior of the crosswalk module will not change with this PR
- minor refactoring
- create `ObjectInfoManager` to manage the object state (stopped, fully_stopped = can be yield, other)
- add option of `disable_stop_for_yield_cancel` not to wait while stopping for canceling yield
- set to false by default
- The flag can be set to true for more aggressive behavior
- launcher PR for https://github.com/autowarefoundation/autoware_launch/pull/449
- no degradation: https://evaluation.tier4.jp/evaluation/reports/0d3efa4d-ac33-53e5-9c01-827a6716d70a?project_id=prd_jt (1575/1588)
Nothing
The PR author …

feat(behavior_velocity_crosswalk_module): looser stop decision

---

planning/obstacle_avoidance_planner/src/node.cpp

When `enable_outside_drivable_area_stop` is false, which means no stop planning when the trajectory is outside the drivable area, currently we have no way to detect the trajectory outside the drivable area.
To detect it, with this PR, the virtual wall whose color is green will be published.
Nothing …

feat(obstacle_avoidance_planner): make virtual wall green when no stop planning

---

planning/behavior_velocity_crosswalk_module/src/debug.cpp

In order to see multiple text markers, I set the different z positions for each text marker.
with this PR
Nothing

feat(behavior_velocity_crosswalk_module): different z for each debug text marker

---

planning/behavior_path_planner/include/behavior_path_planner/parameters.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
planning/behavior_path_planner/src/utils/lane_change/utils.cpp
planning/behavior_path_planner/src/utils/utils.cpp

This PR aims to remove the minimum_prepare_length during lane changing process.
When ego stops at current lane's terminal point (where ego have to stop in order to secure minimum_lane_changing_length), current method allocate `minimum_prepare_length`. However, real world driving doesn't have such distance, and it confuses the surrounding vehicles, because they don't know what ego intention was.
None
Using PSIM
1576/1588
[TEIR IV Internal Link](https://evaluation.tier4.jp/evaluation/reports/54641e30-0940-51ed-957b-010c8b3b7b0b?project_id=prd_jt)
1. We still compute prepare buffer on the minimum_lane_change_length, to avoid various complicated issues.
None
None …

feat(lane_change): removing parameterize minimum prepare distance

---

perception/image_projection_based_fusion/include/image_projection_based_fusion/utils/geometry.hpp

[is_inside](https://github.com/autowarefoundation/autoware.universe/blob/55cb3d58e4e9f509258b384c17c7bba86d39d4c0/perception/image_projection_based_fusion/src/utils/geometry.cpp#L165-L174) function wrong declared in [geometry.hpp](https://github.com/autowarefoundation/autoware.universe/blob/main/perception/image_projection_based_fusion/include/image_projection_based_fusion/utils/geometry.hpp) file, it causes symbol lookup error. …

fix(image_projection_based_fusion): correct helper function parameter type

---

planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp

After setting a modified goal in the goal planner, if the module is deleted in the same cycle by the planner_manager, the modified goal may not be published.
e.g) [tier4 internal scenario](https://evaluation.tier4.jp/evaluation/reports/f8acdb79-281b-5130-9b25-a73f8ca541f4/tests/3cb509a0-b588-53fe-bd7d-85760982dd46/c429c756-9b8d-53db-8807-40f71c72a9f8/64b7a615-d815-51ce-981e-b4a22eff5ccb?project_id=prd_jt)
This happens when the start planner and goal planner are triggered in the first cycle when the goal is close to ego.
To solve this problem, I added a check in node to see if the modified goal has been published.
psim
none
none
The PR author …

fix(behavior_path_planner): check new modified goal in the node side

---

planning/behavior_path_planner/src/planner_manager.cpp

Support backward path drivable area.
before
after
psim
none
none

feat(behavior_path_planner): support backward path drivable area

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/normal.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/lane_change_module_data.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/lane_change_path.hpp
planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/utils.hpp
planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
planning/behavior_path_planner/src/utils/lane_change/utils.cpp

In the name lane change module, there are many variable name inconsistencies, especially for the lane names. In this PR, I used a unified rule to rename lane-related variables.
I use `current_lanes` and `target_lanes` for the lane change module to indicate the name of the lanes before and after lane change respectively. …

refactor(lane_change): fix lane change variable names inconsistency

---

planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
planning/behavior_velocity_intersection_module/src/scene_merge_from_private_road.cpp
planning/behavior_velocity_intersection_module/src/util.cpp
planning/behavior_velocity_intersection_module/src/util.hpp
planning/behavior_velocity_intersection_module/src/util_type.hpp

`IntersectionLanelets::tl_arrow_solid_on` was uninitialized and was not updated carelessly. Due to this bug when `left/right arrow` is not solid on when turning left/right each variable was like this when I debug printed.
```
tl_arrow_solid_on = 0, intersection_lanelets_.value().tl_arrow_solid_on = 144
```
So for most of the time when the path is covering the intersection [this condition](https://github.com/autowarefoundation/autoware.universe/blob/e282c4fe9b6acb6c98874665b2277375f0a6a70b/planning/behavior_velocity_intersection_module/src/scene_intersection.cpp#L656-L658) was true in every iteration. So `first_conflicting_area` was null at first, and then initialized to an area after a few iterations.
But if `lanelets_.value().tl_arrow_solid_on` is left _**uninitialized to 0**_, that …

fix(intersection): fix uninitialized tl_arrow_info variable issue

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/base_class.hpp
planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp
planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp

Because lane change cancel is instantaneous, it is difficult to see which object that cause the lane change to get cancelled.
In this PR, the lane change cancelled information is hold for 2 second, and the information is separated from before approval debug information.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributin …

fix(lane_change): separate visualization after path approval

---

planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp

If checking new modfied goal we need to use not uuid in the node but id of `GoalCandidate` in goal planner.
But id can not be got in the node side, so use the distance between current and previous modified goal.
psim, tier4 internal scenario  
https://evaluation.tier4.jp/evaluation/reports/5418fd51-a30c-5dcb-b620-f43fcb092d8c?project_id=prd_jt
1553/1588 -> 1570/1588
none
none …

fix(goal_planner): fix publishing new modified goal

---

planning/behavior_path_planner/src/utils/utils.cpp

When route lane is looped can not generate path with start_planner.
```
utils::getExtendedCurrentLanes(
planner_data_, backward_path_length, std::numeric_limits<double>::max());
```
In this PR, I added loop check to `getExtendedCurrentLanes`
psim
[
tier4 interanl sceanrio test](https://evaluation.tier4.jp/evaluation/reports/865da983-fb4f-5ea3-bd02-b80f9f27da0e?project_id=prd_jt)
none
none
[pull request …

fix(start_planner): fix loop lanes

---

common/tier4_autoware_utils/include/tier4_autoware_utils/geometry/geometry.hpp
common/tier4_autoware_utils/test/src/geometry/test_geometry.cpp

Added an intersect function that returns the intersection point from the two segments represented by four points.
This function is currently used in several packages since it is much faster than the boost one.
Unit test

feat(tier4_autoware_utils): add intersect function

---

localization/ndt_scan_matcher/src/map_update_module.cpp

In the previous PR, we erased 
```
last_update_position_ = res->pose_with_covariance.pose.pose.position;
```
by mistake, which is necesssary to update the last position where the map is updated (which is used as a reference when to update the map)
([See this line](https://github.com/autowarefoundation/autoware.universe/pull/4165#discussion_r1266571196))
This PR is to add the line in appropriate function.
https://github.com/autowarefoundation/autoware.universe/pull/4165
Ran Logging Simulator with a split map and a sample rosbag from tutorial, and confirmed that the dynamic map loading is working properly from both RViz and log.
Here's a map I used: [sample-map-rosbag_split.zip](https://github.com/autowarefoundation/autoware.universe/files/12079389/sample-map-rosbag_split.zip)
Please check …

fix(ndt_scan_matcher): update member variables properly in map_update_module

---

planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp
planning/behavior_velocity_crosswalk_module/src/util.hpp

- refactor the main function of `modifyPathVelocity` so that the calculation procedure can be easily understood.
- scenario simulator (no degradation)
- 1574/1588 https://evaluation.tier4.jp/evaluation/reports/795e6b48-5a73-5f56-a012-42d425bca3f8?project_id=prd_jt
Nothing …

refactor(behavior_velocity_crosswalk_module): clean up the code of stop line calculation

---

localization/yabloc/yabloc_particle_filter/src/correction/abstract_corrector.cpp

Fix a typo
N/A
None
None
None
None

fix(yabloc_particle_filter): fix typo

---

control/vehicle_cmd_gate/src/vehicle_cmd_filter.hpp
control/vehicle_cmd_gate/src/vehicle_cmd_gate.cpp

In the "vehicle_cmd_gate" module, the current practice is to use the actual longitudinal state of the vehicle (accel=0, speed=0) as the previous command value during a stop. However, this can occasionally lead to a decrease in the commanded acceleration, resulting in a slower start. So, I have made a modification to utilize the larger of the previous command value or the actual longitudinal state of the vehicle as the previous command value.
Before:
After:
The value of ```/control/command/control_cmd/longitudinal/acceleration``` has been improved to increase smoothly.
Tested by rosbag and logging_simulator (See description)
none
none
Improved departure delays …

fix(vehicle_cmd_gate): fix slow start

---

planning/behavior_velocity_crosswalk_module/src/debug.cpp
planning/behavior_velocity_crosswalk_module/src/manager.cpp
planning/behavior_velocity_crosswalk_module/src/manager.hpp
planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp
planning/behavior_velocity_crosswalk_module/src/scene_walkway.cpp
planning/behavior_velocity_crosswalk_module/src/scene_walkway.hpp
planning/behavior_velocity_crosswalk_module/src/util.cpp
planning/behavior_velocity_crosswalk_module/src/util.hpp

Depends on https://github.com/autowarefoundation/autoware.universe/pull/4284
use std::optional instead of boost::optional
Nothing

refactor(behavior_velocity_crosswalk_module): use std::optional instead of boost::optional

---

control/vehicle_cmd_gate/src/vehicle_cmd_gate.cpp

To enable longitudinal jerk filter when engaging. This PR modifies the control command output on MANUAL driving.
With this PR, the control command output will get a close value to the current ego velocity and acceleration, except for the case ego being stopped
None
tested on a real vehicle, and confirmed the filter works well.
None
None
With this PR, the control command output will get a close value to the current ego velocity and acceleration, except for the case ego being stopped
[contribution …

feat(vehicle_cmd_gate): improve transition filter for longitudinal

---

control/vehicle_cmd_gate/src/vehicle_cmd_gate.cpp

Fix the condition for the autonomous mode check
tested on a real vehicle
Behavior is improved when "autoware control is off but still operation mode is in AUTONOMOUS".

fix(vehicle_cmd_gate): auto mode check

---

planning/behavior_path_planner/config/lane_change/lane_change.param.yaml
planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/lane_change_module_data.hpp
planning/behavior_path_planner/src/scene_module/lane_change/manager.cpp
planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp

Add flags for the safety check in the lane change module to enable the user to select whether they want to use objects on the specific lanes.
[Launch PR](https://github.com/autowarefoundation/autoware_launch/pull/462)
PSim
No efffects

feat(lane_change): add safety check flags for lane change

---

launch/tier4_perception_launch/launch/object_recognition/prediction/prediction.launch.xml
launch/tier4_perception_launch/launch/perception.launch.xml

This PR refactors the map_based_prediction package for read parameters from autoware_launch config file.
autoware_launch PR: 
- https://github.com/autowarefoundation/autoware_launch/pull/463
Releated: 
- https://github.com/autowarefoundation/autoware.universe/issues/4250
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributi …

refactor(map_based_prediction): read parameters from autoware_launch

---

planning/obstacle_avoidance_planner/config/obstacle_avoidance_planner.param.yaml
planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/node.hpp
planning/obstacle_avoidance_planner/src/node.cpp

This PR is to add missing functionality of stop margin due to out of drivable area in `obstacle_avoidance_planner` since refactoring done in #2796 
closes #4190 
:exclamation: Must be merged with https://github.com/autowarefoundation/autoware_launch/pull/438 :exclamation: 
Same as mentioned in original PR : #2786 
Original PR : #2786 
Refactoring PR : #2796 
N.A.
Adding a margin for stop point when the the stop point is calculated for the footprint out of drivable area. …

fix(obstacle_avoidance_planner): adding missing functionality for stop margin due to out of drivable area

---

planning/behavior_velocity_intersection_module/src/scene_intersection.cpp

fixes: https://github.com/autowarefoundation/autoware.universe/issues/4153
`ego_lane_with_next_lane` only keeps 2 lanes and in some cases, the total length of these combined lanes may not be in the range of `start_arc_length` and `end_arc_length` calculated beforehand. now I add lanelets to `ego_lane_with_next_lanes` until the total length of added lanelets is between arc values.
https://github.com/autowarefoundation/autoware.universe/assets/32412808/fe7df7cf-45ac-40ba-b107-3602ec9ded02 …

fix(behavior_velocity_planner): expend the ego_lane_with_next_lane area

---

launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml
launch/tier4_perception_launch/launch/object_recognition/detection/lidar_based_detection.launch.xml
launch/tier4_perception_launch/launch/perception.launch.xml

This PR refactors the object_merger package for read parameters from autoware_launch config file.
autoware_launch PR: 
- https://github.com/autowarefoundation/autoware_launch/pull/464
Releated: 
- https://github.com/autowarefoundation/autoware.universe/issues/4250 …

refactor(object_merger): read parameters from autoware_launch
