autowarefoundation/autoware_universe

- planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
Since avoidance module keeps previous path and extend backward path length so that it inserts backward shift line, it needs to update backward path velocity.
Before this PR, ego tries keeping previous path velocity (=10km/h) unexpectedly even when lanelet's velocity limit is 15km/h.
https://github.com/autowarefoundation/autoware.universe/assets/44889564/176df641-0024-4fed-a42f-446c80774231
After this PR, ego can accelerate when the lanelet's velocity limit gets higher.
https://github.com/autowarefoundation/autoware.universe/assets/44889564/41e055b1-00b4-4bf5-87bf-26977c16551a
Nothing. …
> fix(avoidance): overwrite backward path velocity

- .github/workflows/build-and-test-differential.yaml
- https://github.com/autowarefoundation/autoware.universe/actions/runs/5622340681/job/15234819642
They are failing due to lack of disk space.
@mitsudome-r said:
> Regarding the failure is happening when it is downloading the docker size which is about 16 GB.
> However, GitHub only guarantee 14 GB according to https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
- https://github.com/orgs/autowarefoundation/discussions/3469
- https://github.com/autowarefoundation/autoware.universe/issues/4359 …
> chore(workflows): update build-and-test-differential to use self hosted runners

- planning/behavior_velocity_out_of_lane_module/src/debug.cpp
The `behavior_velocity_planner` can crash if the `out_of_lane` module cannot calculate its current footprint.
This PR removes this crash.
Psim
Prevents crashes of the `behavior_velocity_planner`.
> fix(out_of_lane): prevent crash when current footprint is empty

- .github/workflows/build-and-test-differential.yaml
https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners#self-hosted-runner-security
It seems like it is preferred not to use self-hosted-runners to avoid running malicious codes on our runners.
As a quick safety guard, this change will make the build check to run only when label is added by members in AutowareFoundation.
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contri …
> ci: add label checks before running self-hosted runner

- perception/image_projection_based_fusion/docs/roi-cluster-fusion.md
- perception/image_projection_based_fusion/include/image_projection_based_fusion/roi_cluster_fusion/node.hpp
- perception/image_projection_based_fusion/launch/roi_cluster_fusion.launch.xml
- perception/image_projection_based_fusion/src/roi_cluster_fusion/node.cpp
This is to modify existence probability of unknown objects based on unknown roi from camera-based object detection model to differentiate with some kind of ghost pointcloud or exhausted gas poincloud unknown objects. 
[TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT1-976)
Perforamce is confirmed by Lsim …
> fix(roi_cluster_fusion): fuse unknown roi

- planning/behavior_path_planner/src/utils/start_planner/geometric_pull_out.cpp
fix geometric pull out start pose
tihs causes wrong turn signal
not tested 
none
none
> fix(start_planner): fix geometric pull out start pose

- common/perception_utils/include/perception_utils/prime_synchronizer.hpp
```
/home/satoshi/pilot-auto/install/perception_utils/include/perception_utils/prime_synchronizer.hpp:348:10: error: ‘perception_utils::PrimeSynchronizer<tier4_perception_msgs::msg::TrafficSignalArray_<std::allocator<void> >, tier4_perception_msgs::msg::TrafficLightRoiArray_<std::allocator<void> >, sensor_msgs::msg::CameraInfo_<std::allocator<void> >, sensor_msgs::msg::PointCloud2_<std::allocator<void> > >::max_delay
_t_’ will be initialized after [-Werror=reorder] …
```
> fix(perception_utils): fix `-Werror=reorder`

- planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/mpt_optimizer.hpp
- planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/node.hpp
- planning/obstacle_avoidance_planner/src/mpt_optimizer.cpp
- planning/obstacle_avoidance_planner/src/node.cpp
In order to easily use optimization path planner in packages other than obstacle_avoidance_planner, this PR makes the output of MPT's output not std::optional by holding the previous optimized result not in the node itself but in the MPT class.
- scenario simulator (no degradation)
- https://evaluation.tier4.jp/evaluation/reports/e3283471-b1ad-5aa6-8411-3b60f12930fe?project_id=prd_jt
Nothing
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/cont …
> feat(obstacle_avoidance_planner): make MPT's output not std::optional

- planning/behavior_path_planner/src/utils/avoidance/utils.cpp
- planning/behavior_path_planner/src/utils/utils.cpp
- planning/obstacle_avoidance_planner/src/mpt_optimizer.cpp
Depends on https://github.com/autowarefoundation/autoware.universe/pull/4312
use tier4_autoware_utils::intersect instead of defining the function in the node package.
Nothing
> refactor: use tier4_autoware_utils::intersect

- planning/path_smoother/include/path_smoother/elastic_band.hpp
- planning/path_smoother/include/path_smoother/elastic_band_smoother.hpp
- planning/path_smoother/src/elastic_band.cpp
- planning/path_smoother/src/elastic_band_smoother.cpp
- In order to easily use optimization path smoother in packages other than path_planner,
- make EB's output not std::optional by holding the previous optimized result not in the node itself but in the EB class.
- remove PlannerData struct
- minor refactoring
- scenario simulator (no degradation)
- https://evaluation.tier4.jp/evaluation/reports/e3283471-b1ad-5aa6-8411-3b60f12930fe?project_id=prd_jt
Nothing …
> feat(path_smoother): make EB's output not std::optional

- planning/behavior_path_planner/src/planner_manager.cpp
- planning/route_handler/include/route_handler/route_handler.hpp
- planning/route_handler/src/route_handler.cpp
Update root_lanelet_ if it is not in route lanelet.
Rerouging with modified goal update route_laneles, but if following lanes of previous root_lalet contains new root_lanelet_, that is not updated.  This is happen when the previos root_lanelet is before new root lanelets.
```
// check ego is in next lane
const auto next_lanelets = route_handler->getRoutingGraphPtr()->following(root_lanelet_.get());
for (const auto & next : next_lanelets) {
if (next.id() == root_lanelet.id()) {
return;
}
}
```
In a result root_lanelet is not in route_lanels and this causes empty lanelet sequence in 
```
const auto lanelet_sequence = route_handler->getLaneletSequence(
root_lanelet_.get(), pose, backward_length, std::numeric_limits<double>::max());
``` …
> fix(behavior_path_planner): update root lanele if it is not in route lanelet

- sensing/gnss_poser/README.md
- sensing/gnss_poser/include/gnss_poser/gnss_poser_core.hpp
- sensing/gnss_poser/launch/gnss_poser.launch.xml
- sensing/gnss_poser/src/gnss_poser_core.cpp
Adding feature reffered: #4188
This PR offers three options for publishing gnss_pose:
1. Publish coming data immediately (buffer_epoch does not have effect on algorithm).
2. Publish median of the buffer (buffer_epoch setted by user).
3. Publish average value of the poses in the buffer (buffer_epoch setted by user).
All added options runned through logging simulator. 
Different GNSS/INS sensors different accuracies, user should be able to choose the most suitable buffer size and gnss pose publish method for themselves.
The Reviewers **must** check the checkboxes below before approval. …
> feat(gnss_poser): options for gnss pose pub method

- planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/common_structs.hpp
- planning/obstacle_avoidance_planner/src/debug_marker.cpp
- planning/obstacle_avoidance_planner/src/node.cpp
This PR is to add missing functionality of footprint marker in `obstacle_avoidance_planner` since refactoring done in https://github.com/autowarefoundation/autoware.universe/pull/2796 . 
closes #4190 
Same as mentioned in original PR : https://github.com/autowarefoundation/autoware.universe/pull/2689
Original PR : https://github.com/autowarefoundation/autoware.universe/pull/2689
Refactoring PR : https://github.com/autowarefoundation/autoware.universe/pull/2796
N.A.
This PR creates a separate footprint marker and appends it to `marker_array` in `obstacle_avoidance_planner` for easier debugging. …
> fix(obstacle_avoidance_planner): adding missing functionality for footprint marker

- launch/tier4_perception_launch/launch/object_recognition/tracking/tracking.launch.xml
- launch/tier4_perception_launch/launch/perception.launch.xml
- launch/tier4_perception_launch/package.xml
This PR provides tracking for far objects with radar sensor input generated with https://github.com/autowarefoundation/autoware.universe/pull/4330.
To launch radar object tracking node, be sure to set `object_recognition_tracking_radar_object_tracker_data_association_matrix_param_path` and 
`object_recognition_tracking_radar_object_tracker_tracking_setting_param_path`, which represent association settings and tracking settings.
Tested in sample rosbag.
Remember to merge https://github.com/autowarefoundation/autoware_launch/pull/470 at the same time.
Default logsim will try to publish radar tracking results. …
> feat(tier4_perception_launch): add radar tracking node to launcher

- launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml
- launch/tier4_perception_launch/launch/object_recognition/detection/lidar_based_detection.launch.xml
- launch/tier4_perception_launch/launch/perception.launch.xml
- perception/image_projection_based_fusion/launch/pointpainting_fusion.launch.xml
This PR provides migrating lidar detection model parameters from autoware_launch
Releated: https://github.com/autowarefoundation/autoware.universe/issues/4250
- autoware_launch PR: https://github.com/autowarefoundation/autoware_launch/pull/450
> refactor(image_projection_based_fusion): read lidar models parameters from autoware_launch

- planning/obstacle_avoidance_planner/src/node.cpp
When `enable_outside_drivable_area_stop` is false, it is expected that the stop point is not inserted but it is inserted.
This PR fixes this issue.
Stop point insertion by obstacle_avoidance_planner
> fix(obstacle_avoidance_planner): not insert stop point according to the option

- planning/obstacle_cruise_planner/include/obstacle_cruise_planner/common_structs.hpp
- planning/obstacle_cruise_planner/src/node.cpp
- planning/obstacle_cruise_planner/src/planner_interface.cpp
Without this PR, the start/end virtual walls are visualized for slow down, which becomes messy with a lot of obstacles.
This PR makes the slow down virtual wall single as follows.
**Before this PR**
**After this PR**
Before reaching the slow down start position, the virtual wall is visualized at the slow down start position.
While planning slow down, the virtual wall is visualized at the front of the ego position.
Nothing …
> feat(obstacle_cruise_planner): single slow down virtual wall

- launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml
- launch/tier4_perception_launch/launch/perception.launch.xml
This PR changes ```image_projection_based_fusion``` package input rois arguments workflow. After the this PR input rois topic names migrated from ```perception.launch.xml```.
releated: #4250 
> refactor(image_projection_based_fusion): update rois topic names definitions

- perception/map_based_prediction/include/map_based_prediction/map_based_prediction_node.hpp
- perception/map_based_prediction/src/map_based_prediction_node.cpp
This PR is aiming to generate prediction path from/to a shoulder lanelet, which is unconnected in routing graph.
Implemented algorithm has following architecture:
- left/right shoulder lane prediction(center path prediction has similar architecture)
- when two lanelet shares left/right linestring, we judge these lanelets have neighbor relationships
- a lanelet is considered as "isolated" when it does not have any left/right/following lanelet
- when lanelet length is not enough, predicted path could be oddly curved
- validation tries to evaluate the lanelet has enough lane length
- minimum lanelet length is calculated by `obj linear velocity * time_horizon * rate`
- In default, time_horizon is `10` [s] and rate is `0.8`
Tested in psim.
I'll show edge cases:
| cases |result image | 
|--|--| …
> feat(map_based_prediction): enable prediction to/from shoulder lanelet (lanelet not in routing graph)

- launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml
- launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_radar_fusion_based_detection.launch.xml
- launch/tier4_perception_launch/launch/object_recognition/detection/lidar_based_detection.launch.xml
- launch/tier4_perception_launch/launch/perception.launch.xml
- perception/euclidean_cluster/launch/voxel_grid_based_euclidean_cluster.launch.py
- perception/euclidean_cluster/launch/voxel_grid_based_euclidean_cluster.launch.xml
This PR to add option of unuse downsampling pointcloud to improve density of Euclidean Cluter (EC) input pointcloud. 
In the result, small object detection perfomance could be improved. 
| Pipeline before update | Pipeline after update|
| --- | --- |
|![image](https://github.com/autowarefoundation/autoware.universe/assets/94814556/a18fe328-7fec-49b5-b379-0a025366e556)|![image](https://github.com/autowarefoundation/autoware.universe/assets/94814556/45f20731-7b15-4908-b9fc-306eb53f3747)|
[TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT1-3051)
In spire of number of pointcloud input into Euclidean Cluster is increased, the simplified pipeline after change shows no increase of delay time between Ground_segmentation node and Euclidean Cluster node. The result was confirmed by …
> fix(euclidean_cluster): add disuse downsample in clustering pipeline

- planning/behavior_path_planner/config/dynamic_avoidance/dynamic_avoidance.param.yaml
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/dynamic_avoidance/dynamic_avoidance_module.hpp
- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp
- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/manager.cpp
- Avoid a wider range of objects (not only objects in the neighbour lanelets)
- Not avoid objects crossing the ego's path
- minor refactoring
Nothing
> feat(dynamic_avoidance): consider a wider range of objects

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/dynamic_avoidance/dynamic_avoidance_module.hpp
Fixed a bug of updating the existing object. How to deal with the unordered map was wrong.
Nothing
> fix(dynamic_avoidance): fix bug of emplacing existing object

- .github/workflows/spell-check-partial.yaml
Until now, `spell-check-partial` checked changed files only.
But especially when you update update the scope of `spell-check-partial`, the result of `spell-check-partial` is not appropriate.
To resolve this problem, it is reasonable to check all files in `spell-check-partial`.
In most cases, `spell-check-partial` checks more files than needed, but that's not a problem since the files in scope of `spell-check-partial` already have no errors. …
> chore(spell-check-partial): enable for unchanged files

- planning/behavior_path_planner/include/behavior_path_planner/planner_manager.hpp
- planning/behavior_path_planner/src/planner_manager.cpp
Add an error handling when the module output is `null`.
Without this code, some modules may die due to invalid memory access.
Run psim
> feat(behavior_path_planner): add error handling for null output

- planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
not finish start planner when the path is not safe.
psim
[tier4 internal scneario test](https://evaluation.tier4.jp/evaluation/reports/c34af852-c3f8-51eb-87cd-ac35a9dc428d/?project_id=prd_jt)
none
none
> fix(start_planner): not finish start planner when the path is not safe

- planning/behavior_velocity_stop_line_module/README.md
- planning/behavior_velocity_stop_line_module/config/stop_line.param.yaml
- planning/behavior_velocity_stop_line_module/src/debug.cpp
- planning/behavior_velocity_stop_line_module/src/manager.cpp
- planning/behavior_velocity_stop_line_module/src/scene.hpp
Remove unnecessary and unused parameters. Also, rename a parameter to make it easier for users to understand. I also updated the parameter explanation part of the behavior velocity stop line module document.
[Related PR](https://github.com/autowarefoundation/autoware_launch/pull/475)
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/ma …
> refactor(behavior_velocity_stop_line_module): clean stop line module

- perception/image_projection_based_fusion/src/fusion_node.cpp
revert the swap of postprocess and publish
> fix(image_projection_based_fusion): revert the swap of postprocess and publish

- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
closes #4409 
Confirmed via created scenario. Please follow [issue description](https://github.com/autowarefoundation/autoware.universe/issues/4409#issue-1822539134) -> Steps to reproduce
https://github.com/autowarefoundation/autoware.universe/assets/48479081/5c6e6144-d570-40b7-a2d6-6709154c478b
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/c …
> fix(bpp-goal_planner): fix turn signal info for the right side pulling over

- planning/path_smoother/CMakeLists.txt
- planning/path_smoother/config/elastic_band_smoother.param.yaml
- planning/path_smoother/include/path_smoother/common_structs.hpp
- planning/path_smoother/include/path_smoother/elastic_band_smoother.hpp
- planning/path_smoother/include/path_smoother/replan_checker.hpp
- planning/path_smoother/include/path_smoother/type_alias.hpp
- planning/path_smoother/src/elastic_band_smoother.cpp
- planning/path_smoother/src/replan_checker.cpp
Copy the `ReplanChecker` from the `obstacle_avoidance_planner` in order to improve the performance of the `path_smoother`.
Also needs launch PR: https://github.com/autowarefoundation/autoware_launch/pull/482
Psim.
CPU usage before: 200-300%.
CPU usage after: 30-60%.
None
> perf(path_smoother): add ReplanChecker to decrease computation cost

- perception/traffic_light_occlusion_predictor/src/nodelet.cpp
- Fix the bug that causes traffic_light_occlusion_predictor to fall
Considering in_roi_msg could be nullptr, it would cause break down when it's called
Nothing.
Nothing.
> fix(traffic_light_occlusion_predictor): bug fix

- perception/traffic_light_arbiter/include/traffic_light_arbiter/traffic_light_arbiter.hpp
- perception/traffic_light_arbiter/src/traffic_light_arbiter.cpp
publish traffic light info even when a map without traffic lights is subscribed
I tested as below.
- launch traffic_light_arbiter
```
$ros2 launch traffic_light_arbiter traffic_light_arbiter.launch.xml 
```
- publish map without traffic lights
- publish /external/traffic_light_recognition/traffic_signals 
```
$ros2 topic pub /external/traffic_light_recognition/traffic_signals autoware_perception_msgs/msg/TrafficSignalArray {}
```
- confirm that traffic_signals messages are published by traffic_light_arbiter
```
$ ros2 topic echo /perception/traffic_light_arbiter/traffic_signals
```
Even when you use a map without traffic light, traffic_light_arbiter will publish traffic light info.
( When you use a map with traffic light, this PR has no effects on system behavior. ) …
> fix(traffic_light_arbiter): publish traffic light info even when a map without traffic lights is subscribed

- launch/tier4_perception_launch/launch/traffic_light_recognition/traffic_light.launch.xml
- perception/traffic_light_arbiter/launch/traffic_light_arbiter.launch.xml
Previously, arguments were not passed from traffic_light.launch.xml to traffic_light_arbiter.launch.xml, causing some unexpected behavior.
With the changes in this PR, that problem has been solved. The system now works as expected.
Tested by AWSIM
none
none
none
> fix(traffic_light): fix traffic_light_arbiter pipeline

- launch/tier4_perception_launch/launch/traffic_light_recognition/traffic_light.launch.xml
fix typo of tier4_perception_launch
spell check
Nothing
> chore(tier4_perception_launch): fix typo

- localization/yabloc/yabloc_particle_filter/CMakeLists.txt
- localization/yabloc/yabloc_pose_initializer/CMakeLists.txt
From ROS 2 humble, `rosidl_target_interfaces` is deprecated: ref. https://github.com/ros2/rosidl/pull/606
Some packages adapt this changes by using `rosidl_get_typesupport_target` + version checking like [this](https://github.com/autowarefoundation/autoware.universe/blob/main/control/control_performance_analysis/CMakeLists.txt#L41-L52), but yabloc does not.
This PR introduce `rosidl_get_typesupport_target` + version checking to yabloc packages.
Not applicable for behavior. Build succeeded. …
> refactor(yabloc): replace deprecated rosidl API

- planning/behavior_path_planner/config/dynamic_avoidance/dynamic_avoidance.param.yaml
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/dynamic_avoidance/dynamic_avoidance_module.hpp
- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp
- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/manager.cpp
Depends on https://github.com/autowarefoundation/autoware.universe/pull/4390
Avoid cut-in objects if they are close to the ego.
Nothing
> fix(dynamic_avoidance): avoid cut-in object close to the ego

- .github/workflows/openai-pr-reviewer.yaml
Add label check to run Open AI PR reviewer
Bug fix: Added label check to run Open AI PR reviewer in `.github/workflows/openai-pr-reviewer.yaml`.
> "A bug was found, a fix was made,
> Now labels are checked, no more mistakes.
> Open AI PR …
> ci: add prevent-no-label-execution for openai-pr-reviewer

- perception/map_based_prediction/src/map_based_prediction_node.cpp
Fix several typos in the map based prediction module
> refactor(map_based_prediction): fix typo

- perception/image_projection_based_fusion/src/roi_cluster_fusion/node.cpp
This PR to fix bug of roi_cluster_fusion node died when empty pointcloud is published.
> fix(roi_cluster_fusion): fix roi_cluster_fusion died bug

- planning/behavior_velocity_intersection_module/CMakeLists.txt
- planning/behavior_velocity_intersection_module/config/intersection.param.yaml
- planning/behavior_velocity_intersection_module/package.xml
- planning/behavior_velocity_intersection_module/src/debug.cpp
- planning/behavior_velocity_intersection_module/src/manager.cpp
- planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
- planning/behavior_velocity_intersection_module/src/scene_intersection.hpp
- planning/behavior_velocity_intersection_module/src/util_type.hpp
This feature replaces the occlusion grid with occlusion polygon and filtering based on its size.
[Tier IV COMPANY INTERNAL LINK](https://tier4.atlassian.net/browse/RT1-2754)
launcher PR: https://github.com/autowarefoundation/autoware_launch/pull/485
Psim
https://github.com/autowarefoundation/autoware.universe/assets/28677420/f44e87d0-6919-4fac-a1e2-2e4d37771f93
[pull …
> feat(intersection): extract occlusion contour as polygon

- launch/tier4_perception_launch/launch/object_recognition/detection/pointcloud_map_filter.launch.py
- perception/compare_map_segmentation/CMakeLists.txt
- perception/compare_map_segmentation/README.md
- perception/compare_map_segmentation/include/compare_map_segmentation/voxel_grid_map_loader.hpp
- perception/compare_map_segmentation/package.xml
- perception/compare_map_segmentation/src/voxel_grid_map_loader.cpp
- perception/euclidean_cluster/launch/euclidean_cluster.launch.py
- perception/euclidean_cluster/launch/voxel_grid_based_euclidean_cluster.launch.py
- Change the topic to obtain ego-vehicle position in dynamic map loader mode of compare map segmentation.
[TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT1-3245)
- Confirm map comparing result using Logging_simulor.
> fix(compare_map_segmentation): change to using kinematic_state topic

- planning/behavior_path_planner/include/behavior_path_planner/utils/utils.hpp
- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
- planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
- planning/behavior_path_planner/src/utils/goal_planner/geometric_pull_over.cpp
- planning/behavior_path_planner/src/utils/goal_planner/goal_searcher.cpp
- planning/behavior_path_planner/src/utils/goal_planner/shift_pull_over.cpp
- planning/behavior_path_planner/src/utils/start_planner/geometric_pull_out.cpp
- planning/behavior_path_planner/src/utils/start_planner/shift_pull_out.cpp
- planning/behavior_path_planner/src/utils/start_planner/util.cpp
- planning/behavior_path_planner/src/utils/utils.cpp
solve https://github.com/autowarefoundation/autoware.universe/issues/4391
The current_lanes variable currently only includes lanes within a forward_path_length of 300m, and next lanes are determined by extendNextLane. However, if there is more than one candidate for the next lane, and if an incorrect lane is added, the arc coordinates of the goal cannot be calculated correctly. In this PR, we've added the next lane in route_lanes to the extended lanes, if that lane exists. We've also fixed the loop check to only verify start lanes rather than all extended lanes. This is because sometimes the target next lane for extension is the same as the previously extended lanes, which causes a failure in adding the lane. This same issue can result in goal arc coordinates not being calculated …
> fix(start_planner): fix path generation for separated lanes and extended loop lanes

- planning/behavior_path_planner/include/behavior_path_planner/utils/start_planner/shift_pull_out.hpp
- planning/behavior_path_planner/src/utils/start_planner/shift_pull_out.cpp
https://github.com/autowarefoundation/autoware.universe/pull/4418 surfaces potential bugs in loop route path generation.
this is because the extended road lanes has previous lanes of current lanes, and the goal and current pose arc corrdinates are caluculated wrongly. This lead to wrong hasEnoughDistance judgement.
In this PR remove the hasEnoghDistance because currently the distance is calculated validly like https://github.com/autowarefoundation/autoware.universe/pull/4005
https://github.com/autowarefoundation/autoware.universe/pull/4418
[tier4 internal scenario test](https://evaluation.tier4.jp/evaluation/reports/bbc8f39a-8f83-59f3-a725-fa4771960e35?project_id=prd_jt) 1580/1588
base:
1577/1588([2023/07/30](https://evaluation.tier4.jp/evaluation/reports/d1ec5471-3332-5f7c-9203-6d40ef0f27 …
> fix(start_planner): remove shift pull out enough distance check

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/dynamic_avoidance/dynamic_avoidance_module.hpp
- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp
Without this PR, which side to avoid is calculated by the ego's pose and object's pose.
This implementation cannot deal with the case where the ego's path and object's path will cross and which side to avoid is the opposite to the expected side.
With this PR, which side to avoid is calculated by the future ego's pose and object's pose when the collision will occur.
Nothing
[pull …
> feat(dynamic_avoidance): calculate which side to avoid more accurately

- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp
Revert https://github.com/autowarefoundation/autoware.universe/pull/3926
The color of dynamic avoidance has changed from purple to pink for better visibility on Rviz.
The pink color is not used by any other modules now.
planning simualtor
Nothing
> chore(dynamic_avoidance): revert debug marker's color

- map/map_loader/src/lanelet2_map_loader/lanelet2_map_visualization_node.cpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/goal_planner/goal_searcher.hpp
- planning/behavior_path_planner/src/utils/goal_planner/goal_searcher.cpp
Support no_parking_area not only no_stopping_area for goal search
Currently `no_stopping_area` is used for the area where the ego vehicle cannot arrive when pull over. 
related: https://github.com/autowarefoundation/autoware.universe/pull/2492
But it is different from the original use of `no_stopping_area`, so create new `no_parking_area` and will use it in pull_over
the difference between `no_stopping_area` and `no_parking_area`
- `no_stopping_area` is an area where stopping for even a few seconds is not allowed. Stopping due to traffic congestion or waiting at traffic lights is also prohibited. This area is used by `no_stopping_area` module.
- `no_parking_area` is an area where only parking is prohibited. Stopping due to traffic congestion or waiting at traffic lights is not included. …
> feat(goal_planner): add no_parking_area for goal search

- planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
- planning/behavior_velocity_intersection_module/src/scene_intersection.hpp
publish decision status as `std_msg::String`
Psim
> chore(intersection): publish decision status string

- .github/workflows/build-and-test-differential.yaml
This reverts commit 862830d3e670b2962b7c7eaccb2f1266f5c5bc25.
https://github.com/autowarefoundation/autoware.universe/pull/4413#issuecomment-1659057310
> chore(ci): revert "use ec2 for build-and-test-differential (#4413)"

- perception/traffic_light_arbiter/src/traffic_light_arbiter.cpp
I think `latest_perception_msg_` should be cleared here instead of `latest_external_msg_`.
https://github.com/autowarefoundation/autoware.universe/pull/4464/files#diff-8488136a70c0a6c2330c7db712a8d69c5e2111f1b7f83477e67a99887933ca4dR102
I confirmed that this node works by following these steps.
- launch traffic_signal_arbiter
```
ros2 launch traffic_light_arbiter traffic_light_arbiter.launch.xml
```
- publish traffic signal message to `/external/traffic_signals`
- check the output topic of this node. …
> fix(traffic_light_arbiter): clear perception msg when the stamp is over the tolerance

- planning/behavior_velocity_crosswalk_module/config/crosswalk.param.yaml
- planning/behavior_velocity_crosswalk_module/src/manager.cpp
- planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
- planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp
TIER IV internal ticket: https://tier4.atlassian.net/browse/RT1-3240
Suppress sudden stop for stuck vehicle detection in crosswalk module by adding min_acc, max_jerk and min_jerk.
Normal case.
If the stop for stuck vehicle detection is required suddenly, the stop point is inserted forward.
suppress sudden stop for stuck vehicle detection in crosswalk module …
> feat(behavior_velocity_crosswalk_module): suppress sudden stop for stuck vehicle

- planning/behavior_velocity_intersection_module/config/intersection.param.yaml
- planning/behavior_velocity_intersection_module/src/manager.cpp
- planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
- planning/behavior_velocity_intersection_module/src/scene_intersection.hpp
https://tier4.atlassian.net/browse/RT1-3244
launcher PR: https://github.com/autowarefoundation/autoware_launch/pull/492
Psim and experiment
> feat(intersection_occlusion): ignore occlusion behind parked vehicles on the attention lane

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/start_planner/start_planner_module.hpp
- planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
backward extended lanes are added to drivable lanes and this causes unintentional cut overlapped path
```
[component_container_mt-27] target_drivable_lanes: right: 179452left: 179452middle :
[component_container_mt-27] right: 179280left: 179280middle :
[component_container_mt-27] right: 190756left: 190757middle :
[component_container_mt-27] right: 179382left: 190720middle :
[component_container_mt-27] right: 179398left: 190609middle :
[component_container_mt-27] right: 179416left: 179443middle :
[component_container_mt-27] right: 190784left: 190785middle :
[component_container_mt-27] right: 190797left: 190794middle :
[component_container_mt-27] right: 190802left: 190801middle :
[component_container_mt-27] right: 177680left: 190615middle :
```
In this PR, use path point lane ids to …
> fix(start_planner): fix drivable lanes

- planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
- planning/behavior_velocity_intersection_module/src/scene_intersection.hpp
- planning/behavior_velocity_intersection_module/src/util.cpp
If `intersection_occlusion` stop line is ahead of the `pass_judge_line`, ego vehicle might possibly skip collision checking.
https://tier4.atlassian.net/browse/RT1-2844
Psim and experiment
> feat(intersection): disable pass judge decision while peeking

- planning/behavior_path_planner/config/avoidance/avoidance.param.yaml
- planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/avoidance_module_data.hpp
- planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
- planning/behavior_path_planner/src/scene_module/avoidance/manager.cpp
Add new parameter `remain_buffer_distance` in order to keep constant remaining distance between avoidance end point and path end point.
Please approve :arrow_down: before this PR.
https://github.com/autowarefoundation/autoware_launch/pull/493
https://github.com/autowarefoundation/autoware.universe/assets/44889564/909612c8-e7b1-4718-95e7-a0034367e66f …
> feat(avoidance): add parameter to configurate avoidance return point

- planning/behavior_velocity_crosswalk_module/config/crosswalk.param.yaml
- planning/behavior_velocity_crosswalk_module/src/manager.cpp
- planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
- planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp
Depends on https://github.com/autowarefoundation/autoware.universe/pull/4463
Add an option to disable yield for new stopped object.
This option is to achieve aggressive behavior for complex scenes as follows.
In this situation, the pedestrians often appear or disappear due to occlusion and perception's performance limitation.
In order not to yield for 3 seconds for new appeared pedestrians, this option will be useful.
- planning simualtor
- no degradation: https://evaluation.tier4.jp/evaluation/reports/189b1cc2-4f1b-51d0-b819-d6aea0553d20?project_id=prd_jt
Nothing by default …
> feat(crosswalk): add option to disable yield for new stopped object

- localization/gyro_odometer/src/gyro_odometer_core.cpp
This PR fixes wrong paramter name in `gyro_odometer_core.cpp`.
> fix(gyro_odometer): fix output_frame parameter name

- planning/behavior_velocity_crosswalk_module/docs/ttc-ttv.svg
Fixed the doc of TTC/TTV graph.
Previously, `ego_pass_first` and `ego_pass_later` are opposite.
No need.
Nothing
> fix(crosswalk): fix the doc of TTC-TTV graph

- planning/obstacle_avoidance_planner/src/node.cpp
Fixed the bug which tries to calculate the length along the trajectory but actually calculates the length of two points.
Nothing
> fix(obstacle_avoidance_planner): fix the bug of inserting stop point

- launch/tier4_perception_launch/launch/perception.launch.xml
- perception/traffic_light_arbiter/CMakeLists.txt
- perception/traffic_light_arbiter/config/traffic_light_arbiter.param.yaml
- perception/traffic_light_arbiter/launch/traffic_light_arbiter.launch.xml
This PR adds the parameter config file of traffic_light_arbiter to read parameters from autoware_launch.
autoware_launch PR:
- https://github.com/autowarefoundation/autoware_launch/pull/489
- pass the parameters from autoware_launch.
```
ros2 launch autoware_launch autoware.launch.xml lanelet2_map_file:=lanelet2_map.osm pointcloud_map_file:=pcd vehicle_model:=sample_vehicle sensor_model:=sample_sensor_kit map_path:=/tmp/sample_map launch_vehicle:=false launch_system:=false launch_map:=false rviz:=false
```
I confirmed that the parameters were passed properly by changing the parameter of `external_priority` to true.
```
$ ros2 param dump /perception/traffic_light_recognition/traffic_light_arbiter/arbiter
/perception/traffic_light_recognition/traffic_light_arbiter/arbiter: …
```
> refactor(traffic_light_arbiter): read parameters from config file

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp
- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
Fix the issue that goal_planner can not generate path when the ego vehicle is on the original goal after other module(like lane change)
https://github.com/autowarefoundation/autoware.universe/assets/39142679/da3108c8-f888-4494-809d-ac5f39a60a00
[tier4 internal scenario link](https://evaluation.tier4.jp/evaluation/reports/b7d150af-2204-5fef-af1a-1787889bfef7/tests/bda4145e-caa6-59b6-8130-bc8deca1bf73/8ae1963a-08b9-5b22-9ab8-ece7328e0038/e42bff3c-acb6-5407-8f95-fb966019f41d?project_id=prd_jt)
psim, 
related scneario test in local
https://github.com/autowarefoundation/autoware.universe/assets/39142679/6536996a-c234-4897-ab8e-9e6b66b6eeed
[tier4 internal scenario test](https://evaluation.tier4.jp/evaluation/reports/6b1aec75-a584-5585-b6e2-8d9391f0f0e9/?project_id=prd_jt
)
none
none
The PR …
> fix(goal_planner): plan path even if ego is on the original goal

- planning/behavior_velocity_crosswalk_module/config/crosswalk.param.yaml
- planning/behavior_velocity_crosswalk_module/src/manager.cpp
- planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
- planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp
Fixed chattering GO/STOP decision in crosswalk by adding a hysteresis.
- planning simualtor
- no degradation: https://evaluation.tier4.jp/evaluation/reports/189b1cc2-4f1b-51d0-b819-d6aea0553d20?project_id=prd_jt
Chattering suppression of GO/STOP decision in crosswalk
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request …
> feat(crosswalk): suppress chattering of GO/STOP decision

- planning/behavior_velocity_crosswalk_module/config/crosswalk.param.yaml
- planning/behavior_velocity_crosswalk_module/src/manager.cpp
- planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp
make `ego_pass_first/later_margin` gradable by interpolating two vectors which are `ego_pass_*_margin_x` and `ego_pass_*_margin_y`.
Nothing. Can be tuned.
> feat(crosswalk): gradable pass margin

- launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.py
Before this change, to enable abort lane change, we have to set `use_experimental_lane_change:=true`.
To enable it from a parameter file, I remove the code that overwrites the parameter to enable abort lane change from a launch file.
> chore(tier4_planning_launch): enable to abort lane change from a parameter file

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/start_planner/start_planner_module.hpp
- planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
- planning/route_handler/include/route_handler/route_handler.hpp
- planning/route_handler/src/route_handler.cpp
Chage start planner isExecutionRequested condition.
before: recieving new route
after: curent pose is close to route start pose
This change fixes the issue that start_planner can not be executed blocked by goal planner when disabling auto approval.
1. Initially, the start_planner sends a request and gets registered as a candidate.
2. In the next loop, despite the start_planner's enable_simultaneous_execution_as_candidate_module being set to false, the goal_planner presents itself as a candidate and gets set as the highest_priority_module.
3. Since the goal_planner is not in the is_waiting_approval state, the goal_planner is set as the approved module.
4. After that, the manager clears all current candidates for re-evaluation.
5. In the second check of the while loop, the start_planner is …
> fix(start_planner): execute when curent pose is close to route start pose not receiving new route

- perception/object_merger/README.md
- perception/object_merger/config/overlapped_judge.param.yaml
- perception/object_merger/include/object_association_merger/node.hpp
- perception/object_merger/launch/object_association_merger.launch.xml
- perception/object_merger/src/object_association_merger/node.cpp
- This PR aims to separate GIoU thresholds for each class when determining whether unknown objects are overlapped with known objects or how far unknown objects are from known objects to enable merging.
- This also could solve issue #4425 
[TIER IV INTERNAL LINK  ](https://tier4.atlassian.net/browse/RT1-3051)
Some traffic cones detection near by truck was confirmed by internal rosbag. …
> fix(object_merger): preserve unknown objects close to known objects

- planning/behavior_path_planner/include/behavior_path_planner/planner_manager.hpp
- planning/behavior_path_planner/src/planner_manager.cpp
- planning/route_handler/include/route_handler/route_handler.hpp
- planning/route_handler/src/route_handler.cpp
Previously, planner manager removes expired modules according to Last In First Out polycy but it causes some issue since sometimes module keep running even when it completed its own planning role.
In this PR, all module can be removed immediately when it transits `SUCCESS` status.
Remove module immediately once it transits success state. …
> perf(planner_manger): remove lifo limitation

- planning/behavior_path_planner/src/utils/utils.cpp
Without this PR, `closest_idx` from `findNearestSegmentIndex` is considered for calculating minimum index of lateral distance.
However, ideally, this closest index should be considered when minimum index of lateral distance itself is not found.
Due to the current implementation, unexpected closest index is used in some cases.
This PR calculates the minimum index of lateral distance first, and only if not found, closest index from `findNearestSegmentIndex` is used instead.
scenario simulator (https://evaluation.tier4.jp/evaluation/reports/e00f9794-72e8-59f4-95f8-c737db40ad67?project_id=prd_jt)
Nothing …
> fix(behavior_path_planner): drivable area front nearest segment index

- planning/behavior_path_planner/src/turn_signal_decider.cpp
Turn signal decider disable the blinker when the ego vehicle runs on a straight line at intersections. However, this causes some serious problems for the lane change and avoidance module when it tries to change lanes or avoid objects near intersections. In this PR, I change the code by disabling the blinker only when the ego vehicle stops at the intersection.
Scenario Test 1575/1588
[TIRE IV INTERNAL LINK](https://evaluation.tier4.jp/evaluation/reports/dd810336-efe4-52ec-ace6-190ff2f54c58?project_id=prd_jt) …
> feat(behavior_path_planner): change straight turn signal condition

- planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
- planning/behavior_path_planner/src/utils/start_planner/geometric_pull_out.cpp
- planning/behavior_path_planner/src/utils/start_planner/shift_pull_out.cpp
just rename shoulder lanes -> pull out lanes because start planner support normal lane not just shoulder lane
none
none
none
> chore(start_planner): rename shoulder lane variables

- planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
Before this change, the turn signal is turned on when the lane change is aborted.
In this change, I fix to turn off the turn signal in aborting situation.
> fix(behavior_path_planner): fix turn signal for lane change abort

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/dynamic_avoidance/dynamic_avoidance_module.hpp
- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp
- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/manager.cpp
To suppress the chattering of objects appearing/disappearing, whether object's variable (e.g. velocity) is lower/higher than the threshold, the previous object information is memorized with this change.
The meaning of the `counter` for each object is, if the value is positive, the object appears `counter` times in a raw, and if negative, the object disappears `counter` times in a raw.
Nothing …
> feat(dynamic_avoidance): memorize previous object information

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp
- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
publish goal planner stop reasons with https://github.com/autowarefoundation/autoware.universe/pull/3807
`ros2 topic echo /planning/scenario_planning/status/stop_reasons`
```
stop_reasons:
- reason: GoalPlanner
stop_factors:
- stop_pose:
position:
x: 89424.95852330126
y: 43192.74167133794
z: 5.867864464454784
orientation:
x: 0.0004721814577638348
y: -0.0006064983676202207
z: 0.6143136630164131
w: 0.7890615518676334
dist_to_stop_pose: 3.0863225448710594
stop_factor_points: []
---
```
https://github.com/autowarefoundation/autoware.universe/pull/3807
psim
none
none …
> feat(goal_planner): publish stop reason

- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
Fixed a sudden slowdown in the goal planner due to loose criteria with stop_distance_buffer for hasEnoghDistance
In this PR use the buffer only when the ego is stopped.
e.g. lane change -> goal planner
https://github.com/autowarefoundation/autoware.universe/assets/39142679/2d919d42-b840-4a64-a87e-fc1be56889a4
psim
[tier4 internal sceanrio simulator](https://evaluation.tier4.jp/evaluation/reports/tables/new?catalog_id=cb497016-2e2f-4ce0-9ac8-68d77a27a55d&filter=&job_id=ee37df62-9a23-521e-b4e8-f547f811b8fc&project_id=prd_jt&table_config=date%2Chide&target_ids=a44e58f7-6fee-579c-a12d-16a96fccbbfc%2Cb13ab173-1234-5327-9363-90c5b709329f)
none
none
The PR …
> fix(goal_planner): goal planner sudden decel

- launch/tier4_simulator_launch/launch/simulator.launch.xml
Added args to launch camera and V2X fusion modules to test this feature in scenario simulator.
modules in red rectangles in below image is fusion modules.
Related issue:
- https://github.com/autowarefoundation/autoware.universe/issues/2567
Run simple planning simulator.
```
$ ros2 launch autoware_launch planning_simulator.launch.xml map_path:=/tmp/sample_map vehicle_model:=sample_vehicle sensor_model:=sample_sensor_kit 2>&1 | tee autoware.log
```
There are no nodes related to traffic light recognition.
```
$ ros2 node list | grep traffic_light
```
Run simple planning simulator.
```
$ ros2 launch autoware_launch planning_simulator.launch.xml map_path:=/tmp/sample_map vehicle_model:=sample_vehicle sensor_model:=sample_sensor_kit 2>&1 | tee autoware.log
```
Modules to fusion camera and V2X …
> chore(tier4_simulator_launch): launch camera and V2X fusion module in simple planning simulator

- planning/behavior_path_planner/src/utils/utils.cpp
During the calculation of polygons concatenation to remove objects from the drivable area, an infinite loop happens in some complex cases.
This PR fixes it and adds a guard for an infinite loop by adding a maximum number of for loop.
Nothing
> fix(behavior_path_planner): avoid infinity loop of polygons concatenation

- .cspell-partial.json
Ignore cspell errors in `perception/bytetrack/lib`, because the files are from external source and we want to keep the spell errors as a kind of bug-compatibility. 
> chore(ci): ignore perception/bytetrack/lib in spell-check-partial

- common/tier4_calibration_rviz_plugin/src/accel_brake_map_calibrator_button_panel.cpp
fix the name of calibration service server, ```accel_brake_map_calibrator/update_map_dir``` to ```/vehicle/calibration/accel_brake_map_calibrator/update_map_dir```.
Also I changed to output information as below when the service server does not exist
I confirmed that it works fine both when the service exists and when it does not exist
It does not affect automous driving behavior
[pull request …
> fix(accel_brake_map_calibrator_button_panel): fix calibration service name

- planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
The avoidance module inserts slow down section so that the ego vehicle can avoid object whenever the operator approves its maneuver. But sometimes current ego speed exceeds slow down target speed, which causes **undershoot** (Red line in following fig) in motion velocity smoother.
https://github.com/autowarefoundation/autoware.universe/assets/44889564/0bcc4d24-1ec4-4cdd-8d48-bf2829b5ab92
In this PR, I added gurad in order to prevent undershoot. (If the current speed exceeds target slow down speed, it inserts feasible slow down point instead of slow down section.)
--- 
https://github.com/autowarefoundation/autoware.universe/assets/44889564/53f6811d-4de2-4848-9f47-e7b41c658104
https://github.com/autowarefoundation/autoware.universe/assets/44889564/29039f47-9b20-492d-97cc-a293d878f788 …
> feat(avoidance): prevent smoother undershoot

- planning/behavior_velocity_planner/config/behavior_velocity_planner.param.yaml
- planning/mission_planner/README.md
- planning/mission_planner/config/mission_planner.param.yaml
- planning/mission_planner/src/lanelet2_plugins/default_planner.cpp
- planning/mission_planner/src/lanelet2_plugins/default_planner.hpp
- planning/route_handler/include/route_handler/route_handler.hpp
- planning/route_handler/src/route_handler.cpp
This PR is to add as solution for routing `no_drivable_lane(s)` only when the module is enabled.
fixes #4307 
Using planning simulator :
- When `no_drivable_lane` is disabled, the routing for `no_drivable_lane(s)` is not considered
- When When `no_drivable_lane` is enabled, routing for `no_drivable_lane(s)` is considered
:exclamation: **_Must be merged with this [autoware_launch PR](https://github.com/autowarefoundation/autoware_launch/pull/457)_** :exclamation: …
> feat(routing_no_drivable_lane_when_module_enabled): add solution for routing no_drivable_lane only when module enabled

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/dynamic_avoidance/dynamic_avoidance_module.hpp
- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp
The current dynamic avoidance cannot deal with early avoidance against the object laterally coming close to the ego for avoiding parked vehicles since the predicted path is not used due to its instability.
This PR will fix the issue by extracting the objects from the drivable area with "the lateral offset to shift in X [seconds]" by the object's lateral velocity.
https://github.com/autowarefoundation/autoware.universe/assets/20228327/0f058131-6b9a-419c-96f6-c54e6701d737
Nothing …
> feat(dynamic_avoidance): consider shifting objects

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/dynamic_avoidance/dynamic_avoidance_module.hpp
- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp
- use decision with reason for avoidance object filtering
- fix time-to-collision to avoid the objects running right beside the ego.
Nothing
> feat(dynamic_avoidance): use decision with reason

- planning/behavior_path_planner/config/dynamic_avoidance.param.yaml
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/dynamic_avoidance/dynamic_avoidance_module.hpp
- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp
- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/manager.cpp
This PR fixes the following bug where the ego will turn right and there is an oncoming vehicle, resulting in the avoidance on the wrong side.
Nothing
> feat(dynamic_avoidance): ignore oncoming crossing object

- planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
- planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp
Currently, the distance is not set when the decision is GO in the crosswalk module.
This PR always sets the distance even when the decision is GO.
**before**
**after**
Distance is always set in the crosswalk module.
> fix(crosswalk): set distance even when decision is GO

- planning/behavior_path_planner/include/behavior_path_planner/behavior_path_planner_node.hpp
- planning/behavior_path_planner/include/behavior_path_planner/planner_manager.hpp
- planning/behavior_path_planner/src/behavior_path_planner_node.cpp
Add a new publisher to the behavior path planner that publishes if the module can do the lane change or not.
In this PR, we use a new message which is added with [this PR](https://github.com/tier4/tier4_autoware_msgs/pull/95)
> feat(behavior_path_planner): add reroute availability publisher

- planning/behavior_path_planner/config/avoidance/avoidance.param.yaml
- planning/behavior_path_planner/docs/behavior_path_planner_avoidance_design.md
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/avoidance_module_data.hpp
- planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
- planning/behavior_path_planner/src/scene_module/avoidance/manager.cpp
- planning/behavior_path_planner/src/scene_module/lane_change/manager.cpp
Improve & enable avoidance canceling behavior.
Please approve :arrow_down: before this PR.
https://github.com/autowarefoundation/autoware_launch/pull/476
Support avoidance canceling behavior.
> feat(avoidance): enable avoidance cancel

- planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
The lane change module in the autoware samples longitudinal acceleration values based on the velocity of the ego vehicle and the distance to the current and target lanes. Even though it is supposed to check the distance to the end of current lanes, it does not have that check function. In this PR, I added a check function to measure the distance to the end of lane when sampling longitudinal acceleration.
Scenario test
1581/1588
[TIER IV INTERNAL LINK](https://evaluation.tier4.jp/evaluation/reports/ce9ba133-e2ae-5d87-b505-e93de53b6f81?project_id=prd_jt) …
> fix(lane_change): add distance check for the lane change acceleration sampling

- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
visualize planner type at ego position even when goal is not found.
like `None 0/0`
(0/0 is current_path_idx/max_path_idx)
none
none
> feat(goal_planner): visualize planner type even when goal is not found

- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
Currently isStuck() return false if any path has never been found before, and do not plan freespace pull over.
In this PR, fix stuck conditions to plan.
psim
[tier4 internal scenario test](https://evaluation.tier4.jp/evaluation/reports/06c8d79d-1149-5923-aedf-87ac20f87162?project_id=prd_jt)
https://github.com/autowarefoundation/autoware.universe/assets/39142679/8589a557-d24b-4f6a-8ecd-f928e8906275
none
none …
> fix(start_planner): plan freespace pull over even if any path has never been found

- planning/mission_planner/package.xml
- planning/mission_planner/src/mission_planner/mission_planner.cpp
- planning/mission_planner/src/mission_planner/mission_planner.hpp
Add a guard for the mission planner to prevent it from rerouting while the behavior path planner is in lane change, avoidance, and other modules(start planner, goal planner and etc). This can also prevent the entire planner from generating an unsafe path. 
[Screencast from 2023年08月09日 00時25分00秒.webm](https://github.com/autowarefoundation/autoware.universe/assets/43805014/678c3f22-a397-45be-81a2-3182c223646a)
PSim …
> feat(mission_planner): add a guard for rerouting while not following lane

- planning/mission_planner/package.xml
- planning/mission_planner/src/mission_planner/mission_planner.cpp
- planning/mission_planner/src/mission_planner/mission_planner.hpp
Some functions in the mission planner use camel case, although it is supposed to use snake case. In this PR, I changed it to the snake case as well as some variable names to improve readability.
> refactor(mission_planner): use snake case instead of camel case

- planning/behavior_path_planner/config/dynamic_avoidance/dynamic_avoidance.param.yaml
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/dynamic_avoidance/dynamic_avoidance_module.hpp
- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp
- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/manager.cpp
- use hatched_road_markings for dynamic_avoidance
- make some variables ros parameters
dynamic avoidance with hatched road markings
> feat(dynamic_avoidance): use hatched road markings

- planning/behavior_path_planner/config/dynamic_avoidance/dynamic_avoidance.param.yaml
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/dynamic_avoidance/dynamic_avoidance_module.hpp
- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp
- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/manager.cpp
Depends on https://github.com/autowarefoundation/autoware.universe/pull/4566
- Fixed a bug of uninitialized previous lat_offset_to_avoid
- If an object is memorized but lat_offset_to_avoid is not updated, the initial value is 0, and low-pass filter uses it as a previous value, resulting in filtered lat_offset_to_avoid being almost 0.
- Remove calcPathForObjectPolygon because if the ego does the lane change, the calculated path will change and the result of low-pass filter of lat_offset_to_avoid will be wrong.
- Reference path in previous module's output can be used instead.
- modify debug marker for better visibility
minor bug fix of dynamic_avoidance …
> fix(dynamic_avoidance): minor changes with bug fix

- planning/route_handler/src/route_handler.cpp
ix getRouteUuid to return initial value when route is not set
psim
none
none
> fix(route_handler): fix getRouteUuid to return initial value when route is not set

- planning/planning_debug_tools/scripts/perception_replayer/perception_replayer.py
- planning/planning_debug_tools/scripts/perception_replayer/time_manager_widget.py
Added a slider GUI to move the timestamp of rosbag forward/backward for perception_replayer
The following is the video of `planning simulator` with `ros2 run planning_debug_tools  perception_replayer.py -b <bag-files>`
https://github.com/autowarefoundation/autoware.universe/assets/20228327/5a808760-e7ca-4992-8bc6-b8dcac7237f4
Nothing …
> feat(planning_debug_tools): manage time of perception_replayer by slider

- planning/behavior_velocity_intersection_module/README.md
Fix spell-check errors
N/A
N/A
N/A
N/A
N/A
> chore(behavior_velocity_intersection_module): fix spell-check errors

- planning/scenario_selector/src/scenario_selector_node/scenario_selector_node.cpp
prevent changing scneario when same uuid route is received
e.g.
If the goal is modified during a freespace pull over, it is rerouted. If ego is already out of lane at this time, the scenario may change unintentionally.
psim
none
none
> fix(scnenario_selector): prevent changing scneario when same uuid route is received

- launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.py
- planning/behavior_path_planner/include/behavior_path_planner/utils/drivable_area_expansion/drivable_area_expansion.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/drivable_area_expansion/expansion.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/drivable_area_expansion/footprints.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/drivable_area_expansion/map_utils.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/drivable_area_expansion/types.hpp
- planning/behavior_path_planner/src/utils/drivable_area_expansion/drivable_area_expansion.cpp
- planning/behavior_path_planner/src/utils/drivable_area_expansion/expansion.cpp
- planning/behavior_path_planner/src/utils/drivable_area_expansion/footprints.cpp
- planning/behavior_path_planner/src/utils/drivable_area_expansion/map_utils.cpp
- planning/behavior_path_planner/test/test_drivable_area_expansion.cpp
This PR improves the dynamic drivable area expansion, making the bounds look cleaner, especially at the at the start and end of the path.
|- | - |
| ![dynDA_before](https://github.com/autowarefoundation/autoware.universe/assets/78338830/10bf3058-51b7-49e8-9f4d-6e14d495cc01) | ![dynDA_after](https://github.com/autowarefoundation/autoware.universe/assets/78338830/0781682d-11c3-4ad9-8b2e-884890b950f6) |
Psim
Evaluator: https://evaluation.tier4.jp/evaluation/reports/tables/new?project_id=x2_dev&job_id=727d6936-d9ae-5829-98ec-a0f489b09ba9&catalog_id=6888286a-35b1-4121-b322-0c6f0e3d8868&filter=&table_config=date
This should not impact the system behavior …
> fix(behavior_path_planner): fix bad dynamic drivable area expansion at path extremities

- planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
In the planStop function of the crosswalk module, the ```stop_factor``` variable can be accessed even if it is null_opt.
I fixed it.
(TIERIV Internal Link:
https://evaluation.tier4.jp/evaluation/reports/007f6767-d452-53c3-b7ad-0da9a5909d3c/tests/f68cf39a-69b5-53eb-944b-6d84f37d58eb/2e1d61f5-e9d4-5576-a887-aede118ddf0e?project_id=prd_jt 
In scenarios, the behavior module died with following error.
```
[component_container_mt-61] terminate called after throwing an instance of 'std::bad_array_new_length'
[component_container_mt-61]   what():  std::bad_array_new_length
```
)
Tested on Psim
See description. …
> fix(behavior_velocity_crosswalk_module): prevent to access null stop_factor

- map/map_loader/src/pointcloud_map_loader/pointcloud_map_loader_node.cpp
- map/map_projection_loader/src/load_info_from_lanelet2_map.cpp
- map/map_projection_loader/test/test_load_info_from_lanelet2_map.cpp
Add backward compatibility for local map.
When loading the following xml, previous version of map_projection_loader will be in an undefined behavior. In order to address this, I would like to add a backward compatibility for such lanelet as well.
```xml
<?xml version="1.0"?>
<osm version="0.6" generator="lanelet2">
<node id="1" lat="" lon=""/>
</osm>⏎       
```
N/A
Please see the added test
N/A
Backward compatibility has been added in map files. No negative effect intended.
N/A …
> feat(map_projection_loader): add backward compatibility for local map

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/dynamic_avoidance/dynamic_avoidance_module.hpp
- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp
- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/manager.cpp
Dynamic obstacles' polygons to avoid are removed from the drivable area in the dynamic avoidance module.
Currently, the polygons are generated on the ego's path frame.
The method has a limitation case as follows.
Ideally, the polygons should be generated on the object's path frame as follows, resulting in successful avoidance.
By default, this PR's change is not used since the object path is unstable for now.
If it becomes stable, the polygon generation method will be the object path frame.
Nothing …
> feat(dynamic_avoidance): object polygon based drivable area generation

- planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/mpt_optimizer.hpp
- planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/state_equation_generator.hpp
- planning/obstacle_avoidance_planner/src/mpt_optimizer.cpp
- planning/obstacle_avoidance_planner/src/state_equation_generator.cpp
According to https://github.com/orgs/autowarefoundation/discussions/3681, this PR makes the optimization of MPT (Model Predictive Trajectory) sparser resulting in faster calculation.
TODO
I measured the calculation time of obstacle_avoidance_planner with the following route on the sample map.
**without this PR**
**with this PR**
The time rarely increases suddenly, but overall much better than without this PR.
Nothing …
> feat(obstacle_avoidance_planner): faster optimization by sparser re-formulation

- planning/obstacle_avoidance_planner/scripts/calculation_time_plotter.py
Added a depth argument in plotter. Horizontal length of the plot can be changed.
Nothing
> feat(obstacle_avoidance_planner): add depth argument in plotter

- planning/route_handler/src/route_handler.cpp
support shoulder lane in getLeft(Right)Lanelet
psim
[scenario test](https://evaluation.tier4.jp/evaluation/reports/f7bf9416-99c8-5ed1-8794-bbf8eb59d9d2?project_id=prd_jt)
none
none
> feat(route_handler): support shoulder lane in getLeft(Right)Lanelet

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/start_planner/start_planner_module.hpp
- planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
- planning/behavior_path_planner/src/utils/geometric_parallel_parking/geometric_parallel_parking.cpp
- planning/route_handler/src/route_handler.cpp
correct geometric parallel parking lane ids to fix wrong drivable area and path cut etc.
psim
none
none
> fix(start_planner): fix geometric parallel parking lane ids

- planning/behavior_path_planner/src/utils/avoidance/utils.cpp
fix avoidance_by_lc dying with empty lanes.
```
(gdb) bt
#0  lanelet::ConstPrimitive<lanelet::LaneletData>::id (this=0xffffffffffffffe8) at /usr/include/c++/11/bits/shared_ptr_base.h:1295
#1  route_handler::RouteHandler::isInGoalRouteSection (this=0x7f462005cf70, lanelet=...) at /home/kosuke55/pilot-auto/src/autoware/universe/planning/route_handler/src/route_handler.cpp:474
#2  0x00007f464758a8b4 in behavior_path_planner::utils::avoidance::filterTargetObjects (objects=std::vector of length 0, capacity 0, data=..., debug=..., planner_data=std::shared_ptr<const behavior_path_planner::PlannerData> (use count 16, weak count 0) = {...},
parameters=std::shared_ptr<behavior_path_planner::AvoidanceParameters> (use count 4, weak count 0) = {...}) at …
```
> fix(avoidance): fix dying with empty lanes

- perception/map_based_prediction/include/map_based_prediction/map_based_prediction_node.hpp
- perception/map_based_prediction/package.xml
- perception/map_based_prediction/src/map_based_prediction_node.cpp
- Added a publisher of calculation time
- Paths are planed even if the object is outside the lanelet if they are close enough.
**without the PR**
**with the PR**
FYI:
The case where object is in the opposite directional lane
- https://evaluation.tier4.jp/evaluation/reports/5511d35c-462a-5071-95f4-edb057611521?project_id=prd_jt
Nothing …
> feat(map_based_prediction): plan paths of objects outside the lanelets.

- planning/behavior_path_planner/src/utils/utils.cpp
add guard combineDrivableLanes to fix vector::_M_range_insert
```
std::cerr << "new_drivable_lanes_idx: " << new_drivable_lanes_idx
<< ", new_drivable_lanes_vec.size(): " << new_drivable_lanes_vec.size() << std::endl;
if (new_drivable_lanes_idx + 1 >= new_drivable_lanes_vec.size()) {
std::cerr << "die?" << std::endl;
}
updated_drivable_lanes_vec.insert(
updated_drivable_lanes_vec.end(), new_drivable_lanes_vec.begin() + new_drivable_lanes_idx + 1,
new_drivable_lanes_vec.end());
```
```
[component_container_mt-28] new_drivable_lanes_idx: 0, new_drivable_lanes_vec.size(): 0
[component_container_mt-28] die?
[component_container_mt-28] terminate called after throwing an instance of 'std::length_error'
[component_container_mt-28]   what():  vector::_M_range_insert
```
This issue seems to happen …
> fix(behavior_path_planner): add guard to combineDrivableLanes

- perception/traffic_light_multi_camera_fusion/README.md
Fixed broken table display in the documentation.
https://autowarefoundation.github.io/autoware.universe/main/perception/traffic_light_multi_camera_fusion/
> docs(traffic_light_multi_camera_fusion): fix broken table display

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/manager.hpp
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_interface.hpp
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_manager_interface.hpp
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/start_planner/manager.hpp
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/start_planner/start_planner_module.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/goal_planner/util.hpp
- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
- planning/behavior_path_planner/src/scene_module/goal_planner/manager.cpp
- planning/behavior_path_planner/src/scene_module/start_planner/manager.cpp
- planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
- planning/behavior_path_planner/src/utils/goal_planner/util.cpp
The value of `isSimultaneousExecutable*` cannot be changed dynamically when the module is not requested.
For example, we want the value of fixed_goal_planner to always be true, but if there is another module ahead of it in the first place, the module will not be requeted and the value cannot be changed.
In this PR, the value is changed to be changed on the manager side.
Also, complex functions were removed.
psim
LC -> fixed_goal_planner
https://github.com/autowarefoundation/autoware.universe/assets/39142679/53f02b27-e98f-4bb7-bf3d-e1c93f961a45
back pull out -> avoidance
https://github.com/autowarefoundation/autoware.universe/assets/39142679/abe3f7c2-f793-435c-82d9-3a4f93ecd9cf
[tier4 scenario simulator](https://evaluation.tier4.jp/evaluation/reports/c2583793-52dd-52a3-bf9d-9122fdc855d3?pro …
> fix(behavior_path_planner): fix simultaneous execution

- perception/map_based_prediction/include/map_based_prediction/map_based_prediction_node.hpp
- perception/map_based_prediction/src/map_based_prediction_node.cpp
- Dealt with predicted path planning of objects in the opposite directional lanes.
Some examples
- https://evaluation.tier4.jp/evaluation/reports/31b6e359-e5c0-551c-971f-2c1b4bc5e493?project_id=prd_jt
Nothing
> feat(map_based_prediction): consider opposite lanelets path planning

- planning/planning_debug_tools/scripts/perception_replayer/perception_reproducer.py
- planning/planning_debug_tools/scripts/perception_replayer/time_manager_widget.py
- With QSlider, the slider's handle cannot be captured if the mouse cursor is not the handle position when pressing the mouse.
- For better usability, by using the event of mouse press/move/release, the above feature not supported in QSlider is implemented in the new QJumpSlider class.
**without the PR**
Even when the mouse is pressed, the handle position does not move to the cursor position.
**with the PR**
When the mouse is pressed, the handle position moves to the cursor position.
- Make perception_reproduer 10Hz the same as Autoware's perception frequency.
- The current setting results in the too high CPU usage.
Nothing
The PR …
> feat(planning_debug_tools): capture slider handle independently of mouse cursor

- planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
add gurard to generateTotalShiftLine
```
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140344792426048) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140344792426048) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140344792426048, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007fa4ae242476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007fa4ae2287f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007fa4ae6a2b9e in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007fa4ae6ae20c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007fa4ae6ae277 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007fa4ae6ae4d8 in __cxa_throw () from …
```
> fix(avoidance): add gurard to generateTotalShiftLine

- planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
add guard for empty path in updateData
sometimes center_path will be empty and the further processing die.
```
// center line path (output of this function must have size > 1)
const auto center_path = utils::calcCenterLinePath(
planner_data_, reference_pose, longest_dist_to_shift_line,
*getPreviousModuleOutput().reference_path);
```
```
[component_container_mt-28] calcAvoidancePlanningData: 219, getPreviousModuleOutput().path->points.size() : 2
[component_container_mt-28] calcAvoidancePlanningData: 225, center_path.points.size() : 0
```
[internal slack](https://star4.slack.com/archives/C03QW0GU6P7/p1692087479355029)
psim
none
none
The PR author …
> fix(avoidance): add guard for empty path in updateData

- perception/traffic_light_arbiter/src/traffic_light_arbiter.cpp
I think `Key` to find the highest confidence signal should be the `Shape` of the traffic signal.
For example, if the input from the internal has following elements:
- Color::GREEN
- Shape::CIRCLE
- Status::SOLID_ON
```
signals:
- traffic_signal_id: 21001
elements:
- color: 3
shape: 1
status: 2
confidence: 1.0
```
and the input from the external has following elements:
- Color::RED
- Shape::CIRCLE
- Status::SOLID_ON
```
signals:
- traffic_signal_id: 21001
elements:
- color: 1
shape: 1
status: 2
confidence: 1.0
```
the output from traffic_light_arbiter will have the multiple colors for the one signal in the current implementation.
```
signals:
- traffic_signal_id: 21001
elements:
- color: 1
shape: 1
status: 2
confidence: 1.0
- color: 3
shape: 1
status: 2
confidence: 1.0
```
With this PR, …
> fix(traffic_light_arbiter): use the shape as a key to find the highest confidence signal

- planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
- planning/behavior_velocity_intersection_module/src/util.cpp
> feat(intersection): consider object velocity direction

- planning/behavior_velocity_occlusion_spot_module/src/occlusion_spot_utils.cpp
> feat(occlusion spot): consider object velocity direction

- planning/obstacle_velocity_limiter/src/obstacles.cpp
> feat(obstacle_velocity_limiter): consider object velocity direction

- planning/obstacle_cruise_planner/src/node.cpp
> feat(obstacle_cruise_planner): consider object velocity direction

- control/pid_longitudinal_controller/include/pid_longitudinal_controller/longitudinal_controller_utils.hpp
- control/pid_longitudinal_controller/src/longitudinal_controller_utils.cpp
- control/pid_longitudinal_controller/src/pid_longitudinal_controller.cpp
- control/pid_longitudinal_controller/test/test_longitudinal_controller_utils.cpp
In the current implementation, we are calculating the pose after delay compensation by using only velocity, however, adding current acceleration to the formula is going to improve our estimation.
Tested planning_simulator and works well. 
> feat(pid_longitudinal_controller): take into account the current acceleration to calculate delayed pose

- planning/planning_debug_tools/scripts/perception_replayer/perception_replayer.py
The script dies due to the bug of perception_replayer with detected objects publishing.
Nothing
> fix(planning_debug_tools): fix the bug of perception_replayer with detected objects publishing

- system/system_monitor/src/process_monitor/process_monitor.cpp
The `process_monitor` has a bug that it doesn't provide high-memory process information in `%MEM` order.
The results of `top` command are not sorted based on `%MEM` by numeric sort.
Added the `-n` option to the `sort` command.
I'm attaching the results of `top` and `sort` command without numeric sort.
[TIER IV INTERNAL LINK TO JIRA](https://tier4.atlassian.net/browse/RT0-28841)
1. Run Autoware.
2. Run rqt_runtime_monitor.
```console
ros2 run rqt_runtime_monitor rqt_runtime_monitor
```
3. Verify high-memory process are provided in `%MEM` order.
The results of `top` and `sort` command with numeric sort
None
None
None …
> fix(system_monitor): high-memory process are not provided in MEM order

- launch/tier4_localization_launch/launch/pose_twist_fusion_filter/pose_twist_fusion_filter.launch.xml
- localization/ekf_localizer/launch/ekf_localizer.launch.xml
-  since yaw bias estimate this will cause less accuracy at localization disable it by default
- by golfcart
better localization accuracy
> fix: ekf localizer param

- planning/behavior_path_planner/include/behavior_path_planner/utils/utils.hpp
- planning/behavior_path_planner/src/utils/utils.cpp
add combineLanelets to commonize processing like
- combine road_lanes and pull_out_lanes
- combine road_lanes and pull_over_lanes
build
none
none
> feat(behavior_path_planner): add combineLanelets

- planning/obstacle_stop_planner/src/adaptive_cruise_control.cpp
> feat(obstacle_stop_planner): consider object velocity direction

- planning/behavior_path_planner/CMakeLists.txt
- planning/behavior_path_planner/config/start_planner/start_planner.param.yaml
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/start_planner/start_planner_module.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/start_planner/freespace_pull_out.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/start_planner/pull_out_planner_base.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/start_planner/start_planner_parameters.hpp
- planning/behavior_path_planner/src/scene_module/start_planner/manager.cpp
- planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
- planning/behavior_path_planner/src/utils/start_planner/freespace_pull_out.cpp
plan freespace path for pull out when a safe path is not found with shift or geometric pull out.
https://github.com/autowarefoundation/autoware.universe/assets/39142679/617ab9c0-8974-4714-841d-ccc7e2be25c2
https://github.com/autowarefoundation/autoware_launch/pull/514
psim
[tier4 internal scenario simulator](https://evaluation.tier4.jp/evaluation/reports/tables/new?catalog_id=cb497016-2e2f-4ce0-9ac8-68d77a27a55d&filter=&job_id=909517de-72bf-5fcc-9515-2a65039b479e&project_id=prd_jt&table_config=date%2Chide&target_ids=433b6d2d-a67e-506a-a0d4-0d777274a076)
none
none …
> feat(start_planner): support freespace pull out

- planning/behavior_path_planner/src/utils/path_utils.cpp
If freespace path is out of lanes it has no lane ids, this causes behaivor_velocity dying.
```
#12 behavior_velocity_planner::util::getEgoLaneWithNextLane (path=..., associative_ids=..., width=1.8959999999999999) at /home/kosuke55/pilot-auto/src/autoware/universe/planning/behavior_velocity_intersection_module/src/util.cpp:886
886         const int next_id = path.points.at(ego_end).lane_ids.at(0);
```
In this PR set previous point lanes ids if out of laens.
before
after
https://github.com/autowarefoundation/autoware.universe/pull/4668
psim
[tier4 internal scenario test](https://evaluation.tier4.jp/evaluation/reports/774cb365-55ae-5eed-bae9-d87a964834e1?project_id=prd_jt)
fix goal planner scenario
none
none
The PR …
> fix(start/goal_planner): set previous lane_ids if freespace path is out of lanes

- control/mpc_lateral_controller/src/qp_solver/qp_solver_osqp.cpp
- control/mpc_lateral_controller/test/test_mpc.cpp
Sometimes, the polish process in OSQP, which is designed to enhance result accuracy after optimization, can fail, particularly when the problem has a lot of constraints. However, in almost all cases, the optimization result meets the desired accuracy even if the polish fails. This PR allows the use of the optimization result even when the polish process is unsuccessful.
Before:
- Optimization failure -> publish stop command
- Polish failure (but optimization success) -> publish stop command
After:
- Optimization failure -> publish stop command
- Polish failure (but optimization success) -> keep using the optimization result …
> fix(mpc): use optimization result when polish failed

- control/mpc_lateral_controller/include/mpc_lateral_controller/mpc.hpp
- control/mpc_lateral_controller/src/mpc.cpp
The zero-order hold for the steering rate limit interpolation sometimes caused the predicted path to oscillate in situations where the steer rate constraint changed significantly.
This PR solves the issue using linear interpolation in steering rate limit calculation.
None
Run psim
None
None
The steering control behavior is improved when it used the steering rate limit. …
> feat(mpc): 1d interpolate in steering rate limit calculation

- .cspell-partial.json
.svg files were sometimes causing unreasonable error e.g. in https://github.com/autowarefoundation/autoware.universe/pull/4549 where the following part was not ignored by spell-check.
```host=&quot;0i6112g2df9b6ngu9buda4iblme4t77dtbb7m4umbjihr1cp3ej8&quot; ```
Since the above issue has been resolved in https://github.com/tier4/autoware-spell-check-dict/pull/607, I'd like to revert the modification.
N/A
N/A
N/A
N/A
N/A
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/mai …
> ci: reverting control ignorance

- common/component_interface_specs/include/component_interface_specs/map.hpp
- map/map_loader/README.md
- map/map_loader/include/map_loader/lanelet2_map_loader_node.hpp
- map/map_loader/src/lanelet2_map_loader/lanelet2_map_loader_node.cpp
- map/map_projection_loader/test/test_node_load_local_from_yaml.test.py
- map/map_projection_loader/test/test_node_load_mgrs_from_yaml.test.py
- map/map_projection_loader/test/test_node_load_utm_from_yaml.test.py
I'd like to rename `/map/map_projector_type` to `/map/map_projector_info`.
Reasons:
- The type of the topic is `tier4_map_msgs/msg/MapProjectorInfo` which is a little bit different from the topic name. This inconsistency may confuse developers in the near future that may lead to a potential bugs.
- The topic is relatively new and only used in few modules at this moment. Thus, the cost of change is acceptable.
[TIER IV INTERNAL LINK](https://star4.slack.com/archives/CEL0DR2S2/p1691398284897649)
- Launch logging_simulator and ...
- Run `ros2 topic info -v /map/map_projector_type` before this PR and `ros2 topic info -v /map/map_projector_info` after this PR, and confirmed that both matches the same.
- Run sample rosbag from Autoware Tutorial and confirmed that the system works the same …
> feat!: rename map_projector_type to map_projector_info

- launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml
- launch/tier4_perception_launch/launch/object_recognition/detection/lidar_based_detection.launch.xml
|before|after|
|--|--|
|![image](https://github.com/autowarefoundation/autoware.universe/assets/20086766/433ba2d8-c49e-4cb8-8490-a0a5b3d6deeb)| ![image](https://github.com/autowarefoundation/autoware.universe/assets/20086766/b2c9e576-35b4-445e-b177-e8c4aec0ee39)|
- Problem
- L-shape fitting process in `detection_by_tracker` sometimes fail to estimate correct yaw angle
- This causes bad tracking/prediction result
- Solution 
- By lower the `detection_by_tracker` priority, we can get more stable perception output
Ticket: [TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT1-3485)
Tested with rosbag. …
> feat(tier4_perception_launch): lower the detection by tracker priority to suppress yaw oscillation

- planning/obstacle_velocity_limiter/benchmarks/collision_checker_benchmark.cpp
- planning/obstacle_velocity_limiter/include/obstacle_velocity_limiter/debug.hpp
- planning/obstacle_velocity_limiter/include/obstacle_velocity_limiter/distance.hpp
- planning/obstacle_velocity_limiter/include/obstacle_velocity_limiter/forward_projection.hpp
- planning/obstacle_velocity_limiter/include/obstacle_velocity_limiter/map_utils.hpp
- planning/obstacle_velocity_limiter/include/obstacle_velocity_limiter/obstacle_velocity_limiter.hpp
- planning/obstacle_velocity_limiter/include/obstacle_velocity_limiter/obstacle_velocity_limiter_node.hpp
- planning/obstacle_velocity_limiter/include/obstacle_velocity_limiter/obstacles.hpp
- planning/obstacle_velocity_limiter/include/obstacle_velocity_limiter/occupancy_grid_utils.hpp
- planning/obstacle_velocity_limiter/include/obstacle_velocity_limiter/parameters.hpp
- planning/obstacle_velocity_limiter/include/obstacle_velocity_limiter/pointcloud_utils.hpp
- planning/obstacle_velocity_limiter/include/obstacle_velocity_limiter/trajectory_preprocessing.hpp
- planning/obstacle_velocity_limiter/include/obstacle_velocity_limiter/types.hpp
- planning/obstacle_velocity_limiter/script/velocity_visualizer.py
- planning/obstacle_velocity_limiter/src/debug.cpp
- planning/obstacle_velocity_limiter/src/forward_projection.cpp
- planning/obstacle_velocity_limiter/src/map_utils.cpp
- planning/obstacle_velocity_limiter/src/obstacle_velocity_limiter.cpp
- planning/obstacle_velocity_limiter/src/obstacle_velocity_limiter_node.cpp
- planning/obstacle_velocity_limiter/src/obstacles.cpp
- planning/obstacle_velocity_limiter/src/occupancy_grid_utils.cpp
- planning/obstacle_velocity_limiter/src/pointcloud_utils.cpp
- planning/obstacle_velocity_limiter/test/test_collision_distance.cpp
- planning/obstacle_velocity_limiter/test/test_forward_projection.cpp
- planning/obstacle_velocity_limiter/test/test_obstacles.cpp
- planning/obstacle_velocity_limiter/test/test_occupancy_grid_utils.cpp
Correct spelling in the `obstacle_velocity_limiter` package.
> chore(obstacle_velocity_limiter): correct spelling for cspell

- planning/behavior_velocity_intersection_module/config/intersection.param.yaml
- planning/behavior_velocity_intersection_module/src/manager.cpp
Declare a separate parameter for stop_line_margin of merge_from_private
https://tier4.atlassian.net/browse/RT0-28829
https://github.com/autowarefoundation/autoware_launch/pull/521
Psim
> feat(merge_from_private): use separate param

- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp
- planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp
- planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
- planning/behavior_path_planner/src/utils/avoidance/utils.cpp
- planning/behavior_path_planner/src/utils/lane_change/utils.cpp
> feat(behavior_path_planner): consider object velocity direction

- perception/multi_object_tracker/src/tracker/model/bicycle_tracker.cpp
- perception/multi_object_tracker/src/tracker/model/big_vehicle_tracker.cpp
- perception/multi_object_tracker/src/tracker/model/normal_vehicle_tracker.cpp
This PR provides performance tuning about tracking yaw oscillation problem in v42.
Tested with experimental rosbag files and simulations. See more details in [TIER IV INTERNAL SLIDE](https://docs.google.com/presentation/d/1lEvmqknAGox_GwZzFjroicQkzDfOvTevdZgakMiGl64/edit#slide=id.g2754540b8df_1_0). …
> feat(multi_object_tracker): tune system noise to suppress yaw oscillation

- launch/tier4_perception_launch/launch/perception.launch.xml
- perception/lidar_centerpoint/README.md
- perception/lidar_centerpoint/config/centerpoint.param.yaml
- perception/lidar_centerpoint/config/centerpoint_tiny.param.yaml
- perception/lidar_centerpoint/include/lidar_centerpoint/centerpoint_trt.hpp
- perception/lidar_centerpoint/include/lidar_centerpoint/network/network_trt.hpp
- perception/lidar_centerpoint/include/lidar_centerpoint/network/tensorrt_wrapper.hpp
- perception/lidar_centerpoint/launch/lidar_centerpoint.launch.xml
- perception/lidar_centerpoint/lib/centerpoint_trt.cpp
- perception/lidar_centerpoint/lib/network/network_trt.cpp
- perception/lidar_centerpoint/lib/network/tensorrt_wrapper.cpp
- perception/lidar_centerpoint/package.xml
- perception/lidar_centerpoint/src/node.cpp
- add build only option which is necessary to run AWS + Docker 
- fix center point class and add build only option
- revert to use center point tiny as default
Note
-  tiny is AWF default model
- the reason we use center point is center point tiny has bug and it was risky to stay still but After fix which @knzo25 made and @shmpwk merged at https://github.com/autowarefoundation/autoware.universe/commit/461f330f27048e9d7b8d48898e43b9758f18eb75
Therefore there is no reason not to use tiny model.
```
ros2 launch lidar_centerpoint lidar_centerpoint.launch.xml model_name:=centerpoint build_only:=true
ros2 launch lidar_centerpoint lidar_centerpoint.launch.xml model_name:=centerpoint_tiny build_only:=true
```
by AWSIM using center point …
> fix: center point class

- perception/probabilistic_occupancy_grid_map/src/utils/utils.cpp
- perception/probabilistic_occupancy_grid_map/test/test_pointcloud_based_method.py
Pointcloud based occupancy grid map generation node sometimes died by null pointcloud input. (see figure below)
This PR enables to prevent this error by fixing util function and its effectiveness is tested with launch_test.
[TIER IV INTERNAL TICKET](https://tier4.atlassian.net/browse/RT0-28767)
Tested in launch_test. …
> fix(probabilistic_occupancy_gridmap): prevent node death by adding lookupTransform exception in util function

- planning/behavior_path_planner/include/behavior_path_planner/utils/start_planner/pull_out_path.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/start_planner/start_planner_parameters.hpp
- planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
- planning/behavior_path_planner/src/utils/start_planner/geometric_pull_out.cpp
- planning/behavior_path_planner/src/utils/start_planner/shift_pull_out.cpp
I added member variables for `PullOutPath`.
They will be used for ego predicted path generation in safety check
> feat(behavior_path_planner): add PullOutPath member variables for ego predicted path generation

- planning/obstacle_cruise_planner/config/obstacle_cruise_planner.param.yaml
- planning/obstacle_cruise_planner/include/obstacle_cruise_planner/common_structs.hpp
- planning/obstacle_cruise_planner/include/obstacle_cruise_planner/planner_interface.hpp
- planning/obstacle_cruise_planner/src/planner_interface.cpp
This PR applies the following feature to obstacle_cruise_planner
https://github.com/autowarefoundation/autoware.universe/pull/1434
Nothing
> feat(obstacle_cruise_planner): add a hold stop distance feature

- planning/behavior_path_planner/docs/behavior_path_planner_lane_change_design.md
Add missing explanation for lane change parameters.
> docs(lane_change): add missing explanation for lane change parameters

- planning/costmap_generator/nodes/costmap_generator/costmap_generator_node.cpp
Add guard for preventing access to null ```current_pose_wrt_map```.
(Fixed costmap_generator process dying when playing rosbag)
Tested on logging_simulator
> fix(costmap_generator): prevent invalid access for current_pose

- planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
Before this change, we can not change lane if the stopping vehicle is behind of a traffic light stop line.
To fix this issue, I change the parameters for getting parked object function.
[TIER IV INTERNAL TEST](https://evaluation.tier4.jp/evaluation/reports/ede8ead2-204c-57ac-ad70-a5bb19816e80?project_id=prd_jt)
Tested in planning simulator
Before:
After:
Nothing.
If stopping vehicles are behind of traffic light stop line, it will be plan lane change. …
> fix(lane_change): skip safety check for stopping vehicles

- planning/motion_velocity_smoother/launch/motion_velocity_smoother.launch.xml
Parameters of motion velocity smoother was not passed from the config in the autoware launch because the arg name is wrong.
The arg name should be `velocity_smoother_param_path`
https://github.com/autowarefoundation/autoware.universe/blob/1e68b9167270e4f644a0e9a3e6b0577b0ec98c02/launch/tier4_planning_launch/launch/scenario_planning/scenario_planning.launch.xml#L34
```
$ ros2 param dump /planning/scenario_planning/motion_velocity_smoother
/planning/scenario_planning/motion_velocity_smoother:
algorithm_type: JerkFiltered
curvature_calculation_distance: 1.0
curvature_threshold: 0.02
decel_distance_after_curve: 2.0
decel_distance_before_curve: 3.5
dense_min_interval_distance: 0.1
dense_resample_dt: 0.2
ego_nearest_dist_threshold: 3.0
ego_nearest_yaw_threshold: 1.046 …
```
> fix(motion_velocity_smoother): fix the arg name of the parameter

- perception/traffic_light_multi_camera_fusion/include/traffic_light_multi_camera_fusion/node.hpp
- perception/traffic_light_multi_camera_fusion/src/node.cpp
In the current implementation, if a traffic light is linked to multiple regulatory elements, the multi-camera fusion only publishes one signal with a regulatory element. I've updated it to publish all associated regulatory elements with the traffic light perception results.
Tested in simple planning simulator.
This was tested in a basic planning simulator. Below is the output when traffic light 2400 is associated with regulatory elements 1489 and 1493.
```
$ ros2 topic echo /perception/traffic_light_recognition/internal/traffic_signals
stamp:
sec: 1692786155
nanosec: 696961024
signals:
- traffic_signal_id: 1489
elements:
- color: 1
shape: 1
status: 0
confidence: 0.9967631101608276
```
```
stamp:
sec: 1692786410
nanosec: 596963840
signals:
- traffic_signal_id: 1489
elements:
- color: 1 …
```
> fix(traffic_light_multi_camera_fusion): assign multiple regulatory element id for one traffic light

- common/tier4_vehicle_rviz_plugin/src/tools/console_meter.cpp
- common/tier4_vehicle_rviz_plugin/src/tools/steering_angle.cpp
I changed the visualization of vehicle_rviz_plugin to make it more understandable when a speed or steering information is not available.
Tested on Psim
->
> chore: do not display steer and velocity value when message is not subscribed yet

- common/autoware_auto_perception_rviz_plugin/include/object_detection/object_polygon_display_base.hpp
- common/autoware_auto_perception_rviz_plugin/src/object_detection/object_polygon_detail.cpp
The visibility of predicted path is not so good depending on the path confidence.
It's hard to tell the difference in the figure.
nothing
> chore(autoware_auto_perception_rviz_plugin): higher visibility of predicted path color

- planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
- planning/behavior_path_planner/src/utils/path_shifter/path_shifter.cpp
use RCLCPP_DEBUG for some frequent RCLCPP_WARN in behavior_path_planner
unit test
Nothing
> chore(behavior_path_planner): use RCLCPP_DEBUG for some frequent RCLCPP_WARN

- planning/obstacle_cruise_planner/config/obstacle_cruise_planner.param.yaml
- planning/obstacle_cruise_planner/include/obstacle_cruise_planner/node.hpp
- planning/obstacle_cruise_planner/include/obstacle_cruise_planner/planner_interface.hpp
- planning/obstacle_cruise_planner/src/node.cpp
- planning/obstacle_cruise_planner/src/planner_interface.cpp
Added a option to disable checking of feasible obstacle stop.
When the option is set to true, the stop point is always inserted in front of obstacle even if it requires a large deceleration.
Nothing
> feat(obstacle_cruise_planner): add a option to suppress feasible stop check

- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp
The ego does not have to avoid objects behind the ego.
This object filtering is explicitly implemented in this PR.
Nothing
> feat(dynamic_avoidance): not avoid back object

- common/tier4_autoware_utils/include/tier4_autoware_utils/ros/parameter.hpp
- common/tier4_autoware_utils/include/tier4_autoware_utils/tier4_autoware_utils.hpp
Add a new function to get ros param.
This function is copied from [here](https://github.com/autowarefoundation/autoware.universe/blob/main/vehicle/vehicle_info_util/src/vehicle_info_util.cpp/#L22-L36)
None
build pass
None
None
None
> feat(tier4_autoware_utils): add getOrDeclearParam function

- perception/map_based_prediction/src/map_based_prediction_node.cpp
Related to https://github.com/autowarefoundation/autoware.universe/pull/4637,  map_based_prediction package also need to consider vy component of the velocity.
Most of changes is conversion from abs(vx) to hypot(vx, vy).
Tested with Psim.
> feat(map_based_prediciton): consider y component of the velocity vector

- planning/behavior_velocity_blind_spot_module/src/manager.cpp
> chore(blind_spot): use getOrDeclareParam

- planning/behavior_velocity_crosswalk_module/src/manager.cpp
> refactor(crosswalk): use getOrDeclareParameter

- planning/behavior_velocity_detection_area_module/src/manager.cpp
> refactor(detection_area): use getOrDeclareParameter

- planning/behavior_velocity_intersection_module/src/manager.cpp
> refactor(intersection): use getOrDeclareParameter

- planning/behavior_velocity_no_stopping_area_module/src/manager.cpp
> refactor(no_stopping_area): use getOrDeclareParameter

- planning/behavior_velocity_run_out_module/src/manager.cpp
> refactor(run_out): use getOrDeclareParameter

- planning/behavior_velocity_speed_bump_module/src/manager.cpp
> refactor(speed_bump): use getOrDeclareParameter

- planning/behavior_velocity_stop_line_module/src/manager.cpp
> refactor(stop_line): use getOrDeclareParameter

- planning/behavior_velocity_traffic_light_module/src/manager.cpp
> refactor(traffic_light): use getOrDeclareParameter

- planning/behavior_velocity_walkway_module/src/manager.cpp
> refactor(walkway): use getOrDeclareParameter

- common/autoware_auto_perception_rviz_plugin/include/object_detection/object_polygon_display_base.hpp
- common/autoware_auto_perception_rviz_plugin/include/object_detection/predicted_objects_display.hpp
- common/autoware_auto_perception_rviz_plugin/src/object_detection/predicted_objects_display.cpp
We have observed issues related to the processing speed of RVIZ (perception plugin) under scenarios with large amounts of detectable objects.
After profiling, we note that PredictedObjectsDisplay clears / re-adds all markers during updates with new messages, and this behavior is related to the increasing processing time.
By only deleting old marker ids not used in the newest frame, and allowing RVIZ to directly modify the old markers instead of re-adding them, this PR should improve the processing efficiency of PredictedObjectsDisplay at scenes with lots of objects. 
[Private Profiling Results](https://docs.google.com/spreadsheets/d/10ZMnt6rfGExKgIW8CM_S--FvdeLONLpMw3JkQoMIpJI/edit#gid=0)
The tests are performed on the private [ROSbag](https://console.data-search.tier4.jp/projects/prd_jt/e …
> refactor(perception_rviz_plugin): only delete markers with unused MarkersIDs during updates.

- perception/radar_fusion_to_detected_object/src/radar_object_fusion_to_detected_object_node/radar_object_fusion_to_detected_object_node.cpp
This PR changes the sync policy of `radar_fusion_to_detected_object`.
- Background
Due to the bigger functions of Camera-LiDAR fusion, it took time to output objects using Camera-LiDAR fusion.
Therefore, there was a time difference with the radar object, and there were cases where the object was not output by the message filter of radar fusion.
- Change points
This PR loosen the sync policy of `radar_fusion_to_detected_object`.
Test by rosbag. …
> fix(radar_fusion_sync_policy): change sync policy for radar_fusion_to_detected_object

- control/control_validator/src/utils.cpp
Fixed the sign of distance. The output of `calcLateralOffset` is signed.
unit test
nothing
> fix(control_validator): fix the sign of distance

- perception/radar_object_tracker/package.xml
Added missing nlohmann-json-dev dependency
> build: add nlohmann-json-dev dependency

- planning/behavior_path_planner/config/dynamic_avoidance/dynamic_avoidance.param.yaml
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/dynamic_avoidance/dynamic_avoidance_module.hpp
- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp
- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/manager.cpp
Added a minimum longitudinal margin for object polygon to generate  a drivable area.
Nothing
> feat(dynamic_avoidance): minimum object polygon longitudinal margin

- control/trajectory_follower_node/param/lateral/mpc.param.yaml
In the parameter file for testing `trajectory_follower_node` I added a missing parameter compared to [autoware_launch](https://github.com/autowarefoundation/autoware_launch/blob/main/autoware_launch/config/control/trajectory_follower/lateral/mpc.param.yaml).
Without this parameter the test would fail for MPC lateral controller.
I came across this problem while working on #3696 and testing my solution.
I ran `colcon test` on `trajectory_follower_node` and the test passes for MPC. It only fails for pure_pursuit which is expected (#3696).
`colcon test` passes. …
> fix(trajectory_follower_node): add MPC parameter

- common/perception_utils/CMakeLists.txt
Boost does not seem to be used anywhere in the code, but it's declared in `CMakeLists.txt`, this PR removes that reference.
> build: remove Boost from CMakeLists.txt

- launch/tier4_perception_launch/launch/perception.launch.xml
- launch/tier4_perception_launch/launch/traffic_light_recognition/traffic_light.launch.xml
Prepare arguments for traffic light recognition ML models. (No change in software behavior)
The default value for awf/autoware is added in another PR in autoware_launch (https://github.com/autowarefoundation/autoware_launch/pull/538) 
Confirmed with logging_simulator.launch.xml
No effects on system …
> chore: add TLR model args to launch files

- planning/behavior_velocity_crosswalk_module/config/crosswalk.param.yaml
- planning/behavior_velocity_crosswalk_module/src/manager.cpp
- planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
- planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp
Depends on https://github.com/autowarefoundation/autoware.universe/pull/4781
Added a braking distance calculated by current velocity/acceleration and limitation of acceleration/jerk to the pass judge line added by the following PR.
https://github.com/autowarefoundation/autoware.universe/pull/4492
scenario simulator
https://evaluation.tier4.jp/evaluation/reports/54768bcb-5b11-5c3e-99fb-b39bcb4378be?project_id=prd_jt
https://evaluation.tier4.jp/evaluation/reports/ffe1d1f7-ea22-5ad1-84ac-795d4f0d1e5b?project_id=prd_jt
nothing …
> feat(crosswalk): no stop decision with braking distance 

- planning/behavior_velocity_intersection_module/config/intersection.param.yaml
- planning/behavior_velocity_intersection_module/src/manager.cpp
- planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
- planning/behavior_velocity_intersection_module/src/scene_intersection.hpp
Use a latched state machine to avoid chattering of intersection occlusion decision
[TierIV COMPANY INTERNAL LINK](https://tier4.atlassian.net/browse/RT1-3269)
launcher PR: https://github.com/autowarefoundation/autoware_launch/pull/533
Psim and experiment data
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-requ …
> feat(intersection): suppress intersection occlusion chattering

- planning/behavior_path_planner/docs/behavior_path_planner_lane_change_design.md
> fix(lane_change): fix lane_change document

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/dynamic_avoidance/dynamic_avoidance_module.hpp
- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp
- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/manager.cpp
- If the object's path is a cutting-in path, but the object is very close to the ego which has to be avoided, without the PR, the decision is no avoidance.
- To deal with this case, if the object path is like above, the decision to avoid is calculated by the ego and object position.
- Fixed the debug marker's z.
- Dealt with the case where the object is crossing the ego's path, but the decision was avoidance without this PR.
nothing …
> feat(dynamic_avoidance): generate drivable area by ego/object-path-based depending on the case

- localization/ar_tag_based_localizer/src/tag_tf_caster_core.cpp
- map/util/lanelet2_map_preprocessor/src/fix_lane_change_tags.cpp
- perception/traffic_light_arbiter/src/traffic_light_arbiter.cpp
For https://github.com/autowarefoundation/autoware_common/pull/203
> chore(build): include missing lanelet2 header

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_interface.hpp
- planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
- planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp
This pull request refactors the `SceneModuleInterface` class to improve code quality based on clang-tidy's report, and due to `using` declarations for the `appendMarkerArray` function is not exactly used anywhere in `scene_module_interface.hpp`, they are moved to the respective scene module files. …
> refactor(behavior_path_planner): scene module interface clang-tidy

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/base_class.hpp
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/normal.hpp
- planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp
- planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
I add the virtual stop wall for lane change.
Ego vehicle has to stop behind of the end of lane to reserve minimum lane change length if lane change is necessary.
In this change, I set the virtual stop wall at the point.
Nothing.
Virtual stop wall for lane change will be shown in rviz. …
> feat(behavior_path_planner): add virtual stop wall for lane change

- planning/behavior_path_planner/src/utils/drivable_area_expansion/expansion.cpp
- planning/behavior_path_planner/test/test_drivable_area_expansion.cpp
This PR fixes an issue with lines that should not be crossed by the drivable area (e.g., `road_border`).
The current implementation recalculates the expansion distance by using the intersection points between the expanded polygon, and the line to avoid.
The issue occurs when the line to avoid has points _inside_ the polygon that were previously ignored but were closer to the path than the intersection points. With this PR, the points are considered such that the recalculated expansion distance is now correct.
:warning: ~one edge case is still not handled: when the linestring is completely inside the expansion polygon (see the added unit tests).~
Psim
New unit tests
Lines to avoid (e.g., `road_border`) should no longer be crossed by the expanded drivable area. …
> fix(behavior_path_planner): proper drivable area expansion limit with lines

- planning/behavior_path_planner/docs/behavior_path_planner_avoidance_design.md
- planning/behavior_path_planner/docs/behavior_path_planner_lane_change_design.md
Explanation for `object_check_min_road_shoulder_width` is missed.
I add it.
> docs(behavior_path_planner): fix object_check_min_road_shoulder_width explanation

- planning/behavior_path_planner/config/drivable_area_expansion.param.yaml
- planning/behavior_path_planner/include/behavior_path_planner/data_manager.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/drivable_area_expansion/drivable_area_expansion.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/drivable_area_expansion/footprints.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/drivable_area_expansion/parameters.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/drivable_area_expansion/types.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/utils.hpp
- planning/behavior_path_planner/src/behavior_path_planner_node.cpp
- planning/behavior_path_planner/src/utils/drivable_area_expansion/drivable_area_expansion.cpp
- planning/behavior_path_planner/src/utils/drivable_area_expansion/expansion.cpp
- planning/behavior_path_planner/src/utils/drivable_area_expansion/footprints.cpp
- planning/behavior_path_planner/src/utils/utils.cpp
- planning/behavior_path_planner/test/test_drivable_area_expansion.cpp
Improve the stability of the drivable area bounds when using the dynamic expansion.
The instability is caused by the path points moving, so this PR adds a resampling of the points at fixed intervals.
Requires the following PR to add the new parameter: https://github.com/autowarefoundation/autoware_launch/pull/522.
Psim and evaluator.
More stable drivable area bounds when using the dynamic expansion. …
> feat(behavior_path_planner): more stable dynamic drivable area expansion

- planning/behavior_velocity_out_of_lane_module/src/lanelets_selection.cpp
This PR fixes bugs with the `out_of_lane` module where some lanelets could incorrectly be considered as "other" lanes that should not be entered by ego.
The bug was caused by the `boost::geometry::overlaps` function which does not consider the case of the following picture as an overlap.
With this PR, we add checks with `boost::geometry::within` to handle cases where one lanelet is inside the other (e.g., in the picture, blue is inside red).
Psim
Prevents some unwanted stops caused by the `out_of_lane` module …
> fix(out_of_lane): handle undetected overlap edge cases

- planning/behavior_velocity_out_of_lane_module/config/out_of_lane.param.yaml
- planning/behavior_velocity_out_of_lane_module/src/decisions.cpp
- planning/behavior_velocity_out_of_lane_module/src/decisions.hpp
- planning/behavior_velocity_out_of_lane_module/src/filter_predicted_objects.hpp
- planning/behavior_velocity_out_of_lane_module/src/manager.cpp
- planning/behavior_velocity_out_of_lane_module/src/scene_out_of_lane.cpp
- planning/behavior_velocity_out_of_lane_module/src/types.hpp
This PR improves the `out_of_lane` module with the following new features:
- pedestrians are ignored.
- predicted paths that cross the ego vehicle are ignored.
- add a parameter for the minimum ego velocity used for calculating time-to-collision or overlap time ranges.
Requires launch PR https://github.com/autowarefoundation/autoware_launch/pull/548
Evaluator (TIER INTERNAL LINK): https://evaluation.tier4.jp/evaluation/reports/7f7acc7e-dc51-5798-be87-076d91582290?project_id=x2_dev
Psim.
Less incorrect stops when using the `out_of_lane` module, and when ego is stopped or driving slowly, stops are triggered more consistently. …
> feat(out_of_lane): filter predicted paths and add min assumed velocity

- planning/behavior_path_planner/include/behavior_path_planner/planner_manager.hpp
- planning/behavior_path_planner/src/planner_manager.cpp
- planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp
Before this change, reference path may be suddenly changed if the lane change module aborted while avoidance module running.
To fix this problem, I changed the state transition of lane change module and updating root lanelet function.
[TIER IV INTERNAL TEST](https://evaluation.tier4.jp/evaluation/reports/96456b5e-24d7-5623-bac6-993b27999429?project_id=prd_jt)
https://github.com/autowarefoundation/autoware.universe/assets/10190493/53306b2d-2b4f-42a4-8bfe-3e860169aca5
Suddenly changing of reference path is fixed. …
> fix(lane_change): fix state transition in lane change for multiple module cooperation

- planning/behavior_path_planner/src/utils/drivable_area_expansion/drivable_area_expansion.cpp
- planning/behavior_path_planner/test/test_drivable_area_expansion.cpp
This PR fixes an issue when splitting the dynamically expanded drivable area. The issue happens when calculating the left and right bounds from the expanded polygon.
A function calculates the ranges of polygon points that will make the left and right bounds by selecting the start/end points of each bound. In this function, we check whether points are to the left or right of the path. This check was causing the issue and was improved.
Evaluation (TIER IV INTERNAL LINK): https://evaluation.tier4.jp/evaluation/reports/4443b361-435f-5689-8766-23f5f6314348?project_id=x2_dev
Psim
Prevents some issue where the left and right bounds of the dynamically expanded drivable area would be wrong. …
> fix(behavior_path_planner): fix left/right split of the drivable area

- planning/behavior_velocity_no_drivable_lane_module/src/manager.cpp
- planning/behavior_velocity_planner/test/src/test_node_interface.cpp
> refactor(no-drivable-lane): use getOrDeclareParameter

- planning/planning_debug_tools/scripts/trajectory_visualizer.py
Modify to allow setting the maximum speed from the command line, as the fluctuation of the maximum speed on a per-frame  can lead to increased difficulty in visibility.
ros2 run planning_debug_tools trajectory_visualizer.py -v 10
> chore(planning_debug_tools): enable to set max velocity by arg in trajectory_visualizer.py

- control/autonomous_emergency_braking/src/node.cpp
- control/lane_departure_checker/include/lane_departure_checker/lane_departure_checker.hpp
- control/mpc_lateral_controller/src/mpc.cpp
- control/mpc_lateral_controller/src/mpc_lateral_controller.cpp
- control/mpc_lateral_controller/src/mpc_utils.cpp
- control/operation_mode_transition_manager/src/state.cpp
- control/pid_longitudinal_controller/src/pid_longitudinal_controller.cpp
- control/trajectory_follower_node/src/simple_trajectory_follower.cpp
- control/vehicle_cmd_gate/src/vehicle_cmd_gate.hpp
> chore(build): remove motion_utils.hpp and tier4_autoware_utils.hpp control/

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp
- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
This member variable is necessary to for safety check feature in goal_planner module.
> refactor(behavior_path_planner): add vehicle_info_ as member variable in goal_planner

- sensing/imu_corrector/src/imu_corrector_core.cpp
- sensing/imu_corrector/src/imu_corrector_core.hpp
- sensing/radar_static_pointcloud_filter/include/radar_static_pointcloud_filter/radar_static_pointcloud_filter_node.hpp
- sensing/radar_static_pointcloud_filter/src/radar_static_pointcloud_filter_node/radar_static_pointcloud_filter_node.cpp
> chore(build): remove tier4_autoware_utils.hpp sensing/

- perception/map_based_prediction/README.md
- perception/map_based_prediction/launch/map_based_prediction.launch.xml
- perception/map_based_prediction/src/map_based_prediction_node.cpp
- perception/multi_object_tracker/src/tracker/model/normal_vehicle_tracker.cpp
Current launch file for map_based_prediction can not remap the prediction node's input topic.
It is also not good the input topic is specified in the cpp file.
This PR fix above problems and make user easier to choose which input/output topic should be used.
Tested in psim.
None
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelin …
> feat(map_based_prediciton): enable map_based_prediction.launch.xml to remap input topic

- perception/traffic_light_arbiter/src/traffic_light_arbiter.cpp
Switched to using THROTTLE for warning logs to prevent obscuring other logs.
Tested in simple planning simulator.
> chore(traffic_light_arbiter): use THROTTLE to prevent obscuring other logs

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/manager.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/goal_planner/util.hpp
- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
- planning/behavior_path_planner/src/scene_module/goal_planner/manager.cpp
- planning/behavior_path_planner/src/utils/goal_planner/util.cpp
remove `left_side` args from `isAllowedGoalModification`
psim
scnerio test
https://evaluation.tier4.jp/evaluation/reports/9058babd-3979-555b-9559-48ef2ca1d3f4?project_id=prd_jt
> refactor(goal_planner): refactor isAllowedGoalModification

- perception/radar_fusion_to_detected_object/README.md
- perception/radar_fusion_to_detected_object/src/radar_fusion_to_detected_object.cpp
Fix the bug that `threshold_yaw_diff` parameter is not reflected.
None
> fix(radar_fusion_to_detected_object): fix parameter handling

- planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
fix start pose candidates
before
after
psim
https://evaluation.tier4.jp/evaluation/reports/412a6397-1b87-586f-88c7-56febb7def53?project_id=prd_jt
> fix(start_planner): start pose candidates

- planning/route_handler/src/route_handler.cpp
> fix(route_handler): fix getter for pose

- control/operation_mode_transition_manager/src/state.cpp
Fix the trajectory deviation calculation.
(Before): calculate distance between the ego point and the closest point in the trajectory.
(After): calculate distance between the ego point and the interpolated point in the trajectory.
The sampling distance of the trajectory causes inaccuracy in the previous method.
The blue line is the lateral distance calculated in the previous way, and the green line is the new one.
The same update is addressed on the yaw deviation calculation as well.
[TIERIV INTERNAL TICKET](https://tier4.atlassian.net/browse/RT1-3345)
Run psim
None
None
The engage condition is improved …
> fix(operation_transition_manager): trajectgory deviation calculation

- planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
- planning/behavior_path_planner/src/utils/goal_planner/geometric_pull_over.cpp
- planning/behavior_path_planner/src/utils/start_planner/geometric_pull_out.cpp
use combineLanelets for similar proccesing.
https://evaluation.tier4.jp/evaluation/reports/7c5294ef-2b39-58e7-8c87-eb32d83ca475?project_id=prd_jt
> refactor(start/goal_planner): use combineLanelets

- planning/behavior_path_planner/config/goal_planner/goal_planner.param.yaml
- planning/behavior_path_planner/docs/behavior_path_planner_goal_planner_design.md
- planning/behavior_path_planner/include/behavior_path_planner/utils/goal_planner/goal_planner_parameters.hpp
- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
- planning/behavior_path_planner/src/scene_module/goal_planner/manager.cpp
do not use minimum_request_length for fixed goal planner
need
- keep last
- always ececutable
of planner manager
https://github.com/autowarefoundation/autoware_launch/pull/546
psim
https://evaluation.tier4.jp/evaluation/reports/3ae99ec3-73aa-56cd-bd1f-173fdbb2cd9a?project_id=prd_jt
none
none
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-req …
> feat(goal_planner): do not use minimum_request_length for fixed goal planner

- planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
- planning/behavior_velocity_intersection_module/src/util.cpp
- planning/behavior_velocity_intersection_module/src/util.hpp
Fixed unnecessary stuck vehicle detection for vehicles before the attention area.
> feat(intersection): do not generate stuck vehicle detect area before attention area if attention area exists

- planning/behavior_path_planner/include/behavior_path_planner/utils/goal_planner/util.hpp
- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
- planning/behavior_path_planner/src/utils/goal_planner/freespace_pull_over.cpp
- planning/behavior_path_planner/src/utils/goal_planner/geometric_pull_over.cpp
- planning/behavior_path_planner/src/utils/goal_planner/goal_searcher.cpp
- planning/behavior_path_planner/src/utils/goal_planner/shift_pull_over.cpp
- planning/behavior_path_planner/src/utils/goal_planner/util.cpp
- planning/route_handler/include/route_handler/route_handler.hpp
- planning/route_handler/src/route_handler.cpp
fix getPullOverLanes
When getting road lanes as pull over lanes, can not extend beyond route lane.
merge https://github.com/autowarefoundation/autoware.universe/pull/4856 first
psim
https://evaluation.tier4.jp/evaluation/reports/984cdbf0-6f47-5adc-9105-72a0d9b0fa79?project_id=prd_jt
none
none …
> fix(behavior_path_planner): fix functions related to pull over lanes

- planning/planning_debug_tools/scripts/perception_replayer/perception_replayer.py
- planning/planning_debug_tools/scripts/perception_replayer/perception_reproducer.py
This PR disables the publishing of traffic light messages from the perception replayer.
The message is going to change and will cause the script to crash. This will be reverted once the message change is finalized.
Psim
None
> fix(planning_debug_tools): disable traffic light msg in perception replay

- control/operation_mode_transition_manager/README.md
- control/operation_mode_transition_manager/config/operation_mode_transition_manager.param.yaml
- control/operation_mode_transition_manager/src/state.cpp
- control/operation_mode_transition_manager/src/state.hpp
Because it is danger to engage the autonomous driving mode when the vehicle is moving without any consideration (it causes e.g. a danger deceleration), I added a parameter to prohibit the engage on driving.
When this parameter is false, the engage is prohibited anytime the vehicle is moving.
Need to be merged with https://github.com/autowarefoundation/autoware_launch/pull/553
Run psim
None
None
Vehicle engage is not permitted depending on the parameter. …
> feat(operation_transition_mannager): add param enable_engage_on_driving

- planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
fix drivable area of start planner when start from normal road lane witout shoulder lane.
before
after
psim
> fix(start_planner): fix drivable area without shoulder lanes

- perception/traffic_light_map_based_detector/package.xml
- perception/traffic_light_map_based_detector/src/node.cpp
Fix `symbol lookup error`
AWSIM works
https://github.com/autowarefoundation/autoware.universe/assets/28677420/f0eb0ea0-1912-437f-891d-4ebc458069f9
-  [X] The PR follows the [pull request guidelines].
> chore(build): fix traffic_light_map_based_detector

- planning/planning_debug_tools/scripts/perception_replayer/perception_replayer.py
- planning/planning_debug_tools/scripts/perception_replayer/perception_replayer_common.py
- planning/planning_debug_tools/scripts/perception_replayer/perception_reproducer.py
support old auto TrafficSignalArray temporary
https://github.com/autowarefoundation/autoware.universe/pull/4133#discussion_r1318047173
fix the issue with old rosbag
```
$ ros2 run planning_debug_tools perception_replayer.py -b /media/kosuke55/sandisk/rosbag/start_planner_stop_publishing_path/d4d1adc7-4fdf-4613-86b3-0daa2d945b9e_2023-08-25-13-41-44_p0900_5.db3
Stared loading rosbag
[INFO 1694057248.905715364] [rosbag2_storage]: Opened database '/media/kosuke55/sandisk/rosbag/start_planner_stop_publishing_path/d4d1adc7-4fdf-4613-86b3-0daa2d945b9e_2023-08-25-13-41-44_p0900_5.db3' for READ_ONLY. (open() at ./src/rosbag2_storage_default_plugins/sqlite/sqlite_storage.cpp:227)
Ended loading rosbag
Start timer callback
autoware_auto_perception_msgs.msg._traffic_signal_array
Traceback (most recent …
```
> feat(planning_debug_tools): support old auto TrafficSignalArray

- common/tier4_planning_rviz_plugin/include/path/display_base.hpp
The vehicle size parameters of the path rviz plugin are received from the global parameter.
These parameters are applied to the plugin's footprint size but not to the parameters shown in the panel.
rviz
Nothing
> fix(tier4_planning_rviz_plugin): update vehicle info parameters in panel received from global parameter

- planning/surround_obstacle_checker/config/surround_obstacle_checker.param.yaml
- planning/surround_obstacle_checker/include/surround_obstacle_checker/debug_marker.hpp
- planning/surround_obstacle_checker/include/surround_obstacle_checker/node.hpp
- planning/surround_obstacle_checker/src/debug_marker.cpp
- planning/surround_obstacle_checker/src/node.cpp
Currently, the footprint margin cannot be changed depending on the object label
This PR enables
- footprint margins depending on object's label
- e.g.
- footprint margins depending on front, side, and back
- e.g. 
- Just check dynamic object but pointcloud
- Side margin for vehicle objects is 0.
- The ego may have to start when the object is laterally close. The slow down feature by obstacle_cruise_planner adjusts the velocity in this case.
scenario simulator: https://evaluation.tier4.jp/evaluation/reports/1277aee0-04b7-5319-b6ec-9fedac39ec4c?project_id=prd_jt
nothing …
> feat(surround_obstacle_checker): make parameters more tunable

- perception/map_based_prediction/include/map_based_prediction/map_based_prediction_node.hpp
- perception/map_based_prediction/src/map_based_prediction_node.cpp
- perception/map_based_prediction/src/path_generator.cpp
depends https://github.com/autowarefoundation/autoware.universe/pull/4934
none
none
> chore(build): remove tier4_autoware_utils.hpp/motion_utils.hpp from map_based_prediction

- planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
prevent approval when stop path
tier internal ticket
https://tier4.atlassian.net/browse/RT1-3776?focusedCommentId=137031&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-137031
psim
https://evaluation.tier4.jp/evaluation/reports/3a94abc1-0c67-5352-b5f0-f39814ba4b79?project_id=prd_jt
1650/1650
none
none
can not approve when  stop path is used …
> fix(start_planner): prevent approval when stop path

- planning/planning_debug_tools/scripts/perception_replayer/perception_replayer.py
- planning/planning_debug_tools/scripts/perception_replayer/perception_replayer_common.py
Some uninitialized variables in the perception_replayer can cause crashes depending on the topics contained in the bag used.
This PR fixes these crashes.
Rosbag test.
None.
> fix(perception_replayer): initialize class variables to prevent crashes

- control/vehicle_cmd_gate/src/vehicle_cmd_filter.cpp
- control/vehicle_cmd_gate/src/vehicle_cmd_filter.hpp
- control/vehicle_cmd_gate/test/src/test_filter_in_vehicle_cmd_gate_node.cpp
- control/vehicle_cmd_gate/test/src/test_vehicle_cmd_filter.cpp
Use the real velocity for the lateral command filter.
Otherwise, if the velocity command oscillates, the filtered steering oscillates.
The drawback is that it won't guarantee the constraints are met in the series of the output command itself. (We need to see the actual velocity data to check it.) But this is much safer than the previous implementation.
[TIERIV Internal ticket](https://tier4.atlassian.net/browse/RT1-3765)
Run in a real vehicle testing and it worked well.
None
None
Improve the filtering. No effect in the default parameter. …
> fix(vehicle_cmd_gate): use real velocity for the lateral filter

- simulator/simple_planning_simulator/include/simple_planning_simulator/simple_planning_simulator_core.hpp
- simulator/simple_planning_simulator/launch/simple_planning_simulator.launch.py
- simulator/simple_planning_simulator/package.xml
- simulator/simple_planning_simulator/src/simple_planning_simulator/simple_planning_simulator_core.cpp
https://github.com/autowarefoundation/autoware_common/pull/205 should be merged first.
Add an option to consider ego pitch angle for simulation (longitudinal acceleration and ego pose). The angle is calculated by the nearest lanelet hight.
No behavior change by default parameter
Nothing …
> feat(simple_planning_simulator): consider ego pitch angle for simulation

- planning/path_smoother/include/path_smoother/common_structs.hpp
- planning/path_smoother/include/path_smoother/elastic_band_smoother.hpp
- planning/path_smoother/src/elastic_band.cpp
- planning/path_smoother/src/utils/trajectory_utils.cpp
- planning/planning_validator/src/debug_marker.cpp
- planning/planning_validator/src/planning_validator.cpp
- planning/planning_validator/src/utils.cpp
- planning/sampling_based_planner/path_sampler/include/path_sampler/common_structs.hpp
- planning/sampling_based_planner/path_sampler/include/path_sampler/node.hpp
- planning/sampling_based_planner/path_sampler/src/node.cpp
- planning/sampling_based_planner/path_sampler/src/prepare_inputs.cpp
- planning/sampling_based_planner/path_sampler/src/utils/trajectory_utils.cpp
- planning/static_centerline_optimizer/src/static_centerline_optimizer_node.cpp
- planning/static_centerline_optimizer/src/successive_trajectory_optimizer_node.cpp
- planning/static_centerline_optimizer/src/utils.cpp
- planning/surround_obstacle_checker/include/surround_obstacle_checker/node.hpp
- planning/surround_obstacle_checker/src/debug_marker.cpp
- planning/surround_obstacle_checker/src/node.cpp
> chore(build): remove tier4_autoware_utils.hpp/motion_utils.hpp from other planning packages

- planning/behavior_path_planner/src/utils/start_planner/shift_pull_out.cpp
crop backward path to start from narrow space
before
after
psim
https://evaluation.tier4.jp/evaluation/reports/c248c06c-6557-5d52-a552-e17ff68e1246?project_id=prd_jt
1650/1650
none
none
> fix(start_planner): crop backward path to start from narrow space

- planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
The update cycle is observed only at the beginning due to `!last_pull_out_start_update_time_` .
fix this issue and use update cycle not only for backward driving
psim
https://evaluation.tier4.jp/evaluation/reports/57953752-50c7-5dd6-a095-f55eaa7719cd?project_id=prd_jt
none
none
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guideline …
> fix(start_planner): fix path update

- planning/static_centerline_optimizer/src/static_centerline_optimizer_node.cpp
Fixed a problem with double inclusion.
Caused in https://github.com/autowarefoundation/autoware.universe/pull/4940.
It was confirmed that it could be built successfully.
> fix(static_centerline_optimizer): remove double include

- perception/image_projection_based_fusion/include/image_projection_based_fusion/roi_cluster_fusion/node.hpp
- perception/image_projection_based_fusion/launch/roi_cluster_fusion.launch.xml
- perception/image_projection_based_fusion/src/roi_cluster_fusion/node.cpp
Update default launcher parameter `iou_threshold : 0.35 -> 0.65`.
Also, the default values are removed specified in RoIClusterFusion node.  
> fix(image_projection_based_fusion): update parameter value

- planning/behavior_path_planner/include/behavior_path_planner/utils/start_goal_planner_common/utils.hpp
- planning/behavior_path_planner/src/utils/goal_planner/shift_pull_over.cpp
- planning/behavior_path_planner/src/utils/start_goal_planner_common/utils.cpp
- planning/behavior_path_planner/src/utils/start_planner/shift_pull_out.cpp
shifting path make path point order wrong and is_driving_forward false, this causes wrong drivable area.
In this PR remove inverse position path point.
before
```
[component_container_mt-28] is_driving_forward in generateCombinedDrivableArea: 0
[component_container_mt-28] is_driving_forward: 0
```
after
https://tier4.atlassian.net/08ab1e03-283d-4096-9af4-08b3fd6658a6#media-blob-url=true&id=ef931a2e-2c9e-4636-a230-5e3759bab867&contextId=86702&collection=
https://evaluation.tier4.jp/evaluation/reports/66d65d25-8bad-5657-ab02-52686ca71601?project_id=prd_jt
https://evaluation.tier4.jp/evaluation/reports/09e72de7-3ce1-5d09-8582-af3915e70d12?project_id=prd_jt
none
none …
> fix(start/goal_planner): fix inverse order path points

- control/control_validator/src/control_validator.cpp
Use log_throttle for the error message, otherwise the terminal is filled by the same log.
run psim
None
> chore(control_validator): use throttle for the error log

- planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
- planning/behavior_velocity_intersection_module/src/scene_intersection.hpp
- planning/behavior_velocity_intersection_module/src/util.cpp
- planning/behavior_velocity_intersection_module/src/util_type.hpp
https://tier4.atlassian.net/browse/RT1-3267
https://tier4.atlassian.net/browse/RT1-3696
https://tier4.atlassian.net/browse/RT1-3618
Psim
evaluator
https://evaluation.tier4.jp/evaluation/reports/42ec3b4b-cad9-5708-8d3d-669c8d5c00a5?project_id=prd_jt …
> fix(intersection): stuck stop line generation when ego is over fist conflicting area

- planning/behavior_path_planner/src/utils/utils.cpp
It should use `findSegment` function for the segment search, not `findIndex`.
run psim
The following terminal log will disappear.
```
[component_container_mt-28] Segment index is invalid.
```
> fix(behavior_path_planner): use findSegment for segment search

- planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
keep max back distace whithin lanes
2023/09/12 https://evaluation.tier4.jp/evaluation/reports/ded9ec4d-2479-5b6b-ab63-c7334cdc97e3/?project_id=prd_jt
1650/1650
none
none
> fix(start_planner): keep max back distace whithin lanes

- control/lane_departure_checker/include/lane_departure_checker/lane_departure_checker_node.hpp
- control/lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker_node.cpp
> chore(build): only include forward declaration of lanelet stuff in control/ header files

- planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
In the lane change `NormalLaneChange::filterObject` function, the target objects are classified based on which lanelet it is currently occupied, with the target lane's objects being prioritized first during the search.
Therefore, although the target object's base link is in current lane, if its polygon intersect with the target lane, it will be considered as target lane's object.
This caused an issue, since based on the above images, the object is causing unnecessary lane change CANCEL/ABORT.
To fix this, I am placing the lateral check to ensure that the filtering doesn't consider the object as target lane object.
[TIER IV internal link](https://tier4.atlassian.net/browse/RT1-3172)
Using PSIM
Unnecessary lane change cancel occured the whole way. …
> fix(lane_change): fix target object filter

- sensing/imu_corrector/package.xml
`diagnostic_updater` is used in the code, but not declared as a dependency in `package.xml`
> build(imu_corrector): add missing diagnostic_updater dependency

- perception/lidar_centerpoint/lib/centerpoint_trt.cpp
Suppress the warning message that is continuously displayed in the terminal.
Confirmed with logging_simulator.launch that centerpoint launches correctly.
No effects
> chore(lidar_centerpoint): change WARN to DEBUG

- perception/crosswalk_traffic_light_estimator/include/crosswalk_traffic_light_estimator/node.hpp
- perception/crosswalk_traffic_light_estimator/src/node.cpp
- perception/detected_object_validation/include/detected_object_filter/object_lanelet_filter.hpp
- perception/detected_object_validation/include/detected_object_filter/object_position_filter.hpp
- perception/detected_object_validation/src/object_lanelet_filter.cpp
- perception/elevation_map_loader/include/elevation_map_loader/elevation_map_loader_node.hpp
- perception/elevation_map_loader/src/elevation_map_loader_node.cpp
- perception/map_based_prediction/include/map_based_prediction/map_based_prediction_node.hpp
- perception/map_based_prediction/src/map_based_prediction_node.cpp
- perception/traffic_light_map_based_detector/include/traffic_light_map_based_detector/node.hpp
- perception/traffic_light_multi_camera_fusion/include/traffic_light_multi_camera_fusion/node.hpp
- perception/traffic_light_multi_camera_fusion/src/node.cpp
- perception/traffic_light_occlusion_predictor/include/traffic_light_occlusion_predictor/occlusion_predictor.hpp
- perception/traffic_light_visualization/include/traffic_light_map_visualizer/node.hpp
- perception/traffic_light_visualization/src/traffic_light_map_visualizer/node.cpp
> chore(build): only include forward declaration of lanelet stuff in perception/ header files

- perception/object_merger/include/object_association_merger/node.hpp
- perception/object_merger/launch/object_association_merger.launch.xml
- perception/object_merger/src/object_association_merger/node.cpp
To merger between object with large time difference, this PR add queue size parameter for message filter.
As the perception process becomes longer, there are more opportunities to merge objects with header time differences.
So this PR add add queue size parameter for message filter in `object_merger`, and make it easier to debug for the message filter.
Test by rosbag
Default parameter is same as until now, so behavior doesn't change by this PR. …
> feat(object_merger): add queue size parameter

- common/motion_utils/src/resample/resample.cpp
remove duplicated points before resampling to suppress the log:
```
[component_container_mt-28] input points has some duplicated points
[component_container_mt-28] input points has some duplicated points
[component_container_mt-28] input points has some duplicated points
[component_container_mt-28] input points has some duplicated points
[component_container_mt-28] input points has some duplicated points
[component_container_mt-28] input points has some duplicated points
[component_container_mt-28] input points has some duplicated points
[component_container_mt-28] input points has some duplicated points
[component_container_mt-28] input points has some duplicated points
```
run psim, evaluator
https://evaluation.tier4.jp/evaluation/reports/d846b328-b093-5a9d-854a-ffe056ac94ae?project_id=p …
> fix(resample): remove duplicated poinnt before resampling

- common/tier4_autoware_utils/include/tier4_autoware_utils/system/backtrace.hpp
- common/tier4_autoware_utils/include/tier4_autoware_utils/tier4_autoware_utils.hpp
This function displays the stack trace in runtime.
run psim
None, just adding a util function
> feat(tier4_autoware_utils): add function to print backtrace in runtime

- planning/behavior_path_planner/include/behavior_path_planner/utils/start_planner/start_planner_parameters.hpp
- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
before:
collision detected against dynamic objects before aprroval, output is not generated and turnsignal information is calculated based on empty output. in this case, node get died.
after:
Separate condition into 3
1. not safe against **static** objects:
stop on the reference path
2.  not safe against **dynamic** objects and after approval
stop on the pull over path
3. none of above
do nothing
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/cont …
> fix(behavior_path_planner): fix condition when collision detected before approval

- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
if setting `enable_safety_check: false` the node die.
```
[component_container_mt-28]     @     0x7f4fecdc8968 behavior_path_planner::utils::start_goal_planner_common::updatePathProperty()
[component_container_mt-28]     @     0x7f4fecca359c behavior_path_planner::GoalPlannerModule::isSafePath()
[component_container_mt-28]     @     0x7f4feccb3e1e behavior_path_planner::GoalPlannerModule::setOutput()
[component_container_mt-28]     @     0x7f4feccb44bf behavior_path_planner::GoalPlannerModule::planWithGoalModification()
[component_container_mt-28]     @     0x7f4feccb4be3 behavior_path_planner::GoalPlannerModule::plan()
[component_container_mt-28]     @     0x7f4feccb1f16 behavior_path_planner::GoalPlannerModule::planWaitingApprovalWithGoalModification()
[component_container_mt-28]     @ …
```
> fix(goal_planner): fix disabling safety check

- perception/radar_fusion_to_detected_object/src/radar_fusion_to_detected_object.cpp
Fix confidence reference in radar_fusion_to_detected_object.
Test by rosbag
None
> fix(radar_fusion_to_detected_object): fix confidence

- planning/behavior_path_planner/src/behavior_path_planner_node.cpp
- planning/mission_planner/src/mission_planner/mission_planner.cpp
- planning/mission_planner/src/mission_planner/mission_planner.hpp
use trasient local for modified goal for pub/sub because mission planner sometimes does not receive it.
modified goal may be published in 10hz at most, so we need to see if this setting is appropriate.
https://tier4.atlassian.net/browse/RT1-3626
psim
2023/09/17 https://evaluation.tier4.jp/evaluation/reports/f969ecb1-628a-590a-a41a-258300212e8f/?project_id=prd_jt
1668/1668
none
none
[pull request …
> fix(mission_planner/behavior_path_planner): use transient local for modified goal

- localization/ndt_scan_matcher/include/ndt_scan_matcher/util_func.hpp
- localization/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp
- localization/ndt_scan_matcher/src/util_func.cpp
Added code to log input and output Pose of initial position estimation in `align_using_monte_carlo`.
It was confirmed that it can be successfully executed against sample rosbag.
Each time an initial position estimation is performed using NDT, the following three lines of log are output.
Each value is `(x, y, z, qx, qy, qz, qw, roll, pitch, yaw(deg), cov(0,0), cov(1,1), ... cov(5, 5))`.
```
1695192506.8527462 [ndt_scan_matcher-31] [INFO 1695192506.851505952] [localization.pose_estimator.ndt_scan_matcher]: align_using_monte_carlo_input,89570.098658,42300.198565,-3.188279,0.000363,-0.007508,0.018195,0.999806,0.025985,-0.860952,2.084941,1.000000,1.000000,0.010000,0.010000,0.010000,10.000000
...
1695192509.4600489 [ndt_scan_matcher-31] [INFO 1695192509.439114040] …
```
> feat(ndt_scan_matcher): added logging initial pose

- perception/tensorrt_yolo/CMakeLists.txt
See #3137
Depends on https://github.com/autowarefoundation/autoware_common/pull/164
> build(tensorrt_yolo): remove download logic from CMake

- perception/image_projection_based_fusion/CMakeLists.txt
See https://github.com/autowarefoundation/autoware.universe/issues/3137
According to discussion above remove downloading logic from building stage. For now it will be possible to download model files either by ansible or manually as explained in this [PR](https://github.com/autowarefoundation/autoware-documentation/pull/345)  …
> build(image_projection_based_fusion): remove downloading logic from Cmake

- perception/traffic_light_ssd_fine_detector/CMakeLists.txt
See #3137
Depends on https://github.com/autowarefoundation/autoware_common/pull/164
> build(traffic_light_ssd_fine_detector): remove download logic from CMake

- control/operation_mode_transition_manager/src/state.cpp
- control/operation_mode_transition_manager/src/state.hpp
- launch/tier4_control_launch/launch/control.launch.py
The vehicle engage in manual driving should be prohibited when the Autoware is indicating an urgent stop (represented by target `v=0`). 
However, due to the filtering in the `vehicle_cmd_gate`, even if the trajectory follower sends `v=0`, the target velocity of the vehicle_cmd_gate is not 0.
With this PR, `operation_mode_transition_manager` checks the control command from the `trajectory_follower` directly as well as the control command from the `vehicle_cmd_gate` to prohibit the engage in manual driving when the Autoware is indicating an urgent stop.
[TIERIV internal ticket](https://tier4.atlassian.net/browse/RT1-3487)
Run psim.
None
None
The vehicle engage is prohibited when the control module is indicating an urgent stop. …
> fix(operation_mode_transition_manager): check trajectory_follower_cmd for engage condition

- perception/object_merger/launch/object_association_merger.launch.xml
#4994 introduced a minor bug, because a new parameter was not passed appropriately:
```
[object_association_merger_node-45] terminate called after throwing an instance of 'rclcpp::exceptions::InvalidParameterTypeException'
[object_association_merger_node-45]   what():  parameter 'sync_queue_size' has invalid type: Wrong parameter type, parameter {sync_queue_size} is of type {integer}, setting it to {string} is not allowed.
``` …
> fix(object_merger): fixed sync_queue_size parameter

- control/vehicle_cmd_gate/config/vehicle_cmd_gate.param.yaml
- control/vehicle_cmd_gate/src/vehicle_cmd_filter.cpp
- control/vehicle_cmd_gate/src/vehicle_cmd_filter.hpp
- control/vehicle_cmd_gate/src/vehicle_cmd_gate.cpp
- control/vehicle_cmd_gate/test/src/test_filter_in_vehicle_cmd_gate_node.cpp
- control/vehicle_cmd_gate/test/src/test_vehicle_cmd_filter.cpp
Add new filters:
- steering angle limit filter
- steering angle rate limit filter
Note: now there is a filter for lateral acceleration and lateral jerk, but since these values are related to both steering and velocity, it is a bit complicated to tune parameters sometimes. For the issue, I introduce a more simple filter for steering and steering rate limit.
[TIERIV internal ticket](https://tier4.atlassian.net/browse/RT1-3763)
Run psim and make sure the vehicle can drive in a shape turn.
None
New parameters are added. Must be merged with https://github.com/autowarefoundation/autoware_launch/pull/576
Steering angle and steering angle rate filter will be activated …
> feat(vehicle_cmd_gate)!: add steer and steer_rate filter

- perception/tensorrt_yolox/CMakeLists.txt
See #3137
Depends on https://github.com/autowarefoundation/autoware_common/pull/164
> build(tensorrt_yolox): remove download logic from CMake

- localization/ekf_localizer/src/ekf_localizer.cpp
Fix bug in 5054 https://github.com/autowarefoundation/autoware.universe/pull/5054
Not tested
Behavior when vehicle drives backward will be improved
> fix(ekf_localizer): fix bug in #5054

- planning/mission_planner/src/mission_planner/mission_planner.cpp
- planning/mission_planner/src/mission_planner/mission_planner.hpp
To fix the issue: "the set_route api is rejected even though the autoware_state is `WAIT_FOR_ROUTE`".
Publish `routing_state = UNKNOWN` until the routing system is not initialized.
Without this PR, it gets `autoware_state = WAIT_FOR_ROUTE` and `routing_state = UNSET` even if the mission_planner is not ready. Due to this inconsistency, calling set_route while in the wait_for_route state causes the API to fail.
Before this PR, when the ego pose is not set, the route state is UNSET:
```
ros2 topic echo /planning/mission_planning/route_state
stamp:
sec: 1694341968
nanosec: 326244268
state: 0
```
After this PR, when the ego pose is not set, the route state is UNKNOWN:
```
ros2 topic echo /planning/mission_planning/route_state
stamp:
sec: 1694342360
nanosec: 163490802
state: 1
---
```
[TIERIV …
> fix(mission_planner): routing api uninitialization

- simulator/simple_planning_simulator/include/simple_planning_simulator/simple_planning_simulator_core.hpp
- simulator/simple_planning_simulator/src/simple_planning_simulator/simple_planning_simulator_core.cpp
- simulator/simple_planning_simulator/test/test_simple_planning_simulator.cpp
Fix following error.
```
/opt/ros/humble/include/rclcpp/rclcpp/node_impl.hpp:99:47:   required from ‘std::shared_ptr<ROSMessageT> rclcpp::Node::create_subscription(const string&, const rclcpp::QoS&, CallbackT&&, const rclcpp::SubscriptionOptionsWithAllocator<AllocatorT>&, typename MessageMemoryStrategyT::SharedPtr) [with MessageT = autoware_auto_control_msgs::msg::AckermannControlCommand_<std::allocator<void> >; CallbackT = simulation::s
imple_planning_simulator::SimplePlanningSimulator::SimplePlanningSimulator(const rclcpp::NodeOptions&)::<lambda(autoware_auto_control_msgs::msg::AckermannControlCommand_<std::allocator<void> >::SharedPtr)>; AllocatorT = std::allocator<void>; SubscriptionT = rclcpp::Subscription<autoware_auto_control_msgs::msg::AckermannControlCommand_<std::allocator<void> …
```
> fix(simple_planning_simulator): fix build error

- planning/behavior_path_planner/config/lane_change/lane_change.param.yaml
- planning/behavior_path_planner/docs/behavior_path_planner_lane_change_design.md
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/normal.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/lane_change_module_data.hpp
- planning/behavior_path_planner/src/scene_module/lane_change/manager.cpp
- planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
- planning/behavior_path_planner/src/utils/utils.cpp
By introducing this change, you can regulate lane change on crosswalk and intersection.
Changes for config is https://github.com/autowarefoundation/autoware_launch/pull/582
Tested in planning simulator with regulate parameters to `true`.
[TIER IV INTERNAL TEST](https://evaluation.tier4.jp/evaluation/reports/858af897-4998-5a87-abc5-7fa37b975c27?project_id=prd_jt)
Crosswalk:
https://github.com/autowarefoundation/autoware.universe/assets/10190493/2e3c08ef-d2ea-4259-a6bc-c1a0fa1f26cc
Intersection:
https://github.com/autowarefoundation/autoware.universe/assets/10190493/d051fddf-c938-4a48-b3ef-184f3fe5e63e
New parameters added.
Using default parameters, no effects.
If change regulatory parameters, you can regulate lane change on crosswalk and intersection. …
> feat(lane_change): regulate lane change on crosswalk and intersection

- launch/tier4_localization_launch/package.xml
Fixed error
```
+ rosdep install -y --from-paths src --ignore-src --rosdistro humble
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
tier4_localization_launch: Cannot locate rosdep definition for [landmark_based_localizer]
```
It was confirmed that the command passed normally.
N/A …
> fix(tier4_localization_launch):  fixed exec_depend

- planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
visualize backward drving path as greee arrows
> feat(start_planner): visualize backward driving path

- planning/behavior_path_planner/config/goal_planner/goal_planner.param.yaml
- planning/behavior_path_planner/config/start_planner/start_planner.param.yaml
- planning/behavior_path_planner/docs/behavior_path_planner_goal_planner_design.md
- planning/behavior_path_planner/docs/behavior_path_planner_start_planner_design.md
- planning/behavior_path_planner/include/behavior_path_planner/utils/geometric_parallel_parking/geometric_parallel_parking.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/goal_planner/goal_planner_parameters.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/goal_planner/shift_pull_over.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/start_planner/shift_pull_out.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/start_planner/start_planner_parameters.hpp
- planning/behavior_path_planner/src/scene_module/goal_planner/manager.cpp
- planning/behavior_path_planner/src/scene_module/start_planner/manager.cpp
- planning/behavior_path_planner/src/utils/geometric_parallel_parking/geometric_parallel_parking.cpp
- planning/behavior_path_planner/src/utils/goal_planner/shift_pull_over.cpp
- planning/behavior_path_planner/src/utils/start_planner/freespace_pull_out.cpp
- planning/behavior_path_planner/src/utils/start_planner/shift_pull_out.cpp
resample freespace pull out path to fix sparse drivable area.
and make params for resaple reference center line path interval
(the drivable area is out of lane but it will be fixed after start planner is finished at end pose in freespace area)
before
after
psim
2023/09/22 https://evaluation.tier4.jp/evaluation/reports/8252efaa-a564-5b45-a8bb-91fde156e462/?project_id=prd_jt
https://evaluation.tier4.jp/evaluation/reports/72bd5eb6-8f81-5a7f-98a1-caa6381c510b?project_id=prd_jt
none
none
[contribution …
> fix(start/goal_planner): resample path and make params 

- planning/motion_velocity_smoother/README.md
- planning/motion_velocity_smoother/config/default_motion_velocity_smoother.param.yaml
- planning/motion_velocity_smoother/include/motion_velocity_smoother/motion_velocity_smoother_node.hpp
- planning/motion_velocity_smoother/src/motion_velocity_smoother_node.cpp
Add a parameter to control "lateral acceleration filter" and "steering rate filter" in the motion_velocity_smoother.
https://github.com/autowarefoundation/autoware.universe/assets/21360593/13998ec2-91a7-468e-be30-6334d4729414
Run psim
None
> chore(motion_velocity_smoother): add enable curve filtering param

- planning/mission_planner/config/mission_planner.param.yaml
- planning/mission_planner/src/lanelet2_plugins/default_planner.cpp
- planning/mission_planner/src/lanelet2_plugins/default_planner.hpp
add a parameter of `check_footprint_inside_lanes`.
When this parameter is set to false, the feature to cancel the route planning when the footprint on the goal is outside the lanes is disabled.
psim
nothing
> feat(mission_planner): add param of check_footprint_inside_lanes

- control/pid_longitudinal_controller/include/pid_longitudinal_controller/longitudinal_controller_utils.hpp
- control/pid_longitudinal_controller/src/longitudinal_controller_utils.cpp
- control/pid_longitudinal_controller/src/pid_longitudinal_controller.cpp
- control/pid_longitudinal_controller/test/test_longitudinal_controller_utils.cpp
use tier4_autoware_utils::calcElevationAngle instead of an internally defined function.
NOTE:
**The sign of slope_angle will be opposite to the existing one.**
This is because the sign of calcElevationAngle in pid_longitudinal_controller and tier4_autoware_utils are different due to how the dz is calculated. "calcElevationAngle in pid_longitudinal_controller" is wrong.
- calcElevationAngle in pid_longitudinal_controller (wrong)
https://github.com/autowarefoundation/autoware.universe/blob/19114642146db7312a35f7b5841878207776ea6a/control/pid_longitudinal_controller/src/longitudinal_controller_utils.cpp#L119-L129
- calcElevationAngle in tier4_autoware_utils (correct)
https://github.com/autowarefoundation/autoware.universe/blob/19114642146db7312a35f7b5841878207776ea6a/common/tier4_autoware_uti …
> refactor(pid_longitudinal_controller): use common elevetation angle calculation

- control/pid_longitudinal_controller/src/pid_longitudinal_controller.cpp
The following PR uses `m_current_operation_mode.mode` to know if the current driving is autonomous or manual.
However, in my understanding, this value can be `AUTONOMOUS` even when the driving is manual.
https://github.com/autowarefoundation/autoware.universe/pull/2619
Actually, I think `m_current_operation_mode.is_autoware_control_enabled && m_current_operation_mode.mode == OperationModeState::AUTONOMOUS` is the correct one.
nothing
nothing …
> fix(pid_longitudinal_controller): use is_autoware_control_enabled for manual driving

- control/pid_longitudinal_controller/src/pid_longitudinal_controller.cpp
This PR
1. adds a feature that the state transits from EMERGENCY under the looser condition on manual driving.
2. changes the implementation of the PR: https://github.com/autowarefoundation/autoware.universe/pull/3644
**Regarding 1**
If the state transits to EMERGENCY for some reason on manual driving, the state cannot exit EMERGENCY unless the vehicle stops once even if the situation is not an emergency.
In this case, when we use engage-on-driving to transit to autonomous driving, since the state is EMERGENCY, the ego tries to stop once which is unnecessary.
To avoid this behavior, on manual driving, the emergency state should be able to transit to DRIVE without stopping.
**Regarding 2**
To implement the feature 1, this change is necessary.
Additionally, this feature should be applied to …
> feat(pid_longitudinal_controller): transit state from emergency under the looser condition on manual driving

- sensing/imu_corrector/src/gyro_bias_estimator.cpp
Add estimated gyro bias in diagnostics.
Launched Autoware and confirmed that the diagnostics are properly updated.
Not applicable
> feat(imu_corrector): add gyro_bias estimation in diag

- planning/behavior_velocity_intersection_module/config/intersection.param.yaml
- planning/behavior_velocity_intersection_module/src/manager.cpp
- planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
- planning/behavior_velocity_intersection_module/src/scene_intersection.hpp
- planning/behavior_velocity_intersection_module/src/util.cpp
- planning/behavior_velocity_intersection_module/src/util.hpp
- planning/behavior_velocity_intersection_module/src/util_type.hpp
Currently, the collision detection margin is prepared for the case where the traffic signal is green and red.
For more efficient intersection behavior, this PR added a collision detection margin for amber color.
Three traffic protected levels are defined.
- fully protected
- The target lane's traffic signal is red or the ego's traffic signal has an arrow.
- partially protected
- The target lane's traffic signal is amber
- unprotected
- The target lane's traffic signal is green
https://star4.slack.com/archives/C03QW0GU6P7/p1695379403867969?thread_ts=1695378610.532759&cid=C03QW0GU6P7
psim
More efficient intersection behavior considering amber traffic signal. …
> feat(intersection): consider amber traffic signal for collision detection level

- control/pid_longitudinal_controller/src/longitudinal_controller_utils.cpp
Depends on https://github.com/autowarefoundation/autoware.universe/pull/5090
In the case where the slope angle is positive before the goal and negative after the goal as shown in the figure, the current slope compensation works in the opposite direction.
psim
Better slope compensation when arriving at the goal.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/c …
> fix(pid_longitudinal_controller): better slope compensation

- common/motion_utils/include/motion_utils/trajectory/trajectory.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/start_goal_planner_common/utils.hpp
- planning/behavior_path_planner/src/utils/goal_planner/shift_pull_over.cpp
- planning/behavior_path_planner/src/utils/path_shifter/path_shifter.cpp
- planning/behavior_path_planner/src/utils/start_goal_planner_common/utils.cpp
- planning/behavior_path_planner/src/utils/start_planner/shift_pull_out.cpp
remove inverse orientation points after shifting path
edge case example
(④typo 3->2)
before
after
fix https://github.com/autowarefoundation/autoware.universe/pull/4950
> fix(start_planner): remove inverse orientation points

- planning/behavior_path_planner/include/behavior_path_planner/marker_utils/lane_change/debug.hpp
- planning/behavior_path_planner/include/behavior_path_planner/marker_utils/utils.hpp
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/base_class.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/path_safety_checker/path_safety_checker_parameters.hpp
- planning/behavior_path_planner/src/marker_utils/lane_change/debug.cpp
- planning/behavior_path_planner/src/marker_utils/utils.cpp
- planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp
- planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
Currently there is no way to verify objectFilter output for the lane change safety check.
So in this PR, I have add the visualization for object filters.
Yellow = current lane's object
Aqua = target lane's object
Magenta = other lane's object
None
1. Run PSIM.
2. Simulate lane change.
3. Place object similar to above's image.
4. `ros2 param set /planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner lane_change_right.publish_debug_marker true` or `ros2 param set /planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner lane_change_left.publish_debug_marker true`
5. make the the `object_filtered_cube` marker is checked.
None
None
None …
> feat(lane_change): object filter visualization

- planning/behavior_velocity_intersection_module/src/debug.cpp
- planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
- planning/behavior_velocity_intersection_module/src/util.cpp
- planning/behavior_velocity_intersection_module/src/util_type.hpp
Modified intersection occlusion calculation to calculate the distance of each point on the `division` if the point is occluded on the occlusion mask. Also added a marker for the projection.
https://tier4.atlassian.net/browse/RT1-3696
Psim
none.
none.
> feat(intersection): modify occlusion distance calculation and publish projection line

- planning/behavior_velocity_intersection_module/config/intersection.param.yaml
- planning/behavior_velocity_intersection_module/src/manager.cpp
- planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
- planning/behavior_velocity_intersection_module/src/scene_intersection.hpp
- planning/behavior_velocity_intersection_module/src/util.cpp
- planning/behavior_velocity_intersection_module/src/util_type.hpp
Added the option to stop before vehicle heading enters the oncoming lane when peeking offset is positive.
launcher PR: https://github.com/autowarefoundation/autoware_launch/pull/578
https://tier4.atlassian.net/browse/RT1-3284
Psim
https://github.com/autowarefoundation/autoware.universe/assets/28677420/c5b3a0ab-bb9c-4892-8bd1-c6d122b30537
This PR is off by default.
none
none …
> feat(intersection): ensure temporal stop before peeking into oncoming lane

- control/mpc_lateral_controller/src/mpc_lateral_controller.cpp
- control/pid_longitudinal_controller/src/pid_longitudinal_controller.cpp
- control/pure_pursuit/src/pure_pursuit/pure_pursuit_lateral_controller.cpp
use more specific logger names so that they can be controlled separately.
run psim
None
> refactor(controllers): use specific logger name

- planning/behavior_velocity_crosswalk_module/src/manager.cpp
- planning/behavior_velocity_crosswalk_module/src/manager.hpp
- planning/behavior_velocity_walkway_module/src/manager.cpp
- planning/behavior_velocity_walkway_module/src/manager.hpp
Applied the following fix to the crosswalk.
https://github.com/autowarefoundation/autoware.universe/pull/4823
---
Fix module launch condition so that it can activate crosswalk module in the map which has both regulatory element crosswalk and non regulatory element crosswalk.
psim
scenario test: https://evaluation.tier4.jp/evaluation/reports/4e7da0bf-e29b-5060-8c29-562bbbb7827a?project_id=prd_jt
Make it possible to use crosswalk module in specific map. …
> fix(crosswalk): fix module launch condition

- planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
In the image below
lane change module has mistakenly assume the the incoming object belongs to the target lane.
In this PR, we aim to fix this issue.
https://github.com/autowarefoundation/autoware.universe/assets/93502286/d5d9aa6d-7e47-476b-9902-75265aff85a8
https://github.com/autowarefoundation/autoware.universe/assets/93502286/05ad2b5b-e73a-44e4-8b4d-026f08f2686e
None
Test via PSIM
None
None
None …
> fix(lane_change): object filter other lane object

- planning/obstacle_avoidance_planner/src/node.cpp
- planning/path_smoother/src/elastic_band_smoother.cpp
Fixed the bug of
- applyInputVelocity
- extendTrajectory
inserting the stop point forward not as expected.
psim
scenario sim: https://evaluation.tier4.jp/evaluation/reports/6b8930eb-2304-5993-a0c4-9bdff0e815c4?project_id=prd_jt
Nothing
> fix(elastic_band, obstacle_avoidance_planner): fix velocity update

- common/autoware_auto_geometry/CMakeLists.txt
- common/autoware_auto_tf2/CMakeLists.txt
- common/autoware_auto_tf2/include/autoware_auto_tf2/tf2_autoware_auto_msgs.hpp
- planning/behavior_path_planner/CMakeLists.txt
- planning/surround_obstacle_checker/CMakeLists.txt
add workaround for [tf2 update](https://github.com/ros2/geometry2/pull/616)
> chore: add workaround for tf2 update

- planning/behavior_path_planner/include/behavior_path_planner/planner_manager.hpp
- planning/behavior_path_planner/src/planner_manager.cpp
Publish the processing time of each module in behavior_path_planner to debug messages.
None
PSim
When "verbose" is set to True, The behavior_path_planner_node will produce a topics in /planning/scenario_planning/lane_driving/behavior_planning/behavior_planner_manager/debug/processing_time/*
```bash
ros2 run plotjuggler plotjuggler
```
and select /planning/scenario_planning/lane_driving/behavior_planning/behavior_planner_manager/debug/processing_time/*
The verbose parameter is an existing parameter in 
> autoware_launch/autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner.param.yaml
This PR will log the processing time number as in this ros logging:
into debugging topics.
None …
> perf(behavior_path_planner): add processing time publishers to output results from the timer

- localization/landmark_based_localizer/landmark_tf_caster/CMakeLists.txt
- localization/landmark_based_localizer/landmark_tf_caster/package.xml
`package.xml` needs a dependency for `libopencv-dev` (see https://github.com/autowarefoundation/autoware-deb-packages/actions/runs/6275268080/job/17042494020?pr=33)
> build(landmark_tf_caster): add missing libopencv-dev dependency

- planning/behavior_path_planner/include/behavior_path_planner/utils/goal_planner/util.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/utils.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/path_utils.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/start_planner/util.hpp
- planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
- planning/behavior_path_planner/src/utils/goal_planner/util.cpp
- planning/behavior_path_planner/src/utils/lane_change/utils.cpp
- planning/behavior_path_planner/src/utils/path_utils.cpp
- planning/behavior_path_planner/src/utils/start_planner/freespace_pull_out.cpp
- planning/behavior_path_planner/src/utils/start_planner/geometric_pull_out.cpp
- planning/behavior_path_planner/src/utils/start_planner/shift_pull_out.cpp
- planning/behavior_path_planner/src/utils/start_planner/util.cpp
add empty guard to combinePath
fix freespace pull out dying
```
(gdb) p path2.points
$4 = std::vector of length 0, capacity 0
(gdb) f 15
#15 0x00007f5c9b673d94 in behavior_path_planner::FreespacePullOut::plan (this=<optimized out>, start_pose=..., end_pose=...) at /home/kosuke55/pilot-auto/src/autoware/universe/planning/behavior_path_planner/src/utils/start_planner/freespace_pull_out.cpp:100
100         start_planner_utils::combineReferencePath(last_path, road_center_line_path),
(gdb) f 14
#14 behavior_path_planner::start_planner_utils::combineReferencePath (path1=..., path2=...) at /home/kosuke55/pilot-auto/src/autoware/universe/planning/behavior_path_planner/src/utils/start_planner/util.cpp:47
47        path.points.insert(path.points.end(), next(path2.points.begin()), …
```
> fix(behavior_path_planner): add empty guard to combinePath

- common/motion_utils/include/motion_utils/trajectory/trajectory.hpp
- common/tier4_autoware_utils/CMakeLists.txt
- common/tier4_autoware_utils/include/tier4_autoware_utils/system/backtrace.hpp
- common/tier4_autoware_utils/src/system/backtrace.cpp
- Change backtrace logging level  to debug
- add backtrace print in the motion_util functions
Note: how to change the logging level
```
ros2 component load /planning/scenario_planning/lane_driving/behavior_planning/behavior_planning_container logging_demo logging_demo::LoggerConfig
ros2 service call /config_logger logging_demo/srv/ConfigLogger "{logger_name: 'tier4_autoware_utils', level: DEBUG}"
```
None
run psim.
None
None
None …
> feat(motion_utils): add debug backtrace print

- localization/ndt_scan_matcher/config/ndt_scan_matcher.param.yaml
- localization/ndt_scan_matcher/include/ndt_scan_matcher/ndt_scan_matcher_core.hpp
- localization/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp
This PR offersto add exe_time to diagnostics.
Exe time is useful for observe does NDT have problems while matching scans. I can say with my observations, if NDT exe_time is exceeded 24ms, it will be most likely started to cannot match scans properly. So while I'm checking runtime_monitor i would like to see NDT exe_time. Formerly this PR is a part of https://github.com/autowarefoundation/autoware.universe/pull/4854.
Related: https://github.com/autowarefoundation/autoware_launch/pull/559
All added options runned through logging simulator and test vehicle. 
It gives a facility for observing changes in nearest_voxel_transformation_likelihood and exe_time.
The Reviewers **must** check the checkboxes below before approval. …
> feat(ndt_scan_matcher): adding exe time to diagnostics for checking runtime_monitor

- common/autoware_auto_geometry/CMakeLists.txt
- common/autoware_auto_tf2/CMakeLists.txt
- common/autoware_auto_tf2/include/autoware_auto_tf2/tf2_autoware_auto_msgs.hpp
- planning/behavior_path_planner/CMakeLists.txt
- planning/surround_obstacle_checker/CMakeLists.txt
remove duplicated tf2 function introduced in [this PR](https://github.com/ros2/geometry2/pull/616).
This causes build error as below.
```
/home/daisuke/workspace/autoware/src/universe/autoware.universe/common/autoware_auto_tf2/include/autoware_auto_tf2/tf2_autoware_auto_msgs.hpp:60:13: error: redefinition of ‘void tf2::doTransform(const T&, T&, const TransformStamped&) [with T = geometry_msgs::msg::Point32_<std::allocator<void> >; geometry_msgs::msg::TransformStamped = geometry_msgs::msg::TransformStamped_<std::allocator<void> >]’
60 | inline void doTransform(
```
This PR is necessary after next humble sync introduces tf2 geometry msgs 0.25.4. …
> fix(autoware_auto_tf2): remove tf2 geometry function duplicated in tf2 geometry msgs

- localization/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp
Removed duplicate parameter declarations `initial_pose_timeout_sec_`
https://github.com/autowarefoundation/autoware.universe/pull/4916
logging_simulator on sample rosbag
The `ndt_scan_matcher` node will not crash.
> fix(ndt_scan_matcher): removed duplicate parameter declarations "initial_pose_timeout_sec_"

- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
fix goal searcher dying in free space
tested with https://github.com/autowarefoundation/autoware.universe/pull/5114
> fix(goal_planner): fix goal searcher dying in free space

- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
disable freespace planner when fixed goal
(no behavior chanage)
> fix(goal_planner): disable freespace planner when fixed goal

- planning/behavior_velocity_out_of_lane_module/src/decisions.cpp
- planning/behavior_velocity_out_of_lane_module/src/filter_predicted_objects.hpp
When the `calcLateralOffset()` is called for an object's predicted_path, if the object velocity is zero, then all predicted_path points are in the same position, and the lateral distance can not be calculated appropriately. This PR fixes the issue.
None
run psim with out_of_lane module
None
None
Some unstable behavior of the out_of_lane may be fixed. …
> fix(out_of_lane): lateral distance calculation for predicted path

- localization/localization_error_monitor/src/node.cpp
Removed default parameters in the C++ codes in localization_error_monitor.
It is able to build localization_error_monitor locally.
It is also confirmed that the [logging_simulator on the tutorial](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/rosbag-replay-simulation/) works fine.
Less prone to unexpected behavior when parameter definitions are incomplete. …
> refactor(localization_error_monitor): rework parameters

- sensing/gnss_poser/CMakeLists.txt
- sensing/gnss_poser/config/gnss_poser.param.yaml
- sensing/gnss_poser/launch/gnss_poser.launch.xml
- sensing/gnss_poser/src/gnss_poser_core.cpp
Removed default parameters in the C++ codes in gnss_poser
It is able to build gnss_poser locally.
It is also confirmed that the [logging_simulator on the tutorial](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/rosbag-replay-simulation/) works fine.
Less prone to unexpected behavior when parameter definitions are incomplete. …
> refactor(gnss_poser): rework parameters

- sensing/pointcloud_preprocessor/include/pointcloud_preprocessor/time_synchronizer/time_synchronizer_nodelet.hpp
- sensing/pointcloud_preprocessor/launch/preprocessor.launch.py
- sensing/pointcloud_preprocessor/src/time_synchronizer/time_synchronizer_nodelet.cpp
Organize twist input of time_synchronizer as well as concatenate_filter
Not applicable
The node will subscribe to /sensing/vehicle_velocity_converter/twist_with_covariance from now on. But we see no practical effects on the system behavior given that the node is not used yet in the system as far as we know.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contr …
> feat(time_synchronizer): organize twist input

- planning/behavior_velocity_intersection_module/config/intersection.param.yaml
- planning/behavior_velocity_intersection_module/package.xml
- planning/behavior_velocity_intersection_module/src/manager.cpp
- planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
- planning/behavior_velocity_intersection_module/src/scene_intersection.hpp
- planning/behavior_velocity_intersection_module/src/util.cpp
- planning/behavior_velocity_intersection_module/src/util.hpp
Add a flag to use the planned velocity profile from the upstream modules, especially for stop line.
https://tier4.atlassian.net/browse/RT1-3624
launcher PR: https://github.com/autowarefoundation/autoware_launch/pull/597
evaluator: https://evaluation.tier4.jp/evaluation/reports/eb4df583-e8d5-5def-92f1-b163d12ddba5?project_id=prd_jt
In the attached video ego vehicle takes 8 seconds to arrive at the walkway virtual wall, and the `collision_detection.collision_start_margin_time = 4.0`[s] and ego stops at the walkway for 1[s], so the NPC travelling at 3[m/s] from the position which is (8 + 4 + 1) x 3 = 39m before the collision point is expected to be treated as `safe` by the intersection module but actually collides while ego is stopping at the walkway. 
Before this PR, the collision happens …
> feat(intersection): use planned velocity from upstream modules

- localization/ndt_scan_matcher/README.md
- localization/ndt_scan_matcher/config/ndt_scan_matcher.param.yaml
- localization/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp
Since there were still default values in the cpp code, which may occur unexpected results, I deleted them so that `ndt_scan_matcher` can get those value only from `ndt_scan_matcher.param.yaml`.
On this operation, parameter `map_frame` is extracted to `ndt_scan_matcher.param.yaml`.
Plus, I updated `README.md` so that it matches `ndt_scan_matcher.param.yaml`.
Related: https://github.com/autowarefoundation/autoware_launch/pull/596
It is able to build ndt_scan_matcher locally.
It is also confirmed that the [logging_simulator on the tutorial](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/rosbag-replay-simulation/) works fine.
This won't directly do something to the system.
It is expected to be less prone to unexpected behavior when parameter …
> refactor(ndt_scan_matcher): delete default parameters from ndt_scan_matcher_core.cpp

- launch/tier4_localization_launch/launch/pose_twist_estimator/pose_twist_estimator.launch.xml
`automatic_pose_initializer` should be executed only when `gnss_enabled` is true.
Otherwise, `pose_initializer` continuously says "GNSS is not supported"
Note that this PR does not affect any system behavior, but if you set `gnss_enabled:=false` manually, it helps you a lot.
CI
No effect. 
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-reque …
> feat(pose_twist_estimator): automatically initialize pose only with gnss

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/start_planner/start_planner_module.hpp
- planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
`last_approved_pose_` is the pose before start driving backward. 
It replace with `original_start_pose_` and update of `last_approved_pose_` is not necessary.  
output of 
```
ros2 topic echo /planning/hazard_lights_cmd
```
shows hazard lights on
> refactor(behavior_path_planner): remove last_approved_pose_ from start_planner

- perception/traffic_light_fine_detector/README.md
- perception/traffic_light_fine_detector/launch/traffic_light_fine_detector.launch.xml
It also updates default model and data paths. 
[pull …
> fix(traffic_light_fine_detector): add data_path arg and update default model path

- perception/traffic_light_ssd_fine_detector/README.md
- perception/traffic_light_ssd_fine_detector/launch/traffic_light_ssd_fine_detector.launch.xml
As https://github.com/autowarefoundation/autoware/pull/3375 was merged to Autoware.universe. It is possible to use artifacts downloaded there.
https://github.com/autowarefoundation/autoware.universe/pull/3145 was merged and old path to model file is outdated. 
It also updates onnx_file and label_file args and README.
See https://github.com/autowarefoundation/autoware.universe/issues/3137 …
> fix(traffic_light_ssd_fine_detector): add arg data_path, update model file path

- perception/tensorrt_yolo/README.md
- perception/tensorrt_yolo/launch/tensorrt_yolo.launch.xml
As https://github.com/autowarefoundation/autoware/pull/3375 was merged to Autoware.universe. It is possible to use artifacts downloaded there.
https://github.com/autowarefoundation/autoware.universe/pull/3142 was merged and old path to model file is outdated. 
It also updates engine_file, onnx_file, label_file and calib_cache_file in launch and README. …
> fix(tensorrt yolo): update model path

- perception/image_projection_based_fusion/launch/pointpainting_fusion.launch.xml
As https://github.com/autowarefoundation/autoware/pull/3375 was merged to Autoware.universe. It is possible to use artifacts downloaded there.
https://github.com/autowarefoundation/autoware.universe/pull/4904 was merged and old path to model file is outdated. 
It updates model_path arg as well.
The PR …
> fix(image_projection_based_fusion): add arg data_path, update model_path

- planning/behavior_velocity_intersection_module/package.xml
This PR adds the missing `grid_map_core` dependency, used in the code but not declared in `package.xml`
> build(behavior_velocity_intersection_module): add missing grid_map_core dependency

- localization/ekf_localizer/package.xml
- localization/gyro_odometer/package.xml
- localization/landmark_based_localizer/ar_tag_based_localizer/package.xml
- localization/landmark_based_localizer/landmark_tf_caster/package.xml
- localization/localization_error_monitor/package.xml
- localization/yabloc/yabloc_common/package.xml
- localization/yabloc/yabloc_image_processing/package.xml
- localization/yabloc/yabloc_particle_filter/package.xml
- localization/yabloc/yabloc_pose_initializer/package.xml
This PR derived from https://github.com/autowarefoundation/autoware.universe/pull/3606
result of unused.sh (https://github.com/autowarefoundation/autoware/issues/3468)
```
--- Checking src/universe/autoware.universe/localization/ekf_localizer/package.xml ---
sensor_msgs seems not to be used
std_msgs seems not to be used
--- Checking src/universe/autoware.universe/localization/pose_initializer/package.xml ---
--- Checking src/universe/autoware.universe/localization/pose2twist/package.xml ---
--- Checking src/universe/autoware.universe/localization/yabloc/yabloc_particle_filter/package.xml ---
libgoogle-glog-dev seems not to be used
tf2_sensor_msgs seems not to be used
--- Checking src/universe/autoware.universe/localization/yabloc/yabloc_monitor/package.xml ---
--- Checking …
```
> refactor(localization_packages): remove unused <depend> in packages.xml files

- launch/tier4_control_launch/launch/control.launch.py
Add missed launch parameter.
Tested in Psim(enabled and disabled), it worked.
> feat(tier4_control_launch): add launch argument for predicted path checker

- planning/behavior_path_planner/config/lane_change/lane_change.param.yaml
- planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/lane_change_module_data.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/utils.hpp
- planning/behavior_path_planner/src/scene_module/lane_change/manager.cpp
- planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
- planning/behavior_path_planner/src/utils/lane_change/utils.cpp
Add lane expansion parameters and logic for object filtering in lane change module. This improves safety check by allowing user to determine if they want to consider slightly out of lane object as target.
Note: 
Purple cube: other lane object
Aqua cube: target lane object
Yellow cube: current lane object
https://github.com/autowarefoundation/autoware_launch/pull/601
Place target objects via PSIM
None
None
None
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contri …
> feat(lane_change): expand target lanes for object filtering

- perception/crosswalk_traffic_light_estimator/src/node.cpp
Since the shape of the pedestrian lights should be CIRCLE, I changed it from UNKNOWN to CIRCLE.
I confirmed this works with rosbag.
The output of `/perception/traffic_light_recognition/fusion/traffic_signals`
```
stamp:
sec: 1695706515
nanosec: 196955648
signals:
- traffic_signal_id: 1019
elements:
- color: 1
shape: 1
status: 0
confidence: 0.9999982118606567
- traffic_signal_id: 1022
elements:
- color: 1
shape: 1
status: 0
confidence: 0.9999982118606567
```
The output of `/perception/traffic_light_recognition/fusion/traffic_signals`
ID 1026 and 1027 are the pedesrian lights, and their shape is 1 (CIRCLE).
```
---
stamp:
sec: 1695706515
nanosec: 196955648
signals:
- traffic_signal_id: 1019
elements:
- color: 1
shape: 1
status: 0
confidence: 0.9999982118606567
- traffic_signal_id: 1022 …
```
> fix(crosswalk_traffic_light_estimator): change the shape of pedestrian light to CIRCLE

- planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
- If there are multiple elements in traffic signal, crosswalk module may fail to find the RED signal in the current implementation.
I fixed it to check all elements in the signal.
- Check the shape of the signal because the shape of pedestrian lights is CIRCLE in Autoware.
Related ticket:
[TIER IV INTERNAL](https://tier4.atlassian.net/browse/RT0-29271)
NOTE: 
This PR should be merged with https://github.com/autowarefoundation/autoware.universe/pull/5168
CI:
[TIER IV INTERNAL](https://evaluation.tier4.jp/evaluation/reports/72baadd6-1a96-56f0-af13-29c60ae56139?project_id=prd_jt) …
> fix(crosswalk): check all elements in traffic signal

- planning/planning_debug_tools/scripts/trajectory_visualizer.py
Sometimes `self.im10` is undefined because the animator starts before `setPlotTrajectory` is called.
none.
> fix(trajectory_visualizer): fix plotter error

- system/system_monitor/include/system_monitor/process_monitor/process_monitor.hpp
- system/system_monitor/src/process_monitor/process_monitor.cpp
Since the enhancement from https://github.com/autowarefoundation/autoware.universe/pull/4553/, it has been reported that reading the full return of the ```top``` command with hundreds of processes could lead to failure in boost::process::child.
In this PR, we step back the ```top```  reading in boost::process::child to the original version in https://github.com/autowarefoundation/autoware.universe/pull/4553/ which means reading only the program names by default. Then for Top-rated processes, we try to read its command-line name in ```/proc/{PID}/cmdline```. If the reading of a process fails (probably the process ends after the top command), we will only show its program name instead.
None.
PSim …
> perf(system_monitor): fix program command line reading

- common/tier4_logging_level_configure_rviz_plugin/CMakeLists.txt
- common/tier4_logging_level_configure_rviz_plugin/config/logger_config.yaml
- common/tier4_logging_level_configure_rviz_plugin/include/tier4_logging_level_configure_rviz_plugin/logging_level_configure.hpp
- common/tier4_logging_level_configure_rviz_plugin/package.xml
- common/tier4_logging_level_configure_rviz_plugin/src/logging_level_configure.cpp
Update logger level reconfigure plugin.
- Use node interface following https://github.com/autowarefoundation/autoware.universe/pull/5146
- Move hard-corded configuration into yaml file
- Make the panel scrollable
- Change the button color based on the logger level
Special thanks to Chat-GPT. This revision is mostly done by his implementation.
https://github.com/autowarefoundation/autoware.universe/assets/21360593/7613845c-7d72-4222-accb-650b679aedc1
None
run psim
None
None
None …
> feat(logger_level_reconfigure_plugin): use node interface and some cosmetic updates

- planning/behavior_velocity_crosswalk_module/config/crosswalk.param.yaml
- planning/behavior_velocity_crosswalk_module/src/manager.cpp
- planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
- planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp
Currently, the timeout parameter to decide if the pedestrian has the intention to walk to the crosswalk is constant.
In order not to be too conservative, this parameter should depend on the distance from the pedestrian to the crosswalk.
This PR implements the feature.
psim
scenario sim: https://evaluation.tier4.jp/evaluation/reports/18915c07-9a27-5ffc-8a34-5394fd2b4f2b?project_id=prd_jt
nothing
[pull …
> feat(crosswalk): dyanmic timeout for no intention to walk decision

- planning/behavior_velocity_out_of_lane_module/CMakeLists.txt
- planning/behavior_velocity_out_of_lane_module/README.md
- planning/behavior_velocity_out_of_lane_module/config/out_of_lane.param.yaml
- planning/behavior_velocity_out_of_lane_module/src/calculate_slowdown_points.hpp
- planning/behavior_velocity_out_of_lane_module/src/decisions.cpp
- planning/behavior_velocity_out_of_lane_module/src/filter_predicted_objects.hpp
- planning/behavior_velocity_out_of_lane_module/src/footprint.cpp
- planning/behavior_velocity_out_of_lane_module/src/lanelets_selection.cpp
- planning/behavior_velocity_out_of_lane_module/src/manager.cpp
- planning/behavior_velocity_out_of_lane_module/src/scene_out_of_lane.cpp
- planning/behavior_velocity_out_of_lane_module/src/scene_out_of_lane.hpp
- planning/behavior_velocity_out_of_lane_module/src/types.hpp
This PR improves the creation of the stop point decided by the `out_of_lane` module.
Launch PR: https://github.com/autowarefoundation/autoware_launch/pull/615
Psim.
The `out_of_lane` module stop point is better calculated but it is still too unstable.
> fix(out_of_lane): improve stop decision

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/path_safety_checker/safety_check.hpp
- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
- planning/behavior_path_planner/src/utils/path_safety_checker/safety_check.cpp
goal_planner module secure lateral distance for its path planning with corresponding to the centrifugal force
Psim test was performed as figures bellow.
Raw values in the new functions seems to appropriate.
[Screencast from 10-03-2023 02:47:20 PM.webm](https://github.com/autowarefoundation/autoware.universe/assets/141538661/9e8225e3-9255-4ee8-9444-51b25a49e313)
The approaching paths become to secure lateral distance.
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main …
> feat(goal_planner): secure lateral distance for path planning with corresponding to the centrifugal force

- .github/sync-files.yaml
Directly related sync job:
- https://github.com/autowarefoundation/autoware.universe/pull/4372
To me, with the latest changes introduced by us, the sync job has grown way too much in complexity to be easily understood by anyone.
I think it is time to cut off the sync job at least for the `build-and-test-differential.yaml` workflow.
At least until we find a better way to sync this job. Or maybe once we make the containers smaller, we can remove the self hosted option too.
It syncs from:
- https://github.com/autowarefoundation/autoware_common/blob/main/.github/workflows/build-and-test-differential.yaml
to:
- https://github.com/autowarefoundation/autoware.universe/blob/main/.github/workflows/build-and-test-differential.yaml
But while syncing, it makes some brittle changes to the original …
> ci(build-and-test-differential): remove sync for the build-and-test-differential workflows

- mkdocs.yaml
This reverts commit ac06a5c2e05bc166478d1ff5e0d730471089a41c.
The module mkdocs_macros is required to convert json schema to markdown table when mkdocs deploys documentation.
Relevant PR:
https://github.com/autowarefoundation/autoware.universe/pull/4656
https://github.com/autowarefoundation/autoware.universe/pull/4372 …
> revert: "chore: sync files (#4372)"

- planning/obstacle_cruise_planner/src/node.cpp
fix coordinate transformation. linear.x denotes longtidional velocity, not the x velocity in the world coordinate
The value of projection speed are confirmed.
Tier 4 internal tests ware also performed in well
Obstacle cruise planner become to deal with the against vehicles as stop or slow down objects
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributin …
> fix(obstacle_cruise_planner): fix coordinate transformation bag

- localization/ndt_scan_matcher/config/ndt_scan_matcher.param.yaml
In this pull request, I propose to change the default value of `initial_estimate_particles_num`, mainly because the initial pose estimation at AWSIM Nishi-Shinjuku fails about 10% of the time.
https://github.com/autowarefoundation/autoware_launch/pull/618
Performed 1000 initial position estimations and recorded TP scores.
mean_score: 5.171 ± 1.488
mean_elapsed_time: 0.537 ± 0.036 [sec]
mean_score: 5.938 ± 0.911
mean_elapsed_time: 1.073 ± 0.043 [sec]
The TP score improves, but processing time is approximately doubled.
Tested by
1. logging simulator about the [sample rosbag](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/rosbag-replay-simulation/).
2. AWSIM
Improves the performance of initial position estimation, but it takes more time in …
> perf(ndt_scan_matcher): changed default `initial_estimate_particles_num` to 200

- launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml
- launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_radar_fusion_based_detection.launch.xml
- launch/tier4_perception_launch/launch/object_recognition/detection/lidar_based_detection.launch.xml
- launch/tier4_perception_launch/launch/perception.launch.xml
- perception/detected_object_validation/config/obstacle_pointcloud_based_validator.param.yaml
- perception/detected_object_validation/include/obstacle_pointcloud_based_validator/obstacle_pointcloud_based_validator.hpp
- perception/detected_object_validation/launch/obstacle_pointcloud_based_validator.launch.xml
- perception/detected_object_validation/src/obstacle_pointcloud_based_validator.cpp
This PR add threshold pointcloud number for each class in `obstacle_pointcloud_based_validator` to reduce FP of less pointcloud vehicle which is detected by DNN(Centerpoint) model.
[TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT0-29267?focusedCommentId=139292)
Tested by logging_simulator and internal rosbag.
Green: Centerpoint result 
Yellow: Validator result 
Blue: Predicted result …
> fix(detected_object_validation): change the points_num of the validator to be set class by class

- planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
Without this change:
`planner_param_.stop_distance_from_object` is applied even if stop line is associated with crosswalk .
It caused putting stop line at wrong position.
[Screencast from 2023年10月05日 15時44分41秒.webm](https://github.com/autowarefoundation/autoware.universe/assets/32741405/9e6294ca-54f1-430f-8334-c0f82951b419)
With this change:
delete margin so that vehicle can stop at stop line.
[Screencast from 2023年10月05日 15時56分03秒.webm](https://github.com/autowarefoundation/autoware.universe/assets/32741405/fe68e6f3-73a3-4a59-949b-8f839392c37d)
confirmed with psim …
> fix(behavior_velocity_crosswalk_module): stop at stop line associated with crosswalk

- planning/behavior_velocity_intersection_module/config/intersection.param.yaml
- planning/behavior_velocity_intersection_module/src/manager.cpp
- planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
- planning/behavior_velocity_intersection_module/src/scene_intersection.hpp
This PR contains two objectives
1. make configurable to enable/disable the exception behavior in the private areas.
2. change the exception behavior in the private area. BEFORE: If the ego are stopping by a stuck object for a several time duration, then the intersection module cancel the stopping. AFTER: If it is enabled by the launch parameters, the intersection module disregard the stuck objects.
Related PR for launch setting
https://github.com/autowarefoundation/autoware_launch/pull/622
psim test was performed.
disabled
enabled
https://evaluation.tier4.jp/evaluation/reports/fd946252-3247-50f5-9a70-128092c8a5c6?project_id=prd_jt
https://star4.slack.com/archives/C03QW0GU6P7/p1696496558303159
Nothing
New enable/disable parameter is added
No longer behave exceptionally on private area.
The …
> feat(intersection)!: disable the exception behavior in the private areas

- planning/behavior_path_planner/config/lane_change/lane_change.param.yaml
- planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/lane_change_module_data.hpp
- planning/behavior_path_planner/src/scene_module/lane_change/manager.cpp
Separating the parameters for safety check during lane change execution and lane change cancel.
THE FOLLOWING NEEDS TO BE MERGE FIRST: https://github.com/autowarefoundation/autoware_launch/pull/626
> feat(lane_change): separate execution and cancel safety check param

- planning/behavior_velocity_intersection_module/config/intersection.param.yaml
- planning/behavior_velocity_intersection_module/src/manager.cpp
- planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
- planning/behavior_velocity_intersection_module/src/scene_intersection.hpp
When ego vehicle entered the intersection on green traffic light collision is not detected instantly because NPC vehicles are very slow. This PR adds the feature to detect whatever vehicles in the attention area and stop for a while.
https://tier4.atlassian.net/browse/RT0-29284
launcher PR: https://github.com/autowarefoundation/autoware_launch/pull/623
In the attached video [00:07], "intersection" stop line is inserted even if the ego/NPCs are very slow.
https://github.com/autowarefoundation/autoware.universe/assets/28677420/bb195312-7b2a-4714-acb7-735c79f8b610
evaluator: https://evaluation.tier4.jp/evaluation/reports/ec7990b5-f3b7-549c-822d-22c3f72201f1?project_id=prd_jt
none.
none.
The PR reviewers **must** check …
> feat(intersection): yield initially on green light

- control/vehicle_cmd_gate/src/vehicle_cmd_gate.cpp
The original filtering condition in `vehicle_cmd_gate` did not take into account a case where the operation mode is `STOP` and `is_autoware_control_enabled` is true. 
INTERNAL LINK: https://tier4.atlassian.net/browse/RT0-29417
Tested with planning simulator that
- With this PR, psim works normally with the sample map
- If `simple_planning_simulator` incorporates acceleration error (e.g. by adding 0.1[m/s/s] offset in `.longitudinal.acceleration` in [this line](https://github.com/autowarefoundation/autoware.universe/blob/c508aa71c19d09f4198e24cd93c39191c9dacca6/simulator/simple_planning_simulator/src/simple_planning_simulator/simple_planning_simulator_core.cpp#L338)), start planning_simulator, runs the vehicle straight, and push `STOP` button to change the operation mode,
- without this …
> fix(vehicle_cmd_gate): fix filtering condition

- planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
- planning/behavior_path_planner/src/utils/lane_change/utils.cpp
> fix(lane_change): add guard to neigibor lanelets

- planning/behavior_path_planner/include/behavior_path_planner/planner_manager.hpp
- planning/behavior_path_planner/src/behavior_path_planner_node.cpp
- planning/behavior_path_planner/src/planner_manager.cpp
Separate processing time publish function and call it every time.
```
/planning/scenario_planning/lane_driving/behavior_planning/behavior_planner_manager/debug/processing_time/avoidance: tier4_debug_msgs/msg/Float64Stamped
/planning/scenario_planning/lane_driving/behavior_planning/behavior_planner_manager/debug/processing_time/avoidance_by_lane_change: tier4_debug_msgs/msg/Float64Stamped
/planning/scenario_planning/lane_driving/behavior_planning/behavior_planner_manager/debug/processing_time/goal_planner: tier4_debug_msgs/msg/Float64Stamped
/planning/scenario_planning/lane_driving/behavior_planning/behavior_planner_manager/debug/processing_time/lane_change_left: tier4_debug_msgs/msg/Float64Stamped
/planning/scenario_planning/lane_driving/behavior_planning/behavior_planner_manager/debug/pro …
```
> refactor(behavior_path_planner): separate processing time function

- planning/obstacle_velocity_limiter/README.md
- planning/obstacle_velocity_limiter/include/obstacle_velocity_limiter/obstacle_velocity_limiter_node.hpp
- planning/obstacle_velocity_limiter/src/obstacle_velocity_limiter_node.cpp
Use Float64 msg for processing time as other planning modules do.
run psim
None
> chore(obstacle_velocity_limiter): publish processing time as float

- planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
- planning/behavior_velocity_intersection_module/src/scene_merge_from_private_road.cpp
- planning/behavior_velocity_intersection_module/src/util.cpp
- planning/behavior_velocity_intersection_module/src/util_type.hpp
For precise stop line position calculation, find the first intersection point of vehicle footprint with the detection area instead of the position of PathPoint.
Psim
https://github.com/autowarefoundation/autoware.universe/assets/28677420/a7893b55-874f-44e8-a632-cd813f60dac0
none.
none.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-g …
> feat(intersection): find stop line from footprint intersection with areas

- planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
Make the collision check to consider the object width.
The following case will be the corner case of the implementation without this PR.
**before**
The predicted path without the width is used for collision check with the ego lane (orange polygon along the ego path).
Therefore, the intersection stop does not appear not as expected.
**after**
psim
nothing …
> fix(intersection): collision check considering object width

- planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
No stuck detection when the ego turns left
**before**
Unnecessary stop line is inserted.
**after**
psim
No stuck detection when turning left
> feat(intersection): not detect stuck vehicle when turning left

- planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
1) 
- ego is in terminal current lanes
- stationary object is in current lanes
-> keep distance against the object 
2) 
- ego is in terminal current lanes
-> keep lane change buffer to the terminal
3) 
- ego is NOT in terminal current lanes
- stationaly object is target lane
-> keep distance against the object 
4)
- ego is NOT in terminal current lanes
-> keep lane change buffer to the terminal
psim
none
none
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contrib …
> feat(lane_change): keep distance against avoidable stationary objects

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/normal.hpp
- planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
In the original implementation, when the vehicle is stopped, the lane change module samples only one trajectory with `max_acc`. However, when the vehicle is stuck, we need to sample all possible trajectories to escape the stuck situation.
This PR updates the sampling logic so that all possible trajectories are sampled in the stuck situation as in the picture.
[TIERIV INTERNAL TICKET](https://tier4.atlassian.net/browse/RT0-29199)
Run Psim.
None
None
The vehicle may be able to avoid obstacles by lane change when the ego is in stuck. …
> feat(lane_change): sampling all possible longitudinal acceleration when the ego is in stuck

- planning/behavior_velocity_intersection_module/config/intersection.param.yaml
- planning/behavior_velocity_intersection_module/src/manager.cpp
- planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
- planning/behavior_velocity_intersection_module/src/scene_intersection.hpp
Set parameters for stuck vehicle detection turn_direction
launcher PR: https://github.com/autowarefoundation/autoware_launch/pull/630
related scenarios passed
none.
-  [X] The PR follows the [pull request guidelines].
> chore(intersection): parameterize stuck vehicle detection turn_direction

- planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
fixed lane change visualization not showing safe information during debugging.
> fix(lane_change): fixed debug visualization bug

- planning/behavior_velocity_intersection_module/src/util.cpp
Fixed the error caused by unsigned subtraction
https://evaluation.tier4.jp/evaluation/reports/1b310650-c475-5c8d-a468-a5b5c3a701cc?project_id=prd_jt
none.
none.
none.
> fix(intersection): fix unsigned subtraction

- planning/behavior_path_planner/include/behavior_path_planner/data_manager.hpp
- planning/behavior_path_planner/test/test_drivable_area_expansion.cpp
Remove ununsed data in `PlannerData`'s structure.
> refactor(behavior_path_planner): remove planner data unused variable

- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
no need to execute freespace pull over after arriving modified goal
evaluator_description: fix/disable_freespace_on_modified_goal
2023/10/12 https://evaluation.tier4.jp/evaluation/reports/9712fece-0731-5d14-8907-a7935e35a6c4/?project_id=prd_jt
none
none
> fix(goal_planner): disable freespace pull over after arriving modified  goal

- perception/euclidean_cluster/README.md
The given link was broken. I have updated with the correct link.
**Note**: Confirm the [contribution guidelines](https://autowarefoundation.github.io/autoware-documentation/main/contributing/) before submitting a pull request.
Click the `Preview` tab and select a PR template:
- [Standard change](?expand=1&template=standard-change.md)
- [Small change](?expand=1&template=small-change.md)
**Do NOT send a PR with this description.**
> fix(euclidean cluster): update the broken link

- planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
Fix lane change path not appear when `passParkedObject` returns false.
> fix(lane_change): fix force path not appear

- planning/behavior_path_planner/src/utils/lane_change/utils.cpp
- planning/behavior_path_planner/src/utils/path_utils.cpp
`getPathTurnSignal` function uses `shifted_path` and `shift_line``'s `start_idx` and `end_idx`  information to generate turn signal information. 
However, there are possibility that the path points is deleted by `PathShifter`, which will result in the number of points in `shifted_path` is less than `end_idx`.
To avoid behavior path planner node dead, I have added a guard.
As this is mostly happens for lane change module, we also add the guard to remove lane change candidate path when this happens. …
> fix(lane_change): prevent node from dying for trimmed shifted path

- planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/utils.hpp
- planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
- planning/behavior_path_planner/src/utils/lane_change/utils.cpp
Due to `passParkedObject` function returns false, debug visualization didn't publish any `Marker`s due to no information is registed to the `object_debug_`. This PR fixes this issue by updating the `object_debug_` information in the `passParkedObject` function. …
> fix(lane_change): add visualization for passParkedObject

- planning/behavior_path_planner/include/behavior_path_planner/utils/path_safety_checker/safety_check.hpp
fix calcMinimumLongitudinalLength args
> fix(behavior_path_planner): fix calcMinimumLongitudinalLength args

- planning/behavior_velocity_intersection_module/config/intersection.param.yaml
- planning/behavior_velocity_intersection_module/src/debug.cpp
- planning/behavior_velocity_intersection_module/src/manager.cpp
- planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
- planning/behavior_velocity_intersection_module/src/scene_intersection.hpp
- planning/behavior_velocity_intersection_module/src/util.cpp
- planning/behavior_velocity_intersection_module/src/util.hpp
- planning/behavior_velocity_intersection_module/src/util_type.hpp
If the NPC's distance to its stopline before the intersection is larger than the braking distance, it is ignored in the collision detection when ego traffic light color is amber.
launcher PR: https://github.com/autowarefoundation/autoware_launch/pull/635
In the video a NPC approaches from the same position with the same velocity on green/amber traffic light. When ego traffic light color is amber collision detection is not active until the vehicle approaches the stop line.
https://github.com/autowarefoundation/autoware.universe/assets/28677420/8d48833b-70f3-44fe-a449-2943094ec819
evaluator: https://evaluation.tier4.jp/evaluation/reports/9afba9e8-1bed-560f-8a0b-0dbca794fb59?project_id=prd_jt
none.
none. …
> feat(intersection): ignore decelerating vehicle on amber traffic light

- planning/behavior_path_planner/include/behavior_path_planner/utils/path_safety_checker/path_safety_checker_parameters.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/path_safety_checker/safety_check.hpp
- planning/behavior_path_planner/src/marker_utils/utils.cpp
- planning/behavior_path_planner/src/utils/path_safety_checker/safety_check.cpp
- planning/behavior_path_planner/test/test_safety_check.cpp
fix chattering for stopped objects
the cause is that object direction and extending direction is chattering when stopped.
after
https://github.com/autowarefoundation/autoware.universe/assets/39142679/a916dbf5-c475-44d7-bf84-5557796a943a
psim
none
none
> fix(lane_change): fix chattering for stopped objects

- planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
Add a margin for lane change stuck detection distance. Without this PR, the ego vehicle is not judged to be stuck when using a small max_acceleration.
run psim
Stuck detection in lane change is improved.
> fix(lane_change): add margin in stuck detection distance

- common/tier4_logging_level_configure_rviz_plugin/config/logger_config.yaml
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/base_class.hpp
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/normal.hpp
- planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
Add debug log in lane change
None 
Run psim
None
None
None
> refactor(lane_change): add debug log

- planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
- planning/behavior_path_planner/src/utils/path_safety_checker/safety_check.cpp
Do not use reference values of polygon outer.
> fix(lane_change): do not use reference values of polygon outer

- planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
currently target_objects includes objects out of target lanes, this causes chattering of stopping margin, so filter them out
https://github.com/autowarefoundation/autoware.universe/assets/39142679/07b7d067-1d3c-47e9-b953-b263625aac30
https://github.com/autowarefoundation/autoware.universe/assets/39142679/e700e5fc-c65d-41d4-a1fe-98e32ee1e468
psim
evaluator_description: fix/lc_outof_lane_obj
2023/10/16 https://evaluation.tier4.jp/evaluation/reports/45177ccb-ee3a-50ae-b235-e0116a93b666/?project_id=prd_jt
fails are not related to this PR and will be fixed in https://github.com/autowarefoundation/autoware.universe/pull/5325
none
none
The PR author …
> fix(lane_change): filter out objects out of lane to fix stopping margin chattering

- sensing/imu_corrector/README.md
- sensing/imu_corrector/config/gyro_bias_estimator.param.yaml
- sensing/imu_corrector/launch/gyro_bias_estimator.launch.xml
- sensing/imu_corrector/src/gyro_bias_estimation_module.cpp
- sensing/imu_corrector/src/gyro_bias_estimation_module.hpp
- sensing/imu_corrector/src/gyro_bias_estimator.cpp
- sensing/imu_corrector/src/gyro_bias_estimator.hpp
- sensing/imu_corrector/test/test_gyro_bias_estimation_module.cpp
Before : Use `twist` to determine whether ego-vehicle is stopping, and calculate imu bias by comparing it to 0 while it is stopping.
After: Use `ndt pose` to determine whether ego-vehicle is curving, and calculate imu bias by comparing it to ndt pose while it is not curving.
* https://github.com/autowarefoundation/sample_sensor_kit_launch/pull/78
* https://github.com/tier4/aip_launcher/pull/180
* https://github.com/RobotecAI/awsim_sensor_kit_launch/pull/10
It has been confirmed that it works as expected with sample rosbag.
The red dashed line indicates the range extended from the orange line, which is the calibration value, by gyro_bias_threshold.
If it is within the red dashed line range, the IMU bias is considered normal.
For TIER IV's internal rosbags, the result of the IMU bias …
> feat(imu_corrector): changed GyroBiasEstimator to use ndt pose instead of twist

- launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_radar_fusion_based_detection.launch.xml
- perception/tracking_object_merger/include/tracking_object_merger/utils/utils.hpp
After evaluation in xx1 project in TIER IV, https://github.com/autowarefoundation/autoware.universe/pull/5269 has several unintended error.
This PR fixes apparent error fixed in [xx1 project](https://github.com/tier4/autoware.universe/pull/952)
Tested in tier4/pilot.auto.xx1 project. : https://github.com/tier4/autoware.universe/pull/952 …
> fix(tracking_object_merger): fix unintended error in radar tracking merger

- planning/behavior_path_planner/src/utils/drivable_area_expansion/drivable_area_expansion.cpp
This PR fixes bugs with the `max_arc_length` and `extra_arc_length` parameters.
- Path points are now initially cropped using the `max_arc_length` parameter.
-  `max_arc_length = 0.0` is correctly handled as meaning "no limit on the path arc length".
- arc length is correctly calculated when moving up the bound to apply the expansion distance to extra bound points following the `extra_arc_length` parameter.
Psim
Parameters now work correctly. …
> fix(drivable_area_expansion): fix max_arc_length parameter and extra_arc_length parameters

- planning/obstacle_avoidance_planner/src/debug_marker.cpp
- planning/obstacle_avoidance_planner/src/mpt_optimizer.cpp
This PR is to add the missing functionality of fixing lateral calculations in `obstacle_avoidance_planner` since refactoring done in https://github.com/autowarefoundation/autoware.universe/pull/2796 . 
closes #4190 
Before PR:
After PR:
Original PR : https://github.com/autowarefoundation/autoware.universe/pull/2878
Refactoring PR : https://github.com/autowarefoundation/autoware.universe/pull/2796
[pull …
> fix(obstacle_avoidance_planner): fix lateral calculations

- planning/behavior_velocity_intersection_module/src/util.cpp
If detection lanelets have a loop, topological sort runs into infinite loops. I fixed this by checking visited nodes.
with a map that causes loop detection lanelets due to improper RightOfWay setting.
none.
none.
> fix(intersection): fix infinite loop in tsort

- perception/detected_object_validation/include/detected_object_filter/object_lanelet_filter.hpp
- perception/detected_object_validation/src/object_lanelet_filter.cpp
Current object lanelet filter only considers the "road" lanelet. 
This PR takes into account the "shoulder" lanelet where objects are filtered.
This idea is based on the current shoulder lane parking design, which considers objects in or accross the shoulder lanes.
This PR can address the [Internal ticket](https://tier4.atlassian.net/browse/RT1-4092).
The objects in or across the shoulder lanelet **are filtered** after object_lanelet_filter node.
The unknown objects in the picture shows `/perception/object_recognition/detection/objects`
[Filtered in or across the shoulder lanelet movie](https://github.com/autowarefoundation/autoware.universe/assets/42209144/2e6adfc6-270f-44fe-8bc3-622da0db1a30)
The objects in or across the shoulder lanelet **are not filtered** after object_lanelet_filter …
> fix(detected_object_validation): consider shoulder lanelet in object lanelet filter

- sensing/gnss_poser/src/gnss_poser_core.cpp
[tf_gnss_antenna2base_link_msg_ptr](https://github.com/autowarefoundation/autoware.universe/blob/f945c019d4fbd00be2cec7a2f914e06efa9e8251/sensing/gnss_poser/src/gnss_poser_core.cpp#L116-L124) names implies "gnss_link -> base_link" transform and is used that way, but getStaticTransform(gnss_frame_, base_frame_, ... returns the transform "base_link -> gnss_link". The transform direction is not true. 
[Here](https://github.com/autowarefoundation/autoware.universe/blob/4864b1901c67097bf4b692365af7d8766b42ef43/sensing/gnss_poser/src/gnss_poser_core.cpp#L117) the function to make transforms is called. And [this ](https://github.com/autowarefoundation/autoware.universe/blob/4864b1901c67097bf4b692365af7d8766b42ef43/sensing/gnss_poser/src/gnss_poser_core.cpp#L331)line contains transform from …
> fix(gnss_poser): fix_transform_direction_problem

- control/pid_longitudinal_controller/src/pid_longitudinal_controller.cpp
Currently, in the pid_longitudinal_controller, the condition to transit to STOPPED is that the absolute values of the velocity and acceleration are small enough.
However, on the steep ascending slope, if the ego tries to stop by the state transiting to STOPPED but the ego moves backward due to the slope, the state will never transit to STOPPED since the absolute value of the velocity is not small enough.
To deal with this case, the condition to transit to STOPPED is changed as follows
- The absolute values of the velocity and acceleration are small enough, which is the original condition.
- **Or the sign of the velocity is opposite to the expected.**
- e.g. When the shift is forward but the velocity is negative, the condition to transit to STOPPED is met.
unit test
psim
can stop on the …
> feat(pid_longitudinal_controller): transit to STOPPED even if the sign of the ego velocity goes opposite

- launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.py
- planning/behavior_path_planner/include/behavior_path_planner/utils/drivable_area_expansion/drivable_area_expansion.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/drivable_area_expansion/map_utils.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/drivable_area_expansion/types.hpp
- planning/behavior_path_planner/src/utils/drivable_area_expansion/drivable_area_expansion.cpp
- planning/behavior_path_planner/src/utils/drivable_area_expansion/map_utils.cpp
This PR improves the performance of the two heaviest function of the dynamic drivable area expansion feature.
Psim
The runtime of the `behavior_path_planner` should be greatly reduced when using the dynamic drivable area expansion.
> perf(drivable area expansion): use faster lateral offset and nearest line calculations

- localization/ndt_scan_matcher/include/ndt_scan_matcher/ndt_scan_matcher_core.hpp
- localization/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp
Some minor refactoring on ndt_scan_matcher.
* function name changed from `align_using_monte_carlo` to `align_pose`
* Removed an argument `ndt_ptr` from `align_using_monte_carlo`. (This is because `ndt_ptr_` is a member variable and can be used without passing it as an argument)
* Added message if `ndt_ptr_->getInputSource() == nullptr`, `ndt_ptr_->getInputTarget() == nullptr`
* Changed the timing to get the mutex lock
It has been confirmed that this can be done with logging_simulator. …
> refactor(ndt_scan_matcher): rename `align_using_monte_carlo` , etc.

- localization/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp
Corrected the argument given to `validate_num_iteration`.
See https://github.com/tier4/ndt_omp/pull/23
It has been confirmed that this can be done with logging_simulator.
Also, I degraded the accuracy of the localization and set NDT to run at its maximum iterations, then ran Autoware.
The following display was successfully obtained.
> 1697696962.0746102 [ndt_scan_matcher-32] [33m[WARN 1697696962.055757336] [localization.pose_estimator.ndt_scan_matcher]: The number of iterations has reached its upper limit. The number of iterations: 30, Limit: 30 (validate_num_iteration() at /home/shintarosakoda/autoware/src/universe/autoware.universe/localization/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp:655)[0m
The detection of when iteration_num reaches its maximum value will work correctly.
The …
> fix(ndt_scan_matcher): fix `validate_num_iteration`

- planning/route_handler/src/route_handler.cpp
closes https://github.com/autowarefoundation/autoware.universe/issues/5357
_What this PR changes?_
- route_handler filters start_lanelet's to eliminate improper oriented ones wrt start_checkpoint
https://github.com/autowarefoundation/autoware.universe/assets/48479081/8bdeacb0-9947-47e2-83b4-29fc4050c571
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contribut …
> fix(route_handler): filter out start lanelets wrt start checkpoint orientation

- planning/behavior_velocity_intersection_module/config/intersection.param.yaml
- planning/behavior_velocity_intersection_module/src/manager.cpp
- planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
- planning/behavior_velocity_intersection_module/src/scene_intersection.hpp
- planning/behavior_velocity_intersection_module/src/util.cpp
- planning/behavior_velocity_intersection_module/src/util.hpp
use own parameter for max accel/jerk/delay_response_time in intersection module
launcher PR: https://github.com/autowarefoundation/autoware_launch/pull/650
Psim works
none.
> feat(intersection): use own max acc/jerk param

- planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
add guard for
```
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140508136683072) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140508136683072) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140508136683072, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007fca9c042476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007fca9c0287f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007fca9c4a2b9e in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007fca9c4ae20c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007fca9c4ae277 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007fca9c4ae4d8 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#9 …
```
> fix(start_planner): fix invalid lane id access

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp
- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
rebuild goal planner state transition related to 
https://github.com/autowarefoundation/autoware.universe/pull/4518
https://github.com/autowarefoundation/autoware.universe/pull/4518
psim
https://evaluation.tier4.jp/evaluation/reports/a902cb9b-8fb4-5109-937b-b18912cda2e7?project_id=prd_jt
evaluator_description: refactor/goal_planner_state
2023/10/23 https://evaluation.tier4.jp/evaluation/reports/3975f175-2957-554e-a021-d617dfa35158/?project_id=prd_jt
https://evaluation.tier4.jp/evaluation/reports/tables/new?catalog_id=cb497016-2e2f-4ce0-9ac8-68d77a27a55d&filter=&job_id=fee28b13-55cd-5606-882e-b5c476037840&project_id=prd_jt&table_config=date%2Chide&target_ids=8cdcf567-81a6-59db-81f7-f533153b3e57
none
none
The PR …
> refactor(goal_planner): rebuild state transition

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp
- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
This reverts commit 654fa8cd0dbf036cf693abbd137acae9936c327c in https://github.com/autowarefoundation/autoware.universe/pull/5202
transaction cannot lock in the following cases
- thread1: use transaction
- thread2: use just setter/getter
https://github.com/autowarefoundation/autoware.universe/pull/5202
psim
evaluator_description: fix/goal_planner_recursive_mutex
2023/10/23 https://evaluation.tier4.jp/evaluation/reports/fee28b13-55cd-5606-882e-b5c476037840/?project_id=prd_jt
none
none
[contribution …
> fix(goal_planner): use recursive mutex instead of transaction

- planning/behavior_velocity_crosswalk_module/src/manager.cpp
- planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
- planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp
When the map has regulatory element and non-regulatory element crosswalks, the duplicated crosswalks are launched as not expected.
**before**
**after**
psim
scenario test: https://evaluation.tier4.jp/evaluation/reports/d08050b3-5bec-5316-bbcf-ed84daf562e2?project_id=prd_jt
nothing …
> fix(crosswalk): fix duplicated crosswalk launch

- sensing/imu_corrector/launch/gyro_bias_estimator.launch.xml
- sensing/imu_corrector/src/gyro_bias_estimator.cpp
- sensing/imu_corrector/src/gyro_bias_estimator.hpp
Change the input topic used by GyroBiasEstimator from `/localization/pose_estimator/pose_with_covariance` to `/localization/kinematic_state`.
This change comes from the idea that `/localization/kinematic_state` is a more formal pose output from the localization module.
It should be noted that EKF is dependent on the IMU, so the EKF itself will be slightly affected when the IMU bias is not fully compensated.
However, if NDT is used as the pose_estimator, experiments have shown that the effect is small.
* https://github.com/autowarefoundation/sample_sensor_kit_launch/pull/79
* https://github.com/tier4/aip_launcher/pull/183
* https://github.com/RobotecAI/awsim_sensor_kit_launch/pull/11
In sample rosbag
|Before(ndt_pose)|After(ekf_odom)|
|:---------------------:|:--------------------:| …
> feat(imu_corrector): changed input topic of GyroBiasEstimator from ndt_pose to ekf_odom

- system/default_ad_api/src/operation_mode.cpp
- system/default_ad_api/src/operation_mode.hpp
- system/topic_state_monitor/src/topic_state_monitor_core.cpp
We frequently receive reports that, for unknown reasons, it is not possible to switch to Auto mode.
I added explicit messages stating "Cannot switch to AUTO" and "The frequency of the topic has dropped" on the terminal.
run psim
None
> refactor(topic_state_monitor): add state log message

- planning/behavior_velocity_intersection_module/src/util.cpp
- planning/behavior_velocity_intersection_module/src/util.hpp
The argument order of the function in the following PR was wrong.
https://github.com/autowarefoundation/autoware.universe/pull/5370
unit test
bug fix
> fix(intersection): wrong argument order

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp
- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
This reverts commit 3d2a7f6038627ca52a4f0c2af6f5a8d56bc6962b.
dismiss degradation
https://github.com/autowarefoundation/autoware.universe/pull/5371#issuecomment-1776459751
> fix(goal_planner): revert "refactor(goal_planner): rebuild state transition (#5371)"

- planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
- planning/behavior_path_planner/src/utils/utils.cpp
fix terminal stop distance
(extend previous current lanes)
tier4 internal 
- https://tier4.atlassian.net/browse/RT0-29586
- https://star4.slack.com/archives/C03QW0GU6P7/p1698121601048419?thread_ts=1697547628.391719&cid=C03QW0GU6P7
2023/10/24 https://evaluation.tier4.jp/evaluation/reports/fedf22ba-e9e5-5eb3-86ae-6a607bc468d2/?project_id=prd_jt
none
none …
> fix(lane_change): fix terminal stop distance

- common/motion_utils/include/motion_utils/vehicle/vehicle_state_checker.hpp
- common/motion_utils/src/vehicle/vehicle_state_checker.cpp
Fix following build error
```
/opt/ros/humble/include/rclcpp/rclcpp/any_subscription_callback.hpp: In instantiation of ‘rclcpp::AnySubscriptionCallback<MessageT, AllocatorT> rclcpp::AnySubscriptionCallback<MessageT, AllocatorT>::set(CallbackT) [with CallbackT = std::_Bind<void (motion_utils::VehicleStopChecker::*(motion_utils::VehicleStopChecker*, std::_Placeholder<1>))(std::shared_ptr<nav_msgs::msg::Odometry_<std::allocator<void> > >)>; MessageT = nav_msgs::msg::Odometry_<std::allocator<void> >; AllocatorT = std::allocator<void>]’:
/opt/ros/humble/include/rclcpp/rclcpp/subscription_factory.hpp:94:32:   required from ‘rclcpp::SubscriptionFactory rclcpp::create_subscription_factory(CallbackT&&, const rclcpp::SubscriptionOptionsWithAllocator<AllocatorT>&, typename …
```
> fix(motion_utils): fix build error

- planning/behavior_path_planner/config/avoidance/avoidance.param.yaml
- planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/avoidance_module_data.hpp
- planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
- planning/behavior_path_planner/src/scene_module/avoidance/manager.cpp
Added a parameter of use_conservative_buffer_longitudinal.
- When set to true,
- the base_link2front is added to the longitudinal buffer before avoidance to be comparatively conservative against the distance to the object.
- When set to false,
- the base_link2front is **NOT** added to the longitudinal buffer before avoidance to be comparatively aggressive against the distance to the object.
psim
unit test
No behavior change by default …
> feat(avoidance): add use_conservative_buffer_longitudinal

- planning/behavior_path_planner/src/utils/utils.cpp
fix 
```
#0  0x00007f65503de8b4 in ?? () from /opt/ros/humble/lib/x86_64-linux-gnu/liblanelet2_routing.so.1
[Current thread is 1 (Thread 0x7f65307f8640 (LWP 2786369))]
(gdb) bt
#0  0x00007f65503de8b4 in ?? () from /opt/ros/humble/lib/x86_64-linux-gnu/liblanelet2_routing.so.1
#1  0x00007f65503fec0c in ?? () from /opt/ros/humble/lib/x86_64-linux-gnu/liblanelet2_routing.so.1
#2  0x00007f65503fef50 in lanelet::routing::RoutingGraph::previous(lanelet::ConstLanelet const&, bool) const () from /opt/ros/humble/lib/x86_64-linux-gnu/liblanelet2_routing.so.1
#3  0x00007f6550606547 in route_handler::RouteHandler::getPreviousLanelets(lanelet::ConstLanelet const&) const () from /home/kosuke55/pilot-auto/install/route_handler/lib/libroute_handler.so
#4  0x00007f652cb4b548 in …
```
> fix(behavior_path_planner): add guard to extend lane

- map/map_loader/src/lanelet2_map_loader/lanelet2_map_visualization_node.cpp
Show intersection area polygon.
related PR: 
- https://github.com/autowarefoundation/autoware_common/pull/211
- https://github.com/autowarefoundation/autoware_launch/pull/655
Psim.
Nothing.
> feat(map_loader): show intersection areas

- planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
No need to check if it's a private area or not for YieldStuckStop.
psim
scenario test:
https://evaluation.tier4.jp/evaluation/reports/b2f67d83-d5cd-51bf-88f9-4b14dcf4f900?project_id=prd_jt
https://evaluation.tier4.jp/evaluation/reports/41d24c0b-6ff6-5962-a723-a3f418ccaf1d?project_id=prd_jt
nothing
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pu …
> fix(intersection): yield stuck stop

- perception/radar_tracks_msgs_converter/src/radar_tracks_msgs_converter_node/radar_tracks_msgs_converter_node.cpp
Add null check for `transform_` in `radar_tracks_msgs_converter_node.cpp`. 
This prevents node crashes when the radar transformation is unavailable.
Tested with logging_simulator.launch
No effects.
> feat(radar_tracks_msgs_converter): add an error message and prevent the node from crashing.

- planning/behavior_path_planner/include/behavior_path_planner/utils/utils.hpp
- planning/behavior_path_planner/src/utils/utils.cpp
fix infinity extension in loop lanes like
this bug is caused by https://github.com/autowarefoundation/autoware.universe/pull/5392
If there is no first point of path point behind current_lanes, it will loop forever.
This PR only extends if they exist in the same sequence. Furthermore, the extension is restricted to only within the root_lanes.
https://github.com/autowarefoundation/autoware.universe/pull/5392
psim
the failed scenario in local
evaluator_description: fix/getCurrentLanesFromPath
2023/10/26 https://evaluation.tier4.jp/evaluation/reports/bb494913-907e-5aa9-a638-d11a4c087f32/?project_id=prd_jt
https://evaluation.tier4.jp/evaluation/reports/61f7793a-366d-5589-80e4-c817ed75c233/?project_id=prd_jt
The PR …
> fix(behavior_path_planner): fix lane extension in getCurrentLanesFromPath

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp
- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
move some proccess to  UpdateData in gola planner
psim
https://evaluation.tier4.jp/evaluation/reports/ce136103-6ec5-5908-b778-23184480a1c4?project_id=prd_jt
none
none
> refactor(goal_planner): use updateData

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/goal_planner/goal_searcher.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/goal_planner/goal_searcher_base.hpp
- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
- planning/behavior_path_planner/src/utils/goal_planner/goal_searcher.cpp
currently the stop pose when path is not found is caculated from goal search start pose.
this include invalid goal pose like in no_parking_lane and stop too far.
In this PR, calculate stop pose from actual goal candidates which do not include no_parking_lane goal.
before
after
this may solve degradation of https://github.com/autowarefoundation/autoware.universe/pull/5371#issuecomment-1776459751
psim
evaluator_description: feat/goal_planner_stop_pose
2023/10/25 https://evaluation.tier4.jp/evaluation/reports/8bfda284-da50-5c03-ac67-a2f834d6c731/?project_id=prd_jt
evaluator_description: feat/goal_planner_stop_pose
2023/10/26 https://evaluation.tier4.jp/evaluation/reports/04de2c84-3b7f-5299-b0b1-9eb0d98f6721/?project_id=prd_jt
none
none …
> feat(goal_planner): calculate stop pose from closest goal candidate

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/normal.hpp
- planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
Before this change, objects out of target lane may be included depending on the parameters.
So, lane change planner checks parking objects out of target lane, then it may not plan lane change.
In this change, I fix the problem.
[TIER IV INTERNAL TEST](https://evaluation.tier4.jp/evaluation/reports/d763d598-ec96-5092-910b-e41eab1e31df?project_id=prd_jt)
[pull request …
> fix(lane_change): filter objects for skip parking objects

- planning/behavior_path_planner/include/behavior_path_planner/utils/path_utils.hpp
- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
- planning/behavior_path_planner/src/utils/path_utils.cpp
`stop_pose_` is removed in manager every loop, so need to set every loop.
after
> fix(goal_planner): visualize stop wall

- perception/tracking_object_merger/CMakeLists.txt
- perception/tracking_object_merger/include/tracking_object_merger/data_association/data_association.hpp
Remove use of `nlohmann_json`, it's no longer used and it being in `CMakeLists.txt` is causing the Debian build fail (see https://github.com/autowarefoundation/autoware-deb-packages/actions/runs/6639929281/job/18039381566?pr=41)
> build(tracking_object_merger): remove no longer needed nlohmann_json dependency

- system/system_monitor/include/system_monitor/process_monitor/process_monitor.hpp
- system/system_monitor/src/process_monitor/process_monitor.cpp
- Background
- #4553 modified process_monitor to output full command string instead of just a command name. However, it doesn't work with some environment and #5191 fixed the issue. However, the current process_monitor still have some issues.
- Issue
- a. Current process_monitor only outputs a command path (details like parameters are not displayed)
- b. Displayed command name becomes blank when the process is kernel process
- How this PR fixes the issues
- For issue a, the cause is that `NUL` (`0x00`) is used as deliminator in `/proc/{PID}/cmdline` instead of `SPACE` (`0x20`). Code in #4553 reads cmdline into string, but when `NUL` appears, it finishes reading and only the first part (command path) is stored. This PR reads cmdline into buffer, then replace `NUL` to `SPACE` and casts it …
> fix(system_monitor): output command line

- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
updateData()  is always called even if before execution is requested.
this starts path generation too. this process in not necessary and may cause bug because too eary.
and fix the long path
psim.
evaluator_description: fix/pull_over_path_candidate
2023/10/28 https://evaluation.tier4.jp/evaluation/reports/424fc18f-a191-5685-b915-a375c654f96e/?project_id=prd_jt …
> fix(goal_planner): do not generate path candidates before execution

- planning/behavior_path_planner/config/lane_change/lane_change.param.yaml
- planning/behavior_path_planner/include/behavior_path_planner/parameters.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/utils.hpp
- planning/behavior_path_planner/src/behavior_path_planner_node.cpp
- planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp
- planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
- planning/behavior_path_planner/src/utils/lane_change/utils.cpp
- planning/behavior_path_planner/src/utils/utils.cpp
Separate backward buffer parameter for blocking object
Merge this PR first https://github.com/autowarefoundation/autoware_launch/pull/661
[TIER IV INTERNAL TEST](https://evaluation.tier4.jp/evaluation/reports?project_id=prd_jt)
`backward_length_buffer_for_blocking_object` is added.
Able to change backward length buffer for blocking object. …
> fix(lane_change): separate backward buffer for blocking object

- planning/behavior_path_planner/src/turn_signal_decider.cpp
fix turn signal endless loop
https://github.com/autowarefoundation/autoware.universe/issues/5440
https://evaluation.tier4.jp/evaluation/reports/c40eba8d-7d8e-5aa6-9c33-071b5b7841ac?project_id=prd_jt
1665/1667
> fix(behavior_path_planner): fix turn signal endless loop

- .cspell-partial.json
- planning/behavior_velocity_intersection_module/CMakeLists.txt
- planning/behavior_velocity_intersection_module/config/intersection.param.yaml
- planning/behavior_velocity_intersection_module/scripts/ttc.py
- planning/behavior_velocity_intersection_module/src/manager.cpp
- planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
- planning/behavior_velocity_intersection_module/src/scene_intersection.hpp
- planning/behavior_velocity_intersection_module/src/util.cpp
- planning/behavior_velocity_intersection_module/src/util.hpp
launcher PR: https://github.com/autowarefoundation/autoware_launch/pull/666
none.
none.
> chore(intersection): add debug plotter

- planning/behavior_path_planner/config/avoidance/avoidance.param.yaml
- planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/avoidance_module_data.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/utils.hpp
- planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
- planning/behavior_path_planner/src/scene_module/avoidance/manager.cpp
- planning/behavior_path_planner/src/utils/avoidance/utils.cpp
Please review following PR at first:
https://github.com/autowarefoundation/autoware_launch/pull/663
In this PR, avoidance module takes traffic light signal recognitino results into consideration so that it can make more natural path at intersection.
The module decides where the ego should return original lane or start avoidance maneuver from traffic light signal.
|    |  Traffic light color: GREEN  | Traffic light color: RED |
| ---- | ---- | ---- |
| Object is FARTHER than traffic light stop line. (current shift > 0)  | ![Screenshot from 2023-10-28 17-25-37](https://github.com/autowarefoundation/autoware.universe/assets/44889564/b39bf6e4-7d66-478e-b6b6-ed7e77062131) return point is sometimes behind the traffic light stop line. | ![Screenshot from 2023-10-28 …
> feat(avoidance): use traffic light signal info

- control/pid_longitudinal_controller/src/pid_longitudinal_controller.cpp
Not check the steering convergence when the vehicle is moving.
Fixed bug:
- When the vehicle was driving in manual mode, the longitudinal controller was stuck in "STOPPED" mode due to the `steering_convergence` check. Then, the vehicle got stopped when the Autoware was engaged, which was not expected.
Ideal behavior
- The vehicle should be in driving mode even if the steering is not converged in driving mode.
[TIERIV INTERNAL TICKETS](https://tier4.atlassian.net/browse/RT1-3959)
- Run psim
- Run lsim
None
None
Bug on engage is fixed. …
> fix(pid_longitudinal_control): not check steering convergence when moving

- simulator/simple_planning_simulator/include/simple_planning_simulator/simple_planning_simulator_core.hpp
Initialize simulator variables, otherwise for example `is_initialized_` is not initialized correctly causing unexpected behavior.
In my case, ego pose is published before initialization since `is_initialized_` is initialized with a broken value.
run psim
ego pose will not be published before initialization
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contri …
> fix(simple_planning_simulator): initialize variables

- planning/planning_validator/include/planning_validator/planning_validator.hpp
- planning/planning_validator/src/planning_validator.cpp
Setup diagnostic updater after all data is ready. Otherwise, the /diagnostic is published with ERROR state before it is ready.
Before
- diag is published with ERROR state before the required data is received
After
- diag is NOT published before the required data is received
None
Run psim
None
None
See Description
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main …
> fix(planning_validator): not publish diag before data is ready

- planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
Lane change module checks for preferred lane within `forward_lane_length` (for the sake of example, 300 m) from ego vehicle's current position. When preferred lane is found, lane change module will be activated. Then lane change path is computed and if the actual lane changeable lanes is far away, no lane change path will be  generated.
<p align="center">
</p>
However, despite no valid path, `insertStopPose` for `stuck` detection will still be activated and the lane change stop wall appear, despite the actual lane change start point is still far away.
<p align="center">
</p>
When generate for lane change path validity, the lane change start poses are computed and saved in the `status_.lane_Change_path.lane_change_info`. In this PR, the lane change start pose is reuse in the …
> fix(lane_change): stop point activated too early

- vehicle/raw_vehicle_cmd_converter/src/csv_loader.cpp
This is a small bug-fix.
Related issue:
- https://github.com/autowarefoundation/autoware.universe/issues/5311
Related bug report: https://pastebin.com/rxvatCWh
This aims to resolve the first one.
> fix(raw_vehicle_cmd_converter): return false if table is empty

- .github/sync-files.yaml
Related issue: https://github.com/autowarefoundation/autoware/issues/3955
This PR renames the `stale` label into `type:stale` through the `sync-files` job.
This PR automates the creation of the following PR:
- https://github.com/autowarefoundation/autoware.universe/pull/5216/files
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/ …
> ci(sync-files): change stale label to type:stale

- .github/sync-files.yaml
Fixes the label name to match:
Old PR:
- https://github.com/autowarefoundation/autoware.universe/pull/5474
> ci(sync-files): change stale label to status:stale (#5474)

- .github/labeler.yaml
Modifies labels:
- `component:ci` -> `type:ci`
- `component:documentation` -> `type:documentation`
Related issue:
> ci(pr-labeler): update the labeler.yaml to mark ci and documentation as "type:"

- simulator/simple_planning_simulator/README.md
- simulator/simple_planning_simulator/include/simple_planning_simulator/vehicle_model/sim_model_delay_steer_acc.hpp
- simulator/simple_planning_simulator/include/simple_planning_simulator/vehicle_model/sim_model_delay_steer_acc_geared.hpp
- simulator/simple_planning_simulator/include/simple_planning_simulator/vehicle_model/sim_model_delay_steer_vel.hpp
- simulator/simple_planning_simulator/param/simple_planning_simulator_default.param.yaml
- simulator/simple_planning_simulator/src/simple_planning_simulator/simple_planning_simulator_core.cpp
- simulator/simple_planning_simulator/src/simple_planning_simulator/vehicle_model/sim_model_delay_steer_acc.cpp
- simulator/simple_planning_simulator/src/simple_planning_simulator/vehicle_model/sim_model_delay_steer_acc_geared.cpp
- simulator/simple_planning_simulator/src/simple_planning_simulator/vehicle_model/sim_model_delay_steer_vel.cpp
add steer dead band to simulate actual vehicle
before
after
psim
evaluator_description: feat/steer_dead_band_sim
2023/11/03 https://evaluation.tier4.jp/evaluation/reports/d0fde7a0-2138-52e5-be7e-e175d48b776f/?project_id=prd_jt
none
none
> feat(simple_planning_simulator): add steer dead band

- common/tier4_logging_level_configure_rviz_plugin/config/logger_config.yaml
- localization/ekf_localizer/include/ekf_localizer/ekf_localizer.hpp
- localization/ekf_localizer/src/ekf_localizer.cpp
- localization/gyro_odometer/include/gyro_odometer/gyro_odometer_core.hpp
- localization/gyro_odometer/src/gyro_odometer_core.cpp
- localization/localization_error_monitor/include/localization_error_monitor/node.hpp
- localization/localization_error_monitor/package.xml
- localization/localization_error_monitor/src/node.cpp
- localization/ndt_scan_matcher/include/ndt_scan_matcher/ndt_scan_matcher_core.hpp
- localization/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp
- localization/pose_initializer/package.xml
- localization/pose_initializer/src/pose_initializer/pose_initializer_core.cpp
- localization/pose_initializer/src/pose_initializer/pose_initializer_core.hpp
Enable logging_level_configure for localization.
Note that I only enable it for ndt_scan_matcher pipeline and not for YabLoc and other localization methods for now.
Related: https://github.com/autowarefoundation/autoware.universe/pull/5131
Confirmed that, through the RViz plugin, the logging level can be configured runtime.
Not applicable …
> feat(localization): enable logging_level_configure

- localization/ndt_scan_matcher/CMakeLists.txt
- localization/ndt_scan_matcher/package.xml
- localization/ndt_scan_matcher/src/ndt_scan_matcher_node.cpp
Use glog for ndt_scan_matcher.
Please see https://github.com/autowarefoundation/autoware.universe/pull/4714 for more info about glog.
We recently had an issue where ndt_scan_matcher fails in some situation but cannot reproduce, making it difficult for us to investigate. Thus I would like to introduce glog for ndt_scan_matcher, at least temporarily, to improve the traceability.
[INTERNAL LINK
](https://tier4.atlassian.net/browse/RT0-29699)
- Launched Autoware and confirmed that the Autoware works with sample rosbag (with logging_simulator)
- Intentionally put an error in ndt_scan_matcher that terminates the node, and make sure that the glog outputs the log as it is expected
- Confirmed that the test passes
- **Confirmed that the NDT is launched with multi-threaded executor**
None
None
None …
> feat(ndt_scan_matcher): use glog

- localization/ekf_localizer/config/ekf_localizer.param.yaml
- system/system_error_monitor/config/diagnostic_aggregator/localization.param.yaml
Although current emergency handling system for localization solely relies on `localization_accuracy`, the criteria may not be accurate enough given that the covariances of NDT, IMU, and wheel odometry are still under development (e.g. the covariance estimation of NDT is still ongoing, and currently we use a static value that is empirically derived). One alternative criteria that we can use (at least temporarily) is to monitor if the valid NDT results have been published recently. In current Autoware implementation, we can monitor this by checking `no_update_count` in `ekf_localizer`. That being said, **I want to make Autoware Universe ready for using the EKF output for emergency handling**. 
Here are the changes that I would like to propose:
- Add EKF diag monitoring in …
> feat(ekf_localizer, system_error_monitor): system_error_monitor handles ekf diags

- planning/behavior_path_planner/CMakeLists.txt
- planning/behavior_path_planner/include/behavior_path_planner/utils/traffic_light_utils.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/utils.hpp
- planning/behavior_path_planner/src/utils/avoidance/utils.cpp
- planning/behavior_path_planner/src/utils/traffic_light_utils.cpp
- planning/behavior_path_planner/src/utils/utils.cpp
Simple refactoring to separate traffic light utils from `utils.hpp` so and `avoidance/utils.hpp` so that the function can be reused by other modules.
Autoware compilation success and using psim to confirm that no issues.
> refactor(behavior_path_planner): traffic light utils

- system/system_error_monitor/include/system_error_monitor/system_error_monitor_core.hpp
- system/system_error_monitor/src/system_error_monitor_core.cpp
- Do not print ERROR log in NO-FAULT condition
[TIERIV INTERNAL LINK](https://tier4.atlassian.net/browse/RT1-3887)
Run psim
None
Error logs are not displayed in the initializing state.
> refactor(system_error_monitor): hide error log in no-fault condition

- planning/behavior_path_planner/src/utils/utils.cpp
This commit adds a new boolean parameter, `insert_zero_velocity`, to the `getCenterLinePath` function in the `utils.hpp` file. When set to `true`, this parameter will insert a zero velocity to each point in the path. In the `utils.cpp` file, this option is used to insert zero velocities to the reference path generated in the `createGoalAroundPath` function.
get the following the output with 
```
ros2 topic echo /planning/scenario_planning/lane_driving/behavior_planning/path_with_lane_id
``` …
> feat(behavior_path_planner): add option to insert zero velocity to the center line path

- common/motion_utils/include/motion_utils/trajectory/trajectory.hpp
> refactor(motion_utils): fix typo in calcLongitudinalOffsetPose return

- localization/ndt_scan_matcher/include/ndt_scan_matcher/map_update_module.hpp
- localization/ndt_scan_matcher/include/ndt_scan_matcher/ndt_scan_matcher_core.hpp
- localization/ndt_scan_matcher/src/map_update_module.cpp
- localization/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp
As a result of verification, the following error occurred within the timer_diagnostics function, causing the node to crash. 
Therefore, to make it thread-safe, we decided to remove the thread processing.
Furthermore, to ensure thread safety, I've made sure that functions other than callback_sensor_points do not access `state_ptr_`.
N/A
LSim works.
We plan to make significant improvements to the diagnostics of the ndt_scan_matcher in the near future.
https://github.com/autowarefoundation/autoware.universe/pull/5076
N/A
N/A …
> fix(ndt_scan_matcher): delete diagnostics thread

- planning/mission_planner/src/lanelet2_plugins/default_planner.cpp
- planning/mission_planner/src/lanelet2_plugins/utility_functions.cpp
- planning/mission_planner/src/lanelet2_plugins/utility_functions.hpp
solve https://github.com/autowarefoundation/autoware.universe/issues/4078
tier4 internal scenario test
evaluator_description: refactor/use_combineLaneletsShape
2023/11/09 https://evaluation.tier4.jp/evaluation/reports/49b87e58-38d4-5c0e-a471-cd072e2b1523/?project_id=prd_jt
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-reques …
> refactor(mission_planner): use combineLaneletsShape in lanelet2_extension

- planning/mission_planner/src/lanelet2_plugins/default_planner.cpp
- planning/mission_planner/src/lanelet2_plugins/utility_functions.cpp
- planning/mission_planner/src/lanelet2_plugins/utility_functions.hpp
revert (#5535)"
This reverts commit c4ca645cbbd0a7b919ba1c2cdf78742bb81b87b5.because of  degradation
only `combine_lanelets` can combine neighbor lanes
> fix(mission_planner): revert "refactor(mission_planner): use combineLaneletsShape in lanele2_extension (#5535)"

- launch/tier4_planning_launch/launch/scenario_planning/lane_driving/motion_planning/motion_planning.launch.xml
With the recent change, the obstacle_cruise_planner does not work well due to unconnected pipeline of the velocity limit.
This PR fixed the issue.
psim
Just bug fix to make obstacle_cruise_planner work.
> fix(tier4_planning_launch): obstacle_cruise_planner pipeline is not connected

- perception/image_projection_based_fusion/CMakeLists.txt
add missing install for pointpainting cuda lib
> fix(image_projection_based_fusion): add missing install

- common/motion_utils/include/motion_utils/trajectory/trajectory.hpp
- common/motion_utils/test/src/trajectory/benchmark_calcLateralOffset.cpp
Make the `removeOverlapPoints` and `calcLateralOffset` functions faster, simply by calling `reserve` on the vector created in `removeOverlapPoints`.
Benchmark test (disabled by default) was added. It calls the function 10000 times on a trajectory with 1000 points.
- Without the fix: ~250ms.
- After the fix: ~80ms.
To test on you local machine:
```
./build/motion_utils/test_motion_utils --gtest_filter=trajectory_benchmark.\* --gtest_also_run_disabled_tests
```
None. …
> perf(motion_utils): faster removeOverlapPoints and calcLateralOffset functions

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/goal_planner/pull_over_planner_base.hpp
- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
- separate thread safe data from `status_`
- move pull over path related function in the module to the struct
psim
evaluator_description: refactor/goal_planner_thread_safe_data
2023/11/06 https://evaluation.tier4.jp/evaluation/reports/58df5f0b-2bee-5c37-a6f5-8820f16f3a6c/?project_id=prd_jt
https://evaluation.tier4.jp/evaluation/reports/2f0993e2-7c55-5a1f-93f4-1688a5adee04?project_id=prd_jt
https://evaluation.tier4.jp/evaluation/reports/5beeda59-eb94-5097-a30c-448b1588cdb8?project_id=prd_jt
1666/1667
none
none …
> refactor(goal_planner): separate thread safe data

- planning/behavior_path_planner/docs/behavior_path_planner_start_planner_design.md
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/start_planner/start_planner_module.hpp
- planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
The method "calcStartPoseCandidatesBackwardPath" has been renamed to "calcBackwardPathFromStartPose" to better reflect its purpose. The method now calculates the backward path by shifting the original start pose coordinates to align with the pull out lanes. The stop objects in the pull out lanes are filtered by velocity, using the new "filterStopObjectsInPullOutLanes" method. 
Additionally, the redundant "isOverlappedWithLane" method has been removed.
[contribution …
> refactor(start_planner): refactor backward path calculation in StartPlannerModule

- simulator/simple_planning_simulator/README.md
- simulator/simple_planning_simulator/include/simple_planning_simulator/vehicle_model/sim_model_delay_steer_acc.hpp
- simulator/simple_planning_simulator/include/simple_planning_simulator/vehicle_model/sim_model_delay_steer_acc_geared.hpp
- simulator/simple_planning_simulator/param/simple_planning_simulator_default.param.yaml
- simulator/simple_planning_simulator/src/simple_planning_simulator/simple_planning_simulator_core.cpp
- simulator/simple_planning_simulator/src/simple_planning_simulator/vehicle_model/sim_model_delay_steer_acc.cpp
- simulator/simple_planning_simulator/src/simple_planning_simulator/vehicle_model/sim_model_delay_steer_acc_geared.cpp
add acceleration and steer command scaling factor for debug
before
after (if set 0.8 for steer)
> feat(simple_planning_simulator): add acceleration and steer command scaling factor for debug

- launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml
- launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_radar_fusion_based_detection.launch.xml
- launch/tier4_perception_launch/launch/object_recognition/detection/detection.launch.xml
- launch/tier4_perception_launch/launch/object_recognition/detection/lidar_based_detection.launch.xml
- launch/tier4_perception_launch/launch/perception.launch.xml
- perception/detection_by_tracker/CMakeLists.txt
- perception/detection_by_tracker/config/detection_by_tracker.param.yaml
- perception/detection_by_tracker/include/detection_by_tracker/detection_by_tracker_core.hpp
- perception/detection_by_tracker/include/utils/utils.hpp
- perception/detection_by_tracker/launch/detection_by_tracker.launch.xml
- perception/detection_by_tracker/src/detection_by_tracker_core.cpp
- perception/detection_by_tracker/src/utils.cpp
This PR to add ignore option for other labels than UNKNOWN as current. This will allow user to flexibly select which class to be detected by tracker. 
This should be merged together with https://github.com/autowarefoundation/autoware_launch/pull/676 which keep setting as currently so the result should be unchange after PR merged.
[TIER IV INTERNAL LINK](https://star4.slack.com/archives/CRUE57C30/p1698906610256539?thread_ts=1698905091.001629&cid=CRUE57C30)
[contribution …
> fix(detection_by_tracker): add ignore option for each label

- planning/behavior_path_planner/src/marker_utils/utils.cpp
fix object polygon is not available for `passParkedObject` situation
> fix(lane_change): fix object debug marker not having point

- planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/avoidance_module_data.hpp
- planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
This PR fix a bug regarding the nearest search in the function `extendBackwardLength()`
This function requires two pose which are appropriately near to the current ego pose.
The first one is denoted by `orig_ego_idx` and shown in the figure as the blue arrow, the other one is dented by `prev_ego_idx` and shown in the figure as the red arrow.
The code so far failure to find `prev_ego_idx` appropriately and this PR fix this bug.
This PR is re-opened PR from https://github.com/autowarefoundation/autoware.universe/pull/5574 by the author's mistaken force push
psim tests and the tier4 internal test were performed in success. 
This PR enables to the system generates avoidance path appropriately on the curved reference paths  …
> fix(avoidance): fix a bug regarding the nearest search

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp
- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
refactoring plan flow
```
/*　
* state transitions and plan functions used in each state
*
* +--------------------------+
* | RUNNING                  |
* | plnaPullOverAsCandidate()|
* +------------+-------------+
*              | hasDecidedPath()
*  2           v
* +--------------------------+
* | WAITING_APPROVAL         |
* | planPullOverAsCandidate()|
* +------------+-------------+
*              | isActivated()
*  3           v
* +--------------------------+
* | RUNNING                  |
* | planPullOverAsOutput()   |
* +--------------------------+
*/
```
before this PR merge 
- https://github.com/autowarefoundation/autoware.universe/pull/5546
psim
evaluator_description: refactor/goal_planner_plan
2023/11/10 https://evaluation.tier4.jp/evaluation/reports/4030409f-6c74-543f-b949-30d8f …
> refactor(goal_planner): refactoring plan flow and add post process

- planning/external_velocity_limit_selector/src/external_velocity_limit_selector_node.cpp
- planning/motion_velocity_smoother/include/motion_velocity_smoother/motion_velocity_smoother_node.hpp
- planning/motion_velocity_smoother/src/motion_velocity_smoother_node.cpp
Currently, when the mrm_confortable_stop_operator requests the motion_velocity_smoother to stop, no virtual wall appears.
For better visualization, this PR adds the virtual wall by motion_velocity_smoother.
This is the case where the ego would leave the lane soon and MRM occurred by lane departure checker.
psim
Added a motion_velocity_smoother's virtual wall …
> feat(motion_velocity_smoother): add motion_velocity_smoother's virtual wall such as MRM

- planning/behavior_path_planner/src/utils/drivable_area_expansion/drivable_area_expansion.cpp
In order to provide a more stable output, the dynamic drivable area expansion reuses previous points of the path if they move by less than the `reuse_max_deviation` parameter. This can cause situations where the previous points are _behind_ the (non expanded) drivable area bounds. This could cause bugs in the expansion and yield wrong expanded drivable area.
This PR adds a check for this case to prevent bugs from occurring.
Evaluator (TIER IV INTERNAL LINK): 
- https://evaluation.tier4.jp/evaluation/reports/02817151-361b-592f-81f8-cdef75c7f5da?project_id=prd_jt
- https://evaluation.tier4.jp/evaluation/reports/a7918c0e-7ce8-5437-b469-bc64ce7cb597?project_id=prd_jt …
> fix(drivable_area_expansion): fix bug when reusing previous path points

- .github/sync-files.yaml
Part of:
Now that
- https://github.com/autowarefoundation/autoware/pull/3993
is merged, this code is not necessary anymore.
Continuation of:
- https://github.com/autowarefoundation/autoware.universe/pull/5474
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing …
> ci(sync-files): remove stale label pre-commands

- planning/behavior_velocity_run_out_module/package.xml
Added the maintainer of run_out module.
> chore(run_out): add maintainer

- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
need to extend after original goal for modifid goal.
fix 
https://evaluation.tier4.jp/evaluation/reports/8eeaa795-f1ca-5a26-81cc-492c7b4078a3/tests/753aa082-6f6e-528e-827d-12aabe6c616a/bcd56260-8454-57f7-b3a7-fd7f0a21ef4f/ea234da3-27e3-5bf9-9da1-042b56c60690?project_id=prd_jt
psim
evaluator_description: fix/goal_planner_current_lanes
2023/11/15 https://evaluation.tier4.jp/evaluation/reports/b61a0925-c518-5ba3-ba8d-954f7b9c9f83/?project_id=prd_jt
none
none …
> fix(goal_planner): fix extending current lanes

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp
- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
Simplify selectSafePath and do not update thread_data_ internally
before this PR merge 
- https://github.com/autowarefoundation/autoware.universe/pull/5546
- https://github.com/autowarefoundation/autoware.universe/pull/5554
psim
evaluator_description: refactor/goal_planner_select_path
2023/11/13 https://evaluation.tier4.jp/evaluation/reports/c7ce83db-31f7-592a-8619-8bfa9d9a9633/?project_id=prd_jt
evaluator_description: refactor/goal_planner_select_path
2023/11/14 https://evaluation.tier4.jp/evaluation/reports/8eeaa795-f1ca-5a26-81cc-492c7b4078a3/?project_id=prd_jt
evaluator_description: refactor/goal_planner_select_path
2023/11/15 https://evaluation.tier4.jp/evaluation/reports/17dff02f-d1ab-5eb7-9f61-700243053332/?project_id=prd_jt
none
none …
> refactor(goal_planner): refactor select path

- control/lane_departure_checker/include/lane_departure_checker/lane_departure_checker.hpp
- control/lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker.cpp
Without the PR, the curbstones have to be the boundary of the route lanelet to make the lane_departure_checker work.
With the PR, any curbstones can be used by the lane_departure_checker.
To use this feature of lane_departure_checker considering the curbstones, `boundary_departure_checker` should be true and `boundary_types_to_detect` should include `curbstone`.
Most of the implementation of boundarys' search with RTree is from drivable area expansion in the behavior_path_planner.
psim
nothing by default …
> feat(lane_departure_checker): better cubstones's search

- planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
Keep **RUNNING** state while the ego is on the shift line.
https://github.com/autowarefoundation/autoware.universe/assets/44889564/e2dde195-ede1-4c8d-b399-2bdee7cb5ffe
https://github.com/autowarefoundation/autoware.universe/assets/44889564/879afc05-d6c2-4f6b-ad7f-5b31b4d2b186
Return original path more smoothly.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/c …
> fix(avoidance): fix avoidance exit condition

- launch/tier4_perception_launch/launch/perception.launch.xml
Set default parameter `use_radar_tracking_fusion` to true
By logging simulator.launch with `perception_mode:=camera_lidar_radar_fusion` option
- Confirmed that /perception/object_recognition/tracking/radar_object_tracker has been launched
- The topic names are connected as intended. …
> feat(radar_object_tracker): change to use use_radar_tracking_fusion as true

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/goal_planner/pull_over_planner_base.hpp
- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
[feat(goal_planner): keep margin against objects as possible](https://github.com/autowarefoundation/autoware.universe/commit/e73d68329b6c940c7c7b3873dfb25e52f7e73ac8)
before
https://github.com/autowarefoundation/autoware.universe/assets/39142679/ef539b10-3b4a-4d78-8fef-42838bbf3370
after
https://github.com/autowarefoundation/autoware.universe/assets/39142679/a404d9dc-5ebb-46bd-9ba5-591d254eda47
tier4 internal ticket
https://tier4.atlassian.net/browse/RT1-4131
psim
evaluator_description: feat/keep_distance
2023/11/13 https://evaluation.tier4.jp/evaluation/reports/828fceb1-3f15-56bd-b598-2d0be9c3e9ea/?project_id=prd_jt
evaluator_description: feat/keep_distance
2023/11/16 https://evaluation.tier4.jp/evaluation/reports/3feacb18-f7d5-505c-bde4-4d50c98d36f0/?project_id=prd_jt
none
none
none
The …
> feat(goal_planner): keep margin against objects as possible

- planning/behavior_velocity_out_of_lane_module/src/overlapping_range.hpp
- planning/behavior_velocity_out_of_lane_module/src/scene_out_of_lane.cpp
- planning/behavior_velocity_out_of_lane_module/src/scene_out_of_lane.hpp
Improve the reuse of the previous decision in the `out_of_lane` module, avoiding bugs when the path changes suddenly.
Psim
Evaluator (TIER IV INTERNAL LINK): https://evaluation.tier4.jp/evaluation/reports/c2665660-1e2f-5aca-8a75-54820dd34155?project_id=prd_jt
> feat(out_of_lane): improve reuse of previous decision

- planning/behavior_path_planner/config/lane_change/lane_change.param.yaml
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/normal.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/lane_change_module_data.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/utils.hpp
- planning/behavior_path_planner/src/scene_module/lane_change/manager.cpp
- planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
Regulate lane change at the traffic light.
In this PR, by setting `regulate_on_traffic_light` to `true`, lane change module accepts path only when
1) lane changing start pose is after traffic light's stop line.
2) lane changing end pose is before traffic light's stop line.
https://github.com/autowarefoundation/autoware.universe/assets/93502286/6e122c5d-4cc6-4643-8058-7a2167451dde
Parameter is needed https://github.com/autowarefoundation/autoware_launch/pull/673
Evaluator's result https://evaluation.tier4.jp/evaluation/reports/9838be5d-03a2-5bca-94f1-f2170b0ea15a?project_id=prd_jt …
> fix(lane_change): regulate at the traffic light

- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
- planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
- planning/behavior_path_planner/src/utils/start_planner/util.cpp
remove inappropriate reference value
> fix(start_planner, goal_planner): remove inappropriate reference value

- system/component_state_monitor/config/topics.yaml
I would like to propose to monitor the output of `ndt_scan_matcher` which remains to be a critical source for accurate localization. Since most of the components assume that the localization is accurate, it is crucial to detect it's failure, and I would like to make the system as safe as possible with this PR.
[INTERNAL LINK 1](https://star4.slack.com/archives/CEL0DR2S2/p1700200987504589)
[INTERNAL LINK 2](https://star4.slack.com/archives/CEV8XMJBV/p1700204369731349)
Should be merged with https://github.com/autowarefoundation/autoware_launch/pull/692
Run logging simulator and confirmed that it does not raise any emergency (=False positives)
This will surely increase the number of emergency, but we expect the amount to be quite limited. On the contrary, we will now be able to catch the …
> feat(component_state_monitor): monitor pose_estimator output

- simulator/simple_planning_simulator/README.md
- simulator/simple_planning_simulator/src/simple_planning_simulator/simple_planning_simulator_core.cpp
There is a bug on the simple_planning simulator when enable_road_slope_simulation is true. Currently, the ego pitch angle is negative when the ego vehicle is on a downward slope and positive when on an upwards slope, which causes  trouble when computing the acceleration caused by the slope (the sign is negative when it should be positive and vice versa), causing a wrong simulation output. 
The original code: 
As you can see on the code picture, if the vehicle is on an upwards slope, the pitch sign is negative but the resulting acceleration will be positive (-9.81 * sin(negative) = positive value) which makes no sense for an upwards slope.
Examples of wrong behavior: 
The vehicle goes uphill, but its acceleration is high, it overshoots its goal …
> fix(simple_planning_simulator): fix ego sign pitch problem

- planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
Fixed the abort path calculation.
Before:
[Screencast from 2023年11月20日 14時13分31秒.webm](https://github.com/autowarefoundation/autoware.universe/assets/10190493/24f9777d-78a2-4f2d-9880-6b50e1e2773a)
After:
[Screencast from 2023年11月20日 14時10分27秒.webm](https://github.com/autowarefoundation/autoware.universe/assets/10190493/f55fb0a1-94d6-4331-aaca-1c8c9434b334) …
> fix(lane_change): fix abort path

- planning/behavior_path_planner/config/start_planner/start_planner.param.yaml
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/start_planner/start_planner_module.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/start_planner/start_planner_parameters.hpp
- planning/behavior_path_planner/src/scene_module/start_planner/manager.cpp
- planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
The [PR](https://github.com/autowarefoundation/autoware_launch/pull/693) should be merged first.
- Added a new parameter "verbose" to the StartPlannerParameters struct.
- Updated the start_planner.param.yaml file to include the "verbose" parameter.
- Added a new method receivedNewRoute() in the StartPlannerModule class to check if a new route has been received.
- Updated the updateData() method to use the receivedNewRoute() method instead of directly checking if a new route has been received.
- Renamed the method IsGoalBehindOfEgoInSameRouteSegment() to isGoalBehindOfEgoInSameRouteSegment().
- Added a new method logPullOutStatus() to log the pull out status.
- Updated the setDebugData() method to call logPullOutStatus() if the "verbose" parameter is true.
debug information can be shown in …
> refactor(start_planner): add verbose parameter for debug print

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp
- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
refactoring and add checkSafetyWithRSS
> refactor(goal_planner): add rss safety check function 

- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
prevent auto approval for unsafe path
psim
evaluator_description: feat/safe_auto_approval
2023/11/17 https://evaluation.tier4.jp/evaluation/reports/9fe8115c-a1db-5c02-8159-7c5b283a5c51/?project_id=prd_jt
none
none
none
> feat(goal_planner): prevent auto approval for unsafe path

- perception/image_projection_based_fusion/src/pointpainting_fusion/voxel_generator.cpp
`std::bitset<8>(*class_iter).to_string()` seems too slow.
https://stackoverflow.com/questions/28265621/c-program-using-bitset-running-pretty-slow
I have tested with a rosbag and a standalone launch file and modified source to output process time.
Before(no stress)
```
[pointpainting_fusion_node-3] preprocess: 34.269
[pointpainting_fusion_node-3] inference: 0.595
[pointpainting_fusion_node-3] postprocess: 27.488
[pointpainting_fusion_node-3] detect: 67.074
[pointpainting_fusion_node-3] preprocess: 30.979
[pointpainting_fusion_node-3] inference: 0.989
[pointpainting_fusion_node-3] postprocess: 27.701
[pointpainting_fusion_node-3] detect: 62.201
[pointpainting_fusion_node-3] preprocess: 29.456
[pointpainting_fusion_node-3] inference: 0.382
[pointpainting_fusion_node-3] postprocess: 27.757 …
```
> perf(image_projection_based_fusion): replace std::bitset

- planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
The undefined behavior caused by passing a temporary object as an argument to a function was resolved by storing the temporary object in a std::string variable, thereby ensuring an appropriate lifespan.
confrimed in psim and scenario evaluator.
> fix(start_planner): fix logPullOutStatus format specifier

- planning/behavior_velocity_out_of_lane_module/src/filter_predicted_objects.hpp
Preprocess predicted paths used by the `out_of_lane` module to prevent the "Same points are given" error message.
Psim
Less error messages.
> fix(out_of_lane): prevent "Same points are given" error message

- perception/lidar_centerpoint_tvm/package.xml
`tf2_sensor_msgs` needs to be declared as a dependency so that it'll be installed by `rosdep`
> build(lidar_centerpoint_tvm): add missing tf2_sensor_msgs depedency

- perception/image_projection_based_fusion/README.md
- perception/image_projection_based_fusion/package.xml
To solve https://github.com/autowarefoundation/autoware.universe/issues/5607
> chore(image_projection_based_fusion): fix document

- planning/surround_obstacle_checker/README.md
- planning/surround_obstacle_checker/schema/surround_obstacle_checker.schema.json
Implement the ROS Node configuration layout described in https://github.com/orgs/autowarefoundation/discussions/3371 for the `surround_obstacle_checker` package.
- Create the schema
Package successfully build locally.
`colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release --packages-up-to surround_obstacle_checker`
> refactor(surround_obstacle_checker): rework parameters

- control/operation_mode_transition_manager/README.md
- control/operation_mode_transition_manager/schema/operation_mode_transition_manager.schema.json
- control/operation_mode_transition_manager/src/state.cpp
Implement the ROS Node configuration layout described in https://github.com/orgs/autowarefoundation/discussions/3371 for the `operation_mode_transition_manager` package.
- Remove the default value from the source code in order to ensure all parameter values are passed from the parameter files.
- Create the schema
Package successfully build and launch locally.
`colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release --packages-up-to operation_mode_transition_manager` …
> refactor(operation_mode_transition_manager): rework parameters

- system/emergency_handler/README.md
- system/emergency_handler/schema/emergency_handler.schema.json
- system/emergency_handler/src/emergency_handler/emergency_handler_core.cpp
Refactor the ROS Node configuration layout for the detection_by_tracker package according to the [guideline](https://github.com/orgs/autowarefoundation/discussions/3433).
None.
1. Build `colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release --packages-up-to emergency_handler`
2. Launch `ros2 launch emergency_handler emergency_handler.launch.xml`
None.
1. Update README.md
2. Create a schema file
3. Modify all calls to `declare_parameter`
None. …
> refactor(emergency_handler): rework parameters

- control/obstacle_collision_checker/schema/obstacle_collision_checker.json
Implement the ROS Node configuration layout described in https://github.com/orgs/autowarefoundation/discussions/3371 for the obstacle_collision_checker..
> refactor(obstacle_collision_checker): rework parameters

- planning/planning_debug_tools/scripts/processing_time_checker.py
Display processing time in alphabetical order
run psim
None
> refactor(processing_time_checker): display in alphabetical order

- control/vehicle_cmd_gate/schema/vehicle_cmd_gate.json
Implement the ROS Node configuration layout described in https://github.com/orgs/autowarefoundation/discussions/3371 for the vehicle_cmd_gate package.
1. Remove the default value from the source code in order to ensure all parameter values are passed from the parameter files.
2. Create the schema …
> refactor(update_schema_vehicle_cmd_gate): rework parameters

- vehicle/external_cmd_converter/schema/external_cmd_converter.json
- vehicle/external_cmd_converter/src/node.cpp
Implement the ROS Node configuration layout described in https://github.com/orgs/autowarefoundation/discussions/3371 for the vehicle_external_cmd_converter
1. Remove the default value from the source code in order to ensure all parameter values are passed from the parameter files.
2.create schema …
> refactor(vehicle_external_cmd_converter): rework parameters

- perception/map_based_prediction/config/map_based_prediction.param.yaml
- perception/map_based_prediction/include/map_based_prediction/map_based_prediction_node.hpp
- perception/map_based_prediction/src/map_based_prediction_node.cpp
closes https://github.com/autowarefoundation/autoware.universe/issues/5668
:exclamation: **Must be merged after** https://github.com/autowarefoundation/autoware_launch/pull/703
NONE
> feat(map_based_prediction): consider only routable neighbours for lane change

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp
- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
keep has_decided_path if deciding once
Fixed a problem that after a path decision is made, if the path is not safe, the decision is aborted, resulting in no updateRTCStatus in manual mode and no update isExecutionReady
evaluator_description: feat/keep_dicide
2023/11/25 https://evaluation.tier4.jp/evaluation/reports/43420698-cb2f-53fc-8026-f0c23683027e/?project_id=prd_jt
[pull request …
> feat(goal_planner): keep decided path

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/dynamic_avoidance/dynamic_avoidance_module.hpp
- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp
The current dynamic avoidance module cannot deal with the oncoming object's path well where the object's path is forked from the ego's path.
This PR fixed the issue by calculating the distance between the object's path and ego's path.
**before**
The left side of the drivable area around the ego is modified unexpectedly.
**after**
psim
Better handling of the oncoming object's path in dynamic avoidance …
> feat(dyanmic_avoidance): deal with oncoming forked predicted path

- planning/behavior_velocity_run_out_module/README.md
- planning/behavior_velocity_run_out_module/config/run_out.param.yaml
- planning/behavior_velocity_run_out_module/src/dynamic_obstacle.cpp
- planning/behavior_velocity_run_out_module/src/manager.cpp
- planning/behavior_velocity_run_out_module/src/utils.hpp
I added option to use the object's velocity and covariance for the collision detection, and set this as default option.
Currently, objects in run out module have the min and max velocity, which is specified in the parameter.
For example, if the min velocity is 0km/h, and the max velocity is 5km/h, obstacle's polygon to calculate the time to collision is like bellow image.
In this PR, min and max velocity are calculated from the object's velocity and its covariance.
PR for the launch:
- https://github.com/autowarefoundation/autoware_launch/pull/704
PSim
[Scenario Test](https://evaluation.tier4.jp/evaluation/reports/afcc869c-c768-57ac-8b66-c72b3051e488?project_id=prd_jt) (TIER IV Internal)
https://github.com/autowarefoundation/autoware.universe/assets/11865769/1ecd02d9-6605-4200-a6f7-9db3a52 …
> feat(run_out): use the predicted object's velocity and covariance for the collision detection

- planning/behavior_path_planner/config/dynamic_avoidance/dynamic_avoidance.param.yaml
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/dynamic_avoidance/dynamic_avoidance_module.hpp
- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp
- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/manager.cpp
The front vehicle decision whether to avoid or not is wrong sometimes as shown in the following figure.
This PR fixed the issue by calculating how much ratio the object covers the ego's path.
**before**
The dynamic avoidance module tries to avoid the front vehicle unexpectedly.
**after**
psim
accurate front vehicle decision for dynamic avoidance …
> feat(dynamic_avoidance): accurate decision of front vehicle to avoid

- perception/shape_estimation/include/shape_estimation/corrector/truck_corrector.hpp
- perception/shape_estimation/lib/filter/truck_filter.cpp
Since previous truck filter size was too small, there was issue in roi_cluster_fusion can not detect large trucks.
I updated truck size by searching common truck size in japan.
It might need some discussion with some real data we obtained in odaiba.
Tested in lsim.
nothing.
> feat(shape_estimation): fix truck filter max size is too small problem

- planning/objects_of_interest_marker_interface/include/objects_of_interest_marker_interface/marker_utils.hpp
- planning/objects_of_interest_marker_interface/include/objects_of_interest_marker_interface/objects_of_interest_marker_interface.hpp
- planning/objects_of_interest_marker_interface/src/marker_utils.cpp
- planning/objects_of_interest_marker_interface/src/objects_of_interest_marker_interface.cpp
In this PR, I add the name text marker in `objects_of_interest_marker_interface`.
Planning simulator.
Visualizing name text marker.
> feat(objects_of_interest_marker_interface): add name text marker

- planning/behavior_path_planner/include/behavior_path_planner/planner_manager.hpp
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module.hpp
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/manager.hpp
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/dynamic_avoidance/dynamic_avoidance_module.hpp
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/dynamic_avoidance/manager.hpp
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/manager.hpp
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/interface.hpp
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_interface.hpp
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_manager_interface.hpp
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/side_shift/manager.hpp
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/side_shift/side_shift_module.hpp
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/start_planner/manager.hpp
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/start_planner/start_planner_module.hpp
- planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp
- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
- planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp
- planning/behavior_path_planner/src/scene_module/lane_change/manager.cpp
- planning/behavior_path_planner/src/scene_module/side_shift/side_shift_module.cpp
- planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
Before this change, `objects_of_interest_marker_interface` is applied only in lane change module.
In this PR, I apply it to scene modules in behavior path planner.
(However, setting objects of interest marker data is not enabled except lane change module in this PR)
[TIER IV INTERNAL TEST](https://evaluation.tier4.jp/evaluation/reports/d18397e0-e728-5d69-9f2a-f2fca4ee23fe?project_id=prd_jt)
Planning simulator
Objects of interest marker data will be published.
```
/planning/debug/objects_of_interest/**
``` …
> feat(behavior_path_planner): add objects of interest marker interface

- planning/behavior_path_planner/config/avoidance/avoidance.param.yaml
change parameter file to align with the default parameter defined in [autoware_launch](https://github.com/autowarefoundation/autoware_launch/blob/main/autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/avoidance/avoidance.param.yaml)
noticed the differece with this [comment](https://github.com/orgs/autowarefoundation/discussions/4005)
close this PR if this difference is intentional …
> refactor(avoidance): update avoidance parameters

- planning/behavior_velocity_planner_common/include/behavior_velocity_planner_common/scene_module_interface.hpp
- planning/behavior_velocity_planner_common/src/scene_module_interface.cpp
- planning/rtc_interface/include/rtc_interface/rtc_interface.hpp
- planning/rtc_interface/src/rtc_interface.cpp
Before this change, activation status is not updated in the cycle that safety status changed.
In this PR, it enables to sync activation status with current safety status.
[TIER IV INTERNAL TEST](https://evaluation.tier4.jp/evaluation/reports/e0fd3032-83de-57f5-bcbe-98acdfb88349?project_id=prd_jt)
Planning simulator.
Before:
After:
Activation status will be updated in the cycle that safety status updated.
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/m …
> fix(behavior_velocity_planner_common): sync activation when safety status is set

- common/tier4_autoware_utils/include/tier4_autoware_utils/geometry/geometry.hpp
- common/tier4_autoware_utils/src/geometry/geometry.cpp
- common/tier4_autoware_utils/test/src/geometry/test_geometry.cpp
Added a yaw argument in tier4_autoware_utils::calcOffsetPose, and its test.
Unit test
Nothing
> feat(tier4_autoware_utils): add yaw argument in calcOffsetPose

- perception/multi_object_tracker/CMakeLists.txt
- perception/object_merger/CMakeLists.txt
- perception/radar_object_tracker/CMakeLists.txt
- perception/tracking_object_merger/CMakeLists.txt
This PR moves the mussp libraries into their respective package libraries to avoid conflicts when packages are being installed as Debian packages.
See https://github.com/autowarefoundation/autoware-deb-packages/issues/51
Fixes #5705 
> fix: include mussp library into the packages to avoid duplicates

- common/tier4_autoware_utils/src/geometry/geometry.cpp
Since the z value is not interpolated by the intersection function, the driavble area's z position is wrong with dynamic_avoidance module.
psim
Nothing
> feat(tier4_autoware_utils): intersection result with z

- perception/map_based_prediction/CMakeLists.txt
- perception/map_based_prediction/package.xml
- perception/map_based_prediction/src/map_based_prediction_node.cpp
Use glog for map_based_prediction.
Please see https://github.com/autowarefoundation/autoware.universe/pull/4714 for more info about glog.
Error is caused intentionally with following code 
```
int * ptr = nullptr;
*ptr = 42;  // This will cause a crash due to null pointer dereference.
```
and output is following …
> feat(map_based_prediction): use glog

- vehicle/external_cmd_converter/launch/external_cmd_converter.launch.py
- vehicle/external_cmd_converter/launch/external_cmd_converter.launch.xml
The commit introduces a missing launch argument `timer_rate` to the external_cmd_converter. This parameter is used to set the update rate of the timer. The default value for this parameter is 10.0. The changes have been reflected in both .py and .xml launch files.
The error was ocurring when psim is launched as follows
confirmed error disappeared with this change
[pull request …
> fix(external_cmd_converter): define timer_rate parameter

- planning/behavior_path_planner/config/dynamic_avoidance/dynamic_avoidance.param.yaml
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/dynamic_avoidance/dynamic_avoidance_module.hpp
- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp
- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/manager.cpp
Added several min_object_vel parameters in dynamic_avoidance module
psim
Nothing
> feat(dynamic_avoidance): added several min_object_vel parameters

- planning/obstacle_cruise_planner/src/node.cpp
Bug fix of the function introduced in https://github.com/autowarefoundation/autoware.universe/pull/5036
Proper handling with backwad paths is achived
psim test performed 
Before:
After:
See Description
> fix(obstacle_cruise): proper handle with backward paths in the polygon expansion

- planning/behavior_path_planner/include/behavior_path_planner/data_manager.hpp
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/base_class.hpp
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/normal.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/traffic_light_utils.hpp
- planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp
- planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
- planning/behavior_path_planner/src/utils/traffic_light_utils.cpp
In the current implementation, at the traffic light, once lane change path is approved, it will not get cancel. This behavior is safe. However, although it is safe, there are possibility of ego vehicle being stuck in the middle of the lanes, and this behavior is improper.
Therefore, this PR change the lane change behavior at traffic light, by cancelling lane change if ego vehicle is performing lane change in stopped position nearby traffic light.
https://github.com/autowarefoundation/autoware.universe/assets/93502286/86e23021-76b9-48a8-acf4-f0fe7e828269
Test lane change at the traffic light.
Not applicable
Not applicable
Not applicable
The PR author …
> feat(lane_change): cancel lane change on red traffic light

- planning/behavior_path_planner/include/behavior_path_planner/behavior_path_planner_node.hpp
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/avoidance_by_lane_change.hpp
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/base_class.hpp
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/interface.hpp
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/normal.hpp
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_visitor.hpp
- planning/behavior_path_planner/src/behavior_path_planner_node.cpp
- planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp
- planning/behavior_path_planner/src/scene_module/scene_module_visitor.cpp
Lane change debug message is rarely used. This impacts the maintenance cost of the module. This PR aims to remove the debug message implementation. 
None
None
None
None
None
> feat(lane_change): remove debug message

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/dynamic_avoidance/dynamic_avoidance_module.hpp
- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp
Added a minor change to https://github.com/autowarefoundation/autoware.universe/pull/5678.
Without this PR, whether the object's path is forked from the ego's path or not is decided based on the distance between the object's path and ego's reference path.
During avoidance, since the ego's reference path is different from the actual ego's path, the decision is wrong sometimes.
This PR fixes it by using the ego's path instead of the ego's reference path.
psim
Nothing by default …
> fix(dynamic_avoidance): avoidance against forked object's path

- system/system_error_monitor/src/system_error_monitor_core.cpp
The loggingErrors() function is called through the publishHazardStatus function even when isDataReady is false. Therefore, there is a possibility of invalid access to null autoware_state_ and current_gate_mode_, causing the system_error_monitor to crash. This PR has been addressed and fixed.
https://github.com/autowarefoundation/autoware.universe/pull/5522
I launched the logging_simulator/rosbag and confirmed that the system_error_monitor no longer crashes.
none
none
As the description
[contribution …
> fix(system_error_monitor): avoid invalid access to nullptr

- planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
ignore occlusion in the intersection when AMBER in addition to RED
At [00:18] the traffic light color changes to AMBER and the intersection_occlusion wall is canceled.
https://github.com/autowarefoundation/autoware.universe/assets/28677420/4a1c2956-39b0-41a5-aba6-02db2917f2de
none
none.
none. …
> feat(intersection): ignore occlusion on amber color too

- planning/obstacle_cruise_planner/include/obstacle_cruise_planner/common_structs.hpp
- planning/obstacle_cruise_planner/include/obstacle_cruise_planner/node.hpp
- planning/obstacle_cruise_planner/include/obstacle_cruise_planner/planner_interface.hpp
- planning/obstacle_cruise_planner/include/obstacle_cruise_planner/polygon_utils.hpp
- planning/obstacle_cruise_planner/include/obstacle_cruise_planner/utils.hpp
- planning/obstacle_cruise_planner/src/node.cpp
- planning/obstacle_cruise_planner/src/planner_interface.cpp
- planning/obstacle_cruise_planner/src/polygon_utils.cpp
- planning/obstacle_cruise_planner/src/utils.cpp
BEFORE:
The current implementation calculate the stop point by the closest collision point.
This cause inappropriate behavior for looped trajectories.
AFTER:
The followings are achieved by this PR, 
- Proper handling of collision in extended trajectory is achieved (It is the main motivation of this PR).
- The stop point modification around the goal point is now working properly.
- `goal_extension_length` and `goal_extension_interval` may be no longer used and `safe_distance_margin` and `decimate_trajectory_step_length` are used instead.
This PR similar to https://github.com/autowarefoundation/autoware.universe/pull/5512, but this PR maintain more compatibility.
In other words, the function that included in the above PR  _This PR contains the similar feature to …
> feat(obstacle_cruise_planner): prior generation of collision distance

- perception/image_projection_based_fusion/docs/pointpainting-fusion.md
- perception/image_projection_based_fusion/launch/pointpainting_fusion.launch.xml
- perception/image_projection_based_fusion/src/pointpainting_fusion/node.cpp
the option to build tensorrt engine without inference
check with
` ros2 launch image_projection_based_fusion pointpainting_fusion.launch.xml input/rois0:=/perception/object_recognition/detection/rois0 input/camera_info0:=/sensing/camera/camera0/camera_info input/rois1:=/perception/object_recognition/detection/rois1 input/camera_info1:=/sensing/camera/camera1/camera_info input/rois2:=/perception/object_recognition/detection/rois2 input/camera_info2:=/sensing/camera/camera2/camera_info input/rois3:=/perception/object_recognition/detection/rois3 input/camera_info3:=/sensing/camera/camera3/camera_info input/rois4:=/perception/object_recognition/detection/rois4 input/camera_info4:=/sensing/camera/camera4/camera_info input/rois5:=/perception/object_recognition/detection/rois5 …
> feat(pointpainting): add build only option for tensort engine

- system/system_monitor/include/system_monitor/process_monitor/diag_task.hpp
Fix the process monitor outputting uninitialized diag level
1. Run `ros2 launch system_monitor system_monitor.launch.xml`
2. Run `ros2 topic echo /diagnostics | grep process_monitor -B1` in another terminal.
Before
```
- level: "\x90"
name: 'process_monitor: High-load Proc[0]'
--
- level: "\x03"
name: 'process_monitor: High-load Proc[1]'
--
- level: ç
name: 'process_monitor: High-load Proc[2]'
--
- level: ç
name: 'process_monitor: High-load Proc[3]'
--
- level: "\0"
name: 'process_monitor: High-load Proc[4]'
--
- level: '4'
name: 'process_monitor: High-mem Proc[0]'
--
- level: '4'
name: 'process_monitor: High-mem Proc[1]'
--
- level: "\x91"
name: 'process_monitor: High-mem Proc[2]'
--
- level: "\0"
name: 'process_monitor: High-mem Proc[3]'
--
- level: "\0"
name: 'process_monitor: High-mem …
```
> fix(system_monitor): fix uninitialized diag level of process monitor

- planning/obstacle_cruise_planner/config/obstacle_cruise_planner.param.yaml
- planning/obstacle_cruise_planner/include/obstacle_cruise_planner/node.hpp
- planning/obstacle_cruise_planner/src/node.cpp
remove unused params corresponds to https://github.com/autowarefoundation/autoware.universe/pull/5619
launch PR: https://github.com/autowarefoundation/autoware_launch/pull/716
psim tests was perfomed.
> chore(obstacle_cruise)!: remove unused params

- planning/.pages
- planning/README.md
Navigating the planning module documentation is quite challenging because the current document's hierarchical structure is based on the alphabetical order of folders, and on whether a docs folder exists in the module's folder.
The behavior path planner and behavior velocity planner are particularly affected, which might cause confusion for users about which document they should view first to understand the planning modules.
This PR aims to resolve this issue by manually specifying the order of the documents. …
> docs(planning): update documentation structure

- .github/workflows/spell-check-all.yaml
For continuous tracking of number of cspell errors, I added a schedule trigger to `spell-check-all` workflow.
This workflow is run correctly on this branch.
https://github.com/autowarefoundation/autoware.universe/actions/runs/7082321085
> chore(ci): enable cron trigger for spell-check-all

- localization/landmark_based_localizer/ar_tag_based_localizer/src/ar_tag_based_localizer.cpp
- localization/landmark_based_localizer/ar_tag_based_localizer/src/ar_tag_based_localizer.hpp
- localization/landmark_based_localizer/landmark_manager/include/landmark_manager/landmark_manager.hpp
- localization/landmark_based_localizer/landmark_manager/package.xml
- localization/landmark_based_localizer/landmark_manager/src/landmark_manager.cpp
Moved `calc_new_self_pose` from ar_tag_based_localizer to landmark_manger
This is introduced to share the same implementation as the LiDAR Marker Localizer.
* Before: mean_error[m]	0.614
* After : mean_error[m] 0.613 …
> refactor(landmark_manager): move `calc_new_self_pose` from ar_tag_based_localizer to landmark_manger

- launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml
- launch/tier4_perception_launch/launch/object_recognition/detection/detection.launch.xml
Refactor perception launcher
- Delete duplicated parameter
- Change parameter order by each sensor
None
> refactor(tier4_perception_launch): refactor perception launcher

- planning/mission_planner/include/mission_planner/mission_planner_interface.hpp
- planning/mission_planner/src/mission_planner/mission_planner.cpp
use ClearRoute instead of Trigger to prevent dying.
ServiceException from Trigger can not be caught.
tier4 internal slack
https://star4.slack.com/archives/C03QW0GU6P7/p1701669957434089
psim
> fix(mission_planner): use ClearRoute instead of Trigger to prevent dying

- planning/mission_planner/src/mission_planner/mission_planner.cpp
// Check reroute availability only when state is SET.
// This allows clear even if the module is running after the ARRIVED GOAL.
psim
> fix(mission_planner): fix clear_mrm_route

- planning/mission_planner/src/mission_planner/mission_planner.cpp
fix https://github.com/autowarefoundation/autoware.universe/pull/3460 for case (2)
(1)
```
/*
* find the index of the original route that has same idx with the front segment of the new
* route
*
*                          start_idx
* +-----------+-----------+-----------+-----------+-----------+
* |           |           |           |           |           |
* +-----------+-----------+-----------+-----------+-----------+
* |           |           |           |           |           |
* +-----------+-----------+-----------+-----------+-----------+
*  original    original    original    original    original
*                          target      target      target
*/
```
(2)
```
/*
* find the target route that has same idx with the front segment of the original route
*
* …
```
> fix(mission_planner): fix check_reroute_safety

- planning/behavior_path_planner/config/goal_planner/goal_planner.param.yaml
- planning/behavior_path_planner/config/start_planner/start_planner.param.yaml
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/start_planner/start_planner_module.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/start_planner/start_planner_parameters.hpp
- planning/behavior_path_planner/src/scene_module/goal_planner/manager.cpp
- planning/behavior_path_planner/src/scene_module/start_planner/manager.cpp
- planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
- planning/behavior_path_planner/src/utils/start_goal_planner_common/utils.cpp
- planning/behavior_path_planner_common/include/behavior_path_planner_common/utils/path_safety_checker/path_safety_checker_parameters.hpp
This [PR](https://github.com/autowarefoundation/autoware_launch/pull/719) should be merged first!!!
This commit refactors the start_planner module in several ways:
- The verbose parameter is removed from the YAML configuration file and replaced with a print_debug_info parameter under a new debug section.
- A new function, initVariables(), is introduced to initialize member variables, which is called during processOnEntry() and processOnExit().
- The function isBackwardDrivingComplete() is renamed to hasFinishedBackwardDriving() to better reflect its purpose. It also includes additional debug prints.
- A new function, checkCollisionWithDynamicObjects(), is introduced to encapsulate the logic for checking collisions with dynamic objects.
- The function isExecutionReady() is modified to use …
> refactor(start_planner): refactor debug and safety check logic

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/dynamic_avoidance/dynamic_avoidance_module.hpp
- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp
In the dynamic_avoidance module, the object's polygon removed from the drivable area is created along the previous module's reference path in the behavior_path_planner.
However, when the LC starts to run with the dynamic avoidance, since the LC changes the reference path suddenly, the object polygon's lateral position will be wrong due to the low-pass filter to the distance between the polygon and the reference path.
psim
dynamic avoidance with LC can be achieved.
[contribution …
> fix(dynamic_avoidance): deal with reference path changing by LC

- system/component_state_monitor/config/topics.yaml
I propose adding a topic monitor for the output of the traffic light recognition system. This is necessary because, in the current implementation of Autoware, the vehicle continues to operate as normal even when traffic signal messages are not received. Implementing this monitor could enhance safety by ensuring appropriate responses to traffic signal status.
PR for the launch:
- https://github.com/autowarefoundation/autoware_launch/pull/720
Related links
- [TIER IV INTERNAL](https://star4.slack.com/archives/C03S84LDJGG/p1701751131170859?thread_ts=1701412549.186139&cid=C03S84LDJGG)
- [TIER IV INTERNAL](https://tier4.atlassian.net/browse/RT1-3997)
Run logging simulator and confirmed hazard status is published properly.
Terminal1
Run logging simulator.
```
ros2 launch autoware_launch …
```
> feat(component_state_monitor): monitor traffic light recognition output

- planning/behavior_path_planner/config/dynamic_avoidance/dynamic_avoidance.param.yaml
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/dynamic_avoidance/dynamic_avoidance_module.hpp
- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp
- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/manager.cpp
Defined the path_generation_method deleted by https://github.com/autowarefoundation/autoware.universe/pull/4813
Since the object's predicted path is still unstable, the default method is based on not the object's path but the ego's path.
psim
Nothing by default
> feat(dynamic_avoidance): reintroduce path_generation_method

- planning/mission_planner/src/mission_planner/mission_planner.cpp
> feat(mission_planner): print reroute info

- planning/behavior_path_planner/src/behavior_path_planner_node.cpp
reset previous modified goal when new rouet is received. 
if the modified goal for the new route is the same as previous one, the modified goal is not published in 
https://github.com/autowarefoundation/autoware.universe/blob/feat/mrm-pull-over-manager/planning/behavior_path_planner/src/behavior_path_planner_node.cpp#L571-L575 …
> fix(behavior_path_planner): reset previou modified goal

- planning/mission_planner/src/mission_planner/mission_planner.cpp
fix reroute chattering when mrm route clear fails
psim
> fix(mission_planner): fix reroute chattering when mrm route clear fails

- planning/behavior_path_planner/include/behavior_path_planner/behavior_path_planner_node.hpp
- planning/behavior_path_planner/include/behavior_path_planner/planner_manager.hpp
- planning/behavior_path_planner/src/behavior_path_planner_node.cpp
- planning/behavior_path_planner/src/planner_manager.cpp
when only always executable modules (like fixed_goal_planner, dynamic avoidance(in the future?)) are running, reroute is allowd.
psim
> feat(behavior_path_planner): allow reroute when always executable module running or candidate modules is running

- planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
Fix PR for the [PR](https://github.com/autowarefoundation/autoware.universe/pull/5747)
1. The `updateData()` function now sets `status_.is_safe_dynamic_objects` to true when `requiresDynamicObjectsCollisionDetection()` returns false.
2. The `isExecutionReady()` function now checks for dynamic object collisions only if `requiresDynamicObjectsCollisionDetection()` returns true and `isWaitingApproval()` also returns true. This change ensures that dynamic object collision detection is performed only when necessary and approval is pending. …
> fix(start_planner): check safety only when waiting approval

- planning/behavior_path_planner/config/start_planner/start_planner.param.yaml
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/start_planner/start_planner_module.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/start_planner/start_planner_parameters.hpp
- planning/behavior_path_planner/src/scene_module/start_planner/manager.cpp
- planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
- planning/behavior_path_planner_common/include/behavior_path_planner_common/utils/path_safety_checker/objects_filtering.hpp
- planning/behavior_path_planner_common/src/utils/path_safety_checker/objects_filtering.cpp
**This [PR](https://github.com/autowarefoundation/autoware_launch/pull/723) should be merged first!!!**
This commit introduces a new feature in the start_planner module for checking surrounding moving obstacles.
- It adds parameters to specify the search radius and threshold velocity for moving obstacles, along with flags to indicate which types of objects should be checked.
- The `noMovingObjectsAround` function has been added to filter dynamic objects within a certain radius based on their velocity.
- If no moving objects are detected, the function returns true; otherwise, it returns false.
- This feature enhances the safety of the start_planner by ensuring that the path can't be approved while surrond moving obstacles exist.
confirmed with psim that safe status becomes false 
※safety …
> feat(start_planner): add surround moving obstacle check

- planning/behavior_path_goal_planner_module/src/goal_planner_module.cpp
- planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp
- planning/behavior_path_start_planner_module/src/start_planner_module.cpp
remove unnecessary TODO
TRYING status doesn't exist anymore
> refactor(behavior_path_planner): delete unnecessary TODO

- planning/behavior_velocity_crosswalk_module/config/crosswalk.param.yaml
- planning/behavior_velocity_crosswalk_module/src/manager.cpp
update comments for parameters
fix typo
> chore(crosswalk): update comments

- common/motion_utils/src/trajectory/tmp_conversion.cpp
- common/motion_utils/test/src/trajectory/test_trajectory.cpp
After this PR the `CAPACITY` constant from the `Trajectory`  message is no longer used in the universe code.
Required by https://github.com/autowarefoundation/autoware_msgs/pull/76
Psim
None
> refactor(motion_utils): stop using CAPACITY from Trajectory message

- localization/ekf_localizer/src/ekf_module.cpp
[In the recent PR of ekf localizer](https://github.com/autowarefoundation/autoware.universe/pull/5691), a new variable `accumulated_delay_times_` have been introduced so that the calculation of `delay_step` in `updateMeasurementPose/Twist()` will not be distorted when the timer callback has unintended time periods. 
However, the initialization of thefirst element of `accumulated_delay_times_` was `ekf_dt` seconds large while it should zero, which leads to a computation error of `delay_step` that will be one step earlier. 
This PR should fix that.
Tested and worked well in the [rosbag replay simulation tutorial](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/rosbag-replay-simulation/).
Also, tested with TIER IV internal rosbags too.
A few …
> fix(ekf_localizer): correct the initialization of accumulated_delay_times to obtain accurate computation of delay_time

- system/autoware_auto_msgs_adapter/test/test_msg_predicted_objects.cpp
Close #5742
Fixed a bug that was accessing out of range with vector in predicted path test.
`colcon test --packages-select autoware_auto_msgs_adapter`
> fix(autoware_auto_msgs_adapter): fix predicted path test

- localization/localization_util/src/smart_pose_buffer.cpp
Fixed rejection criteria of `SmartPoseBuffer::interpolate`.
See comments in changed code.
There are no effects on system behavior for basic vehicles.
In environments where LiDAR is lightweight, such as AWSIM, SmartPoseBuffer::interpolate are less likely to fail. …
> fix(localization_util): fixed rejection criteria of SmartPoseBuffer::interpolate

- planning/behavior_velocity_traffic_light_module/README.md
- planning/behavior_velocity_traffic_light_module/config/traffic_light.param.yaml
- planning/behavior_velocity_traffic_light_module/src/manager.cpp
- planning/behavior_velocity_traffic_light_module/src/scene.cpp
- planning/behavior_velocity_traffic_light_module/src/scene.hpp
Before this change, traffic light module plans PASS if the traffic light signal is timed out.
In this PR, I changed the behavior of traffic light module as following:
1. If a corresponding traffic light signal have never been found, it treats as a signal to pass.
2. If a corresponding traffic light signal is found but timed out, it treats as a signal to stop.
Furthermore, in this PR, I add the parameter to prevent chattering.
Please merge following PR before merge this PR
https://github.com/autowarefoundation/autoware_launch/pull/727
[TIER IV INTERNAL TEST](https://evaluation.tier4.jp/evaluation/reports/fcd51dca-0400-592f-b86b-052475e126f4?project_id=prd_jt)
Before:
[Screencast from 2023年12月08日 17時08分51秒.webm](https://github.com/autowarefoundation/autoware.universe/assets/10190493/52d3f1b7 …
> fix(traffic_light): stop if the traffic light signal timed out

- planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/goal_planner_module.hpp
- planning/behavior_path_goal_planner_module/src/goal_planner_module.cpp
- planning/behavior_path_goal_planner_module/src/util.cpp
check**Original**GoalIsInShoulder must check **original** goal pose
and remove unused methods.
this fix https://github.com/autowarefoundation/autoware.universe/pull/5533#issuecomment-1834013029
before
after
tier4 internal ticket
https://tier4.atlassian.net/browse/RT1-4666
psim
evaluator_description: fix/check_goal_is_in_shoulder
2023/12/11 https://evaluation.tier4.jp/evaluation/reports/11a68df2-9b57-500e-b5f2-56c687c126ea/?project_id=prd_jt …
> fix(goal_planner): fix checkOriginalGoalIsInShoulder

- localization/landmark_based_localizer/landmark_manager/CMakeLists.txt
Changed `landmark_manager` to a shared library
It is just a mistake that I did not make it a shared library until now.
`landmark_manager` will work as a shared library. …
> fix(landmark_manager): changed to a shared library

- launch/tier4_localization_launch/launch/localization.launch.xml
- launch/tier4_perception_launch/launch/obstacle_segmentation/ground_segmentation/ground_segmentation.launch.py
rename lidar topic of localization_launch and ground_segmentation_launch. 
`/sensing/lidar/<lidar name>/outlier_filtered/pointcloud` --> `/sensing/lidar/<lidar name>/pointcloud`
**Merge all Related PRs at the same time.**
https://github.com/autowarefoundation/autoware-documentation/pull/491
https://github.com/autowarefoundation/autoware.universe/pull/5781
https://github.com/autowarefoundation/sample_sensor_kit_launch/pull/82
https://github.com/autowarefoundation/autoware_launch/pull/722
https://github.com/RobotecAI/awsim_sensor_kit_launch/pull/12
https://github.com/autowarefoundation/awf_reference_sensor_kit_launch/pull/7
LSim works.
rename lidar topic of localization_launch and ground_segmentation_launch. 
`/sensing/lidar/<lidar name>/outlier_filtered/pointcloud` --> …
> refactor(localization_launch, ground_segmentation_launch): rename lidar topic

- system/system_error_monitor/config/diagnostic_aggregator/control.param.yaml
add missing control.param.ymal update for https://github.com/autowarefoundation/autoware.universe/pull/4549
psim
https://github.com/autowarefoundation/autoware.universe/assets/39142679/726fa0ed-ad44-4fed-aeb6-652394a1f6c2
system_error_monitor.param.yaml
```
/autoware/control/autonomous_driving/performance_monitoring/control_validator: { sf_at: "none", lf_at: "warn", spf_at: "error"}
```
vehicle cmd gate
```
use_emergency_handling: true
``` …
> feat(system_error_monitor): aggregate control validator diagnostics

- perception/tracking_object_merger/include/tracking_object_merger/utils/utils.hpp
- perception/tracking_object_merger/src/utils/utils.cpp
Tracking object merger has several functions to update tracklet kinematics with input objects.
- `updateOnlyObjectVelocity` is called when input is radar and tracklet do not have radar measurements recently
- `updateExceptVelocity` is called when input is lidar and tracklet is generated from radar
Previously, these functions do not check the velocity and yaw direction so it could cause unintended objects motion direction update.
- 1. Check motion direction calculated from orientation and velocity direction
- if motion direction do not match between measurement and tracklet, give up update
- 2. Check yaw direction between tracklet and measurement
- if yaw direction is inverse, rotate either measurement or tracklet to prevent object motion reverted
[TIER IV INTERNAL …
> feat(tracking_object_merger): check motion direction and yaw direction to prevent unintended direction update

- launch/tier4_perception_launch/launch/obstacle_segmentation/ground_segmentation/ground_segmentation.launch.py
This to add glog_component for debugging when a node of pointcloud_container crashed. 
Confirmed by logging_simulator that glob_component was executed.
If an error is added in one of pointcloud_container's node, for example voxel_based_compare_map_filter_nodelet.cpp 
`sed -i -z 's|pcl::PointCloud<pcl::PointXYZ>::Ptr pcl_output(new pcl::PointCloud<pcl::PointXYZ>);\n|pcl::PointCloud<pcl::PointXYZ>::Ptr pcl_output(new pcl::PointCloud<pcl::PointXYZ>);\n  throw std::runtime_error("error!!!!!!!!!!!!!!!!!!");\n|' ./src/universe/autoware.universe/perception/compare_map_segmentation/src/voxel_based_compare_map_filter_nodelet.cpp`
It will throw out some stack trace for debugging as bellow
```
[component_container_mt-1] terminate called after throwing an instance of 'std::runtime_error' …
```
> chore: add glog_component for pointcloud_container

- launch/tier4_localization_launch/launch/pose_twist_estimator/ar_tag_based_localizer.launch.xml
- localization/landmark_based_localizer/ar_tag_based_localizer/launch/ar_tag_based_localizer.launch.xml
- localization/landmark_based_localizer/ar_tag_based_localizer/package.xml
- localization/landmark_based_localizer/ar_tag_based_localizer/src/ar_tag_based_localizer.cpp
- localization/landmark_based_localizer/ar_tag_based_localizer/src/ar_tag_based_localizer.hpp
- localization/landmark_based_localizer/ar_tag_based_localizer/src/main.cpp
- localization/landmark_based_localizer/ar_tag_based_localizer/test/test.cpp
Refactored `ar_tag_based_localizer`.
* Changed launch nest
* Before `/localization/pose_estimator/ar_tag_based_localizer/ar_tag_based_localizer`
* After `/localization/pose_estimator/ar_tag_based_localizer`
* Previously, `landmark_parser` was running as a node, so it was necessary to create a namespace and launch nodes within it, but that is no longer the case.
* Fixed launch.xml to remap correctly
* Removed `image_transport`
* it has allowed to remove setup function also
* Fixed the code of the qos variable (the contents remain unchanged)
* Fixed cam_info_callback
* Fixed test …
> refactor(ar_tag_based_localizer): refactor pub/sub and so on

- simulator/simple_planning_simulator/README.md
- simulator/simple_planning_simulator/include/simple_planning_simulator/simple_planning_simulator_core.hpp
- simulator/simple_planning_simulator/src/simple_planning_simulator/simple_planning_simulator_core.cpp
add mesurent_steer_bias. the default value is 0.0
mesurent_steer_bias : 1.0
https://github.com/autowarefoundation/autoware.universe/assets/39142679/05e17e02-05fb-41c2-9c8c-a6688d0f1219
> feat(simple_planning_simulator): add mesurent_steer_bias

- planning/behavior_velocity_no_stopping_area_module/src/scene_no_stopping_area.cpp
- planning/behavior_velocity_planner_common/include/behavior_velocity_planner_common/scene_module_interface.hpp
- planning/behavior_velocity_planner_common/package.xml
- planning/behavior_velocity_planner_common/src/scene_module_interface.cpp
Apply `objects_of_interest_marker_interface` to `behavior_velocity_planner`.
Furthermore, apply to `behavior_velocity_no_stopping_area_module` as example.
https://github.com/autowarefoundation/autoware.universe/pull/5564
[TIER IV INTERNAL TEST](https://evaluation.tier4.jp/evaluation/reports/ba54dca2-0bc2-50f4-b003-d4c2ebf0eafa?project_id=prd_jt)
If vehicle is stuck:
If vehicle is not stuck:
See https://github.com/autowarefoundation/autoware.universe/pull/5564
Objects of interest marker data can be shown. …
> feat(behavior_velocity_planner_common): add objects_of_interest_marker_intereface to behavior_velocity_planner

- planning/behavior_velocity_crosswalk_module/config/crosswalk.param.yaml
- planning/behavior_velocity_crosswalk_module/include/behavior_velocity_crosswalk_module/util.hpp
- planning/behavior_velocity_crosswalk_module/src/manager.cpp
- planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
- planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp
Fixed to ignore the predicted path that crosses the crosswalk in almost the same direction as ego vehicle.
launcher PR: https://github.com/autowarefoundation/autoware_launch/pull/733
https://tier4.atlassian.net/browse/RT1-3967
https://evaluation.tier4.jp/evaluation/reports/8acb8fe9-6f94-5427-8bbe-58b7914b1d4c?project_id=prd_jt
https://github.com/autowarefoundation/autoware.universe/assets/28677420/0c51b76b-8994-44c9-997b-083796e093ed
https://github.com/autowarefoundation/autoware.universe/assets/28677420/50e7ed2c-45bb-4cc5-8064-170f9030a5ac
crosswalk stopline does not appear
https://github.com/autowarefoundation/autoware.universe/assets/28677420/2d0b62eb-fdd8-4f0e-b994-24bdaafce0c9
https://github.com/autowarefoundation/autoware.universe/assets/28677420/6e54aea4-806e-4e83-8983-5872fce0cc7e …
> feat(crosswalk): ignore predicted path going across the crosswalk

- planning/behavior_path_goal_planner_module/src/goal_planner_module.cpp
set rederence path for candidate path
psim
> fix(goal_planner): set rederence path for candidate path

- planning/motion_velocity_smoother/src/motion_velocity_smoother_node.cpp
After the ego reaches the goal, in some cases the following message is shown which is unnecessary.
This PR changes the condition of the message according to https://autowarefoundation.github.io/autoware.universe/main/system/default_ad_api/document/operation-mode/
psim
nothing …
> chore(motion_velocity_smoother): remove unnecessary info of non autonomous control

- launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.xml
- planning/behavior_path_planner/README.md
Removed the unnecessary parameter of `use_experimental_lane_change_function` which was introduced by https://github.com/autowarefoundation/autoware_launch/pull/418 but is currently not used.
psim
Nothing
> refactor(behavior_path_planner): remove use_experimental_lane_change_function

- planning/planning_debug_tools/scripts/perception_replayer/perception_reproducer.py
Since the type of `PredictedObjects` is too large and copying the predicted objects is too heavy, the hertz of the perception_reproducer is sometimes less than 10, resulting in the published objects disappearing on Rviz.
This PR improved the calculation time of perception_reproducer when using `predicted object` mode.
Total time is
- Before this PR: 50 - 80ms (sometimes 100 - 200ms and the objects disappear)
- After this PR: 15 - 25ms
psim
nothing …
> perf(planning_debug_tools): improve calculation time of perception_reproducer

- control/pid_longitudinal_controller/src/pid_longitudinal_controller.cpp
When the ego exceeds the goal position, the longitudinal controller does the emergency stop.
Even after the ego stops, the control state in the longitudinal controller is still emergency and showing the following unnecessary message.
This PR changes the condition from the emergency to the stopped.
In the emergency state, when the ego successfully stopped, the state will be changed to the stopped.
psim
nothing
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contrib …
> feat(pid_longitudinal_controller): change the condition from emergency to stopped

- planning/behavior_velocity_planner_common/src/scene_module_interface.cpp
When launching behavior_velocity_planner's modules, the following message to register the new modules is shown, which is for developers but makes the terminal messy.
```
[component_container_mt-29] [INFO 1702873200.701397039] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: register task: module = crosswalk, id = 1595 (registerModule():177)
[component_container_mt-29] [INFO 1702873200.703595298] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: register task: module = crosswalk, id = 1598 (registerModule():177)
[component_container_mt-29] [INFO 1702873200.707912157] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: register task: module = crosswalk, id = 1596 …
```
> chore(behavior_velocity_planner): use DEBUG for launching modules

- map/map_loader/src/lanelet2_map_loader/lanelet2_map_visualization_node.cpp
Add crosswalk_id visualization.
This must be merged after https://github.com/autowarefoundation/autoware_common/pull/220.
run psim and see the crosswalk id visualized
None
> chore(map_loader): visualize crosswalk id

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/dynamic_avoidance/manager.hpp
- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/manager.cpp
Without the PR, the dynamic avoidance did not become the IDLE state when the avoidance module is WAITING_APPROVAL.
This PR makes the dynamic avoidance always IDLE when requested by using the isAlwaysExecutableModule function.
psim
nothing
> feat(dynamic_avoidance): always launch the module when requested

- planning/behavior_velocity_run_out_module/config/run_out.param.yaml
- planning/behavior_velocity_run_out_module/package.xml
- planning/behavior_velocity_run_out_module/src/manager.cpp
- planning/behavior_velocity_run_out_module/src/scene.cpp
- planning/behavior_velocity_run_out_module/src/scene.hpp
- planning/behavior_velocity_run_out_module/src/utils.hpp
New feature to ignore the collision points on crosswalk
[Screencast from 2023年12月14日 19時34分23秒.webm](https://github.com/autowarefoundation/autoware.universe/assets/141538661/a0c80e9a-1b5f-46f0-875e-07d961849f7e)
PR for the launch 
https://github.com/autowarefoundation/autoware_launch/pull/737
psim tests was performed
Tier 4 internal test
https://evaluation.tier4.jp/evaluation/reports/a25119ef-0f00-5c86-9c75-374b03e3ef70?project_id=prd_jt
https://evaluation.tier4.jp/evaluation/reports/tables/new?catalog_id=095ae8b3-a23b-4a08-8674-10a681449693&filter=&job_id=db6eadfe-646e-5a43-aa6b-0e5e2540cb66&project_id=prd_jt&table_config=date&target_ids=d75114be-5409-570c-b1c6-ad308c87db33 …
> feat(run_out)!: ignore the collision points on crosswalk

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/dynamic_avoidance/dynamic_avoidance_module.hpp
- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp
When creating an object polygon to extract from the drivable area, the previous module's path instead of its reference path is used to avoid the following too large extraction.
NOTE: prev_input_ref_path_points_ and ref_path_before_lane_change_ are not used.
psim
nothing
> fix(dynamic_avoidance): fix drivable area generation during LC

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/dynamic_avoidance/dynamic_avoidance_module.hpp
- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp
Consider the forked object's path from ego's path when calculating the longitudinal length of the object polygon to remove from the drivable area.
psim
nothing
> feat(dynamic_avoidance): deal with forked path of the same directional vehicles

- planning/behavior_velocity_intersection_module/config/intersection.param.yaml
- planning/behavior_velocity_intersection_module/src/manager.cpp
- planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
- planning/behavior_velocity_intersection_module/src/scene_intersection.hpp
disable stuck vehicle detection against private lane
launcher PR: https://github.com/autowarefoundation/autoware_launch/pull/744
none.\
none.
> feat(intersection): disable stuck detection against private lane

- planning/behavior_velocity_run_out_module/src/scene.cpp
In the current implementation, the run-out module inserts a stop point when the ego vehicle is stationary. This is to prevent the stop decision from oscillating. This approach is particularly necessary for methods that assume pedestrians running out (`Point`s or `ObjectWithoutPath`), as these methods continuously detect objects. However, I believe this feature has a minimal impact when the method is set to `Object`. Therefore, I have disabled this feature for the `Object` method.
Simple planning simulator
Stop point is inserted when the ego has stopped.
https://github.com/autowarefoundation/autoware.universe/assets/11865769/4ff1b27d-c487-47e8-9af9-25e0a3469da3
https://github.com/autowarefoundation/autoware.universe/assets/11865769/c6bc296b-38a1-4771-84b2-5fc463410bf4
The …
> fix(run_out): do not insert stop point when stopped in Object method

- planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/shift_pull_out.hpp
- planning/behavior_path_start_planner_module/src/shift_pull_out.cpp
refine shift pull out path to start pose
before
after
evaluator_description: fix/shift_pull_out_start
2023/12/14 https://evaluation.tier4.jp/evaluation/reports/e8673ccf-7003-5fbb-a379-7c7c6f8cabe8/?project_id=prd_jt
> fix(start_planner): refine shift pull out path to start pose

- planning/behavior_velocity_traffic_light_module/package.xml
- planning/behavior_velocity_traffic_light_module/src/debug.cpp
- planning/behavior_velocity_traffic_light_module/src/manager.cpp
- planning/behavior_velocity_traffic_light_module/src/manager.hpp
- planning/behavior_velocity_traffic_light_module/src/scene.cpp
- planning/behavior_velocity_traffic_light_module/src/scene.hpp
Replace `boost::optional` to `std::optional` in traffic_light module.
> refactor(traffic_light_module): boost::optional to std::optional

- planning/behavior_path_planner/include/behavior_path_planner/planner_manager.hpp
Fix a bug that scene modules does not publish `steering_factor` topics.
> fix(behavior_path_planner): publish steering factor from scene modules

- control/pid_longitudinal_controller/README.md
I have updated the documentation to provide a more comprehensive explanation of the parameter associated with the `STOPPED` state, aiming to enhance clarity and understanding for users.
Related: link:
[TIER IV INTERNAL LINK](https://star4.slack.com/archives/C03QW0GU6P7/p1702956736838629?thread_ts=1702946228.311829&cid=C03QW0GU6P7)
None.
None. …
> docs(pid_longitudinal_controller): add the explanation of STOPPED Parameter

- map/map_loader/src/lanelet2_map_loader/lanelet2_dummy_projector.hpp
- map/map_loader/src/lanelet2_map_loader/lanelet2_local_projector.hpp
- map/map_loader/src/lanelet2_map_loader/lanelet2_map_loader_node.cpp
Close https://github.com/autowarefoundation/autoware/issues/3427. Use dummy projector when using local coordinates. The dummy projector does no conversion calculations and always returns (0, 0, ele).
https://github.com/autowarefoundation/autoware/issues/3427.
Check if the vehicle can drive autonomously in the simple planning simulator using local coordinate map.
Note: Since the tutorial map also has local coordinates, you can test it by adding the following file.
```yaml
projector_type: local
```
None
None
MRGS conversion is no longer performed when local projector type is selected. …
> feat(map_loader): use dummy projector when using local coordinates

- planning/behavior_path_avoidance_module/config/avoidance.param.yaml
- planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/data_structs.hpp
- planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/parameter_helper.hpp
- planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/scene.hpp
- planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/utils.hpp
- planning/behavior_path_avoidance_module/src/scene.cpp
- planning/behavior_path_avoidance_module/src/utils.cpp
Related PR: https://github.com/autowarefoundation/autoware_launch/pull/747
Avoidance module basically avoid only objects that have offset from current lane (e.g. parked vehicle on road shoulder). But sometimes we met the situation where it is difficult to judge whether the vehicle is parked or not by only their shift length. In that case, avoidance module checks the time duration since the object speed is less than threshold.
However, following behavior is caused by this feature.
https://github.com/autowarefoundation/autoware.universe/assets/44889564/c59f6418-8415-4b21-a718-cdb5272f648c
In this PR, I added another condition to that feature, and check moving distance. If the object moves more than threshold, avoidance module judges the object is **NOT** parked vehicle and ignore it even if …
> fix(avoidance): check moving distance

- planning/behavior_path_planner_common/src/utils/drivable_area_expansion/static_drivable_area.cpp
Potentially reduce processing time on CutOverlappedLanes by breaking early when finding the first path point within drivable lanes, also simplified a little the code by using a lambda function.
[TIER IV Internal link: Evaluator tests for first commit](https://evaluation.tier4.jp/evaluation/reports/66241d2b-028e-58b4-a506-3948dbbe463a?project_id=prd_jt) (Currently running a new test, but in principle there is no degradation related to this change)
Ran evaluator (see above) and also tested on PSim if the overlapped lanes are cut correctly, the behavior is correct. …
> feat(behavior_path_planner): potentially speed up cut overlapped lanes

- planning/freespace_planning_algorithms/include/freespace_planning_algorithms/rrtstar_core.hpp
- planning/freespace_planning_algorithms/src/rrtstar_core.cpp
replace boost optional to std optional
> refactor(freespace_planning_algorithm): boost optional to std

- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp
Changed the logic about which side to avoid
- When the target object velocity is the same direction as the ego
- Check if the current object position is left or right against the ego's path
- When the target object velocity is NOT the same direction as the ego
- Check if the object position in the near future is left or right against the ego's path
psim
nothing …
> fix(dynamic_avoidance): fix which side to avoid

- localization/ekf_localizer/README.md
- localization/ekf_localizer/config/ekf_localizer.param.yaml
- localization/ekf_localizer/include/ekf_localizer/hyper_parameters.hpp
- localization/ekf_localizer/src/ekf_localizer.cpp
Simple1DFilter parameters will be added to the parameter file to be able to change these parameters from the parameter file.
> refactor(ekf_localizer): add Simple1DFilter params to parameter file

- planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/data_structs.hpp
- planning/behavior_path_avoidance_module/src/debug.cpp
- planning/behavior_path_avoidance_module/src/utils.cpp
In this PR, I defined 3 types of object behavior:
- `NONE`
- `MERGING`
- `DEVIATING`
Most of all parked vehicle are categolized `Behavior::NONE`.
(e.g. parked vehicle on road shoulder.)
If the object try merging to ego lane, it's categolized this behavior. Basically, the ego vehicle yields merging vehicle and does **NOT** execute avoidance maneuver.
(e.g. merging from private road.)
If the object try moving adjacent lane or somewhere else, it's categolized this behavior. In this case, the ego vehicle try avoidance the object because the ego doesn't have to follow it anymore.
(e.g. u-turn in intersection.) …
> feat(avoidance): don't avoid merging vehicle

- planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/data_structs.hpp
- planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/debug.hpp
- planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/helper.hpp
- planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/manager.hpp
- planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/scene.hpp
- planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/shift_line_generator.hpp
- planning/behavior_path_avoidance_module/package.xml
- planning/behavior_path_avoidance_module/src/debug.cpp
- planning/behavior_path_avoidance_module/src/scene.cpp
- planning/behavior_path_avoidance_module/src/shift_line_generator.cpp
- planning/behavior_path_avoidance_module/src/utils.cpp
- planning/behavior_path_avoidance_module/test/test_behavior_path_planner_node_interface.cpp
Remove unused header in avoidance module.
Also apply some very minor changes based on clang-tidy.
> refactor(avoidance): remove unused header

- planning/behavior_path_avoidance_module/src/scene.cpp
Output safety check target object infomartion as commonized marker.
- `ColorName::GREEN` -> safe objects
- `ColorName::RED` -> unsafe objects
Psim
Nothing.
> feat(avoidance): output objects of interest

- common/autoware_auto_perception_rviz_plugin/include/object_detection/object_polygon_detail.hpp
- common/autoware_auto_perception_rviz_plugin/include/object_detection/object_polygon_display_base.hpp
- common/autoware_auto_perception_rviz_plugin/include/object_detection/tracked_objects_display.hpp
- common/autoware_auto_perception_rviz_plugin/src/object_detection/detected_objects_display.cpp
- common/autoware_auto_perception_rviz_plugin/src/object_detection/object_polygon_detail.cpp
- common/autoware_auto_perception_rviz_plugin/src/object_detection/predicted_objects_display.cpp
- common/autoware_auto_perception_rviz_plugin/src/object_detection/tracked_objects_display.cpp
related PR: https://github.com/autowarefoundation/autoware.universe/pull/5823 implementation of 'is_stationary' flag on radar tracking objects
feat (autoware_auto_perception_rviz_plugin): In the tracked objects plugin, visualizing object dynamic status can be chosen.
Simulations of sensing and perception modules were performed under a tier4 deployment, and the messages were selectively visualized by the Rviz plugin.
https://github.com/autowarefoundation/autoware.universe/assets/42434141/3f187061-a96e-4ea6-8949-df2f433821f3 …
> feat(perception_rviz_plugin): tracked object option to filter by is_stationary flag

- control/autonomous_emergency_braking/src/node.cpp
Fixes #5931
This PR fixes the calculation of ego to object distance. 
At the following `motion_utils::calcSignedArcLength` function:
https://github.com/autowarefoundation/autoware.universe/blob/f63ad331dabd1b979c14b8f6d20a20ecc5dec8c2/control/autonomous_emergency_braking/src/node.cpp#L367-L368
For instance, the predicted trajectory points of 'ego_path' have a size of 50, with only 15 predicted points provided. Consequently, the remaining 35 points have coordinates x: 0, y: 0, z: 0. As we've set 'current_p' to x: 0, y: 0, z: 0, the distance calculation becomes impossible. To resolve this issue, we need to utilize 'current_p' as the first index of 'ego_path' for calculating the distance between the ego and the object.
https://github.com/autowarefoundation/autoware.universe/blob/f63ad331dabd1 …
> fix(AEB): ego to object distance calculation logic with predicted path

- system/system_error_monitor/config/diagnostic_aggregator/localization.param.yaml
https://github.com/autowarefoundation/autoware.universe/pull/5439
Add pose_instability_detector to diagnostic_aggregator.
We haven't added the diagnostics to the system_error_monitor yet, so Autoware's behavior remains unchanged. ( Even if there's an error in diagnostics, Autoware won't switch to Emergency mode. )
Confirmed that there are no errors in Psim. …
> feat: add pose_instability_detector to diagnostic_aggregator

- planning/behavior_path_planner_common/src/utils/drivable_area_expansion/static_drivable_area.cpp
Added a guard of obstacle polygon points' size so that the behavior path planner node will not die.
psim
Nothing
> fix(behavior_path_planner_common): added a guard of obstacle polygon points

- planning/behavior_path_planner_common/src/utils/drivable_area_expansion/static_drivable_area.cpp
Fix https://github.com/autowarefoundation/autoware.universe/issues/5825.
I found a bug in drivable bound edge(start/goal point) processing logic.
This function got unexpected point index since there is no constraints. As a result, left bound was not built properly.
```c++
size_t findNearestSegmentIndexFromLateralDistance(
const std::vector<T> & points, const geometry_msgs::msg::Point & target_point)
```
In this PR, I added yaw threshold so that it can get proper point index.
Psim
https://github.com/autowarefoundation/autoware.universe/assets/44889564/3ef02177-182a-480f-b539-4449b6cd7bb0
Nothing. …
> fix(static_drivable_area_expansion): fix bug in drivable bound edge processing logic

- planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/parameter_helper.hpp
Following param declaration was removed accidentally. Fixed it in this PR.
```c++
p.ego_predicted_path_params.time_horizon_for_front_object =
getOrDeclareParameter<double>(*node, ns + "time_horizon_for_front_object");
```
Psim
Nothing.
> fix(avoidance): add missing param declaration

- planning/behavior_path_planner_common/src/utils/path_safety_checker/safety_check.cpp
Don't override polygon data even if it doesn't find corresponding time pose.
Psim
Nothing.
> fix(safety_check): don't override collision polygon even if it doesn't find corresponding time pose

- planning/behavior_path_planner/config/drivable_area_expansion.param.yaml
- planning/behavior_path_planner/src/behavior_path_planner_node.cpp
- planning/behavior_path_planner_common/include/behavior_path_planner_common/utils/drivable_area_expansion/drivable_area_expansion.hpp
- planning/behavior_path_planner_common/include/behavior_path_planner_common/utils/drivable_area_expansion/parameters.hpp
- planning/behavior_path_planner_common/include/behavior_path_planner_common/utils/drivable_area_expansion/path_projection.hpp
- planning/behavior_path_planner_common/include/behavior_path_planner_common/utils/drivable_area_expansion/types.hpp
- planning/behavior_path_planner_common/src/utils/drivable_area_expansion/drivable_area_expansion.cpp
- planning/behavior_path_planner_common/test/test_drivable_area_expansion.cpp
This PR improves the calculations of the drivable area expansion. Previously, the left and right bounds were expanded independently. With this PR, they are expanded together such that the resulting drivable area width is more accurately equals to the desired width.
Required launch PR: https://github.com/autowarefoundation/autoware_launch/pull/755
Psim
Evaluator (TIER IV INTERNAL LINK): 
- https://evaluation.tier4.jp/evaluation/reports/2491b8b3-717e-5cf8-be74-6d95c22181c1?project_id=x2_dev
- https://evaluation.tier4.jp/evaluation/reports/c4a4e2aa-55fd-59e4-b4b5-472c14457c5c?project_id=prd_jt
drivable area expansion more accurately achieve the desired minimum width. …
> feat(drivable area expansion): do not over expand beyond the desired width

- planning/behavior_path_avoidance_module/src/shift_line_generator.cpp
Avoidance module keeps distance between ego and shift line start point farther than threshold. And it trims shift lines whose start point is closer than threshold as invalid path. But both of threshold (shift line generation and validation) refer common value (calculate in `helper_->getMinimumPrepareDistance()`).Then, sometimes front shift line is trimmed unexpectedly.
As a result, invalid output path is generated. In this PR, I fixed validate function and add `1e-3` to check condition.
Psim
Nothing. …
> fix(avoidance): fix condition to trim front shift line

- localization/ndt_scan_matcher/include/ndt_scan_matcher/ndt_scan_matcher_core.hpp
- localization/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp
This PR addresses a issue related to oscillation detection in the ndt_scan_matcher.
The execution time of the ndt_scan_matcher is proportional to the number of iterations. In the current [ndt_omp implementation](https://github.com/tier4/ndt_omp/blob/03f63ed7d3f9bf54bebf254060a1d70eb62308f3/include/multigrid_pclomp/multigrid_ndt_omp_impl.hpp#L907-L914), since line search is disabled, ndt_scan_matcher sometimes experiences oscillations, leading to a high number of iterations. Monitoring for oscillation can be beneficial when ndt_scan_matcher performance slows down.
* Fixed a bug where the vector was not normalized in the calculation of oscillation.
* Fixed to add output the oscillation count in `/diagnostics`.
It has been confirmed that the `logging_simulator` runs with the same accuracy as …
> fix(ndt_scan_matcher): fixed oscillation in ndt_scan_matcher

- localization/ndt_scan_matcher/src/map_update_module.cpp
In this pull request, the data race for `ndt_ptr_` has been fixed.
In the traditional code, within the `update_ndt()` of the `map_update_module`, a copy of the `ndt_ptr_`  was obtained and changes were applied to this copy then it was written back.
However, the class `NormalDistributionsTransform`, which was copied, internally contains a shared_ptr as a member variable. As a result, a simple copy resulted in a shallow copy.
Consequently, when the map update of NDT and the pose estimation by NDT occurred simultaneously, it led to data race issues.
Because the shared_ptr is deeply used in the `NormalDistributionsTransform`, implementing a deep copy is difficult.
So the lock scope has been expanded. As a result, it is no longer necessary to make a copy of `ndt_ptr_`, and updates are now …
> fix(ndt_scan_matcher): fixed a lock scope in update_ndt

- planning/behavior_path_avoidance_module/src/utils.cpp
Basically, it is able to filter objects that should be avoid with high confidence if the ego goes straight in intersection because the lane infomation defined in HDMap is relatively accurate. On the other hand, it is more difficult to filter avoidance target objects based on right/left turning lane since sometimes thier lane bounds are not painted on ground in real world. Additionally, there are vehicles turn left and merge to ego lane, and ego vehicle doesn't have to avoid them.
Then, avoidance module uses some filtering condition (e.g. objects merging to ego lane are ignored.) for objects on right/left lane in order not to output unnecessary avoidance path.
But I found those condition applied for objects on straight lane unintentionally and caused scenario fails as follow. …
> fix(avoidance): don't ignore objects on straight lane in intersection

- planning/behavior_path_avoidance_by_lane_change_module/src/scene.cpp
- planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/interface.hpp
- planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/scene.hpp
- planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/utils/base_class.hpp
- planning/behavior_path_lane_change_module/src/interface.cpp
- planning/behavior_path_lane_change_module/src/scene.cpp
- planning/behavior_path_planner_common/include/behavior_path_planner_common/interface/scene_module_interface.hpp
Support new state for lane change modules.
[Evaluator result](https://evaluation.tier4.jp/evaluation/reports/5276e914-deec-554d-85f1-7a82709a49d1?project_id=prd_jt)
> refactor(lane_change): use new interface for state

- planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/interface.hpp
- planning/behavior_path_lane_change_module/src/interface.cpp
- planning/behavior_path_planner_common/include/behavior_path_planner_common/interface/scene_module_interface.hpp
Hide `updateCurrentState()` as private function. Inherit class only can override state transit conditions, and interface decides next state based on them.
This PR contains following modifications.
- remove `virtual` qualifier from `updateState()`
- remove `virtual` qualifier from `updateCurrentState()`
- move `current_state_` to private
Psim
Nothing. …
> refactor(bpp): remove virtual qualifier

- planning/behavior_path_start_planner_module/src/start_planner_module.cpp
static collision check end pose and polygon is visualized as red arrow and polygon.
```
collision_check_distance_from_end: -10.0
```
https://github.com/autowarefoundation/autoware.universe/assets/39142679/322e0130-7501-4518-ae16-ff589569bba6
> feat(start_planner): add static collision check end polygon marker

- perception/map_based_prediction/schema/map_based_pediction.schema.json
Implement the ROS Node configuration layout described in https://github.com/orgs/autowarefoundation/discussions/3371 for the localization_error_monitor package.
Remove the default value from the source code in order to ensure all parameter values are passed from the parameter files.
Create the schema
[pull request …
> refactor(updated-map-based-prediction): rework parameters

- planning/mission_planner/src/lanelet2_plugins/default_planner.cpp
fixes #5881
when `enable_correct_goal_pose` is set to true, only goal poses within lanelets are modified.
[Screencast from 12-15-2023 04_26_37 PM.webm](https://github.com/autowarefoundation/autoware.universe/assets/18645627/a655bee3-16b8-47bc-9432-3ab9d2b68814)
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines …
> feat(mission_planner): restrict enable_correct_goal_pose to poses within lanelets

- planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
- planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp
The module side modification regarding to https://github.com/autowarefoundation/autoware.universe/pull/5875
[Screencast from 12-26-2023 05:11:20 PM.webm](https://github.com/autowarefoundation/autoware.universe/assets/141538661/fed0db66-f43e-4a61-a7bd-956f9e64fb43)
Psim test was performed. …
> feat(crosswalk): add interset makers

- perception/map_based_prediction/README.md
- perception/map_based_prediction/config/map_based_prediction.param.yaml
- perception/map_based_prediction/include/map_based_prediction/map_based_prediction_node.hpp
- perception/map_based_prediction/src/map_based_prediction_node.cpp
Implement a lateral acceleration-based pruning mechanism to eliminate unfeasible vehicle paths. See link for more details: [TIER IV INTERNAL LINK](https://tier4.atlassian.net/wiki/spaces/~7120207d8589d164d74a6d8162863204d3efe2/pages/2977566225/Map+based+prediction+with+lateral+acceleration+constraints)
Also, added the possibility of updating parameters in real time (only used for the parameters added by this PR). 
[TIER IV INTERNAL LINK](https://tier4.atlassian.net/wiki/spaces/~7120207d8589d164d74a6d8162863204d3efe2/pages/2977566225/Map+based+prediction+with+lateral+acceleration+constraints)
PSim with different vehicle speeds and Evaluator tests (I did not find degradation caused by this PR.
): [TIER IV INTERNAL LINK]( https://evaluation.tier4.jp/evaluation/reports/4b9c1ce4-30bf-5bbb-ae97- …
> feat(map_based_prediction): prediction with acc constraints

- planning/behavior_path_goal_planner_module/src/goal_planner_module.cpp
- planning/behavior_path_planner_common/include/behavior_path_planner_common/utils/parking_departure/utils.hpp
- planning/behavior_path_planner_common/src/utils/parking_departure/utils.cpp
- planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/start_planner_module.hpp
- planning/behavior_path_start_planner_module/src/start_planner_module.cpp
visualize stop line when module inserts stop line in the path
confirmed with psim
> feat(start_planner): visualize stop line for safety check feature

- planning/behavior_path_planner_common/include/behavior_path_planner_common/marker_utils/utils.hpp
- planning/behavior_path_planner_common/include/behavior_path_planner_common/utils/parking_departure/common_module_data.hpp
- planning/behavior_path_planner_common/src/marker_utils/utils.cpp
- planning/behavior_path_start_planner_module/src/start_planner_module.cpp
visualize refined start pose
and start pose candidates with idx
> feat(start_planner): visualize refined start pose and start pose candidates with idx

- planning/motion_velocity_smoother/src/smoother/smoother_base.cpp
see #5964
Before PR, `front_wheel_angle_rad` values were shifted by 1 point forward. Consequently, Autoware may now turn slightly later than before.
> fix(motion_velocity_smoother): front wheel steer rate calculation

- control/mpc_lateral_controller/src/lowpass_filter.cpp
- control/mpc_lateral_controller/test/test_lowpass_filter.cpp
Bug fix: filt_vector in lowpass_filter.cpp
https://github.com/autowarefoundation/autoware.universe/blob/ec99b2f2218f6b27a0f9567480df73fe1ed2aea6/control/mpc_lateral_controller/src/lowpass_filter.cpp#L113-L139
case num=3 and u.size()=4 (e.g. u={1.0, 1.0, 1.0, 1.0})
if i=2, then num_tmp=i=2. So j in {-2,-1,0,1,2}.
When j=2, then i+j=4 and u[i+j] is list index out of range.
I have fixed the above problem.
I added new tests to test_lowpass_filter.cpp. …
> fix(filt_vector): fix a problem of list index out of range in filt_vector

- control/pid_longitudinal_controller/src/pid_longitudinal_controller.cpp
For some reason, this message is shown always after the ego reaches the goal in some cases, resulting in the messy terminal.
It's enough to show this message only once for each case (e.g. During moving the steering angle to the target when the ego is stopped, it's enough to show this message only once.).
This PR makes the message shown only once for each case.
psim
nothing …
> chore(pid_longitudinal_controller): change INFO printing frequency

- planning/surround_obstacle_checker/include/surround_obstacle_checker/debug_marker.hpp
- planning/surround_obstacle_checker/src/debug_marker.cpp
By the following PR, a stop virtual wall by the external velocity limit is published from the motion_velocity_smoother for MRM comfortable stop.
https://github.com/autowarefoundation/autoware.universe/pull/5555
The surround obstacle checker, which uses the external velocity limit to stop the ego, internally publishes the stop virtual wall, resulting in the duplicated walls.
This PR removes the publisher of the wall in the surround obstacle checker.
psim
Nothing …
> fix(surround_obstacle_checker): remove the virtual wall from the node

- control/joy_controller/README.md
- control/joy_controller/include/joy_controller/joy_converter/xbox_joy_converter.hpp
- control/joy_controller/include/joy_controller/joy_converter/xone_joy_converter.hpp
- control/joy_controller/launch/joy_controller.launch.xml
- control/joy_controller/schema/joy_controller.schema.json
- control/joy_controller/src/joy_controller/joy_controller_node.cpp
Simply adds Xbox One **bluetooth** joy key mapping. It is worth mentioning that Xbox One joy connected via USB acts like a P65 joy.
> feat(joy_controller): add xbox one joy mapping

- control/joy_controller/README.md
- control/joy_controller/config/joy_controller.param.yaml
- control/joy_controller/include/joy_controller/joy_controller.hpp
- control/joy_controller/schema/joy_controller.schema.json
- control/joy_controller/src/joy_controller/joy_controller_node.cpp
Some vehicle platforms has only exposed high level API for velocity commands. At early stage of development the `kinematic_state` topic might not be ready to operate on. With that aspects in mind, a pure velocity control with remote controller would be welcome. The new feature `raw_control` by default is false, therefore it does not affect current developers workspace. …
> feat(joy_controller): allow to control without odometry

- planning/obstacle_avoidance_planner/scripts/calculation_time_plotter.py
- planning/path_smoother/CMakeLists.txt
- planning/path_smoother/scripts/calculation_time_plotter.py
Added a plotter of the calculation time of the path_smoother package.
psim
nothing
> feat(path_smoother): add a plotter of calculation time

- planning/obstacle_avoidance_planner/src/mpt_optimizer.cpp
When updating the bounds of QP with a warm start in the obstacle_avoidance_planner package, this PR uses `osqp_update_bounds` instead of `osqp_update_lower/upper_bound`.
According to the OSQP's implementation, the condition of whether the lower bound is smaller than the upper bound is checked in each `osqp_upper_lower/upper_bound` function.
Without this PR, since the lower and upper bounds are updated separately, when the lower bound is updated but the upper bound is not updated, the condition may not be met, resulting in the following printing many times.
```
[ERROR] upper bound must be greater than or equal to lower bound
```
In addition, in the latest version of OSQP's implementation, `osqp_update_lower/upper_bound` will be removed.
https://github.com/osqp/osqp/issues/192
psim
nothing …
> fix(obstacle_avoidance_planner): use update_bounds instead of update_lower/upper_bounds

- planning/behavior_velocity_traffic_light_module/src/scene.cpp
The following debug printing is shown every time the ego passes through the traffic light which is not necessary for the daily use.
```
APPROACH -> GO_OUT
GO_OUT(RESTART) -> APPROACH
```
This PR makes them to use RCLCPP_DEBUG instead of RCLCPP_INFO.
psim
nothing
> chore(traffic_light_module): use RCLCPP_DEBUG for the debug printing

- map/map_height_fitter/src/map_height_fitter.cpp
The map_height_fitter package shows the following debug printing every time the ego pose is set, which is unnecessary for daily use.
```
[initial_pose_adaptor-37] [INFO 1703780545.900383599] [default_ad_api.helpers.initial_pose_adaptor]: original point: 89389.414 43158.734 0.000 (fit():171)
[initial_pose_adaptor-37] [INFO 1703780545.901397153] [default_ad_api.helpers.initial_pose_adaptor]: Send request to map_loader (get_partial_point_cloud_map():104)
[initial_pose_adaptor-37] [INFO 1703780545.902191874] [default_ad_api.helpers.initial_pose_adaptor]: Loaded partial pcd map from map_loader (grid size: 0) (get_partial_point_cloud_map():116)
[initial_pose_adaptor-37] [INFO 1703780545.902478060] [default_ad_api.helpers.initial_pose_adaptor]: modified point: 89389.414 43158.734 0.000 …
```
> chore(map_height_fitter): set log level of debug printing to DEBUG

- common/tier4_api_utils/include/tier4_api_utils/rclcpp/client.hpp
- common/tier4_control_rviz_plugin/src/tools/manual_controller.cpp
- common/tier4_state_rviz_plugin/src/autoware_state_panel.hpp
Some packages in common/ (e.g. rviz plugins to connect with the Autoware) show the debug printing as follows when using ROS2 service, which is not necessary for daily use.
```
client request
Status 0,
```
This PR sets its log level from INFO to DEBUG.
psim
Nothing
> chore: set log level of debug printing in rviz plugin to DEBUG

- common/component_interface_utils/include/component_interface_utils/rclcpp/interface.hpp
Currently, when
- the ego pose is set
- the Autoware is engaged
- the ego arrives the goal
- etc,
the following multiple debug printing is shown by component_interface_utils, which is not necessary for daily use.
```
[component_container_mt-35] [INFO 1702834054.891762811] [default_ad_api.node.routing]: server call: /api/routing/clear_route (log():55)
[component_container_mt-35] [INFO 1702834054.892185041] [default_ad_api.node.routing]: client call: /planning/mission_planning/clear_route (log():55)
[component_container_mt-35] [INFO 1702834054.892788913] [default_ad_api.node.routing]: client exit: /planning/mission_planning/clear_route (log():55)
[component_container_mt-35] [INFO 1702834054.892814293] [default_ad_api.node.routing]: server exit: /api/routing/clear_route (log():55) …
```
> chore(component_interface_utils): set log level of debug printing to DEBUG

- planning/behavior_path_planner/config/dynamic_avoidance/dynamic_avoidance.param.yaml
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/dynamic_avoidance/dynamic_avoidance_module.hpp
- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp
- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/manager.cpp
- planning/behavior_path_planner_common/include/behavior_path_planner_common/marker_utils/utils.hpp
- planning/behavior_path_planner_common/src/marker_utils/utils.cpp
In order to suppress sudden steering by the change of the drivable area just in front of the ego, the feasible ego's path considering lateral acc/jerk is calculated, and the object polygon to be removed from the drivable area is limited to this feasible path.
psim
Nothing
> feat(dynamic_avoidance): apply ego's lateral acc/jerk constraints to object polygon

- common/motion_utils/src/resample/resample.cpp
Fixed the bug of the right bound assignment in resamplePath of `autoware_auto_planning_msgs::msg::Path`.
- psim
- scenario test:
- https://evaluation.tier4.jp/evaluation/reports/6081423c-7cdd-5ca4-b754-ce8d0e210277?project_id=prd_jt
- https://evaluation.tier4.jp/evaluation/reports/467fd48b-0c73-5cc7-b28c-37a476cccebc?project_id=prd_jt
Nothing …
> fix(motion_utils): fix the right bound assignment in resamplePath

- common/motion_utils/include/motion_utils/trajectory/conversion.hpp
- common/motion_utils/src/trajectory/conversion.cpp
- planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/utils/trajectory_utils.hpp
- planning/obstacle_avoidance_planner/src/mpt_optimizer.cpp
- planning/obstacle_avoidance_planner/src/node.cpp
- planning/obstacle_avoidance_planner/src/utils/trajectory_utils.cpp
- planning/obstacle_cruise_planner/src/node.cpp
- planning/path_smoother/include/path_smoother/utils/trajectory_utils.hpp
- planning/path_smoother/src/elastic_band.cpp
- planning/path_smoother/src/elastic_band_smoother.cpp
- planning/path_smoother/src/utils/trajectory_utils.cpp
- planning/planning_topic_converter/src/path_to_trajectory.cpp
- planning/sampling_based_planner/path_sampler/include/path_sampler/utils/trajectory_utils.hpp
- planning/sampling_based_planner/path_sampler/src/node.cpp
- planning/sampling_based_planner/path_sampler/src/utils/trajectory_utils.cpp
Added a header argument with a default value in motion_utils::convertToTrajectory, which is a necessary variable for the visualization in Rviz.
And removed the utility functions to fill in the header of the trajectory which became unnecessary with the upper change in the obstacle_avoidance_planner, path_smoother, path_sampler, and planning_topic_converter packages.
psim
Nothing
[pull request …
> feat(motion_utils, etc): add header argument in convertToTrajectory

- planning/mission_planner/src/lanelet2_plugins/default_planner.cpp
- planning/mission_planner/src/mission_planner/mission_planner.cpp
Use RCLCPP_DEBUG instead of RCLCPP_INFO for the debug printing in the mission_planner package.
psim
Nothing
> chore(mission_planner): use RCLCPP_DEBUG for debug printing

- perception/multi_object_tracker/package.xml
`multi_object_tracker` is missing a dependency for `diagnostic_updater`
> build(multi_object_tracker): add missing diagnostic_updater dependency

- planning/behavior_velocity_planner/config/behavior_velocity_planner.param.yaml
- planning/behavior_velocity_planner/src/node.cpp
- planning/behavior_velocity_planner/src/node.hpp
- planning/behavior_velocity_planner_common/include/behavior_velocity_planner_common/utilization/path_utilization.hpp
Currently, the output path's interval of the behavior_velocity_planner is decided in the default argument of the utility function, which is hard to find and cannot be changed easily.
This PR moves the interval variable to the yaml file.
psim
Nothing
> refactor(behavior_velocity_planner): output path's interval can be designated by yaml

- planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
This PR fixes a bug in the stop position calculation besides the stop line.
The figures show psim tests with crosswalk_attention_range: 10.0
Before:
After:
[Screencast from 01-05-2024 06:36:20 PM.webm](https://github.com/autowarefoundation/autoware.universe/assets/141538661/652b96ef-36dc-42f7-93f7-2947fdb940d1)
psim tests and tier4 internal tests were perfomed.
[pull request …
> fix(crosswalk): stopping besides the stop line

- map/map_projection_loader/include/map_projection_loader/map_projection_loader.hpp
- map/map_projection_loader/src/map_projection_loader.cpp
I would like to make the part where the `map_projector_info` object is created an independent library so that not only this node but also other nodes can use this.
- Launch logging_simulator and confirmed that localization works fine with sample rosbag and map
- Colcon test passes
No effects expected
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing …
> refactor(map_projection_loader): make important part a library

- planning/behavior_velocity_intersection_module/src/scene_merge_from_private_road.cpp
- planning/behavior_velocity_intersection_module/src/scene_merge_from_private_road.hpp
merge from private was calculating first_conflicting_lanelet from the vanilla conflicting_lanelets, so it was including sibling lanelets that should be eliminated.
evaluator: https://evaluation.tier4.jp/evaluation/reports?project_id=prd_jt + https://evaluation.tier4.jp/evaluation/reports/8c170bc5-37af-5fa2-9316-a65c80e11304?project_id=prd_jt
none
none …
> fix((merge_from_private): fixed first attention lanelet calculation

- planning/behavior_path_planner_common/src/utils/drivable_area_expansion/static_drivable_area.cpp
Fix drivable bound extracsion logic in https://github.com/autowarefoundation/autoware.universe/pull/6006/commits/0fb37b129f209a0252bd566c030c140082488ad4. Before this PR, sometimes the intersection area bound was broken like following fig.
Psim (map: odaiba_stable/222-20231225030104904261)
Nothing. …
> fix(static_drivable_area_expansion): fix bound extraction logic

- planning/behavior_path_avoidance_by_lane_change_module/src/scene.cpp
- planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/utils.hpp
- planning/behavior_path_avoidance_module/src/scene.cpp
- planning/behavior_path_avoidance_module/src/utils.cpp
- planning/behavior_path_planner_common/include/behavior_path_planner_common/utils/traffic_light_utils.hpp
- planning/behavior_path_planner_common/src/utils/traffic_light_utils.cpp
Previously, avoidance module always expanded drivable area as much as possible. However, sometimes it blocked vehicle on opposite lane when the ego was waiting for red traffic light. In this situation, the ego basically should **NOT** straddle lane bound if there is possibility to stop by traffic signal.
After this PR, the module limits drivable lanes expansion and generates avoidance path within current lane when the ego is going to stop at stop line by traffic signal.
```c++
const auto update_left_lanelets = [&](const lanelet::ConstLanelet & target_lane) {
const auto next_lanes = route_handler->getNextLanelets(target_lane);
const auto is_stop_signal = utils::traffic_light::isTrafficSignalStop(next_lanes, planner_data);
if (is_stop_signal && !in_avoidance_maneuver) {
return;
}
const auto …
```
> feat(avoidance): check traffic light info in order to limit drivable area

- planning/behavior_path_avoidance_module/src/scene.cpp
- planning/behavior_path_avoidance_module/src/shift_line_generator.cpp
Return path is not generated properly.
Nothing.
> fix(avoidance): return shift path was not generated expectedly

- launch/tier4_localization_launch/launch/pose_twist_estimator/ndt_scan_matcher.launch.xml
- localization/ndt_scan_matcher/launch/ndt_scan_matcher.launch.xml
The topic name settings in `ndt_scan_matcher.launch.xml` have been changed.
It is recommended to use abstract topic names for topics described in launch within a package. [ekf_localizer.launch.xml](https://github.com/autowarefoundation/autoware.universe/blob/142bc49b57f6ca002c99efa6406b22ce9012448d/localization/ekf_localizer/launch/ekf_localizer.launch.xml) is a good example. Following this, I made the same changes to `ndt_scan_matcher`.
The specific topic name is deleted in the launch file in the `ndt_scan_matcher` package. Instead, set the name used by autoware in `launch/tier4_localization_launch/launch/pose_twist_estimator/ndt_scan_matcher.launch.xml`.
As a minor change, I also aligned the order in which topic names are written in these files.
Also, `input_map_points_topic` has been …
> refactor(ndt_scan_matcher): fixed ndt_scan_matcher.launch.xml

- planning/behavior_velocity_intersection_module/src/debug.cpp
- planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
- planning/behavior_velocity_intersection_module/src/scene_intersection.hpp
obtain second_attention_lanelet as well as first_attention_lanelet
evaluator: https://evaluation.tier4.jp/evaluation/reports/f101b282-365a-5a42-bc3d-eaf7681328ce?project_id=prd_jt
If the intersection is single lane, second_attention_lane is null.
none.
none.
> feat(intersection): distinguish 1st/2nd attention lanelet

- planning/motion_velocity_smoother/src/motion_velocity_smoother_node.cpp
Closes: https://github.com/autowarefoundation/autoware.universe/issues/6027
The input trajectory of the applyStopApproachingVelocity() function does not have zero velocity on the last point. Because there is no zero velocity on the last point, applyStopApproachingVelocity() function returns none. Therefore,  stopping_distance and stopping_velocity parameters do not work. 
Tested on PSim for stopping_velocity: 0.0, stopping_distance: 5.0 :
https://github.com/autowarefoundation/autoware.universe/assets/45468306/c6eac644-2b73-4488-8844-88ee881a241c
Vehicle can stop before 5.0 meters from the goal point. …
> fix(motion_velocity_smoother): make stopping_distance and stopping_velocity be able to work

- launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.xml
Arguments for the behavior path planner to select which modules are run are defined twice.
This PR removes the duplicates.
> refactor(tier4_planning_launch): remove duplicate arguments in launchfile

- planning/behavior_path_lane_change_module/src/interface.cpp
Before abort process, lane change module should check if ego vehicle can return to original lane or not. And if it can't, abort path should not be computed.
None.
Using PSIM to check abort behavior
None
None
None
> fix(lane_change): check able to return to original lane in abort

- localization/ekf_localizer/README.md
- localization/ekf_localizer/config/ekf_localizer.param.yaml
- localization/ekf_localizer/include/ekf_localizer/hyper_parameters.hpp
- localization/ekf_localizer/src/ekf_localizer.cpp
`ekf_localizer` broadcasts `map` -> `base_link` transformation which is fundamental to the operation of the entire system. However, custom modifications within the architecture (e.g. using Cartographer) may require to turn off this feature. Setting up `tf_rate` to 0.0 returns an exception, remapping `/tf` is inappropriate due to the need to use `EKFLocalizer::callbackInitialPose`. Therefore, the `tf_publish` parameter would be welcome. The parameter will be set to `true` by default so that it does not affect the current developers workspace.
Similar solution is used in [geo_pose_projector](https://github.com/autowarefoundation/autoware.universe/blob/7c6666051157d2f26572144296700eb1238f4f08/localization/geo_pose_projector/src/geo_pose_projector.cpp#L46).
The …
> feat(ekf_localizer): tf publisher as an option

- perception/map_based_prediction/include/map_based_prediction/map_based_prediction_node.hpp
- perception/map_based_prediction/src/map_based_prediction_node.cpp
- perception/map_based_prediction/src/path_generator.cpp
small refactoring and fixing a bug with negative yaw rates. 
Tested on Psim
> fix(map_based_prediction): yaw rate can be overwritten by max function

- planning/behavior_velocity_intersection_module/config/intersection.param.yaml
- planning/behavior_velocity_intersection_module/src/manager.cpp
- planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
occlusion.max_clearance_distance was not initialized so occlusion detection was not working well. Also is_amber_or_red variable was declared as double unintentionally.
occlusion feature works as before
none.
none.
> fix(intersection): fix bugs

- planning/mission_planner/src/lanelet2_plugins/default_planner.cpp
- planning/mission_planner/src/lanelet2_plugins/utility_functions.cpp
- planning/mission_planner/src/lanelet2_plugins/utility_functions.hpp
check shoulder lanelets for `check_goal_footprint`
before
after
https://evaluation.tier4.jp/evaluation/reports/63c21419-52a0-5df7-b2f7-28bc5db0aa67?project_id=prd_jt
https://evaluation.tier4.jp/evaluation/reports/tables/new?catalog_id=095ae8b3-a23b-4a08-8674-10a681449693&filter=&job_id=63c21419-52a0-5df7-b2f7-28bc5db0aa67&project_id=prd_jt&table_config=date%2Ctotal%2Chide&target_ids=6fed1e3d-f2a8-52da-a8c1-bdb93f176217
psim …
> feat(mission_planner): check shoulder lanelets for check_goal_footprint

- localization/landmark_based_localizer/landmark_manager/include/landmark_manager/landmark_manager.hpp
- localization/landmark_based_localizer/landmark_manager/src/landmark_manager.cpp
A function has been added to return an array of landmarks in the `landmark_manager`.
This function is intended to be used in the [`lidar_marker_localizer`](https://github.com/autowarefoundation/autoware.universe/pull/5573) for searching the nearest landmark and so on.
LSim works. …
> feat(landmark_manager): add get_landmarrks func

- common/autoware_auto_perception_rviz_plugin/include/object_detection/object_polygon_detail.hpp
- common/autoware_auto_perception_rviz_plugin/include/object_detection/object_polygon_display_base.hpp
- common/autoware_auto_perception_rviz_plugin/src/object_detection/detected_objects_display.cpp
- common/autoware_auto_perception_rviz_plugin/src/object_detection/object_polygon_detail.cpp
- common/autoware_auto_perception_rviz_plugin/src/object_detection/predicted_objects_display.cpp
- common/autoware_auto_perception_rviz_plugin/src/object_detection/tracked_objects_display.cpp
This PR is to visualize orientation (heading direction) of objects (detected object, tracked object, predicted object).
The orientation will be visualized only when the object orientation flag is VALID.  The predicted object do not have the flag and the direction will be visualized since the direction is always available.
Simulations of sensing and perception modules were performed under a tier4 deployment, and the messages were selectively visualized by the Rviz plugin.
https://github.com/autowarefoundation/autoware.universe/assets/42434141/ea56257d-70a3-4909-84f1-bc1942bb42c3 …
> feat(perception_rviz_plugin): visualize object heading direction on 3d bounding box

- common/geography_utils/src/lanelet2_projector.cpp
Without this PR, when handling the MGRS projector created by `geography_utils::get_lanelet2_projector`, the following error occurred.
https://github.com/autowarefoundation/autoware_common/blob/6bbda6513206ea968f76f310a4bf2847bff3a583/tmp/lanelet2_extension/lib/mgrs_projector.cpp#L82-L83
Run static_centerline_optimizer's script
Nothing …
> feat(geography_utils): add mgrs code in projector

- planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/data_structs.hpp
- planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/scene.hpp
- planning/behavior_path_avoidance_module/src/debug.cpp
- planning/behavior_path_avoidance_module/src/scene.cpp
- planning/behavior_path_avoidance_module/src/utils.cpp
- planning/behavior_path_planner_common/src/turn_signal_decider.cpp
- planning/behavior_path_planner_common/src/utils/drivable_area_expansion/static_drivable_area.cpp
Reduce aggregated costs 14.7% to **10.7%** in behavior planning container by following improvement.
- reduce frequecy to call `calcSignedArcLength`
- don't use `boost::geometry::union_`
- don't use `std::hypot`
> perf(bpp): reduce computational cost

- localization/ekf_localizer/include/ekf_localizer/ekf_localizer.hpp
- localization/ekf_localizer/src/ekf_localizer.cpp
Changed the handling of timestamps in `ekf_localizer`.
I found that `this->now()` returns different timestamps even during a single timer callback execution.
Therefore, I think it would be better to obtain the timestamp only once at the beginning of timer callback execution, and use it commonly in one callback. Please let me know if there is any misunderstanding.
* Before : 0.051 [m]
* After :  0.050 [m]
I plotted the difference between the value of one step and the value of the next step regarding x, y, z and timestamp of Pose output by EKF.
* Before
* After
It seems that the topic timestamps output by EKF will be slightly more stable. …
> fix(ekf_localizer): fixed timer in ekf_localizer

- planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/start_planner_module.hpp
- planning/behavior_path_start_planner_module/src/start_planner_module.cpp
Output safety check target object infomartion as commonized marker.
ColorName::GREEN -> safe objects
ColorName::RED -> unsafe objects
https://github.com/autowarefoundation/autoware.universe/assets/39142679/f2481b68-e762-49b5-9bf9-953f6c7f6002
psim
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelin …
> feat(start_planner): output objects of interest

- common/autoware_auto_perception_rviz_plugin/include/autoware_auto_perception_rviz_plugin/object_detection/object_polygon_detail.hpp
- common/autoware_auto_perception_rviz_plugin/include/autoware_auto_perception_rviz_plugin/object_detection/object_polygon_display_base.hpp
- common/autoware_auto_perception_rviz_plugin/src/object_detection/detected_objects_display.cpp
- common/autoware_auto_perception_rviz_plugin/src/object_detection/object_polygon_detail.cpp
- common/autoware_auto_perception_rviz_plugin/src/object_detection/predicted_objects_display.cpp
- common/autoware_auto_perception_rviz_plugin/src/object_detection/tracked_objects_display.cpp
1. Modify pose covariance to draw eclipse instead of cross. (white eclipse)
2. Add visualizations of
* Yaw Covariance (white section)
* Twist Covariance (red eclipse)
* Yaw Rate (red section)
* Yaw Rate Covariance (pink H-shape)
3. Add option to configure confidence Interval of 'Covariance' 
https://github.com/autowarefoundation/autoware.universe/assets/42434141/37c09b2e-2939-4c0d-a447-08b85aaecbc3
* Default value of the new visualizations are `false`. It is to reduce complexity of default view.
* Naming convention of `covariance` was inherited. The visualizations of `covariance` is the confidence interval.
The PR …
> feat(perception_rviz_plugin): rviz object covariances

- planning/static_centerline_optimizer/launch/static_centerline_optimizer.launch.xml
- planning/static_centerline_optimizer/package.xml
- planning/static_centerline_optimizer/src/static_centerline_optimizer_node.cpp
- planning/static_centerline_optimizer/test/test_static_centerline_optimizer.test.py
The behavior_velocity_planner's path interval was recently extracted from the hard code to the yaml file.
The static_centerline_optimizer package depends on the originally hard-coded parameter.
This PR makes the static_centerline_optimizer to load the parameter from the yaml file.
Unit test
Nothing …
> feat(static_centerline_optimizer): get behavior_velocity_planner's path interval from yaml

- planning/behavior_path_avoidance_by_lane_change_module/src/scene.cpp
- planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/utils.hpp
- planning/behavior_path_avoidance_module/src/scene.cpp
- planning/behavior_path_avoidance_module/src/shift_line_generator.cpp
- planning/behavior_path_avoidance_module/src/utils.cpp
Previously, avoidance module generate detection area based on latest planned path. In this PR, I fixed detection area calcuration logic by using reference path in order not to prevent endless loop.
Nothing.
> feat(avoidance): improve object detection area in order not to prevent endless loop

- localization/ndt_scan_matcher/include/ndt_scan_matcher/ndt_scan_matcher_core.hpp
- localization/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp
I would like to change the handling of `output_pose_covariance` param from the map coordinate system to the base_link coordinate system.
Along with this, a feature to convert `output_pose_covariance` to the map coordinate system based on the estimated pose has been added.
- LSim works as usual.
※ The output covariance of NDT have changed slightly, so it is not exactly the same as before.
- When [output_pose_covariance](https://github.com/autowarefoundation/autoware_launch/blob/main/autoware_launch/config/localization/ndt_scan_matcher.param.yaml#L62-L70
) is modified, the output covariance becomes aligned with the estimated pose.
example
```
output_pose_covariance:
[
30.0, 0.0,   0.0,   0.0,      0.0,      0.0,
0.0,   10.0, 0.0,   0.0,      0.0,      0.0,
0.0,   0.0,   0.0225, 0.0, …
```
> feat(ndt_scan_matcher): change coordinate of output_pose_covariance 

- localization/yabloc/yabloc_image_processing/launch/image_processing.launch.xml
- localization/yabloc/yabloc_particle_filter/README.md
- localization/yabloc/yabloc_particle_filter/include/yabloc_particle_filter/prediction/predictor.hpp
- localization/yabloc/yabloc_particle_filter/launch/yabloc_particle_filter.launch.xml
- localization/yabloc/yabloc_particle_filter/src/prediction/predictor.cpp
This PR adds a service to stop and resume yabloc.
This was created to split the PR https://github.com/autowarefoundation/autoware.universe/pull/5846
* I have also changed the inappropriate default value for `resized_image`. This change does not affect the behavior since it is overwritten by the upper launch file.
The following data sets were used to confirm the behavior. 
(We can conrifm the behavior of this [even with the sample rosbag in logging_simulator.](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/rosbag-replay-simulation/))
* [map](https://github.com/tier4/AWSIM/releases/download/v1.1.0/nishishinjuku_autoware_map.zip) : This link was quoted from [AWSIM tutorial](https://tier4.github.io/AWSIM/GettingStarted/QuickStartDemo/#start-the-dem …
> feat(yabloc): add yabloc trigger service to suspend and restart the estimation

- planning/behavior_path_goal_planner_module/src/goal_searcher.cpp
exclude goals located laterally in no_parking_areas
green small arrows are goal candidates.
before
after
psim
evaluator_description: feat/excule_goals
2024/01/16 https://evaluation.tier4.jp/evaluation/reports/3d4e05ae-9697-5f39-a988-a23aa971982e/?project_id=prd_jt …
> feat(goal_planner): exclude goals located laterally in no_parking_areas

- planning/behavior_path_avoidance_module/src/utils.cpp
Related PR: https://github.com/autowarefoundation/autoware.universe/pull/6084
Issue: there are some gaps between detection areas.
Psim.
Nothing.
> fix(avoidance): fix detection area issue in avoidance module

- perception/tensorrt_yolo/config/yolov3.param.yaml
- perception/tensorrt_yolo/config/yolov4-tiny.param.yaml
- perception/tensorrt_yolo/config/yolov4.param.yaml
- perception/tensorrt_yolo/config/yolov5l.param.yaml
- perception/tensorrt_yolo/config/yolov5m.param.yaml
- perception/tensorrt_yolo/config/yolov5s.param.yaml
- perception/tensorrt_yolo/config/yolov5x.param.yaml
Before this PR I got the following error when I launched `tensorrt_yolo`.
```shell
$ ros2 launch tensorrt_yolo tensorrt_yolo.launch.xml build_only:=true
[INFO] [launch]: All log files can be found below /home/ktro2828/.ros/log/2024-01-17-11-08-58-611535-ktro2828-desktop-31696
[INFO] [tensorrt_yolo_node-1]: process started with pid [31697]
[tensorrt_yolo_node-1] terminate called after throwing an instance of 'rclcpp::exceptions::UninitializedStaticallyTypedParameterException'
[tensorrt_yolo_node-1]   what():  Statically typed parameter 'score_thresh' must be initialized.
[ERROR] [tensorrt_yolo_node-1]: process has died [pid 31697, exit code -6, cmd '/home/ktro2828/workspace/autoware.universe/install/tensorrt_yolo/lib/tensorrt_yolo/te …
```
> fix: rename `score_threshold` into `score_thresh` in config

- planning/behavior_path_planner/include/behavior_path_planner/planner_manager.hpp
- planning/behavior_path_planner/src/planner_manager.cpp
Output planner manager internal state as a topic.
Related PR: https://github.com/autowarefoundation/autoware.universe/pull/6100
Psim
`ros2 topic echo /planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/debug/internal_state`
Output topic as `/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/debug/internal_state` …
> feat(behavior_path_planner): output manager internal state as topic

- planning/behavior_path_goal_planner_module/src/goal_planner_module.cpp
remove duplicated execution condition
> refactor(goal_planner): remove duplicated execution condition

- planning/behavior_path_planner/src/behavior_path_planner_node.cpp
- planning/behavior_velocity_planner/src/node.cpp
Previously PlannerData of behavior_velocity and behavior_path did not clean old data in the traffic_light_id_map.
For planning policy we should not save old data which is missing in current observation. If some module wants to save traffic signal information that is not available currently, it should save it individually.
I used intersection module for test. The intersection module ignores occlusion when the traffic signal is RED.
occlusion it detected at the beginning because  {10575, GREEN} is available. Then at [00:04] occlusion is not detected because {10575, RED}. Then at [00:14] the info of 10575 is lost, and its info is remaining at planner_data, so occlusion is not detected because it is still interpreted as RED.
https://github.com/autowarefoundation/autoware.universe/assets/286774 …
> fix(behavior_velocity_planner, behavior_path_planner): refresh raw traffic light id map every callback

- perception/radar_tracks_msgs_converter/README.md
- perception/radar_tracks_msgs_converter/launch/radar_tracks_msgs_converter.launch.xml
This PR change a default parameter for twist compensation in `radar_tracks_msgs_converter`.
The feature of twist compensation is used for Autoware integration in most case, so this PR change its default parameters according to the current use case.
Tests by rosbag.
The parameter in `aip_launcher` is specified and used, so it has no effect. …
> fix(radar_tracks_msgs_converter): change default parameter for twist compensation

- launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml
- launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_radar_fusion_based_detection.launch.xml
- launch/tier4_perception_launch/launch/perception.launch.xml
Fix declaration method of pointpainting. Aligning to that of centerpoint.
Launched pilot-auto.xx1 (TIER IV private repository) with pointpainting node and confirmed that it successfully launches and publishes the estimation.
Not applicable
> fix(pointpainting): fix param path declaration

- planning/behavior_velocity_blind_spot_module/config/blind_spot.param.yaml
- planning/behavior_velocity_blind_spot_module/src/debug.cpp
- planning/behavior_velocity_blind_spot_module/src/manager.cpp
- planning/behavior_velocity_blind_spot_module/src/scene.cpp
- planning/behavior_velocity_blind_spot_module/src/scene.hpp
Add the feature to consider wrong vehicles on the adjacent opposite lane to some extent
launcher PR: https://github.com/autowarefoundation/autoware_launch/pull/695
https://tier4.atlassian.net/browse/RT1-3027
evaluator: https://evaluation.tier4.jp/evaluation/reports/0edea585-2686-5670-80e4-11bdf643eb6c?project_id=prd_jt
The blind spot polygon is generated on the opposite side
https://github.com/autowarefoundation/autoware.universe/assets/28677420/9862f92e-e143-490a-aab9-23912fc910c2
none.
none.
none. …
> feat(blind_spot): consider opposite adjacent lane for wrong vehicles

- planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
Fixes: https://github.com/autowarefoundation/autoware.universe/issues/6102
https://github.com/autowarefoundation/autoware.universe/assets/32412808/6963af10-4b71-4f72-a281-f171481d6eb2
> fix(behavior_velocity_crosswalk_module): check if p_safety_slow is empty

- perception/map_based_prediction/README.md
- perception/map_based_prediction/config/map_based_prediction.param.yaml
- perception/map_based_prediction/include/map_based_prediction/map_based_prediction_node.hpp
- perception/map_based_prediction/include/map_based_prediction/path_generator.hpp
- perception/map_based_prediction/src/map_based_prediction_node.cpp
- perception/map_based_prediction/src/path_generator.cpp
This PR adds acceleration readings from perception into the map_based_prediction module (can be toggled on or off. Off by default) to calculate path lengths more accurately.
Since including acceleration might have a big impact on path length (the time horizon for prediction is usually between 10 to 18s and we cannot assume a car will accelerate for that long) this feature uses a decaying acceleration model to calculate the path length after time_horizon T: 
> a(t) = a_0 * e ^(-λ*t) 
were a_0 is the instantaneous acceleration detected by perception, λ is the exponential decaying constant, and t is time with 0 <= t <= T. 
The result is a map based prediction that also includes (attenuated/decaying) acceleration information for a more accurate prediction.
Also, there is a slightly more …
> feat(map_based_prediction): use obstacle acceleration for map prediction

- planning/behavior_path_goal_planner_module/src/goal_planner_module.cpp
- planning/behavior_path_start_planner_module/src/start_planner_module.cpp
do not call freespace planner callback when not necessary
evaluator_description: fix/guard_freespace_planner
2024/01/19 https://evaluation.tier4.jp/evaluation/reports/f1f05d54-86e8-5b44-aa4b-631a16a39e81/?project_id=prd_jt
> fix(start/goal_planner): do not call freespace planner callback when not necessary

- planning/behavior_path_goal_planner_module/README.md
- planning/behavior_path_goal_planner_module/config/goal_planner.param.yaml
- planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/goal_planner_parameters.hpp
- planning/behavior_path_goal_planner_module/src/goal_planner_module.cpp
- planning/behavior_path_goal_planner_module/src/manager.cpp
expand pull over lanes for detection area of path generation collision check
before
after
psim
evaluator_description: feat/goal_planner_detection_area
2024/01/19 https://evaluation.tier4.jp/evaluation/reports/bfad8a8b-f2f3-592f-bed8-b6f12d0a2f7c/?project_id=prd_jt …
> feat(goal_planner): expand pull over lanes for detection area of path generation collision check

- planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/goal_planner_module.hpp
- planning/behavior_path_goal_planner_module/src/goal_planner_module.cpp
store info strings with stop_pose_ and display them as debug marker
evaluator_description: feat/stop_pose_info
2024/01/19 https://evaluation.tier4.jp/evaluation/reports/8b9874ba-f0fc-5b31-b784-77595d0eaad9/?project_id=prd_jt
https://evaluation.tier4.jp/evaluation/reports/b213ad21-1371-5559-bdbf-e86f8de56a13?project_id=prd_jt …
> feat(goal_planner): display stop pose infomation

- planning/planning_validator/include/planning_validator/planning_validator.hpp
- planning/planning_validator/msg/PlanningValidatorStatus.msg
- planning/planning_validator/src/planning_validator.cpp
Add a trajectory size check in the planning validator. Before, the `planning_validator` does not perform any validation for trajectories with less than 3 trajectory points. After, the `planning_validator` raises an error for the no-enough-points trajectory.
[TIERIV INTERNAL LINK](https://tier4.atlassian.net/browse/RT1-4973)
1. change planning_validator publish policy to 1 or 2: https://github.com/autowarefoundation/autoware_launch/blob/main/autoware_launch/config/planning/scenario_planning/common/planning_validator/planning_validator.param.yaml/#L7
2. run psim
3. publish an empty trajectory and check if the control module won't show any error message on the terminal.
```sh
$ ros2 topic pub /planning/scenario_planning/motion_velocity_smoother/trajectory …
```
> feat(planning_validator): add invalid size error

- planning/behavior_path_dynamic_avoidance_module/include/behavior_path_dynamic_avoidance_module/scene.hpp
- planning/behavior_path_dynamic_avoidance_module/src/scene.cpp
- check if the lowpass filter to the lateral offset to avoid should be enabled or not depending on whether the reference path changes or not.
- Tuned the parameter when to start avoiding the front object whose direction is the same as the ego.
psim
Nothing
> feat(dynamic_avoidance): add a guard of LPF for reference path changed by avoidance/LC

- sensing/gnss_poser/README.md
- sensing/gnss_poser/config/gnss_poser.param.yaml
- sensing/gnss_poser/include/gnss_poser/gnss_poser_core.hpp
- sensing/gnss_poser/schema/gnss_poser.schema.json
- sensing/gnss_poser/src/gnss_poser_core.cpp
This PR resolves https://github.com/autowarefoundation/autoware.universe/issues/6108
* Removed `gnss_frame` which indicates antenna's frame_id from parameters.
* Changed to identify the antenna's frame_id by referencing `nav_sat_fix.header.frame_id`.
(Please note the `header.frame_id` in NavSatFix indicates the frame_id of the antenna, not the Earth or ellipsoid.  See also https://docs.ros.org/en/noetic/api/sensor_msgs/html/msg/NavSatFix.html)
[TIER IV INTERNAL ANNOUNCEMENT LINK](https://star4.slack.com/archives/C4P0NSMB5/p1705640076668249)
* https://github.com/autowarefoundation/sample_sensor_kit_launch/pull/88
* https://github.com/autowarefoundation/awf_reference_sensor_kit_launch/pull/8
* https://github.com/tier4/aip_launcher/pull/201
I have tested …
> feat(gnss_poser): use header.frame_id as gnss_frame

- planning/behavior_path_dynamic_avoidance_module/src/scene.cpp
It seems debug `cerr` is still remaining.
```
[component_container_mt-29] 0                                                                                                             
[component_container_mt-29] 0                                                                                                             
[component_container_mt-29] 0                                                                                                             
[component_container_mt-29] 0                                                                                                             
[component_container_mt-29] 0                                                                                                             
[component_container_mt-29] 0 …
```
> fix(dynamic_avoidance): remove cerr
