autowarefoundation/autoware_universe

- planning/behavior_path_planner/config/goal_planner/goal_planner.param.yaml
- planning/behavior_path_planner/docs/behavior_path_planner_goal_planner_design.md
this parameter was added in 
https://github.com/autowarefoundation/autoware.universe/pull/2667
to prevent path distortion by obstacle_avoidance_planner when footprint is close to drivable area.
before
but currently this distortion was fixed in obstacle_avoidance_planner, so set the parameter 0.0
tier4 internal slack
https://star4.slack.com/archives/C03QW0GU6P7/p1693896015165389
psim
https://evaluation.tier4.jp/evaluation/reports/d58d4ccd-e0c9-534a-89af-17ffeaa9c114?project_id=prd_jt
1648/1650 -> 1648/1650 …
> feat(goal_planner): set ignore_distance_from_lane_start 0.0

- planning/behavior_path_planner/include/behavior_path_planner/utils/start_planner/freespace_pull_out.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/start_planner/geometric_pull_out.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/start_planner/pull_out_planner_base.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/start_planner/shift_pull_out.hpp
- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
- planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
- planning/behavior_path_planner/src/utils/geometric_parallel_parking/geometric_parallel_parking.cpp
- planning/behavior_path_planner/src/utils/start_planner/freespace_pull_out.cpp
- planning/behavior_path_planner/src/utils/start_planner/geometric_pull_out.cpp
- planning/behavior_path_planner/src/utils/start_planner/shift_pull_out.cpp
> refactor(start/goal_planner): minor refactor like const and reference

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/start_planner/start_planner_module.hpp
- planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
fix start pose candidats when the ego is close to the lane end
before
after
psim
https://evaluation.tier4.jp/evaluation/reports/b5d4bb8b-12fd-5595-bdda-7d0b3011e0fc?project_id=prd_jt
none
none
> fix(start_planner): fix start pose candidats when the ego is close to the lane end

- planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
run start planner even if ego is out of lane
before
lane following
after
start planner
not start planner if completely out of lane
psim
https://evaluation.tier4.jp/evaluation/reports/3ae99ec3-73aa-56cd-bd1f-173fdbb2cd9a?project_id=prd_jt
none
none
> feat(start_planner): run start planner even if ego is out of lane

- perception/image_projection_based_fusion/include/image_projection_based_fusion/pointpainting_fusion/voxel_generator.hpp
- perception/image_projection_based_fusion/src/pointpainting_fusion/node.cpp
- perception/image_projection_based_fusion/src/pointpainting_fusion/voxel_generator.cpp
- Enable assigning multiple class to one point, in order to be consistent with the training settings.
- The value of each class is set as pow(2, class_index), e.g.  {"CAR": 1, "BICYCLE": 2, "PEDESTRIAN": 4}
- The "CLASS" field of a point is the sum of all the classes, e.g. if the projected point is inside the "CAR" roi and "PEDESTRIAN" roi at the same time, its "CLASS" is 5.
- The "CLASS“ value is decoded by voxel_generator into one-hot code, e.g 00000101, where each bit represents a class.
https://tier4.atlassian.net/wiki/spaces/CT/pages/2851864699/SP+2023-08-08+PointPainting+Sync
rosbag:https://drive.google.com/drive/folders/161wVB87jIu2E9CC9hRmaKwAAWjaDney_
The brightest points are assigned as pedestrian and car at the same time. …
> fix(image_projection_based_fusion): multi class of one point

- perception/map_based_prediction/README.md
- perception/map_based_prediction/package.xml
I change 2 points 
- set unit for all parameter
- explanation mae be wrong so switch
> docs(map_based_prediction): minor refactor for explanation of parameter

- planning/planning_debug_tools/scripts/trajectory_visualizer.py
Remove duplicated implementations to simplify the code.
run psim and visualize the trajectory.
```
ros2 run planning_debug_tools trajectory_visualizer.py -v 20
```
None
> refactor(trajectory_visualizer): remove duplicated implementation

- localization/ndt_scan_matcher/README.md
- localization/ndt_scan_matcher/config/ndt_scan_matcher.param.yaml
- localization/ndt_scan_matcher/include/ndt_scan_matcher/ndt_scan_matcher_core.hpp
- localization/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp
There have been cases where the localization fails due to significant delay in the LiDAR topic. To simplify future root cause investigation, the delay time of the LiDAR topic has been added to diagnostics. If the delay time is significant, it will transition to a WARN state and also output a message on the console.
merge with [autoware_launch](https://github.com/autowarefoundation/autoware_launch/pull/540)
- Logging simulator works, and `lidar_topic_delay_time_sec` has been added in rqt_runtime_monitor. 
If there is a delay in the LiDAR topic, it will transition to WARN state.
None
add a parameter in the ndt_scan_matcher node's  diag 
add a parameter in the ndt_scan_matcher.param.yaml
None …
> feat(ndt_scan_matcher): add diag lidar_topic_delay_time_sec

- planning/planning_debug_tools/scripts/perception_replayer/perception_replayer.py
- planning/planning_debug_tools/scripts/perception_replayer/perception_replayer_common.py
- planning/planning_debug_tools/scripts/perception_replayer/time_manager_widget.py
add initial pose publisher to perception replayer
https://github.com/autowarefoundation/autoware.universe/assets/39142679/ef54589d-74db-4b82-8502-a83b9c015745
psim
none
none
> feat(planning_debug_tools): add recorded ego pose publisher to perception replayer

- planning/behavior_path_planner/include/behavior_path_planner/data_manager.hpp
- planning/behavior_path_planner/src/utils/drivable_area_expansion/drivable_area_expansion.cpp
- planning/behavior_path_planner/test/test_turn_signal.cpp
- planning/behavior_velocity_out_of_lane_module/src/debug.cpp
- planning/behavior_velocity_out_of_lane_module/src/decisions.cpp
- planning/freespace_planner/package.xml
- planning/freespace_planner/src/freespace_planner/freespace_planner_node.cpp
- planning/freespace_planning_algorithms/src/abstract_algorithm.cpp
- planning/freespace_planning_algorithms/src/astar_search.cpp
- planning/mission_planner/src/lanelet2_plugins/default_planner.cpp
- planning/mission_planner/src/lanelet2_plugins/utility_functions.hpp
- planning/mission_planner/src/mission_planner/arrival_checker.cpp
- planning/route_handler/include/route_handler/route_handler.hpp
- planning/route_handler/package.xml
- planning/route_handler/src/route_handler.cpp
- planning/static_centerline_optimizer/include/static_centerline_optimizer/type_alias.hpp
> chore(build): remove tier4_autoware_utils.hpp/motion_utils.hpp from freespace/route_handler

- planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/common_structs.hpp
- planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/mpt_optimizer.hpp
- planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/node.hpp
- planning/obstacle_avoidance_planner/src/debug_marker.cpp
- planning/obstacle_avoidance_planner/src/mpt_optimizer.cpp
- planning/obstacle_avoidance_planner/src/node.cpp
- planning/obstacle_avoidance_planner/src/replan_checker.cpp
- planning/obstacle_avoidance_planner/src/utils/geometry_utils.cpp
- planning/obstacle_avoidance_planner/src/utils/trajectory_utils.cpp
- planning/obstacle_cruise_planner/include/obstacle_cruise_planner/common_structs.hpp
- planning/obstacle_cruise_planner/include/obstacle_cruise_planner/optimization_based_planner/optimization_based_planner.hpp
- planning/obstacle_cruise_planner/include/obstacle_cruise_planner/planner_interface.hpp
- planning/obstacle_cruise_planner/include/obstacle_cruise_planner/polygon_utils.hpp
- planning/obstacle_cruise_planner/include/obstacle_cruise_planner/utils.hpp
- planning/obstacle_cruise_planner/src/node.cpp
- planning/obstacle_cruise_planner/src/optimization_based_planner/optimization_based_planner.cpp
- planning/obstacle_cruise_planner/src/pid_based_planner/pid_based_planner.cpp
- planning/obstacle_cruise_planner/src/planner_interface.cpp
- planning/obstacle_cruise_planner/src/utils.cpp
- planning/obstacle_stop_planner/include/obstacle_stop_planner/adaptive_cruise_control.hpp
- planning/obstacle_stop_planner/include/obstacle_stop_planner/node.hpp
- planning/obstacle_stop_planner/include/obstacle_stop_planner/planner_utils.hpp
- planning/obstacle_stop_planner/src/adaptive_cruise_control.cpp
- planning/obstacle_stop_planner/src/debug_marker.cpp
- planning/obstacle_stop_planner/src/planner_utils.cpp
> chore(build): remove tier4_autoware_utils.hpp/motion_utils.hpp from obstacle_planning

- planning/static_centerline_optimizer/src/static_centerline_optimizer_node.cpp
https://github.com/orgs/autowarefoundation/discussions/3824
none.
none.
> fix(static_centerline_optimzier): fix build

- planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
> refactor(start_planner): refactor drivable lanes

- planning/obstacle_cruise_planner/config/obstacle_cruise_planner.param.yaml
- planning/obstacle_cruise_planner/include/obstacle_cruise_planner/common_structs.hpp
- planning/obstacle_cruise_planner/include/obstacle_cruise_planner/node.hpp
- planning/obstacle_cruise_planner/include/obstacle_cruise_planner/planner_interface.hpp
- planning/obstacle_cruise_planner/src/node.cpp
- planning/obstacle_cruise_planner/src/planner_interface.cpp
**No behavior change by default since this feature is disabled.**
When the obstacle stop feature runs on a curve, the distance from the ego to the object is too large which we feel a weird behavior.
This PR deals with this case by approaching the obstacle with the following algorithm.
before
after
psim
Nothing
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/co …
> feat(obstacle_cruise_planner): approching stop on curve

- planning/behavior_path_planner/src/utils/goal_planner/goal_searcher.cpp
> refactor(goal_planner): remove unused variables

- planning/behavior_path_planner/config/goal_planner/goal_planner.param.yaml
- planning/behavior_path_planner/include/behavior_path_planner/utils/goal_planner/goal_planner_parameters.hpp
- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
- planning/behavior_path_planner/src/scene_module/goal_planner/manager.cpp
- planning/behavior_path_planner/src/utils/goal_planner/goal_searcher.cpp
use only static objects in pull over lanes to path generation
dynamic objects are used in `safety_checker`
before
https://github.com/autowarefoundation/autoware.universe/assets/39142679/5b3c256e-9d57-456c-8042-816173246b1c
after
NOTE: `use_occupancy_grid: false`
(dymamic objects are still used for creating occupancy_grid_map.)
https://github.com/autowarefoundation/autoware.universe/assets/39142679/032ca553-4bae-4f0d-8f80-fcca260a625d
psim
2023/09/12 https://evaluation.tier4.jp/evaluation/reports/b7be79c5-3c42-523f-a2bc-19685d3cade7/?project_id=prd_jt
1664/1664
none
none
After all …
> feat(goal_planner): use only static objects in pull over lanes to path generation

- common/rtc_manager_rviz_plugin/src/rtc_manager_panel.cpp
- fix panel chattering.
- sort rtc statuses so that it can priotize and show waiting approval module status.
Psim
Nothing.
> fix(rtc_manager_panel): fix panel chattering

- planning/behavior_path_planner/config/goal_planner/goal_planner.param.yaml
- planning/behavior_path_planner/docs/behavior_path_planner_goal_planner_design.md
- planning/behavior_path_planner/include/behavior_path_planner/utils/goal_planner/goal_planner_parameters.hpp
- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
- planning/behavior_path_planner/src/scene_module/goal_planner/manager.cpp
- planning/behavior_path_planner/src/utils/goal_planner/goal_searcher.cpp
add options of occupancy grid map to use only for goal search not for path collision check
https://github.com/autowarefoundation/autoware.universe/assets/39142679/850755c2-6228-4bc9-bb9c-c01364ce7da5
psim
2023/09/12 https://evaluation.tier4.jp/evaluation/reports/e858cbab-6630-5862-9836-10f1db2f76f9/?project_id=prd_jt
none
none …
> feat(goal_planner): add options of occupancy grid map to use only for goal search

- perception/simple_object_merger/src/simple_object_merger_node/simple_object_merger_node.cpp
Fix timeout for simple_object_merger to use rosbag.
Test by rosbag
None
> fix(simple_object_merger): fix timeout

- planning/obstacle_stop_planner/src/adaptive_cruise_control.cpp
I have corrected the index of the maximum speed embedding by adaptive cruise control, addressing the issue of fluctuating target acceleration.
Before
After
Despite the correction, the acceleration still exhibits oscillations, but the amplitude has been improved to approximately one-third of the original. 
none
he issue of fluctuating target acceleration by adaptive_cruise control will be improved
[pull …
> fix(adaptive_cruise_planner): prevent large vibration of acceleration command

- planning/planning_debug_tools/scripts/perception_replayer/perception_replayer.py
- planning/planning_debug_tools/scripts/perception_replayer/perception_replayer_common.py
- planning/planning_debug_tools/scripts/perception_replayer/perception_reproducer.py
Make the reproducer to load only rosbag file.
run it with psim
None
> chore(perception_reproducer): load only rosbag file

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/dynamic_avoidance/dynamic_avoidance_module.hpp
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/avoidance_module_data.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/goal_planner/goal_planner_parameters.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/lane_change_module_data.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/lane_following/module_data.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/path_safety_checker/path_safety_checker_parameters.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/start_planner/start_planner_parameters.hpp
this is not all but set initial value.
include https://github.com/autowarefoundation/autoware.universe/pull/5001
2023/09/16 https://evaluation.tier4.jp/evaluation/reports/e90b10ff-c4f4-5c66-838a-3d267efd0c77/?project_id=prd_jt
none
none
> fix(behaivor_path_planner): fix uninitialized variables

- common/motion_utils/include/motion_utils/marker/marker_helper.hpp
- common/motion_utils/include/motion_utils/marker/virtual_wall_marker_creator.hpp
- common/motion_utils/src/marker/marker_helper.cpp
- common/motion_utils/src/marker/virtual_wall_marker_creator.cpp
- planning/obstacle_cruise_planner/src/planner_interface.cpp
add sign longitudinal offset.
after
psim
none
none
> fix(obstacle_cruise_planner): fix backward virtual wall

- common/motion_utils/include/motion_utils/marker/marker_helper.hpp
- common/motion_utils/include/motion_utils/marker/virtual_wall_marker_creator.hpp
- common/motion_utils/src/marker/marker_helper.cpp
- common/motion_utils/src/marker/virtual_wall_marker_creator.cpp
- planning/obstacle_cruise_planner/src/node.cpp
- planning/obstacle_cruise_planner/src/planner_interface.cpp
fix stop against objects after backward trajectory terminal
after
psim
https://evaluation.tier4.jp/evaluation/reports/b14a1114-7b89-5567-ab7b-95ebf2480565?project_id=prd_jt
1668/1668
none
none
> fix(obstacle_cruise_planner): fix stop against objects after backward trajectory terminal

- planning/behavior_path_planner/src/utils/geometric_parallel_parking/geometric_parallel_parking.cpp
Add empty check of ```road_center_line_path``` before accessing it.
I confirmed that the behavior_path_planner no longer crashes due to this pull request when the goal is set as shown in this image 
Without merging the PR:
none
none
behavior_path_planner no longer crashes due to invalid access for  ```road_center_line_path.front()```  …
> fix(pull_out): add empty check

- planning/behavior_path_planner/src/utils/utils.cpp
I am not sure the details, but werror seems to happen after https://github.com/autowarefoundation/autoware.universe/pull/5008 in my environment.
```
../../src/autoware/universe/planning/behavior_path_planner/src/utils/utils.cpp:2517:44: error: ‘front_segment_idx.boost::optional<long unsigned int>::<unnamed>.boost::optional_detail::tc_optional_base<long unsigned int>::m_storage’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
2517 |   for (size_t i = *rear_segment_idx + 1; i < *front_segment_idx; i++) {
|                                          ~~^~~~~~~~~~~~~~~~~~~~
../../src/autoware/universe/planning/behavior_path_planner/src/utils/utils.cpp:2517:39: error: ‘rear_segment_idx.boost::optional<long unsigned …
```
> fix(behavior_path_planner): fix Werror=maybe-uninitialized

- localization/localization_error_monitor/package.xml
- sensing/gnss_poser/package.xml
Add maintainer
Not applicable
Not applicable
> chore: add maintainer in localization_error_monitor and gnss_poser

- localization/ndt_scan_matcher/src/pose_array_interpolator.cpp
Fix code miss.
LSim works well.
> fix(ndt_scan_matcher): pose_array_interpolator

- perception/lidar_centerpoint/CMakeLists.txt
See #3137
Depends on https://github.com/autowarefoundation/autoware_common/pull/164
> build(lidar_centerpoint): remove download logic from CMake

- planning/planning_validator/package.xml
> chore(planning_validator): add maintainer

- control/mpc_lateral_controller/CMakeLists.txt
- control/mpc_lateral_controller/include/mpc_lateral_controller/mpc.hpp
- control/mpc_lateral_controller/include/mpc_lateral_controller/mpc_lateral_controller.hpp
- control/mpc_lateral_controller/include/mpc_lateral_controller/mpc_utils.hpp
- control/mpc_lateral_controller/src/mpc.cpp
- control/mpc_lateral_controller/src/mpc_lateral_controller.cpp
- control/mpc_lateral_controller/src/mpc_utils.cpp
- control/mpc_lateral_controller/test/test_mpc.cpp
Without the PR, the relative time vector around ego changes over time, resulting in pretty bad control.
https://tier4.atlassian.net/browse/RT0-28891?focusedCommentId=137957 (Videos in internal link)
This PR fixes the issue by
- 1. make dynamicSmoothingVelocity use the segment index of ego pose which may be the previous of nearest index.
- 2. make resampleMPCTrajectoryByDistance resample the ego pose projected to the trajectory
- This makes a major improvement on the issue.
- 3. make calcNearestPoseInterp stable over time by using sequential points not by using skipping two points
The implementation (with this PR and even without this PR) looks hard to read and maintain. Need to be refactored.
psim
Stabler steering control …
> fix(mpc): precise resampling around ego for stabling control

- sensing/pointcloud_preprocessor/src/concatenate_data/concatenate_and_time_sync_nodelet.cpp
Fixes #5010.
Tested with two Ousters, for several weeks (100+ hours) it never failed. Before fix it failed time after time.
> fix(concatenate_data): replace data empty check to avoid nullptr

- planning/behavior_path_planner/src/utils/path_safety_checker/objects_filtering.cpp
Refactor and optimize `objects_filtering.cpp` in behavior path planner. Simplify the logic while removing uninitialized variables.
> refactor(behavior_path_planner): uninitialized values in createPredictedPath

- localization/ndt_scan_matcher/README.md
Added description about parameter `ndt_base_frame`.
> docs(ndt_scan_matcher): update readme

- common/tier4_target_object_type_rviz_plugin/package.xml
Code uses OpenCV but it's not declared in `package.xml`
> build(tier4_target_object_type_rviz_plugin): add missing cv_bridge dependency

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp
- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
do not finish goal planner.
the behavior does not change because the previous code has mistakes.
( `hasFinishedGoalPlanner` use not original goal but `isOnModifiedGoal()` )
psim
none
none
> refactor(goal_planner): do not finish goal planner

- planning/behavior_path_planner/include/behavior_path_planner/utils/geometric_parallel_parking/geometric_parallel_parking.hpp
remove unused params and initialize variables
> chore(geometric_parallel_parking): remove unused params and initialize variables

- planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
- planning/behavior_path_planner/src/utils/utils.cpp
skip make monotonic and combine for backward driving path to fix wrong path cutting.
before
after
https://tier4.atlassian.net/browse/RT1-3916
psim
2023/09/24 https://evaluation.tier4.jp/evaluation/reports/c8442761-7ea2-5929-9634-f5be44ee741e/?project_id=prd_jt
none
none
none
> fix(start_planner): fix backward drving path cutting

- planning/planning_debug_tools/scripts/perception_replayer/perception_replayer.py
- planning/planning_debug_tools/scripts/perception_replayer/perception_replayer_common.py
- planning/planning_debug_tools/scripts/perception_replayer/perception_reproducer.py
- planning/planning_debug_tools/scripts/perception_replayer/utils.py
improve computational efficiency.
Test: 
Computational time is reduced from 84ms -> 8ms
- Use numpy for ego nearest time search: 40ms -> 0.6ms
- Use binary search instead of linear search for rosbag objects: 2.5ms -> 0.02ms
- Use pickle library instead of deepcopy: 22ms -> 5ms
- Move the kill-perception command in a low-frequency timer: 10ms -> 0.3ms (on average)
Also these features are added:
- verbose option and stopwatch code.
- publish ego pose recorded in rosbag
Before
```
Time for find_nearest_ego_odom_by_observation: 45.78 ms
Time for find_topics_by_timestamp: 2.59 ms
Time for message deepcopy: 22.04 ms
Time for transform and publish: 2.89 ms
Time for total on_timer: 84.80 ms
```
After 
```
Time for find_nearest_ego_odom_by_observation: 0.60 ms
Time for find_topics_by_timestamp: …
```
> refactor(perception_reproducer): improve computational efficiency

- planning/behavior_velocity_intersection_module/config/intersection.param.yaml
- planning/behavior_velocity_intersection_module/src/manager.cpp
- planning/behavior_velocity_intersection_module/src/scene_merge_from_private_road.cpp
- planning/behavior_velocity_intersection_module/src/scene_merge_from_private_road.hpp
This PR made stop_distance_threshold in merge_from_private tunable.
Unit test
Nothing
> feat(merge_from_private): make stop_distance_threshold tunable

- control/pid_longitudinal_controller/include/pid_longitudinal_controller/pid_longitudinal_controller.hpp
- control/pid_longitudinal_controller/src/pid_longitudinal_controller.cpp
Resolves https://github.com/autowarefoundation/autoware.universe/issues/4267
psim
Nothing
> fix(pid_longitudinal_controller): fix the sign of velocity

- planning/behavior_path_planner/config/lane_change/lane_change.param.yaml
- planning/behavior_path_planner/docs/behavior_path_planner_lane_change_design.md
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/normal.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/lane_change_module_data.hpp
- planning/behavior_path_planner/src/scene_module/lane_change/manager.cpp
- planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
To avoid stucking, it enables lane change in crosswalk/intersection.
If the ego vehicle stops more than `stuck_detection.stop_time` seconds, it is regarded as a stuck.
If the ego vehicle velocity is smaller than `stuck_detection.velocity`, it is regarded as stopping.
[TIER IV INTERNAL TEST](https://evaluation.tier4.jp/evaluation/reports/8ffbfee4-bc6d-5da4-a5e5-6507c90a3101?project_id=prd_jt)
Tested in planning simulator
https://github.com/autowarefoundation/autoware.universe/assets/10190493/7ded4102-54fa-4e11-9c50-3bbf28227781
Parameters are added. `stuck_detection.velocity` and `stuck_detection.stop_time`.
Enable lane change in crosswalk/intersection if ego vehicle gets stuck …
> feat(lane_change): enable lane change in crosswalk/intersection if ego vehicle gets stuck

- planning/behavior_path_planner/config/dynamic_avoidance/dynamic_avoidance.param.yaml
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/dynamic_avoidance/dynamic_avoidance_module.hpp
- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp
- planning/behavior_path_planner/src/scene_module/dynamic_avoidance/manager.cpp
Added a max obstacle velocity parameter for dynamic_avoidance
unit test
psim
> feat(dynamic_avoidance): add max obstacle vel

- planning/behavior_path_planner/include/behavior_path_planner/utils/goal_planner/goal_searcher.hpp
- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
- planning/behavior_path_planner/src/utils/goal_planner/goal_searcher.cpp
extract target objects at fist
none
psim
2023/09/26 https://evaluation.tier4.jp/evaluation/reports/f88e9d63-7163-5b72-a73c-ef30a5f8e013/?project_id=prd_jt
none
none
> perf(goal_planner): speed up goal candidates update

- planning/behavior_path_planner/docs/behavior_path_planner_start_planner_design.md
> docs(start_planner): add freespace pull out docs

- planning/behavior_path_planner/README.md
- planning/behavior_path_planner/docs/behavior_path_planner_goal_planner_design.md
move smooth goal connection to goal planner docs
> docs(goal_planner): move smooth goal connection to goal planner docs

- perception/traffic_light_classifier/README.md
- perception/traffic_light_classifier/launch/traffic_light_classifier.launch.xml
As https://github.com/autowarefoundation/autoware/pull/3375 was merged to Autoware.universe. It is possible to use artifacts downloaded there.
https://github.com/autowarefoundation/autoware.universe/pull/3144 was merged and old path to model file is outdated. 
It also updates classifier_model_path and classifier_label_path args.
See https://github.com/autowarefoundation/autoware.universe/issues/3137 …
> fix(traffic_light_classifier): add arg data_path, update model path

- planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
Add missing debug info.
Tested on planning simulator.
> fix(avoidance): add debug info

- common/component_interface_utils/CMakeLists.txt
- common/component_interface_utils/package.xml
- common/component_interface_utils/test/test_component_interface_utils.cpp
add common interface utils test
Add test in the common/interface_utils
There is no effect on the function.
> feat: add common interface utils test

- perception/lidar_apollo_segmentation_tvm/src/lidar_apollo_segmentation_tvm.cpp
- perception/multi_object_tracker/models.md
- perception/traffic_light_classifier/README.md
Fix typo and add ignore cspells
No effects.
> chore: fix spell-check errors in perception packages

- perception/heatmap_visualizer/CMakeLists.txt
- perception/heatmap_visualizer/README.md
- perception/heatmap_visualizer/config/heatmap_visualizer.param.yaml
- perception/heatmap_visualizer/launch/heatmap_visualizer.launch.xml
- perception/heatmap_visualizer/schema/heatmap_visualizer.schema.json
- perception/heatmap_visualizer/src/heatmap_visualizer_node.cpp
- Add ROS node configuration with JSON Schema as discussed in https://github.com/orgs/autowarefoundation/discussions/3371
- Remove default parameter specified in `declare_parameter()`
> refactor(heatmap_visualizer): add JSON Schema and remove default value definition

- planning/behavior_velocity_blind_spot_module/src/debug.cpp
Fix undefined reference crash
Psim works
> fix(blind_spot): fix runtime crash

- common/autoware_auto_tf2/include/autoware_auto_tf2/tf2_autoware_auto_msgs.hpp
fix(autoware_auto_tf2):  build fail for duplicated tf2 geometry msgs
by build 
> fix(autoware_auto_tf2):  build fail for duplicated tf2 geometry msgs

- map/map_projection_loader/README.md
The sample config in the README is wrong. I have corrected it.
Only readme is changed.
Only readme is changed.
> fix(map_projection_loader): fix sample config parameter in readme

- common/kalman_filter/CMakeLists.txt
- common/kalman_filter/package.xml
- common/kalman_filter/test/test_kalman_filter.cpp
- common/kalman_filter/test/test_time_delay_kalman_filter.cpp
add kalman_filter test
unit test.
Add test in  `common/kalman_filter/test/`.
There is no effect on the function.
> feat(kalman_filter): add gtest

- planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
Update target lane information if valid path not found
> fix(lane_change): update target lane if valid path not found

- map/map_height_fitter/package.xml
- map/map_loader/CMakeLists.txt
- map/map_loader/package.xml
- map/map_projection_loader/package.xml
- map/util/lanelet2_map_preprocessor/CMakeLists.txt
- map/util/lanelet2_map_preprocessor/package.xml
This PR derived from https://github.com/autowarefoundation/autoware.universe/pull/3606
result of unused.sh (https://github.com/autowarefoundation/autoware/issues/3468)
```
--- Checking src/universe/autoware.universe/map/map_projection_loader/package.xml ---
rclcpp_components seems not to be used
--- Checking src/universe/autoware.universe/map/util/lanelet2_map_preprocessor/package.xml ---
pcl_ros seems not to be used
--- Checking src/universe/autoware.universe/map/map_loader/package.xml ---
pcl_ros seems not to be used
std_msgs seems not to be used
tf2_geometry_msgs seems not to be used
tf2_ros seems not to be used
tier4_autoware_utils seems not to be used
--- Checking src/universe/autoware.universe/map/map_height_fitter/package.xml ---
tf2 seems not to be used
--- Checking …
```
> refactor(map_packages): remove unused depend in pakcages.xml files

- planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
Originally, if there was a stationary vehicle in the target lane, the ego stopped without taking a lane change margin. However, it should take the margin in some cases, like in the video.
I modified the condition for not taking a lane change margin from "when there's a stationary vehicle in the target lane" to "when there's a stationary vehicle in the target lane within the lane change zone".
[Screencast from 2023年10月13日 00時44分25秒.webm](https://github.com/autowarefoundation/autoware.universe/assets/21360593/848fffe5-623c-410f-a454-46e85f0fc57f)
None
Run psim
It is easy to review commits one by one.
None
improve lane change performance
The PR author …
> fix(lane_change): update target lane obj block condition

- simulator/simple_planning_simulator/src/simple_planning_simulator/simple_planning_simulator_core.cpp
Publish lateral acceleration.
Run psim
Lateral acceleration is calculated appropriately in sim.
> feat(simple_planning_sim): publish lateral acceleration

- planning/behavior_velocity_intersection_module/config/intersection.param.yaml
- planning/behavior_velocity_intersection_module/src/debug.cpp
- planning/behavior_velocity_intersection_module/src/manager.cpp
- planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
- planning/behavior_velocity_intersection_module/src/scene_intersection.hpp
- planning/behavior_velocity_intersection_module/src/util.cpp
- planning/behavior_velocity_intersection_module/src/util.hpp
- planning/behavior_velocity_intersection_module/src/util_type.hpp
When entering the merging lane, if there is not enough space, the ego should stop before entering instead of not entering by force.
This PR adds a feature to insert a stop point in this case named YieldStuckStop.
**before**
Even if there is **not enough space** to enter the merging lane, no stop point is inserted.
Therefore, the ego will enter by force and make the vehicle uncomfortable, or the worst case scenario, the ego will collide with the vehicle.
**after**
If there is **not enough space** to enter the merging lane, the intersection stop is inserted.
If there is enough space, no stop point is inserted.
- psim
- scenario test: https://evaluation.tier4.jp/evaluation/reports/74d3c623-5ce8-57be-a6e3-a5ea018966e0?project_id=prd_jt
yield stuck detection when the ego enters the merging …
> feat(intersection): new feature of yield stuck detection

- planning/behavior_path_planner/config/lane_change/lane_change.param.yaml
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/base_class.hpp
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/normal.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/lane_change_module_data.hpp
- planning/behavior_path_planner/src/scene_module/lane_change/manager.cpp
- planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
add rss paramas for stuck
If path is not found with normal RSS params and ego is stuck, use the RSS for stuck for path generaetion
psim
evaluator_description: feat/rss_for_stuck
2023/10/13 https://evaluation.tier4.jp/evaluation/reports/0caf4a17-cee0-5de3-9b2a-c84a1f1340b0/?project_id=prd_jt
none
none
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing …
> feat(lane_change): add rss paramas for stuck

- perception/multi_object_tracker/include/multi_object_tracker/tracker/model/bicycle_tracker.hpp
- perception/multi_object_tracker/include/multi_object_tracker/tracker/model/big_vehicle_tracker.hpp
- perception/multi_object_tracker/include/multi_object_tracker/tracker/model/normal_vehicle_tracker.hpp
- perception/multi_object_tracker/include/multi_object_tracker/tracker/model/pedestrian_tracker.hpp
- perception/multi_object_tracker/src/tracker/model/bicycle_tracker.cpp
- perception/multi_object_tracker/src/tracker/model/big_vehicle_tracker.cpp
- perception/multi_object_tracker/src/tracker/model/normal_vehicle_tracker.cpp
- perception/multi_object_tracker/src/tracker/model/pedestrian_tracker.cpp
This is just test development for prediction.
I added acc estimation to any classification tracker except `Unknown` object.
> feature(multi_object_tracker): add acc estimation model

- planning/behavior_path_planner/src/utils/drivable_area_expansion/drivable_area_expansion.cpp
Hotfix to fix a bug that can cause out of bound crashes.
Psim.
Should prevent out of bound crashes
> fix(drivable_area_expansion): correct bound limit check

- planning/behavior_velocity_intersection_module/src/util.cpp
the variable `last_intersection_stop_line_candidate_idx` in `calcIntersectionPassingTime` is the index of original path, but this index was used in the operation to interpolated path (the smoothed path).
I fixed this by finding the corresponding point on the `smoothed_reference_path`.
https://tier4.atlassian.net/browse/RT1-4118
Psim
none.
none. …
> fix(intersection): fix misuse of original path index to interpolated path

- planning/planning_debug_tools/scripts/perception_replayer/perception_replayer_common.py
stop of publishing objects causes system error so continue publishing objects even if out of recorded timestamp
```
[system_error_monitor-16] [ERROR 1697607651.001223091] [system_error_monitor /autoware/perception/node_alive_monitoring/topic_status/topic_state_monitor_object_recognition_objects: perception_topic_status]: [Single Point Fault]: Error (logThrottledNamed() at /home/kosuke55/pilot-auto.x2/src/autoware/universe/system/system_error_monitor/src/system_error_monitor_core.cpp:54)
```
before
after
psim …
> fix(perception_reproducer): publish objects even if out of recorded timestamp

- planning/planning_debug_tools/scripts/perception_replayer/perception_replayer_common.py
> perf(perception_reproducer): improve ego pose extraction

- planning/behavior_path_planner/src/utils/path_safety_checker/safety_check.cpp
> fix(lane_change): fix debug marker

- planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp
- planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
to prevent chattering disable cancel 
- check ego pose
- check also in PreparePhase
before
https://github.com/autowarefoundation/autoware.universe/assets/39142679/4330407c-ba36-45d1-af0b-9d807917aed1
after
https://github.com/autowarefoundation/autoware.universe/assets/39142679/6ad31237-48be-445c-96e0-c4d6a73e90b5
psim
evaluator_description: feat/lc_cancel
2023/10/18 https://evaluation.tier4.jp/evaluation/reports/6c2db15d-f12c-5000-ba55-974c213216e6/?project_id=prd_jt
none
none
none
[contribution …
> feat(lane_change): disable cancel when ego is out of current lanes

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/goal_planner/util.hpp
- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
- planning/behavior_path_planner/src/utils/goal_planner/util.cpp
mutex lock for all getter and setter of status
psim
https://evaluation.tier4.jp/evaluation/reports/fa995602-0947-5708-99e6-ee35e89c868e?project_id=prd_jt
none
none
> fix(goal_planner): mutex lock for all getter and setter of status

- sensing/pointcloud_preprocessor/src/crop_box_filter/crop_box_filter_nodelet.cpp
fixes #5252
@beginningfan
None
> perf(pointcloud_preprocessor): move print out of hot loop

- planning/behavior_velocity_crosswalk_module/package.xml
add maintainer for behavior_velocity_crosswalk_module
> chore(behavior_velocity_crosswalk_module): add maintainer

- common/motion_utils/include/motion_utils/trajectory/trajectory.hpp
faster removeOverlapPoints
unit test
nothing
> perf(motion_utils): faster removeOverlapPoints

- planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
https://github.com/autowarefoundation/autoware.universe/pull/5372#pullrequestreview-1691749058
> refactor(start_planner): guard for invalid lane id

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp
- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
fixed goal pushing memory leak.
psim
none
none
> fix(goal_planner): fixed goal memory leak

- planning/planning_debug_tools/scripts/processing_time_checker.py
- add some options
-  windows_size to average
- bar_scale to enrich display
- Search topics every 1 second for missing topics
None
Psim
None
None
None
> chore(processing_time_checker): update for windows size and rich display

- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
fix hasEnoughDistance
evaluator_description: fix/hasEnoughDistance
2023/10/25 https://evaluation.tier4.jp/evaluation/reports/d9618f16-e014-5715-bb46-713321e029df/?project_id=prd_jt
> fix(goal_planner): fix hasEnoughDistance

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp
- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
https://github.com/autowarefoundation/autoware.universe/pull/5371  again
psim
evaluator_description: refactor/goal_planner_state
2023/10/26 https://evaluation.tier4.jp/evaluation/reports/22db895d-99f4-5e82-87cb-1ab63ad1e3a7/?project_id=prd_jt
evaluator_description: refactor/goal_planner_state
2023/10/26 https://evaluation.tier4.jp/evaluation/reports/2af9f34f-9383-5086-b85a-e5326f35df7d/?project_id=prd_jt
https://evaluation.tier4.jp/evaluation/reports/7cc42693-9c46-57f4-a15d-a8974fd10021?project_id=prd_jt
1665/1667
none
none …
> refactor(goal_planner): rebuild state transition (#5371)" (#5399)" 

- common/tier4_logging_level_configure_rviz_plugin/README.md
> docs(logger_level_reconfigure): update readme

- map/map_loader/README.md
Update readme for users who are using large maps
Not applicable
Not applicable
> chore(map_loader): update readme

- .github/sync-files.yaml
Related PRs (reverse chronological order):
- https://github.com/autowarefoundation/autoware.universe/pull/5216/files/1b94ac5a52ccb35b965144cf0ed074b3804dd5e8#r1380270743
- https://github.com/autowarefoundation/autoware.universe/pull/5213
- https://github.com/autowarefoundation/autoware.universe/pull/4656
- https://github.com/autowarefoundation/autoware.universe/pull/4372 …
> ci(sync-files): add mkdocs_macros module

- .github/labeler.yaml
The pr-labeler action auto-labels the PRs in this repository by the folder names.
This PR, updates the label names to conform:
For more usage info on pr-labeler action: https://github.com/actions/labeler#common-examples
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/c …
> ci(pr-labeler): update the labeler.yaml to include "component:"

- .github/workflows/openai-pr-reviewer.yaml
> ci(openai-pr-reviewer): update the bot label

- .github/workflows/build-and-test-differential.yaml
> ci(build-and-test-differential): update the required tag

- common/tier4_logging_level_configure_rviz_plugin/config/logger_config.yaml
- common/tier4_logging_level_configure_rviz_plugin/include/tier4_logging_level_configure_rviz_plugin/logging_level_configure.hpp
- common/tier4_logging_level_configure_rviz_plugin/src/logging_level_configure.cpp
support button grouping
run psim
None
> refactor(logging_level_configure_plugin): support button grouping

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_interface.hpp
> refactor(behavior_path_planner): add const to interface methods

- launch/tier4_localization_launch/launch/pose_twist_estimator/eagleye/eagleye_rt.launch.xml
- launch/tier4_localization_launch/launch/pose_twist_estimator/eagleye/geo_pose_converter.launch.xml
- launch/tier4_localization_launch/package.xml
MUST BE MERGED WITH https://github.com/MapIV/eagleye/pull/312
[INTERNAL JIRA LINK](https://tier4.atlassian.net/browse/RT1-3575)
See https://github.com/MapIV/eagleye/pull/312
No effect expected
> feat(eagleye): split fix2pose

- planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp
small refactoring to declutter `updateState` in lane change module.
> refactor(lane_change): update state log

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/base_class.hpp
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/normal.hpp
- planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp
- planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
Before this change, if the abort condition is satisfied, it outputs lane change abort path that is cut at the terminal point of current lane with lane change buffer.
In this change, it inserts the stop point in the abort path to reserve lane change buffer instead of cutting.
[TIER IV INTERNAL TEST](https://evaluation.tier4.jp/evaluation/reports/bf8709a6-a66c-57dc-a31d-e9ed0529b637?project_id=prd_jt)
Planning Simulator
Before:
[Screencast_before](https://github.com/autowarefoundation/autoware.universe/assets/10190493/db87c637-f325-408f-aa3a-9037108c8a63)
After:
[Screencast_after](https://github.com/autowarefoundation/autoware.universe/assets/10190493/49380782-ecb1-46d6-b0e1-733609b3c546) …
> fix(lane_change): do not cut abort path

- planning/behavior_velocity_intersection_module/src/util.cpp
replace all `findNearestIndex` with `findFirstNearestIndexWithSoftConstraints`.
https://tier4.atlassian.net/browse/RT1-3639
evaluator: https://evaluation.tier4.jp/evaluation/reports/0902d585-9f82-51b2-a2fd-80079b374b8f?project_id=prd_jt
none.
none.
> fix(intersection): replace with findFirstNearestIndexWithSoftConstraints

- planning/behavior_velocity_intersection_module/src/util.cpp
additional fix for https://github.com/autowarefoundation/autoware.universe/pull/5507
In https://github.com/autowarefoundation/autoware.universe/pull/5507, only the interval between each resampled points were checked, so no points were accumulated actually. I fixed this to save previous resample point.
The orange polygon contains only beginning/end of the intersection part of the path
The orange polygon is normal
none.
none. …
> fix(intersection): fix wrong resample process

- planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
same type of chenge with https://github.com/autowarefoundation/autoware.universe/pull/5525
psim
Nothin
> refactor(start_planner): support new interface

- localization/landmark_based_localizer/ar_tag_based_localizer/package.xml
- localization/landmark_based_localizer/ar_tag_based_localizer/src/ar_tag_based_localizer.cpp
- localization/landmark_based_localizer/ar_tag_based_localizer/src/ar_tag_based_localizer.hpp
Refactoed `ar_tag_based_localizer`
* Simplified the Pose calculation code by using the `localization_util` package
* Reduced redundant type names using type aliases
It has been confirmed that `ar_tag_based_localizer` works with the same performance as before.
There is no effect on system behavior.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pu …
> refactor(ar_tag_based_localizer): refactor `ar_tag_based_localizer`

- control/trajectory_follower_node/include/trajectory_follower_node/controller_node.hpp
- control/trajectory_follower_node/src/controller_node.cpp
Publish processing time from trajectory follower.
run psim
None
> feat(controller): publish processing time

- planning/behavior_velocity_intersection_module/README.md
- planning/behavior_velocity_intersection_module/docs/data-structure.drawio.svg
- planning/behavior_velocity_intersection_module/src/manager.cpp
- planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
- planning/behavior_velocity_intersection_module/src/scene_merge_from_private_road.cpp
- planning/behavior_velocity_intersection_module/src/util.cpp
- planning/behavior_velocity_intersection_module/src/util.hpp
- planning/behavior_velocity_intersection_module/src/util_type.hpp
The pass judge line is designed to be the boundary position of collision checking. If ego did not detect collision with upcoming vehicles at t1 and then suddenly detected at t2, ego speed maybe too large to safely stop without any overshoot into the upcoming lane. Right now if ego vehicle passed the pass judge position it will indecisively drive without collision checking.
In this PR I organized this position:
- if occlusion detection is disabled, use the default pass judge line position for all cases
- if occlusion detection is enabled and:
- if there are traffic lights, use the `occlusion_peeking_limit_line` as the pass judge line in order to continue peeking while occlusion is detected.
- I considered using the `default_pass_judge_line` when occlusion is not detected, but …
> feat(intersection): use the centerline position of first attention area if there is no traffic light

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/goal_planner/pull_over_planner_base.hpp
- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
update status in one function and reduce variables
psim
https://evaluation.tier4.jp/evaluation/reports/f4fbf067-1dd4-5159-b0ae-f963941582be?project_id=prd_jt
none
none
none
> refactor(goal_planner): add updateStatus and reduce variables 

- .github/labeler.yaml
Related issue:
This label was overlooked, now fixing.
> ci(labeler): rename simulator to simulation

- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
> fix(goal_planner): fix detection_polygons visualiztion

- launch/tier4_perception_launch/package.xml
Add dependency of a new package in tier4_perception_launch.
Not applicable
Not applicable
> build(tier4_perception_launch): add tracking_object_merger

- planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp
- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
- add prev_data_ insted of status_
- refactor goal_seach process
before this PR merge
- refactor(goal_planner): add updateStatus and reduce variables  #5546
- https://github.com/autowarefoundation/autoware.universe/pull/5554- 
https://github.com/autowarefoundation/autoware.universe/pull/5559
psim
evaluator_description: refactor/goal_planner_prev_data
2023/11/13 https://evaluation.tier4.jp/evaluation/reports/c9206d7f-785d-5a0d-aa94-fd85c9e5103b/?project_id=prd_jt
evaluator_description: refactor/goal_planner_prev_data
2023/11/13 https://evaluation.tier4.jp/evaluation/reports/d7f5a53f-72dd-5c2e-af64-1520c7ecd73c/?project_id=prd_jt
evaluator_description: refactor/goal_planner_prev_data
2023/11/16 https://evaluation.tier4.jp/evaluation/reports/dc4f98c1-4c6c-5c05-abe0-782e224d23ef/?project_id=pr …
> refactor(goal_planner): add prev_data instead of status 

- common/autoware_auto_tf2/include/autoware_auto_tf2/tf2_autoware_auto_msgs.hpp
- common/tier4_screen_capture_rviz_plugin/src/screen_capture_panel.cpp
fix: setformat date
eg.)
`cap- 2023-11-20-11-27-56.mp4.mp4` to `cap-2023-11-20-11-27-56.mp4`
by capture rviz plugin
> fix(tier4 sceen capture panel): fix setFormatDate

- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
fix https://github.com/autowarefoundation/autoware.universe/pull/5621 
https://evaluation.tier4.jp/evaluation/reports/7ef36218-083f-58a2-bb51-f993325f0b3e?project_id=prd_jt
> fix(goal_planner): fix prevent auto approval for unsafe path #5621

- planning/behavior_path_planner/include/behavior_path_planner/marker_utils/utils.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/path_safety_checker/safety_check.hpp
- planning/behavior_path_planner/src/marker_utils/utils.cpp
- planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
- planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
- planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
- planning/behavior_path_planner/src/utils/lane_change/utils.cpp
- planning/behavior_path_planner/src/utils/path_safety_checker/safety_check.cpp
just move function 
separeted from https://github.com/autowarefoundation/autoware.universe/pull/5646
build
none
none
> refactor(behavior_path_planner): move createObjectDebug to safety check

- planning/behavior_path_planner/config/goal_planner/goal_planner.param.yaml
- planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/path_safety_checker/path_safety_checker_parameters.hpp
- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
- planning/behavior_path_planner/src/scene_module/goal_planner/manager.cpp
add time hysteresis to keep unsafe
```
/*　　
*　　                    ==== is_safe
*　　                    ---- current_is_safe
*　　  is_safe
*　　   |
*　　   |                   time
*　　 1 +--+    +---+       +---=========   +--+
*　　   |  |    |   |       |           |   |  |
*　　   |  |    |   |       |           |   |  |
*　　   |  |    |   |       |           |   |  |
*　　   |  |    |   |       |           |   |  |
*　　 0 =========================-------==========-- t
*/
```
separated from https://github.com/autowarefoundation/autoware.universe/pull/5646
evaluator_description: feat/keep_unsafe
2023/11/24 https://evaluation.tier4.jp/evaluation/reports/c7d74b6c-30af-5d48-9b09-aa0ff6bc31e5/?project_id=prd_jt
none
none
The PR …
> feat(goal_planner): add time hysteresis to keep unsafe

- system/velodyne_monitor/schema/velodyne_monitor.json
- system/velodyne_monitor/src/velodyne_monitor.cpp
mplement the ROS Node configuration layout described in https://github.com/orgs/autowarefoundation/discussions/3371 for the system_velodyne package.
1. Remove the default value from the source code in order to ensure all parameter values are passed from the parameter files.
2. Create the schema …
> refactor(system-velodyne-monitor): rework parameters

- common/tier4_logging_level_configure_rviz_plugin/config/logger_config.yaml
Update the config file in logging_level_configure to show a button for the tier4_autoware_utils
run psim
None
> feat(logging_level_configure_rviz_plugin): add autoware_util logger button

- planning/behavior_path_planner/include/behavior_path_planner/marker_utils/utils.hpp
- planning/behavior_path_planner/include/behavior_path_planner/utils/path_safety_checker/safety_check.hpp
- planning/behavior_path_planner/src/marker_utils/utils.cpp
- planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
- planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
- planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
- planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
- planning/behavior_path_planner/src/utils/lane_change/utils.cpp
- planning/behavior_path_planner/src/utils/path_safety_checker/safety_check.cpp
…
just move function
separeted from https://github.com/autowarefoundation/autoware.universe/pull/5646
> refactor(behavior_path_planner): move updateCollisionCheckDebugMap to safety checker

- launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml
- launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_radar_fusion_based_detection.launch.xml
- launch/tier4_perception_launch/launch/object_recognition/detection/detection.launch.xml
- launch/tier4_perception_launch/launch/object_recognition/detection/lidar_based_detection.launch.xml
- launch/tier4_perception_launch/launch/perception.launch.xml
This PR to remove default parameters in tier4_perception_launch to improve code readability. 
> chore(tier4_perception_launcher): remove launch parameter default of detection_by_tracker

- planning/objects_of_interest_marker_interface/package.xml
Add maintainer of `objects_of_interest_marker_interface`
> chore(objects_of_interest_marker_interface): add maintainer

- planning/rtc_interface/package.xml
add maintainer for rtc_interface package
> chore(rtc_interface): add maintainer

- perception/image_projection_based_fusion/include/image_projection_based_fusion/fusion_node.hpp
- perception/image_projection_based_fusion/src/fusion_node.cpp
Rename internal variable related to cache for better readability and customizability.
Confirmed that the build succeeds.
No effect expected.
> refactor(image_projection_based_fusion): rename cache-related variables' name

- planning/path_smoother/src/elastic_band.cpp
By using the sparse matrix, the calculation time and CPU usage of the elastic band became much smaller.
This is the calculation time of the path_smoother node.
**before**
**after**
The CPU usage of 1 second's average by pidstat.
The upper one is behavior_planning_container's one, and **the lower is motion_planning_container's** which includes the path_smoother node.
**before**
**after**
psim
scenario test: https://evaluation.tier4.jp/evaluation/reports/aa6f8e20-1494-55b8-b4f2-76cd5b81370b?project_id=prd_jt
nothing …
> fix(path_smoother): faster elastic band by sparse matrix

- planning/behavior_path_planner/src/utils/lane_change/utils.cpp
- planning/route_handler/include/route_handler/route_handler.hpp
include shoulder lane to avoid objects.
change the getLeft/RighLane's get_shoulder_lane `ture`
before
after
tier internal 
- ticket https://tier4.atlassian.net/browse/RT1-4453
- slack https://star4.slack.com/archives/C03QW0GU6P7/p1701419046585209
psim
evaluator_description: fix/avoidance_shoulder_lane
2023/12/01 https://evaluation.tier4.jp/evaluation/reports/67a11f68-a375-52ad-ad44-967add38275d?project_id=prd_jt
1752/1755
none
none …
> fix(avoidance): include shoulder lane to avoid

- localization/landmark_based_localizer/README.md
- localization/landmark_based_localizer/ar_tag_based_localizer/config/ar_tag_based_localizer.param.yaml
- localization/landmark_based_localizer/ar_tag_based_localizer/src/ar_tag_based_localizer.cpp
- localization/landmark_based_localizer/ar_tag_based_localizer/src/ar_tag_based_localizer.hpp
- localization/landmark_based_localizer/doc_image/consider_orientation.drawio.svg
- localization/landmark_based_localizer/landmark_manager/include/landmark_manager/landmark_manager.hpp
- localization/landmark_based_localizer/landmark_manager/src/landmark_manager.cpp
Added an argument named `consider_orientation` to the `calculate_new_self_pose` function in the `LandmarkManager` class.
See the following link for details of the arguments.
https://github.com/autowarefoundation/autoware.universe/blob/15a3025915dbc5ddd22d94f1f18fc24d30450783/localization/landmark_based_localizer/README.md#about-consider_orientation
Each error is
* Before : 0.613 [m]
* After
* `consider_orientation = true` : 0.613 [m]
* `consider_orientation = false` : 0.613 [m]
The average error itself did not change, but false was better judged by the appearance in Rviz, so false is the default.
|consider_orientation|Figure|
|:--------:|:-------:|
|true|![Screenshot from …
> feat(landmark_manager): add consider_orientation

- planning/mission_planner/src/mission_planner/mission_planner.cpp
judge reroute safe when ego is stopped
psim
> feat(mission_planner): judge reroute safe when ego is stopped

- perception/multi_object_tracker/config/multi_object_tracker_node.param.yaml
Just fix multi_object_tracker node parameter typography
> fix(multi_object_tracker): fix typo in node yaml parameter

- perception/shape_estimation/include/shape_estimation/corrector/bicycle_corrector.hpp
- perception/shape_estimation/include/shape_estimation/corrector/corrector.hpp
- perception/shape_estimation/lib/shape_estimator.cpp
Solves https://github.com/autowarefoundation/autoware.universe/issues/5859
> feat(shape_estimation): add bicycle shape corrector

- launch/tier4_map_launch/package.xml
- map/map_height_fitter/package.xml
- map/map_loader/package.xml
- map/map_projection_loader/package.xml
- map/map_tf_generator/package.xml
Add Localization & Mapping team member in TIER IV to map packages maintainer.
N/A
N/A
> chore: add maintainer in map packages

- planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
> chore(crosswalk): remove debug print

- planning/behavior_velocity_crosswalk_module/package.xml
- planning/obstacle_cruise_planner/package.xml
> chore(crosswalk, obstacle_cruise): add maintainer

- planning/behavior_path_planner_common/package.xml
Add maintainer for drivable area expansion.
Nothing.
Nothing.
> chore(behavior_path_planner_common): add maintainer

- planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/scene.hpp
- planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/utils.hpp
- planning/behavior_path_avoidance_module/src/scene.cpp
- planning/behavior_path_avoidance_module/src/utils.cpp
Previously, avoidance module ouputted turn signal even in the follwoing cases:
- there is **NO** adjacent lane on shift side.
- ego vehicle does **NOT** go inside the shift side lane.
Sometimes, this behavior makes behind vehicle driver confuse that ego try moving to adjacent lane.
In this PR, I fixed turn signal decision logic so that module can output natural turn signals.
do **NOT** output turn signal
https://github.com/autowarefoundation/autoware.universe/assets/44889564/be0e1fed-5f5b-460a-b8e9-ba9292cb996b
do **NOT** output turn signal
https://github.com/autowarefoundation/autoware.universe/assets/44889564/41e3319f-f46c-4f08-92e0-df5330d491c1
output turn signal
https://github.com/autowarefoundation/autoware.universe/assets/44889564/a5b30731-51a0-43d0-b11e-4a684550831f …
> feat(avoidance): suppress unnatural turn signal

- planning/behavior_path_avoidance_by_lane_change_module/src/scene.cpp
- planning/behavior_path_lane_change_module/src/interface.cpp
Reduce logger level from WARN to DEBUG
> fix(lane_change): change logger level to DEBUG

- planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
old common: https://evaluation.tier4.jp/evaluation/reports/10918fb5-0904-5988-8690-b43c49bc4f03?project_id=prd_jt
new common: https://evaluation.tier4.jp/evaluation/reports/556db970-8140-50a8-9d64-2485efc9a71d?project_id=prd_jt
none.
none.
> fix(intersection): fix private condition

- common/tier4_logging_level_configure_rviz_plugin/config/logger_config.yaml
> feat(tier4_logging_level_configure_rviz_plugin): add goal/start planner

- planning/behavior_path_planner/include/behavior_path_planner/planner_manager.hpp
- planning/behavior_path_planner/src/planner_manager.cpp
Apply clang-tidy result.
Note that this PR doesn't include fix for
1. Function case name
2. cognitive complexity
> refactor(planner_manager): apply clang-tidy

- planning/surround_obstacle_checker/README.md
Related PR: https://github.com/autowarefoundation/autoware.universe/pull/4925
Add surround_obstacle_checker descriptions for some parameters
none
> docs(surround_obstacle_checker): add descriptions of some parameters

- planning/behavior_path_planner/include/behavior_path_planner/planner_manager.hpp
- planning/behavior_path_planner/src/planner_manager.cpp
run keep last approved modules after candidate modules
before
```
approved module 1 -> approved modules 2 (keep_last) -> candidate modules
```
after
```
approved module 1 -> candidate modules  -> approved modules 2 (keep_last) 
```
this images shows the goal planner's `previous_module_output` as debug arrows and it is same to candidates avoidance modules
https://github.com/autowarefoundation/autoware.universe/assets/39142679/c0003f46-a02c-42ac-8103-3c75db038546
psim
evaluator_description: feat/keep_last_after_candidates
2023/12/27 https://evaluation.tier4.jp/evaluation/reports/fe919ec7-44af-5cac-8494-3db4611fb700/?project_id=prd_jt
none
none
The PR …
> feat(behavior_path_planner): run keep last approved modules after candidate modules

- planning/behavior_path_planner_common/src/utils/drivable_area_expansion/static_drivable_area.cpp
Use `findNearestSegmentIndexFromLateralDistance` in order to fix broken drivable bound.
https://github.com/autowarefoundation/autoware.universe/assets/44889564/25187fcf-3044-4286-9dce-ea2ed7fcd789
https://github.com/autowarefoundation/autoware.universe/assets/44889564/c8ef8521-bc72-4b31-bd44-7d3610df712f
Nothing.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main …
> fix(static_drivable_area_expansion): fix drivable bound edge process

- localization/ekf_localizer/README.md
- localization/ekf_localizer/src/ekf_module.cpp
* Modified README.md format.
* Added some comments to explain the behavior of yaw bias
Related issue: https://github.com/autowarefoundation/autoware.universe/issues/5808
This PR only changes the documents & comments.
This PR only changes the documents & comments.
> docs(ekf_localizer): improve readme and explain confusing process

- common/traffic_light_utils/include/traffic_light_utils/traffic_light_utils.hpp
- common/traffic_light_utils/package.xml
- common/traffic_light_utils/src/traffic_light_utils.cpp
- planning/behavior_path_planner_common/include/behavior_path_planner_common/utils/traffic_light_utils.hpp
- planning/behavior_path_planner_common/package.xml
- planning/behavior_path_planner_common/src/utils/traffic_light_utils.cpp
- planning/behavior_velocity_traffic_light_module/package.xml
- planning/behavior_velocity_traffic_light_module/src/scene.cpp
- planning/behavior_velocity_traffic_light_module/src/scene.hpp
In https://github.com/autowarefoundation/autoware.universe/commit/1ec5ff3aeee94b1b27e50566ceb4ebc156e2790d, I fixed traffic signal processing function so that modules can handle unknown traffic signal in the same way as red signal.
In the other commits, I added the function in common/traffic_ligth_utils and used it in order to prevent stop judge inconsistency among planning modules.
Effect avoidance and lane change behavior. …
> fix(avoidance, lane_change): modules handle unknown traffic signal in the same way as red signal

- perception/map_based_prediction/src/map_based_prediction_node.cpp
This PR evolves the pedestrian's predicted path to cope with continuous pedestrian crossings.
Before:
After:
psim tests and tier4 internal tests were performed.
Not changed
> feat(map_based_prediction): cope with consecutive crosswalks

- planning/behavior_velocity_crosswalk_module/config/crosswalk.param.yaml
- planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
This PR change the TTC formula that would be appropriate for the ego_pass_first judge.
psim test and the tier4 internal tests were performed.
https://evaluation.tier4.jp/evaluation/reports/a2e1eedd-1fc7-5667-be85-e912fbca2e44?project_id=prd_jt
> feat(crosswalk): change the TTC formula

- launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml
- launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_radar_fusion_based_detection.launch.xml
- launch/tier4_perception_launch/launch/object_recognition/detection/detection.launch.xml
- launch/tier4_perception_launch/launch/perception.launch.xml
Re-organize the image_projection_based_fusion parameters defined in launch files
https://github.com/autowarefoundation/autoware_launch/pull/789
Confirmed with logging_simulator.launch.xml
> fix(image_projection_based_fusion): re-organize the parameters for image projection fusion

- planning/behavior_path_goal_planner_module/src/goal_planner_module.cpp
- planning/behavior_path_planner_common/src/utils/path_safety_checker/safety_check.cpp
Output safety check target object infomartion as commonized marker.
- ColorName::GREEN -> safe objects
- ColorName::RED -> unsafe objects
https://github.com/autowarefoundation/autoware.universe/assets/39142679/8de4e8f8-511e-4980-ad80-41b972b7bfbb
psim
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guid …
> feat(goal_planner): output objects of interest

- planning/behavior_path_goal_planner_module/src/goal_planner_module.cpp
add scale buffer to calcModuleRequestLength
psim
2024/01/14 https://evaluation.tier4.jp/evaluation/reports/1964114c-4918-5108-889a-b870a26c6a26/?project_id=prd_jt
> feat(goal_planner): add scale buffer to calcModuleRequestLength

- planning/mission_planner/src/mission_planner/mission_planner.cpp
Add logs for reroute safety check.
> chore(mission_planner): add logs for reroute safety check

- launch/tier4_localization_launch/package.xml
- localization/ekf_localizer/package.xml
- localization/geo_pose_projector/package.xml
- localization/gyro_odometer/package.xml
- localization/landmark_based_localizer/ar_tag_based_localizer/package.xml
- localization/landmark_based_localizer/landmark_manager/package.xml
- localization/localization_error_monitor/package.xml
- localization/localization_util/package.xml
- localization/ndt_scan_matcher/package.xml
- localization/pose2twist/package.xml
- localization/pose_initializer/package.xml
- localization/pose_instability_detector/package.xml
- localization/stop_filter/package.xml
- localization/tree_structured_parzen_estimator/package.xml
- localization/twist2accel/package.xml
- localization/yabloc/yabloc_common/package.xml
- localization/yabloc/yabloc_image_processing/package.xml
- localization/yabloc/yabloc_monitor/package.xml
- localization/yabloc/yabloc_particle_filter/package.xml
- localization/yabloc/yabloc_pose_initializer/package.xml
- map/map_height_fitter/package.xml
- map/map_loader/package.xml
- map/map_projection_loader/package.xml
- map/map_tf_generator/package.xml
Added the necessary members for the following directories. (Excluding map/util/lanelet2_map_preprocessor)
* localization
* map
* launch/tier4_localization_launch
N/A
N/A
> chore: add localization & mapping maintainers

- vehicle/vehicle_info_util/Readme.md
- vehicle/vehicle_info_util/config/vehicle_info.param.yaml
update vehicle info docs based on https://github.com/orgs/autowarefoundation/discussions/4050
> docs(vehicle_info): add docs for versioning

- launch/tier4_perception_launch/launch/obstacle_segmentation/ground_segmentation/ground_segmentation.launch.py
Move glog declaration for pointcloud_container in autoware_launch, where the container is launched.
MUST BE MERGED WITH https://github.com/autowarefoundation/autoware_launch/pull/805
Checked that glog_component is included in pointcloud_container with `ros2 component list`.
No effect expected …
> chore(pointcloud_container): move glog_component to autoware_launch

- planning/behavior_velocity_crosswalk_module/config/crosswalk.param.yaml
- planning/behavior_velocity_walkway_module/config/walkway.param.yaml
- planning/obstacle_cruise_planner/config/obstacle_cruise_planner.param.yaml
change params to vehicle tested values
launch side: https://github.com/autowarefoundation/autoware_launch/pull/797
Vehicle tests have been performed.
tier4 internal tests https://evaluation.tier4.jp/evaluation/reports/66872580-e421-5b93-9d03-45eadb92273f?project_id=prd_jt
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contribut …
> chore(planning): change params to vehicle tested values

- planning/behavior_path_start_planner_module/README.md
fix image filename in README.md
> docs(start_planner): fix image filename in README.md

- planning/behavior_velocity_run_out_module/package.xml
Added the maintainer of run out module.
None
None
> chore(run_out): add maintainer

- map/map_projection_loader/README.md
add limitations for the map_projection_loader.
> docs(map_projection_loader): add limitations

- perception/shape_estimation/launch/shape_estimation.launch.xml
Remove unnecessary param from launcher
Not tested
No effect expected
> chore(shape_estimation): remove unnecessary param

- planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/goal_planner_module.hpp
- planning/behavior_path_goal_planner_module/src/goal_planner_module.cpp
consider moving objects when deciding path
psim
evaluator_description: feat/safety_check_deciding
2024/01/26 https://evaluation.tier4.jp/evaluation/reports/698d1c27-d8d0-507a-9dc2-d7e0527c539d/?project_id=prd_jt
> feat(goal_planner): consider moving objects when deciding path

- planning/behavior_path_goal_planner_module/package.xml
- planning/behavior_path_start_planner_module/package.xml
Add maintainer to start/goal planner
> chore(start/goal_planner): add maintainer

- control/control_validator/package.xml
Add maintainer to control_validator
> chore(control_validator): add maintainer

- perception/image_projection_based_fusion/package.xml
to remove a maintainer from package.xml
> chore: remove maintainer

- launch/tier4_map_launch/package.xml
> chore(tier4_map_launch): add maintainer

- .github/workflows/build-and-test-differential.yaml
Remove prevent-no-label-execution which was temporarily introduced in https://github.com/autowarefoundation/autoware.universe/pull/4368
Not applicable
Not applicable
> ci(build-and-test-differential): remove prevent-no-label-execution

- planning/behavior_path_goal_planner_module/README.md
> docs(behavior_path_goal_planner): fix typo tha -> the

- evaluator/tier4_metrics_rviz_plugin/package.xml
Adds missing dependency. Waiting for https://github.com/ros/rosdistro/pull/39791 to be merged in the `rosdistro` repository.
> build(tier4_metrics_rviz_plugin): add missing dependency

- perception/radar_tracks_msgs_converter/src/radar_tracks_msgs_converter_node/radar_tracks_msgs_converter_node.cpp
Delete default parameter in src of `radar_tracks_msgs_converter`.
No
> fix(radar_tracks_msgs_converter): delete default param in src

- planning/behavior_path_avoidance_module/package.xml
Add @zulfaqar-azmi-t4 to avoidance module maintainer.
Nothing.
Nothing.
> chore(avoidance): add maintainer

- planning/behavior_velocity_crosswalk_module/config/crosswalk.param.yaml
change ego pass later param related to 
https://github.com/autowarefoundation/autoware.universe/pull/6033
https://github.com/autowarefoundation/autoware_launch/pull/780
psim and tier4 internal test
> chore(crosswalk): change LATER param

- planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/utils.hpp
- planning/behavior_path_avoidance_module/src/scene.cpp
- planning/behavior_path_avoidance_module/src/utils.cpp
Previously, there were ignored lane that should be considered in safety check area. (yellow area) Sometimes, this caused unsafe avoidance maneuver.
After this PR, it adds lane to safety check area properly.
In **RIGHT** side avoidance maneuver.
In **LEFT** side avoidance maneuver.
Improve avoidance maneuver. …
> fix(avoidance): safety check target lanes

- map/util/lanelet2_map_preprocessor/package.xml
> chore(lanelet2_map_preprocessor): add maintainers

- launch/tier4_localization_launch/launch/localization.launch.xml
- launch/tier4_localization_launch/launch/pose_twist_estimator/ar_tag_based_localizer.launch.xml
Fixed so that parameters of `ar_tag_based_localizer` can be set from `autoware_launch`.
* https://github.com/autowarefoundation/autoware_launch/pull/871
If you would like to review this pull request, please also register as a reviewer for the autoware_launch PR above.
The following scenarios have been confirmed.
```
driving_log_replayer simulation run -p ar_tag_based_localizer
```
* [INTERNAL_DATA](https://drive.google.com/file/d/1rdiGpQEG70D0swBFPAgdlRgLww0AToIJ/view?usp=sharing)
In this data, the Point Cloud Data (PCD) for Normal Distributions Transform (NDT) has been intentionally omitted in a specific section, causing NDT to fail in the section.
However, when using `pose_source:=ndt_artag`, since the vehicle's position can still be determined using `ar_tag_based_localizer` within this …
> fix(ar_tag_based_localizer): add ar tag based localizer param

- planning/behavior_path_planner_common/src/utils/drivable_area_expansion/static_drivable_area.cpp
The behavior path module output was cut unintentionally even when the path was NOT overlapped because it detected overlapping by polygon intersection. boost geometry library judged "overlapped" if the two polygons shared contour linestrings.
In this PR, I use **overlapped polygon area** in order to judge properly.
https://github.com/autowarefoundation/autoware.universe/assets/44889564/d9fa65f4-698d-4092-87ec-3610f3778cc7
Nothing. …
> fix(bpp-common): use polygon area to check overlap lanelet

- planning/external_velocity_limit_selector/src/external_velocity_limit_selector_node.cpp
- https://github.com/autowarefoundation/autoware.universe/pull/6388
Fix following error.
```
[ERROR] [external_velocity_limit_selector-28]: process has died [pid 116410, exit code -6, cmd '/home/satoshi/pilot-auto/install/external_velocity_limit_selector/lib/external_velocity_limit_selector/external_velocity_limit_selector --ros-args -r __node:=external_velocity_limit_selector -r __ns:=/planning/scenario_planning -p use_sim_time:=False -p wheel_radius:=0.383 -p wheel_wid
th:=0.235 -p wheel_base:=2.79 -p wheel_tread:=1.64 -p front_overhang:=1.0 -p rear_overhang:=1.1 -p left_overhang:=0.128 -p right_overhang:=0.128 -p vehicle_height:=2.5 -p max_steer_angle:=0.7 --params-file /home/satoshi/pilot-auto/install/autoware_launch/share/autoware_launch/config/planning/scenario_planning/common/common …
```
> fix(external_velocity_limit_selector): fix parameter name

- sensing/gnss_poser/package.xml
> chore(gnss_poser): add maintainer

- planning/.pages
Add missing module to the list of `behavior_velocity_planner` modules.
> docs(planning): add dynamic_obstacle_stop to the list of modules

- sensing/pointcloud_preprocessor/package.xml
Add @kyoichi-sugahara  as maintainer for pointcloud_preprocessor package
mainly for maintaince of blockage diag feature 
> chore(pointcloud_preprocessor): add maintainer

- .github/workflows/json-schema-check.yaml
Make it possible to test this manually too.
Reference: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
> ci(json-schema-check): make it possible to run it manually too

- .github/workflows/build-and-test.yaml
This workflow has been failing due to low space for a long time.
- https://github.com/autowarefoundation/autoware.universe/actions/runs/7997414878/job/21841841123#step:2:189
> ci(build-and-test): run under self hosted

- sensing/tier4_pcl_extensions/package.xml
The `tier4_pcl_extensions` currently has only one maintainers.
Just in case, we would like to add some Sensing members since the package lies in this group
> chore(tier4_pcl_extensions): add maintainers

- system/default_ad_api/src/interface.cpp
- system/default_ad_api/test/node/interface_version.py
> feat(default_ad_api): release adapi v1.1.0

- .github/workflows/build-and-test-differential.yaml
Solves:
- https://github.com/autowarefoundation/autoware.universe/issues/6494
Also the reasoning behind this PR is explained in the issue.
> ci(build-and-test-differential): remove non-cuda job

- planning/behavior_velocity_intersection_module/src/decision_result.cpp
- planning/behavior_velocity_intersection_module/src/decision_result.hpp
- planning/behavior_velocity_intersection_module/src/manager.cpp
- planning/behavior_velocity_intersection_module/src/manager.hpp
- planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
- planning/behavior_velocity_intersection_module/src/scene_intersection.hpp
- planning/behavior_velocity_intersection_module/src/scene_intersection_prepare_data.cpp
- publish `/planning/scenario_planning/lane_driving/behavior_planning/debug/intersection_traffic_signal`
- add information of occlusion in the diagnosis
https://github.com/autowarefoundation/autoware.universe/assets/28677420/24f7db50-9f89-435f-b92e-f3b5bc4cfa8e
```
data: 'intersection178481 : InternalError because conflicting area is empty
intersection177680 : Safe:
occlusion_report:NotOccluded and the best occlusion clearance is -1.000000
intersection177696 : FirstWaitBeforeOcclusion:
occlusion_report:StaticallyOccluded and the best occlusion clearance is 10.495981
'
```
none
none …
> feat(intersection): add traffic signal info publisher and detailed occlusion diagnosis 

- perception/detection_by_tracker/package.xml
- perception/multi_object_tracker/package.xml
- perception/object_merger/package.xml
- perception/radar_object_tracker/package.xml
- perception/tracking_object_merger/package.xml
Add maintainer to object tracker packages
> chore: add maintainer to object tracker packages

- common/autoware_overlay_rviz_plugin/autoware_overlay_rviz_plugin/package.xml
This PR adds a missing dependency to `ament_cmake_auto`
> build(autoware_overlay_rviz_plugin): add missing ament_cmake_auto dependency

- evaluator/tier4_metrics_rviz_plugin/package.xml
add @kosuke55 and @rej55 as maintainer
> chore(tier4_metrics_rviz_plugin): add kosuke55 and rej55 as maintainer

- planning/behavior_velocity_out_of_lane_module/src/scene_out_of_lane.cpp
Set the velocity factor of the `out_of_lane` module to `ROUTE_OBSTACLE`.
> feat(out_of_lane): set velocity_factor to ROUTE_OBSTACLE

- planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/start_planner_module.hpp
- planning/behavior_path_start_planner_module/src/start_planner_module.cpp
Refactor several methods of the start planner for clarity, readability and maybe performance
[TIER IV INTERNAL LINK](https://evaluation.ci.tier4.jp/evaluation/reports/4678f6f1-fb97-5d33-b973-e60c2bfda348?project_id=prd_jt)
> refactor(start planner): refactor for clarity, readability and maybe performance

- planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
- planning/behavior_velocity_dynamic_obstacle_stop_module/src/scene_dynamic_obstacle_stop.cpp
- planning/behavior_velocity_out_of_lane_module/src/scene_out_of_lane.cpp
Update velocity factors for the new message format, fixing the build failures.
Psim
> fix(dynamic_obstacle_stop,out_of_lane,crosswalk): update velocity factor

- planning/behavior_velocity_dynamic_obstacle_stop_module/src/scene_dynamic_obstacle_stop.cpp
Fix of the run time error for https://github.com/autowarefoundation/autoware.universe/pull/6683
scenario test
https://evaluation.tier4.jp/evaluation/reports/1e15d1eb-9dab-562f-8e32-226ddea8f71e?project_id=prd_jt
We can run Autoware successfully.
> fix(dynamic_obstacle_stop): fix run time error

- system/default_ad_api/src/planning.cpp
> feat(default_ad_api): add dynamic_obstacle_stop velocity factor topic

- system/default_ad_api/src/interface.cpp
- system/default_ad_api/test/node/interface_version.py
Release AD API v1.2.0. See https://github.com/autowarefoundation/autoware-documentation/pull/534 for release notes.
> feat(default_ad_api): release adapi v1.2.0

- planning/static_centerline_optimizer/include/static_centerline_optimizer/static_centerline_optimizer_node.hpp
- planning/static_centerline_optimizer/launch/static_centerline_optimizer.launch.xml
- planning/static_centerline_optimizer/scripts/centerline_updater_helper.py
- planning/static_centerline_optimizer/scripts/tmp/run.sh
- planning/static_centerline_optimizer/src/static_centerline_optimizer_node.cpp
Added a helper GUI for the static centerline optimization.
https://github.com/autowarefoundation/autoware.universe/assets/20228327/57d88a07-d943-4b9d-9dd5-4f96e629967a
Test with tmp/run.sh with the GUI
Nothing
> feat(static_centerline_optimizer): static centerline optimizer with GUI

- evaluator/perception_online_evaluator/README.md
add descrtiption about yaw rate evaluation
> docs(perception_online_evaluator): add description about yaw rate evaluation

- planning/behavior_path_avoidance_module/config/avoidance.param.yaml
- planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/data_structs.hpp
- planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/helper.hpp
- planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/parameter_helper.hpp
- planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/scene.hpp
- planning/behavior_path_avoidance_module/src/manager.cpp
- planning/behavior_path_avoidance_module/src/scene.cpp
:warning: Please review https://github.com/autowarefoundation/autoware_launch/pull/947 at first.
I improved avoidance module so that it can set acceleration limit during avoidnace maneuver. The acceleration limit is applied until the ego passes through the side of target object. 
I confirmed this feature worked well with real vehicle in closed course. I set `max_acceleration` to 0.3m/ss, and we can see the acceleration is limited by the value during avoidance maneuver.
https://github.com/autowarefoundation/autoware.universe/assets/44889564/e7fbcc0c-7741-4202-b299-00024aa4a743
Improve avoidance behavior. …
> feat(avoidance): limit acceleration during avoidance maneuver

- planning/behavior_path_avoidance_by_lane_change_module/config/avoidance_by_lane_change.param.yaml
- planning/behavior_path_avoidance_by_lane_change_module/src/manager.cpp
- planning/behavior_path_avoidance_module/config/avoidance.param.yaml
- planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/data_structs.hpp
- planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/helper.hpp
- planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/parameter_helper.hpp
- planning/behavior_path_avoidance_module/src/manager.cpp
- planning/behavior_path_avoidance_module/src/scene.cpp
- planning/behavior_path_avoidance_module/src/shift_line_generator.cpp
- planning/behavior_path_avoidance_module/src/utils.cpp
- `moving_speed_threshold` -> `th_moving_speed`
- `moving_time_threshold` -> `th_moving_time`
- `safety_buffer_longitudinal` -> `longitudinal_buffer`
- `time_threshold` -> `th_stopped_time`
- `distance_threshold` -> `th_moving_distance`
- `quantize_filter_threshold` -> `quantize_size`
- `object_last_seen_threshold` -> `max_compensation_time`
- `lateral_execution_threshold` -> `th_avoid_execution`
- `lateral_small_shift_threshold` -> `th_small_shift_length`
- `soft_road_shoulder_margin` -> `soft_drivable_bound_margin`
- `hard_road_shoulder_margin` -> `hard_drivable_bound_margin`
- `enable_cancel_maneuver` -> `cancel.enable`
- `threshold_distance_object_is_on_center` -> `parked_vehicle.th_offset_from_centerline`
- `object_check_shiftable_ratio` -> `parked_vehicle.th_shiftable_ratio`
- …
> refactor(avoidance): rebuild parameter structure

- planning/behavior_velocity_intersection_module/src/scene_intersection_stuck.cpp
detect stuck vehicle based on their position w.r.t stuck detect area
https://evaluation.tier4.jp/evaluation/reports/2068f350-c0d1-5069-b0ea-de9b374fd1fe?project_id=prd_jt
following scenarios are fixed accordingly
https://evaluation.tier4.jp/evaluation/reports/2068f350-c0d1-5069-b0ea-de9b374fd1fe/tests/f0200857-9800-5bcb-b6d6-97e582e16ea4?project_id=prd_jt
none
none …
> fix(intersection): detect stuck vehicle by position on detect area

- perception/compare_map_segmentation/src/distance_based_compare_map_filter_nodelet.cpp
- perception/compare_map_segmentation/src/voxel_based_approximate_compare_map_filter_nodelet.cpp
- perception/compare_map_segmentation/src/voxel_based_compare_map_filter_nodelet.cpp
- perception/compare_map_segmentation/src/voxel_distance_based_compare_map_filter_nodelet.cpp
- To add intensity field for `compare_map_segmentation` to solve the issue https://github.com/autowarefoundation/autoware.universe/issues/6785
- This PR changes from fixed pointcloud type of output like pcl::PointXYZ to the dynamic one by referencing the `point_step` of PointCloud2 input topic.
- [TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT1-5980)
Confirmed by logging_simulator that the intensity is added into the current empty padding fiedl (offset 12)
- Testing on the sample rosbag shows the processing time isn't affected much, even seems get slightly faster.
|    Before    |    After    |
|  --- | ---  |
| ![image](https://github.com/autowarefoundation/autoware.universe/assets/94814556/b0976e59-d7ce-4762-bc92-301aa3ac14d0)| …
> fix(compare_map_segmentation): add intensity field

- planning/path_smoother/docs/eb.md
Fixed the mathjax visualization error of path_smoother's document.
NOTE:
The boldsymbol is replaced with mathbf which is not italic. I could not find a way to make the text bold and italic.
Nothing
Nothing
> fix(path_smoother): fix mathjax visualization error

- evaluator/perception_online_evaluator/test/test_perception_online_evaluator_node.cpp
make waitForDummyNode better and direct.
previously, this function waits for receiving marker topic.
In this PR, wait for pub/sub connection.
unit test
100% tests passed, 0 tests failed out of 5
> feat(perception_online_evaluator): better waitForDummyNode

- common/tier4_logging_level_configure_rviz_plugin/README.md
> docs(tier4_logging_level_configure_rviz_plugin): update document

- planning/behavior_path_avoidance_by_lane_change_module/src/scene.cpp
- planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/utils/utils.hpp
- planning/behavior_path_lane_change_module/src/scene.cpp
- planning/behavior_path_lane_change_module/src/utils/utils.cpp
Refactor calcMinimumLaneChangeLength and calcMaximumLaneChange length function to use std::accumulate.
> refactor(lane_change): refactor min and max lane change length

- common/tier4_logging_level_configure_rviz_plugin/config/logger_config.yaml
- planning/behavior_path_lane_change_module/src/utils/utils.cpp
Renamed the logger in the lane change utils, and add them in the logger config.
> refactor(lane_change): fix logger

- control/mpc_lateral_controller/include/mpc_lateral_controller/mpc_lateral_controller.hpp
- control/pid_longitudinal_controller/include/pid_longitudinal_controller/pid_longitudinal_controller.hpp
- control/trajectory_follower_node/include/trajectory_follower_node/controller_node.hpp
- control/trajectory_follower_node/test/test_controller_node.cpp
- simulator/simple_planning_simulator/include/simple_planning_simulator/simple_planning_simulator_core.hpp
This PR removes unused messages from Autoware.Universe.
We already replaced most of the codes for each messages as the following:
* VehicleControlCommand -> autoware_control_msgs/Control
* VehicleKinematicState -> autoware_localization_msgs/KinematicState
* VehicleOdometry -> nav_msgs/Odometry
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-r …
> feat!: remove VehicleControlCommand, VehicleKinematicState, and vehicleOdometry messages

- common/tier4_logging_level_configure_rviz_plugin/config/logger_config.yaml
Add route handler's logger into logging level configure.
> fix(route_handler): add logger

- launch/tier4_perception_launch/launch/object_recognition/detection/detector/lidar_dnn_detector.launch.xml
- perception/lidar_centerpoint/config/centerpoint_tiny.param.yaml
- perception/lidar_centerpoint/launch/lidar_centerpoint.launch.xml
- This to add param.yaml file for centerpoint_tiny to reuse the internal evalutor setting 
> fix(lidar_centerpoint): add param file for centerpoint_tiny

- common/tier4_simulated_clock_rviz_plugin/README.md
Update the guide to include additional step on how to use, and added some warnings.
> docs(tier4_simulated_clock_rviz_plugin): update how to use

- planning/behavior_path_avoidance_by_lane_change_module/src/scene.cpp
- planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/data_structs.hpp
- planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/debug.hpp
- planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/helper.hpp
- planning/behavior_path_avoidance_module/src/debug.cpp
- planning/behavior_path_avoidance_module/src/scene.cpp
- planning/behavior_path_avoidance_module/src/shift_line_generator.cpp
- planning/behavior_path_avoidance_module/src/utils.cpp
Remove dependency for `tier4_planning_msgs::msg::AvoidanceDebugFactor`.
> refactor(avoidance): rebuild object info list

- .github/PULL_REQUEST_TEMPLATE/small-change.md
- .github/PULL_REQUEST_TEMPLATE/standard-change.md
Augment the pull request template to enhance requirements for documenting interface changes.
1. Add the "Interface changes" section in small-change, because we witness many small changes including additional debugging topics and parameters that are not well-documented in current PRs.
2. Add template tables for documenting changes in topics and parameters for standard change. We hope this could help code contributors create clean visualizations of the interface updates.
https://github.com/autowarefoundation/autoware/pull/4654 …
> feat(pull_request_templates): improve the pull request template to enhance requirements on documenting interface changes

- perception/image_projection_based_fusion/include/image_projection_based_fusion/roi_detected_object_fusion/node.hpp
- perception/image_projection_based_fusion/include/image_projection_based_fusion/roi_pointcloud_fusion/node.hpp
- perception/image_projection_based_fusion/include/image_projection_based_fusion/segmentation_pointcloud_fusion/node.hpp
- perception/image_projection_based_fusion/include/image_projection_based_fusion/utils/utils.hpp
- perception/image_projection_based_fusion/package.xml
- perception/image_projection_based_fusion/src/pointpainting_fusion/node.cpp
- perception/image_projection_based_fusion/src/roi_cluster_fusion/node.cpp
- perception/image_projection_based_fusion/src/roi_detected_object_fusion/node.cpp
- perception/image_projection_based_fusion/src/roi_pointcloud_fusion/node.cpp
- perception/image_projection_based_fusion/src/segmentation_pointcloud_fusion/node.cpp
- perception/image_projection_based_fusion/src/utils/utils.cpp
In image_projection_based_fusion, only the internal parameters of the camera were considered, and no distortion correction was applied. As a result, when projecting onto images with significant distortion, misalignments occurred. This Pull Request has been modified to account for distortion.
In roi_cluster_fusion, operation has been confirmed on the actual machine.
before
after
[pull request …
> feat(image projection based fusion): unrecify 3d point for image projection based fusion

- control/vehicle_cmd_gate/src/vehicle_cmd_filter.cpp
- control/vehicle_cmd_gate/src/vehicle_cmd_filter.hpp
- control/vehicle_cmd_gate/src/vehicle_cmd_gate.cpp
- control/vehicle_cmd_gate/src/vehicle_cmd_gate.hpp
This PR adds support for real time param reloading (ie. using rqt reconfigure) for the vehicle_cmd_gate module
PSim + rqt_reconfigure
We can issue new parameters for the module without restarting Autoware.
> feat(vehicle_cmd_gate): support for real time update params for v cmd gate

- perception/ground_segmentation/package.xml
- perception/map_based_prediction/package.xml
- perception/object_range_splitter/package.xml
- perception/traffic_light_classifier/package.xml
- perception/traffic_light_map_based_detector/package.xml
- perception/traffic_light_visualization/package.xml
- sensing/image_diagnostics/package.xml
- sensing/pointcloud_preprocessor/package.xml
This PR adds some maintainers to make review process smoother.
See more details in [TIER IV Internal Slack link](https://tier4.enterprise.slack.com/docs/T4PNQAM70/F0723AMFAA3).
> chore: update sensing/perception maintainer

- planning/behavior_path_sampling_planner_module/src/sampling_planner_module.cpp
- planning/sampling_based_planner/path_sampler/include/path_sampler/node.hpp
- planning/sampling_based_planner/path_sampler/include/path_sampler/parameters.hpp
- planning/sampling_based_planner/path_sampler/src/node.cpp
- planning/sampling_based_planner/sampler_common/include/sampler_common/constraints/hard_constraint.hpp
- planning/sampling_based_planner/sampler_common/include/sampler_common/structures.hpp
- planning/sampling_based_planner/sampler_common/src/sampler_common/constraints/hard_constraint.cpp
Improves the `path_planner`:
-  output smoother trajectories by no longer connecting the generated trajectory to the reference path.
- add parameters to give more control over the hard constraints and the previous path reuse.
- fix crashes caused by empty `poses` in the `sampler_common::Path`.
Requires the launch PR: https://github.com/autowarefoundation/autoware_launch/pull/983
Psim. Running with `launch_avoidance_module:=false` and `motion_stop_planner_type:=none`.
https://github.com/autowarefoundation/autoware.universe/assets/78338830/0b938fba-b603-4c42-9f9d-1d5724ae5f64 …
> feat(path_sampler): make the trajectory smoother, add params, fix crash

- evaluator/control_evaluator/CMakeLists.txt
- evaluator/control_evaluator/README.md
- evaluator/control_evaluator/include/control_evaluator/control_evaluator_node.hpp
- evaluator/control_evaluator/launch/control_evaluator.launch.xml
- evaluator/control_evaluator/package.xml
- evaluator/control_evaluator/param/control_evaluator.defaults.yaml
- evaluator/control_evaluator/src/control_evaluator_node.cpp
- launch/tier4_control_launch/launch/control.launch.py
- launch/tier4_control_launch/package.xml
This PR introduces a control evaluator for Autoware control which can be used for similar purposes as the planning_evaluator, localization_evaluator, etc.
Since proper metrics have not been agreed on for the different control modules, this PR only introduces a simple control evaluator that reads diagnostics info from the AEB module and outputs diagnostic information to the `/control/control_evaluator/metrics`  topic depending if the AEB module was activated or not. However, this evaluator can be expanded and improved as required, for the moment this PR introduces mostly a skeleton for the control evaluator.  
PSIM:
After doing ros2 topic echo /control/control_evaluator/metrics you can get messages like this from the evaluator
---
header:
stamp:
sec: 1715242312
nanosec: 781787947
frame_id: …
> feat(control_evaluator): implement a control evaluator

- planning/behavior_path_avoidance_module/package.xml
- planning/behavior_path_planner/package.xml
- planning/behavior_path_planner_common/package.xml
- planning/route_handler/package.xml
Added maintainer to planning modules
None
> chore: added maintainer

- simulator/simple_planning_simulator/package.xml
Add maintainer for simple planning simulator
> chore(simple_planning_simulator): add maintainer

- system/default_ad_api_helpers/automatic_pose_initializer/CMakeLists.txt
- system/default_ad_api_helpers/automatic_pose_initializer/launch/automatic_pose_initializer.launch.xml
- system/default_ad_api_helpers/automatic_pose_initializer/package.xml
- system/default_ad_api_helpers/automatic_pose_initializer/src/automatic_pose_initializer.cpp
- system/default_ad_api_helpers/automatic_pose_initializer/src/automatic_pose_initializer.hpp
Componentize node in automatic_pose_initializer.
> feat(automatic_pose_initializer): componentize node

- perception/shape_estimation/src/node.cpp
When the `classification` is an empty collection, there was a segfault due to call to `.front()` object
Note that, this problem exists in many others nodes, I didn't want to generate a big PR though. 
fix: Subscribing to topic with and without the classification.  …
> fix(shape_estimation): segfault when the classification was empty

- planning/obstacle_cruise_planner/include/obstacle_cruise_planner/node.hpp
> fix(obstacle_cruise_planner): fix typo

- perception/radar_object_tracker/CMakeLists.txt
- perception/radar_object_tracker/include/radar_object_tracker/utils/radar_object_tracker_utils.hpp
- perception/radar_object_tracker/package.xml
- perception/radar_object_tracker/src/radar_object_tracker_node/radar_object_tracker_node.cpp
- perception/radar_object_tracker/src/utils/radar_object_tracker_utils.cpp
- perception/radar_object_tracker/test/test_radar_object_tracker_utils.cpp
This PR contains:
1. fix lanelet based filter algorithm in radar_object_tracker.
2. move functions in main cpp to `radar_object_tracker_utils`
3. add gtest to prevent further error
As figure shown below, previous method would fail to filter forward orientated with negative velocity.
[TIER IV INTERNAL URL](https://star4.slack.com/archives/C054K088X2N/p1715667537773129)
gtest is added in this PR.
[pull …
> feat(radar_object_tracker): fix lanelet based filter and add test

- perception/map_based_prediction/include/map_based_prediction/path_generator.hpp
- perception/map_based_prediction/src/path_generator.cpp
Add const for some functions in PathGenerator
Build succeeds.
No effect expected.
No effect expected.
> refactor(map_based_prediction): add const

- perception/map_based_prediction/test/map_based_prediction/test_path_generator.cpp
> fix(map_based_prediction): fix typo

- map/map_projection_loader/README.md
- map/map_projection_loader/docs/map_projector_type.svg
I visualized how each projector type projects coordinates.
1. [geography_utils::get_lanelet2_projector()](https://github.com/autowarefoundation/autoware.universe/blob/e7a826858bd4164701b26a2f2d0c059ba80606fc/common/geography_utils/src/lanelet2_projector.cpp#L27-L32)
2.  [UtmProjector::UtmProjector()](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/4789fde6c3bafcd5a8d721d11c5d92870ca59a22/lanelet2_projection/src/UTM.cpp#L8-L13)
3.  [UTMUPS::Forward()](https://github.com/geographiclib/geographiclib/blob/2fa1c84ab172305701127d116921a4f3c64b9a79/src/UTMUPS.cpp#L79-L90)
1. [geography_utils::get_lanelet2_projector()](https://github.com/autowarefoundation/autoware.universe/blob/e7a826858bd4164701b26a2f2d0c059ba80606fc/common/geography_utils/src/lanelet2_projector.cpp#L40-L47) …
> docs(map_projection_loader): add projector type image

- perception/shape_estimation/CMakeLists.txt
- perception/shape_estimation/package.xml
- perception/shape_estimation/test/shape_estimation/test_shape_estimator.cpp
- perception/shape_estimation/test/test_shape_estimation.cpp
Add test for shape_estimation package.
```sh
colcon test --packages-select shape_estimation 
cat log/latest_test/shape_estimation/stdout.log
```
> test(shape_estimation): add unit test on shape_estimation

- perception/euclidean_cluster/include/euclidean_cluster/euclidean_cluster.hpp
- perception/euclidean_cluster/include/euclidean_cluster/euclidean_cluster_interface.hpp
- perception/euclidean_cluster/include/euclidean_cluster/utils.hpp
- perception/euclidean_cluster/include/euclidean_cluster/voxel_grid_based_euclidean_cluster.hpp
- perception/euclidean_cluster/lib/euclidean_cluster.cpp
- perception/euclidean_cluster/lib/utils.cpp
- perception/euclidean_cluster/lib/voxel_grid_based_euclidean_cluster.cpp
- perception/euclidean_cluster/src/voxel_grid_based_euclidean_cluster_node.cpp
- To process and output the fields of clusters' pointcloud as the input topic including `intensity` field for `voxel_grid_based_euclidean_cluster` to solve the issue https://github.com/autowarefoundation/autoware.universe/issues/6785
- [TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT1-5996?focusedCommentId=166391)
- Confirmed by logging_simulator that voxel_grid_based_euclidean_cluster
- Can process and output the topic with intensity field:
- Processing time increase a little bit for a quite complicated scene
| Before | After | 
| -- | -- | 
|![image](https://github.com/autowarefoundation/autoware.universe/assets/94814556/8f8b33f5-3400-4e45-a47b-e75643b1a0b3)| ![image](https://github.com/autowarefoundation/autoware.universe/assets/94814556/9f48a446-8a6b-4ed8-98f2-c2bd16f3e613 …
> fix(euclidean_cluster): add intensity field

- planning/behavior_path_avoidance_module/config/avoidance.param.yaml
- planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/data_structs.hpp
- planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/debug.hpp
- planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/parameter_helper.hpp
- planning/behavior_path_avoidance_module/schema/avoidance.schema.json
- planning/behavior_path_avoidance_module/src/debug.cpp
- planning/behavior_path_avoidance_module/src/manager.cpp
- planning/behavior_path_avoidance_module/src/scene.cpp
Make it possible to select output debug marker infomation from yaml file.
```yaml
debug:
enable_other_objects_marker: false
enable_other_objects_info: false
enable_detection_area_marker: false
enable_drivable_bound_marker: false
enable_safety_check_marker: false
enable_shift_line_marker: false
enable_lane_marker: false
enable_misc_marker: false
```
Related PR: https://github.com/autowarefoundation/autoware_launch/pull/996
Psim
https://github.com/autowarefoundation/autoware.universe/assets/44889564/c8c4c1c3-80c6-4dfc-aced-b0e320c49ae3
Nothing. …
> feat(avoidance): make it selectable output debug marker from yaml

- evaluator/perception_online_evaluator/param/perception_online_evaluator.defaults.yaml
Change resolution of detection range list
> fix(perception_online_evaluator): fix range resolution

- perception/detected_object_validation/CMakeLists.txt
- perception/detected_object_validation/test/test_utils.cpp
Add unit tests of `detected_object_validation/utils`.
> test(detected_object_validation): add unit tests of utils

- localization/landmark_based_localizer/landmark_manager/src/landmark_manager.cpp
adjust the volume threshold to ease the validation
> fix(landmark_manager): adjust volume threshold

- planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/data_structs.hpp
- planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/scene.hpp
- planning/behavior_path_avoidance_module/src/scene.cpp
- planning/behavior_path_planner_common/include/behavior_path_planner_common/interface/scene_module_interface.hpp
Fixed avoidance module to transit SUCCEEDED state when the ego avoid all obstacles.
https://github.com/autowarefoundation/autoware.universe/assets/44889564/1a82ffb6-977c-4625-8588-4eaa1f9fcb1f
Nothing.
> fix(avoidance): fix RTC state transition

- planning/freespace_planning_algorithms/package.xml
Adds missing `pybind11_vendor` dependency, see https://github.com/autowarefoundation/autoware-deb-packages/actions/runs/9252065989/job/25448967373?pr=87
> build(freespace_planning_algorithms): add pybind11_vendor dependency

- planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/util.hpp
- planning/behavior_path_goal_planner_module/src/shift_pull_over.cpp
- planning/behavior_path_goal_planner_module/src/util.cpp
Shift paths in parking_lot are allowed even outside the lane.
This is because the previous module (avoidance) generates a path outside the lane.
releted: tier4 internal ticket (https://tier4.atlassian.net/browse/RT0-31536)
before
shift path outside lanes is rejected
[Screencast from 04-23-24 16_55_26 (1).webm](https://github.com/autowarefoundation/autoware.universe/assets/39142679/bbb2b0af-5077-4941-879b-8a6aaec33fb3)
https://github.com/autowarefoundation/autoware.universe/assets/39142679/24f7d8e0-043c-40e8-9657-7fd3d21ccce7
after
shift path outside lanes but inside parking lot is selected.
https://github.com/autowarefoundation/autoware.universe/assets/39142679/82a51e0e-f24f-4a47-8601-74479fd82778
psim
https://evaluation.tier4.jp/evaluation/reports/dff6363f-b6f5-5411-8b81-55791cd5c527/?pro …
> feat(goal_planner): allow shift pull over in parking lot outside lane

- common/.pages
- common/README.md
- common/autoware_point_types/README.md
- common/traffic_light_recognition_marker_publisher/Readme.md
Adding .pages file in the common folder so that the `common` tab on the document's page is much more structured.
> docs(common): adding .pages file

- system/default_ad_api/src/diagnostics.cpp
- system/default_ad_api/src/interface.cpp
- system/default_ad_api/test/node/interface_version.py
Release AD API v1.3.0. See https://github.com/autowarefoundation/autoware-documentation/pull/559 for [release notes](https://autowarefoundation.github.io/autoware-documentation/pr-559/design/autoware-interfaces/ad-api/release/).
- Fix QoS to match documentation …
> feat(default_ad_api): release adapi v1.3.0

- sensing/pointcloud_preprocessor/package.xml
Add @drwnz  and @meliketanrikulu  (asked by Fatih https://github.com/autowarefoundation/autoware.universe/pull/7027) as maintainers in pointcloud_preprocessor. 
> chore(pointcloud_preprocessor): add maintainers to pointcloud preprocessor

- control/autonomous_emergency_braking/src/node.cpp
https://github.com/autowarefoundation/autoware/issues/4752
https://github.com/autowarefoundation/autoware/issues/4752
node does not die
none
none
> fix(autonomous_emergency_braking): fix invalid access to imu_ptr

- common/object_recognition_utils/test/src/test_predicted_path_utils.cpp
The test was still failing after: https://github.com/autowarefoundation/autoware.universe/pull/7268. 
> fix(object_recognition_utils): fix test for resamplePredictedPath_by_vector

- planning/.pages
- planning/autoware_behavior_path_dynamic_obstacle_avoidance_module/README.md
- planning/autoware_behavior_path_static_obstacle_avoidance_module/schema/static_obstacle_avoidance.schema.json
- planning/behavior_path_avoidance_by_lane_change_module/README.md
- planning/behavior_path_lane_change_module/README.md
fix path to document due to recent renaming of avoidance modules.
> docs(planning): fix path to documents

- .github/CODEOWNERS
- launch/tier4_planning_launch/launch/scenario_planning/lane_driving/motion_planning/motion_planning.launch.xml
- launch/tier4_planning_launch/package.xml
- planning/.pages
- planning/autoware_planning_topic_converter/CMakeLists.txt
- planning/autoware_planning_topic_converter/README.md
- planning/autoware_planning_topic_converter/include/autoware_planning_topic_converter/converter_base.hpp
- planning/autoware_planning_topic_converter/include/autoware_planning_topic_converter/path_to_trajectory.hpp
- planning/autoware_planning_topic_converter/package.xml
- planning/autoware_planning_topic_converter/src/path_to_trajectory.cpp
rename package to autoware_planning_topic_converter from planning_topic_converter.
Psim
Nothing.
> chore(autoware_planning_topic_converter): add prefix `autoware_`

- perception/map_based_prediction/src/path_generator.cpp
the args order of `generatePolynomialPath` in `generatePathForOnLaneVehicle` is wrong 
this causes short predicted path on shoulder lane
related PR: https://github.com/autowarefoundation/autoware.universe/pull/7157
before
after
psim
https://evaluation.tier4.jp/evaluation/reports/3d822ba7-52df-5927-b0ae-a30acb522d22/?project_id=prd_jt …
> fix(map_based_prediction): fix generatePathForOnLaneVehicle

- planning/obstacle_cruise_planner/config/obstacle_cruise_planner.param.yaml
disable a recent implemented feature
psim
> feat(obstacle_curise): revert lateral stop margin for unknown objects

- control/smart_mpc_trajectory_follower/package.xml
add maitainers
@kosuke55 
@TakaHoribe 
@takayuki5168 
> chore(smart_mpc): add maitainers

- planning/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp
See https://github.com/tier4/autoware.universe/pull/1324.
After avoidance is performed, it may be impossible to approve the behavior of returning to the original route due to environmental factors.
This may prevent the vehicle from continuing autonomous driving.
To solve this problem, the behavior of returning to the original route will not take drivable area constraints into account.
https://github.com/autowarefoundation/autoware.universe/assets/44889564/a3e88f90-816d-419b-bc45-036296fadfd2
https://github.com/autowarefoundation/autoware.universe/assets/44889564/cbf98a5e-af27-419b-8187-e04f0109eecc
Psim
Nothing. …
> fix(static_obstacle_avoidance): return shift validation

- control/lane_departure_checker/package.xml
Add @zulfaqar-azmi-t4 as the maintainer.
> chore(lane_departure_checker): add maintainer

- launch/tier4_perception_launch/package.xml
> chore(tier4_perception_launch): rename autoware_map_based_prediction_depend

- .github/workflows/clang-tidy-differential.yaml
Forgot to add the requirement condition to the workflow in:
- https://github.com/autowarefoundation/autoware.universe/pull/7331
> ci(clang-tidy-differential): fix tag requirement

- localization/ndt_scan_matcher/include/ndt_scan_matcher/diagnostics_module.hpp
- localization/ndt_scan_matcher/include/ndt_scan_matcher/hyper_parameters.hpp
- localization/ndt_scan_matcher/include/ndt_scan_matcher/ndt_scan_matcher_core.hpp
- localization/ndt_scan_matcher/src/diagnostics_module.cpp
- localization/ndt_scan_matcher/src/map_update_module.cpp
- localization/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp
- localization/ndt_scan_matcher/test/test_util.hpp
Reverts autowarefoundation/autoware.universe#7278
> refactor(ndt scan matcher): apply static analysis revert

- launch/tier4_map_launch/package.xml
- map/map_loader/package.xml
- map/util/lanelet2_map_preprocessor/package.xml
> chore(map): udpate maintainer

- control/autoware_control_validator/src/control_validator.cpp
> fix(autoware_control_validator): fix vehicle info utils

- planning/autoware_behavior_velocity_virtual_traffic_light_module/src/manager.cpp
suppress re-launch by the back path
> fix(virtual traffic light): suppress launch

- .github/workflows/build-and-test-differential-arm64.yaml
- .github/workflows/build-and-test-differential.yaml
Reverts autowarefoundation/autoware.universe#7408
> fix: revert "ci(build-and-test-differential): set checkout fetch-depth to 1"

- control/autoware_operation_mode_transition_manager/src/node.cpp
additional fix for https://github.com/autowarefoundation/autoware.universe/pull/7328
https://github.com/autowarefoundation/autoware.universe/pull/7328
https://evaluation.tier4.jp/evaluation/reports/3f2a1a76-e01d-5b4b-833d-8943d9ca6979?project_id=prd_jt
none
none
> fix(operation mode manager): add nullptr check in onTimer

- planning/autoware_behavior_path_avoidance_by_lane_change_module/test/test_behavior_path_planner_node_interface.cpp
- planning/autoware_static_centerline_generator/package.xml
- planning/autoware_static_centerline_generator/test/test_static_centerline_generator.test.py
> fix(static_centerline_generator): fix dependency

- planning/autoware_behavior_velocity_planner/test/src/test_node_interface.cpp
Related PR: https://github.com/autowarefoundation/autoware.universe/pull/7425
PASS CI.
Nothing.
> fix(autoware_behavior_velocity_planner): remove no prefix

- planning/.pages
- planning/autoware_behavior_path_goal_planner_module/README.md
docs(plannig): fix invalid link
> docs(plannig): fix invalid link

- planning/autoware_behavior_path_planner/include/autoware_behavior_path_planner/behavior_path_planner_node.hpp
- planning/autoware_behavior_path_planner/src/behavior_path_planner_node.cpp
https://tier4.atlassian.net/browse/RT1-6587
https://tier4.atlassian.net/browse/RT1-6587
https://evaluation.tier4.jp/evaluation/reports/3f2a1a76-e01d-5b4b-833d-8943d9ca6979?project_id=prd_jt
none
none
> feat(behavior_path_planner): replace polling subscribers

- planning/autoware_behavior_path_lane_change_module/package.xml
- planning/autoware_route_handler/package.xml
Adding @mkquda as one of the codeowner.
> chore(route_handler, lane_change): add codeowner

- planning/behavior_velocity_occlusion_spot_module/plugins.xml
Remove a file that was wrongly kept when renaming the package.
> chore(planning): remove ghost file

- common/autoware_test_utils/include/autoware_test_utils/autoware_test_utils.hpp
- common/autoware_test_utils/src/autoware_test_utils.cpp
Write functions to load paths from folders. Example include route file, test lanelet map and config.
> refactor(autoware_test_utils): function to load paths from folder

- localization/pose_estimator_arbiter/package.xml
As the packages belonging to Localizatoin and Map are basically maintained by this member, we will do the same for this package.
> chore(pose_estimator_arbiter): add maintainers to pose_estimator_arbiter

- evaluator/control_evaluator/CMakeLists.txt
- evaluator/control_evaluator/include/control_evaluator/control_evaluator_node.hpp
- evaluator/control_evaluator/include/control_evaluator/metrics/deviation_metrics.hpp
- evaluator/control_evaluator/launch/control_evaluator.launch.xml
- evaluator/control_evaluator/package.xml
- evaluator/control_evaluator/src/control_evaluator_node.cpp
- evaluator/control_evaluator/src/metrics/deviation_metrics.cpp
- launch/tier4_control_launch/launch/control.launch.py
- add deviation metrics
- ego lateral deviation from trajectory
- ego yaw deviation from trajecotory
- add queue for target diagnostics 
- multiple decisions sent with different diagnostics can be handled.
psim
check deviation
check aeb
https://evaluation.tier4.jp/evaluation/reports/418bdf9d-d2f1-51af-8c7e-7350be917243?project_id=prd_jt …
> feat(control_evaluator): add deviation metrics and queue for diagnostics

- planning/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp
The goal planner re-generates candidate path when the shape of the previous module output changes. The shape change is determined by the distance of the path end point, which is also applicable when the path is extended by the modified goal. Therefore, in this PR, the lateral distance is checked, and the distance is not calculated for points outside the segment.
before
re-generating candidate path after finding path once. 
https://github.com/autowarefoundation/autoware.universe/assets/39142679/82496bf8-8d6c-4db5-8102-aebc6618776b
after
prevent re-generating candidate path
https://github.com/autowarefoundation/autoware.universe/assets/39142679/17a63b75-5f9a-4a95-a5c1-be71e2f91c5f
psim
[https://evaluation.tier4.jp/evaluation/reports/a5e6aa5a-dc4f-5bde-892c-c336d0732574?project_id=prd_jt …
> fix(goal_planner): check lateral distance for previous output path shape change check

- launch/tier4_control_launch/launch/control.launch.py
- launch/tier4_simulator_launch/launch/simulator.launch.xml
- fix output metrics topic name same as component evaluator
- add control evaluator to diagnostics converter target 
scenario simulator
check with https://evaluation.tier4.jp/evaluation/scenarios/e98c7490-304f-408d-bb44-9c9c016d5d6f?project_id=prd_jt
topic name change
`/control/control_evaluator/metrics` -> `/diagnostic/control_evaluator/metrics` …
> feat(diagnostic_converter): fix output metrics topic name and add to converter

- .github/workflows/build-and-test-differential.yaml
- .github/workflows/build-and-test.yaml
Closes:
- https://github.com/autowarefoundation/autoware.universe/issues/7501
> ci: add cache to build-and-test derivatives

- planning/autoware_planning_topic_converter/include/autoware/planning_topic_converter/converter_base.hpp
- planning/autoware_planning_topic_converter/include/autoware/planning_topic_converter/path_to_trajectory.hpp
- planning/autoware_planning_topic_converter/src/path_to_trajectory.cpp
> feat(planning_topic_converter): rename to include/autoware/{package_name}

- planning/autoware_planning_validator/CMakeLists.txt
- planning/autoware_planning_validator/include/autoware/planning_validator/debug_marker.hpp
- planning/autoware_planning_validator/include/autoware/planning_validator/planning_validator.hpp
- planning/autoware_planning_validator/include/autoware/planning_validator/utils.hpp
- planning/autoware_planning_validator/src/debug_marker.cpp
- planning/autoware_planning_validator/src/planning_validator.cpp
- planning/autoware_planning_validator/src/utils.cpp
- planning/autoware_planning_validator/test/src/test_planning_validator_functions.cpp
- planning/autoware_planning_validator/test/src/test_planning_validator_node_interface.cpp
- planning/autoware_planning_validator/test/src/test_planning_validator_pubsub.cpp
> feat(planning_validator): rename to include/autoware/{package_name}

- planning/motion_velocity_planner/autoware_motion_velocity_dynamic_obstacle_stop_module/src/dynamic_obstacle_stop_module.hpp
- planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/src/obstacle_velocity_limiter.hpp
- planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/src/obstacle_velocity_limiter_module.hpp
- planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/filter_predicted_objects.hpp
- planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_module.hpp
- planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/planner_data.hpp
- planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/plugin_module_interface.hpp
- planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/velocity_planning_result.hpp
- planning/motion_velocity_planner/autoware_motion_velocity_planner_node/src/node.hpp
- planning/motion_velocity_planner/autoware_motion_velocity_planner_node/src/planner_manager.hpp
> feat(motion_velocity_planner): rename include directories

- control/autoware_external_cmd_selector/include/autoware/external_cmd_selector/external_cmd_selector_node.hpp
- control/autoware_external_cmd_selector/src/autoware_external_cmd_selector/external_cmd_selector_node.cpp
- control/autoware_joy_controller/include/autoware/joy_controller/joy_controller.hpp
- control/autoware_joy_controller/include/autoware/joy_controller/joy_converter/ds4_joy_converter.hpp
- control/autoware_joy_controller/include/autoware/joy_controller/joy_converter/g29_joy_converter.hpp
- control/autoware_joy_controller/include/autoware/joy_controller/joy_converter/joy_converter_base.hpp
- control/autoware_joy_controller/include/autoware/joy_controller/joy_converter/p65_joy_converter.hpp
- control/autoware_joy_controller/include/autoware/joy_controller/joy_converter/xbox_joy_converter.hpp
- control/autoware_joy_controller/src/joy_controller_node.cpp
refactor directory structures of the trajectory followers
https://autowarefoundation.github.io/autoware-documentation/main/contributing/coding-guidelines/ros-nodes/directory-structure/
build and psim tests
Nothing
> refactor(control)!: refactor directory structures of the control interface nodes

- planning/autoware_path_smoother/include/autoware/path_smoother/common_structs.hpp
- planning/autoware_path_smoother/include/autoware/path_smoother/elastic_band.hpp
- planning/autoware_path_smoother/include/autoware/path_smoother/elastic_band_smoother.hpp
- planning/autoware_path_smoother/include/autoware/path_smoother/replan_checker.hpp
- planning/autoware_path_smoother/include/autoware/path_smoother/type_alias.hpp
- planning/autoware_path_smoother/include/autoware/path_smoother/utils/geometry_utils.hpp
- planning/autoware_path_smoother/include/autoware/path_smoother/utils/trajectory_utils.hpp
- planning/autoware_path_smoother/src/elastic_band.cpp
- planning/autoware_path_smoother/src/elastic_band_smoother.cpp
- planning/autoware_path_smoother/src/replan_checker.cpp
- planning/autoware_path_smoother/src/utils/trajectory_utils.cpp
- planning/autoware_path_smoother/test/test_autoware_path_smoother_node_interface.cpp
- planning/autoware_static_centerline_generator/src/centerline_source/optimization_trajectory_based_centerline.cpp
> feat(path_smoother): rename to include/autoware/{package_name}

- planning/autoware_objects_of_interest_marker_interface/include/autoware/objects_of_interest_marker_interface/coloring.hpp
- planning/autoware_objects_of_interest_marker_interface/include/autoware/objects_of_interest_marker_interface/marker_data.hpp
- planning/autoware_objects_of_interest_marker_interface/include/autoware/objects_of_interest_marker_interface/marker_utils.hpp
- planning/autoware_objects_of_interest_marker_interface/include/autoware/objects_of_interest_marker_interface/objects_of_interest_marker_interface.hpp
- planning/autoware_objects_of_interest_marker_interface/src/coloring.cpp
- planning/autoware_objects_of_interest_marker_interface/src/marker_utils.cpp
- planning/autoware_objects_of_interest_marker_interface/src/objects_of_interest_marker_interface.cpp
- planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/interface/scene_module_interface.hpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/include/autoware/behavior_velocity_planner_common/scene_module_interface.hpp
rename to include/autoware/{package_name}
> refactor(objects_of_interest_marker_interface): rename to include/autoware/{package_name}

- .github/CODEOWNERS
- planning/.pages
- planning/behavior_velocity_planner/autoware_behavior_velocity_planner/README.md
- planning/behavior_velocity_planner/autoware_behavior_velocity_run_out_module/README.md
> chore(behavior_velocity_planner): fix CODEOWNERS and page links

- control/autoware_autonomous_emergency_braking/include/autoware/autonomous_emergency_braking/node.hpp
- control/autoware_autonomous_emergency_braking/src/node.cpp
- control/autoware_control_validator/CMakeLists.txt
- control/autoware_control_validator/include/autoware/control_validator/control_validator.hpp
- control/autoware_control_validator/include/autoware/control_validator/debug_marker.hpp
- control/autoware_control_validator/include/autoware/control_validator/utils.hpp
- control/autoware_control_validator/src/control_validator.cpp
- control/autoware_control_validator/src/debug_marker.cpp
- control/autoware_control_validator/src/utils.cpp
- control/autoware_lane_departure_checker/include/autoware/lane_departure_checker/lane_departure_checker.hpp
- control/autoware_lane_departure_checker/include/autoware/lane_departure_checker/lane_departure_checker_node.hpp
- control/autoware_lane_departure_checker/include/autoware/lane_departure_checker/util/create_vehicle_footprint.hpp
- control/autoware_lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker.cpp
- control/autoware_lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker_node.cpp
- control/autoware_shift_decider/include/autoware/shift_decider/autoware_shift_decider.hpp
- control/autoware_shift_decider/src/autoware_shift_decider.cpp
- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/geometric_pull_over.hpp
- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_module.hpp
- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/shift_pull_over.hpp
- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/util.hpp
- planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/parking_departure/geometric_parallel_parking.hpp
- planning/behavior_path_planner/autoware_behavior_path_start_planner_module/include/autoware/behavior_path_start_planner_module/geometric_pull_out.hpp
- planning/behavior_path_planner/autoware_behavior_path_start_planner_module/include/autoware/behavior_path_start_planner_module/shift_pull_out.hpp
- planning/behavior_path_planner/autoware_behavior_path_start_planner_module/include/autoware/behavior_path_start_planner_module/start_planner_module.hpp
refactor directory structures of the trajectory followers
https://autowarefoundation.github.io/autoware-documentation/main/contributing/coding-guidelines/ros-nodes/directory-structure/
build and psim tests
Nothing
> refactor(control)!: refactor directory structures of the control checkers

- planning/autoware_rtc_interface/include/autoware/rtc_interface/rtc_interface.hpp
- planning/autoware_rtc_interface/src/rtc_interface.cpp
- planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/interface/scene_module_interface.hpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/include/autoware/behavior_velocity_planner_common/scene_module_interface.hpp
merge https://github.com/autowarefoundation/autoware.universe/pull/7522 first
> refactor(rtc_interface)!: rename to include/autoware/{package_name}

- planning/autoware_freespace_planner/include/autoware/freespace_planner/freespace_planner_node.hpp
- planning/autoware_mission_planner/src/lanelet2_plugins/default_planner.hpp
- planning/autoware_mission_planner/src/lanelet2_plugins/utility_functions.hpp
- planning/autoware_mission_planner/src/mission_planner/mission_planner.hpp
- planning/autoware_planning_test_manager/include/autoware_planning_test_manager/autoware_planning_test_manager_utils.hpp
- planning/autoware_remaining_distance_time_calculator/src/remaining_distance_time_calculator_node.hpp
- planning/autoware_route_handler/include/autoware/route_handler/route_handler.hpp
- planning/autoware_route_handler/src/route_handler.cpp
- planning/autoware_route_handler/test/test_route_handler.hpp
- planning/autoware_scenario_selector/include/autoware/scenario_selector/node.hpp
- planning/autoware_static_centerline_generator/src/type_alias.hpp
- planning/autoware_static_centerline_generator/src/utils.hpp
- planning/behavior_path_planner/autoware_behavior_path_external_request_lane_change_module/src/manager.hpp
- planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/manager.hpp
- planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/utils.hpp
- planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/data_manager.hpp
- planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/interface/scene_module_interface.hpp
- planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/turn_signal_decider.hpp
- planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/drivable_area_expansion/drivable_area_expansion.hpp
- planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/utils.hpp
- planning/behavior_path_planner/autoware_behavior_path_start_planner_module/include/autoware/behavior_path_start_planner_module/util.hpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/include/autoware/behavior_velocity_planner_common/planner_data.hpp
- planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/decisions.hpp
- planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/lanelets_selection.hpp
- planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/types.hpp
- planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/planner_data.hpp
merge https://github.com/autowarefoundation/autoware.universe/pull/7522 first
> refactor(route_handler)!: rename to include/autoware/{package_name} 

- sensing/livox/livox_tag_filter/src/livox_tag_filter_node/livox_tag_filter_node.cpp
https://github.com/orgs/autowarefoundation/discussions/4876
https://github.com/orgs/autowarefoundation/discussions/4876
build pass
none
none
> refactor(livox): apply clang-tidy check

- planning/autoware_obstacle_cruise_planner/src/planner_interface.cpp
https://github.com/orgs/autowarefoundation/discussions/4876
https://github.com/orgs/autowarefoundation/discussions/4876
https://evaluation.tier4.jp/evaluation/reports/34fd6c81-c497-51d8-a078-994d55f83b23?project_id=prd_jt
none
none
> refactor(obstacle_cruise_planner): apply clang-tidy check

- planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection_collision.cpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/include/autoware/behavior_velocity_planner_common/utilization/util.hpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/src/utilization/util.cpp
https://github.com/orgs/autowarefoundation/discussions/4876
https://github.com/orgs/autowarefoundation/discussions/4876
https://evaluation.tier4.jp/evaluation/reports/34fd6c81-c497-51d8-a078-994d55f83b23?project_id=prd_jt
none
none
> refactor(behavior_velocity_intersection): apply clang-tidy check

- .cppcheck_suppressions
> ci(cppcheck): fix cppcheck suppression list

- .cppcheck_suppressions
> ci(cppcheck): remove unnecessary cppcheck suppressions

- control/autoware_mpc_lateral_controller/src/mpc.cpp
Relax the steering rate constraint when the longitudinal speed is zero.
The steering rate constraint is too strict, hindering the change of the steering angle.
This PR fixes this problem.
`steer_rate_lim: 0.0` (before)
[Screencast from 06-20-2024 10_08_14 AM.webm](https://github.com/autowarefoundation/autoware.universe/assets/80969277/f83feba6-86ec-4d0c-bfa8-185ca1ce2f78)
`steer_rate_lim: 5.0` (after)
[Screencast from 06-20-2024 10_11_32 AM.webm](https://github.com/autowarefoundation/autoware.universe/assets/80969277/90f1cd59-d9ab-4a4b-a432-3a4e83c3aebc)
`steer_rate_lim: 100.0` (was requested but not changed in this PR #7581) 
[Screencast from 06-20-2024 10_16_30 AM.webm](https://github.com/autowarefoundation/autoware.universe/assets/80969277/bde4aca7-ddee-44ab-bb71-c2618c75b791) …
> fix(autoware_mpc_lateral_controller): relax the steering rate constraint at zero speed

- sensing/pointcloud_preprocessor/src/concatenate_data/concatenate_and_time_sync_nodelet.cpp
- sensing/pointcloud_preprocessor/src/concatenate_data/concatenate_pointclouds.cpp
- sensing/pointcloud_preprocessor/src/time_synchronizer/time_synchronizer_nodelet.cpp
This is a fix based on cppcheck `constVariableReference` warnings
```
sensing/pointcloud_preprocessor/src/concatenate_data/concatenate_and_time_sync_nodelet.cpp:152:17: style: Variable 'input_topic' can be declared as reference to const [constVariableReference]
for (auto & input_topic : input_topics_) {
^
sensing/pointcloud_preprocessor/src/concatenate_data/concatenate_pointclouds.cpp:108:17: style: Variable 'input_topic' can be declared as reference to const [constVariableReference]
for (auto & input_topic : input_topics_) {
^
sensing/pointcloud_preprocessor/src/time_synchronizer/time_synchronizer_nodelet.cpp:121:17: style: Variable 'input_topic' can be declared as reference to const [constVariableReference]
for (auto & input_topic : input_topics_) {
^
``` …
> fix(pointcloud_preprocessor): fix constVariableReference warnings

- sensing/gnss_poser/src/gnss_poser_core.cpp
> chore(typo): temoporary => temporary

- .github/workflows/cppcheck-daily.yaml
Ignore test directories on `cppcheck-daily`
> chore(ci): update cppcheck-daily

- system/default_ad_api/src/interface.cpp
- system/default_ad_api/test/node/interface_version.py
Release AD API v1.4.0. See https://github.com/autowarefoundation/autoware-documentation/pull/572 for [release notes](https://autowarefoundation.github.io/autoware-documentation/pr-572/design/autoware-interfaces/ad-api/release/).
> feat(default_ad_api): release adapi v1.4.0

- planning/.pages
- planning/autoware_rtc_interface/README.md
FIx the link to rtc replayer 
None.
None.
None.
None.
> docs(rtc_replayer): fix wrong link

- map/map_loader/src/lanelet2_map_loader/lanelet2_map_visualization_node.cpp
Updating the color of the parking spaces / lot to make them more appealing and neutral looking
- https://github.com/autowarefoundation/autoware.universe/issues/7725
Checking against different color shades.
None.
None.
None.
> style: updating the colors for the parking spaces and lot

- .github/workflows/build-and-test-daily-arm64.yaml
- .github/workflows/build-and-test-daily.yaml
- .github/workflows/build-and-test-differential-arm64.yaml
- .github/workflows/build-and-test-differential.yaml
- .github/workflows/build-and-test.yaml
- sensing/gnss_poser/src/gnss_poser_core.cpp
Fix: https://github.com/autowarefoundation/autoware.universe/actions/runs/9740736192/job/26878461354#step:17:57
- https://github.com/autowarefoundation/autoware.universe/issues/7769
- https://github.com/codecov/codecov-action?tab=readme-ov-file#usage
For forks:
- https://docs.codecov.com/docs/codecov-uploader#if-youre-using-the-action
- > The [Codecov GitHub Action](https://github.com/codecov/codecov-action) is capable of automatically detecting that it is running from a fork and will automatically correctly populate the branch parameter when uploading.
- Should work out of the box but did not test for forks yet.
- https://github.com/autowarefoundation/autoware.universe/pull/7767#issuecomment-2199688434
None.
None.
None.
> ci: add codecov token

- evaluator/autoware_control_evaluator/include/autoware/control_evaluator/control_evaluator_node.hpp
- evaluator/autoware_control_evaluator/launch/control_evaluator.launch.xml
- evaluator/autoware_control_evaluator/package.xml
- evaluator/autoware_control_evaluator/src/control_evaluator_node.cpp
- launch/tier4_control_launch/launch/control.launch.py
This PR adds kinematic state info, current lane id, and arc coordinate info to the /metrics topic. This will facilitate the usage of the DLR.  
Sample: 
- level: "\0"
name: ego_lane_info
message: ''
values:
- key: lane_id
value: '361'
- key: s
value: '256.831547'
- key: t
value: '0.475424'
- level: "\0"
name: kinematic_state
message: ''
values:
- key: vel
value: '0.843630'
- key: acc
value: '0.761389'
- key: jerk
value: '-0.357093'
---
- Link
PSim
See video:
https://github.com/autowarefoundation/autoware.universe/assets/25967964/d330f3f5-245b-4dad-942e-ac7608dab076
https://github.com/autowarefoundation/autoware.universe/assets/25967964/89216948-9121-4f14-9d81-103e6a0f567c
None.
None.
None.
> feat(control_evaluator): add lanelet info to the metrics

- perception/lidar_apollo_instance_segmentation/package.xml
- perception/lidar_apollo_segmentation_tvm/package.xml
- perception/lidar_apollo_segmentation_tvm_nodes/package.xml
Some packages were left without maintainers so I would like to add @YoshiRi as a temporary maintainer (some of the packages may be deprecated soon)
- Link
None.
None.
None.
> chore: add maintainers to the apollo related packages

- perception/object_merger/src/association/data_association.cpp
This is a fix based on cppcheck `knownConditionTrueFalse` warnings
```
perception/object_merger/src/association/data_association.cpp:144:13: style: Condition 'passed_gate' is always true [knownConditionTrueFalse]
if (passed_gate) {
^
perception/object_merger/src/association/data_association.cpp:142:28: note: Assignment 'passed_gate=true', assigned value is 1
bool passed_gate = true;
^
perception/object_merger/src/association/data_association.cpp:144:13: note: Condition 'passed_gate' is always true
if (passed_gate) {
^
```
- Link
None.
None.
None.
> fix(object_merger): fix knownConditionTrueFalse

- perception/radar_object_tracker/src/association/data_association.cpp
```
perception/radar_object_tracker/src/association/data_association.cpp:212:13: style: Condition 'passed_gate' is always true [knownConditionTrueFalse]
if (passed_gate) {
^
perception/radar_object_tracker/src/association/data_association.cpp:210:28: note: Assignment 'passed_gate=true', assigned value is 1
bool passed_gate = true;
^
perception/radar_object_tracker/src/association/data_association.cpp:212:13: note: Condition 'passed_gate' is always true
if (passed_gate) {
^
```
- Link
None.
None.
None.
> fix(radar_object_tracker): fix knownConditionTrueFalse

- perception/tracking_object_merger/src/association/data_association.cpp
```
perception/tracking_object_merger/src/association/data_association.cpp:194:9: style: Condition 'passed_gate' is always true [knownConditionTrueFalse]
if (passed_gate) {
^
perception/tracking_object_merger/src/association/data_association.cpp:192:24: note: Assignment 'passed_gate=true', assigned value is 1
bool passed_gate = true;
^
perception/tracking_object_merger/src/association/data_association.cpp:194:9: note: Condition 'passed_gate' is always true
if (passed_gate) {
^
```
- Link
None.
None.
None.
> fix(tracking_object_merger): fix knownConditionTrueFalse

- perception/multi_object_tracker/src/data_association/data_association.cpp
This is a fix based on cppcheck `knownConditionTrueFalse` warnings
```
perception/multi_object_tracker/src/data_association/data_association.cpp:179:13: style: Condition 'passed_gate' is always true [knownConditionTrueFalse]
if (passed_gate) {
^
perception/multi_object_tracker/src/data_association/data_association.cpp:177:28: note: Assignment 'passed_gate=true', assigned value is 1
bool passed_gate = true;
^
perception/multi_object_tracker/src/data_association/data_association.cpp:179:13: note: Condition 'passed_gate' is always true
if (passed_gate) {
^
```
- Link
None.
None.
None.
> fix(multi_object_tracker): fix knownConditionTrueFalse

- .github/workflows/cppcheck-differential.yaml
- launch/tier4_control_launch/launch/control.launch.py
This is a fix for false positive of cppcheck-differential
https://github.com/autowarefoundation/autoware.universe/actions/runs/9786372157/job/27022156208?pr=7682
- Link
https://github.com/autowarefoundation/autoware.universe/actions/runs/9788189074/job/27025844992?pr=7829
None.
None.
None.
> fix(ci): skip when modified package has no cpp/hpp files

- .github/CODEOWNERS
Add 2 new codeowners to some packages of the `motion_velocity_planner` .
- Link
None.
None.
None.
> chore(motion_velocity_planner): add new codeowners

- perception/tensorrt_yolox/src/tensorrt_yolox.cpp
This is a fix based on cppcheck `knownConditionTrueFalse` warnings
```
perception/tensorrt_yolox/src/tensorrt_yolox.cpp:512:7: style: Condition 'letterbox' is always true [knownConditionTrueFalse]
if (letterbox) {
^
perception/tensorrt_yolox/src/tensorrt_yolox.cpp:511:20: note: Assignment 'letterbox=true', assigned value is 1
bool letterbox = true;
^
perception/tensorrt_yolox/src/tensorrt_yolox.cpp:512:7: note: Condition 'letterbox' is always true
if (letterbox) {
^
perception/tensorrt_yolox/src/tensorrt_yolox.cpp:655:7: style: Condition 'letterbox' is always true [knownConditionTrueFalse]
if (letterbox) {
^
perception/tensorrt_yolox/src/tensorrt_yolox.cpp:653:20: note: Assignment 'letterbox=true', assigned value is 1
bool letterbox = true;
^ …
```
> fix(tensorrt_yolox): fix knownConditionTrueFalse

- evaluator/autoware_planning_evaluator/include/autoware/planning_evaluator/planning_evaluator_node.hpp
- evaluator/autoware_planning_evaluator/src/planning_evaluator_node.cpp
This PR adds polling subscribers for the planning evaluator
- Link
PSim
ros2 topic echo /diagnostic/planning_evaluator/metrics -> Example:
---
header:
stamp:
sec: 1720056519
nanosec: 946113057
frame_id: ''
status:
- level: "\0"
name: ego_lane_info
message: ''
values:
- key: lane_id
value: '173483'
- key: s
value: '234.875044'
- key: t
value: '-1.072408'
- level: "\0"
name: kinematic_state
message: ''
values:
- key: vel
value: '3.372105'
- key: acc
value: '0.113005'
- key: jerk
value: '-0.116732'
- level: "\0"
name: curvature
message: ''
values:
- key: min
value: '-0.017109219101186311'
- key: max
value: '0.044968926638249571'
- key: mean
value: '-0.00118892212238621448351'
... …
> feat(planning_evaluator): add planning evaluator polling sub

- planning/motion_velocity_planner/autoware_motion_velocity_planner_node/src/node.cpp
- planning/motion_velocity_planner/autoware_motion_velocity_planner_node/src/node.hpp
> fix(motion_planning): fix processing time topic names

- launch/tier4_perception_launch/package.xml
Add @technolojin as maintainer of tier4_perception_launch
None.
None.
None.
> refactor(tier4_perception_launch): add maintainer to tier4_perception_launch

- launch/tier4_planning_launch/launch/scenario_planning/lane_driving/motion_planning/motion_planning.launch.xml
- planning/sampling_based_planner/autoware_frenet_planner/src/frenet_planner/frenet_planner.cpp
> fix(frenet_planner): fix mistake in the curvature calculation

- .github/workflows/cppcheck-differential.yaml
- common/perception_utils/package.xml
Ignore a package which contains only hpp files in cppcheck-differential.
A bug happend here: 
https://github.com/autowarefoundation/autoware.universe/actions/runs/9885752229/job/27304337550?pr=7899
Confirmed that cppcheck-run-step is skipped for `perception_util` package
https://github.com/autowarefoundation/autoware.universe/actions/runs/9886483884/job/27306342212?pr=7961
None.
None.
None.
> fix(ci): ignore only-hpp-package in cppcheck-differential

- planning/behavior_path_planner/autoware_behavior_path_sampling_planner_module/src/manager.cpp
- planning/behavior_path_planner/autoware_behavior_path_sampling_planner_module/src/sampling_planner_module.cpp
```
planning/behavior_path_planner/autoware_behavior_path_sampling_planner_module/src/manager.cpp:87:17: style: Local variable 'ns' shadows outer variable [shadowVariable]
std::string ns{"constraints.hard"};
^
planning/behavior_path_planner/autoware_behavior_path_sampling_planner_module/src/manager.cpp:97:17: style: Local variable 'ns' shadows outer variable [shadowVariable]
std::string ns{"sampling"};
^
planning/behavior_path_planner/autoware_behavior_path_sampling_planner_module/src/manager.cpp:120:17: style: Local variable 'ns' shadows outer variable [shadowVariable]
std::string ns{"preprocessing"};
^
planning/behavior_path_planner/autoware_behavior_path_sampling_planner_module/src/sampling_planner_module.cpp:556:19: style: Local …
```
> fix(autoware_behavior_path_sampling_planner_module): fix shadowVariable

- planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp
- planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp
```
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp:1448:20: style: Local variable 'debug_print' shadows outer variable [shadowVariable]
const auto debug_print = [&](const auto & s) {
^
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp:895:32: style: Local variable 'sub_type' shadows outer variable [shadowVariable]
const lanelet::Attribute sub_type = ll.attribute(lanelet::AttributeName::Subtype);
^
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp:916:32: style: Local variable 'sub_type' shadows outer variable [shadowVariable]
const lanelet::Attribute sub_type = ll.attribute(lanelet::AttributeName::Subtype);
^ …
```
> fix(autoware_behavior_path_lane_change_module): fix shadowVariable

- planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection.cpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection_prepare_data.cpp
```
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection.cpp:395:22: style: Local variable 'closest_idx' shadows outer variable [shadowVariable]
const auto closest_idx = intersection_stoplines.closest_idx;
^
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection_prepare_data.cpp:692:24: style: Local variable 'inserted' shadows outer variable [shadowVariable]
const auto & inserted = detection_ids.insert(l.id());
^
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection_prepare_data.cpp:713:24: style: Local variable 'inserted' shadows outer variable [shadowVariable]
const auto & inserted …
```
> fix(autoware_behavior_velocity_intersection_module): fix shadowVariable

- launch/tier4_simulator_launch/launch/simulator.launch.xml
- launch/tier4_system_launch/launch/system.launch.xml
- system/autoware_processing_time_checker/CMakeLists.txt
- system/autoware_processing_time_checker/README.md
- system/autoware_processing_time_checker/config/processing_time_checker.param.yaml
- system/autoware_processing_time_checker/launch/processing_time_checker.launch.xml
- system/autoware_processing_time_checker/package.xml
- system/autoware_processing_time_checker/schema/duplicated_node_checker.schema.json
- system/autoware_processing_time_checker/schema/processing_time_checker.schema.json
- system/autoware_processing_time_checker/src/processing_time_checker.cpp
- system/autoware_processing_time_checker/src/processing_time_checker.hpp
launcher PR: https://github.com/autowarefoundation/autoware_launch/pull/1072
Added a processing_time_checker to publish diagnotics for the processing time using the input of the processing time of each module.
The default config tracks the following modules.
```
[processing_time_checker_node-1] lateral
[processing_time_checker_node-1] longitudinal
[processing_time_checker_node-1] lane_departure_checker_node
[processing_time_checker_node-1] map_based_prediction
[processing_time_checker_node-1] multi_object_tracker
[processing_time_checker_node-1] planning_validator
[processing_time_checker_node-1] avoidance_by_lane_change
[processing_time_checker_node-1] dynamic_obstacle_avoidance
[processing_time_checker_node-1] goal_planner
[processing_time_checker_node-1] lane_change_left …
```
> feat(processing_time_checker): add a new package

- localization/localization_error_monitor/README.md
fix input description of localization_error_monitor
None.
None.
None.
None.
> docs(localization_error_monitor): fix input description of localization_error_monitor

- launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.xml
- planning/behavior_path_planner/autoware_behavior_path_avoidance_by_lane_change_module/src/scene.cpp
- planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/scene.hpp
- planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/base_class.hpp
- planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/data_structs.hpp
- planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/path.hpp
- planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/utils.hpp
- planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/interface.cpp
- planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp
- planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp
Creating polygon is expensive. Due to creation of lanes polygon at multiple different place, it increases the computational time. 
With this PR, computational time can be reduces up to 10ms when there's no lanes updated.
Before PR: More spikes on the computation
After PR: Less spikes
- Link
None.
None.
None.
> refactor(lane_change): update lanes and its polygons only  when it's updated

- planning/autoware_velocity_smoother/include/autoware/velocity_smoother/node.hpp
- planning/autoware_velocity_smoother/include/autoware/velocity_smoother/smoother/analytical_jerk_constrained_smoother/analytical_jerk_constrained_smoother.hpp
- planning/autoware_velocity_smoother/include/autoware/velocity_smoother/smoother/jerk_filtered_smoother.hpp
- planning/autoware_velocity_smoother/include/autoware/velocity_smoother/smoother/l2_pseudo_jerk_smoother.hpp
- planning/autoware_velocity_smoother/include/autoware/velocity_smoother/smoother/linf_pseudo_jerk_smoother.hpp
- planning/autoware_velocity_smoother/include/autoware/velocity_smoother/smoother/smoother_base.hpp
- planning/autoware_velocity_smoother/src/node.cpp
- planning/autoware_velocity_smoother/src/smoother/analytical_jerk_constrained_smoother/analytical_jerk_constrained_smoother.cpp
- planning/autoware_velocity_smoother/src/smoother/jerk_filtered_smoother.cpp
- planning/autoware_velocity_smoother/src/smoother/l2_pseudo_jerk_smoother.cpp
- planning/autoware_velocity_smoother/src/smoother/linf_pseudo_jerk_smoother.cpp
- planning/autoware_velocity_smoother/src/smoother/smoother_base.cpp
Added a time_keeper in velocity_smoother
- Link
psim worked.
`ros2 run autoware_debug_tools processing_time_visualizer` shows below.
```
onCurrentTrajectory: 11.59 [ms]
├── calcExternalVelocityLimit: 0.00 [ms]
├── updateDataForExternalVelocityLimit: 0.01 [ms]
└── calcTrajectoryVelocity: 11.39 [ms]
├── applyExternalVelocityLimit: 0.01 [ms]
├── applyStopApproachingVelocity: 0.00 [ms]
└── smoothVelocity: 11.37 [ms]
├── calcInitialMotion: 0.00 [ms]
├── applyLateralAccelerationFilter: 1.18 [ms]
├── applySteeringRateLimit: 0.21 [ms]
├── resampleTrajectory: 3.49 [ms]
├── apply: 6.39 [ms]
│   ├── forwardJerkFilter: 0.15 [ms]
│   ├── backwardJerkFilter: 0.20 [ms]
│   │   └── forwardJerkFilter: 0.15 [ms]
│   ├── mergeFilteredTrajectory: 0.03 [ms]
│ …
```
> feat(velocity_smoother): add time_keeper

- planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/README.md
- planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/config/static_obstacle_avoidance.param.yaml
- planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/data_structs.hpp
- planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/parameter_helper.hpp
- planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/schema/static_obstacle_avoidance.schema.json
- planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/manager.cpp
- planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp
In previous implementation, unknown obejct was handled as vehicle type object. In this PR, I fixed filtering logic to separate flow for UNKNOWN.
:warning: Please merge this PR with https://github.com/autowarefoundation/autoware_launch/pull/1074.
In freespace area, sometimes there is a vehicle which is NOT along lanelet because actually real lane doesn't exit in most of cases. But this module filtered vehicle in private freespace same as vehicles which are on public road. As a result, this module didn't avoid parked vehicle in following situation because this module deals with it as MERGING vehicle.
In this PR, I changed logic to avoid object which is NOT on ego lane regardless of its angle.
- Link
None.
None.
None.
> fix(static_obstacle_avoidance): fix issues in target filtiering logic

- planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp
Integrate time_keeper to static obstacle avoidance module.
- Link
Psim
```
---
nodes:
- id: 1
name: static_obstacle_avoidance=>run
processing_time: 8.37
parent_id: 0
- id: 2
name: updateData
processing_time: 5.357
parent_id: 1
- id: 3
name: fillFundamentalData
processing_time: 2.897
parent_id: 2
- id: 4
name: extendBackwardLength
processing_time: 0.246
parent_id: 3
- id: 5
name: fillAvoidanceTargetObjects
processing_time: 1.214
parent_id: 3
- id: 6
name: createObjectData
processing_time: 0.015
parent_id: 5
- id: 7
name: fillAvoidanceTargetData
processing_time: 0.005
parent_id: 3
- id: 8
name: calcDistanceToStopLine
processing_time: 0.002
parent_id: 7
- id: 9
name: fillShiftLine
processing_time: 1.657
parent_id: 2
- id: 10
name: isValidShiftLine
processing_time: 0.621 …
```
> feat(static_obstacle_avoidance): integrate time keeper to major functions

- vehicle/autoware_steer_offset_estimator/Readme.md
Current documentation page is broken. This PR fixes it.
https://autowarefoundation.github.io/autoware.universe/main/vehicle/autoware_steer_offset_estimator/Readme/
> fix(steer_offset_estimator): fix link to json schema in README

- planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/include/autoware/behavior_velocity_planner_common/scene_module_interface.hpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/src/scene_module_interface.cpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_stop_line_module/src/scene.cpp
Add time_keeper to behavior_velocity_planner and apply this to stop_line_module.
```
SceneModuleManagerInterface::modifyPathVelocity: 0.30 [ms]
├── modifyPathVelocity (lane_id:=36222): 0.06 [ms]
│   ├── createTargetPoint: 0.00 [ms]
│   └── calcSegmentIndexFromPointIndex & findEgoSegmentIndex & calcSignedArcLength: 0.03 [ms]
├── modifyPathVelocity (lane_id:=30339): 0.06 [ms]
│   ├── createTargetPoint: 0.00 [ms]
│   └── calcSegmentIndexFromPointIndex & findEgoSegmentIndex & calcSignedArcLength: 0.03 [ms]
├── modifyPathVelocity (lane_id:=30617): 0.06 [ms]
│   ├── createTargetPoint: 0.00 [ms]
│   └── calcSegmentIndexFromPointIndex & findEgoSegmentIndex & calcSignedArcLength: 0.03 [ms]
└── modifyPathVelocity (lane_id:=30346): 0.06 [ms]
├── createTargetPoint: 0.00 [ms]
└── …
```
> feat(autoware_behavior_velocity_planner_common,autoware_behavior_velocity_stop_line_module): add time_keeper to bvp

- perception/ground_segmentation/src/ray_ground_filter/node.cpp
- perception/ground_segmentation/src/ray_ground_filter/node.hpp
- perception/ground_segmentation/src/scan_ground_filter/node.cpp
- perception/ground_segmentation/src/scan_ground_filter/node.hpp
```
perception/ground_segmentation/src/ray_ground_filter/node.cpp:262:78: style: Parameter 'out_cloud_msg_ptr' can be declared as reference to const [constParameterReference]
const PointCloud2::ConstSharedPtr & in_cloud_ptr, PointCloud2::SharedPtr & out_cloud_msg_ptr)
^
perception/ground_segmentation/src/ray_ground_filter/node.cpp:274:71: style: Parameter 'in_indices' can be declared as reference to const [constParameterReference]
const PointCloud2::ConstSharedPtr in_cloud_ptr, pcl::PointIndices & in_indices,
^
perception/ground_segmentation/src/scan_ground_filter/node.cpp:248:34: style: Parameter 'p_orig_point' can be declared as reference to const [constParameterReference]
PointData & p, pcl::PointXYZ & p_orig_point, const …
```
> fix(ground_segmentation): fix constParameterReference

- launch/tier4_perception_launch/package.xml
I delete unnecessary dependency
None
None
None.
None.
None.
> fix(tier4_perception_launch): delete unnecessary dependency

- control/autoware_control_validator/README.md
- control/autoware_control_validator/src/control_validator.cpp
fix some misses in a previous PR
fixed doc link
https://autowarefoundation.github.io/autoware.universe/pr-8104/control/autoware_control_validator/
https://github.com/autowarefoundation/autoware.universe/pull/7806
psim test
None.
None.
None.
> fix(control_validator): fix param names and doc

- planning/autoware_rtc_interface/include/autoware/rtc_interface/rtc_interface.hpp
- planning/autoware_rtc_interface/src/rtc_interface.cpp
- planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/interface/scene_module_interface.hpp
Exclude the cooperate statuses whose state is SUCCEEDED or FAILDED from `isActivate()` check. 
```c++
bool existApprovedRequest() const
{
return std::any_of(
rtc_interface_ptr_map_.begin(), rtc_interface_ptr_map_.end(), [&](const auto & rtc) {
if (!rtc.second->isRegistered(uuid_map_.at(rtc.first))) {
return false;
}
if (rtc.second->isTerminated(uuid_map_.at(rtc.first))) {
return true;
}
return rtc.second->isActivated(uuid_map_.at(rtc.first));
});
}
bool existNotApprovedRequest() const
{
return std::any_of(
rtc_interface_ptr_map_.begin(), rtc_interface_ptr_map_.end(), [&](const auto & rtc) {
return rtc.second->isRegistered(uuid_map_.at(rtc.first)) &&
!rtc.second->isActivated(uuid_map_.at(rtc.first)) &&
!rtc.second->isTerminated(uuid_map_.at(rtc.first));
});
}
```
- Link …
> fix(bpp, rtc_interface): fix state transition

- planning/autoware_rtc_interface/src/rtc_interface.cpp
Fixes RTC interface build error due to [PR](https://github.com/autowarefoundation/autoware.universe/pull/7743).
https://github.com/autowarefoundation/autoware.universe/pull/7743
https://github.com/autowarefoundation/autoware.universe/pull/8094
Successfully build and Pass CI/CD
None.
None.
None.
> fix(rtc_interface): fix build error

- system/diagnostic_graph_aggregator/src/common/graph/config.cpp
- system/diagnostic_graph_aggregator/src/common/graph/loader.cpp
- system/diagnostic_graph_aggregator/src/common/graph/units.cpp
```
system/diagnostic_graph_aggregator/src/common/graph/config.cpp:267:21: style: Variable 'unit' can be declared as pointer to const [constVariableReference]
for (const auto & unit : units) {
^
system/diagnostic_graph_aggregator/src/common/graph/config.cpp:268:22: style: Variable 'link' can be declared as pointer to const [constVariableReference]
if (const auto & link = unit->item) ++degrees[link->child];
^
system/diagnostic_graph_aggregator/src/common/graph/config.cpp:269:23: style: Variable 'link' can be declared as pointer to const [constVariableReference]
for (const auto & link : unit->list) ++degrees[link->child];
^
system/diagnostic_graph_aggregator/src/common/graph/loader.cpp:62:21: style: Variable 'config' can be …
```
> fix(diagnostic_graph_aggregator): fix constVariableReference

- tools/reaction_analyzer/src/subscriber.cpp
```
tools/reaction_analyzer/src/subscriber.cpp:275:12: style: Variable 'buffer' can be declared as reference to const [constVariableReference]
auto & buffer = std::get<MessageBuffer>(variant);
^
tools/reaction_analyzer/src/subscriber.cpp:366:12: style: Variable 'buffer' can be declared as reference to const [constVariableReference]
auto & buffer = std::get<MessageBuffer>(variant);
^
tools/reaction_analyzer/src/subscriber.cpp:443:12: style: Variable 'buffer' can be declared as reference to const [constVariableReference]
auto & buffer = std::get<MessageBuffer>(variant);
^
tools/reaction_analyzer/src/subscriber.cpp:523:12: style: Variable 'buffer' can be declared as reference to const [constVariableReference]
auto & buffer = …
```
> fix(reaction_analyzer): fix constVariableReference

- perception/detected_object_validation/src/lanelet_filter/lanelet_filter.cpp
- perception/detected_object_validation/src/lanelet_filter/lanelet_filter.hpp
This PR is to use the [`search`](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/4789fde6c3bafcd5a8d721d11c5d92870ca59a22/lanelet2_core/include/lanelet2_core/LaneletMap.h#L172) method instead of searching the intersected lanelets by iterating with a for loop.
Changes:
- `getIntersectedLanelets`: change to use `search`
- `objectCallback`: merge to single call of `getIntersectedLanelets`,
- `filterObject`: merge conditions of `intersected_road_lanelets` and `intersected_shoulder_lanelets`
- `lanelet_filter.hpp`: remove unused var and fix method args
- Link
Checked by comparing the fetched intersected lanelet number in the autoware [sample scene](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/rosbag-replay-simul …
> fix(detected_object_validation): use search for searching intersected lanelet

- planning/autoware_velocity_smoother/package.xml
Add maintainer to velocity_smoother package.
None
Not applicable
None.
None.
None.
> chore(velocity_smoother): add maintainer 

- control/autoware_vehicle_cmd_gate/src/vehicle_cmd_gate.hpp
```
control/autoware_vehicle_cmd_gate/src/vehicle_cmd_gate.cpp:466:62: style: inconclusive: Function 'publishControlCommands' argument 1 names different: declaration 'input_msg' definition 'commands'. [funcArgNamesDifferent]
void VehicleCmdGate::publishControlCommands(const Commands & commands)
^
control/autoware_vehicle_cmd_gate/src/vehicle_cmd_gate.cpp:603:62: style: inconclusive: Function 'filterControlCommand' argument 1 names different: declaration 'msg' definition 'in'. [funcArgNamesDifferent]
Control VehicleCmdGate::filterControlCommand(const Control & in)
^
```
- Link
None.
None.
None.
> fix(autoware_vehicle_cmd_gate): fix funcArgNamesDifferent

- sensing/radar_threshold_filter/src/radar_threshold_filter_node.hpp
```
sensing/radar_threshold_filter/src/radar_threshold_filter_node.cpp:117:71: style: inconclusive: Function 'onData' argument 1 names different: declaration 'msg' definition 'radar_msg'. [funcArgNamesDifferent]
void RadarThresholdFilterNode::onData(const RadarScan::ConstSharedPtr radar_msg)
^
```
- Link
None.
None.
None.
> fix(radar_threshold_filter): fix funcArgNamesDifferent

- perception/probabilistic_occupancy_grid_map/src/fusion/synchronized_grid_map_fusion_node.cpp
```
perception/probabilistic_occupancy_grid_map/src/fusion/synchronized_grid_map_fusion_node.cpp:43:27: style: Condition 'num_input_topics_<1' is always false [knownConditionTrueFalse]
if (num_input_topics_ < 1) {
^
perception/probabilistic_occupancy_grid_map/src/fusion/synchronized_grid_map_fusion_node.cpp:39:28: note: Assuming that condition 'input_topics_.empty()' is not redundant
if (input_topics_.empty()) {
^
perception/probabilistic_occupancy_grid_map/src/fusion/synchronized_grid_map_fusion_node.cpp:42:43: note: Assignment 'num_input_topics_=input_topics_.size()', assigned value is greater than 0
num_input_topics_ = input_topics_.size();
^
perception/probabilistic_occupancy_grid_map/src/fusion/synchronized_grid_map_fus …
```
> fix(probabilistic_occupancy_grid_map): fix knownConditionTrueFalse warning

- sensing/autoware_pointcloud_preprocessor/src/downsample_filter/robin_hood.h
```
sensing/autoware_pointcloud_preprocessor/src/downsample_filter/robin_hood.h:2498:13: style: Condition '!increase_size()' is always false [knownConditionTrueFalse]
if (!increase_size()) {
^
sensing/autoware_pointcloud_preprocessor/src/downsample_filter/robin_hood.h:2498:27: note: Calling function 'increase_size' returns 1
if (!increase_size()) {
^
sensing/autoware_pointcloud_preprocessor/src/downsample_filter/robin_hood.h:2498:13: note: Condition '!increase_size()' is always false
if (!increase_size()) {
^
```
- Link
None.
None.
None.
> fix(autoware_pointcloud_preprocessor): fix knownConditionTrueFalse warning

- planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/src/scene.hpp
```
planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/src/scene.cpp:390:58: style: inconclusive: Function 'cutPredictPathWithDuration' argument 2 names different: declaration 'object' definition 'object_original'. [funcArgNamesDifferent]
const autoware_perception_msgs::msg::PredictedObject & object_original,
^
planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/src/scene.cpp:413:52: style: inconclusive: Function 'isOverPassJudge' argument 1 names different: declaration 'path' definition 'input_path'. [funcArgNamesDifferent]
const tier4_planning_msgs::msg::PathWithLaneId & input_path,
^
planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/src/sc …
```
> fix(autoware_behavior_velocity_blind_spot_module): fix funcArgNamesDifferent

- control/autoware_mpc_lateral_controller/src/lowpass_filter.cpp
- control/autoware_mpc_lateral_controller/src/mpc_lateral_controller.cpp
This is a fix based on cppcheck warnings
```
control/autoware_mpc_lateral_controller/src/lowpass_filter.cpp:66:10: style: The scope of the variable 'y0' can be reduced. [variableScope]
double y0 = 0.0;
^
control/autoware_mpc_lateral_controller/src/lowpass_filter.cpp:67:10: style: The scope of the variable 'u0' can be reduced. [variableScope]
double u0 = 0.0;
^
control/autoware_mpc_lateral_controller/src/lowpass_filter.cpp:66:13: style: Variable 'y0' is assigned a value that is never used. [unreadVariable]
double y0 = 0.0;
^
control/autoware_mpc_lateral_controller/src/lowpass_filter.cpp:67:13: style: Variable 'u0' is assigned a value that is never used. [unreadVariable]
double u0 = 0.0;
^
control/autoware_mpc_lateral_controller/src/mpc_lateral_controller.cpp:584:10: style: The scope of the …
```
> fix(autoware_mpc_lateral_controller): fix cppcheck warnings

- simulator/simple_planning_simulator/src/simple_planning_simulator/vehicle_model/sim_model_actuation_cmd.cpp
fix acceleration of actuation simulator.
Currently, the derivative of acceleration was calculated from the acceleration command only. This can result in inappropriate values (e.g., 0) for the published acceleration topic. Calculate the derivative of acceleration based on the current acceleration state and indication as in other models.
- Link
- unit test 
- psim
None.
None.
None.
> fix(simple_planning_simulator): fix publised acc of actuation simulator

- .github/CODEOWNERS
Fix typo of CODEOWNERS
- Link
None.
None.
None.
> fix(autoware_lidar_apollo_instance_segmentation): fix typo of CODEOWNERS

- planning/autoware_path_optimizer/include/autoware/path_optimizer/utils/trajectory_utils.hpp
- planning/autoware_path_optimizer/src/utils/trajectory_utils.cpp
```
planning/autoware_path_optimizer/src/utils/trajectory_utils.cpp:139:38: performance: Function parameter 'traj_points' should be passed by const reference. [passedByValue]
const std::vector<TrajectoryPoint> traj_points, const double interval)
^
planning/autoware_path_optimizer/src/utils/trajectory_utils.cpp:151:38: performance: Function parameter 'traj_points' should be passed by const reference. [passedByValue]
const std::vector<TrajectoryPoint> traj_points, const double interval)
^
planning/autoware_path_optimizer/src/utils/trajectory_utils.cpp:162:37: performance: Function parameter 'ref_points' should be passed by const reference. [passedByValue]
const std::vector<ReferencePoint> ref_points, const double interval)
^ …
```
> fix(autoware_path_optimizer): fix passedByValue

- common/tier4_localization_rviz_plugin/package.xml
add maintainer and author for tier4_localization_rviz_plugin
- Link
None.
None.
None.
> chore(tier4_localization_rviz_plugin): add maintainer and author

- planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/interface.cpp
Once the cooperateStatus for lane change was deactivated, the module state transits to `WAITING_APPROVAL` from `RUNNING`. This causes a problem when the auto mode is changed to manual when triggering force deactivation: approve from operators would be needed to trigger the lane change since the UUID in the RTC interface would not be changed.
This PR changes the state to `FAILURE` once it is force deactivated in the lane change preparing phase , and solves the above problem by restarting the lane change module; this would publish a new UUID in the RTC interface with the auto mode set to true.
[RTC force deactivate](https://github.com/autowarefoundation/autoware.universe/pull/8221)
Psim + RTC manager
[Before:](https://github.com/user-attachments/assets/c01b9db5-1edc-49c7-a64b-8ef8641a797d) …
> feat(lane_change): force deactivation in prepare phase

- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp
> feat(goal_planner): add time keeper

- planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/path_safety_checker/safety_check.hpp
- planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_safety_checker/safety_check.cpp
Calculate the distance between the object and the footprint at orientation when the object is minimum/maximum at the point of ego on the path, respectively. For each of them, return a pair to determine if they are within the margin or not, and make a collision judgment.
Intended use
- If it's safe at min_distance, it's safe
- If max_distance is unsafe, it's unsafe.
- Otherwise, use precise collision check check (e.g. footprint polygon)
- Link
psim
None.
None.
None.
> feat(path_safety_checker): add rough collision check

- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_module.hpp
- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/pull_over_planner_base.hpp
- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/util.hpp
- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/freespace_pull_over.cpp
- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/geometric_pull_over.cpp
- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp
- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/shift_pull_over.cpp
reduce proccesing time
- Filter objects in advance.
- (the most effective part in this PR)
- Calculate path curvature in advance
- rough collision check 
- https://github.com/autowarefoundation/autoware.universe/pull/8193 
- If it's safe at min_distance, it's safe
- If max_distance is unsafe, it's unsafe.
- Otherwise, use footprint to make the decision,
when `needPathUpdate()`  (once per 1s)
before:
60-70ms 
after:
20-30ms 
object is not related to the time so much.
not when `needPathUpdate()`  
after
~10 ms
- Link
- https://tier4.atlassian.net/browse/RT1-6970
psim
2024/07/25 https://evaluation.tier4.jp/evaluation/reports/04c830e5-290e-5a36-8702-526a5fba407d/?project_id=prd_jt
3589/3590
None.
None.
None.
> perf(goal_planner): reduce processing time 

- simulator/learning_based_vehicle_model/include/learning_based_vehicle_model/model_connections_helpers.hpp
- simulator/learning_based_vehicle_model/src/model_connections_helpers.cpp
```
simulator/learning_based_vehicle_model/src/model_connections_helpers.cpp:18:78: performance: Function parameter 'map' should be passed by const reference. [passedByValue]
std::vector<double> vector1, std::vector<double> vector2, std::vector<int> map, bool inverse)
^
simulator/learning_based_vehicle_model/src/model_connections_helpers.cpp:30:23: performance: Function parameter 'connection_names_1' should be passed by const reference. [passedByValue]
std::vector<char *> connection_names_1, std::vector<char *> connection_names_2)
^
simulator/learning_based_vehicle_model/src/model_connections_helpers.cpp:30:63: performance: Function parameter 'connection_names_2' should be passed by const reference. [passedByValue]
std::vector<char *> …
```
> fix(learning_based_vehicle_model): fix passedByValue

- planning/behavior_velocity_planner/autoware_behavior_velocity_occlusion_spot_module/src/debug.cpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_occlusion_spot_module/src/occlusion_spot_utils.cpp
```
planning/behavior_velocity_planner/autoware_behavior_velocity_occlusion_spot_module/src/debug.cpp:134:53: performance: Function parameter 'ns' should be passed by const reference. [passedByValue]
const BasicPolygons & polygons, const std::string ns, const int id, const double z)
^
planning/behavior_velocity_planner/autoware_behavior_velocity_occlusion_spot_module/src/debug.cpp:162:48: performance: Function parameter 'ns' should be passed by const reference. [passedByValue]
const Polygons2d & slices, const std::string ns, const int id, const double z)
^
planning/behavior_velocity_planner/autoware_behavior_velocity_occlusion_spot_module/src/occlusion_spot_utils.cpp:105:30: performance: Function parameter 'pc1' should be passed by …
```
> fix(autoware_behavior_velocity_occlusion_module): fix passedByValue

- planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/parking_departure/geometric_parallel_parking.cpp
Assuming parallel poses, calculate the approximate start pose on the centerline from the goal pose. After that align start pose on the centerline
before
after
- Link
- https://tier4.atlassian.net/browse/RT1-7303
psim
2024/08/02 https://evaluation.tier4.jp/evaluation/reports/d1593110-9f0e-5abb-9f19-18733fc8b0da/?project_id=prd_jt
None.
None.
None.
> fix(start/goal_planner): align geometric parall parking start pose with center line

- README.md
Add codecov badge.
- Link
None.
None.
None.
> chore(readme): add codecov badge

- planning/behavior_path_planner/autoware_behavior_path_lane_change_module/package.xml
Add @maxime-clem as codeowner
- Link
Build CI succeed
None.
None.
None.
> chore(lane_change): add codeowner

- planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp
Current debug print doesn't provide enough  information of the paths. 
Furthermore, RCLCPP_DEBUG_STREAM cannot be used with logging level configure tools.
So in this PR, these two items are addressed.
Depends on https://github.com/autowarefoundation/autoware.universe/pull/8357
- Link
PSIM
None.
None.
None.
> refactor(lane_change): refactor  debug print when  computing paths

- perception/autoware_map_based_prediction/src/map_based_prediction_node.cpp
remove unecessary calculation
- Link
worst case reduced from 30ms to 20ms
before 
```
objectsCallback: 30.16 [ms], run count: 1
├── trafficSignalsCallback: 0.01 [ms], run count: 1
├── removeStaleTrafficLightInfo: 0.00 [ms], run count: 1
├── updateObjectData: 0.00 [ms], run count: 22
├── getCurrentLanelets: 2.52 [ms], run count: 22
│   ├── checkCloseLaneletCondition: 0.85 [ms], run count: 220
│   ├── isDuplicated: 0.00 [ms], run count: 22
│   └── calculateLocalLikelihood: 0.14 [ms], run count: 17
├── updateRoadUsersHistory: 0.16 [ms], run count: 22
├── getPredictedReferencePath: 2.95 [ms], run count: 9
│   ├── predictObjectManeuver: 0.15 [ms], run count: 7
│   │   └── predictObjectManeuverByLatDiffDistance: 0.13 [ms], run count: 7
│   │ …
```
> perf(map_based_prediction): remove unncessary withinRoadLanelet()

- planning/motion_velocity_planner/autoware_motion_velocity_dynamic_obstacle_stop_module/CMakeLists.txt
- planning/motion_velocity_planner/autoware_motion_velocity_dynamic_obstacle_stop_module/package.xml
- planning/motion_velocity_planner/autoware_motion_velocity_dynamic_obstacle_stop_module/src/object_filtering.cpp
- planning/motion_velocity_planner/autoware_motion_velocity_dynamic_obstacle_stop_module/src/object_filtering.hpp
- planning/motion_velocity_planner/autoware_motion_velocity_dynamic_obstacle_stop_module/src/types.hpp
- planning/motion_velocity_planner/autoware_motion_velocity_dynamic_obstacle_stop_module/test/test_object_filtering.cpp
Refactor and add tests for the dynamic object filtering of the `dynamic_obstacle_stop` module.
A few bugs are also fixed.
- [TIER IV internal link (Evaluator)](https://evaluation.tier4.jp/evaluation/reports/2f14d3c3-7969-5909-8bbb-af5b0e8282e6?project_id=prd_jt)
Scenarios and unit tests
None.
None.
None.
> test(dynamic_obstacle_stop): add tests and do some refactoring

- planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/package.xml
> chore(out_of_lane): add Mamoru SOBUE as maintainer

- system/system_monitor/src/cpu_monitor/cpu_monitor_base.cpp
- system/system_monitor/src/process_monitor/process_monitor.cpp
```
system/system_monitor/src/cpu_monitor/cpu_monitor_base.cpp:178:15: style: The scope of the variable 'cpu_name' can be reduced. [variableScope]
std::string cpu_name;
^
system/system_monitor/src/cpu_monitor/cpu_monitor_base.cpp:179:9: style: The scope of the variable 'usr' can be reduced. [variableScope]
float usr{0.0};
^
system/system_monitor/src/cpu_monitor/cpu_monitor_base.cpp:180:9: style: The scope of the variable 'nice' can be reduced. [variableScope]
float nice{0.0};
^
system/system_monitor/src/cpu_monitor/cpu_monitor_base.cpp:181:9: style: The scope of the variable 'sys' can be reduced. [variableScope]
float sys{0.0};
^
system/system_monitor/src/cpu_monitor/cpu_monitor_base.cpp:182:9: style: The scope of the variable …
```
> fix(system_monitor): fix variableScope

- planning/autoware_freespace_planner/README.md
- planning/autoware_freespace_planner/schema/freespace_planner.schema.json
Implement the ROS Node configuration layout described in https://github.com/orgs/autowarefoundation/discussions/3371
Package built and launch locally.
> refactor(autoware_freespace_planner): rework parameters

- evaluator/kinematic_evaluator/CMakeLists.txt
- evaluator/kinematic_evaluator/README.md
- evaluator/kinematic_evaluator/schema/kinematic_evaluator.schema.json
Implement the ROS Node configuration layout described in https://github.com/orgs/autowarefoundation/discussions/3371
Package built and launch locally.
> refactor(kinematic_evaluator): rework parameters

- planning/autoware_freespace_planning_algorithms/package.xml
https://github.com/autowarefoundation/autoware/actions/runs/10365463767/job/28735822112#step:5:13138
> ```
> #38 295.8 --- stderr: autoware_freespace_planning_algorithms
> #38 295.8 /usr/bin/ld: /opt/ros/humble/lib/librosbag2_cpp.so: undefined reference to `rosbag2_storage::get_default_storage_id[abi:cxx11]()'
> ```
- https://github.com/autowarefoundation/autoware/issues/5089
**Related PRs:**
- https://github.com/autowarefoundation/autoware_tools/pull/96
- https://github.com/autowarefoundation/autoware/pull/5092
None.
None.
None.
> chore(autoware_freespace_planning_algorithms): add missing dependency

- control/autoware_vehicle_cmd_gate/src/vehicle_cmd_gate.cpp
Since the `gear` field is not used as mentioned in https://github.com/autowarefoundation/autoware.universe/pull/8351, we no longer have to use the `Commands` struct. I replace it with the `Control` struct.
None
- build on CI
- run with psim
None.
None.
None.
> refactor(vehicle_cmd_gate): use smaller class for filter command

- perception/autoware_tensorrt_yolox/README.md
Fix path to json schema file in README
[- Link](https://github.com/autowarefoundation/autoware.universe/issues/8341)
None.
None.
None.
> fix(autoware_tensorrt_yolox): fix path to json schema files in README

- vehicle/autoware_accel_brake_map_calibrator/scripts/calc_utils.py
fix for https://github.com/autowarefoundation/autoware.universe/pull/8527
https://results.pre-commit.ci/run/github/429651616/1724056061.MLB04FzrTtu8RBn8sIvggg
- Link
pre-commit run
None.
None.
None.
> refactor(autowre_accel_brake_map_calibrator): fix for flake-ros v0.9.0

- planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/path_safety_checker/safety_check.hpp
- planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_safety_checker/safety_check.cpp
similar to https://github.com/autowarefoundation/autoware.universe/pull/8193, add safety check function to calculate rough  distance between the ego vehicle and the objects. Calculate the distance when the distance is minimized or maximized when the direction of the ego and the object is changed.
- Link
None.
None.
None.
> feat(behavior_path_planner_common): add calculateRoughDistanceToObjects

- planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/package.xml
Add a 2nd codeowner to the `obstacle_velocity_limiter`.
- Link
None.
None.
None.
> chore(obstacle_velocity_limiter): add Alqudah Mohammad as codeowner

- planning/behavior_path_planner/autoware_behavior_path_planner_common/test_map/road_shoulder/lanelet2_map.osm
updated the road_shoulder map for use in Psim
- Link
None.
None.
None.
> chore(behavior_path_planner_common): update road_shoulder test_map

- localization/yabloc/yabloc_common/include/yabloc_common/cv_decompress.hpp
- localization/yabloc/yabloc_common/include/yabloc_common/pose_conversions.hpp
- localization/yabloc/yabloc_common/src/cv_decompress.cpp
- localization/yabloc/yabloc_common/src/ground_server/polygon_operation.cpp
- localization/yabloc/yabloc_common/src/pose_conversions.cpp
However, I have suppressed `sample_from_polygons` because I found it to be a work in progress in the comments.
```
localization/yabloc/yabloc_common/src/cv_decompress.cpp:73:0: style: The function 'decompress_to_ros_msg' is never used. [unusedFunction]
sensor_msgs::msg::Image::ConstSharedPtr decompress_to_ros_msg(
^
localization/yabloc/yabloc_common/src/ground_server/polygon_operation.cpp:21:0: style: The function 'sample_from_polygons' is never used. [unusedFunction]
pcl::PointCloud<pcl::PointXYZ> sample_from_polygons(const lanelet::PolygonLayer & polygons)
^
localization/yabloc/yabloc_common/src/pose_conversions.cpp:21:0: style: The function 'affine_to_pose' is never used. [unusedFunction]
geometry_msgs::msg::Pose …
```
> fix(yabloc_common): fix unusedFunction

- .github/actions/build-and-test-differential/action.yaml
- .github/workflows/build-and-test-differential.yaml
This PR is to prepare functionality that does not execute build-and-test-differential (humble, -cuda) for PRs related to packages that are not related to cuda.
This PR moved build-and-test-differential to .github/actions/build-and-test-differential.
I will submit a PR later to ignore build-and-test-differential (humble, -cuda).
- https://github.com/autowarefoundation/autoware.universe/pull/8547#pullrequestreview-2249746828
None.
None.
None.
> ci(build-and-test-differential): separate build-and-test-differential job to composite action

- control/autoware_vehicle_cmd_gate/src/vehicle_cmd_filter.cpp
- control/autoware_vehicle_cmd_gate/src/vehicle_cmd_filter.hpp
```
control/autoware_vehicle_cmd_gate/src/vehicle_cmd_filter.cpp:43:0: style: The function 'setSteerLim' is never used. [unusedFunction]
void VehicleCmdFilter::setSteerLim(const LimitArray & v)
^
control/autoware_vehicle_cmd_gate/src/vehicle_cmd_filter.cpp:49:0: style: The function 'setSteerRateLim' is never used. [unusedFunction]
void VehicleCmdFilter::setSteerRateLim(const LimitArray & v)
^
control/autoware_vehicle_cmd_gate/src/vehicle_cmd_filter.cpp:55:0: style: The function 'setLonAccLim' is never used. [unusedFunction]
void VehicleCmdFilter::setLonAccLim(const LimitArray & v)
^
control/autoware_vehicle_cmd_gate/src/vehicle_cmd_filter.cpp:61:0: style: The function 'setLonJerkLim' is never used. [unusedFunction]
void …
```
> fix(autoware_vehicle_cmd_gate): fix unusedFunction

- perception/autoware_ground_segmentation/src/scan_ground_filter/node.hpp
```
perception/autoware_ground_segmentation/src/scan_ground_filter/node.hpp:146:0: style: The function 'getGridId' is never used. [unusedFunction]
uint16_t getGridId() const { return grid_id; }
^
perception/autoware_ground_segmentation/src/scan_ground_filter/node.hpp:148:0: style: The function 'getIndices' is never used. [unusedFunction]
pcl::PointIndices getIndices() const { return pcl_indices; }
^
perception/autoware_ground_segmentation/src/scan_ground_filter/node.hpp:149:0: style: The function 'getHeightList' is never used. [unusedFunction]
std::vector<float> getHeightList() const { return height_list; }
^
```
- Link
None.
None.
None.
> fix(autoware_ground_segmentation): fix unusedFunction

- perception/autoware_multi_object_tracker/src/processor/input_manager.cpp
- perception/autoware_multi_object_tracker/src/processor/input_manager.hpp
```
perception/autoware_multi_object_tracker/src/processor/input_manager.cpp:49:0: style: The function 'getTimestamps' is never used. [unusedFunction]
bool InputStream::getTimestamps(
^
perception/autoware_multi_object_tracker/src/processor/input_manager.hpp:49:0: style: The function 'setQueueSize' is never used. [unusedFunction]
void setQueueSize(size_t que_size) { que_size_ = que_size; }
^
perception/autoware_multi_object_tracker/src/processor/input_manager.hpp:63:0: style: The function 'getNames' is never used. [unusedFunction]
void getNames(std::string & long_name, std::string & short_name) const
^
perception/autoware_multi_object_tracker/src/processor/input_manager.hpp:70:0: style: The function 'getLongName' is never used. …
```
> fix(autoware_multi_object_tracker): fix unusedFunction

- simulator/simple_planning_simulator/src/simple_planning_simulator/vehicle_model/sim_model_delay_steer_acc_geared_wo_fall_guard.cpp
This PR fixes one more mistake in https://github.com/autowarefoundation/autoware.universe/pull/8607
https://github.com/autowarefoundation/autoware.universe/pull/8607
None.
None.
> fix(simple_planning_simulator): fix dimension

- .github/CODEOWNERS
- perception/autoware_tensorrt_yolox/package.xml
Add a code maintainer.
- Link
None.
None.
None.
> chore(autoware_tensorrt_yolox): add Kotaro Uetake as maintainer

- common/tier4_camera_view_rviz_plugin/src/bird_eye_view_controller.cpp
- common/tier4_camera_view_rviz_plugin/src/bird_eye_view_controller.hpp
- common/tier4_camera_view_rviz_plugin/src/third_person_view_controller.cpp
```
common/tier4_camera_view_rviz_plugin/src/bird_eye_view_controller.cpp:102:0: style: The function 'handleMouseEvent' is never used. [unusedFunction]
void BirdEyeViewController::handleMouseEvent(rviz_common::ViewportMouseEvent & event)
^
common/tier4_camera_view_rviz_plugin/src/bird_eye_view_controller.cpp:181:0: style: The function 'lookAt' is never used. [unusedFunction]
void BirdEyeViewController::lookAt(const Ogre::Vector3 & point)
^
common/tier4_camera_view_rviz_plugin/src/bird_eye_view_controller.cpp:186:0: style: The function 'onTargetFrameChanged' is never used. [unusedFunction]
void BirdEyeViewController::onTargetFrameChanged(
^
common/tier4_camera_view_rviz_plugin/src/third_person_view_controller.cpp:229:0: style: The …
```
> fix(tier4_camera_view_rviz_plugin): fix unusedFunction

- planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/debug.hpp
- planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/debug.cpp
- planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp
```
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/debug.cpp:234:0: style: The function 'createEgoStatusMarkerArray' is never used. [unusedFunction]
MarkerArray createEgoStatusMarkerArray(
^
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/debug.cpp:349:0: style: The function 'createPredictedVehiclePositions' is never used. [unusedFunction]
MarkerArray createPredictedVehiclePositions(const PathWithLaneId & path, std::string && ns)
^
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp:117:0: style: The function 'calcSignedArcLengthToFirstNearestPoint' is never used. [unusedFunction]
double …
```
> fix(autoware_behavior_path_static_obstacle_avoidance_module): fix unusedFunction

- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/CMakeLists.txt
- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_module.hpp
- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/pull_over_planner/freespace_pull_over.hpp
- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/pull_over_planner/geometric_pull_over.hpp
- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/pull_over_planner/pull_over_planner_base.hpp
- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/pull_over_planner/shift_pull_over.hpp
- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/util.hpp
- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/freespace_pull_over.cpp
- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/geometric_pull_over.cpp
- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/shift_pull_over.cpp
just moved files
- Link
just moved fles
None.
None.
None.
> refactor(goal_planner): move pull_over_planner directory

- perception/autoware_lidar_centerpoint/config/centerpoint_sigma.param.yaml
This PR is required to run centerpoint_sigma and do not affect current running models.
- Link
None.
None.
None.
> chore(autoware_lidar_centerpoint): add centerpoint sigma parameter

- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp
Fix typo
- Link
None.
None.
None.
> fix(goal_planner): fix typo

- sensing/autoware_pointcloud_preprocessor/launch/vector_map_inside_area_filter_node.launch.xml
Fix typo
- Link
None.
None.
None.
> fix(pointcloud_preprocessor): fix typo

- planning/behavior_path_planner/autoware_behavior_path_planner/include/autoware/behavior_path_planner/behavior_path_planner_node.hpp
- planning/behavior_path_planner/autoware_behavior_path_planner/src/behavior_path_planner_node.cpp
- planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/data_manager.hpp
add the function to initialize planner data parameter for unit_test/development usage
- Link
build passes
None.
None.
None.
> refactor(behavior_path_planner): planner data parameter initializer function

- .cmakelintrc
- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/CMakeLists.txt
- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/examples/plot_map.cpp
- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/manager.hpp
depend https://github.com/autowarefoundation/autoware.universe/pull/8767
- Link
- [CompanyName internal link](https://tier4.atlassian.net/browse/RT1-7457)
None.
None.
None.
> feat(behavior_path_goal planner): add example plot for development

- build_depends.repos
for https://github.com/autowarefoundation/autoware_lanelet2_extension/pull/30
- Link
just upgrade dependency
None.
None.
None.
> chore(ci): update lanelet2_extension version for build

- planning/sampling_based_planner/autoware_frenet_planner/include/autoware_frenet_planner/frenet_planner.hpp
- planning/sampling_based_planner/autoware_frenet_planner/src/frenet_planner/frenet_planner.cpp
This is a fix based on cppcheck unusedFunction warnings.
```
src/frenet_planner/frenet_planner.cpp:36:0: style: The function 'generateTrajectories' is never used. [unusedFunction]
std::vector<Trajectory> generateTrajectories(
^
src/frenet_planner/frenet_planner.cpp:56:0: style: The function 'generateLowVelocityTrajectories' is never used. [unusedFunction]
std::vector<Trajectory> generateLowVelocityTrajectories(
^
```
- Link
None.
None.
None.
> fix(autoware_frenet_planner): fix unusedFunction

- planning/sampling_based_planner/autoware_frenet_planner/include/autoware_frenet_planner/frenet_planner.hpp
- planning/sampling_based_planner/autoware_frenet_planner/src/frenet_planner/frenet_planner.cpp
Fixed build error when using tools due to #8788 
- #8788 
Confirmation of build including tools.
None.
None.
None.
> fix(autoware_frenet_planner): fix build error

- perception/autoware_map_based_prediction/include/map_based_prediction/map_based_prediction_node.hpp
- perception/autoware_map_based_prediction/include/map_based_prediction/path_generator.hpp
- perception/autoware_map_based_prediction/src/map_based_prediction_node.cpp
- perception/autoware_map_based_prediction/src/path_generator.cpp
This reverts commit 67265bbd60c85282c1c3cf65e603098e0c30c477.
- Link
revert of PR https://github.com/autowarefoundation/autoware.universe/pull/8602
None.
None.
None.
> revert(autoware_map_based_prediction): revert improve frenet path gen

- perception/autoware_map_based_prediction/include/map_based_prediction/map_based_prediction_node.hpp
- perception/autoware_map_based_prediction/include/map_based_prediction/path_generator.hpp
- perception/autoware_map_based_prediction/src/map_based_prediction_node.cpp
- perception/autoware_map_based_prediction/src/path_generator.cpp
Please see the original PR
https://github.com/autowarefoundation/autoware.universe/pull/8602
* a bug is fixed
The predicted object orientation was wrong.
before
after 
- Link
- original PR
https://github.com/autowarefoundation/autoware.universe/pull/8602
- revert PR
https://github.com/autowarefoundation/autoware.universe/pull/8808
None.
None.
None.
> feat(autoware_map_based_prediction): improve frenet path generation

- map/map_loader/README.md
update the link of map_projection_loader
- Link
check the link
None.
None.
None.
> docs(map_loader): update the link of map_projection_loader

- common/tier4_localization_rviz_plugin/src/pose_history_footprint/display.cpp
This is a fix based on cppcheck knownConditionTrueFalse warnings.
Prevention against future CI changes.
```
common/tier4_localization_rviz_plugin/src/pose_history_footprint/display.cpp:206:7: style: Condition '!history_.empty()' is always true [knownConditionTrueFalse]
if (!history_.empty()) {
^
```
- Link
None.
None.
None.
> fix(tier4_localization_rviz_plugin): fix knownConditionTrueFalse

- map/map_loader/README.md
update the link of pointcloud_divider 
https://github.com/autowarefoundation/autoware-documentation/pull/609
- Link
check the link
None.
None.
None.
> docs(map_loader): update the link of pointcloud_divider

- common/signal_processing/include/signal_processing/lowpass_filter_1d.hpp
- common/signal_processing/src/lowpass_filter_1d.cpp
add setGain() function
- Link
psim
None.
None.
None.
> feat(signal_processing): add set gain function

- tools/reaction_analyzer/README.md
- tools/reaction_analyzer/param/reaction_analyzer.param.yaml
While running the reaction analyzer tool within Autoware Universe, I encountered errors due to changes in message types and PointCloud layout. The current bag files need to be updated to be compatible with the new message types in Autoware.
Package built and launch locally.
> docs(reaction_analyzer): update bag files and the README

- planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/util.cpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/util.hpp
Fix typo.
- Link
Build.
None.
None.
None.
> fix(intersection): fix typo

- control/autoware_mpc_lateral_controller/src/mpc_lateral_controller.cpp
Delete L.107 because L.104 and L.107 are duplicates.
https://github.com/autowarefoundation/autoware.universe/blob/c1aac51443b6fafc4acd6b3e718be39851396f44/control/autoware_mpc_lateral_controller/src/mpc_lateral_controller.cpp#L101-L109
(As a supplement,) `setVehicleModel` is just a setter function, so this change will not change its behavior.
https://github.com/autowarefoundation/autoware.universe/blob/c1aac51443b6fafc4acd6b3e718be39851396f44/control/autoware_mpc_lateral_controller/include/autoware/mpc_lateral_controller/mpc.hpp#L470-L477
None.
None.
None.
None.
> chore: remove duplicate line in mpc_lateral_controller.cpp

- control/autoware_mpc_lateral_controller/param/lateral_controller_defaults.param.yaml
align parameter in the yaml file to the [autoware_launch](https://github.com/autowarefoundation/autoware_launch)
Each package's unit test on CI passes
None.
None.
None.
> chore(mpc_lateral_controller): consistent parameters with autoware_launch

- planning/autoware_obstacle_stop_planner/config/adaptive_cruise_control.param.yaml
- planning/autoware_obstacle_stop_planner/config/obstacle_stop_planner.param.yaml
- planning/autoware_obstacle_stop_planner/schema/obstacle_stop_planner.schema.json
- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/config/goal_planner.param.yaml
- planning/behavior_path_planner/autoware_behavior_path_planner/config/behavior_path_planner.param.yaml
- planning/behavior_path_planner/autoware_behavior_path_start_planner_module/config/start_planner.param.yaml
- planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/config/out_of_lane.param.yaml
align parameter in the yaml file to the [autoware_launch](https://github.com/autowarefoundation/autoware_launch)
Each package's unit test on CI passes
None.
None.
None.
> chore(planning): consistent parameters with autoware_launch

- .cspell.json
- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_module.hpp
- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/util.hpp
- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp
- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/util.cpp
- https://evaluation.tier4.jp/evaluation/reports/52307c23-e4ec-53e1-87f5-0e414c2d410a?project_id=prd_jt
None.
None.
None.
> feat(goal_planner): move PathDecidingStatus to other controller class

- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_module.hpp
- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp
just removed unused variable 
- Link
build passes
None.
None.
None.
> refactor(goal_planner): remove unnecessary GoalPlannerData member

- planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/package.xml
- planning/motion_velocity_planner/autoware_motion_velocity_planner_common/package.xml
- planning/motion_velocity_planner/autoware_motion_velocity_planner_node/package.xml
> chore(motion_velocity_planner): add Alqudah Mohammad as maintainer

- common/tier4_localization_rviz_plugin/src/pose_history/pose_history_display.cpp
- common/tier4_localization_rviz_plugin/src/pose_with_covariance_history/pose_with_covariance_history_display.cpp
Due to a modification to cppcheck's CI, comment suppression is no longer required for items that previously generated warnings.
```
common/tier4_localization_rviz_plugin/src/pose_history/pose_history_display.cpp:48:0: information: Unmatched suppression: unusedFunction [unmatchedSuppression]
void PoseHistory::onInitialize()
^
common/tier4_localization_rviz_plugin/src/pose_with_covariance_history/pose_with_covariance_history_display.cpp:96:0: information: Unmatched suppression: unusedFunction [unmatchedSuppression]
void PoseWithCovarianceHistory::onEnable()
^
common/tier4_localization_rviz_plugin/src/pose_with_covariance_history/pose_with_covariance_history_display.cpp:102:0: information: Unmatched suppression: unusedFunction …
```
> fix(tier4_localization_rviz_plugin): fix unmatchedSuppression

- .cppcheck_suppressions
Removed unusedFunction and unknownMacro
- Link
None.
None.
None.
> ci(cppcheck): remove unnecessary suppressions

- .github/CODEOWNERS
- perception/autoware_detected_object_feature_remover/package.xml
Add me and @ktro2828 as a codeowner of this package.
- Link
None.
None.
None.
> chore(autoware_deteted_object_feature_remover): add code owners

- common/object_recognition_utils/include/object_recognition_utils/transform.hpp
Implement covariance transform in the transformObjects function.
tf2 transformCovariance()
Document http://docs.ros.org/en/melodic/api/tf2_geometry_msgs/html/c++/namespacetf2.html#a56c7997d60eaa1c18e7bbb2e63d03272
Code http://docs.ros.org/en/melodic/api/tf2_geometry_msgs/html/c++/tf2__geometry__msgs_8h_source.html#l00823
None.
None.
None.
> feat(object_recognition_utils): implement covariance transform in the transformObjects

- perception/autoware_shape_estimation/CMakeLists.txt
- perception/autoware_shape_estimation/package.xml
- perception/autoware_shape_estimation/test/test_shape_estimation_node.cpp
This PR added unit testing for `ShapeEstimationNode`.
- Link
None.
None.
None.
> test(autoware_shape_estimation): add unit testing for `ShapeEstimationNode`

- .cppcheck_suppressions
add `unusedFunction` suppression
[TIER IV INTERNAL](https://star4.slack.com/archives/C4P0NSMB5/p1727424355914199)
[TIER IV INTERNAL](https://star4.slack.com/archives/C024FRX4UNL/p1727405055055549)
None.
None.
None.
> ci(cppcheck): add unusedFunction suppression

- codecov.yaml
ignore files named "debug.cpp", "debug.hpp" from metrics
- Link
None.
None.
None.
> chore(codecov): ignore filename with 'debug' basename

- codecov.yaml
I added component settings to codecov.yaml to analyze the coverage of planning and control packages maintained by TIER IV.
- Link
None.
None.
None.
> feat(codecov): add codecov component for planning and control

- codecov.yaml
add T4 managed Planning/Control target in codecov
- Link
Not applicable
None.
None.
None.
> ci(codecov): update planning target component

- codecov.yaml
add Localization/Map TIER IV Maintained Packages
- Link
None.
None.
None.
> ci(codecov): add map/localization target

- codecov.yaml
> ci(codecov): add setting for entire each component

- control/obstacle_collision_checker/include/obstacle_collision_checker/obstacle_collision_checker.hpp
- control/obstacle_collision_checker/include/obstacle_collision_checker/obstacle_collision_checker_node.hpp
- control/obstacle_collision_checker/src/obstacle_collision_checker_node/obstacle_collision_checker.cpp
- control/obstacle_collision_checker/src/obstacle_collision_checker_node/obstacle_collision_checker_node.cpp
- control/obstacle_collision_checker/test/test_obstacle_collision_checker.cpp
- launch/tier4_control_launch/launch/control.launch.xml
Add tests and make the code easier to test in the `obstacle_collision_checker` package.
- Link
None.
None.
None.
> test(obstacle_collision_checker): refactor and add tests

- sensing/cuda_utils/package.xml
Updated maintainers for the cuda_utils package
- Link
None.
None.
None.
> chore: added maintainers to the cuda_utils package

- common/tensorrt_common/package.xml
Update maintainers for tensorrt_common.
- Link
None.
None.
None.
> chore(tensorrt_common): update maintainers

- planning/autoware_mission_planner/test/test_lanelet2_plugins_default_planner.cpp
fix typo
- Link
None.
None.
None.
> chore(mission_planner): fix typo

- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/pull_over_planner/pull_over_planner_base.hpp
- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/thread_data.hpp
- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp
depends https://github.com/autowarefoundation/autoware.universe/pull/9010
- https://tier4.atlassian.net/browse/RT1-7966
- https://evaluation.tier4.jp/evaluation/reports/12476487-bc54-5b1c-9e24-c43206fb17e2?page_size=50&project_id=prd_jt
None.
None.
None.
> refactor(goal_planner): remove lane parking pull over path

- planning/autoware_obstacle_cruise_planner/package.xml
cc @yuki-takagi-66 
https://github.com/autowarefoundation/autoware.universe/pull/8072#issuecomment-2399778744
- Link
None.
None.
None.
> chore(obstacle_cruise_planner): add maintainer

- planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/CMakeLists.txt
- planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/package.xml
- planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/scene.cpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/utils.cpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/utils.hpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/test/test_utils.cpp
> test(traffic_light): write test for utils

- planning/behavior_path_planner/autoware_behavior_path_lane_change_module/README.md
- planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/scene.hpp
- planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/base_class.hpp
- planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/utils.hpp
- planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/interface.cpp
- planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp
- planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp
The lane change module evaluates the validity of the lane change start point. If the start point is determined to be invalid, the module responds by placing a stop point only at the terminal start position.
An invalid start point occurs when it is not located within the target neighboring lane.
https://github.com/user-attachments/assets/386bbdf8-3e0e-482c-b40c-5880da545cf5
However, as highlighted in above video (t > 0:05), checking the start point's validity is impractical in certain scenarios. By the time the start point becomes valid, the expected stop point's position is already behind the ego vehicle. This results in the stop point being incorrectly placed behind the ego vehicle, leading to sudden and unintended deceleration.
The proposed PR addresses this issue by improving how the …
> fix(lane_change): insert stop for current lanes object (RT0-33761) 

- .github/workflows/build-and-test-differential.yaml
- .github/workflows/cancel-previous-workflows.yaml
- .github/workflows/check-build-depends.yaml
- .github/workflows/clang-tidy-pr-comments-manually.yaml
- .github/workflows/clang-tidy-pr-comments.yaml
- .github/workflows/comment-on-pr.yaml
- .github/workflows/cppcheck-differential.yaml
- .github/workflows/cppcheck-weekly.yaml
- .github/workflows/dco.yaml
- .github/workflows/delete-closed-pr-docs.yaml
- .github/workflows/deploy-docs.yaml
- .github/workflows/github-release.yaml
- .github/workflows/json-schema-check.yaml
- .github/workflows/pr-agent.yaml
- .github/workflows/pr-labeler.yaml
- .github/workflows/pre-commit-autoupdate.yaml
- .github/workflows/pre-commit-optional.yaml
- .github/workflows/pre-commit.yaml
- .github/workflows/spell-check-daily.yaml
- .github/workflows/spell-check-differential.yaml
- .github/workflows/sync-files.yaml
- .github/workflows/update-codeowners-from-packages.yaml
Former PR is https://github.com/autowarefoundation/autoware/pull/5320.
> It seems that the version of Ubuntu of GitHub Runner used when `runs-on: ubuntu-latest` has been gradually switching from Ubuntu 22.04 to Ubuntu 24.04 toward the end of October. [actions/runner-images#10636](https://github.com/actions/runner-images/issues/10636)
> 
> This has caused some CI checks to start failing. https://github.com/autowarefoundation/autoware/actions/runs/11254191077/job/31291276368?pr=5319
> 
> This PR changes the `runs-on` value to `ubuntu-22.04` instead of `ubuntu-latest`.
Former PR is https://github.com/autowarefoundation/autoware/pull/5320.
- Link
None.
None.
None.
> fix(.github): change `runs-on` value from `ubuntu-latest` to `ubuntu-22.04`

- localization/autoware_pose_covariance_modifier/README.md
This PR fixes the gt (greater than) symbol issue in the mermaid chart in the README.md file of the [autoware_pose_covariance_modifier](https://github.com/autowarefoundation/autoware.universe/tree/aaa8429d91670c813e6264a8382ae1ffab7179a9/localization/autoware_pose_covariance_modifier#flowcharts) package.
Before this PR:
After this PR:
- [autoware_pose_covariance_modifier](https://github.com/autowarefoundation/autoware.universe/tree/aaa8429d91670c813e6264a8382ae1ffab7179a9/localization/autoware_pose_covariance_modifier)
None.
None.
None.
> docs(autoware_pose_covariance_modifier): fix gt symbol

- control/autoware_control_validator/include/autoware/control_validator/control_validator.hpp
- control/autoware_control_validator/src/control_validator.cpp
- control/autoware_vehicle_cmd_gate/src/vehicle_cmd_gate.cpp
- control/autoware_vehicle_cmd_gate/src/vehicle_cmd_gate.hpp
- planning/autoware_costmap_generator/include/autoware_costmap_generator/costmap_generator.hpp
- planning/autoware_costmap_generator/nodes/autoware_costmap_generator/costmap_generator_node.cpp
- planning/autoware_scenario_selector/include/autoware/scenario_selector/node.hpp
- planning/autoware_scenario_selector/src/node.cpp
- planning/autoware_surround_obstacle_checker/src/node.cpp
- planning/autoware_surround_obstacle_checker/src/node.hpp
- system/autoware_processing_time_checker/config/processing_time_checker.param.yaml
Added processing_time_publiser for the following five
And, various processing_times can be referenced from /system/processing_time_checker/metrics.
- /planning/scenario_planning/parking/costmap_generator
- /control/control_validator
- /planning/scenario_planning/scenario_selector
- /planning/scenario_planning/lane_driving/motion_planning/surround_obstacle_checker
- /control/vehicle_cmd_gate
Result of `ros2 topic echo /system/processing_time_checker/metrics`
Sorry, we could not figure out why it is taking so long.
However, since TimeKeeper() was outputting similar results, we thought it was not a mistake in the measurement method.
None.
None.
None.
> feat(costmap_generator, control_validator, scenario_selector, surround_obstacle_checker, vehicle_cmd_gate): add processing time pub.

- planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/CMakeLists.txt
- planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/package.xml
- planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/src/scene.cpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/src/scene.hpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/src/utils.cpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/src/utils.hpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/test/test_utils.cpp
Refactor the code of the `detection_area` module and add unit tests.
- Link
None.
None.
None.
> test(detection_area): refactor and add unit tests

- perception/autoware_map_based_prediction/package.xml
Add maintainers to the autoware_map_based_prediction
- Link
None.
None.
None.
> chore(autoware_map_based_prediction): add maintainers to package.xml

- launch/tier4_system_launch/launch/system.launch.xml
fixed to use `autoware_component_interface_tools`
Related PR
- https://github.com/autowarefoundation/autoware.universe/pull/9093
* Done : `planning_simulator` with [sample_map](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/planning-simulation/)
* Done: `logging_simulator` with [sample_rosbag](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/rosbag-replay-simulation/)
* Done: `e2e_simulator` with [AWSIM v1.3.0](https://github.com/tier4/AWSIM/releases/tag/v1.3.0)
None.
None.
None.
> fix(system): fixed to use autoware_component_interface_tools

- launch/tier4_simulator_launch/launch/simulator.launch.xml
follow up  https://github.com/autowarefoundation/autoware.universe/pull/8681
https://github.com/autowarefoundation/autoware_launch/pull/1195
psim tests
None.
None.
None.
> chore(simple_planning_simulator): add stop_filter_param_path

- common/autoware_vehicle_info_utils/CMakeLists.txt
- common/autoware_vehicle_info_utils/include/autoware_vehicle_info_utils/vehicle_info.hpp
- common/autoware_vehicle_info_utils/include/autoware_vehicle_info_utils/vehicle_info_utils.hpp
- common/autoware_vehicle_info_utils/package.xml
- common/autoware_vehicle_info_utils/src/vehicle_info.cpp
- common/autoware_vehicle_info_utils/src/vehicle_info_utils.cpp
- common/autoware_vehicle_info_utils/test/test_vehicle_info_utils.cpp
add the API description for the footprint point order
- Link
None.
None.
None.
> refactor(vehicle_info): add API description, add unit-tests, add owner

- common/autoware_test_utils/include/autoware_test_utils/mock_data_parser.hpp
- common/autoware_test_utils/src/mock_data_parser.cpp
- common/autoware_test_utils/test/test_mock_data_parser.cpp
check the diff for this PR here: https://github.com/tier4/autoware.universe/compare/chore/autoware_test_utils/sanitizer-header...tier4:autoware.universe:feat/autoware_test_utils/autoware-msgs
depends https://github.com/autowarefoundation/autoware.universe/pull/9174
- Link
None.
None.
None.
> feat(autoware_test_utils): add parser for PredictedObjects

- control/autoware_collision_detector/package.xml
add @TomohitoAndo as maintainer
Not applicable
None.
None.
None.
> chore(collision_detector): add maintainer 

- .github/CODEOWNERS
- common/autoware_time_utils/CMakeLists.txt
- common/autoware_time_utils/include/autoware/time_utils/stopwatch.hpp
- common/autoware_time_utils/include/autoware/time_utils/time_utils.hpp
- common/autoware_time_utils/include/autoware/time_utils/visibility_control.hpp
- common/autoware_time_utils/package.xml
- common/autoware_time_utils/src/time_utils/time_utils.cpp
prefix package and namespace with autoware
None.
None.
None.
> refactor(time_utils): prefix package and namespace with autoware

- perception/autoware_map_based_prediction/CMakeLists.txt
- perception/autoware_map_based_prediction/include/map_based_prediction/data_structure.hpp
- perception/autoware_map_based_prediction/include/map_based_prediction/map_based_prediction_node.hpp
- perception/autoware_map_based_prediction/include/map_based_prediction/path_generator.hpp
- perception/autoware_map_based_prediction/include/map_based_prediction/predictor_vru.hpp
- perception/autoware_map_based_prediction/include/map_based_prediction/utils.hpp
- perception/autoware_map_based_prediction/src/debug.cpp
- perception/autoware_map_based_prediction/src/map_based_prediction_node.cpp
- perception/autoware_map_based_prediction/src/path_generator.cpp
- perception/autoware_map_based_prediction/src/predictor_vru.cpp
- perception/autoware_map_based_prediction/src/utils.cpp
- perception/autoware_map_based_prediction/test/map_based_prediction/test_path_generator.cpp
Split pedestrian/bicycle prediction from the main code.
1. split data structure 
2. split pedestrian/bicycle prediction so called VRU(vulnerable road user) predictor
3. split utility functions
This PR do NOT contain any logic change.
- Link
[TIER IV INTERNAL](https://evaluation.tier4.jp/evaluation/reports/364fdb3f-37f2-5dc9-b5e4-d754d5591c0c?project_id=prd_jt)
None.
None.
None.
> refactor(autoware_map_based_prediction): split pedestrian and bicycle predictor

- control/autoware_collision_detector/include/autoware/collision_detector/node.hpp
- control/autoware_collision_detector/src/node.cpp
Use polling subscriber for collision detector.
None
Build successful and works on PSim
[Screencast from 2024年11月01日 14時27分07秒.webm](https://github.com/user-attachments/assets/429f0b31-046f-4d9e-9f0a-607ead0568c5)
None.
None.
None.
> feat(collision_detector): use polling subscriber

- planning/autoware_obstacle_cruise_planner/CMakeLists.txt
- planning/autoware_obstacle_cruise_planner/test/test_obstacle_cruise_planner_utils.cpp
add function tests
- Link
None.
None.
None.
> chore(obstacle_cruise_planner): add function tests for a utils function

- planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/CMakeLists.txt
- planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/package.xml
- planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/test/test_crosswalk.cpp
add unit tests
- Link
None.
None.
None.
> test(crosswalk): add unit test

- .github/CODEOWNERS
- perception/autoware_bytetrack/package.xml
- perception/autoware_lidar_apollo_instance_segmentation/CMakeLists.txt
- perception/autoware_lidar_apollo_instance_segmentation/include/autoware/lidar_apollo_instance_segmentation/detector.hpp
- perception/autoware_lidar_apollo_instance_segmentation/package.xml
- perception/autoware_lidar_apollo_instance_segmentation/src/detector.cpp
- perception/autoware_shape_estimation/include/autoware/shape_estimation/tensorrt_shape_estimator.hpp
- perception/autoware_shape_estimation/lib/tensorrt_shape_estimator.cpp
- perception/autoware_shape_estimation/package.xml
- perception/autoware_tensorrt_classifier/include/autoware/tensorrt_classifier/calibrator.hpp
- perception/autoware_tensorrt_classifier/include/autoware/tensorrt_classifier/tensorrt_classifier.hpp
- perception/autoware_tensorrt_classifier/package.xml
- perception/autoware_tensorrt_classifier/src/tensorrt_classifier.cpp
- perception/autoware_tensorrt_yolox/include/autoware/tensorrt_yolox/calibrator.hpp
- perception/autoware_tensorrt_yolox/include/autoware/tensorrt_yolox/tensorrt_yolox.hpp
- perception/autoware_tensorrt_yolox/package.xml
- perception/autoware_tensorrt_yolox/src/tensorrt_yolox.cpp
- perception/autoware_traffic_light_classifier/package.xml
- perception/autoware_traffic_light_classifier/src/classifier/cnn_classifier.hpp
- sensing/autoware_cuda_utils/CMakeLists.txt
- sensing/autoware_cuda_utils/README.md
- sensing/autoware_cuda_utils/include/autoware/cuda_utils/cuda_check_error.hpp
- sensing/autoware_cuda_utils/include/autoware/cuda_utils/cuda_unique_ptr.hpp
- sensing/autoware_cuda_utils/include/autoware/cuda_utils/stream_unique_ptr.hpp
- sensing/autoware_cuda_utils/package.xml
prefix package and namespace with autoware
None.
None.
None.
> refactor(cuda_utils): prefix package and namespace with autoware

- common/autoware_geography_utils/package.xml
update maintainers
- Link
None.
None.
None.
> chore(autoware_geography_utils): update maintainers

- planning/behavior_velocity_planner/autoware_behavior_velocity_planner/src/node.cpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_planner/src/node.hpp
Use polling subscriber.
- Link
None.
None.
None.
> fix(bvp): use polling subscriber

- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp
sort candidate path only when num to avoid is different to prioritize the goal which has less num_onjects_to_avoid.
this solves stuck by putting modified goal after objects
before
after
- Link
https://tier4.atlassian.net/browse/RT0-31696
- psim
- 2024/11/08 https://evaluation.tier4.jp/evaluation/reports/eb167be9-cb2a-572d-b002-0762c517042d/?project_id=prd_jt
None.
None.
None.
> feat(goal_planner): sort candidate path only when num to avoid is different

- launch/tier4_control_launch/launch/control.launch.xml
This PR adds a parameter to set AEB's state check to true or false in the launch file, this changes is aimed at facilitating ci/cd evaluation where turning this parameter on and off is sometimes necessary depending on the evaluation tool (DLR, planning simulation, etc).
Example usage:
`ros2 launch autoware_launch logging_simulator.launch.xml map_path:=$HOME/autoware_map/lane_change_map  vehicle_model:=lexus sensor_model:=aip_xx1  using_logging_simulator:=true
`
Note:
requires launch changes: https://github.com/autowarefoundation/autoware_launch/pull/1218
- Link
Psim
None.
None.
None.
> feat(aeb): set global param to override autoware state check

- codecov.yaml
update T4 maintained packages.
- Link
None.
None.
None.
> chore(codecov): update maintained packages

- .github/CODEOWNERS
fix codeowner file's directory name
- Link
None.
None.
None.
> fix(codeowner): fix codeowner file's directory name

- planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp
Outputs velocity factor when this module modifies path velocity.
Psim
None.
None.
None.
> feat(avoidance): output velocity factor

- planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/start_planner_module.cpp
Outputs velocity factor when this module modifies path velocity.
Psim
None.
None.
None.
> feat(start_planner): output velocity factor

- perception/autoware_compare_map_segmentation/package.xml
- To add maintainer
- Link
None.
None.
None.
> chore(compare_map_segmentation): add maintainer

- control/autoware_mpc_lateral_controller/package.xml
add maintainer
- Link
None.
None.
None.
> chore(autoware_mpc_lateral_controller): add maintainer

- perception/autoware_occupancy_grid_map_outlier_filter/src/occupancy_grid_map_outlier_filter_node.cpp
This is a fix based on clang-tidy `bugprone-incorrect-roundings` error.
```
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_occupancy_grid_map_outlier_filter/src/occupancy_grid_map_outlier_filter_node.cpp:143:16: error: casting (double + 0.5) to integer leads to incorrect rounding; consider using lround (#include <cmath>) instead [bugprone-incorrect-roundings,-warnings-as-errors]
std::max(static_cast<int>(min_points_and_distance_ratio_ / distance + 0.5f), min_points_),
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_occupancy_grid_map_outlier_filter/src/occupancy_grid_map_outlier_filter_node.cpp:143:33: error: casting (double + 0.5) to integer leads to incorrect rounding; consider using lround (#include <cmath>) instead …
```
> fix(autoware_occupancy_grid_map_outlier_filter): fix bugprone-incorrect-roundings

- common/autoware_test_utils/launch/psim_intersection.launch.xml
- common/autoware_test_utils/launch/psim_road_shoulder.launch.xml
- common/autoware_test_utils/rviz/psim_test_map.rviz
- common/autoware_test_utils/test_map/intersection/lanelet2_map.osm
add TrafficLight to intersection_map and rviz config. Also use awsim_sensor_kit_description for ease.
- Link
None.
None.
None.
> test(autoware_test_utils): add TrafficLight to map, fix launcher

- planning/behavior_velocity_planner/autoware_behavior_velocity_stop_line_module/package.xml
Add maintainers of autoware_behavior_velocity_stop_line_module.
- Link
None.
None.
None.
> chore(autoware_behavior_velocity_stop_line_module): add maintainer

- planning/behavior_path_planner/autoware_behavior_path_planner_common/package.xml
Add package maintainer for `behavior_path_planner_common`
None.
N/A
None.
None.
None.
> chore(behavior_path_planner_common): add package maintainer

- common/autoware_pyplot/CMakeLists.txt
- common/autoware_pyplot/include/autoware/pyplot/axes.hpp
- common/autoware_pyplot/include/autoware/pyplot/common.hpp
- common/autoware_pyplot/include/autoware/pyplot/figure.hpp
- common/autoware_pyplot/include/autoware/pyplot/legend.hpp
- common/autoware_pyplot/include/autoware/pyplot/loader.hpp
- common/autoware_pyplot/include/autoware/pyplot/patches.hpp
- common/autoware_pyplot/include/autoware/pyplot/pyplot.hpp
- common/autoware_pyplot/include/autoware/pyplot/quiver.hpp
- common/autoware_pyplot/include/autoware/pyplot/text.hpp
- common/autoware_pyplot/package.xml
- common/autoware_pyplot/src/axes.cpp
- common/autoware_pyplot/src/common.cpp
- common/autoware_pyplot/src/figure.cpp
- common/autoware_pyplot/src/legend.cpp
- common/autoware_pyplot/src/patches.cpp
- common/autoware_pyplot/src/pyplot.cpp
- common/autoware_pyplot/src/quiver.cpp
- common/autoware_pyplot/src/text.cpp
- common/autoware_pyplot/test/test_pyplot.cpp
> feat(pyplot): add C++ pyplot

- planning/behavior_path_planner/autoware_behavior_path_planner_common/test/test_objects_filtering.cpp
Add unit test for `autoware_behavior_path_planner_common/src/utils/path_safety_checker/objects_filtering.cpp`.
None
Colcon test
```
4: [----------] 15 tests from BehaviorPathPlanningObjectsFiltering
4: [ RUN      ] BehaviorPathPlanningObjectsFiltering.velocity_filter
4: [       OK ] BehaviorPathPlanningObjectsFiltering.velocity_filter (0 ms)
4: [ RUN      ] BehaviorPathPlanningObjectsFiltering.position_filter
4: [       OK ] BehaviorPathPlanningObjectsFiltering.position_filter (0 ms)
4: [ RUN      ] BehaviorPathPlanningObjectsFiltering.is_within_circle
4: [       OK ] BehaviorPathPlanningObjectsFiltering.is_within_circle (0 ms)
4: [ RUN      ] BehaviorPathPlanningObjectsFiltering.isCentroidWithinLanelet
4: [       OK ] BehaviorPathPlanningObjectsFiltering.isCentroidWithinLanelet (0 ms)
4: …
```
> test(bpp_common): add unit test for object filtering

- control/autoware_autonomous_emergency_braking/README.md
I have added an explanation of the IMU Path Generation section, which details:
1. Overview of IMU path generation based on vehicle velocity and angular velocity
2. Constraints and countermeasures to handle path distortion
3. Advantages and limitations of lateral deviation control
4. Detailed algorithm for path generation including:
- Selection of check points
- Path generation process
- Termination conditions
None
None.
@danielsanchezaran 
Looking at the diff on GitHub, it may appear that the original text has been removed. However, no content from the original text was actually deleted - rather, the structure was reorganized and processing flows were added.
Please feel free to comment if anything seems unclear or concerning.
None.
<!-- ⬇️🔴
None.
> docs(autoware_autonomous_emergency_braking): enhance IMU path generation section with constraints and algorithm details

- evaluator/localization_evaluator/package.xml
Add some maintainers to localization_evaluator
- Link
None.
None.
None.
> chore(localization_evaluator): add some maintainers

- perception/autoware_traffic_light_classifier/src/classifier/classifier_interface.hpp
This is a fix based on clang-tidy `clang-diagnostic-delete-abstract-non-virtual-dtor` error.
```
/usr/include/c++/11/bits/unique_ptr.h:85:2: error: delete called on 'autoware::traffic_light::ClassifierInterface' that is abstract but has non-virtual destructor [clang-diagnostic-delete-abstract-non-virtual-dtor]
delete __ptr;
^
/usr/include/c++/11/bits/unique_ptr.h:361:4: note: in instantiation of member function 'std::default_delete<autoware::traffic_light::ClassifierInterface>::operator()' requested here
get_deleter()(std::move(__ptr));
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_traffic_light_classifier/src/single_image_debug_inference_node.cpp:68:12: note: in instantiation of member function …
```
> fix(autoware_traffic_light_classifier): fix clang-diagnostic-delete-abstract-non-virtual-dtor

- perception/autoware_image_projection_based_fusion/include/autoware/image_projection_based_fusion/roi_cluster_fusion/node.hpp
This is a fix based on clang-tidy `clang-diagnostic-inconsistent-missing-override` error.
```
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_image_projection_based_fusion/include/autoware/image_projection_based_fusion/roi_cluster_fusion/node.hpp:57:8: error: 'out_of_scope' overrides a member function but is not marked 'override' [clang-diagnostic-inconsistent-missing-override]
bool out_of_scope(const DetectedObjectWithFeature & obj);
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_image_projection_based_fusion/include/autoware/image_projection_based_fusion/fusion_node.hpp:134:16: note: overridden virtual function is here
virtual bool out_of_scope(const ObjType & obj) = 0;
^
```
- Link
None.
None.
None.
> fix(autoware_image_projection_based_fusion): fix clang-diagnostic-inconsistent-missing-override

- .github/sync-files.yaml
- https://github.com/autowarefoundation/autoware/issues/4058
**Continuation of:**
- https://github.com/autowarefoundation/autoware.universe/pull/5879
- https://github.com/autowarefoundation/autoware.universe/pull/7568
None.
None.
None.
> ci(sync-files): make use of sync-files-templates repo

- evaluator/autoware_control_evaluator/test/test_control_evaluator_node.cpp
- evaluator/autoware_planning_evaluator/src/planning_evaluator_node.cpp
- evaluator/autoware_planning_evaluator/test/test_planning_evaluator_node.cpp
- evaluator/kinematic_evaluator/test/test_kinematic_evaluator_node.cpp
- evaluator/localization_evaluator/test/test_localization_evaluator_node.cpp
- evaluator/perception_online_evaluator/src/metrics/detection_count.cpp
- evaluator/perception_online_evaluator/src/metrics/deviation_metrics.cpp
- evaluator/perception_online_evaluator/src/utils/marker_utils.cpp
- evaluator/perception_online_evaluator/src/utils/objects_filtering.cpp
- evaluator/perception_online_evaluator/test/test_perception_online_evaluator_node.cpp
- evaluator/scenario_simulator_v2_adapter/src/converter_node.cpp
> fix(cpplint): include what you use - evaluator

- map/autoware_map_height_fitter/src/map_height_fitter.cpp
- map/autoware_map_loader/src/lanelet2_map_loader/lanelet2_map_loader_node.cpp
- map/autoware_map_loader/src/pointcloud_map_loader/differential_map_loader_module.cpp
- map/autoware_map_loader/src/pointcloud_map_loader/partial_map_loader_module.cpp
- map/autoware_map_loader/src/pointcloud_map_loader/pointcloud_map_loader_node.cpp
- map/autoware_map_loader/src/pointcloud_map_loader/selected_map_loader_module.cpp
- map/autoware_map_loader/src/pointcloud_map_loader/utils.cpp
- map/autoware_map_loader/test/test_differential_map_loader_module.cpp
- map/autoware_map_loader/test/test_load_pcd_metadata.cpp
- map/autoware_map_loader/test/test_partial_map_loader_module.cpp
- map/autoware_map_loader/test/test_pointcloud_map_loader_module.cpp
- map/autoware_map_loader/test/test_replace_with_absolute_path.cpp
- map/autoware_map_projection_loader/src/map_projection_loader.cpp
- map/autoware_map_projection_loader/test/test_load_info_from_lanelet2_map.cpp
- map/autoware_map_tf_generator/src/pcd_map_tf_generator_node.cpp
- map/autoware_map_tf_generator/src/vector_map_tf_generator_node.cpp
- map/autoware_map_tf_generator/test/test_uniform_random.cpp
> fix(cpplint): include what you use - map

- sensing/autoware_image_diagnostics/src/image_diagnostics_node.cpp
- sensing/autoware_imu_corrector/src/gyro_bias_estimation_module.cpp
- sensing/autoware_imu_corrector/src/gyro_bias_estimator.cpp
- sensing/autoware_imu_corrector/src/imu_corrector_core.cpp
- sensing/autoware_imu_corrector/test/test_gyro_bias_estimation_module.cpp
- sensing/autoware_pointcloud_preprocessor/src/blockage_diag/blockage_diag_node.cpp
- sensing/autoware_pointcloud_preprocessor/src/concatenate_data/concatenate_and_time_sync_nodelet.cpp
- sensing/autoware_pointcloud_preprocessor/src/crop_box_filter/crop_box_filter_node.cpp
- sensing/autoware_pointcloud_preprocessor/src/distortion_corrector/distortion_corrector.cpp
- sensing/autoware_pointcloud_preprocessor/src/distortion_corrector/distortion_corrector_node.cpp
- sensing/autoware_pointcloud_preprocessor/src/downsample_filter/faster_voxel_grid_downsample_filter.cpp
- sensing/autoware_pointcloud_preprocessor/src/downsample_filter/pickup_based_voxel_grid_downsample_filter_node.cpp
- sensing/autoware_pointcloud_preprocessor/src/downsample_filter/robin_hood.h
- sensing/autoware_pointcloud_preprocessor/src/outlier_filter/ring_outlier_filter_node.cpp
- sensing/autoware_pointcloud_preprocessor/src/polygon_remover/polygon_remover.cpp
- sensing/autoware_pointcloud_preprocessor/src/time_synchronizer/time_synchronizer_node.cpp
- sensing/autoware_pointcloud_preprocessor/src/utility/geometry.cpp
- sensing/autoware_pointcloud_preprocessor/src/vector_map_filter/vector_map_inside_area_filter_node.cpp
- sensing/autoware_pointcloud_preprocessor/test/test_distortion_corrector_node.cpp
- sensing/autoware_radar_tracks_noise_filter/test/radar_tracks_noise_filter/test_radar_tracks_noise_filter_is_noise.cpp
- sensing/vehicle_velocity_converter/src/vehicle_velocity_converter.cpp
> fix(cpplint): include what you use - sensing

- simulator/dummy_perception_publisher/src/node.cpp
- simulator/dummy_perception_publisher/src/pointcloud_creator.cpp
- simulator/dummy_perception_publisher/src/signed_distance_function.cpp
- simulator/fault_injection/include/fault_injection/fault_injection_diag_updater.hpp
- simulator/learning_based_vehicle_model/src/interconnected_model.cpp
- simulator/learning_based_vehicle_model/src/model_connections_helpers.cpp
- simulator/learning_based_vehicle_model/src/simple_pymodel.cpp
- simulator/simple_planning_simulator/src/simple_planning_simulator/simple_planning_simulator_core.cpp
- simulator/simple_planning_simulator/src/simple_planning_simulator/utils/csv_loader.cpp
- simulator/simple_planning_simulator/src/simple_planning_simulator/vehicle_model/sim_model_actuation_cmd.cpp
- simulator/simple_planning_simulator/src/simple_planning_simulator/vehicle_model/sim_model_delay_steer_map_acc_geared.cpp
- simulator/simple_planning_simulator/src/simple_planning_simulator/vehicle_model/sim_model_learned_steer_vel.cpp
- simulator/simple_planning_simulator/test/test_simple_planning_simulator.cpp
- simulator/tier4_dummy_object_rviz_plugin/src/tools/interactive_object.cpp
> fix(cpplint): include what you use - simulator

- tools/reaction_analyzer/src/reaction_analyzer_node.cpp
- tools/reaction_analyzer/src/subscriber.cpp
- tools/reaction_analyzer/src/topic_publisher.cpp
- tools/reaction_analyzer/src/utils.cpp
> fix(cpplint): include what you use - tools

- vehicle/autoware_accel_brake_map_calibrator/include/autoware_accel_brake_map_calibrator/accel_brake_map_calibrator_node.hpp
- vehicle/autoware_accel_brake_map_calibrator/src/accel_brake_map_calibrator_node.cpp
- vehicle/autoware_external_cmd_converter/src/node.cpp
- vehicle/autoware_external_cmd_converter/tests/test_external_cmd_converter.cpp
- vehicle/autoware_raw_vehicle_cmd_converter/src/csv_loader.cpp
- vehicle/autoware_raw_vehicle_cmd_converter/src/node.cpp
- vehicle/autoware_raw_vehicle_cmd_converter/src/pid.cpp
- vehicle/autoware_raw_vehicle_cmd_converter/test/test_autoware_raw_vehicle_cmd_converter.cpp
> fix(cpplint): include what you use - vehicle

- control/autoware_autonomous_emergency_braking/package.xml
add package maintainer for `autoware_autonomous_emergency_braking`
None.
None.
None.
None.
> chore(autoware_autonomous_emergency_braking): add package maintainer

- planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/package.xml
add maintainer of autoware_behavior_path_static_obstacle_avoidance_module.
- Link
None.
None.
None.
> chore(autoware_behavior_path_static_obstacle_avoidance_module): add maintainer

- launch/tier4_perception_launch/launch/object_recognition/detection/detection.launch.xml
- launch/tier4_perception_launch/launch/object_recognition/detection/detector/camera_lidar_detector.launch.xml
- launch/tier4_perception_launch/launch/object_recognition/detection/detector/lidar_rule_detector.launch.xml
- launch/tier4_perception_launch/launch/object_recognition/detection/detector/tracker_based_detector.launch.xml
- launch/tier4_perception_launch/launch/perception.launch.xml
1. Clarify interfaces between nodes for better readability.
2. Let `euclidean_cluster` use container.
This PR do not contain logic changes.
- Link
[TIER IV INTERNAL](https://evaluation.tier4.jp/evaluation/reports/2dd579d9-7d6f-5071-a67a-098893157b40?project_id=prd_jt)
Tested on various modes and the operation is confirmed.
None.
None.
None.
> refactor(tier4_perception_launch): refactoring detection launchers

- evaluator/perception_online_evaluator/src/metrics/detection_count.cpp
```
/home/emb4/autoware/autoware/src/universe/autoware.universe/evaluator/perception_online_evaluator/src/metrics/detection_count.cpp:113:69: error: repeated branch in conditional chain [bugprone-branch-clone,-warnings-as-errors]
if (time_series_counts_.find(i) == time_series_counts_.end()) {
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/evaluator/perception_online_evaluator/src/metrics/detection_count.cpp:116:8: note: end of the original
} else if (time_series_counts_[i].find(range_str) == time_series_counts_[i].end()) {
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/evaluator/perception_online_evaluator/src/metrics/detection_count.cpp:116:90: note: clone 1 starts here
} else if …
```
> fix(perception_online_evaluator): fix bugprone-branch-clone

- perception/autoware_radar_fusion_to_detected_object/src/node.cpp
- perception/autoware_radar_fusion_to_detected_object/src/radar_fusion_to_detected_object.cpp
This is a fix based on clang-tidy `bugprone-branch-clone` and `bugprone-reserved-identifier` error.
```
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_radar_fusion_to_detected_object/src/node.cpp:28:26: error: declaration uses identifier '_1', which is reserved in the global namespace; cannot be fixed automatically [bugprone-reserved-identifier,-warnings-as-errors]
using std::placeholders::_1;
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_radar_fusion_to_detected_object/src/radar_fusion_to_detected_object.cpp:161:43: error: repeated branch in conditional chain [bugprone-branch-clone,-warnings-as-errors]
if (std::abs(diff_yaw) < yaw_threshold) {
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autow …
```
> fix(autoware_radar_fusion_to_detected_object): fix bugprone-errors

- common/autoware_test_utils/test_map/road_shoulder/lanelet2_map.osm
- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/test/test_util.cpp
add another bus-stop area
- Link
None.
None.
None.
> chore(autoware_test_utils): update test map

- control/autoware_pid_longitudinal_controller/include/autoware/pid_longitudinal_controller/debug_values.hpp
- control/autoware_pid_longitudinal_controller/include/autoware/pid_longitudinal_controller/smooth_stop.hpp
- control/autoware_pid_longitudinal_controller/src/pid_longitudinal_controller.cpp
- control/autoware_pid_longitudinal_controller/src/smooth_stop.cpp
- control/autoware_pid_longitudinal_controller/test/test_smooth_stop.cpp
Added smooth_stop mode in debug_values for debugging.
psim worked.
None.
None.
None.
> feat(pid_longitudinal_controller): add smooth_stop mode in debug_values

- perception/autoware_ground_segmentation/src/scan_ground_filter/node.cpp
```
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_ground_segmentation/src/scan_ground_filter/node.cpp:261:64: error: repeated branch in conditional chain [bugprone-branch-clone,-warnings-as-errors]
(std::abs(height_from_obj) >= split_height_distance_)) {
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_ground_segmentation/src/scan_ground_filter/node.cpp:263:8: note: end of the original
} else if (is_point_close_to_prev && std::abs(height_from_gnd) < split_height_distance_) {
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_ground_segmentation/src/scan_ground_filter/node.cpp:267:14: note: clone 1 starts here
} else {
^
``` …
> fix(autoware_ground_segmentation): fix bugprone-branch-clone

- planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/package.xml
- planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/manager.hpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/manager.hpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_planner/package.xml
- planning/behavior_velocity_planner/autoware_behavior_velocity_planner/src/node.hpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/include/autoware/behavior_velocity_planner_common/planner_data.hpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/package.xml
Remove unnecessary messages shown in the PR's title.
unit test
None.
None.
None.
> feat(behavior_velocity_planner): remove unnecessary tier4_api_msgs

- build_depends.repos
update autoware_internal_tools version in build_depends.repos
- Link
None.
None.
None.
> feat: update autoware_internal_msgs version in build_depends.repos

- planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/planner_data.hpp
- planning/motion_velocity_planner/autoware_motion_velocity_planner_node/README.md
- planning/motion_velocity_planner/autoware_motion_velocity_planner_node/launch/motion_velocity_planner.launch.xml
- planning/motion_velocity_planner/autoware_motion_velocity_planner_node/src/node.cpp
- planning/motion_velocity_planner/autoware_motion_velocity_planner_node/src/node.hpp
- planning/motion_velocity_planner/autoware_motion_velocity_planner_node/test/src/test_node_interface.cpp
Remove unnecessary messages shown in the PR's title.
unit test
None.
None.
None.
> feat(motion_velocity_planner): remove unnecessary tier4_api_msgs and tier4_v2x_msgs

- control/autoware_trajectory_follower_node/config/plot_juggler_trajectory_follower.xml
update plotjuggler settings
- Link
None.
None.
None.
> feat(pid_longitudinal_controller): update plotjuggler settings

- control/autoware_trajectory_follower_node/config/plot_juggler_trajectory_follower.xml
fix spell
- Link
None.
None.
None.
> chore(trajectory_follower_node): fix typos

- .cppcheck_suppressions
ignore examples/ directory for cppcheck because they are used for documentation/development/plotting.
- Link
None.
None.
None.
> chore(cppcheck): ignore examples/ dir

- planning/README.md
This pull request corrects minor grammatical errors and includes a sentence revised for clarity.
> fix(planning): corrects minor typos

- planning/behavior_velocity_planner/autoware_behavior_velocity_stop_line_module/README.md
This pull request corrects minor grammatical errors.
fix(planning): corrects typo in svg [#9814](https://github.com/autowarefoundation/autoware.universe/pull/9814)
@yhisaki Please review this pull request when you have time.
> fix(planning): corrects typos

- planning/behavior_path_planner/autoware_behavior_path_planner/docs/behavior_path_planner_manager_design.md
- planning/behavior_path_planner/autoware_behavior_path_planner/package.xml
Slightly revise the explanation of the planner manager.
- Link
None.
None.
None.
> docs(bpp): revise explanation for Failure modules

- planning/behavior_path_planner/autoware_behavior_path_planner/README.md
This pull request includes minor adjustments for clarity and consistency.
@satoshi-ota please review this pull request when you have time.
> fix(planning): text revisions

- planning/autoware_rtc_interface/src/rtc_interface.cpp
```
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/autoware_rtc_interface/src/rtc_interface.cpp:83:46: error: repeated branch in conditional chain [bugprone-branch-clone,-warnings-as-errors]
} else if (module_name == "traffic_light") {
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/autoware_rtc_interface/src/rtc_interface.cpp:85:4: note: end of the original
} else if (module_name == "virtual_traffic_light") {
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/autoware_rtc_interface/src/rtc_interface.cpp:85:54: note: clone 1 starts here
} else if (module_name == "virtual_traffic_light") {
^
```
- Link
None.
None.
None.
> fix(autoware_rtc_interface): fix bugprone-branch-clone

- planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/src/scene.cpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection.cpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_no_drivable_lane_module/src/scene.cpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_no_stopping_area_module/src/scene_no_stopping_area.cpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_occlusion_spot_module/src/scene_occlusion_spot.cpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/include/autoware/behavior_velocity_planner_common/scene_module_interface.hpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_stop_line_module/src/scene.cpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_stop_line_module/src/scene.hpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/manager.cpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/scene.cpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_virtual_traffic_light_module/src/scene.cpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_virtual_traffic_light_module/src/scene.hpp
wrap up this work: https://github.com/autowarefoundation/autoware.universe/pull/9927
- https://github.com/tier4/autoware.universe/pull/1767
- https://github.com/tier4/autoware.universe/pull/1766
https://github.com/autowarefoundation/autoware.universe/pull/9927
- Link
- https://evaluation.tier4.jp/evaluation/reports/e824150d-92fd-5df5-bd6c-cd9e24411af3?project_id=prd_jt
None.
None.
None.
> feat(behavior_velocity_planner)!: remove velocity_factor completely

- planning/behavior_path_planner/autoware_behavior_path_planner_common/docs/behavior_path_planner_path_generation_design.md
fix dead link in path_generator
- https://star4.slack.com/archives/C03QW0GU6P7/p1737537841828419?thread_ts=1737537730.575109&cid=C03QW0GU6P7
check the page
- https://github.com/autowarefoundation/autoware.universe/blob/f360763d2153ce62c80f272f44151526f09bdd1f/planning/behavior_path_planner/autoware_behavior_path_planner/README.md
- https://github.com/autowarefoundation/autoware.universe/blob/fcd1c7bdbb7bef749b57e8c13ba255fa4e7de2ae/planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/path_shifter/path_shifter.hpp
None.
None.
None.
> docs(behavior_path_planner): fix dead link in path_generator

- planning/behavior_path_planner/autoware_behavior_path_planner_common/docs/behavior_path_planner_path_generation_design.md
This pull request includes minor adjustments for clarity and consistency.
https://star4.slack.com/archives/C03QW0GU6P7/p1737537841828419?thread_ts=1737537730.575109&cid=C03QW0GU6P7
@kosuke55 Please review this pull request when you have time.
None.
None.
> docs(behaivor_path_planner_common): includes minor corrections

- perception/autoware_lidar_centerpoint/package.xml
Adds maintainer to `autoware_lidar_centerpoint`.
- Link
None.
None.
None.
> chore(autoware_lidar_centerpoint): add maintainer

- system/autoware_topic_relay_controller/config/topic_relay_controller.param.yaml
This PR fixes the typo `necessary`. 
- https://github.com/autowarefoundation/autoware.universe/pull/10080#issuecomment-2641837292
- https://github.com/autowarefoundation/autoware.universe/actions/runs/13191924050/job/36826302482?pr=10080
None.
None.
None.
> fix(autoware_topic_relay_controller): fix typo

- sensing/autoware_pointcloud_preprocessor/package.xml
Add myself to pointcloud_preprocessor codeowners.
> chore(pointcloud_preprocessor): add Max to codeowners

- perception/autoware_map_based_prediction/README.md
- perception/autoware_map_based_prediction/include/map_based_prediction/map_based_prediction_node.hpp
- perception/autoware_map_based_prediction/src/map_based_prediction_node.cpp
delete unsed function in autoware_map_based_prediction
https://github.com/autowarefoundation/autoware.universe/pull/3806
https://github.com/autowarefoundation/autoware.universe/pull/2822
I confirmed that Autoware builds successfully and launches properly.
None.
None.
None.
> chore(autoware_map_based_prediction): delete unused function and parameter

- common/autoware_trajectory/package.xml
remove unnecessary tier4 planing msgs to port to core.
[internal slack](https://star4.slack.com/archives/C070FQMREVB/p1739160176405139?thread_ts=1739159894.310699&cid=C070FQMREVB)
to merge
https://github.com/autowarefoundation/autoware.core/pull/138#issuecomment-2614719834
- Link
build in local
2025/02/11 https://evaluation.tier4.jp/evaluation/reports/f996e92a-0991-5cd0-90e1-8a27ce519d81/?project_id=prd_jt
None.
None.
None.
> chore(autoware_trajectory): remove unnecessary tier4_planing_msgs dependency

- planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/drivable_area_expansion/static_drivable_area.cpp
minor refactor for readability
- Link
None.
None.
None.
> refactor(bpp_common): refactor calcBound

- control/autoware_autonomous_emergency_braking/package.xml
chore(autonomous_emergency_braking): remove unnecessary dependency
- Link
None.
None.
None.
> chore(autonomous_emergency_braking): remove unnecessary dependency

- launch/tier4_perception_launch/launch/perception.launch.xml
Change tlr pedestrian classifier model
https://github.com/autowarefoundation/autoware_launch/pull/1329
- Link
https://evaluation.ci.tier4.jp/evaluation/reports/e7ce0622-19ed-53ac-8406-4f1d8e3caabd?project_id=prd_jt
None.
None.
None.
> feat(tier4_perception_launch): change tlr pedestrian classifier model 

- perception/autoware_traffic_light_selector/package.xml
`autoware_traffic_light_selector` fails to build with this message:
```
2025-02-14T06:16:35.9827972Z CMake Error at CMakeLists.txt:8 (find_package):
2025-02-14T06:16:35.9829016Z   By not providing "FindSophus.cmake" in CMAKE_MODULE_PATH this project has
2025-02-14T06:16:35.9830530Z   asked CMake to find a package configuration file provided by "Sophus", but
2025-02-14T06:16:35.9831421Z   CMake did not find one.
2025-02-14T06:16:35.9831759Z
2025-02-14T06:16:35.9832182Z   Could not find a package configuration file provided by "Sophus" with any
2025-02-14T06:16:35.9833075Z   of the following names:
2025-02-14T06:16:35.9833506Z
2025-02-14T06:16:35.9833701Z     SophusConfig.cmake
2025-02-14T06:16:35.9834135Z     sophus-config.cmake
2025-02-14T06:16:35.9834329Z
2025-02-14T06:16:35.9834603Z …
```
> build(autoware_traffic_light_selector): fix missing sophus dependency

- .github/workflows/clang-tidy-differential.yaml
- visualization/autoware_bag_time_manager_rviz_plugin/src/bag_time_manager_panel.cpp
- I've missed this workflow during this PR: https://github.com/autowarefoundation/autoware.universe/pull/10148
- This PR fixes it.
- https://github.com/autowarefoundation/autoware.universe/issues/10159
- Testing with a [dummy change](https://github.com/autowarefoundation/autoware.universe/pull/10162/commits/c0291604c7176a57e3f1ec0dbb688b1de95b15cd):
-  https://github.com/autowarefoundation/autoware.universe/actions/runs/13406141904/job/37446436915?pr=10162 ✅
None.
None.
None.
> ci(build_depends.repos): fix for clang-tidy-differential

- perception/autoware_traffic_light_category_merger/package.xml
This adds missing dependency of autoware_universe_utils in package.xml.
Currently, the dependency is introduced via autoware_test_utils, but autoware_test_utils will no longer depend on autoware_universe_utils after porting to Autoware Core in https://github.com/autowarefoundation/autoware.core/pull/172. Therefore, we should explicitly define dependency to use autoware_universe_utils in this package. (like in [this line](https://github.com/autowarefoundation/autoware.universe/blob/81489202f5f98ef84917de82a7f40337e4f0336c/perception/autoware_traffic_light_category_merger/src/traffic_light_category_merger_node.hpp#L18))
- Related Discussion: https://github.com/orgs/autowarefoundation/discussions/5365
- Related PR: https://github.com/autowarefoundation/autoware.core/pull/172
Build test in …
> fix(autoware_traffic_light_category_merger): add missing dependency to autoware_universe_utils

- planning/autoware_objects_of_interest_marker_interface/include/autoware/objects_of_interest_marker_interface/coloring.hpp
- planning/autoware_objects_of_interest_marker_interface/include/autoware/objects_of_interest_marker_interface/marker_utils.hpp
- planning/autoware_objects_of_interest_marker_interface/package.xml
- planning/autoware_objects_of_interest_marker_interface/src/coloring.cpp
- planning/autoware_objects_of_interest_marker_interface/src/marker_utils.cpp
- planning/autoware_objects_of_interest_marker_interface/src/objects_of_interest_marker_interface.cpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/occluded_crosswalk.cpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection_occlusion.cpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection_prepare_data.cpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection_stuck.cpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_merge_from_private_road.cpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_walkway_module/src/scene_walkway.cpp
- planning/motion_velocity_planner/autoware_motion_velocity_obstacle_cruise_module/src/obstacle_cruise_module.cpp
- planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/src/obstacle_slow_down_module.cpp
- planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/obstacle_stop_module.cpp
This PR replaces autoware_universe_utils with autoware_utils in autoware_objects_of_interest_marker_interface as preparation of porting to Autoware Core.
This also modify packages that depend on autoware_universe_utils via autoware_objects_of_interest_marker_interface to pass the build CI, but the modification is only adding extra header files so it shouldn't have any affect to the behavior.
- https://github.com/autowarefoundation/autoware.core/issues/131
Related PRs:
- https://github.com/autowarefoundation/autoware.universe/pull/9931
- https://github.com/autowarefoundation/autoware.core/pull/168
Tested on TIER IV Evaluator
https://evaluation.ci.tier4.jp/evaluation/reports/ee4d479b-6b65-50f4-80b5-e25ffef8f1e3?project_id=prd_jt
None.
None.
None.
> feat(autoware_objects_of_interest_marker_interface): replace autoware_universe_utils with autoware_utils

- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/pull_over_planner/shift_pull_over.hpp
- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/shift_pull_over.cpp
just remove unused function
- Link
None.
None.
None.
> refactor(goal_planner, QC): remove unused function

- perception/autoware_elevation_map_loader/package.xml
add grid_map_rviz_plugin to dependency to visualize in rviz
( but this is not necessary to build elevation_map_loader.)
internal: https://star4.slack.com/archives/C024FRX4UNL/p1739748576891299
- Link
rosdep install ( but this package is already installed in my envirionment)
```
~/pilot-auto (main $%=)
$ rosdep install -y --from-paths src --ignore-src --rosdistro $ROS_DISTRO
#All required rosdeps installed successfully
```
None.
None.
None.
> feat(elevation_map_loader): add grid_map_rviz_plugin to dependency

- planning/autoware_route_handler/include/autoware/route_handler/route_handler.hpp
- planning/autoware_route_handler/src/route_handler.cpp
just remove unused function
- Link
build ci passes
None.
None.
None.
> chore(route_handler, QC): remove unused function

- control/autoware_mpc_lateral_controller/package.xml
Add package maintainer
None.
N/A
None.
None.
None.
> chore(mpc_lateral_controller): add package maintainer

- launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.xml
This PR remaps output topics of `path_generator` (turn signal and hazard signal).
None.
None.
None.
> fix(tier4_planning_launch): remap topics for path_generator

- planning/autoware_path_optimizer/include/autoware/path_optimizer/mpt_optimizer.hpp
- planning/autoware_path_optimizer/src/mpt_optimizer.cpp
Removed unnecessary optional in path_optimizer
psim worked well.
None.
None.
None.
> fix(path_optimizer): remove unnecesary optional

- planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_collisions.cpp
In function `calculate_object_path_time_collisions` the time is initialized with `time_step` and is incremented before processing each  pose along the object predicted path, which causes the time calculation to be 2 steps ahead of the correct value.
This PR fixes the issue by initializing the time with zero and incrementing after processing each pose.
None.
- [TIER IV Internal Evaluator](https://evaluation.tier4.jp/evaluation/reports/e7730f44-a138-5c33-8087-86e37198ea08?project_id=prd_jt)
None.
None.
None.
> fix(out_of_lane): fix object path time collision calculation

- sensing/autoware_cuda_pointcloud_preprocessor/package.xml
Add maintainer.
- Link
None.
None.
None.
> chore(autoware_cuda_pointcloud_preprocessor): add maintainer

- evaluator/autoware_localization_evaluator/package.xml
- perception/autoware_image_projection_based_fusion/package.xml
- perception/autoware_lidar_centerpoint/package.xml
Remove minoda-san from code maintainer.
- As part of the history, do not remove minoda-san from author
- He is the only code owner of package `tier4_system_rviz_plugin`. Someone need to be a maintainer
- Link
None.
None.
None.
> chore(localization, perception): remove koji minoda as maintainer from multiple packages

- common/autoware_traffic_light_utils/package.xml
- launch/tier4_perception_launch/package.xml
- perception/autoware_lidar_centerpoint/package.xml
- perception/autoware_object_range_splitter/package.xml
- perception/autoware_object_velocity_splitter/package.xml
- perception/autoware_shape_estimation/package.xml
- perception/autoware_simple_object_merger/package.xml
- perception/autoware_tensorrt_classifier/package.xml
- sensing/autoware_image_diagnostics/package.xml
Updating code owner
- add Saeki-san to traffic light related packages
- add Tanaka-san to centerpoint, since the maintainers has been reduced
- add Taekjin to object related packages
- Link
None.
None.
None.
> chore(perception): code owner revision

- build_depends_humble.repos
- common/autoware_agnocast_wrapper/CMakeLists.txt
- common/autoware_agnocast_wrapper/README.md
- common/autoware_agnocast_wrapper/cmake/agnocast_wrapper_config_extras.cmake
- common/autoware_agnocast_wrapper/include/autoware/agnocast_wrapper/autoware_agnocast_wrapper.hpp
- common/autoware_agnocast_wrapper/package.xml
Re-create https://github.com/autowarefoundation/autoware_universe/pull/10371.
Please refer to the `README.md` for the purpose and usage of the package.
- Agnocast Repository: <https://github.com/tier4/agnocast>
- Discussion on Agnocast Integration into Autoware: <https://github.com/orgs/autowarefoundation/discussions/5835>
- https://github.com/autowarefoundation/autoware/issues/5968
The expected behavior described in the `README.md` has been tested on each of the branches listed below using the macros provided by this package.
- https://github.com/veqcc/autoware/tree/test/agnocast
- https://github.com/veqcc/autoware.universe/commits/test/agnocast/
- https://github.com/autowarefoundation/autoware_launch/commits/test/agnocast/
- https://github.com/autowarefoundation/sample_sensor_kit_launch/ …
> feat: add autoware_agnocast_wrapper package

- localization/autoware_landmark_based_localizer/autoware_lidar_marker_localizer/launch/lidar_marker_localizer.launch.xml
fix typo
- Link
None.
None.
None.
> fix(lidar_marker_localizer): fix typo in launch file

- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp
- planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/scene.hpp
- planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp
apply THROTTLE to frequent log in the behavior_path_planner
- Link
Build passed.
None.
None.
None.
> fix(behavior_path_planner): apply THROTTLE to frequent log

- planning/autoware_planning_validator/src/planning_validator.cpp
- planning/autoware_remaining_distance_time_calculator/src/remaining_distance_time_calculator_node.cpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_run_out_module/src/scene.cpp
apply THROTTLE to frequent log in the planning component
- Link
Build passed.
None.
None.
None.
> fix(planning): apply THROTTLE to frequent log

- planning/autoware_planning_validator/package.xml
Add maintainer.
None.
None.
None.
None.
> chore(autoware_planning_validator): add new maintainers to planning_validator

- launch/tier4_perception_launch/launch/object_recognition/detection/detector/lidar_dnn_detector.launch.xml
This PR adds a launch argument of parameter file path for the lidar_centerpoint package to introduce diagnostics.
See https://github.com/autowarefoundation/autoware_universe/pull/10284 .
This PR must merge with https://github.com/autowarefoundation/autoware_launch/pull/1377 .
- Link
Checked by running a sample ROS bag and confirmed that it can read the parameter file properly with https://github.com/autowarefoundation/autoware_launch/pull/1377 .
None.
None.
None.
> feat(perception_launch): add common param file

- system/autoware_mrm_handler/src/mrm_handler/mrm_handler_core.cpp
Modify log level because there are too many logs to read.
- [TIER IV internal link](https://star4.slack.com/archives/C075BTE8TPB/p1744074295183139)
Check the vehicle drives in autonomous mode using simple planning simulator.
None.
None.
None.
> feat(mrm_handler): modify log level

- perception/autoware_image_projection_based_fusion/config/pointpainting_common.param.yaml
- perception/autoware_image_projection_based_fusion/include/autoware/image_projection_based_fusion/pointpainting_fusion/node.hpp
- perception/autoware_image_projection_based_fusion/launch/pointpainting_fusion.launch.xml
- perception/autoware_image_projection_based_fusion/schema/pointpainting_common.schema.json
- perception/autoware_image_projection_based_fusion/src/pointpainting_fusion/node.cpp
This PR adds diagnostics for pointpainting's processing time.
If the processing time exceeds `max_allowed_processing_time_ms`, a warning topic will be published.
Consecutive delays will be also checked.
If the difference of two timestamp (current and last in-time processed timestamp) is larger than `max_acceptable_consecutive_delay_ms`, it will determine as an error state.
If the new processing time is below the `max_allowed_processing_time_ms`, it will update the timestamp of last in-time processed case.
- Link
Tested by checking the rqt_runtime_monitor.
Run rqt_runtime_monitor by
```sh
ros2 run rqt_runtime_monitor rqt_runtime_monitor
```
None.
None.
None.
> feat(pointpainting_fusion): add diagnostics for processing time of pointpainting

- launch/tier4_autoware_api_launch/launch/deprecated_api.launch.xml
The msgs for manual driving API has been replaced with autowar_adapi_v1_msgs. The previous one uses tier4_api_msgs, so add adapter for compatibility.
https://github.com/autowarefoundation/autoware_universe/pull/10354
https://github.com/tier4/tier4_ad_api_adaptor/pull/138
- https://github.com/autowarefoundation/autoware/issues/3096#issuecomment-2785846336
See https://github.com/tier4/tier4_ad_api_adaptor/pull/138
None.
None.
None.
> feat(tier4_autoware_api_launch): launch tier4_deprecated_api_adapter

- build_depends_humble.repos
This updates the versions in build_depends_humble.repos to match with the versions in [autoware.repos](https://github.com/autowarefoundation/autoware/blob/main/autoware.repos) from autoware repository. 
This resolves the issues that we are having with some build-and-test-differential action ([example](https://github.com/autowarefoundation/autoware_universe/actions/runs/14393503988/job/40365017050?pr=9197#step:15:16844))
- https://github.com/autowarefoundation/autoware_universe/pull/9197
No change in Autoware behavior so we just have to check if the build CI passes for this PR.
https://github.com/autowarefoundation/autoware_universe/actions/runs/14395683442/job/40370843134?pr=10437
None.
None.
None.
> ci: update versions in build_depends_humble.repos

- perception/autoware_bevfusion/package.xml
Add maintainer.
- Link
None.
None.
None.
> chore(autoware_bevfusion): add maintainer

- perception/autoware_tensorrt_yolox/CMakeLists.txt
This PR installs a shared library named `libautoware_tensorrt_yolox_gpu_preprocess.so` under the `install` directory.
This makes the outcome binary linked to the shared library under the install directory instead of one under the build directory
None.
- Check the linking status before modification
```bash
$ source install/setup.bash
$ ls ./install/autoware_tensorrt_yolox/lib/
autoware_tensorrt_yolox  libautoware_tensorrt_yolox.so  libautoware_tensorrt_yolox_node.so  liibyolox_single_image_inference_node.so
$ ldd ./install/autoware_tensorrt_yolox/lib/libautoware_tensorrt_yolox.so | grep gpu
libautoware_tensorrt_yolox_gpu_preprocess.so => ${AUTOWARE_DIR}/build/autoware_tensorrt_yolox/libautoware_tensorrt_yolox_gpu_preprocess.so
```
- After modification, rebuild the package
```bash
$ rm -rf …
```
> fix(autoware_tensorrt_yolox): explicitly install shared library

- perception/autoware_tensorrt_yolox/package.xml
```
In file included from /home/autoware/pilot-auto/src/autoware/universe/perception/autoware_tensorrt_yolox/src/tensorrt_yolox_node.cpp:15:
/home/autoware/pilot-auto/src/autoware/universe/perception/autoware_tensorrt_yolox/include/autoware/tensorrt_yolox/tensorrt_yolox_node.hpp:21:10: fatal error: autoware_utils/ros/debug_publisher.hpp: No such file or directory
21 | #include <autoware_utils/ros/debug_publisher.hpp>
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gmake[2]: *** [CMakeFiles/autoware_tensorrt_yolox_node.dir/build.make:76: CMakeFiles/autoware_tensorrt_yolox_node.dir/src/tensorrt_yolox_node.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:254: CMakeFiles/autoware_tensorrt_yolox_node.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
--- …
```
> feat(tensorrt_yolox): add autoware_utils packages

- perception/autoware_detected_object_validation/src/lanelet_filter/lanelet_filter.cpp
- perception/autoware_simple_object_merger/src/simple_object_merger_node.cpp
- perception/autoware_simple_object_merger/src/simple_object_merger_node.hpp
Limit the logger warning frequency up to 3.0 sec
- Link
- I manually cherry-picked the features and build & test example data in [autowarefundation main branch](https://github.com/autowarefoundation/autoware/tree/main)
- Below are tested -> **normal**
- [Logging_simulator](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/rosbag-replay-simulation/#rosbag-replay-simulation)
- [Planning simulator](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/planning-simulation/#basic-simulations)
- I cherry-picked the features and build & test in Autoware for bus project using rosbag of 1min duration and check the count of log contains `Topic of /sensing/radar/rear_center/detected_objects is timeout …
> feat: reduce warn log frequency

- perception/autoware_radar_object_tracker/src/association/data_association.cpp
Add  required headers. https://github.com/autowarefoundation/autoware_core/pull/385 revealed this issue.
https://github.com/autowarefoundation/autoware_core/pull/385 
Check if the universe build passes.
None.
None.
None.
> fix(radar_object_tracker): add required headers

- control/autoware_mpc_lateral_controller/include/autoware/mpc_lateral_controller/qp_solver/qp_solver_osqp.hpp
- control/autoware_mpc_lateral_controller/src/mpc_lateral_controller.cpp
- control/autoware_mpc_lateral_controller/src/qp_solver/qp_solver_osqp.cpp
- control/autoware_mpc_lateral_controller/test/test_mpc.cpp
- control/autoware_operation_mode_transition_manager/src/node.cpp
- control/autoware_operation_mode_transition_manager/src/state.cpp
apply THROTTLE to frequent log in the control component
- Link
Build passed.
None.
None.
None.
> fix(control): apply THROTTLE to frequent log

- control/autoware_control_validator/src/control_validator.cpp
This PR addresses the following issue:
Currently, the control_validator cancels the validation process if the point size of predicted_trajectory is less than two. This causes longitudinal validations to be canceled when the ego vehicle overruns the goal pose, even though such situations are critical.
In addition, to reduce maintenance costs, `calcSignedArcLength()` in the `dist_to_stop` calculation is now used correctly.
psim:
error diags are published when the ego overrun the goal.
tier4 scenario tests https://evaluation.tier4.jp/evaluation/reports/18d7c46d-2b9d-56fb-8c73-ab3ea47f996d?project_id=prd_jt
tier4 DLR tests https://evaluation.tier4.jp/evaluation/reports/75697820-226d-564f-81ad-34bc94c764ca?project_id=prd_jt
None.
None.
None.
> fix(control_validator): fix less trajectory point check

- perception/autoware_elevation_map_loader/package.xml
This PR adds map_msgs as a dependency to fix build issues.
- https://github.com/autowarefoundation/autoware-deb-packages/issues/129
None.
None.
None.
> build(autoware_elevation_map_loader): add map_msgs dependency

- planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/src/types.hpp
Based on cppcheck `unusedFunction` warings
```
<error id="unusedFunction" severity="style" msg="The function &apos;has_data_before_time&apos; is never used." verbose="The function &apos;has_data_before_time&apos; is never used." cwe="561">
<location file="planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/src/types.hpp" line="278" column="0"/>
<symbol>has_data_before_time</symbol>
</error>
<error id="unusedFunction" severity="style" msg="The function &apos;first_index_at_or_after_time&apos; is never used." verbose="The function &apos;first_index_at_or_after_time&apos; is never used." cwe="561">
<location file="planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/src/types.hpp" line="282" column="0"/>
<symbol>first_index_at_or_after_time</symbol> …
```
> fix(motion_velocity_planner): remove unused functions

- planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/interface/scene_module_manager_interface.hpp
- planning/behavior_path_planner/autoware_behavior_path_start_planner_module/include/autoware/behavior_path_start_planner_module/start_planner_module.hpp
- planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/start_planner_module.cpp
There are several factors that `start_planner` can't generate path, such as when the vehicle deviates from its lane or when safety cannot be guaranteed with stationary objects. Since it is difficult to definitively determine these factors, I added details in the [PR](https://github.com/autowarefoundation/autoware_universe/pull/10029).
However, from a user perspective, there are many complex elements such as planner priorities, so I added the route generation failure factors to the detail field as a judgment criterion that can handle most cases without considering edge cases.
I expect that detailed judgments will still be made based on the explanation in this [PR](https://github.com/autowarefoundation/autoware_universe/pull/10029).
- Link
All test cases confirmed that the …
> feat(start_planner): add virtual stop detail

- common/tier4_api_utils/include/tier4_api_utils/rclcpp/service.hpp
Modify log level because there are too many logs to read.
- [TIER IV internal link](https://star4.slack.com/archives/C075BTE8TPB/p1744074295183139)
Check the vehicle drives in autonomous mode using simple planning simulator.
None.
None.
None.
> feat(tier4_api_utils): modify log level

- map/autoware_lanelet2_map_visualizer/src/lanelet2_map_visualization_node.cpp
This PR visualize waypoints if 
- [use_waypoints](https://github.com/autowarefoundation/autoware_launch/blob/4db3ae9257e67fc5c5ce94f9d6adc29f477b279a/autoware_launch/config/map/lanelet2_map_loader.param.yaml#L5C5-L5C18): true
:exclamation: **Should be merged after and tested with** https://github.com/autowarefoundation/autoware_lanelet2_extension/pull/56
**Before**
**After**
- Link
None.
None.
None.
> feat(autoware_lanelet2_map_visualizer): visualize waypoints

- perception/autoware_traffic_light_category_merger/CMakeLists.txt
- perception/autoware_traffic_light_category_merger/src/traffic_light_category_merger_node.cpp
- perception/autoware_traffic_light_category_merger/src/traffic_light_category_merger_node.hpp
This PR get to reduce dependency.
- Link
https://evaluation.ci.tier4.jp/evaluation/reports/fe29e7e0-9dff-5692-aa12-306f806ea6ed?project_id=prd_jt
None.
None.
None.
> chore(autoware_traffic_light_category_merger): reduce dependency

- control/autoware_control_validator/package.xml
update maintainer
None.
None.
None.
> chore(control_validator): update maintainer

- perception/autoware_bevfusion/schema/bevfusion.schema.json
fix the schema file
- Link
None.
None.
None.
> feat(bevfusion.schema): add default values for sensor_fusion and thresholds array

- launch/tier4_perception_launch/launch/object_recognition/detection/detection.launch.xml
- launch/tier4_perception_launch/launch/object_recognition/detection/detector/camera_lidar_detector.launch.xml
- launch/tier4_perception_launch/launch/perception.launch.xml
- perception/autoware_image_projection_based_fusion/launch/segmentation_pointcloud_fusion.launch.py
- Add camera IDs selectable for segmentation_pointcloud_fusion node.
- Merge together with https://github.com/autowarefoundation/autoware_launch/pull/1439
- [TIER IV internal LINK](https://tier4.atlassian.net/browse/RT0-36931)
- Tested and passed by Internal evaluator: https://evaluation.tier4.jp/evaluation/reports/baeb4a91-32db-53cb-a657-e9e84d281019?project_id=prd_jt
- run logging_simulator with `use_image_segmentation_based_filter` used option:
- `ros2 launch autoware_launch logging_simulator.launch.xml map_path:=/home/autoware/data/maps/odaiba/split/335-20230619111251589507/ vehicle_model:=lexus sensor_model:=aip_xx1 rviz:=true  perception:=true sensing:=true localization:=false control:=false planning:=false use_traffic_light_recognition:=false perception_mode:=camera_lidar_fusion …
> fix(segmentation pointcloud fusion): fix launch for selectable camera IDs

- launch/tier4_perception_launch/launch/object_recognition/detection/filter/radar_filter.launch.xml
- launch/tier4_perception_launch/package.xml
- perception/autoware_simple_object_merger/src/simple_object_merger_node.cpp
update for new radar message definition
1. remove autoware_radar_crossing_objects_noise_filter
2. remove autoware_radar_object_clustering
3. simple object merger pub/sub QoS setting
- message https://github.com/autowarefoundation/autoware_msgs/pull/120
- nebula driver https://github.com/tier4/nebula/pull/284
- adapter  https://github.com/autowarefoundation/autoware_universe/pull/10459
- adapter update https://github.com/autowarefoundation/autoware_universe/pull/10556
- universe launcher https://github.com/autowarefoundation/autoware_universe/pull/10580
- autoware_launch https://github.com/autowarefoundation/autoware_launch/pull/1428
- aip_launcher https://github.com/tier4/aip_launcher/pull/446
- autoware https://github.com/autowarefoundation/autoware/pull/6128
[INTERNAL …
> feat(radar): update radar pipeline

- sensing/autoware_radar_objects_adapter/README.md
fix the schema file path.
- Link
None.
None.
None.
> fix(autoware_radar_objects_adapter): update schema path in readme

- perception/autoware_tensorrt_yolox/CMakeLists.txt
> feat(autoware_tensorrt_yolox): added target architectures for yolox

- perception/autoware_lidar_transfusion/CMakeLists.txt
- [Link](https://github.com/autowarefoundation/autoware_universe/issues/10610)
None.
None.
None.
> feat(autoware_lidar_transfusion): added target architectures for transfusion

- perception/autoware_bevfusion/CMakeLists.txt
> feat(autoware_bevfusion): added target architectures for bevfusion

- perception/autoware_lidar_centerpoint/CMakeLists.txt
> feat(autoware_lidar_centerpoint): added target architectures for centerpoint

- perception/autoware_tensorrt_plugins/package.xml
Update maintainers.
- Link
None.
None.
None.
> chore(autoware_tensorrt_plugins): update maintainer

- perception/autoware_compare_map_segmentation/package.xml
- perception/autoware_elevation_map_loader/package.xml
add @asa-naki to maitainer to elevation_map pacakges
- Link
not tested
None.
None.
None.
> chore(elevation_map): add @asa-naki to maitainer

- system/autoware_mrm_emergency_stop_operator/README.md
- system/autoware_mrm_emergency_stop_operator/src/mrm_emergency_stop_operator/mrm_emergency_stop_operator_core.cpp
- system/mrm_emergency_stop_operator/schema/mrm_emergency_stop_operator.schema.json
----------------------------------------------
Implement the ROS Node configuration layout described in [Autoware Foundation Discussion #3371](https://github.com/orgs/autowarefoundation/discussions/3371) for the `mrm_emergency_stop_operator` package.
- Remove duplication of parameter declaration between the source code and the parameter file.
- Remove the default value from the source code to ensure all parameter values are passed from the parameter files.
- Use types that match those returned from declare_parameter() to prevent confusion and potential coding errors.
- Move the default parameter file to a standardized location. Use the JSON Schema for that.
----------------------------------------------
Package built locally with `colcon build --symlink-install --cmake-args …
> refactor(mrm_emergency_stop_operator ): rework parameter

- perception/autoware_crosswalk_traffic_light_estimator/package.xml
- perception/autoware_tensorrt_classifier/package.xml
- perception/autoware_traffic_light_arbiter/package.xml
- perception/autoware_traffic_light_category_merger/package.xml
- perception/autoware_traffic_light_classifier/package.xml
- perception/autoware_traffic_light_fine_detector/package.xml
- perception/autoware_traffic_light_map_based_detector/package.xml
- perception/autoware_traffic_light_multi_camera_fusion/package.xml
- perception/autoware_traffic_light_occlusion_predictor/package.xml
- perception/autoware_traffic_light_selector/package.xml
- perception/autoware_traffic_light_visualization/package.xml
- add Taekjin Lee
- remove Kenzo-san
- Link
None.
None.
None.
> chore: update traffic light packages code owner

- perception/autoware_multi_object_tracker/include/autoware/multi_object_tracker/object_model/types.hpp
- perception/autoware_multi_object_tracker/include/autoware/multi_object_tracker/tracker/model/tracker_base.hpp
- perception/autoware_multi_object_tracker/include/autoware/multi_object_tracker/tracker/motion_model/motion_model_base.hpp
- perception/autoware_multi_object_tracker/lib/association/association.cpp
- perception/autoware_multi_object_tracker/lib/object_model/types.cpp
- perception/autoware_multi_object_tracker/lib/tracker/model/tracker_base.cpp
- perception/autoware_multi_object_tracker/lib/tracker/model/vehicle_tracker.cpp
- perception/autoware_multi_object_tracker/src/debugger/debug_object.cpp
- perception/autoware_multi_object_tracker/src/debugger/debug_object.hpp
- perception/autoware_multi_object_tracker/src/processor/processor.cpp
- perception/autoware_multi_object_tracker/src/processor/processor.hpp
Evaluate tracker confidentiality by its pose covariance size (as tracker uncertainty).
- define isConfident method to replace tracker counter based algorithm
- define isExpired method instead of tracker counters
- update `TrackerProcessor::removeOverlappedTracker`
- rename it to `mergeOverlappedTracker` and merge existence probability
- determine merge  by tracker's certainty
- debug visualization message improvements
- Link
[TIER IV INTERNAL work ticket](https://tier4.atlassian.net/browse/RT1-10114)
[TIER IV INTERNAL issue ticket](https://tier4.atlassian.net/browse/RT0-35964)
[TEST RESULT](https://evaluation.tier4.jp/evaluation/reports/c9fe4bd9-1cc7-5779-845d-fda4031be39f?project_id=prd_jt)
[PLANNING TEST](https://evaluation.tier4.jp/evaluation/reports/62e644de-cccb-52eb …
> feat(autoware_multi_object_tracker): tracker confidence check by its uncertainty

- control/autoware_control_validator/README.md
- control/autoware_control_validator/config/control_validator.param.yaml
- control/autoware_control_validator/include/autoware/control_validator/control_validator.hpp
- control/autoware_control_validator/launch/control_validator.launch.xml
- control/autoware_control_validator/msg/ControlValidatorStatus.msg
- control/autoware_control_validator/script/max_steering_rate_checker.py
- control/autoware_control_validator/src/control_validator.cpp
This PR adds steering rate validation to the control validator package, which ensures the steering commands won't produce excessive lateral jerk. The implementation:
- Adds a new `LateralJerkValidator` class that calculates lateral jerk from steering rate
- Adds a subscription to the steering status topic
- Updates the control validator status message to include steering rate and lateral jerk values
Additionally, this PR includes a python script (`max_steering_rate_checker.py`) that:
- Calculates and visualizes the maximum allowable steering rate based on vehicle velocity
- Helps developers understand the physical constraints and safety thresholds
The script can be used as a development and tuning tool when configuring the steering rate validation parameters.
**should be merged with …
> feat(control_validator): add lateral jerk validation

- perception/autoware_bevfusion/package.xml
- perception/autoware_bytetrack/package.xml
- perception/autoware_cluster_merger/package.xml
- perception/autoware_compare_map_segmentation/package.xml
- perception/autoware_detected_object_feature_remover/package.xml
- perception/autoware_detected_object_validation/package.xml
- perception/autoware_detection_by_tracker/package.xml
- perception/autoware_euclidean_cluster/package.xml
- perception/autoware_ground_segmentation/package.xml
- perception/autoware_image_projection_based_fusion/package.xml
- perception/autoware_lidar_apollo_instance_segmentation/package.xml
- perception/autoware_lidar_centerpoint/package.xml
- perception/autoware_lidar_transfusion/package.xml
- perception/autoware_multi_object_tracker/package.xml
- perception/autoware_object_merger/package.xml
- perception/autoware_object_range_splitter/package.xml
- perception/autoware_object_velocity_splitter/package.xml
- perception/autoware_occupancy_grid_map_outlier_filter/package.xml
- perception/autoware_probabilistic_occupancy_grid_map/package.xml
- perception/autoware_radar_crossing_objects_noise_filter/package.xml
- perception/autoware_raindrop_cluster_filter/package.xml
- perception/autoware_shape_estimation/package.xml
- perception/autoware_tensorrt_common/package.xml
- perception/autoware_tensorrt_plugins/package.xml
- perception/autoware_tensorrt_yolox/package.xml
- perception/autoware_tracking_object_merger/package.xml
- perception/perception_utils/package.xml
- add Lei Gu-san to detector and tracker packages
- add Taekjin to perception packages
- add Uetake-san Saeki-san, and Kok-san to ML detector packages
- Link
None.
None.
None.
> chore: perception code owner update

- perception/autoware_probabilistic_occupancy_grid_map/CMakeLists.txt
> feat(autoware_probabilistic_occupancy_grid_map): added target architectures for the ogm

- planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/parking_departure/geometric_parallel_parking.cpp
sorry this caused degradation so revert
Reverts autowarefoundation/autoware_universe#9622
https://evaluation.tier4.jp/evaluation/reports/tables/new?catalog_id=095ae8b3-a23b-4a08-8674-10a681449693&filter=&job_id=21e894e6-9200-5847-9910-7414ede440ec&project_id=prd_jt&scenario_id=e804c705-afa2-4143-b7a8-db4d5b06b372&suite_id=643ee502-163e-4fb2-b302-0b5b828e7650&table_config=date
before 
after
> fix(autoware_behavior_path_planner_common): revert "modify geometric parallel parking path planning" #9622

- launch/tier4_planning_launch/launch/scenario_planning/lane_driving/motion_planning/motion_planning.launch.xml
1. elastic band, path_optimizer
2. elastic band, none
smoothed_path_to_trajectory_converter is enabled
3. none, path_optimizer
path_smoother_relay is enabled
4. none, none
path_to_trajectory_converter is enabled
- Link
2025/05/20 https://evaluation.tier4.jp/evaluation/reports/09649d2c-5c62-5fba-986d-1c8bb226a849/?project_id=prd_jt
2025/05/20 https://evaluation.tier4.jp/evaluation/reports/222ea44f-a423-5f68-969f-fc6ddccc118f/?project_id=prd_jt
None.
None.
None.
> feat(motion_planning): add direct path to trajectory conversion pipeline when both motion_path_smoother and motion_path_planner are disabled

- perception/autoware_elevation_map_loader/src/elevation_map_loader_node.cpp
This PR improves the logging in the Elevation Map Loader to provide clearer indication of the map generation process. The logging now clearly shows when elevation map operations are starting, in progress, and completed.
- https://tier4.atlassian.net/browse/EVT4-2046 
With the current logs it's hard to tell which process is taking the time
build 
```
Finished <<< autoware_elevation_map_loader [38.0s]
```
None.
None.
None.
> feat(elevation_map_loader): improve log message

- planning/behavior_path_planner/autoware_behavior_path_avoidance_by_lane_change_module/src/scene.cpp
- planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/scene.hpp
- planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/utils.hpp
- planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp
- planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp
- planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/test/test_utils.cpp
In this bug fix, once a stop point inserted by static_obstacle_avoidance is determined to be stoppable, that decision is retained thereafter.
[Before bug fix](https://github.com/user-attachments/assets/69747e6f-6f9f-43e3-855c-d92ea148bb54)
[After Buf fix](https://github.com/user-attachments/assets/36c87bf9-6fab-4acf-99af-893e81f85cce)
- https://tier4.atlassian.net/wiki/spaces/~712020d4419494e4d045a58395dc3e567dcf92/pages/3636592738/Failed+_2025+04+14
Evaluator
- Before
- https://evaluation.tier4.jp/evaluation/reports/17aaab51-7efc-51b3-91f6-e99d794ff7c9?project_id=prd_jt
- After
- https://evaluation.tier4.jp/evaluation/reports/cc4ddae7-33aa-58e5-a15a-a73266b74cfb?project_id=prd_jt
None.
None.
None.
> fix(static_obstacle_avoidance): fix the judging algorithm that determines whether the vehicle can stop in front of the inserted stop line.

- planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/README.md
Update the parameter's explanation in README of the obstacle slow down.
- Link
None.
None.
None.
> feat(obstacle_slow_down): update parameter explanation

- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/util.hpp
- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp
- planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/util.cpp
- planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/start_planner_module.cpp
- planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/debug.hpp
- planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/scene.hpp
- planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/debug.cpp
- planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp
The Planning nodes use info and debug markers respectively.
The info marker is for the brief analysis of the node and does not make the rviz busy, and the debug marker contains detailed information for deeper analysis.
The following is **when visualizing the info markers.**
start_planner
goal_planner
static_obstacle_avoidance
- Link
None.
None.
None.
> feat(behavior_path_planner): organize a part of behavior path info/debug markers

- planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/config/intersection.param.yaml
- planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/intersection_stoplines.hpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/manager.cpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection.cpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection.hpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection_collision.cpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection_prepare_data.cpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/util.cpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/util.hpp
- https://github.com/autowarefoundation/autoware_launch/pull/1456
- https://tier4.atlassian.net/browse/RT0-35072
- Link
https://evaluation.tier4.jp/evaluation/reports/356a926e-74ae-53eb-994b-022f5108c82c?project_id=prd_jt
None.
None.
None.
> feat(intersection): experimental overshoot in merging

- evaluator/autoware_control_evaluator/src/control_evaluator_node.cpp
Refactored the branching logic of control_evaluator as the [discussion](https://github.com/autowarefoundation/autoware_universe/pull/10719#issuecomment-2914482190).
- Link
evaluator: https://evaluation.tier4.jp/evaluation/reports/99381c32-5c5f-50c8-adf4-a62e45460240?project_id=prd_jt
None.
None.
None.
> chore(control_evaluator): refactor control evaluator's logics.

- localization/autoware_pose_initializer/package.xml
- localization/autoware_pose_initializer/src/ekf_localization_trigger_module.cpp
- localization/autoware_pose_initializer/src/gnss_module.cpp
- localization/autoware_pose_initializer/src/localization_module.cpp
- localization/autoware_pose_initializer/src/ndt_localization_trigger_module.cpp
- localization/autoware_pose_initializer/src/pose_initializer_core.cpp
- localization/autoware_pose_initializer/src/pose_initializer_core.hpp
in order to port autoware_pose_initializer to autoware.core, we have to replace tier4 related dependency with autoware dependency, and remove dependency to universe packages
- Link https://github.com/autowarefoundation/autoware_core/issues/484
1. colcon build with entier autoware -- `colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release --symlink-install`
2. using AWSIM‘s pointcloud and gnss for input, using rviz for visual checking that auto-localization-initialize and continus localization using ndt works
2.1  in terminal 1 launch AWSIM and use `ros2 topic list` to confirm that the pointcloud and gnss topic exist 
2.2  in terminal 2 source autoware workspace first, then type `ros2 launch autoware_launch e2e_simulator.launch.xml vehicle_model:=sample_vehicle …
> feat(autoware_pose_initializer): remove dependency to universe packages

- planning/planning_validator/autoware_planning_validator/include/autoware/planning_validator/node.hpp
- planning/planning_validator/autoware_planning_validator/include/autoware/planning_validator/types.hpp
- planning/planning_validator/autoware_planning_validator/launch/planning_validator.launch.xml
- planning/planning_validator/autoware_planning_validator/package.xml
- planning/planning_validator/autoware_planning_validator/src/node.cpp
- planning/planning_validator/autoware_planning_validator/test/src/test_planning_validator_node_interface.cpp
- planning/planning_validator/autoware_planning_validator_trajectory_checker/test/test_trajectory_checker_diag.cpp
This PR enhances the planning_validator module by subscribing to an additional topic for improved collision detection. By incorporating more data sources, the system can perform more accurate validation of planned trajectories, contributing to safer autonomous driving behavior.
```c++
autoware_utils::InterProcessPollingSubscriber<PointCloud2> sub_pointcloud_{
this, "~/input/pointcloud", autoware_utils::single_depth_sensor_qos()};
autoware_utils::InterProcessPollingSubscriber<
LaneletRoute, autoware_utils::polling_policy::Newest>
sub_route_{this, "~/input/route", rclcpp::QoS{1}.transient_local()};
autoware_utils::InterProcessPollingSubscriber<
LaneletMapBin, autoware_utils::polling_policy::Newest>
sub_lanelet_map_bin_{this, "~/input/lanelet_map_bin", rclcpp::QoS{1}.transient_local()};
``` …
> feat(planning_validator): subscribe additional topic for collision detection

- launch/tier4_perception_launch/launch/occupancy_grid_map/probabilistic_occupancy_grid_map.launch.xml
- launch/tier4_simulator_launch/launch/simulator.launch.xml
**This PR must be merged after https://github.com/autowarefoundation/autoware_launch/pull/1479**
We are currently trying to run simulator.launch.xml as standalone launch in order to run Autoware in multi-container setup in this issue. However, probabilistic_occupancy_grid_map.launch.xml fails to launch properly because it cannot find pointcloud_container, which is not created in multi-container settings. (Check [my comment](https://github.com/autowarefoundation/autoware/pull/6184#issuecomment-2948129756) for the details)
This PR adds `use_pointcloud_container` to tier4_simulator launch so that users can configure whether to use pointcloud_container from launch argument to resolve the issue. 
It is set to true by default to keep the behavior when we launch this file from …
> feat(tier4_simulator_launch): add use_pointcloud_container argument

- launch/tier4_perception_launch/launch/occupancy_grid_map/probabilistic_occupancy_grid_map.launch.xml
- launch/tier4_simulator_launch/launch/simulator.launch.xml
This PR is a `humble` backport of https://github.com/autowarefoundation/autoware_universe/pull/10770.
> feat(tier4_simulator_launch): add use_pointcloud_container argument (#10770)

- planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/README.md
- planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/config/detection_area.param.yaml
- planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/src/manager.cpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/src/scene.cpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/src/scene.hpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/src/utils.cpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/src/utils.hpp
improve log message
- print module id, regulatory element id, stop line id when logging.
- print state change
```
[Module ID: 9872][Reg: 9872][Lane: 9285][Line: 9866] state changed: GO -> STOP
```
- print detected obstacle positions(from map and ego base link), time elapsed since last detection, and ego vehicle position when ego-vehicle is in STOP state (off by default)
```
[Module ID: 9872][Reg: 9872][Lane: 9285][Line: 9866] ego: map_coord(3774.68, 73700.80, 19.58), obstacle: map_coord(3776.44, 73711.89, 19.76), ego_coord(6.66, 9.05, 0.20)
```
- Link
psim
2025/06/11 https://evaluation.tier4.jp/evaluation/reports/5c168b87-cfd5-5cf8-9613-617ca43ab7a4/?project_id=prd_jt
None.
None.
None.
> feat(detection_area): improve log message

- sensing/autoware_cuda_pointcloud_preprocessor/package.xml
Added myself as a CUDA pointcloud preprocessor maintainer uponn request by @amadeuszsz.
> chore(autoware_cuda_pointcloud_preprocessor): add myself as maintainer

- planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp
Fixed an issue where the detection logic for lane departure into the oncoming lane was inaccurate.
Specifically:
Improved the check for whether the avoidance path stays within the current lane boundary, especially when no adjacent opposite-direction lanelets are available.
Introduced a geometric check using the vehicle footprint and the left/right bounds of the current lane to determine if the vehicle intrudes into the oncoming lane.
In the previous logic, there were edge cases where lane departure into the oncoming lane could not be correctly detected, resulting in the system erroneously executing an avoidance maneuver even when the vehicle would intrude into the oncoming lane.
- https://github.com/autowarefoundation/autoware_universe/pull/10585
None.
None.
None.
> fix(static_obstacle_avoidance): fixed an issue where the detection of lane departure into the oncoming lane was inaccurate

- perception/autoware_object_velocity_splitter/package.xml
- perception/autoware_radar_fusion_to_detected_object/package.xml
- perception/autoware_radar_tracks_msgs_converter/package.xml
- perception/autoware_simple_object_merger/package.xml
- sensing/autoware_radar_scan_to_pointcloud2/package.xml
- sensing/autoware_radar_static_pointcloud_filter/package.xml
- sensing/autoware_radar_threshold_filter/package.xml
- sensing/autoware_radar_tracks_noise_filter/package.xml
This PR delete maintainer for radar packages.
None.
None.
None.
None.
None.
> chore(radar): delete maintainer for radar packages

- system/autoware_command_mode_types/CMakeLists.txt
- system/autoware_command_mode_types/README.md
- system/autoware_command_mode_types/doc/command-mode-architecture.drawio.svg
- system/autoware_command_mode_types/include/autoware_command_mode_types/modes.hpp
- system/autoware_command_mode_types/include/autoware_command_mode_types/sources.hpp
- system/autoware_command_mode_types/package.xml
Add constants used by command mode packages.
- https://github.com/autowarefoundation/autoware_universe/issues/9235
None
None.
None.
None.
> feat(command_mode_types): create package

- system/autoware_command_mode_decider/CMakeLists.txt
- system/autoware_command_mode_decider/README.md
- system/autoware_command_mode_decider/config/default.param.yaml
- system/autoware_command_mode_decider/doc/peripheral-ros-graph.drawio.svg
- system/autoware_command_mode_decider/include/autoware_command_mode_decider/plugin.hpp
- system/autoware_command_mode_decider/include/autoware_command_mode_decider/status.hpp
- system/autoware_command_mode_decider/launch/decider.launch.xml
- system/autoware_command_mode_decider/msg/DeciderDebug.msg
- system/autoware_command_mode_decider/package.xml
- system/autoware_command_mode_decider/src/command_mode_decider_base.cpp
- system/autoware_command_mode_decider/src/command_mode_decider_base.hpp
- system/autoware_command_mode_decider/src/plugin/plugin.cpp
- system/autoware_command_mode_decider/src/plugin/status.cpp
- system/autoware_command_mode_decider_plugins/CMakeLists.txt
- system/autoware_command_mode_decider_plugins/package.xml
- system/autoware_command_mode_decider_plugins/plugins.xml
- system/autoware_command_mode_decider_plugins/src/command_mode_decider.cpp
- system/autoware_command_mode_decider_plugins/src/command_mode_decider.hpp
Add command mode decider package that determine which mode to activate from operation mode or MRM. See README for details.
- https://github.com/autowarefoundation/autoware.universe/issues/9235
See https://github.com/autowarefoundation/autoware.universe/pull/10169.
Also, this PR change was tested in a real vehicle as an evaluation of the MRM on multiple ECUs.
None.
None.
None.
> feat(command_mode_decider): create package

- planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp
The previous implementation simply checked whether an object’s position was within the intersection polygon, without considering its routing context or lane connections.
As a result, it failed to detect parked vehicles that may exist within T-shaped intersections, particularly on side lanes that do not continue straight. This update improves the ability to accurately detect such objects and avoid unsafe maneuvers near intersections.
As shown below, when the detected vehicle is positioned to the left and there is no left-turn lane, it may be a parked vehicle.
- Link
None.
None.
None.
> fix(static_obstacle_avoidance): fix filtering logic to avoid vehicle in T-intersection

- system/autoware_processing_time_checker/config/processing_time_checker.param.yaml
launcher in universe update for
https://github.com/autowarefoundation/autoware_core/pull/549
- Link
same to https://github.com/autowarefoundation/autoware_core/pull/549
None.
None.
None.
> feat(path_generator): publish processing time

- perception/autoware_ground_segmentation/src/scan_ground_filter/node.cpp
Issue in Non-Grid Mode Ground Classification (**POINT_FOLLOW** Logic)
Only assign **POINT_FOLLOW** if the previous point was classified as GROUND and the current point is very close to it
The Bug: How Misclassifications Happened
A ray of points hits the side of a car / barrier (**NON_GROUND**) and then the road surface (**GROUND**).
The first few points are correctly identified as **NON_GROUND**.
The algorithm then processes the first point that is actually on the road. This point is very close to the last point on the car's tire / barrier.
The Flaw: The original code would see that this new road point was close to the previous non-ground point and assign it the temporary **POINT_FOLLOW** label.
The code would then resolve this temporary label. It had a rule: "If the previous point was …
> feat(autoware_ground_segmentation): change point follow logic (#294)

- planning/motion_velocity_planner/autoware_motion_velocity_obstacle_cruise_module/src/obstacle_cruise_module.cpp
- planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/src/obstacle_slow_down_module.cpp
follow the function name change in [link](https://github.com/autowarefoundation/autoware_core/pull/558)
No behavior changes are expected.
engage available in psim
None.
None.
None.
> refactor(obstacle_slowdown_module, obstacle_cruise_module): follow function name change in autoware_core

- system/autoware_default_adapi_universe/document/autoware-state.md
- system/autoware_default_adapi_universe/document/images/autoware-state-table.drawio.svg
Add detailed description for autoware state compatibility document.
- [TIER IV internal link](https://star4.slack.com/archives/CACBYGS4W/p1751357599987129?thread_ts=1751356814.796859&cid=CACBYGS4W)
None
None.
None.
None.
> docs(default_adapi_universe): add detailed description for autoware state arrived

- control/autoware_vehicle_cmd_gate/README.md
- control/autoware_vehicle_cmd_gate/package.xml
Update maintainer and document.
- https://tier4.atlassian.net/wiki/spaces/CT/pages/3816882516/PC+Vehicle+Cmd+Gate
- Link
None.
None.
None.
> feat(vehicle_cmd_gate): update maintainer and readme

- planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/package.xml
Add Zulfaqar Azmi as maintainer of the `autoware_motion_velocity_run_out_module` package.
- Link
None.
None.
None.
> chore(run_out): add Zulfaqar Azmi as maintainer

- planning/planning_validator/autoware_planning_validator_intersection_collision_checker/config/intersection_collision_checker.param.yaml
- planning/planning_validator/autoware_planning_validator_intersection_collision_checker/include/autoware/planning_validator_intersection_collision_checker/types.hpp
- planning/planning_validator/autoware_planning_validator_intersection_collision_checker/package.xml
- planning/planning_validator/autoware_planning_validator_intersection_collision_checker/param/intersection_collision_checker_node_parameters.yaml
- planning/planning_validator/autoware_planning_validator_intersection_collision_checker/src/intersection_collision_checker.cpp
- planning/planning_validator/autoware_planning_validator_intersection_collision_checker/src/utils.cpp
This PR applies the following changes to `intersection_collision_checker` module to reduce false positive occurrence.
- Target lane selection:
- Use turn lanelets centerline string (instead of trajectory linesting) to create a bounding box to get the set initial candidate lanelets
- This will prevent unnecessarily checking lanelets that are not around the turn area before ego arrives at turn
- PCD Object velocity estimation:
- Apply a reset acceleration threshold (if measured acceleration exceeds threshold then reset tracking info)
- Apply a max velocity threshold to avoid outlier data affecting subsequent measurements
- [Launcher PR](https://github.com/autowarefoundation/autoware_launch/pull/1538)
- PSIM
- LSIM
- [Internal TIER IV …
> feat(intersection_collision_checker): improve target lane selection and velocity estimation to reduce false positives

- launch/tier4_perception_launch/launch/object_recognition/detection/detection.launch.xml
- launch/tier4_perception_launch/launch/object_recognition/tracking/tracking.launch.xml
- launch/tier4_perception_launch/launch/perception.launch.xml
* when `use_radar_tracking_fusion` is false, the radar pipeline will work with detected object (as before)
* replace range_splitter and velocity_splitter to the object_sorter
* set lanelet filter for tracked objects
* remove radar object tracker
* replacing parameter file paths
This PR requires https://github.com/tier4/aip_launcher/pull/481
This PR need to be merged with https://github.com/autowarefoundation/autoware_launch/pull/1531
- Link
None.
None.
None.
> feat(radar pipeline): radar tracked object pipeline

- planning/behavior_path_planner/autoware_behavior_path_bidirectional_traffic_module/README.md
Remove invalid link from README.
- Link
None.
None.
None.
> chore(bidirectional_traffic): modify readme

- launch/tier4_simulator_launch/launch/simulator.launch.xml
Simplify object tracker in simulation.
In the simulation situation, only the detected object `/perception/object_recognition/objects` is simulated.
Therefore, other tracker merger (such as radar pipeline) is not working anyway.
This PR simplify the object tracker by directly calling the multi-object-tracker, so that unused requirement of configurations are not needed.
This PR will not introduce any logical change. It may reduce computational cost for the simulation.
- Link
tested by launching the planning-simulator
None.
None.
None.
> fix(simulator.launch): replace object recognition tracking with multi-object tracker integration

- control/autoware_control_command_gate/CMakeLists.txt
- control/autoware_control_command_gate/config/default.param.yaml
- control/autoware_control_command_gate/package.xml
- control/autoware_control_command_gate/src/command/compatibility.cpp
- control/autoware_control_command_gate/src/command/compatibility.hpp
- control/autoware_control_command_gate/src/command/compatibility/emergency_interface.cpp
- control/autoware_control_command_gate/src/command/compatibility/emergency_interface.hpp
- control/autoware_control_command_gate/src/command/compatibility/moderate_stop_interface.cpp
- control/autoware_control_command_gate/src/command/compatibility/moderate_stop_interface.hpp
Add vehicle_cmd_gate interface for comatibility.
https://github.com/autowarefoundation/autoware_universe/pull/10169
1. Launch planning simulation.
1. Check that the vehicle stops when Set Emergency button on RViz is pushed.
1. Check that the vehicle stops when following command is executed.
```bash
ros2 service call /control/vehicle_cmd_gate/set_stop tier4_control_msgs/srv/SetStop "stop: true"
```
The moderate_stop_interface.cpp and hpp are same as vehicle_cmd_gate.
None.
None.
> feat(control_command_gate): support vehicle_cmd_gate interface

- launch/tier4_perception_launch/launch/object_recognition/detection/detection.launch.xml
- launch/tier4_perception_launch/launch/object_recognition/detection/detector/camera_lidar_detector.launch.xml
- launch/tier4_perception_launch/launch/object_recognition/detection/merger/camera_lidar_merger.launch.xml
- launch/tier4_perception_launch/launch/object_recognition/detection/merger/camera_lidar_radar_merger.launch.xml
- launch/tier4_perception_launch/launch/perception.launch.xml
- perception/autoware_image_projection_based_fusion/launch/pointpainting_fusion.launch.xml
- perception/autoware_image_projection_based_fusion/launch/roi_cluster_fusion.launch.xml
- perception/autoware_image_projection_based_fusion/launch/roi_detected_object_fusion.launch.xml
- perception/autoware_image_projection_based_fusion/launch/roi_pointcloud_fusion.launch.xml
- perception/autoware_image_projection_based_fusion/launch/segmentation_pointcloud_fusion.launch.xml
- Add one more camera for camera_fusion mode
- Link
- Confirmed by logging_simulator that correct number of camera are used for fusion
```
autoware@npc2201009-ubuntu22:~/autoware.proj$ ros2 node info /perception/object_recognition/detection/clustering/camera_lidar_fusion/roi_cluster_fusion
/perception/object_recognition/detection/clustering/camera_lidar_fusion/roi_cluster_fusion
Subscribers:
/clock: rosgraph_msgs/msg/Clock
/parameter_events: rcl_interfaces/msg/ParameterEvent
/perception/object_recognition/detection/clustering/clusters: tier4_perception_msgs/msg/DetectedObjectsWithFeature
/perception/object_recognition/detection/rois0: tier4_perception_msgs/msg/DetectedObjectsWithFeature
/perception/object_recognition/detection/rois1: …
```
> fix(tier4_perception_launch): add one more camera fusion

- perception/autoware_radar_object_tracker/config/radar_object_tracker.param.yaml
This PR changes package name in config file.
- Link
None.
None.
None.
> feat(autoware_radar_object_tracker): change package name in config file

- perception/autoware_tensorrt_common/src/tensorrt_common.cpp
> chore(autoware_tensorrt_common): improved logging when loading plugins

- sensing/autoware_pointcloud_preprocessor/docs/concatenate-data.md
Brief description of available concatenation strategies. This part of documentation will be linked in
- https://github.com/autowarefoundation/autoware_msgs/pull/142
- Link
None.
None.
None.
> docs(autoware_pointcloud_preprocessor): point cloud concatenation strategies

- common/autoware_universe_utils/README.md
- control/autoware_autonomous_emergency_braking/README.md
- control/autoware_collision_detector/README.md
- evaluator/autoware_planning_evaluator/README.md
- perception/autoware_probabilistic_occupancy_grid_map/pointcloud-based-occupancy-grid-map.md
- perception/autoware_radar_object_tracker/models.md
- perception/autoware_shape_estimation/README.md
- planning/autoware_path_optimizer/README.md
- planning/behavior_path_planner/autoware_behavior_path_lane_change_module/README.md
- planning/behavior_path_planner/autoware_behavior_path_start_planner_module/README.md
- planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/README.md
- planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/README.md
- simulator/autoware_carla_interface/README.md
- system/autoware_bluetooth_monitor/README.md
- tools/reaction_analyzer/README.md
- This is the backport of https://github.com/autowarefoundation/autoware_universe/pull/10982
**Related PR:**
- https://github.com/autowarefoundation/autoware_universe/pull/10985#issuecomment-3078084736
Just basic doc updates.
None.
None.
None.
> style(pre-commit): autofix (#10982)

- .github/workflows/bump-repo-versions-build-depends.yaml
This adds the workflow that automatically detects the new version release in the repositories listed within .repos files.
This workflow is already added to [autoware repository](https://github.com/autowarefoundation/autoware/blob/main/.github/workflows/bump-repo-versions-autoware.yaml) and seems to be working fine. 
- https://github.com/orgs/autowarefoundation/discussions/4958
- https://github.com/autowarefoundation/autoware/pull/5212
Tested in my fork: https://github.com/mitsudome-r/autoware_universe/actions/runs/16367924876
Generated PR: https://github.com/mitsudome-r/autoware_universe/pull/18
None.
None.
None.
> feat(workflow): add workflow to automatically update versions in build_depends.repos

- planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/start_planner_module.cpp
**Issue with Current Implementation:**
In the conventional start_planner, each planner was provided with poses aligned to the lane (regardless of the vehicle's actual orientation) as starting point information for path generation. This causes issues where path generation and lane departure detection within the planner cannot consider the vehicle's actual orientation.
**Proposed Changes:**
Whether to generate paths or perform departure detection considering the current vehicle orientation depends on the implementation within each planner. However, modify the implmentation to pass the vehicle's orientation as information so that at least orientation-aware departure detection can be performed.
**Exception for Reverse Paths:**
For path which include backward driving, will continue to provide …
> feat(start_planner): improve trajectory generation with consideration of current ego vehicle heading

- planning/planning_validator/autoware_planning_validator_intersection_collision_checker/config/intersection_collision_checker.param.yaml
- planning/planning_validator/autoware_planning_validator_intersection_collision_checker/include/autoware/planning_validator_intersection_collision_checker/intersection_collision_checker.hpp
- planning/planning_validator/autoware_planning_validator_intersection_collision_checker/include/autoware/planning_validator_intersection_collision_checker/types.hpp
- planning/planning_validator/autoware_planning_validator_intersection_collision_checker/param/intersection_collision_checker_node_parameters.yaml
- planning/planning_validator/autoware_planning_validator_intersection_collision_checker/src/intersection_collision_checker.cpp
- planning/planning_validator/autoware_planning_validator_intersection_collision_checker/src/utils.cpp
This PR improves ICC module to address frequent false negatives.
the following changes are applied:
- velocity updated using 2 point LPF :arrow_right: velocity updated with linear regression applied a fixed circular buffer of distance measurements
- tracking reset based on raw acceleration value :arrow_right: tracking reset based on raw velocity value and tracked acceleration value
- decision stability based on on/off time buffer :arrow_right: decision stability based on on/off time buffer AND collision lanelet id consistency
- [Launcher PR](https://github.com/autowarefoundation/autoware_launch/pull/1562)
- PSIM
- LSIM
- Internal TIER IV Evaluators:
- [CommonScenario_Basic](https://evaluation.tier4.jp/evaluation/reports/38361026-e35f-5781-896b-e433d782facf?project_id=prd_jt)
- …
> feat(intersection_collision_checker): improve logic to address false negatives

- planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection.cpp
"traffic_light_id" key is optional in autoware and TIER IV's Pilot.auto now. 
- https://autowarefoundation.github.io/autoware-documentation/main/design/autoware-architecture/map/map-requirements/vector-map-requirements-overview/category_traffic_light/
- https://docs.pilot.auto/reference-design/common/map-requirements/vector-map-requirements/category_traffic_light
This PR remove reference to it.
attention_area changes accordingly
https://github.com/user-attachments/assets/11881cbd-bd95-4225-b745-6a6106ec36a9
attention_area does not change accordingly
https://github.com/user-attachments/assets/b0618100-48f4-47e2-aff7-e6609c732093
attention_area changes accordingly
https://github.com/user-attachments/assets/05e642db-287d-4f99-a080-0f7afb684186
attention_area does not change accordingly …
> fix(intersection): remove reference "traffic_light_id" as it is deprecated

- planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/README.md
- planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/config/crosswalk.param.yaml
- planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/manager.cpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp
This PR implements a mechanism to retain previously detected object information for a short duration after the perception system loses track of the object. This enhancement improves robustness against temporary detection failures or occlusions in the crosswalk module.
- Added a new parameter `lost_detection_timeout` to configure the retention duration.
- Modified `ObjectInfoManager::finalize()` to remove objects only if they have not been detected for longer than lost_detection_timeout.
- Ensured that the last detection time is updated per object upon each successful detection.
:warning: Please review this PR as well.
https://github.com/autowarefoundation/autoware_launch/pull/1565
- https://github.com/autowarefoundation/autoware_universe/pull/11028
None.
None.
None.
> feat(crosswalk): improve robustness to prevent stop decision from being canceled by transient noise

- launch/tier4_perception_launch/launch/object_recognition/detection/detection.launch.xml
- launch/tier4_perception_launch/launch/object_recognition/detection/merger/camera_lidar_merger.launch.xml
- launch/tier4_perception_launch/launch/object_recognition/detection/merger/camera_lidar_radar_merger.launch.xml
- launch/tier4_perception_launch/launch/perception.launch.xml
- perception/autoware_object_merger/config/object_association_merger.param.yaml
- perception/autoware_object_merger/include/autoware/object_merger/object_association_merger_node.hpp
- perception/autoware_object_merger/schema/object_association_merger.schema.json
- perception/autoware_object_merger/src/object_association_merger_node.cpp
- Add priority mode for object merger which based on each class
- Need merging with https://github.com/autowarefoundation/autoware_launch/pull/1568
- [TIER IV internal link](https://tier4.atlassian.net/browse/RT1-10784)
- Link
- Test with [internal evaluator](https://evaluation.tier4.jp/evaluation/reports/7561bfee-39c7-5197-9208-7e20fb679dad?project_id=prd_jt)
- Confirmed by logging_simulator on internal (bus) product autoware with new priority_mode: 
[Screencast from 2025年07月23日 15時44分06秒.webm](https://github.com/user-attachments/assets/a632e452-32d0-48ff-9d9d-77fe082d2c90)
None.
None.
None.
> fix(autoware_object_merger): add merger priority_mode

- build_depends_humble.repos
Align the Agnocast version with that of https://github.com/autowarefoundation/autoware.
https://github.com/autowarefoundation/autoware/pull/6332
Evaluator: [TIER IV Internal Link](https://evaluation.tier4.jp/evaluation/reports/030d3b1b-730b-52c0-b135-13c32810cfaa?project_id=prd_jt)
None.
None.
> feat(repos): upgrade agnocast version to 2.1.1

- planning/planning_validator/autoware_planning_validator_intersection_collision_checker/config/intersection_collision_checker.param.yaml
- planning/planning_validator/autoware_planning_validator_intersection_collision_checker/include/autoware/planning_validator_intersection_collision_checker/types.hpp
- planning/planning_validator/autoware_planning_validator_intersection_collision_checker/param/intersection_collision_checker_node_parameters.yaml
- planning/planning_validator/autoware_planning_validator_intersection_collision_checker/src/intersection_collision_checker.cpp
when tracked pcd object arrives at overlap point, distance measurement jumps around and becomes unstable causing unstable collision decision. This PR improves handling of tracked pcd objects when they arrive at overlap point to stabilize collision decision.
This PR also adds parameter `max_history_time` to configure max valid age of tracked object data before its discarded.
- [Launcher PR](https://github.com/autowarefoundation/autoware_launch/pull/1575)
- PSIM
- LSIM
- Internal TIER IV Evaluators:
- [CommonScenario_Basic](https://evaluation.tier4.jp/evaluation/reports/7b723435-23a2-51f3-8aaf-be1872deed3b?project_id=prd_jt)
- [ControlDLRCommon_Basic](https://evaluation.tier4.jp/evaluation/reports/10992478-4dda-5367-bda8-2ec1ad33b404?project_id=prd_jt)
- …
> fix(intersection_collision_checker): improve logic for objects near overlap

- planning/autoware_surround_obstacle_checker/package.xml
Update maintainer.
- Link
None.
None.
None.
> chore(surround_obstacle_checker): update maintainer

- planning/planning_validator/autoware_planning_validator_intersection_collision_checker/README.md
Update documentation of intersection_collision_checker to:
- reflect current implementation
- add flowcharts to describe workflow.
- add missing parameters decriptions
None.
N/A
None.
None.
None.
> docs(intersection_collision_checker): update documentation

- evaluator/autoware_control_evaluator/src/control_evaluator_node.cpp
Fix control evaluator's distance to uncrossable boundary, so that it constantly publishing values. 
The new behaviors are
if boundary is nearby = publishes distance to boundary
if no boundary found = publishes contant `search_distance` value.
- Link
None.
None.
None.
> fix(control_evaluator): publish dist to uncrossable boundary

- planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/boundary_departure_prevention_module.cpp
- planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/slow_down_interpolator.cpp
- planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/slow_down_interpolator.hpp
- planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/utils.cpp
- planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/utils.hpp
BDP inserts slow down distance when ego approaches or leaving lane through road border. 
Departure interval is first generated to find the distance to slow down point, and the lateral distance to boundary.
Then slow down point is computed
What the slow down feature do
1. Dynamic comfort to hard slow down
When the longitudinal gap is sufficient, the planner slows with the comfort limits (th_jerk_mps3.min, th_acc_mps2.min) for a smoother ride.
As the gap shrinks, it automatically escalates to the hard limits (.max) so that the target conditions are still met.
https://github.com/user-attachments/assets/9a92de78-9628-4b65-ba13-4727b794645b
⚠️ This PR is best tested by cherry-picking parameters from [custom branch](https://github.com/zulfaqar-azmi-t4/autoware_launch/blob/tmp-improving-slow-down …
> feat(boundary_departure): slow down computation

- launch/tier4_perception_launch/launch/object_recognition/tracking/tracking.launch.xml
- perception/autoware_multi_object_tracker/README.md
- perception/autoware_multi_object_tracker/config/input_channels.param.yaml
- perception/autoware_multi_object_tracker/schema/input_channels.schema.json
- To add `irregular_object_detector` result into `multi_object_tracker`
- Need merge with https://github.com/autowarefoundation/autoware_launch/pull/1587
- Link
- Run logging_simulator with option `use_multi_channel_tracker_merger=true`
- Confirm that `/perception/object_recognition/tracking/multi_object_tracker` subscribe `/perception/object_recognition/detection/irregular_object/objects` topic
```
autoware@dpc2007005:~/autoware.proj$ ros2 node info /perception/object_recognition/tracking/multi_object_tracker 
/perception/object_recognition/tracking/multi_object_tracker
Subscribers:
/clock: rosgraph_msgs/msg/Clock
/parameter_events: rcl_interfaces/msg/ParameterEvent
/perception/object_recognition/detection/centerpoint/validation/objects: …
```
> fix(multi_object_tracker): add irregular objects topic

- perception/autoware_multi_object_tracker/config/multi_object_tracker_node.param.yaml
- perception/autoware_multi_object_tracker/include/autoware/multi_object_tracker/association/association.hpp
- perception/autoware_multi_object_tracker/include/autoware/multi_object_tracker/object_model/object_model.hpp
- perception/autoware_multi_object_tracker/include/autoware/multi_object_tracker/object_model/types.hpp
- perception/autoware_multi_object_tracker/include/autoware/multi_object_tracker/tracker/model/multiple_vehicle_tracker.hpp
- perception/autoware_multi_object_tracker/include/autoware/multi_object_tracker/tracker/model/pass_through_tracker.hpp
- perception/autoware_multi_object_tracker/include/autoware/multi_object_tracker/tracker/model/pedestrian_and_bicycle_tracker.hpp
- perception/autoware_multi_object_tracker/include/autoware/multi_object_tracker/tracker/model/pedestrian_tracker.hpp
- perception/autoware_multi_object_tracker/include/autoware/multi_object_tracker/tracker/model/tracker_base.hpp
- perception/autoware_multi_object_tracker/include/autoware/multi_object_tracker/tracker/model/unknown_tracker.hpp
- perception/autoware_multi_object_tracker/include/autoware/multi_object_tracker/tracker/model/vehicle_tracker.hpp
- perception/autoware_multi_object_tracker/lib/association/association.cpp
- perception/autoware_multi_object_tracker/lib/tracker/model/multiple_vehicle_tracker.cpp
- perception/autoware_multi_object_tracker/lib/tracker/model/pass_through_tracker.cpp
- perception/autoware_multi_object_tracker/lib/tracker/model/pedestrian_and_bicycle_tracker.cpp
- perception/autoware_multi_object_tracker/lib/tracker/model/pedestrian_tracker.cpp
- perception/autoware_multi_object_tracker/lib/tracker/model/unknown_tracker.cpp
- perception/autoware_multi_object_tracker/lib/tracker/model/vehicle_tracker.cpp
- perception/autoware_multi_object_tracker/schema/multi_object_tracker_node.schema.json
- perception/autoware_multi_object_tracker/src/multi_object_tracker_node.cpp
- perception/autoware_multi_object_tracker/src/processor/processor.cpp
- perception/autoware_multi_object_tracker/src/processor/processor.hpp
- perception/autoware_multi_object_tracker/test/test_bench.cpp
- perception/autoware_multi_object_tracker/test/test_bench.hpp
Association was set by the tracker's class. However, the class label and the tracker type is not the same.
This PR explicitly defines the tracker type.
If an "unknown_tracker" has update in classification, it could be a CAR (for example)
If an vehicle detection comes, the vehicle detection will be associated to the unknown_tracker, which cannot estimate the vehicle motion model properly.
By defining tracker type and matrix of detection label -> tracker matrix, make sure given detection is associated to intended tracker type.
* before
https://github.com/user-attachments/assets/7550a913-7dcb-4592-80cb-55080fb54ff8
* after
https://github.com/user-attachments/assets/cdab6330-d18c-451e-b2cb-05f9ba1721c0
* enum `TrackerType` is defined
* association configuration `can_assign_matrix` …
> fix(multi object tracker): tracker type to associate

- common/autoware_component_interface_specs_universe/include/autoware/component_interface_specs_universe/planning.hpp
- control/autoware_control_performance_analysis/README.md
- control/autoware_control_performance_analysis/launch/control_performance_analysis.launch.xml
- control/autoware_control_validator/launch/control_validator.launch.xml
- control/autoware_lane_departure_checker/README.md
- control/autoware_lane_departure_checker/launch/lane_departure_checker.launch.xml
- control/autoware_obstacle_collision_checker/launch/obstacle_collision_checker.launch.xml
- control/autoware_operation_mode_transition_manager/README.md
- control/autoware_operation_mode_transition_manager/launch/autonomous_mode_transition_flag_node.launch.xml
- control/autoware_operation_mode_transition_manager/launch/operation_mode_transition_manager.launch.xml
- control/autoware_predicted_path_checker/launch/predicted_path_checker.launch.xml
- control/autoware_pure_pursuit/launch/pure_pursuit.launch.xml
- control/autoware_smart_mpc_trajectory_follower/scripts/pympc_trajectory_follower.py
- control/autoware_trajectory_follower_node/launch/simple_trajectory_follower.launch.xml
- evaluator/autoware_control_evaluator/launch/control_evaluator.launch.xml
- evaluator/autoware_planning_evaluator/launch/planning_evaluator.launch.xml
- launch/tier4_control_launch/launch/control.launch.xml
- launch/tier4_planning_launch/launch/planning.launch.xml
- planning/motion_velocity_planner/autoware_motion_velocity_obstacle_cruise_module/src/optimization_based_planner/optimization_based_planner.cpp
- planning/planning_validator/autoware_planning_validator/launch/planning_validator.launch.xml
- simulator/autoware_simple_planning_simulator/launch/simple_planning_simulator.launch.py
- system/autoware_component_state_monitor/config/topics.yaml
- tools/reaction_analyzer/param/reaction_analyzer.param.yaml
This is the PR corresponding to phase 2. This PR is scheduled to be merged on August 11.
https://github.com/autowarefoundation/autoware/issues/6292
https://github.com/autowarefoundation/autoware/issues/6292
- Link
Please refer to this.
https://github.com/autowarefoundation/autoware/issues/6292#issuecomment-3166352528
None.
None.
None.
> feat: change planning output topic name to /planning/trajectory

- common/autoware_boundary_departure_checker/CMakeLists.txt
- common/autoware_boundary_departure_checker/include/autoware/boundary_departure_checker/boundary_departure_checker.hpp
- common/autoware_boundary_departure_checker/include/autoware/boundary_departure_checker/data_structs.hpp
- common/autoware_boundary_departure_checker/include/autoware/boundary_departure_checker/parameters.hpp
- common/autoware_boundary_departure_checker/include/autoware/boundary_departure_checker/steering_abnormality_utils.hpp
- common/autoware_boundary_departure_checker/include/autoware/boundary_departure_checker/utils.hpp
- common/autoware_boundary_departure_checker/package.xml
- common/autoware_boundary_departure_checker/src/boundary_departure_checker_abnormality.cpp
- common/autoware_boundary_departure_checker/src/steering_abnormality_utils.cpp
- common/autoware_boundary_departure_checker/src/utils.cpp
- planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/config/boundary_departure_prevention.param.yaml
- planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/schema/boundary_departure_prevention.schema.json
- planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/boundary_departure_prevention_module.cpp
- planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/parameters.hpp
This PR improves the steering abnormality of the `boundary_departure_checker` to support 4 types of steering abnormalities that each can be finely tuned.
The PR also fixes the dynamic parameters of the module.
Required PR to populate the wheel angle in the MPC predicted trajectory: https://github.com/autowarefoundation/autoware_universe/pull/11153
Required launch PR: https://github.com/autowarefoundation/autoware_launch/pull/1600
- [TIER IV JIRA](https://tier4.atlassian.net/browse/RT1-10442)
Psim
None.
None.
None.
> feat(boundary_departure_checker): improve steering abnormality

- planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/scene.cpp
This PR fixes an issue in the stop point calculation during restart suppression, which occurs when the next stop position is within a configured threshold and the vehicle should remain stopped instead of restarting. Previously, the inserted stop point was calculated directly from the ego pose without projecting it onto the path, causing the planned trajectory to become distorted. The fix projects the ego position onto the path using `calcSignedArcLength` and `calcLongitudinalOffsetPose`, ensuring the stop point lies exactly on the path and preventing path deformation while maintaining the intended restart suppression behavior.
| BEFORE | AFTER |
| --- | --- |
|  <video src="https://github.com/user-attachments/assets/aa720c29-076e-431f-83f1-2c5edd141618"/> |  <video …
> fix(traffic_light): fix: incorrect inserted stop point calculation for restart suppression

- launch/tier4_perception_launch/launch/object_recognition/prediction/prediction.launch.xml
- launch/tier4_perception_launch/package.xml
- perception/autoware_simpl_prediction/config/simpl.param.yaml
- perception/autoware_simpl_prediction/launch/simpl.launch.xml
This PR updates the launcher in order to add an option to choose prediction model type; `map_based` or `simpl`.
The default value of the model type is `map_based` the same as before, so there is no influence on the entire system.
In the future, we need to launch both `map_based` and `simpl`(or another ML-model) in parallel.
Then, we need to add an extra option to realize it.
- [TIER IV internal link](https://tier4.atlassian.net/browse/RT1-10964?focusedCommentId=251180&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&sourceType=mention#comment-251180)
- Launch `map_based_prediction`
```shell
ros2 launch autoware_launch logging_simulator.launch.xml ... prediction_model_type:=map_based
```
- Launch `simpl_prediction`
```shell
ros2 launch …
```
> feat(tier4_perception_launch): add an option to choose prediction model type

- planning/planning_validator/autoware_planning_validator/CMakeLists.txt
- planning/planning_validator/autoware_planning_validator/README.md
- planning/planning_validator/autoware_planning_validator/include/autoware/planning_validator/node.hpp
- planning/planning_validator/autoware_planning_validator/launch/planning_validator.launch.xml
- planning/planning_validator/autoware_planning_validator/package.xml
- planning/planning_validator/autoware_planning_validator/src/node.cpp
- planning/planning_validator/autoware_planning_validator_trajectory_checker/test/test_trajectory_checker_diag.cpp
same change with https://github.com/autowarefoundation/autoware_universe/pull/10871
Disable the planning validator's validation  when autonomous control is not active.
None.
None.
| Change type   | Topic Type      | Topic Name    | Message Type        | Description       |
|:--------------|:----------------|:--------------|:--------------------|:------------------|
| Added | Sub | `~/input/operational_mode_state` | [autoware_adapi_v1_msgs/msg/OperationModeState](https://autowarefoundation.github.io/autoware-documentation/pr-279/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/msg/OperationModeState/#autoware_adapi_v1_msgsmsgoperationmodestate)  | Autoware Operation mode state |
None.
> feat(planning_validator): add operational mode state handling and validation filtering

- launch/tier4_control_launch/package.xml
add maintainer for tier4_control_launch package
- Link
None.
None.
None.
> chore(tier4_control_launch): add maintainers 

- planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/include/autoware/behavior_velocity_intersection_module/decision_result.hpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/include/autoware/behavior_velocity_intersection_module/scene_intersection.hpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection.cpp
- planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection_collision.cpp
This PR prevents slow forward movement when control performance is low by holding the stop position based on the collision detection of the intersection module.
https://github.com/user-attachments/assets/76b6b170-58c0-497b-9a24-eb1b04923c96
- [CommonScenario_Basic](https://evaluation.tier4.jp/evaluation/reports/82f6a9f4-9663-525e-8865-e85bb01e8192?project_id=prd_jt)
- [FuncVerificationScenario_Basic](https://evaluation.tier4.jp/evaluation/reports/bedc50f2-8c64-5334-ad1c-e633032dda50?project_id=prd_jt)
- [ControlDLRCommon_Basic](https://evaluation.tier4.jp/evaluation/reports/29cc6d41-7d89-5941-9429-fee0a3938dc8?project_id=prd_jt)
None.
None.
None.
> fix(intersection): hold collision stop pose

- planning/autoware_diffusion_planner/include/autoware/diffusion_planner/diffusion_planner_node.hpp
- planning/autoware_diffusion_planner/include/autoware/diffusion_planner/preprocessing/preprocessing_utils.hpp
- planning/autoware_diffusion_planner/src/conversion/lanelet.cpp
- planning/autoware_diffusion_planner/src/diffusion_planner_node.cpp
- planning/autoware_diffusion_planner/src/preprocessing/preprocessing_utils.cpp
This PR refactors the `create_ego_agent_past` function by moving it from the `DiffusionPlanner` class to the `preprocessing_utils` module to make it reusable from data conversion tools.
```diff
diff --git a/autoware_launch/config/control/trajectory_follower/longitudinal/pid.param.yaml b/autoware_launch/config/control/trajectory_follower/longitudinal/pid.param.yaml
index 9dfa666a..8d9093ac 100644
--- a/autoware_launch/config/control/trajectory_follower/longitudinal/pid.param.yaml
+++ b/autoware_launch/config/control/trajectory_follower/longitudinal/pid.param.yaml
@@ -6,7 +6,7 @@
enable_overshoot_emergency: false
enable_large_tracking_error_emergency: true
enable_slope_compensation: true
-    enable_keep_stopped_until_steer_convergence: true
+ …
```
> refactor(diffusion_planner): move `create_ego_agent_past` to preprocessing_utils

- perception/autoware_probabilistic_occupancy_grid_map/src/laserscan_based_occupancy_grid_map/laserscan_based_occupancy_grid_map_node.cpp
On tag v0.45.0, when transforming laser/obstacle/raw pointclouds in `laserscan_based_occupancy_grid_map_node`, TF gaps could lead to crashes or undefined behavior. This PR ensures that if TF is temporarily unavailable during pointcloud transforms, the current frame is skipped and a warning is logged, preventing a crash.
- ROS 2: Humble
- Build: CPU
- Reproduction:  Start the complete Autoware stack, including localization,perception and simulate transient TF loss between `base_link` -> `map` by continually initializing the localization system, which will temporarily lose TF between these frames.
The issue arises when **TF transformations between the `base_link` and `map` frames** are temporarily unavailable or delayed. When the node attempts to process pointcloud data without valid …
> fix(autoware_probabilistic_occupancy_grid_map): skip frame when TF is unavailable to avoid crash

- planning/autoware_diffusion_planner/include/autoware/diffusion_planner/diffusion_planner_node.hpp
- planning/autoware_diffusion_planner/include/autoware/diffusion_planner/dimensions.hpp
- planning/autoware_diffusion_planner/include/autoware/diffusion_planner/postprocessing/postprocessing_utils.hpp
- planning/autoware_diffusion_planner/package.xml
- planning/autoware_diffusion_planner/src/diffusion_planner_node.cpp
- planning/autoware_diffusion_planner/src/postprocessing/postprocessing_utils.cpp
This PR adds diagnostics functionality to the diffusion planner to monitor inference status and input data metrics. The changes enable real-time monitoring of the planner's health through diagnostic messages that track map loading, input data availability, and various input metrics.
- Adds a DiagnosticsInterface to track inference status and publish diagnostic messages
- Implements a utility function to count valid elements in tensor data for monitoring input quality
- Updates tensor shape definitions to use named constants for better maintainability
https://github.com/user-attachments/assets/41e90af6-4b0e-46eb-bfa9-6f009be982b3
None.
| Change type   | Topic Type      | Topic Name    | Message Type        | Description       | …
> feat(diffusion_planner): add diagnostics

- planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/boundary_departure_prevention_module.cpp
- planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/boundary_departure_prevention_module.hpp
- planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/parameters.hpp
simplify `updater_ptr_`'s lambda call, and let `get_diagnotic` function have the responsibility to print error statement.
**Parent Issue:** [TIER IV Internal Link - Issue's ticket](https://tier4.atlassian.net/browse/RT1-10999)
**Previous related fix:** [fix(boundary_departure): explicitly delete diagnotics ptr after module's destruction #11217](https://github.com/autowarefoundation/autoware_universe/pull/11217)
[TIER IV Internal Link - ControlDLR Test](https://evaluation.tier4.jp/evaluation/reports/27dc7420-c207-5501-b089-55fc274a9cab?project_id=prd_jt)
[TIER IV Internal Link - FuncVerification Test](https://evaluation.tier4.jp/evaluation/reports/5d695f8b-ca16-5676-b2f4-5a4e5fb01d02?project_id=prd_jt)
[TIER IV Internal Link - CommonScenario_Basic …
> refactor(boundary_departure): simplify diagnostic pointer call

- planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/boundary_departure_prevention_module.cpp
- planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/boundary_departure_prevention_module.hpp
Refactors `plan()` to a single point of return. This removes repetitive `RCLCPP_DEBUG` calls and prevents `update_ptr_` from being triggered in multiple code paths.
**Parent Issue:** [TIER IV Internal Link - Issue's ticket](https://tier4.atlassian.net/browse/RT1-10999)
**Previous related fix:** 
- [fix(boundary_departure): explicitly delete diagnotics ptr after module's destruction #11217](https://github.com/autowarefoundation/autoware_universe/pull/11217)
- [refactor(boundary_departure): simplify diagnostic pointer call #11243
](https://github.com/autowarefoundation/autoware_universe/pull/11243)
[TIER IV Internal Link - ControlDLR Test](https://evaluation.tier4.jp/evaluation/reports/27dc7420-c207-5501-b089-55fc274a9cab?project_id=prd_jt)
[TIER IV Internal Link - FuncVerification …
> refactor(boundary_departure): make plan single-exit to eliminate repeated debug logs and redundant update_ptr_ calls

- planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/shift_line_generator.cpp
In the previous code, for example, when avoiding a static obstacle on the left by shifting to the right, depending on the feasible shift length, the path could shift left and approach the obstacle. However, in this PR, we ensured that the path does not shift to the left of the current position.
- before
[bug.webm](https://github.com/user-attachments/assets/33c56fe8-4afd-45ce-9df2-85240458fb9f)
- after
[after.webm](https://github.com/user-attachments/assets/383bc21b-4481-49fd-b2e0-8bf6934b8afb)
- [Ticket](https://tier4.atlassian.net/browse/RT0-38543?atlOrigin=eyJpIjoiNGI4YzM4NmMxYWUzNDg5YWE3ZjU4ZGNhM2IxNTQ4NjIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
- [Slack](https://star4.slack.com/archives/C074CCKN35E/p1755571539585369)
- [[PR check][Lexus][FuncVerificationScenario_Basic] planning …
> fix(static_obstacle_avoidance): fix multiple shift line generation algorithm

- vehicle/autoware_steer_offset_estimator/package.xml
> chore(autoware_steer_offset_estimator): add maintainer

- planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/src/run_out_module.cpp
This PR fixes the pose of the PlanningFactor-based virtual wall in the run_out module.
Before
After
- psim
- [CommonScenario_Basic](https://evaluation.tier4.jp/evaluation/reports/a44f557f-74f8-5c97-a43a-b25099ec6d0e?project_id=prd_jt)
- [FuncVerificationScenario_Basic](https://evaluation.tier4.jp/evaluation/reports/bd9775f5-bdaa-5bab-860d-38166137449f?project_id=prd_jt)
- [ControlDLRCommon_Basic](https://evaluation.tier4.jp/evaluation/reports/b48435aa-9182-551a-aa52-336b3a0f1d54?project_id=prd_jt)
None.
None.
None.
> fix(run_out): fix virtual wall pose

- planning/autoware_diffusion_planner/README.md
Add a section about the Diffusion Planner model versioning.
- https://github.com/autowarefoundation/autoware/pull/6460
- https://github.com/autowarefoundation/autoware_universe/pull/11351
- Link
None.
None.
None.
> feat(diffusion-planner): update ONNX model versioning details and limitations

- planning/autoware_diffusion_planner/config/diffusion_planner.param.yaml
- planning/autoware_diffusion_planner/include/autoware/diffusion_planner/diffusion_planner_node.hpp
- planning/autoware_diffusion_planner/include/autoware/diffusion_planner/dimensions.hpp
- planning/autoware_diffusion_planner/include/autoware/diffusion_planner/preprocessing/preprocessing_utils.hpp
- planning/autoware_diffusion_planner/schema/diffusion_planner.schema.json
- planning/autoware_diffusion_planner/src/diffusion_planner_node.cpp
- planning/autoware_diffusion_planner/src/preprocessing/preprocessing_utils.cpp
This PR adds support for sampled trajectories as a new input to the diffusion planner model and introduces a temperature parameter to control the randomness of trajectory sampling. The changes enable the diffusion model to use randomly sampled trajectories as additional input for improved planning performance.
- Add `sampled_trajectories` as a new model input with corresponding tensor shapes and memory allocation
- Introduce a `temperature` parameter to control the standard deviation of the normal distribution used for trajectory sampling
- Update preprocessing utilities to generate random sampled trajectories and skip normalization for this new input
https://github.com/user-attachments/assets/bcea7731-8f11-4b06-8d59-446e0139e01f
None.
None.
None.
> feat(diffusion_planner): add `sampled_trajectories` to the model input and add a new parameter `temperature`

- launch/tier4_perception_launch/launch/object_recognition/detection/detection.launch.xml
- launch/tier4_perception_launch/launch/object_recognition/detection/detector/camera_2d_detector.launch.xml
- launch/tier4_perception_launch/launch/object_recognition/detection/detector/camera_lidar_detector.launch.xml
- launch/tier4_perception_launch/launch/perception.launch.xml
This PR enables to swittch 2d detector model like YOLOX using `model_path`, `label_path`, `color_map_path`.
https://github.com/autowarefoundation/autoware_launch/pull/1644
- Link
I ran the following command
```
map_path:=$MAP_PATH \
vehicle_model:=$VEHICLE_MODEL \
sensor_model:=$SENSOR_MODEL \
localization:=false \
planning:=false \
control:=false \
perception_mode:=camera_lidar_fusion \
camera_2d_detector/model_path:=/home/masatosaeki/autoware_data/tensorrt_yolox/yolox-sPlus-opt-pseudoV2-T4-960x960-T4-seg16cls.onnx  \
enable_2d_detection:=true
```
I got the following output
```
$ ros2 node list | grep yolox
/perception/object_recognition/detection/tensorrt_yolox0 …
```
> feat(launch): add args to select the 2d camera detection model

- planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/drivable_area_expansion/static_drivable_area.cpp
1. **Fixed setting of intersection polygon point**
- Replaced hardcoded `PolygonPoint{*intersection, 0, 0.0, 0.0}` with proper Frenet coordinate transformation using `transformBoundFrenetCoordinate(bound, *intersection)`
- Added `bound` parameter to `concatenateTwoPolygons` and `concatenatePolygons` functions to enable proper coordinate calculations
2. **Added bounds validation for vector operations**
- Added safety checks before erasing elements from `updated_bound` vector
- Prevents crashes when `removed_start_idx` or `removed_end_idx` are out of bounds or invalid
- Added warning logging when invalid indices are detected
- https://tier4.atlassian.net/browse/RT0-39335
[[PR check][Lexus][CommonScenario_Basic] planning test](https://evaluation.tier4.jp/evaluation/reports/8ec17916-e6b4-57f9- …
> fix(drivable_area): add bounds validation and proper coordinate transformation in drivable area processing

- perception/autoware_lidar_apollo_instance_segmentation/config/hdl-64.param.yaml
- perception/autoware_lidar_apollo_instance_segmentation/config/vlp-16.param.yaml
- perception/autoware_lidar_apollo_instance_segmentation/config/vls-128.param.yaml
- perception/autoware_lidar_apollo_instance_segmentation/launch/lidar_apollo_instance_segmentation.launch.xml
- perception/autoware_lidar_apollo_instance_segmentation/schema/hdl-64.schema.json
- perception/autoware_lidar_apollo_instance_segmentation/schema/vlp-16.schema.json
- perception/autoware_lidar_apollo_instance_segmentation/schema/vls-128.schema.json
This PR organizes the parameters described in the launch file and parameter file.
- Link
None.
None.
None.
> refactor(autoware_lidar_apollo_instance_segmentation): refactor launch and parameter

- planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection_collision.cpp
In specific edge cases including a loop, upcoming vehicle's path overtakes ego from behind, causing FP stops.
This PR handles this case  by checking the intersection of "entry line" of "ego_poly" and the object's BBox at the entry line on the predicted path.
https://tier4.atlassian.net/browse/RT0-37869
- https://evaluation.tier4.jp/evaluation/reports/3fab8f00-c71e-5bfa-abe1-75cac0f8f2a5?project_id=prd_jt
- https://evaluation.tier4.jp/evaluation/reports/d06087c4-0465-5e35-8987-4a4a70988b5c?project_id=prd_jt
- https://evaluation.tier4.jp/evaluation/reports/fe950a86-36e5-5bcf-ad66-9024331de141?project_id=prd_jt
None.
None.
None.
> feat(intersection): ignore precited path overtaking ego

- planning/autoware_trajectory_optimizer/src/utils.cpp
This PR fixes an issue in the trajectory optimizer by adding acceleration recalculation after velocity changes. When the maximum velocity is applied to trajectory points, the acceleration values need to be recalculated to maintain consistency between velocity and acceleration values in the trajectory.
None.
None.
None.
> fix(trajectory_optimizer): add acceleration recalculation

- planning/autoware_diffusion_planner/include/autoware/diffusion_planner/diffusion_planner_node.hpp
- planning/autoware_diffusion_planner/src/diffusion_planner_node.cpp
Fixed the issue where the agent’s prediction results were incorrectly associated.
before
[Screencast from 2025年10月07日 10時28分57秒.webm](https://github.com/user-attachments/assets/1cca3fce-e20d-4c27-beba-18e86292fc6e)
after
[Screencast from 2025年10月07日 10時36分44秒.webm](https://github.com/user-attachments/assets/bed5c702-e283-4d61-accb-97d3ea2dd1fb)
- Link
None.
None.
None.
> fix(diffusion_planner): wrong agent index

- planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/config/static_obstacle_avoidance.param.yaml
- planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/data_structs.hpp
- planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/helper.hpp
- planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/parameter_helper.hpp
- planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/schema/static_obstacle_avoidance.schema.json
- planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/debug.cpp
- planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp
This PR resolves two issues in the `static_obstacle_avoidance` module that caused the vehicle to become stuck.
- illegally parked vehicles:
Enables the vehicle to avoid other vehicles stopped in no-parking zones (e.g. inteersections). This behavior can be controlled via a policy parameter.
before
https://github.com/user-attachments/assets/6abf54dd-e1b0-4ed8-9852-b9ce273122a6
after
https://github.com/user-attachments/assets/9ea6b36f-0ee6-4737-93c7-b75d02c9e141
- VRUs on lanes with shoulders:
Fixes a issue where the vehicle could not avoid a VRU stopped on a lanelet that has a road shoulder.
before
https://github.com/user-attachments/assets/2824f484-b385-461f-9948-dd5a65424360
after
https://github.com/user-attachments/assets/49fa42a3-d447-4887-8619-88e7460f5c16
- …
> feat(static_obstacle_avoidance): avoidance for parking violation and vru

- perception/autoware_detected_object_validation/package.xml
- perception/autoware_image_projection_based_fusion/package.xml
- perception/autoware_object_sorter/package.xml
- perception/autoware_shape_estimation/package.xml
- perception/autoware_simple_object_merger/package.xml
This PR adds me as a maintainer to
- autoware_detected_object_validation
- autoware_image_projection_based_fusion
- autoware_shape_estimation
- autoware_simple_object_merger
Update old e-mail address:
- autoware_object_sorter
- Link
None.
None.
None.
> chore(perception): add maintainer
