.github/workflows/build-and-test-pr.yaml, .github/workflows/build-and-test-scheduled.yaml
=> ci: add build CI

build_depends.repos
#1
This PR depends on
- #4 
Add autoware auto msgs from https://github.com/tier4/autoware_auto_msgs.iv
Check the following item
- Readme
- Launch file
=> feat:  add autoware auto msgs depends

build_depends.repos
Related Issue
#1 
Related Link
Description
Add detected object feature remover from https://github.com/tier4/tier4_ament_lint
How to review
Check the following item
Readme
Launch file
=> feat: add autoware lint common

build_depends.repos
#85 
Add autoware_auto_dependencies to build_depends for CI.
Please check url and reference branch.
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check …
=> feat: add autoware_auto_dependencies to build_depends

build_depends.repos, vehicle/pacmod_interface/CMakeLists.txt, vehicle/pacmod_interface/README.md, vehicle/pacmod_interface/config/pacmod.param.yaml, vehicle/pacmod_interface/config/pacmod_extra.param.yaml, vehicle/pacmod_interface/include/pacmod_additional_debug_publisher/pacmod_additional_debug_publisher_node.hpp, vehicle/pacmod_interface/include/pacmod_dynamic_parameter_changer/pacmod_dynamic_parameter_changer_node.hpp, vehicle/pacmod_interface/include/pacmod_interface/pacmod_diag_publisher.hpp, vehicle/pacmod_interface/include/pacmod_interface/pacmod_interface.hpp, vehicle/pacmod_interface/launch/pacmod_additional_debug_publisher.launch.xml, vehicle/pacmod_interface/launch/pacmod_interface.launch.xml, vehicle/pacmod_interface/package.xml, vehicle/pacmod_interface/src/pacmod_additional_debug_publisher/pacmod_additional_debug_publisher_main.cpp, vehicle/pacmod_interface/src/pacmod_additional_debug_publisher/pacmod_additional_debug_publisher_node.cpp, vehicle/pacmod_interface/src/pacmod_dynamic_parameter_changer/pacmod_dynamic_parameter_changer_main.cpp, vehicle/pacmod_interface/src/pacmod_dynamic_parameter_changer/pacmod_dynamic_parameter_changer_node.cpp, vehicle/pacmod_interface/src/pacmod_interface/pacmod_diag_publisher.cpp, vehicle/pacmod_interface/src/pacmod_interface/pacmod_diag_publisher_node.cpp, vehicle/pacmod_interface/src/pacmod_interface/pacmod_interface.cpp, vehicle/pacmod_interface/src/pacmod_interface/pacmod_interface_node.cpp
https://github.com/autowarefoundation/autoware.universe/issues/1
Add pacmod_interface packages from https://github.com/tier4/AutowareArchitectureProposal.iv
Check the following item
- Readme
- Launch file
=> feat: add pacmod_interface package

perception/multi_object_tracker/src/tracker/model/pedestrian_tracker.cpp
[commit-guidelines]: https://www.conventionalcommits.org/en/v1.0.0/
[spell-check-dict]: …
=> fix: fix pedestrian shape (#760)

system/autoware_state_monitor/include/autoware_state_monitor/state_machine.hpp, system/autoware_state_monitor/launch/autoware_state_monitor.launch.xml, system/autoware_state_monitor/package.xml, system/autoware_state_monitor/src/autoware_state_monitor_node/autoware_state_monitor_node.cpp, system/autoware_state_monitor/src/autoware_state_monitor_node/state_machine.cpp
* add angle restriction for arrvied goal
* fix typo
* fix for pre commit
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some …
=> feat: add angle restriction for arrived goal (#765)

map/lanelet2_extension/lib/utilities.cpp
=> fix: fix isInLanelet (#770)

.github/workflows/build-and-test-pr.yaml, .github/workflows/build-and-test-scheduled.yaml, .github/workflows/generate-docs.yaml, .github/workflows/remove-old-pr-docs.yaml, .github/workflows/semantic-pull-request.yaml, .github/workflows/spell-check-pr.yaml
#104
In order to prevent CI corrupted, freeze the reference to point to the current hash.
Check if CI passes.
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell …
=> chore: freeze CI ref

perception/elevation_map_loader/include/elevation_map_loader/elevation_map_loader_node.hpp, perception/elevation_map_loader/src/elevation_map_loader_node.cpp
=> fix: fix elevation map bug (#774)

build_depends.repos
fix build depends
https://github.com/autowarefoundation/autoware.universe/pull/201
https://github.com/autowarefoundation/autoware.universe/pull/200
fix build depends using https://github.com/tier4/AutowareArchitectureProposal_msgs/tree/tier4/universe
- **Check spelling**: …
=> fix: build repends

build_depends.repos
fix repos
fix build depends
check with vcs import
https://github.com/autowarefoundation/autoware.universe/pull/202#discussion_r771276217
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add …
=> fix(repos): fix repos

common/osqp_interface/src/osqp_interface.cpp
https://github.com/autowarefoundation/autoware.universe/issues/213
add updateQ function in osqp interface which was removed during porting .iv to .universe
No effect to the current universe code since this function is not used so far.
- **Check spelling**: NOT required to …
=> feat: add updateQ function in osqp interface

common/autoware_point_types/CMakeLists.txt, common/autoware_point_types/include/autoware_point_types/types.hpp, common/autoware_point_types/package.xml, common/autoware_point_types/test/test_point_types.cpp
* add point_types
* Revert "add point_types"
This reverts commit 5810000cd1cbd876bc22372e2bb74ccaca06187b.
* create autoware_point_types pkg
* add include
* add cmath
* fix author
* fix bug
* define epsilon as argument
* add test
* remove unnamed namespace
* update test
* fix test name
* use std::max
* change comparison method
* remove unnencessary line
* fix test
* fix comparison method name
- …
=> feat: add point_types for wrapper (#784)

sensing/pointcloud_preprocessor/include/pointcloud_preprocessor/outlier_filter/ring_outlier_filter_nodelet.hpp, sensing/pointcloud_preprocessor/package.xml, sensing/pointcloud_preprocessor/src/outlier_filter/ring_outlier_filter_nodelet.cpp
* use point cloud msg wrapper
* fix CMakeList
* fix format
* fix bug
* refactor code to reduce calculation cost
* format code
* change point types namespace
* remove unnecessary declaration
* add point_cloud_msg_wrapper dependency
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false positives? See the …
=> feat: use point cloud wraper in ring outlier filter (#780)

planning/behavior_path_planner/src/utilities.cpp
- fix function of convertToFrenetCoordinate3d
judgement of position in frenet coordinate
tier4/autoware.iv#2359
tier4/autoware.iv#2367
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add …
=> fix(behavior_path_planner): fix/frenet coordinate 3d

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
This PR fixes right expansion direction of lanelet (yellow line) .
Before:
After: …
=> fix(behavior_path_planner): fix right expansion direction of lanelet

sensing/pointcloud_preprocessor/src/outlier_filter/ring_outlier_filter_nodelet.cpp
- https://github.com/autowarefoundation/autoware.universe/pull/241
fix invalid outlier rejection process.
```sh
ros2 launch autoware_launch logging_simulator.launch.xml map_path:=/home/satoshi/map/glp vehicle_model:=gsm8 sensor_model:=aip_x2 planning:=false control:=false scenario_simulation:=true
```
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false positives? See the …
=> fix: ring outlier filter bug

control/pure_pursuit/CMakeLists.txt, control/pure_pursuit/config/pure_pursuit.param.yaml, control/pure_pursuit/include/pure_pursuit/pure_pursuit.hpp, control/pure_pursuit/include/pure_pursuit/pure_pursuit_node.hpp, control/pure_pursuit/include/pure_pursuit/pure_pursuit_viz.hpp, control/pure_pursuit/include/pure_pursuit/util/interpolate.hpp, control/pure_pursuit/include/pure_pursuit/util/marker_helper.hpp, control/pure_pursuit/include/pure_pursuit/util/planning_utils.hpp, control/pure_pursuit/include/pure_pursuit/util/tf_utils.hpp, control/pure_pursuit/launch/pure_pursuit.launch.xml, control/pure_pursuit/package.xml, control/pure_pursuit/src/pure_pursuit/pure_pursuit_node.cpp, control/pure_pursuit/src/pure_pursuit/pure_pursuit_viz.cpp, control/pure_pursuit/src/pure_pursuit_core/interpolate.cpp, control/pure_pursuit/src/pure_pursuit_core/planning_utils.cpp, control/pure_pursuit/src/pure_pursuit_core/pure_pursuit.cpp
Port pure_pursuit package.
Using `tier4_autoware_utils` is future work. …
=> feat: port pure_pursuit

launch/tier4_localization_launch/launch/util/util.launch.py
`RandomDownsampleFilter` should have been launched, but `VoxelGridDownsampleFilter` was launched by mistake.
`RandomDownsampleFilter` should be launched.
the same PR: https://github.com/tier4/AutowareArchitectureProposal_launcher/pull/168
- **Check spelling**: NOT required …
=> fix: typo in localization util.launch.py

system/ad_service_state_monitor/launch/ad_service_state_monitor.launch.xml, system/ad_service_state_monitor/src/ad_service_state_monitor_node/ad_service_state_monitor_node.cpp
This PR fixes
- add parameter setting
- convert degree to radian  for th_arrived_angle …
=> fix(ad_service_state_monitor): rad2deg conversion

launch/tier4_localization_launch/launch/pose_estimator/pose_estimator.launch.xml, localization/ndt_scan_matcher/launch/ndt_scan_matcher.launch.xml
Signed-off-by: Yamato Ando <yamato.ando@gmail.com>
Remove unused param `output_diagnostics_topic` in ndt_scan_matcher launch file.
ndt scan mathcer node should work.
https://github.com/tier4/AutowareArchitectureProposal_launcher/pull/172
- **Check spelling**: NOT required to …
=> fix: remove unused param

control/trajectory_follower_nodes/src/longitudinal_controller_node.cpp
In longitudinal controller module, reset previous acceleration when the Control State transions  from STOPPED/STOPPING to DRIVE.
This is to prevent the car from taking an unnecessarily long time to start moving by jerk limitation.
Check on planning simulator.
Set stopped_acc/min_acc  to -100.0, and compare time to start moving.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false …
=> feat(trajectory_follower_nodes): reset previous acceleration when the car starts moving

.github/workflows/build-and-test-arm-pr.yaml, .github/workflows/build-and-test-pr.yaml, .github/workflows/build-and-test-scheduled.yaml, .github/workflows/check-build-depends.yaml, .github/workflows/delete-closed-pr-docs.yaml, .github/workflows/deploy-docs.yaml, .github/workflows/spell-check.yaml
=> style: fix English

planning/behavior_velocity_planner/src/scene_module/detection_area/debug.cpp, planning/behavior_velocity_planner/src/scene_module/detection_area/scene.cpp
#313 
publish all point cloud in detection area is very heavy so publish one point for debug.
launch psim see rviz marker is noticable.
from 
to 
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you …
=> chore(behavior_velocity): lighten detection area debug marker

launch/tier4_vehicle_launch/README.md, perception/multi_object_tracker/README.md, planning/behavior_velocity_planner/README.md, sensing/imu_corrector/README.md, system/system_error_monitor/README.md
=> docs: fix invalid links

.github/workflows/build-and-test-pr.yaml, .github/workflows/build-and-test.yaml
Signed-off-by: Keisuke Shima <19993104+KeisukeShima@users.noreply.github.com>
Fix build and test error:
https://github.com/autowarefoundation/autoware.universe/actions/runs/1770255441
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). …
=> ci(build-and-test-pr): change option

common/web_controller/launch/web_controller.launch.xml
The launch file of the web controller also launches rosbridge, but rosbridge is used for other purposes besides the web controller, so it is not a suitable place to launch it.
Therefore, delete this file and use AutowareArchitectureProposal_launcher to launch it.
- `ros2 launch web_controller web_controller.launch.xml`
- check `ros2 node list|grep rosbridge`, is empty
https://github.com/tier4/AutowareArchitectureProposal_launcher/pull/175
- **Build and …
=> fix(web controller): remove rosbridge launch from web_controller launch file

planning/obstacle_stop_planner/README.md
add documentation of obstacle_stop_planner …
=> docs: add obstacle stop doc

vehicle/pacmod_interface/include/pacmod_interface/pacmod_interface.hpp, vehicle/pacmod_interface/src/pacmod_interface/pacmod_interface.cpp
add parameter for tuning tire radius to correct vehicle odometry.
confirm vehicle odometry is changed by this parameter.
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to …
=> feat(pacmod_interface): add parameter for tuning tire radius

perception/map_based_prediction/CMakeLists.txt, perception/map_based_prediction/include/map_based_prediction.hpp, perception/map_based_prediction/src/map_based_prediction.cpp, perception/map_based_prediction/src/map_based_prediction_ros.cpp
This PR has below changes.
- suppess warnings `-Wunused-parameter` and `-Wformat-security`
- add Werror
- fix clang-tidy error 
```
error: method 'getPredictedPath' can be made const [readability-make-member-function-const,-warnings-as-errors]
error: method 'getLinearPredictedPath' can be made const [readability-make-member-function-const,-warnings-as-errors]
```
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is …
=> fix(map based prediction): suppress warnings 

launch/tier4_localization_launch/config/ndt_scan_matcher.param.yaml, localization/ndt_scan_matcher/config/ndt_scan_matcher.param.yaml, localization/ndt_scan_matcher/include/ndt_scan_matcher/ndt_scan_matcher_core.hpp, localization/ndt_scan_matcher/include/ndt_scan_matcher/util_func.hpp, localization/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp, localization/ndt_scan_matcher/src/util_func.cpp
parameterize the number of particles to estimate initial pose.
Build with https://github.com/tier4/autoware_launch/pull/181.
Please change the number of particles from the yaml file,
and check `/localization/pose_estimator/monte_carlo_initial_pose_marker` on RViz.
The number of  particles should increase or decrease.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false positives? …
=> feat(ndt_scan_matcher): add particles param

planning/behavior_velocity_planner/include/scene_module/occlusion_spot/scene_occlusion_spot_in_private_road.hpp, planning/behavior_velocity_planner/src/scene_module/intersection/util.cpp, planning/behavior_velocity_planner/src/scene_module/no_stopping_area/scene_no_stopping_area.cpp, planning/behavior_velocity_planner/src/scene_module/occlusion_spot/debug.cpp, planning/behavior_velocity_planner/src/scene_module/occlusion_spot/occlusion_spot_utils.cpp, planning/behavior_velocity_planner/src/scene_module/occlusion_spot/scene_occlusion_spot_in_private_road.cpp
- fix last point of angle at spline interpolation at below modules (bug fix)
added marker to confirm this fix
- intersection
- blindspot
- occlusion spot
- no stopping area
- fix duplicated polygon of sidewalk slice(just visualization problem)
launch Psim
and see debug markers using  Map in Private Area tag
autoware_launch
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false …
=> fix(behavior_velocity): visualization and interpolation

localization/vehicle_velocity_converter/README.md
Very small spell correction so no issue is required
Just replace `This package is converted` -> `This package converts`
Just look at it 
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add …
=> docs(vehicle_velocity_converter): sentence correction in README

.github/workflows/build-and-test-differential-self-hosted.yaml, .github/workflows/build-and-test-differential.yaml, .github/workflows/build-and-test-self-hosted.yaml, .github/workflows/build-and-test.yaml, .github/workflows/check-build-depends.yaml
Signed-off-by: Keisuke Shima <19993104+KeisukeShima@users.noreply.github.com>
https://github.com/autowarefoundation/autoware.universe/issues/286
https://github.com/autowarefoundation/autoware-documentation/issues/2
I replaced build-and-test with build and test workflow.
When new actions are merged, this workflow will be enabled.
Check workflow.
https://github.com/autowarefoundation/autoware-github-actions/pull/49
- **Build and test for PR / …
=> ci: update build and test workflow

control/trajectory_follower_nodes/design/longitudinal_controller-design.md
https://github.com/autowarefoundation/autoware.universe/issues/380
Added the explanation of parameters of ongitudinal controller
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). …
=> feat(longitudinal controller): add params explanation

control/trajectory_follower_nodes/param/longitudinal_controller_defaults.yaml
Unused parameters are in the yaml file.
Removed unnecessary parameters (vehicle dynamics pamaeters) in longitudinal controller
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words …
=> feat(longitudinal controller): remove unnecessary params

sensing/pointcloud_preprocessor/src/outlier_filter/ring_outlier_filter_nodelet.cpp
If the index of the ring is greater than 127, the node will die due to out_of_rage of the vector, so use unordered_map.
This is for
- sensors with more than 128 rings in the future.
- sensors with ring index of 1-128 (I'm not sure if it exists)
https://github.com/tier4/autoware.iv/pull/2419
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s). Found false positives? See the …
=> feat(pointcloud_preprocessor): use unordered_map in ring_outlier_filter

localization/gyro_odometer/README.md
Signed-off-by: Yamato Ando <yamato.ando@gmail.com>
update gyro_odometer's readme.
Please make sure it's a correct sentence.
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to …
=> feat(gyro_odometer): update readme

planning/obstacle_stop_planner/config/plot_juggler_adaptive_cruise.xml, planning/obstacle_stop_planner/config/plot_juggler_slow_down.xml, planning/obstacle_stop_planner/src/adaptive_cruise_control.cpp, planning/obstacle_stop_planner/src/debug_marker.cpp
The plotJuggler config can not be loaded correctly.
Fix topic names used there. …
=> fix(obstacle_stop_planner): fix debug topic name

common/interpolation/include/interpolation/linear_interpolation.hpp, common/interpolation/src/linear_interpolation.cpp, common/interpolation/test/src/test_linear_interpolation.cpp
None.
- Add an interpolation function for a scalar key_value.
- Add related tests.
Check if the `colcon test` passes.
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the …
=> feat(interpolation): add float key lerp api

launch/tier4_integration_launch/README.md, launch/tier4_integration_launch/integration_launch.drawio.svg, launch/tier4_integration_launch/launch/ci_planning_simulator.launch.xml, launch/tier4_integration_launch/launch/release.launch.xml, launch/tier4_integration_launch/package.xml
=> fix: replace tier4_autoware_launch with autoware_launch

system/ad_service_state_monitor/config/ad_service_state_monitor.param.yaml, system/ad_service_state_monitor/config/ad_service_state_monitor.planning_simulation.param.yaml
fix typo `Autoware` -> `AD Service` …
=> chore(ad_service_state_monitor): fix node names in comments

launch/tier4_perception_launch/launch/occupancy_grid_map/occupancy_grid_map.launch.py, simulator/dummy_perception_publisher/launch/dummy_perception_publisher.launch.xml
- improvements
laserscan to occupancy grid refer to perception launch 
fix angle increment according to https://github.com/tier4/autoware_launch/pull/220
```
-  <include file="$(find-pkg-share laserscan_to_occupancy_grid_map)/launch/laserscan_to_occupancy_grid_map.launch.py">
+ <include file="$(find-pkg-share tier4_perception_launch)/launch/occupancy_grid_map/occupancy_grid_map.launch.py">
```
@kenji-miyake 
is this change ok to use perception_launch?
launch psim and see the behavior is the same
https://github.com/tier4/autoware_launch/pull/220
**PR Author should check the checkboxes below before …
=> fix(dummy_perception): fix to use launch at perception launch

launch/tier4_planning_launch/launch/scenario_planning/scenario_planning.launch.xml
None
Add parameter options for the motion_velocity_smoother as a description tag.
None
None …
=> refactor(scenario_planning.launch.xml): add parameter description

sensing/pointcloud_preprocessor/docs/dual-return-outlier-filter.md, sensing/pointcloud_preprocessor/include/pointcloud_preprocessor/outlier_filter/dual_return_outlier_filter_nodelet.hpp, sensing/pointcloud_preprocessor/src/outlier_filter/dual_return_outlier_filter_nodelet.cpp
https://github.com/tier4/AutowareArchitectureProposal.iv/pull/782
Porting PR of https://github.com/tier4/AutowareArchitectureProposal.iv/pull/782: Change output of LiDAR visibility diag
- Change initial output value of diagnostic to stale
- Separate warning threshold from error threshold
- Change debug topic names
Make sure this PR is the same with https://github.com/tier4/AutowareArchitectureProposal.iv/pull/782
Confirm the initial output of the LiDAR visibility diag is stale, value is -1.
- **Build and test for PR / …
=> fix(dual_return_outlier_filter): change visibility diag initial value

planning/behavior_velocity_planner/include/behavior_velocity_planner/node.hpp, planning/behavior_velocity_planner/include/behavior_velocity_planner/planner_manager.hpp, planning/behavior_velocity_planner/src/node.cpp, planning/behavior_velocity_planner/src/planner_manager.cpp
https://github.com/autowarefoundation/autoware.universe/issues/275
To solve [this problem](https://github.com/autowarefoundation/autoware.universe/issues/275) in behavior velocity planner,  multi thread is used for callbacks by passing a different callback group, whose type is MutuallyExclusive, to each calback.
Run simple psim, and see if each callback of subscribes is called in a steady cycle. …
=> feat(behavior_velocity): use multi thread

control/vehicle_cmd_gate/package.xml
Signed-off-by: Keisuke Shima <19993104+KeisukeShima@users.noreply.github.com>
I found a full-width space and have corrected it.
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some …
=> fix(vehicle_cmd_gate): fix whitespace

planning/behavior_path_planner/src/utilities.cpp
https://github.com/autowarefoundation/autoware.universe/issues/503
Because of the current algorithm of generating drivable area, the drivable area tries to capture both ego pose and the trajectory to follow.
Therefore, if ego pose is far away from the trajectory (like once generating trajectory, and then reposition the ego pose far away), the size of drivable area will be so large.
This cannot happen in the real world, but happen in the simulation.
To fix this issue, drivable area tries to capture just the trajectory to follow
in simple psim, check if the size of drivable area won't be large after once generating trajectory and repositioning the ego pose far away.
If you are adding new package following items are …
=> feat(behavior_path_planner): make not too large drivable area after repositioning ego pose

launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml, launch/tier4_perception_launch/launch/object_recognition/detection/lidar_based_detection.launch.xml, perception/roi_cluster_fusion/src/roi_cluster_fusion_nodelet.cpp, perception/shape_estimation/launch/shape_estimation.launch.xml, sensing/image_transport_decompressor/CMakeLists.txt, sensing/image_transport_decompressor/launch/image_transport_decompressor.launch.xml
Fixed a porting error in camera lidar fusion when porting to autoware.auto.
Confirmed to work with tier4 rosbag on my environment.
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). …
=> fix: integration miss related to camera lidar fusion

planning/behavior_velocity_planner/src/scene_module/traffic_light/scene.cpp
#504 
- fix stop line insertion in traffic light 
* target velocity point
| insert target point index  
--------------*-----------------------|-----
check CI pass
one of failure is because of ad service state monitor which is not included in CI-commit
https://github.com/autowarefoundation/autoware.universe/pull/505
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up …
=> fix(behavior_velocity): add traffic light stop point insert

control/vehicle_cmd_gate/src/vehicle_cmd_gate.cpp
#529
add missing time stamp at emergency and stop command
launch psim and see behavior …
=> fix(vehicle_cmd_gate): add missing time stamp

sensing/laserscan_to_occupancy_grid_map/include/laserscan_to_occupancy_grid_map/laserscan_to_occupancy_grid_map_node.hpp, sensing/laserscan_to_occupancy_grid_map/include/laserscan_to_occupancy_grid_map/updater/occupancy_grid_map_binary_bayes_filter_updater.hpp, sensing/laserscan_to_occupancy_grid_map/include/laserscan_to_occupancy_grid_map/updater/occupancy_grid_map_updater_interface.hpp, sensing/laserscan_to_occupancy_grid_map/src/laserscan_to_occupancy_grid_map_node.cpp, sensing/laserscan_to_occupancy_grid_map/src/updater/occupancy_grid_map_binary_bayes_filter_updater.cpp
Supported because we want to use single frame results without using time series filters. …
=> feat: support single frame mode

system/system_error_monitor/config/diagnostic_aggregator/system.param.yaml, system/system_error_monitor/launch/system_error_monitor.launch.xml
This PR has two changes.
- add arg `extra_agg_config_file_system` to register user specific diag
- delete tier4 specific diags 
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some …
=> feat(system_error_monitor): add arg `extra_agg_config_file_system` to register user specific diag and delete tier4 specific diags

localization/ekf_localizer/README.md
Updated subscribed topics message type in the README.md based on ekf_localizer package
PR author **must** check the checkboxes below when creating the PR.
Reviewers **must** check the checkboxes below before approval.
PR author **must** check the checkboxes below before merging.
After all checkboxes are checked, anyone who has the write access can merge the PR.
=> docs(ekf_localizer): update subscribed topic msg type

common/tier4_perception_rviz_plugin/CMakeLists.txt, common/tier4_perception_rviz_plugin/src/tools/car_pose.cpp, common/tier4_perception_rviz_plugin/src/tools/car_pose.hpp, common/tier4_perception_rviz_plugin/src/tools/interactive_object.cpp, common/tier4_perception_rviz_plugin/src/tools/interactive_object.hpp, common/tier4_perception_rviz_plugin/src/tools/pedestrian_pose.cpp, common/tier4_perception_rviz_plugin/src/tools/pedestrian_pose.hpp, common/tier4_perception_rviz_plugin/src/tools/unknown_pose.cpp, common/tier4_perception_rviz_plugin/src/tools/unknown_pose.hpp
Support 2D interactive dummy car/unknown object.
- https://github.com/autowarefoundation/autoware.universe/issues/533
https://user-images.githubusercontent.com/44889564/159410919-ab5fce2b-ab9f-4629-afb2-6f6babd44cd6.mp4
please see the above video.
key commands are...
| action | key command |
| ---- | ---- |
| ADD  | Shift + Click Right Button |
| MOVE | Hold down Right Button + Drug and Drop |
| DELETE | Alt + Click Right Button |
PR author **must** check the checkboxes below when creating the PR.
Reviewers **must** check the checkboxes below before approval.
PR author **must** check the checkboxes below before merging.
After all checkboxes are checked, anyone who has the write access can merge the PR.
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/m …
=> feat(tier4_perception_rviz_plugin): plugin supports interactive manipulation for dummy CAR & UNKNOWN object

launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml, launch/tier4_perception_launch/launch/object_recognition/detection/detection.launch.xml, launch/tier4_perception_launch/launch/object_recognition/detection/lidar_based_detection.launch.xml, launch/tier4_perception_launch/launch/perception.launch.xml, perception/detected_object_validation/launch/obstacle_pointcloud_based_validator.launch.xml, perception/euclidean_cluster/launch/voxel_grid_based_euclidean_cluster.launch.xml
The detected object validator using the pointcloud map is added in the perception launch.
Also, fix bug caused by typo
=> feat: launch detected object validator

system/system_monitor/README.md, system/system_monitor/config/hdd_monitor.param.yaml, system/system_monitor/docs/hdd_reader.md, system/system_monitor/docs/ros_parameters.md, system/system_monitor/docs/topics_hdd_monitor.md, system/system_monitor/include/hdd_reader/hdd_reader.hpp, system/system_monitor/include/system_monitor/hdd_monitor/hdd_monitor.hpp, system/system_monitor/reader/hdd_reader/hdd_reader.cpp, system/system_monitor/src/hdd_monitor/hdd_monitor.cpp
add some S.M.A.R.T information for monitoring HDD life to diagnostics
https://github.com/tier4/autoware.universe/pull/25
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to …
=> feat(system_monitor): add some smart information to diagnostics

planning/behavior_velocity_planner/src/node.cpp
fix behavior velocity fix commonly used acceleration check
=> fix(behavior_velocity): add check of common acceleration

launch/tier4_localization_launch/launch/localization.launch.xml, launch/tier4_localization_launch/launch/util/util.launch.py, launch/tier4_localization_launch/launch/util/util.launch.xml, launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml, launch/tier4_perception_launch/launch/object_recognition/detection/detection.launch.xml, launch/tier4_perception_launch/launch/object_recognition/detection/lidar_based_detection.launch.xml, launch/tier4_perception_launch/launch/perception.launch.xml
fix localization and perception launch for tutorial.
Also I changed centerpoint to apollo detector because it seems to better than centerpoint
https://github.com/autowarefoundation/autoware.universe/issues/643#issue-1194223701
=> fix: localization and perception launch for tutorial

planning/behavior_path_planner/src/behavior_path_planner_node.cpp, planning/freespace_planner/src/freespace_planner/freespace_planner_node.cpp
Set `transient-local` for route subscribers.
=> fix(route): set transient_local for route subscriber

launch/tier4_autoware_api_launch/CMakeLists.txt, launch/tier4_autoware_api_launch/README.md, launch/tier4_autoware_api_launch/launch/autoware_api.launch.xml, launch/tier4_autoware_api_launch/launch/include/external_api_adaptor.launch.py, launch/tier4_autoware_api_launch/launch/include/internal_api_adaptor.launch.py, launch/tier4_autoware_api_launch/launch/include/internal_api_relay.launch.xml, launch/tier4_autoware_api_launch/package.xml
Signed-off-by: mitsudome-r <ryohsuke.mitsudome@tier4.jp>
This PR adds tier4_autoware_api_launch package to the repository which is required to connect Autoware with TIER IV's scenario simulator. 
For the details, please refer to https://github.com/autowarefoundation/autoware.universe/issues/656.
https://github.com/autowarefoundation/autoware.universe/issues/656
Follow the [installation instruction](https://autowarefoundation.github.io/autoware-documentation/main/installation/autoware/source-installation/) from the documentation and confirm that it build without an error.
This PR depends on https://github.com/autowarefoundation/autoware/pull/156
The …
=> feat(tier4_autoware_api_launch): add tier4_autoware_api_launch package

planning/behavior_velocity_planner/src/scene_module/traffic_light/scene.cpp
=> fix(behavior_velocity): traffic light missing debug wall pose

launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/blind_spot.param.yaml, launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml, launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/detection_area.param.yaml, launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml, launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/no_stopping_area.param.yaml, launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/occlusion_spot.param.yaml, launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/stop_line.param.yaml, launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/traffic_light.param.yaml, launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/virtual_traffic_light.param.yaml, launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.py
Signed-off-by: k-obitsu <koichi.obitsu@tier4.jp>
- Fixed the path of 'stop_line.param.yaml' in 'behavior_planning.launch.py'
- Related to the above, added param.yaml files.
=> fix(tier4_planning_launch): fix tier4_planning_launch package

perception/multi_object_tracker/src/multi_object_tracker_core.cpp
https://github.com/autowarefoundation/autoware.universe/pull/655#issuecomment-1100903993
=> fix(multi_object_tracker): fix for unknown object

common/interpolation/include/interpolation/spline_interpolation_points_2d.hpp, common/interpolation/src/spline_interpolation_points_2d.cpp, common/interpolation/test/src/test_spline_interpolation.cpp
I think template function must be implemented in header, if without explicit instantiation in the impl file. 
Otherwise, using such function may cause compile time error, or worse  symbol lookup error in runtime. 
@takayuki5168 
@TakaHoribe 
reference: 
https://stackoverflow.com/questions/495021/why-can-templates-only-be-implemented-in-the-header-file
A test was added in https://github.com/autowarefoundation/autoware.universe/commit/f4723923e738352bd684c77a96432ea0adc8d6fc
which cannot be compiled with the original code with the following message: 
```
/usr/bin/ld: CMakeFiles/test_interpolation.dir/test/src/test_spline_interpolation.cpp.o: in function `spline_interpolation_SplineInterpolationPoints2dPolymorphism_Test::TestBody()':
test_spline_interpolation.cpp:(.text+0x21b7): undefined …
```
=> fix(interpolation): implementation of template function to header

launch/tier4_planning_launch/config/scenario_planning/common/motion_velocity_smoother/motion_velocity_smoother.param.yaml
=> fix(motion_velocity_smoother): add stop decel parameter

common/autoware_testing/design/autoware_testing-design.md
Fix link to the wikipedia article for smoke testing
=> docs(autoware_testing): fix link

planning/motion_velocity_smoother/scripts/trajectory_visualizer.py
In trajectory_visualizer.py, 
the arc length of the point with index 0 of each trajectory is considered to be 0, and  there was a problem that the positions of each trajectory were not aligned.
In this PR, the positions of  each trajectory are aligned by considering the arc length of the point closest to the vehicle position as 0.
(The arc length of the points behind the vehicle become minus.)
$ros2 run motion_velocity_smoother trajectory_visualizer.py 
Before 
`obstacle_stop_traj` and `opt fianl` are offset sideways
After
`obstacle_stop_traj` and `opt fianl` are aligned. …
=> fix: trajectory visualizer

system/dummy_diag_publisher/package.xml
modify the following error on rolling
```
/home/daisuke/workspace/autoware.proj.universe.rolling/src/autoware/universe/system/dummy_diag_publisher/src/dummy_diag_publisher_node/dummy_diag_publisher_node.cpp:104:10: fatal error: rclcpp_components/register_node_macro.hpp: そのようなファイルやディレクトリはありません
104 | #include <rclcpp_components/register_node_macro.hpp>
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gmake[2]: *** [CMakeFiles/dummy_diag_publisher.dir/build.make:76: CMakeFiles/dummy_diag_publisher.dir/src/dummy_diag_publisher_node/dummy_diag_publisher_node.cpp.o] エラー 1
gmake[1]: *** [CMakeFiles/Makefile2:139: CMakeFiles/dummy_diag_publisher.dir/all] エラー 2
gmake: *** [Makefile:146: all] エラー 2
--- stderr: …
```
=> fix(dummy_diag_publisher): modify build error in rolling

control/control_performance_analysis/CMakeLists.txt, control/control_performance_analysis/package.xml
See https://docs.ros.org/en/foxy/Releases/Release-Humble-Hawksbill.html#rosidl-cmake.
=> fix(control_performance_analysis): modify build error in rolling

perception/detected_object_validation/src/obstacle_pointcloud_based_validator.cpp, perception/detected_object_validation/src/occupancy_grid_based_validator.cpp
=> fix(detected_object_validation): modify build error in rolling

perception/image_projection_based_fusion/package.xml
This PR fixed the following build error on rolling.
```
gmake[2]: *** [CMakeFiles/image_projection_based_fusion.dir/build.make:76: CMakeFiles/image_projection_based_fusion.dir/src/fusion_node.cpp.o] エラー 1
In file included from /home/daisuke/workspace/autoware.proj.universe.rolling/src/autoware/universe/perception/image_projection_based_fusion/src/roi_detected_object_fusion/node.cpp:18:
/home/daisuke/workspace/autoware.proj.universe.rolling/src/autoware/universe/perception/image_projection_based_fusion/include/image_projection_based_fusion/utils/utils.hpp:24:10: fatal error: tf2_eigen/tf2_eigen.h: そのようなファイルやディレクトリはありません
24 | #include <tf2_eigen/tf2_eigen.h>
|          ^~~~~~~~~~~~~~~~~~~~~~~
gmake[2]: *** [CMakeFiles/image_projection_based_fusion.dir/build.make:146: …
```
=> fix(image_projection_based_fusion): modify build error in rolling

simulator/fault_injection/CMakeLists.txt, simulator/fault_injection/src/fault_injection_node/fault_injection_node.cpp
=> fix(fault_injection): modify build error in rolling

map/map_loader/CMakeLists.txt
=> fix(map_loader): modify build error in rolling

perception/map_based_prediction/src/map_based_prediction_node.cpp
=> fix(map_based_prediction): modify build error in rolling

planning/freespace_planner/include/freespace_planner/freespace_planner_node.hpp
=> fix(freespace_planner): modify build error in rolling

perception/lidar_centerpoint/package.xml
=> fix(lidar_centerpoint): modify build error in rolling

sensing/probabilistic_occupancy_grid_map/package.xml
=> fix(probabilistic_occupancy_grid_map): modify build error in rolling

planning/obstacle_stop_planner/src/adaptive_cruise_control.cpp, planning/obstacle_stop_planner/src/debug_marker.cpp, planning/obstacle_stop_planner/src/node.cpp
=> fix(obstacle_stop_planner): modify build error in rolling

control/obstacle_collision_checker/src/obstacle_collision_checker_node/obstacle_collision_checker.cpp
=> fix(obstacle_collision_checker): modify build error in rolling

control/pure_pursuit/CMakeLists.txt, control/pure_pursuit/include/pure_pursuit/util/planning_utils.hpp, control/pure_pursuit/include/pure_pursuit/util/tf_utils.hpp, control/pure_pursuit/package.xml
=> fix(pure_pursuit): modify build error in rolling

localization/ndt/CMakeLists.txt, localization/ndt/include/ndt/base.hpp, localization/ndt/include/ndt/impl/omp.hpp, localization/ndt/include/ndt/impl/pcl_generic.hpp, localization/ndt/include/ndt/impl/pcl_modified.hpp, localization/ndt/include/ndt/omp.hpp, localization/ndt/include/ndt/pcl_generic.hpp, localization/ndt/include/ndt/pcl_modified.hpp, localization/ndt_pcl_modified/CMakeLists.txt, localization/ndt_pcl_modified/include/ndt_pcl_modified/impl/ndt.hpp, localization/ndt_pcl_modified/include/ndt_pcl_modified/ndt.hpp, localization/ndt_scan_matcher/include/ndt_scan_matcher/ndt_scan_matcher_core.hpp, localization/ndt_scan_matcher/include/ndt_scan_matcher/util_func.hpp, localization/ndt_scan_matcher/package.xml, localization/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp
This PR fixes the build errors of ndt related packages on rolling distro mainly caused by PCL update.
See the links below.
https://github.com/PointCloudLibrary/pcl/commit/88524c1b4b28c64912e1fc619690acb3457ed9fa
https://github.com/PointCloudLibrary/pcl/issues/2792
https://github.com/ros-perception/perception_pcl/pull/361 …
=> fix: modify build error of ndt related packages in rolling

sensing/gnss_poser/CMakeLists.txt, sensing/gnss_poser/include/gnss_poser/gnss_poser_core.hpp, sensing/gnss_poser/package.xml
=> fix(gnss_poser): modify build error in rolling

perception/traffic_light_map_based_detector/package.xml
=> fix(traffic_light_map_based_detector): modify build error in rolling

common/tier4_planning_rviz_plugin/src/tools/jsk_overlay_utils.hpp
=> fix(tier4_planning_rviz_plugins): modify build error in rolling

localization/stop_filter/package.xml
=> fix(stop_filter): modify build error in rolling

planning/behavior_velocity_planner/CMakeLists.txt, planning/behavior_velocity_planner/include/scene_module/intersection/util.hpp, planning/behavior_velocity_planner/include/scene_module/occlusion_spot/grid_utils.hpp, planning/behavior_velocity_planner/include/scene_module/occlusion_spot/occlusion_spot_utils.hpp, planning/behavior_velocity_planner/include/utilization/arc_lane_util.hpp, planning/behavior_velocity_planner/src/node.cpp, planning/behavior_velocity_planner/src/scene_module/detection_area/debug.cpp, planning/behavior_velocity_planner/src/scene_module/detection_area/scene.cpp, planning/behavior_velocity_planner/src/scene_module/no_stopping_area/debug.cpp, planning/behavior_velocity_planner/src/scene_module/no_stopping_area/scene_no_stopping_area.cpp, planning/behavior_velocity_planner/src/scene_module/stop_line/debug.cpp, planning/behavior_velocity_planner/src/scene_module/traffic_light/debug.cpp, planning/behavior_velocity_planner/src/scene_module/traffic_light/scene.cpp, planning/behavior_velocity_planner/src/utilization/path_utilization.cpp, planning/behavior_velocity_planner/test/src/test_occlusion_spot_utils.cpp, planning/behavior_velocity_planner/test/src/utils.hpp
=> fix(behavior_velocity_planner): modify build error in rolling

planning/behavior_path_planner/src/utilities.cpp, planning/route_handler/include/route_handler/route_handler.hpp, planning/route_handler/src/route_handler.cpp
When the initial ego pose is close to the boudary between two lanelets, the ego pose's footprint is sometimes out of the drivable area, which makes the trajectory points' velocities zero by obstacle_avoidance_planner, as shown in the following figure.
I expanded the drivable area properly so that the ego pose is inside the drivable area.
---
FYI
The same handling is already done for the goal pose (for end trajectory point)
https://github.com/autowarefoundation/autoware.universe/blob/ae8422b668441157e59bc72fa14bad46fd0ec8dd/planning/behavior_path_planner/src/utilities.cpp#L1140-L1143
So this PR means the same handling will be done for the initial pose (for start trajectory point)
The second issue of …
=> feat(behavior_path_planner): make initial ego pose in drivable area

common/component_interface_utils/include/component_interface_utils/rclcpp/service_server.hpp, perception/lidar_apollo_instance_segmentation/CMakeLists.txt, perception/lidar_apollo_instance_segmentation/include/lidar_apollo_instance_segmentation/detector.hpp, perception/lidar_apollo_instance_segmentation/package.xml, perception/lidar_apollo_instance_segmentation/src/cluster2d.cpp, simulator/fault_injection/CMakeLists.txt, simulator/fault_injection/src/fault_injection_node/fault_injection_node.cpp, system/default_ad_api/CMakeLists.txt
- USE_DEPRECATED_TO_YAML
- USE_TF2_GEOMETRY_MSGS_DEPRECATED_HEADER
- rclcpp_components
=> fix: apply fixes for rolling

common/autoware_auto_geometry/design/polygon_intersection_2d-design.md
=> docs(autoware_auto_geometry): fix link

map/util/lanelet2_map_preprocessor/CMakeLists.txt, map/util/lanelet2_map_preprocessor/src/fix_lane_change_tags.cpp, map/util/lanelet2_map_preprocessor/src/fix_z_value_by_pcd.cpp, map/util/lanelet2_map_preprocessor/src/merge_close_lines.cpp, map/util/lanelet2_map_preprocessor/src/merge_close_points.cpp, map/util/lanelet2_map_preprocessor/src/remove_unreferenced_geometry.cpp, map/util/lanelet2_map_preprocessor/src/transform_maps.cpp
Resolves #457
Note: I've not tested the behavior of each tool.
=> feat: port lanelet2_map_preprocessor to ROS2

map/util/lanelet2_map_preprocessor/CMakeLists.txt, map/util/lanelet2_map_preprocessor/launch/fix_z_value_by_pcd.launch.xml, map/util/lanelet2_map_preprocessor/launch/transform_maps.launch.xml, map/util/lanelet2_map_preprocessor/package.xml, map/util/lanelet2_map_preprocessor/src/fix_lane_change_tags.cpp, map/util/lanelet2_map_preprocessor/src/fix_z_value_by_pcd.cpp, map/util/lanelet2_map_preprocessor/src/merge_close_lines.cpp, map/util/lanelet2_map_preprocessor/src/merge_close_points.cpp, map/util/lanelet2_map_preprocessor/src/remove_unreferenced_geometry.cpp, map/util/lanelet2_map_preprocessor/src/transform_maps.cpp
part of 
https://github.com/autowarefoundation/autoware.universe/issues/457
This ports lanelet2_map_preprocessor package into ROS2. 
Run the following launch files and make sure that it works:
* `ros2 launch lanelet2_map_preprocessor transform_maps.launch.xml llt_map_path:=<input_lanelet2_map> pcd_map_path:=<input pointcloud_map> llt_output_path:=<output_lanelet2_map> pcd_output_path:=<output_pointcloud_map> x:=<translation value for x>`
* ros2 launch lanelet2_map_preprocessor fix_z_value_by_pcd.launch.xml  llt_map_path:=<input_lanelet2_map> pcd_map_path:=<input pointcloud_map> llt_output_path:=<output_lanelet2_map>`
**Reviewers should check the checkboxes …
=> feat(lanelet2_map_preprocessor): port lanelet2_map_preprocessor from ROS1 to ROS2

system/system_monitor/src/gpu_monitor/tegra_gpu_monitor.cpp
Signed-off-by: Shark Liu <shark.liu@autocore.ai>
Resolve #868 
#868 
Nvidia AGX Xavier
=> fix(system_monitor): fix build error on tegra platform

system/ad_service_state_monitor/src/ad_service_state_monitor_node/ad_service_state_monitor_node.cpp
Resolves https://github.com/autowarefoundation/autoware.universe/issues/513
Limit the size of odometry buffer 40, which is `state_param_.th_stopped_time_sec` (= 1 sec) * localization topic hz( = 40Hz).
I confirmed that with the current default setting, the size of odometry buffer does not change (the size limit is equal to the limit based on time).
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the …
=> feat(ad_service_state_monitor): limit odometry buffer size

launch/tier4_perception_launch/launch/object_recognition/prediction/prediction.launch.xml
Removed naive prediction package in prediction launch.
=> feat: remove deprecated package in prediction launch

perception/lidar_apollo_instance_segmentation/CMakeLists.txt, perception/lidar_apollo_instance_segmentation/lib/include/TrtNet.hpp, perception/lidar_apollo_instance_segmentation/lib/src/TrtNet.cpp, perception/lidar_apollo_instance_segmentation/src/detector.cpp, perception/lidar_centerpoint/CMakeLists.txt, perception/lidar_centerpoint/lib/include/tensorrt_wrapper.hpp, perception/lidar_centerpoint/lib/src/tensorrt_wrapper.cpp, perception/tensorrt_yolo/CMakeLists.txt, perception/tensorrt_yolo/lib/include/trt_yolo.hpp, perception/tensorrt_yolo/lib/src/trt_yolo.cpp, perception/traffic_light_classifier/CMakeLists.txt, perception/traffic_light_classifier/utils/trt_common.cpp, perception/traffic_light_ssd_fine_detector/CMakeLists.txt, perception/traffic_light_ssd_fine_detector/lib/include/trt_ssd.hpp, perception/traffic_light_ssd_fine_detector/lib/src/trt_ssd.cpp
=> fix: update nvinfer api

common/tier4_state_rviz_plugin/package.xml, common/tier4_state_rviz_plugin/src/autoware_state_panel.cpp, common/tier4_state_rviz_plugin/src/autoware_state_panel.hpp
add velocity limit to rviz plugin panel to test easily
https://user-images.githubusercontent.com/65527974/167554153-a2ad3118-cd70-4690-86f9-40dcc6858db1.mp4
By Psim
please add autoware state panel first
=> feat(rviz_plugins): add velocity limit to autoware state panel

map/lanelet2_extension/lib/utilities.cpp, planning/behavior_path_planner/src/utilities.cpp
The iteration of closing drivable area will be 1, which was previously 10.
If the iteration is 10, there is a certain difference between drivable area's boundary and lane's boundary.
=> feat(behavior_path_planner): weakened noise filtering of drivable area

control/vehicle_cmd_gate/CMakeLists.txt, control/vehicle_cmd_gate/include/vehicle_cmd_gate/vehicle_cmd_gate.hpp, control/vehicle_cmd_gate/src/vehicle_cmd_gate.cpp
=> refactor(vehicle-cmd-gate): using namespace for msgs

launch/tier4_system_launch/config/system_monitor/hdd_monitor.param.yaml, system/system_error_monitor/config/diagnostic_aggregator/system.param.yaml, system/system_monitor/README.md
add some S.M.A.R.T information for monitoring HDD life to diagnostics
fix param files and description in README
https://github.com/tier4/autoware.universe/pull/25
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See …
=> fix(system_monitor): add some smart information to diagnostics

map/lanelet2_extension/include/lanelet2_extension/visualization/visualization.hpp, map/lanelet2_extension/lib/visualization.cpp, map/map_loader/src/lanelet2_map_loader/lanelet2_map_visualization_node.cpp
- visualize center line by points
- It is useful to confirm `center_line_resolution`
=> feat(map_loader): visualize center line by points

launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/behavior_velocity_planner.param.yaml, launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.py, planning/behavior_velocity_planner/config/behavior_velocity_planner.param.yaml
- create parameter yaml for behavior_velocity_planner
=> feat(tier4_planning_launch): create parameter yaml for behavior_velocity_planner

launch/tier4_map_launch/launch/map.launch.py
- refactor map.launch.py to use LaunchConfiguration().perform(context) in the future
=> refactor: tier4_map_launch

.github/sync-files.yaml
Changes for https://github.com/autowarefoundation/autoware_common/pull/75.
=> ci(sync-files): update settings

common/kalman_filter/CMakeLists.txt, common/motion_common/CMakeLists.txt, common/osqp_interface/CMakeLists.txt, common/tier4_debug_tools/CMakeLists.txt, common/tier4_planning_rviz_plugin/CMakeLists.txt, control/control_performance_analysis/CMakeLists.txt, control/pure_pursuit/CMakeLists.txt, localization/ekf_localizer/CMakeLists.txt, perception/detected_object_validation/CMakeLists.txt, perception/detection_by_tracker/CMakeLists.txt, perception/image_projection_based_fusion/CMakeLists.txt, perception/map_based_prediction/CMakeLists.txt, perception/multi_object_tracker/CMakeLists.txt, perception/shape_estimation/CMakeLists.txt, perception/traffic_light_map_based_detector/CMakeLists.txt, planning/behavior_velocity_planner/CMakeLists.txt, planning/motion_velocity_smoother/CMakeLists.txt, planning/obstacle_avoidance_planner/CMakeLists.txt, planning/obstacle_stop_planner/CMakeLists.txt, planning/surround_obstacle_checker/CMakeLists.txt, sensing/probabilistic_occupancy_grid_map/CMakeLists.txt, sensing/tier4_pcl_extensions/CMakeLists.txt
To resolve this error with Humble arm64.
https://github.com/autowarefoundation/autoware/runs/6612576310?check_suite_focus=true#step:6:5286
Related: https://github.com/autowarefoundation/autoware_common/pull/76
=> fix: set Eigen include directory as SYSTEM for Humble arm64

launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml, launch/tier4_perception_launch/launch/object_recognition/detection/detection_preprocess.launch.py, launch/tier4_perception_launch/launch/object_recognition/detection/lidar_based_detection.launch.xml
=> fix(tier4_perception_launch): rename pkg name

launch/tier4_autoware_api_launch/launch/include/internal_api_relay.launch.xml, planning/scenario_selector/launch/dummy_scenario_selector_lane_driving.launch.xml, planning/scenario_selector/launch/dummy_scenario_selector_parking.launch.xml
related to https://github.com/autowarefoundation/autoware/pull/375
=> chore: replace topic tools

simulator/simple_planning_simulator/design/simple_planning_simulator-design.md
docs(simulator): fixed simple_planning_simulator table
Fixed markdown table to be rendered properly.
=> docs(simulator): fixed simple_planning_simulator table

planning/behavior_path_planner/src/utilities.cpp, planning/route_handler/src/route_handler.cpp
=> feat(behavior_path_planner): use enough backward length for drivable area

launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/rtc_auto_approver/rtc_auto_approver.param.yaml, launch/tier4_planning_launch/launch/scenario_planning/lane_driving.launch.xml
Signed-off-by: Fumiya Watanabe <rej55.g@gmail.com>
Launch rtc_auto_approver in tier4_planning_launch.
https://github.com/autowarefoundation/autoware.universe/issues/891
https://github.com/autowarefoundation/autoware.universe/pull/964
Run planning simulator and check `ros2 node list | grep planning` …
=> feat(tier4_planning_launch): launch rtc_auto_approver

launch/tier4_autoware_api_launch/launch/autoware_api.launch.xml
=> fix(tier4_autoware_api_launch): typo

map/lanelet2_extension/lib/utilities.cpp
With the following PR, we got the error message from lanelet2_extension when just driving the road since offset calculation has changed with the following PR and it differs from what lanelet2 assumes in [this verification function](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/700a96290c9782654e3cf4c287ab1ddec2b7cfbe/lanelet2_core/include/lanelet2_core/geometry/impl/LineString.h#L399-L401)
https://github.com/autowarefoundation/autoware.universe/pull/838/files
With this PR, the verification function is only applied to `offsetNoThrow` function which is what lanelet2 assumes for adding offset. …
=> fix(lanelet2_extension): remove unnecessary error message

launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml, map/lanelet2_extension/include/lanelet2_extension/utility/utilities.hpp, map/lanelet2_extension/lib/utilities.cpp, planning/behavior_velocity_planner/config/intersection.param.yaml, planning/behavior_velocity_planner/include/scene_module/intersection/scene_intersection.hpp, planning/behavior_velocity_planner/include/scene_module/intersection/scene_merge_from_private_road.hpp, planning/behavior_velocity_planner/include/scene_module/intersection/util.hpp, planning/behavior_velocity_planner/src/scene_module/intersection/debug.cpp, planning/behavior_velocity_planner/src/scene_module/intersection/manager.cpp, planning/behavior_velocity_planner/src/scene_module/intersection/scene_intersection.cpp, planning/behavior_velocity_planner/src/scene_module/intersection/scene_merge_from_private_road.cpp, planning/behavior_velocity_planner/src/scene_module/intersection/util.cpp
One of the problems with the current intersection module is that vehicles traveling outside the lanelet cannot be considered as recognized vehicles even if they are at risk of collision.
In the future, this will be solved by improving the performance of the prediction, but this will take time.
Therefore, we consider solving this problem by extending the lanelet used for recognition in the lateral direction.
In this PR, we have achieved visualization of the extended lanelet.
In addition modified it to have parameters for the extension in the right and left directions.
Example: right : 0.5 m, left : 0.5 m extension
Example: right : 2.0 m, left : 0.5 m extension
https://user-images.githubusercontent.com/57553950/171788794-da9f9288-ddae-44a7-8e2e-fb90f5022464.mp4 …
=> feat(intersection): add conflicting area with margin debug

launch/tier4_simulator_launch/launch/simulator.launch.xml
sync autoware launch
https://github.com/tier4/scenario_simulator_v2/pull/803
https://github.com/tier4/autoware_launch/pull/344
use ogm only psim . 
=> feat!: replace ogm at scenario simulation

planning/behavior_velocity_planner/src/node.cpp
Update velocity limit QoS: Volatile -> TransientLocal
=> fix(behavior_velocity_limit): update velocity limit qos (to TransientLodal)

planning/obstacle_cruise_planner/include/obstacle_cruise_planner/pid_based_planner/pid_based_planner.hpp, planning/obstacle_cruise_planner/src/pid_based_planner/pid_based_planner.cpp
Fix distance calculation function.
=> fix(obstacle_cruise_planner): fix distance calculation function

control/trajectory_follower_nodes/test/test_lateral_controller_node.cpp, control/trajectory_follower_nodes/test/test_longitudinal_controller_node.cpp
Signed-off-by: Maxime CLEMENT <maxime.clement@tier4.jp>
Delete a couple of flaky tests that are not so important.
=> test(trajectory_follower_nodes): delete flaky set_param_smoke_test

common/autoware_ad_api_msgs/README.md
Move the document for developers.
https://github.com/autowarefoundation/autoware-documentation/pull/115#discussion_r893481749
=> docs(autoware_ad_api_msgs): update readme

planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module.hpp, planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
Fixed a bug that the cause of avoidance failure of a specific type is not output.
Cause of failure to output normally without merging the PR
Cause of failure to output normally only after merging the PR
=> fix: behavior path avoidance debug

common/tier4_control_rviz_plugin/README.md, common/tier4_control_rviz_plugin/src/tools/manual_controller.cpp
enable testing for backward motion
https://user-images.githubusercontent.com/65527974/174014653-ee1bb6f1-33fb-4442-bc17-d769e079e629.mp4
=> feat(manual_controller): support backward driving

common/neural_networks_provider/CMakeLists.txt, common/neural_networks_provider/design/neural_networks-design.md, common/neural_networks_provider/download_neural_networks.sh, common/neural_networks_provider/neural_networks_provider-extras.cmake, common/neural_networks_provider/package.xml
Port neural_networks from Autoware.Auto, this package
is used to download pre-compiled networks.
Also add artifact hash functionality, used for checking
whether there is a new version of the networks in the S3 bucket.
Issue-Id: SCM-4491
Signed-off-by: Luca Foschiani <luca.foschiani@arm.com>
Change-Id: Ia18e239797989a2639dc01dcea2abeaeacd94f44
This package adds neural networks downloading functionality. It has been ported from Autoware.Auto.
https://github.com/autowarefoundation/autoware.universe/issues/628
https://github.com/autowarefoundation/autoware/discussions/226
After all …
=> feat(neural_networks_provider): port neural_networks_provider

planning/behavior_velocity_planner/src/scene_module/intersection/scene_intersection.cpp
Signed-off-by: 1222-takeshi <m.takeshi1995@gmail.com>
Added the following to detection vehicle type at intersection
- TRAILER
=> fix(intersection_module): fix target vehicle type

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
Signed-off-by: Muhammad Zulfaqar Azmi <zulfaqar.azmi@tier4.jp>
Fix spell check in the `avoidance_module.cpp`
=> chore(behavior_path_planner): fix spelling error

perception/multi_object_tracker/src/tracker/model/big_vehicle_tracker.cpp, perception/multi_object_tracker/src/tracker/model/normal_vehicle_tracker.cpp
Fix Measurement dimension when measurement velocity is invalid
=> fix(multi_object_tracker): fix measurement dimension

launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/intersection.param.yaml, planning/behavior_velocity_planner/config/intersection.param.yaml, planning/behavior_velocity_planner/include/scene_module/intersection/scene_merge_from_private_road.hpp, planning/behavior_velocity_planner/intersection-design.md
Signed-off-by: 1222-takeshi <m.takeshi1995@gmail.com>
Related PR
https://github.com/autowarefoundation/autoware.universe/pull/1178
=> fix(intersection_module): remove decel parameter

launch/tier4_planning_launch/config/scenario_planning/parking/freespace_planner/freespace_planner.param.yaml, planning/freespace_planner/README.md, planning/freespace_planner/config/freespace_planner.param.yaml, planning/freespace_planner/include/freespace_planner/freespace_planner_node.hpp, planning/freespace_planner/src/freespace_planner/freespace_planner_node.cpp
=> refactor(freespace_planner): parameterize margin.

perception/radar_tracks_msgs_converter/include/radar_tracks_msgs_converter/radar_tracks_msgs_converter_node.hpp, perception/radar_tracks_msgs_converter/launch/radar_tracks_msgs_converter.launch.xml, perception/radar_tracks_msgs_converter/src/radar_tracks_msgs_converter_node/radar_tracks_msgs_converter_node.cpp
Change Twist Topic to `/localization/kinematic_state`
=> feat(radar_tracks_msgs_converter): change twist topic

sensing/tier4_pcl_extensions/include/tier4_pcl_extensions/voxel_grid_nearest_centroid_impl.hpp, sensing/tier4_pcl_extensions/package.xml
Signed-off-by: RyuYamamoto <ryu.yamamoto@tier4.jp>
refactoring tier4_pcl_extensions(voxel_grid_nearest_centroid) using range-v3 library.
https://github.com/ericniebler/range-v3
(range-v3 is an external library and needs to be installed by rosdep, but Iother packages can be improved by using this library and can easily replace library if c++20 will be able to use in ROS2)
tier4_pcl_extensions is not used now, so only need to check if build is successful.
If  try in logging simulator, change ValueGridDownsampleFilterComponent to ApproximateDownsampleFilter in localization_launch.launch.launch.xml/util.launch.xml , check localization works fine.
https://github.com/autowarefoundation/autoware.universe/blob/main/launch/tier4_localization_launch/launch/util/util.launch.py#L47
The PR author …
=> fix(tier4_pcl_extensions): refactoring using range-v3 library

perception/radar_tracks_msgs_converter/README.md
Fix README according to [this PR change](https://github.com/autowarefoundation/autoware.universe/pull/1195).
=> fix(radar_tracks_msgs_converter): fix readme

planning/behavior_velocity_planner/config/crosswalk.param.yaml, planning/behavior_velocity_planner/include/scene_module/crosswalk/scene_crosswalk.hpp, planning/behavior_velocity_planner/include/scene_module/crosswalk/scene_walkway.hpp, planning/behavior_velocity_planner/include/scene_module/crosswalk/util.hpp, planning/behavior_velocity_planner/include/scene_module/scene_module_interface.hpp, planning/behavior_velocity_planner/package.xml, planning/behavior_velocity_planner/src/scene_module/crosswalk/debug.cpp, planning/behavior_velocity_planner/src/scene_module/crosswalk/manager.cpp, planning/behavior_velocity_planner/src/scene_module/crosswalk/scene_crosswalk.cpp, planning/behavior_velocity_planner/src/scene_module/crosswalk/scene_walkway.cpp, planning/behavior_velocity_planner/src/scene_module/crosswalk/util.cpp
- Update crosswalk pass judge logic
- New crosswalk module compares TTV(Time-To-Vehicle: the time it takes for a pedestrian to cross a crosswalk and arrive on the Ego path) with TTC(Time-To-Collision: the time it takes for Ego to reach the virtual collision point) to determine whether to stop or pass.
- https://github.com/tier4/autoware_launch/pull/375
Confirmed PASS the scenario test at `prd_jt` with evaluator.
https://evaluation.tier4.jp/evaluation/reports/4b5eba23-125a-5dcb-b6d2-bc3fff5bd09a?project_id=prd_jt …
=> feat(behavior_velocity_planner): update crosswalk pass judge logic

perception/radar_tracks_msgs_converter/include/radar_tracks_msgs_converter/radar_tracks_msgs_converter_node.hpp, perception/radar_tracks_msgs_converter/package.xml
Fix include file because of build failure from [this change](https://github.com/autowarefoundation/autoware.universe/pull/1195).
=> fix(radar_track_converter): fix include file

planning/obstacle_avoidance_planner/src/node.cpp
fix node dying bug in obstacle avoidance planner
=> fix(obstacle_avoidance_planner): fix node dying bug

launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/crosswalk.param.yaml
- update crosswalk param
- https://github.com/autowarefoundation/autoware.universe/pull/1184
=> feat(tier4_planning_launch): update crosswalk param

launch/tier4_perception_launch/config/object_recognition/tracking/multi_object_tracker/data_association_matrix.param.yaml, perception/multi_object_tracker/config/data_association_matrix.param.yaml
change iou param of multi object  tracking
before
https://user-images.githubusercontent.com/8327598/177683021-28d21f30-91a9-48e8-8e0d-73e24370507d.mp4
after
=> feat: change iou param of multi object  tracking

planning/freespace_planner/include/freespace_planner/freespace_planner_node.hpp, planning/freespace_planner/src/freespace_planner/freespace_planner_node.cpp, planning/scenario_selector/include/scenario_selector/scenario_selector_node.hpp, planning/scenario_selector/src/scenario_selector_node/scenario_selector_node.cpp
Signed-off-by: NorahXiong <norah.xiong@autocore.ai>
fix #1272
#1272
Before:
After
=> fix: invalid parameter query between nodes

planning/behavior_velocity_planner/src/scene_module/crosswalk/scene_crosswalk.cpp
=> fix(behavior_velocity_planner): fix calculation for stop distance

launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml, launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_radar_fusion_based_detection.launch.xml, launch/tier4_perception_launch/launch/object_recognition/detection/detection.launch.xml, launch/tier4_perception_launch/launch/object_recognition/detection/lidar_based_detection.launch.xml, launch/tier4_perception_launch/launch/object_recognition/detection/lidar_radar_based_detection.launch.xml, launch/tier4_perception_launch/launch/object_recognition/detection/radar_based_detection.launch.xml, launch/tier4_perception_launch/launch/obstacle_segmentation/ground_segmentation/ground_segmentation.launch.py, launch/tier4_perception_launch/launch/perception.launch.xml
Fixed reviewed points by <https://github.com/autowarefoundation/autoware.universe/pull/1263> <https://github.com/autowarefoundation/autoware.universe/pull/1285>.
=> feat(tier4_perception_launch): add radar fusion launch

launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml, launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_radar_fusion_based_detection.launch.xml, launch/tier4_perception_launch/launch/object_recognition/detection/detection.launch.xml, launch/tier4_perception_launch/launch/object_recognition/detection/lidar_based_detection.launch.xml, launch/tier4_perception_launch/launch/object_recognition/detection/lidar_radar_based_detection.launch.xml, launch/tier4_perception_launch/launch/perception.launch.xml
=> fix(tier4_perception_launch): pass pointcloud_container params to pointcloud_map_filter in detection module

common/tier4_autoware_utils/include/tier4_autoware_utils/trajectory/trajectory.hpp, common/tier4_autoware_utils/test/src/trajectory/test_trajectory.cpp
Since the use can use current  insertPoint funcion only when we know the inserted point, it's not useful when we don't know the inserted point in advance.  To deal with this limitation, I added a new insertPoint function that only takes trajectory and insert point length. This function will be used insertStopPoint function in the future.
Note that insertStopPoint function has many implementations in autoware.universe now.
- [obstacle_cruise_planner](https://github.com/autowarefoundation/autoware.universe/blob/main/planning/obstacle_cruise_planner/src/utils.cpp#L156-L217)
- [behavior_path_planner](https://github.com/autowarefoundation/autoware.universe/blob/main/planning/behavior_path_planner/src/utilities.cpp#L1368-L1408)
- [motion_velocity_smoother](https://github.com/autowarefoundation/a …
=> feat(tier4_autoware_utils): add inset target point function by length

planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/pull_over_module.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_bt_node_interface.hpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp, planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp, planning/behavior_path_planner/src/scene_module/lane_change/lane_change_module.cpp, planning/behavior_path_planner/src/scene_module/pull_out/pull_out_module.cpp, planning/behavior_path_planner/src/scene_module/pull_over/pull_over_module.cpp, planning/behavior_path_planner/src/scene_module/scene_module_bt_node_interface.cpp, planning/behavior_path_planner/src/scene_module/side_shift/side_shift_module.cpp
- `is_waiting_approval` has an initial value of `true` so it is always `true` when in IDLE state due to the [reset](https://github.com/autowarefoundation/autoware.universe/blob/main/planning/behavior_path_planner/src/behavior_tree_manager.cpp#L87-L89)
-  changed the initial value to `false`
-  Added `waitApproval()` in `planWaitingApproval()` to update `is_waiting_approval` to `true` once execution request is success.
(also fixed some typos)
fix https://github.com/autowarefoundation/autoware.universe/pull/1317
psim 
- lane change
- smooth goal connection works.
- `is_waiting_approval` of other modules  are `false` 
- before approval
- after approval
- pull over
- skip smooth goal connection
- `is_waiting_approval` of other modules  are `false` 
- before approval
- after approval
The PR …
=> fix(behavior_path_planner): is_waiting_approval

launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml, launch/tier4_perception_launch/launch/object_recognition/detection/lidar_based_detection.launch.xml, perception/object_merger/launch/object_association_merger.launch.xml
bug fix https://github.com/autowarefoundation/autoware.universe/pull/1294
it is caused by [new arg](https://github.com/autowarefoundation/autoware.universe/pull/1294/files#diff-ccff78fba11731d406265db7d4974958f24546c123d1658b91b908064033a148R5), because the arg pass to lidar_apollo_instance_segmentation
related : 
https://github.com/autowarefoundation/autoware.universe/pull/1301
https://github.com/autowarefoundation/autoware.universe/pull/1336 …
=> feat: update and fix detection launch

common/motion_utils/include/motion_utils/trajectory/trajectory.hpp, common/tier4_autoware_utils/include/tier4_autoware_utils/geometry/geometry.hpp, common/tier4_autoware_utils/include/tier4_autoware_utils/geometry/path_with_lane_id_geometry.hpp, common/tier4_autoware_utils/test/src/geometry/test_geometry.cpp, common/tier4_autoware_utils/test/src/geometry/test_path_with_lane_id_geometry.cpp, planning/behavior_velocity_planner/include/behavior_velocity_planner/node.hpp, planning/behavior_velocity_planner/src/node.cpp, planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/node.hpp, planning/obstacle_avoidance_planner/src/node.cpp, planning/obstacle_stop_planner/include/obstacle_stop_planner/node.hpp, planning/obstacle_stop_planner/src/node.cpp
=> feat(motion_utils): add isDrivingForward function

common/tier4_autoware_utils/include/tier4_autoware_utils/geometry/geometry.hpp, common/tier4_autoware_utils/include/tier4_autoware_utils/geometry/path_with_lane_id_geometry.hpp, common/tier4_autoware_utils/test/src/geometry/test_geometry.cpp, common/tier4_autoware_utils/test/src/geometry/test_path_with_lane_id_geometry.cpp
=> feat(tier4_autoware_utils): add setter/getter of longitudinal velocity

launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.py, launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.xml, planning/behavior_path_planner/include/behavior_path_planner/behavior_path_planner_node.hpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp
Remove unnecessary publisher and subscriber.
=> fix(behavior_path_planner): remove unnecessary publisher and subscriber 

vehicle/vehicle_info_util/include/vehicle_info_util/vehicle_info.hpp, vehicle/vehicle_info_util/src/vehicle_info_util.cpp
correct max_steer_angle unit
No dependency on other packages or repositories.
=> fix(vehicle_info_util): correct max_steer_angle unit

launch/tier4_autoware_api_launch/launch/autoware_api.launch.xml, launch/tier4_autoware_api_launch/launch/include/external_api_adaptor.launch.py
This PR aims for flexible use cases for tier4_autoware_api_launch by adding arguments on whether to launch some modules.
=> feat(tier4_autoware_api_launch): add some arguments

launch/tier4_system_launch/config/ad_service_state_monitor/ad_service_state_monitor.param.yaml, launch/tier4_system_launch/config/ad_service_state_monitor/ad_service_state_monitor.planning_simulation.param.yaml, launch/tier4_system_launch/config/emergency_handler/emergency_handler.param.yaml, launch/tier4_system_launch/config/system_error_monitor/diagnostic_aggregator/control.param.yaml, launch/tier4_system_launch/config/system_error_monitor/diagnostic_aggregator/localization.param.yaml, launch/tier4_system_launch/config/system_error_monitor/diagnostic_aggregator/map.param.yaml, launch/tier4_system_launch/config/system_error_monitor/diagnostic_aggregator/perception.param.yaml, launch/tier4_system_launch/config/system_error_monitor/diagnostic_aggregator/planning.param.yaml, launch/tier4_system_launch/config/system_error_monitor/diagnostic_aggregator/sensing.param.yaml, launch/tier4_system_launch/config/system_error_monitor/diagnostic_aggregator/system.param.yaml, launch/tier4_system_launch/config/system_error_monitor/diagnostic_aggregator/vehicle.param.yaml, launch/tier4_system_launch/config/system_error_monitor/system_error_monitor.param.yaml, launch/tier4_system_launch/config/system_error_monitor/system_error_monitor.planning_simulation.param.yaml, launch/tier4_system_launch/launch/system.launch.xml
Set `tier4_system_launch_param_path` variable and refer to relative path from it for config files
https://github.com/autowarefoundation/autoware.universe/pull/1337
=> feat(tier4_system_launch): declare tier4_system_launch_param_path

planning/motion_velocity_smoother/CMakeLists.txt, planning/motion_velocity_smoother/include/motion_velocity_smoother/motion_velocity_smoother_node.hpp, planning/motion_velocity_smoother/include/motion_velocity_smoother/trajectory_utils.hpp, planning/motion_velocity_smoother/src/motion_velocity_smoother_node.cpp, planning/motion_velocity_smoother/src/smoother/analytical_jerk_constrained_smoother/analytical_jerk_constrained_smoother.cpp, planning/motion_velocity_smoother/src/smoother/smoother_base.cpp, planning/motion_velocity_smoother/src/trajectory_utils.cpp
=> refactor(motion_velocity_smoother): clean up code

common/motion_utils/include/motion_utils/trajectory/trajectory.hpp, control/trajectory_follower/include/trajectory_follower/mpc.hpp, control/trajectory_follower/include/trajectory_follower/mpc_trajectory.hpp, control/trajectory_follower/include/trajectory_follower/mpc_utils.hpp, control/trajectory_follower/src/mpc.cpp, control/trajectory_follower/src/mpc_utils.cpp, planning/behavior_velocity_planner/include/behavior_velocity_planner/node.hpp, planning/behavior_velocity_planner/src/node.cpp, planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/node.hpp, planning/obstacle_avoidance_planner/src/node.cpp, planning/obstacle_cruise_planner/include/obstacle_cruise_planner/node.hpp, planning/obstacle_cruise_planner/src/node.cpp, planning/obstacle_stop_planner/include/obstacle_stop_planner/node.hpp, planning/obstacle_stop_planner/src/node.cpp
The sign of the curvature is calculated by the speed, and when the speed is 0, the previous value is used according to the following.
`m_sign_vx = ref_vx > ep ? 1 : (ref_vx < -ep ? -1 : m_sign_vx);`
This means that if we drive backward and then send a path with a forward speed of 0, `m_sign_vx` will not be updated, but the sign of the steer command will be reversed.
In this PR, it has been modified to determine if it is forwad driving or not by looking at the yaw of the path points.
psim 
https://user-images.githubusercontent.com/39142679/180802251-c1796e4c-1fa2-4da2-b432-a3a403e4546a.mp4
with this PR
https://user-images.githubusercontent.com/39142679/180801504-c51e10e2-a1fb-4e50-bb3a-2a69fff2bd6a.mp4 …
=> fix(trajectory_follower): detect driving direction with yaw

planning/behavior_velocity_planner/config/detection_area.param.yaml, planning/behavior_velocity_planner/include/scene_module/detection_area/scene.hpp, planning/behavior_velocity_planner/src/scene_module/detection_area/manager.cpp, planning/behavior_velocity_planner/src/scene_module/detection_area/scene.cpp
Now, this ego always try to stop at the stop position by re-starting (re-approach) even if the ego is stopped near the planned stop position in the module. On the other hand, if the stopping performance of the vehicle is poor (e.g. it cannot stop for one meter) and once it starts traveling, there is a possibility that the vehicle may over the stop position, in which case there may be a issue for the vehicle to continue stopping on the spot, if the distance between the ego and stop position is closer than threshold.
So, in this PR, I fixed following points.
- add new param `hold_stop_margin_distance` (default: 0.0 [m])
- if the following condisions are satisfied, the ego keep stopping at current position.
condition 1. the ego has stopped
condition 2. the distance between  the ego and stop …
=> feat(behavior_velocity_planner): changeable maximum stop distance

launch/tier4_planning_launch/config/scenario_planning/lane_driving/motion_planning/obstacle_cruise_planner/obstacle_cruise_planner.param.yaml
add missing param in obstacle_cruise_planner
=> fix(obstacle_cruise_planner): add missing param

planning/obstacle_cruise_planner/README.md
=> fix(obstacle_cruise_planner): update doc name

planning/behavior_velocity_planner/virtual-traffic-light-design.md
add document about map format of virtual traffic light
=> docs(behavior_velocity_planner): add map format doc

control/control_performance_analysis/README.md, control/control_performance_analysis/config/control_performance_analysis.param.yaml, control/control_performance_analysis/include/control_performance_analysis/control_performance_analysis_core.hpp, control/control_performance_analysis/include/control_performance_analysis/control_performance_analysis_node.hpp, control/control_performance_analysis/include/control_performance_analysis/control_performance_analysis_utils.hpp, control/control_performance_analysis/package.xml, control/control_performance_analysis/src/control_performance_analysis_core.cpp, control/control_performance_analysis/src/control_performance_analysis_node.cpp
Closes: #1521 
#567 
Tested in 2 different maps and results seem good.
=> fix(control_performance_analysis): fix choosing wrong closest trajectory point

perception/lidar_centerpoint/lib/postprocess/postprocess_kernel.cu
Signed-off-by: WfHit <33973397+WfHit@users.noreply.github.com>
fix #1545
=> fix(lidar_centerpoint): fix function sigmoid() 

planning/behavior_velocity_planner/src/scene_module/occlusion_spot/risk_predictive_braking.cpp
change min insert distance  to avoid spline interpolate wavy
check this is solved with this PR
Note:
use Spherical Linear Interpolation is todo
=> chore(occlusion_spot): change min distance to insert

common/tier4_autoware_utils/include/tier4_autoware_utils/geometry/geometry.hpp
=> fix(tier4_autoware_utils): add maybe_unused

planning/behavior_path_planner/src/scene_module/pull_over/pull_over_module.cpp
Solved a problem where setting a goal after a loop pull_over did not work well. Because current_lanes does not contain goal, goal_arc_length cannot be calculated correctly (it becomes 0) and pull_oevr module is invoked. In addition, arc_length could not be calculated properly in the module processing, this caused bug.
In this PR, when a goal is far away and current_lanes does not contain the goal, the module will not be launched.
psim
https://user-images.githubusercontent.com/39142679/184055846-bd4fff7a-8248-4a3a-8e83-aa540dfef8e3.mp4 …
=> fix(behavior_path_planner): pull_over far goal bug

planning/behavior_velocity_planner/include/utilization/util.hpp, planning/behavior_velocity_planner/src/scene_module/crosswalk/manager.cpp, planning/behavior_velocity_planner/src/utilization/util.cpp
https://github.com/autowarefoundation/autoware.universe/pull/1564
Before this change, the behavior planning module is repeatedly registered and unregistered due to the problem of a algorithm to get lane_id from PathWithLaneId.
To fix this behavior, I fixed the logic to get lane ids from path.
https://user-images.githubusercontent.com/59680180/184799932-985da1e0-e9c8-43e7-ab06-53fe7f325800.mp4
For exmaple, in this movies, the crosswalk module was unregistered once and registered again, then a stopping point was embedded and the vehicle suddenly decelerated.
After this change, registrations/unregistrations of behavior_velocity modules become stable. …
=> fix(behavior_velocity_planner): fix the algorithm to get lane_ids from path

launch/tier4_planning_launch/config/scenario_planning/common/nearest_search.param.yaml, launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.py, launch/tier4_planning_launch/launch/scenario_planning/lane_driving/motion_planning/motion_planning.launch.py, launch/tier4_planning_launch/launch/scenario_planning/scenario_planning.launch.xml
added nearest search param for new algorithm of nearest index search.
https://github.com/autowarefoundation/autoware.universe/issues/1581
=> feat(tier4_planning_launch): add nearest search param

perception/radar_fusion_to_detected_object/package.xml, perception/radar_tracks_msgs_converter/package.xml
=> chore: fix radar package author

common/tier4_state_rviz_plugin/src/autoware_state_panel.cpp, common/tier4_state_rviz_plugin/src/autoware_state_panel.hpp
This reverts commit 57720204fd401a59b5dffd12d5b8958e5ae2a5af.
Fix buttons in the panel are not worked.
=> revert(tier4_state_rviz_plugin): readability-identifier-naming (#1595)

perception/radar_tracks_msgs_converter/src/radar_tracks_msgs_converter_node/radar_tracks_msgs_converter_node.cpp
Fix parameter update in radar_tracks_msgs_converter.
=> fix(radar_tracks_msgs_converter): fix param update

common/tier4_traffic_light_rviz_plugin/src/traffic_light_publish_panel.cpp, common/tier4_traffic_light_rviz_plugin/src/traffic_light_publish_panel.hpp
Signed-off-by: h-ohta <hiroki.ota@tier4.jp>
- apply clang-tidy
=> refactor(tier4_traffic_light_rviz_plugin): apply clang-tidy

common/polar_grid/src/polar_grid_display.cpp, common/polar_grid/src/polar_grid_display.hpp
Signed-off-by: h-ohta <hiroki.ota@tier4.jp>
apply clang-tidy
=> refactor(polar_grid): apply clang-tidy

common/tier4_api_utils/include/tier4_api_utils/rclcpp/client.hpp
=> refactor(tier4_api_utils): apply clang-tidy

common/goal_distance_calculator/package.xml
=> chore: change maintainer's email

perception/lidar_apollo_instance_segmentation/package.xml
change e-mail address in lidar_apollo_instance_segmentation
=> chore(lidar_apollo_instance_segmentation): update package.xml

launch/tier4_localization_launch/package.xml, localization/ekf_localizer/package.xml, localization/gyro_odometer/package.xml, localization/initial_pose_button_panel/package.xml, localization/localization_error_monitor/package.xml, localization/ndt/package.xml, localization/ndt_pcl_modified/package.xml, localization/ndt_scan_matcher/package.xml, localization/pose2twist/package.xml, localization/pose_initializer/package.xml, localization/stop_filter/package.xml, localization/twist2accel/package.xml, sensing/geo_pos_conv/package.xml, sensing/gnss_poser/package.xml, sensing/imu_corrector/package.xml
modify maintainer and e-mail address
=> chore(localization packages, etc): modify maintainer and e-mail address

common/tvm_utility/design/tvm-utility-design.md
https://github.com/autowarefoundation/autoware/discussions/226
-> https://github.com/autowarefoundation/autoware_core_universe_prototype/discussions/226
-> https://github.com/autowarefoundation/autoware/discussions/2557
=> docs(tvm_utility): fix broken link

common/motion_utils/package.xml
Update author and maintainer and their email address. 
=> chore(motion_utils): update package.xml

control/lane_departure_checker/include/lane_departure_checker/lane_departure_checker.hpp, control/lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker.cpp, launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/pull_over/pull_over.param.yaml, planning/behavior_path_planner/config/pull_over/pull_over.param.yaml, planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/util.hpp, planning/behavior_path_planner/src/scene_module/pull_over/pull_over_module.cpp, planning/behavior_path_planner/src/scene_module/pull_over/util.cpp
fix pull over shift parking
- distorted path near the goal
- It occurs when resampliStop embedding goal points. 
- (previously, the goal point was removed by resampling, but this is no longer a problem.ng when the path points are close)
- modify lane id in shift
- resample before path shift.
- less likely to [fail path shift](https://github.com/autowarefoundation/autoware.universe/blob/57720204fd401a59b5dffd12d5b8958e5ae2a5af/planning/behavior_path_planner/src/scene_module/utils/path_shifter.cpp#L88-L91)
- check lane_departure for each shit path. 
distorted path near the goal
before
after 
https://user-images.githubusercontent.com/39142679/185905501-358d41ed-168d-4817-a5b3-f7a93559a112.mp4
this PR depends on https://github.com/autowarefoundation/autoware.universe/pull/1633
psim 
The PR …
=> fix(behavior_path_planner): pull_over shift parking

planning/freespace_planning_algorithms/package.xml
As in the title, with @aohsato's consent.
=> chore(freespace-planning-algorithm): change maintainer

control/lane_departure_checker/include/lane_departure_checker/lane_departure_checker.hpp, control/lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker.cpp, control/lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker_node.cpp
issue
https://github.com/autowarefoundation/autoware.universe/issues/1581
depends on
https://github.com/tier4/autoware_launch/pull/442
https://github.com/autowarefoundation/autoware.universe/pull/1590
=> fix(lane_departure_checker): use common nearest ego search

launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/behavior_path_planner.param.yaml, planning/behavior_path_planner/config/behavior_path_planner.param.yaml, planning/behavior_path_planner/include/behavior_path_planner/parameters.hpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp
Resampled output path in behavior path planner so that users can modify interval of the path.
=> feat(behavior_path_planner): resample output path

planning/behavior_velocity_planner/include/scene_module/blind_spot/scene.hpp, planning/behavior_velocity_planner/src/scene_module/blind_spot/scene.cpp
verify behavior is same as before
note: pass judge insertion can add more complexity because it needs to handle stop line index if pass judge is inserted.
```
/* insert judge point */
// need to remove const because pass judge idx will be changed by insert stop point
int pass_judge_idx_ip = std::min(
static_cast<int>(path_ip.points.size()) - 1, std::max(stop_idx_ip - pass_judge_idx_dist, 0));
if (has_prior_stopline || stop_idx_ip == pass_judge_idx_ip) {
*pass_judge_line_idx = *stop_line_idx;
} else {
bool is_pass_judge_point_inserted = true;
//! insertPoint check if there is no duplicated point
*pass_judge_line_idx =
insertPoint(pass_judge_idx_ip, path_ip, path, is_pass_judge_point_inserted);
if (is_pass_judge_point_inserted)
++(*stop_line_idx);  // stop index is incremented by judge line …
```
=> refactor(blindspot): replace pass judge with arc length comparison

launch/tier4_planning_launch/config/scenario_planning/lane_driving/motion_planning/surround_obstacle_checker/surround_obstacle_checker.param.yaml, planning/surround_obstacle_checker/README.md, planning/surround_obstacle_checker/config/surround_obstacle_checker.param.yaml, planning/surround_obstacle_checker/include/surround_obstacle_checker/debug_marker.hpp, planning/surround_obstacle_checker/include/surround_obstacle_checker/node.hpp, planning/surround_obstacle_checker/src/debug_marker.cpp, planning/surround_obstacle_checker/src/node.cpp
Signed-off-by: Mehmet Dogru <42mehmetdogru42@gmail.com>
closes https://github.com/autowarefoundation/autoware.universe/issues/1574
=> feat(surround_obstacle_checker): add vehicle footprint with offset

perception/lidar_centerpoint/launch/lidar_centerpoint.launch.xml
Add score threshold paramter to center point.
=> feat(lidar_centerpoint): add score threshold parameter to center point

planning/motion_velocity_smoother/include/motion_velocity_smoother/trajectory_utils.hpp, planning/motion_velocity_smoother/src/motion_velocity_smoother_node.cpp, planning/motion_velocity_smoother/src/trajectory_utils.cpp
Delete unnecessary functions and use motion utils. Also, delete push_back functions to improve the performance.
=> feat(motion_velocity_smoother): use utility functions in autoware

.github/workflows/build-and-test-differential.yaml
Please refer to https://github.com/autowarefoundation/autoware-github-actions/pull/178.
I used this action and option.
https://github.com/tj-actions/changed-files#outputs
=> ci(clang-tidy): analyze only modified files

NOTICE
I updated `NOTICE` for AutoCore and Leo Drive since it seems they started using the format of `The Autoware Contributors`. (For example in https://github.com/autowarefoundation/autoware.universe/pull/1137.)
Related: https://github.com/autowarefoundation/autoware.ai/issues/2425
The format is from https://github.com/apache/solr/blob/0ba432371064586a900ae1e66b483f0685d4ef7f/NOTICE.txt.
@Sharrrrk @xmfcx Could you check if your license notations are appropriate? I've checked some of your files, but I'm not confident. …
=> chore: update NOTICE

launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/pull_over/pull_over.param.yaml, planning/behavior_path_planner/README.md, planning/behavior_path_planner/config/pull_over/pull_over.param.yaml, planning/behavior_path_planner/src/behavior_path_planner_node.cpp
If pull_over is attempted from driving at high speed (ex: 40 km), the stop is not planned until `request_length`(100m) closer to the start point and the maximum deceleration is exceeded, so the parking path is not adopted at the target position.
Therefore, in this PR, `request_length` and `maximum_deceleration` are increased.
launcher: https://github.com/tier4/autoware_launch/pull/468
before
https://user-images.githubusercontent.com/39142679/188547895-c83213ec-8904-4a91-a97e-bfa61c287353.mp4
(hz is falling down is another issue. I will fix it in another PR.)
after
https://user-images.githubusercontent.com/39142679/188547993-ba516c20-d236-411b-b9b3-8b8fc475146a.mp4 …
=> fix(behavior_path_planner): fix pull_over request_length and maximum_deceleration

launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/pull_over/pull_over.param.yaml, planning/behavior_path_planner/README.md, planning/behavior_path_planner/config/pull_over/pull_over.param.yaml, planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/pull_over_module.hpp, planning/behavior_path_planner/include/behavior_path_planner/utilities.hpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp, planning/behavior_path_planner/src/scene_module/pull_over/pull_over_module.cpp, planning/behavior_path_planner/src/utilities.cpp
In https://github.com/autowarefoundation/autoware.universe/pull/1777, `goal_to_object_margin`  is no longer used.
In this PR, use `goal_to_object_margin` again to ensure some longitudinal distance between the goal and objects.
https://github.com/autowarefoundation/autoware.universe/pull/1777,
psim
`goal_to_object_margin` : 0.0
the distance between ego to object is 1.0(same to `object_recognition_collision_check_margin`)
`goal_to_object_margin` :2.0 (default)
`goal_to_object_margin` :5.0
[contribution …
=> feat(behavior_path_planner): check goal to objects logitudinal distance for pull_over

system/velodyne_monitor/Readme.md
- add known limits for velodyne_monitor
=> docs(velodyne_monitor): add known limits

common/motion_utils/include/motion_utils/motion_utils.hpp
Add interpolation header file to the motion_utils.hpp
=> feat(motion_utils): add interpolation header file

control/shift_decider/include/shift_decider/shift_decider.hpp, control/shift_decider/launch/shift_decider.launch.xml, control/shift_decider/package.xml, control/shift_decider/src/shift_decider.cpp, launch/tier4_control_launch/launch/control.launch.py
Signed-off-by: lilyildiz <y.yzk61@gmail.com>
Closes  #1813 
=> feat(shift_decider): put the gear in park when vehicle reaches the goal

launch/tier4_autoware_api_launch/package.xml, launch/tier4_localization_launch/package.xml
=> fix: add adapi dependency

common/motion_utils/package.xml, planning/behavior_path_planner/package.xml, planning/behavior_velocity_planner/package.xml, vehicle/vehicle_info_util/package.xml
=> chore: add code owners

planning/behavior_path_planner/package.xml
=> chore(behavior_path_planner): add code owner

launch/tier4_planning_launch/package.xml
Add maintainers of each planning module to tier4_planning_launch.
=> chore(tier4_planning_launch): add maintainers

launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/pull_over/pull_over.param.yaml, planning/behavior_path_planner/CMakeLists.txt, planning/behavior_path_planner/config/pull_over/pull_over.param.yaml, planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/geometric_pull_over.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/pull_over_module.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/pull_over_parameters.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/pull_over_path.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/pull_over_planner_base.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/shift_pull_over.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/util.hpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp, planning/behavior_path_planner/src/scene_module/pull_over/geometric_pull_over.cpp, planning/behavior_path_planner/src/scene_module/pull_over/pull_over_module.cpp, planning/behavior_path_planner/src/scene_module/pull_over/shift_pull_over.cpp, planning/behavior_path_planner/src/scene_module/pull_over/util.cpp, planning/behavior_path_planner/src/scene_module/utils/geometric_parallel_parking.cpp
- Add pull_over_base_planner class.
- Each planner (shift_pull_over, geometric_pull_over) inherits this base class
- some refactors
launcher: https://github.com/tier4/autoware_launch/pull/491
psim
=> feat(behavior_path_planner): add pull_over base class

common/tier4_planning_rviz_plugin/include/path/display.hpp, common/tier4_planning_rviz_plugin/src/path/display.cpp
=> refactor(tier4_planning_rviz_plugin): apply clang-tidy for path

launch/tier4_planning_launch/package.xml, planning/behavior_velocity_planner/package.xml
Signed-off-by: Tomohito Ando <tomohito.ando@tier4.jp>
Added code maintainer for run out module.
=> chore(behavior_velocity): add maintainer for run out module

common/kalman_filter/package.xml
=> fix(kalman_filter): add more maintainers

planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_out/pull_out_module.hpp, planning/behavior_path_planner/src/scene_module/pull_out/geometric_pull_out.cpp, planning/behavior_path_planner/src/scene_module/pull_out/pull_out_module.cpp, planning/behavior_path_planner/src/scene_module/pull_out/shift_pull_out.cpp, planning/behavior_path_planner/src/scene_module/pull_over/geometric_pull_over.cpp, planning/behavior_path_planner/src/scene_module/pull_over/shift_pull_over.cpp, planning/behavior_path_planner/src/utilities.cpp, planning/route_handler/include/route_handler/route_handler.hpp, planning/route_handler/src/route_handler.cpp
Fixed a problem that prevented pull_out on lane boundaries.
- Fixed back_finished decision
- Fixed previous lane of `getExtendedCurrentLanes` 
- Use this function also for pull_out  and pull_over
[TIERIV INTERNAL LINK ticket](https://tier4.atlassian.net/browse/T4PB-21563) 
psim 
pull_over -> pull_out works well
https://user-images.githubusercontent.com/39142679/193543633-08cc9214-016a-454d-a768-05778f0dfa0c.mp4
shift pull out works well on the lane boundary  …
=> fix(behavior_path_planner): pull out on lane boundary

common/motion_utils/include/motion_utils/resample/resample.hpp, common/motion_utils/src/resample/resample.cpp, planning/behavior_path_planner/src/turn_signal_decider.cpp
fix indent of comment
rename resamplePath to resamplePoseVector
=> refactor(motion_utils): resample

control/lane_departure_checker/include/lane_departure_checker/lane_departure_checker.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_out/pull_out_module.hpp, planning/behavior_path_planner/src/scene_module/pull_out/pull_out_module.cpp, planning/behavior_path_planner/src/scene_module/pull_out/shift_pull_out.cpp
- not run pull out if ego is out of lane
- fix shift  pull out lane departure check.
- previously used current pose to end pose even if backward driving is need, so changed to using pull out start pose (= backward driving end pose) instead of current_pose
these changes fixed infinity backward driving behavior when putting ego out of lane.
[TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/T4PB-21564)
psim 
if ego is out of lane, do not run pull_over but just lane_following.
[contribution …
=> fix(behavior_path_planner): not run pull out if out of lane

common/tier4_autoware_utils/include/tier4_autoware_utils/geometry/boost_polygon_utils.hpp, common/tier4_autoware_utils/src/geometry/boost_polygon_utils.cpp
Add polygon util function to tier4_autoware_utils
=> feat(tier4_autoware_utils): add polygon util function

launch/tier4_planning_launch/config/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/pull_over/pull_over.param.yaml, planning/behavior_path_planner/README.md, planning/behavior_path_planner/config/pull_over/pull_over.param.yaml, planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/pull_over_module.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/pull_over_parameters.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/util.hpp, planning/behavior_path_planner/include/behavior_path_planner/utilities.hpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp, planning/behavior_path_planner/src/scene_module/pull_over/pull_over_module.cpp, planning/behavior_path_planner/src/scene_module/pull_over/shift_pull_over.cpp, planning/behavior_path_planner/src/scene_module/pull_over/util.cpp, planning/behavior_path_planner/src/utilities.cpp
Add lateral goal search to pull_over.
- If objects are present near the shoulder of the road, the goal is searched laterally.
- Visualize goal candidates(green pose) and their priority(white text)
with objects
https://user-images.githubusercontent.com/39142679/194519608-0cffeb8f-1112-4335-924d-3d0fda0b87e7.mp4
with not recognized object(using occupancy grid )
https://user-images.githubusercontent.com/39142679/194518588-c94a803d-9e21-47e8-98d7-02b3ea88113e.mp4
check with big wall
https://user-images.githubusercontent.com/39142679/194517090-67c6a880-6e52-4c7f-ba5c-d5006ee90dda.mp4
[TIERIV INTERNAL LINK](https://tier4.atlassian.net/browse/T4PB-21907)
https://github.com/tier4/autoware_launch/pull/507 …
=> feat(behavior_path_planner): pull_over lateral goal search

common/tier4_planning_rviz_plugin/src/tools/jsk_overlay_utils.cpp, common/tier4_planning_rviz_plugin/src/tools/jsk_overlay_utils.hpp, common/tier4_vehicle_rviz_plugin/src/tools/jsk_overlay_utils.cpp, common/tier4_vehicle_rviz_plugin/src/tools/jsk_overlay_utils.hpp
According to https://github.com/jsk-ros-pkg/jsk_visualization/blob/7d31711959cfe88eaef8fc8a426accaf6dd02621/jsk_rviz_plugins/src/overlay_utils.cpp#L3, I fixed the license of jsk's rviz plugins code. (BSD 2.0 -> BSD)
=> fix(tier4_planning/vehicle_rviz_plugin): fixed license

launch/tier4_control_launch/launch/control.launch.py
- sync
https://github.com/tier4/autoware_launch/pull/514
=> feat(control_launch): add longitudinal controller mode

planning/behavior_path_planner/CMakeLists.txt, planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/goal_searcher.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/goal_searcher_base.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/pull_over_module.hpp, planning/behavior_path_planner/src/scene_module/pull_over/goal_searcher.cpp, planning/behavior_path_planner/src/scene_module/pull_over/pull_over_module.cpp, planning/behavior_path_planner/src/scene_module/pull_over/util.cpp
Add a goal searcher interface, and make the current goal search the class which inherits the interface.
[TIERIV INTERNAL LINK](https://tier4.atlassian.net/browse/T4PB-21976)
psim 
https://user-images.githubusercontent.com/39142679/195764529-355650d3-877a-45ae-90b0-d94175fa8e5e.mp4
https://user-images.githubusercontent.com/39142679/195764543-a6465a9e-0a0d-4767-b1a6-fd4ec775fa33.mp4
TIERIV internal scenario test
pull over 23/23 passed
https://evaluation.tier4.jp/evaluation/reports/9942d986-e85f-5454-8f11-f68a1d6c2dfd/tests/34fe9d4e-7a58-5238-bed3-5342df176f61?project_id=prd_jt …
=> feat(behavior_path_planner): add pull over goal searcher interface

planning/behavior_path_planner/behavior_path_planner_turn_signal-design.md
Add parameter descriptions to the turn signal decider document. 
=> feat(behavior_path_planner): update turn signal document

common/osqp_interface/package.xml
add maintainers in osqp_interface
=> chore(osqp_interface): add maintainers

control/trajectory_follower/include/trajectory_follower/mpc.hpp, control/trajectory_follower/src/mpc.cpp, control/trajectory_follower_nodes/test/test_controller_node.cpp, control/trajectory_follower_nodes/test/test_lateral_controller_node.cpp, control/trajectory_follower_nodes/test/test_longitudinal_controller_node.cpp, planning/behavior_path_planner/README.md, planning/behavior_path_planner/src/scene_module/utils/geometric_parallel_parking.cpp, planning/behavior_velocity_planner/src/scene_module/intersection/util.cpp, planning/behavior_velocity_planner/src/scene_module/occlusion_spot/grid_utils.cpp, planning/obstacle_avoidance_planner/README.md, planning/planning_debug_tools/Readme.md
=> chore: fix typos

perception/ground_segmentation/package.xml, sensing/pointcloud_preprocessor/package.xml
=> chore: add maintainer in ground_segmentation and pointcloud_preprocessor

perception/multi_object_tracker/src/multi_object_tracker_core.cpp
With the introduction of Detection By Tracker, special codes for tracking are no longer necessary.
With the improvement of Detection's performance, this code has been removed because this happen often bad behavior.
=> feat(multi object tracking): remove specific tracking

launch/tier4_autoware_api_launch/launch/autoware_api.launch.xml
This package is not suitable for inclusion in autowarefoundation because it is a package for interim support of TIER IV's products.
=> feat(autoware_api_launch): delete image base64 converter launch

system/system_monitor/README.md, system/system_monitor/docs/hdd_reader.md, system/system_monitor/docs/ros_parameters.md, system/system_monitor/docs/topics_cpu_monitor.md, system/system_monitor/docs/topics_hdd_monitor.md, system/system_monitor/docs/topics_voltage_monitor.md, system/system_monitor/docs/traffic_reader.md, system/system_monitor/include/system_monitor/gpu_monitor/tegra_gpu_monitor.hpp, system/system_monitor/include/system_monitor/voltage_monitor/voltage_monitor.hpp, system/system_monitor/src/net_monitor/net_monitor.cpp, system/system_monitor/src/net_monitor/nl80211.cpp, system/system_monitor/src/voltage_monitor/voltage_monitor.cpp
Fixed several spell-check errors.
=> chore(system_monitor): fix typos

control/trajectory_follower/package.xml
Latest evaluator outputs following build error:
```
In file included from /home/autoware/autoware.proj/src/autoware/universe/control/trajectory_follower/src/pid_longitudinal_controller.cpp:15:
/home/autoware/autoware.proj/src/autoware/universe/control/trajectory_follower/include/trajectory_follower/pid_longitudinal_controller.hpp:18:10: fatal error: diagnostic_updater/diagnostic_updater.hpp: No such file or directory
18 | #include "diagnostic_updater/diagnostic_updater.hpp"
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/longitudinal_controller_lib.dir/build.make:63: CMakeFiles/longitudinal_controller_lib.dir/src/pid_longitudinal_controller.cpp.o] Error 1
make[1]: *** …
```
=> fix(trajectory_follower): add diagnostics dependency

planning/behavior_path_planner/src/scene_module/utils/geometric_parallel_parking.cpp
Fix geometric parallel parking lane ids.
Currently, using only goal closest road/shoulder lanes, but this is not enough to deal with a lane boundary.
(This produces insufficient drivable area and distorts the trajectory)
In this PR, changed to using all current road lanes and pull over target shoulder lanes. …
=> fix(behavior_path_planner): geometric parking lane id

planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/geometric_pull_over.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/goal_searcher.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/goal_searcher_base.hpp, planning/behavior_path_planner/src/scene_module/pull_over/geometric_pull_over.cpp, planning/behavior_path_planner/src/scene_module/pull_over/goal_searcher.cpp, planning/behavior_path_planner/src/scene_module/pull_over/pull_over_module.cpp
- Check if goal candidates are in the lanes.
- Check lane departure also for geometric parallel parking.
psim
green arrows are goal candidates. they all are in the lanes.
Check lane departure also for geometric parallel parking.
before
after
=> fix(behavior_path_planner): check if goal candidates are in the lanes

perception/map_based_prediction/README.md, perception/map_based_prediction/config/map_based_prediction.param.yaml, perception/map_based_prediction/include/map_based_prediction/map_based_prediction_node.hpp, perception/map_based_prediction/include/map_based_prediction/path_generator.hpp, perception/map_based_prediction/src/map_based_prediction_node.cpp, perception/map_based_prediction/src/path_generator.cpp
Close https://github.com/autowarefoundation/autoware.universe/issues/1487
=> fix(map_based_prediction): add param in use path prediction for crosswalk users

system/default_ad_api/document/motion.drawio.svg, system/default_ad_api/src/motion.cpp, system/default_ad_api/src/motion.hpp
Fix a bug in motion state that prevented vehicle from starting.
=> fix(default_ad_api): change motion state transition

system/default_ad_api/launch/default_ad_api.launch.py
Temporary disable motion API. https://github.com/autowarefoundation/autoware.universe/pull/2181
=> fix(default_ad_api): disable motion api temporary

control/vehicle_cmd_gate/src/vehicle_cmd_gate.cpp, system/default_ad_api/launch/default_ad_api.launch.py
Fix for https://github.com/autowarefoundation/autoware.universe/pull/2189
=> fix(vehicle_cmd_gate): fix pause control command

.github/sync-files.yaml
Related:
- https://github.com/autowarefoundation/autoware_common/pull/125
- https://github.com/autowarefoundation/autoware_common/pull/126
=> ci(sync-files): sync clang-tidy-pr-comments workflows

planning/behavior_velocity_planner/traffic-light-design.md
=> docs(behavior_velocity.traffic): fix typo

launch/tier4_control_launch/package.xml, launch/tier4_planning_launch/package.xml
add missing dependency in tier4_planning/control_launch
=> feat(tier4_planning/control_launch): add missing dependency

localization/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp
I made a small mistake in the previous PR. https://github.com/autowarefoundation/autoware.universe/pull/2199
=> fix(ndt_scan_matcher): fix ndt_ptr in align_using_monte_carlo

map/map_loader/package.xml
=> chore(map_loader): add maintainer

planning/mission_planner/src/mission_planner/mission_planner.cpp, system/default_ad_api/src/utils/route_conversion.cpp
Apply https://github.com/autowarefoundation/autoware_msgs/pull/41
=> feat: apply renaming of vector map route message

launch/tier4_simulator_launch/launch/simulator.launch.xml
Fix https://github.com/tier4/autoware.universe/issues/182
=> fix(tier4_simulator_launch): fix path

planning/behavior_path_planner/src/scene_module/pull_out/pull_out_module.cpp, planning/behavior_path_planner/src/scene_module/pull_out/util.cpp
=> feat(behavior_path_planner): delete unnecessary procedure

sensing/gnss_poser/README.md
Signed-off-by: melike tanrikulu <melike@leodrive.ai>
This PR update the README.md  according to gnss_poser package update
Related PR: https://github.com/autowarefoundation/autoware.universe/pull/1230
=> refactor(gnss_poser): update README change navpvt to autoware_sensing_msgs

.github/workflows/update-codeowners-from-packages.yaml
See https://github.com/autowarefoundation/autoware-github-actions/pull/194.
=> ci(update-codeowners-from-packages): add global codeowners

system/default_ad_api/src/interface.cpp
Release the default adapi v1.0.0.
=> feat(default_ad_api): interface version 1.0.0

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_utils.cpp
Add utils header in avoidance utils
=> feat(behavior_path_planner): add missing header

system/default_ad_api/test/node/interface_version.py
=> fix(default_ad_api): fix test

common/autoware_ad_api_specs/package.xml, common/component_interface_specs/package.xml, common/component_interface_utils/package.xml, common/path_distance_calculator/package.xml, common/tier4_api_utils/package.xml, common/tier4_datetime_rviz_plugin/package.xml, common/tier4_localization_rviz_plugin/package.xml, launch/tier4_autoware_api_launch/package.xml, system/component_state_monitor/package.xml, system/default_ad_api/package.xml, system/default_ad_api_helpers/ad_api_adaptors/package.xml, system/default_ad_api_helpers/automatic_pose_initializer/package.xml
=> chore: add api maintainers

planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/lane_change_module.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/util.hpp, planning/behavior_path_planner/src/scene_module/lane_change/lane_change_module.cpp, planning/behavior_path_planner/src/scene_module/lane_change/util.cpp
To simplify the code in the `LaneChangeModule`, and make it more expressive, the code need to be refactor.
Requires https://github.com/autowarefoundation/autoware.universe/pull/2287 to be merged first.
=> refactor(behavior_path_planner): refactor lane change main functions

perception/traffic_light_ssd_fine_detector/README.md
[Issue #1087](https://github.com/autowarefoundation/autoware.universe/issues/1087)
* Update training information in traffic_light_ssd_fine_detector/README.md
=> docs: update traffic light ssd README.md

launch/tier4_map_launch/package.xml
=> chore(tier4_map_launch): add maintainers

.github/sync-files.yaml, .github/workflows/build-and-test-differential-self-hosted.yaml, .github/workflows/build-and-test-differential.yaml
Reverts autowarefoundation/autoware.universe#1669.
Resolves https://github.com/autowarefoundation/autoware.universe/issues/2409.
=> revert: revert "ci(build-and-test-differential): disable no-cuda test"

common/tier4_state_rviz_plugin/package.xml
Add maintainer of tier4_state_rviz_plugin.
=> chore(tier4_state_rviz_plugin): add maintainer

simulator/simple_planning_simulator/package.xml
Added me as a maintainer of simple_planning_simulator
=> chore(simple_planning_simulator): add maintainer 

perception/traffic_light_classifier/README.md
[Issue #1087](https://github.com/autowarefoundation/autoware.universe/issues/1087)
* Update training data information in traffic_light_classifier/README.md
=> docs: update training data for traffic light

localization/stop_filter/src/stop_filter.cpp, localization/twist2accel/src/twist2accel.cpp
=> fix: remove unnecessary DEBUG_INFO declarations

planning/behavior_velocity_planner/src/scene_module/crosswalk/scene_walkway.cpp
=> feat(behavior_velocity_planner): clean walkway module

planning/behavior_path_planner/include/behavior_path_planner/behavior_path_planner_node.hpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp, planning/behavior_path_planner/src/utilities.cpp
Remove unnecessary code for drivable area and also clean codes for turn signal decider
Related PR (Drivable area change)
https://github.com/autowarefoundation/autoware.universe/pull/2472
=> feat(behavior_path_planner): remove unnecessary code and clean turn signal decider

simulator/simple_planning_simulator/src/simple_planning_simulator/vehicle_model/sim_model_delay_steer_acc_geared.cpp, simulator/simple_planning_simulator/src/simple_planning_simulator/vehicle_model/sim_model_ideal_steer_acc_geared.cpp
make a function to remove duplicated code.
Tests are performed with go/stop behavior in the simple planning simulator.
=> refactor(simple_planning_simulator): make function for duplicated code

planning/behavior_path_planner/src/utilities.cpp
Currently, the goal extension is not working properly in autoware.universe due to the wrong overlapping check when generating a drivable area. In this PR I fixed the problem and checked it working well with this modification.
- Before PR
- After PR …
=> fix(behavior_path_planner): fix goal lanelet extension

perception/map_based_prediction/include/map_based_prediction/map_based_prediction_node.hpp, perception/map_based_prediction/src/map_based_prediction_node.cpp, perception/map_based_prediction/src/path_generator.cpp
Currently, map based prediction returns empty predicted paths when it does not have enough length of reference path. This causes the program unstable when using `obstacle_cruise_planner`, so I fixed the problem in this PR. More specifically, `map_based_prediction` returns non-empty paths even when it does not have appropriate reference paths.
- Before PR
https://user-images.githubusercontent.com/43805014/208396648-680380bc-4964-4cab-b7cc-dfc8be1bdec4.mp4
- After PR
https://user-images.githubusercontent.com/43805014/208397752-2e83b29e-cd69-4ec5-b6de-24b795e9824d.mp4
PSim …
=> fix(map_based_prediction): return non-empty predicted path

perception/map_based_prediction/package.xml
Add maintainers to the map based prediction package
=> feat(map_based_prediction): add maintainers

launch/tier4_control_launch/config/operation_mode_transition_manager/operation_mode_transition_manager.param.yaml
Add parameter to operation_mode_transition_manager.param.yaml
https://github.com/autowarefoundation/autoware.universe/pull/2523
=> fix(tier4_control_launch): add parameter about nearest search

.github/CODEOWNERS, perception/lidar_centerpoint/package.xml
Signed-off-by: Kenzo Lobos-Tsunekawa <kenzo.lobos@tier4.jp>
=> chore(lidar_centerpoint): update maintainer

system/component_state_monitor/config/topics.yaml
=> fix(component_state_monitor): fix lanelet route package

launch/tier4_map_launch/CMakeLists.txt, launch/tier4_map_launch/README.md, launch/tier4_map_launch/config/pointcloud_map_loader.param.yaml, launch/tier4_map_launch/launch/map.launch.py, launch/tier4_map_launch/launch/map.launch.xml
Move config to autoware_launch.
Two PRs should be merged at the same time.
- https://github.com/autowarefoundation/autoware.universe/pull/2538
- https://github.com/autowarefoundation/autoware_launch/pull/128
https://github.com/autowarefoundation/autoware_launch/issues/66
Launch logging_simulator.launch.xml and verified that the lanelet and pointcloud maps are displayed on RViz. …
=> feat(tier4_map_launch): remove configs and move to autoware_launch

common/motion_utils/include/motion_utils/trajectory/trajectory.hpp, planning/behavior_path_planner/README.md, planning/behavior_path_planner/config/pull_out/pull_out.param.yaml, planning/behavior_path_planner/config/pull_over/pull_over.param.yaml, planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_out/pull_out_module.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_out/pull_out_parameters.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_out/shift_pull_out.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/goal_searcher.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/goal_searcher_base.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/pull_over_module.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/pull_over_parameters.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/pull_over_planner_base.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/shift_pull_over.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/util.hpp, planning/behavior_path_planner/include/behavior_path_planner/utilities.hpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp, planning/behavior_path_planner/src/scene_module/pull_out/pull_out_module.cpp, planning/behavior_path_planner/src/scene_module/pull_out/shift_pull_out.cpp, planning/behavior_path_planner/src/scene_module/pull_over/goal_searcher.cpp, planning/behavior_path_planner/src/scene_module/pull_over/pull_over_module.cpp, planning/behavior_path_planner/src/scene_module/pull_over/shift_pull_over.cpp, planning/behavior_path_planner/src/scene_module/pull_over/util.cpp, planning/behavior_path_planner/src/scene_module/utils/geometric_parallel_parking.cpp, planning/behavior_path_planner/src/utilities.cpp, planning/planning_debug_tools/include/planning_debug_tools/trajectory_analyzer.hpp, planning/planning_debug_tools/include/planning_debug_tools/util.hpp
https://user-images.githubusercontent.com/39142679/203253194-bd027d2b-d2cb-46a8-b036-0bb2fc932a94.mp4
https://user-images.githubusercontent.com/39142679/203253626-04b66217-dd4e-460b-b86b-2c5393c104ce.MOV
[tier4 internal link](https://tier4.atlassian.net/browse/T4PB-23507)
[tier4 internal test](https://evaluation.tier4.jp/evaluation/reports/6f16cf2b-c1bb-51dc-8e6b-1d350efe5df6?project_id=prd_jt) 820/825 …
=> feat(behavior_path_planner): plan shift pull over/out on curve

localization/localization_error_monitor/CMakeLists.txt
=> fix(localization_error_monitor): fix CMakeLists.txt

control/operation_mode_transition_manager/src/state.cpp, control/operation_mode_transition_manager/src/util.hpp
Set true for all engage-check conditions when `check_engage_condition` is false.
=> refactor(oepration__mode_transition_manager): improve visibility for debug topic

control/pure_pursuit/include/pure_pursuit/pure_pursuit_lateral_controller.hpp, control/pure_pursuit/src/pure_pursuit/pure_pursuit_lateral_controller.cpp, control/trajectory_follower/include/trajectory_follower/input_data.hpp, control/trajectory_follower/include/trajectory_follower/lateral_controller_base.hpp, control/trajectory_follower/include/trajectory_follower/longitudinal_controller_base.hpp, control/trajectory_follower/include/trajectory_follower/mpc_lateral_controller.hpp, control/trajectory_follower/include/trajectory_follower/pid_longitudinal_controller.hpp, control/trajectory_follower/include/trajectory_follower/sync_data.hpp, control/trajectory_follower/src/mpc_lateral_controller.cpp, control/trajectory_follower/src/pid_longitudinal_controller.cpp, control/trajectory_follower_nodes/include/trajectory_follower_nodes/controller_node.hpp, control/trajectory_follower_nodes/package.xml, control/trajectory_follower_nodes/src/controller_node.cpp, control/trajectory_follower_nodes/test/test_controller_node.cpp
What I refactored is mainly as follows.
- refactor the main function of controller_node.cpp
- create input data -> check if the controller is ready -> initialize if required -> run -> sync
https://github.com/autowarefoundation/autoware.universe/blob/e72ab74718492259ad6f635f73fa83e32d839391/control/trajectory_follower_nodes/src/controller_node.cpp#L187-L210
- We can initialize the controller as we want depending on the controller's algorithm at that time.
- make each variable in input_data not a pointer so that lat/lon controllers do not need to check each variable in set_input is nullptr or not
- make isReady function in lat/lon controllers so that run() function will not return boost::none;
- Previously, in run() function, we check …
=> refactor(trajectory_follower_nodes): refactor the controller framework

planning/mission_planner/src/lanelet2_plugins/default_planner.cpp, planning/mission_planner/src/lanelet2_plugins/default_planner.hpp
fix initialize function of mission planner
=> fix(mission_planner): fix initialize function

planning/behavior_velocity_planner/src/scene_module/intersection/scene_intersection.cpp
Fixed the logger level from INFO to DEBUG which was contaminated by previous PR.
=> fix(intersection): fix logger level

planning/rtc_auto_mode_manager/include/rtc_auto_mode_manager/node.hpp, planning/rtc_auto_mode_manager/include/rtc_auto_mode_manager/rtc_auto_mode_manager_interface.hpp, planning/rtc_auto_mode_manager/src/node.cpp, planning/rtc_auto_mode_manager/src/rtc_auto_mode_manager_interface.cpp
This PR needs https://github.com/tier4/tier4_autoware_msgs/pull/70
add auto mode status array
=> feat(rtc_auto_mode_manager)!: add auto mode status array

planning/behavior_path_planner/src/scene_module/utils/path_shifter.cpp
`RCLCPP_WARN_THROTTLE` -> `RCLCPP_DEBUG`
=> fix(path_shifter): fix log level for nominal case

planning/freespace_planning_algorithms/README.md
=> docs(freespace-planner): fix syntax error

planning/behavior_velocity_planner/src/scene_module/detection_area/debug.cpp, planning/obstacle_cruise_planner/src/pid_based_planner/pid_based_planner.cpp
Fixed typo. (obstalce -> obstacle)
=> chore: fix typo

planning/obstacle_stop_planner/config/obstacle_stop_planner.param.yaml, planning/obstacle_stop_planner/include/obstacle_stop_planner/node.hpp, planning/obstacle_stop_planner/include/obstacle_stop_planner/planner_data.hpp, planning/obstacle_stop_planner/src/node.cpp
- add parameter for voxel grid parameter for filtering pointcloud
- publish pointcloud as debug
- please review with https://github.com/autowarefoundation/autoware_launch/pull/156
https://github.com/autowarefoundation/autoware_launch/pull/156
TIERIV INTERNAL LINK: https://tier4.atlassian.net/browse/T4PB-24714
red: `/planning/scenario_planning/lane_driving/motion_planning/obstacle_stop_planner/debug/obstacle_pointcloud`
white: `/perception/obstacle_segmentation/pointcloud`
confirmed publishing pointcloud in psim
voxel_grid_x: 0.5, voxel_grid_y: 0.5 …
=> feat(obstacle_stop_planner): add parameter for voxel grid filter and publish pointcloud as debug

localization/ekf_localizer/include/ekf_localizer/ekf_localizer.hpp, localization/ekf_localizer/src/ekf_localizer.cpp
Remove an unnecessary variable 
=> refactor(ekf_localizer): remove 'dim_x_ex_' as it is no longer used

localization/ekf_localizer/src/ekf_localizer.cpp
To simplify the code, I added a function that warns if delay time is less than zero 
=> refactor(ekf_localizer): add a function that warns if delay time < 0

planning/behavior_path_planner/behavior_path_planner_avoidance-design.md, planning/behavior_path_planner/image/avoidance_design/target_vehicle_selection.drawio.svg
=> docs(behavior_path_planner): fix typos

planning/route_handler/src/route_handler.cpp
If shoulder lane is short, can not get it.
tier4 internal link
https://star4.slack.com/archives/CEV8XMJBV/p1674028598540389?thread_ts=1673483543.019879&cid=CEV8XMJBV
=> fix(route_handler): fix getShoulderLaneletSequence

perception/lidar_apollo_instance_segmentation/README.md
fix pre-commit
```
ERROR: 1 dead links found!
[✖] https://github.com/ApolloAuto/apollo/blob/master/docs/specs/3d_obstacle_perception.md → Status: 404
```
https://github.com/autowarefoundation/autoware.universe/actions/runs/3951072136/jobs/6764448235 …
=> chore(lidar_apollo_instance_segmentation): modify invalid link

launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.py, launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.xml, planning/behavior_path_planner/include/behavior_path_planner/behavior_path_planner_node.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/pull_over_module.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_interface.hpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp, planning/behavior_path_planner/src/scene_module/pull_over/pull_over_module.cpp, planning/mission_planner/src/mission_planner/arrival_checker.cpp, planning/mission_planner/src/mission_planner/arrival_checker.hpp, planning/mission_planner/src/mission_planner/mission_planner.cpp, planning/mission_planner/src/mission_planner/mission_planner.hpp, planning/route_handler/include/route_handler/route_handler.hpp, planning/route_handler/src/route_handler.cpp
publish modified goal with uuid as proposed in https://github.com/autowarefoundation/autoware/discussions/2983
> modified goal stamp
Use the stamp of the timing when behavior_path_planner is triggered for modified goal. It is the same as path_with_lane_id's one.
> modified goal publish timing
Only when the goal is modified and do not publish in a module that does not have a modification function.
TODO other than this PR
- support uuid in mission planner (generate uuid etc)
- support PoseStampedWithUuid visualization in rviz_plugin
https://github.com/tier4/autoware_launch/pull/674
psim
publish modified goal only when goal is modified
https://user-images.githubusercontent.com/39142679/210081598-88f2aac5-8d8a-479e-879d-e2349906c970.mp4
state change to ARRIVED when arrived the modified goal …
=> feat(behavior_path_planner): modified goal with uuid

planning/planning_validator/test/src/test_planning_validator_helper.cpp
=> chore(planning_validator): fix typo

planning/route_handler/package.xml, planning/rtc_auto_mode_manager/package.xml, planning/rtc_interface/package.xml
Add maintainers in route_handler, rtc_interface and rtc_auto_mode_manager.
=> chore(route_handler, rtc_interface, rtc_auto_mode_manager): add maintainer

control/operation_mode_transition_manager/package.xml
=> chore(operation_mode_transition_manager): add maintainer

control/vehicle_cmd_gate/package.xml
Signed-off-by: Takamasa Horibe <horibe.takamasa@gmail.com>
Add maintainer of vehicle_cmd_gate
=> chore(vehicle_cmd_gate): add maintainer

control/operation_mode_transition_manager/README.md, control/operation_mode_transition_manager/src/node.cpp, control/operation_mode_transition_manager/src/node.hpp
- Update readme
- fix suffix for some member variables
=> docs(operation_mode_transition_manager): update readme

control/trajectory_follower_base/include/trajectory_follower_base/input_data.hpp, control/trajectory_follower_base/include/trajectory_follower_base/lateral_controller_base.hpp, control/trajectory_follower_base/include/trajectory_follower_base/longitudinal_controller_base.hpp, control/trajectory_follower_base/include/trajectory_follower_base/sync_data.hpp, control/trajectory_follower_base/src/lateral_controller_base.cpp, control/trajectory_follower_base/src/longitudinal_controller_base.cpp, control/trajectory_follower_node/include/trajectory_follower_node/controller_node.hpp, control/trajectory_follower_node/src/controller_node.cpp
use shorter namespace expression
=> refactor(trajectory_follower_base): use shorter namespace expression

localization/ekf_localizer/CMakeLists.txt, localization/ekf_localizer/include/ekf_localizer/warning_message.hpp, localization/ekf_localizer/src/ekf_localizer.cpp, localization/ekf_localizer/src/mahalanobis.cpp, localization/ekf_localizer/src/warning_message.cpp, localization/ekf_localizer/test/test_mahalanobis.cpp, localization/ekf_localizer/test/test_warning_message.cpp
Remove the mahalanobis gate function to explicitly show the actual measured distance in the warning message. 
Removed the tests of the mahalanobis gate and added tests for the ordinal mahalanobis distance.
=> refactor(ekf_localizer): replace the mahalanobisGate function with a simple if statement

planning/behavior_path_planner/src/scene_module/lane_change/external_request_lane_change_module.cpp, planning/behavior_path_planner/src/scene_module/lane_change/lane_change_module.cpp, planning/behavior_path_planner/src/scene_module/lane_change/util.cpp, planning/behavior_velocity_planner/include/scene_module/intersection/manager.hpp, planning/behavior_velocity_planner/include/scene_module/traffic_light/manager.hpp, planning/behavior_velocity_planner/src/scene_module/intersection/manager.cpp, planning/behavior_velocity_planner/src/scene_module/traffic_light/manager.cpp, planning/route_handler/include/route_handler/route_handler.hpp, planning/route_handler/src/route_handler.cpp
Signed-off-by: Fumiya Watanabe <rej55.g@gmail.com>
Before this change, lane change module restricts perform lane change in intersection.
In this change, it enables lane change in intersection.
To prevent reboot intersection module and traffic light module, I fixed the register condition of intersection module and traffic light module.
- Intersection module
- Register module if all parent lanes of checking lane are not included in parent lanes of registered lanes or the lane changeable neighbor lanes of the parent lanes
- Traffic light module
- Register module if all traffic lights of checking lane are not included in traffic lights of registered lanes
Tested in planning_simulator.
Tested in real vehicle and TIER IV internal test.  …
=> feat(behavior_path_planner): enable lane change in intersection

common/kalman_filter/package.xml
=> build(kalman_filter): add build dependency

system/dummy_infrastructure/package.xml
=> build(dummy_infrastructure): add build dependency

planning/obstacle_avoidance_planner/src/utils/debug_utils.cpp
Signed-off-by: Mehmet Dogru <42mehmetdogru42@gmail.com>
closes #2688 
This PR creates a separate footprint marker and appends it to `vis_marker_array` in `obstacle_avoidance_planner` for easier debugging.
=> feat(obstacle_avoidance_planner): add a separate marker for the first footprint which goes out of drivable area

system/bluetooth_monitor/package.xml
=> build(bluetooth_monitor): add build dependency

system/system_monitor/package.xml
=> build(system_monitor): add build dependency

localization/gyro_odometer/CMakeLists.txt, localization/gyro_odometer/include/gyro_odometer/gyro_odometer_core.hpp, localization/gyro_odometer/package.xml, localization/gyro_odometer/src/gyro_odometer_core.cpp, localization/gyro_odometer/src/gyro_odometer_node.cpp, localization/gyro_odometer/test/test_gyro_odometer_helper.cpp, localization/gyro_odometer/test/test_gyro_odometer_helper.hpp, localization/gyro_odometer/test/test_gyro_odometer_pubsub.cpp, localization/gyro_odometer/test/test_main.cpp
Add a simple test for gyro_odometer
=> test(gyro_odometer): add test

launch/tier4_map_launch/CMakeLists.txt, launch/tier4_map_launch/config/pointcloud_map_loader.param.yaml, launch/tier4_map_launch/launch/map.launch.py, launch/tier4_map_launch/launch/map.launch.xml
Remove unused config from tier4_map_launch
Should be merged at the same time with:
- (TIER IV internal link) https://github.com/tier4/autoware_launch/pull/731
=> refactor(tier4_map_launch): remove unused config

sensing/gnss_poser/package.xml
=> build(gnss_poser): add build dependency

launch/tier4_control_launch/package.xml
=> chore(control_launch): add maintainer

common/motion_utils/src/marker/marker_helper.cpp
Fixed virtual wall marker addition condition
=> fix(motion_utils): fixed virtual wall marker to appear

planning/behavior_velocity_planner/include/scene_module/intersection/scene_intersection.hpp, planning/behavior_velocity_planner/src/scene_module/intersection/debug.cpp, planning/behavior_velocity_planner/src/scene_module/intersection/scene_intersection.cpp
Additional fix for https://github.com/autowarefoundation/autoware.universe/pull/2506
=> chore(intersection): remove unnecessary marker

control/pid_longitudinal_controller/include/pid_longitudinal_controller/debug_values.hpp, control/pid_longitudinal_controller/src/pid_longitudinal_controller.cpp
For accurate control, the feedforward should be calculated in the arclength coordinate system, not in the time coordinate system. Otherwise, even if FF is applied, the vehicle speed deviation will diverge.
Note: the definition (role) of the feedforward control is to keep the deviation error constant. 
The target velocity (planning system) and feedback control are designed on the arclength coordinate, so the feedforward should follow as well.
sim and real vehicle experiments are done.
Here is one of the tests. 
**Before** : the control error is about 0.3m/s on average and not converging. (target=green, actual=pink)
**After** : the control error is about 0.1 on average, smaller than before. (target=green, actual=pink) …
=> feat(longitudinal_controller): add feedforward conversion to arc coordinate

planning/costmap_generator/package.xml
add costmap_generator maintainers
@kosuke55 
@TakaHoribe 
@takayuki5168 
@purewater0901 
=> chore(costmap_generator): add maintainers

perception/detected_object_validation/package.xml
=> build(detected_object_validation): add build dependency

common/autoware_auto_perception_rviz_plugin/package.xml
=> build(autoware_auto_perception_rviz_plugin): add build dependency

common/signal_processing/package.xml
=> build(signal_processing): add build dependency

planning/freespace_planner/package.xml, planning/freespace_planning_algorithms/package.xml
add maitainers
@kosuke55
@takayuki5168
@purewater0901
=> chore(freespace_planner): add maintainers

common/rtc_manager_rviz_plugin/package.xml
Add code owner of rtc_manager_rviz_plugin package
=> chore(rtc_manager_rviz_plugin): add code owner

common/rtc_manager_rviz_plugin/src/rtc_manager_panel.cpp, common/rtc_manager_rviz_plugin/src/rtc_manager_panel.hpp
Signed-off-by: taikitanaka3 <taiki.tanaka@tier4.jp>
In some case RTC stauts expired without deleted so I add viewer for the number of rtc status.
[tier4 internal](https://star4.slack.com/archives/C03JS7G3H8U/p1675214997411399)
=> feat(rtc_manager_rviz_plugin): add the number of rtc status

planning/behavior_path_planner/src/scene_module/pull_out/shift_pull_out.cpp
In pull out module ,sometimes ```route_handler.getCenterLinePath(road_lanes, s_start, s_end, true);``` returns empty path and then a invalid access occurs. I fixed it.
=> fix(behavior_path_planner): do not access empty path in pull out module

planning/behavior_path_planner/src/utilities.cpp
This is just a refactor, common duplicated lines of getExtendedCurrentLanes
=> refactor(behavior_path_planner): common duplicated lines of getExtendedCurrentLanes

common/interpolation/package.xml
Add maintainer to the interpolation package
=> feat(interpolation): add maintainer

planning/behavior_velocity_planner/src/node.cpp
Signed-off-by: Vincent Richard <richard-v@macnica.co.jp>
Fix #2706
=> fix(behavior_velocity_planner): fix misc concurrency issues

planning/motion_velocity_smoother/include/motion_velocity_smoother/smoother/analytical_jerk_constrained_smoother/analytical_jerk_constrained_smoother.hpp, planning/motion_velocity_smoother/include/motion_velocity_smoother/smoother/smoother_base.hpp, planning/motion_velocity_smoother/src/motion_velocity_smoother_node.cpp, planning/motion_velocity_smoother/src/smoother/analytical_jerk_constrained_smoother/analytical_jerk_constrained_smoother.cpp, planning/motion_velocity_smoother/src/smoother/smoother_base.cpp
The `motion_utils::resampleTrajectory` takes a long time and is applied two times in `applyLateralAccelerationFilter()` and `applySteeringRateLimit()`. This resampling aims to make the trajectory interval constant, so we don't have to apply it every time.
I added the option to use resampling, and in the current implementation, resampling is applied only once in the `applyLateralAccelerationFilter()`. 
**This improves the computational speed: 34ms -> 26ms on average, 25% improvement.**
**Before**
**After** …
=> refactor(motion_velocity_smoother): remove unneccesary resampling

localization/ekf_localizer/src/state_transition.cpp
Signed-off-by: Vincent Richard <vincent.francois.richard@gmail.com>
=> chore(ekf_localizer): typo

perception/detection_by_tracker/src/detection_by_tracker_core.cpp
Signed-off-by: yoshiri <yoshiyoshidetteiu@gmail.com>
Just remove unnecessary print function in dbt.
=> refactor(detection_by_tracker): remove unnecessary statement

planning/motion_velocity_smoother/package.xml
Signed-off-by: Fumiya Watanabe <rej55.g@gmail.com>
Add maintainer in motion_velocity_smoother
=> chore(motion_velocity_smoother): add maintainer

planning/behavior_path_planner/include/behavior_path_planner/behavior_path_planner_node.hpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp
Replace deprecated function
https://github.com/ros2/rclcpp/blob/8e6a6fb32d8d6a818b483660e326f2c5313b64ae/rclcpp/include/rclcpp/any_subscription_callback.hpp#L391
=> fix(behavior_path_planner): replace deprecated function

planning/behavior_path_planner/src/utilities.cpp
Signed-off-by: Muhammad Zulfaqar <zulfaqar.azmi@tier4.jp>
Current lane change method checks the future stopping distance and if it is safe, then lane change will be executed. However, there is a potential of lane change is executed when the inter-vehicle distance is too near to each other. This because the lacks of logic to check for current distance between vehicle. This PR aims to solve this by including the necessary check.
This PR is to solve LC-00004_001_case6_v2 scenario.
[TIER IV internal link](https://evaluation.tier4.jp/evaluation/reports/a2007753-6969-5c92-843a-8373068ff4f6/tests/45053b85-35f1-55a9-901c-34c539d5245d/542deebf-784e-51e3-a122-a256e0952531/a0d01324-01bc-5d1c-90a6-effa92e7c665?project_id=prd_jt)
[TIER IV internal …
=> fix(lane_change): safe intervehicle distance in collision check

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
The way to expand the drivable area has some edge cases as follows.
I tested some places of adjacent fork road (隣接した分岐路) in odaiba map, and it worked well.
**case1**
before
after
**case2**
before
after
**case3**
before
after
**case4**
before
after
=> fix(behavior_path_planner): fix drivable area expansion method outside intersection

planning/planning_debug_tools/scripts/perception_reproducer.py
This script is supposed to be used with planning simulator, and it publishes objects (and traffic signals) from the rosbag.
The predicted objects from the rosbag, where the ego pose at that time is closest to the current ego pose in the simulation, will be published every cycle.
**How to use this script**
terminal1: run psim, and set the ego, where around the rosbag was recorded, and goal pose
terminal2: `python3 perception_reproducer.py -b <bag-file-path> -p` or `python3 perception_reproducer.py -d <bag-dir-path> -p`
Then, engage the vehicle.
[Screencast from 2023年02月15日 02時45分01秒.webm](https://user-images.githubusercontent.com/20228327/218816499-b053c87a-53a9-4ec1-beb1-9f25a3304d7d.webm)
NOTE: This script will kill …
=> feat(planning_debug_tools): add perception_reproducer.py

planning/behavior_path_planner/test/test_drivable_area_expansion.cpp
This PR fixes tests that were failing in the `build-and-test-self-hosted` environment.
=> fix(behavior_path_planner): fix tests failing in CI

common/tier4_autoware_utils/include/tier4_autoware_utils/ros/uuid_helper.hpp
add generateUUID to uuid helper
=> feat(tier4_autoware_utils): add generateUUID to uuid helper

perception/occupancy_grid_map_outlier_filter/include/occupancy_grid_map_outlier_filter/occupancy_grid_map_outlier_filter_nodelet.hpp, perception/occupancy_grid_map_outlier_filter/src/occupancy_grid_map_outlier_filter_nodelet.cpp
In occupancy_grid_map_outlier_filter, the low_confidence_pointcloud extracted from occupancy_grid_map are compared with all input pointcloud. It's waste of time to compare without pointcloud outside of occupancy_grid_map so this PR to exclude pcl outside of occupancy_grid_map from input of RadiusSearch filter. 
[TIERIV INTERNAL LINK](https://tier4.atlassian.net/browse/T4PB-25711)
Before change
Green: high_confidence_pc, Pink: low_confidence_pc
After change: 
Green: high_confidence_pc, Pink: low_confidence_pc …
=> fix(occupancy_grid_map_ouliter_filter): reduce radius search region

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_utils.cpp, planning/behavior_path_planner/test/input.hpp
=> fix(behavior_path_planner): remove unnecessary include

common/motion_utils/include/motion_utils/trajectory/trajectory.hpp
Signed-off-by: AhmedEbrahim <ahmed.a.d.ebrahim@gmail.com>
closes #2803 
=> fix(motion_utils): add doxygen comments for utility functions in trajectory header

launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml
It doesn't match the arg on the node launch file and tier4_perception_launch.
fix typo thrust -> trust 
=> fix(tier4_perception_launch): fix typo

planning/behavior_path_planner/CMakeLists.txt, planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_out/pull_out_module.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/pull_over_module.hpp, planning/behavior_path_planner/include/behavior_path_planner/util/pull_out/geometric_pull_out.hpp, planning/behavior_path_planner/include/behavior_path_planner/util/pull_out/pull_out_parameters.hpp, planning/behavior_path_planner/include/behavior_path_planner/util/pull_out/pull_out_path.hpp, planning/behavior_path_planner/include/behavior_path_planner/util/pull_out/pull_out_planner_base.hpp, planning/behavior_path_planner/include/behavior_path_planner/util/pull_out/shift_pull_out.hpp, planning/behavior_path_planner/include/behavior_path_planner/util/pull_out/util.hpp, planning/behavior_path_planner/include/behavior_path_planner/util/pull_over/geometric_pull_over.hpp, planning/behavior_path_planner/include/behavior_path_planner/util/pull_over/goal_searcher.hpp, planning/behavior_path_planner/include/behavior_path_planner/util/pull_over/goal_searcher_base.hpp, planning/behavior_path_planner/include/behavior_path_planner/util/pull_over/pull_over_parameters.hpp, planning/behavior_path_planner/include/behavior_path_planner/util/pull_over/pull_over_planner_base.hpp, planning/behavior_path_planner/include/behavior_path_planner/util/pull_over/shift_pull_over.hpp, planning/behavior_path_planner/include/behavior_path_planner/util/pull_over/util.hpp, planning/behavior_path_planner/include/behavior_path_planner/utilities.hpp, planning/behavior_path_planner/src/scene_module/pull_out/pull_out_module.cpp, planning/behavior_path_planner/src/scene_module/pull_over/pull_over_module.cpp, planning/behavior_path_planner/src/util/pull_out/geometric_pull_out.cpp, planning/behavior_path_planner/src/util/pull_out/shift_pull_out.cpp, planning/behavior_path_planner/src/util/pull_out/util.cpp, planning/behavior_path_planner/src/util/pull_over/geometric_pull_over.cpp, planning/behavior_path_planner/src/util/pull_over/goal_searcher.cpp, planning/behavior_path_planner/src/util/pull_over/shift_pull_over.cpp, planning/behavior_path_planner/src/util/pull_over/util.cpp
move pull out/over utils directory
=> chore(pull_out/over): move pull out/over utils

planning/obstacle_avoidance_planner/src/mpt_optimizer.cpp, planning/obstacle_avoidance_planner/src/node.cpp, planning/obstacle_avoidance_planner/src/utils/debug_utils.cpp
Signed-off-by: beyza <bnk@leodrive.ai>
fixes: https://github.com/autowarefoundation/autoware.universe/issues/2663
=> fix(obstacle_avoidance_planner):  fix lateral calculations

planning/behavior_path_planner/CMakeLists.txt, planning/behavior_path_planner/include/behavior_path_planner/behavior_path_planner_node.hpp, planning/behavior_path_planner/include/behavior_path_planner/marker_util/avoidance/debug.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module.hpp, planning/behavior_path_planner/include/behavior_path_planner/util/avoidance/avoidance_module_data.hpp, planning/behavior_path_planner/include/behavior_path_planner/util/avoidance/util.hpp, planning/behavior_path_planner/src/marker_util/avoidance/debug.cpp, planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp, planning/behavior_path_planner/src/util/avoidance/util.cpp, planning/behavior_path_planner/test/test_avoidance_utils.cpp
move avoidance utils directory
=> chore(avoidance): move avoidance utils directory

planning/obstacle_stop_planner/package.xml
Added missing `libopencv-dev` in `package.xml`
=> build(obstacle_stop_planner): added libopencv-dev dependency

planning/obstacle_stop_planner/README.md, planning/obstacle_stop_planner/config/obstacle_stop_planner.param.yaml, planning/obstacle_stop_planner/include/obstacle_stop_planner/planner_data.hpp, planning/obstacle_stop_planner/src/node.cpp
At ```obstacle_stop_planner```, If extend_distance parameter is set to 0.0 by default, ```obstacle_stop_planner``` does not consider the obstacle after vehicle_length. With this PR, extend trajectory by ```max_longitudinal_margin``` parameter for object detection area.
autoware_launch PR: https://github.com/autowarefoundation/autoware_launch/pull/224
closes #2513
Initial   |  Arrived 
:-------------------------:|:-------------------------:
Initial   |  Arrived 
:-------------------------:|:-------------------------: …
=> feat(obstacle_stop_planner): extend trajectory along vehicle length

control/control_performance_analysis/package.xml, control/external_cmd_selector/package.xml, control/joy_controller/package.xml, control/obstacle_collision_checker/package.xml, planning/scenario_selector/package.xml
add maintainers of following mofules:
- control_performance_analysis
- external_cmd_selector
- joy_controller
- obstacle_collision_checker
- scenario_selector
=> chore(control, planning): add maintainers

planning/behavior_path_planner/behavior_path_planner_avoidance_design.md, planning/behavior_path_planner/behavior_path_planner_drivable_area_design.md, planning/behavior_path_planner/behavior_path_planner_lane_change_design.md, planning/behavior_path_planner/behavior_path_planner_limitations.md, planning/behavior_path_planner/behavior_path_planner_path_generation_design.md, planning/behavior_path_planner/behavior_path_planner_side_shift_design.md, planning/behavior_path_planner/behavior_path_planner_turn_signal_design.md
=> docs(behavior_path_planner): align document title

planning/motion_velocity_smoother/src/motion_velocity_smoother_node.cpp
Before this change, ego vehicle moves after removing an object although a stop signal is sent to the vehicle through external velocity limit.
The reason is the distance to set external velocity limit is not updated after the vehicle stopped caused by the object.
To fix this, I add the update condition of the distance to set external velocity limit.
Before
https://user-images.githubusercontent.com/10190493/221740221-c1c6fb5d-f317-4ee5-8593-5dbf8e3f04e2.mp4
After
https://user-images.githubusercontent.com/10190493/221740294-d79de8e8-fa61-4bef-8b74-e5cf9392e77b.mp4 …
=> fix(motion_velocity_smoother): fix external velocity limit if ego vehicle is stopped

planning/behavior_path_planner/config/avoidance/avoidance.param.yaml, planning/behavior_path_planner/include/behavior_path_planner/util/avoidance/avoidance_module_data.hpp, planning/behavior_path_planner/include/behavior_path_planner/utilities.hpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp, planning/behavior_path_planner/src/marker_util/avoidance/debug.cpp, planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp, planning/behavior_path_planner/src/utilities.cpp
https://github.com/autowarefoundation/autoware_launch/pull/226
For now, the module filtiering parked car from perception outputs, and execute avoidance for only those cars. The filtiering conditions are following:
- Stopped for more than T[s] time.
- Farther away from lane center line than D[m].
- Pull over the left (right) road shoulder.
However, there are still parked vehicles that do **NOT** satisfy the above conditions.
In this PR, I add new option for avoidance filtering logic to avoid all vehicle that stopped for a longer time than threshold.
```yaml
...
enable_force_avoidance_for_stopped_vehicle: false
...
threshold_time_force_avoidance_for_stopped_vehicle: 10.0 # [s]
object_check_force_avoidance_clearance: 30.0    # [m]
...
``` …
=> feat(avoidance): enable to avoid vehicles that stopped for a long time

common/tier4_state_rviz_plugin/src/autoware_state_panel.cpp
=> fix(tier4_state_rviz_plugin): fix typo

common/tier4_planning_rviz_plugin/package.xml
Add me as a tier4_rviz_planning_plugin maintainer
=> feat(tier4_planning_rviz_plugin): add maintainer

perception/euclidean_cluster/config/voxel_grid_based_euclidean_cluster.param.yaml
Fix crash in https://github.com/autowarefoundation/autoware.universe/issues/2974
Refactored https://github.com/autowarefoundation/autoware.universe/pull/2975
=> fix(euclidean_cluster): add crop box missing input frame

planning/behavior_path_planner/src/utilities.cpp
fix calcLateralDistanceFromEgoToObject.
when  `signed_distance_from_left < 0.0 && signed_distance_from_right > 0.0` point is between left and right
psim
=> fix(behavior_path_planner): fix calcLateralDistanceFromEgoToObject

perception/traffic_light_ssd_fine_detector/README.md, perception/traffic_light_ssd_fine_detector/launch/traffic_light_ssd_fine_detector.launch.xml, perception/traffic_light_ssd_fine_detector/src/nodelet.cpp
- the option to build tensorrt engine without inference is required for test on cloud
=> feat(traffic_light_ssd_fine_detector): add build only option for tensorrt engine

perception/traffic_light_classifier/README.md, perception/traffic_light_classifier/launch/traffic_light_classifier.launch.xml
fix <https://github.com/autowarefoundation/autoware.universe/pull/2985>.
=> chore(traffic_light_classifier): add missing launch args and fix typo

planning/behavior_path_planner/CMakeLists.txt, planning/behavior_path_planner/include/behavior_path_planner/behavior_path_planner_node.hpp, planning/behavior_path_planner/include/behavior_path_planner/parameters.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_out/manager.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_out/pull_out_module.hpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp, planning/behavior_path_planner/src/scene_module/pull_out/manager.cpp, planning/behavior_path_planner/src/scene_module/pull_out/pull_out_module.cpp
https://github.com/autowarefoundation/autoware_launch/pull/236
It is able to build avoidance module on new framework (added in https://github.com/autowarefoundation/autoware.universe/pull/2919).
Checkout your branch of autoware_launch to `feat/support-new-framework-pull-out`.
https://github.com/autowarefoundation/autoware_launch/tree/feat/support-new-framework-pull-out
In addtion, we may have to comment out module names which haven't supported new framework yet in [rtc_auto_mode_manager.param.yaml](https://github.com/autowarefoundation/autoware_launch/blob/feat/support-new-framework-pull-out/autoware_launch/config/planning/scenario_planning/lane_driving/behavior_planning/rtc_auto_mode_manager/rtc_auto_mode_manager.param.yaml).
```yaml
/**: …
```
=> feat(pull_out): support new framework

planning/behavior_path_planner/package.xml
=> chore(behavior_path_planner): add maintainer

planning/behavior_path_planner/CMakeLists.txt, planning/behavior_path_planner/include/behavior_path_planner/behavior_path_planner_node.hpp, planning/behavior_path_planner/include/behavior_path_planner/data_manager.hpp, planning/behavior_path_planner/include/behavior_path_planner/parameters.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/side_shift/manager.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/side_shift/side_shift_module.hpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp, planning/behavior_path_planner/src/scene_module/side_shift/manager.cpp, planning/behavior_path_planner/src/scene_module/side_shift/side_shift_module.cpp
https://github.com/autowarefoundation/autoware_launch/pull/234
It is able to build side shift module on new framework (added in https://github.com/autowarefoundation/autoware.universe/pull/2919).
- https://github.com/autowarefoundation/autoware.universe/pull/2919
Checkout your branch of autoware_launch to `feat/support-new-framework-side-shift`.
https://github.com/autowarefoundation/autoware_launch/tree/feat/support-new-framework-side-shift
Please set following flag to `FALSE`, and confirm to pass all build.
https://github.com/autowarefoundation/autoware.universe/blob/ad5595389a629346476ee06391260ffea53159ef/planning/behavior_path_planner/CMakeLists.txt#L10
The PR …
=> feat(side_shift): support new framework side shift

control/trajectory_follower_node/package.xml
=> build(trajectory_follower_node): added missing dependencies

system/component_state_monitor/package.xml
=> fix(component_state_monitor): add dependency on topic_state_monitor

planning/behavior_path_planner/src/scene_module/pull_over/pull_over_module.cpp
The vehicle decelerate before goal seach area but,  after the vehicle passes the search start point the point can not be found.
So deleration velocity can not be set and the vehicle accerates again.
In this PR, after passing search start point, set the current velocity to the pass.
[Screencast from 2023年03月09日 11時11分52秒.webm](https://user-images.githubusercontent.com/39142679/223906937-e3ef4b85-ce20-4f6d-adb1-d83ab55fa0c3.webm)
[Screencast from 2023年03月09日 11時53分24秒.webm](https://user-images.githubusercontent.com/39142679/223907288-2e41e5d6-f441-4583-bbb3-d3f9fc8c0f03.webm)
After all …
=> fix(behavior_path_planner): prevent re-acceleration in pull over

sensing/pointcloud_preprocessor/src/crop_box_filter/crop_box_filter_nodelet.cpp
Following https://github.com/autowarefoundation/autoware.universe/pull/2992#discussion_r1123993553
=> perf(crop_box_filter):  skip useless copy

launch/tier4_simulator_launch/package.xml
Just added a code owner for tier4_simulator_launch
=> chore(tier4_simulator_launch): add code owner

common/autoware_testing/package.xml
Added missing export for downstream packages.
=> build(autoware_testing): add missing dependencies

launch/tier4_localization_launch/package.xml
=> chore(tier4_localization_launch): add maintainer

common/rtc_manager_rviz_plugin/src/rtc_manager_panel.cpp
https://github.com/tier4/tier4_autoware_msgs/pull/71
add new module `avoidance_by_lc`
=> feat(rtc_manager_rviz_plugin): add avoidance by lc

evaluator/diagnostic_converter/src/converter_node.cpp
Topic name must not have ":", "@", ...
So I applied regex to the calculated topic name.
I confirmed that the diagnostic converter node did not die where the diag's key has the string ":".
=> feat(diagnostic_converter): apply regex for topic name

planning/behavior_velocity_planner/config/detection_area.param.yaml, planning/behavior_velocity_planner/detection-area-design.md, planning/behavior_velocity_planner/include/scene_module/detection_area/scene.hpp, planning/behavior_velocity_planner/src/scene_module/detection_area/manager.cpp, planning/behavior_velocity_planner/src/scene_module/detection_area/scene.cpp
Fixed an issue that the detection area was ignored under the following conditions
- The stop line is tied to the detection area
- The ego vehicle stops a few centimeters over the stop line
- When an object enters the detection area while the ego vehicle is stopping, the ego vehicle ignores the detection area and starts
https://github.com/autowarefoundation/autoware_launch/pull/260
Confirmed with the planning simulator
Before
https://user-images.githubusercontent.com/876355/225901665-3c5afd7c-6afb-4884-b834-93ef477d3210.mp4
After
https://user-images.githubusercontent.com/876355/225901688-63ecef6a-8e81-410d-bc13-fe972b424b4e.mp4 …
=> fix(behavior_velocity_planner): fix detection area being ignored when the ego vehicle stops over the stop line

planning/behavior_path_planner/behavior_path_planner_avoidance_design.md, planning/behavior_path_planner/behavior_path_planner_path_generation_design.md
Fixed math formulation format in doc of behavior_path_planner
=> fix(behavior_path_planner): fix math formulation in doc

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
**NOT** skip shift line generation when the ego is avoiding.
=> fix(avoidance): fix shift line generation logic

control/pid_longitudinal_controller/package.xml
=> refactor(pid_longitudinal_controller): remove unused dependency

control/autonomous_emergency_braking/package.xml
=> feat(autonomous_emergency_braking): add maintainer

control/trajectory_follower_base/package.xml
=> refactor(trajectory_follower_base): remove unused dependency

planning/behavior_path_planner/include/behavior_path_planner/behavior_path_planner_node.hpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp
solves #2495
Properly lock mutex for `planner_data_` and `bt_manager_` read/write.
=> fix(behavior_path_planner): concurrency issue

common/tier4_screen_capture_rviz_plugin/src/screen_capture_panel.cpp
=> fix(tier4_screen_capture_rviz_plugin): fix extra/missing naming components

launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.py, planning/behavior_path_planner/config/drivable_area_expansion.param.yaml, planning/behavior_path_planner/config/scene_module_manager.param.yaml
Add parameter config file for manager.
This PR must be merged with https://github.com/autowarefoundation/autoware_launch/pull/270.
=> feat(behavior_path_planner): update behavior param file

planning/costmap_generator/nodes/costmap_generator/costmap_generator_node.cpp
[costmap_generator_delete_param.webm](https://user-images.githubusercontent.com/100691117/226564509-8bbbeed8-e844-4d07-b103-d86ab82c503b.webm)
=> refactor(costmap_generator): delete default values

common/motion_utils/include/motion_utils/trajectory/trajectory.hpp, common/motion_utils/test/src/trajectory/test_trajectory.cpp
add `insertDecelPoint` to motion_utils
test code
=> feat(motion_utils): add insertDecelPoint

launch/tier4_perception_launch/launch/perception.launch.xml, perception/lidar_centerpoint/config/centerpoint_tiny.param.yaml, perception/traffic_light_map_based_detector/config/traffic_light_map_based_detector.param.yaml
cherry pick
- https://github.com/autowarefoundation/autoware.universe/commit/8ce9156e63ad156c71285c5d1b0fb36b9e0a42d2
- https://github.com/autowarefoundation/autoware.universe/commit/61e6e08b8c55c599bcf4d60bc56a9a566a531386
=> chore: update awsim-stable branch

launch/tier4_control_launch/launch/control.launch.py
Add necessary parameters to tier4_control_launch
=> fix(control_launch): add necessary parameter

perception/lidar_apollo_segmentation_tvm/package.xml
=> refactor(lidar_apollo_segmentation_tvm): remove unused depend

common/motion_utils/include/motion_utils/trajectory/interpolation.hpp, common/motion_utils/test/src/trajectory/test_interpolation.cpp
Add a new interpolation function that computes an interpolated pose from the given path base on the length from the front point.
Add unit tests
=> feat(motion_utils): add new interpolation function

planning/static_centerline_optimizer/rviz/static_centerline_optimizer.rviz
Path Footprint rviz plugin was recently merged to Path rviz plugin.
I applied this change to the rviz config of static_centerline_optimizer.
Confirmed that static_centerline_optimizer worked well with rviz.
=> fix(static_centerline_optimizer): fix rviz for fooptrint

planning/behavior_path_planner/include/behavior_path_planner/utilities.hpp, planning/behavior_path_planner/src/utilities.cpp, planning/behavior_path_planner/test/test_utilities.cpp
Remove unnecessary conversion functions from utils file in behavior path planner
=> refactor(behavior_path_planner): remove unnecessary conversion funtion

launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml, launch/tier4_perception_launch/launch/object_recognition/detection/detection.launch.xml, launch/tier4_perception_launch/launch/perception.launch.xml
I made it possible to change parameters from autoware_launch that are highly likely to be modified depending on their usage.
I confirmed that the recognition module launched successfully.
=> chore(tier4_perception_launch): add custom parameters for roi_cluster_fusion

planning/behavior_path_planner/src/util/lane_change/util.cpp
Fixed the bug where the bound is short enough when executing lane_change.
scenario works well
`webauto ci scenario run --project-id prd_jt --scenario-id 3d826953-1897-48ba-a5bb-a2fc973c06ff --runtime-path /home/takayuki/pilot-auto.main --scenario-parameters __tier4_modifier_oncommingcar_initial_speed=4.167` …
=> fix(behavior_path_planner): fix the bug of short bound

common/motion_utils/include/motion_utils/trajectory/trajectory.hpp, common/motion_utils/test/src/trajectory/test_trajectory.cpp, planning/behavior_path_planner/src/util/path_shifter/path_shifter.cpp
Shifting curved path points causes invalid orientation, so in this PR add `removeInvalidOrientationPoints` for removing these  points.
before
after
[tier4 internal ticket](https://tier4.atlassian.net/browse/RT1-1640)
psim
test code
=> fix(behavior_path): add removeInvalidOrientationPoints to motion_utils for path shifter on a curve

perception/bytetrack/package.xml
Added Boost and Eigen dependencies to `package.xml` so that package can be built in isolation.
Building this package in isolation fails unless these dependencies are added.
=> build(bytetrack): add missing dependencies

planning/behavior_path_planner/config/lane_change/lane_change.param.yaml, planning/behavior_path_planner/include/behavior_path_planner/parameters.hpp, planning/behavior_path_planner/include/behavior_path_planner/util/lane_change/lane_change_module_data.hpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp, planning/behavior_path_planner/src/scene_module/avoidance_by_lc/module.cpp, planning/behavior_path_planner/src/scene_module/lane_change/external_request_lane_change_module.cpp, planning/behavior_path_planner/src/scene_module/lane_change/lane_change_module.cpp, planning/behavior_path_planner/src/util/lane_change/util.cpp, planning/behavior_path_planner/src/utilities.cpp
Rename lane change parameters name
Related Link
https://github.com/autowarefoundation/autoware_launch/pull/282
=> refactor(behavior_path_planner): rename lane change parameters

planning/mission_planner/package.xml
add @kosuke55 and @purewater0901 to `mission_planner` code owners
not tested
=> chore(mission_planner): add code owners

common/component_interface_specs/package.xml
=> chore(component_interface_specs): update maintainers

perception/traffic_light_ssd_fine_detector/README.md
- In pre-commit optional, outdated link occurs error below. So I fixed link.
- I got this link from @Mingyu1991 in [TIER IV INTERNAL LINK](https://star4.slack.com/archives/C4P0NSMB5/p1681203514104599?thread_ts=1681202837.414059&cid=C4P0NSMB5)
```
FILE: perception/traffic_light_ssd_fine_detector/README.md
[✓] https://github.com/qfgaohao/pytorch-ssd
[✖] https://storage.googleapis.com/models-hao/mb2-ssd-lite-mp-0_686.pth
[✓] https://drive.google.com/uc?id=1USFDPRH9JrVdGoqt27qHjRgittwc0kcO
3 links checked.
ERROR: 1 dead links found!
[✖] https://storage.googleapis.com/models-hao/mb2-ssd-lite-mp-0_686.pth → Status: 404
```
The PR author …
=> docs(traffic_light_ssd_fine_detector): fix outdated link

planning/behavior_path_planner/src/scene_module/avoidance_by_lc/module.cpp
fix build error.
```
/home/satoshi/pilot-auto/src/autoware/universe/planning/behavior_path_planner/src/scene_module/avoidance_by_lc/module.cpp: In member function ‘std::pair<bool, bool> behavior_path_planner::AvoidanceByLCModule::getSafePath(const ConstLanelets&, double, behavior_path_planner::LaneChangePath&) const’:                                                                                                                      
/home/satoshi/pilot-auto/src/autoware/universe/planning/behavior_path_planner/src/scene_module/avoidance_by_lc/module.cpp:653:32: error: ‘utils’ has not been declared …
```
=> fix(avoidance_by_lc): fix build error

planning/behavior_path_planner/include/behavior_path_planner/util/avoidance/avoidance_module_data.hpp, planning/behavior_path_planner/include/behavior_path_planner/util/avoidance/util.hpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp, planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp, planning/behavior_path_planner/src/util/avoidance/util.cpp
The avoidance module has some buffer parameters for avoidance path generation.
- lateral buffer
- longitudinal buffer
- envelope polygon buffer
In this PR, it is able to set these parameters independently for each class (e.g. pedestrian, bus, motorcycle).
:arrow_down: It should be merged before this PR.
https://github.com/autowarefoundation/autoware_launch/pull/286
https://github.com/autowarefoundation/autoware_launch/pull/286
```yaml
pedestrian:
enable: true
envelope_buffer_margin: 0.8
safety_buffer_lateral: 1.0
safety_buffer_longitudinal: 1.0
```
```yaml
bus:
enable: true
envelope_buffer_margin: 0.3
safety_buffer_lateral: 0.7
safety_buffer_longitudinal: 0.0
``` …
=> feat(avoidance): margin can be set independently for each class

planning/planning_test_utils/package.xml
=> chore(planning_test_utils): add maintainer

planning/behavior_path_planner/include/behavior_path_planner/planner_manager.hpp, planning/behavior_path_planner/src/planner_manager.cpp
refactoring new planner manager.
[[TIER IV INTERNAL LINK]](https://evaluation.tier4.jp/evaluation/reports/00598a6a-b608-59d8-85bf-45b90945b0bf?project_id=prd_jt) This PR 1326/1329
[[TIER IV INTERNAL LINK]](https://evaluation.tier4.jp/evaluation/reports/afbc9e46-7960-5a79-ba55-8de13f4d6843?project_id=prd_jt) Baseline 1326/1329 …
=> refactor(planner_manager): cleanup code

planning/behavior_velocity_planner/config/intersection.param.yaml, planning/behavior_velocity_planner/include/scene_module/intersection/scene_intersection.hpp, planning/behavior_velocity_planner/src/scene_module/intersection/manager.cpp, planning/behavior_velocity_planner/src/scene_module/intersection/scene_intersection.cpp
Organized param file for intersection module for readability
launcher PR: https://github.com/autowarefoundation/autoware_launch/pull/297
Both intersection/merge_from_private module works without throwing ros parameter exceptions.
None
=> refactor(behavior_velocity_planner::intersection): organize param intersection

perception/traffic_light_classifier/README.md
- In pre-commit optional,  link to non-existent file occurs error below. So I fixed it.
```
FILE: perception/traffic_light_classifier/README.md
[✓] https://en.wikipedia.org/wiki/Vienna_Convention_on_Road_Signs_and_Signals#Traffic_lights
[✓] https://gitlab.com/autowarefoundation/autoware.auto/autoware_auto_msgs/-/merge_requests/16
[✓] https://arxiv.org/abs/1801.04381v3
[✖] ./data/traffic_light_classifier_mobilenetv2.onnx
[✓] https://arxiv.org/abs/1905.11946v5
[✓] https://openaccess.thecvf.com/content_cvpr_2016/html/He_Deep_Residual_Learning_CVPR_2016_paper.html
[✓] https://arxiv.org/abs/1905.02244
[✓] https://github.com/open-mmlab/mmclassification.git
[✓] https://mmclassification.readthedocs.io/en/latest/
[✓] https://mmclassification.readthedocs.io/en/latest/faq.html
[✓] …
```
=> docs(traffic_light_classifier): remove link

perception/traffic_light_classifier/README.md, perception/traffic_light_classifier/package.xml
- I fixed typo.
```
❯ cspell perception/traffic_light_classifier/README.md
1/1 ./perception/traffic_light_classifier/README.md 294.36ms
CSpell: Files checked: 1, Issues found: 0 in 0 files
```
=> docs(traffic_light_classifier): fix typo

planning/planning_test_utils/include/planning_interface_test_manager/planning_interface_test_manager.hpp
Remove no implemented functions
=> fix(planning_test_utils): remove unused declaration

planning/scenario_selector/include/scenario_selector/scenario_selector_node.hpp, planning/scenario_selector/src/scenario_selector_node/scenario_selector_node.cpp
change ego positioin source from tf to odom
=> feat(scenario_selector): change ego positioin source from tf to odom

system/default_ad_api/package.xml, system/default_ad_api_helpers/ad_api_adaptors/package.xml, system/default_ad_api_helpers/ad_api_visualizers/package.xml, system/default_ad_api_helpers/automatic_pose_initializer/package.xml
add @yukkysaito to default_ad_api maintainers
sort names
=> chore(default_ad_api): add yukkysaito and mitsudome-r to maintainer

perception/lidar_apollo_segmentation_tvm/package.xml, perception/lidar_apollo_segmentation_tvm_nodes/package.xml
Add maintainer to `lidar_apollo_segmentation_tvm` and `lidar_apollo_segmentation_tvm_node`
Relates to #3378 
=> chore(lidar_apollo_segmentation_tvm): add maintainer

perception/probabilistic_occupancy_grid_map/laserscan-based-occupancy-grid-map.md
I changed link to paper in Internet archive because we can find original paper published in IEEE.
=> docs(probabilistic_occupancy_grid_map): change link to official link in IEEE

planning/mission_planner/src/mission_planner/mission_planner.cpp
Pass the `allow_goal_modification` of the API to the planning internal route.
https://github.com/autowarefoundation/autoware_adapi_msgs/pull/30,
psim 
=> feat(mission_planner): inherit allow_goal_modification

planning/planning_test_utils/include/planning_interface_test_manager/planning_interface_test_manager.hpp, planning/planning_test_utils/include/planning_interface_test_manager/planning_interface_test_manager_utils.hpp, planning/planning_test_utils/src/planning_interface_test_manager.cpp
- remove unused declarations
- add comment
=> refactor(planning_test_utils): minor refactor and add comments

planning/behavior_path_planner/config/pull_over/pull_over.param.yaml
related to https://github.com/autowarefoundation/autoware.universe/pull/3363#discussion_r1170213448, use same pull over params as launcher
https://github.com/autowarefoundation/autoware.universe/pull/3363
psim, scenario test(test with the same value of launcher)
=> feat(behavior_path_planner): use same pull over params as launcher

planning/behavior_path_planner/CMakeLists.txt, planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/base_class.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/bt_normal.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/interface.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/lane_change_module.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_visitor.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/utils.hpp, planning/behavior_path_planner/src/scene_module/lane_change/bt_normal.cpp, planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp, planning/behavior_path_planner/src/scene_module/lane_change/lane_change_module.cpp, planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp, planning/behavior_path_planner/src/utils/lane_change/utils.cpp
To reduce code duplication in the lane change module, it is necessary to standardize the implementation of all lane change related functions. However, this task is challenging because the module currently integrates both the interface and the implementation. Therefore, to enhance maintainability by eliminating code duplication, the proposed PR will divide the interface and implementation of the lane change module.
https://github.com/autowarefoundation/autoware.universe/pull/3453
- #3453 needs to be merge first (DONE)
- Interface code are still duplicating, and another PR will be made to solve this.
- Avoidance by lane change and old external request lane change also has duplicates, another PRs will be made to solve this.
No effects on the Autoware interfaces, as this is changes in the …
=> refactor(lane_change): separate implementation and interface 2

planning/mission_planner/config/mission_planner.param.yaml, planning/mission_planner/src/mission_planner/mission_planner.cpp, planning/mission_planner/src/mission_planner/mission_planner.hpp
Add a function that checks reroute safety
https://github.com/autowarefoundation/autoware_launch/pull/306
In this PR, I only add a single function, and I did not use the function with the current implementation.
No interface changes
No effects
=> feat(mission_planner): add safety check function

planning/obstacle_avoidance_planner/README.md
add title in readme to follow other modules
=> docs(obstacle_avoidance_planner): add title in readme

perception/compare_map_segmentation/package.xml, perception/detected_object_validation/package.xml, perception/detection_by_tracker/package.xml, perception/map_based_prediction/package.xml, perception/multi_object_tracker/package.xml, perception/object_merger/package.xml, perception/occupancy_grid_map_outlier_filter/package.xml, perception/probabilistic_occupancy_grid_map/package.xml, perception/shape_estimation/package.xml
Add maintainer to perception packages
=> chore: add maintainer to perception packages

planning/behavior_path_planner/src/scene_module/pull_out/pull_out_module.cpp
add pull out debug markers
psim
=> feat(behavior_path_planenr): add pull out debug marker

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp, planning/behavior_path_planner/src/utils/avoidance/util.cpp, planning/behavior_path_planner/src/utils/utils.cpp
Fix degration in https://github.com/autowarefoundation/autoware.universe/pull/3350.
Fill object's stop time.
Psim
If `enable_force_avoidance_for_stopped_vehicle` is set as true, ego executes force avoid depending on the object's stop time.
=> fix(avoidance): fix but in moving time calculation logic

common/motion_utils/include/motion_utils/marker/marker_helper.hpp, common/motion_utils/src/marker/marker_helper.cpp, planning/behavior_velocity_planner/src/scene_module/blind_spot/debug.cpp, planning/behavior_velocity_planner/src/scene_module/crosswalk/debug.cpp, planning/behavior_velocity_planner/src/scene_module/detection_area/debug.cpp, planning/behavior_velocity_planner/src/scene_module/intersection/debug.cpp, planning/behavior_velocity_planner/src/scene_module/no_stopping_area/debug.cpp, planning/behavior_velocity_planner/src/scene_module/run_out/debug.cpp, planning/behavior_velocity_planner/src/scene_module/stop_line/debug.cpp, planning/behavior_velocity_planner/src/scene_module/virtual_traffic_light/debug.cpp
Fixes https://github.com/autowarefoundation/autoware.universe/issues/3138
=> fix(motion_utils): improve mechanism to delete virtual wall markers

common/motion_utils/include/motion_utils/trajectory/trajectory.hpp, common/motion_utils/test/src/trajectory/test_trajectory.cpp
add `calcYawDeviation` to motion_utils to calculate deviation from path to a pose
psim
=> feat(motion_utils): add calcYawDeviation

planning/static_centerline_optimizer/src/static_centerline_optimizer_node.cpp
When we launch static centerline optimizer with vector map builder, `evaluate` function is not called and thus RViz does not show `debug/unsafe_footprints`.
This PR fixes this by moving the `evaluate` function.
I tested this by planning path with vector map builder and `debug/unsafe_footprints` is appeared on RViz.
Nothing because this is for debug topic. …
=> fix(static_centerline_optimizer): show unsafe footprints with vector map builder

common/autoware_ad_api_specs/package.xml, common/component_interface_utils/package.xml
Update codeowners/maintainers.
=> chore: update codeowners

planning/behavior_velocity_planner/include/scene_module/intersection/scene_intersection.hpp, planning/behavior_velocity_planner/src/scene_module/intersection/debug.cpp, planning/behavior_velocity_planner/src/scene_module/intersection/manager.cpp
I fixed the visualizer to show all virtual wall markers from intersection module.
=> feat(intersection): fixed virtual wall visualization

planning/obstacle_stop_planner/src/node.cpp
fix the error of `"Segment index is invalid."` when the ego is at the goal.
https://github.com/autowarefoundation/autoware.universe/blob/main/common/motion_utils/include/motion_utils/trajectory/trajectory.hpp#L310
psim
=> fix(obstacle_stop_planner): fix error at goal

planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/pull_over_module.hpp, planning/behavior_path_planner/src/scene_module/pull_over/pull_over_module.cpp
prevent pull over path chattering by adding path update duration.
[tier4 internal ticket](https://tier4.atlassian.net/browse/RT1-2164)
psim, lsim
no
prevent pull over path chatering
=> fix(behavior_path_planner): prevent pull over chattering

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
Update same grad filter parameter for two step avoidance.
Related PR
- https://github.com/autowarefoundation/autoware.universe/pull/3160
Tight same grad filter threshold makes it hard to combine two shift lines (red boxed shift line).
https://user-images.githubusercontent.com/44889564/234252517-36345ad9-f0df-4a35-b4bd-a23c37df51f7.mp4
Relax filter threshold to make it easier to merge two shift lines.
https://user-images.githubusercontent.com/44889564/234252452-8c9bc7c3-946d-441a-8a62-ede64d507978.mp4
Psim&Evaluator&Real Vehicle
Improve two step avoidance. …
=> fix(avoidance): tuning same grad filter parameter

planning/behavior_path_planner/include/behavior_path_planner/scene_module/pull_over/pull_over_module.hpp, planning/behavior_path_planner/src/scene_module/pull_over/pull_over_module.cpp
not plan freespace pull over path after arrinving goal.
[tier4 internal ticket](https://tier4.atlassian.net/browse/RT1-2165)
psim
no
no (just prevent generating path after arriving goal which is not used for drving)
=> fix(behavior_path_planner): prevent replanning freespace pull over path after arriving goal

planning/behavior_path_planner/include/behavior_path_planner/planner_manager.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_interface.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_manager_interface.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/avoidance_module_data.hpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp, planning/behavior_path_planner/src/behavior_tree_manager.cpp, planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
In this PR, I added interface to publish virttual wall.
`/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/virtual_wall/MODULE_NAME`
- https://github.com/autowarefoundation/autoware_launch/pull/325
Psim
Show virtual wall in Rviz.
output virtual wall as following topic name.
`/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/virtual_wall/MODULE_NAME`
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contri …
=> feat(behaivor_path_planner): output virtual wall

planning/behavior_path_planner/config/behavior_path_planner_tree.xml, planning/behavior_path_planner/config/behavior_path_planner_tree_lane_change_only.xml, planning/behavior_path_planner/config/behavior_path_planner_tree_lane_change_only_old.xml, planning/behavior_path_planner/config/behavior_path_planner_tree_old.xml, planning/behavior_path_planner/config/behavior_path_planner_tree_pull_out.xml, planning/behavior_path_planner/config/behavior_path_planner_tree_with_external_request_LC.xml
for fixing test
```
4: [ RUN      ] PlanningModuleInterfaceTest.NodeTestWithExceptionRoute
4: [INFO] [1682491372.661798961] [behavior_path_planner]: use behavior tree.
Error: OR] [1682491372.677759528] [behavior_path_planner.behavior_tree_manager]: Failed to create BT from: /__w/autoware.universe/autoware.universe/install/behavior_path_planner/share/behavior_path_planner/config/behavior_path_planner_tree.xml
```
build, test in local
no
no …
=> fix(behavior_path_planner): fix bt tree xml

planning/behavior_path_planner/CMakeLists.txt
sorry:bow:
fix behavior path new archi build. pull_over is remained in cmake for new archi.
local build 
no
no
=> fix(behavior_path_planner): fix new behavior_path build

planning/behavior_path_planner/CMakeLists.txt, planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/utils.hpp, planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp, planning/behavior_path_planner/src/scene_module/avoidance_by_lc/module.cpp, planning/behavior_path_planner/src/utils/avoidance/utils.cpp, planning/behavior_path_planner/test/test_avoidance_utils.cpp
=> refactor(avoidance): rename util to utils

planning/obstacle_stop_planner/package.xml
Add maintainer myself to package.xml file.
=> refactor(obstacle_stop_planner): update package xml

planning/behavior_path_planner/README.md, planning/behavior_path_planner/docs/behavior_path_planner_manager_design.md, planning/behavior_path_planner/image/manager/approved_modules_stack.svg, planning/behavior_path_planner/image/manager/candidate_modules_stack.svg, planning/behavior_path_planner/image/manager/failure_modules.svg, planning/behavior_path_planner/image/manager/lane_change_remove.svg, planning/behavior_path_planner/image/manager/lane_change_skip.svg, planning/behavior_path_planner/image/manager/manager_overview.svg, planning/behavior_path_planner/image/manager/process_step1.svg, planning/behavior_path_planner/image/manager/process_step2.svg, planning/behavior_path_planner/image/manager/process_step4.svg, planning/behavior_path_planner/image/manager/process_step5.svg, planning/behavior_path_planner/image/manager/process_step6.svg, planning/behavior_path_planner/image/manager/scene_module.svg, planning/behavior_path_planner/image/manager/sub_managers.svg, planning/behavior_path_planner/image/manager/success_modules_remove.svg, planning/behavior_path_planner/image/manager/success_modules_skip.svg, planning/behavior_path_planner/image/manager/waiting_approve.svg
Create documentation for NEW manager.
Nothing.
Nothing.
=> docs(behaivor_path_planner): add documentation for new planner manager

planning/behavior_path_planner/src/marker_util/avoidance/debug.cpp, planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
- set incorrect namespace, scale and color in for loop.
- remove unnecessary marker (`unavoidable_objects`).
Psim
Nothing.
=> fix(avoidance): fix bug in debug marker generation

planning/behavior_path_planner/CMakeLists.txt, planning/behavior_path_planner/src/utils/safety_check.cpp, planning/behavior_path_planner/test/test_lane_change_utils.cpp
Shorten `pointToSegment` function
=> refactor(behavior_path_planner): shorten pointToSegment function

planning/behavior_path_planner/include/behavior_path_planner/behavior_tree_manager.hpp, planning/behavior_path_planner/include/behavior_path_planner/planner_manager.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/utils.hpp, planning/behavior_path_planner/src/behavior_tree_manager.cpp, planning/behavior_path_planner/src/planner_manager.cpp, planning/behavior_path_planner/src/utils/utils.cpp
`pull_out` can not be executed due to https://github.com/autowarefoundation/autoware.universe/pull/3075
In this PR, check the ego is shoulder lane not only road lane
https://github.com/autowarefoundation/autoware.universe/pull/3075
psim
wip [tier4 scenario test](https://evaluation.tier4.jp/evaluation/reports/8c12c7c2-f127-5d60-93ca-cc6f6bcf8b3c/?project_id=prd_jt)
note that if putting the goal near ego, pull out can not be executed because of `goal_planner`, this is limitation of behavior path old architecture. this will be supported in behaivor path new architecture with https://github.com/autowarefoundation/autoware.universe/pull/3574 
no
pull out can be executed …
=> fix(behavior_path_planner): check ego is in shoulder lane when creating goal around path

.github/sync-files.yaml, planning/behavior_path_planner/docs/behavior_path_planner_interface_design.md
add config to sync mkdocs.yaml between https://github.com/autowarefoundation/autoware-documentation and https://github.com/autowarefoundation/autoware.universe.
https://github.com/autowarefoundation/autoware.universe/pull/3622 is generated by [this](https://github.com/autowarefoundation/autoware.universe/actions/runs/4878574654) action.
Nothing. …
=> chore(sync): sync mkdocs.yaml

.pages
=> docs(.pages): ignore top-level documents for better visibility

planning/obstacle_velocity_limiter/test/test_obstacle_velocity_limiter_node_interface.cpp
=> test(obstacle_velocity_limiter): add off-track test

planning/planning_validator/test/src/test_planning_validator_node_interface.cpp
=> test(planning_validator): add off-track test

control/mpc_lateral_controller/src/qp_solver/qp_solver_osqp.cpp, planning/motion_velocity_smoother/src/smoother/jerk_filtered_smoother.cpp, planning/motion_velocity_smoother/src/smoother/l2_pseudo_jerk_smoother.cpp, planning/motion_velocity_smoother/src/smoother/linf_pseudo_jerk_smoother.cpp, planning/obstacle_avoidance_planner/src/eb_path_smoother.cpp, planning/obstacle_avoidance_planner/src/mpt_optimizer.cpp, planning/obstacle_cruise_planner/src/optimization_based_planner/velocity_optimizer.cpp
Closes https://github.com/autowarefoundation/autoware.universe/issues/3040
Tested on many scenarios and did not find any issue.
Evaluation platform (private TIER IV link): https://evaluation.tier4.jp/evaluation/reports/3ca173ae-b970-521e-9ccd-6060280fb62a?project_id=prd_jt
Prevent crashes when the optimization with OSQP returns NaN values. …
=> feat: handle NaNs when using OSQP

planning/behavior_path_planner/docs/behavior_path_planner_interface_design.md, planning/behavior_path_planner/docs/behavior_path_planner_manager_design.md, planning/behavior_path_planner/image/manager/avoidance.svg, planning/behavior_path_planner/image/manager/example_behavior.svg, planning/behavior_path_planner/image/manager/lane_change.svg, planning/behavior_path_planner/image/manager/module_select.svg, planning/behavior_path_planner/image/manager/multiple_candidates.svg, planning/behavior_path_planner/image/manager/output_module.svg, planning/behavior_path_planner/image/manager/request_step1.svg, planning/behavior_path_planner/image/manager/request_step2-2.svg, planning/behavior_path_planner/image/manager/request_step2-3.svg, planning/behavior_path_planner/image/manager/request_step2.svg, planning/behavior_path_planner/image/manager/request_step3.svg, planning/behavior_path_planner/image/manager/request_step4-2.svg, planning/behavior_path_planner/image/manager/request_step4-3.svg, planning/behavior_path_planner/image/manager/request_step4.svg, planning/behavior_path_planner/image/manager/request_step5.svg, planning/behavior_path_planner/image/manager/root_generation.svg, planning/behavior_path_planner/image/manager/root_lanelet.svg
Add some new figures in manager document.
https://autowarefoundation.github.io/autoware.universe/pr-3614/
Nothing.
=> docs(behavior): update planner manager document

planning/behavior_path_planner/src/utils/avoidance/utils.cpp
- use lowest instead of min
Psim
Improve avoidance target filtering behavior.
=> fix(avoidance): use lowest instead of min

map/map_loader/README.md
Fix readme in map_loader
Update the example map directory structure to the one that the current Autoware (as default) assumes
Not applicable
None
=> fix(map_loader): fix readme

perception/traffic_light_ssd_fine_detector/README.md
Add document to apply ML model trained with [open-mmlab/mmdetection](https://github.com/open-mmlab/mmdetection).
This PR should be merged after https://github.com/autowarefoundation/autoware.universe/pull/3485
=> docs(traffic_light_ssd_fine_detector): add document for training model with mmdetection

planning/planning_test_utils/include/planning_interface_test_manager/planning_interface_test_manager_utils.hpp
before this change node is not associated with executor.
By explicitly associate executor with node, error was solved. 
Confirmed test success in local environment.
=> fix(behavior_path_planner): fix executor association with node

planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_manager_interface.hpp
Currently, there is a issue that behavior_path_planner process dies due to invalid access to null idling_module_.
This issue occurs frequently when the goal is re-set after parking on the shoulder. 
I fixed it.
I confirmed that the behavior_path_planner process does not die even if the goal pose is set after parking on the road shoulder.
https://github.com/autowarefoundation/autoware.universe/assets/59680180/9fab1951-cde3-4949-bd90-b9553890055e
no
The behavior planner process becomes not to die in the above situation. …
=> fix(behavior_path_planner): fix invalid access to idling_module

planning/behavior_path_planner/src/utils/utils.cpp
fix the bug that `pull_out` can not be done after `goal_planner`. this is caused by using previous modified_goal for checking `isEgoOutOfRoute` and generating stop path.
https://github.com/autowarefoundation/autoware.universe/assets/39142679/af9deb80-ac2a-4141-898a-c436ce20c5e4
In this PR, check the uuid of modified_goal.
psim
https://github.com/autowarefoundation/autoware.universe/assets/39142679/6821200b-396e-4f7f-af62-a3ddd263cdb6 …
=> fix(behavior_path_planner): check modified goal uuid in isEgoOutOfRoute

planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp, planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
rafactoring goal_planner by 
- split functions 
- remove unnecessary processes
- common proccess
- add explanation 
- categorize functions and variables
psim
~~wip tier4 internal scenario tests https://evaluation.tier4.jp/evaluation/reports/f15507de-0d9f-5c16-9d36-07f42866f829/?project_id=prd_jt~~
https://evaluation.tier4.jp/evaluation/reports/e1e9ba80-66d2-5172-82e5-529193879630?project_id=prd_jt
1321/1350
not applicable
not applicable …
=> refactor(behavior_path_planner): refactoring goal_planner

planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp
Ignore avoiding dynamic obstacles which will cut into the ego lane.
The figure shows obstacles that will cut into the ego lane, so the ego does not avoid.
Ignore cut-in vehicles when avoiding dynamic obstacles.
=> feat(dynamic_avoidance): ignore cut-in vehicles

control/control_performance_analysis/include/control_performance_analysis/control_performance_analysis_core.hpp, control/control_performance_analysis/src/control_performance_analysis_core.cpp
This PR has three changes:
- (main) To fix interpolation issue, replace implementation with motion_utils
- (minor) To fix process die issue, add a guard when closest idx search is failed
- (minor) use autoware_utils for calcDistance2d
Sometimes the interpolated pose diverges, especially for yaw angle as in the video. (the big moving axis is the interpolated pose, visualized for debug)
https://github.com/autowarefoundation/autoware.universe/assets/21360593/62eb6d8f-7717-4b44-b379-f10502106880
The cause is the way of the interpolation. For example, the `ratio` value which must be in the range of 0 ~ 1 gets 10 or 100 sometimes.
I replaced the method with motion_utils and confirmed it is fixed.
https://github.com/autowarefoundation/autoware.universe/assets/21360593/556c5876-80b4-4484-b61d-1e6b …
=> fix(control_performance_analysis): fix interpolate method

planning/behavior_path_planner/src/marker_util/avoidance/debug.cpp
Output `Marker::CYLINDER` type marker for following small objects.
- PEDESTRIAN
- MOTORCYCLE
- BICYCLE
- UNKNOWN
Befor this PR, the module outputs `Marker::CUBE` for those small objects.
Psim
Nothing.
=> feat(avoidance): output cylinder type marker for small objects

planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp
avoid backward obstacle overtaking the ego
[Screencast from 2023年05月11日 23時20分19秒.webm](https://github.com/autowarefoundation/autoware.universe/assets/20228327/93927bbe-9ad4-475f-9b24-b1622c451379)
Nothing
=> feat(dynamic_avoidance): avoid backward obstacle

planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_manager_interface.hpp
Initialize module at the moment of registering.
Nothing.
=> fix(behavior_path_planner): init idling module

planning/behavior_velocity_planner/src/scene_module/intersection/scene_intersection.cpp
Added guard for bad optional access
Psim and experiment
=> fix(intersection): fixed bad optional access

planning/behavior_path_planner/src/utils/path_utils.cpp
keep terminal point in resamplePathWithSpline
psim
not applicable
not applicable
=> fix(behavior_path_planner): keep terminal point in resamplePathWithSpline

planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp, planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
goal planner can be approved after running the module once, so cancel the module and request approval again at the appropriate time. (if the ego is far from the goal)
This PR allows for approval only at the appropriate time(after the path is decided).
[tier4 internal ticket](https://tier4.atlassian.net/browse/RT1-232?search_id=0442ed52-8b5a-47a9-a0b2-09c67785b3e3)
psim
https://github.com/autowarefoundation/autoware.universe/assets/39142679/1c9f3ad3-02f9-42ad-8bf9-2f1a51283f2c
not applicable
not applicable …
=> feat(behavior_path_planner): request approval after deciding path in goal_planner

planning/behavior_velocity_planner/src/scene_module/crosswalk/debug.cpp
https://github.com/autowarefoundation/autoware.universe/pull/3654
I fixed the same problem as crosswalk module in the walkway module.
https://github.com/autowarefoundation/autoware.universe/pull/3654
Before
After
no
no
All walkway virtual wall can be visualized  in Rviz.
=> fix(behavior_velocity_planner): fixed walkway virtual wall marker id duplication

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
Update avoidance velocity if the ego is faster than last saved velocity in order to prevent sudden brake.
Psim
Prevent sudden brake.
=> fix(avoidance): update ego avoidance velocity if the ego is faster than saved velocity

common/motion_utils/src/resample/resample.cpp
=> fix(motion_utils): fix resample index

planning/behavior_path_planner/src/marker_util/avoidance/debug.cpp
- use magic enum
Psim
Nothing.
=> refactor(avoidance): use magic enum

common/qp_interface/CMakeLists.txt, common/qp_interface/design/qp_interface-design.md, common/qp_interface/include/qp_interface/osqp_csc_matrix_conv.hpp, common/qp_interface/include/qp_interface/osqp_interface.hpp, common/qp_interface/include/qp_interface/qp_interface.hpp, common/qp_interface/package.xml, common/qp_interface/src/osqp_csc_matrix_conv.cpp, common/qp_interface/src/osqp_interface.cpp, common/qp_interface/src/qp_interface.cpp, common/qp_interface/test/test_csc_matrix_conv.cpp, common/qp_interface/test/test_osqp_interface.cpp
To deal with multiple QP solvers, I created a `qp_interface` package.
The existing `osqp_interface` package will be replaced with this package soon.
Unit test
=> feat(qp_interface): add new package which will contain various qp solvers

perception/bytetrack/package.xml
This is a backport of https://github.com/autowarefoundation/autoware.universe/pull/3280
=> backport: build(bytetrack): add missing dependencies

common/autoware_auto_geometry/package.xml
=> chore(autoware_auto_geometry): add maintainer

planning/obstacle_velocity_limiter/include/obstacle_velocity_limiter/obstacle_velocity_limiter_node.hpp, planning/obstacle_velocity_limiter/src/obstacle_velocity_limiter_node.cpp
In current implementation, ```current_odometry_ptr_``` is used at ```motion_utils::findNearestIndex(msg->points, current_odometry_ptr_->pose.pose)``` before valid input check (```validInputs()```).
Therefore, it is possible to cause a null pointer access. I fixed it.
no
I cofimred that the build successed and autoware launched.
no
no
no …
=> fix(obstacle_velicity_limiter): fix invalid access to odometry pointer

planning/obstacle_stop_planner/README.md
fix following error.
**[CI check](https://github.com/autowarefoundation/autoware.universe/actions/runs/5010923551/jobs/8981234512?pr=3746)**
Nothing.
=> docs(obstacle_stop_planner): fix dead link error in pre-commit optional

.markdown-link-check.json, common/autoware_auto_geometry/design/polygon_intersection_2d-design.md
=> docs(autoware_auto_geometry): fix link to paper

common/qp_interface/CMakeLists.txt, common/qp_interface/include/qp_interface/osqp_interface.hpp, common/qp_interface/include/qp_interface/proxqp_interface.hpp, common/qp_interface/include/qp_interface/qp_interface.hpp, common/qp_interface/package.xml, common/qp_interface/src/osqp_interface.cpp, common/qp_interface/src/proxqp_interface.cpp, common/qp_interface/src/qp_interface.cpp, common/qp_interface/test/test_osqp_interface.cpp, common/qp_interface/test/test_proxqp_interface.cpp
depends on https://github.com/autowarefoundation/autoware.universe/pull/3697
Support proxqp in qp_interface
https://github.com/Simple-Robotics/proxsuite
Unit test
=> feat(qp_interface): support proxqp

planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_manager_interface.hpp
- reset idling module in delete function.
Nothing.
=> fix(behavior_path_planner): reset idling module

planning/behavior_path_planner/include/behavior_path_planner/planner_manager.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_interface.hpp, planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp, planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp, planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp, planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp, planning/behavior_path_planner/src/scene_module/lane_following/lane_following_module.cpp, planning/behavior_path_planner/src/scene_module/pull_out/pull_out_module.cpp, planning/behavior_path_planner/src/scene_module/scene_module_bt_node_interface.cpp, planning/behavior_path_planner/src/scene_module/side_shift/side_shift_module.cpp
The returned type of `updateState` is [discarded](https://github.com/autowarefoundation/autoware.universe/blob/e4fefd4c1312e59d4c2d041a6a8d41b1265ef2b6/planning/behavior_path_planner/include/behavior_path_planner/planner_manager.hpp#L185) in planner_manager,
and if the implementation of `updateState` didn't update the member variable `current_state_`,
the states will not be updated in new architecture.
To solve this issue, the `updateCurrentState` setter is introduced to update the `current_state_` explicitly.
None
1. Compile with OLD and NEW architecture.
2. Testing with CI (OLD) - [TIER IV INTERNAL LINK](https://evaluation.tier4.jp/evaluation/reports/e1c1ac7e-0c3c-569a-9544-89ae76f542bd?project_id=prd_jt)
3. Testing with CI (NEW) - [TIER IV INTERNAL …
=> fix(behavior_path_planner): use setter to set current_state_

planning/behavior_velocity_planner/include/scene_module/intersection/scene_intersection.hpp, planning/behavior_velocity_planner/include/scene_module/intersection/util.hpp, planning/behavior_velocity_planner/src/node.cpp, planning/behavior_velocity_planner/src/scene_module/detection_area/scene.cpp, planning/behavior_velocity_planner/src/scene_module/intersection/debug.cpp, planning/behavior_velocity_planner/src/scene_module/intersection/scene_intersection.cpp, planning/behavior_velocity_planner/src/scene_module/intersection/util.cpp, planning/behavior_velocity_planner/src/utilization/util.cpp
- FIx typos in `behavior_velocity_planner`
- Modify some variable names in `behavior_velocity_planner` to avoid cspell errors 
=> chore(typo/cspell): fix typos and cscpell errors in `behavior_velocity_planner`

planning/behavior_path_planner/src/utils/utils.cpp
In the pull-over module, backward long path (e.g. The internal path length in the figure is 33 meters.)  is used when creating the drivable area, which causes the wrong nearest index search on the U-turn.
without the PR
with the PR
can pull over in U-turn
=> fix(behavior_path_planner): generate drivable area for long backward path

planning/behavior_velocity_intersection_module/src/manager.cpp, planning/behavior_velocity_intersection_module/src/scene_intersection.cpp, planning/behavior_velocity_intersection_module/src/scene_intersection.hpp, planning/behavior_velocity_planner/config/intersection.param.yaml
add the option to use intersection_area
parameter PR: https://github.com/autowarefoundation/autoware_launch/pull/366
=> feat(intersection): add the option to use intersection_area

planning/behavior_velocity_intersection_module/src/debug.cpp, planning/behavior_velocity_intersection_module/src/scene_intersection.cpp, planning/behavior_velocity_intersection_module/src/scene_intersection.hpp, planning/behavior_velocity_intersection_module/src/util.cpp
Define the pass judge line as the line which is before the point where the path intersects the upcoming lane by braking distance.
https://tier4.atlassian.net/browse/RT1-1890
intersection scenario passes https://evaluation.tier4.jp/evaluation/reports/8f4eeb55-08e2-5778-adfe-bd5694b6d3f0?project_id=prd_jt …
=> fix(intersection): decide go/stop by checking pass judge 

launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.py, planning/behavior_path_planner/include/behavior_path_planner/behavior_path_planner_node.hpp, planning/behavior_path_planner/include/behavior_path_planner/planner_manager.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_interface.hpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp, planning/behavior_path_planner/src/behavior_tree_manager.cpp, planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
- Output stop reason from `behavior_path_planner` modules.
- This PR should be merged after https://github.com/tier4/tier4_autoware_msgs/pull/89
[TIER IV INTERNAL TICKET](https://tier4.atlassian.net/browse/RT1-2465)
Show stop reason & distance (only `avoidance`)
=> feat(behavior_path_planner): output stop reasons

common/bag_time_manager_rviz_plugin/src/bag_time_manager_panel.cpp, common/rtc_manager_rviz_plugin/src/rtc_manager_panel.cpp, common/tier4_automatic_goal_rviz_plugin/src/automatic_goal_sender.cpp, common/tier4_control_rviz_plugin/src/tools/manual_controller.cpp, common/tier4_state_rviz_plugin/src/autoware_state_panel.cpp, control/joy_controller/src/joy_controller/joy_controller_node.cpp, localization/ndt_scan_matcher/src/map_update_module.cpp, planning/rtc_auto_mode_manager/src/rtc_auto_mode_manager_interface.cpp, planning/rtc_replayer/src/rtc_replayer_node.cpp
related to https://github.com/autowarefoundation/autoware.universe/pull/2783#discussion_r1094858025
=> build(iron): remove rmw_qos_profile_t

planning/mission_planner/README.md, planning/mission_planner/config/mission_planner.param.yaml, planning/mission_planner/src/mission_planner/mission_planner.cpp, planning/mission_planner/src/mission_planner/mission_planner.hpp
Add a minimum checking length to prevent the new goal from being too close from the current ego position.
[Launch PR](https://github.com/autowarefoundation/autoware_launch/pull/370)
=> feat(mission_planner): add minimum checking length

planning/mission_planner/src/mission_planner/mission_planner.cpp, planning/mission_planner/src/mission_planner/mission_planner.hpp
This reverts commit 358d4a7a31272868231951d5ecd73a4d5924a7cf.
https://github.com/autowarefoundation/autoware.universe/pull/3821 changed API behavior, so revert this.
We need to discuss this more.
https://github.com/autowarefoundation/autoware.universe/pull/3821
not tested
no applicable
no applicable
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/ …
=> fix(mission_planner): revert add mrm reroute (#3821)

planning/behavior_velocity_out_of_lane_module/src/scene_out_of_lane.cpp
Fix use of the `VirtualWallMarkerCreator`.
Tested in the planning simulation.
=> fix(behavior_velocity_out_of_lane_module): fix virtual wall markers

planning/behavior_velocity_blind_spot_module/src/debug.cpp
Fixed blind_spot module to use `module_id_` for virtual wall marker creator.
When there are multiple blind_spot modules running and all of them are disapproved on RTC, VirtualWall(BlindSpot) gives error on rviz.
No error for VirtualWall(BllindSpot) …
=> fix(blind_spot): fix virtual wall marker id duplication

sensing/pointcloud_preprocessor/src/outlier_filter/ring_outlier_filter_nodelet.cpp
* Correct the output intensity of ring-outlier-filter since its current output seems always zero like value.
* Fix point fileds error mentioned [here](https://github.com/autowarefoundation/autoware.universe/pull/3014#issuecomment-1565621541)
I checked the output intensity is reasonable value.
(before) 
(after: obviously intensity is included)
I checked the output pointcloud position is exactly the same in the before and after, but only the intensity is different.
(True in image below means "same", False means "not same")
Also I checked the processing time.
The average time is almost the same; 10.88 ms (before) and  10.95 ms (after) in my desktop PC.
The graph below shows the processing time for before and after applying this PR.  …
=> fix(pointcloud_preprocessor): fix output intensity value of  ring outlier filter 

perception/lidar_centerpoint/package.xml
add missing dependencies for centerpoint to avoid build error with iron
=> build(iron): add missing dependencies for centerpoint

perception/elevation_map_loader/CMakeLists.txt, perception/elevation_map_loader/src/elevation_map_loader_node.cpp
add workaroud for rosbag2 storage plugin update for iron
=> build(iron): add workaroud for rosbag2 storage plugin update

planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp, planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
goal candidates were generated in processOnEntry(), and this function is called when the module is registered(even if isExecutionRequested return false)
so, wrong planner_data(e.g. current pose) may be used for pull_over at that time
(e.g. in `lane_change` -> `pull_over` situation, the goal candidate was generated for pull_over before lane_chnage with inappropriate current_pose at that time)
before
goal candidates can not be found because of out-of-lane.
https://github.com/autowarefoundation/autoware.universe/assets/39142679/6229fd32-41ac-4082-af55-49ad88ad994e
after
https://github.com/autowarefoundation/autoware.universe/assets/39142679/01e286ff-8135-4615-993e-1d65b777eaa6
[tier4 internal ticket](https://tier4.atlassian.net/browse/RT1-2532)
psim
not applicable
not applicable
The PR …
=> fix(goal_planner): generate goal candidates after execution

planning/behavior_path_planner/src/utils/utils.cpp
check previous lanes in isEgoOutOfRoute for backward driving(e.g. pull_out)
fix the following problem
https://github.com/autowarefoundation/autoware.universe/assets/39142679/8a013129-ee38-47ed-b066-c68df0d7573d
psim
not applicable
not applicable
=> fix(behavior_path_planner): check previous lanes in isEgoOutOfRoute

common/component_interface_specs/include/component_interface_specs/control.hpp, control/vehicle_cmd_gate/CMakeLists.txt, control/vehicle_cmd_gate/README.md, control/vehicle_cmd_gate/config/vehicle_cmd_gate.param.yaml, control/vehicle_cmd_gate/src/moderate_stop_interface.cpp, control/vehicle_cmd_gate/src/moderate_stop_interface.hpp, control/vehicle_cmd_gate/src/vehicle_cmd_gate.cpp, control/vehicle_cmd_gate/src/vehicle_cmd_gate.hpp
https://github.com/autowarefoundation/autoware.universe/pull/2528
As mentioned in this link(https://github.com/tier4/tier4_autoware_msgs/pull/82#issuecomment-1539395279), we want to add a new interface to make the vehicle stop while moving. 
Tested in planning simulator, worked well.
Before testing, you should check out the branch here: https://github.com/tier4/tier4_autoware_msgs/pull/88
And also PR above should be merged first. …
=> feat(vehicle_cmd_gate): add moderate_stop_interface to make vehicle stop

planning/behavior_path_planner/src/utils/pull_out/shift_pull_out.cpp
move generating reference path to out of for loop.
psim
not applicable 
not applicable
=> refactor(pull_out): generate shift pull out reference path only once

planning/behavior_path_planner/src/scene_module/pull_out/pull_out_module.cpp
fix invalid idx access in pull out
psim
not applicable
not applicable 
=> fix(pull_out): fix invalid current path idx access

planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
fix invalid current path idx access in goal_planner
not tested
not applicable
not applicable
=> fix(goal_planner): fix invalid current path idx access

planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
Fix pull over sudden deceleration after passing the start offset pose.
In this PR, consider the minimum deceleration distance with deceleration and jerk limit when inserting velocity.
[
tier4 internal link](https://tier4.atlassian.net/browse/RT1-2616)
psim
before (0:32)
https://github.com/autowarefoundation/autoware.universe/assets/39142679/aab7542c-07fc-48b1-b1d0-a917a13e6f2d
after
https://github.com/autowarefoundation/autoware.universe/assets/39142679/f7179855-fec2-4beb-9036-c16f3b416e72
not applicable 
not applicable …
=> fix(goal_planner): fix pull over sudden deceleration

planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/helper.hpp, planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
- add helper class.
- clean up `avoidance_module.hpp` file.
Nothing. Just refactoring.
=> refactor(avoidance): create helper class

planning/behavior_path_planner/src/utils/avoidance/utils.cpp
Cleaned up the code about calculating to_road_shoulder_distance for higher maintainability and readability.
=> refactor(avoidance): calculate to_road_shoulder_distance

planning/obstacle_cruise_planner/README.md
I corrected a slight typo in the doc of obstacle cruise planner.
=> docs(obstacle_cruise_planner): slight typo correction

planning/mission_planner/README.md
=> docs(mission_planner): update readme

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
Remove invalid registered shift lines that have huge lateral offset to ego position.
Nothing.
=> feat(avoidance): remove invalid registered shift lines

planning/behavior_path_planner/include/behavior_path_planner/marker_util/debug_utilities.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/avoidance_module_data.hpp, planning/behavior_path_planner/src/marker_util/avoidance/debug.cpp, planning/behavior_path_planner/src/marker_util/debug_utilities.cpp, planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
Add shift line validator. Check the gap between the proposed shift path and current ego position, if it is larger than threshold, the shift lines are discarded as invalid ones. https://github.com/autowarefoundation/autoware.universe/pull/3847/commits/0d57bfdd73e2fe5408a89b2cd76e732bada516cd
White line in fig is the proposed shift path.
- improve shift line debug marker (show shift line start/end correspondence). https://github.com/autowarefoundation/autoware.universe/pull/3847/commits/4579b07a299398f0415597188ee7d0e1b40e291d
- show merged shift line's gradient. https://github.com/autowarefoundation/autoware.universe/pull/3847/commits/ddae084d3467673b4b55aa0e2306681a680e90d4
](https://evaluation.tier4.jp/evaluation/reports/dd8932a9-8a67-543f-b9ea-81709370a05a?project_id=prd_jt)
Not …
=> feat(avoidance): add shift line validator

planning/obstacle_cruise_planner/config/obstacle_cruise_planner.param.yaml, planning/obstacle_cruise_planner/include/obstacle_cruise_planner/node.hpp, planning/obstacle_cruise_planner/src/node.cpp, planning/obstacle_cruise_planner/src/planner_interface.cpp
suppress sudden slow down by obstacle_cruise_planner's slow down feature.
planning simulator & real vehicle
Nothing
=> feat(obstacle_cruise_planner): suppress sudden slow down

planning/behavior_path_planner/config/avoidance/avoidance.param.yaml, planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/avoidance_module_data.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/utils.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/utils.hpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp, planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp, planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp, planning/behavior_path_planner/src/utils/lane_change/utils.cpp, planning/behavior_path_planner/src/utils/utils.cpp
Improve yield maneuver in avoidance module.
- try to stop with in lane limit if avoidance shift is initiated.
- if there is not enough distance to stop within lane, continue avoidance maneuver.
- prevent sudden stop for adjacent lane vehice when the ego exceed avoidance dead line.
NPC spawns on adjacent lane after the avoidance maneuver start.
```
webauto ci scenario run --project-id prd_jt --scenario-id d81938cb-598b-4d08-a779-9af787bd263f --runtime-path /$HOME/pilot-auto --scenario-parameters __tier4_modifier_d=40
```
https://github.com/autowarefoundation/autoware.universe/assets/44889564/5a58f648-efe8-4cfc-8200-1b01c87be1f0
The ego shift is small enough to return original path but exceeds avoidance dead line. In this case, there is a possibility to cause sudden stop in previous …
=> feat(avoidance): stop within current lane in unsafe situation

planning/behavior_path_planner/src/utils/path_utils.cpp
Small refactoring for `utils::resamplePathWithSpline`
Test with planning simulator
=> fix(behavior_path_planner): small refactoring for resamplePathWithSpline

planning/motion_velocity_smoother/include/motion_velocity_smoother/motion_velocity_smoother_node.hpp, planning/motion_velocity_smoother/include/motion_velocity_smoother/smoother/smoother_base.hpp, planning/motion_velocity_smoother/src/motion_velocity_smoother_node.cpp, planning/motion_velocity_smoother/src/smoother/smoother_base.cpp
To improve readability, remove unnecessary local variables, and move smoother initialization into a separate function.
Psim
None
=> refactor(velocity_smoother): simplify calcInitialMotion function

planning/behavior_path_planner/include/behavior_path_planner/scene_module/avoidance/avoidance_module.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/helper.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/utils.hpp, planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp, planning/behavior_path_planner/src/utils/avoidance/utils.cpp
Move small utilility functions to helper class or utils file.
Nothing.
=> refactor(avoidance): move small functions to other files

planning/motion_velocity_smoother/include/motion_velocity_smoother/trajectory_utils.hpp, planning/motion_velocity_smoother/src/motion_velocity_smoother_node.cpp, planning/motion_velocity_smoother/src/trajectory_utils.cpp
move stop distance calculation code into util
Run psim
None
=> refactor(velocity_smoother): move function to util

planning/behavior_path_planner/docs/behavior_path_planner_lane_change_design.md, planning/behavior_path_planner/docs/behavior_path_planner_path_generation_design.md
Add some explanations about accelerated lane change path generation.
=> docs(behavior_path_planner): add accelerated lane change explanations

planning/behavior_velocity_speed_bump_module/package.xml
Adds a new maintainer to `behavior_velocity_speed_bump_module`
=> chore(behavior_velocity_speed_bump_module): add maintainer

planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
I fixed an issue that the direction of the turn signal was incorrectly reversed in start_planner.
https://github.com/autowarefoundation/autoware.universe/pull/3945
Checked on Psim.
none
none
The direction of the turn signal at the start will be corrected
=> fix(bebavior_path_planner): fix turn signal direction in start_planner

planning/behavior_path_planner/docs/behavior_path_planner_path_generation_design.md
The image in path shifter document is broken.
I fixed it.
=> fix(behavior_path_planner): fix link in path shifter document

planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
Fix the parameter for check is_stopped.
not tested
none
noen
=> fix(start_planner): fix start planner is_stopped

.github/sync-files.yaml
Change sync files source that do not contain repository-specific settings. Related to https://github.com/autowarefoundation/autoware-documentation/pull/395.
=> chore(sync-files): update sync files source of mkdocs

planning/behavior_path_planner/CMakeLists.txt, planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/base_class.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/normal.hpp, planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
Currently lane change module will not be able to extend lane change path after approved, and it caused some problem when there are other module besides lane change is activated.
[Screencast from 2023年06月14日 14時24分28秒.webm](https://github.com/autowarefoundation/autoware.universe/assets/93502286/36070864-a41e-4d20-affb-3c1b978824c4)
Due to the design of the new planner, if there are other modules that is approved while at the same time, lane change module is also active, the new planner will wait for all the approved module to return `SUCCESS` before every one of them exit.  
Implemented a new feature for extending the lane change path in the `lane_change` module. 
[Screencast from 2023年05月30日 19時48分24秒.webm](https://github.com/autowarefoundation/autoware.universe/assets/93502286/322045db-42 …
=> fix(lane_change): extend path during lane changing 

planning/behavior_path_planner/src/utils/path_utils.cpp
keep the closest stop point instead of the terminal point.
- https://github.com/autowarefoundation/autoware.universe/pull/3720
- https://github.com/autowarefoundation/autoware.universe/pull/3813
- https://tier4.atlassian.net/browse/RT1-2372
psim
tier4 internal scenario test 
old archi
[1340/1372](https://evaluation.tier4.jp/evaluation/reports/1f370288-c342-5384-9c40-b1249ca51534?project_id=prd_jt) -> [1326/1372](https://evaluation.tier4.jp/evaluation/reports/e1bdc3ba-332a-5459-9a2a-91f4a6f055f8?project_id=prd_jt)
new archi
[1249/1372](https://evaluation.tier4.jp/evaluation/reports/e60f7b2e-0b9a-5e08-887f-3a6bb64e3404?project_id=prd_jt) -> [1302/1372](https://evaluation.tier4.jp/evaluation/reports/71eda76f-a0a1-58bb-918c-4dd05b23022a?project_id=prd_jt)
this PR fix intersection/crosswalk …
=> fix(behavior_path_planner): fix resample stop point

planning/behavior_path_planner/docs/behavior_path_planner_manager_design.md
forget to update document of `behavior_path_planner_manager_design` in this [PR](https://github.com/autowarefoundation/autoware.universe/pull/3894)
=> docs(behavior_path_planner): minor update behavior_path_planner_manager_design doc

control/mpc_lateral_controller/README.md
- Add a description for the new parameters
- Improve the how-to-tune section
=> docs(mpc): update readme for how-to-tune-mpc

planning/behavior_path_planner/docs/behavior_path_planner_goal_planner_design.md
just fix typo in goal_planner docs
=> chore(goal_planner): fix video title in goal_planner docs

planning/behavior_path_planner/include/behavior_path_planner/utils/utils.hpp, planning/behavior_path_planner/src/utils/utils.cpp
Create a new function to judge if the object is a parked object or not
=> feat(behavior_path_planner): add a function to judge a parked vehicle

system/autoware_auto_msgs_adapter/package.xml
@isamu-takagi san, I've added you as a maintainer to the package too, is that alright? I think you have the most insights in the package.
=> chore(autoware_auto_msg_adapter): update maintainers

planning/behavior_path_planner/package.xml
Backport of #3987 for release/2023.05
=> build: fix opencv dependency (release/2023.05)

planning/mission_planner/src/mission_planner/mission_planner.cpp
Fix typo in the mission planner
=> refactor(mission_planner): fix typo

perception/probabilistic_occupancy_grid_map/laserscan-based-occupancy-grid-map.md, perception/probabilistic_occupancy_grid_map/pointcloud-based-occupancy-grid-map.md
Fixed math equations rendering
=> docs: occupancy grid

planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
visualize start planner type as text marker.
psim
none
none
=> feat(start_planner): visualize start planner type

planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp
The avoidance module doesn't generate shift line for objects that are behind the nearest unavoidable object since the ego can't avoid behind ones as long as it avoids nearest one.
But in following situation, the module can ignore the nearest unavoidable object (= behind ego vehicle), and it shoud generate shift lines for front object if that is avoidable.
In this PR
https://github.com/autowarefoundation/autoware.universe/assets/44889564/cb8f399f-3f95-4c80-a2c8-bf5417af54f4
Improve avoidance maneuver. …
=> feat(avoidance): ignore behind unavoidable objects

planning/mission_planner/src/lanelet2_plugins/default_planner.cpp
Change marker color to improve the visibility
Run psim
=> chore(mission_planner): fix route marker

planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp, planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp
minor refactoring of crosswalk module.
Nothing
=> refactor(crosswalk): minor refactoring

planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_manager_interface.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/start_planner/start_planner_module.hpp, planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp, planning/behavior_path_planner/src/scene_module/start_planner/manager.cpp, planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
```
setIsSimultaneousExecutableAsApprovedModule(false);
setIsSimultaneousExecutableAsCandidateModule(false);
```
when backward driving of pull out.
this prevents LC from being approved when back and generating invalid path
[Screencast from 2023年06月22日 11時24分17秒.webm](https://github.com/autowarefoundation/autoware.universe/assets/39142679/57612182-2e0c-48ed-98f5-cd8c947122a3)
[tier4 internal ticket](https://tier4.atlassian.net/browse/RT1-2852)
psim
https://github.com/autowarefoundation/autoware.universe/assets/39142679/1a5232e6-f99d-4d67-841a-44ba3cfbb0de
none
none …
=> fix(start_planner): not run other modules when back pull out

planning/behavior_path_planner/package.xml
Backport of #3987 for `release/2023.06`
=> build: fix opencv dependency (release/2023.06)

system/default_ad_api/document/fail-safe.md, system/default_ad_api/document/interface.md, system/default_ad_api/document/localization.md, system/default_ad_api/document/motion.md, system/default_ad_api/document/operation-mode.md, system/default_ad_api/document/routing.md
- Links in `default_ad_api` are dead and pre-commit ci failed. So I fixed them.
```bash
Markdown Link Check......................................................Failed
- hook id: markdown-link-check
- exit code: 1
ERROR: 1 dead links found in system/default_ad_api/document/motion.md !
[✖] https://autowarefoundation.github.io/autoware-documentation/main/design/autoware-interfaces/ad-api/list/api/motion/ → Status: 404
ERROR: 1 dead links found in system/default_ad_api/document/interface.md !
[✖] https://autowarefoundation.github.io/autoware-documentation/main/design/autoware-interfaces/ad-api/list/api/interface/ → Status: 404
ERROR: 1 dead links found in system/default_ad_api/document/fail-safe.md !
[✖] https://autowarefoundation.github.io/autoware-documentation/main/design/autoware-interfac …
```
=> docs(default_ad_api): fix link in default_ad_api

planning/mission_planner/src/mission_planner/mission_planner.cpp
Add mrm goal modification for mission planner to enable it modify the goal even when it is in the emergency mode.
=> feat(mission_planner): add mrm goal modification

planning/behavior_path_planner/config/lane_change/lane_change.param.yaml
https://github.com/autowarefoundation/autoware_launch/pull/418
=> fix(behavior_path_planner): enable abort lane change default

planning/behavior_path_planner/src/behavior_path_planner_node.cpp
Lock root path only when the vehicle is controlled by autoware with autonomous mode.
Nothing.
=> fix(behavior_path_planner): fix route update condition

planning/behavior_path_planner/src/turn_signal_decider.cpp
getIntersectionTurnSignalInfo did not consider lane sequences with the same turn_direction and thier start/emd point is changed while driving. this caused wrong winker behavior.
https://github.com/autowarefoundation/autoware.universe/assets/39142679/6b08de38-68a8-4fe6-a594-288009fab596
In this PR, combine separaed  lane sequences with the same turn_direction into one and caclulate start/end point from the lane.
https://github.com/autowarefoundation/autoware_common/pull/193
psim
https://github.com/autowarefoundation/autoware.universe/assets/39142679/5b281020-998a-4ebb-ac5c-86162ff75650
tier4 internal scenario test
[1571/1579](https://evaluation.tier4.jp/evaluation/reports/31fbc63c-7332-5476-963c-26f1593ca803?project_id=prd_jt) -> [1572/1579](https://evaluation.tier4.jp/evaluation/reports/f6 …
=> fix(behavior_path_planner): support separated lanes in getIntersectionTurnSignalInfo

common/global_parameter_loader/package.xml, common/tier4_api_utils/package.xml, common/tier4_autoware_utils/package.xml, common/tier4_debug_tools/package.xml, control/external_cmd_selector/package.xml, control/joy_controller/package.xml, control/lane_departure_checker/package.xml, control/obstacle_collision_checker/package.xml, control/pure_pursuit/package.xml, launch/tier4_autoware_api_launch/package.xml, launch/tier4_system_launch/package.xml, planning/scenario_selector/package.xml, sensing/livox/livox_tag_filter/package.xml, system/component_state_monitor/package.xml, system/dummy_diag_publisher/package.xml, system/dummy_infrastructure/package.xml, system/emergency_handler/package.xml, system/system_error_monitor/package.xml, system/topic_state_monitor/package.xml
Same as https://github.com/autowarefoundation/autoware_common/pull/195.
=> chore: update maintainer

system/default_ad_api/src/vehicle.cpp
=> fix(default_ad_api): pointer check

planning/planning_debug_tools/scripts/closest_velocity_checker.py
Show acceleration in planning trajectory
run node with Psim
=> fix(closest_velocity_checker): add planning acceleration

perception/image_projection_based_fusion/docs/roi-cluster-fusion.md, perception/image_projection_based_fusion/include/image_projection_based_fusion/roi_cluster_fusion/node.hpp, perception/image_projection_based_fusion/include/image_projection_based_fusion/utils/geometry.hpp, perception/image_projection_based_fusion/launch/roi_cluster_fusion.launch.xml, perception/image_projection_based_fusion/src/roi_cluster_fusion/node.cpp, perception/image_projection_based_fusion/src/utils/geometry.cpp
This PR updates `roi_cluster_fusion` to prevent FP, which detects shrubbery as a car.
This PR adds support of **checking whether cluster RoI is inside of RoI detected by 2D detector**.
I added the following function to achieve the above.
```c++
/**
* @param outer : RoI detected by 2D detector
* @param inner : Cluster RoI
* @param outer_offset_scale : A scale factor to extend outer RoI a little. Defaults to 1.1.
*/
bool is_inside(
const sensor_msgs::msg::RegionOfInterest & outer,
const sensor_msgs::msg::RegionOfInterest & inner, const double outer_offset_scale = 1.1);
```
[TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT1-2663)
**Before**
https://github.com/autowarefoundation/autoware.universe/assets/60615504/20eb8ba9-27af-4d64-9e67-d466bf643945
**After** …
=> feat(roi_cluster_fusion): check whether cluster RoI is inside of RoI detected by 2D detector

localization/pose_initializer/src/pose_initializer/gnss_module.cpp, map/map_height_fitter/CMakeLists.txt, map/map_height_fitter/include/map_height_fitter/map_height_fitter.hpp, map/map_height_fitter/launch/map_height_fitter.launch.xml, map/map_height_fitter/package.xml, map/map_height_fitter/src/map_height_fitter.cpp, map/map_height_fitter/src/node.cpp, system/default_ad_api_helpers/ad_api_adaptors/src/initial_pose_adaptor.cpp
Add map height fitter node for python tools.
Check `/map/map_height_fitter/service`.
=> feat(map_height_fitter): add service node

planning/behavior_velocity_intersection_module/config/intersection.param.yaml, planning/behavior_velocity_intersection_module/src/manager.cpp, planning/behavior_velocity_intersection_module/src/scene_intersection.cpp, planning/behavior_velocity_intersection_module/src/scene_intersection.hpp, planning/behavior_velocity_intersection_module/src/scene_merge_from_private_road.cpp, planning/behavior_velocity_intersection_module/src/scene_merge_from_private_road.hpp, planning/behavior_velocity_intersection_module/src/util.cpp, planning/behavior_velocity_intersection_module/src/util.hpp
fixes: https://github.com/autowarefoundation/autoware.universe/issues/3969
Before this PR:
https://www.youtube.com/watch?v=85KuJ6GFbMk
After this PR:
https://www.youtube.com/watch?v=Qt-jrlWgqYQ&ab_channel=BeyzaNurKaya
=> feat(behavior_velocity_intersection_module): consider NPC vehicles driving on the wrong direction lane on intersection

planning/behavior_path_planner/include/behavior_path_planner/scene_module/start_planner/start_planner_module.hpp, planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
fix typos `start_planner_planners_`
none
none
none
=> chore(start_planner): fix typos

perception/radar_object_clustering/CMakeLists.txt, perception/radar_object_clustering/README.md, perception/radar_object_clustering/docs/clustering.drawio.svg, perception/radar_object_clustering/docs/radar_clustering.drawio.svg, perception/radar_object_clustering/include/radar_object_clustering/radar_object_clustering_node.hpp, perception/radar_object_clustering/launch/radar_object_clustering.launch.xml, perception/radar_object_clustering/package.xml, perception/radar_object_clustering/src/radar_object_clustering_node/radar_object_clustering_node.cpp
This PR add `radar_object_clustering`, which make clustered objects from radar DetectedObjects, the objects which is converted from RadarTracks by [radar_tracks_msgs_converter](https://github.com/autowarefoundation/autoware.universe/tree/main/perception/radar_tracks_msgs_converter) and is processed by noise filter.
This package can combine multiple radar detections from one object into one and adjust class and size.
About detail algorithm and purpose I wrote to README.md, so it would be helpful if you could review it at same time.
Tested by rosbag
No
No …
=> feat(radar_object_clustering): add radar_object_clustering

planning/behavior_path_planner/src/planner_manager.cpp
Add a warning message for invalid ego pose.
=> chore(behavior_path_planner): add message for invalid ego pose

planning/behavior_velocity_planner_common/README.md
=> docs(behavior_velocity_planner_common): add readme

control/operation_mode_transition_manager/msg/OperationModeTransitionManagerDebug.msg, control/operation_mode_transition_manager/src/node.cpp
update debug topic for easy understanding
tested in psim
=> chore(operation_mode_transition_manager): update debug topic

control/pure_pursuit/README.md
=> docs(pure_pursuit): add readme

localization/yabloc/yabloc_image_processing/README.md, localization/yabloc/yabloc_image_processing/launch/image_processing.launch.xml, localization/yabloc/yabloc_image_processing/launch/overlay.launch.xml, localization/yabloc/yabloc_image_processing/launch/yabloc_image_processing.launch.xml, localization/yabloc/yabloc_image_processing/src/lanelet2_overlay/lanelet2_overlay_core.cpp, localization/yabloc/yabloc_particle_filter/launch/yabloc_particle_filter.launch.xml, localization/yabloc/yabloc_particle_filter/src/common/particle_visualize_node.cpp
Fix typo and some other terms to pass spell-check CI
N/A
N/A
N/A
N/A
N/A
=> fix(yabloc): fix spell-check CI

planning/behavior_velocity_no_drivable_lane_module/README.md, planning/behavior_velocity_no_drivable_lane_module/package.xml
=> refactor(no_drivable_lane): updating readme file to remove rtc table

.github/workflows/spell-check-all.yaml
Currently, spell-check-differential is one of the CI executed by pull requests as a trigger.
However, since there are too many cspell errors, the error is almost ignored.
Also, spell-check-differential cannot provide the full picture of the spell error in the repository.
Therefore, in order to accelerate the efforts to fix typo, I propose this workflow that can continue to track the entire cspell errors. …
=> chore(cspell): add spell-check-all.yaml

perception/tensorrt_classifier/README.md
Add README.md to the package as mentioned [here](https://star4.slack.com/archives/C4P0NSMB5/p1688988968483219)
Nothing.
Nothing.
=> feat(tensorrt_classifier): add README.md

planning/behavior_velocity_crosswalk_module/package.xml, planning/behavior_velocity_out_of_lane_module/package.xml
add a maintainer of behavior_velocity_crosswalk/out_of_lane
No need
Nothing
=> chore(behavior_velocity_crosswalk/out_of_lane): add a maintainer

launch/tier4_perception_launch/launch/perception.launch.xml, perception/euclidean_cluster/launch/euclidean_cluster.launch.py, perception/euclidean_cluster/launch/voxel_grid_based_euclidean_cluster.launch.py
This PR refactors the euclidean_cluster package for read parameters from autoware_launch config file. 
autoware_launch PR: https://github.com/autowarefoundation/autoware_launch/pull/445
Releated: #4250
=> refactor(euclidean clustering): read parameters from autoware_launch

planning/behavior_path_planner/include/behavior_path_planner/utils/start_planner/shift_pull_out.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/start_planner/util.hpp, planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp, planning/behavior_path_planner/src/utils/start_planner/geometric_pull_out.cpp, planning/behavior_path_planner/src/utils/start_planner/shift_pull_out.cpp, planning/behavior_path_planner/src/utils/start_planner/util.cpp
Fixed pull out when backing across multiple lanes.
Currently the lane of the backward start pose can not be got.
and rename shoulder_lanes to pull_out_lanes because the lanes is not only shoulder after supporting road_lanes
psim
none
none
=> fix(start_planner): fix back pull out due to inability to get back lanes

planning/behavior_velocity_no_drivable_lane_module/README.md
=> refactor(no_drivable_lane): updating readme file to remove rtc

planning/behavior_velocity_intersection_module/config/intersection.param.yaml, planning/behavior_velocity_intersection_module/src/manager.cpp, planning/behavior_velocity_intersection_module/src/scene_intersection.cpp, planning/behavior_velocity_intersection_module/src/scene_intersection.hpp, planning/behavior_velocity_intersection_module/src/util.cpp, planning/behavior_velocity_planner_common/src/utilization/path_utilization.cpp
When the arrow signal is solid-on,
(1) restrict the detection area to only conflicting lanelets without RightOfWay
(2) ignore occlusion
parameter PR: https://github.com/autowarefoundation/autoware_launch/pull/456
[TIER IV COMPANY INTERNAL LINK](https://tier4.atlassian.net/browse/RT1-2350)
(1) detection area is not extended backward
(2) occlusion peeking is disabled when right arrow signal is turned on
https://github.com/autowarefoundation/autoware.universe/assets/28677420/11589f53-9dde-4e54-993c-2e894c8c79ff …
=> feat(intersection): add behavior for arrow signal

planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/utils.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/utils.hpp, planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp, planning/behavior_path_planner/src/utils/avoidance/utils.cpp, planning/behavior_path_planner/src/utils/utils.cpp
- Fix unstable drivable area generation logic.
- Improve monotonic bound generation logic.
- Fix small bug that might cause endless loop.
:arrow_down: Before this PR.
https://github.com/autowarefoundation/autoware.universe/assets/44889564/2d2b8e21-45b1-4a16-aa96-daae157963c1
:arrow_down: After this PR.
https://github.com/autowarefoundation/autoware.universe/assets/44889564/f74e5989-b9c4-4a90-a420-fa91c414a130
https://github.com/autowarefoundation/autoware.universe/assets/44889564/d68feba1-ccec-4f8a-a66a-2024c1393e29
Stablize drivable area bounds. …
=> fix(utils): fix unstable drivable area generation

localization/yabloc/docs/yabloc_architecture.drawio.svg
Fix spell-check
N/A
N/A
N/A
N/A
N/A
=> fix(yabloc): fix spell-check

.cspell-partial.json
Enable spell-check-partial for localization directory.
N/A
N/A
N/A
N/A
N/A
=> ci: enable spell-check-partial for localization

localization/yabloc/docs/yabloc_architecture.drawio.svg
Fix spell-check
vectormap -> vector_map
N/A
N/A
N/A
N/A
N/A
=> fix(yabloc): fix spell-check 'vectormap'

planning/behavior_path_planner/config/avoidance/avoidance.param.yaml, planning/behavior_path_planner/config/avoidance_by_lc/avoidance_by_lc.param.yaml, planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/avoidance_module_data.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/lane_change_module_data.hpp, planning/behavior_path_planner/src/scene_module/avoidance/manager.cpp, planning/behavior_path_planner/src/scene_module/lane_change/avoidance_by_lane_change.cpp, planning/behavior_path_planner/src/scene_module/lane_change/manager.cpp
Previously, normal avoidance module & avoidance by lane change module use common parameters and activation logic.
In this PR, I make it possible to configurate avoidance target for each modules.
```yaml
target_object:
car:
is_target: true                              # [-]
execute_num: 2                               # [-]
moving_speed_threshold: 1.0                  # [m/s]
moving_time_threshold: 1.0                   # [s]
max_expand_ratio: 0.0                        # [-]
envelope_buffer_margin: 0.3                  # [m]
safety_buffer_lateral: 0.7                   # [m]
```
Please approve :arrow_down: before this PR.
https://github.com/autowarefoundation/autoware_launch/pull/469
](https://evaluation.tier4.jp/evaluation/reports/829ef700-1de9-56d3-8d9e-648c6db08340?project_id=prd_jt) …
=> feat(avodiance_by_lc): make it possible to configurate flexibly

launch/tier4_perception_launch/launch/object_recognition/detection/pointcloud_map_filter.launch.py, perception/compare_map_segmentation/README.md, perception/compare_map_segmentation/include/compare_map_segmentation/distance_based_compare_map_filter_nodelet.hpp, perception/compare_map_segmentation/include/compare_map_segmentation/voxel_based_approximate_compare_map_filter_nodelet.hpp, perception/compare_map_segmentation/include/compare_map_segmentation/voxel_distance_based_compare_map_filter_nodelet.hpp, perception/compare_map_segmentation/include/compare_map_segmentation/voxel_grid_map_loader.hpp, perception/compare_map_segmentation/launch/voxel_based_compare_map_filter.launch.xml, perception/compare_map_segmentation/src/voxel_based_approximate_compare_map_filter_nodelet.cpp, perception/compare_map_segmentation/src/voxel_based_compare_map_filter_nodelet.cpp, perception/compare_map_segmentation/src/voxel_distance_based_compare_map_filter_nodelet.cpp, perception/compare_map_segmentation/src/voxel_grid_map_loader.cpp, perception/euclidean_cluster/launch/euclidean_cluster.launch.py
This updates to add option to reduce distance threshold in z axis  in voxel_based_compare_map filtering.
[TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT1-3051)
Confirm performance by logging simulator.
| Before updating | After updating |
|----| ----| 
| Sample rosbag:![Screenshot from 2023-07-12 09-35-06](https://github.com/autowarefoundation/autoware.universe/assets/94814556/433689d9-a5f2-4908-8580-759cba60eb1d)  | ![Screenshot from 2023-07-12 09-05-47](https://github.com/autowarefoundation/autoware.universe/assets/94814556/5e61d311-220d-4eee-9bb8-af337a86e2d2)|
|Internal rosbag for a traffic sign cone
Only 1 ring of pointcloud left | 3 rings of pointcloud left | 
| ![image](https://github.com/autowarefoundation/autoware.universe/assets/94814556/147dcd38-3c50-4a8d-a598-af84 …
=> fix(compare_map_segmentation): add option to reduce distance_threshold in z axis

evaluator/planning_evaluator/src/metrics/obstacle_metrics.cpp
fix typo of planning evaluator
spell check
Nothing
=> fix(planning_evaluator): fix typo

common/autoware_auto_geometry/include/geometry/bounding_box/eigenbox_2d.hpp, common/autoware_auto_geometry/test/include/test_bounding_box.hpp, common/autoware_auto_geometry/test/include/test_spatial_hash.hpp, common/autoware_auto_geometry/test/src/test_convex_hull.cpp, common/autoware_auto_geometry/test/src/test_hull_pockets.cpp
Fix spell-check
N/A
Build test passes
N/A
N/A
N/A
=> fix(autoware_auto_geometry): fix typo

.cspell-partial.json
Enable spell-check-partial for common directory
blocked by https://github.com/autowarefoundation/autoware.universe/pull/4396
N/A
N/A
N/A
N/A
=> ci: enable spell-check-partial for common

system/default_ad_api/document/images/autoware-state-table.drawio.svg
Fix autoware state compatibility table. [TIER IV INTERNAL LINK](https://star4.slack.com/archives/CTEJP8L4T/p1690366705604999?thread_ts=1681813177.227659&cid=CTEJP8L4T)
=> docs(default_ad_api): fix autoware state compatibility table

perception/image_projection_based_fusion/src/pointpainting_fusion/node.cpp
to resolove issue by empty pointcloud
```
[pointpainting_fusion_node-79] terminate called after throwing an instance of 'std::runtime_error'
[pointpainting_fusion_node-79]   what():  Field x does not exist
```
- test with normal data
- test with invalid data
=> fix(image_projection_based_fusion): fix pointpainting error caused by empty pointcloud

planning/behavior_path_planner/config/dynamic_avoidance/dynamic_avoidance.param.yaml, planning/behavior_path_planner/include/behavior_path_planner/scene_module/dynamic_avoidance/dynamic_avoidance_module.hpp, planning/behavior_path_planner/src/scene_module/dynamic_avoidance/dynamic_avoidance_module.cpp, planning/behavior_path_planner/src/scene_module/dynamic_avoidance/manager.cpp, planning/behavior_path_planner/src/utils/utils.cpp
Added a debug info about the reason to ignore avoidance in dynamic avoidance.
Nothing
=> feat(dynamic_avoidance): add debug info for obstacle filtering

.github/workflows/openai-pr-reviewer.yaml
=> feat: change from ChatGPT3.5 to 4.0

.cspell-partial.json
Enable spell-check-partial for system directory
N/A
N/A
N/A
N/A
N/A
=> ci: enable spell-check-partial for system

.cspell-partial.json
enable spell-check-partial for evaluator and launch directory
N/A
N/A
N/A
N/A
N/A
=> ci: enable spell-check-partial for evaluator and launch

perception/traffic_light_arbiter/package.xml, perception/traffic_light_classifier/launch/traffic_light_classifier.launch.xml, perception/traffic_light_fine_detector/launch/traffic_light_fine_detector.launch.xml, perception/traffic_light_fine_detector/package.xml, perception/traffic_light_multi_camera_fusion/package.xml, perception/traffic_light_occlusion_predictor/package.xml
* change default model in launch sample of traffic light fine_detector and classifier
* add maintainer to TLR packages
=> chore: change TLR default model

planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp, planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp
When there are no traffic signals for crosswalks, the ego will yield for 3 seconds **with** stopping.
[Screencast from 2023年07月31日 14時22分07秒.webm](https://github.com/autowarefoundation/autoware.universe/assets/20228327/e9d8520f-cec9-4bde-beca-037d1156a61c)
When there is traffic signals for crosswalks, the ego will yield for 3 seconds **without** stopping.
[Screencast from 2023年07月31日 14時24分21秒.webm](https://github.com/autowarefoundation/autoware.universe/assets/20228327/feac2076-9c1e-4f99-9fda-66c0245564dc)
- planning simualtor
- no degradation: https://evaluation.tier4.jp/evaluation/reports/189b1cc2-4f1b-51d0-b819-d6aea0553d20?project_id=prd_jt
Nothing by default
The PR reviewers **must** check …
=> feat(crosswalk): disable cancel yield at no traffic signals intersection

planning/behavior_path_planner/src/utils/utils.cpp
Fix the issues that the path can not generated when putting goal in lane change case.
Currenty stop extending lanes when the lane is same to goal lane, so in this case check goal route section too.
due to https://github.com/autowarefoundation/autoware.universe/pull/4418
psim
and check loop cases 
[tier4 internal sceanrio test](https://evaluation.tier4.jp/evaluation/reports/dd22bc33-b6ba-5874-8e09-b03c70c5b1ac?project_id=prd_jt) 1577/1588
none
none …
=> fix(start_planner): fix extending lanes in lane change case

planning/behavior_path_planner/src/utils/utils.cpp
The point removing method erases all path points once the overlapped lane id is found.
The method current method is faster in term of computation (found and return).
However, if the first path point is overlapped, it will removed the rest of the points, which will cause the planning container to die.
```
for (size_t i = 0; i < path.points.size(); ++i) {
const auto & lane_ids = path.points.at(i).lane_ids;
for (const auto & lane_id : lane_ids) {
if (
std::find(removed_lane_ids.begin(), removed_lane_ids.end(), lane_id) !=
removed_lane_ids.end()) {
path.points.erase(path.points.begin() + i, path.points.end());
return shorten_lanes;
}
}
}
```
if `std::find(removed_lane_ids.begin(), removed_lane_ids.end(), lane_id) != removed_lane_ids.end()` is `true` when `i = 0`, it will erase all path …
=> fix(behavior_path_planner): search duplicated lane id with remove_if

planning/behavior_velocity_crosswalk_module/config/crosswalk.param.yaml, planning/behavior_velocity_crosswalk_module/src/manager.cpp, planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp, planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp
Depends on https://github.com/autowarefoundation/autoware.universe/pull/4471
Added a pass judge line to the crosswalk module which is tunable.
If the ego touches the crosswalk, the stop planning will be never done.
=> feat(crosswalk): add pass judge line

planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/base_class.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/normal.hpp, planning/behavior_path_planner/src/scene_module/lane_change/interface.cpp, planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
Before this change, it cannot do multiple lane change because stop point to ensure minimum lane change length is not inserted.
In this change, I insert the stop point.
Furthermore, I add the relaxation of finish judge to execute next lane change definitely.
[TIER IV INTERNAL TEST](https://evaluation.tier4.jp/evaluation/reports/036c842a-560e-5ee5-bb0a-ab567770e03d?project_id=prd_jt)
https://github.com/autowarefoundation/autoware.universe/assets/10190493/a5889f5e-2906-43d7-bcc8-bbe18ffb126e
Nothing.
Nothing. …
=> fix(behavior_path_planner): insert stop point for multiple lane change

planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
fix start planner invalid lane access
```
[component_container_mt-27] terminate called after throwing an instance of 'lanelet::NoSuchPrimitiveError'
[component_container_mt-27]   what():  Tried to lookup an element with id InvalId!
```
psim
none
none
=> fix(start_planner): invalid lane id access

planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
Ignore objects out of pull out lanes for start pose search
psim
before
after
none
none
=> feat(start_planner): ignore objects out of pull out lanes for start pose search

planning/behavior_path_planner/config/start_planner/start_planner.param.yaml, planning/behavior_path_planner/include/behavior_path_planner/utils/start_planner/start_planner_parameters.hpp, planning/behavior_path_planner/src/scene_module/start_planner/manager.cpp, planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp, planning/behavior_path_planner/src/utils/start_planner/geometric_pull_out.cpp, planning/behavior_path_planner/src/utils/start_planner/shift_pull_out.cpp
Use only stop objects in pull out lanes for collision check
In the future use moving objects for safety check.
psim
https://github.com/autowarefoundation/autoware.universe/assets/39142679/18cf6cc7-9dfc-47eb-bb5d-9849e6e00441
https://evaluation.tier4.jp/evaluation/reports/aa44361c-2338-5500-8efc-f8c3144560c1?project_id=prd_jt
1578/1588
none
none …
=> feat(start_planner): use stop objects in pull out lanes for collision check

planning/route_handler/include/route_handler/route_handler.hpp, planning/route_handler/src/route_handler.cpp
Fix the issue that when the ego vehicle is stopped and the modified route is received request start planner again
In this PR check not modified route start pose but original route start pose for start planner execution request.
https://github.com/autowarefoundation/autoware.universe/pull/4453
psim
[tier4 internal sceanrio simulator](https://evaluation.tier4.jp/evaluation/reports/tables/new?catalog_id=cb497016-2e2f-4ce0-9ac8-68d77a27a55d&filter=&job_id=ee37df62-9a23-521e-b4e8-f547f811b8fc&project_id=prd_jt&table_config=date%2Chide&target_ids=a44e58f7-6fee-579c-a12d-16a96fccbbfc%2Cb13ab173-1234-5327-9363-90c5b709329f)
none
none …
=> fix(start_plannere): do not request when modifed route is received

planning/route_handler/package.xml
add @takayuki5168 to route handler code owner
=> chore(route_handler): add takayuki5168 to route handler code owner

planning/behavior_path_planner/config/lane_change/lane_change.param.yaml, planning/behavior_path_planner/include/behavior_path_planner/parameters.hpp, planning/behavior_path_planner/src/behavior_path_planner_node.cpp
Remove an unused parameter from the lane change module and parameter file
[launch PR](https://github.com/autowarefoundation/autoware_launch/pull/501)
=> feat(lane_change): remove unused parameters

planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
add missing change of "do not request when modifed route is received https://github.com/autowarefoundation/autoware.universe/pull/4528
In #4528 `getOriginalStartPose()` is just added to route_handler, so in this PR use the funciton in start_planner.
psim
[tier4 internal sceanrio test](https://evaluation.tier4.jp/evaluation/reports/b4433249-281f-5148-93eb-b74b657fb87f?project_id=prd_jt)
none
none
[pull …
=> fix(start_planner): add missing change of "do not request when modifed route is received #4528"

planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
add life time to debug markers
psim
none
none
=> feat(goal_planner): add life time to debug markers

perception/image_projection_based_fusion/src/fusion_node.cpp
Fix from RCLCPP_WARN to RCLCPP_WARN_THROTTLE because other logs are not visible on the console
=> chore(image_projection_based_fusion): change to throttle log

perception/multi_object_tracker/include/multi_object_tracker/utils/utils.hpp, perception/multi_object_tracker/models.md
Fix spell-check errors: https://github.com/autowarefoundation/autoware.universe/actions/runs/5806829839/job/15740497229#step:11:1012
Errors due to the person names should be fixed later in https://github.com/tier4/autoware-spell-check-dict
N/A
N/A
N/A
N/A
N/A
=> chore(multi_object_tracker): fix spell-check errors

planning/scenario_selector/src/scenario_selector_node/scenario_selector_node.cpp
fix typo of https://github.com/autowarefoundation/autoware.universe/pull/4569
https://github.com/autowarefoundation/autoware.universe/pull/4569
none
none
none
=> chore(scenario_selector): fix typo

control/lane_departure_checker/package.xml
Add maintainer for lane_departure_checker package.
=> feat(lane_departure_checker): add maintainer

planning/obstacle_avoidance_planner/config/obstacle_avoidance_planner.param.yaml, planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/debug_marker.hpp, planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/mpt_optimizer.hpp, planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/node.hpp, planning/obstacle_avoidance_planner/scripts/calculation_time_plotter.py, planning/obstacle_avoidance_planner/src/debug_marker.cpp, planning/obstacle_avoidance_planner/src/mpt_optimizer.cpp, planning/obstacle_avoidance_planner/src/node.cpp
- Decreased default debug markers to publish
- Circles visualization is a bit heavy.
- Extra debug markers can be published by changing a flag.
- Effective multiple nearest index search in the for loop with `calcSegmentLengthVector`.
- Modify the script to plot the calculation time of functions which is or may be heavy.
**without the PR**
**with the PR**
replan every 1 second (default)
FYI: replan every cycle
**without the PR**
**with the PR**
replan every 1 second (default)
FYI: replan every cycle
- https://evaluation.tier4.jp/evaluation/reports/31286aea-7053-5fd1-82db-08e9fc4a65f0?project_id=prd_jt
Nothing …
=> perf(obstacle_avoidance_planner): smaller calculation time

perception/probabilistic_occupancy_grid_map/CMakeLists.txt, perception/probabilistic_occupancy_grid_map/launch/pointcloud_based_occupancy_grid_map.launch.py, perception/probabilistic_occupancy_grid_map/package.xml, perception/probabilistic_occupancy_grid_map/test/test_pointcloud_based_method.py, perception/probabilistic_occupancy_grid_map/test/test_utils.cpp
It seems there are sometimes unknown error occurred in this package in some project.
I added two test frameworks for future development of pointcloud based occupancy grid map node
- launch testing: test I/O of the pointcloud based method
- gtest: test util function
Current test case only supports
- Happy path testing
- Exceptions
- Pointclouds msg without any point
- Output point will become 0
[TIER IV INTERNAL TICKET LINK](https://tier4.atlassian.net/browse/RT0-28767)
- run both test
```
colcon test --packages-select probabilistic_occupancy_grid_map --event-handlers console_direct+
```
- run launch test
```
launch_test src/universe/autoware.universe/perception/probabilistic_occupancy_grid_map/test/test_pointcloud_based_method.py
```
- run gtest
``` …
```
=> feat(probabilistic_occupancy_grid_map): add launch test and gtest for future debugging

planning/behavior_path_planner/docs/behavior_path_planner_avoidance_design.md
Update documents for debug marker to align with code changes. 
Command tested on PSim launch.
=> fix(documents for behavior path planner): change output_debug_marker to publish debug marker following code changes.

.cspell-partial.json
Disable spell-check-partial for control directory.
=> chore(ci): disable spell-check-partial for control directory

planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp
Winker direction shold be decided with lateral offset between start pose and closest road lane center path.
build
none
none
=> fix(start_planner): fix blinker direction

planning/behavior_path_planner/CMakeLists.txt, planning/behavior_path_planner/include/behavior_path_planner/scene_module/lane_change/normal.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/avoidance/utils.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/lane_change_module_data.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/lane_change/utils.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/path_safety_checker/objects_filtering.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/path_safety_checker/path_safety_checker_parameters.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/path_safety_checker/safety_check.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/utils.hpp, planning/behavior_path_planner/src/scene_module/avoidance/avoidance_module.cpp, planning/behavior_path_planner/src/scene_module/lane_change/avoidance_by_lane_change.cpp, planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp, planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp, planning/behavior_path_planner/src/utils/goal_planner/goal_searcher.cpp, planning/behavior_path_planner/src/utils/path_safety_checker/objects_filtering.cpp, planning/behavior_path_planner/src/utils/path_safety_checker/safety_check.cpp, planning/behavior_path_planner/src/utils/start_planner/geometric_pull_out.cpp, planning/behavior_path_planner/src/utils/start_planner/shift_pull_out.cpp, planning/behavior_path_planner/src/utils/utils.cpp, planning/behavior_path_planner/test/test_safety_check.cpp
Next step of this [PR](https://github.com/autowarefoundation/autoware.universe/pull/4644)
Separate many functions related to objects filtering from utils.
Define parameters related path safety check against dynamic objects.
And refactor functions  so that other scene module can use the refactord function in objects filtering by defining proposing parameter. …
=> refactor(behavior_path_planner): separete function in utils to objects_filtering 

localization/ekf_localizer/config/ekf_localizer.param.yaml
fix upper case to lower case
Not neccesary.
=> fix(ekf_localizer): fix True to true

launch/tier4_map_launch/launch/map.launch.py, map/map_loader/include/map_loader/lanelet2_map_loader_node.hpp, map/map_loader/package.xml, map/map_loader/src/lanelet2_map_loader/lanelet2_map_loader_node.cpp, map/map_loader/src/pointcloud_map_loader/pointcloud_map_loader_node.cpp, map/map_projection_loader/include/map_projection_loader/map_projection_loader.hpp, map/map_projection_loader/launch/map_projection_loader.launch.xml, map/map_projection_loader/package.xml, map/map_projection_loader/src/map_projection_loader.cpp, map/map_projection_loader/test/test_node_load_local_from_yaml.test.py, map/map_projection_loader/test/test_node_load_mgrs_from_yaml.test.py, map/map_projection_loader/test/test_node_load_utm_from_yaml.test.py
Use component_interface_specs for map interface
N/A
- Ran logging_simulator with sample rosbags and confirmed that it runs successfully.
- Ran `ros2 topic info -v /map/map_projector_type` and confirmed that it does not change before and after PR.
N/A
N/A
No effect
=> fix(map_loader, map_projection_loader): use component interface specs

planning/behavior_path_planner/include/behavior_path_planner/utils/goal_planner/freespace_pull_over.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/path_utils.hpp, planning/behavior_path_planner/src/utils/goal_planner/freespace_pull_over.cpp, planning/behavior_path_planner/src/utils/path_utils.cpp
set lane ids to freespace pull over path
psim
none
none
=> feat(goal_planner): add lane ids to freespace path

planning/freespace_planning_algorithms/test/debug_plot.py
=> chore(freespace_planning_algorithms): fix spell

planning/planning_validator/include/planning_validator/utils.hpp, planning/planning_validator/src/utils.cpp
=> chore(planning_validator): fix spell

planning/sampling_based_planner/bezier_sampler/include/bezier_sampler/bezier.hpp, planning/sampling_based_planner/bezier_sampler/include/bezier_sampler/bezier_sampling.hpp, planning/sampling_based_planner/frenet_planner/include/frenet_planner/structures.hpp, planning/sampling_based_planner/frenet_planner/src/frenet_planner/frenet_planner.cpp, planning/sampling_based_planner/path_sampler/README.md, planning/sampling_based_planner/path_sampler/src/node.cpp, planning/sampling_based_planner/path_sampler/src/path_generation.cpp, planning/sampling_based_planner/path_sampler/src/prepare_inputs.cpp, planning/sampling_based_planner/sampler_common/include/sampler_common/structures.hpp
This PR fixes all cspell errors from packages in the `planning/sampling_based_planner` folder.
None.
=> fix(sampling_based_planner): correct spelling for cspell

planning/behavior_velocity_occlusion_spot_module/docs/occlusion_spot.drawio.svg, planning/behavior_velocity_occlusion_spot_module/docs/velocity_planning.drawio.svg
This PR fixes the cspell errors found in the `behavior_velocity_occlusion_spot_module` package.
=> chore(behavior_velocity_occlusion_spot): correct spelling for cspell

perception/probabilistic_occupancy_grid_map/src/laserscan_based_occupancy_grid_map/laserscan_based_occupancy_grid_map_node.cpp, perception/probabilistic_occupancy_grid_map/src/pointcloud_based_occupancy_grid_map/pointcloud_based_occupancy_grid_map_node.cpp
Same as https://github.com/autowarefoundation/autoware.universe/pull/4713.
AWSIM
Prevent node die
=> fix(probabilistic_occupancy_gridmap): prevent node death by adding lookupTransform exception in util function

planning/behavior_path_planner/docs/behavior_path_planner_lane_change_design.md
=> docs(lane_change): fix document for lane change

sensing/imu_corrector/package.xml
=> chore(imu_corrector): add maintainer

launch/tier4_planning_launch/launch/scenario_planning/scenario_planning.launch.xml
- use motion_velocity_smoother container
- add glog component
run psim
display glog on the terminal
=> feat(motion_velocity_smoother.launch): add glog component

launch/tier4_planning_launch/launch/mission_planning/mission_planning.launch.xml
- Add glog in mission_planning.lanch
- use mission_planning_container
run psim
display glog on the terminal
=> feat(mission_planning.launch): add glog in mission planner

map/map_projection_loader/README.md
Fix description in readme
None
None
=> fix(map_projection_loader): fix readme

planning/obstacle_cruise_planner/package.xml
Added a maintainer of obstacle_cruise_planner
No need
Nothing
=> chore(obstacle_cruise_planner): add maintainers

perception/map_based_prediction/package.xml
Added a maintainer of map_based_prediction.
I want at least one member from the TIER IV Planning/Control team to be a maintainer.
No need
Nothing
=> chore(map_based_prediction): add maintainer

planning/behavior_velocity_occlusion_spot_module/src/manager.cpp
=> refactor(occlusion_spot): use getOrDeclareParameter

control/vehicle_cmd_gate/package.xml, control/vehicle_cmd_gate/src/marker_helper.hpp, control/vehicle_cmd_gate/src/vehicle_cmd_gate.cpp, control/vehicle_cmd_gate/src/vehicle_cmd_gate.hpp
Add a feature to output debug markers when filters of vehicle_cmd_gate are enabled.
https://github.com/autowarefoundation/autoware.universe/assets/59680180/85d74b61-83c8-4286-ae23-88cc3496baaf
(Tested by modifying the values of some filters.)
Not applicable. (Change on only visualization)
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-reques …
=> feat: add marker of cmd gate filter 

perception/map_based_prediction/config/map_based_prediction.param.yaml, perception/map_based_prediction/include/map_based_prediction/map_based_prediction_node.hpp, perception/map_based_prediction/include/map_based_prediction/path_generator.hpp, perception/map_based_prediction/src/map_based_prediction_node.cpp, perception/map_based_prediction/src/path_generator.cpp
In the crosswalk prediction, whether the pedestrian will cross the crosswalk is judged by checking the angle against the pedestrian's velocity and the direction from the pedestrian to the crosswalk.
For more precise calculation, how to calculate this angle is improved as follows.
The angle threshold is changed from 90 degree to 45 degree. IMO, this aggressive parameter can be achieved by this precise calculation.
unit test
scenario simulator
https://evaluation.tier4.jp/evaluation/reports/14ebd96e-17b1-5ea0-89e4-7e7e6c6cd2d4?project_id=prd_jt
https://evaluation.tier4.jp/evaluation/reports/45350a78-cb0f-54fd-8cbf-ef6a34608435?project_id=prd_jt
nothing …
=> feat(map_based_prediction): improve crosswalk prediction

map/map_projection_loader/package.xml
This PR declares `yaml-cpp` as a dependency in `package.xml`
=> build: added missing yaml-cpp dependency

planning/behavior_velocity_crosswalk_module/src/debug.cpp, planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
The collision point between the ego's path and object's path is calculated as follows.
Since one-step object's polygon is small enough, the collision point is unstable, resulting in a chattering of GO/STOP decision of the crosswalk module.
**Without the PR**
"Ego's time to collision" is unstable.
**With the PR**
"Ego's time to collision" is stable.
scenario simulator
https://evaluation.tier4.jp/evaluation/reports/54768bcb-5b11-5c3e-99fb-b39bcb4378be?project_id=prd_jt
https://evaluation.tier4.jp/evaluation/reports/ffe1d1f7-ea22-5ad1-84ac-795d4f0d1e5b?project_id=prd_jt
Nothing …
=> feat(crosswalk): stabler collision point

planning/behavior_velocity_intersection_module/README.md, planning/behavior_velocity_intersection_module/config/intersection.param.yaml, planning/behavior_velocity_intersection_module/docs/stuck-vehicle.drawio.svg, planning/behavior_velocity_intersection_module/src/manager.cpp, planning/behavior_velocity_intersection_module/src/scene_intersection.cpp, planning/behavior_velocity_intersection_module/src/scene_intersection.hpp, planning/behavior_velocity_intersection_module/src/util.cpp, planning/behavior_velocity_intersection_module/src/util.hpp, planning/behavior_velocity_intersection_module/src/util_type.hpp
calculate the stuck vehicle detect area using
- the path from the first point inside `conflicting area` to the last point inside the intersection lane
- the path on the next lane up to `stuck_vehicle_detect_dist`
launcher PR: https://github.com/autowarefoundation/autoware_launch/pull/532 …
=> feat(intersection): strict definition of stuck vehicle detection area

planning/behavior_velocity_intersection_module/package.xml
Added missing `libopencv-dev` dependency.
=> build(behavior_velocity_intersection_module): add libopencv-dev dependency

perception/map_based_prediction/package.xml
=> chore(map_base_prediction): add maintainer

planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp, planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp
remove allow_goal_modification_
psim
=> refactor(goal_planner): remove unncecessary variable

control/autonomous_emergency_braking/include/autonomous_emergency_braking/node.hpp, control/trajectory_follower_node/include/trajectory_follower_node/controller_node.hpp, control/trajectory_follower_node/package.xml, control/trajectory_follower_node/src/controller_node.cpp, planning/behavior_path_planner/src/utils/drivable_area_expansion/footprints.cpp, vehicle/vehicle_info_util/CMakeLists.txt, vehicle/vehicle_info_util/include/vehicle_info_util/vehicle_info.hpp, vehicle/vehicle_info_util/src/vehicle_info.cpp
=> chore(build): remove tier4_autoware_utils.hpp in vehicle/

main.py, mkdocs.yaml, mkdocs_macros.py, perception/lidar_apollo_segmentation_tvm_nodes/README.md
This adds a python script for mkdocs to generate markdown table for README from ROS node parameter's json schema.
=> feat: add feature to convert json schema to markdown table

common/path_distance_calculator/src/path_distance_calculator.cpp
depends: https://github.com/autowarefoundation/autoware.universe/pull/4829
=> chore(build): remove motion_utils.hpp in common/

system/default_ad_api/src/planning.cpp, system/default_ad_api/src/planning.hpp
=> chore(build): remove tier4_autoware_utils.hpp system/

map/map_projection_loader/src/map_projection_loader.cpp
Output altitude from yaml file as well as latlon.
Edit map_projector_info.yaml and verify that the altitude is correctly reflected when using LocalCartesianUTM
=> fix(map_projection_loader): fix altitude output

localization/gyro_odometer/include/gyro_odometer/gyro_odometer_core.hpp
=> chore(build): remove tier4_autoware_utils.hpp localization/ map/

planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/manager.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/scene_module_manager_interface.hpp, planning/behavior_path_planner/src/planner_manager.cpp, planning/behavior_path_planner/src/scene_module/goal_planner/manager.cpp
add always executable module option and use it for fixed_goal_planner
psim
https://evaluation.tier4.jp/evaluation/reports/tables/new?catalog_id=cb497016-2e2f-4ce0-9ac8-68d77a27a55d&filter=&job_id=fcd5b992-96de-5b41-a439-9741a5ac9848&project_id=prd_jt&table_config=date%2Chide&target_ids=8b5e813f-8274-511e-afc1-addd20898a79
when avoidance is not 'simultaneously executable'. …
=> feat(behavior_path_planner): add always executable module option

sensing/imu_corrector/package.xml, sensing/imu_corrector/src/imu_corrector_core.cpp
Fix build error
The current version fails to build with the following error msg:
```bash
/usr/bin/ld: CMakeFiles/imu_corrector.dir/src/imu_corrector_core.cpp.o: in function `transformVector3(geometry_msgs::msg::Vector3_<std::allocator<void> > const&, geometry_msgs::msg::TransformStamped_<std::allocator<void> > const&)':
imu_corrector_core.cpp:(.text+0x48f): undefined reference to `void tf2::doTransform<geometry_msgs::msg::Vector3Stamped_<std::allocator<void> > >(geometry_msgs::msg::Vector3Stamped_<std::allocator<void> > const&, geometry_msgs::msg::Vector3Stamped_<std::allocator<void> >&, geometry_msgs::msg::TransformStamped_<std::allocator<void> > const&)'
```
This build error occurs after https://github.com/autowarefoundation/autoware.universe/pull/4841
Build test passes
None
The PR …
=> fix(imu_corrector): fix build failure

planning/behavior_path_planner/src/scene_module/lane_change/normal.cpp
Skip processes included in https://github.com/autowarefoundation/autoware.universe/pull/4591 and https://github.com/autowarefoundation/autoware.universe/pull/4733 because they includes bugs.
Tested in planning simulator
=> fix(lane_change): skip parked object filtering

planning/behavior_path_planner/src/utils/goal_planner/util.cpp
fix https://github.com/autowarefoundation/autoware.universe/pull/4856
=> fix(behavior_path_planner): fix checkOriginalGoalIsInShoulder

planning/behavior_path_planner/include/behavior_path_planner/utils/utils.hpp, planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp, planning/behavior_path_planner/src/utils/goal_planner/goal_searcher.cpp, planning/behavior_path_planner/src/utils/utils.cpp
Fix goal search for narrow shoulder lane considering patterns when the bound of the vehicle at pull over lane's center line is outside the bound of the lanelet.
before (skip checking is in lane)
after
psim
https://evaluation.tier4.jp/evaluation/reports/25c84c50-d734-5075-9ab2-fc1e45884ff6?project_id=prd_jt
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contri …
=> fix(goal_planner): fix goal search for narrow shoulder lane

common/perception_utils/package.xml, perception/crosswalk_traffic_light_estimator/package.xml, perception/traffic_light_fine_detector/package.xml, perception/traffic_light_multi_camera_fusion/package.xml, perception/traffic_light_occlusion_predictor/package.xml
Change maintainer of traffic light relate packages
No effects
=> chore: update maintainer of TLR packages

planning/behavior_path_planner/config/goal_planner/goal_planner.param.yaml, planning/behavior_path_planner/config/start_planner/start_planner.param.yaml, planning/behavior_path_planner/include/behavior_path_planner/scene_module/goal_planner/goal_planner_module.hpp, planning/behavior_path_planner/include/behavior_path_planner/scene_module/start_planner/start_planner_module.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/start_goal_planner_common/utils.hpp, planning/behavior_path_planner/include/behavior_path_planner/utils/start_planner/util.hpp, planning/behavior_path_planner/src/scene_module/goal_planner/goal_planner_module.cpp, planning/behavior_path_planner/src/scene_module/goal_planner/manager.cpp, planning/behavior_path_planner/src/scene_module/start_planner/manager.cpp, planning/behavior_path_planner/src/scene_module/start_planner/start_planner_module.cpp, planning/behavior_path_planner/src/utils/start_goal_planner_common/utils.cpp, planning/behavior_velocity_out_of_lane_module/README.md
should be merged with the [PR](https://github.com/autowarefoundation/autoware.universe/pull/4873) in autoware_launcher
WIP(explain feature later)
WIP
Nothing
When safety checker judge it's not safe, you can't execute start/goal_planner.
safety check for goal_planner
[Screencast from 2023年09月04日 19時16分04秒.webm](https://github.com/autowarefoundation/autoware.universe/assets/32741405/83943439-4cd0-4dc5-a271-9c0a94a41b1b)
safety check for start_planner
[Screencast from 2023年09月04日 20時06分33秒.webm](https://github.com/autowarefoundation/autoware.universe/assets/32741405/8241d629-6df6-44db-8cb9-4b20a82e181d) …
=> feat(behavior_path_planner): add safety check against dynamic objects for start/goal planner
