autowarefoundation/autoware_universe

launch/tier4_vehicle_launch/launch/vehicle.launch.xml
vehicle/raw_vehicle_cmd_converter/config/raw_vehicle_cmd_converter.param.yaml
vehicle/raw_vehicle_cmd_converter/launch/raw_vehicle_converter.launch.xml
vehicle/raw_vehicle_cmd_converter/schema/raw_vehicle_cmd_converter.schema.json

According to https://github.com/autowarefoundation/autoware.universe/pull/5134, some parameters are moved into yaml files.
However, if we launch `raw_vehicle_cmd_converter` from `autoware_launch`, some parameters defined in launch files does not appear.
In this change, I fixed above problems.
accel/brake/steer map path should change at launch, so I removed `csv_path_**_map` from yaml file and add them into xml file. …

fix(raw_vehicle_cmd_converter): fix parameter files to parse path to csv files

---

planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/util.hpp
planning/behavior_path_goal_planner_module/src/goal_planner_module.cpp
planning/behavior_path_goal_planner_module/src/goal_searcher.cpp
planning/behavior_path_goal_planner_module/src/util.cpp

related to https://github.com/autowarefoundation/autoware.universe/pull/6124
- make utils for fitltering objects
- use expanded pull over lanes for filtering in goal searche
evaluator_description: feat/expanded_pull_over_lanes_searcher
2024/01/22 https://evaluation.tier4.jp/evaluation/reports/0f47f61d-aa59-587b-829b-f25e65d41095/?project_id=prd_jt …

feat(goal_planner): use expanded pull over lanes for filtering in goal searcher

---

planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/goal_planner_module.hpp
planning/behavior_path_goal_planner_module/src/goal_planner_module.cpp

- to fix sudden stop remove
```
for (auto & point : stop_path->points) {
point.point.longitudinal_velocity_mps = 0.0;
}
```
- previous stop path was incorrectly saved. 
- some conditions that was not used was removed.
- refactoring
psim
check safety check after approval
https://github.com/autowarefoundation/autoware.universe/assets/39142679/a7360da7-5664-4a2b-af26-30ba6a497490
evaluator_description: fix/goal_planner_stop_path
2024/01/19 https://evaluation.tier4.jp/evaluation/reports/fe649661-060b-5e6d-bfa4-df534b2de755/?project_id=prd_jt
https://evaluation.tier4.jp/evaluation/reports/8d7cee06-ef13-5b5f-a6f3-dbfb603813db?project_id=prd_jt
2024/01/21 https://evaluation.tier4.jp/evaluation/reports/7f725890-6209-52ec-8939-8bee2abe54d2/?project_id=prd_jt …

fix(goal_planner): fix sudden stop and simpify process 

---

planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/goal_planner_module.hpp
planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/goal_searcher.hpp
planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/goal_searcher_base.hpp
planning/behavior_path_goal_planner_module/src/goal_planner_module.cpp
planning/behavior_path_goal_planner_module/src/goal_searcher.cpp

add deciding status to check collision for for a certain period of time
before:
transit DECIDED path status soon if current path has no collision and ego vehicle is close enogh to the pull over start pose.
after:
transit DECIDING path status to check collision for certain period of time. After that transit DECIDED.
psim
evaluator_description: feat/diciding_status_goal_planner
2024/01/22 https://evaluation.tier4.jp/evaluation/reports/152a0e19-00c0-5672-87cc-cb890ec47116/?project_id=prd_jt
evaluator_description: feat/diciding_status_goal_planner
2024/01/22 https://evaluation.tier4.jp/evaluation/reports/227d58ab-1b54-57fd-9ef5-28f1bd937906/?project_id=prd_jt
https://evaluation.tier4.jp/evaluation/reports/b9299466-6c46-5dc8-928e-71eb53b4a9fb?project_id=prd_jt
goal planner scenarios faile only …

feat(goal_planner): add deciding status to check collision for for a certain period of time

---

system/system_error_monitor/config/diagnostic_aggregator/planning.param.yaml

Enable error diag handling for invalid trajectory size. This is for https://github.com/autowarefoundation/autoware.universe/pull/6126.
None
1. Run psim. 
2. publish empty trajectory as follows.
```
$ ros2 topic pub /planning/scenario_planning/motion_velocity_smoother/trajectory autoware_auto_planning_msgs/msg/Trajectory "{header: {stamp: now, frame_id: "base_link"}}"
```
3. check if the error handling is performed on the terminal message. 
for `/diagnostics` topic, 
```
sec: 1705844112
nanosec: 527912365
frame_id: ''
status:
- level: "\x02"
name: 'planning_validator: trajectory_validation_size'
message: invalid trajectory size is found
hardware_id: planning_validator
values: []
```
for `/system/emergency/hazard_status` topic, 
```
- level: "\x02"
name: …
```

feat(system_error_monitor): enable invalid trajectory size diag

---

planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/scene.hpp
planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/utils/base_class.hpp
planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/utils/path.hpp
planning/behavior_path_lane_change_module/src/interface.cpp
planning/behavior_path_lane_change_module/src/scene.cpp

Current lane change module immediately compute lane changing path upon `processOnEntry()`.
However, technically it should compute the path only if execution is requested.
Therefore, this PR refactor lane change module so that `updateLaneChangeStates` is not run during `processOnEntry()`
None
Evaluator ([test 1](https://evaluation.tier4.jp/evaluation/reports/306ed7e7-8895-5cc0-946a-fac880fd7f72?project_id=prd_jt))
- Some scenario has failed but the issue is not from this PR.
Evaluator (TBA)
None
None
None …

refactor(lane_change): update lc status in updateData

---

sensing/gnss_poser/schema/gnss_poser.schema.json

Removed obsolete parameter `gnss_frame` from `gnss_poser.schema.json`
This should have been removed in https://github.com/autowarefoundation/autoware.universe/pull/6116  But it was not.
This package passes the JSON schema check.
Does not affect.

fix(gnss_poser): remove gnss_frame from schema.json

---

sensing/pointcloud_preprocessor/docs/ring-outlier-filter.md
sensing/pointcloud_preprocessor/include/pointcloud_preprocessor/outlier_filter/ring_outlier_filter_nodelet.hpp
sensing/pointcloud_preprocessor/package.xml
sensing/pointcloud_preprocessor/src/outlier_filter/ring_outlier_filter_nodelet.cpp

This reverts commit e45c1ce8df336aef408650532b0477dd174ae27d.
It reduces computation time of ring_outlier_filter, but also results in missing points for pointpainting.
Part of the concatenated/pointcloud is lost when pointpainting module [filtering the points out of the range](https://github.com/autowarefoundation/autoware.universe/blob/main/perception/image_projection_based_fusion/src/pointpainting_fusion/node.cpp#L239-L241), while they actually lie within the range. This leads to the misdetection of the bus, because only half of its pointcloud is input to the network.
- blue points: /sensing/lidar/concatenated/pointcloud
- red points: /perception/object_recognition/detection/pointpainting/output
- blue bounding boxes: /perception/object_recognition/detection/objects
After reverting, the …

revert(perf_ring_outlier_filter): temporal revert for further investigation

---

evaluator/planning_evaluator/src/metrics/trajectory_metrics.cpp

Crashes were caused by subtracting 1 from unsigned integer (`size_t`), causing crashes with empty trajectories (where the size = 0).
To reproduce the crash, you can publish an empty trajectory with the following command:
```
ros2 topic pub /planning/scenario_planning/trajectory autoware_auto_planning_msgs/msg/Trajectory "{header: {stamp: now, frame_id: "base_link"}}"
```
PSim
[pull …

fix(planning_evaluator): fix crashes with empty trajectories

---

localization/ndt_scan_matcher/config/ndt_scan_matcher.param.yaml
localization/ndt_scan_matcher/include/ndt_scan_matcher/ndt_scan_matcher_core.hpp
localization/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp

`critical_upper_bound_exe_time_ms` has been modified from int type to double type.
LSim works.

fix(ndt_scan_matcher): fix type of critical_upper_bound_exe_time_ms

---

planning/behavior_velocity_crosswalk_module/config/crosswalk.param.yaml
planning/behavior_velocity_crosswalk_module/src/manager.cpp
planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp

This PR improve the stuck prevention function on the crosswalks.
[Screencast from 01-23-2024 03:28:44 PM.webm](https://github.com/autowarefoundation/autoware.universe/assets/141538661/d6803e77-c132-4ca3-8809-51bcd2eb7c52)
launch PR: https://github.com/autowarefoundation/autoware_launch/pull/816 …

feat(crosswalk)!: improve stuck prevention on crosswalk

---

planning/behavior_path_dynamic_avoidance_module/src/scene.cpp

inherit modified goal
evaluator_description: fix/dynamic_avoindace_modified_goal
2024/01/26 https://evaluation.tier4.jp/evaluation/reports/33f24db9-516f-5310-afd9-2a1125c16467/?project_id=prd_jt

fix(dynamic_avoidance_planner): inherit modified goal

---

planning/behavior_path_planner_common/src/utils/drivable_area_expansion/static_drivable_area.cpp
planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/start_planner_module.hpp
planning/behavior_path_start_planner_module/src/start_planner_module.cpp

`drivable_margin` is set for freespace planner in start_planner module and the start_planner assume the parameter is not erased following modules.
But in some cases like dynamic_avoidance module runs after start_planner module, `drivable_margin` is erased.
so in this PR, changed `combineDrivableAreaInfo` to inherit `drivable_margin` from previous module output 
[pull request …

fix(start_planner): update drivable area info and enable idle to running state transition

---

localization/localization_error_monitor/src/diagnostics.cpp
simulator/fault_injection/config/fault_injection.param.yaml
system/system_error_monitor/config/diagnostic_aggregator/localization.param.yaml
system/system_error_monitor/config/system_error_monitor.param.yaml
system/system_error_monitor/config/system_error_monitor.planning_simulation.param.yaml

This is for the issue https://github.com/autowarefoundation/autoware.universe/issues/3065
This must be merged simultaneously with https://github.com/autowarefoundation/autoware_launch/pull/605 .
Rename "localization_accuracy" to localization_error_ellipse
It was confirmed that Build is OK.
Start to display `localization_error_ellipse` instead of `localization_accuracy`.  …

refactor(localization_error_monitor): rename localization_accuracy

---

planning/behavior_path_planner/src/planner_manager.cpp

sort keep last modules considering priority.
when the parameter is following dynamic_avoiadnce shoulder be last.
```
goal_planner:
enable_rtc: false
enable_simultaneous_execution_as_approved_module: true
enable_simultaneous_execution_as_candidate_module: false
keep_last: true
priority: 1
max_module_size: 1
dynamic_avoidance:
enable_rtc: false
enable_simultaneous_execution_as_approved_module: true
enable_simultaneous_execution_as_candidate_module: true
keep_last: true
priority: 7
max_module_size: 1
```
before
after
psim
2024/01/25 https://evaluation.tier4.jp/evaluation/reports/2744b0ff-2c3b-5816-94fd-0f0ffe27b725/?project_id=prd_jt
https://evaluation.tier4.jp/evaluation/reports/254e158d-7800-583e-b078-7a9529a53b86?project_id=prd_jt …

fix(behavior_path_planner): sort keep last modules considering priority

---

localization/yabloc/yabloc_common/README.md
localization/yabloc/yabloc_image_processing/README.md

Fixed parameter visualizations that were not updated in  https://github.com/autowarefoundation/autoware.universe/pull/6170
With the following, I confirmed that there are 10 json.schema under `localization/yabloc/`.
```
$ find localization/yabloc/ |grep schema.json
localization/yabloc/yabloc_monitor/schema/yabloc_monitor.schema.json
localization/yabloc/yabloc_image_processing/schema/undistort.schema.json
localization/yabloc/yabloc_image_processing/schema/graph_segment.schema.json
localization/yabloc/yabloc_image_processing/schema/segment_filter.schema.json
localization/yabloc/yabloc_common/schema/ground_server.schema.json
localization/yabloc/yabloc_common/schema/ll2_decomposer.schema.json
localization/yabloc/yabloc_particle_filter/schema/gnss_particle_corrector.schema.json …
```

chore(yabloc): replace parameters by json_to_markdown in readme

---

planning/behavior_path_avoidance_module/src/utils.cpp

Turn signal doesn't turn on if the adjacent and current lanelet share its previous lanelet.
[Screencast from 2024年01月23日 16時14分37秒.webm](https://github.com/autowarefoundation/autoware.universe/assets/44889564/00c65d43-2a46-4238-b5d2-9ec094dbf690)
Psim.
Uploading simplescreenrecorder-2024-01-26_18.11.19.mp4…
Fix turn signal bug. …

fix(avoidance): turn signal doesn't turn on

---

planning/behavior_path_avoidance_module/src/utils.cpp

Fix bug caused by https://github.com/autowarefoundation/autoware.universe/pull/6188. Check opposite lane existence.
[CURRENT TEST RESULT](https://evaluation.tier4.jp/evaluation/reports/749ee5ec-b9eb-51d7-ad73-d9793bcc33c2/tests/892400f8-ec6c-51fe-984d-8595d6ba52ad?project_id=prd_jt) (80FAILs: 217/297)
](https://evaluation.tier4.jp/evaluation/reports/0d48a29d-80fa-53d3-b043-938a59a63800?project_id=prd_jt)
Nothing.
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/con …

fix(avoidance): fix bug in turn signal decision

---

perception/detected_object_validation/config/obstacle_pointcloud_based_validator.param.yaml
perception/detected_object_validation/config/occupancy_grid_based_validator.param.yaml
perception/detected_object_validation/launch/obstacle_pointcloud_based_validator.launch.xml
perception/detected_object_validation/launch/occupancy_grid_based_validator.launch.xml

Use parameter file
Launch each nodes individually and confirmed that they load parameters as expected
No effect expected

chore(detected_object_validation): rework parameters

---

planning/behavior_path_avoidance_by_lane_change_module/src/scene.cpp
planning/behavior_path_avoidance_module/config/avoidance.param.yaml
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/data_structs.hpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/parameter_helper.hpp
planning/behavior_path_avoidance_module/src/scene.cpp
planning/behavior_path_planner/src/planner_manager.cpp
planning/behavior_path_planner_common/include/behavior_path_planner_common/data_manager.hpp
planning/behavior_path_planner_common/include/behavior_path_planner_common/utils/drivable_area_expansion/static_drivable_area.hpp
planning/behavior_path_planner_common/src/utils/drivable_area_expansion/static_drivable_area.cpp

Previously, since avoidance module didn't consider freespace areas (parking log) as drivable space, sometimes the ego couldn't avoid objects. (In this case, the module used only lanelets as drivable space.)
In this PR, I implement new feature to use freespace to avoid objects.
Please review this PR at first.
https://github.com/autowarefoundation/autoware_launch/pull/818
https://github.com/autowarefoundation/autoware.universe/assets/44889564/b39b99f9-9aac-4966-8041-dfdd3815afed
Improve avoidance flexibility. …

feat(avoidance): make it possible to use freespace areas in avoidance module

---

planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/interface.hpp
planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/utils/base_class.hpp
planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/utils/debug_structs.hpp
planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/utils/markers.hpp
planning/behavior_path_lane_change_module/src/interface.cpp
planning/behavior_path_lane_change_module/src/scene.cpp
planning/behavior_path_lane_change_module/src/utils/markers.cpp

Combine all debug data in lane change into single struct.
This is so that if new debug info is added, we dont need to update the `base_class.hpp`
None
Tested via PSIM.
None
None
None

refactor(lane_change): combine all debug data into single struct

---

perception/tracking_object_merger/config/data_association_matrix.param.yaml
perception/tracking_object_merger/src/utils/utils.cpp

This PR fixes wrong association settings for tracking object merger.
- before: unknown class was not associated each other
- after: unknown objects will associated each other
Less unknown objects will appear

fix(tracking_object_merger): enable to association unknown class in tracker merger

---

localization/ndt_scan_matcher/README.md
localization/ndt_scan_matcher/config/ndt_scan_matcher.param.yaml
localization/ndt_scan_matcher/include/ndt_scan_matcher/ndt_scan_matcher_core.hpp
localization/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp

I renamed "de-grounded" to pass the spell check.
LSim works

refactor(ndt_scan_matcher): rename de-grounded

---

planning/behavior_velocity_blind_spot_module/src/scene.cpp
planning/behavior_velocity_blind_spot_module/src/scene.hpp
planning/behavior_velocity_intersection_module/src/scene_intersection_collision.cpp

add objects of interest marker for intersection and blind_spot

feat(intersection, blind_spot): add objects of interest marker

---

localization/yabloc/yabloc_pose_initializer/CMakeLists.txt
localization/yabloc/yabloc_pose_initializer/package.xml

Missing dependencies for `yabloc_pose_initializer` that uses OpenCV

build(yabloc_pose_initializer): fix dependencies

---

planning/behavior_velocity_intersection_module/src/decision_result.cpp
planning/behavior_velocity_intersection_module/src/scene_intersection.cpp

Basically pass judge passage is judged when "was_safe". And when occlusion detection is enabled, at intersection without traffic light, "OccludedAbsenceTrafficLight" context is treated as safe in terms of occlusion.
https://tier4.atlassian.net/browse/RT1-4771
intersection occlusion is ON
the pass judge line is still green after passage
the pass judge line turns red after passage
none
none
[pull request …

fix(intersection): judge pass judge at intersection without tl with occlusion detection

---

perception/traffic_light_fine_detector/launch/traffic_light_fine_detector.launch.xml

I confirmed that it launches with 
`ros2 launch traffic_light_fine_detector  traffic_light_fine_detector.launch.xml `
No effectes

chore(traffic_light_fine_detector): fix_default_tlr_yolox_model_name

---

planning/behavior_path_avoidance_module/src/debug.cpp
planning/behavior_path_avoidance_module/src/utils.cpp

Fow now, unknown objects tracking result is more unstable than other class objects. Sometimes, ghost unknown object is detected and avoidance module generates unnecessary path.
In this PR, I added another target filtering logic for unknown to keep current path until module confirmed the unknown is actually exist and keeps stopping more that 3.0 seconds. 
Related Ticket: https://tier4.atlassian.net/browse/RT1-5044
https://github.com/autowarefoundation/autoware.universe/assets/44889564/e4097daf-c20a-4b7c-8aa9-a3c939dff588
Suppress unnecessary avoidance behavior. …

fix(avoidance): update filtering logic for non-vehicle

---

planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/goal_planner_module.hpp
planning/behavior_path_goal_planner_module/src/goal_planner_module.cpp

when ego vehicle is far from previous module output, do not update path based on that to prevent sudden steer maneuver
evaluator_description: fix/goal_planner_path_update
2024/01/30 https://evaluation.tier4.jp/evaluation/reports/a424adc8-7204-5a6f-ae4c-3a03318c8b86/?project_id=prd_jt
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/ …

fix(goal_planner): fix deviated path update

---

map/map_loader/src/pointcloud_map_loader/pointcloud_map_loader_node.cpp

When using a divided map, `pointcloud_map_metadata.yaml` is required.
However, when autoware was run without it, the cause was not displayed in the error message.
This pull request has been modified so that the following error message appears once per second.
```
[map.pointcloud_map_loader]: PCD metadata file not found: /path/to/pointcloud_map_metadata.yaml
```
<details>
<summary>Example of error messages that appears on the screen</summary>
```
[component_container-27] [ERROR] [1706590993.214443999] [map.pointcloud_map_loader]: PCD metadata file not found: /home/shintarosakoda/Downloads/nishishinjuku_autoware_map_divided_without_metadata/pointcloud_map_metadata.yaml
[scenario_selector-68] [INFO] [1706590993.254920052] [planning.scenario_planning.scenario_selector]: Waiting for current …
```

fix(map_loader): change error handling when pcd_metadata file not found

---

planning/behavior_path_goal_planner_module/src/goal_planner_module.cpp

add extra_lateral_margin to both side
tier4 internal ticket https://tier4.atlassian.net/browse/RT1-5080
psim
evaluator_description: feat/extra_lateral_margin
2024/01/30 https://evaluation.tier4.jp/evaluation/reports/cedc6047-7cb6-5b1f-a9a5-f52b371d8230/?project_id=prd_jt
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request- …

feat(goal_planner): add extra_lateral_margin to both side

---

mkdocs_macros.py

I want to add an item to properties in [this part](https://github.com/autowarefoundation/autoware.universe/blob/2d819a3a217562e1df5cd43ba7274813add77f08/localization/ndt_scan_matcher/schema/sub/ndt.json#L38-L40) of [this PR](https://github.com/autowarefoundation/autoware.universe/pull/6229
), just for reference. However, when creating a table in a JSON file, it gives the following error.
So, if an item contains $ref, I would like to exclude it from the table creation.
browse several pages using  `mkdocs serve` and confirmed that the formatting is not distorted.
After …

feat(mkdocs_macros): ignore  when creating a table

---

planning/behavior_path_avoidance_module/src/scene.cpp
planning/behavior_path_avoidance_module/src/utils.cpp

Add function to check if the object is stopped or not.
```c++
bool isMovingObject(
const ObjectData & object, const std::shared_ptr<AvoidanceParameters> & parameters)
{
const auto object_type = utils::getHighestProbLabel(object.object.classification);
const auto object_parameter = parameters->object_parameters.at(object_type);
return object.move_time > object_parameter.moving_time_threshold;
}
```
Psim
Nothing. …

refactor(avoidance): add function to check if the object is moving

---

planning/behavior_path_lane_change_module/src/interface.cpp
planning/behavior_path_lane_change_module/src/scene.cpp

Before this change, lane change module does not generate lane change path during abort state.
In this change, it will generate lane change path and wait approval during abort state.
[TIER IV INTERNAL LINK](https://evaluation.tier4.jp/evaluation/reports/d6bb0dcd-aa5e-5008-baa8-7ff9dabc9088?project_id=prd_jt)
[Screencast from 2024年01月30日 17時24分05秒.webm](https://github.com/autowarefoundation/autoware.universe/assets/10190493/4a06fbcd-1fe3-4587-b351-2e9ad04dad84)
Lane change module outputs lane change candidate during abort state. …

feat(lane_change): wait approval with abort state

---

perception/ground_segmentation/CMakeLists.txt
perception/ground_segmentation/config/ground_segmentation.param.yaml
perception/ground_segmentation/config/ransac_ground_filter.param.yaml
perception/ground_segmentation/config/ray_ground_filter.param.yaml
perception/ground_segmentation/config/scan_ground_filter.param.yaml
perception/ground_segmentation/launch/ransac_ground_filter.launch.xml
perception/ground_segmentation/launch/ray_ground_filter.launch.xml
perception/ground_segmentation/launch/scan_ground_filter.launch.xml
perception/ground_segmentation/src/ransac_ground_filter_nodelet.cpp
perception/ground_segmentation/src/ray_ground_filter_nodelet.cpp
perception/ground_segmentation/src/scan_ground_filter_nodelet.cpp
perception/ground_segmentation/test/test_ray_ground_filter.cpp
perception/ground_segmentation/test/test_scan_ground_filter.cpp

- Add default parameter file for each node. 
- Must merge with https://github.com/autowarefoundation/autoware_launch/pull/831
- Confirm each node of `ground_segmentation` successfully loads the default paramters from yaml file.

chore(ground_segmentation): rework params

---

perception/lidar_centerpoint/package.xml

to remove a maintainer from package.xml

chore: remove maintainer

---

planning/obstacle_stop_planner/src/node.cpp

add vector size guard to fix this issue https://github.com/autowarefoundation/autoware.universe/issues/6151
psim tests

fix(obstacle_stop): add vector size guard

---

.github/workflows/build-and-test-differential.yaml

Use GitHub runner.
The runner has been changed as follows:
- https://github.com/autowarefoundation/autoware.universe/pull/4364 GitHub runner -> self-hosted runner
- https://github.com/autowarefoundation/autoware.universe/pull/4413 self-hosted runner -> EC2 runner
- https://github.com/autowarefoundation/autoware.universe/pull/4477 EC2 runner -> self-hosted runner
Apparently the disk image size has been reduced, and thus we would like to use GitHub Runner again, since current self-hosted runner based CI is too slow to execute multiple PRs.
Test run: https://github.com/HansRobo/autoware.universe/actions/runs/7736637727/job/21094318337
Remaining disk space:
```
$ dh -a
Filesystem     1K-blocks     Used Available Use% Mounted on
overlay         87204404 75316916  11871104  87% /
```
`du` …

ci(build-and-test-differential): use github runner

---

localization/ndt_scan_matcher/config/ndt_scan_matcher.param.yaml
localization/ndt_scan_matcher/include/ndt_scan_matcher/hyper_parameters.hpp
localization/ndt_scan_matcher/include/ndt_scan_matcher/map_update_module.hpp
localization/ndt_scan_matcher/include/ndt_scan_matcher/ndt_scan_matcher_core.hpp
localization/ndt_scan_matcher/src/map_update_module.cpp
localization/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp

hierarchized the parameters in the `config/ndt_scan_matcher.param.yaml` file.
Additionally, I made the following changes:
- structured the parameter variables in the source code.
- renamed some parameters.
- removed the `RCLCPP_INFO` output after loading parameters (as it is unnecessary to display).
- deleted `input_sensor_points_queue_size` (as there is no situation where this parameter changes, I fixed it to a constant value).
※Regarding the README, I plan to submit a PR introducing the JSON schema shortly after merging this PR, and I will update the README at that time. https://github.com/autowarefoundation/autoware.universe/pull/6229
LSim works …

refactor(ndt_scan_matcher): hierarchize parameters

---

planning/behavior_velocity_intersection_module/src/scene_intersection.cpp

currently INTERSECTION_OCCLUSION does not respond to RTC disapproval if the `occlusion.enable` is OFF, based on the assumption that the user will not have the need to stop at intersection_occlusion stopline if he/she disabled `occlusion.enable`. With this change, INTERSECTION_OCCLUSION responds RTC disapproval even if `occlusion.enable` is OFF.
https://github.com/autowarefoundation/autoware.universe/assets/28677420/0ed4623e-fe28-4d6b-b49a-add4a95041e0
INTERSECTION_OCCLUSION stops if it is manual even if `occlusion.enable` is OFF and the user intentionally disabled occlusion detection.
INTERSECTION_OCCLUSION stops if it is manual even if `occlusion.enable` is OFF and the user intentionally disabled occlusion detection. …

feat(intersection_occlusion)!: react RTC disapproval and stop even if occlusion detection is OFF

---

.github/workflows/build-and-test-differential.yaml

Check disk usage
Not applicable
Not applicable

ci(build-and-test-differential): add df -h

---

map/map_loader/src/lanelet2_map_loader/lanelet2_map_loader_node.cpp

Improve the error message when the map load fails.
run psim and check the error message.
None

chore(lanelet2_map_loader): enrich error message

---

planning/behavior_path_lane_change_module/README.md

add description for lane expansion
https://github.com/autowarefoundation/autoware.universe/commit/c99c6b2fc7062e6e21edb80a1b96797f59d04efb

docs(lane_change): add description for lane expansion

---

planning/behavior_velocity_intersection_module/src/scene_merge_from_private_road.cpp

In https://github.com/autowarefoundation/autoware.universe/pull/5972/files, the stopline offset confused with baselink2front.
https://evaluation.tier4.jp/evaluation/reports/ed4aeae1-f94b-580e-81e1-bcfa42680e6f?project_id=prd_jt
none
none

fix(merge_from_private): fix stop position calculation

---

common/tensorrt_common/include/tensorrt_common/logger.hpp

This pull request partially reverts https://github.com/autowarefoundation/autoware.universe/pull/6117 so that tensorrt_common can be built on Jetson Orin.
tensorrt_common was built on a Jetson Orin ECU.

fix(tensorrt_common): revert change that breaks build on Jetson Orin

---

map/map_loader/src/pointcloud_map_loader/pointcloud_map_loader_node.cpp

This reverts commit https://github.com/autowarefoundation/autoware.universe/pull/6227 (25bc636fe0f796c63daac60123aa6138146e515d).
After the pull request above, if "divided map is used and pointcloud_map_metadata.yaml is missing", initial_pose_adaptor does not work properly and there is unexpected side effects in planning_simulator, so we decide to revert.
* It has been confirmed that Autoware works properly if `pointcloud_map_metadata.yaml` is present (in AWSIM).
* It has been confirmed that the above error message continues to appear if `pointcloud_map_metadata.yaml` is missing (in AWSIM).
The error message will change. …

revert(map_loader): revert the change error handling when pcd_metadata file

---

perception/map_based_prediction/config/map_based_prediction.param.yaml
perception/map_based_prediction/include/map_based_prediction/map_based_prediction_node.hpp
perception/map_based_prediction/launch/map_based_prediction.launch.xml
perception/map_based_prediction/package.xml
perception/map_based_prediction/src/map_based_prediction_node.cpp

use crosswalk signals to predict the pedestrian paths
[Screencast from 01-29-2024 01:10:43 PM.webm](https://github.com/autowarefoundation/autoware.universe/assets/141538661/b764167a-9ab4-4586-8ffb-b48c488b143e)
psim tests and tier4 internal tests were perfomed.
https://evaluation.tier4.jp/evaluation/reports/2f207a70-d4d9-51d8-9e5f-37136b92e392?project_id=prd_jt
map_based_prediction becomes to subscribe `/perception/traffic_light_recognition/traffic_signals`. …

feat(map_based_prediction): consider crosswalks signals

---

planning/behavior_velocity_intersection_module/src/scene_intersection_occlusion.cpp

depends https://github.com/autowarefoundation/autoware.universe/pull/6272
this PR affects only intersections with traffic lights.
for the convenience of Psim users and scenario files, if no corresponding traffic light information is published for the associated traffic light, it is treated as "RED" and it only runs collision checking.
tested by setting `enable.occlusion` to true
until [00:58], no traffic signal information is published, so only collision is checked initially because traffic light is not published.
at [00:58] traffic light is published, so occlusion detection becomes effective and ego starts peeking and then stops.
at [02:10] the color is GREEN and intersection_occlusion is effective, but after that it turns YELLOW/RED, and intersection_occlusion is ignore. …

feat(intersection): initially ignore occlusion at intersection with tl, if tl info has never been available

---

planning/behavior_path_goal_planner_module/src/goal_planner_module.cpp

suppress error message
chaged error -> debug

chore(goal_planner): suppress error message

---

planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/utils/trajectory_utils.hpp
planning/path_smoother/include/path_smoother/utils/trajectory_utils.hpp

Fixes https://github.com/autowarefoundation/autoware.universe/issues/6205
Changed the logger level of debug print from WARN to DEBUG.
psim
Nothing

fix(obstacle_avoidance_planner, path_smoother): change logger level of debug print

---

.github/workflows/build-and-test-differential.yaml

This reverts https://github.com/autowarefoundation/autoware.universe/pull/6278 and https://github.com/autowarefoundation/autoware.universe/pull/6292 since actions still fail due to no disk space left on device.

ci(build-and-test-differential): revert use github runner

---

planning/obstacle_cruise_planner/README.md
planning/obstacle_cruise_planner/config/obstacle_cruise_planner.param.yaml
planning/obstacle_cruise_planner/include/obstacle_cruise_planner/common_structs.hpp
planning/obstacle_cruise_planner/include/obstacle_cruise_planner/node.hpp
planning/obstacle_cruise_planner/src/node.cpp

This PR adds an (optional) yield functionality for the obstacle cruise planner.  The yield action is performed by cruising behind vehicles on neighbor lanes that might cut in into the ego vehicle's current lane. 
How it works: 
The algorithm searches for cruise type obstacles that: 
a) are moving faster than a speed threshold (parameter) and are in front of the ego.
b) have another cruise obstacle that is stopped in front of them.
c) will collide with the stopped obstacle within a given time (if they continue a straight path towards it)
[TIER IV internal link](https://tier4.atlassian.net/browse/RT1-3025)
Scenario Evaluation tests: [TIER IV INTERNAL LINK](https://evaluation.ci.tier4.jp/evaluation/reports/d5ebd35f-0812-5d79-b912-e06fb831f1ed?project_id=prd_jt)
Several tests with PSim: …

feat(obstacle_cruise_planner): yield function for ocp

---

planning/behavior_path_avoidance_module/src/utils.cpp

Fix bug. In previous implementaion, the module calculated the shift ratioby using envelope polygon centroid for each objects. But it should use original object's position in that logic.
Improve avoidance maneuver.

fix(avoidance): don't use polygon centroid in shiftable ratio calculation

---

planning/behavior_path_start_planner_module/src/start_planner_module.cpp

Fixes: https://github.com/autowarefoundation/autoware.universe/issues/6317
https://github.com/autowarefoundation/autoware.universe/assets/32412808/04bb7073-9118-4ec0-9d07-219fef8ac466

fix(behavior_path_start_planner_module): check if pull_out_path is empty

---

planning/behavior_velocity_intersection_module/src/object_manager.cpp

fixed the wrong midpoint calculation from
```
x + y /  2.0
```
to
```
(x + y) / 2.0
```
https://tier4.atlassian.net/browse/RT1-4773
at [00:15], unnecessary stop happens due to miscalculation
https://github.com/autowarefoundation/autoware.universe/assets/28677420/ea8aa057-2e75-4b04-a7e6-9bcbb020ebe8
https://github.com/autowarefoundation/autoware.universe/assets/28677420/9ebe04a8-0ede-425c-ab05-ca58def7aed8
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributin …

fix(intersection): fix stopline midpoint calculation

---

localization/ekf_localizer/README.md
localization/ekf_localizer/config/ekf_localizer.param.yaml
localization/ekf_localizer/include/ekf_localizer/hyper_parameters.hpp
localization/ekf_localizer/launch/ekf_localizer.launch.xml
localization/ekf_localizer/schema/ekf_localizer.schema.json
localization/ekf_localizer/schema/sub/diagnostics.sub_schema.json
localization/ekf_localizer/schema/sub/misc.sub_schema.json
localization/ekf_localizer/schema/sub/node.sub_schema.json
localization/ekf_localizer/schema/sub/pose_measurement.sub_schema.json
localization/ekf_localizer/schema/sub/process_noise.sub_schema.json
localization/ekf_localizer/schema/sub/simple_1d_filter_parameters.sub_schema.json
localization/ekf_localizer/schema/sub/twist_measurement.sub_schema.json

This pull request must be merged with [the autoware_launch pull request](https://github.com/autowarefoundation/autoware_launch/pull/847).
Please see both pull request.
Implement the ROS Node configuration layout described in https://github.com/orgs/autowarefoundation/discussions/3371.
- Remove the default value from the source code in order to ensure all parameter values are passed from the parameter files.
- already completed.
- Create the yaml configs in this package and the autoware_launch repository.
- already completed.
- Create the schema.
- This PR.
- Update `Parameters` chapter in the readme file.
- This PR.
1. run autoware & replay rosbag that can start localization(Autoware sample rosbag is recommended).
2. command the following
```
ros2 param dump …
```

refactor(ekf_localizer): rework parameters

---

planning/behavior_path_start_planner_module/src/start_planner_module.cpp

remove unnecessary debug print

fix(start_planner): remove debug print statement in setDrivableAreaInfo function

---

planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/goal_planner_module.hpp
planning/behavior_path_goal_planner_module/src/goal_planner_module.cpp
planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/start_planner_module.hpp
planning/behavior_path_start_planner_module/src/start_planner_module.cpp

Wait for the multithreaded callback to finish in the destructor for 
https://github.com/autowarefoundation/autoware.universe/issues/5154
psim
evaluator_description: fix/start_goal_multithread
2024/02/06 https://evaluation.tier4.jp/evaluation/reports/a099d691-034b-5484-a751-547fe6c34756/?project_id=prd_jt
evaluator_description: fix/start_goal_multithread
2024/02/06 https://evaluation.tier4.jp/evaluation/reports/18277ac1-dd2a-5069-bced-148402a874bf/?project_id=prd_jt
[contribution …

fix(start/goal_planner): fix multi thread memory crash

---

perception/multi_object_tracker/src/tracker/model/bicycle_tracker.cpp
perception/multi_object_tracker/src/tracker/model/big_vehicle_tracker.cpp
perception/multi_object_tracker/src/tracker/model/normal_vehicle_tracker.cpp

When detected object type is cylinder, it has no length. 
The current tracker always updates its bounding box dimension, and then update the wheel-to-center lengths.
This fix limits the wheel-to-center lengths `lr_` and `lf_` to have a minimum values, so that the prediction do not divide very small number. 
Tested on Tier4 deployment environment and its data replay.
[pull request …

fix(multi_object_tracker): bicycle motion model - set minimum wheel-to-center length

---

planning/behavior_velocity_intersection_module/src/scene_intersection_occlusion.cpp

To run intersection_occlusion by default, PR https://github.com/autowarefoundation/autoware.universe/pull/6273 was shipped to handle intersection with traffic light smoothly. But it was missing the care for intersection without traffic light.
https://evaluation.tier4.jp/evaluation/reports/16a8370a-8fc2-5763-8dbe-3520492cef8c?project_id=prd_jt
initially, if no traffic light information is available, occlusion is ignored.
if traffic light information is available, occlusion is cared.
[contribution …

fix(intersection_occlusion): fix for PR6273 without traffic light

---

planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/helper.hpp
planning/behavior_path_avoidance_module/src/shift_line_generator.cpp

In following case, the module judge the object is avoidable but the output path violates jerk limitation. The cause is that the module validates path safety with same parameter for path generation. In order to fix this issue, I added small margin to confortable check condition.
```c++
bool isComfortable(const AvoidLineArray & shift_lines) const
{
const auto JERK_BUFFER = 0.1;  // [m/sss]
return std::all_of(shift_lines.begin(), shift_lines.end(), [&](const auto & line) {
return PathShifter::calcJerkFromLatLonDistance(
line.getRelativeLength(), line.getRelativeLongitudinal(), getAvoidanceEgoSpeed()) <
getLateralMaxJerkLimit() + JERK_BUFFER;
});
}
```
Basically, avoidance module inserts stop point only for objects it can avoid. But sometimes the module inserts stop point unexpectedly for …

fix(avoidance): unexpected stop decision in avoidance module

---

sensing/pointcloud_preprocessor/src/concatenate_data/concatenate_and_time_sync_nodelet.cpp
sensing/pointcloud_preprocessor/src/time_synchronizer/time_synchronizer_nodelet.cpp

- concatenate process exit with completing topics subscription or timeout
- topic with empty pointclouds are returned and not counted as subscribed, so that the concatenate node will wait until timeout. This will cause a slight delay.
- Our XX1 vehicle faces lower topic rate with this problem
- enable concatenate node to count empty pointclouds as well
- Need some escape for the latter concatenation process
[TIER IV INTERNAL SLACK DISCUSSION](https://star4.slack.com/archives/CEV8XMJBV/p1706778201191269?thread_ts=1706602751.904249&cid=CEV8XMJBV)
Tested with jpntaxi settings and rosbag. …

feat(pointcloud_preprocessor): enable to count empty pointclouds topic in concatenate pointclouds nodelet

---

perception/object_range_splitter/src/node.cpp

Delete default parameter in src of `object_range_splitter`.
No

fix(object_range_splitter): delete default param in src

---

control/joy_controller/config/joy_controller.param.yaml
control/joy_controller/launch/joy_controller.launch.xml
control/trajectory_follower_node/CMakeLists.txt
control/trajectory_follower_node/config/simple_trajectory_follower.param.yaml
control/trajectory_follower_node/launch/simple_trajectory_follower.launch.xml
control/vehicle_cmd_gate/config/vehicle_cmd_gate.param.yaml
control/vehicle_cmd_gate/launch/vehicle_cmd_gate.launch.xml
control/vehicle_cmd_gate/test/src/test_filter_in_vehicle_cmd_gate_node.cpp
planning/obstacle_avoidance_planner/launch/obstacle_avoidance_planner.launch.xml
planning/obstacle_stop_planner/config/obstacle_stop_planner.param.yaml
planning/obstacle_stop_planner/launch/obstacle_stop_planner.launch.xml
vehicle/external_cmd_converter/CMakeLists.txt
vehicle/external_cmd_converter/config/external_cmd_converter.param.yaml
vehicle/external_cmd_converter/launch/external_cmd_converter.launch.xml

In order to ready for JSON scheme, change ROS params to declare in yaml files.
launch: https://github.com/autowarefoundation/autoware_launch/pull/833
the work for raw_vehicle_cmd_converter is still remain.
Not yet

chore(planning/control/vehicle): declare ROS params in yaml files

---

planning/behavior_velocity_intersection_module/config/intersection.param.yaml
planning/behavior_velocity_intersection_module/src/manager.cpp
planning/behavior_velocity_intersection_module/src/scene_intersection.hpp
planning/behavior_velocity_intersection_module/src/scene_intersection_collision.cpp

use different expected deceleration for bike/car on amber/red traffic light
https://github.com/autowarefoundation/autoware_launch/pull/852
https://tier4.atlassian.net/browse/RT1-4773
https://evaluation.tier4.jp/evaluation/reports/a40b1c77-0f2a-5017-95e8-f397bf4c3f25?project_id=prd_jt
at [00:12] intersection stop line is released
https://github.com/autowarefoundation/autoware.universe/assets/28677420/8a7514ad-73e3-4973-ac40-f43eff873e51
none
none …

feat(intersection): use different expected deceleration for bike/car

---

common/tier4_target_object_type_rviz_plugin/src/target_object_type_panel.cpp

Update some ros parameter names for the target_object_type
Before
After
None

chore(object_type_panel): update rosparam name config

---

planning/behavior_velocity_intersection_module/src/object_manager.cpp
planning/behavior_velocity_intersection_module/src/object_manager.hpp
planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
planning/behavior_velocity_intersection_module/src/scene_intersection.hpp
planning/behavior_velocity_intersection_module/src/scene_intersection_collision.cpp
planning/behavior_velocity_intersection_module/src/scene_intersection_occlusion.cpp
planning/behavior_velocity_intersection_module/src/scene_intersection_prepare_data.cpp

added `const` to member functions for readability
https://evaluation.tier4.jp/evaluation/reports/a40b1c77-0f2a-5017-95e8-f397bf4c3f25?project_id=prd_jt

chore(intersection): add const to member functions, replace enum with class tag for occlusion

---

planning/behavior_path_goal_planner_module/config/goal_planner.param.yaml
planning/behavior_path_start_planner_module/README.md
planning/behavior_path_start_planner_module/config/start_planner.param.yaml

remove unused param and update time horizon for goal planner's safety check
launcher change in this [PR](https://github.com/autowarefoundation/autoware_launch/pull/863) should be merged first
confirmed goal planner's safety check properly working
[Screencast from 2024年02月07日 21時56分46秒.webm](https://github.com/autowarefoundation/autoware.universe/assets/32741405/5a71dbe9-fcab-44e3-9db5-c9ca153e3090)
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/co …

feat(start/goal_planner): remove unused param and update time horizon for goal planner's safety check

---

planning/behavior_path_avoidance_by_lane_change_module/src/scene.cpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/data_structs.hpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/helper.hpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/utils.hpp
planning/behavior_path_avoidance_module/src/debug.cpp
planning/behavior_path_avoidance_module/src/scene.cpp
planning/behavior_path_avoidance_module/src/shift_line_generator.cpp
planning/behavior_path_avoidance_module/src/utils.cpp

Related tickets: https://tier4.atlassian.net/browse/RT1-4740
This PR includes following two modifications of stopped objects handling:
commit: https://github.com/autowarefoundation/autoware.universe/pull/6252/commits/0cedbfc152b2f311569e4829a19afc3d5d875e3f
Previously, the avoidance module considered all objects in safety check logic. But sometimes it judged **UNSAFE** for stopped object on shift side lane. This caused unnecessary yield maneuver. (Basically, I don't think it's meaningless to yield for stopped objects.) Therefore, I fixed logic in order to ignore them in safety check logic.
commit: https://github.com/autowarefoundation/autoware.universe/pull/6252/commits/e6f5cabaf494f01a0d4d7343b15324b8834adbe9
On the other hand, it need to consider stopped object in avoidance path …

feat(avoidance): consider objects on shift side lane

---

planning/behavior_path_lane_change_module/src/utils/utils.cpp

solve this issue[TIER IV internal JIRA link](https://tier4.atlassian.net/browse/RT1-5047)
When start planner performing geometric pull out, it requires time to transition to recovery steering angle. Therefore ego needs to stop during this recovery perios.
However, due to ego is currently in the current lane of lane change, it caused lane change to be activated, and the start planner path and ego vehicle path is combined.
Lane change path uses previous path output as the preparation path, and also compute new lane changing path. As the result of this combination, start planner couldn't perform the recovery steering, due to the discontinuity of the path caused by the combination of start planner path and lane change path.
To avoid this issue, when computing lane change path, the continuity …

fix(lane_change): orientation check when constructing path

---

planning/behavior_velocity_intersection_module/config/intersection.param.yaml
planning/behavior_velocity_intersection_module/src/manager.cpp
planning/behavior_velocity_intersection_module/src/scene_intersection.hpp
planning/behavior_velocity_intersection_module/src/scene_intersection_collision.cpp
planning/behavior_velocity_intersection_module/src/scene_intersection_stuck.cpp

https://github.com/autowarefoundation/autoware_launch/pull/851
set the target vehicle type for
- stuck vehicle detection
- yield stuck vehicle detection
- collision detection
https://evaluation.tier4.jp/evaluation/reports/a40b1c77-0f2a-5017-95e8-f397bf4c3f25?project_id=prd_jt
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-req …

chore(intersection): target type param

---

planning/behavior_path_planner_common/src/utils/drivable_area_expansion/static_drivable_area.cpp

Fix invalid drivable area bound z-pos.
Psim
Nothing.

fix(static_drivable_area_expansion): fix invalid z-pos

---

control/autonomous_emergency_braking/include/autonomous_emergency_braking/node.hpp
control/autonomous_emergency_braking/package.xml
control/autonomous_emergency_braking/src/node.cpp

AEB calculates empty path when ego is low speed, so empty check is necessary internally.
https://tier4.atlassian.net/browse/RT1-5170

fix(AEB): check empty path at low speed

---

control/control_validator/src/control_validator.cpp

Add error handling for an empty trajectory.
Note: this is a temporal fix. This invalid size must be handled as an error diag.
[TIERIV INTERNAL LINK](https://tier4.atlassian.net/browse/RT1-4972)
run psim and publish an empty trajectory.
```
ros2 topic pub /planning/scenario_planning/trajectory autoware_auto_planning_msgs/msg/Trajectory "{header: {stamp: now, frame_id: map}}"
```
**Before**
**After**
None
None
None
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/con …

fix(control_validator): process died for an empty trajectory

---

common/tier4_adapi_rviz_plugin/src/route_panel.cpp
common/tier4_adapi_rviz_plugin/src/route_panel.hpp

Add route change button to call `/api/routing/change_route_points` API.
None
1. Launch planning simulation and initialize pose.
2. Add RoutePanel by selecting "Panels" -> "Add new panel" from the rviz menu.
3. Change the topic name of 2D Goal Pose to "/rviz/routing/pose" by the topic property panel. 
4. Clear the "auto clear" checkbox.
5. Set the route.
6. Set the route again
7. Check that setting the route fails.
8. Push change button
9. Check that setting the route succeeds.
None
None
None
[contribution …

feat(tier4_adapi_rviz_plugin): add change button to the route panel

---

planning/behavior_path_dynamic_avoidance_module/include/behavior_path_dynamic_avoidance_module/scene.hpp
planning/behavior_path_dynamic_avoidance_module/src/scene.cpp

fix(dynamic_avoidance): fix minor bugs and comment

---

perception/map_based_prediction/README.md
perception/map_based_prediction/config/map_based_prediction.param.yaml
perception/map_based_prediction/include/map_based_prediction/map_based_prediction_node.hpp
perception/map_based_prediction/src/map_based_prediction_node.cpp
planning/behavior_velocity_crosswalk_module/README.md
planning/behavior_velocity_crosswalk_module/config/crosswalk.param.yaml
planning/behavior_velocity_crosswalk_module/src/manager.cpp
planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp

Re-implementation of pedestrians' behavior prediction against green signal
[Screencast from 02-07-2024 05:33:45 PM.webm](https://github.com/autowarefoundation/autoware.universe/assets/141538661/4f8a3eeb-6aa5-4353-856b-1abe91486cf3)
launch PR: https://github.com/autowarefoundation/autoware_launch/pull/860
https://evaluation.tier4.jp/evaluation/reports/3b89397e-be2d-578a-a5d5-e5eda5c762a1?project_id=prd_jt …

feat(map based prediction, crosswalk)!: transplantation of pedestrians' behavior prediction against green signal

---

perception/map_based_prediction/src/map_based_prediction_node.cpp

There are the cases that static objects yaw orientation flipping.
This is caused by `MapBasedPredictionNode::updateObjectData(TrackedObject & object)`, so this PR tried to fix flipping by skipping orientation fix process when target object is stable.
Tested with Psim.
Static object will be no more flipping.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contr …

feat(map_based_prediction): fix object flipping via update function

---

planning/behavior_velocity_out_of_lane_module/src/footprint.cpp
planning/behavior_velocity_out_of_lane_module/src/lanelets_selection.cpp
planning/behavior_velocity_out_of_lane_module/src/lanelets_selection.hpp
planning/behavior_velocity_out_of_lane_module/src/overlapping_range.cpp
planning/behavior_velocity_out_of_lane_module/src/scene_out_of_lane.cpp

This PR improves the `out_of_lane` module to reduces the amount of wrong stops it triggers.
The module uses "path lanelets" and assumes that it is fine for the ego footprint to enter these lanelets, and no `out_of_lane` stop can be triggered.
Previously, only the lanelets whose IDs were set in the path message were considered "path lanelets". Now, all lanelets crossed by the ego path linestring are considered.
Psim, perception reproducer and evaluator (https://evaluation.tier4.jp/evaluation/reports/tables/new?catalog_id=095ae8b3-a23b-4a08-8674-10a681449693&filter=&job_id=6905310e-f675-5fd8-a32a-4f074603610e&project_id=prd_jt&table_config=date).
Less wrong stops with the `out_of_lane` module. …

fix(out_of_lane): ignore overlaps over all lanelets crossed by the ego path

---

control/vehicle_cmd_gate/src/vehicle_cmd_gate.cpp
control/vehicle_cmd_gate/src/vehicle_cmd_gate.hpp

This PR solves the following issues:
* If the user sends stop command to autoware while driving, autoware does not do steering control while stopping: https://github.com/autowarefoundation/autoware.universe/issues/5796
* https://github.com/autowarefoundation/autoware.universe/issues/4915
* https://github.com/autowarefoundation/autoware.universe/issues/6044
Tested on Psim, working as we want.
[pull …

fix(vehicle_cmd_gate): fix the problems while transition from/to stopped state

---

perception/object_velocity_splitter/src/object_velocity_splitter_node/object_velocity_splitter_node.cpp

Delete default parameter in src of `object_velocity_splitter`.
No

fix(object_velocity_splitter): delete default param in src

---

perception/simple_object_merger/src/simple_object_merger_node/simple_object_merger_node.cpp

Delete default parameter in src of `simple_object_merger`.
No

fix(simple_object_merger): delete default param in src

---

sensing/radar_tracks_noise_filter/src/radar_tracks_noise_filter_node/radar_tracks_noise_filter_node.cpp

Delete default parameter in src of `radar_tracks_noise_filter`.
No

fix(radar_tracks_noise_filter): delete default param in src

---

sensing/radar_threshold_filter/src/radar_threshold_filter_node/radar_threshold_filter_node.cpp

Delete default parameter in src of `radar_threshold_filter`.
No

fix(radar_threshold_filter): delete default param in src

---

perception/radar_crossing_objects_noise_filter/src/radar_crossing_objects_noise_filter_node/radar_crossing_objects_noise_filter_node.cpp

Delete default parameter in src of `radar_crossing_objects_noise_filter`.
No

fix(radar_crossing_objects_noise_filter): delete default param in src

---

planning/behavior_path_start_planner_module/src/start_planner_module.cpp

Originally, all the start_planner specific information is visualized with the same topic of `/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/debug/start_planner`.
It becomes cluttered because everything is visualized by just enabling one checkbox as shown in the folloing screenshot.
After categorizing in this PR,
info marker's are 
- `back_end_pose`
- `start_pose`
- `end_pose`
- `static_collision_check_end_pose`
- `static_collision_check_end_polygon`
- `planner_type`
- `filtered_objects`
- `predicted_path_for_safety_check`
- `ego_and_target_polygon_relation`
- `ego_and_target_polygon_relation_text`
- `ego_and_target_polygon_relation_cube`
debug marker's are 
- `refined_start_pose`
- `full_path`
- `backward_driving_path`
- `start_pose_candidates`
- …

refactor(start_planner): separate debug and info marker for rviz visualization

---

launch/tier4_perception_launch/package.xml

By https://github.com/autowarefoundation/autoware.universe/pull/6361, `tensorrt_yolo` has been removed but still remained as `exec_depend` in `tier4_perception_launch`.
This PR will fix the following error.
```
tier4_perception_launch: Cannot locate rosdep definition for [tensorrt_yolo]
``` …

fix: remove `tensorrt_yolo` from package dependencies in launcher

---

planning/behavior_path_avoidance_module/src/utils.cpp

The avoidance module judged wrong avoidable judge because it used unexpected overhang point to calculate road shoulder distance.
Nothing.

fix(avoidance): fix bug in minimum overhang distance calculation

---

common/traffic_light_utils/include/traffic_light_utils/traffic_light_utils.hpp
common/traffic_light_utils/src/traffic_light_utils.cpp
common/traffic_light_utils/test/test_traffic_light_utils.cpp
perception/crosswalk_traffic_light_estimator/README.md
perception/crosswalk_traffic_light_estimator/include/crosswalk_traffic_light_estimator/node.hpp
perception/traffic_light_classifier/README.md
perception/traffic_light_classifier/include/traffic_light_classifier/classifier_interface.hpp
perception/traffic_light_classifier/include/traffic_light_classifier/cnn_classifier.hpp
perception/traffic_light_classifier/include/traffic_light_classifier/color_classifier.hpp
perception/traffic_light_classifier/include/traffic_light_classifier/nodelet.hpp
perception/traffic_light_classifier/src/cnn_classifier.cpp
perception/traffic_light_classifier/src/color_classifier.cpp
perception/traffic_light_classifier/src/nodelet.cpp
perception/traffic_light_classifier/src/single_image_debug_inference_node.cpp
perception/traffic_light_multi_camera_fusion/include/traffic_light_multi_camera_fusion/node.hpp
perception/traffic_light_multi_camera_fusion/src/node.cpp
perception/traffic_light_occlusion_predictor/include/traffic_light_occlusion_predictor/nodelet.hpp
perception/traffic_light_occlusion_predictor/src/nodelet.cpp
perception/traffic_light_visualization/README.md
perception/traffic_light_visualization/include/traffic_light_visualization/traffic_light_roi_visualizer/nodelet.hpp
perception/traffic_light_visualization/src/traffic_light_roi_visualizer/nodelet.cpp

- Rename traffic_signal to traffic_light
- MUST BE MERGED AFTER https://github.com/tier4/tier4_autoware_msgs/pull/112
- [INTERNAL discussion link](https://star4.slack.com/archives/C4P0NSMB5/p1707124882013789?thread_ts=1707108734.051959&cid=C4P0NSMB5) 
Confirmed that the perception function runs correctly with logging_simulator.launch.xml. …

refactor(tier4_perception_msgs): rename traffic_signal to traffic_light

---

planning/behavior_path_planner_common/include/behavior_path_planner_common/utils/drivable_area_expansion/static_drivable_area.hpp
planning/behavior_path_planner_common/src/utils/drivable_area_expansion/static_drivable_area.cpp

Remove function `makeBoundLongitudinallyMonotonic` due to the following reasons:
- It is NOT necessary to make bound monotonic for any modules. (Even for `obstacle_avoidance_planner`)
- It is difficult to maintain the function when planner supports drivable expansion for various area (e.g. zebra, intersection, freespace...).
- It is too complex and unreadable to understand the process.
|    | in lane following  | in avoidance maneuver |
| ---- | ---- | ---- |
|  BEFORE  | ![Screenshot from 2024-02-13 10-35-13](https://github.com/autowarefoundation/autoware.universe/assets/44889564/aa09ccd9-1415-451c-aa14-4dfb2ffe9eab) | ![Screenshot from 2024-02-13 10-35-04](https://github.com/autowarefoundation/autoware.universe/assets/44889564/84503c44-c504-4e50-9c86-a45e42f08c16)  |
|  AFTER  | …

fix(static_drivable_area_expansion): remove process to make drivable bound longitudinally monotonic

---

planning/behavior_path_goal_planner_module/config/goal_planner.param.yaml
planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/goal_planner_module.hpp
planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/goal_planner_parameters.hpp
planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/util.hpp
planning/behavior_path_goal_planner_module/src/goal_planner_module.cpp
planning/behavior_path_goal_planner_module/src/manager.cpp
planning/behavior_path_goal_planner_module/src/util.cpp

https://github.com/autowarefoundation/autoware_launch/pull/867
https://tier4.atlassian.net/browse/RT1-4778
https://evaluation.tier4.jp/evaluation/reports/6d05a363-3ef6-536d-9f77-0cc9769c821b?project_id=prd_jt
This is an old video so at [00:09] safety check was not executed for another vehicle, but now it is fixed.
https://github.com/autowarefoundation/autoware.universe/assets/28677420/fdf31a26-d263-4388-9234-34ea798cf323
https://github.com/autowarefoundation/autoware.universe/assets/28677420/13e635d2-c513-4e55-a207-3e218fd9fb15
none
none …

feat(goal_planne): check objects within the area between ego edge and boudary of pull_over_lanes

---

map/map_loader/src/pointcloud_map_loader/pointcloud_map_loader_node.cpp

Part of:
- https://github.com/autowarefoundation/autoware.universe/issues/5539
Right now, even when we create a metadata with a single pcd, we receive "Create PCD metadata, as the pointcloud is a single file." warning from `pointcloud_map_loader`.
But it should throw the warning if there is no metadata but there is no metadata at all.
I've reordered the logic structure so:
In order:
1. if metadata exists -> use new method
2. if not, but only 1 pcd -> use exceptional method and warn
3. if not -> throw warning (no metadata)
cc. @ahmeddesokyebrahim 
Help appreciated. …

fix(map_loader): fix warnings with single point cloud map metadata

---

perception/tracking_object_merger/README.md
perception/tracking_object_merger/include/tracking_object_merger/utils/tracker_state.hpp
perception/tracking_object_merger/src/decorative_tracker_merger.cpp
perception/tracking_object_merger/src/utils/tracker_state.cpp

As reported in https://github.com/autowarefoundation/autoware.universe/issues/6373, tracker object merger fails to manage tracklets when input objects are empty.
This PR fixes that unintended behavior by
- Do not skip update when input objects are empty
- Add additional tracklet survival check before publishing it
https://github.com/autowarefoundation/autoware.universe/issues/6373
@brkay54 could you check this PR with your error case? …

fix(tracker_object_merger): add sanity check for tracker merger

---

control/pid_longitudinal_controller/package.xml
control/pid_longitudinal_controller/src/pid_longitudinal_controller.cpp

in getControlData(), path points of control_data.interpolated_traj are inserted/removed so the nearest/target index should be obtained later.
```
#12 autoware::motion::control::pid_longitudinal_controller::PidLongitudinalController::getControlData (this=0x7f3794097470, current_pose=...)
at /home/autoware/workspace/pilot-auto.xx1/src/autoware/universe/control/pid_longitudinal_controller/src/pid_longitudinal_controller.cpp:504
504         control_data.[interpolated_traj.points.at](http://interpolated_traj.points.at/)(control_data.target_idx).longitudinal_velocity_mps);
(gdb) p target_idx
No symbol "target_idx" in current context.
(gdb) p control_data.target_idx
$1 = 44
(gdb) p control_data.interpolated_traj.points.size()
$2 = 44
(gdb) p control_data.nearest_idx
$3 = 43
(gdb) p …
```

fix(pid_longitudinal_controller): fixed nearest/target index before/after insertion and removal of path points

---

planning/external_velocity_limit_selector/config/default_common.param.yaml
planning/motion_velocity_smoother/config/default_common.param.yaml
planning/motion_velocity_smoother/src/motion_velocity_smoother_node.cpp
planning/obstacle_cruise_planner/config/default_common.param.yaml
planning/obstacle_stop_planner/config/common.param.yaml
planning/planning_test_utils/config/test_common.param.yaml
planning/static_centerline_optimizer/config/common.param.yaml

The maximum velocity is currently defined in the motion_velocity_smoother, though it's a common parameter.
This PR moved the parameter to common.param.yaml
Unit test
psim
Nothing

feat(motion_velocity_smoother): use common max_vel

---

perception/image_projection_based_fusion/src/fusion_node.cpp

Fix a bug in https://github.com/autowarefoundation/autoware.universe/pull/6181
Tested with Autoware w/ following packages:
- pointpainting
- roi_cluster_fusion
- roi_detected_object_fusion
- roi_pointcloud_fusion
Bug fixed

fix(image_projection_based_fusion): fix bug

---

perception/radar_tracks_msgs_converter/config/radar_tracks_msgs_converter.param.yaml

add a missing parameter 'new_frame_id'
Tested on a TIER IV logging simulator environment.
Able to launch radar_tracks_msgs_converter.

fix(radar_tracks_msgs_converter): add a missing parameter 'new_frame_id'

---

.cspell-partial.json
perception/map_based_prediction/README.md
perception/map_based_prediction/include/map_based_prediction/map_based_prediction_node.hpp
perception/map_based_prediction/src/map_based_prediction_node.cpp

suppress spell check failure for map_based_prediction
- add routable as ignore word to .cspell-partial.json
- Sgnal -> Signal
- additon -> addition
I check spell check is succeess.

fix(map_based_prediction): suppress spell check failure

---

.cspell-partial.json

the words, `quantizer`, `imageio` and `mimsave` are added to `autoware-spell-check-dict` in folloing pull-request.
https://github.com/tier4/autoware-spell-check-dict/pull/656
https://github.com/tier4/autoware-spell-check-dict/pull/655
So, I delete these words from `.cspell-partial.json`
Check `spell-check-partial` is green …

chore(cspell): update .cspell-partial.json

---

planning/obstacle_stop_planner/include/obstacle_stop_planner/adaptive_cruise_control.hpp
planning/obstacle_stop_planner/src/adaptive_cruise_control.cpp

when `use_predicted_objects` is False,
1. the process goes on even if object_ptr is nullptr: https://github.com/autowarefoundation/autoware.universe/blob/c6868005de05b4e8dac5ca44d09836534317b91e/planning/obstacle_stop_planner/src/node.cpp#L298-L301
2. through
- searchObstacle: (https://github.com/autowarefoundation/autoware.universe/blob/c6868005de05b4e8dac5ca44d09836534317b91e/planning/obstacle_stop_planner/src/node.cpp#L361-L366)
- insertAdaptiveCruiseVelocity: (https://github.com/autowarefoundation/autoware.universe/blob/c6868005de05b4e8dac5ca44d09836534317b91e/planning/obstacle_stop_planner/src/node.cpp#L571-L575)
- estimatePointVelocityFromObject: (https://github.com/autowarefoundation/autoware.universe/blob/c6868005de05b4e8dac5ca44d09836534317b91e/planning/obstacle_stop_planner/src/a …

fix(obstacle_stop_planner): fix null object_ptr access when use_predicted_objects = False

---

localization/pose_instability_detector/config/pose_instability_detector.param.yaml
localization/pose_instability_detector/schema/pose_instability_detector.schema.json

Currently, `interval_sec` in `pose_instability_detector` is set to 1.0 seconds.
However, the localization_stability timeout in `system_error_monitor`, which aggregates this, is also set to 1.0 seconds.
https://github.com/autowarefoundation/autoware.universe/blob/b2cd2aac9ebd5bb3e8468c10ee2b008a6ef1101b/system/system_error_monitor/config/diagnostic_aggregator/localization.param.yaml#L33-L37
Therefore, if there is even a slight delay, it will become stale.
In thie PR, I have changed `interval_sec` of `pose_instability_detector` to 0.5 seconds so that it does not become stale immediately even if there is a delay.
There are two solutions: increase the `timeout` of `system_monitor` or decrease `interval_sec` of `pose_instability_detector`.
I chose to decrease the `interval_sec` of …

fix(pose_instability_detector): changed the interval_sec value of pose_instability_detector

---

perception/tracking_object_merger/src/utils/utils.cpp

fix spell check for tracking_object_merger

fix(tracking_object_merger): fix spell check

---

perception/radar_object_tracker/src/tracker/model/constant_turn_rate_motion_tracker.cpp

fix spell check for radar_object_tracker

fix(radar_object_tracker): fix spell check

---

planning/motion_velocity_smoother/src/smoother/smoother_base.cpp

see https://github.com/autowarefoundation/autoware.universe/issues/5964
After PR, the first point `front_wheel_angle_rad` is calculated:
```
header:
stamp:
sec: 1703741879
nanosec: 946795572
frame_id: map
points:
- time_from_start:
sec: 0
nanosec: 0
pose:
position:
x: 3743.6276524283326
y: 73751.62245752678
z: 0.0
orientation:
x: 0.0
y: 0.0
z: 0.7743217436642739
w: 0.6327920964177086
longitudinal_velocity_mps: 0.25
lateral_velocity_mps: 0.0
acceleration_mps2: 0.10000000149011612
heading_rate_rps: 0.0
front_wheel_angle_rad: -0.17300020158290863
rear_wheel_angle_rad: 0.0
```
`front_wheel_angle_rad` is mostly unused, so little to no effect?
The PR …

fix(motion_velocity_smoother): calc first point front_wheel_angle_rad

---

perception/bytetrack/README.md
perception/bytetrack/lib/include/data_type.h
perception/probabilistic_occupancy_grid_map/test/test_synchronized_grid_map_fusion_node.py
perception/tracking_object_merger/src/decorative_tracker_merger.cpp

fix(perception): fix typo

---

planning/behavior_path_avoidance_by_lane_change_module/src/scene.cpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/utils.hpp
planning/behavior_path_avoidance_module/src/scene.cpp
planning/behavior_path_avoidance_module/src/utils.cpp

There two bug in logic to limit avoidance shift length by traffic light signal.
Before this PR.
After this PR.
Before this PR.
https://github.com/autowarefoundation/autoware.universe/assets/44889564/d91e6974-3dc5-4fdf-989a-dd4dbf5037c7
After this PR.
https://github.com/autowarefoundation/autoware.universe/assets/44889564/11a35350-d3fc-42a5-9a7a-78547d3581a8
Nothing. …

fix(avoidance): limit drivable lane only when the ego in on original lane

---

perception/compare_map_segmentation/src/voxel_grid_map_loader.cpp

Focused function has intention to reduce height distance effect so that the function won't filter out ground pointcloud.
Problem in original code is that it will also reduce the horizontal error threshold since 3d euclidean distance is just reduced.
I changed inclusion decision logic from 3d euclidean distance to comparison with each axis: which will more easier to understand and tune.
Tested with X2 rosbag. …

feat(compare_map_segmentation): change height downsize logic

---

launch/tier4_control_launch/launch/control.launch.py

divide control_validator from control_container
https://tier4.atlassian.net/browse/RT1-4972
https://tier4.atlassian.net/browse/RT1-5341
https://tier4.atlassian.net/browse/RT1-5342
```
/control/control_container
1  /control/trajectory_follower/controller_node_exe
2  /control/external_cmd_selector
3  /control/external_cmd_converter
4  /control/control_validator
5  /control/trajectory_follower/lane_departure_checker_node
6  /control/shift_decider
7  /control/vehicle_cmd_gate
8  /control/operation_mode_transition_manager
9  /control/glog_component
```
```
/control/control_validator_container
1  /control/control_validator
2  /control/glog_component
/control/control_container
1  /control/trajectory_follower/controller_node_exe
2  /control/external_cmd_selector
3  /control/external_cmd_converter …
```

feat(tier4_control_launch): run control_validator out of main control container

---

planning/behavior_path_planner_common/src/utils/drivable_area_expansion/drivable_area_expansion.cpp

The `behavior_path_planner` may crash if some points in the map are too close to eachother or form a too sharp angle.
This PR prevents crashes by handling the exception that may occur when calculating curvatures of the path.
Psim
No crash on bad maps

fix(behavior_path_planner): catch exception when calculating curvature

---

planning/obstacle_stop_planner/include/obstacle_stop_planner/node.hpp
planning/obstacle_stop_planner/src/node.cpp

This PR closes following issues:
https://github.com/autowarefoundation/autoware.universe/issues/5449
https://github.com/autowarefoundation/autoware.universe/issues/6007
The purpose of this PR is fixing logical bug. 
At first for loop [here](https://github.com/autowarefoundation/autoware.universe/blob/65bb40985f8c9e488f30d467e13a3cfff9333f28/planning/obstacle_stop_planner/src/node.cpp#L603), it searches collision on trajectory by looking into predicted objects. If there is a collision object, it finds the nearest point of the object (by looking both intersected points and corner points [here](https://github.com/autowarefoundation/autoware.universe/blob/65bb40985f8c9e488f30d467e13a3cfff9333f28/planning/obstacle_stop_planner/src/node.cpp#L805-L830)), and it pushes predicted object, time, and …

fix(obstacle_stop_planner): change the nearest_collision_point calculation place

---

launch/tier4_perception_launch/launch/object_recognition/detection/detector/camera_lidar_detector.launch.xml
perception/image_projection_based_fusion/src/fusion_node.cpp

- To rename unclear namespace of debug topics published by `fusion.cpp` interface.
[TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT1-5357)
- Confirm by logging_simulator that debug topics namespace matching with node name
- Before:
`
/perception/object_recognition/detection/clustering/camera_lidar_fusion/image_projection_based_fusion/debug/roi0/timestamp_interval_ms
/perception/object_recognition/detection/clustering/image_projection_based_fusion/debug/roi0/timestamp_interval_ms
/perception/object_recognition/detection/image_projection_based_fusion/debug/roi0/timestamp_interval_ms
/perception/object_recognition/detection/pointpainting/image_projection_based_fusion/debug/roi0/timestamp_interval_ms
`
- After: 
`autoware@npc2201009-ubuntu22:~/autoware$ ros2 topic list | grep …

chore(image_projection_based_fusion): rename debug topics

---

planning/behavior_path_avoidance_module/config/avoidance.param.yaml
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/parameter_helper.hpp
planning/behavior_path_planner_common/include/behavior_path_planner_common/utils/path_safety_checker/path_safety_checker_parameters.hpp
planning/behavior_path_planner_common/src/utils/path_safety_checker/safety_check.cpp

:warning: Please approve following PR first.
https://github.com/autowarefoundation/autoware_launch/pull/865
Current `safety_checker` assumes that steering angle is fixed during braking and creates rectangle polygon to check safety based on each predicted poses. However, basically it is able to change steering angle anytime. Additionally, previous logic sometimes caused false positive and modules judged unsafe excessively because the detection polygon covered not only adjacent lane but also the area where the ego wouldn't go through.
In this PR, I added option to switch steering policy during breaking from `fixed` or `free`.
In this policy, the safety checker creates rectangle polygon based on each predicted poses. (original method)
In this policy, the safety checker creates polygon along …

feat(safety_check): add option to use polygon along path in safety check

---

planning/obstacle_stop_planner/package.xml

Add maintainer myself to package.xml file.

refactor(obstacle_stop_planner): update package.xml

---

planning/behavior_path_planner_common/src/utils/path_safety_checker/safety_check.cpp

the behavior is not changed.
just modify updateCollisionCheckDebugMap call timing

fix(goal_planner): fix updateCollisionCheckDebugMap timing in checkSafetyWithIntegralPredictedPolygon

---

planning/behavior_path_lane_change_module/src/interface.cpp
planning/behavior_path_lane_change_module/src/manager.cpp

Currently dynamic reconfigure is not working in lane change module despite it was supported.
So this PR aims to fix this.
Also, some new parameters is added to the reconfigurable list.
None
1. Run lane change module in psim.
2. Add lane change debug marker
3. Try run the following command
```
ros2 param set /planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner lane_change.publish_debug_marker false
```
https://github.com/autowarefoundation/autoware.universe/assets/93502286/8e6d776b-1575-43e0-b8bb-e87e9fa3cf80
You can also use `rqt_reconfigure`
None
None
None …

fix(lane_change): fix dynamic reconfigure and add parameters

---

launch/tier4_control_launch/launch/control.launch.py

fixed the glog_component duplication
https://evaluation.tier4.jp/evaluation/reports/f84f38ac-829c-514c-82d9-ffce7155efd7?project_id=prd_jt

chore(tier4_control_launch): fix control validator name duplication

---

sensing/pointcloud_preprocessor/src/blockage_diag/blockage_diag_nodelet.cpp

- To fix a bug of output blockage angle range
[TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT1-5392)
- Confirmed by logging_simulator and rqt_monitor_robot the reasonable output `blockage_angle_range_deg`
| --- | ---|
| ![image](https://github.com/autowarefoundation/autoware.universe/assets/94814556/9c4a88dd-63b0-48cd-a580-a89b1e848d8c) |![image](https://github.com/autowarefoundation/autoware.universe/assets/94814556/4c39bd8e-c2c4-4404-ba67-31ad769a0fbb)| …

fix(blockage_diag): output blockage angle range bug fix

---

perception/traffic_light_multi_camera_fusion/src/node.cpp

The purpose of this PR is to avoid mistrial resulted from low-confidence misdetection.
Before, the multi camera fusion is based only on the size and truncation state of the rois. As a consequence, if the misdetected roi is not truncated and has the biggest area among the group, the fusion result could be misled to green as below.
Trusting the results with the highest confidence instead of area could avoid such problem. And it also seems reliable in other situations as far as we observed.
left: detection result
right: fusion result …

feat(traffic_light_multi_camera_fusion): take confidence into consideration

---

planning/mission_planner/package.xml
planning/mission_planner/src/lanelet2_plugins/default_planner.cpp
planning/mission_planner/src/lanelet2_plugins/default_planner.hpp
planning/mission_planner/src/lanelet2_plugins/utility_functions.cpp
planning/mission_planner/src/lanelet2_plugins/utility_functions.hpp

- added doxygen comments to functions
- removed unused functions / replaced with existing utility functions
- for check_goal_footprint, use boost::within instead
https://evaluation.tier4.jp/evaluation/reports/71566d0a-8f2d-556b-95b0-4ab69d7fd4d4?project_id=prd_jt
none
none

refactor(mission_planner): add comment functions/remove unused stuff/add comment

---

perception/lidar_apollo_instance_segmentation/README.md
perception/lidar_apollo_instance_segmentation/launch/lidar_apollo_instance_segmentation.launch.xml
perception/lidar_apollo_instance_segmentation/src/detector.cpp

add build_only option for pre task
launch build_only:=true and false
```
$ ros2 launch lidar_apollo_instance_segmentation lidar_apollo_instance_segmentation.launch.xml model_name:=apollo model_path:=/home/autoware/autoware_data/lidar_apollo_instance_segmentation model_param_path:=$(ros2 pkg prefix lidar_apollo_instance_segmentation --share)/config/apollo.param.yaml build_only:=true
[INFO] [launch]: All log files can be found below /home/kosuke55/.ros/log/2024-02-20-01-55-20-283389-DPC2103005-2590669
[INFO] [lidar_apollo_instance_segmentation_node-1]: process started with pid [2590672]
[lidar_apollo_instance_segmentation_node-1] [I] [TRT] [MemUsageChange] Init CUDA: CPU +564, GPU +0, now: CPU 587, GPU 2980 (MiB) …
```

feat(lidar_apollo_instance_segmentation): add build_only option

---

perception/traffic_light_arbiter/CMakeLists.txt
perception/traffic_light_arbiter/README.md
perception/traffic_light_arbiter/config/traffic_light_arbiter.param.yaml
perception/traffic_light_arbiter/include/traffic_light_arbiter/signal_match_validator.hpp
perception/traffic_light_arbiter/include/traffic_light_arbiter/traffic_light_arbiter.hpp
perception/traffic_light_arbiter/src/signal_match_validator.cpp
perception/traffic_light_arbiter/src/traffic_light_arbiter.cpp

I added the signal match validator, which validate the match between perception signals and external signals and publish the received color only when they are identical.
This feature aims to enhance safety when both perception and external sources are available. It can be enabled by setting enable_signal_matching to true, though it is set to false by default.
- [TIER IV INTERNAL JIRA LINK](https://tier4.atlassian.net/browse/RT0-29986)
- https://github.com/autowarefoundation/autoware_launch/pull/879
- PR for launch
I conducted tests using the rosbag simulator. Please note that the Traffic Light Monitor Panel was specifically created for this testing and has not yet been merged into autoware.universe.
https://github.com/autowarefoundation/autoware.universe/assets/11865769/ea0faac2-3685-4084- …

feat(traffic_light_arbiter): add signal match validator

---

perception/tracking_object_merger/src/utils/utils.cpp

Related previous work (PR) : https://github.com/autowarefoundation/autoware.universe/pull/5853
The multi-object tracker (mainly from lidar, blue box) has opposite direction and when the radar object is also used to obtain velocity, the merger trusts the orientation of the main object (lidar object). As result, the merged object (yellow box) has the reversed direction.
https://github.com/autowarefoundation/autoware.universe/assets/42434141/1a8af674-8d82-4a6f-a071-e7b5a6006d71
Previous
Current tracked object merger treats velocity as scalar value, and determine its direction based on some logic which causes this issue.
Fixed
The velocity merger converts measured velocity vector to target object coordinate system. 
[TIER IV INTERNAL](https://tier4.atlassian.net/browse/RT1-5257)
Tested on …

fix(tracking_object_merger): merge velocity base on target object coordinate system

---

planning/mission_planner/src/lanelet2_plugins/default_planner.cpp

related PR: https://github.com/autowarefoundation/autoware.universe/pull/6447
fix unexpected marker color.
Psim
Nothing.

fix(mission_planner): fix marker color

---

simulator/simple_planning_simulator/param/simple_planning_simulator_default.param.yaml

Add the parameter used to simulate slopes with the `simple_planning_simulator`.

feat(simple_planning_simulator): add enable_road_slope_simulation param

---

perception/image_projection_based_fusion/config/pointpainting.param.yaml

Score_threshold parameter is mistakenly modified by https://github.com/autowarefoundation/autoware.universe/commit/cc0b1081a74a265a3dac05d5830610242aa0ecd3, so I fixed it.
[TIER IV INTERNAL LINK](https://star4.slack.com/archives/C03S84LDJGG/p1708403287430539?thread_ts=1708400772.055019&cid=C03S84LDJGG)
I did not run autoware with this PR …

fix(pointpainting): recovery default parameter

---

planning/behavior_path_lane_change_module/README.md
planning/behavior_path_lane_change_module/config/lane_change.param.yaml
planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/scene.hpp
planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/utils/base_class.hpp
planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/utils/data_structs.hpp
planning/behavior_path_lane_change_module/src/interface.cpp
planning/behavior_path_lane_change_module/src/manager.cpp
planning/behavior_path_lane_change_module/src/scene.cpp

Adding hysteresis to lane change cancel.
Previously, once lane change path is approved, if it is unsafe, the module will cancel the path immediately.
If there are chances that the approval chatters due to the path being safe and unsafe often.
This might be caused by the dismal positional differences between ego and target objects at every time instance.
With this new feature, the path will only be cancelled if the number of unsafe count exceed `unsafe_hysteresis_threshold`.
https://github.com/autowarefoundation/autoware.universe/assets/93502286/006c11fc-fcf6-41ef-a829-6042e546a453
This launcher is needed: https://github.com/autowarefoundation/autoware_launch/pull/844
TBA
I made this on top of https://github.com/autowarefoundation/autoware.universe/pull/6276, do it needs to be merged …

feat(lane_change): cancel hysteresis

---

localization/pose_estimator_arbiter/README.md

I have corrected the typos in the table in README.
Any test is not applicable.
This PR does not affect the behavior.

docs(pose_estimator_arbiter): fix pose initializer parameter table

---

common/autoware_auto_perception_rviz_plugin/include/autoware_auto_perception_rviz_plugin/object_detection/object_polygon_detail.hpp
common/autoware_auto_perception_rviz_plugin/src/object_detection/object_polygon_detail.cpp
common/autoware_auto_perception_rviz_plugin/src/object_detection/predicted_objects_display.cpp

Current bounding box orientation marker (triangle on the front side) is only visible when the object's `orientation_availability` is `AVAILABLE`.
In the tracker development process, there was necessity to know object orientation even the `orientation_availability` is `SIGN_UNKNOWN`.
`orientation_availability==SIGN_UNKNOWN`
`orientation_availability==AVAILABLE` & `orientation_availability==SIGN_UNKNOWN`
* Minor changes
* marker lifetime is adjusted to have same, so that there is no residual
* the marker lifetime is shorten to 0.15 second
* (bugfix) yaw rate marker of predicted object was remained inappropriately, now it is fixed. 
* twist covariance marker color is adjusted
The visualization in rviz2 was confirmed. …

feat(autoware_auto_perception_rviz_plugin): indicate object orientation, parameter adjustments, bugfix

---

planning/behavior_path_avoidance_by_lane_change_module/include/behavior_path_avoidance_by_lane_change_module/scene.hpp
planning/behavior_path_avoidance_by_lane_change_module/src/interface.cpp
planning/behavior_path_avoidance_by_lane_change_module/src/scene.cpp
planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/utils/debug_structs.hpp
planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/utils/markers.hpp
planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/utils/utils.hpp
planning/behavior_path_lane_change_module/src/scene.cpp
planning/behavior_path_lane_change_module/src/utils/markers.cpp
planning/behavior_path_lane_change_module/src/utils/utils.cpp

Previous avoidance by lane change execution condition uses maximum_avoidance_distance. This cause AbLC to be difficult to be execution.
Also there is no way to know visually about the execution check area.
This PR aims to solve two things
1. Use minimum avoidance distance and adopted freenet convention, `length` for longitudinal distance. `min_avoidance_length` is now used.
2. Added debug marker to visualize execution request condition area.
3. Slight refactoring so that `isExecutionRequested` function is not too long. …

fix(avoidance_by_lane_change): loosen execution condition

---

planning/behavior_velocity_planner/schema/behavior_velocity_planner.schema.json
vehicle/raw_vehicle_cmd_converter/schema/raw_vehicle_cmd_converter.schema.json

Updated the obsolete schema json files in planning/vehicle
`json-schema-check / json-schema-check (pull_request)`  has no errors for planning/vehicle.
Nothing

fix: fix schema json in planning/vehicle

---

planning/behavior_velocity_planner/src/node.cpp
planning/behavior_velocity_planner_common/include/behavior_velocity_planner_common/planner_data.hpp
planning/behavior_velocity_traffic_light_module/src/scene.cpp

In the current implementation, the decision to proceed is made individually for each traffic signal. As a result, the ego vehicle sometimes moves forward even when a signal message is not received.
To address this issue, I introduced a variable that tracks whether a signal message has been received. Now, if a signal message is received but a subsequent traffic signal message is not, the ego vehicle will stop.
https://github.com/autowarefoundation/autoware.universe/assets/11865769/a223f88b-35ad-41e5-813c-0630cd4f2741
[TIER IV INTERNAL LINK](https://star4.slack.com/archives/C03QW0GU6P7/p1707982960796549)
I conducted tests in simple planning simulator.
In the following video, if the traffic signal of 1008 has once received, the stop point is inserted to the traffic signal of 1002 because the …

feat(behavior_velocity_traffic_light): ensure stopping if a signal, once received, is not received again

---

.github/workflows/build-and-test.yaml

This workflow doesn't do anything because it is being run under `container:` field.
- https://github.com/autowarefoundation/autoware.universe/blob/38b58458fe22377e6dce727b90a76f46a709ddc2/.github/workflows/build-and-test.yaml#L13
- https://github.com/autowarefoundation/autoware.universe/actions/runs/7997414878/job/21841840903#step:4:1
It tries to clean up clutter in the host machine but cannot do so because it is being run in the container.
For it to work, we would need to utilize a docker-bake action to run this.
Till then, I'm removing this.
After all …

ci(build-and-test): remove free-disk-space

---

perception/compare_map_segmentation/schema/distance_based_compare_map_filter.schema.json
perception/compare_map_segmentation/schema/voxel_based_approximate_compare_map_filter.schema.json
perception/compare_map_segmentation/schema/voxel_based_compare_map_filter.schema.json
perception/compare_map_segmentation/schema/voxel_distance_based_compare_map_filter.schema.json
planning/behavior_velocity_planner/schema/behavior_velocity_planner.schema.json

Part of:
- https://github.com/autowarefoundation/autoware.universe/issues/6473

fix(json-schema-check): update schemas

---

planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/start_planner_module.hpp
planning/behavior_path_start_planner_module/src/start_planner_module.cpp

Start the timeout count for temporal stop for blinker preparation when AW is engaged and approved.
https://github.com/autowarefoundation/autoware.universe/pull/6412
if the prepare time is 3.0, even if the module is auto mode, waits for 3sec before start
https://github.com/autowarefoundation/autoware.universe/assets/28677420/5d8ee65a-154d-4435-b664-d47ca6138da6
By default the parameter is 0 and has no effect.
https://github.com/autowarefoundation/autoware.universe/assets/28677420/07b43371-966b-4cc2-bc49-8173e406fd3b
none
none …

fix(start_planner): start prepare blinker when autonomous mode is available

---

perception/probabilistic_occupancy_grid_map/src/pointcloud_based_occupancy_grid_map/pointcloud_based_occupancy_grid_map_node.cpp

As reported in https://github.com/orgs/autowarefoundation/discussions/4202#discussioncomment-8564823, we found probabilistic occupancy grid map is published not on the baes_link but on the raw pointcloud frame.
https://github.com/orgs/autowarefoundation/discussions/4202#discussioncomment-8564823
@tseco15 Could you check this PR in your environment and check if the problem is fixed? …

fix(probabilistic_occupancy_grid_map): fix robot_pose to refer base_link_frame

---

planning/route_handler/include/route_handler/route_handler.hpp
planning/route_handler/src/route_handler.cpp

add preferred lane getter function.
```c++
lanelet::ConstLanelets RouteHandler::getPreferredLanelets() const
{
return preferred_lanelets_;
}
```
Nothing.
Nothing.

feat(route_handler): add preferred lane getter function

---

planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/data_structs.hpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/scene.hpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/utils.hpp
planning/behavior_path_avoidance_module/src/scene.cpp
planning/behavior_path_avoidance_module/src/utils.cpp
planning/behavior_path_planner_common/include/behavior_path_planner_common/utils/path_shifter/path_shifter.hpp

Previously, avoidance module continued to turn on blinker until the ego returned original path completely. Sometimes, the module keeped turn signal even when the ego stopped in front of intersection due to red traffic light. However, the signal maybe causes misunderstanding that the ego is going to turn left or right at the intersection.
In this PR, I fixed turn signal calculation logic in order to disable turn signal if the ego stopped in original lane.
https://github.com/autowarefoundation/autoware.universe/assets/44889564/97ca3497-0107-40a0-bdd4-a4c1644140bc
Nothing.
After all …

fix(avoidance): turn off blinker when the ego return original lane

---

planning/behavior_path_start_planner_module/src/manager.cpp

Add support for rqt reconfigure for the start planner
Tests in PSim: 
https://github.com/autowarefoundation/autoware.universe/assets/25967964/75984661-2190-44c3-8fa6-75214a86d00c
In the above example, I use a custom script to place the ego vehicle in the same position for each test, at the beggining, both geometric pull out and shift pull out are enabled, then I disable both and call my script to place the start and goal in the same pose, this time, there is no path since both pull out methods are disabled (params updated successfully) , then I enable geometric_pull out and set the ego poses again and a path is generated using geom pull out
Note that the start and goal pose must be placed again after updating parameters.  …

feat(behavior_path_start_planner_module): add support for rqt reconfig

---

localization/ndt_scan_matcher/include/ndt_scan_matcher/map_update_module.hpp
localization/ndt_scan_matcher/src/map_update_module.cpp

In the current implementation, the process continues even if there is no change in update_ndt, then the pointer is switched, and the original ndt object is destroyed.
I'm not sure which thread calls the NDT destructor when it is destroyed, but it has a negative impact on the overall operation of NDT.
* Add a bool return indicating whether ndt has been updated in update_ndt.
* Use this return value to switch the behavior in update_map.
* single pcd
* multi pcd
I confirmed that it works properly with AWSIM as well. …

fix(ndt_scan_matcher): add a bool return indicating whether ndt has been updated in update_ndt

---

planning/behavior_path_avoidance_module/config/avoidance.param.yaml
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/data_structs.hpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/helper.hpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/parameter_helper.hpp
planning/behavior_path_avoidance_module/src/scene.cpp

Related ticket: https://tier4.atlassian.net/browse/RT1-5327
Related PR: https://github.com/autowarefoundation/autoware_launch/pull/891
Previously, avoidance module created return shift path and approved it as soon as possible. However, I think it is better to wait return shift approval because sometimes the vehicle can't detect objcets behind avoidance target. Othrewise, there is a possibility that the vehicle can't avoid behind object in following situaiton. (avoidance module creats return shift path even when there is anothre object behind current avoidance target.)
In this PR, I added a param to delay return shift approval.
```yaml
ratio_for_return_shift_approval: 0.5          # [-]
```
If we set this param to 0.3, the module creates return shift path after reaching 70% of avoidance …

feat(avoidance): wait next shift approval until the ego reaches shift length threshold

---

sensing/pointcloud_preprocessor/docs/ring-outlier-filter.md
sensing/pointcloud_preprocessor/include/pointcloud_preprocessor/outlier_filter/ring_outlier_filter_nodelet.hpp
sensing/pointcloud_preprocessor/package.xml
sensing/pointcloud_preprocessor/src/outlier_filter/ring_outlier_filter_nodelet.cpp

Publish excluded points in ring_outlier_filter for visualization.
This feature is disabled by default. 
The white points have been excluded by the ring_outlier_filter, whereas the colorful points represent the pointcloud after the ring_outlier_filter.
running [logging_simulator](https://autowarefoundation.github.io/autoware-documentation/main/contributing/coding-guidelines/ros-nodes/launch-files/#autoware_launch) with enabling sensing moudle. 
1. Visualizing filtered/excluded pointcloud in rviz by applying following change 
<details>
<summary>necessary change for autoware.rviz</summary>
```
- Alpha: 1
Autocompute Intensity Bounds: true
Autocompute Value Bounds:
Max Value: 5
Min Value: -10
Value: false
Axis: Z
Channel Name: intensity
Class: rviz_default_plugins/PointCloud2
Color: 255; 255; …
```

feat(pointcloud_preprocessor): publish excluded points in ring_outlier_filter for debug purpose

---

common/tier4_autoware_utils/include/tier4_autoware_utils/geometry/boost_geometry.hpp
control/lane_departure_checker/include/lane_departure_checker/lane_departure_checker.hpp
control/lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker.cpp
planning/behavior_path_planner_common/include/behavior_path_planner_common/utils/parking_departure/geometric_parallel_parking.hpp
planning/behavior_path_planner_common/package.xml
planning/behavior_path_planner_common/src/utils/parking_departure/geometric_parallel_parking.cpp
planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/geometric_pull_out.hpp
planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/shift_pull_out.hpp
planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/start_planner_module.hpp
planning/behavior_path_start_planner_module/src/geometric_pull_out.cpp
planning/behavior_path_start_planner_module/src/shift_pull_out.cpp
planning/behavior_path_start_planner_module/src/start_planner_module.cpp

In this PR, a new departure check set of functions have been added to lane_departure_checker that:
1. Creates an ego vehicle footprint convex hull.
2. Checks which lanelets are touched by the footprint hull using the MapLayer
3. Then Checks if each individual footprint is fully within the lanelets or not
I have implemented this check for shift pull out and geometric pull out to improve and be able to consider all the necessary lanelets to do a proper out of lane check. This solves the issue in which the ego vehicle cannot start with a shift pull out on overlapped lanes:
Before, the shift pull out planner cannot generate a route when the ego overlaps more than one lane (other planners are disabled): 
After the changes on this PR:
Tests performed: Psim and Scenario tests: [TIER IV INTERNAL …

feat(lane_departure_checker,start_planner): add check for path within lanes for bvspm

---

launch/tier4_planning_launch/launch/planning.launch.xml
launch/tier4_planning_launch/launch/scenario_planning/lane_driving.launch.xml
launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.xml
launch/tier4_planning_launch/launch/scenario_planning/scenario_planning.launch.xml
planning/behavior_velocity_planner/src/node.cpp
planning/behavior_velocity_planner/test/src/test_node_interface.cpp
planning/behavior_velocity_planner_common/include/behavior_velocity_planner_common/planner_data.hpp
planning/behavior_velocity_traffic_light_module/src/scene.cpp

This PR extends the feature to deal with the traffic signal depending on whether it's a simulation or not, implemented in the following PR.
https://github.com/autowarefoundation/autoware.universe/pull/6468
Regarding the Autoware's planning behavior for the traffic signal, we have the following three requirements.
- By default, the traffic signal topic is **NOT** published.
- The ego does not want to stop at the traffic signal.
- The traffic signal topic is always published.
- The ego does **NOT** want to stop at the traffic signal where the color is not contained in the topic.
- real environment
- The traffic signal topic is always published.
- The ego wants to stop at the traffic signal where the color is not contained in the topic for safety in …

feat(traffic_light): depend on is_simulation for scenario simulator

---

perception/detected_object_validation/package.xml
perception/elevation_map_loader/package.xml
perception/traffic_light_fine_detector/package.xml
perception/traffic_light_map_based_detector/package.xml

I want to update maintainers following [TIER IV INTERNAL LINK](https://tier4.atlassian.net/wiki/spaces/CT/pages/2527037972/SP) 

chore: update maintainers

---

planning/mission_planner/src/mission_planner/mission_planner.cpp
planning/mission_planner/src/mission_planner/mission_planner.hpp

when the rerouting happened between main/mrm, the safety check logic tries to find the common interval between the two. the previous logic worked only when the common interval beginning matches  the beginning of either route.
So if the common interval is in the middle of each route, it fails to find "100 200 300" as shown in below.
```
original: 10 11 100 200 300 1000 
route  :  1  2  100 200 300 1000
```
In this PR the beginning of common interval is obtained in naive way.
https://tier4.atlassian.net/browse/RT1-5332
https://github.com/autowarefoundation/autoware.universe/assets/28677420/6f637d30-a730-4c21-9023-8533f5c86789
none
none
The PR author …

fix(mission_planner): find the first common interval naively for main/mrm reroute check

---

planning/behavior_path_start_planner_module/README.md
planning/behavior_path_start_planner_module/config/start_planner.param.yaml
planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/data_structs.hpp
planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/start_planner_module.hpp
planning/behavior_path_start_planner_module/src/manager.cpp
planning/behavior_path_start_planner_module/src/shift_pull_out.cpp
planning/behavior_path_start_planner_module/src/start_planner_module.cpp

Add a parameter: `allow_check_shift_path_lane_departure_override` to disable lane departure check IF the ego vehicle's original pose happens to not be fully inside a lanelet(s).
Note, some refactoring is also done. 
NOTE: requires launch changes-> https://github.com/autowarefoundation/autoware_launch/pull/893
PSim tests. Example video: 
https://github.com/autowarefoundation/autoware.universe/assets/25967964/e9cf194e-7681-4ef2-94a2-ef0c8a7323f8
the above video shows the inclusion of the requested feature, First, I show how the start planner works if lane departure check is disabled, 2nd I enable lane departure check but also the new option to override lane departure if partly outside of lane when starting, finally I turn off the override option and the lane departure check is executed (and …

feat(start_planner): allow lane departure check override

---

planning/behavior_velocity_no_stopping_area_module/src/scene_no_stopping_area.cpp

In a current path planning and in a no stopping area module, there is a margin after a no stopping area so that the ego vehicle can’t stop right behind the no stopping areas. 
For example, if the distance from the goal position to the end of the no stopping area is shorter than 2.6 m, in the case of the medium size car with the rear overhang about 0.85 m, the ego vehicle can not enter into the no stopping area, which is problematic. 
The details of the problem are described in the JIRA  Ticket : https://tier4.atlassian.net/browse/RT1-5039
To resolve this problem, I added the following 2 changes to the source file of no stopping area module.
1. Deletion of the 3 lines ( L327-L329 of the old file ).
This sets the index value from which to start the search of `ego_area_end_idx` to be …

fix(no_stopping_area): fix stopping in front of a no stopping area in parking on the shoulder

---

.github/workflows/json-schema-check.yaml

The `json-schema-check` workflow is required for merging pull-request now.
But `json-schema-check` fires only when you edited parameter files or schema files.
So, `json-schema-check` blocks merging pull-requests without parameter files or schema files changes.
This is a naive solution, and there may be a more elegant method, but I will suggest it for now.
Related: #6473  …

fix(ci): remove json-schema-check filter

---

planning/behavior_path_avoidance_module/config/avoidance.param.yaml
planning/behavior_path_planner/config/behavior_path_planner.param.yaml

refactor(behavior_path_planner): remove unused drivable area parameters

---

.github/workflows/json-schema-check.yaml
localization/ekf_localizer/schema/ekf_localizer.schema.json

Continuation from:
- https://github.com/autowarefoundation/autoware.universe/pull/6524
With this restructuring of the actions,
- `pre-check` will check if relevant files are changed
- if yes, `json-schema-check` will do its thing
- if not, `no-relevant-changes` will return successful
Tests are below:
- https://github.com/autowarefoundation/autoware.universe/pull/6530#issuecomment-1972950391 …

ci(json-schema-check): run only if relevant files are changed

---

perception/probabilistic_occupancy_grid_map/src/pointcloud_based_occupancy_grid_map/pointcloud_based_occupancy_grid_map_node.cpp
sensing/pointcloud_preprocessor/include/pointcloud_preprocessor/concatenate_data/concatenate_and_time_sync_nodelet.hpp
sensing/pointcloud_preprocessor/include/pointcloud_preprocessor/time_synchronizer/time_synchronizer_nodelet.hpp
sensing/pointcloud_preprocessor/src/concatenate_data/concatenate_and_time_sync_nodelet.cpp
sensing/pointcloud_preprocessor/src/concatenate_data/concatenate_pointclouds.cpp
sensing/pointcloud_preprocessor/src/time_synchronizer/time_synchronizer_nodelet.cpp

This PR enables to `concatenate_node` or `time_sync_node` to publish any name.
This feature is going to used in interface change: 
https://github.com/orgs/autowarefoundation/discussions/4158
- The topic rename function tries to rename input topic by replacing last part of the topic name
-  example: `/sensing/lidar/sample/input_pointcloud` to `/sensing/lidar/sample/<postfix>`
-  postfix is controlled by rosparam `synchronized_pointcloud_postfix`, we set `pointcloud` as default as for [the above discussion](https://github.com/orgs/autowarefoundation/discussions/4158)
- If the input topic end with `pointcloud`, the topic name replace function returns the same name, so we replace synchronized pointcloud name with `pointcloud_synchronized` …

feat(pointcloud_preprocessor): enable to change synchronized pointcloud topic name

---

perception/lidar_apollo_segmentation_tvm/data/models/baidu_cnn/inference_engine_tvm_config.hpp
perception/lidar_centerpoint_tvm/data/models/centerpoint_backbone/inference_engine_tvm_config.hpp
perception/lidar_centerpoint_tvm/data/models/centerpoint_backbone/preprocessing_inference_engine_tvm_config.hpp
perception/lidar_centerpoint_tvm/data/models/centerpoint_encoder/inference_engine_tvm_config.hpp
perception/multi_object_tracker/src/tracker/model/pedestrian_tracker.cpp
perception/probabilistic_occupancy_grid_map/include/probabilistic_occupancy_grid_map/fusion/synchronized_grid_map_fusion_node.hpp
perception/probabilistic_occupancy_grid_map/include/probabilistic_occupancy_grid_map/updater/occupancy_grid_map_log_odds_bayes_filter_updater.hpp
perception/probabilistic_occupancy_grid_map/src/fusion/synchronized_grid_map_fusion_node.cpp
perception/probabilistic_occupancy_grid_map/src/updater/occupancy_grid_map_log_odds_bayes_filter_updater.cpp

I fix spell check failures to ignore LOBF, bcnn, CTRV and DLCPU.
I followed ↓.
https://github.com/autowarefoundation/autoware.universe/blob/6b1a459a138bb04f1fcf5f8c9c160718032ce65d/common/tvm_utility/data/models/abs_model_aarch64/inference_engine_tvm_config.hpp#L40

fix: suppress spell check failure to ignore LOBF, bcnn, CTRV and DLCPU

---

planning/behavior_path_start_planner_module/README.md
planning/behavior_path_start_planner_module/config/start_planner.param.yaml
planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/data_structs.hpp
planning/behavior_path_start_planner_module/src/manager.cpp
planning/behavior_path_start_planner_module/src/start_planner_module.cpp

In the original implementation, when generating path, a constant distance margin was attempted to be maintained regardless of the object's class. This approach led to a problem where path could not be generated due to the occurrence of objects of an unknown type, even when there were actually no objects exist.
Ideally, we expect that objects of unknown type will not be detected when no objects exist. However, as a short-term measure, we will enable path generation by ignoring specific classes through parameter adjustment.
Please be cautious when setting this parameter to false, as objects of an unknown class might be recognized, and there could actually be objects present.
In the PR description, I'd like to explain the path generation based on the following settings:
When the …

feat(start_planner): add object_types_to_check_for_path_generation

---

launch/tier4_perception_launch/launch/obstacle_segmentation/ground_segmentation/ground_segmentation.launch.py
launch/tier4_perception_launch/launch/perception.launch.xml
perception/probabilistic_occupancy_grid_map/synchronized_grid_map_fusion.md

- Rename to more reasonable topic name of ground_segmentation pipeline.
[TIER IV INTERNAL LINK](https://star4.slack.com/archives/C03S84LDJGG/p1709522148776059?thread_ts=1709520926.605739&cid=C03S84LDJGG)
-  I confirmed by `loggging-simulator`:
- The node and topic name have been updated:  
- Ground_segmentation worked and output result as before. 
[pull request …

chore(ground_segmentation): rename topic and node

---

planning/behavior_path_lane_change_module/src/interface.cpp

Fix approval chatter when lane change is running while no valid path is available
[Before](https://github.com/autowarefoundation/autoware.universe/assets/93502286/85c02277-3825-4f80-9677-53a1f2c570b1)
[After](https://github.com/autowarefoundation/autoware.universe/assets/93502286/27223870-64e8-4f48-a08e-b5653a1a9d92) …

fix(lane_change): approval chatters when no valid paths

---

planning/behavior_velocity_intersection_module/src/scene_intersection_stuck.cpp

add size check
https://github.com/autowarefoundation/autoware_common/pull/240
This issue is possible if the map contained a lanelet linestring with no points.
none
none

fix(intersection): fix possible invalid access

---

common/tier4_state_rviz_plugin/src/autoware_state_panel.cpp

This PR adds pull over indicator to AutowareStatePanel.
Since the pull over has already been added to [MrmState.msg](https://github.com/autowarefoundation/autoware_adapi_msgs/pull/43/files), it will not cause a build error.
[Screencast from 2024年03月04日 17時23分27秒.webm](https://github.com/autowarefoundation/autoware.universe/assets/70682030/b62cd858-2522-4df0-ba2b-a2f31874137d)
[pull …

feat: add pull over to autoware_state_panel of rviz

---

control/mpc_lateral_controller/src/mpc_lateral_controller.cpp

Fix the reported [issue](https://github.com/autowarefoundation/autoware.universe/issues/6421)
reset `m_ctrl_cmd_prev` during manual mode.
problem is described in the issue.
1. run logging_simulator with enabling only control module with following command
```
ros2 launch autoware_launch logging_simulator.launch.xml map_path:=/path_to_your_map/ vehicle_model:=your_vehicle sensor_model:=aip_xx1 perception:=false sensing:=false control:=true planning:=false localozation:=false
```
2. play rosbag 
To remap topics related to the `trajectory_follower_node` stored in a rosbag to the control topics used by autoware, you can use the following option command
```
--remap /control/trajectory_follower/control_cmd:=/exclude/control_cmd /control/trajectory_follower/controller_node_exe/lateral/debug/proces …
```

fix(mpc_lateral_controller): reset ctrl_cmd_prev during manual mode

---

launch/tier4_perception_launch/launch/obstacle_segmentation/ground_segmentation/ground_segmentation.launch.py

- Change to use `vehicle_height` for `max_z` parameter of `/perception/obstacle_segmentation/xx_crop_box_filter' nodes
- Need merge together with https://github.com/autowarefoundation/autoware_launch/pull/906
[TIER IV INTERNAL LINK](https://star4.slack.com/archives/C03S84LDJGG/p1709688432469209?thread_ts=1709652542.797929&cid=C03S84LDJGG)
- Confirmed by `logging_simulator` that the correct `max_z` and `min_z` were parsed to `obstacle_segmentation/crop_box_filter' node as desired. …

chore(ground_segmentation_launch): change max_z of cropbox filter to vehicle_height

---

.github/workflows/build-and-test-arm64.yaml
.github/workflows/build-and-test-differential-arm64.yaml
.github/workflows/build-and-test-differential.yaml
.github/workflows/build-and-test.yaml

Part of:
- https://github.com/autowarefoundation/autoware/issues/3999
This PR:
- Renames the jobs:
- `build-and-test-differential-self-hosted` **->** `build-and-test-differential-arm64`
- `build-and-test-self-hosted` **->** `build-and-test-arm64`
- Changes the runners for `build-and-test-differential` and `build-and-test`:
- **from:** `[self-hosted, linux, X64]`
- **to:** `ubuntu-latest` # github public runners
- Changes the target images (for all 4 workflows):
- **from:** `autoware-universe:humble-latest`
- **to:** `autoware-openadk:latest-prebuilt`
- Updates the disk space displaying mini jobs
- Updates the tag to `type:arm64` (this was forgotten when we overhauled the repository labels) …

ci: update build-and-test and -differential jobs

---

planning/behavior_path_avoidance_by_lane_change_module/config/avoidance_by_lane_change.param.yaml
planning/behavior_path_avoidance_by_lane_change_module/src/manager.cpp
planning/behavior_path_avoidance_by_lane_change_module/src/scene.cpp
planning/behavior_path_avoidance_module/config/avoidance.param.yaml
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/data_structs.hpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/parameter_helper.hpp
planning/behavior_path_avoidance_module/src/debug.cpp
planning/behavior_path_avoidance_module/src/manager.cpp
planning/behavior_path_avoidance_module/src/scene.cpp
planning/behavior_path_avoidance_module/src/shift_line_generator.cpp
planning/behavior_path_avoidance_module/src/utils.cpp

The module creates avoidance path not only for PARKED vehilce but also NON-PARKED vehicle. And, it used common lateral margin for both type of vehicle. But I think the module should be able to use different lateral margin for each types based on the assumption that the door might open and the driver might get out the car if it's a PARKED vehilce. In that case, we should set larger lateral margin for PARKED vehicle than the param for NON-PARKED vehicle.
In this PR, I rebuild lateral params and make it possible to set lateral params dependently.
For example, it's able to tune as follow. In this setting, avoidance module keeps 1.5m (0.3 + 0.5 + **0.7**) for PARKED vehicle.
```yaml
bus:
...
lateral_margin:
soft_margin: 0.5                           # [m]
hard_margin: 0.2 …
```

feat(avoidance): change lateral margin based on if it's parked vehicle

---

evaluator/perception_online_evaluator/include/perception_online_evaluator/metrics_calculator.hpp
evaluator/perception_online_evaluator/include/perception_online_evaluator/utils/objects_filtering.hpp
evaluator/perception_online_evaluator/package.xml
evaluator/perception_online_evaluator/src/metrics_calculator.cpp
evaluator/perception_online_evaluator/src/utils/objects_filtering.cpp
evaluator/perception_online_evaluator/test/test_perception_online_evaluator_node.cpp

publish metrics of each object class
e.g. `predicted_path_deviation_CAR_5.00`
psim
evaluator_description: feat/perception_eval_object_class
2024/03/06 https://evaluation.tier4.jp/evaluation/reports/0d75e8bd-369e-5045-b438-8801d9012492/?project_id=prd_jt
unit test
```
1: [==========] Running 16 tests from 1 test suite.
1: [----------] Global test environment set-up.
1: [----------] 16 tests from EvalTest
1: [ RUN      ] EvalTest.testLateralDeviation_deviation0
1: [       OK ] EvalTest.testLateralDeviation_deviation0 (1627 ms)
1: [ RUN      ] EvalTest.testLateralDeviation_deviation1
1: [       OK ] EvalTest.testLateralDeviation_deviation1 (1625 ms)
1: [ RUN      ] EvalTest.testLateralDeviation_oscillation
1: [       OK ] EvalTest.testLateralDeviation_oscillation (2635 ms)
1: [ RUN      ] …
```

feat(perception_online_evaluator): publish metrics of each object class

---

planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/start_planner_module.hpp
planning/behavior_path_start_planner_module/src/start_planner_module.cpp

In the following PRs
- https://github.com/autowarefoundation/autoware.universe/pull/6470
- https://github.com/autowarefoundation/autoware.universe/pull/6438
I intended to "let the vehicle stop for a while before starting pull out action to turn the blinker for a specific time", but forgot the case where the vehicle first drives backward and then start pull out by forward driving. I changed it to start the "blinker preparation" when forward-driving started.
https://evaluation.tier4.jp/evaluation/reports/02465796-fdcb-5949-89d7-aa5dd8ec3e85?project_id=prd_jt
If the prepare time is set to 3 seconds, ego stops a for while before starting forward driving.
https://github.com/autowarefoundation/autoware.universe/assets/28677420/30869363-d253-4a79-9c9f-998a1fdb57dd …

fix(start_planner): consider backward completion before preparing blinker

---

vehicle/raw_vehicle_cmd_converter/config/raw_vehicle_cmd_converter.param.yaml
vehicle/raw_vehicle_cmd_converter/launch/raw_vehicle_converter.launch.xml
vehicle/raw_vehicle_cmd_converter/schema/raw_vehicle_cmd_converter.schema.json

Part of:
- https://github.com/autowarefoundation/autoware.universe/issues/6473
Continuation of:
- https://github.com/autowarefoundation/autoware.universe/pull/6456
- https://github.com/autowarefoundation/autoware.universe/pull/6136
- https://github.com/autowarefoundation/autoware.universe/pull/5134
Related PR:
- https://github.com/autowarefoundation/autoware_launch/pull/884
- `autoware_launch` PR should be merged after this PR. …

fix(raw_vehicle_cmd_converter): csv paths are resolved in param.yaml

---

planning/behavior_path_planner_common/src/utils/drivable_area_expansion/static_drivable_area.cpp

Related ticket: https://tier4.atlassian.net/browse/RT1-5459
Add guard to prevent `std::out_of_range` in following loop.
```c++
// Insert middle points
for (size_t i = start_idx + 1; i <= goal_idx; ++i) {
const auto & next_point = tmp_bound.at(i);
const double dist = tier4_autoware_utils::calcDistance2d(processed_bound.back(), next_point);
if (dist > overlap_threshold) {
processed_bound.push_back(next_point);
}
}
```
Psim
Nothing. …

fix(drivable_area_expansion): fix invalid access

---

evaluator/tier4_metrics_rviz_plugin/src/metrics_visualize_panel.hpp

Fixed metrics_name column is reversed to "metrics_name" and its value.
before
after

fix(tier4_metrics_rviz_plugin): fix metrics_name column

---

planning/route_handler/src/route_handler.cpp

if the rough goal is specified on driving lane, then the leftmost shoulder lane is chosen in getLaneletSequence() function as the `outermost_lane`, and the shoulder lanelets before/after that shoulder lane are collected after this PR. But before this PR, since `only_route_lanes` is false in this case and the shoulder lanes are not included in the default RoutingGraph, the call to getLaneletSequneceAfter/getLaneletSequneceUpTo does not yield any shoulder lanes, which is the reason why the result contains only the single shoulder lane. And if the shoulder is associated with no_parking_area, then goal_planner cannot find any valid road shoulder to park.
https://tier4.atlassian.net/browse/RT1-5528
In the following video the goal is on the driving lane whose left side lane is a shoulder lane …

fix(route_handler): query shoulder lane in getLaneletSequence() if only_route_lanes is false and the arg is shoulder type

---

planning/behavior_velocity_out_of_lane_module/config/out_of_lane.param.yaml
planning/behavior_velocity_out_of_lane_module/package.xml
planning/behavior_velocity_out_of_lane_module/src/decisions.cpp
planning/behavior_velocity_out_of_lane_module/src/filter_predicted_objects.cpp
planning/behavior_velocity_out_of_lane_module/src/filter_predicted_objects.hpp
planning/behavior_velocity_out_of_lane_module/src/manager.cpp
planning/behavior_velocity_out_of_lane_module/src/scene_out_of_lane.cpp
planning/behavior_velocity_out_of_lane_module/src/types.hpp

To avoid incorrect stops with the `out_of_lane` module, the predicted paths of dynamic objects can now be cut beyond the stop line of a red traffic light.
Required launch PR: https://github.com/autowarefoundation/autoware_launch/pull/885
(TIER IV INTERNAL LINKS)
- No degradation with the common release tests: https://evaluation.tier4.jp/evaluation/reports/5998b617-c2bb-5cbf-b068-a7efba51727d?project_id=prd_jt
- Fixes some failing out_of_lane scenarios with the common future tests: https://evaluation.tier4.jp/evaluation/reports/24f76080-71ba-5c27-903a-32f341d3f1fe?project_id=prd_jt
Can also be tested with Psim and the traffic light panel. …

feat(out_of_lane): cut predicted paths after red lights

---

evaluator/tier4_metrics_rviz_plugin/src/metrics_visualize_panel.cpp
evaluator/tier4_metrics_rviz_plugin/src/metrics_visualize_panel.hpp

switch visualization target topic
- "/diagnostic/planning_evaluator/metrics"
- "/diagnostic/perception_online_evaluator/metrics"
https://github.com/autowarefoundation/autoware.universe/assets/39142679/8007162a-50df-4e02-b36a-c37d0958c98a
psim

feat(tier4_metrics_rviz_plugin): switch visualization target topic

---

system/component_state_monitor/config/topics.yaml

I lowered the threshold of pose_estimator_pose because it was triggering too frequently.
related PR https://github.com/autowarefoundation/autoware_launch/pull/910

fix(component_state_monitor): change pose_estimator_pose rate

---

evaluator/tier4_metrics_rviz_plugin/CMakeLists.txt
evaluator/tier4_metrics_rviz_plugin/include/metrics_visualize_panel.hpp
evaluator/tier4_metrics_rviz_plugin/src/metrics_visualize_panel.cpp

add selected metrics view tab
https://github.com/autowarefoundation/autoware.universe/assets/39142679/fa93d115-d372-4894-949d-9da17e8147e1

feat(tier4_metrics_rviz_plugin): add selected metrics view tab

---

localization/ndt_scan_matcher/src/map_update_module.cpp

The current `ndt_scan_matcher` crashes if the initial pose is placed far from the PCD map.
This is because in the case where `update_ndt` fails, `voxel_centroids_ptr_` of ndt remains nullptr and is referenced in subsequent code.
This pull request works around this issue by adding error handling.
Placing the initial position estimate far from the PCD no longer causes a crash.
[contribution …

fix(ndt_scan_matcher): added error handling about update_ndt

---

control/mpc_lateral_controller/src/mpc.cpp

When driving backward, the MPC's precision was not good.
This is because the curvature's sign for the delay compensation was wrong when driving backward. This PR fixed the issue.
In the following videos, see the deviation between the planned trajectory and the white line that is MPC's predicted trajectory.
**before**
https://github.com/autowarefoundation/autoware.universe/assets/20228327/0d366fcd-ed28-4e81-b754-eb2849854bc3
**after**
https://github.com/autowarefoundation/autoware.universe/assets/20228327/f2d011a8-507e-4182-b715-c7039b2506c8
psim
more precise tracking control when backward driving …

fix(mpc_lateral_controller): precise backward driving

---

sensing/imu_corrector/config/gyro_bias_estimator.param.yaml

Because the current gyro bias threshold is too severe to most gyro sensors, this PR relaxes it.
[TIER IV internal ticket](https://tier4.atlassian.net/browse/RT1-5513)
Tested this parameter on our product.

chore(imu_corrector): relax gyro bias threshold parameter

---

control/lane_departure_checker/include/lane_departure_checker/lane_departure_checker.hpp
control/lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker.cpp
launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.xml
planning/behavior_path_start_planner_module/src/shift_pull_out.cpp

Currently there is an issue with the LaneDepartureChecker::getFusedLaneletPolygonForPath() method of the lane departure checker which causes it to return an incomplete or sometimes disjointed polygon. The result is that sometimes part of the ego path would be cut. This PR solves the issue.
Before: 
After:
Before: 
After:
https://github.com/autowarefoundation/autoware.universe/assets/25967964/f9971a93-864e-4a6e-b9be-2294d6d6dc45
Evaluator tests -> No degradation: [TIER IV INTERNAL LINK](https://evaluation.tier4.jp/evaluation/reports/1cc5f592-b259-5ec7-906f-7b4bc715d1d0?project_id=prd_jt) …

fix(lane_departure_checker): empty lanelet polygon

---

evaluator/perception_online_evaluator/package.xml

This PR adds a dependency to `lanelet2_extension` to fix a missing include.

build(perception_online_evaluator): add lanelet2_extension dependency

---

planning/behavior_path_avoidance_module/src/scene.cpp

Sometimes, the avoidance modue generate unnecessary avoidance path for objects which are in intersection even when the ego stops by red traffic signal.
Related PR: https://tier4.atlassian.net/browse/RT1-5365
In this PR, I fixed detection range so that the module can ignore unrelated object.
Improve avoidance behavior. …

fix(avoidance): ignore objects are in intersection when the ego stops by red traffic signal

---

evaluator/perception_online_evaluator/test/test_perception_online_evaluator_node.cpp

Fix `-Werror=deprecated-declarations` error.
```
In file included from /opt/ros/humble/include/rclcpp/rclcpp/subscription_base.hpp:32,                                                                                                                                                                                                                                                                                                                                           
from /opt/ros/humble/include/rclcpp/rclcpp/callback_group.hpp:29, …
```

fix(perception_online_evaluator): fix build error

---

perception/detection_by_tracker/include/detection_by_tracker/debugger.hpp
perception/detection_by_tracker/src/detection_by_tracker_core.cpp
perception/map_based_prediction/README.md
perception/map_based_prediction/include/map_based_prediction/map_based_prediction_node.hpp
perception/map_based_prediction/src/map_based_prediction_node.cpp
perception/multi_object_tracker/src/multi_object_tracker_core.cpp
perception/object_merger/include/object_merger/node.hpp
perception/object_merger/src/object_association_merger/node.cpp
perception/shape_estimation/src/node.cpp
perception/shape_estimation/src/node.hpp
perception/tracking_object_merger/include/tracking_object_merger/decorative_tracker_merger.hpp
perception/tracking_object_merger/src/decorative_tracker_merger.cpp

I added debug topic publisher in following packages:
- map_based_prediction
- tracking_object_merger
- object_merger
- shape_estimation
- detection_by_tracker
- radar_object_tracker
Those package will publish
- cyclic time: elapsed time per one callback cycle
- processing time: calculation time from the callback beginning to end
Tested with Lsim. …

feat(map_based_prediction, etc): publish processing time in various perception nodes

---

planning/behavior_velocity_intersection_module/src/debug.cpp
planning/behavior_velocity_intersection_module/src/scene_intersection.hpp
planning/behavior_velocity_intersection_module/src/scene_intersection_occlusion.cpp

modify the dynamic occlusion estimation by triangle, not by line.
form a triangle with 
- the nearest occlusion cell
- and the occluded cell behind that cell
- ego position
and check if it collides with vehicles inside intersection_area
https://evaluation.tier4.jp/evaluation/reports/1a7dd4ca-b9df-5114-98e4-a821c072baa3?project_id=prd_jt
https://github.com/autowarefoundation/autoware.universe/assets/28677420/e0e1f5e8-79c2-4885-91a9-ba003507b9ac
https://github.com/autowarefoundation/autoware.universe/assets/28677420/6208075b-c1e3-449e-8f45-7f0ff65cdb81
none
none …

fix(intersection_occlusion): estimate dynamic occlusion source with triangle

---

localization/localization_util/src/smart_pose_buffer.cpp
localization/localization_util/src/util_func.cpp
localization/ndt_scan_matcher/src/map_update_module.cpp
localization/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp
localization/pose_initializer/src/pose_initializer/ndt_module.cpp
sensing/pointcloud_preprocessor/src/concatenate_data/concatenate_and_time_sync_nodelet.cpp
sensing/pointcloud_preprocessor/src/filter.cpp

This PR is one of group of PRs that aim to fix Autoware logging system to achieve the goal of reducing excessive error and warning logs on Autoware launch. 
Part of:
- https://github.com/autowarefoundation/autoware.universe/issues/5539
More details in the [issue](https://github.com/autowarefoundation/autoware.universe/issues/5539).
- Planning Simulation
- Run [Autoware planning simulator](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/planning-simulation/) and you can see no more excessive and recurring error, warning, and info message when the system running as expected
- Rosbag Replay Simulation
- Run [Autoware rosbag repay simulation](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/rosbag-replay-s …

fix(log-messages): reduce excessive log messages

---

build_depends.repos
common/tier4_autoware_utils/include/tier4_autoware_utils/ros/published_time_publisher.hpp
common/tier4_autoware_utils/package.xml

Part of:
- https://github.com/autowarefoundation/autoware.universe/issues/6255
Required for:
- https://github.com/autowarefoundation/autoware.universe/pull/6490
Depends on:
- https://github.com/autowarefoundation/autoware/pull/4212
- https://github.com/autowarefoundation/autoware_internal_msgs/pull/1
This interface would be enabled only if the use_published_time = true. 
Tested on PSim and e2e_simulator, worked well. …

feat(tier4_autoware_utils): add published time debug class into utils

---

planning/behavior_velocity_blind_spot_module/src/scene.cpp
planning/behavior_velocity_blind_spot_module/src/scene.hpp

blind_spot module did not work in there are no conflicting lanes on the assigned lane. As a fallback, in that case, use the entry of the intersection lane for collision detection.
If there is not conflicting lanelet, blind_spot module does not work properly or does nothing.
https://github.com/autowarefoundation/autoware.universe/assets/28677420/3f1f0d76-4d51-4e42-9d0a-d1f0925028b6
blind_spot module works without conflicting lanelet
https://github.com/autowarefoundation/autoware.universe/assets/28677420/7f54d94d-49b8-4091-87bc-2c47be613cf2
https://tier4.atlassian.net/browse/RT1-5514
https://evaluation.tier4.jp/evaluation/reports/637486ef-6bc2-545c-b6bc-abe0f2285cd8?project_id=prd_jt
none
none …

fix(blind_spot): find collision point using sibling straight lanelet boundary

---

sensing/pointcloud_preprocessor/docs/ring-outlier-filter.md
sensing/pointcloud_preprocessor/include/pointcloud_preprocessor/outlier_filter/ring_outlier_filter_nodelet.hpp
sensing/pointcloud_preprocessor/src/outlier_filter/dual_return_outlier_filter_nodelet.cpp
sensing/pointcloud_preprocessor/src/outlier_filter/ring_outlier_filter_nodelet.cpp

Refactor for the [PR](https://github.com/autowarefoundation/autoware.universe/pull/6483) 
- Renamed the `publish_excluded_points` flag to `publish_noise_points`.
- Removed the `extractExcludedPoints` function
- Defined `setUpPointCloudFormat` to consolidate duplicate processes
- Renamed `horizontal_res` to `horizontal_resolution`.
confirmed with logging simulator
described in the [PR](https://github.com/autowarefoundation/autoware.universe/pull/6483)  …

refactor(pointcloud_preprocessor): publish noise points in ring outlier filter

---

perception/multi_object_tracker/CMakeLists.txt
perception/multi_object_tracker/include/multi_object_tracker/tracker/model/pedestrian_tracker.hpp
perception/multi_object_tracker/include/multi_object_tracker/tracker/motion_model/ctrv_motion_model.hpp
perception/multi_object_tracker/src/tracker/motion_model/bicycle_motion_model.cpp

add cspell ignore for CTRV to pass spell-check-partial
pass spell-check-partial

fix: add cspell ignore for CTRV

---

planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
planning/behavior_velocity_intersection_module/src/scene_intersection.hpp
planning/behavior_velocity_intersection_module/src/scene_intersection_occlusion.cpp
planning/behavior_velocity_intersection_module/src/scene_intersection_prepare_data.cpp

if the priority level changed from NOT_PRIORITIZED to PRIORITIZED, the intersection_occlusion wall is quickly removed for smooth start.
there is a short elapsed time gap until intersection_occlusion is cleared ( about 1~2 second).
https://github.com/autowarefoundation/autoware.universe/assets/28677420/d3dc8c19-dd2e-4fec-820d-dfc39c4e5725
there is very few delay.
https://github.com/autowarefoundation/autoware.universe/assets/28677420/f5ccfc03-0763-4763-a58a-e313619465c8
https://tier4.atlassian.net/browse/RT1-5444
https://evaluation.tier4.jp/evaluation/reports/9fa78d8a-3af7-5dc1-ab69-19d8d9a7a7d5?project_id=prd_jt
none
none …

feat(intersection_occlusion): quickly delete occlusion wall on change from green to yellow/red

---

control/pid_longitudinal_controller/include/pid_longitudinal_controller/pid_longitudinal_controller.hpp
control/pid_longitudinal_controller/src/pid_longitudinal_controller.cpp
launch/tier4_control_launch/launch/control.launch.py

Added a text marker of "steering not converged" to easily notice that the ego keeps stopped since the steering control is not converged.
Disabled by default.
psim
Nothing

feat(pid_longitudinal_controller): add maker for stop reason

---

launch/tier4_simulator_launch/launch/simulator.launch.xml

Part of:
- https://github.com/autowarefoundation/autoware.universe/issues/6547
Required for:
- https://github.com/autowarefoundation/autoware.universe/pull/5954
Reaction_analyzer runs with PSim and it publishes its perception outputs to be able to measure exact reaction times. 
What we want to do is we can be able to disable the perception publishers.
This change does not have any effect on system behavior because its default value is `true`.
Tested in PSim. Works as we expected. 
- `launch_simulator_perception_modules` is `true` -> it does not have any effect on the system.
- `launch_simulator_perception_modules` is `false` -> it does not launch perception-related modules. …

feat(tier4_simulator_launch): add option to disable all perception related modules

---

perception/multi_object_tracker/include/multi_object_tracker/multi_object_tracker_core.hpp
perception/multi_object_tracker/src/multi_object_tracker_core.cpp
perception/multi_object_tracker/src/tracker/motion_model/bicycle_motion_model.cpp
perception/multi_object_tracker/src/tracker/motion_model/ctrv_motion_model.cpp
perception/multi_object_tracker/src/tracker/motion_model/cv_motion_model.cpp
perception/multi_object_tracker/src/tracker/motion_model/motion_model_base.cpp

The extended kalman filter update process was done in multiple-step when the given time-step is too large.
However, the implementation was not work as intended.
* multi-step prediction
```c++
// if dt is too large, shorten dt and repeat prediction
const uint32_t repeat = std::ceil(dt / dt_max_);
const double dt_ = dt / repeat;
for (uint32_t i = 0; i < repeat; ++i) {
if (!predictStateStep(dt_, tmp_ekf_for_no_update)) {
return false;
}
}
```
The motion model prediction is linealization of non-linear motion model. The prediction step assumes the time difference is small enough. By keeping the prediction time step small, a maximum time step was set and the prediction is to be conducted in multiple times.
* Found symptom: the multi-step prediction is not working as intended. 
Until the reason …

fix(multi_object_tracker): mot multi-step prediction is not work as intended

---

sensing/pointcloud_preprocessor/src/concatenate_data/concatenate_pointclouds.cpp
sensing/pointcloud_preprocessor/src/time_synchronizer/time_synchronizer_nodelet.cpp

- https://github.com/autowarefoundation/autoware.universe/issues/6032
In the issue above, we discussed that a more efficient method would be for the nodes themselves to report the delays.
I missed adding this debug publisher to concatenate_pointclouds and time_synchronizer.
Tested with e2e_simulator. Works well. …

feat(pointcloud_preprocessor): add pipeline_latency_ms debug publisher to missed modules

---

perception/multi_object_tracker/include/multi_object_tracker/tracker/model/tracker_base.hpp
perception/multi_object_tracker/src/tracker/model/multiple_vehicle_tracker.cpp
perception/multi_object_tracker/src/tracker/model/pedestrian_and_bicycle_tracker.cpp
perception/multi_object_tracker/src/tracker/model/tracker_base.cpp

The current object tracker uses the incoming classification directly.
When the detection has ambiguous classification, the classification result may changes in a short time.
Frequent classification change may have negative impact on the tracked object consumers (planner). 
In this PR, a simple classification filter is introduced.
// 0. Normalize the input classification
// 1-1. Update the matched classification probability with a gain (ratio of 0.05)
// 1-2. If the label is not found, add it to the classification list
// 2. Remove the class with probability < remove_threshold (0.001)
// 3. Normalize tracking classification
[TIER IV INTERNAL](https://tier4.atlassian.net/browse/RT1-5725)
https://github.com/autowarefoundation/autoware.universe/assets/42434141/43ec72ca-951a-4585-a7c5-51f7ee0e0 …

feat(multi_object_tracker): add object class filtering in tracking process

---

planning/behavior_path_avoidance_by_lane_change_module/src/manager.cpp
planning/behavior_path_avoidance_module/config/avoidance.param.yaml
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/data_structs.hpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/helper.hpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/parameter_helper.hpp
planning/behavior_path_avoidance_module/src/debug.cpp
planning/behavior_path_avoidance_module/src/scene.cpp
planning/behavior_path_avoidance_module/src/shift_line_generator.cpp
planning/behavior_path_avoidance_module/src/utils.cpp

Related PR: https://github.com/autowarefoundation/autoware_launch/pull/923
Related ticket: https://tier4.atlassian.net/browse/RT1-202
Fix bug. The module ignored merging vehicle unexpectedly. Originally, I designed the module generates avoidance path for every objects that are NOT on ego lane. (Only for objects in intersection, the module sometimes ignores them.)
https://github.com/autowarefoundation/autoware.universe/assets/44889564/a436e96e-7760-4668-b32c-3c60a05dbd91
And, this PR includes small refactoring as well.
```
webauto ci scenario run --project-id prd_jt --scenario-id f9e88ceb-0e06-48d5-9bad-be5ed4a244a0 --scenario-parameters '__tier4_modifier_npc_position_t=3'
```
Nothing.
The PR reviewers **must** check …

fix(avoidance): the module ignored merging objects unexpectedly

---

planning/behavior_path_lane_change_module/src/scene.cpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner_common/include/behavior_path_planner_common/parameters.hpp

Lane change max velocity computation currently doesn't consider the parameterized input from `common.max_vel`. The result is that it causes the prepare path to be much longer than anticipated, plus, the results also affects the safety check, where the expected velocity is different from the actual velocity, which causes many safety check issues. 
This PR aims to solve this by including the max_vel parameter
Prepare path is long, plus safety check is difficult to be approved.
https://github.com/autowarefoundation/autoware.universe/assets/93502286/79d9c978-9830-40fe-98f7-5fe3e371a8e6
Safety check is much simpler to be approved.
https://github.com/autowarefoundation/autoware.universe/assets/93502286/d82662a9-87f8-49b8-8800-25d97bdb1b32
TBA
None
None
None …

fix(lane_change): consider max velocity during path planning

---

localization/ndt_scan_matcher/src/map_update_module.cpp

The following PR for ndt_omp has been changed to now crash when a nullptr is passed to `MultiGridNormalDistributionsTransform::setInputSource`.
https://github.com/tier4/ndt_omp/pull/40/files
In this PR, Fixed the possibility of passing nullptr during initial position estimation in map_update_module.
This could occur in situations with low computing resources, such as on a laptop. This is because if there is no long range LiDAR in the concat point cloud, input pointcloud cannot be accepted and input_source remains as nullptr.
* It has been confirmed that the `logging_simulator` runs with the same accuracy as before on AWSIM data with GT.
This will prevent the NDT node from crashing. …

fix(ndt_scan_matcher): avoid passing nullptr in ndt

---

planning/behavior_path_planner_common/docs/behavior_path_planner_turn_signal_design.md
planning/behavior_path_planner_common/include/behavior_path_planner_common/data_manager.hpp
planning/behavior_path_planner_common/include/behavior_path_planner_common/turn_signal_decider.hpp
planning/behavior_path_planner_common/src/turn_signal_decider.cpp

Add a general method to obtain the correct turnSignalInfo for all behavior path planner modules.
This PR implements only the method itself. The method has been tested with the start planner, goal planner, avoidance and lane change modules as depicted here: https://github.com/autowarefoundation/autoware.universe/pull/6622
This PR is 1 of 5 and the other PRs will depend on this one (to be linked)
Please see the Above link for further details
After approving this PR, the following PRs implement this method in the bpp modules: 
Avoidance: https://github.com/autowarefoundation/autoware.universe/pull/6626
Lane Change: https://github.com/autowarefoundation/autoware.universe/pull/6627
Start Planner: https://github.com/autowarefoundation/autoware.universe/pull/6628
Goal Planner: …

feat(behavior_path_planner_common): add general method for calculating turn signal for bpp modules

---

planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/freespace_pull_out.hpp
planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/geometric_pull_out.hpp
planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/pull_out_planner_base.hpp
planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/shift_pull_out.hpp
planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/util.hpp
planning/behavior_path_start_planner_module/src/geometric_pull_out.cpp
planning/behavior_path_start_planner_module/src/shift_pull_out.cpp
planning/behavior_path_start_planner_module/src/start_planner_module.cpp
planning/behavior_path_start_planner_module/src/util.cpp

Currently, collision checking is done AFTER the geometric and shift pull out planners have decided on a candidate output path. The result is that, a path that is collided might be chosen as an output path and then eliminated by the collision checking. 
With this PR, the collision checking is moved inside the planners themselves, so, especially in the case of shift pull out, if a candidate path has a collision with a target object, it might generate a different path that is inside lanes and not collided.
Further description here: [TIER IV INTERNAL LINK](https://app.slack.com/client/E01J1USSLPP/C03QW0GU6P7)
Related ticket: [TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT1-5491)
Further description here: [TIER IV INTERNAL …

feat(start_planner): move collision check to plan method

---

common/tier4_autoware_utils/test/src/ros/test_published_time_publisher.cpp

**Part of:**
- https://github.com/autowarefoundation/autoware.universe/issues/6255
**Required from:**
- https://github.com/autowarefoundation/autoware.universe/pull/6440#pullrequestreview-1931367141
**Depends on:**
- https://github.com/autowarefoundation/autoware.universe/pull/6490
_because of renaming of `publish()` function_ …

feat(published_time_publisher): add unit test

---

planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/start_planner_module.hpp
planning/behavior_path_start_planner_module/src/start_planner_module.cpp

Implements the changes of https://github.com/autowarefoundation/autoware.universe/pull/6625 for the start planner module's turnSignalInfo calculation into the Avoidance module. Please see original PR for a bigger description: https://github.com/autowarefoundation/autoware.universe/pull/6622/files
This PR is 1 out of 5 and depends on this PR: https://github.com/autowarefoundation/autoware.universe/pull/6625
The idea is to implement the general method for getting the turn signal into the start,goal,avoidance and LC modules.
See https://github.com/autowarefoundation/autoware.universe/pull/6622/files …

feat(start_planner): add general turn signal method to start planner

---

planning/behavior_path_goal_planner_module/src/goal_planner_module.cpp
planning/route_handler/src/route_handler.cpp

if the road shoulder forms a loop, this logic enters an infinite loop.
https://tier4.atlassian.net/browse/RT1-5730
tested on the map with a looped shoulder
none
none

fix(route_handler): detect looped road shoulders in getShoulderLaneletSequence()

---

sensing/pointcloud_preprocessor/include/pointcloud_preprocessor/concatenate_data/concatenate_and_time_sync_nodelet.hpp
sensing/pointcloud_preprocessor/include/pointcloud_preprocessor/time_synchronizer/time_synchronizer_nodelet.hpp
sensing/pointcloud_preprocessor/src/concatenate_data/concatenate_and_time_sync_nodelet.cpp
sensing/pointcloud_preprocessor/src/time_synchronizer/time_synchronizer_nodelet.cpp

Related https://github.com/autowarefoundation/autoware.universe/pull/5485, this PR enables to publish synchronized pointclouds in sensor_frame.
- changes
- add rosparam to handle wheather synchronized pointcloud should be published in output frame or input(original) frame
- add pointcloud transform process when need to publish in sensor frame
- put latency measurement description to  last part of the pointcloud callback
```
❯ ros2 topic echo /sensing/lidar/top/pointcloud --field header
1710144739.261797 [112]       ros2: determined wlp9s0 (udp/10.0.57.190) as highest quality interface, selected for automatic interface.
stamp:
sec: 1585897258
nanosec: 286857728
frame_id: velodyne_top
```
https://github.com/orgs/autowarefoundation/discussions/4158
Tested with Lsim.
Need to merge …

feat(pointcloud_preprocessor): make concatenate node to publish pointclouds in sensor frame

---

common/tier4_autoware_utils/CMakeLists.txt
common/tier4_autoware_utils/include/tier4_autoware_utils/ros/published_time_publisher.hpp

fix(tier4_autoware_utils): fix build error (caused by `published_time_publisher.hpp`)

---

planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/pull_out_planner_base.hpp
planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/util.hpp
planning/behavior_path_start_planner_module/src/util.cpp

If the path for collision check happens to be empty, it might cause a crash, this PR introduces a sanity check for said cases. 
PSim and compilation tests

feat(start_planner): add a sanity check if the path is empty

---

planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/scene.hpp
planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/utils/base_class.hpp
planning/behavior_path_lane_change_module/src/scene.cpp

Implements the changes of https://github.com/autowarefoundation/autoware.universe/pull/6625 for the Lane Change module's turnSignalInfo calculation into the Avoidance module. Please see original PR for a bigger description: https://github.com/autowarefoundation/autoware.universe/pull/6622/files
This PR is 1 out of 5 and depends on this PR: https://github.com/autowarefoundation/autoware.universe/pull/6625
The idea is to implement the general method for getting the turn signal into the start,goal,avoidance and LC modules.
See https://github.com/autowarefoundation/autoware.universe/pull/6622/files
See https://github.com/autowarefoundation/autoware.universe/pull/6622/files …

feat(lane_change_module): add general method to get turn signal for LC module

---

planning/obstacle_cruise_planner/config/obstacle_cruise_planner.param.yaml
planning/obstacle_cruise_planner/include/obstacle_cruise_planner/common_structs.hpp

Move slow down min acc and min jerk params to the ocp's params file for better clarity.
Related Launch PR: https://github.com/autowarefoundation/autoware_launch/pull/926
Related ticket: [TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT1-5275)
PSim

refactor(obstacle_cruise_planner): move slow down params to a clear location

---

.github/workflows/build-and-test-differential.yaml

- This was removed with:
- https://github.com/autowarefoundation/autoware.universe/pull/6507
- Now that the essential tasks are running on the github public runners, we can bring this job back
Related PR:
- https://github.com/autowarefoundation/autoware.universe/pull/6641
I will add a small bug to test if it could catch that. …

ci(build-and-test-differential): bring back clang-tidy-differential job

---

localization/landmark_based_localizer/ar_tag_based_localizer/test/test.cpp

Added a 1 second wait to the test to address the issue below.
https://github.com/autowarefoundation/autoware.universe/issues/6619
It has been confirmed that the following command succeeds more than 200 times.
```
colcon test --packages-select ar_tag_based_localizer --event-handlers console_cohesion+
``` …

fix(ar_tag_based_localizer): added 1 second wait to test

---

common/tier4_autoware_utils/include/tier4_autoware_utils/ros/published_time_publisher.hpp

Fixes some clang-tidy errors on this code.
Related:
- https://github.com/autowarefoundation/autoware.universe/pull/6647
- https://github.com/autowarefoundation/autoware.universe/pull/6641
- https://github.com/autowarefoundation/autoware.universe/pull/6440
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request- …

fix(tier4_autoware_utils): clang-tidy errors for published_time_publisher

---

planning/behavior_path_avoidance_by_lane_change_module/src/manager.cpp
planning/behavior_path_avoidance_module/config/avoidance.param.yaml
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/data_structs.hpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/helper.hpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/parameter_helper.hpp
planning/behavior_path_avoidance_module/src/debug.cpp
planning/behavior_path_avoidance_module/src/scene.cpp
planning/behavior_path_avoidance_module/src/shift_line_generator.cpp
planning/behavior_path_avoidance_module/src/utils.cpp

Related PR: https://github.com/autowarefoundation/autoware_launch/pull/925 (Please approve at first.)
Related ticket: https://tier4.atlassian.net/browse/RT1-5553
Previously, the module generates avoidance path as soon as it detects ambiguous stopped vehicle. However, this sometimes caused unnecessary avoidance maneuver. Basically, we should wait and see such kind vehicles at first. And if necessary, the module should generates avoidance path after closing them.
```yaml
avoidance_for_ambiguous_vehicle:
enable: false                                  # [-]
closest_distance_to_wait_and_see: 10.0         # [m]
...
```
The module waits avoidance path generation until the ego gets closer to ambiguous vehicle. When the distance between ego and avoidance start point is less than …

feat(avoidance): wait and see ambiguous stopped vehicle

---

planning/behavior_velocity_dynamic_obstacle_stop_module/README.md
planning/behavior_velocity_dynamic_obstacle_stop_module/config/dynamic_obstacle_stop.param.yaml
planning/behavior_velocity_dynamic_obstacle_stop_module/src/manager.cpp
planning/behavior_velocity_dynamic_obstacle_stop_module/src/object_filtering.cpp
planning/behavior_velocity_dynamic_obstacle_stop_module/src/scene_dynamic_obstacle_stop.cpp
planning/behavior_velocity_dynamic_obstacle_stop_module/src/types.hpp

Add an option to ignore unavoidable collisions with the `dynamic_obstacle_stop` module.
If an object is detected as heading straight toward the ego vehicle, such that even if ego stops the collision would be unavoidable, then the object is ignored by the module.
This is to avoid sudden stops caused by noise in the perception.
Required launch PR: https://github.com/autowarefoundation/autoware_launch/pull/916
(TIER IV INTERNAL LINK) https://tier4.atlassian.net/browse/RT1-5690 …

feat(dynamic_obstacle_stop): add option to ignore unavoidable collisions

---

sensing/pointcloud_preprocessor/include/pointcloud_preprocessor/outlier_filter/dual_return_outlier_filter_nodelet.hpp

This pull request encapsulates the roi_mode_map_ within the DualReturnOutlierFilterComponent class to improve the organization of the code and its maintainability. 
Previously, roi_mode_map_ was defined in the global namespace, which could potentially lead to naming conflicts. …

refactor(pointcloud_preprocessor): move roi_mode_map_ definition inside DualReturnOutlierFilterComponent class

---

planning/behavior_path_avoidance_module/config/avoidance.param.yaml
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/data_structs.hpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/parameter_helper.hpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/scene.hpp
planning/behavior_path_avoidance_module/src/scene.cpp

Fix bug. The module inserts stop point unexpectedly even when it is not able to generate valid avoidance path.
Failed scenarios: [UC-v2-F-15-00103_001_case01_cmn_general](https://evaluation.ci.tier4.jp/evaluation/reports/c5d5563c-4266-5604-b1ea-22f9eca30ec6/tests/e08fb472-6552-56bd-bdc2-11855ba5b5e3/b01dbb01-6292-511f-ad5f-d813822d8024/87895384-d19f-5f50-8d23-74fe5e4594c5?project_id=prd_jt)
Please approve https://github.com/autowarefoundation/autoware_launch/pull/928 at first.
```
webauto ci scenario run --project-id prd_jt --scenario-id c10116dc-4e4b-4703-91ca-b8be78209633 --scenario-version-id 1
```
https://github.com/autowarefoundation/autoware.universe/assets/44889564/23a640ba-f5eb-4a94-aa40-a9f252c1d25f
Nothing. …

fix(avoidance): don't slow down if avoidance is NOT definitely necessary during unsafe condition

---

planning/behavior_velocity_out_of_lane_module/src/filter_predicted_objects.cpp

Fixes an edge case with the feature to cut predicted paths at red traffic lights.
In some case the predicted path goes slightly around the stop line and it is not correctly cut.
With this PR, the stop line is made longer to avoid this edge case.
- TIER IV INTERNAL LINK: https://tier4.atlassian.net/browse/RT1-5753
Psim …

fix(out_of_lane): use bigger stop lines to cut predicted paths

---

launch/tier4_control_launch/launch/control.launch.py

Enabling heavy processing nodes like AEB can lead to inadequate performance in single-threaded mode. Therefore, we will enable multi-threading for the control container.
I confirmed that the control container has been multithreaded.
$ps ax|grep control_container
-> ...rclcpp_components/component_container_**mt** --ros-args -r __node:=control_container -r...
No effects on default
[pull …

feat: enable multithreading for the control container

---

planning/behavior_velocity_dynamic_obstacle_stop_module/src/scene_dynamic_obstacle_stop.cpp

set velocity factor of `dynamic_obstacle_stop` to `ROUTE_OBSTACLE`.

feat(dynamic_obstacle_stop): set velocity factor to ROUTE_OBSTACLE

---

planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp

add velocity factor when slowing down in the `crosswalk` module.

feat(crosswalk): add velocity factor when slowing down

---

common/motion_utils/include/motion_utils/trajectory/trajectory.hpp

Fix node dying.
```shell
terminate called after throwing an instance of 'std::out_of_range'
what():  vector::_M_range_check: __n (which is 54) >= this->size() (which is 54)
Thread 1 "behavior_path_p" received signal SIGABRT, Aborted.
0x00007ffff74969fc in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff74969fc in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff7442476 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff74287f3 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007ffff78a2b9e in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff78ae20c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff78ae277 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff78ae4d8 …
```

fix(motion_utils): check size after overlap points removal

---

perception/probabilistic_occupancy_grid_map/launch/multi_lidar_pointcloud_based_occupancy_grid_map.launch.py

This is bug fix of https://github.com/autowarefoundation/autoware.universe/pull/5485.
Due to old launch configuration paramter `container_name`, multi_lidar_ogm process fail when `use_pointcloud_container` is True.
Tested with TIER IV xx1 vehicle and Lsim

fix(probabilistic_occupancy_grid_map): fix launch config name from old one

---

planning/planning_validator/src/planning_validator.cpp

Related JIRA Ticket:  https://tier4.atlassian.net/browse/RT0-29352
In the planning validator, among other checks, the max lateral acceleration is calculated and checked whether it is larger than 1G [ms^2] or not from an input of trajectory. The lateral accelerations are calculated from longitudinal velocities and curvatures at every trajectory points.
The validation function in the planning validator includes two internal trajectory variables, namely `trajectory`, an input from the motion velocity smoother which is densely sampled near the ego and sparsely sampled otherwise with the policy explained [here](https://autowarefoundation.github.io/autoware.universe/main/planning/motion_velocity_smoother/#resample-trajectory) , and `resampled`, representing the same path as `trajectory` but …

fix(planning_validator): calculate max lateral acceleration after resampling trajectory

---

launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.xml

[Glog](https://github.com/autowarefoundation/autoware.universe/pull/4714) is useful to find stack-trace message when the process dies.
Currently, it usually appears in the console, but does not appear in the `~/.ros/<date>/launch.log`.
This PR enables glog to output both in console and launch.log **in planning module**.
Confirmed there is stack-trace both in console and launch.log in my local environment.
Also, it has little effect on the CPU. This is because most ROS logs are already recorded in both console and launch.log. Almost only glog affects it.
After all …

chore(tier4_planning_launch): set log output both

---

planning/behavior_velocity_out_of_lane_module/src/lanelets_selection.cpp
planning/behavior_velocity_out_of_lane_module/src/lanelets_selection.hpp

`path_lanelets` are not considered for overlaps in the `out_of_lane`. They are currently calculated as all the lanelets crossed by the ego path linestring.
In some lane change edge cases, the ego path linestring does not cross a lanelet but the ego footprint will overlap the lanelet, possibly causing the `out_of_lane` module to detect a collision and cause a stop.
With this PR, a function to add the missing lane change lanelets is added.
In the following picture, the lane changing path (green) overlaps the 4 lanelets, but the current `path_lanelets` only includes 3 lanelets (in blue). With this PR, all 4 lanelets are correctly found.
--- | ---
Psim
Evaluator (TIER IV INTERNAL LINK): https://evaluation.tier4.jp/evaluation/reports/tables/new?catalog_id=095ae8b3-a23b-4a08-8674-10a681449693&fi …

fix(out_of_lane): calculate path lanelets that we can miss during a lane change

---

planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/goal_planner_module.hpp
planning/behavior_path_goal_planner_module/src/goal_planner_module.cpp

Implements the changes of https://github.com/autowarefoundation/autoware.universe/pull/6625 for the Goal Planner module's turnSignalInfo calculation into the Avoidance module. Please see original PR for a bigger description: https://github.com/autowarefoundation/autoware.universe/pull/6622/files
This PR is 1 out of 5 and depends on this PR: https://github.com/autowarefoundation/autoware.universe/pull/6625
The idea is to implement the general method for getting the turn signal into the start,goal,avoidance and LC modules.
See https://github.com/autowarefoundation/autoware.universe/pull/6622/files …

feat(goal_planner): add general turnsignalinfo method for goal planner

---

planning/behavior_path_goal_planner_module/src/manager.cpp

Add support for rqt reconfig for the start planner

feat(goal_planner): add param reconfig to goal planner

---

control/vehicle_cmd_gate/test/src/test_filter_in_vehicle_cmd_gate_node.cpp

Continuation from:
- https://github.com/autowarefoundation/autoware.universe/pull/6661
Attempts to fix:
- https://github.com/autowarefoundation/autoware.universe/issues/6612
@takayuki5168 -san, I've implemented this variable window length calculation to smooth out the control values.
https://github.com/autowarefoundation/autoware.universe/blob/9f319571cd7a4270aa67d8c07e812b4b569e301e/control/vehicle_cmd_gate/test/src/test_filter_in_vehicle_cmd_gate_node.cpp#L84-L86
`checkFilter(2)` should work same as the original implementation.
But higher values will will average over 3 or more values for buffering spiky test results.
`colcon test --event-handlers console_cohesion+ --packages-select vehicle_cmd_gate` passes successfully with or without this PR.
- …

fix(vehicle_cmd_gate): fix publisher HZ in the unit test by introducing variable window length

---

planning/behavior_path_lane_change_module/src/interface.cpp
planning/behavior_path_lane_change_module/src/scene.cpp

When lane change plans for lane changing path, when there is no valid path, it will return empty path. When the empty path is sent to the next module, it causes the module to die. In this case, it is the Avoidance  module.
```
[component_container_mt-73]     @     0x7f7a1aa8f7f3 abort
[component_container_mt-73]     @     0x7f7a1aaf0676 (unknown)
[component_container_mt-73]     @     0x7f7a1ab07cfc (unknown)
[component_container_mt-73]     @     0x7f7a1ab09a44 (unknown)
[component_container_mt-73]     @     0x7f7a1ab0c453 free
[component_container_mt-73]     @     0x7f79eddf7dad autoware_auto_planning_msgs::msg::PathWithLaneId_<>::operator=()
[component_container_mt-73]     @     0x7f79eddf4998 behavior_path_planner::AvoidanceModule::updateData()
[component_container_mt-73]     @ …
```

fix(lane_change): do not return empty path if no valid path

---

planning/behavior_path_avoidance_by_lane_change_module/include/behavior_path_avoidance_by_lane_change_module/scene.hpp
planning/behavior_path_avoidance_by_lane_change_module/src/scene.cpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/data_structs.hpp
planning/behavior_path_lane_change_module/src/interface.cpp

Avoidance by Lane Change's (AbLC) object filtering algorithm for activation condition, shares the same method as Avoidance module's filters. Due to this, there are many instances where AbLC couldn't be activated due to the differences between the parameter, and the expected behavior.
This PR aims to loosen the filtering condition, so that it is more easier to be activated.
Object in current lane is removed from being an target object, and avoidance or lane change will be activated instead.
https://github.com/autowarefoundation/autoware.universe/assets/93502286/78c2f0ce-2ddc-4a71-8372-1f7944af75fe
Object in current lane is registered as target object, and AbLC is activated.
https://github.com/autowarefoundation/autoware.universe/assets/93502286/189b8303-eb22-4e99-a2ff-9905b1c7d472
None …

fix(avoidance_by_lane_change): object filtering too conservative

---

planning/behavior_velocity_run_out_module/README.md
planning/behavior_velocity_run_out_module/config/run_out.param.yaml
planning/behavior_velocity_run_out_module/package.xml
planning/behavior_velocity_run_out_module/src/manager.cpp
planning/behavior_velocity_run_out_module/src/scene.cpp
planning/behavior_velocity_run_out_module/src/scene.hpp
planning/behavior_velocity_run_out_module/src/utils.hpp

Add motorcycles to run out module target obstacles: 
Reasoning: 
There are many situations in which object recognition misrepresents bicycles as motorcycles. It also makes little sense to say that if the ego vehicle needs to suddenly stop for a bicycle, why wouldn't it also stop for a motorcycle? 
Ticket: [TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT1-5643)
PSim
Requires launch changes: https://github.com/autowarefoundation/autoware_launch/pull/936
Run out module can activate for motorcycles too. …

feat(run_out): add motorcyles to run out module target obstacles

---

planning/behavior_path_goal_planner_module/src/goal_planner_module.cpp

stop path candidates update after arriving modified goal
https://evaluation.tier4.jp/evaluation/reports/409479c2-0399-5e0e-bb86-f45e52943eee?project_id=prd_jt

fix(goal_planner): stop path candidates update after arriving modified goal

---

planning/static_centerline_optimizer/CMakeLists.txt
planning/static_centerline_optimizer/package.xml

I found the build time of `static_centerline_optimizer` to be too long and maybe this PR will help.
It simply removes some unused dependencies (opencv and eigen) and moves the `behavior_*_planner`  dependencies to `test_dependencies` (for build we only need `behavior_path_planner_common`. …

perf(static_centerline_optimizer): cleanup the package dependencies

---

planning/freespace_planner/src/freespace_planner/freespace_planner_node.cpp

fixes #6380 
fixes #6378 
fixes #6381 
This PR is one of group of PRs that aim to fix Autoware logging system to achieve the goal of reducing excessive error and warning logs on Autoware launch. 
Part of:
- https://github.com/autowarefoundation/autoware.universe/issues/5539
More details in the [issue](https://github.com/autowarefoundation/autoware.universe/issues/5539).
- Before this PR : https://youtu.be/UgCDS1_il0c
- After this PR : https://youtu.be/Wa5EIJ_Sw6Y
N.A
The errors and warnings mentioned in #6380 , #6378, and #6381 are no longer occuring. …

fix(freespace_planner): fix parking trajectory errors and warnings when parking completed

---

sensing/pointcloud_preprocessor/config/blockage_diagnostics_param_file.yaml
sensing/pointcloud_preprocessor/include/pointcloud_preprocessor/blockage_diag/blockage_diag_nodelet.hpp
sensing/pointcloud_preprocessor/src/blockage_diag/blockage_diag_nodelet.cpp

- To change dust diagnostics and publish debug image as optional. There is no any change in blockage and dust detection result.
- Need merge together with param update for each product 
- https://github.com/tier4/aip_launcher/pull/225
- https://github.com/tier4/aip_launcher/pull/224
- [TIER IV INTERNAL LINK](https://star4.slack.com/archives/C03S84LDJGG/p1710731596847099?thread_ts=1710731286.879449&cid=C03S84LDJGG)
- Confirmed by `logging_simulator` that each `blockage_diag` node reflected the optional params correctly.
```
enable_dust_diag: false
publish_debug_image: false
```
```
enable_dust_diag: true
publish_debug_image: false
```
```
enable_dust_diag: false
publish_debug_image: true
``` …

chore(blockage_diag): add dust diagnostic option param

---

planning/behavior_velocity_dynamic_obstacle_stop_module/README.md
planning/behavior_velocity_dynamic_obstacle_stop_module/config/dynamic_obstacle_stop.param.yaml
planning/behavior_velocity_dynamic_obstacle_stop_module/src/collision.cpp
planning/behavior_velocity_dynamic_obstacle_stop_module/src/collision.hpp
planning/behavior_velocity_dynamic_obstacle_stop_module/src/debug.cpp
planning/behavior_velocity_dynamic_obstacle_stop_module/src/debug.hpp
planning/behavior_velocity_dynamic_obstacle_stop_module/src/manager.cpp
planning/behavior_velocity_dynamic_obstacle_stop_module/src/object_stop_decision.cpp
planning/behavior_velocity_dynamic_obstacle_stop_module/src/object_stop_decision.hpp
planning/behavior_velocity_dynamic_obstacle_stop_module/src/scene_dynamic_obstacle_stop.cpp
planning/behavior_velocity_dynamic_obstacle_stop_module/src/scene_dynamic_obstacle_stop.hpp
planning/behavior_velocity_dynamic_obstacle_stop_module/src/types.hpp

Add a time buffer for each dynamic object to add/remove the decision to stop.
Also improve debug markers to clearly show the state of the markers of each dynamic object.
Required launch PR: https://github.com/autowarefoundation/autoware_launch/pull/933
Psim

feat(dynamic_obstacle_stop): use a time buffer for each dynamic objects

---

planning/behavior_velocity_crosswalk_module/README.md
planning/behavior_velocity_crosswalk_module/config/crosswalk.param.yaml
planning/behavior_velocity_crosswalk_module/include/behavior_velocity_crosswalk_module/util.hpp
planning/behavior_velocity_crosswalk_module/src/debug.cpp
planning/behavior_velocity_crosswalk_module/src/manager.cpp
planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp

Required launch PR: https://github.com/autowarefoundation/autoware_launch/pull/919
Psim

feat(crosswalk): ignore occlusions in the presence of traffic lights

---

control/mpc_lateral_controller/model_predictive_control_algorithm.md

Fix 2  mathjax visualization error
1)
Missing or unrecognized delimiter for \left
github-mathjax doesn't recognize 
\left\{ \}\right
https://github.com/orsharir/github-mathjax/issues/16
So I fix it as \lbrace, \rbrace.
2)
Some equation aren't output because of "\dot{u}.
So I fix it as \dot u …

docs(mpc_lateral_controller): modify mathjax visualization error

---

planning/behavior_velocity_dynamic_obstacle_stop_module/src/scene_dynamic_obstacle_stop.cpp

Refactor of the unnesessary logging information which is enabled in this https://github.com/autowarefoundation/autoware.universe/pull/6683
without this change, following output is shown in the terminal
```
[INFO 1711879593.700843163] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner.dynamic_obstacle_stop_module]: Total time = 7.00us
1711879593.7013659 [component_container_mt-30] 	preprocessing = 5.00us
1711879593.7014267 [component_container_mt-30] 	footprints = 0.00us
1711879593.7014904 [component_container_mt-30] 	collisions = 0.00us
```
with this change, the output is not shown in the teminal
The …

refactor(dynamic_obstacle_stop): change log level for processing time

---

planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/utils/debug_structs.hpp
planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/utils/markers.hpp
planning/behavior_path_lane_change_module/src/interface.cpp
planning/behavior_path_lane_change_module/src/scene.cpp
planning/behavior_path_lane_change_module/src/utils/markers.cpp

Adding additional debug marker for lane change module
- visualize current, target, backward target lanes
- visualize distances metrics
- visualize some of the reasons

feat(lane_change): additional debug markers

---

localization/ndt_scan_matcher/src/map_update_module.cpp

Since `service_ndt_align` needed to be called after startup for the map point cloud to be loaded,
there was an issue when not performing initial position estimation with NDT.
In particular, with [the PR directly passing the initial position](https://github.com/autowarefoundation/autoware.universe/pull/6692), there was an issue where the map point cloud was not being loaded.
So, I have fixed this issue.
LSim works. …

feat(ndt_scan_matcher): fix first update map

---

evaluator/perception_online_evaluator/include/perception_online_evaluator/utils/marker_utils.hpp
evaluator/perception_online_evaluator/src/perception_online_evaluator_node.cpp
evaluator/perception_online_evaluator/src/utils/marker_utils.cpp

making debug marker for each uuid objects is heavy, so unify the markers.
psim

feat(perception_online_evaluator): unify debug markers instead of separating for each object

---

evaluator/perception_online_evaluator/param/perception_online_evaluator.defaults.yaml
evaluator/perception_online_evaluator/src/metrics_calculator.cpp
evaluator/perception_online_evaluator/test/test_perception_online_evaluator_node.cpp

1. extract moving objects to check 
- predicted path deviation
- yaw deviation
- lateral deviation
because these deviation of stopped object is noisy.
yaw rate for stopped objects is checked by
https://github.com/autowarefoundation/autoware.universe/pull/6667
2. make smoothing path stable.
- psim with perception replyer
before
after
- unit test …

feat(perception_online_evaluator): extract moving object for deviation check

---

planning/behavior_path_start_planner_module/config/start_planner.param.yaml
planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/data_structs.hpp
planning/behavior_path_start_planner_module/src/manager.cpp
planning/behavior_path_start_planner_module/src/shift_pull_out.cpp

Sometimes, backwards path cropping may cause the starting point on the output path to have a big longitudinal offset between the last point of the backward path and the starting point of pull out, like here: https://evaluation.ci.tier4.jp/evaluation/reports/d982b5c4-0306-5ec0-be4d-4c0720090edb/tests/a6f3baf6-627c-5a6e-bd08-4f04dfe24559/eff3a61a-55fd-547e-b968-4acd7288a7eb/93168fc7-5735-5005-9745-465e76e192d0?project_id=prd_jt
This distance causes  problems with the planning validator when PlanningValidator::checkValidLongitudinalDistanceDeviation() is called.
This PR solves the issue by checking the distance between said points and eliminating the paths that dont comply with it. 
Note, requires launch changes: https://github.com/autowarefoundation/autoware_launch/pull/942
internal …

feat(start_planner): add validation check to prevent over cropped paths

---

planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/utils/trajectory_utils.hpp
planning/obstacle_avoidance_planner/src/mpt_optimizer.cpp
planning/obstacle_avoidance_planner/src/utils/trajectory_utils.cpp

If the reference path on the mpt_optimizer has points that are too close to each other, or are the same, calling the creation of the spline like this: 
`ref_points_spline = SplineInterpolationPoints2d(ref_points);`
generates a spline with less points than the reference path, which causes a crash in autoware when the method obstacle_avoidance_planner::MPTOptimizer::updateOrientation() is called, as it happened here: [TIER IV INTERNAL LINK](https://evaluation.tier4.jp/evaluation/reports/d8425419-b7ae-50b1-ad5e-6cc2a76f7247/tests/29422684-1dde-5fef-bb5e-61ad8e74662b/08bb5129-f242-52f7-8f82-5cac9dfb8b64/a36b3372-1789-5fcf-9647-e325df1ab847?project_id=prd_jt) 
This PR adds a sanitize function to prevent that from happening with the MPTOptimizer::calcReferencePoints method.  The sanitize …

feat(obstacle_avoidance_planner): sanitize reference points

---

launch/tier4_simulator_launch/launch/simulator.launch.xml

Fixed an issue where planning_simulator was stuck on the following pull request
* https://github.com/autowarefoundation/autoware.universe/pull/6692
planning_simulator will work

fix(pose_initializer): added "user_defined_initial_pose" to dummy localization

---

control/predicted_path_checker/src/predicted_path_checker_node/predicted_path_checker_node.cpp

Fixes: https://github.com/autowarefoundation/autoware.universe/issues/6728
https://github.com/autowarefoundation/autoware.universe/assets/32412808/daec0101-cba8-4f5d-9370-e74488741be3

fix(predicted_path_checker): check if trajectory size

---

planning/static_centerline_optimizer/include/static_centerline_optimizer/static_centerline_optimizer_node.hpp
planning/static_centerline_optimizer/package.xml
planning/static_centerline_optimizer/scripts/tmp/run.sh
planning/static_centerline_optimizer/src/static_centerline_optimizer_node.cpp

Without this PR, the lat/lon of the generated LL2 map has an issue of becoming around 0.
This PR fixes the issue by giving a correct projector to `lanelet::write` function
Test with the tmp/run.sh script.
Nothing

fix(static_centerline_optimizer): fix latlon values of generated LL2 map

---

planning/behavior_path_lane_change_module/README.md
planning/behavior_path_lane_change_module/config/lane_change.param.yaml
planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/scene.hpp
planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/utils/data_structs.hpp
planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/utils/utils.hpp
planning/behavior_path_lane_change_module/src/manager.cpp
planning/behavior_path_lane_change_module/src/scene.cpp
planning/behavior_path_lane_change_module/src/utils/utils.cpp

⚠️ Launch PR needs to be appoved first [launch#930](https://github.com/autowarefoundation/autoware_launch/pull/930)
Due to lane change is performed instantaneously after exiting from the intersection, sometimes the safety check might be a little be delayed, causes the CANCEL process to not be executed when necessary.
To avoid this issue, we have to increase the lane change safety check horizon, by also performing the safety check for the prepare phase when ego vehicle is in the intersection.
https://github.com/autowarefoundation/autoware.universe/assets/93502286/0929fd8b-3927-4e74-80ce-2f881c4f1bac
https://github.com/autowarefoundation/autoware.universe/assets/93502286/ba470bf0-04bb-425a-9dc1-926024ac24e1
None
PSIM, and rosbag.
Evaluator: TBA
None
None
None …

fix(lane_change): check prepare phase in intersection

---

planning/behavior_path_lane_change_module/src/utils/utils.cpp

When exceeding  certain distance, lane change terminal path is not generated. This PR aims  to fix this issue.
see after 0:36s
https://github.com/autowarefoundation/autoware.universe/assets/93502286/3d5b06e1-0bd4-4320-b5f7-1460ecd2eab6
https://github.com/autowarefoundation/autoware.universe/assets/93502286/734b50b5-5fba-458f-b93d-bfbf2a5213b5 …

fix(lane_change): fix terminal path not working in some case

---

planning/behavior_path_goal_planner_module/src/goal_planner_module.cpp

just delete unnecessary comments
https://github.com/autowarefoundation/autoware.universe/pull/6629

chore(goal_planner): delete unnecessary comments

---

sensing/pointcloud_preprocessor/src/time_synchronizer/time_synchronizer_nodelet.cpp

Partially fixes #6575 
In `time_synchronizer_nodelet`, It has timer cancel and reset functionalities when the input point cloud messages were not set successfully. However, if the `input_offsets` were not set as parameter, nodelet can not operate fully because of the `offset_map_.size() > 0 ` always false:
https://github.com/autowarefoundation/autoware.universe/blob/872cbddd7fea8ef7387ec514e3803a76eb69e457/sensing/pointcloud_preprocessor/src/time_synchronizer/time_synchronizer_nodelet.cpp#L527-L537
To avoid this behavior, added another code snippet to set zero offset if it was not defined.
Tested with `e2e_simulator`, behavior was not observed in #6575 while running pipeline with `time_synchronizer_nodelet`. …

feat(time_synchronizer_nodelet): set input_offsets zero if it was not defined

---

common/tier4_autoware_utils/include/tier4_autoware_utils/ros/polling_reciever.hpp
common/tier4_autoware_utils/include/tier4_autoware_utils/ros/polling_subscriber.hpp
planning/obstacle_cruise_planner/include/obstacle_cruise_planner/node.hpp
planning/obstacle_cruise_planner/src/node.cpp

change to read topic by polling instead of best_effort callback
psim test and tier4 internal tests were performed
If we access to getData() without any call of updatelatestDate() following message will be shown
[component_container_mt-31] terminate called after throwing an instance of 'std::runtime_error'
[component_container_mt-31]   what():  Bad_optional_access in class InterProcessPollingSubscriber
[component_container_mt-31] *** Aborted at 1712130709 (unix time) try "date -d @1712130709" if you are using GNU date ***
[component_container_mt-31] PC: @                0x0 (unknown)
[component_container_mt-31] *** SIGABRT (@0x3e8002983f9) received by PID 2720761 (TID 0x7fe1de7ec640) from PID 2720761; stack trace: ***
[component_container_mt-31]     @     0x7fe1d84b6046 (unknown) …

feat(tier4_autoware_utils, obstacle_cruise): change to read topic by polling

---

system/hazard_status_converter/package.xml
system/hazard_status_converter/src/converter.cpp
system/hazard_status_converter/src/converter.hpp

Ignore errors during initialization.
https://github.com/autowarefoundation/autoware.universe/blob/main/system/system_error_monitor/src/system_error_monitor_core.cpp#L177-L202
1. Disable emergency_handler and system_error_monitor
2. Launch psim
3. Launch following command in another terminal
`ros2 launch hazard_status_converter hazard_status_converter.launch.xml`
4. Launch following command in another terminal
`ros2 launch diagnostic_graph_aggregator example-main.launch.xml`
5. Change operation mode and check if SPF only in that mode
Fix to be the same behavior of previous hazard_status …

fix(hazard_status_converter): check current operation mode

---

planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/utils/utils.hpp
planning/behavior_path_lane_change_module/src/scene.cpp
planning/behavior_path_lane_change_module/src/utils/utils.cpp

Even when limiting lane changing velocity with max_velocity, the distance is still using the accelerating lane change distance.
Therefore, it is possible to get lane changing path longer than expected.
This PR aims to fix this by comparing acceleration path and max velocity path.
PSIM
Lane change path with 40km/h max velocity. The distance is further. Each lane segments is 25 meters long.
Lane change path with 40km/h max velocity. The distance is shorter compared to **Before PR**.
[TIER IV internal link](https://evaluation.tier4.jp/evaluation/reports/eb9e2c63-8ebe-5456-b2bf-658e880c6fc9?project_id=prd_jt)
The PR …

fix(lane_change): limit prepare and lane changing length

---

evaluator/perception_online_evaluator/src/metrics_calculator.cpp
evaluator/perception_online_evaluator/src/perception_online_evaluator_node.cpp

Some objects will have their orientation reversed, so ignore them from the yaw_rate.
Detection of those objects requires other metrics
drving log replayer

feat(perception_online_evaluator): ignore reversal of orientation from yaw_rate calculation

---

perception/detected_object_validation/src/obstacle_pointcloud_based_validator.cpp

Previously, object validation will be skipped when obstacle pointcloud is empty.
This PR fixes this issue.
Tickets: https://tier4.atlassian.net/jira/software/c/projects/RT1/boards/448/backlog?selectedIssue=RT1-5684&text=valida

feat(obstacle_pointcloud_based_validator_node): skip validation when obstacle pointcloud is empty

---

planning/behavior_velocity_run_out_module/config/run_out.param.yaml
planning/behavior_velocity_run_out_module/src/manager.cpp
planning/behavior_velocity_run_out_module/src/scene.cpp
planning/behavior_velocity_run_out_module/src/scene.hpp
planning/behavior_velocity_run_out_module/src/utils.hpp

When the run_out module outputs a stop point, it often causes a deceleration on the ego vehicle, but because the ego vehicle decelerates, it often happens that the initial collision target object is no longer detected as a collision candidate (because the ego vehicle slowed down and now the predicted collision using the obstacle's speed is no longer detected), which leads to the stop point promptly disappearing which can be somewhat unsafe. 
For said reasons, it is probably best to maintain the stop point/stop wall of the run out module for a certain time, every time one is issued. This PR introduces that feature. 
A parameter called "keep_stop_point_time" (default 1 second) is used to customize how long the stop wall will remain. 
Example (with keep_stop_point_time set to 10 seconds): …

feat(run_out): maintain run out stop wall

---

planning/route_handler/src/route_handler.cpp

Removed cast to int which cause overflow and exception when lanelet id is greater than int. verified that lanelet.Id is  type int64
before, exception was thrown because could  not find element with negative id :
after there is no exception 
Fix exception in case when lanelet contains larger ids (int could not handle) …

fix(route_handler): exception in route_handler caused by int overflow

---

perception/multi_object_tracker/include/multi_object_tracker/debugger.hpp
perception/multi_object_tracker/src/debugger.cpp
perception/multi_object_tracker/src/multi_object_tracker_core.cpp

The previous debugger timer refactoring caused a large error on the initial processing_timing value.
1) Initial behavior of MOT: Even if there is no object input, it was publishing latency. A conditions for timing-related publishing is added. It will check if the first message has arrived.
2) Definition of measured time: Currently, the internal processing is divided into two parts, so the total time is defined as processing_time, and the time from input to output is defined as processing_latency. …

fix(multi_object_tracker): debugger timers checks if the timer is initialized

---

planning/behavior_path_planner/src/behavior_path_planner_node.cpp

check occupancy_grid_map before running behavior_path_planner node.
https://evaluation.tier4.jp/evaluation/reports/05b6788e-9aac-56da-8989-6fe2229ff7da?project_id=prd_jt
none
none

fix(behavior_path_planner): fix behavior_path_planner node to check occupancy_grid before running

---

planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/parameter_helper.hpp
planning/behavior_path_avoidance_module/src/manager.cpp

Make it possible to update params from dynamic reconfigure.
Psim
Nothing.

fix(avoidance): add update param to use rqt reconfigure

---

common/tier4_autoware_utils/include/tier4_autoware_utils/ros/polling_subscriber.hpp

Related PR: https://github.com/autowarefoundation/autoware.universe/pull/6702
Fix following build error.
```
--- stderr: obstacle_cruise_planner                                                                                                                                                                                                                                                                                                                                                                                             
In file included from /home/satoshi/pilot-auto/src/autoware/universe/planning/obstacle_cruise_planner/include/obstacle_cruise_planner/node.hpp:24, …
```

fix(tier4_autoware_utils): fix `-Werror=unused-parameter`

---

planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/scene.hpp
planning/behavior_path_lane_change_module/src/scene.cpp
planning/behavior_path_planner/include/behavior_path_planner/behavior_path_planner_node.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner_common/include/behavior_path_planner_common/data_manager.hpp
planning/behavior_path_planner_common/include/behavior_path_planner_common/utils/path_safety_checker/safety_check.hpp
planning/behavior_path_planner_common/src/utils/path_safety_checker/safety_check.cpp

- Lane change doesn't subscribe to external velocity limiter.
- Therefore despite planning path with maximum velocity from common param[[1](https://github.com/autowarefoundation/autoware.universe/pull/6615)][[2](https://github.com/autowarefoundation/autoware.universe/pull/6734)], if user changes the maximum velocity via external velocity limiter, there will be mismatch between the path point's velocity, and the current limited velocity.
- Up until this point, when performing safety check, the path point's velocity is used to perform safety check. 
- This only happens in lane change module because it is the module that supports accelerating path at the moment. 
- However, because of the velocity mismatch, if the limited velocity is smaller than the path point's velocity, it might cause …

feat(lane_change): use external velocity limit in safety check

---

perception/multi_object_tracker/src/debugger.cpp
perception/multi_object_tracker/src/multi_object_tracker_core.cpp

In some simulation configuration, the MOT had crash.
```
[openscenario_interpreter_node-3] [multi_object_tracker-52] terminate called after throwing an instance of 'std::runtime_error'
[openscenario_interpreter_node-3] [multi_object_tracker-52]   what():  can't subtract times with different time sources [2 != 1]
[openscenario_interpreter_node-3] [multi_object_tracker-52] *** Aborted at 1712577962 (unix time) try "date -d @1712577962" if you are using GNU date ***
[openscenario_interpreter_node-3] [multi_object_tracker-52] PC: @                0x0 (unknown)
[openscenario_interpreter_node-3] [multi_object_tracker-52] *** SIGABRT (@0x3e800003010) received by PID 12304 (TID 0x7f0786116380) from PID 12304; stack trace: ***
[openscenario_interpreter_node-3] [multi_object_tracker-52]     @ …
```

fix(multi_object_tracker): mot timer bug fix

---

perception/multi_object_tracker/include/multi_object_tracker/multi_object_tracker_core.hpp
perception/multi_object_tracker/src/multi_object_tracker_core.cpp

This PR suggests a new method to reduce latency about 100 ms.
Current multi_object_tracker publishes the tracked object triggered by a timer. This timer ensures the topic is published in target frequency. The delay is compensated by predict the tracked objects motion.
However, the input (merged objects from multiple detectors) frequency is unstable (see the following plots, name of `input_latency_ms`). The instability of the detection latency is absorbed by the multi_object_tracker and adds latency about one cycle (100 ms of TIER IV configuration). 
there is two triggers to publish the tracked object
1) on measurement : When the publishing frequency is in the target window, publish right after the process is done. The publishing object will be compensated the delay from the measurement to …

feat(multi_object_tracker): reduce publish delay

---

planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/utils.hpp
planning/behavior_path_avoidance_module/src/scene.cpp
planning/behavior_path_avoidance_module/src/utils.cpp

The avoidance module couldn't create avoidance path in following situation. The module makes avoidance path for object on the ego's lane only when it's a parked vehicle. And, it assumed there is no parked vehicle on ego's lane if the lane has both right and left adjacent lane. 
On the other hand, if the right or left lane is a road shoulder lane, there is a possibility that there is parked vehicle on ego's lane. (if it is a large vehicle and the road should is narrow, maybe the vehicles position is on ego's lane.)
However, since previous avoidance module considered the road shoudler lanes as road lanes, the module didn't create avoidance path in following situation.
In this PR, I fixed the argument in order not to get adjacent road shoulder lanelet in following function.
```c++
const auto …
```

fix(avoidance): bug in the logic to judge whether it's a parked vehicle

---

planning/behavior_path_avoidance_module/src/scene.cpp

The avoidance module has two type lateral hard margin params:
1. lateral hard margin for parked vehicle
2. lateral hard margin for othther objects
Basically, it should choose proper one based on the data "if it's parked vehicle" but there are bugs that only latter param is used. This may cause wrong stop distance calculation.
```c++
double AvoidanceModule::calcDistanceToStopLine(const ObjectData & object) const
{
const auto & p = parameters_;
const auto & vehicle_width = planner_data_->parameters.vehicle_width;
...
const auto object_type = utils::getHighestProbLabel(object.object.classification);
const auto object_parameter = parameters_->object_parameters.at(object_type);
const auto avoid_margin = object_parameter.lateral_hard_margin * object.distance_factor + …
```

fix(avoidance): fix margin param inconsistency

---

planning/freespace_planning_algorithms/src/astar_search.cpp

closes https://github.com/autowarefoundation/autoware.universe/issues/5988
The freespace planner output trajectory does not connect to goal pose. It stops before reaching exact pose. Intended behavior is for `base_link` to land on goal pose after completing trajectory.
Example image of current planned trajectory not reaching goal (notice incomplete velocity profile to goal):
`lateral_goal_range: 0.5` and `longitudinal_goal_range: 2.0` search parameters are checked to decide if goal has been found in A* search algorithm (half of above values are checked). The nearest node satisfying this condition is found by astar to become the terminal node. This terminal node thus can have a maximum error of `1m` due to  `longitudinal_goal_range: 2.0` constraint. Reducing these search parameters would …

fix(freespace_planning_algorithms): fix issue of astar search planner not reaching goal pose

---

planning/behavior_path_dynamic_avoidance_module/README.md

docs(dynamic_avoidance): fix sentence

---

planning/static_centerline_optimizer/config/static_centerline_optimizer.param.yaml
planning/static_centerline_optimizer/include/static_centerline_optimizer/static_centerline_optimizer_node.hpp
planning/static_centerline_optimizer/src/static_centerline_optimizer_node.cpp

Previously, only the optimization path planning was used for the source of the centerline.
With this PR, other sources are admitted as well.
Unit test
Nothing

refactor(static_centerline_optimizer): admit I/F for other sources of  centerline

---

planning/behavior_path_avoidance_module/src/utils.cpp

The avoidance module calculates distance to drivable bound by using `tier4_autoware_utils::intersection` with following step.
1. check object offset direction based on current path. (fig: on left)
2. calculate overhang point (=p1). (fig: black point)
3. calculate offset point (=p2) based on overhang points by using `tier4_autoware_utils::calcOffsetPose`.
4. calculate intersect point (=p3) between line p1-p2 and drivable bound.
5. calculate distance (=`D`) p1 to p3.
In most case (fig: nominal case), we can find intersect by following logic. But, in edge case, we can't.
```c++
const auto p2 =
calcOffsetPose(p_tmp, 0.0, (isOnRight(object) ? 100.0 : -100.0), 0.0).position;
const auto opt_intersect =
tier4_autoware_utils::intersect(p1.second, p2, bound.at(i - 1), bound.at(i));
```
Then, there …

fix(avoidance): fix invalid road bound distance calculation

---

planning/static_centerline_optimizer/include/static_centerline_optimizer/centerline_source/bag_ego_trajectory_based_centerline.hpp
planning/static_centerline_optimizer/include/static_centerline_optimizer/centerline_source/optimization_trajectory_based_centerline.hpp
planning/static_centerline_optimizer/include/static_centerline_optimizer/static_centerline_optimizer_node.hpp
planning/static_centerline_optimizer/include/static_centerline_optimizer/utils.hpp
planning/static_centerline_optimizer/launch/static_centerline_optimizer.launch.xml
planning/static_centerline_optimizer/src/centerline_source/bag_ego_trajectory_based_centerline.cpp
planning/static_centerline_optimizer/src/centerline_source/optimization_trajectory_based_centerline.cpp
planning/static_centerline_optimizer/src/static_centerline_optimizer_node.cpp
planning/static_centerline_optimizer/src/utils.cpp

clean up the code of the static_centerline_optimizer package.
Unit test
Nothing

refactor(static_centerline_optimizer): clean up the code

---

planning/behavior_path_avoidance_module/config/avoidance.param.yaml
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/data_structs.hpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/helper.hpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/parameter_helper.hpp
planning/behavior_path_avoidance_module/schema/avoidance.schema.json
planning/behavior_path_avoidance_module/src/manager.cpp

I think we don't have to set `use_conservative_buffer_longitudinal` per object classes. Then, I added `consider_front_overhang` and `consider_rear_overhang` instead of it.
Additionally, I removed unused parameters in struct.
Psim
Nothing.

refactor(avoidance): unify redundant parameters

---

launch/tier4_perception_launch/launch/obstacle_segmentation/ground_segmentation/ground_segmentation.launch.py

- To rename `/perception/obstacle_segmentation/single_frame/pointcloud` which becomes conflict when `addition_lidars` or `ransac_input_topics` are used.
Current: 
After: 
- [TIER IV INTERNAL LINK](https://star4.slack.com/archives/C03S84LDJGG/p1712897348252399)
- Confirmed by `logging_simulator` there is no name confict:
- Left lidar is used as additional_lidars: `additional_lidars: ["left"]`
- Left lidar is used as ransac_input_topics: `ransac_input_topics: ["left"]` …

fix(ground_segmentation launch): fix topic name conflict in additional_lidars option

---

planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/pull_out_planner_base.hpp
planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/start_planner_module.hpp
planning/behavior_path_start_planner_module/src/start_planner_module.cpp

related work for https://github.com/autowarefoundation/autoware.universe/pull/6740
following variables are copied to thread local variable for thread-safety
- planner_data_
- getCurrentStatus() result
- parameters_
- isStopped() result
- `status_` (PullOutStatus)
https://github.com/autowarefoundation/autoware.universe/issues/6718
https://evaluation.tier4.jp/evaluation/reports/51d9494d-0cb2-5726-bd8e-80583125eb27?project_id=prd_jt
none
none …

feat(start_planner): fix non-thread-safe access

---

planning/behavior_path_lane_change_module/src/interface.cpp

Terminal path logic is currently causing node dying.
So this PR  will temporarily revert the function.
Once the issue is identified, it will be enabled again.

revert(lane_change): disable terminal path

---

planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/geometric_pull_over.hpp
planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/goal_planner_module.hpp
planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/goal_searcher.hpp
planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/goal_searcher_base.hpp
planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/shift_pull_over.hpp
planning/behavior_path_goal_planner_module/src/geometric_pull_over.cpp
planning/behavior_path_goal_planner_module/src/goal_planner_module.cpp
planning/behavior_path_goal_planner_module/src/goal_searcher.cpp
planning/behavior_path_goal_planner_module/src/shift_pull_over.cpp

depends https://github.com/autowarefoundation/autoware.universe/pull/6752
As described here https://github.com/autowarefoundation/autoware.universe/issues/6718, current goal_planner module is not thread-safe.
Following variables are not thread safe currently.
1. each shared point member of planner_data_ and their shared pointer members like route_handler->lanelet_map_ptr/routing_graph_ptr
2. getCurrentStatus()
3. getPreviousModuleOutput()
4. occupancy_grid_map_
5. last_previous_module_output_
6. prev_data_
7. goal_planner_data.check_collision
8. parameters_
9. ego_predicted_path_params_
10. objects_filtering_params_
11. safety_check_params_
1. PlannerData
2. getCurrentStatus()
3. getPreviousModuleOutput()
4. occupancy_grid_map_
8. parameters_
9. ego_predicted_path_params_
10. …

feat(goal_planner): fix non-thread-safe access in goal_planner

---

planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/geometric_pull_over.hpp
planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/goal_planner_module.hpp
planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/goal_searcher.hpp
planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/goal_searcher_base.hpp
planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/shift_pull_over.hpp
planning/behavior_path_goal_planner_module/src/geometric_pull_over.cpp
planning/behavior_path_goal_planner_module/src/goal_planner_module.cpp
planning/behavior_path_goal_planner_module/src/goal_searcher.cpp
planning/behavior_path_goal_planner_module/src/shift_pull_over.cpp

https://github.com/autowarefoundation/autoware.universe/pull/6740/files
none
none
none

revert(goal_planner): fix non-thread-safe access in goal_planner (#6740)

---

planning/obstacle_avoidance_planner/docs/mpt.md

Fixed the mathjax visualization error of obstacle_avoidance_planner's document.
NOTE:
The boldsymbol is replaced with mathbf which is not italic. I could not find a way to make the text bold and italic.
Nothing
Nothing

fix(obstacle_avoidance_planner): fix mathjax visualization error

---

common/tier4_autoware_utils/CMakeLists.txt
common/tier4_autoware_utils/include/tier4_autoware_utils/ros/logger_level_configure.hpp
common/tier4_autoware_utils/package.xml
common/tier4_autoware_utils/src/ros/logger_level_configure.cpp
common/tier4_logging_level_configure_rviz_plugin/config/logger_config.yaml
launch/tier4_control_launch/launch/control.launch.py
launch/tier4_control_launch/package.xml
launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.xml
launch/tier4_planning_launch/launch/scenario_planning/lane_driving/motion_planning/motion_planning.launch.xml
launch/tier4_planning_launch/launch/scenario_planning/scenario_planning.launch.xml
launch/tier4_planning_launch/package.xml
planning/mission_planner/launch/mission_planner.launch.xml

- Related PR: 
- https://github.com/autowarefoundation/autoware.universe/pull/5204
- https://github.com/autowarefoundation/autoware.universe/pull/5101
We have to send service with container name when we change output level of stand alone logger `rclcpp::get_logger`. (08ece4cde68e48fc6061de20e928bc9b3db25885) Additionally, we need to load `logging_demo::LoggerConfig` node to the target container. (3089230a7fb58ae28b2b83a6927844021b8da577)
Psim
```
$ ros2 service list | grep container_logger_configure
/control/control_validator_container/container_logger_configure/config_logger
/control/control_validator_container/container_logger_configure/describe_parameters
/control/control_validator_container/container_logger_configure/get_parameter_types …
```

feat(logger_level_configure): make it possible to change level of container logger

---

planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp

restricts to enter the IGNORE status for the objects is on the ego's path
[Screencast from 04-17-2024 08:06:50 PM.webm](https://github.com/autowarefoundation/autoware.universe/assets/141538661/0b8886c8-9418-4ee3-95c4-8107e88da200)
psim and tier4 internal tests were performed
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-requ …

feat(crosswalk): restricts to enter the IGNORE status

---

planning/obstacle_cruise_planner/config/obstacle_cruise_planner.param.yaml
planning/obstacle_cruise_planner/include/obstacle_cruise_planner/node.hpp
planning/obstacle_cruise_planner/src/node.cpp
planning/obstacle_cruise_planner/src/polygon_utils.cpp

This PR makes the stop planning ignore right beside objects.
After this PR, the stop polygons are expanded only the in front of vehicle
This PR corresponds to parameter change https://github.com/autowarefoundation/autoware_launch/pull/948 …

feat(obstacle_cruise): ignore right beside objects

---

planning/behavior_path_planner_common/src/utils/path_safety_checker/objects_filtering.cpp
planning/behavior_path_start_planner_module/src/start_planner_module.cpp

Previously, including dynamic objects present in the shoulder lane as part of the safety check led to unnecessary stops when the ego vehicle started moving. However, completely ignoring objects in the shoulder lane can result in potentially dangerous situations.
- In a recently merged separate [PR](https://github.com/autowarefoundation/autoware.universe/pull/6545), changes were made to disable the safety check functionality once the ego vehicle has entered the merging lane to a certain extent, thereby preventing unnecessary stops. 
- This approach prioritizes safety by ensuring that objects in the shoulder lane are still considered during the safety check process.
For the reasons mentioned above, this PR includes changes to incorporate objects present in the shoulder lane as part of the …

feat(behavior_path_planner_common): add safety target object located on shoulder lane

---

common/tier4_autoware_utils/CMakeLists.txt
common/tier4_autoware_utils/include/tier4_autoware_utils/ros/logger_level_configure.hpp
common/tier4_autoware_utils/package.xml
common/tier4_autoware_utils/src/ros/logger_level_configure.cpp
common/tier4_logging_level_configure_rviz_plugin/config/logger_config.yaml
launch/tier4_control_launch/launch/control.launch.py
launch/tier4_control_launch/package.xml
launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.xml
launch/tier4_planning_launch/launch/scenario_planning/lane_driving/motion_planning/motion_planning.launch.xml
launch/tier4_planning_launch/launch/scenario_planning/scenario_planning.launch.xml
launch/tier4_planning_launch/package.xml
planning/mission_planner/launch/mission_planner.launch.xml

I found we don't have to create and load LoggerLevelConfigureNode to container. Sorry for confusion.
This reverts commit 51b5f830780eb69bd1a7dfe60e295773f394fd8e.
Psim.
Nothing.

revert: "feat(logger_level_configure): make it possible to change level of container logger (#6823)"

---

sensing/pointcloud_preprocessor/src/distortion_corrector/distortion_corrector.cpp

This PR contains two changes:
1. Avoiding calling `RCLCPP_WARN_STREAM_THROTTLE` for a number of points
2. Removing unnecessary `for` loops and `rclcpp::Time` class instantiations
**`RCLCPP_WARN_STREAM_THROTTLE` takes some processing time even if it does not actually output logs**, so calling it for a number of points would take a very long time. :sob:   In practice, printing once per point cloud is sufficient, so I made that change.
The second change provides a slight speedup. In my environment (with about 300,000 points), it resulted in a maximum speedup of about **10 ms**.
---
Also, if the distortion_corrector is delayed for some reason, the following scenario occurs, which is fatal:
1. Processing is significantly delayed for some reason.
2. Twist and IMU are stored in the queue at the …

perf(pointcloud_preprocessor): prevent excessive log and speed up a bit

---

planning/behavior_path_avoidance_by_lane_change_module/src/scene.cpp
planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/scene.hpp
planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/utils/base_class.hpp
planning/behavior_path_lane_change_module/src/interface.cpp
planning/behavior_path_lane_change_module/src/scene.cpp

Small refactoring.
Make return previous output a common function.

refactor(lane_change): make return previous output a common function

---

perception/probabilistic_occupancy_grid_map/src/pointcloud_based_occupancy_grid_map/occupancy_grid_map_fixed.cpp
perception/probabilistic_occupancy_grid_map/src/pointcloud_based_occupancy_grid_map/occupancy_grid_map_projective.cpp

This PR is mainly for the multi_lidar occupancy grid map creation feature.
Previously, we need to filter obstacle pointcloud by raw one to get correct sensor fov. This filtering process yields accurate correspondence between raw and obstacle pointcloud and unignorable computation cost.
With this PR, we can roughly get similar result without that process and it means sensor fov imitation works even when `filter_obstacle_pointcloud_by_raw_pointcloud` is `false`.
Here show the sample result with front_left lidar. 
- color point: raw pc
- white point: obstacle pc
| previous | with this PR |
|--|--|
|![Screenshot from 2024-04-21 02-34-35](https://github.com/autowarefoundation/autoware.universe/assets/20086766/4ed5d558-6f55-49f1-bcfe-4cd1b7f09f8e)| ![Screenshot from 2024-04-21 …

feat(probabilistic_occupancy_grid_map): enable to create partial occupancy grid map without filter obstacle pointcloud

---

common/tier4_logging_level_configure_rviz_plugin/config/logger_config.yaml
planning/behavior_path_avoidance_module/config/avoidance.param.yaml
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/data_structs.hpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/parameter_helper.hpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/utils.hpp
planning/behavior_path_avoidance_module/schema/avoidance.schema.json
planning/behavior_path_avoidance_module/src/manager.cpp
planning/behavior_path_avoidance_module/src/scene.cpp
planning/behavior_path_avoidance_module/src/utils.cpp
planning/behavior_path_planner/config/behavior_path_planner.param.yaml
planning/behavior_path_planner/include/behavior_path_planner/planner_manager.hpp
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/src/planner_manager.cpp
planning/behavior_path_planner_common/include/behavior_path_planner_common/parameters.hpp

Now that we can change logger level dynamically by following feature.
- logging_level_configure (https://github.com/autowarefoundation/autoware.universe/pull/5112)
So, I changed several `RCLCPP_INFO` to `RCLCPP_DEBUG` and removed verbose flag in bpp.
Psim
Nothing.

refactor(bpp, avoidance): remove unnecessary verbose flag

---

launch/tier4_perception_launch/launch/perception.launch.xml
launch/tier4_simulator_launch/launch/simulator.launch.xml

add use_perception_online_evaluator option and disable it by default.
this is because currently the computational costs is high.
psim with this option true and false

feat(perception_online_evaluator): add use_perception_online_evaluator option and disable it by default

---

common/tier4_screen_capture_rviz_plugin/README.md
common/tier4_screen_capture_rviz_plugin/package.xml
common/tier4_screen_capture_rviz_plugin/src/screen_capture_panel.cpp
common/tier4_screen_capture_rviz_plugin/src/screen_capture_panel.hpp

Add new service to capture screen shot by external trigger.
I think this feature is very useful when we use it with RandomSim or AWSIM. I added client to RandomSim scenario file in order to output capture trigger so that it can record the situation as a screen shot as follow.
Ego vehicle is stuck due to the node death.
```c++
capture_video_srv_ = raw_node_->create_service<std_srvs::srv::Trigger>(
"/debug/capture/video",
std::bind(&AutowareScreenCapturePanel::onCaptureVideoTrigger, this, _1, _2));
capture_screen_shot_srv_ = raw_node_->create_service<std_srvs::srv::Trigger>(
"/debug/capture/screen_shot",
std::bind(&AutowareScreenCapturePanel::onCaptureScreenShotTrigger, this, _1, _2));
```
Psim
Nothing. …

feat(tier4_screen_capture_panel): add new service to capture screen shot

---

planning/behavior_path_planner_common/include/behavior_path_planner_common/interface/scene_module_interface.hpp

Add validation to detect empty path.
```
[component_container_mt-30]   what():  [avoidance][motion_utils] validateNonEmpty(): Points is empty.  
```
```c++
virtual BehaviorModuleOutput run()
{
updateData();
const auto output = isWaitingApproval() ? planWaitingApproval() : plan();
try {
motion_utils::validateNonEmpty(output.path.points);
} catch (const std::exception & ex) {
throw std::invalid_argument("[" + name_ + "]" + ex.what());
}
return output;
}
```
Psim.
```
[component_container_mt-30] terminate called after throwing an instance of 'std::invalid_argument' …
```

feat(bpp-interface): add empty path validation

---

planning/behavior_path_lane_change_module/src/utils/utils.cpp
planning/behavior_path_planner_common/include/behavior_path_planner_common/utils/path_safety_checker/path_safety_checker_parameters.hpp
planning/behavior_path_planner_common/src/utils/path_safety_checker/objects_filtering.cpp

Minor refactoring to simplify the initialization of Extended Predicted Object

refactor(bpp): simplify extended predicted object initialization

---

perception/image_projection_based_fusion/config/roi_pointcloud_fusion.param.yaml
perception/image_projection_based_fusion/docs/roi-pointcloud-fusion.md
perception/image_projection_based_fusion/include/image_projection_based_fusion/roi_pointcloud_fusion/node.hpp
perception/image_projection_based_fusion/include/image_projection_based_fusion/utils/utils.hpp
perception/image_projection_based_fusion/schema/roi_pointcloud_fusion.schema.json
perception/image_projection_based_fusion/src/roi_pointcloud_fusion/node.cpp
perception/image_projection_based_fusion/src/utils/utils.cpp

- This PR to add `max_cluster_size` to limit the range of objects that roi_pointcloud fusion node processes, since this node mainly focuses on small and less points unknown (traffic cones) objects which missed by Euclidean Clusters.
- Need to merge after https://github.com/autowarefoundation/autoware_launch/pull/956 is merged. …

chore(roi_pointcloud_fusion): add maximum cluster size param

---

planning/behavior_path_planner_common/src/turn_signal_decider.cpp

Improves the turn signal performances with large maps.
The performance issue was reported here first: https://github.com/orgs/autowarefoundation/discussions/4075
Psim with large map generated with https://github.com/kminoda/large_lanelet2_generator/blob/main/hilbert_curve.ipynb
- Also added a `<tag k="turn_direction" v="left" />` to all lanelet relations.
Improved performance with very long routes …

perf(behavior_path_planner_common): simplify turn signal loop to support large maps

---

perception/image_projection_based_fusion/include/image_projection_based_fusion/utils/utils.hpp
perception/image_projection_based_fusion/src/roi_pointcloud_fusion/node.cpp
perception/image_projection_based_fusion/src/utils/utils.cpp

- To process and output the clusters' pointcloud field as input topic including `intensity` field for `roi_pointcloud_fusion` node to solve the issue https://github.com/autowarefoundation/autoware.universe/issues/6785
- [TIER IV INTERNAL JIRA LINK](https://tier4.atlassian.net/browse/RT1-6035)
- Confirmed by logging_simulator that the node output cluster with intensity 
- Compare the performance on traffic cones detection by roi_pointcloud_fusion node  
|    Before    |    After    |
|  --- | ---  |
|[c94c9405-edde-4fd9-8316-91091575d839_2024-04-16-09-58-15_p0900_0_n3_roi_pointcloud_original.webm](https://github.com/autowarefoundation/autoware.universe/assets/94814556/c47f68e8-ab06-48c2-994a-5a6fd6b12785) | [c94c9405-edde-4fd9-8316-91091575d839_2024-04-16-09-58-15_p0900_0_n3_roi_pointcloud_ …

fix(image_projection_based_fusion): add intensity field for roi_pointcloud_fusion

---

planning/freespace_planning_algorithms/CMakeLists.txt
planning/freespace_planning_algorithms/README.md
planning/freespace_planning_algorithms/freespace_planning_algorithms/astar_search.py
planning/freespace_planning_algorithms/package.xml
planning/freespace_planning_algorithms/scripts/bind/astar_search_pybind.cpp
planning/freespace_planning_algorithms/scripts/example/example.py

Make the following feature into the freespace_planning_algorithms package.
- Astar search class with python
- add `setMap()` function that sets "costmap" into the Astar class
- add `makePlan()` function in the Astar class
Test with the data: settings, costmap, initial pose, and goalpose.
These data were successful in finding the goal in planning simulation with autoware.
evaluator_description: feat/freespace_astar_python
2024/03/13 https://evaluation.tier4.jp/evaluation/reports/3b522d1a-59f5-56a3-aaeb-de18be2c5042/?project_id=prd_jt
-- success to find goal by python, too.
https://evaluation.tier4.jp/evaluation/reports/d4a8a1ce-15b6-5301-95c6-23092a8dbe18?project_id=prd_jt
There is no affection in autoware by this feature. …

feat(freespace_planning_algorithms): add Astar search by python

---

launch/tier4_perception_launch/launch/traffic_light_recognition/traffic_light.launch.xml

This PR changes the traffic light recognition pipeline. 
Currently, `crosswalk_traffic_light_estimator` is launched before `traffic_light_arbiter`. This causes crosswalk traffic light estimation to work only for internal traffic signals, not for external V2X signals.
Switching their places on the launch file is proposed, so that `crosswalk_traffic_light_estimator` will be the last node on the pipeline and will work for all traffic signals including V2X.
Fixes: https://github.com/autowarefoundation/autoware.universe/issues/6878
Tested on logging simulator with a bag file.
`traffic_light_arbiter` used to output the traffic signals at the end of the pipeline as `/perception/traffic_light_recognition/traffic_signals` topic. Now, `crosswalk_traffic_light_estimator` is at the end and it outputs …

fix(tier4_perception_launch): change traffic light recognition pipeline

---

simulator/fault_injection/config/fault_injection.param.yaml
system/system_diagnostic_monitor/config/autoware-psim.yaml
system/system_diagnostic_monitor/config/localization.yaml
system/system_error_monitor/config/diagnostic_aggregator/localization.param.yaml
system/system_error_monitor/config/system_error_monitor.param.yaml
system/system_error_monitor/config/system_error_monitor.planning_simulation.param.yaml

remaked the diag of ndt scan matcher at https://github.com/autowarefoundation/autoware.universe/pull/5076,
so I renamed accordingly.
I confirmed that diag of localization works well.
The conditions for becoming warn/error have changed.
For more details, please refer to [the readme of the NDT Scan Matcher](https://github.com/autowarefoundation/autoware.universe/blob/fd147ff78de55298cd827d4e57aae5e5e851b958/localization/ndt_scan_matcher/README.md). …

feat(system diags): rename diag of ndt scan matcher

---

control/autonomous_emergency_braking/README.md
control/autonomous_emergency_braking/config/autonomous_emergency_braking.param.yaml
control/autonomous_emergency_braking/include/autonomous_emergency_braking/node.hpp
control/autonomous_emergency_braking/src/node.cpp

This PR introduces an overhaul to the autonomous_emergency_braking (AEB) module. 
1. Added Euclidean clustering to consider only groups of point clouds that are bigger than a certain size (given by cluster tolerance and min amount of point parameters).
2. The Point Cloud from sensing is cropped to only include points close to, or inside the ego predicted path.
3. A Convex hull is created around each cluster of objects. The Vertices of the hull are the points used to calculate if a collision happens or not (the vertices of the hull correspond to the most “external points”, so it really only makes sense to consider said points.
4. Only the closest Object/Vertex is evaluated for collision, (if ego evaluates that the closest point is safe, the other points will be safe too since they have, by …

feat(autonomous_emergency_braking): filter and crop aeb pointcloud

---

planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/scene.hpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/utils.hpp
planning/behavior_path_avoidance_module/src/scene.cpp
planning/behavior_path_avoidance_module/src/utils.cpp

**BACKGROUND**: Avoidance module has option to avoid ambiguous stopped vehicle in order to prevent stuck. If the object keeps stopped speed (less than `th_moving_speed`) for a certain period of time (more than `th_stopped_time`), this module create avoidance path even if it's not obvious parked vehicle.
On the other hand, basically, we can't set `th_moving_speed` to zero because there should be a perception noise. As a result, sometimes the module reacted to vehicle that is moving super slowly. And, I found it necessary to add the logic to check object moving distance.
- `th_moving_speed`: 1.0m/s
- car speed: 0.5m/s < `th_moving_speed`
https://github.com/autowarefoundation/autoware.universe/assets/44889564/563f1732-9c5c-465b-b3ff-db3e791b9e45
**BUG**: The filter to check moving distance …

fix(avoidance): fix bug in the logic to check object moving distance

---

common/autoware_auto_perception_rviz_plugin/include/autoware_auto_perception_rviz_plugin/object_detection/object_polygon_detail.hpp
common/autoware_auto_perception_rviz_plugin/include/autoware_auto_perception_rviz_plugin/object_detection/object_polygon_display_base.hpp
common/autoware_auto_perception_rviz_plugin/src/object_detection/object_polygon_detail.cpp

The detected objects are now displayed as skeletons. It is now difficult to determine if distant objects are being detected, e.g. in crowded intersections. 
I have added a visualization option to fill in the objects. In Rviz, you can toggle a flag to change the visualization.
**Set Object Fill Type to `Skeleton` (Default):**
**Set Object Fill Type to `Fill`:**
- Run psim/lsim
- Change the `Object Fill Type` to `Skeleton(Default)/FIll` and check if the visualization is changed.
None
None
Object marker will have a new option in Rviz …

chore(autoware_auto_perception_rviz_plugin): improve distant object visibility 

---

planning/behavior_path_avoidance_module/src/utils.cpp

There are two issues in the logic to judge parked vehicle.
**BUG**: Return unexpected result for vehicle on opposite lane as follow. Previously, the module used `most_right_lanelet_candidates` data only when it was road shoulder lanes. But it should use opposite lane info even when it's not road shoulder lane so that it can judge if it's parked vehicle properly in following situation.
```c++
const auto most_right_road_lanelet =
route_handler->getMostRightLanelet(object.overhang_lanelet);
const auto most_right_lanelet_candidates =
route_handler->getLaneletMapPtr()->laneletLayer.findUsages(
most_right_road_lanelet.rightBound());
lanelet::ConstLanelet most_right_lanelet = most_right_road_lanelet;
const lanelet::Attribute sub_type =
most_right_lanelet.attribute(lanelet::AttributeName::Subtype) …
```

fix(avoidance): fix logic to check if it is parked vehicle

---

planning/behavior_path_avoidance_module/config/avoidance.param.yaml
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/data_structs.hpp
planning/behavior_path_avoidance_module/schema/avoidance.schema.json
planning/behavior_path_avoidance_module/src/debug.cpp
planning/behavior_path_avoidance_module/src/utils.cpp

Related PR: https://github.com/autowarefoundation/autoware_launch/pull/974
Related ticket: https://tier4.atlassian.net/browse/RT1-5553
Previous avoidance module creates avoidance path for merging/deviating vehicle. However, sometimes it caused unnatural behavior as follow. In this situation, perception module detected ghost deviationg vehicle and module tried to avoid it with huge leteral shift length. I think the ego should stop behind of the it even if it's not perception false positive because most of the rear of the vehicle is still in Ego's lane.
In this PR, I fixed logic to check overhang distance and ignore such a vehicle.
```json
"merging_vehicle": {
"type": "object",
"properties": {
"th_overhang_distance": {
"type": "number",
"description": "Distance threshold between overhang …
```

fix(avoidance): don't avoid merging/deviating vehicle whose overhang distance is larger than threshold

---

planning/behavior_path_planner_common/include/behavior_path_planner_common/utils/path_safety_checker/safety_check.hpp
planning/behavior_path_planner_common/src/utils/path_safety_checker/safety_check.cpp

The variable is_stopped_object is of type `bool`, but for some reason, it was mistakenly written as `double`. This PR aims to fix this.

fix(bpp): change wrong function parameter's type for safety check

---

planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/parameter_helper.hpp
planning/behavior_path_avoidance_module/schema/avoidance.schema.json
planning/behavior_path_avoidance_module/src/manager.cpp

Add missing parameter declaration.
```c++
{
const std::string ns = "avoidance.target_filtering.merging_vehicle.";
p.th_overhang_distance = getOrDeclareParameter<double>(*node, ns + "th_overhang_distance");
}
```
Psim
Nothing.

fix(avoidance): add missing parameter declaration

---

system/component_state_monitor/config/topics.yaml

Similar to https://github.com/autowarefoundation/autoware.universe/pull/6563, this PR relaxes the timeout of  pose_estimator_pose. 
Related PR: https://github.com/autowarefoundation/autoware_launch/pull/979
Suppressed too much diag warning

chore(component_state_monitor): relax pose_estimator_pose timeout

---

planning/mission_planner/src/mission_planner/mission_planner.cpp
planning/mission_planner/src/mission_planner/mission_planner.hpp

Sometimes, while investigating the planning module, we might find a bug that we want to report on GitHub issues. 
However, if we didn't echo the initial and goal poses before the simulation, we might miss this information, which could cause difficulties for the ticket's assignee in reproducing the issues. 
Since log information is stored in the .ros folder, if we printed the above information, then we could just search back through the log and add the information to the ticket accurately. 
Additionally, I personally think that initial and goal poses are essential pieces of information, and it is acceptable to publish them in the terminal. 
I believe a lot of man-hours can be saved if we have this information in the terminal log.
The following information are published.
``` …
```

feat(mission_planner): publish initial and goal poses to logs

---

perception/radar_tracks_msgs_converter/src/radar_tracks_msgs_converter_node/radar_tracks_msgs_converter_node.cpp
sensing/radar_tracks_noise_filter/src/radar_tracks_noise_filter_node/radar_tracks_noise_filter_node.cpp

This is trivial changes for radar processing node to subscribe best_effort messages from newer nebula driver output.

chore(radar_track_msgs_converter): change radar tracks subscription qos to besteffort

---

planning/behavior_path_planner_common/src/utils/path_utils.cpp

This is a fix based on cppcheck warning `containerOutOfBounds`.
```
planning/behavior_path_planner_common/src/utils/path_utils.cpp:450:29: error: Out of bounds access in expression 'base_s.at(1)' because 'base_s' is empty. [containerOutOfBounds]
const double h = base_s.at(1) - base_s.at(0);
^
planning/behavior_path_planner_common/src/utils/path_utils.cpp:483:5: note: Calling function 'splineTwoPoints', 1st argument 'base_s' value is size=0
base_s, base_x, std::cos(tf2::getYaw(start_pose.orientation)),
^
planning/behavior_path_planner_common/src/utils/path_utils.cpp:450:29: note: Access out of bounds
const double h = base_s.at(1) - base_s.at(0);
^
planning/behavior_path_planner_common/src/utils/path_utils.cpp:450:44: error: Out of bounds access in expression 'base_s.at(0)' because 'base_s' …
```

fix(behavior_path_planner_common): fix warning of containerOutOfBounds

---

common/autoware_auto_common/include/autoware_auto_common/common/types.hpp

from C++ 20 char8_t is a restricted keyword:
https://en.cppreference.com/w/cpp/keyword/char8_t
Error when compiling with `-std=c++20`   

fix: do not use c++20 char8_t keyword

---

control/control_performance_analysis/src/control_performance_analysis_core.cpp

This is a bugfix based on the cppcheck warning `ignoredReturnValue`.
```
control/control_performance_analysis/src/control_performance_analysis_core.cpp:404:10: warning: Return value of function std::make_pair() is not used. [ignoredReturnValue]
std::make_pair(false, interp_point.pose);
^
```
It means that the value of `std::make_pair(false, interp_point.pose)` was ignored.
And it seems it should be used as a return value of `calculateClosestPose`. …

fix(control_performance_analysis): fix bug of ignoredReturnValue

---

evaluator/perception_online_evaluator/src/metrics/detection_count.cpp

This is a fix based on cppcheck warning `constStatement`.
```
evaluator/perception_online_evaluator/src/metrics/detection_count.cpp:71:39: warning: Redundant code: Found unused member access. [constStatement]
unique_timestamps_.insert(timestamp).second;
^
evaluator/perception_online_evaluator/src/metrics/detection_count.cpp:122:50: warning: Redundant code: Found unused member access. [constStatement]
seen_uuids_[classification][range].insert(uuid).second;
^
```
It means that the return values are not used even though `.second` returns `bool`.
And it seems they should be deleted.
After …

fix(perception_online_evaluator): fix bug of constStatement

---

common/tier4_logging_level_configure_rviz_plugin/config/logger_config.yaml
planning/behavior_path_planner_common/include/behavior_path_planner_common/utils/path_shifter/path_shifter.hpp
planning/behavior_path_planner_common/src/utils/path_shifter/path_shifter.cpp

Clean up clang-tidy a little bit.
- added path shifter into logging level configuration.
- I didn't change function names to snake case.
- There are some variables that i think are better if we leave as is.

refactor(bpp): path shifter clang tidy and logging level configuration

---

perception/occupancy_grid_map_outlier_filter/include/occupancy_grid_map_outlier_filter/occupancy_grid_map_outlier_filter_nodelet.hpp
perception/occupancy_grid_map_outlier_filter/src/occupancy_grid_map_outlier_filter_nodelet.cpp

- To add intensity field for `occupancy_grid_map_outlier_filter` to solve the issue https://github.com/autowarefoundation/autoware.universe/issues/6785
- This PR will avoid fixed pointcloud type like pcl::PointXYZ or pcl::PointXYZI. 
- Almost of all calculations are replaced and done directly in Pointcloud2 except kd_tree_->radiusSearch. So that the pointcloud type will be coppied through the node by reference `point_step` of input topic so that the pointcloud type which is processed and output depends and is the same as input pointcloud type. 
- [TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT1-5980)
- Releated PR: https://github.com/autowarefoundation/autoware.universe/pull/6791
Confirmed by logging_simulator that the intensity is added into the current empty padding fiedl …

fix(occupancy_grid_map_outlier_filter): add intensity field

---

planning/behavior_velocity_crosswalk_module/config/crosswalk.param.yaml
planning/behavior_velocity_crosswalk_module/src/manager.cpp
planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp

Parameter update to follow the change of significance by https://github.com/autowarefoundation/autoware.universe/pull/6033
[Screencast from 04-30-2024 09:16:56 AM.webm](https://github.com/autowarefoundation/autoware.universe/assets/141538661/bc04896b-d5b0-4225-8185-3b083d79573f)
launch PR: https://github.com/autowarefoundation/autoware_launch/pull/977
[pull …

feat(crosswalk)!: change ego min assumed speed

---

planning/behavior_path_avoidance_by_lane_change_module/src/scene.cpp
planning/behavior_path_goal_planner_module/src/util.cpp
planning/behavior_path_lane_change_module/README.md
planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/scene.hpp
planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/utils/data_structs.hpp
planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/utils/debug_structs.hpp
planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/utils/utils.hpp
planning/behavior_path_lane_change_module/src/scene.cpp
planning/behavior_path_lane_change_module/src/utils/utils.cpp
planning/behavior_path_planner_common/include/behavior_path_planner_common/utils/path_safety_checker/objects_filtering.hpp
planning/behavior_path_planner_common/include/behavior_path_planner_common/utils/path_safety_checker/safety_check.hpp
planning/behavior_path_planner_common/include/behavior_path_planner_common/utils/utils.hpp
planning/behavior_path_planner_common/src/utils/path_safety_checker/objects_filtering.cpp
planning/behavior_path_planner_common/src/utils/path_safety_checker/safety_check.cpp
planning/behavior_path_planner_common/src/utils/utils.cpp
planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/pull_out_planner_base.hpp
planning/behavior_path_start_planner_module/src/start_planner_module.cpp

Lane change object filters checks for object's arc length from ego, and this time consuming process might be resource extensive if the number of object is huge. 
To avoid this issue, the object filtering in lane change is improve, by first performing rough checks, by checking object current location and speed, and then remove if it is not fulfill the requirement.
The following will be the new logic for the object filtering
[TIER IV Internal Link](https://tier4.atlassian.net/browse/RT0-31074)
[TIER IV Internal link](https://evaluation.tier4.jp/evaluation/reports/e9c1a608-f60a-5ff9-9577-e93481afdf80?project_id=prd_jt)
None
None
None
The PR author …

perf(lane_change): rework object filter

---

planning/behavior_path_lane_change_module/src/scene.cpp

For scenario simulator.
Lane change safety checks are still performed even though the collision check object list is empty.

fix(lane_change): return safe is object list is empty

---

system/diagnostic_graph_aggregator/src/common/graph/config.cpp

Close #6928
Fixed a bug where unit links were incorrectly updated. https://github.com/autowarefoundation/autoware.universe/issues/6928
Not applicable (the iterator is invalidated by assignment, but it works in my environment, so I didn't add any code to detect it.).
None
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request- …

fix(diagnostic_graph_aggregator): fix a bug where unit links were incorrectly updated

---

control/autonomous_emergency_braking/README.md
control/autonomous_emergency_braking/config/autonomous_emergency_braking.param.yaml
control/autonomous_emergency_braking/include/autonomous_emergency_braking/node.hpp
control/autonomous_emergency_braking/src/node.cpp

This PR introduces obstacle velocity estimation to the AEB module. 
Currently, the AEB module uses RSS distance to determine if a collision between ego and the obstacle will collide or not, but the object speed is set to 0 by default. This sometimes causes the ego vehicle to issue a stop when it gets close to an object in front that is moving forward.
This PR uses detected object history and the change of object position between point cloud frames to calculate the object's velocity along the ego path's longitudinal axis. Furthermore the velocity is added to a queue of "object velocities" and the median value is chosen as the current object speed (That is done to account for possible jumps of velocity due to false detection).
This calculation is necessary to correctly compute the RSS …

feat(autonomous_emergency_braking): add obstacle velocity estimation for AEB

---

planning/behavior_path_start_planner_module/src/start_planner_module.cpp

Related to this ticket: [TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT1-6090)
on Autoware, the start planner has a check that lets it ignore rear vehicles if the gap between the ego and its merging lane is not big enough to let the rear vehicle pass through, this is done on the isPreventingRearVehicleFromPassingThrough() function. 
However, there are situations where the function isPreventingRearVehicleFromPassingThrough() does not consider objects that are not directly behind the ego vehicle but that have a predicted path that goes through the ego path. In said cases isPreventingRearVehicleFromPassingThrough() will return false because it does not detect an object behind ego (this is for safety) but then the dynamic  obstacle collision check will detect the object an issue …

feat(start_planner): add centerline crossing check

---

perception/ground_segmentation/src/scan_ground_filter_nodelet.cpp

This is a fix based on cppcheck warning `identicalConditionAfterEarlyExit`.
```
perception/ground_segmentation/src/scan_ground_filter_nodelet.cpp:398:65: warning: Identical condition '!initialized_first_gnd_grid', second condition is always false [identicalConditionAfterEarlyExit]
if (prev_list_init == false && initialized_first_gnd_grid == false) {
^
perception/ground_segmentation/src/scan_ground_filter_nodelet.cpp:386:11: note: If condition '!initialized_first_gnd_grid' is true, the function will return/exit
if (!initialized_first_gnd_grid) {
^
perception/ground_segmentation/src/scan_ground_filter_nodelet.cpp:398:65: note: Testing identical condition '!initialized_first_gnd_grid'
if (prev_list_init == false && initialized_first_gnd_grid == false) {
^
```
It means that the program early …

fix(ground_segmentation): fix warning of identicalConditionAfterEarlyExit

---

launch/tier4_perception_launch/launch/object_recognition/detection/pointcloud_map_filter.launch.py
sensing/pointcloud_preprocessor/include/pointcloud_preprocessor/downsample_filter/faster_voxel_grid_downsample_filter.hpp
sensing/pointcloud_preprocessor/src/downsample_filter/faster_voxel_grid_downsample_filter.cpp

- To process and output the intensity field for `voxel_grid_downsample_filter` to solve the issue https://github.com/autowarefoundation/autoware.universe/issues/6785
- As internal discuss, this PR will assign intensity for centroid pointcloud by using the average intensity of the points inside the voxel.
- [TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT1-6007)
- Confirmed by logging_simulator that `pointcloud_map_filtered/downsampled/pointcloud` node is able to output pointcloud with intensity within 16bytes …

fix(voxel_grid_downsample_filter): add intensity field

---

planning/behavior_path_goal_planner_module/src/goal_planner_module.cpp
planning/behavior_path_goal_planner_module/src/util.cpp
planning/behavior_path_planner_common/src/utils/path_safety_checker/objects_filtering.cpp
planning/behavior_path_planner_common/src/utils/path_utils.cpp
planning/behavior_path_planner_common/src/utils/utils.cpp
planning/behavior_path_start_planner_module/src/util.cpp
planning/route_handler/include/route_handler/route_handler.hpp
planning/route_handler/src/route_handler.cpp
planning/static_centerline_generator/src/static_centerline_generator_node.cpp

Currently, some functions are performing queries on ALL shoulder or road lanelets of the map.
With very large maps, this leads to performance issues which are solved by this PR.
Evaluator (TIER IV INTERNAL LINK): https://evaluation.tier4.jp/evaluation/reports/7a9c88f8-9724-57ba-a7cf-568b385f18f6?project_id=prd_jt …

perf(route_handler): simplify queries on the road and shoulder lanelets

---

planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/interface.hpp
planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/scene.hpp
planning/behavior_path_lane_change_module/include/behavior_path_lane_change_module/utils/base_class.hpp
planning/behavior_path_lane_change_module/src/interface.cpp
planning/behavior_path_lane_change_module/src/scene.cpp

Refactoring getCurrentTurnSignalInfo function.
Originally it was in interface, but this function seems to be more related to lane change implementation, so it is moved to scene.cpp file.

refactor(lane_change): move getCurrentTurnSignalInfo to scene file

---

planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/data_structs.hpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/debug.hpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/helper.hpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/scene.hpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/shift_line_generator.hpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/type_alias.hpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/utils.hpp
planning/behavior_path_avoidance_module/src/debug.cpp
planning/behavior_path_avoidance_module/src/scene.cpp
planning/behavior_path_avoidance_module/src/shift_line_generator.cpp
planning/behavior_path_avoidance_module/src/utils.cpp

Organize alias for types and functions which are often used.
```c++
namespace behavior_path_planner
{
// auto msgs
using autoware_auto_perception_msgs::msg::PredictedObject;
using autoware_auto_perception_msgs::msg::PredictedPath;
using autoware_auto_planning_msgs::msg::PathWithLaneId;
// ROS 2 general msgs
using geometry_msgs::msg::Point;
using geometry_msgs::msg::Pose;
using geometry_msgs::msg::TransformStamped;
using geometry_msgs::msg::Vector3;
using std_msgs::msg::ColorRGBA;
using visualization_msgs::msg::Marker;
using visualization_msgs::msg::MarkerArray;
// tier4 msgs
using tier4_planning_msgs::msg::AvoidanceDebugMsg;
using tier4_planning_msgs::msg::AvoidanceDebugMsgArray;
// tier4 utils functions
using tier4_autoware_utils::appendMarkerArray;
using …
```

refactor(avoidance): organize alias

---

common/tvm_utility/example/yolo_v2_tiny/main.cpp

This is a fix based on cppcheck warning `negativeContainerIndex`.
```
common/tvm_utility/example/yolo_v2_tiny/main.cpp:213:28: warning: Array index -1 is out of bounds. [negativeContainerIndex]
auto max_score = class_probabilities[max_ind] * p_0 / p_total;
^
common/tvm_utility/example/yolo_v2_tiny/main.cpp:194:26: note: Assignment 'max_ind=-1', assigned value is -1
int max_ind = -1;
^
common/tvm_utility/example/yolo_v2_tiny/main.cpp:195:44: note: Assuming condition is false
for (size_t i_class = 0; i_class < n_classes; i_class++) {
^
common/tvm_utility/example/yolo_v2_tiny/main.cpp:213:28: note: Negative array index
auto max_score = class_probabilities[max_ind] * p_0 / p_total;
^
```
It means that `class_probabilities[max_ind]` will cause out of bounds array access, if `max_ind` is not …

fix(tvm_utility): fix warning of negativeContainerIndex

---

localization/yabloc/yabloc_pose_initializer/src/camera/projector_module.cpp

This is a fix based on cppcheck warning `iterateByValue`.
```
localization/yabloc/yabloc_pose_initializer/src/camera/projector_module.cpp:53:15: performance: Range variable 'contour' should be declared as const reference. [iterateByValue]
for (auto contour : contours) {
^
```
If you have any problem with const references, please close this PR without merging.
No …

perf(yabloc): fix performance warning of iterateByValue

---

launch/tier4_perception_launch/launch/object_recognition/detection/detector/camera_lidar_detector.launch.xml
launch/tier4_perception_launch/launch/perception.launch.xml
perception/raindrop_cluster_filter/CMakeLists.txt
perception/raindrop_cluster_filter/config/low_intensity_cluster_filter.param.yaml
perception/raindrop_cluster_filter/include/raindrop_cluster_filter/low_intensity_cluster_filter/low_intensity_cluster_filter.hpp
perception/raindrop_cluster_filter/launch/low_intensity_cluster_filter.launch.xml
perception/raindrop_cluster_filter/package.xml
perception/raindrop_cluster_filter/raindrop_cluster_filter.md
perception/raindrop_cluster_filter/src/low_intensity_cluster_filter.cpp

- This PR to add a new node called `low_intensity_cluster_filter` which mainly focus on filtering known objects with very low intensity pointcloud such as raindrop or water splash to solve issue: https://github.com/autowarefoundation/autoware.universe/issues/6785 
[TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT1-6030)
- I have tested on [internal rosbag](https://console.data-search.tier4.jp/projects/prd_jt/environments/559b0634-c871-40e6-876e-0c57b20f7fe1/rosbags/c8a0b111-8b67-4a51-a27b-2773b6f19954) and confirmed by `logging_simulator` and `perception_online_evaluator` tool that the unknown objects number in `/perception/object_recognition/objects` has been decreased. 
| Before | After | 
| -- | -- |
Red Unknown Polygon: Before change
White Unknown Polygon: After change …

feat: add low_intensity_cluster_filter

---

perception/traffic_light_classifier/src/cnn_classifier.cpp

This is a fix based on cppcheck warning `uninitvar`.
```
perception/traffic_light_classifier/src/cnn_classifier.cpp:130:51: warning: Uninitialized variable: probability [uninitvar]
std::string text = label + " " + std::to_string(probability);
^
perception/traffic_light_classifier/src/cnn_classifier.cpp:113:29: note: Assuming condition is false
for (std::size_t i = 0; i < traffic_signal.elements.size(); i++) {
^
perception/traffic_light_classifier/src/cnn_classifier.cpp:130:51: note: Uninitialized variable: probability
std::string text = label + " " + std::to_string(probability);
^
```
When the argument `traffic_signal` is empty, the `probability` will not be initialized. …

fix(traffic_light_classifier): fix warning of uninitvar

---

build_depends.repos

Add glog for build_depends.repos in universe.
Examples for use: https://github.com/autowarefoundation/autoware.universe/pull/6792
https://github.com/autowarefoundation/autoware.universe/pull/6792
Run ci & build in local.
This will add glog with v0.6.0
None
None
None
This will add glog with v0.6.0 in CI
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributi …

feat(build_depends): add glog-vendor

---

planning/behavior_path_goal_planner_module/src/shift_pull_over.cpp

currently the z height of shifted path is ignored
this scenario 
https://evaluation.tier4.jp/evaluation/reports/7176a79c-e86f-5c51-a4f9-c540f26bc201/tests/118f7554-b829-5b59-a447-2c4cc3df9bdf/d353d3e8-f86e-52b3-8cab-6b0cc855e832/1dc1b0e9-fd19-5cde-a7f1-79053bb2e8d6?project_id=prd_jt&state=failed
none
none …

feat(goal_planner): align z-height of road_shoulder

---

common/glog_component/CMakeLists.txt
common/glog_component/package.xml
common/glog_component/src/glog_component.cpp
evaluator/perception_online_evaluator/CMakeLists.txt
evaluator/perception_online_evaluator/package.xml
evaluator/perception_online_evaluator/src/perception_online_evaluator_node.cpp
localization/ndt_scan_matcher/package.xml
localization/ndt_scan_matcher/src/ndt_scan_matcher_node.cpp
localization/pose_estimator_arbiter/package.xml
localization/pose_estimator_arbiter/src/pose_estimator_arbiter/pose_estimator_arbiter_node.cpp
localization/yabloc/yabloc_common/package.xml
localization/yabloc/yabloc_common/src/ground_server/ground_server_node.cpp
localization/yabloc/yabloc_particle_filter/src/camera_corrector/camera_particle_corrector_node.cpp
perception/map_based_prediction/package.xml
perception/map_based_prediction/src/map_based_prediction_node.cpp
perception/multi_object_tracker/CMakeLists.txt
perception/multi_object_tracker/package.xml
perception/multi_object_tracker/src/multi_object_tracker_node.cpp
perception/radar_object_tracker/package.xml
perception/radar_object_tracker/src/radar_object_tracker_node/radar_object_tracker_node.cpp
perception/tracking_object_merger/package.xml
perception/tracking_object_merger/src/decorative_tracker_merger.cpp

Add `IsGoogleLoggingInitialized()` check before glog initialization as the multiple initializations terminate the process.
Must be merged after
- https://github.com/autowarefoundation/autoware/pull/4614
- https://github.com/autowarefoundation/autoware.universe/pull/6952
- Build 
- Run psim
- Confirm the glog works correctly as before
- `kill -15 <pid>` should show the stack trace for the glog-installed process, e.g. `map_based_prediction`
None
None
None …

chore(glog): add initialization check

---

perception/image_projection_based_fusion/include/image_projection_based_fusion/roi_detected_object_fusion/node.hpp
perception/image_projection_based_fusion/include/image_projection_based_fusion/roi_pointcloud_fusion/node.hpp
perception/image_projection_based_fusion/include/image_projection_based_fusion/segmentation_pointcloud_fusion/node.hpp
perception/image_projection_based_fusion/include/image_projection_based_fusion/utils/utils.hpp
perception/image_projection_based_fusion/package.xml
perception/image_projection_based_fusion/src/pointpainting_fusion/node.cpp
perception/image_projection_based_fusion/src/roi_cluster_fusion/node.cpp
perception/image_projection_based_fusion/src/roi_detected_object_fusion/node.cpp
perception/image_projection_based_fusion/src/roi_pointcloud_fusion/node.cpp
perception/image_projection_based_fusion/src/segmentation_pointcloud_fusion/node.cpp
perception/image_projection_based_fusion/src/utils/utils.cpp

Reverts autowarefoundation/autoware.universe#6902 because sometime pointpainting node is crashed

feat(image projection based fusion): revert #6902 (unrecify 3d point for image projection based fusion)

---

system/system_monitor/src/net_monitor/net_monitor.cpp

This is a fix based on cppcheck warning `containerOutOfBounds`.
```
system/system_monitor/src/net_monitor/net_monitor.cpp:262:69: warning: Either the condition 'list.size()>=3' is redundant or size of 'list' can be 3. Expression 'list[3]' causes access out of bounds. [containerOutOfBounds]
status.add(fmt::format("nethogs {}: program", index), list[3].c_str());
^
system/system_monitor/src/net_monitor/net_monitor.cpp:261:25: note: Assuming that condition 'list.size()>=3' is not redundant
if (list.size() >= 3) {
^
system/system_monitor/src/net_monitor/net_monitor.cpp:262:69: note: Access out of bounds
status.add(fmt::format("nethogs {}: program", index), list[3].c_str());
^
``` …

fix(system_monitor): fix warning of containerOutOfBounds

---

planning/behavior_path_planner/include/behavior_path_planner/planner_manager.hpp
planning/behavior_path_planner/src/planner_manager.cpp
planning/behavior_path_planner_common/include/behavior_path_planner_common/interface/scene_module_interface.hpp
planning/behavior_path_planner_common/include/behavior_path_planner_common/interface/scene_module_manager_interface.hpp

Before: Since the publisher was in scene module interface, it stopped publishing rtc cooperate status when scene module was killed by planner manager.
**After: It keeps publishing rtc cooperate status even after scene module is killed. In this case, it publishes empty cooperate status. (See following movie.)**
https://github.com/autowarefoundation/autoware.universe/assets/44889564/8a5762c5-560c-466e-b6ee-b48922c95e44
Keep publishing rtc cooperate status. …

fix(bpp): keep publishing rtc cooperate status

---

perception/map_based_prediction/config/map_based_prediction.param.yaml
perception/map_based_prediction/include/map_based_prediction/map_based_prediction_node.hpp
perception/map_based_prediction/include/map_based_prediction/path_generator.hpp
perception/map_based_prediction/schema/map_based_prediction.schema.json
perception/map_based_prediction/src/map_based_prediction_node.cpp
perception/map_based_prediction/src/path_generator.cpp

use different time horizon for vehicle, pedestrian, unknow.
https://github.com/autowarefoundation/autoware_launch/pull/967
https://tier4.atlassian.net/browse/RT1-5447
https://evaluation.tier4.jp/evaluation/reports/02aeaa59-9278-5e31-ad5d-922d46fcf123?project_id=prd_jt
none
none
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guideline …

feat(map_based_prediction): use different time horizon

---

perception/map_based_prediction/src/map_based_prediction_node.cpp
perception/map_based_prediction/src/path_generator.cpp

Improving pedestrian path generation efficiency.
There was an issue that the prediction module had performance drop when many pedestrians were cross a crosswalk.
This PR is to remove unnecessary process repeats for efficiency.
[TIER IV INTERNAL](https://tier4.atlassian.net/browse/RT0-30941)
Also,this PR contains fix about invalid memory access.
Tested under Tier 4 replay environment.
https://github.com/autowarefoundation/autoware.universe/assets/42434141/b490f547-65a3-48d4-966c-5f43d853a4b0
A small performance improvement.
This PR do not completely solve the performance drop issue. It need to be improved further.
N/A …

fix(map_based_prediction): improve pedestrian path generation efficiency

---

planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/geometric_pull_over.hpp
planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/goal_planner_module.hpp
planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/goal_searcher.hpp
planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/goal_searcher_base.hpp
planning/behavior_path_goal_planner_module/include/behavior_path_goal_planner_module/shift_pull_over.hpp
planning/behavior_path_goal_planner_module/src/geometric_pull_over.cpp
planning/behavior_path_goal_planner_module/src/goal_planner_module.cpp
planning/behavior_path_goal_planner_module/src/goal_searcher.cpp
planning/behavior_path_goal_planner_module/src/shift_pull_over.cpp

modified PR of this https://github.com/autowarefoundation/autoware.universe/pull/6740
https://github.com/autowarefoundation/autoware.universe/pull/6740
see https://github.com/autowarefoundation/autoware.universe/pull/6740
none
none
none
none

feat(goal_planner): fix non-thread-safe access in goal_planner (revert of #6809 and minor fix)

---

control/autonomous_emergency_braking/include/autonomous_emergency_braking/node.hpp
control/autonomous_emergency_braking/src/node.cpp

Add param update support (ie. rqt reconfigure) for the AEB module.
Note that the aeb_hz is not included on the paramUpdate list since it is directly linked to a Timer and I am not quite sure if is is possible to reset the timer like this: 
`  {
// start time
double aeb_hz{0.0};
const bool is_aeb_hz_updated = updateParam<double>(parameters, "aeb_hz", aeb_hz);
if (is_aeb_hz_updated) {
const auto period_ns = rclcpp::Rate(aeb_hz).period();
timer_.reset();
timer_ =
rclcpp::create_timer(this, this->get_clock(), period_ns, std::bind(&AEB::onTimer, this));
}
}`
Without it causing troubles? 
PSim + rqt_reconfigure …

feat(autonomous_emergency_braking): add param update support for AEB

---

control/autonomous_emergency_braking/include/autonomous_emergency_braking/node.hpp

std::remove_if does not directly remove the objects from the container, so old velocities might still remain after the timeout has passed, it is necessary to call erase too as parth of the [erase-remove idiom](https://en.wikipedia.org/wiki/Erase%E2%80%93remove_idiom). Also, it is not necessary to delete history if a speed cannot be calculated. This PR fixes those issues.
PSim …

fix(autonomous_emergency_braking): add missing erase to velocity history

---

system/component_state_monitor/config/topics.yaml

To monitor the health of the NDT,
it is not appropriate to monitor `/localizaiton/pose_estimator/pose_with_covariance` , and it often leads to false detections. Therefore, I will remove this monitoring.
If NDT health monitoring is still necessary, I will consider alternative methods.
LSim works.
N/A
N/A
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contribut …

fix(componet_state_monitor): remove ndt node alive monitoring

---

perception/map_based_prediction/config/map_based_prediction.param.yaml
perception/map_based_prediction/include/map_based_prediction/map_based_prediction_node.hpp
perception/map_based_prediction/include/map_based_prediction/path_generator.hpp
perception/map_based_prediction/schema/map_based_prediction.schema.json
perception/map_based_prediction/src/map_based_prediction_node.cpp
perception/map_based_prediction/src/path_generator.cpp

This reverts commit d5aa5d61c5d346aa97ea12065dd75a6f7b1e6b5c.

fix(map_based_prediction): revert use different time horizon (#6877)

---

common/autoware_overlay_rviz_plugin/autoware_overlay_rviz_plugin/include/turn_signals_display.hpp
common/autoware_overlay_rviz_plugin/autoware_overlay_rviz_plugin/src/gear_display.cpp
common/autoware_overlay_rviz_plugin/autoware_overlay_rviz_plugin/src/signal_display.cpp
common/autoware_overlay_rviz_plugin/autoware_overlay_rviz_plugin/src/speed_display.cpp
common/autoware_overlay_rviz_plugin/autoware_overlay_rviz_plugin/src/speed_limit_display.cpp
common/autoware_overlay_rviz_plugin/autoware_overlay_rviz_plugin/src/steering_wheel_display.cpp
common/autoware_overlay_rviz_plugin/autoware_overlay_rviz_plugin/src/traffic_display.cpp
common/autoware_overlay_rviz_plugin/autoware_overlay_rviz_plugin/src/turn_signals_display.cpp

**Merge with:**
- https://github.com/autowarefoundation/autoware_launch/pull/982
**Part of:**
- https://github.com/autowarefoundation/autoware.universe/issues/6882
Design Update of the RVIZ2 Autoware Overlay 

feat: update rviz2 overlay

---

planning/behavior_path_side_shift_module/include/behavior_path_side_shift_module/scene.hpp
planning/behavior_path_side_shift_module/src/scene.cpp

Fix https://github.com/autowarefoundation/autoware.universe/issues/6554
Psim
Evaluator (TIER IV INTERNAL LINK): https://evaluation.tier4.jp/evaluation/reports/2df90fa5-bb82-5846-bbbe-735a6a541c0e?project_id=prd_jt

perf(side_shift): fix unupdated prev path that caused heavy interpolation

---

planning/mission_planner/src/mission_planner/mission_planner.cpp

This is a fix based on CppCheck warning
```
planning/mission_planner/src/mission_planner/mission_planner.cpp:253:18: style: Condition 'is_reroute' is always true [knownConditionTrueFalse]
change_state(is_reroute ? RouteState::SET : RouteState::UNSET);
^
planning/mission_planner/src/mission_planner/mission_planner.cpp:251:7: note: Assuming that condition 'is_reroute' is not redundant
if (is_reroute && !check_reroute_safety(*current_route_, route)) {
^
planning/mission_planner/src/mission_planner/mission_planner.cpp:253:18: note: Condition 'is_reroute' is always true
change_state(is_reroute ? RouteState::SET : RouteState::UNSET);
^
planning/mission_planner/src/mission_planner/mission_planner.cpp:301:18: style: Condition 'is_reroute' is always true [knownConditionTrueFalse] …
```

refactor(mission_planner): remove redundant `is_reroute` check

---

planning/behavior_path_avoidance_by_lane_change_module/src/interface.cpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/scene.hpp
planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/type_alias.hpp
planning/behavior_path_planner_common/include/behavior_path_planner_common/interface/scene_module_interface.hpp
planning/behavior_velocity_blind_spot_module/src/manager.cpp
planning/behavior_velocity_crosswalk_module/src/manager.cpp
planning/behavior_velocity_detection_area_module/src/manager.cpp
planning/behavior_velocity_intersection_module/src/manager.cpp
planning/behavior_velocity_no_stopping_area_module/src/manager.cpp
planning/behavior_velocity_planner_common/include/behavior_velocity_planner_common/scene_module_interface.hpp
planning/behavior_velocity_planner_common/src/scene_module_interface.cpp
planning/behavior_velocity_traffic_light_module/src/manager.cpp
planning/rtc_interface/include/rtc_interface/rtc_interface.hpp
planning/rtc_interface/src/rtc_interface.cpp

I added new field to `tier4_rtc_msgs/CooperateStatus` msgs.
https://github.com/tier4/tier4_autoware_msgs/pull/119
Please update `tier4_autoware_msgs` to latest one including https://github.com/tier4/tier4_autoware_msgs/pull/119.
Update rtc cooperate status msg type in https://github.com/tier4/tier4_autoware_msgs/pull/119. …

feat(rtc_interface)!: add new field to rtc cooperate status

---

planning/behavior_velocity_run_out_module/src/debug.cpp
planning/behavior_velocity_run_out_module/src/debug.hpp

This is a fix based on CppCheck warning
```
planning/behavior_velocity_run_out_module/src/debug.cpp:74:14: warning: Member variable 'RunOutDebug::accel_reason_' is not initialized in the constructor. [uninitMemberVar]
RunOutDebug::RunOutDebug(rclcpp::Node & node) : node_(node)
^
```
As the warning shows, the variable `accel_reason_` could be used in `publishDebugValue()` without being initialized.
I added `UNKNOWN` to `AccelReason` enum class, but if you consider somthing better, I would appreciate it.
No …

fix(behavior_velocity_run_out_module): initialize `accel_reason_`

---

vehicle/accel_brake_map_calibrator/src/accel_brake_map_calibrator_node.cpp

I have fixed accel_brake_map_calibrator not to output invalid maps.
( 
In particular, in previous implementations, there were cases where an invalid map would be outputted when the values of adjacent elements in the map were very close. I have fixed this issue. )
(TIERIV Internal Link) https://tier4.atlassian.net/browse/RT0-31507
Before:
An accel_brake_map_calibrator output invalid accel_map.csv
Output:
> default,0,0.1,0.572158,1.04432,1.51647,1.98863,2.46079,2.93295,3.40511,3.87726,4.34942,4.82158,5.29374,5.76589,6.23805,6.71021,7.18237,7.65453,8.12668,8.59884,9.071
0,-0.13,-0.129,-0.163,-0.163,-0.165,-0.201,-0.227,-0.283,-0.333,-0.411,-0.465,-0.498,-0.499,-0.5,-0.553,-0.58,-0.581,-0.582,-0.583,-0.584,-0.585
0.001,-0.129,-0.128,-0.162,-0.162,-0.164,-0.2,-0.226,-0.282,-0.332,-0.41,-0.464,- …

fix(accel_brake_map_calibrator): fix accel_brake_map_calibrator not to output invalid maps

---

system/mrm_emergency_stop_operator/include/mrm_emergency_stop_operator/mrm_emergency_stop_operator_core.hpp
system/mrm_emergency_stop_operator/package.xml
system/mrm_emergency_stop_operator/src/mrm_emergency_stop_operator/mrm_emergency_stop_operator_core.cpp

Add support for updating mrm emergency stop with rqt_reconfigure. Also added the vector include requested by pre-commit.
PSim
Using the AEB module to test the changes, I lowered the min jerk and acceleration and the ego cannot stop reasonably fast (as expected), see video:
https://github.com/autowarefoundation/autoware.universe/assets/25967964/42eebb30-b953-41ff-84d6-91156f744b41 …

feat(mrm_emergency_stop_operator): add support for real time param reconfigure for mrm_emergency_stop

---

planning/behavior_velocity_out_of_lane_module/config/out_of_lane.param.yaml
planning/behavior_velocity_out_of_lane_module/src/lanelets_selection.cpp
planning/behavior_velocity_out_of_lane_module/src/manager.cpp
planning/behavior_velocity_out_of_lane_module/src/types.hpp

Add an option to ignore all lanelets adjacent to the path lanelets where a lane change is possible. This prevents the `out_of_lane` from triggering stops during avoidance where the ego vehicle will overlap the adjacent lane.
Requires the launch PR: https://github.com/autowarefoundation/autoware_launch/pull/986
Psim and bag replay.
Evaluator (TIER IV INTERNAL LINK): https://evaluation.tier4.jp/evaluation/reports/659253fa-a67a-5341-a576-50afe030c401?project_id=prd_jt
Reduce wrong stops caused by the `out_of_lane` module. …

feat(out_of_lane): add option to ignore overlaps in lane changes

---

planning/behavior_velocity_occlusion_spot_module/src/debug.cpp
planning/behavior_velocity_occlusion_spot_module/src/grid_utils.cpp
planning/behavior_velocity_occlusion_spot_module/src/occlusion_spot_utils.cpp
planning/behavior_velocity_occlusion_spot_module/src/occlusion_spot_utils.hpp

This is based on CppCheck warnings.
1. remove unnecessary if branch
https://github.com/autowarefoundation/autoware.universe/commit/30b90a3b7fc0f70a1c9851641c56682b5c48dfc3
```
planning/behavior_velocity_occlusion_spot_module/src/grid_utils.cpp:91:9: style: Condition 'polys' is always true [knownConditionTrueFalse]
if (polys) {
^
planning/behavior_velocity_occlusion_spot_module/src/grid_utils.cpp:89:16: note: Assignment 'polys=true', assigned value is 1
bool polys = true;
^
planning/behavior_velocity_occlusion_spot_module/src/grid_utils.cpp:91:9: note: Condition 'polys' is always true
if (polys) {
^
planning/behavior_velocity_occlusion_spot_module/src/grid_utils.cpp:89:8: style: The scope of the variable 'polys' can be reduced. [variableScope]
bool polys = true;
^
```
2. add const for …

refactor(behavior_velocity_occlusion_spot_module): reduce cppcheck warning

---

localization/ndt_scan_matcher/config/ndt_scan_matcher.param.yaml
localization/ndt_scan_matcher/schema/sub/initial_pose_estimation.json
localization/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp
localization/tree_structured_parzen_estimator/include/tree_structured_parzen_estimator/tree_structured_parzen_estimator.hpp
localization/tree_structured_parzen_estimator/src/tree_structured_parzen_estimator.cpp
localization/tree_structured_parzen_estimator/test/test_tpe.cpp

The current `ndt_scan_matcher` uses Tree-Structured Parzen Estimator (TPE) for initial pose estimation. However, this implementation is not very good and often searches far away positions on the square.
In the image below, the search is being performed at a position far from the correct position on the upper and left sides.
One of the reasons for this is that TPE is designed as a general-purpose optimization class and is formulated as sampling for a uniform distribution. `ndt_scan_matcher` performs sampling based on normal distribution, so we introduce mutual conversion between uniform distribution and normal distribution, but it seems that this is not working as expected.
First, since TPE is only used in ndt_scan_matcher, we changed it to an implementation specialized for optimization in …

fix(ndt_scan_matcher): improved tpe

---

planning/behavior_velocity_occlusion_spot_module/src/debug.cpp
planning/behavior_velocity_occlusion_spot_module/src/occlusion_spot_utils.cpp
planning/behavior_velocity_occlusion_spot_module/src/occlusion_spot_utils.hpp

This fixes `build-and-test-differential / clang-tidy-differential` errors in https://github.com/autowarefoundation/autoware.universe/pull/6987:
```
/__w/autoware.universe/autoware.universe/planning/behavior_velocity_occlusion_spot_module/src/debug.cpp:36:29: error: using decl 'createDefaultMarker' is unused [misc-unused-using-decls,-warnings-as-errors]
using tier4_autoware_utils::createDefaultMarker;
^
/__w/autoware.universe/autoware.universe/planning/behavior_velocity_occlusion_spot_module/src/debug.cpp:36:29: note: remove the using
using tier4_autoware_utils::createDefaultMarker;
~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
/__w/autoware.universe/autoware.universe/planning/behavior_velocity_occlusion_spot_module/src/occlusion_spot_utils.hpp:60:16: error: using decl 'ArcCoordinates' …
```

refactor(behavior_velocity_occlusion_spot_module): remove unnecessary declaration

---

planning/behavior_path_dynamic_avoidance_module/src/scene.cpp

This is a fix based on CppCheck warning
```
planning/behavior_path_dynamic_avoidance_module/src/scene.cpp:1806:46: performance: Function parameter 'outer_body_path' should be passed by const reference. [passedByValue]
std::vector<geometry_msgs::msg::Point> outer_body_path) -> tier4_autoware_utils::Polygon2d {
^
```
No …

perf(behavior_path_dynamic_avoidance_module): use const reference

---

planning/behavior_path_planner_common/include/behavior_path_planner_common/turn_signal_decider.hpp

Refactor to make the code a little bit more clean and comply more with C++ iterators
PSim

refactor(turn_signal_decider): straddle bound method

---

common/motion_utils/CMakeLists.txt
common/motion_utils/include/motion_utils/factor/velocity_factor_interface.hpp
common/motion_utils/package.xml
common/motion_utils/src/factor/velocity_factor_interface.cpp
planning/behavior_velocity_intersection_module/src/scene_intersection.cpp
planning/behavior_velocity_planner_common/CMakeLists.txt
planning/behavior_velocity_planner_common/include/behavior_velocity_planner_common/scene_module_interface.hpp

Move the `VelocityFactorInterface` to the `motion_utils` package so that it can be easily used in more packages.
PSim

refactor(behavior_velocity_planner_common): move VelocityFactorInterface to motion_utils

---

planning/behavior_path_planner_common/src/turn_signal_decider.cpp
planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/start_planner_module.hpp
planning/behavior_path_start_planner_module/src/start_planner_module.cpp

When the ego vehicle is starting from a road and not the shoulder lane, it is possible that the blinkers are not properly activated. 
This is caused by 2 things:
1.  The check for lane bound straddling (crossing a lane bound) is failed. This check is not necessary when doing a pull out because we should turn on the blinkers anyways.
2. The shift is small and the ego is stopped. This happens because the ego is starting from complete stop so its speed is close to 0 and if the shift pull out lane is small/has a small shift, the blinkers are ignored, which is not desired in this case. 
To solve the issue I added an override for the first check if the ego is doing a pullout, and for the second issue I slightly modified the variable  `status_.first_engaged_and_driving_forward_time` to only be …

fix(start_planner): issue when ego does not straddle lane bounds and starts from 0 speed

---

simulator/simple_planning_simulator/src/simple_planning_simulator/simple_planning_simulator_core.cpp

Currently, when using the Planning_simulator, /vehicle/status/control_mode [is not published until the vehicle's position is provided](https://github.com/autowarefoundation/autoware.universe/blob/a5fdb8d85b2f27f632e48f1fa5682d6b055b696c/simulator/simple_planning_simulator/src/simple_planning_simulator/simple_planning_simulator_core.cpp#L360-L419). However, in actual vehicle usage, /vehicle/status/control_mode is published immediately after the vehicle_interface and the vehicle start up (ex. [pacmod_interface](https://github.com/tier4/pacmod_interface/blob/b779f8496f7f5c92ddf2dcf321897fe8602f0414/pacmod_interface/src/pacmod_interface/pacmod_interface.cpp#L323)) . To align the Planning_simulator with this actual behavior, I have modified it to publish /vehicle/status/control_mode …

chore(simple_planning_simulator): publish control mode before the self-position is given

---

system/diagnostic_graph_aggregator/CMakeLists.txt
system/diagnostic_graph_aggregator/launch/aggregator.launch.xml
system/diagnostic_graph_aggregator/package.xml
system/diagnostic_graph_aggregator/src/node/aggregator.cpp
system/diagnostic_graph_aggregator/src/node/aggregator.hpp

Componentize node in diagnostic_graph_aggregator.

feat(diagnostic_graph_aggregator): componentize node

---

common/component_interface_tools/CMakeLists.txt
common/component_interface_tools/launch/service_log_checker.launch.xml
common/component_interface_tools/package.xml
common/component_interface_tools/src/service_log_checker.cpp
common/component_interface_tools/src/service_log_checker.hpp

Componentize node in component_interface_tools.

feat(component_interface_tools): componentize node

---

map/map_height_fitter/src/map_height_fitter.cpp

Improve performance of the `map_height_fitter` when getting the ground height.
Currently, it checks ALL lanelets to find the closest one. With this PR, the query is more efficient (thanks to the R-tree used in the lanelet layer). 

perf(map_height_fitter): more efficient query to find closest lanelet

---

planning/autoware_static_centerline_generator/rviz/static_centerline_generator.rviz
planning/autoware_static_centerline_generator/scripts/app.py
planning/autoware_static_centerline_generator/scripts/centerline_updater_helper.py
planning/autoware_static_centerline_generator/src/static_centerline_generator_node.cpp

This is a followup PR to https://github.com/autowarefoundation/autoware.universe/pull/6817 that includes @xmfcx 's latest comments, but unfortunately got merged prematurely.

fix(autoware_static_centerline_generator): remove prefix from topics and node names

---

planning/behavior_path_lane_change_module/src/scene.cpp

Revert terminal path calculation in abort path

fix(lane_change): remove terminal in abort path

---

system/default_ad_api_helpers/ad_api_adaptors/CMakeLists.txt
system/default_ad_api_helpers/ad_api_adaptors/launch/rviz_adaptors.launch.xml
system/default_ad_api_helpers/ad_api_adaptors/package.xml
system/default_ad_api_helpers/ad_api_adaptors/src/initial_pose_adaptor.cpp
system/default_ad_api_helpers/ad_api_adaptors/src/initial_pose_adaptor.hpp
system/default_ad_api_helpers/ad_api_adaptors/src/routing_adaptor.cpp
system/default_ad_api_helpers/ad_api_adaptors/src/routing_adaptor.hpp

Componentize node in ad_api_adaptors.

feat(ad_api_adaptors): componentize nodes

---

system/default_ad_api_helpers/automatic_pose_initializer/CMakeLists.txt

`automatic_pose_initializer` is changed as a plugin in the pull request below, but it is not launched because the name is incorrect, causing an issue where autoware cannot start automatic initial pose estimation.
* https://github.com/autowarefoundation/autoware.universe/pull/7021
logging_simulator works well.
Initial pose estimation starts successfully. …

fix(automatic_pose_initializer): fix plugin name

---

map/util/lanelet2_map_preprocessor/src/fix_lane_change_tags.cpp
map/util/lanelet2_map_preprocessor/src/fix_z_value_by_pcd.cpp
map/util/lanelet2_map_preprocessor/src/merge_close_lines.cpp
map/util/lanelet2_map_preprocessor/src/merge_close_points.cpp
map/util/lanelet2_map_preprocessor/src/remove_unreferenced_geometry.cpp

use set.find instead of std::find for better performance.
Also remove the unused `exists` functions.
Psim

perf(lanelet2_map_preprocessor): use set.find instead of std::find

---

planning/behavior_path_avoidance_module/src/utils.cpp

[TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT1-6050)
Related PR: https://github.com/autowarefoundation/autoware.universe/pull/6781
The module searches most overhanging point by following steps:
1. pick a point from envelope polygon contour (P1).
2. create new point from P1 by using `calcOffsetPose` (P2).
3. search intersection point between P1-P2 and drivable bound.
4. calculate distance between intersection point and P1.
5. _apply step1~4 for all polygon points._
6. sort point by distance calculated in step4.
7. pick the point whose distance is smallest from sorted points as most overhanging point.
```c++
const auto p2 = calcOffsetPose(p_tmp, 0.0, (isOnRight(object) ? -1.0 : 1.0), 0.0).position;
```
Previously, the point (P2) is calculated with constant offset value. …

fix(avoidance): unexpected road shoulder distance calculation result

---

planning/autoware_planning_test_manager/include/autoware_planning_test_manager/autoware_planning_test_manager_utils.hpp
planning/autoware_planning_test_manager/src/autoware_planning_test_manager.cpp
planning/planning_test_utils/include/planning_test_utils/planning_test_utils.hpp
planning/planning_test_utils/package.xml

Removing route handler dependencies from planning_test_utils.
Move function that are used by `autoware_planning_test_manager` to the `autoware_planning_test_manager_utils.hpp`

refactor(planning_test_utils): remove route_handler dependencies

---

common/tier4_autoware_utils/include/tier4_autoware_utils/ros/polling_subscriber.hpp
planning/obstacle_cruise_planner/include/obstacle_cruise_planner/node.hpp
planning/obstacle_cruise_planner/src/node.cpp

- add the argument for QoS to polling subscriber (default is QoS{1})
- if the user did not specify depth == 1 for their custom QoS, raise exeception
- rename getData() to takeData() that does the `take()` and `getData()` in one method
- refactored obstacle_cruise for this change
works as before
none
none
none
none …

feat(tier4_autoware_utils): default QoS setting of polling subscriber

---

planning/behavior_path_planner_common/include/behavior_path_planner_common/interface/scene_module_interface.hpp
planning/behavior_path_planner_common/include/behavior_path_planner_common/interface/scene_module_manager_interface.hpp
planning/behavior_velocity_planner_common/include/behavior_velocity_planner_common/scene_module_interface.hpp
planning/behavior_velocity_planner_common/src/scene_module_interface.cpp
planning/rtc_interface/include/rtc_interface/rtc_interface.hpp
planning/rtc_interface/src/rtc_interface.cpp

Don't remove rtc cooperate status even after manager stops module execution immediately. The manager checks timestamp in cooperate status and removes old cooperate status by using following function.
```c++
void RTCInterface::removeExpiredCooperateStatus()
{
std::lock_guard<std::mutex> lock(mutex_);
const auto itr = std::remove_if(
registered_status_.statuses.begin(), registered_status_.statuses.end(),
[](const auto & status) {
return (rclcpp::Clock{RCL_ROS_TIME}.now() - status.stamp).seconds() > 10.0;
});
registered_status_.statuses.erase(itr, registered_status_.statuses.end());
}
```
https://github.com/autowarefoundation/autoware.universe/assets/44889564/14fdbb9f-6ec2-47a9-8cd0-384c5d536ddb
Nothing. …

fix(bpp, bvp): keep rtc cooperate status even after manager stops module execution

---

planning/mission_planner/src/lanelet2_plugins/default_planner.hpp

Fixes #6302 
Making sure no problems in compilation and while running planning simulator with basic test.

refactor(default_planner): refactor default_planner header not to hide base class public methods

---

common/motion_utils/include/motion_utils/resample/resample_utils.hpp
common/motion_utils/include/motion_utils/trajectory/trajectory.hpp
common/motion_utils/test/src/trajectory/test_trajectory.cpp
common/tier4_logging_level_configure_rviz_plugin/config/logger_config.yaml

Use rclcpp logging instead so that we can control the log with logging level configure plugin.
Directly use RCLCPP::DEBUG instead of common function, because it allows us to see which line in the the code is actually printing the messages.

refactor(motion_utils): supress log message with rclcpp logging

---

control/autonomous_emergency_braking/include/autonomous_emergency_braking/node.hpp
control/autonomous_emergency_braking/package.xml
control/autonomous_emergency_braking/src/node.cpp

replace the subscriber to InterProcessPollingSubscriber 
depends https://github.com/autowarefoundation/autoware.universe/pull/6976
https://tier4.atlassian.net/browse/RT1-5790
the module works as before
https://github.com/autowarefoundation/autoware.universe/assets/28677420/508c0f88-06eb-47ba-969e-4c1376301530
https://github.com/autowarefoundation/autoware.universe/assets/28677420/86c7982a-4ad3-41fa-8d23-5a92d1bf2e04
none
none …

feat(aeb): replace InterProcessPollingSubscriber

---

planning/behavior_velocity_planner/src/node.cpp
planning/behavior_velocity_traffic_light_module/package.xml
planning/behavior_velocity_traffic_light_module/src/manager.cpp
planning/behavior_velocity_traffic_light_module/src/manager.hpp
planning/behavior_velocity_traffic_light_module/src/scene.cpp
planning/behavior_velocity_traffic_light_module/src/scene.hpp

do not use the option to overwrite unknown with past known information
On change to from GREEN to UNKNOWN, ego does not stop
https://github.com/autowarefoundation/autoware.universe/assets/28677420/c0b9aaf9-7795-469e-bde8-9b2b21b23956
On change to from GREEN to UNKNOWN, ego stops
https://github.com/autowarefoundation/autoware.universe/assets/28677420/6b6556a8-29cd-42e0-86ba-5cd187c014a6
none …

feat(behavior_velocity_traffic_light): do not overwrite unknown with past known color

---

planning/autoware_static_centerline_generator/launch/static_centerline_generator.launch.xml
planning/autoware_static_centerline_generator/src/static_centerline_generator_node.cpp
planning/autoware_static_centerline_generator/src/static_centerline_generator_node.hpp
planning/autoware_static_centerline_generator/src/utils.cpp
planning/autoware_static_centerline_generator/src/utils.hpp

The centerline of the lanelet2 map was not correctly updated by the current autoware_static_centerline_generator due to the wrong usage of the map projector. This PR fixed the issue.
Unit test
Nothing

fix(autoware_static_centerline_generator): update the centerline correctly with map projector

---

planning/obstacle_cruise_planner/include/obstacle_cruise_planner/polygon_utils.hpp
planning/obstacle_cruise_planner/src/node.cpp
planning/obstacle_cruise_planner/src/polygon_utils.cpp
planning/obstacle_cruise_planner/src/utils.cpp

reduce computation cost in polygon collision check by setting adopting inclusive circle distance
Before
After
psim and tier4 internal test

feat(obstacle cruise): reduce computation cost

---

perception/tracking_object_merger/src/data_association/data_association.cpp

Removed unused `tracker_pose` and `measurement_pose` variables.
There is a warning from cppcheck:
```
perception/tracking_object_merger/src/data_association/data_association.cpp:183:36: style: Variable 'tracker_pose' is assigned a value that is never used. [unreadVariable]
std::vector<double> tracker_pose = {
^
perception/tracking_object_merger/src/data_association/data_association.cpp:186:40: style: Variable 'measurement_pose' is assigned a value that is never used. [unreadVariable]
std::vector<double> measurement_pose = {
^
```
No …

refactor(tracking_object_merger): remove unread variables

---

perception/ground_segmentation/src/ransac_ground_filter_nodelet.cpp
perception/ground_segmentation/src/scan_ground_filter_nodelet.cpp

These are refactoring based on cppcheck:
```
perception/ground_segmentation/src/ransac_ground_filter_nodelet.cpp:105:10: style: inconclusive: Found duplicate branches for 'if' and 'else'. [duplicateBranch]
} else if (unit_axis_ == "z") {
^
perception/ground_segmentation/src/ransac_ground_filter_nodelet.cpp:107:5: note: Found duplicate branches for 'if' and 'else'.
} else {
^
perception/ground_segmentation/src/ransac_ground_filter_nodelet.cpp:105:10: note: Found duplicate branches for 'if' and 'else'.
} else if (unit_axis_ == "z") {
^
perception/ground_segmentation/src/ransac_ground_filter_nodelet.cpp:387:12: style: inconclusive: Found duplicate branches for 'if' and 'else'. [duplicateBranch]
} else if (unit_axis_ == "z") {
^
perception/ground_segmentation/src/ransac_ground_filter_nodelet.c …
```

refactor(ground_segmentation): refactor based on cppcheck 

---

planning/mission_planner/src/lanelet2_plugins/default_planner.cpp
planning/mission_planner/src/lanelet2_plugins/default_planner.hpp
planning/mission_planner/src/lanelet2_plugins/utility_functions.cpp
planning/mission_planner/src/lanelet2_plugins/utility_functions.hpp

No longer query ALL road and shoulder lanelets in the mission_planner.
There was an issue in the previous PR https://github.com/autowarefoundation/autoware.universe/pull/7024 with the `RoutingGraph` used by the mission planner. When checking if a goal fits inside the lane, we need to retrieve the lanelets following the closest lanelet to the goal. For some reason there were cases where, _for the same input lanelet_, the `RoutingGraph::following(lanelet)` function would return different value and some valid goal would become invalid.
I refactored the mission planner to not directly use the routing graph, but instead use the `route_handler` to achieve the same operation. This fixed the issue (see the [evaluation results](https://evaluation.tier4.jp/evaluation/reports/c27675c8-314b-515d-b469- …

perf(mission_planner): remove queries on all road and shoulder lanelets

---

planning/behavior_velocity_no_stopping_area_module/src/scene_no_stopping_area.cpp

I have made several chages based on CppCheck warnings.
Some commits are irrelevant to CppCheck.
1. remove redundant if branch
https://github.com/autowarefoundation/autoware.universe/commit/e0e49be0b07240e9c2097ed726397badeb983dfd
```
planning/behavior_velocity_no_stopping_area_module/src/scene_no_stopping_area.cpp:94:13: style: Condition '!collision_points.empty()' is always true [knownConditionTrueFalse]
if (!collision_points.empty()) {
^
planning/behavior_velocity_no_stopping_area_module/src/scene_no_stopping_area.cpp:90:35: note: Assuming that condition 'collision_points.empty()' is not redundant
if (collision_points.empty()) {
^
planning/behavior_velocity_no_stopping_area_module/src/scene_no_stopping_area.cpp:94:13: note: Condition '!collision_points.empty()' is always true
if …
```

refactor(behavior_velocity_no_stopping_area_module): cppcheck warnings

---

planning/behavior_velocity_planner/src/node.cpp

In the construction of AnalyticalJerkConstrainedSmoother in behavior_velocity_planner node, `SmootherBase::setWheelBase` was not called, potentially influencing intersection module.
https://github.com/autowarefoundation/autoware.universe/issues/6915
this should be fixed anyway.
none
none
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request …

fix(behavior_velocity_planner): fix uninitialized smoother param

---

planning/rtc_interface/include/rtc_interface/rtc_interface.hpp
planning/rtc_interface/src/rtc_interface.cpp

Some issues were caused by `rclcpp::Clock{RCL_ROS_TIME}` when we used `--use-sim-time` option. In this PR, I fixed and used clock created by node to judge expired cooperate status.
Psim
Nothing.

fix(rtc_interface): use clock created by node to judge expired cooperate status

---

planning/planning_test_utils/test/test_mock_data_parser.cpp

```
--- stderr: planning_test_utils                                                                                     
In file included from /home/satoshi/pilot-auto/src/autoware/universe/planning/planning_test_utils/test/test_mock_data_parser.cpp:15:
/opt/ros/humble/src/gtest_vendor/include/gtest/gtest.h: In instantiation of ‘testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int]’:
/opt/ros/humble/src/gtest_vendor/include/gtest/gtest.h:1554:23:   required from ‘static testing::AssertionResult testing::internal::EqHelper::Compare(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int; typename std::enable_if<((! std::is_integral<_Tp>::value) || (! …
```

fix(planning_test_utils): fix build error `-werror=sign-compare`

---

planning/behavior_path_avoidance_module/include/behavior_path_avoidance_module/scene.hpp
planning/behavior_path_avoidance_module/src/scene.cpp

After this PR, avoidance module doesn't remove rtc cooperate status even when the maneuver is canceled. It set `State::FAILED` to rtc state and keep publishing canceled rtc cooperate status.
https://github.com/autowarefoundation/autoware.universe/assets/44889564/a17974bd-04f5-493a-9a20-a56c7e9bc9d4
Nothing.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contr …

fix(avoidance): transit rtc cooperate state to FAILED from RUNNING

---

planning/behavior_path_avoidance_module/src/utils.cpp

Previously, avoidance module outputed following error even in nominal case. I fixed logger level from `ERROR` to `DEBUG`.
```
[component_container_mt-30] [ERROR 1716341804.717495512] [planning.scenario_planning.lane_driving.behavior_planning.behavior_path_planner.avoidance.utils]: Drivable area expansion reaches max iteration.
```
Psim
Nothing. …

fix(avoidance): fix logger level

---

common/motion_utils/include/motion_utils/trajectory/trajectory.hpp
common/motion_utils/test/src/trajectory/test_trajectory.cpp
planning/behavior_path_planner_common/src/utils/path_shifter/path_shifter.cpp

Fix logic to remove invalid orientation points. After this PR, basically, the function `removeInvalidOrientationPoints` removes not only front point but also behind one to prevent following chain reaction.

fix(motion_utils): remove only first point whose orientation is invalid

---

perception/image_projection_based_fusion/CMakeLists.txt
perception/image_projection_based_fusion/package.xml
perception/image_projection_based_fusion/test/test_utils.cpp

- Add unit test for `closest_cluster` function in image_projection_based_fusion package
[TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT1-6385)
- Confirmed the colcon test passed

chore(image_projection_based_fusion): add unit test for utils

---

control/autonomous_emergency_braking/README.md

Add a brief section explaining pros and cons of using steering and IMU.
Related link: [TIER IV INTERNAL LINK](https://star4.slack.com/archives/C03QW0GU6P7/p1713420391372759?thread_ts=1713419406.383599&cid=C03QW0GU6P7)

feat(autonomous_emergency_braking): add info about IMU vs Steering info for AEB doc

---

planning/behavior_path_planner_common/src/utils/occupancy_grid_based_collision_detector/occupancy_grid_based_collision_detector.cpp

https://github.com/orgs/autowarefoundation/discussions/4748
no need, just removed unnecessary calculation
none
none

perf(behavior_path_planner_common): remove unnecessary angle calculation in OccupancyGridMapBasedDetector

---

evaluator/perception_online_evaluator/include/perception_online_evaluator/metrics/metric.hpp
evaluator/perception_online_evaluator/include/perception_online_evaluator/metrics_calculator.hpp
evaluator/perception_online_evaluator/include/perception_online_evaluator/perception_online_evaluator_node.hpp
evaluator/perception_online_evaluator/src/metrics_calculator.cpp
evaluator/perception_online_evaluator/src/perception_online_evaluator_node.cpp
evaluator/perception_online_evaluator/test/test_perception_online_evaluator_node.cpp

Previously, only stat with `max`, `mean`, and `min` as keys could be handled in diagnostics, but this PR allows `metric_value` with a single value.
This is to allow only one value to be included in metrics such as object counts, since all stat values are the same, which is redundant.
- stat type
```
- level: "\0"
name: predicted_path_deviation_variance_CAR_5.00
message: ''
values:
- key: min
value: '0.039821'
- key: max
value: '0.039821'
- key: mean
value: '0.039821'
```
- metric_value type
```
- level: "\0"
name: interval_average_objects_count_UNKNOWN_r100.00_h10.00
message: ''
values:
- key: metric_value
value: '4.000000'
```
psim
no interface changes for autoware.
but the diagnostic key used for tools (driving_log_replayer etc) is chaged …

feat(perception_online_evaluator): add metric_value not only stat

---

planning/obstacle_cruise_planner/src/node.cpp

fix incorrect comments and organize if-else structure
I guess this PR does not cause any behavior change.

refactor(obstacle_cruise): refactor a function checkConsistency()

---

evaluator/perception_online_evaluator/include/perception_online_evaluator/metrics/metric.hpp
evaluator/perception_online_evaluator/include/perception_online_evaluator/metrics_calculator.hpp
evaluator/perception_online_evaluator/include/perception_online_evaluator/perception_online_evaluator_node.hpp
evaluator/perception_online_evaluator/src/metrics_calculator.cpp
evaluator/perception_online_evaluator/src/perception_online_evaluator_node.cpp
evaluator/perception_online_evaluator/test/test_perception_online_evaluator_node.cpp

Reverts autowarefoundation/autoware.universe#7100
is not yet ready to support in driving_log_replayer. so once revert it.

fix(perception_online_evaluator): revert "add metric_value not only stat (#7100)"

---

common/autoware_ad_api_specs/include/autoware_ad_api_specs/system.hpp
system/default_ad_api/CMakeLists.txt
system/default_ad_api/launch/default_ad_api.launch.py
system/default_ad_api/src/heartbeat.cpp
system/default_ad_api/src/heartbeat.hpp

Add heartbeat API. [See the documentation for details.](https://autowarefoundation.github.io/autoware-documentation/main/design/autoware-interfaces/ad-api/features/heartbeat/)
https://github.com/orgs/autowarefoundation/discussions/4561
https://github.com/autowarefoundation/autoware-documentation/pull/536
https://autowarefoundation.github.io/autoware-documentation/main/design/autoware-interfaces/ad-api/features/heartbeat/
`ros2 topic echo /api/system/heartbeat`
None
| Topic Name       | Type                | Direction | Update Description                                            |
| ---------------- | ------------------- | --------- | ------------------------------------------------------------- |
| `/api/system/heartbeat` | `autoware_adapi_v1_msgs/msgHeartbeat`   | Publisher | Heartbeat …

feat(default_ad_api): add heratbeat api

---

common/tier4_autoware_utils/include/tier4_autoware_utils/math/trigonometry.hpp
common/tier4_autoware_utils/src/math/trigonometry.cpp
common/tier4_autoware_utils/test/src/math/test_trigonometry.cpp

I have implemented a faster sin ans cos calculation.
Calling `sin_and_cos` is faster than calling `sin` and `cos` separately.
It is useful, for example, for `DistortionCorrector`.
I found that around 35% of CPU time in DistortionCorrector is occupied by `sin` and `cos`,
and I have confirmed 10~20% latency improvement with faster `sin_and_cos`. cc @vividf 
I have written a test code and the test has passed. …

feat(tier4_autoware_utils): faster sin and cos

---

planning/behavior_velocity_blind_spot_module/CMakeLists.txt
planning/behavior_velocity_blind_spot_module/src/debug.cpp
planning/behavior_velocity_blind_spot_module/src/decisions.cpp
planning/behavior_velocity_blind_spot_module/src/manager.cpp
planning/behavior_velocity_blind_spot_module/src/scene.cpp
planning/behavior_velocity_blind_spot_module/src/scene.hpp

categorize the scene into
- InternalError
- OverPassJudge
- Unsafe
- Safe
and act according to RTC and that scene respectively.
https://evaluation.tier4.jp/evaluation/reports/089988e0-7552-5c60-9fdc-a6dc6a157377?project_id=prd_jt
none
none

refactor(blind_spot): devide scene into Categories and act accordingly

---

planning/behavior_path_planner_common/include/behavior_path_planner_common/interface/scene_module_interface.hpp

Support for new RTC state transition.
It updates RTC state to `State::SUCCEEDED` if the module exits with `ModuleStatus::SUCCESS`.
*Applying to avoidance module is a future work.*
[TIER IV INTERNAL TEST](https://evaluation.tier4.jp/evaluation/reports/f51f28f5-1695-52a6-8072-77783f64e33f?project_id=prd_jt)
I checked that the state in `/planning/cooperate_status/**` changes from `RUNNING = 1` to `SUCCEEDED = 3`.
[Screencast from 2024年05月27日 11時17分04秒.webm](https://github.com/autowarefoundation/autoware.universe/assets/10190493/4e055ee7-23a0-418c-83f3-178df6f2f7c2)
[Screencast from 2024年05月27日 11時18分45秒.webm](https://github.com/autowarefoundation/autoware.universe/assets/10190493/c28f4220-d760-417c-8a67-74152e5b6b11) …

feat(behavior_path_planner_common): update RTC state to SUCCEEDED

---

planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp

fix not to calculate the distance from the null polygon

fix(crosswalk): fix calclation distance from the null polygons

---

launch/tier4_system_launch/launch/system.launch.xml
system/system_diagnostic_monitor/config/map.yaml

- modify argument for https://github.com/autowarefoundation/autoware_launch/pull/1000
- fix typo in diagnostic graph settings
This PR be merged with https://github.com/autowarefoundation/autoware_launch/pull/1000 at the same time.
See https://github.com/autowarefoundation/autoware_launch/pull/1000.
See https://github.com/autowarefoundation/autoware_launch/pull/1000.
None …

feat(tier4_system_launch): modify diagnostic_graph_aggregator_graph argument

---

planning/behavior_velocity_blind_spot_module/src/scene.cpp
planning/behavior_velocity_blind_spot_module/src/scene.hpp

Fix typo in `planning/behavior_velocity_blind_spot_module` to suppress the spell-check warnings.
I am not sure about `Dafe`. Assuming it is a typo for `Safe`.

fix(behavior_velocity_blind_spot_module): fix typo in behavior_velocity_blind_spot_module

---

planning/planning_test_utils/CMakeLists.txt
planning/planning_test_utils/include/planning_test_utils/planning_test_utils.hpp
planning/planning_test_utils/src/planning_test_utils.cpp

Separate the inplementation in the header file to cpp file.
Added doxygen comments

refactor(planning_test_utils): separate hpp and cpp

---

localization/ndt_scan_matcher/src/map_update_module.cpp
localization/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp

`ndt_scan_matcher` outputs timestamps as `double` to `/diagnostics`. 
In [diagnostics_module](https://github.com/autowarefoundation/autoware.universe/blob/main/localization/ndt_scan_matcher/include/ndt_scan_matcher/diagnostics_module.hpp#L45-L52), this is converted to `string` by `std::to_string`, so it has 6 decimal places and the last 3 digits are removed.
To match other topics (like `pose_with_covariance`), it is useful to keep the full timestamp. So, I fixed it.
logging_simulator works well.
`topic_time_stamp` is changed to `int64_t`.
There is no effects on system behavior.
After …

fix(ndt_scan_matcher): changed the type of timestamp from double to int in ndt diag

---

planning/behavior_velocity_blind_spot_module/config/blind_spot.param.yaml
planning/behavior_velocity_blind_spot_module/src/debug.cpp
planning/behavior_velocity_blind_spot_module/src/manager.cpp
planning/behavior_velocity_blind_spot_module/src/scene.cpp
planning/behavior_velocity_blind_spot_module/src/scene.hpp

https://github.com/autowarefoundation/autoware_launch/pull/1002
https://github.com/autowarefoundation/autoware.universe/assets/28677420/ad82e308-fb8d-4725-954b-3960e6a67bb7
https://github.com/autowarefoundation/autoware.universe/assets/28677420/b76b021f-da3e-4c3d-b259-f24ab355f423
https://tier4.atlassian.net/browse/RT1-6086
https://evaluation.tier4.jp/evaluation/reports/0e08ae93-cb10-5d29-a00c-b730127dcd66?project_id=prd_jt
none
none …

feat(behavior_velocity_blind_spot): use TTC for object in detection_area

---

perception/multi_object_tracker/include/multi_object_tracker/processor/input_manager.hpp
perception/multi_object_tracker/src/processor/input_manager.cpp

The input stream checked the object time interval inputs (object_latest_time and object_oldest_time) whether the latest time is later than the oldest time. 
There was a report that the reversed timing settings (object_latest_time is older than object_oldest_time) was observed and the assertion stop the node, in the planning simulation environment.
https://github.com/autowarefoundation/autoware.universe/pull/6820#discussion_r1615201758
1. InputManager::getObjectTimeInterval
Eliminated possibility to ouput the time interval settings (object_latest_time and object_oldest_time) in wrong order.
2. latest_object_time_ (renamed to latest_exported_object_time_)
Initializing this value to `now` (time at the initialization) can cause the reversed times. 
This value will be initialized to a bit …

fix(multi_object_tracker): input stream timimg functions 

---

common/tier4_planning_rviz_plugin/include/tier4_planning_rviz_plugin/path/display_base.hpp

Every time the path length changed, it caused a memory leak. This PR fixes that.
I confirmed that the text is still displayed in the planning simulator. I also confirmed that leaks caused by movable text have been eliminated.
I confirmed that the text is still displayed in the planning simulator. I also confirmed that leaks caused by movable text have been eliminated.
after …

fix(tier4_planning_rviz_plugin): memory leak

---

perception/detected_object_validation/config/object_lanelet_filter.param.yaml
perception/detected_object_validation/include/detected_object_validation/detected_object_filter/object_lanelet_filter.hpp
perception/detected_object_validation/src/object_lanelet_filter.cpp

This PR updates lanelet filter so that it can filter objects with opposite velocity toward belonging lanelet.
New filter will check if:
- object has valid velocity larger than threshold (defalt: 3.0 m/s)
- object velocity direction does not differ with its lanelet (default 45 deg)
merge [launcher PR](https://github.com/autowarefoundation/autoware_launch/pull/998) first.
Here shows the example that filter opposite directed car.
|before| after filtered|
|--|--|
|![Screenshot from 2024-05-24 02-08-53](https://github.com/autowarefoundation/autoware.universe/assets/20086766/f3860426-5290-40bd-8267-60749dd4bf32) |![Screenshot from 2024-05-24 02-08-58](https://github.com/autowarefoundation/autoware.universe/assets/20086766/151da453-5053-4ad3-b7a4-03b2aa7e8adc) | …

feat(object_lanelet_filter): add velocity direction based object lanelet filter

---

planning/behavior_path_planner/config/behavior_path_planner.param.yaml
planning/behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner_common/docs/behavior_path_planner_turn_signal_design.md
planning/behavior_path_planner_common/include/behavior_path_planner_common/parameters.hpp
planning/behavior_path_planner_common/src/turn_signal_decider.cpp

Currently, there is a hard coded THRESHOLD value to decide if the ego is close enough to finish its shift and turn off the blinkers. This PR makes that value a parameter. 
Requires launch changes:  https://github.com/autowarefoundation/autoware_launch/pull/1007
PSim
Added turn_signal_remaining_shift_length_threshold: 0.1 -> same value as prev hardcoded value so no behavior change.
[pull request …

feat(behavior_path_planner_common,turn_signal_decider): add turn_signal_remaining_shift_length_threshold

---

.github/workflows/build-and-test-arm64.yaml
.github/workflows/build-and-test-differential-arm64.yaml
.github/workflows/build-and-test-differential.yaml
.github/workflows/build-and-test.yaml

This PR changes the docker image name from `autoware-openadk` to `autoware` according to https://github.com/autowarefoundation/autoware/pull/4785.

refactor(ci): rename docker image from `autoware-openadk` to `autoware`

---

localization/localization_error_monitor/src/localization_error_monitor.cpp

Currently, `localization_error_monitor` outputs a timestamp in the diagnostic message header with the node's `this->now()` set. However, we are interested in the time when the message monitored by the `localization_error_monitor` node was published. So I changed the timestamp to be set, from `this->now()` to `input_msg->header.stamp`.
I ran logging_simulator and parsed the `/diagnostics` topic from the saved rosbag.
I have confirmed that all timestamps in `localization: localization_error_monitor` have a match in `localization: ekf_localizer`.  
There are no interface changes. …

fix(localization_error_monitor): fixed header stamp

---

perception/multi_object_tracker/include/multi_object_tracker/utils/utils.hpp
perception/multi_object_tracker/src/tracker/model/bicycle_tracker.cpp
perception/multi_object_tracker/src/tracker/model/big_vehicle_tracker.cpp
perception/multi_object_tracker/src/tracker/model/normal_vehicle_tracker.cpp
perception/multi_object_tracker/src/tracker/model/pedestrian_tracker.cpp

A bug was reported that a huge (length of 6km) object is appeared from the object tracking.
It is happening when a unknown object (shape of `autoware_auto_perception_msgs::msg::Shape::POLYGON`) is assigned to a bicycle tracker.
It was caused by `utils::convertConvexHullToBoundingBox(object, bbox_object)` which treats the footprint points as global (map coordinate) position, while the input is local (the object coordinate).
1. Fix bug on `utils::convertConvexHullToBoundingBox(object, bbox_object)`
2. Add a detected object size checker. Update the object size only if the size is proper
1. Configure `data_association_matrix.param.yaml` to enable the unknown object can be assigned to bicycle tracker
```yaml
/**:
can_assign_matrix:
#UNKNOWN, CAR, TRUCK, BUS,  TRAILER, …
```

fix(multi_object_tracker): prevent too large object tracking

---

localization/ndt_scan_matcher/package.xml

This PR is for removing the unused dependency in ndt_scan_matcher/package.xml which should be removed in the https://github.com/autowarefoundation/autoware.universe/pull/7130

fix(ndt_scan_matcher): remove unused dependency

---

planning/motion_velocity_smoother/src/smoother/analytical_jerk_constrained_smoother/velocity_planning_utils.cpp

Remove `stringstream` creation to improve performance

chore(motion_velocity_smoother): remove string stream creation

---

planning/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp

This PR includes followng bug fixes:
Check if object's lane within/without not only for object's closest lane but also its next/prev lanes.
If there was road shoulder lane on left side, the module created avoidance path not only for vehicle whose footprint was on road shoulder lane but also vehicles stopped without pulling over the side of the road.
Use location tag to judge if it's a virtual intersection or not. …

fix(avoidance): fix bugs in parked vehicle filtering logic

---

planning/obstacle_cruise_planner/config/obstacle_cruise_planner.param.yaml
planning/obstacle_cruise_planner/include/obstacle_cruise_planner/node.hpp
planning/obstacle_cruise_planner/src/node.cpp

This PR provides a feature to ignore grazing against unknown objects, such as bushes.
[Screencast from 2024年05月30日 19時07分47秒.webm](https://github.com/autowarefoundation/autoware.universe/assets/141538661/5cb215c8-0fb9-48af-b5e0-4c66c61d62d5)
To create the demo movie, I set up that pedestrians are assumed as unknown.
The movie shows that no stop-planning takes place if the collision width is small enough against the pedestrian.
launch PR: https://github.com/autowarefoundation/autoware_launch/pull/1009 …

feat(obstacle_cruise_planner)!: ignore to garze against unknwon objects

---

map/map_height_fitter/CMakeLists.txt
map/map_height_fitter/launch/map_height_fitter.launch.xml
map/map_height_fitter/package.xml
map/map_height_fitter/src/map_height_fitter_node.cpp

Componentize the node in `map/map_height_fitter`.
(Add glog feature to map_height_fitter)
Also, add log output and change the file name (`node.cpp` -> `map_height_fitter_node.cpp`) to match the other packages.
Confirmed that terminating the `map_height_fitter` process will output logs to both the terminal and the log file.
Since it will not get launched from Autoware, directly launch the package for testing.
```Text
1717135375.6562157 [map_height_fitter_node-1] [INFO] [1717135375.655949160] [rclcpp]: signal_handler(signum=15)
1717135375.6563284 [map_height_fitter_node-1] *** Aborted at 1717135375 (unix time) try "date -d @1717135375" if you are using GNU date ***
1717135375.6568561 [map_height_fitter_node-1] PC: @                0x0 (unknown)
1717135375.6570129 [map_height_fitter_node-1] …
```

feat(map_height_fitter): componentize MapHeightFitter

---

system/diagnostic_graph_utils/CMakeLists.txt
system/diagnostic_graph_utils/doc/node/converter.md
system/diagnostic_graph_utils/doc/node/dump.md
system/diagnostic_graph_utils/package.xml
system/diagnostic_graph_utils/src/node/converter.cpp
system/diagnostic_graph_utils/src/node/converter.hpp
system/diagnostic_graph_utils/src/node/dump.cpp
system/diagnostic_graph_utils/src/node/dump.hpp

Componetize nodes in diagnostic_graph_utils.

feat(diagnostic_graph_utils): componentize node

---

planning/behavior_path_start_planner_module/README.md
planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/start_planner_module.hpp
planning/behavior_path_start_planner_module/src/start_planner_module.cpp

- refactor the flow of `canTransitSuccessState`
- update flowchart of end condition 
---

refactor(start_planner): improve readability of end condition

---

localization/ndt_scan_matcher/include/ndt_scan_matcher/diagnostics_module.hpp
localization/ndt_scan_matcher/src/diagnostics_module.cpp
localization/ndt_scan_matcher/src/map_update_module.cpp
localization/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp

For the same reason as [this PR](https://github.com/autowarefoundation/autoware.universe/pull/7174), I changed the header stamp to match the message's timestamp
confirmed that the header.stamp of diagnostic match the `topic_time_stamp`, `timer_callback_time_stamp` and `service_call_time_stamp`.
example …

fix(ndt_scan_matcher): change diag time_stamp

---

map/map_tf_generator/launch/map_tf_generator.launch.xml

Add log output to `map/map_tf_generator`.
It is set to "both",  which outputs to both the terminal and the log file.
I checked that both the terminal and the log file will receive the log output.
The log file when the running process get killed:
```Text
...
1717144765.1524458 [vector_map_tf_generator-1] [INFO] [1717144765.151681543] [rclcpp]: signal_handler(signum=15)
1717144765.1528726 [vector_map_tf_generator-1] *** Aborted at 1717144765 (unix time) try "date -d @1717144765" if you are using GNU date ***
1717144765.1554124 [vector_map_tf_generator-1] PC: @                0x0 (unknown)
1717144765.1563036 [vector_map_tf_generator-1] *** SIGTERM (@0x3e8000e1b20) received by PID 3203430 (TID 0x7f11b08f1680) from PID 924448; stack trace: ***
1717144765.1571054 [vector_map_tf_generator-1] …
```

fix(map_tf_generator): add log output

---

sensing/gnss_poser/launch/gnss_poser.launch.xml

Change the log output of `sensing/gnss_poser` from screen to both, which outputs to both the terminal and the log file.
I checked both the terminal and the log file will receive the log output.
The log file when the running process get killed:
```
...
1717146883.2361288 [gnss_poser-37] [INFO] [1717146883.235703527] [rclcpp]: signal_handler(signum=15)
1717146883.2367308 [gnss_poser-37] *** Aborted at 1717146883 (unix time) try "date -d @1717146883" if you are using GNU date ***
1717146883.2371097 [gnss_poser-37] PC: @                0x0 (unknown)
1717146883.2371683 [gnss_poser-37] *** SIGTERM (@0x3e8000e1b20) received by PID 3219247 (TID 0x7f6aa6c3d680) from PID 924448; stack trace: ***
1717146883.2375939 [gnss_poser-37]     @     0x7f6aa72324d6 google::(anonymous …
```

fix(gnss_poser): change log output from screen to both

---

control/lane_departure_checker/README.md
control/lane_departure_checker/config/lane_departure_checker.param.yaml
control/lane_departure_checker/include/lane_departure_checker/lane_departure_checker.hpp
control/lane_departure_checker/schema/lane_departure_checker.json
control/lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker.cpp
control/lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker_node.cpp
planning/behavior_path_start_planner_module/README.md
planning/behavior_path_start_planner_module/config/start_planner.param.yaml
planning/behavior_path_start_planner_module/include/behavior_path_start_planner_module/data_structs.hpp
planning/behavior_path_start_planner_module/src/manager.cpp
planning/behavior_path_start_planner_module/src/start_planner_module.cpp

This adds the option for an extra margin on the ego footprint when checking for out of lane.  
Requires launch changes: https://github.com/autowarefoundation/autoware_launch/pull/1011
Addresses this [TICKET](https://tier4.atlassian.net/browse/RT0-31697)
PSim
[EVALUATOR TESTS TIER IV INTERNAL LINK](https://evaluation.tier4.jp/evaluation/reports/d885ed92-5051-50b1-8db5-89fd0521a86a?project_id=prd_jt)
footprint_extra_margin -> an extra margin used to increase the ego footprint size …

feat(start_planner,lane_departure_checker): add margin param for lane departure check

---

planning/obstacle_avoidance_planner/include/obstacle_avoidance_planner/node.hpp
planning/obstacle_avoidance_planner/src/node.cpp

feat(obstacle_avoidance_planner): use polling subscriber

---

planning/path_smoother/include/path_smoother/elastic_band_smoother.hpp
planning/path_smoother/src/elastic_band_smoother.cpp

feat(path_smoother): use polling subscriber

---

localization/yabloc/yabloc_common/src/extract_line_segments.cpp

This is a refactor based on clang-tidy CRITICAL warning:
```
variable 'sqrt_two' cannot be implicitly captured in a lambda with no capture-default specified
```
As the warning says, `sqrt_two` is not captured.
No
No
No

fix(yabloc): fix bug in capturing in lambda function

---

localization/yabloc/yabloc_common/src/extract_line_segments.cpp

This is a refactor based on clang-tidy CRITICAL warning:
```
constexpr variable 'sqrt_two' must be initialized by a constant expression
```
As the warning says, the std::sqrt function is not a constexpr function yet (from C++26).
No
No
No

refactor(yabloc): use constexpr properly

---

common/autoware_auto_common/include/autoware_auto_common/helper_functions/message_adapters.hpp

Resolve https://github.com/autowarefoundation/autoware.universe/issues/7205
clang-tidy does not put warning for nullptr_t

fix(autoware_auto_common): nullptr_t

---

perception/detected_object_validation/include/detected_object_validation/detected_object_filter/object_lanelet_filter.hpp
perception/detected_object_validation/include/detected_object_validation/utils/utils.hpp
perception/detected_object_validation/src/object_lanelet_filter.cpp

This PR tries to use an object footprint pointcloud to judge the object is inside any lanelet. 
Currently, objects are filtered by calculating polygon overlap with lanelet.
This PR fixes the issue that unknown objects sometimes assumed to be inside the lanelet even if its pointcloud do not exist in the lanelet.
Tested with actual driving data
- Before this change: 
- pink is clustering result, white is detection output 
- After
- unknown object is properly filtered with this PR …

feat(detected_object_validation): filter unknown objects with its footprint

---

map/map_height_fitter/package.xml
map/map_height_fitter/src/map_height_fitter.cpp
map/map_loader/README.md
map/map_loader/include/map_loader/lanelet2_map_loader_node.hpp
map/map_loader/include/map_loader/lanelet2_map_visualization_node.hpp
map/map_loader/package.xml
map/map_loader/src/lanelet2_map_loader/lanelet2_map_loader_node.cpp
map/map_loader/src/lanelet2_map_loader/lanelet2_map_visualization_node.cpp
map/map_tf_generator/README.md
map/map_tf_generator/src/vector_map_tf_generator_node.cpp

This is subset of https://github.com/autowarefoundation/autoware.universe/pull/6893 to make it easier to review.
This includes all the modification for `map` directory in the original PR. 
Depends on:
- https://github.com/autowarefoundation/autoware_common/pull/247
https://github.com/autowarefoundation/autoware.universe/pull/6893
https://github.com/orgs/autowarefoundation/discussions/3862
Message types are modified according to the table in [this comment](https://github.com/orgs/autowarefoundation/discussions/3862#discussioncomment-9638820). …

feat!: replace autoware_auto_msgs with autoware_msgs for map modules

---

simulator/dummy_perception_publisher/CMakeLists.txt
simulator/dummy_perception_publisher/README.md
simulator/dummy_perception_publisher/include/dummy_perception_publisher/node.hpp
simulator/dummy_perception_publisher/msg/Object.msg
simulator/dummy_perception_publisher/package.xml
simulator/dummy_perception_publisher/src/empty_objects_publisher.cpp
simulator/dummy_perception_publisher/src/node.cpp
simulator/simple_planning_simulator/README.md
simulator/simple_planning_simulator/include/simple_planning_simulator/simple_planning_simulator_core.hpp
simulator/simple_planning_simulator/include/simple_planning_simulator/vehicle_model/sim_model_delay_steer_acc_geared.hpp
simulator/simple_planning_simulator/include/simple_planning_simulator/vehicle_model/sim_model_delay_steer_map_acc_geared.hpp
simulator/simple_planning_simulator/include/simple_planning_simulator/vehicle_model/sim_model_ideal_steer_acc_geared.hpp
simulator/simple_planning_simulator/include/simple_planning_simulator/vehicle_model/sim_model_interface.hpp
simulator/simple_planning_simulator/package.xml
simulator/simple_planning_simulator/src/simple_planning_simulator/simple_planning_simulator_core.cpp
simulator/simple_planning_simulator/src/simple_planning_simulator/vehicle_model/sim_model_delay_steer_acc_geared.cpp
simulator/simple_planning_simulator/src/simple_planning_simulator/vehicle_model/sim_model_delay_steer_map_acc_geared.cpp
simulator/simple_planning_simulator/src/simple_planning_simulator/vehicle_model/sim_model_ideal_steer_acc_geared.cpp
simulator/simple_planning_simulator/test/test_simple_planning_simulator.cpp

This is a subset of https://github.com/autowarefoundation/autoware.universe/pull/6893 to make it easier to review.
This includes all the modification for `simulator` directory in the original PR. 
https://github.com/autowarefoundation/autoware.universe/pull/6893
https://github.com/orgs/autowarefoundation/discussions/3862
Message types are modified according to the table in [this comment](https://github.com/orgs/autowarefoundation/discussions/3862#discussioncomment-9638820). …

feat!: replace autoware_auto_msgs with autoware_msgs for simulator modules

---

vehicle/accel_brake_map_calibrator/include/accel_brake_map_calibrator/accel_brake_map_calibrator_node.hpp
vehicle/accel_brake_map_calibrator/package.xml
vehicle/accel_brake_map_calibrator/scripts/actuation_cmd_publisher.py
vehicle/accel_brake_map_calibrator/test/sim_actuation_status_publisher.py
vehicle/external_cmd_converter/README.md
vehicle/external_cmd_converter/include/external_cmd_converter/node.hpp
vehicle/external_cmd_converter/package.xml
vehicle/external_cmd_converter/src/node.cpp
vehicle/raw_vehicle_cmd_converter/README.md
vehicle/raw_vehicle_cmd_converter/include/raw_vehicle_cmd_converter/node.hpp
vehicle/raw_vehicle_cmd_converter/package.xml
vehicle/raw_vehicle_cmd_converter/src/node.cpp
vehicle/steer_offset_estimator/Readme.md
vehicle/steer_offset_estimator/include/steer_offset_estimator/steer_offset_estimator_node.hpp
vehicle/steer_offset_estimator/package.xml

This is a subset of https://github.com/autowarefoundation/autoware.universe/pull/6893 to make it easier to review.
This includes all the modification for `vehicle` directory in the original PR. 
https://github.com/autowarefoundation/autoware.universe/pull/6893
https://github.com/orgs/autowarefoundation/discussions/3862
Message types are modified according to the table in [this comment](https://github.com/orgs/autowarefoundation/discussions/3862#discussioncomment-9638820). …

feat!: replace autoware_auto_msgs with autoware_msgs for vehicle modules

---

launch/tier4_perception_launch/launch/traffic_light_recognition/traffic_light.launch.xml
launch/tier4_planning_launch/launch/scenario_planning/lane_driving/motion_planning/motion_planning.launch.xml

This is subset of https://github.com/autowarefoundation/autoware.universe/pull/6893 to make it easier to review.
This includes all the modification for `launch` directory in the original PR. 
https://github.com/autowarefoundation/autoware.universe/pull/6893
https://github.com/orgs/autowarefoundation/discussions/3862
Message types are modified according to the table in [this comment](https://github.com/orgs/autowarefoundation/discussions/3862#discussioncomment-9638820). …

feat!: replace autoware_auto_msgs with autoware_msgs for launch files

---

common/object_recognition_utils/test/src/test_predicted_path_utils.cpp

This fixes the failing test for object_recognition_utils caused by [migration to autoware_msgs](https://github.com/orgs/autowarefoundation/discussions/4803).
New autoware_msgs does not have the bound limit for predicted path so there are tests that are no longer needed.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributin …

feat(object_recognition_utils): fix failing test

---

.github/workflows/dco.yaml

Signed-off-by: Kotaro Yoshimoto pythagora.yoshimoto@gmail.com
DCO check is not working now.
https://github.com/dcoapp/app/issues/211
Alternatively, I added this workflow as proposed in the issue.
Well done!
https://github.com/autowarefoundation/autoware.universe/actions/runs/9377200258/job/25818372246 …

chore(ci): add a workflow for DCO check to avoid DCO bot system failure

---

planning/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp
planning/behavior_path_goal_planner_module/src/goal_planner_module.cpp
planning/behavior_path_lane_change_module/src/scene.cpp
planning/behavior_path_planner_common/include/behavior_path_planner_common/turn_signal_decider.hpp
planning/behavior_path_planner_common/src/turn_signal_decider.cpp

Sometimes, bpp module outputs unnecessary turn signal during multiple module execution. When multiple modules are running in series, the latter module is dominant for the path followed by Ego, so if there is an overlap in the turn signal section, it is overwritten by the latter module's signal.
https://github.com/autowarefoundation/autoware.universe/assets/44889564/752f1608-63f7-42d3-b039-12d3d77fd5a7
Ticket: [TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT1-5329)
](https://evaluation.tier4.jp/evaluation/reports/de64be41-da90-5413-88dd-c853ea522213?project_id=prd_jt)
Fix turn signal inconsistency. …

fix(bpp): overwrite turn signal by latter module

---

simulator/simple_planning_simulator/launch/simple_planning_simulator.launch.py

The `odom` frame is not used in Autoware so this PR removes the `odom` static publisher from the `simple_planning_simulator` launch file.
Psim.

refactor(simple_planning_simulator): remove static odom tf publisher

---

planning/surround_obstacle_checker/include/surround_obstacle_checker/node.hpp
planning/surround_obstacle_checker/src/node.cpp

feat(surround_obstacle_checker): use polling subscriber

---

system/emergency_handler/include/emergency_handler/emergency_handler_core.hpp
system/emergency_handler/src/emergency_handler/emergency_handler_core.cpp
system/mrm_handler/include/mrm_handler/mrm_handler_core.hpp
system/mrm_handler/src/mrm_handler/mrm_handler_core.cpp

Currently, both handlers always output a DRIVE gear when an emergency message makes the ego stop, which causes a very dangerous behavior (at least in simulations) when the ego vehicle is going backwards and an emergency is triggered -> since the gear is changed to Drive and the ego is going backwards, the simulator gives a positive velocity to the ego and makes it shoot forward (See video). Note that I used a script to simulate the AEB module activating to make these tests easier.
[Screencast from 2024年05月28日 15時24分35秒.webm](https://github.com/autowarefoundation/autoware.universe/assets/25967964/02e668a6-622c-4e02-8b41-eb0b9b79ba22)
After this PR fix: 
https://github.com/autowarefoundation/autoware.universe/assets/25967964/edb4f21d-b009-4517-a8bf-9a04f342974c
PSIM …

fix(emergency_handler,mrm_handler): check for ego speed when determining the gear command

---

system/mrm_handler/src/mrm_handler/mrm_handler_core.cpp

Refactor the state machine
PSim

refactor(mrm_handler): use switch for state machine

---

build_depends.repos

This makes the same change that we made to autoware.repos in autoware repository in [this PR](https://github.com/autowarefoundation/autoware/pull/4141).
This should make the build faster in the build-and-test CI. For the details, please check the above PR.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request …

chore(ci): add faster ament_cmake to build_depends.repos

---

.github/workflows/build-and-test.yaml

Since this job is triggered once the PR is merged to main, we will run it on self hosted instances to not burden the github hosted runners.
This way, more urgent `build-and-test-differential` jobs can keep running on the github hosted instances.
If we merge 5 PRs in a short amount of time, we will have 10 `build-and-test` (cuda and non-cuda) jobs start, each taking about 2 hours. And these are not even urgent since they are already merged.
But they will occupy 10/20 of the GitHub Hosted Runners for the next 2 hours.
The `build-and-test-differential` jobs will occupy the rest and most of the very small jobs will be unable to run for a long while. …

ci(build-and-test): run on self hosted

---

sensing/pointcloud_preprocessor/CMakeLists.txt
sensing/pointcloud_preprocessor/docs/vector-map-inside-area-filter.md
sensing/pointcloud_preprocessor/include/pointcloud_preprocessor/utility/utilities.hpp
sensing/pointcloud_preprocessor/include/pointcloud_preprocessor/vector_map_filter/vector_map_inside_area_filter.hpp
sensing/pointcloud_preprocessor/src/utility/utilities.cpp
sensing/pointcloud_preprocessor/src/vector_map_filter/vector_map_inside_area_filter.cpp
sensing/pointcloud_preprocessor/test/test_utilities.cpp

This PR add features to `VectorMapInsideAreaFilterComponent`, which is used to filter pointcloud by polygon defined in lanelet map with `no_obstacle_segmentation_area` attribute.
This PR enables the node to use z information to filter pointcloud so that it will not remove too much pointcloud.
utilities functions update is tested with gtest. …

feat(pointcloud_preprocessor): add z filter in vector map inside 

---

localization/pose2twist/CMakeLists.txt
localization/pose2twist/README.md
localization/pose2twist/include/pose2twist/pose2twist_core.hpp
localization/pose2twist/src/pose2twist_core.cpp
localization/pose2twist/test/test_angular_velocity.cpp

I have modified the method for obtaining angular velocity from pose.
In the previous approach, incorrect values could be obtained when pitch or yaw were not zero.
Additionally, I have added tests to verify the correctness of my implementation.
I have confirmed that twist is being output by launching logging_simulator and pose_twist.launch.
Furthermore, I have verified that the estimated angular velocity does not differ from the previous method.
(Since roll and pitch are sufficiently small in the sample rosbag, the previous method also estimate the correct angular velocity.)
gtest has been passed.
`colcon test --event-handlers console_cohesion+ summary+ --packages-select pose2twist`
Not applicable. 
Interface does not change. …

fix(pose2twist): compute angular velocity through quaternion

---

planning/behavior_path_sampling_planner_module/src/sampling_planner_module.cpp

Fixes https://github.com/autowarefoundation/autoware.universe/issues/7209

refactor(sampling_planner_module): use std::make_shared

---

launch/tier4_planning_launch/launch/planning.launch.xml
launch/tier4_planning_launch/package.xml
planning/.pages
planning/autoware_planning_test_manager/README.md
planning/planning_validator/CMakeLists.txt
planning/planning_validator/README.md
planning/planning_validator/config/planning_validator_plotjugler_config.xml
planning/planning_validator/image/planning_validator.drawio.svg
planning/planning_validator/include/autoware_planning_validator/debug_marker.hpp
planning/planning_validator/include/autoware_planning_validator/planning_validator.hpp
planning/planning_validator/include/autoware_planning_validator/utils.hpp
planning/planning_validator/launch/invalid_trajectory_publisher.launch.xml
planning/planning_validator/launch/planning_validator.launch.xml
planning/planning_validator/package.xml
planning/planning_validator/src/debug_marker.cpp
planning/planning_validator/src/invalid_trajectory_publisher/invalid_trajectory_publisher.cpp
planning/planning_validator/src/invalid_trajectory_publisher/invalid_trajectory_publisher.hpp
planning/planning_validator/src/planning_validator.cpp
planning/planning_validator/src/utils.cpp
planning/planning_validator/test/src/test_planning_validator_functions.cpp
planning/planning_validator/test/src/test_planning_validator_node_interface.cpp
planning/planning_validator/test/src/test_planning_validator_pubsub.cpp

rename package to autoware_planning_validator from planninga_validator.
Part of:
check psim and echo topic with following command
```
ros2 topic echo /planning/autoware_planning_validator/validation_status
```
get the following output
```
---
stamp:
sec: 1717669025
nanosec: 502505657
is_valid_size: true
is_valid_finite_value: true
is_valid_interval: true
is_valid_relative_angle: true
is_valid_curvature: true
is_valid_lateral_acc: true
is_valid_longitudinal_max_acc: true
is_valid_longitudinal_min_acc: true
is_valid_steering: true
is_valid_steering_rate: true
is_valid_velocity_deviation: true
is_valid_distance_deviation: true
is_valid_longitudinal_distance_deviation: true
is_valid_forward_trajectory_length: true
trajectory_size: …
```

refactor(planning_validator)!: prefix package and namespace with autoware

---

localization/gyro_odometer/include/gyro_odometer/diagnostics_module.hpp
localization/gyro_odometer/include/gyro_odometer/gyro_odometer_core.hpp
localization/gyro_odometer/src/diagnostics_module.cpp
localization/gyro_odometer/src/gyro_odometer_core.cpp
localization/gyro_odometer/test/test_gyro_odometer_helper.cpp
localization/gyro_odometer/test/test_gyro_odometer_helper.hpp
localization/gyro_odometer/test/test_gyro_odometer_pubsub.cpp

This PR applies some suggestions from the linter to `localization/gyro_odometer`.
Fixed:
- rename 
- use initialization list for some variable (in test)
- removed default destructor
- rename ambiguous function name (collide with some library)
- remove "using declaration" in header file
<details>
```
#!/bin/bash
set -eux
TARGET_DIR=$1
exit 1
fi
set +eux
set -eux
fdfind -e cpp -e hpp …
```

refactor(gyro_odometer): apply static analysis

---

evaluator/perception_online_evaluator/include/perception_online_evaluator/metrics/metric.hpp
evaluator/perception_online_evaluator/include/perception_online_evaluator/metrics_calculator.hpp
evaluator/perception_online_evaluator/include/perception_online_evaluator/perception_online_evaluator_node.hpp
evaluator/perception_online_evaluator/src/metrics_calculator.cpp
evaluator/perception_online_evaluator/src/perception_online_evaluator_node.cpp
evaluator/perception_online_evaluator/test/test_perception_online_evaluator_node.cpp

this PR need to wait for driving log replayer
Reverts autowarefoundation/autoware.universe#7118
https://github.com/autowarefoundation/autoware.universe/pull/7100
Previously, only stat with `max`, `mean`, and `min` as keys could be handled in diagnostics, but this PR allows `metric_value` with a single value.
This is to allow only one value to be included in metrics such as object counts, since all stat values are the same, which is redundant.
- stat type
```
- level: "\0"
name: predicted_path_deviation_variance_CAR_5.00
message: ''
values:
- key: min
value: '0.039821'
- key: max
value: '0.039821'
- key: mean
value: '0.039821'
```
- metric_value type
```
- level: "\0"
name: interval_average_objects_count_UNKNOWN_r100.00_h10.00
message: ''
values:
- key: …
```

fix(perception_online_evaluator):  add metric_value not only stat (#7100)(#7118) (revert of revert)

---

planning/planning_validator/launch/planning_validator.launch.xml

change node name in the [PR](https://github.com/autowarefoundation/autoware.universe/pull/7320) and it causes diag error.
As a result, autoware engage from RVIZ gui was not working.
The error was following by clicking the gui bottom
```
[service_log_checker_node-4] [ERROR 1717762673.010612554] [system.service_log_checker]: /api/operation_mode/change_to_autonomous: status code 1 'The mode change is blocked by the system.' (/default_ad_api/node/operation_mode) (set_error():84)
```
confirmed engage works with psim …

fix(autoware_planning_validator): revert node name change

---

launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.xml
launch/tier4_planning_launch/launch/scenario_planning/lane_driving/motion_planning/motion_planning.launch.xml

Currently, the autoware cannot be launched successfully due to the unexpected modules registered to behavior_path_planner and motion_velocity_planner.
This PR fixed this issue.
simple planning simulator
The autoware can be launched successfully.

fix(tier4_planning_launch): unexpected modules were registered

---

planning/autoware_velocity_smoother/include/autoware_velocity_smoother/node.hpp
planning/autoware_velocity_smoother/src/node.cpp

feat(autoware_velocity_smoother): use polling subscriber

---

control/joy_controller/include/joy_controller/joy_controller.hpp
control/joy_controller/package.xml
control/joy_controller/src/joy_controller/joy_controller_node.cpp

The same as https://github.com/autowarefoundation/autoware.universe/pull/6997 based on [the discussion](https://github.com/orgs/autowarefoundation/discussions/4612), the polling subscriber is used in the obstacle_avoidance_planner.
Nothing …

feat(joy_controller): use polling subscriber

---

common/tier4_autoware_utils/include/tier4_autoware_utils/ros/transform_listener.hpp

In the simple planning simulator, before putting the ego pose, a lot of warning by map_based_prediction is shown in the terminal as shown in the following figur.e
This PR suppresses the frequency of this warning.
psim
Nothing

feat(tier4_autoware_utils): suppress too many warning of TF transform failure

---

perception/multi_object_tracker/src/debugger/debug_object.cpp

In the planning simulator, the multi-object-tracker crash was reported.
https://github.com/autowarefoundation/autoware.universe/pull/7127#issuecomment-2139952978
```
[multi_object_tracker_node-49] *** Aborted at 1717082878 (unix time) try "date -d @1717082878" if you are using GNU date ***
[multi_object_tracker_node-49] PC: @                0x0 (unknown)
[multi_object_tracker_node-49] *** SIGSEGV (@0x20) received by PID 461172 (TID 0x7df1e7c2f8c0) from PID 32; stack trace: ***
[multi_object_tracker_node-49]     @     0x7df1e548a206 (unknown)
[multi_object_tracker_node-49]     @     0x7df1e7a45320 (unknown)
[multi_object_tracker_node-49]     @     0x7df1e4932f0f TrackerObjectDebugger::process()
[multi_object_tracker_node-49]     @     0x7df1e48f8e08 TrackerDebugger::publishObjectsMarkers() …
```

fix(multi_object_tracker): fix segmentation fault bug of the debug object process 

---

control/lane_departure_checker/include/autoware_lane_departure_checker/lane_departure_checker_node.hpp
control/lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker_node.cpp
planning/behavior_path_planner/package.xml

after the [PR](https://github.com/autowarefoundation/autoware.universe/pull/7325) is merged
run psim …

feat(autoware_lane_departure_checker): use polling subscriber

---

control/operation_mode_transition_manager/package.xml
control/pure_pursuit/package.xml
control/shift_decider/package.xml

Adding as maintainer @takayuki5168 to the following control modules
1. Operation mode transition manager
2. Pure pursuit
3. Shift Decider

chore(control): add maintainer for several control modules

---

common/tier4_autoware_utils/include/tier4_autoware_utils/ros/polling_subscriber.hpp

enable rclcpp-like usage
```
auto sub_autoware_state_ptr =
tier4_autoware_utils::InterProcessPollingSubscriber<AutowareState>::create_subscription(
this, "/autoware/state");
```
I replaced a subscriber in AEB module 
```
auto sub_autoware_state_ptr =
tier4_autoware_utils::InterProcessPollingSubscriber<AutowareState>::create_subscription(
this, "/autoware/state");
```
and checked it works
none
none …

feat(tier4_autoware_utils): add InterProcessPollingSubscriber helper factory

---

launch/tier4_planning_launch/launch/scenario_planning/lane_driving/motion_planning/motion_planning.launch.xml

A previous PR changed the input topics of the `obstacle_velocity_limiter`, causing the `motion_velocity_planner` output to be ignored (see https://github.com/autowarefoundation/autoware.universe/commit/d2f41bc62e6a25bec56b767b0ef19987a6e4c0d6#diff-68856cde486208f016738f11d6bd8defc247a7f8c5c55b9d739d928d778f94c4L149).
The present PR fixes the issue.
Psim
Modules of the `motion_velocity_planner` (currently only the `out_of_lane` module) are working as expected.
None …

fix(motion_planning.launch): fix input traj of obstacle_velocity_limiter

---

planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/filter_predicted_objects.cpp
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware_motion_velocity_planner_common/planner_data.hpp
planning/motion_velocity_planner/autoware_motion_velocity_planner_node/src/node.cpp
planning/motion_velocity_planner/autoware_motion_velocity_planner_node/src/node.hpp

Use a polling subscriber for the topics of the `motion_velocity_planner`, improving the performance of the node.
Psim

feat(motion_velocity_planner): use polling subscriber to efficiently get messages

---

.github/CODEOWNERS
planning/.pages
planning/autoware_behavior_velocity_planner/README.md
planning/autoware_behavior_velocity_planner/package.xml
planning/autoware_behavior_velocity_planner/test/src/test_node_interface.cpp
planning/autoware_behavior_velocity_run_out_module/README.md
planning/behavior_velocity_occlusion_spot_module/plugins.xml

Fix issues with documentation links, package dependencies, and codeowners introduces by https://github.com/autowarefoundation/autoware.universe/pull/7357

fix(occlusion_spot_module): fix dependencies, docs, codeowners

---

localization/pose_initializer/src/pose_initializer/copy_vector_to_array.hpp
localization/pose_initializer/src/pose_initializer/gnss_module.cpp
localization/pose_initializer/src/pose_initializer/gnss_module.hpp
localization/pose_initializer/src/pose_initializer/ndt_module.cpp
localization/pose_initializer/src/pose_initializer/pose_initializer_core.cpp
localization/pose_initializer/src/pose_initializer/pose_initializer_core.hpp
localization/pose_initializer/src/pose_initializer/yabloc_module.cpp
localization/pose_initializer/test/test_copy_vector_to_array.cpp

Fixed all of the points raised by clang-tidy, cpplint and cppcheck.
<details>
```
#!/bin/bash
set -eux
TARGET_DIR=$1
exit 1
fi
set +eux
set -eux
fdfind -e cpp -e hpp --full-path ${TARGET_DIR} | xargs -P $(nproc) -I{} cpplint {}
fdfind -e cpp -e hpp --full-path ${TARGET_DIR} | xargs -P $(nproc) -I{} clang-tidy -p build/ {}
```
</details>
---
before PR
<details>
<summary>output from above commands</summary>
```
$ ./check_linter.sh …
```

refactor(pose_initializer): apply static analysis

---

localization/localization_util/src/util_func.cpp
localization/localization_util/test/test_smart_pose_buffer.cpp

This PR applies some suggestions from the linter to `localization/localization_util`.
Fixed:
- remove meaningless conditions
- (removed unused codes in test)
the notion "style: Variable 'ex' can be..." from cppcheck is fixed in https://github.com/autowarefoundation/autoware.universe/pull/7278
<details>
```
#!/bin/bash
set -eux
TARGET_DIR=$1
exit 1
fi
set +eux
set -eux
fdfind -e cpp -e hpp --full-path ${TARGET_DIR} | xargs -P $(nproc) …
```

refactor(localization_util): apply static analysis

---

planning/planning_validator/include/autoware_planning_validator/planning_validator.hpp
planning/planning_validator/src/planning_validator.cpp
planning/planning_validator/test/src/test_planning_validator_pubsub.cpp

after the [PR](https://github.com/autowarefoundation/autoware.universe/pull/7320) is merged
check psim and echo topic with following command
```
ros2 topic echo /planning/autoware_planning_validator/validation_status
```
get the following output
```
---
stamp:
sec: 1717738132
nanosec: 36705836
is_valid_size: true
is_valid_finite_value: true
is_valid_interval: true
is_valid_relative_angle: true
is_valid_curvature: true
is_valid_lateral_acc: true
is_valid_longitudinal_max_acc: true
is_valid_longitudinal_min_acc: true
is_valid_steering: true …
```

feat(planning_validator): use polling subscriber

---

map/map_tf_generator/include/map_tf_generator/uniform_random.hpp
map/map_tf_generator/src/pcd_map_tf_generator_node.cpp
map/map_tf_generator/src/vector_map_tf_generator_node.cpp
map/map_tf_generator/test/test_uniform_random.cpp

This PR applies some suggestions from the linter to `map/map_tf_generator`.
Fixed:
- variable name changed from VAR_NAME to var_name
- use initialization list for some variable
Not fixed:
- using [std, boost]::variant for safe access
- for speed concern
<details>
```
#!/bin/bash
set -eux
TARGET_DIR=$1
exit 1
fi
set +eux
set -eux
fdfind -e cpp -e hpp --full-path ${TARGET_DIR} | xargs -P …
```

refactor(map_tf_generator): apply static analysis

---

.github/workflows/build-and-test-differential-arm64.yaml
.github/workflows/build-and-test-differential.yaml

Right now this step takes about 2m22s.
This happens for all jobs even before checking if any relevant files are changed.
**Before:** it downloaded the entire history and branches of the repository.
**After:** it only downloads the latest state of the repo (shallow copy).
This PR CI, now it takes 5s (down from 2m22s). …

ci(build-and-test-differential): set checkout fetch-depth to 1

---

common/tier4_autoware_utils/include/tier4_autoware_utils/ros/polling_subscriber.hpp

Enable accumulation of past data with a polling subscriber.
If you want to accumulate 100 pieces of past data, declare the polling subscriber as follows.
```cpp
tier4_autoware_utils::InterProcessPollingSubscriber<nav_msgs::msg::Odometry, 100>::SharedPtr sub_odom_;
```
By doing so, takeData returns a history as a std::vector.
```cpp
std::vector<std::shared_ptr<const nav_msgs::msg::Odometry>> msgs = sub_odom_->takeData();
```
It has been confirmed that it works correctly in [this branch](https://github.com/yhisaki/autoware.universe/tree/polling_subscriber-scenario_selector).
This feature is implemented using [template specialization](https://en.cppreference.com/w/cpp/language/partial_specialization) and [SFINAE](https://en.cppreference.com/w/cpp/language/sfinae).
Not …

feat(polling_subscriber): polling srbscriber for multiple data

---

common/tier4_autoware_utils/include/tier4_autoware_utils/ros/polling_subscriber.hpp
control/lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker_node.cpp

add `takeNewData` to polling subscriber
use case: current PollingSubscriber::takeData() returns the previously-taken data if popping from dds queue failed. But sometimes we want to know if the taken-data is "stale". For example we want to process lanelet_map message only when the process is called initially or the map has changed by differential loading.
lane_departure_checker becomes lightweight.
none
none …

feat(tier4_autoware_utils): add the API to check if taken data is stale

---

planning/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware_behavior_path_static_obstacle_avoidance_module/data_structs.hpp
planning/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware_behavior_path_static_obstacle_avoidance_module/helper.hpp
planning/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp
planning/autoware_behavior_path_static_obstacle_avoidance_module/src/shift_line_generator.cpp

Previously, the static_obstacle_avoidance module inserted stop point only for object whom the ego could avoid after deceleration. On ther other hand, this module temporaily limits drivable area width to prevent the ego from stopping with straddling multiple lanes. But if it doesn't insert stop point, the ego maybe get closer to target object than minimum distance for avoidance.
In this PR, I added logic to insert stop point so that the ego can avoid object after the traffic signal changes GREEEN.
https://github.com/autowarefoundation/autoware.universe/assets/44889564/55ea1ca5-d586-4971-ad49-b0ec7bc32be6
https://github.com/autowarefoundation/autoware.universe/assets/44889564/eeedbfcf-4e46-4cc3-9226-1fd1e5baa385 …

feat(avoidance): keep enough distance to avoid object in front of red signal

---

launch/tier4_control_launch/package.xml
perception/autoware_crosswalk_traffic_light_estimator/src/node.cpp

I encountered the following error:
```
/home/shintarosakoda/autoware/src/universe/autoware.universe/perception/autoware_crosswalk_traffic_light_estimator/src/node.cpp:14:10: fatal error: crosswalk_traffic_light_estimator/node.hpp: そのようなファイルやディレクトリはありません
14 | #include "crosswalk_traffic_light_estimator/node.hpp"
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
and
```
+ rosdep install -y --from-paths src --ignore-src --rosdistro humble
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
tier4_control_launch: Cannot locate rosdep definition for [external_cmd_selector]
```
Related PR
* https://github.com/autowarefoundation/autoware.universe/pull/7384
* https://github.com/autowarefoundation/autoware.universe/pull/7365
I have …

fix(tier4_control_launch, crosswalk_traffic_light_estimator): fix a mistake when adding prefixes

---

control/autoware_control_validator/include/autoware_control_validator/control_validator.hpp
control/autoware_control_validator/src/control_validator.cpp

Add polling subscriber to control validator
PSIM

feat(autoware_control_validator): add polling subcribers

---

perception/autoware_map_based_prediction/include/map_based_prediction/map_based_prediction_node.hpp
perception/autoware_map_based_prediction/src/map_based_prediction_node.cpp

feat(map based prediction): use polling subscriber

---

planning/autoware_behavior_velocity_planner/package.xml

fix 
```
+ rosdep install -y --from-paths src --ignore-src --rosdistro humble
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
autoware_behavior_velocity_planner: Cannot locate rosdep definition for [behavior_velocity_no_stopping_area_module]
```
rosdep install …

fix(behavior_velocity_planner): fix test_depend

---

control/operation_mode_transition_manager/src/node.cpp
control/operation_mode_transition_manager/src/node.hpp

Applying polling subscriber based on [the discussion](https://github.com/orgs/autowarefoundation/discussions/4612).
Run PSIM and ensure that vehicle is engaged.

feat(operation_mode_transition_manager): use polling subscriber

---

control/pure_pursuit/include/pure_pursuit/pure_pursuit_node.hpp
control/pure_pursuit/src/pure_pursuit/pure_pursuit_node.cpp

Applying polling subscriber based on [the discussion](https://github.com/orgs/autowarefoundation/discussions/4612).
Change lateral controller to pure_pursuit.
Run PSIM and ensure that vehicle is engaged.

feat(pure_pursuit): add polling subscriber

---

control/autoware_shift_decider/include/autoware_shift_decider/autoware_shift_decider.hpp
control/autoware_shift_decider/package.xml
control/autoware_shift_decider/src/autoware_shift_decider.cpp

Applying polling subscriber based on [the discussion](https://github.com/orgs/autowarefoundation/discussions/4612).
Run PSIM and ensure that vehicle is engaged.

feat(shift_decider): use polling subscriber

---

vehicle/autoware_accel_brake_map_calibrator/include/autoware_accel_brake_map_calibrator/accel_brake_map_calibrator_node.hpp
vehicle/autoware_accel_brake_map_calibrator/package.xml
vehicle/autoware_accel_brake_map_calibrator/src/accel_brake_map_calibrator_node.cpp

In this PR, instead of getting msg in callback, it is changed to get msg using takeData function of polling_subscriber in utils.
Recreate PR from https://github.com/autowarefoundation/autoware.universe/pull/7282 to handle conflicts happned from this PR merge https://github.com/autowarefoundation/autoware.universe/pull/7351
```
// terminal1
ros2 launch accel_brake_map_calibrator accel_brake_map_calibrator.launch.xml rviz:=true use_sim_time:=true
// terminal2
ros2 bag play <rosbag file> --clock
```
The module works as before. By the way, I only have a rosbag file that was collected with the old messages (autoware_auto_* msgs). I don't have any rosbag files with the new messages (autoware_* msgs). So, I confirmed with the old rosbag file and replaced the messages later. …

feat(accel_brake_map_calibrator): replace polling takeData function with the callback function

---

planning/autoware_behavior_path_start_planner_module/src/shift_pull_out.cpp

The issue is unexpected high curvature was observed when high lateral acceleration is applied for the path generation in the start planner.
**lateral_acc = 0.4**  (maximum curvature is 0.07)
but curvature calculated in the `planning_evaluator` exceeds the expected curvature 
```
--
name: curvature
message: ''
values:
- key: min
value: '-0.077920683269826679'
- key: max
value: '0.029597384047832055'
- key: mean
value: '-0.00717520342333883057143'
--
```
After applying this PR
**lateral_acc = 0.4**  (maximum curvature is 0.07)
```
--
name: curvature
message: ''
values:
- key: min
value: '-0.047812135579225153'
- key: max
value: '0.039412954283098052'
- key: mean
value: '-0.0140280992746446812733'
- level: "\0"
--
```
The issue seems to be that the path points …

fix(start_planner): set minimum velocity to avoid high curvature in trajectroy  

---

planning/autoware_behavior_path_dynamic_obstacle_avoidance_module/test/test_behavior_path_planner_node_interface.cpp
planning/autoware_behavior_path_external_request_lane_change_module/test/test_behavior_path_planner_node_interface.cpp
planning/autoware_behavior_path_lane_change_module/test/test_behavior_path_planner_node_interface.cpp
planning/autoware_behavior_path_planner/test/test_autoware_behavior_path_planner_node_interface.cpp
planning/autoware_behavior_path_planner_common/include/autoware_behavior_path_planner_common/data_manager.hpp
planning/autoware_behavior_path_planner_common/include/autoware_behavior_path_planner_common/utils/drivable_area_expansion/drivable_area_expansion.hpp
planning/autoware_behavior_path_planner_common/include/autoware_behavior_path_planner_common/utils/drivable_area_expansion/footprints.hpp
planning/autoware_behavior_path_planner_common/include/autoware_behavior_path_planner_common/utils/drivable_area_expansion/map_utils.hpp
planning/autoware_behavior_path_planner_common/include/autoware_behavior_path_planner_common/utils/drivable_area_expansion/parameters.hpp
planning/autoware_behavior_path_planner_common/include/autoware_behavior_path_planner_common/utils/drivable_area_expansion/path_projection.hpp
planning/autoware_behavior_path_planner_common/include/autoware_behavior_path_planner_common/utils/drivable_area_expansion/static_drivable_area.hpp
planning/autoware_behavior_path_planner_common/include/autoware_behavior_path_planner_common/utils/drivable_area_expansion/types.hpp
planning/autoware_behavior_path_planner_common/src/utils/drivable_area_expansion/drivable_area_expansion.cpp
planning/autoware_behavior_path_planner_common/src/utils/drivable_area_expansion/footprints.cpp
planning/autoware_behavior_path_planner_common/src/utils/drivable_area_expansion/map_utils.cpp
planning/autoware_behavior_path_planner_common/src/utils/drivable_area_expansion/static_drivable_area.cpp
planning/autoware_behavior_path_planner_common/test/test_drivable_area_expansion.cpp
planning/autoware_behavior_path_side_shift_module/test/test_behavior_path_planner_node_interface.cpp
planning/autoware_behavior_path_static_obstacle_avoidance_module/test/test_behavior_path_planner_node_interface.cpp

Change namespace from `drivable_area_expansion`  to `autoware::behavior_path_planner::drivable_area_expansion`.
Psim

refactor(behavior_path_planner_common): fix namespace of drivable_area_expansion

---

.github/workflows/build-and-test-differential-arm64.yaml
.github/workflows/build-and-test-differential.yaml

Previous PRs (in chrono order):
- https://github.com/autowarefoundation/autoware.universe/pull/7408 (caused failure)
- https://github.com/autowarefoundation/autoware.universe/pull/7441 (reverted)
- https://github.com/autowarefoundation/autoware-github-actions/pull/299 (fixed the source of failure)
Now this PR aims to fetch only the necessary commits (PR commits) to get the list of modified packages.
See the tests made in:
- https://github.com/autowarefoundation/autoware-github-actions/pull/299
- Both failure and success conditions were tested.
- Tests were done on a complex PR with various ugly merge commits to make sure it won't fail.
Build and test differential jobs will be about 2m20s faster. …

ci(build-and-test-differential): fetch only necessary commits

---

localization/pose_estimator_arbiter/example_rule/src/pose_estimator_arbiter/rule_helper/grid_key.hpp
localization/pose_estimator_arbiter/example_rule/src/pose_estimator_arbiter/rule_helper/pcd_occupancy.cpp
localization/pose_estimator_arbiter/example_rule/src/pose_estimator_arbiter/rule_helper/pcd_occupancy.hpp
localization/pose_estimator_arbiter/example_rule/src/pose_estimator_arbiter/rule_helper/pose_estimator_area.cpp
localization/pose_estimator_arbiter/example_rule/src/pose_estimator_arbiter/rule_helper/pose_estimator_area.hpp
localization/pose_estimator_arbiter/example_rule/src/pose_estimator_arbiter/switch_rule/pcd_map_based_rule.cpp
localization/pose_estimator_arbiter/example_rule/src/pose_estimator_arbiter/switch_rule/pcd_map_based_rule.hpp
localization/pose_estimator_arbiter/example_rule/src/pose_estimator_arbiter/switch_rule/vector_map_based_rule.cpp
localization/pose_estimator_arbiter/example_rule/src/pose_estimator_arbiter/switch_rule/vector_map_based_rule.hpp
localization/pose_estimator_arbiter/example_rule/test/test_pcd_map_based_rule.cpp
localization/pose_estimator_arbiter/example_rule/test/test_rule_helper.cpp
localization/pose_estimator_arbiter/example_rule/test/test_vector_map_based_rule.cpp
localization/pose_estimator_arbiter/src/pose_estimator_arbiter/pose_estimator_type.hpp
localization/pose_estimator_arbiter/src/pose_estimator_arbiter/shared_data.hpp
localization/pose_estimator_arbiter/src/pose_estimator_arbiter/stopper/base_stopper.hpp
localization/pose_estimator_arbiter/src/pose_estimator_arbiter/stopper/stopper_artag.hpp
localization/pose_estimator_arbiter/src/pose_estimator_arbiter/stopper/stopper_eagleye.hpp
localization/pose_estimator_arbiter/src/pose_estimator_arbiter/stopper/stopper_ndt.hpp
localization/pose_estimator_arbiter/src/pose_estimator_arbiter/stopper/stopper_yabloc.hpp
localization/pose_estimator_arbiter/src/pose_estimator_arbiter/switch_rule/base_switch_rule.hpp
localization/pose_estimator_arbiter/src/pose_estimator_arbiter/switch_rule/enable_all_rule.cpp
localization/pose_estimator_arbiter/src/pose_estimator_arbiter/switch_rule/enable_all_rule.hpp

This PR applies some suggestions from the linter to `localization/pose_estimator_arbiter`.
Fixed:
- add missing includes
- add explicit constructor definition (e.g. copy constructor)
- [modernize-pass-by-value](https://clang.llvm.org/extra/clang-tidy/checks/modernize/pass-by-value.html)
- instead of using const-reference, pass value and then move
- change class name in tests to avoid name collision
- change private variable name (adding `_`)
not Fixed:
<details>
```
#!/bin/bash
set -eux
TARGET_DIR=$1
echo "This script must be run in …
```

refactor(pose_estimator_arbiter): apply static analysis

---

planning/autoware_behavior_path_planner_common/include/autoware_behavior_path_planner_common/utils/parking_departure/geometric_parallel_parking.hpp
planning/autoware_behavior_path_planner_common/src/utils/parking_departure/geometric_parallel_parking.cpp
planning/autoware_behavior_path_start_planner_module/config/start_planner.param.yaml
planning/autoware_behavior_path_start_planner_module/src/manager.cpp

Because of removing necessary parameter in this [PR](https://github.com/autowarefoundation/autoware_launch/pull/1022), geometric path(path includs dry steering) can't be generated.
In this PR, 
- restore the param. 
- change the variable name from `pull_out_path_interval` to `pull_out_arc_path_interval`
parameter change is in this [PR](https://github.com/autowarefoundation/autoware_launch/pull/1027)
run psim and confirmed geometric path can be generated. …

fix(start_planner): redefine the necessary parameters

---

localization/pose_instability_detector/include/autoware/pose_instability_detector/pose_instability_detector.hpp
localization/pose_instability_detector/src/pose_instability_detector.cpp

This PR applies some suggestions from the linter to `localization/pose_instability_detector`.
Fixed:
- removed unused private variable
- change camelCase to snake_case
- add initialization to uninitialized variable
- add `const` or `static` to method which can be it
<details>
```
#!/bin/bash
set -eux
TARGET_DIR=$1
exit 1
fi
set +eux
set -eux
fdfind -e cpp -e hpp --full-path ${TARGET_DIR} | xargs -P $(nproc) -I{} cpplint {}
fdfind -e cpp …
```

refactor(pose_instability_detector): apply static analysis

---

common/tier4_autoware_utils/include/tier4_autoware_utils/ros/polling_subscriber.hpp
control/autoware_autonomous_emergency_braking/include/autoware_autonomous_emergency_braking/node.hpp
planning/autoware_behavior_velocity_planner/src/node.hpp
planning/autoware_surround_obstacle_checker/include/autoware_surround_obstacle_checker/node.hpp
planning/motion_velocity_planner/autoware_motion_velocity_planner_node/src/node.hpp

Use single depth sensor data qos for PointCloud polling subscribers

fix(planning): set single depth sensor data qos for pointlcoud polling subscribers

---

.github/workflows/pre-commit-autoupdate.yaml

Add `pre-commit-autoupdate` from:
- https://github.com/autowarefoundation/autoware_common/blob/a7e776a47e309fba1b1ab7c14ecd2d51aa2e39f7/.github/workflows/pre-commit-autoupdate.yaml
We can set up the sync-files job later.

ci(pre-commit-autoupdate): add new workflow

---

localization/yabloc/yabloc_image_processing/include/yabloc_image_processing/graph_segment/histogram.hpp
localization/yabloc/yabloc_image_processing/include/yabloc_image_processing/lanelet2_overlay/lanelet2_overlay.hpp
localization/yabloc/yabloc_image_processing/include/yabloc_image_processing/line_segment_detector/line_segment_detector.hpp
localization/yabloc/yabloc_image_processing/include/yabloc_image_processing/segment_filter/segment_filter.hpp
localization/yabloc/yabloc_image_processing/src/graph_segment/graph_segment_core.cpp
localization/yabloc/yabloc_image_processing/src/graph_segment/similar_area_searcher.cpp
localization/yabloc/yabloc_image_processing/src/lanelet2_overlay/lanelet2_overlay_core.cpp
localization/yabloc/yabloc_image_processing/src/line_segment_detector/line_segment_detector_core.cpp
localization/yabloc/yabloc_image_processing/src/line_segments_overlay/line_segments_overlay_core.cpp
localization/yabloc/yabloc_image_processing/src/segment_filter/segment_filter_core.cpp
localization/yabloc/yabloc_image_processing/src/undistort/undistort_node.cpp

This PR applies some suggestions from the linter to `localization/yabloc/yabloc_image_processing`.
Fixed:
- add `_` to private variable
- align variable name in header's definition and the implementation
- LOCAL_VAR to local_var
- add or removed keyword from function/method which linter suggested
- remove `reinterpret_cast`
- [cv::Mat](https://docs.opencv.org/4.5.4/d3/d63/classcv_1_1Mat.html) takes `void *data`
not Fixed:
- pointer arithmetic ([cppcoreguidelines-pro-bounds-pointer-arithmetic](https://releases.llvm.org/13.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/cppcoreguidelines-pro-bounds-pointer-arithm …

refactor(yabloc_image_processing): apply static analysis

---

planning/autoware_behavior_path_planner/src/behavior_path_planner_node.cpp

This PR fixes a bug where the current route lanelet was not properly reset when driving manually.
The previous condition used `planner_manager_->hasApprovedModules()` which would be true when the goal or dynamic obstacle avoidance modules were running.
The new condition uses `planner_manager_->hasNonAlwaysExecutableApprovedModules()` which ignores the goal and dynamic obstacle avoidance modules.
Psim and made sure that a previously failing scenario is now passing. …

fix(behavior_path_planner): reset current route lanelet in manual drive

---

planning/autoware_scenario_selector/include/autoware/scenario_selector/node.hpp
planning/autoware_scenario_selector/src/node.cpp
planning/autoware_scenario_selector/test/test_autoware_scenario_selector_node_interface.cpp

feat(scenario_selector): rename to include/autoware/{package_name}

---

common/autoware_test_utils/src/autoware_test_utils.cpp
map/map_loader/README.md
map/map_loader/config/lanelet2_map_loader.param.yaml
map/map_loader/schema/lanelet2_map_loader.schema.json
map/map_loader/src/lanelet2_map_loader/lanelet2_map_loader_node.cpp
map/map_loader/test/lanelet2_map_loader_launch.test.py
planning/autoware_static_centerline_generator/src/static_centerline_generator_node.cpp

The change by https://github.com/autowarefoundation/autoware_common/pull/252
In the above PR, `use_waypoints` is defined and this PR uses it. Please see the above PR in detail.
simple planning simulator works.
The centerline is treated as waypoints inside the Autoware's implementation.
As a result, the centerline will be connected to the planned path smoothly, and fix several limitations described [here](https://github.com/autowarefoundation/autoware_common/blob/a933c529414cf3ffe730f8fa0c8c65942cfffa9a/tmp/lanelet2_extension/docs/lanelet2_format_extension.md#centerline)
After all …

feat(map_loader): add waypoints flag

---

control/autoware_joy_controller/src/joy_controller_node.cpp

Fix https://github.com/orgs/autowarefoundation/discussions/4882
The following commands would be enough to cause a crash:
```
ros2 launch autoware_joy_controller joy_controller.launch.xml
ros2 launch autoware_vehicle_cmd_gate vehicle_cmd_gate.launch.xml
```
With this PR no crash happens.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributi …

fix(joy_controller): check for nullptr messages

---

system/system_monitor/src/gpu_monitor/nvml_gpu_monitor.cpp

This is a fix based on cppcheck `unsignedLessThanZero` warning
```
system/system_monitor/src/gpu_monitor/nvml_gpu_monitor.cpp:222:18: style: Checking if unsigned expression 'util_count' is less than zero. [unsignedLessThanZero]
if (util_count <= 0) {
^
```
If the fix is different from your original intention, please add your modification commit!
No
No
No …

fix(system_monitor): fix unsignedLessThanZero warning

---

planning/behavior_path_planner/autoware_behavior_path_planner_common/src/turn_signal_decider.cpp

This is a fix based on cppcheck `redundantIfRemove` warning
```
planning/behavior_path_planner/autoware_behavior_path_planner_common/src/turn_signal_decider.cpp:252:11: style: Redundant checking of STL container element existence before removing it. [redundantIfRemove]
if (desired_start_point_map_.find(lane_id) != desired_start_point_map_.end()) {
^
```
You may check how the `erace` works when there exists no matching value or iterator:
https://cpprefjp.github.io/reference/map/map/erase.html
No
No
No …

fix(behavior_path_planner): fix redundantIfRemove warning

---

.github/workflows/build-and-test.yaml

Default ccache `max_size=5GB` which can be too much for our github hosted machines.
This PR reduces it to `600MB`.
Related links:
- https://ccache.dev/manual/latest.html#_configuration_file_syntax
- https://ccache.dev/manual/latest.html#_configuration_options
Related issue:
- https://github.com/autowarefoundation/autoware.universe/issues/7501
Ran the workflow against this branch:
- https://github.com/autowarefoundation/autoware.universe/actions/runs/9562281575/job/26358331612#step:11:20
It works ✅
I had a ccache cache of 30GB on my machine.
Set the max size to 5GB.
Then rebuilt the Autoware.
The ccache size gradually became smaller down to 4GB automatically. …

ci(build-and-test): limit ccache size

---

system/system_diagnostic_monitor/config/control.yaml

Since local commands are published from other than joy_controller, such as tier4_control_rviz_plugin, fix diagnostic graph.
Launch planning simulator and check that the operation mode can be changed to local/remote.

fix(system_diagnostic_monitor): fix local mode config

---

planning/behavior_velocity_planner/autoware_behavior_velocity_occlusion_spot_module/test/src/utils.hpp

This is a fix based on cppcheck `redundantAssignment` warning
```
planning/behavior_velocity_planner/autoware_behavior_velocity_occlusion_spot_module/test/src/utils.hpp:89:34: style: Variable 'intersection_pose.position.x' is reassigned a value before the old one has been used. [redundantAssignment]
intersection_pose.position.x = y0 + y_step * i;
^
```
[pull request …

fix(autoware_behavior_velocity_occlusion_spot_module): fix redundantAssignment bug

---

planning/behavior_path_planner/autoware_behavior_path_planner_common/test/test_turn_signal.cpp

This is a fix based on cppcheck `redundantAssignment` warning
```
planning/behavior_path_planner/autoware_behavior_path_planner_common/test/test_turn_signal.cpp:341:44: style: Variable 'behavior_signal_info.turn_signal.command' is reassigned a value before the old one has been used. [redundantAssignment]
behavior_signal_info.turn_signal.command = TurnIndicatorsCommand::ENABLE_RIGHT;
^
planning/behavior_path_planner/autoware_behavior_path_planner_common/test/test_turn_signal.cpp:340:44: note: behavior_signal_info.turn_signal.command is assigned
behavior_signal_info.turn_signal.command = TurnIndicatorsCommand::ENABLE_RIGHT;
^
planning/behavior_path_planner/autoware_behavior_path_planner_common/test/test_turn_signal.cpp:341:44: note: behavior_signal_info.turn_signal.command is overwritten …
```

fix(behavior_path_planner): fix redundantAssignment warning

---

common/tvm_utility/example/yolo_v2_tiny/main.cpp

This is a fix based on cppcheck `selfAssignment` and `shadowArgument` warnings
```
common/tvm_utility/example/yolo_v2_tiny/main.cpp:123:34: style: Redundant assignment of 'label_filename' to itself. [selfAssignment]
std::string label_filename = label_filename;
^
common/tvm_utility/example/yolo_v2_tiny/main.cpp:134:35: style: Redundant assignment of 'anchor_filename' to itself. [selfAssignment]
std::string anchor_filename = anchor_filename;
^
common/tvm_utility/example/yolo_v2_tiny/main.cpp:123:19: style: Local variable 'label_filename' shadows outer argument [shadowArgument]
std::string label_filename = label_filename;
^
common/tvm_utility/example/yolo_v2_tiny/main.cpp:113:73: note: Shadowed declaration
tvm_utility::pipeline::InferenceEngineTVMConfig config, std::string label_filename,
^ …
```

fix(tvm_utility): fix selfAssignment warnings

---

perception/multi_object_tracker/src/debugger/debug_object.cpp

This is a fix based on cppcheck `uselessCallsSubstr` warning
```
perception/multi_object_tracker/src/debugger/debug_object.cpp:240:7: performance: Ineffective call of function 'substr' because a prefix of the string is assigned to itself. Use resize() or pop_back() instead. [uselessCallsSubstr]
existence_probability_text.substr(0, existence_probability_text.size() - 1);
^
``` …

fix(multi_object_tracker): fix uselessCallsSubstr warning

---

perception/lidar_apollo_segmentation_tvm/src/log_table.cpp

This is a fix based on cppcheck `unpreciseMathCall` warning
```
perception/lidar_apollo_segmentation_tvm/src/log_table.cpp:49:15: style: Expression 'log(1 + x)' can be replaced by 'log1p(x)' to avoid loss of precision. [unpreciseMathCall]
return std::log(1.0f + num);
^
```
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contribu …

fix(lidar_apollo_segmentation_tvm): fix unpreciseMathCall warning

---

system/mrm_handler/src/mrm_handler/mrm_handler_core.cpp

This is a fix based on cppcheck `multiCondition` warning
```
system/mrm_handler/src/mrm_handler/mrm_handler_core.cpp:94:16: style: Expression is always true because 'else if' condition is opposite to previous condition at line 92. [multiCondition]
} else if (!msg->autonomous) {
^
system/mrm_handler/src/mrm_handler/mrm_handler_core.cpp:92:12: note: first condition
if (msg->autonomous) {
^
system/mrm_handler/src/mrm_handler/mrm_handler_core.cpp:94:16: note: else if condition is opposite to first condition
} else if (!msg->autonomous) {
^
```
No
No
No …

fix(mrm_handler): fix multiCondition warning

---

.gitignore

Currently, prettier automatically makes directory `/node_modules` when I run `pre-commit run -a`.
CI
Nothing.

fix(.gitignore): add config to ignore directory which is made by prettier

---

simulator/simple_planning_simulator/src/simple_planning_simulator/vehicle_model/sim_model_delay_steer_acc_geared.cpp
simulator/simple_planning_simulator/src/simple_planning_simulator/vehicle_model/sim_model_delay_steer_map_acc_geared.cpp
simulator/simple_planning_simulator/src/simple_planning_simulator/vehicle_model/sim_model_ideal_steer_acc_geared.cpp

This is a fix based on cppcheck warning
```
simulator/simple_planning_simulator/src/simple_planning_simulator/vehicle_model/sim_model_delay_steer_acc_geared.cpp:180:10: style: inconclusive: Found duplicate branches for 'if' and 'else'. [duplicateBranch]
} else if (gear == GearCommand::PARK) {
^
simulator/simple_planning_simulator/src/simple_planning_simulator/vehicle_model/sim_model_delay_steer_acc_geared.cpp:182:5: note: Found duplicate branches for 'if' and 'else'.
} else {
^
simulator/simple_planning_simulator/src/simple_planning_simulator/vehicle_model/sim_model_delay_steer_acc_geared.cpp:180:10: note: Found duplicate branches for 'if' and 'else'.
} else if (gear == GearCommand::PARK) {
^
simulator/simple_planning_simulator/src/simple_planning_simulator/vehicle_model/sim_model_delay_st …
```

fix(simple_planning_simulator): fix duplicateBranch warnings

---

planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/drivable_area_expansion/static_drivable_area.cpp

This is a fix based on cppcheck `redundantContinue` warning
```
planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/drivable_area_expansion/static_drivable_area.cpp:360:5: style: 'continue' is redundant since it is the last statement in a loop. [redundantContinue]
continue;
^
``` …

fix(autoware_behavior_path_planner_common): fix redundantContinue warning

---

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/debug.cpp

This is a fix based on cppcheck `duplicateCondition` wrnings
```
lanning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/debug.cpp:586:17: style: The if condition is the same as the previous if condition [duplicateCondition]
if (parameters->enable_shift_line_marker) {
^
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/debug.cpp:577:17: note: First condition
if (parameters->enable_shift_line_marker) {
^
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/debug.cpp:586:17: note: Second condition
if (parameters->enable_shift_line_marker) {
^
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/debug.cpp:591:17: style: The if condition is the …
```

fix(autoware_behavior_path_static_obstacle_avoidance_module): fix duplicateCondition warnings

---

planning/autoware_obstacle_cruise_planner/src/node.cpp
planning/autoware_obstacle_cruise_planner/src/planner_interface.cpp

This is a fix based on cppcheck `unusedScopedObject` bug
```
planning/autoware_obstacle_cruise_planner/src/node.cpp:409:12: style: Instance of 'std::logic_error' object is destroyed immediately. [unusedScopedObject]
std::logic_error("Designated algorithm is not supported.");
^
planning/autoware_obstacle_cruise_planner/src/planner_interface.cpp:146:10: style: Instance of 'std::logic_error' object is destroyed immediately. [unusedScopedObject]
std::logic_error("[obstacle_cruise_planner](findReachTime): search range is invalid");
^
planning/autoware_obstacle_cruise_planner/src/planner_interface.cpp:178:10: style: Instance of 'std::logic_error' object is destroyed immediately. [unusedScopedObject]
std::logic_error("max_slowdown_jerk and max_slowdown_accel should be negative");
^
```
Not …

fix(autoware_obstacle_cruise_planner): fix unusedScopedObject bug

---

control/autoware_mpc_lateral_controller/include/autoware/mpc_lateral_controller/mpc_lateral_controller.hpp
control/autoware_mpc_lateral_controller/src/mpc_lateral_controller.cpp
control/autoware_trajectory_follower_node/include/autoware/trajectory_follower_node/controller_node.hpp
control/autoware_trajectory_follower_node/src/controller_node.cpp

The car is expected to experience an MRM stop when MPC fails.
https://tier4.atlassian.net/jira/software/c/projects/RT1/boards/438?selectedIssue=RT1-6221
Set the is_mpc_solved to false manually.
We received the error message.
[Screencast from 06-05-2024 03:34:32 PM.webm](https://github.com/autowarefoundation/autoware.universe/assets/80969277/b2951d7c-edd6-4c45-b506-fd8ef49e9684)
[pull request …

feat(mpc_lateral_controller): signal a MRM when MPC fails.

---

simulator/learning_based_vehicle_model/src/model_connections_helpers.cpp

This is a fix based on cppcheck `constVariablePointer` warning
```
simulator/learning_based_vehicle_model/src/model_connections_helpers.cpp:35:13: style: Variable 'name_2' can be declared as pointer to const [constVariablePointer]
for (auto name_2 : connection_names_2) {
^
``` …

fix(learning_based_vehicle_model): fix constVariablePointer warning

---

system/system_monitor/src/net_monitor/net_monitor.cpp

This is a fix based on cppcheck warnings below
```
system/system_monitor/src/net_monitor/net_monitor.cpp:285:12: style: The scope of the variable 'unit_reassembles_failed' can be reduced. [variableScope]
uint64_t unit_reassembles_failed = 0;
^
system/system_monitor/src/net_monitor/net_monitor.cpp:159:15: style: Unused variable: error_str [unusedVariable]
std::string error_str;
^
system/system_monitor/src/net_monitor/net_monitor.cpp:160:28: style: Unused variable: interface_names [unusedVariable]
std::vector<std::string> interface_names;
^
system/system_monitor/src/net_monitor/net_monitor.cpp:457:21: style: Variable 'ether_request.cmd' is assigned a value that is never used. [unreadVariable]
ether_request.cmd = ETHTOOL_GSET;
^
``` …

fix(net_monitor): fix cppcheck warnings

---

planning/sampling_based_planner/autoware_path_sampler/src/node.cpp

This is a fix based on cppcheck `unusedVariable` warning
```
planning/sampling_based_planner/autoware_path_sampler/src/node.cpp:526:32: style: Unused variable: trajectory [unusedVariable]
std::vector<TrajectoryPoint> trajectory;
^
```

fix(autoware_path_sampler): fix unusedVariable warning

---

planning/autoware_velocity_smoother/src/trajectory_utils.cpp

This is a fix based on cppcheck `unusedVariable` warning
```
planning/autoware_velocity_smoother/src/trajectory_utils.cpp:303:46: style: Unused variable: state [unusedVariable]
std::tuple<double, double, double, double> state;
^
```

fix(autoware_velocity_smoother): fix unusedVariable warning

---

control/autoware_autonomous_emergency_braking/CMakeLists.txt
control/autoware_autonomous_emergency_braking/config/autonomous_emergency_braking.param.yaml
control/autoware_autonomous_emergency_braking/include/autoware/autonomous_emergency_braking/node.hpp
control/autoware_autonomous_emergency_braking/include/autoware/autonomous_emergency_braking/utils.hpp
control/autoware_autonomous_emergency_braking/launch/autoware_autonomous_emergency_braking.launch.xml
control/autoware_autonomous_emergency_braking/src/node.cpp
control/autoware_autonomous_emergency_braking/src/utils.cpp
launch/tier4_control_launch/launch/control.launch.py

This PR introduces support for using predicted objects on AEB collision checking. It also enables toggling on and off pointcloud based and predicted object based collision checking. 
PSim
The attached video shows the predicted object usage alongside the usual pointcloud method, I also turn off the point cloud method while the ego is moving and detecting an obstacle, and there is no problem with the transition.
https://github.com/autowarefoundation/autoware.universe/assets/25967964/248fd524-a8d1-4bdb-b424-d426a4a13783 …

feat(autonomous_emergency_braking): add predicted object support for aeb

---

planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/start_planner_module.cpp

This is a fix based on cppcheck `duplicateBreak` warning
```
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/start_planner_module.cpp:905:3: style: Consecutive return, break, continue, goto or throw statements are unnecessary. [duplicateBreak]
return order_priority;
^
```
This modification is just to avoid cppcheck warnings.
[pull request …

fix(autoware_behavior_path_start_planner_module): fix duplicateBreak warning

---

control/autoware_mpc_lateral_controller/include/autoware/mpc_lateral_controller/mpc.hpp
control/autoware_mpc_lateral_controller/src/mpc.cpp
control/autoware_mpc_lateral_controller/src/mpc_lateral_controller.cpp

The MPC steering angle stops tracking the actual one while the car is driving manually.
This causes the so-called "improper initial steering angle" after switching from manual to auto as below:
_case 1_
[Screencast from 06-14-2024 01:39:49 PM.webm](https://github.com/autowarefoundation/autoware.universe/assets/80969277/6fea01bd-8df3-4dbd-915e-749d7fb49b1b)
_case 2_
[Screencast from 06-14-2024 02:10:00 PM.webm](https://github.com/autowarefoundation/autoware.universe/assets/80969277/e7c29978-28c2-404e-9aa9-65d7e099a633)
_case 3_
[Screencast from 06-14-2024 02:31:54 PM.webm](https://github.com/autowarefoundation/autoware.universe/assets/80969277/08ce5885-81b9-4d93-ae9f-64cea905dfb4)
This PR aligns the MPC steering angle when the car is controlled manually.
The resulting response of the …

fix(mpc_lateral_controller): align the MPC steering angle when the car is controlled manually.

---

planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/src/utilization/util.cpp

This is a fix based on cppcheck `unusedScopedObject` bug
```
planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/src/utilization/util.cpp:418:10: style: Instance of 'std::logic_error' object is destroyed immediately. [unusedScopedObject]
std::logic_error("[behavior_velocity](findReachTime): search range is invalid");
^
planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/src/utilization/util.cpp:450:10: style: Instance of 'std::logic_error' object is destroyed immediately. [unusedScopedObject]
std::logic_error("max_slowdown_jerk and max_slowdown_accel should be negative");
^
``` …

fix(autoware_behavior_velocity_planner_common): fix unusedScopedObject bug

---

planning/autoware_freespace_planning_algorithms/src/abstract_algorithm.cpp

This is a fix based on cppcheck `unusedScopedObject` warning
```
planning/autoware_freespace_planning_algorithms/src/abstract_algorithm.cpp:94:10: style: Instance of 'std::runtime_error' object is destroyed immediately. [unusedScopedObject]
std::runtime_error("cannot compute cost because waypoint has size 0");
^
``` …

fix(autoware_freespace_planning_algorithms): fix unusedScopedObject bug

---

planning/autoware_path_optimizer/src/mpt_optimizer.cpp

This is a fix based on cppcheck `redundantContinue` warning
```
planning/autoware_path_optimizer/src/mpt_optimizer.cpp:957:7: style: 'continue' is redundant since it is the last statement in a loop. [redundantContinue]
continue;
^
planning/autoware_path_optimizer/src/mpt_optimizer.cpp:1007:7: style: 'continue' is redundant since it is the last statement in a loop. [redundantContinue]
continue;
^
``` …

fix(autoware_path_optimizer): fix redundantContinue warnings

---

control/autoware_mpc_lateral_controller/src/mpc_lateral_controller.cpp

This is a fix based on cppcheck `duplicateAssignExpression` warning
```
control/autoware_mpc_lateral_controller/src/mpc_lateral_controller.cpp:499:10: style: inconclusive: Same expression used in consecutive assignments of 'min_steering_value' and 'max_steering_value'. [duplicateAssignExpression]
double min_steering_value = m_mpc_steering_history[0].first.steering_tire_angle;
^
```
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/con …

fix(autoware_mpc_lateral_controller): fix duplicateAssignExpression warning

---

control/autoware_mpc_lateral_controller/src/mpc_lateral_controller.cpp

This is a fix based on cppcheck `duplicateExpression` warning
```
control/autoware_mpc_lateral_controller/src/mpc_lateral_controller.cpp:635:83: style: Same expression on both sides of '||'. [duplicateExpression]
!isfinite(p.longitudinal_velocity_mps) || !isfinite(p.lateral_velocity_mps) ||
^
```
`!isfinite(p.lateral_velocity_mps)` is duplicated.
No
No
No …

fix(autoware_mpc_lateral_controller): fix duplicateExpression warning

---

.github/workflows/cppcheck-differential.yaml

Install bainary cppcheck via snap for greater version 
https://snapcraft.io/cppcheck
In this pull-request, the workflow installs from edge channel for version 2.14.x.
well done!
https://github.com/autowarefoundation/autoware.universe/actions/runs/9606917228/job/26497227001?pr=7611
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pul …

chore(ci): install binary cppcheck from snap

---

.github/workflows/cppcheck-differential.yaml

I tried to apply the knowledge gained from `autowarefoundation/get-modified-packages` action's development to cppcheck workflow.
https://github.com/autowarefoundation/autoware-github-actions/pull/299
https://github.com/autowarefoundation/autoware.universe/actions/runs/9596328091/job/26462963086
https://github.com/autowarefoundation/autoware.universe/actions/runs/9596328104/job/26495780548#step:7:8
N/A
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main …

chore(ci): change way to get modified files for cppcheck

---

.github/workflows/cppcheck-differential.yaml

I found out that we don't need to use the latest version of `cppcheck` for CI (greater or equal to 2.11 is OK), so I'll use the stable version.
OK!
https://github.com/autowarefoundation/autoware.universe/actions/runs/9607510009/job/26498784376?pr=7613

chore(ci): install cppcheck from snap stable channel for CI

---

sensing/gnss_poser/src/gnss_poser_core.cpp

When `use_gnss_ins_orientation` is true, gnss_poser will create
```cpp
msg_gnss_ins_orientation_stamped_ = std::make_shared<autoware_sensing_msgs::msg::GnssInsOrientationStamped>())
```
first, and then publish this as a PoseWithCovarianceStamped object. (This declaration is done at Line 36 of gnss_poser_core.cpp)
On this initialization, `msg_gnss_ins_orientaiton_stamped_` will have zero angular variance and it will be published as it is if no orientation topic have arrived yet, which will leads to transformation error mentioned in this issue. (https://github.com/orgs/autowarefoundation/discussions/4667). So technically Autoware only works if the orientation arrives late, but this is less noticed since few people use transformation to this pose. 
**Hence, this PR will set initial values …

fix(gnss_poser): give msg_gnss_ins_orientation_stamped_ initial rmse values

---

.github/workflows/cppcheck-daily.yaml

Install bainary cppcheck via snap for cppcheck-daily.
https://snapcraft.io/cppcheck
Wait till the next daily cppcheck CI works.

chore(ci): install binary cppcheck from snap for cppcheck-daily

---

sensing/image_transport_decompressor/CMakeLists.txt

- To fix bug: `[ERROR] [launch]: Caught exception in launch (see debug for traceback): [Errno 2] No such file or directory: '/home/autoware/autoware/install/image_transport_decompressor/share/image_transport_decompressor/config/image_transport_decompressor.param.yaml'`
when running `ros2 launch image_transport_decompressor image_transport_decompressor.launch.xml`
- Confimed that after change is able to run `ros2 launch image_transport_decompressor image_transport_decompressor.launch.xml` …

fix(image_transport_decompressor): missing config setting

---

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/utils.hpp

Changed utils logger name to `planning.scenario_planning.lane_driving.behavior_planning.behavior_path_planner.static_obstacle_avoidance.utils`
from `planning.scenario_planning.lane_driving.behavior_planning.behavior_path_planner.avoidance.utils` to keep consistency. 
Related [PR](https://github.com/autowarefoundation/autoware_tools/pull/62).
None
[pull request …

refactor(static_obstacle_avoidance): change logger name for utils   

---

sensing/pointcloud_preprocessor/src/outlier_filter/dual_return_outlier_filter_nodelet.cpp

This is a fix based on cppcheck `arrayIndexThenCheck` warning
```
sensing/pointcloud_preprocessor/src/outlier_filter/dual_return_outlier_filter_nodelet.cpp:234:36: style: Array index 'current_deleted_index' is used before limits check. [arrayIndexThenCheck]
while ((uint)deleted_azimuths[current_deleted_index] <
^
```
You know the current implementation is correct.
This fix is just to avoid cppcheck warning by changing the evaluation order in while loop condition. …

fix(pointcloud_preprocessor): fix arrayIndexThenCheck warning

---

perception/tracking_object_merger/include/tracking_object_merger/utils/utils.hpp
perception/tracking_object_merger/src/utils/utils.cpp

This is a fix based on cppcheck `shadowArgument` warning
```
perception/tracking_object_merger/src/utils/utils.cpp:169:21: style: Local variable 'obj' shadows outer argument [shadowArgument]
for (const auto & obj : obj.objects) {
^
perception/tracking_object_merger/src/utils/utils.cpp:161:26: note: Shadowed declaration
const TrackedObjects & obj, const std_msgs::msg::Header & header)
^
perception/tracking_object_merger/src/utils/utils.cpp:169:21: note: Shadow variable
for (const auto & obj : obj.objects) {
^
``` …

fix(tracking_object_merger): fix shadowArgument warning

---

planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/drivable_area_expansion/static_drivable_area.cpp

This is a fix based on cppcheck `shadowArgument` warning
```
planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/drivable_area_expansion/static_drivable_area.cpp:748:21: style: Local variable 'lanes' shadows outer argument [shadowArgument]
for (const auto & lanes : shorten_lanes) {
^
planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/drivable_area_expansion/static_drivable_area.cpp:690:61: note: Shadowed declaration
PathWithLaneId & path, const std::vector<DrivableLanes> & lanes)
^
planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/drivable_area_expansion/static_drivable_area.cpp:748:21: note: Shadow variable
for (const auto & lanes : shorten_lanes) {
^
```
Since this is just to avoid shadowArgument, if you …

fix(autoware_behavior_path_planner_common): fix shadowArgument warning

---

common/tier4_camera_view_rviz_plugin/src/bird_eye_view_controller.hpp
common/tier4_camera_view_rviz_plugin/src/third_person_view_controller.hpp

This is a fix based on cppcheck `funcArgNamesDifferent` warnings
```
common/tier4_camera_view_rviz_plugin/src/bird_eye_view_controller.cpp:102:80: style: inconclusive: Function 'handleMouseEvent' argument 1 names different: declaration 'evt' definition 'event'. [funcArgNamesDifferent]
void BirdEyeViewController::handleMouseEvent(rviz_common::ViewportMouseEvent & event)
^
common/tier4_camera_view_rviz_plugin/src/bird_eye_view_controller.hpp:75:59: note: Function 'handleMouseEvent' argument 1 names different: declaration 'evt' definition 'event'.
void handleMouseEvent(rviz_common::ViewportMouseEvent & evt) override;
^
common/tier4_camera_view_rviz_plugin/src/bird_eye_view_controller.cpp:102:80: note: Function 'handleMouseEvent' argument 1 names different: declaration 'evt' definition …
```

fix(tier4_camera_view_rviz_plugin): fix funcArgNamesDifferent warnings

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_searcher.cpp

This is a fix based on cppcheck `variableScope` and `unreadVariable` warnings
```
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_searcher.cpp:164:12: style: The scope of the variable 'lateral_offset' can be reduced. [variableScope]
double lateral_offset = 0.0;
^
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_searcher.cpp:164:27: style: Variable 'lateral_offset' is assigned a value that is never used. [unreadVariable]
double lateral_offset = 0.0;
^
``` …

fix(autoware_behavior_path_goal_planner_module): fix lateral_offset related warnings

---

perception/probabilistic_occupancy_grid_map/src/pointcloud_based_occupancy_grid_map/occupancy_grid_map_projective.cpp

```
perception/probabilistic_occupancy_grid_map/src/pointcloud_based_occupancy_grid_map/occupancy_grid_map_projective.cpp:228:13: style: Condition '!no_visible_point_beyond' is always true [knownConditionTrueFalse]
if (!no_visible_point_beyond) {
^
perception/probabilistic_occupancy_grid_map/src/pointcloud_based_occupancy_grid_map/occupancy_grid_map_projective.cpp:218:11: note: Assuming that condition 'no_visible_point_beyond' is not redundant
if (no_visible_point_beyond) {
^
perception/probabilistic_occupancy_grid_map/src/pointcloud_based_occupancy_grid_map/occupancy_grid_map_projective.cpp:228:13: note: Condition '!no_visible_point_beyond' is always true
if (!no_visible_point_beyond) {
^ …
```

fix(probabilistic_occupancy_grid_map): fix knownConditionTrueFalse warning

---

planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/src/trajectory_preprocessing.cpp

This is a fix based on cppcheck `unreadVariable` warning
```
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/src/trajectory_preprocessing.cpp:71:10: style: Variable 't' is assigned a value that is never used. [unreadVariable]
auto t = 0.0;
^
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/src/trajectory_preprocessing.cpp:79:7: style: Variable 't' is assigned a value that is never used. [unreadVariable]
t += dt;
^
``` …

fix(autoware_motion_velocity_obstacle_velocity_limiter_module): fix unreadVariable warning

---

sensing/pointcloud_preprocessor/src/outlier_filter/dual_return_outlier_filter_nodelet.cpp

```
sensing/pointcloud_preprocessor/src/outlier_filter/dual_return_outlier_filter_nodelet.cpp:91:11: style: Redundant initialization for 'level'. The initialized value is overwritten before it is read. [redundantInitialization]
level = DiagnosticStatus::STALE;
^
sensing/pointcloud_preprocessor/src/outlier_filter/dual_return_outlier_filter_nodelet.cpp:89:14: note: level is initialized
auto level = DiagnosticStatus::OK;
^
sensing/pointcloud_preprocessor/src/outlier_filter/dual_return_outlier_filter_nodelet.cpp:91:11: note: level is overwritten
level = DiagnosticStatus::STALE;
^
``` …

fix(pointcloud_preprocessor): fix redundantInitialization warning

---

planning/autoware_obstacle_cruise_planner/src/optimization_based_planner/optimization_based_planner.cpp

This is a fix based on cppcheck `unreadVariable` warning
```
planning/autoware_obstacle_cruise_planner/src/optimization_based_planner/optimization_based_planner.cpp:705:34: style: Variable 'time' is assigned a value that is never used. [unreadVariable]
const std::vector<double> time = opt_result.t;
^
``` …

fix(autoware_obstacle_cruise_planner): fix unreadVariable warning

---

planning/behavior_velocity_planner/autoware_behavior_velocity_no_drivable_lane_module/src/util.cpp

This is a fix based on cppcheck `containerOutOfBounds` warning
```
planning/behavior_velocity_planner/autoware_behavior_velocity_no_drivable_lane_module/src/util.cpp:96:37: warning: inconclusive: Either the condition 'intersects.size()==1' is redundant or size of 'intersects' can be 1. Expression 'intersects.at(i)' causes access out of bounds. [containerOutOfBounds]
const auto & p = intersects.at(i);
^
planning/behavior_velocity_planner/autoware_behavior_velocity_no_drivable_lane_module/src/util.cpp:99:28: note: Assuming that condition 'intersects.size()==1' is not redundant
(intersects.size() == 1 && is_last_path_point_inside_polygon)) {
^
planning/behavior_velocity_planner/autoware_behavior_velocity_no_drivable_lane_module/src/util.cpp:96:37: note: Access out of bounds
const auto & p = …
```

fix(autoware_behavior_velocity_no_drivable_lane_module): fix containerOutOfBounds wawrning

---

common/autoware_test_utils/src/autoware_test_utils.cpp
planning/autoware_route_handler/test/test_route_handler.cpp
planning/autoware_route_handler/test/test_route_handler.hpp

Add unit test for lane change related function.
Also fix setMap to be able to get local coordinate properly.

feat(route_handler): add unit test for lane change related functions

---

planning/motion_velocity_planner/autoware_motion_velocity_dynamic_obstacle_stop_module/src/dynamic_obstacle_stop_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/src/obstacle_velocity_limiter_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/plugin_module_interface.hpp
planning/motion_velocity_planner/autoware_motion_velocity_planner_node/src/node.cpp
planning/motion_velocity_planner/autoware_motion_velocity_planner_node/src/node.hpp

Publish processing times of the `motion_velocity_planner` and its modules.
Psim
New topics:
- `/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/debug/processing_time_ms`
- `/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/debug/dynamic_obstacle_stop/processing_time_ms`
- `/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/debug/obstacle_velocity_limiter/processing_time_ms`
- `/planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/debug/out_of_lane/processing_time_ms` …

feat(motion_velocity_planner): publish processing times

---

perception/tensorrt_yolox/src/tensorrt_yolox.cpp

This is a fix based on cppcheck `unusedVariable` warning
```
perception/tensorrt_yolox/src/tensorrt_yolox.cpp:681:24: style: Unused variable: images [unusedVariable]
std::vector<cv::Mat> images;
^
```

fix(tensorrt_yolox): fix unusedVariable warning

---

.cppcheck_suppressions

Fixed `arrayIndexThenCheck` by https://github.com/autowarefoundation/autoware.universe/pull/7547

chore(ci): remove arrayIndexThenCheck

---

planning/behavior_path_planner/autoware_behavior_path_dynamic_obstacle_avoidance_module/src/scene.cpp

This is a fix based on cppcheck `bitwiseOnBoolean warning
```
planning/behavior_path_planner/autoware_behavior_path_dynamic_obstacle_avoidance_module/src/scene.cpp:1474:47: style: inconclusive: Boolean expression 'enable_lowpass_filter' is used in bitwise operation. Did you mean '&&'? [bitwiseOnBoolean]
(prev_min_lat_avoid_to_offset.has_value() & enable_lowpass_filter)
^
planning/behavior_path_planner/autoware_behavior_path_dynamic_obstacle_avoidance_module/src/scene.cpp:1559:47: style: inconclusive: Boolean expression 'enable_lowpass_filter' is used in bitwise operation. Did you mean '&&'? [bitwiseOnBoolean]
(prev_min_lat_avoid_to_offset.has_value() & enable_lowpass_filter)
^
```
The …

fix(autoware_behavior_path_dynamic_obstacle_avoidance_module): fix bitwiseOnBoolean warning

---

perception/bytetrack/lib/src/lapjv.cpp
perception/bytetrack/lib/src/strack.cpp
perception/bytetrack/lib/src/utils.cpp
perception/bytetrack/src/bytetrack_visualizer_node.cpp

This is a fix based on cppcheck warnings
```
perception/bytetrack/lib/src/lapjv.cpp:184:56: style: Parameter 'd' can be declared as pointer to const [constParameterPointer]
uint_t _find_dense(const uint_t n, uint_t lo, cost_t * d, int_t * cols, [[maybe_unused]] int_t * y)
^
perception/bytetrack/lib/src/lapjv.cpp:206:25: style: Parameter 'y' can be declared as pointer to const [constParameterPointer]
int_t * pred, int_t * y, cost_t * v)
^
perception/bytetrack/lib/src/lapjv.cpp:206:37: style: Parameter 'v' can be declared as pointer to const [constParameterPointer]
int_t * pred, int_t * y, cost_t * v)
^
perception/bytetrack/lib/src/strack.cpp:120:27: style: Variable 'xyah' is assigned a value that is never used. [unreadVariable]
std::vector<float> xyah = tlwh_to_xyah(_tlwh_tmp);
^ …
```

fix(bytetrack): fix cppcheck warnings

---

planning/autoware_obstacle_cruise_planner/src/optimization_based_planner/optimization_based_planner.cpp
planning/autoware_obstacle_cruise_planner/src/planner_interface.cpp

```
planning/autoware_obstacle_cruise_planner/src/optimization_based_planner/optimization_based_planner.cpp:351:18: style: Condition 'stop_dist' is always true [knownConditionTrueFalse]
} else if (stop_dist) {
^
```
and 
```
planning/autoware_obstacle_cruise_planner/src/planner_interface.cpp:640:49: style: Condition 'slow_down_end_idx' is always true [knownConditionTrueFalse]
slow_down_debug_multi_array_.data.push_back(slow_down_end_idx ? *slow_down_end_idx : -1.0);
^
```
After all …

fix(autoware_obstacle_cruise_planner): fix knownConditionTrueFalse warnings

---

.cppcheck_suppressions

Ignore `cstyle` and `uninit` in `.cppcheck_suppressions` as typo.
No errors on `spell-check-differential`
https://github.com/autowarefoundation/autoware.universe/actions/runs/9640760877/job/26585111573?pr=7647

chore(cspell): ignore some words in .cppcheck_suppressions

---

planning/autoware_obstacle_cruise_planner/src/pid_based_planner/pid_based_planner.cpp

This is a fix based on cppcheck warning.
```
src/universe/autoware.universe/planning/autoware_obstacle_cruise_planner/src/pid_based_planner/pid_based_planner.cpp:584:15: style: Local variable 'i' shadows outer variable [shadowVariable]
for (size_t i = 0; i < s_vec.size(); ++i) {
^
src/universe/autoware.universe/planning/autoware_obstacle_cruise_planner/src/pid_based_planner/pid_based_planner.cpp:512:16: note: Shadowed declaration
const auto & i = longitudinal_info_;
^
src/universe/autoware.universe/planning/autoware_obstacle_cruise_planner/src/pid_based_planner/pid_based_planner.cpp:584:15: note: Shadow variable
for (size_t i = 0; i < s_vec.size(); ++i) {
^
src/universe/autoware.universe/planning/autoware_obstacle_cruise_planner/src/pid_based_planner/pid_based_planner.cpp:600:15: style: …
```

fix(autoware_obstacle_cruise_planner): fix shadowVariable warning

---

planning/autoware_obstacle_cruise_planner/src/planner_interface.cpp

This is a fix based on cppcheck warning.
```
src/universe/autoware.universe/planning/autoware_obstacle_cruise_planner/src/planner_interface.cpp:626:17: style: Local variable 'i' shadows outer variable [shadowVariable]
for (size_t i = (slow_down_start_idx ? *slow_down_start_idx : 0); i <= *slow_down_end_idx;
^
src/universe/autoware.universe/planning/autoware_obstacle_cruise_planner/src/planner_interface.cpp:579:15: note: Shadowed declaration
for (size_t i = 0; i < obstacles.size(); ++i) {
^
src/universe/autoware.universe/planning/autoware_obstacle_cruise_planner/src/planner_interface.cpp:626:17: note: Shadow variable
for (size_t i = (slow_down_start_idx ? *slow_down_start_idx : 0); i <= *slow_down_end_idx;
``` …

fix(autoware_obstacle_cruise_planner): fix shadowVariable warning in generateSlowDownTrajectory

---

localization/autoware_landmark_based_localizer/autoware_ar_tag_based_localizer/src/ar_tag_based_localizer.cpp
localization/yabloc/yabloc_common/src/cv_decompress.cpp
localization/yabloc/yabloc_common/src/pub_sub.cpp
localization/yabloc/yabloc_image_processing/src/line_segments_overlay/line_segments_overlay_core.cpp
localization/yabloc/yabloc_image_processing/src/undistort/undistort_node.cpp
localization/yabloc/yabloc_pose_initializer/src/camera/camera_pose_initializer_core.cpp
perception/traffic_light_map_based_detector/include/traffic_light_map_based_detector/node.hpp
perception/traffic_light_occlusion_predictor/include/traffic_light_occlusion_predictor/nodelet.hpp
perception/traffic_light_occlusion_predictor/include/traffic_light_occlusion_predictor/occlusion_predictor.hpp
perception/traffic_light_visualization/include/traffic_light_visualization/traffic_light_roi_visualizer/nodelet.hpp

With the release of Jazzy, some packages have deprecated old header files.
On the other hand, some newer header files are not available in Humble, so I would like to introduce `__has_include` macro.
Ref: https://github.com/orgs/autowarefoundation/discussions/4893
`colcon test` passed in both Humble and Jazzy environment. …

fix: replace deprecated header in Jazzy

---

common/tier4_camera_view_rviz_plugin/src/bird_eye_view_controller.cpp
common/tier4_camera_view_rviz_plugin/src/bird_eye_view_controller.hpp
common/tier4_camera_view_rviz_plugin/src/third_person_view_controller.cpp
common/tier4_camera_view_rviz_plugin/src/third_person_view_controller.hpp
common/tier4_perception_rviz_plugin/src/tools/util.hpp
common/tier4_vehicle_rviz_plugin/src/tools/velocity_history.hpp

OgreVector3.h is deprecated in Jazzy, so this PR replace it
`colcon test` passed in both Humble and Jazzy.

fix: replace Ogre deprecated header

---

common/autoware_test_utils/include/autoware_test_utils/autoware_test_utils.hpp

Add `jump_clock` interface
Tested with the other PR: https://github.com/autowarefoundation/autoware.universe/pull/7637
None
None
None

feat(autoware_test_utils): add jump_clock interface

---

system/diagnostic_graph_aggregator/src/common/graph/config.cpp

```
src/universe/autoware.universe/system/diagnostic_graph_aggregator/src/common/graph/config.cpp:105:21: style: Local variable 'data' shadows outer argument [shadowArgument]
for (const auto & data : list) {
^
src/universe/autoware.universe/system/diagnostic_graph_aggregator/src/common/graph/config.cpp:94:62: note: Shadowed declaration
UnitConfig * FileLoader::create_unit_config(const TreeData & data)
^
src/universe/autoware.universe/system/diagnostic_graph_aggregator/src/common/graph/config.cpp:105:21: note: Shadow variable
for (const auto & data : list) {
``` …

fix(diagnostic_graph_aggregator): fix shadowArg warning in create_unit_config

---

planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/utils.cpp

```
src/universe/autoware.universe/planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/utils.cpp:737:36: style: Local variable 'lanelets' shadows outer argument [shadowArgument]
lanelet::ConstLanelets lanelets = {llt};
^
src/universe/autoware.universe/planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/utils.cpp:694:61: note: Shadowed declaration
const Pose & current_pose, const lanelet::ConstLanelets & lanelets,
^
src/universe/autoware.universe/planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/utils.cpp:737:36: note: Shadow variable
lanelet::ConstLanelets lanelets = {llt};
^
``` …

fix(autoware_behavior_path_planner_common): fix shadowArgument warning in getDistanceToCrosswalk

---

control/autoware_smart_mpc_trajectory_follower/autoware_smart_mpc_trajectory_follower/scripts/drive_functions.py
control/autoware_smart_mpc_trajectory_follower/autoware_smart_mpc_trajectory_follower/scripts/pympc_trajectory_follower.py
control/autoware_smart_mpc_trajectory_follower/setup.py
launch/tier4_control_launch/launch/control.launch.py

smart_mpc can not work by some recent other package modification.
In this PR, fix it by
- adding control_state diag
- change msg type
- change package names
control state is checked in
https://github.com/tier4/autoware.universe/blob/ebc73da8d5c503e76a9bc86cc29cc0ad52c5b9c0/system/system_diagnostic_monitor/config/control.yaml#L55-L58
this feature was introduced in https://github.com/autowarefoundation/autoware.universe/pull/6715
use same state which is used in pid https://github.com/tier4/autoware.universe/blob/ebc73da8d5c503e76a9bc86cc29cc0ad52c5b9c0/control/autoware_pid_longitudinal_controller/include/autoware/pid_longitudinal_controller/pid_longitudinal_controller.hpp#L126
(but it is better to share the structure in actual)
psim
control state changes like
stopped -> drive -> stopping -> …

fix(smart_mpc_trajectory_folower): fix running by adding control_state and changing msg/package_name

---

planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_utils.cpp

This is a fix based on cppcheck `containerOutOfBounds` error
```
planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_utils.cpp:481:39: error: Out of bounds access in expression 'base_s.back()' because 'base_s' is empty. [containerOutOfBounds]
for (double s = eps; s < base_s.back() - eps; s += resample_interval) {
^
planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_utils.cpp:494:41: error: Out of bounds access in expression 'base_s.back()' because 'base_s' is empty. [containerOutOfBounds]
end_pose, start_pose, (base_s.back() - new_s.at(i)) / base_s.back());
^
```
You know this is a false positive in cppcheck.
This PR is just to avoid cppcheck warnings.
- Link
None.
None.
None.

fix(autoware_behavior_path_planner_common): fix containerOutOfBounds warning

---

perception/tensorrt_yolox/src/tensorrt_yolox.cpp

```
perception/tensorrt_yolox/src/tensorrt_yolox.cpp:119:24: style: Unused variable: rgb [unusedVariable]
std::vector<int> rgb;
^
```
- Link
None.
None.
None.

fix(tensorrt_yolox): fix unusedVariable warnings

---

.github/workflows/comment-on-pr.yaml

It failed on this fork pr:
- https://github.com/autowarefoundation/autoware.universe/pull/7678
With error:
- https://github.com/autowarefoundation/autoware.universe/actions/runs/9657331258/job/26636407771?pr=7678#step:3:26
- `Error: Resource not accessible by integration`
Now changing the trigger to [`pull_request_target`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target) so it can access repo's github token for commenting.
Also changing the general naming to fit the repo's other workflows. Shouldn't affect anything since I've added this new workflow just yesterday.
**Follow up from:**
- https://github.com/autowarefoundation/autoware.universe/pull/7667
Related solution:
- https://github.com/marocchino/sticky-pull-request-comment/issues/22 …

ci(comment-on-pr): make it work on forks

---

control/autoware_vehicle_cmd_gate/test/src/test_filter_in_vehicle_cmd_gate_node.cpp

Change vehicle_cmd_gate running hz to fix the CI test failure.
CI Test is failed in the latest autoware
https://github.com/autowarefoundation/autoware.universe/actions/runs/9654259291/job/26628146305
- Build
- Run colcon test
**Confirmed the test passes:**
https://github.com/autowarefoundation/autoware.universe/actions/runs/9657390668/job/26636582526?pr=7678
This could fail in github ci, need to check.
None.
None.

fix(vehicle_cmd_gate): colcon test failure due to heavy process

---

control/autoware_lane_departure_checker/include/autoware/lane_departure_checker/lane_departure_checker_node.hpp
control/autoware_lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker_node.cpp
planning/motion_velocity_planner/autoware_motion_velocity_dynamic_obstacle_stop_module/src/dynamic_obstacle_stop_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/src/obstacle_velocity_limiter_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/plugin_module_interface.hpp
planning/motion_velocity_planner/autoware_motion_velocity_planner_common/package.xml
planning/motion_velocity_planner/autoware_motion_velocity_planner_node/package.xml
planning/motion_velocity_planner/autoware_motion_velocity_planner_node/src/node.cpp
planning/motion_velocity_planner/autoware_motion_velocity_planner_node/src/node.hpp

Add missing processing time publishers in the `Float64` format.
Psim
None.
`.../processing_time_ms` topics type changed for the `motion_velocity_planner` modules and for the `lane_departure_checker`.
None.

feat(motion_velocity_planner, lane_departure_checker): add processing time Float64 publishers

---

perception/lidar_centerpoint/test/test_postprocess_kernel.cpp

These are fixes based on clang-tidy CRITICAL warnings ( = clang compile error)
For example,
```
constexpr variable 'detection_yaw_sin' must be initialized by a constant expression
```
- Link
None.
None.
None.

fix(lidar_centerpoint): fix constexpr related bugs

---

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/schema/static_obstacle_avoidance.schema.json

Fix json schema. Previously, mkdocs outputed following error when I opened static obstacle avoidance page.
```
Traceback (most recent call last):
File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/mkdocs_macros/plugin.py", line 527, in render
return md_template.render(**page_variables)
File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/jinja2/environment.py", line 1304, in render
self.environment.handle_exception()
File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/jinja2/environment.py", line 939, in handle_exception
raise rewrite_traceback_stack(source=source)
File "<template>", line 1221, in top-level template code
File "/home/runner/work/autoware.universe/autoware.universe/mkdocs_macros.py", line 72, in json_to_markdown …
```

fix(static_obstacle_avoidance): fix json schema

---

control/autoware_pid_longitudinal_controller/include/autoware/pid_longitudinal_controller/pid_longitudinal_controller.hpp
control/autoware_pid_longitudinal_controller/src/pid_longitudinal_controller.cpp
control/autoware_trajectory_follower_node/src/controller_node.cpp

This PR units diagnostic_updater_ in PID and MPC.
1. Local test by manually setting `m_control_state = ControlState::EMERGENCY;`
[Screencast from 06-25-2024 11:48:17 AM.webm](https://github.com/autowarefoundation/autoware.universe/assets/80969277/bc84e11f-4fbb-4ec2-9278-bf3a5d168423)
2. Scenario test
https://evaluation.tier4.jp/evaluation/reports/a1a6f1d7-0cbb-56f4-bf11-3fb2cbea910d?project_id=prd_jt
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/ …

fix(autoware_pid_longitudinal_controller, autoware_trajectory_follower_node): unite diagnostic_updater_ in PID and MPC.

---

control/autoware_mpc_lateral_controller/include/autoware/mpc_lateral_controller/mpc.hpp
control/autoware_mpc_lateral_controller/src/mpc.cpp

Delete the steer rate constraint at zero speed.
Note that the steer rate limit will be consequently determined by the velocity-based and curvature-based limits.
Further modifications might be necessary for these two limits. 
https://evaluation.tier4.jp/evaluation/reports/50dbfc26-ee89-5da5-89f8-76f7215d2ec8?project_id=prd_jt
after deleting the unrelevant variables:
https://evaluation.tier4.jp/evaluation/reports/ac287872-a0a1-5223-a9f9-8b8dbea19c52?project_id=prd_jt
[contribution …

fix(autoware_mpc_lateral_controller): delete the zero speed constraint

---

launch/tier4_perception_launch/launch/object_recognition/detection/detection.launch.xml
launch/tier4_perception_launch/launch/object_recognition/detection/detector/camera_lidar_detector.launch.xml
launch/tier4_perception_launch/launch/object_recognition/detection/detector/lidar_dnn_detector.launch.xml
launch/tier4_perception_launch/launch/object_recognition/detection/detector/lidar_rule_detector.launch.xml
launch/tier4_perception_launch/launch/object_recognition/detection/detector/tracker_based_detector.launch.xml
launch/tier4_perception_launch/launch/object_recognition/detection/merger/camera_lidar_merger.launch.xml
launch/tier4_perception_launch/launch/object_recognition/detection/merger/camera_lidar_radar_merger.launch.xml
launch/tier4_perception_launch/launch/object_recognition/tracking/tracking.launch.xml
launch/tier4_perception_launch/launch/perception.launch.xml

Add an perception option `use_multi_channel_tracker_merger`.
This option replaces object merge pipeline to the [multi-object-tracker multi input functionality](https://github.com/autowarefoundation/autoware.universe/pull/6820).
The new pipeline will be tested.
This work is based on the perception launcher refactoring https://github.com/autowarefoundation/autoware.universe/pull/7194
* perception_mode:=camera_lidar_radar_fusion lidar_detection_model:=pointpainting
* perception_mode:=camera_lidar_radar_fusion lidar_detection_model:=centerpoint
* perception_mode:=camera_lidar_fusion **lidar_detection_model:=pointpainting
* perception_mode:=camera_lidar_fusion lidar_detection_model:=centerpoint
* perception_mode:=camera_lidar_fusion lidar_detection_model:=apollo
* …

feat(tier4_perception_launch): enable multi channel tracker merger

---

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/README.md

Fix wrong flowchart.
- Link
None.
None.
None.

docs(static_obstacle_avoidance): fix wrong flowchart

---

planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/src/obstacle_velocity_limiter.hpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/src/obstacle_velocity_limiter_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/src/trajectory_preprocessing.cpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/src/trajectory_preprocessing.hpp
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/trajectory_preprocessing.hpp

Quick fix to improve the performance of the `out_of_lane` module.
A better solution should be implemented in the future.
- JIRA ticket: [TIER IV Internal link](https://tier4.atlassian.net/browse/RT1-6913)
Psim
- Evaluator: [TIER IV Internal link](https://evaluation.tier4.jp/evaluation/reports/804e7a90-7bc5-593d-a844-6f6a87f01a84?project_id=prd_jt)
None.
None.

perf(out_of_lane): downsample the trajectory to improve performance

---

perception/tensorrt_yolox/src/tensorrt_yolox.cpp

This is a fix based on cppcheck `duplicateBreak` warning
```
perception/tensorrt_yolox/src/tensorrt_yolox.cpp:1282:5: style: Consecutive return, break, continue, goto or throw statements are unnecessary. [duplicateBreak]
return;
^
```
- Link
None.
None.
None.

fix(tensorrt_yolox): fix duplicateBreak warning

---

perception/radar_object_tracker/src/tracker/model/linear_motion_tracker.cpp

This is a fix based on cppcheck `duplicateBranch` warning
```
perception/radar_object_tracker/src/tracker/model/linear_motion_tracker.cpp:143:3: style: inconclusive: Found duplicate branches for 'if' and 'else'. [duplicateBranch]
if (has_acceleration_covariance) {
^
perception/radar_object_tracker/src/tracker/model/linear_motion_tracker.cpp:153:5: note: Found duplicate branches for 'if' and 'else'.
} else {
^
perception/radar_object_tracker/src/tracker/model/linear_motion_tracker.cpp:143:3: note: Found duplicate branches for 'if' and 'else'.
if (has_acceleration_covariance) {
^
```
- Link
None.
None.
None.

fix(radar_object_tracker): fix duplicateBranch warning

---

planning/autoware_velocity_smoother/src/node.cpp

This is a fix based on cppcheck `duplicateBreak` warning
```
planning/autoware_velocity_smoother/src/node.cpp:1016:3: style: Consecutive return, break, continue, goto or throw statements are unnecessary. [duplicateBreak]
return AlgorithmType::INVALID;
^
```
- Link
None.
None.
None.

fix(autoware_velocity_smoother): fix duplicateBreak warning

---

localization/localization_error_monitor/include/localization_error_monitor/localization_error_monitor.hpp
localization/localization_error_monitor/package.xml
localization/localization_error_monitor/src/localization_error_monitor.cpp
localization/localization_util/CMakeLists.txt
localization/localization_util/include/localization_util/covariance_ellipse.hpp
localization/localization_util/src/covariance_ellipse.cpp

Since several modules, not only ekf, output pose_with_covariance, it would be a good idea to move the error ellipse struct and its visualization code into localization_util to make it common.
None.
I have confirmed that logging_simulator works well.
To get a larger error ellipse, I ran the experiment with NDT turned off and confirmed that the correct error ellipse was visualized just as before.
None.
None.
None.

refactor(localization_util): add covariance_ellipse to localization_util

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/README.md
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/config/goal_planner.param.yaml
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/manager.cpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/README.md
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/config/lane_change.param.yaml
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/data_structs.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/manager.cpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/docs/behavior_path_planner_safety_check.md
planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/path_safety_checker/path_safety_checker_parameters.hpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/path_safety_checker/safety_check.hpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_safety_checker/safety_check.cpp
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/README.md
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/config/start_planner.param.yaml
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/include/autoware/behavior_path_start_planner_module/data_structs.hpp
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/include/autoware/behavior_path_start_planner_module/start_planner_module.hpp
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/manager.cpp
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/start_planner_module.cpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/config/static_obstacle_avoidance.param.yaml
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/data_structs.hpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/parameter_helper.hpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/schema/static_obstacle_avoidance.schema.json
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp

This PR adds a yaw threshold to skip rss check when the yaws of the ego predicted path and the predicted object are too different, to avoid RSS checks like this:
Note, this PR requires launch changes: https://github.com/autowarefoundation/autoware_launch/pull/1040
[TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT1-6090?focusedCommentId=174545)
PSim
Degradation tests [TIER IV INTERNAL LINK](https://evaluation.ci.tier4.jp/evaluation/reports/ea324569-680e-535d-b18a-c8a358db0738?project_id=prd_jt) …

feat(start_planner): yaw threshold for rss check

---

planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/src/scene.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_no_stopping_area_module/src/scene_no_stopping_area.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/include/autoware/behavior_velocity_planner_common/utilization/arc_lane_util.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/src/utilization/arc_lane_util.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/test/src/test_arc_lane_util.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_stop_line_module/src/scene.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_virtual_traffic_light_module/src/scene.cpp

Currently, when checking the intersection of stop_line and path, it was checked if the lane_id of the intersection is the same as the one specified. However, this check is meaningless and may cause the following error. Therefore, the code to check the lane_id has been removed.
https://tier4.atlassian.net/browse/RT0-30839
https://evaluation.ci.tier4.jp/evaluation/reports/6f5f6e7c-1d11-5ca3-b5cd-f89ac8fca216?project_id=prd_jt
None.
None.
None.

fix(autoware_behavior_velocity_planner_common): remove lane_id check from arc_lane_util

---

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/README.md
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/config/static_obstacle_avoidance.param.yaml
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/data_structs.hpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/parameter_helper.hpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/schema/static_obstacle_avoidance.schema.json
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp

We don't expect to set params for drivable lane as follow:
```yaml
use_adjacent_lane: false
use_opposite_lane: true
```
However, we were able to do that in previous config structure.
I fixed it to prevent unexpected paramter configuration.
:warning: Please approve this PR at first.
- https://github.com/autowarefoundation/autoware_launch/pull/1042
Psim
```yaml
use_lane_type: "same_direction_lane"
```
```yaml
use_lane_type: "opposite_direction_lane"
```
None.
None.
None.

refactor(static_obstacle_avoidance): organize params for drivable lane

---

planning/obstacle_stop_planner/src/adaptive_cruise_control.cpp

This is a fix based on cppcheck `unreadVariable` warning
```
planning/obstacle_stop_planner/src/adaptive_cruise_control.cpp:646:14: style: Variable 'diff_vel' is assigned a value that is never used. [unreadVariable]
diff_vel *= param_.d_coeff_pos;
^
planning/obstacle_stop_planner/src/adaptive_cruise_control.cpp:649:14: style: Variable 'diff_vel' is assigned a value that is never used. [unreadVariable]
diff_vel *= param_.d_coeff_neg;
^
```
It seems to be a bug for me, so I changed it to multiply each `coeff` to `add_vel_d`, not to `diff_vel`.
Please confirm it carefully. thank you. …

fix(obstacle_stop_planner): fix unreadVariable warning

---

localization/autoware_landmark_based_localizer/autoware_ar_tag_based_localizer/README.md
localization/pose_estimator_arbiter/README.md

Since `autoware_auto_msgs` is replaced to `autoware_msgs`, I've updated the sample rosbags written in the README.md of localization modules to suit this change.
Sample rosbags of the following has been updated in this PR
- autoware_ar_tag_based_localizer
- pose_estimator_arbiter
These rosbags are made and preserved by TIER IV.
The disscussion of changing the message types: https://github.com/orgs/autowarefoundation/discussions/3862
I've tested all rosbags work in the current autoware.universe.
None.
None.
None.

chore: update sample rosbags for localization modules

---

perception/object_velocity_splitter/CMakeLists.txt
perception/object_velocity_splitter/include/autoware/object_velocity_splitter/object_velocity_splitter_node.hpp
perception/object_velocity_splitter/src/object_velocity_splitter_node.cpp
perception/object_velocity_splitter/src/object_velocity_splitter_node.hpp

Also, align directory structure to follow [the coding guidelines.](https://autowarefoundation.github.io/autoware-documentation/main/contributing/coding-guidelines/ros-nodes/directory-structure/#exporting-a-composable-node-component-executables) …

refactor(object_velocity_splitter)!: fix namespace and directory structure

---

perception/radar_object_clustering/CMakeLists.txt
perception/radar_object_clustering/include/autoware/radar_object_clustering/radar_object_clustering_node.hpp
perception/radar_object_clustering/src/radar_object_clustering_node.cpp
perception/radar_object_clustering/src/radar_object_clustering_node.hpp

Also, align directory structure to follow [the coding guidelines.](https://autowarefoundation.github.io/autoware-documentation/main/contributing/coding-guidelines/ros-nodes/directory-structure/#exporting-a-composable-node-component-executables) …

refactor(radar_object_clustering)!: fix namespace and directory structure

---

planning/behavior_velocity_planner/autoware_behavior_velocity_speed_bump_module/src/util.cpp

This is a fix based on cppcheck `containerOutOfBounds` warning
```
planning/behavior_velocity_planner/autoware_behavior_velocity_speed_bump_module/src/util.cpp:104:37: warning: inconclusive: Either the condition 'intersects.size()==1' is redundant or size of 'intersects' can be 1. Expression 'intersects.at(i)' causes access out of bounds. [containerOutOfBounds]
const auto & p = intersects.at(i);
^
planning/behavior_velocity_planner/autoware_behavior_velocity_speed_bump_module/src/util.cpp:107:28: note: Assuming that condition 'intersects.size()==1' is not redundant
(intersects.size() == 1 && is_last_path_point_inside_polygon)) {
^
planning/behavior_velocity_planner/autoware_behavior_velocity_speed_bump_module/src/util.cpp:104:37: note: Access out of bounds
const auto & p = …
```

fix(autoware_behavior_velocity_speed_bump_module): fix containerOutOfBounds warning

---

.cppcheck_suppressions

Could be merged after https://github.com/autowarefoundation/autoware.universe/pull/7671 is merged.
- Link
None.
None.
None.

chore(ci): remove unnecessary cppcheck suppressions

---

perception/object_merger/README.md
perception/object_merger/config/object_association_merger.param.yaml
perception/object_merger/schema/data_association_matrix.schema.json
perception/object_merger/schema/object_association_merger.schema.json
perception/object_merger/schema/overlapped_judge.schema.json
perception/object_merger/src/object_association_merger/node.cpp

Implement the ROS Node configuration layout described in https://github.com/orgs/autowarefoundation/discussions/3371 for the `object_merger` package.
* Remove the default value from the source code in order to ensure all parameter values are passed from the parameter files.
* Use types that match the ones returned from declare_parameter() in order to prevent confusion and potential coding errors.
* Move the default parameter file to a standardized location. Use the JSON Schema for that.
* Updated readme file.
Package built and launched locally.
Nothing inside the src code part was changed, only taking the parameters out.
Parameter values are now required to be passed to the node when launched.
None …

refactor(object_merger): rework parameters

---

control/autoware_autonomous_emergency_braking/src/node.cpp

Due to the use of resize() the path vector generates a vector full of path points with position x:0 y:0 z:0 . This causes the AEB module to generate a wrong polygon path (because the last path poses are located at the base link). 
This PR fixes the issue by doing reserve() instead, which seems like the original intention of the original commit. 
- Link
Before: 
The polygon is disjointed and an NPC is wrongly detected as an obstacle.
After: 
The polygons are correct and no collision is detected!
None.
None.
None.

fix(autonomous_emergency_braking): aeb strange mpc polygon

---

control/autoware_autonomous_emergency_braking/README.md
control/autoware_autonomous_emergency_braking/include/autoware/autonomous_emergency_braking/node.hpp
control/autoware_autonomous_emergency_braking/src/node.cpp

Add support to compute RSS distance with negative object speeds.
- Link
PSim 
See video for testing when ego goes forward and backwards, default NPC car speed is 3 m/s
https://github.com/autowarefoundation/autoware.universe/assets/25967964/5f93c9c3-b68e-4f65-9063-d9e5457cd0e2
None.
None.
None.

feat(autonomous_emergency_braking): aeb add support negative speeds

---

.github/CODEOWNERS
control/autoware_autonomous_emergency_braking/include/autoware/autonomous_emergency_braking/node.hpp
control/autoware_autonomous_emergency_braking/include/autoware/autonomous_emergency_braking/utils.hpp
control/autoware_autonomous_emergency_braking/src/node.cpp
control/autoware_autonomous_emergency_braking/src/utils.cpp

Apply changes suggested by clangd 
- Link
PSim
None.
None.
None.

chore(autonomous_emergency_braking): apply clangd suggestions to aeb

---

localization/yabloc/yabloc_pose_initializer/include/yabloc_pose_initializer/camera/camera_pose_initializer.hpp
localization/yabloc/yabloc_pose_initializer/include/yabloc_pose_initializer/camera/semantic_segmentation.hpp
localization/yabloc/yabloc_pose_initializer/src/camera/camera_pose_initializer_core.cpp
localization/yabloc/yabloc_pose_initializer/src/camera/lane_image.cpp
localization/yabloc/yabloc_pose_initializer/src/camera/marker_module.cpp
localization/yabloc/yabloc_pose_initializer/src/camera/projector_module.cpp
localization/yabloc/yabloc_pose_initializer/src/camera/semantic_segmentation.cpp

This PR applies some suggestions from the linter to `localization/yabloc/yabloc_pose_initializer`.
Fixed:
- camelCase to snake_case for variable
- remove `_` from non-private variable
- align variable name in header's definition and the implementation
- LOCAL_VAR to local_var
- add or removed keyword from function/method which linter suggested
not Fixed:
- [hicpp-signed-bitwise](https://releases.llvm.org/14.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/hicpp-signed-bitwise.html)
- this occurs from bit shift operation in OpenCV, so currently it is marked as `NOLINT`
- C11 extension error [clang-diagnostic-c11-extensions]
- like `error: '_Atomic' is a C11 extension [clang-diagnostic-c11-extensions] …

refactor(yabloc_pose_initializer): apply static analysis

---

launch/tier4_system_launch/launch/system.launch.xml

By default, use mrm_handler instead of emergency_handler. 
See https://github.com/orgs/autowarefoundation/discussions/4176 for details.
- https://github.com/orgs/autowarefoundation/discussions/4176
- https://github.com/autowarefoundation/autoware_launch/pull/1043
Launch planning simulation, and check the vehicle can reach a goal.
None.
None.
Use  [diagnostic_graph_aggregator config](https://github.com/autowarefoundation/autoware.universe/tree/main/system/system_diagnostic_monitor/config) instead of  [system_error_monitor config](https://github.com/autowarefoundation/autoware.universe/tree/main/system/system_error_monitor/config).

feat(tier4_system_launch): use mrm handler by default

---

localization/pose_instability_detector/src/pose_instability_detector.cpp
localization/pose_instability_detector/test/test.cpp

In `pose_instability_detector`, a bug has been fixed that in rare abnormal cases, it may access to outside the queue size and crash, or it may show abnormal values.
I have added test cases that cause this, and I have confirmed that it fails probabilistically if it is not fixed.
Since accessing outside the range is undefined behavior, it does not necessarily always fail.
By making a modification of pose_instability_detector.cpp, the test will no longer fail even after 100 consecutive attempts.
None.
The following script was used.
```
./test_loop.sh pose_instability_detector
```
```bash
#!/bin/bash
set -eux
TEST_TARGET_PKG=$1
LOOP_NUM=${2:-100}
colcon build --symlink-install \
--cmake-args \
-DCMAKE_BUILD_TYPE=Release \
-DBUILD_TESTING=ON \
--packages-select $TEST_TARGET_PKG
for ((i=1; …
```

fix(pose_instability_detector): fix a rare error

---

control/autoware_joy_controller/include/autoware/joy_controller/joy_controller.hpp
control/autoware_joy_controller/include/autoware/joy_controller/joy_converter/g29_joy_converter.hpp
control/autoware_joy_controller/include/autoware/joy_controller/joy_converter/joy_converter_base.hpp
control/autoware_joy_controller/src/joy_controller_node.cpp

- Because a virtual class requires a virtual destructor, it has been added.
- Some refactorings
https://stackoverflow.com/questions/461203/when-to-use-virtual-destructors
None.
None.
None.

fix(autoware_joy_controller): add virtual destructor to autoware_joy_controller

---

common/tvm_utility/include/tvm_utility/pipeline.hpp

Because a virtual class requires a virtual destructor, it has been added.
https://stackoverflow.com/questions/461203/when-to-use-virtual-destructors
None.
None.
None.

fix(tvm_utility): add virtual destructor to tvm_utility

---

planning/autoware_static_centerline_generator/scripts/centerline_updater_helper.py

Saving the map twice by centerline_updater_helper.py did not work well as written in the comment of the changes.
This PR suppress the usage.
Unit test passed.
None.
None.
None.

fix(static_centerline_generator): save_map only once

---

.cppcheck_suppressions

Solved `duplicateBranch` warnings in https://github.com/autowarefoundation/autoware.universe/pull/7695
None.
None.
None.

chore(ci): remove unnecessary cppcheck suppression

---

evaluator/autoware_planning_evaluator/include/autoware/planning_evaluator/planning_evaluator_node.hpp
evaluator/autoware_planning_evaluator/launch/planning_evaluator.launch.xml
evaluator/autoware_planning_evaluator/package.xml
evaluator/autoware_planning_evaluator/src/planning_evaluator_node.cpp

Add kinematic state and lanelet info to the planning evaluator for DLR purposes. 
- Link
PSim
https://github.com/autowarefoundation/autoware.universe/assets/25967964/e639f63f-67b9-4ffb-b861-c35db7b13db4
None.
None.
None.

feat(planning_evaluator): add lanelet info to the planning evaluator

---

evaluator/autoware_control_evaluator/CMakeLists.txt
evaluator/autoware_control_evaluator/include/autoware/control_evaluator/control_evaluator_node.hpp
evaluator/autoware_control_evaluator/src/control_evaluator_node.cpp
launch/tier4_control_launch/launch/control.launch.py

Change class name and use the remapped topic name for consistency.
- Link
PSim
https://github.com/autowarefoundation/autoware.universe/assets/25967964/01b8833f-b32e-46ec-84e9-f38ffd2b2489
None.
None.
None.

refactor(control_evaluator): use class naming standard and use remapped param name

---

system/mrm_handler/include/mrm_handler/mrm_handler_core.hpp
system/mrm_handler/src/mrm_handler/mrm_handler_core.cpp

By switching to the diagnostics graph in the [PR](https://github.com/autowarefoundation/autoware_launch/pull/1043), a problem arose where the state becomes emergency when scenario_simulator_v2 starts up, causing the simulation to fail.
This change fixes the above problem by operating MRM only during autonomous operation mode.
None.
None.
None.

feat(mrm_handler): operate mrm only when autonomous operation mode

---

codecov.yaml

Since CodeCov configuration was fixed with:
- https://github.com/autowarefoundation/autoware.universe/pull/7767
We started having these checks as errors in CI.
Since we are not enforcing this check to pass, I'm reducing the thresholds to allow anything to pass these tests.
And we'll use it as an informative tool for the time being.
https://github.com/autowarefoundation/autoware.universe/commits/main/
- https://docs.codecov.com/docs/commit-status#project-status
**Partly Related Issue:**
- https://github.com/autowarefoundation/autoware.universe/issues/7769
Since this works with a GitHub App, I guess we can't test it unless we merge it :D
It's all well documented and change is minimal so it should be alright.
Here I am pasting the explanation of the values that I've changed.
In summary, I'm …

ci(codecov.yaml): make ci succeed regardless of coverage

---

.github/cppcheck-problem-matcher.json
.github/workflows/cppcheck-daily.yaml
.github/workflows/cppcheck-differential.yaml
simulator/simple_planning_simulator/src/simple_planning_simulator/simple_planning_simulator_core.cpp

Add problem matcher for cppcheck messages to annotate in file diff view in GitHub.
Check the cppcheck error is matched well.
https://github.com/autowarefoundation/autoware.universe/actions/runs/9763078681/job/26948068884?pr=7794#step:12:7
None.
None.
None.

chore(ci): add problem matcher for cppcheck

---

sensing/pointcloud_preprocessor/src/downsample_filter/faster_voxel_grid_downsample_filter.cpp

This PR fixes a typo in the if statement in the `get_min_max_voxel` function in faster_voxel_grid_downsample_filter.cpp.
[Discussion in Slack](https://star4.slack.com/archives/CEV8XMJBV/p1719965385138959?thread_ts=1719796541.332269&cid=CEV8XMJBV) (TIER IV internal)
None.
None.
None.
None.

fix(faster_voxel_grid_downsample_filter): typo in if statement in get_min_max_voxel()

---

common/autoware_point_types/package.xml

In https://github.com/autowarefoundation/autoware.universe/pull/6996
Files from the `autoware_point_types` are changed. However, the maintainer no longer belongs to the organization and such, new mantainers need to be added.
- Link
None.
None.
None.

chore: updated maintainers for the autoware_point_types package

---

sensing/livox/autoware_livox_tag_filter/src/livox_tag_filter_node.cpp
sensing/pointcloud_preprocessor/src/concatenate_data/concatenate_and_time_sync_nodelet.cpp
sensing/pointcloud_preprocessor/src/concatenate_data/concatenate_pointclouds.cpp
sensing/pointcloud_preprocessor/src/crop_box_filter/crop_box_filter_nodelet.cpp
sensing/pointcloud_preprocessor/src/distortion_corrector/distortion_corrector.cpp
sensing/pointcloud_preprocessor/src/filter.cpp
sensing/pointcloud_preprocessor/src/outlier_filter/dual_return_outlier_filter_nodelet.cpp
sensing/pointcloud_preprocessor/src/outlier_filter/ring_outlier_filter_nodelet.cpp
sensing/pointcloud_preprocessor/src/time_synchronizer/time_synchronizer_nodelet.cpp
sensing/pointcloud_preprocessor/src/vector_map_filter/lanelet2_map_filter_nodelet.cpp
sensing/radar_scan_to_pointcloud2/src/radar_scan_to_pointcloud2_node/radar_scan_to_pointcloud2_node.cpp

This change would allow runtime qos configuration for filter output topic. Currently, it is not even possible to use filters with nodes which have qos configured as reliable. 
According to [ROS2 documentation](https://design.ros2.org/articles/qos_configurability.html) it would be possible to configure qos at runtime:
```
Node(
package="pointcloud_preprocessor",
executable="crop_box_filter_node",
name="crop_box_filter",
parameters=[
{"input_frame": "base_link"},
{"output_frame": "base_link"},
{"qos_overrides.output.reliability": "reliable"},
],
),
```            
The `output` topic must be in fact fully qualified topic name, and cannot be changed after the node is constructed, however this feature is still extending filter nodes usability. 
Feature: I've tested crop-box-filter with …

feat(pointcloud_preprocessor): runtime configurable output topic qos

---

codecov.yaml

I think I should have updated these lines too.
It got better, only 2 are failing now. With these too, all should pass.
**Continuation from:**
- https://github.com/autowarefoundation/autoware.universe/pull/7793
The targets for these were changed [in the previous PR](https://github.com/autowarefoundation/autoware.universe/pull/7793):
None.
None.

ci(codecov.yaml): make it pass regardless of coverage

---

perception/autoware_map_based_prediction/src/map_based_prediction_node.cpp
perception/autoware_map_based_prediction/src/path_generator.cpp

This is a fix based on cppcheck `syntaxError` error.
```
perception/autoware_map_based_prediction/src/map_based_prediction_node.cpp:1774:16: error: The code contains unhandled character(s) (character code=206). Neither unicode nor extended ascii is supported. [syntaxError]
const double λ = std::log(2) / acceleration_exponential_half_life_;
^
perception/autoware_map_based_prediction/src/path_generator.cpp:424:15: error: The code contains unhandled character(s) (character code=206). Neither unicode nor extended ascii is supported. [syntaxError]
const float λ = std::log(2) / acceleration_exponential_half_life_;
^
```
Changes are only renaming `λ` to `lambda`.
- Link
None.
None.
None.

fix(autoware_map_based_prediction): fix syntaxError

---

common/tier4_planning_rviz_plugin/include/tier4_planning_rviz_plugin/path/display.hpp

Fixes: https://github.com/autowarefoundation/autoware.universe/issues/7684
Actually, cases where `diff_angle` is 0 are handled differently [here](https://github.com/autowarefoundation/autoware.universe/blob/fbbc44ceb33c423c00ba3caa826ff77c8958d920/common/tier4_planning_rviz_plugin/include/tier4_planning_rviz_plugin/path/display.hpp#L80), but when values ​​very close to 0 are handled as any other value, the width is miscalculated, so strange boundaries appear.
**Parent Issue:** 
- https://github.com/autowarefoundation/autoware.universe/issues/7634
- In psim
| Before  | After |
| ------------- | ------------- |
| <video src="https://github.com/autowarefoundation/autoware.universe/assets/32412808/bb8e6efa-5db4-4d08-a0a0-707edc649e4f">  | <video …

fix(tier4_planning_rviz_plugin): fix calculation of drivable area bounds

---

planning/autoware_freespace_planning_algorithms/scripts/bind/astar_search_pybind.cpp

This is just to avoid cppcheck `syntaxError` error
```
planning/autoware_freespace_planning_algorithms/scripts/bind/astar_search_pybind.cpp:102:1: error: syntax error [syntaxError]
PYBIND11_MODULE(autoware_freespace_planning_algorithms_pybind, p)
^
```
- Link
None.
None.
None.

fix(autoware_freespace_planning_algorithms): fix syntaxError

---

planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_shifter/path_shifter.cpp

```
planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_shifter/path_shifter.cpp:197:39: style: Condition 'shift_line.start_idx<=i' is always true [knownConditionTrueFalse]
} else if (shift_line.start_idx <= i && i <= shift_line.end_idx) {
^
planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_shifter/path_shifter.cpp:195:13: note: Assuming that condition 'i<shift_line.start_idx' is not redundant
if (i < shift_line.start_idx) {
^
planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_shifter/path_shifter.cpp:197:39: note: Condition 'shift_line.start_idx<=i' is always true
} else if (shift_line.start_idx <= i && i <= …
```

fix(autoware_behavior_path_planner_common): fix knownConditionTrueFalse

---

perception/cluster_merger/CMakeLists.txt
perception/cluster_merger/src/cluster_merger_node.cpp
perception/cluster_merger/src/cluster_merger_node.hpp

In a local recompute environment, TIER IV Cloud enviornment.
[TIER IV INTERNAL](https://evaluation.tier4.jp/evaluation/reports/dccc10d6-26a4-5389-9712-b821f000bdb1?project_id=prd_jt)
None.
None.
None.

refactor(cluster_merger)!: fix namespace and directory structure

---

localization/autoware_stop_filter/CMakeLists.txt

This PR fix the plugin name of `stop_filter`.
If this fix is not applied, the `stop_filter` node will not be launched properly and the `/localization/kinematic_state` topic will not be output.
- https://github.com/autowarefoundation/autoware.universe/pull/7789
* Autoware + AWSIM works
* logging_simulator works
None.
None.
None.

fix(stop_filter): fix plugin name

---

perception/detection_by_tracker/CMakeLists.txt
perception/detection_by_tracker/launch/detection_by_tracker.launch.xml
perception/detection_by_tracker/package.xml
perception/detection_by_tracker/src/debugger/debugger.hpp
perception/detection_by_tracker/src/detection_by_tracker_node.cpp
perception/detection_by_tracker/src/detection_by_tracker_node.hpp
perception/detection_by_tracker/src/utils/utils.cpp
perception/detection_by_tracker/src/utils/utils.hpp

Tested in a local recompute environment and the TIER IV Cloud environment.
[TIER IV INTERNAL](https://evaluation.tier4.jp/evaluation/reports/dccc10d6-26a4-5389-9712-b821f000bdb1?project_id=prd_jt)
None.
None.
None.

refactor(detection_by_tracker)!: fix namespace and directory structure

---

planning/autoware_freespace_planning_algorithms/autoware_freespace_planning_algorithms/astar_search.py
planning/autoware_freespace_planning_algorithms/scripts/bind/astar_search_pybind.cpp

This is an updated version of the [A* python wrapper](https://github.com/autowarefoundation/autoware.universe/pull/6398)
The previous version does not have [is_back](https://github.com/autowarefoundation/autoware.universe/blob/7a6bf3983bdc602856ab6accefa5a04cb1d3f748/planning/autoware_freespace_planning_algorithms/include/autoware/freespace_planning_algorithms/abstract_algorithm.hpp#L105) in the result return of A* search. I append it with this PR.
[#6398](https://github.com/autowarefoundation/autoware.universe/pull/6398)
Evaluator: https://evaluation.tier4.jp/evaluation/reports/54647b99-62d4-5849-b6f8-d7d78de25c8c?project_id=prd_jt
N/A
N/A
This feature is independent of the main autoware features. There are no effects. …

feat(freespace_planning_algorithms): add is_back flag into the return of A* python wrapper

---

planning/autoware_freespace_planning_algorithms/src/astar_search.cpp

Modify A* script for standalone running.
When the A* algorithm runs via the freespace_planner node, the planner clears the A* node previously. 
But when the makePlan() method in the A* node runs standalone (for example running via python wrapper), the node is not cleared.
I append clearNode() in makePlan().
Python wrapper of A* algorithms [PR#6398](https://github.com/autowarefoundation/autoware.universe/pull/6398)
Tools for python wrapper [autoware_tools PR#28](https://github.com/autowarefoundation/autoware_tools/pull/28)
Evaluator: https://evaluation.tier4.jp/evaluation/reports/fbb9175f-1204-5605-a2fd-fbc995e6aaed?project_id=prd_jt
There are no changes in interfaces. …

chore(freespace_planning_algorithm): modify A* script for standalone running

---

perception/radar_fusion_to_detected_object/src/radar_fusion_to_detected_object.cpp

This is a cppcheck warning
```
perception/radar_fusion_to_detected_object/src/radar_fusion_to_detected_object.cpp:98:32: style: Condition 'split_objects.size()==1' is always true [knownConditionTrueFalse]
if (split_objects.size() == 1) {
^
```
What did you mean here?
Maybe my modification `split_object.size() == 1` is incorrect.
- Link
None.
None.
None.

fix(radar_fusion_to_detected_object): fix knownConditionTrueFalse

---

planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/intersection_lanelets.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/object_manager.cpp

This is a fix based on cppcheck `shadowFunction` warnings
```
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/intersection_lanelets.cpp:51:16: style: Local variable 'first_attention_lane' shadows outer function [shadowFunction]
const auto first_attention_lane = first_attention_lane_.value();
^
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/intersection_lanelets.hpp:86:48: note: Shadowed declaration
const std::optional<lanelet::ConstLanelet> & first_attention_lane() const
^
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/intersection_lanelets.cpp:51:16: note: Shadow variable
const auto first_attention_lane = first_attention_lane_.value();
^
```
``` …
```

fix(autoware_behavior_velocity_intersection_module): fix shadowFunction

---

planning/autoware_obstacle_cruise_planner/include/autoware/obstacle_cruise_planner/planner_interface.hpp
planning/autoware_obstacle_cruise_planner/src/node.cpp
planning/autoware_obstacle_cruise_planner/src/planner_interface.cpp

Add an output to /diagnostics showing data about stop. 
Also refactored a complex boolean logic to improve readability in node.cpp
- Link
PSim
ros2 topic echo /diagnostics:
Example output: 
Stop: 
header:
stamp:
sec: 1720074365
nanosec: 133470854
frame_id: map
status:
- level: "\0"
name: obstacle_cruise_planner
message: ''
values:
- key: decision
value: stop
- key: stop_position
value: '{89607.856760, 43010.903088, 6.367879}'
- key: stop_orientation
value: '{0.959131, 0.000695, -0.002355, 0.282953}'
- key: distance_to_stop_pose
value: '0.132687'
- key: collision_point
value: '{89614.570092, 43016.732919, 6.323306}'
No stop decision: 
---
header:
stamp:
sec: 1720073879
nanosec: 55494950
frame_id: map
status:
- level: "\0"
name: obstacle_cruise_planner …

feat(obstacle_cruise_planner): add diagnostics publishing to cruise planner
