system/diagnostic_graph_aggregator/src/common/graph/config.cpp, system/diagnostic_graph_aggregator/src/common/graph/data.cpp, system/diagnostic_graph_aggregator/src/common/graph/units.cpp
This is a fix based on cppcheck `shadowFunction` warnings
```
system/diagnostic_graph_aggregator/src/common/graph/config.cpp:71:14: style: Local variable 'paths' shadows outer function [shadowFunction]
const auto paths = tree.optional("files").children("files");
^
system/diagnostic_graph_aggregator/src/common/graph/config.hpp:73:16: note: Shadowed declaration
const auto & paths() const { return paths_; }
^
system/diagnostic_graph_aggregator/src/common/graph/config.cpp:71:14: note: Shadow variable
const auto paths = tree.optional("files").children("files");
^
```
```
system/diagnostic_graph_aggregator/src/common/graph/data.cpp:38:14: style: Local variable 'path' shadows outer function [shadowFunction]
const auto path = path_.field(name);
^ …
```
=> fix(diagnostic_graph_aggregator): fix shadowFunction

planning/behavior_path_planner/autoware_behavior_path_avoidance_by_lane_change_module/src/scene.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/util.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/path_safety_checker/objects_filtering.hpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_safety_checker/objects_filtering.cpp, planning/behavior_path_planner/autoware_behavior_path_start_planner_module/include/autoware/behavior_path_start_planner_module/pull_out_planner_base.hpp, planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/start_planner_module.cpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp
Sometimes, the safety check caused false positive because it couldn't judge which lane the object belonged to properly.
**Example**: the red lanes mean safety check target lane for avoidance maneuver in following movie and a vehicle is trying to merge ego lane. Basically, the avoidance module only check objects which are on shift side adjacent lane, so the ego don't have to revert avoidance path due to the object in this case. But the object becomes safety check target when it's on safety check target lane even though the direction is different from the lane direction.
https://github.com/autowarefoundation/autoware.universe/assets/44889564/2b276be3-a8b3-4356-a4c3-1bb8261c392e
---
After this PR, we're going to be able to set yaw deviation threshold and ignore the object whose pose is not …
=> feat(safety_check): filter safety check targe objects by yaw deviation between pose and lane

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/config/goal_planner.param.yaml, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_parameters.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/pull_over_planner_base.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/manager.cpp
prioritize low curvature pull over path rather than high curvature one.
before
after
NOTE:
Currently, the curvature is calculated between the start and end poses. There is no prioritization among high curvatures, but it may be necessary to improve this by reducing the priority of paths with high curvature close to the curb, etc.
- Link
- https://tier4.atlassian.net/browse/RT1-6546
psim
2024/07/03 https://evaluation.tier4.jp/evaluation/reports/e544fff5-a209-56e3-ac19-47e3f7c2620a?project_id=prd_jt
None.
None.
None.
=> feat(goal_planner): prioritize pull over path by curvature

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/data_structs.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/debug.cpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/shift_line_generator.cpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp
Originally, this module checks whether the object polygon is perfectly in intersection polygon. But somtimes it caused wrong judgement due to the perception performance or noise. In this PR, I changed the logic to use object position point instead of its polygon for `boost::geometry::within` function.
---
This moule checks whether the object is on ego lane by using `route_handler->getNextLaneletWithinRoute`. But the lane where the bus is on is NOT included in route lanelet in following fig.
Then, I added following process to handle this situation.
```c++
if (route_handler->getNextLaneletWithinRoute(object.overhang_lanelet, &next_lanelet)) {
...
} else {
for (const auto & lane : route_handler->getNextLanelets(object.overhang_lanelet)) {
if (boost::geometry::within( …
```
=> fix(static_obstacle_avoidance): fix issues in target object filtering logic

launch/tier4_perception_launch/launch/obstacle_segmentation/ground_segmentation/ground_segmentation.launch.py, perception/occupancy_grid_map_outlier_filter/CMakeLists.txt, perception/occupancy_grid_map_outlier_filter/package.xml, perception/occupancy_grid_map_outlier_filter/src/occupancy_grid_map_outlier_filter_node.cpp, perception/occupancy_grid_map_outlier_filter/src/occupancy_grid_map_outlier_filter_node.hpp
Tested in a local recompute environment and the TIER IV Cloud environment.
[TIER IV INTERNAL](https://evaluation.tier4.jp/evaluation/reports/dccc10d6-26a4-5389-9712-b821f000bdb1?project_id=prd_jt)
None.
None.
None.
=> refactor(occupancy_grid_map_outlier_filter)!: fix namespace and directory structure

perception/detected_object_feature_remover/CMakeLists.txt, perception/detected_object_feature_remover/launch/detected_object_feature_remover.launch.xml, perception/detected_object_feature_remover/src/detected_object_feature_remover_node.cpp, perception/detected_object_feature_remover/src/detected_object_feature_remover_node.hpp
Tested in a local recompute environment and the TIER IV Cloud environment.
[TIER IV INTERNAL](https://evaluation.tier4.jp/evaluation/reports/dccc10d6-26a4-5389-9712-b821f000bdb1?project_id=prd_jt)
None.
None.
None.
=> refactor(detected_object_feature_remover)!: fix namespace and directory structure

planning/motion_velocity_planner/autoware_motion_velocity_planner_node/src/node.cpp
Currently slowdowns in the `motion_velocity_planner` are incorrectly setting a velocity of 0.
This PR fixes the issue by using the correct velocity.
- Link
None.
None.
None.
=> fix(motion_velocity_planner): use the slowdown velocity (instead of 0)

map/map_height_fitter/include/map_height_fitter/map_height_fitter.hpp, map/map_height_fitter/src/map_height_fitter.cpp
This PR applies some suggestions from the linter to `map/map_height_fitter`.
Fixed:
- add or removed keyword from function/method which linter suggested
- add explicit delete for constructor
- fix use of std::make_shared with pcl::PointXYZ
not Fixed:
- Link
Checked with clang-tidy (v14.0.0) and cppcheck (v2.14.1)
<details>
```
#!/bin/bash
set -eux
TARGET_DIR=$1
exit 1
fi
set +eux
export …
```
=> refactor(map_height_fitter): apply static analysis 

planning/autoware_velocity_smoother/src/node.cpp
[Before using the polling subscriber ](https://github.com/autowarefoundation/autoware.universe/pull/7216) the member variable `external_velocity_limit_ptr_` was set to `nullptr` once it was used. However by using `takeData()` the latest msg would be used continuously.  This PR solves the problem by utilizing `takeNewData()` instead of `takeData()`.
None
[TIER IV internal simulator](https://evaluation.tier4.jp/evaluation/reports/f87b4ca1-b5db-53c7-ba1e-a97b5217e34f?project_id=prd_jt)
None.
None.
None.
=> refactor(velocity_smoother): change method to take data for external velocity

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp
Left opposite lanes were not considered in the getAdjacentLane function. This PR adds the left opposite lanes inside the function.
None
[Internal test](https://evaluation.tier4.jp/evaluation/reports/2231c1a3-cf06-55fd-b04e-e251873acdc3?project_id=prd_jt)
None.
None.
Static obstacle avoidance should cover wider scenes.
=> refactor(static_avoidance): modify getAdjacentLane function

perception/probabilistic_occupancy_grid_map/src/fusion/single_frame_fusion_policy.cpp, perception/probabilistic_occupancy_grid_map/src/pointcloud_based_occupancy_grid_map/occupancy_grid_map_projective.cpp
This is a fix based on cppcheck `noExplicitConstructor` warnings
```
perception/probabilistic_occupancy_grid_map/src/pointcloud_based_occupancy_grid_map/occupancy_grid_map_projective.cpp:78:5: style: Struct 'BinInfo3D' has a constructor with 1 argument that is not explicit. [noExplicitConstructor]
BinInfo3D(
^
perception/probabilistic_occupancy_grid_map/src/fusion/single_frame_fusion_policy.cpp:174:3: style: Struct 'dempsterShaferOccupancy' has a constructor with 1 argument that is not explicit. [noExplicitConstructor]
dempsterShaferOccupancy(double occupied_probability)
^
```
- Link
None.
None.
None.
=> fix(probabilistic_occupancy_grid_map): fix noExplicitConstructor

sensing/imu_corrector/src/gyro_bias_estimator.cpp
This is a fix based on cppcheck `shadowFunction` warning
```
sensing/imu_corrector/src/gyro_bias_estimator.cpp:54:8: style: Local variable 'timer_callback' shadows outer function [shadowFunction]
auto timer_callback = std::bind(&GyroBiasEstimator::timer_callback, this);
^
sensing/imu_corrector/src/gyro_bias_estimator.hpp:51:8: note: Shadowed declaration
void timer_callback();
^
sensing/imu_corrector/src/gyro_bias_estimator.cpp:54:8: note: Shadow variable
auto timer_callback = std::bind(&GyroBiasEstimator::timer_callback, this);
^
```
- Link
None.
None.
None.
=> fix(imu_corrector): fix shadowFunction

launch/tier4_control_launch/launch/control.launch.xml
The name is not correct which does not let Autoware launch the control evaluator
- [Link](https://github.com/autowarefoundation/autoware.universe/pull/7682)
PSim +  ros2 topic echo /diagnostic/control_evaluator/metrics
None.
None.
None.
=> fix(control_launch): fix control launch control_evaluator plugin name

perception/traffic_light_occlusion_predictor/src/nodelet.cpp, perception/traffic_light_occlusion_predictor/src/occlusion_predictor.cpp
This is a fix based on cppcheck warnings
```
perception/traffic_light_occlusion_predictor/src/nodelet.cpp:132:10: style: The scope of the variable 'not_detected_roi' can be reduced. [variableScope]
size_t not_detected_roi = 0;
^
```
`static_assert` is splited just to avoid cppcheck warnings.
```
perception/traffic_light_occlusion_predictor/src/occlusion_predictor.cpp:214:43: style: Same expression on both sides of '&&' because 'horizontal_sample_num>1' and 'vertical_sample_num>1' represent the same value. [knownConditionTrueFalse]
static_assert(horizontal_sample_num > 1 && vertical_sample_num > 1);
^
perception/traffic_light_occlusion_predictor/src/occlusion_predictor.cpp:212:42: note: 'horizontal_sample_num' is assigned value '20' here.
const uint32_t horizontal_sample_num = 20;
^ …
```
=> fix(traffic_light_occlusion_predictor): fix cppcheck warnings

planning/autoware_planning_validator/src/invalid_trajectory_publisher/invalid_trajectory_publisher.cpp
```
planning/autoware_planning_validator/src/invalid_trajectory_publisher/invalid_trajectory_publisher.cpp:64:7: style: Condition 'EXIT_AFTER_PUBLISH' is always false [knownConditionTrueFalse]
if (EXIT_AFTER_PUBLISH) {
^
planning/autoware_planning_validator/src/invalid_trajectory_publisher/invalid_trajectory_publisher.cpp:63:29: note: Assignment 'EXIT_AFTER_PUBLISH=false', assigned value is 0
bool EXIT_AFTER_PUBLISH = false;
^
planning/autoware_planning_validator/src/invalid_trajectory_publisher/invalid_trajectory_publisher.cpp:64:7: note: Condition 'EXIT_AFTER_PUBLISH' is always false
if (EXIT_AFTER_PUBLISH) {
^
```
- Link
None.
None.
None.
=> fix(autoware_planning_validator): fix knownConditionTrueFalse

launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.xml, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/base_class.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/data_structs.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/path.hpp
Move lane change data structs to lane change namespace to avoid LaneChangeXXXXX naming.
Also added common data which will be use for further refactoring or development.
None
Build success
None.
None.
None.
=> refactor(lane_change): move struct to lane change namespace

perception/image_projection_based_fusion/config/segmentation_pointcloud_fusion.param.yaml, perception/image_projection_based_fusion/docs/segmentation-pointcloud-fusion.md, perception/image_projection_based_fusion/include/image_projection_based_fusion/segmentation_pointcloud_fusion/node.hpp, perception/image_projection_based_fusion/schema/segmentation_pointcloud_fusion.schema.json, perception/image_projection_based_fusion/src/segmentation_pointcloud_fusion/node.cpp
- To change the parameter declaration to avoid unintentional error.
- [TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT1-3590)
None.
None.
None.
=> fix(image_projection_based_fusion): segmentation pointcloud fusion param update

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/README.md, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp
As this module didn't have proper filtering flow for PEDESTRIAN and BICYCLE, sometimes it caused unnecessary avoidance maneuver. Therefor, I added new condition to ignore them if they are in intersection or stop on middle of the road.
https://github.com/autowarefoundation/autoware.universe/assets/44889564/b7512e57-ea56-4f8e-82ee-0fc1cb3d44fb
- [TIER IV INTERNAL LINK](https://docs.google.com/presentation/d/1f9DNCud0YqOaA6c7MObs9_ndUUMJ1LPCjxq2M81R3rs/edit#slide=id.g2e4c3337cea_0_57)
https://github.com/autowarefoundation/autoware.universe/assets/44889564/b2f96bb6-5188-4850-9ab2-d38fde200ddc
None.
None.
None.
=> fix(static_obstacle_avoidance): ignore pedestrian/cyclist who is not on road edge

perception/autoware_map_based_prediction/src/map_based_prediction_node.cpp
Improve queries on fence linestrings in the `map_based_prediction`.
Instead of retrieving ALL fench linestrings to check for intersections, which can be very heavy on huge maps, we now do the following:
1. efficiently retrieve all linestrings in the predicted path bounding box.
2. keep the fences and check for intersections with the predicted path.
[pull request …
=> perf(map_based_prediction): remove query on all fences linestrings

localization/yabloc/yabloc_image_processing/src/undistort/undistort_node.cpp
This is a fix based on cppcheck `shadowFunction` warnings
```
localization/yabloc/yabloc_image_processing/src/undistort/undistort_node.cpp:56:10: style: Local variable 'on_image' shadows outer function [shadowFunction]
auto on_image = std::bind(&UndistortNode::on_image, this, _1);
^
localization/yabloc/yabloc_image_processing/src/undistort/undistort_node.cpp:140:8: note: Shadowed declaration
void on_image(const Image & msg)
^
localization/yabloc/yabloc_image_processing/src/undistort/undistort_node.cpp:56:10: note: Shadow variable
auto on_image = std::bind(&UndistortNode::on_image, this, _1);
^
localization/yabloc/yabloc_image_processing/src/undistort/undistort_node.cpp:57:10: style: Local variable 'on_compressed_image' shadows outer function [shadowFunction]
auto on_compressed_image = …
```
=> fix(yabloc_image_processing): fix shadowFunction

common/fake_test_node/test/test_fake_test_node.cpp, common/osqp_interface/test/test_osqp_interface.cpp, common/qp_interface/test/test_osqp_interface.cpp, common/qp_interface/test/test_proxqp_interface.cpp
This is a fix based on cppcheck warnings.
```
common/fake_test_node/test/test_fake_test_node.cpp:101:0: information: Unmatched suppression: syntaxError [unmatchedSuppression]
::testing::Values(-5, 0, 42));
^
common/osqp_interface/test/test_osqp_interface.cpp:41:0: information: Unmatched suppression: syntaxError [unmatchedSuppression]
TEST(TestOsqpInterface, BasicQp)
^
common/qp_interface/test/test_osqp_interface.cpp:41:0: information: Unmatched suppression: syntaxError [unmatchedSuppression]
TEST(TestOsqpInterface, BasicQp)
^
common/qp_interface/test/test_proxqp_interface.cpp:42:0: information: Unmatched suppression: syntaxError [unmatchedSuppression]
TEST(TestProxqpInterface, BasicQp)
^
```
There is no need to suppress cppcheck errors in `test` directories since they are out of scope of …
=> fix(fake_test_node, osqp_interface, qp_interface): remove unnecessary cppcheck inline suppressions

planning/autoware_mission_planner/README.md, planning/autoware_mission_planner/launch/mission_planner.launch.xml, planning/autoware_mission_planner/src/mission_planner/mission_planner.cpp, planning/autoware_mission_planner/src/mission_planner/mission_planner.hpp
Before this change, we cannot re-plan new route if some modules in behavior_path_planner is running.
In this PR, this enables to re-plan new route if the vehicle is on manual driving mode.
- Subscribe `/system/operation_mode/state`
- If the ego vehicle is not on autonomous driving state, the safety checking process will be skipped.
- Link
Tested in simulator.
[TIER IV INTERNAL LINK](https://evaluation.tier4.jp/evaluation/reports/b811e7ce-af74-55c2-ba0a-8735f0a530cc?project_id=prd_jt)
https://github.com/autowarefoundation/autoware.universe/assets/10190493/75dddc5a-8cd5-4707-a730-e02e17997dea
None.
None.
| Change type   | Topic Type      | Topic Name    | Message Type        | Description       |
|:--------------|:----------------|:--------------|:--------------------|:---- …
=> feat(mission_planner): reroute in manual driving

map/map_loader/include/map_loader/lanelet2_map_loader_node.hpp, map/map_loader/include/map_loader/lanelet2_map_visualization_node.hpp, map/map_loader/src/lanelet2_map_loader/lanelet2_local_projector.hpp, map/map_loader/src/lanelet2_map_loader/lanelet2_map_loader_node.cpp, map/map_loader/src/lanelet2_map_loader/lanelet2_map_visualization_node.cpp, map/map_loader/src/pointcloud_map_loader/differential_map_loader_module.cpp, map/map_loader/src/pointcloud_map_loader/differential_map_loader_module.hpp, map/map_loader/src/pointcloud_map_loader/partial_map_loader_module.cpp, map/map_loader/src/pointcloud_map_loader/partial_map_loader_module.hpp, map/map_loader/src/pointcloud_map_loader/pointcloud_map_loader_module.cpp, map/map_loader/src/pointcloud_map_loader/pointcloud_map_loader_module.hpp, map/map_loader/src/pointcloud_map_loader/pointcloud_map_loader_node.cpp, map/map_loader/src/pointcloud_map_loader/pointcloud_map_loader_node.hpp, map/map_loader/src/pointcloud_map_loader/selected_map_loader_module.cpp, map/map_loader/src/pointcloud_map_loader/selected_map_loader_module.hpp, map/map_loader/src/pointcloud_map_loader/utils.cpp, map/map_loader/src/pointcloud_map_loader/utils.hpp, map/map_loader/test/test_cylinder_box_overlap.cpp, map/map_loader/test/test_load_pcd_metadata.cpp, map/map_loader/test/test_pointcloud_map_loader_module.cpp, map/map_loader/test/test_replace_with_absolute_path.cpp
This PR applies some suggestions from the linter to `map/map_loader`.
Fixed:
- camelCase to snake_case for variable
- align variable name in header's definition and the implementation
- remove unused
- change function/method
- add keyword from function/method which linter suggested
not Fixed:
- Link
Checked with clang-tidy (v14.0.0) and cppcheck (v2.14.1)
If you are using the same kind of script which I used in the past PRs, you need to be careful to set the package name.
You need to change the `${TARGET_DIR}` to `/${TARGET_DIR}/`, otherwise it will check other `..._map_loader_...` packages …
=> refactor(map_loader): apply static analysis

sensing/gnss_poser/include/gnss_poser/gnss_poser_core.hpp, sensing/gnss_poser/src/gnss_poser_core.cpp
This PR applies some suggestions from the linter to `sensing/gnss_poser`.
Fixed:
- camelCase to snake_case for variable
- add `_` to private variable
- change function/method
- add keyword to function/method which linter suggested
- Link
Checked with clang-tidy (v14.0.0) and cppcheck (v2.14.1)
<details>
```
#!/bin/bash
set -eux
TARGET_DIR=$1
exit 1
fi
set +eux …
```
=> refactor(gnss_poser): apply static analysis

map/util/lanelet2_map_preprocessor/src/fix_lane_change_tags.cpp, map/util/lanelet2_map_preprocessor/src/fix_z_value_by_pcd.cpp, map/util/lanelet2_map_preprocessor/src/merge_close_lines.cpp, map/util/lanelet2_map_preprocessor/src/merge_close_points.cpp, map/util/lanelet2_map_preprocessor/src/remove_unreferenced_geometry.cpp, map/util/lanelet2_map_preprocessor/src/transform_maps.cpp
This PR applies some suggestions from the linter to `map/util/lanelet2_map_preprocessor`.
Fixed:
- change function/method
- add or removed keyword from function/method which linter suggested
- removed unused function/method
- avoid using raw loop
not Fixed:
- possibly throwing an exception in main warning [bugprone-exception-escape](https://clang.llvm.org/extra/clang-tidy/checks/bugprone/exception-escape.html)
- Link
Checked with clang-tidy (v14.0.0) and cppcheck (v2.14.1)
Use `.cppcheck_suppressions` for suppressing some notation from cppcheck.
<details> …
=> refactor(lanelet2_map_preprocessor): apply static analysis

sensing/pointcloud_preprocessor/include/pointcloud_preprocessor/distortion_corrector/distortion_corrector.hpp, sensing/pointcloud_preprocessor/src/distortion_corrector/distortion_corrector.cpp
The distortion corrector node didn't save the geometry message correctly which caused the imu to base link transform become identity. 
- Link
Tested with the sample rosbag and the unit test I am working on. 
None.
None.
None.
=> fix(pointcloud_preprocessor): fix the bug where the geometry message was not saved correctly.

perception/multi_object_tracker/src/multi_object_tracker_node.cpp
multi_object_tracker publish timing is controlled not too frequent.
However, the timing the current publish timing did not consider processing time.
[TIER IV INTERNAL](https://tier4.atlassian.net/wiki/spaces/AIP/pages/3197929026/Pilot.Auto+v0.30.0+Test+Report#%EF%BC%9CCARET%E8%A8%88%E6%B8%AC%EF%BC%9E)
Tested by the reporter. 
None.
None.
None.
=> fix(multi_object_tracker): fix publish interval adjust timing

perception/detection_by_tracker/src/debugger/debugger.hpp, perception/detection_by_tracker/src/detection_by_tracker_node.cpp, perception/detection_by_tracker/src/detection_by_tracker_node.hpp, perception/euclidean_cluster/CMakeLists.txt, perception/euclidean_cluster/include/autoware/euclidean_cluster/euclidean_cluster.hpp, perception/euclidean_cluster/include/autoware/euclidean_cluster/euclidean_cluster_interface.hpp, perception/euclidean_cluster/include/autoware/euclidean_cluster/utils.hpp, perception/euclidean_cluster/include/autoware/euclidean_cluster/voxel_grid_based_euclidean_cluster.hpp, perception/euclidean_cluster/launch/euclidean_cluster.launch.py, perception/euclidean_cluster/launch/voxel_grid_based_euclidean_cluster.launch.py, perception/euclidean_cluster/lib/euclidean_cluster.cpp, perception/euclidean_cluster/lib/utils.cpp, perception/euclidean_cluster/lib/voxel_grid_based_euclidean_cluster.cpp, perception/euclidean_cluster/src/euclidean_cluster_node.cpp, perception/euclidean_cluster/src/euclidean_cluster_node.hpp, perception/euclidean_cluster/src/voxel_grid_based_euclidean_cluster_node.cpp, perception/euclidean_cluster/src/voxel_grid_based_euclidean_cluster_node.hpp, perception/image_projection_based_fusion/src/roi_pointcloud_fusion/node.cpp
Tested in a local recompute environment and the [TIER IV Cloud](https://evaluation.tier4.jp/evaluation/reports/955a612c-f809-5855-95c7-6ce0843e2ce1?project_id=prd_jt) environment.
None.
None.
None.
=> refactor(euclidean_cluster)!: fix namespace and directory structure

planning/behavior_velocity_planner/autoware_behavior_velocity_planner/test/src/test_node_interface.cpp
=> chore(autoware_behavior_velocity_planner): remove no_prefix function from tests

perception/euclidean_cluster/package.xml
`StopWatch` and `DebugPublisher` of 'autoware_universe_utils' were sourced indirectly via package 'compare_map_segmentation'. This PR fixes it for direct include.
No logic changes. Build test is enough.
None.
None.
None.
=> fix(euclidean_cluster): include autoware_universe_utils headers

common/autoware_motion_utils/include/autoware/motion_utils/trajectory/trajectory.hpp, common/autoware_motion_utils/src/trajectory/trajectory.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/shift_pull_over.cpp, planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/shift_pull_out.cpp
- Rename function (clarify that it is segment length, not sum)
- Fixed length calculation for overlapping segments in arc length in calcBeforeShiftedArcLength
- Link
- https://tier4.atlassian.net/browse/RT1-7071
psim (check start/goal planner path shape in odaiba)
2024/07/08 https://evaluation.tier4.jp/evaluation/reports/cd627f0a-c391-5855-b028-735852c4d4af/?project_id=prd_jt
None.
None.
None.
=> fix(start/goal_planner): fix addition of duplicate segments in calcBeforeShiftedArcLength

planning/behavior_path_planner/autoware_behavior_path_avoidance_by_lane_change_module/src/scene.cpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/debug.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/scene.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/utils.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/debug.cpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp
This module compensates object even after the system lost them until the time has passed more than threshold.
However, since the longitudinal distance of compensated object was not updated, the avoidance stop point was not calculated expectedly. 0:30~ in following movie, the stop point moved forward even though the target object kept stopping.
https://github.com/autowarefoundation/autoware.universe/assets/44889564/141bd0e8-4d25-4b9a-8497-982e0c1148bf
In this PR, I fixed to update longitudinal for compensated objects in following function.
```c++
void compensateLostTargetObjects(
ObjectDataArray & stored_objects, AvoidancePlanningData & data, const rclcpp::Time & now,
const std::shared_ptr<const PlannerData> & planner_data,
const std::shared_ptr<AvoidanceParameters> & parameters)
{
const …
```
=> fix(static_obstacle_avoidance): stop position is unstable

planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/src/scene.cpp
- [T4](https://tier4.atlassian.net/browse/RT0-32251)
https://evaluation.tier4.jp/evaluation/reports/97397db0-ddae-5840-81d7-7ecad06f45df?project_id=prd_jt
works as before
None.
None.
None.
=> feat(blind_spot): consider road_shoulder if exist

evaluator/autoware_control_evaluator/include/autoware/control_evaluator/control_evaluator_node.hpp, evaluator/autoware_control_evaluator/src/control_evaluator_node.cpp, evaluator/autoware_evaluator_utils/CMakeLists.txt, evaluator/autoware_evaluator_utils/README.md, evaluator/autoware_evaluator_utils/include/autoware/evaluator_utils/evaluator_utils.hpp, evaluator/autoware_evaluator_utils/package.xml, evaluator/autoware_evaluator_utils/src/evaluator_utils.cpp, evaluator/autoware_planning_evaluator/include/autoware/planning_evaluator/planning_evaluator_node.hpp, evaluator/autoware_planning_evaluator/launch/planning_evaluator.launch.xml, evaluator/autoware_planning_evaluator/package.xml, evaluator/autoware_planning_evaluator/src/planning_evaluator_node.cpp
This PR adds subscription from the planning evaluator side to the /diagnostics topic to monitor the obstacle_cruise outputs. It also adds a common evaluator utils library to reduce code repetition.
- Link
psim
https://evaluation.ci.tier4.jp/evaluation/reports/6d538dbe-2fd0-5fb4-82c7-8fa02b16e5e0?project_id=prd_jt
None.
None.
None.
=> feat(planning_evaluator,control_evaluator, evaluator utils): add diagnostics subscriber to planning eval

sensing/image_diagnostics/CMakeLists.txt, sensing/image_diagnostics/src/image_diagnostics_node.cpp, sensing/image_diagnostics/src/image_diagnostics_node.hpp
```
ros2 launch image_transport_decompressor image_transport_decompressor.launch.xml \
input_topic_name:=/sensing/camera/camera0/image_rect_color/compressed \
output_topic_name:=/sensing/camera/camera0/image_rect_color
ros2 launch image_diagnostics image_diagnostics_node.launch.xml input_topic_name:=/sensing/camera/camera0/image_rect_color
```
None.
None.
None.
=> refactor(image_diagnostics): fix namespace and directory structure

control/autoware_mpc_lateral_controller/include/autoware/mpc_lateral_controller/mpc.hpp, control/autoware_mpc_lateral_controller/src/mpc.cpp, control/autoware_pid_longitudinal_controller/include/autoware/pid_longitudinal_controller/pid_longitudinal_controller.hpp, control/autoware_pid_longitudinal_controller/src/pid_longitudinal_controller.cpp, control/autoware_trajectory_follower_node/test/test_controller_node.cpp
Once the dry steering (steering while the ego stops) was supported in the controller for the geometric path by the start/goal planner.
However, this dry steering feature does not work well currently due to the recent change.
This PR revived the the dry steering feature.
**Without this PR**
case1 (geometric path planning)
https://github.com/autowarefoundation/autoware.universe/assets/20228327/07fc0dcb-21ba-45d5-9f8e-a4a10519488a
**With this PR**
case1 (geometric path planning)
https://github.com/autowarefoundation/autoware.universe/assets/20228327/5220ed78-d093-4c24-aae8-0ef3c9bbc9e3
case2 (freespace path planning)
https://github.com/autowarefoundation/autoware.universe/assets/20228327/23891825-e5d4-46ca-bf6b-b50f6f37b58c
- [CompanyName internal …
=> fix(controller): revival of dry steering

planning/behavior_velocity_planner/autoware_behavior_velocity_no_drivable_lane_module/src/scene.cpp
Fix errors found by using clang
```cpp
// size_t target_point_idx; <= uninitilized
size_t target_point_idx = 0;
if (op_target_point_idx) {
target_point_idx = op_target_point_idx.value();
}
geometry_msgs::msg::Point stop_point =
autoware::universe_utils::getPoint(path->points.at(target_point_idx).point);
```
- Link
None.
None.
None.
=> fix(autoware_behavior_velocity_no_drivable_lane_module): fix bug of uninitialization

sensing/pointcloud_preprocessor/src/filter.cpp
Some of our code is still using data with the old pointcloud type. In this PR I add temporary retro-compatibility by disabling the related memory checks
- [TIER IV INTERNAL LINK](https://star4.slack.com/archives/C03S84LDJGG/p1720571462988769)
None.
None.
None.
=> fix: added temporary retrocompatibility to old perception data

sensing/radar_threshold_filter/CMakeLists.txt, sensing/radar_threshold_filter/src/radar_threshold_filter_node.cpp, sensing/radar_threshold_filter/src/radar_threshold_filter_node.hpp, sensing/radar_threshold_filter/test/radar_threshold_filter/test_radar_threshold_filter.cpp
Tested in a local recompute environment and the [TIER IV Cloud ](https://evaluation.tier4.jp/evaluation/reports/4c0e46a3-ab5b-5d2d-b35b-d16ca7fd4f38?project_id=prd_jt)environment.
None.
None.
None.
=> refactor(radar_threshold_filter): fix namespace and directory structure

sensing/radar_scan_to_pointcloud2/CMakeLists.txt, sensing/radar_scan_to_pointcloud2/package.xml, sensing/radar_scan_to_pointcloud2/src/radar_scan_to_pointcloud2_node.cpp, sensing/radar_scan_to_pointcloud2/src/radar_scan_to_pointcloud2_node.hpp
Tested in a local recompute environment and the [TIER IV Cloud ](https://evaluation.tier4.jp/evaluation/reports/4c0e46a3-ab5b-5d2d-b35b-d16ca7fd4f38?project_id=prd_jt)environment.
None.
None.
None.
=> refactor(radar_scan_to_pointcloud2): fix namespace and directory structure

sensing/radar_tracks_noise_filter/CMakeLists.txt, sensing/radar_tracks_noise_filter/src/radar_tracks_noise_filter_node.cpp, sensing/radar_tracks_noise_filter/src/radar_tracks_noise_filter_node.hpp, sensing/radar_tracks_noise_filter/test/radar_tracks_noise_filter/test_radar_tracks_noise_filter_is_noise.cpp
Tested in a local recompute environment and the [TIER IV Cloud ](https://evaluation.tier4.jp/evaluation/reports/4c0e46a3-ab5b-5d2d-b35b-d16ca7fd4f38?project_id=prd_jt)environment.
None.
None.
None.
=> refactor(radar_tracks_noise_filter)!: fix namespace and directory structure

sensing/radar_static_pointcloud_filter/CMakeLists.txt, sensing/radar_static_pointcloud_filter/package.xml, sensing/radar_static_pointcloud_filter/src/radar_static_pointcloud_filter_node.cpp, sensing/radar_static_pointcloud_filter/src/radar_static_pointcloud_filter_node.hpp
Tested in a local recompute environment and the [TIER IV Cloud ](https://evaluation.tier4.jp/evaluation/reports/4c0e46a3-ab5b-5d2d-b35b-d16ca7fd4f38?project_id=prd_jt)environment.
None.
None.
None.
=> refactor(radar_static_pointcloud_filter): fix namespace and directory structure

perception/object_merger/src/association/solver/successive_shortest_path.cpp
```
perception/object_merger/src/association/solver/successive_shortest_path.cpp:331:14: style: Local variable 'v' shadows outer variable [shadowVariable]
for (int v = 0; v < n_nodes; ++v) {
^
```
- Link
None.
None.
None.
=> fix(object_merger): fix shadowVariable

perception/multi_object_tracker/src/multi_object_tracker_node.cpp
```
perception/multi_object_tracker/src/multi_object_tracker_core.cpp:353:20: style: Local variable 'tentative_objects_msg' shadows outer variable [shadowVariable]
TrackedObjects tentative_objects_msg;
^
```
- Link
None.
None.
None.
=> fix(multi_object_tracker): fix shadowVariable

planning/behavior_path_planner/autoware_behavior_path_avoidance_by_lane_change_module/src/manager.cpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/config/static_obstacle_avoidance.param.yaml, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/data_structs.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/helper.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/parameter_helper.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/schema/static_obstacle_avoidance.schema.json, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/manager.cpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp
Add new option to select behavior policy for the vehicle this module can't judge if it's a parked vehicle or not.
If user set `auto` policy, this module avoids such a ambiguous vehicle automatically.
https://github.com/autowarefoundation/autoware.universe/assets/44889564/6b2ea27c-70eb-4840-a6f3-9da21ff483f9
If user set `manual` policy, this module generates avoidance candidate path and keeps waiting execution until operator approves it.
https://github.com/autowarefoundation/autoware.universe/assets/44889564/f9906ce3-1adf-4fe7-822e-71c7ecdd4387
If user set `ignore` policy, this module never avoids such a ambiguous vehicle.
https://github.com/autowarefoundation/autoware.universe/assets/44889564/fd399fa2-f35f-49e0-9e07-fdd65e39f50e
- Link
None.
None.
None.
=> fix(static_obstacle_avoidance): don't automatically avoid ambiguous vehicle

perception/lidar_apollo_segmentation_tvm/src/lidar_apollo_segmentation_tvm.cpp
```
perception/lidar_apollo_segmentation_tvm/src/lidar_apollo_segmentation_tvm.cpp:170:33: style: Local variable 'transformed_cloud' shadows outer variable [shadowVariable]
sensor_msgs::msg::PointCloud2 transformed_cloud;
^
```
Using range-based for loop.
- Link
None.
None.
None.
=> fix(lidar_apollo_segmentation_tvm): fix shadowVariable

perception/autoware_radar_object_tracker/src/association/ssp/successive_shortest_path.cpp
```
perception/autoware_radar_object_tracker/src/association/ssp/successive_shortest_path.cpp:331:14: style: Local variable 'v' shadows outer variable [shadowVariable]
for (int v = 0; v < n_nodes; ++v) {
^
```
- Link
None.
None.
None.
=> fix(autoware_radar_object_tracker): fix shadowVariable

perception/tensorrt_yolox/src/tensorrt_yolox.cpp
```
perception/tensorrt_yolox/src/tensorrt_yolox.cpp:133:16: style: Local variable 'npos' shadows outer variable [shadowVariable]
size_t npos = colormapString.find_first_of(',');
^
```
- Link
None.
None.
None.
=> fix(tensorrt_yolox): fix shadowVariable

perception/tracking_object_merger/src/association/solver/successive_shortest_path.cpp
```
perception/tracking_object_merger/src/association/solver/successive_shortest_path.cpp:331:14: style: Local variable 'v' shadows outer variable [shadowVariable]
for (int v = 0; v < n_nodes; ++v) {
^
```
- Link
None.
None.
None.
=> fix(tracking_object_merger): fix shadowVariable

perception/lidar_transfusion/CMakeLists.txt
Fixes the CI issue:
```shell
error while loading shared libraries: libtransfusion_cuda_lib.so: cannot open shared object file: No such file or directory
```
- Link
None.
None.
None.
=> fix(lidar_transfusion): install lib

vehicle/autoware_external_cmd_converter/src/node.cpp
This pull request addresses an issue where the availability of local/remote mode becomes false after the first activation. This is achieved by making necessary adjustments to fix the check_topic_state function.
Subscribed topics in autoware_external_converter are used only when GateMode is set to EXTERNAL. Therefore, I propose that check_topic_state should return true when GateMode is set to AUTO. This change will prevent the availability of local/remote mode from becoming false due to a mischeck.
[Screencast from 2024年07月08日 17時38分38秒.webm](https://github.com/tier4/autoware.universe/assets/165623782/449de164-82e0-4ab3-8ca8-dc33342909ba)
The PR …
=> fix(autoware_external_cmd_converter): fix check_topic_state

planning/autoware_obstacle_cruise_planner/include/autoware/obstacle_cruise_planner/node.hpp, planning/autoware_obstacle_cruise_planner/src/node.cpp
This PR enables chattering prevention by retaining past obstacle information for a certain amount of time.
Psim
[cp.webm](https://github.com/autowarefoundation/autoware.universe/assets/50359861/08b03105-3179-4235-ada2-aeb5819a366b)
Evaluation:
- w/ point cloud handling disabled: https://evaluation.tier4.jp/evaluation/reports/c87c22b7-48c2-5d48-b552-db5a2323a75e?project_id=prd_jt
- w/ both ML-based objects and point cloud handling enabled: https://evaluation.tier4.jp/evaluation/reports/186f3773-68c0-5efe-99c8-054c5006c001?project_id=prd_jt
None.
None.
None.
=> feat(obstacle_cruise_planner): prevent chattering when using point cloud

planning/motion_velocity_planner/autoware_motion_velocity_dynamic_obstacle_stop_module/src/footprint.cpp
Follow recommendation from https://github.com/autowarefoundation/autoware.universe/pull/7730#discussion_r1658153092
- Link
Psim
None.
None.
None.
=> perf(dynamic_obstacle_stop): construct rtree nodes in place

planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/utils.cpp
```
planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/utils.cpp:1271:21: style: Local variable 'p' shadows outer variable [shadowVariable]
for (const auto & p : path.points) {
^
```
- Link
None.
None.
None.
=> fix(autoware_behavior_path_planner_common): fix shadowVariable

perception/probabilistic_occupancy_grid_map/lib/costmap_2d/occupancy_grid_map_fixed.cpp, perception/probabilistic_occupancy_grid_map/lib/costmap_2d/occupancy_grid_map_projective.cpp
```
probabilistic_occupancy_grid_map/lib/costmap_2d/occupancy_grid_map_fixed.cpp:218:22: style: Local variable 'source' shadows outer variable [shadowVariable]
const auto & source = obstacle_pointcloud_angle_bin.at(dist_index);
^
probabilistic_occupancy_grid_map/lib/costmap_2d/occupancy_grid_map_projective.cpp:278:22: style: Local variable 'source' shadows outer variable [shadowVariable]
const auto & source = obstacle_pointcloud_angle_bin.at(dist_index);
^
```
Using range-based for loop.
- Link
None.
None.
None.
=> fix(probabilistic_occupancy_grid_map): fix shadowVariable

evaluator/autoware_planning_evaluator/include/autoware/planning_evaluator/planning_evaluator_node.hpp, evaluator/autoware_planning_evaluator/src/planning_evaluator_node.cpp, planning/autoware_obstacle_cruise_planner/include/autoware/obstacle_cruise_planner/common_structs.hpp, planning/autoware_obstacle_cruise_planner/include/autoware/obstacle_cruise_planner/planner_interface.hpp, planning/autoware_obstacle_cruise_planner/src/node.cpp, planning/autoware_obstacle_cruise_planner/src/optimization_based_planner/optimization_based_planner.cpp, planning/autoware_obstacle_cruise_planner/src/pid_based_planner/pid_based_planner.cpp, planning/autoware_obstacle_cruise_planner/src/planner_interface.cpp
This PR adds cruise and slow down diag info to the cruise planner. The planning_evaluator interprets all 3 messages and outputs the corresponding result. 
https://github.com/autowarefoundation/autoware.universe/assets/25967964/de651924-3237-48ec-a1c3-92ae90620725
- Link
PSim
None.
None.
None.
=> feat(cruise_planner,planning_evaluator): add cruise and slow down diags

.cppcheck_suppressions
Remove cstyleCast
See cppcheck-daily
- https://github.com/autowarefoundation/autoware.universe/actions/runs/9802237058
None.
None.
None.
=> chore(cppcheck): delete cstyleCast from .cppcheck_suppressions

planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/src/trajectory_preprocessing.cpp
```
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/src/trajectory_preprocessing.cpp:74:18: style: Local variable 'prev_point' shadows outer variable [shadowVariable]
const auto & prev_point = trajectory[i - 1];
^
```
- Link
None.
None.
None.
=> fix(autoware_motion_velocity_obstacle_velocity_limiter_module): fix shadowVariable

system/system_monitor/src/hdd_monitor/hdd_monitor.cpp
```
system/system_monitor/src/hdd_monitor/hdd_monitor.cpp:687:35: style: Local variable 'oa' shadows outer variable [shadowVariable]
boost::archive::text_iarchive oa(iss);
^
```
- Link
None.
None.
None.
=> fix(system_monitor): fix shadowVariable

system/system_error_monitor/src/system_error_monitor_core.cpp
```
system/system_error_monitor/src/system_error_monitor_core.cpp:291:18: style: Local variable 'param_key' shadows outer variable [shadowVariable]
const auto & param_key = split_names.at(1);
```
- Link
None.
None.
None.
=> fix(system_error_monitor): fix shadowVariable

localization/autoware_stop_filter/src/stop_filter.hpp
```
localization/autoware_stop_filter/src/stop_filter.cpp:29:52: style: inconclusive: Function 'StopFilter' argument 1 names different: declaration 'options' definition 'node_options'. [funcArgNamesDifferent]
StopFilter::StopFilter(const rclcpp::NodeOptions & node_options)
^
```
- Link
None.
None.
None.
=> fix(autoware_stop_filter): fix funcArgNamesDifferent

perception/detection_by_tracker/src/detection_by_tracker_node.hpp
```
perception/detection_by_tracker/src/detection_by_tracker_node.cpp:204:66: style: inconclusive: Function 'divideUnderSegmentedObjects' argument 2 names different: declaration 'in_objects' definition 'in_cluster_objects'. [funcArgNamesDifferent]
const tier4_perception_msgs::msg::DetectedObjectsWithFeature & in_cluster_objects,
^
perception/detection_by_tracker/src/detection_by_tracker_node.cpp:343:66: style: inconclusive: Function 'mergeOverSegmentedObjects' argument 2 names different: declaration 'in_objects' definition 'in_cluster_objects'. [funcArgNamesDifferent]
const tier4_perception_msgs::msg::DetectedObjectsWithFeature & in_cluster_objects,
^
```
- Link
None.
None.
None.
=> fix(detection_by_tracker): fix funcArgNamesDifferent

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/interface.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/base_class.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/interface.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp, planning/behavior_path_planner/autoware_behavior_path_planner/include/autoware/behavior_path_planner/planner_manager.hpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/interface/scene_module_interface.hpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/interface/scene_module_manager_interface.hpp
Add time_keeper to scene module manager interface and apply this to lane_change module.
```
lane_change_right=>run: 0.41 [ms]
├── updateData: 0.03 [ms]
├── plan: 0.29 [ms]
│   ├── generateOutput: 0.21 [ms]
│   │   ├── extendPath: 0.01 [ms]
│   │   ├── getReferencePath: 0.09 [ms]
│   │   ├── updateOutputTurnSignal: 0.08 [ms]
│   │   ├── insertStopPoint: 0.00 [ms]
│   │   └── extendOutputDrivableArea: 0.01 [ms]
│   ├── updateSteeringFactorPtr: 0.04 [ms]
│   └── updateRTCStatus: 0.00 [ms]
├── isVehicleStuck: 0.00 [ms]
│   └── isVehicleStuck: 0.00 [ms]
└── isLaneChangePathSafe: 0.00 [ms]
```
- Link
None.
None.
None.
=> feat(autoware_behavior_path_planner_common,autoware_behavior_path_lane_change_module): add time_keeper to bpp

common/qp_interface/include/qp_interface/osqp_csc_matrix_conv.hpp, common/qp_interface/include/qp_interface/osqp_interface.hpp, common/qp_interface/include/qp_interface/proxqp_interface.hpp, common/qp_interface/include/qp_interface/qp_interface.hpp, common/qp_interface/src/osqp_csc_matrix_conv.cpp, common/qp_interface/src/osqp_interface.cpp, common/qp_interface/src/proxqp_interface.cpp, common/qp_interface/src/qp_interface.cpp, common/qp_interface/test/test_csc_matrix_conv.cpp, common/qp_interface/test/test_osqp_interface.cpp, common/qp_interface/test/test_proxqp_interface.cpp
This package is not used by any package in Autoware currently.
- Changed namespace
- `qp` -> `autoware::common`
- Changed the member variable expression
- `m_XXX` -> `XXX_` (just my preference according to most of the planning and control packages)
- Added `isSolved` function
- Currently, there is no way for the node side to know whether the optimization was successful.
- Minor change to constructors, member functions
unit test
OSQPInterface in the `qp_interface` package is not well organized since it's almost just copied from the `osqp_interface` package.
None.
None.
=> refactor(qp_interface): clean up the code

planning/behavior_path_planner/autoware_behavior_path_planner/config/behavior_path_planner.param.yaml, planning/behavior_path_planner/autoware_behavior_path_planner/include/autoware/behavior_path_planner/planner_manager.hpp, planning/behavior_path_planner/autoware_behavior_path_planner/src/behavior_path_planner_node.cpp, planning/behavior_path_planner/autoware_behavior_path_planner/src/planner_manager.cpp
This [PR](https://github.com/autowarefoundation/autoware_launch/pull/1064) should be merged first.
When scene modules A > B > C are in the approved state and A fails, all modules (A, B, C) are removed from `approved_modules`. Additionally, `candidate_modules` becomes empty, causing all modules A-Z to be re-evaluated through `getRequestModules` -> `runRequestModules`. This leads to A > B > C being approved again, and if A fails once more, an infinite loop may occur.
Prevent modules that have been removed from `approved_modules` due to success or failure from being added again by `getRequestModules`.
1. In `runApprovedModules`, add modules that have transitioned to success or failure state to `deleted_modules`.
2. In `getRequestModules`, skip the execution request judgment for modules that …
=> feat(autoware_behavior_path_planner): prevent infinite loop in approving scene module process

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/debug.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/debug.cpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp
Show marker for operator when system requests cooperation. This marker is published only when the user set policy of ego behavior for ambiguous situation to `manual`.
```yaml
avoidance_for_ambiguous_vehicle:
policy: "manual"                                # [-]
```
Topic: `/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/info/static_obstacle_avoidance`
Additionally, I updated marker color for ignored objects to Gray from Green.
Topic: `/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/debug/static_obstacle_avoidance`
- https://github.com/autowarefoundation/autoware.universe/pull/7851
None.
None.
None.
=> feat(static_obstacle_avoidance): show markers when system requests operator support

perception/object_merger/src/object_association_merger_node.hpp
```
perception/object_merger/src/object_association_merger_node.cpp:133:74: style: inconclusive: Function 'objectsCallback' argument 1 names different: declaration 'input_object0_msg' definition 'input_objects0_msg'. [funcArgNamesDifferent]
const autoware_perception_msgs::msg::DetectedObjects::ConstSharedPtr & input_objects0_msg,
^
perception/object_merger/src/object_association_merger_node.cpp:134:74: style: inconclusive: Function 'objectsCallback' argument 2 names different: declaration 'input_object1_msg' definition 'input_objects1_msg'. [funcArgNamesDifferent]
const autoware_perception_msgs::msg::DetectedObjects::ConstSharedPtr & input_objects1_msg)
^
```
- Link
None.
None.
None.
=> fix(object_merger): fix funcArgNamesDifferent

perception/autoware_radar_object_tracker/src/radar_object_tracker_node.hpp
```
perception/autoware_radar_object_tracker/src/radar_object_tracker_node.cpp:132:72: style: inconclusive: Function 'onMap' argument 1 names different: declaration 'map_msg' definition 'msg'. [funcArgNamesDifferent]
void RadarObjectTrackerNode::onMap(const LaneletMapBin::ConstSharedPtr msg)
^
```
- Link
None.
None.
None.
=> fix(autoware_radar_object_tracker): fix funcArgNamesDifferent

perception/tracking_object_merger/src/decorative_tracker_merger_node.hpp
```
perception/tracking_object_merger/src/decorative_tracker_merger_node.cpp:196:42: style: inconclusive: Function 'mainObjectsCallback' argument 1 names different: declaration 'input_object_msg' definition 'main_objects'. [funcArgNamesDifferent]
const TrackedObjects::ConstSharedPtr & main_objects)
^
perception/tracking_object_merger/src/decorative_tracker_merger_node.cpp:245:93: style: inconclusive: Function 'subObjectsCallback' argument 1 names different: declaration 'input_object_msg' definition 'msg'. [funcArgNamesDifferent]
void DecorativeTrackerMergerNode::subObjectsCallback(const TrackedObjects::ConstSharedPtr & msg)
^
perception/tracking_object_merger/src/decorative_tracker_merger_node.cpp:269:27: style: inconclusive: …
```
=> fix(tracking_object_merger): fix funcArgNamesDifferent

planning/autoware_mission_planner/src/lanelet2_plugins/default_planner.hpp
```
planning/autoware_mission_planner/src/lanelet2_plugins/default_planner.cpp:219:42: style: inconclusive: Function 'visualize_debug_footprint' argument 1 names different: declaration 'goal_footprint_' definition 'goal_footprint'. [funcArgNamesDifferent]
autoware::universe_utils::LinearRing2d goal_footprint) const
^
```
- Link
None.
None.
None.
=> fix(autoware_mission_planner): fix funcArgNamesDifferent

planning/motion_velocity_planner/autoware_motion_velocity_dynamic_obstacle_stop_module/src/collision.hpp
```
planning/motion_velocity_planner/autoware_motion_velocity_dynamic_obstacle_stop_module/src/collision.cpp:66:52: style: inconclusive: Function 'find_collisions' argument 3 names different: declaration 'obstacle_forward_footprints' definition 'object_forward_footprints'. [funcArgNamesDifferent]
const autoware::universe_utils::MultiPolygon2d & object_forward_footprints)
^
```
- Link
None.
None.
None.
=> fix(autoware_motion_velocity_dynamic_obstacle_stop_module): fix funcArgNamesDifferent

control/predicted_path_checker/include/predicted_path_checker/utils.hpp, control/predicted_path_checker/src/predicted_path_checker_node/utils.cpp
```
control/predicted_path_checker/src/predicted_path_checker_node/utils.cpp:151:47: style: Parameter 'vehicle_info' can be declared as reference to const [constParameterReference]
autoware::vehicle_info_utils::VehicleInfo & vehicle_info)
^
```
- Link
None.
None.
None.
=> fix(predicted_path_checker): fix constParameterReference 

planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/parking_departure/utils.hpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/parking_departure/utils.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_shifter/path_shifter.cpp
```
planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/parking_departure/utils.cpp:89:45: style: Parameter 'ego_predicted_path_params' can be declared as reference to const [constParameterReference]
std::shared_ptr<EgoPredictedPathParams> & ego_predicted_path_params,
^
planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_shifter/path_shifter.cpp:504:17: style: Parameter 'a' can be declared as reference to const [constParameterReference]
[](auto & a, auto & b) { return a.end_idx > b.end_idx; });
^
planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_shifter/path_shifter.cpp:504:27: style: Parameter 'b' can be declared as reference to …
```
=> fix(autoware_behavior_path_planner_common): fix constParameterReference

planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/src/occupancy_grid_utils.hpp
```
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/src/occupancy_grid_utils.cpp:27:71: style: inconclusive: Function 'maskPolygons' argument 2 names different: declaration 'masks' definition 'obstacle_masks'. [funcArgNamesDifferent]
void maskPolygons(grid_map::GridMap & grid_map, const ObstacleMasks & obstacle_masks)
^
```
- Link
None.
None.
None.
=> fix(autoware_motion_velocity_obstacle_velocity_limiter_module): fix funcArgNamesDifferent

simulator/learning_based_vehicle_model/src/model_connections_helpers.cpp
```
simulator/learning_based_vehicle_model/src/model_connections_helpers.cpp:35:21: style: Variable 'name_2' can be declared as pointer to const [constVariableReference]
for (const auto & name_2 : connection_names_2) {
^
```
- Link
None.
None.
None.
=> fix(learning_based_vehicle_model): fix constVariableReference

system/mrm_handler/src/mrm_handler/mrm_handler_core.cpp
Currently, if use_emergency_holding is set to true, the ego will enter emergency mode if it is not changed to autonomous mode within "timeout_emergency_recovery" seconds, which is not the expected behavior. 
This PR adds a check for Autonomous mode before increasing the timer, which solves the issue. 
- Link
PSim
https://github.com/user-attachments/assets/f5441097-dd87-41ba-81b6-93d6faa81668
None.
None.
None.
=> fix(mrm_handler): add check for autonomous mode and do some refactoring

perception/detected_object_validation/src/obstacle_pointcloud/obstacle_pointcloud_validator.cpp, perception/detected_object_validation/src/obstacle_pointcloud/obstacle_pointcloud_validator.hpp
```
perception/detected_object_validation/src/obstacle_pointcloud/obstacle_pointcloud_validator.cpp:41:48: style: Parameter 'points_num_threshold_param' can be declared as reference to const [constParameterReference]
Validator::Validator(PointsNumThresholdParam & points_num_threshold_param)
^
```
- Link
None.
None.
None.
=> fix(detected_object_validation): fix constParameterReference

planning/behavior_path_planner/autoware_behavior_path_dynamic_obstacle_avoidance_module/include/autoware/behavior_path_dynamic_obstacle_avoidance_module/manager.hpp, planning/behavior_path_planner/autoware_behavior_path_dynamic_obstacle_avoidance_module/include/autoware/behavior_path_dynamic_obstacle_avoidance_module/scene.hpp, planning/behavior_path_planner/autoware_behavior_path_dynamic_obstacle_avoidance_module/src/scene.cpp
- Added a time_keeper
- Improved the computational performance of the dynamic obstacle avoidance
- give `std::vector<geometry_msgs::msg::Pose>` instead of `std::vector<PathPointWithLaneId>`
- NOTE: The implementation became a bit complicated. It should be refactored soon by @yhisaki 's trajectory class.
- modify the function to calculate the distance between the ego's path and the pedestrian by using its shape CYLINDER.
- decrease the number to call findNearest functions.
https://evaluation.tier4.jp/evaluation/reports/170ee563-4550-5ee4-ad5a-c8bfd8ccd44d?project_id=prd_jt
The processing time was measured in the following condition.
**before**
16.3 ms at maximum
```
updateData: 16.292 [ms]
├── registerRegulatedObjects: 0.44 [ms]
├── registerUnregulatedObjects: …
```
=> perf(dynamic_obstacle_avoidance): decrease the computation time with time_keeper

system/mrm_handler/include/mrm_handler/mrm_handler_core.hpp, system/mrm_handler/launch/mrm_handler.launch.xml, system/mrm_handler/src/mrm_handler/mrm_handler_core.cpp
Subscribe gear command in mrm_handler so that in emergency the mrm_handler knows the proper gear.
- [TIER IV INTERNAL](https://star4.slack.com/archives/C4P0NSMB5/p1721192193289009)
- [TIER IV INTERNAL](https://star4.slack.com/archives/C03QW0GU6P7/p1720530226145199)
Psim
None.
None.
None.
=> feat(mrm_handler): input gear command

control/autoware_pure_pursuit/src/autoware_pure_pursuit_core/interpolate.cpp
```
control/autoware_pure_pursuit/src/autoware_pure_pursuit_core/interpolate.cpp:232:12: style: Local variable 'i' shadows outer variable [shadowVariable]
for (int i = 0; i < static_cast<int>(normalized_idx.size()); ++i) {
^
```
- Link
None.
None.
None.
=> fix(autoware_pure_pursuit): fix shadowVariable

perception/autoware_map_based_prediction/src/map_based_prediction_node.cpp
```
perception/autoware_map_based_prediction/src/map_based_prediction_node.cpp:1039:21: style: Local variable 'object_id' shadows outer variable [shadowVariable]
std::string object_id = autoware::universe_utils::toHexString(object.object_id);
^
```
This variable was removed because it was not used.
- Link
None.
None.
None.
=> fix(autoware_map_based_prediction): fix shadowVariable

planning/autoware_velocity_smoother/src/smoother/analytical_jerk_constrained_smoother/analytical_jerk_constrained_smoother.cpp
```
planning/autoware_velocity_smoother/src/smoother/analytical_jerk_constrained_smoother/analytical_jerk_constrained_smoother.cpp:376:20: style: Local variable 'start_index' shadows outer variable [shadowVariable]
const size_t start_index = std::get<0>(lat_acc_filtered_range);
^
planning/autoware_velocity_smoother/src/smoother/analytical_jerk_constrained_smoother/analytical_jerk_constrained_smoother.cpp:377:20: style: Local variable 'end_index' shadows outer variable [shadowVariable]
const size_t end_index = std::get<1>(lat_acc_filtered_range);
^
planning/autoware_velocity_smoother/src/smoother/analytical_jerk_constrained_smoother/analytical_jerk_constrained_smoother.cpp:378:20: style: Local variable 'min_latacc_velocity' shadows …
```
=> fix(autoware_velocity_smoother): fix shadowVariablefix:shadowVariable

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/freespace_pull_over.cpp
```
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/freespace_pull_over.cpp:125:15: style: Local variable 'path' shadows outer variable [shadowVariable]
for (auto & path : partial_paths) {
^
```
- Link
None.
None.
None.
=> fix(autoware_behavior_path_goal_planner_module): fix shadowVariable

common/tensorrt_common/include/tensorrt_common/simple_profiler.hpp, common/tensorrt_common/src/simple_profiler.cpp
```
common/tensorrt_common/src/simple_profiler.cpp:81:64: style: Parameter 'value' can be declared as reference to const [constParameterReference]
std::ostream & operator<<(std::ostream & out, SimpleProfiler & value)
^
```
- Link
None.
None.
None.
=> fix(tensorrt_common): fix constParameterReference

perception/detected_object_validation/src/obstacle_pointcloud/obstacle_pointcloud_validator.hpp
```
perception/detected_object_validation/src/obstacle_pointcloud/obstacle_pointcloud_validator.cpp:98:44: style: inconclusive: Function 'getPointCloudWithinObject' argument 2 names different: declaration 'neighbor_pointcloud' definition 'pointcloud'. [funcArgNamesDifferent]
const pcl::PointCloud<pcl::PointXY>::Ptr pointcloud)
^
```
- Link
None.
None.
None.
=> fix(detected_object_validation): fix funcArgNamesDifferent

perception/compare_map_segmentation/src/voxel_grid_map_loader/voxel_grid_map_loader.hpp
```
perception/compare_map_segmentation/src/voxel_grid_map_loader/voxel_grid_map_loader.cpp:329:97: style: inconclusive: Function 'onEstimatedPoseCallback' argument 1 names different: declaration 'pose' definition 'msg'. [funcArgNamesDifferent]
void VoxelGridDynamicMapLoader::onEstimatedPoseCallback(nav_msgs::msg::Odometry::ConstSharedPtr msg)
^
```
- Link
None.
None.
None.
=> fix(compare_map_segmentation): fix funcArgNamesDifferent

localization/localization_util/CMakeLists.txt, localization/localization_util/include/localization_util/diagnostics_module.hpp, localization/localization_util/src/diagnostics_module.cpp, localization/ndt_scan_matcher/CMakeLists.txt, localization/ndt_scan_matcher/include/ndt_scan_matcher/map_update_module.hpp, localization/ndt_scan_matcher/include/ndt_scan_matcher/ndt_scan_matcher_core.hpp
Moved diagnostics_module from ndt_scan_matcher to localization_util.
- Link
- Check that localization works correctly in logging_simulator.
- Check that the diagnostics topic in ndt_scan_matcher is published.
None.
None.
None.
=> refactor(localization_util): move diagnostics_module

control/autoware_control_validator/README.md, control/autoware_control_validator/config/control_validator.param.yaml, control/autoware_control_validator/include/autoware/control_validator/control_validator.hpp, control/autoware_control_validator/msg/ControlValidatorStatus.msg, control/autoware_control_validator/src/control_validator.cpp
This PR  add velocity check function to validate vehicle velocity controllers.
If the current velocity has over velocity or reversed velocity against the target velocity for the velocity controller, control_validator will publish diagnostic msg.
https://github.com/autowarefoundation/autoware_launch/pull/1050
- Link
psim and teir4 internal tests
None.
=> feat(control_validator)!: add velocity check

planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/README.md, planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/include/autoware/behavior_velocity_crosswalk_module/util.hpp, planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp, planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/util.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_walkway_module/src/scene_walkway.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_walkway_module/src/scene_walkway.hpp
clean up the structure and create a brief flowchart
scenario test:
https://evaluation.tier4.jp/evaluation/reports/43f87901-7267-566d-9f08-fb27c1191175?project_id=prd_jt
None.
None.
None.
=> refactor(crosswalk): clean up the structure and create a brief flowchart

common/autoware_universe_utils/CMakeLists.txt, common/autoware_universe_utils/include/autoware/universe_utils/geometry/geometry.hpp, common/autoware_universe_utils/include/autoware/universe_utils/geometry/gjk_2d.hpp, common/autoware_universe_utils/include/autoware/universe_utils/geometry/random_convex_polygon.hpp, common/autoware_universe_utils/src/geometry/geometry.cpp, common/autoware_universe_utils/src/geometry/gjk_2d.cpp, common/autoware_universe_utils/src/geometry/random_convex_polygon.cpp, common/autoware_universe_utils/test/src/geometry/test_geometry.cpp
Implement the GJK algorithm allowing ~4x speed compared to `boost::geometry::intersects` to determine if 2 polygons intersects.
:warning: the polygons must be convex.
Unit tests.
None.
None.
None.
=> feat(universe_utils): add GJK implementation for 2D convex polygon collision check

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/shift_line_generator.cpp
Now if front object is NOT avoidable as following fig, this module doesn't generate avoidance path even when behind object is avoidable. I think if the front object blocks ego path, it's proper behavior. But if the ego can go through, this module must generate avoidance path for behind object.
After this PR, this module will output avoidance path for behind object if front object is NOT on the path.
If front object is on ego path, this module won't generate avoidance path.
Additionally, if the front object is RIGHT and behind object is LEFT, this module won't generate avoidance path because the avoidance path for behind object might conflict front object, and vice versa.
- Link
None.
None.
None.
=> fix(static_obstacle_avoidance): avoid object behind unavoidance object if unavoidable is not on the path

system/emergency_handler/package.xml, system/mrm_handler/package.xml
This is basically based on [this](https://github.com/autowarefoundation/autoware/issues/3468#issuecomment-2235846503)
- Link
None.
None.
None.
=> fix(mrm_handler, emergency_handler): remove unnecessary depend

perception/detected_object_validation/src/occupancy_grid_map/occupancy_grid_map_validator.cpp
```
perception/detected_object_validation/src/occupancy_grid_map/occupancy_grid_map_validator.cpp:166:14: style: Local variable 'mask' shadows outer variable [shadowVariable]
auto mask = getMask(ros_occ_grid, object, passed_objects_image);
^
perception/detected_object_validation/src/occupancy_grid_map/occupancy_grid_map_validator.cpp:169:14: style: Local variable 'mask' shadows outer variable [shadowVariable]
auto mask = getMask(ros_occ_grid, object, removed_objects_image);
^
```
- Link
None.
None.
None.
=> fix(detected_object_validation): fix shadowVariable

evaluator/perception_online_evaluator/src/perception_online_evaluator_node.cpp
```
evaluator/perception_online_evaluator/src/perception_online_evaluator_node.cpp:278:23: style: Local variable 'ns' shadows outer variable [shadowVariable]
const std::string ns = "debug_marker.";
^
```
- Link
None.
None.
None.
=> fix(perception_online_evaluator): fix shadowVariable

perception/traffic_light_map_based_detector/src/node.cpp
```
perception/traffic_light_map_based_detector/src/node.cpp:190:38: style: Variable 'ex' can be declared as reference to const [constVariableReference]
} catch (tf2::TransformException & ex) {
^
```
- Link
None.
None.
None.
=> fix(traffic_light_map_based_detector): fix constVariableReference

perception/traffic_light_multi_camera_fusion/src/node.cpp
```
perception/traffic_light_multi_camera_fusion/src/node.cpp:296:15: style: Variable 'p' can be declared as reference to const [constVariableReference]
for (auto & p : fused_record_map) {
^
```
- Link
None.
None.
None.
=> fix(traffic_light_multi_camera_fusion): fix constVariableReference

perception/autoware_crosswalk_traffic_light_estimator/src/node.cpp
```
perception/autoware_crosswalk_traffic_light_estimator/src/node.cpp:212:15: style: Variable 'last_traffic_signal' can be declared as reference to const [constVariableReference]
for (auto & last_traffic_signal : last_detect_color_) {
^
```
- Link
None.
None.
None.
=> fix(autoware_crosswalk_traffic_light_estimator): fix constVariableReference

perception/autoware_radar_fusion_to_detected_object/src/include/radar_fusion_to_detected_object.hpp, perception/autoware_radar_fusion_to_detected_object/src/radar_fusion_to_detected_object.cpp
```
perception/autoware_radar_fusion_to_detected_object/src/radar_fusion_to_detected_object.cpp:208:77: style: Parameter 'radars' can be declared as reference to const [constParameterReference]
const DetectedObject & object, std::shared_ptr<std::vector<RadarInput>> & radars)
^
perception/autoware_radar_fusion_to_detected_object/src/radar_fusion_to_detected_object.cpp:301:77: style: Parameter 'radars' can be declared as reference to const [constParameterReference]
const DetectedObject & object, std::shared_ptr<std::vector<RadarInput>> & radars)
^
```
- Link
None.
None.
None.
=> fix(autoware_radar_fusion_to_detected_object): fix constParameterReference

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/utils.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp
```
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp:889:16: style: Parameter 'object' can be declared as reference to const [constParameterReference]
ObjectData & object, const std::shared_ptr<AvoidanceParameters> & parameters)
^
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp:1104:81: style: Parameter 'planner_data' can be declared as reference to const [constParameterReference]
const lanelet::ConstLanelets & lanelets, std::shared_ptr<const PlannerData> & planner_data)
^
```
- Link
None.
None.
None.
=> fix(autoware_behavior_path_static_obstacle_avoidance_module): fix constParameterReference

planning/autoware_rtc_interface/include/autoware/rtc_interface/rtc_interface.hpp, planning/autoware_rtc_interface/src/rtc_interface.cpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/scene.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp
When static obstacle avoidance was force activated by operators under unsafe condition, the yield maneuver activates and the avoidance is canceled.
Although, when force activated it should activate the avoidance maneuver (never cancel) regardless to the safe/unsafe judgement inside the module. This PR enables static obstacle avoidance once the the avoidance path is force activated via RTC.
Psim
[Before](https://github.com/user-attachments/assets/0319e799-5a65-47c0-bfe3-23c104bfc20e)
[After](https://github.com/user-attachments/assets/876ac81d-5076-4d9d-b0c9-142151c840f9)
[TIER IV internal test](https://evaluation.tier4.jp/evaluation/reports/0a9c3bda-f162-5d37-b2de-e25ee177602a?project_id=prd_jt)
The RTC interface module is changed as well
None.
None.
=> feat(static_obstacle_avoidance): enable force execution under unsafe conditions

perception/traffic_light_occlusion_predictor/CMakeLists.txt, perception/traffic_light_occlusion_predictor/src/node.cpp, perception/traffic_light_occlusion_predictor/src/node.hpp, perception/traffic_light_occlusion_predictor/src/occlusion_predictor.cpp, perception/traffic_light_occlusion_predictor/src/occlusion_predictor.hpp
=> refactor(traffic_light_occlusion_predictor): fix namespace and directory structure

planning/autoware_surround_obstacle_checker/src/node.hpp
```
planning/autoware_surround_obstacle_checker/src/node.cpp:517:44: style: inconclusive: Function 'isStopRequired' argument 2 names different: declaration 'is_stopped' definition 'is_vehicle_stopped'. [funcArgNamesDifferent]
const bool is_obstacle_found, const bool is_vehicle_stopped)
^
```
- Link
None.
None.
None.
=> fix(autoware_surround_obstacle_checker): fix funcArgNamesDifferent

planning/autoware_surround_obstacle_checker/src/node.cpp
```
planning/autoware_surround_obstacle_checker/src/node.cpp:509:38: style: Variable 'ex' can be declared as reference to const [constVariableReference]
} catch (tf2::TransformException & ex) {
^
```
- Link
None.
None.
None.
=> fix(autoware_surround_obstacle_checker): fix constVariableReference

control/autoware_operation_mode_transition_manager/src/node.hpp
```
control/autoware_operation_mode_transition_manager/src/node.cpp:116:87: style: inconclusive: Function 'changeOperationMode' argument 1 names different: declaration 'mode' definition 'request_mode'. [funcArgNamesDifferent]
void OperationModeTransitionManager::changeOperationMode(std::optional<OperationMode> request_mode)
^
```
- Link
None.
None.
None.
=> fix(autoware_operation_mode_transition_manager): fix funcArgNamesDifferent

planning/autoware_static_centerline_generator/src/utils.hpp
```
planning/autoware_static_centerline_generator/src/utils.cpp:106:61: style: inconclusive: Function 'get_path_with_lane_id' argument 4 names different: declaration 'nearest_ego_dist_threshold' definition 'ego_nearest_dist_threshold'. [funcArgNamesDifferent]
const geometry_msgs::msg::Pose & start_pose, const double ego_nearest_dist_threshold,
^
planning/autoware_static_centerline_generator/src/utils.cpp:107:16: style: inconclusive: Function 'get_path_with_lane_id' argument 5 names different: declaration 'nearest_ego_yaw_threshold' definition 'ego_nearest_yaw_threshold'. [funcArgNamesDifferent]
const double ego_nearest_yaw_threshold)
^
```
- Link
None.
None.
None.
=> fix(autoware_static_centerline_generator): fix funcArgNamesDifferent

sensing/pointcloud_preprocessor/src/concatenate_data/concatenate_and_time_sync_nodelet.cpp, sensing/pointcloud_preprocessor/src/concatenate_data/concatenate_pointclouds.cpp, sensing/pointcloud_preprocessor/src/time_synchronizer/time_synchronizer_nodelet.cpp
```
sensing/pointcloud_preprocessor/src/concatenate_data/concatenate_and_time_sync_nodelet.cpp:507:79: style: Parameter 'field' can be declared as reference to const [constParameterReference]
std::any_of(input_ptr->fields.begin(), input_ptr->fields.end(), [](auto & field) {
^
sensing/pointcloud_preprocessor/src/concatenate_data/concatenate_and_time_sync_nodelet.cpp:512:79: style: Parameter 'field' can be declared as reference to const [constParameterReference]
std::any_of(input_ptr->fields.begin(), input_ptr->fields.end(), [](auto & field) {
^
sensing/pointcloud_preprocessor/src/concatenate_data/concatenate_and_time_sync_nodelet.cpp:517:79: style: Parameter 'field' can be declared as reference to const …
```
=> fix(pointcloud_preprocessor): fix constParameterReference

common/autoware_overlay_rviz_plugin/autoware_overlay_rviz_plugin/include/signal_display.hpp, common/autoware_overlay_rviz_plugin/autoware_overlay_rviz_plugin/include/traffic_display.hpp, common/autoware_overlay_rviz_plugin/autoware_overlay_rviz_plugin/src/signal_display.cpp, common/autoware_overlay_rviz_plugin/autoware_overlay_rviz_plugin/src/traffic_display.cpp
The signal_display node subscribes the `TrafficLightGroupArray` message, but in [RViz config](https://github.com/autowarefoundation/autoware_launch/blob/f85eb6cad1e99db59bb47850f8f8171b7b4b1604/autoware_launch/rviz/autoware.rviz#L259), it specifis the `TrafficLightGroup` message. (The config was changed in [this PR](https://github.com/autowarefoundation/autoware_launch/pull/981).)
This caused the duplicated type definition and the traffic light display didn't work.
```
$ ros2 topic info /planning/scenario_planning/lane_driving/behavior_planning/debug/traffic_signal
Type: ['autoware_perception_msgs/msg/TrafficLightGroup', 'autoware_perception_msgs/msg/TrafficLightGroupArray']
Publisher count: 1
Subscription count: 1
```
I changed the message type of subscriber to `TrafficLightGroup` …
=> fix(autoware_overlay_rviz_plugin): topic type of traffic light

planning/behavior_path_planner/autoware_behavior_path_start_planner_module/include/autoware/behavior_path_start_planner_module/data_structs.hpp, planning/behavior_path_planner/autoware_behavior_path_start_planner_module/include/autoware/behavior_path_start_planner_module/start_planner_module.hpp, planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/start_planner_module.cpp
check current_pose and estimated_stop_pose for isPreventingRearVehicleFromPassingThrough.
Prevent the ego vehicle from getting stuck blocking other vehicles as a result of the stop. Use the predictive points of the stop to determine whether to block.
before this PR
https://github.com/user-attachments/assets/c778931b-edcb-46cb-bce4-1e3ab8220dd2
- Link
- https://tier4.atlassian.net/browse/RT1-7072
- psim with rosbag reproducer 
check safety check does not work when it is not necessary
https://github.com/user-attachments/assets/b8dc995f-b18b-454c-b667-c082cc666116
- psim
check safety check works properly and do not over work
https://github.com/user-attachments/assets/4c17e7e6-0763-4d53-a5bd-663cdc9c9bac
- evaluator
2024/07/19 …
=> feat(start_planner): check current_pose and estimated_stop_pose for isPreventingRearVehicleFromPassingThrough

localization/autoware_pose_covariance_modifier/src/include/pose_covariance_modifier.hpp
```
localization/autoware_pose_covariance_modifier/src/pose_covariance_modifier.cpp:74:73: style: inconclusive: Function 'callback_gnss_pose_with_cov' argument 1 names different: declaration 'msg' definition 'msg_pose_with_cov_in'. [funcArgNamesDifferent]
const geometry_msgs::msg::PoseWithCovarianceStamped::ConstSharedPtr & msg_pose_with_cov_in)
^
```
- Link
None.
None.
None.
=> fix(autoware_pose_covariance_modifier): fix funcArgNamesDifferent

perception/traffic_light_map_based_detector/CMakeLists.txt, perception/traffic_light_map_based_detector/package.xml, perception/traffic_light_map_based_detector/src/traffic_light_map_based_detector_node.cpp, perception/traffic_light_map_based_detector/src/traffic_light_map_based_detector_node.hpp
=> refactor(traffic_light_map_based_detector): fix namespace and directory structure

perception/traffic_light_multi_camera_fusion/CMakeLists.txt, perception/traffic_light_multi_camera_fusion/src/traffic_light_multi_camera_fusion_node.cpp, perception/traffic_light_multi_camera_fusion/src/traffic_light_multi_camera_fusion_node.hpp
=> refactor(traffic_light_multi_camera_fusion): fix namespace and directory structure

perception/autoware_multi_object_tracker/README.md
Fix missing transition to new package path
- Link
None.
None.
None.
=> fix(autoware_multi_object_tracker): missing parameter schema path fix

control/autoware_vehicle_cmd_gate/README.md, control/autoware_vehicle_cmd_gate/config/vehicle_cmd_gate.param.yaml, control/autoware_vehicle_cmd_gate/src/vehicle_cmd_gate.cpp
This PR delete rate limit skipping function which is activated when the vehicle departure.
More appropriate feature, including stopping, can be achieved by the parameter settings.
https://github.com/autowarefoundation/autoware_launch/pull/1077
I have tested this change by two type of real vehicles.
None.
None.
=> refactor(vehicle_cmd_gate)!: delete rate limit skipping function for vehicle departure

planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/interface/scene_module_interface.hpp
With the change made in the related link, existApprovedRequest function returned true value even when all cooperateStatus has terminated. Due to this change, some modules in the behavior path planner was not approved under appropriate condition. This PR reverts the existApprovedRequest function return value.
https://github.com/autowarefoundation/autoware.universe/pull/7743
[TIER IV internal test](https://evaluation.tier4.jp/evaluation/reports/2cc549ca-985d-5095-af3a-dd810ac8342f/tests/05e2ce34-0e97-58bd-a8fa-6a6db6f01477/bfcc5be5-4d0e-5a91-b2c7-cfbf68b971ec/f5fa29cf-6d53-57e1-b339-ab904359f326?project_id=prd_jt)
The state transition around terminated cooperate status would be considered once again, and would be implemented in future PR.
None.
None.
=> fix(bpp): fix approved request search 

launch/tier4_perception_launch/launch/traffic_light_recognition/traffic_light_node_container.launch.py, perception/traffic_light_fine_detector/CMakeLists.txt, perception/traffic_light_fine_detector/src/traffic_light_fine_detector_node.cpp, perception/traffic_light_fine_detector/src/traffic_light_fine_detector_node.hpp
=> refactor(traffic_light_fine_detector): fix namespace and directory structure

planning/autoware_costmap_generator/nodes/autoware_costmap_generator/costmap_generator_node.cpp, planning/autoware_scenario_selector/src/node.cpp
Use the improved `getLinkedParkingLot()` function so that it does not requiring providing ALL parking lots lanelets.
- Requires https://github.com/autowarefoundation/autoware_lanelet2_extension/pull/19
Psim
None.
None.
None.
=> perf(costmap_generator, scenario_selector): faster getLinkedParkingLot

.github/CODEOWNERS
- To fix typo which was pointed out here https://github.com/autowarefoundation/autoware.universe/pull/8003#discussion_r1685966432
- Link
None.
None.
None.
=> chore(euclidean_cluster): typo in Codeowners list

perception/autoware_lidar_transfusion/test/test_postprocess_kernel.cpp, perception/autoware_lidar_transfusion/test/test_preprocess_kernel.cpp, perception/autoware_lidar_transfusion/test/test_voxel_generator.cpp, perception/autoware_lidar_transfusion/test/test_voxel_generator.hpp
The commented out transfusion tests had not been updated to the latest headers so they did not compile. This PR just addressed that
None.
None.
None.
=> fix(lidar_transfusion): commented tests were out of date

planning/autoware_freespace_planning_algorithms/src/astar_search.cpp, planning/autoware_freespace_planning_algorithms/src/rrtstar_core.cpp
```
planning/autoware_freespace_planning_algorithms/src/astar_search.cpp:308:37: style: Local variable 'pose' shadows outer variable [shadowVariable]
geometry_msgs::msg::PoseStamped pose;
^
planning/autoware_freespace_planning_algorithms/src/astar_search.cpp:313:21: style: Local variable 'pw' shadows outer variable [shadowVariable]
PlannerWaypoint pw;
^
planning/autoware_freespace_planning_algorithms/src/rrtstar_core.cpp:186:19: style: Local variable 'node_best_parent' shadows outer variable [shadowVariable]
NodeSharedPtr node_best_parent;
^
```
- Link
None.
None.
None.
=> fix(autoware_freespace_planning_algorithms): fix shadowVariable

perception/probabilistic_occupancy_grid_map/src/fusion/synchronized_grid_map_fusion_node.hpp
```
perception/probabilistic_occupancy_grid_map/src/fusion/synchronized_grid_map_fusion_node.cpp:183:23: style: inconclusive: Function 'onGridMap' argument 2 names different: declaration 'input_topic' definition 'topic_name'. [funcArgNamesDifferent]
const std::string & topic_name)
^
```
- Link
None.
None.
None.
=> fix(probabilistic_occupancy_grid_map): fix funcArgNamesDifferent

perception/autoware_detection_by_tracker/src/tracker/tracker_handler.cpp, perception/autoware_detection_by_tracker/src/tracker/tracker_handler.hpp
```
perception/autoware_detection_by_tracker/src/tracker/tracker_handler.cpp:26:71: style: inconclusive: Function 'onTrackedObjects' argument 1 names different: declaration 'input_objects_msg' definition 'msg'. [funcArgNamesDifferent]
const autoware_perception_msgs::msg::TrackedObjects::ConstSharedPtr msg)
^
```
- Link
None.
None.
None.
=> fix(autoware_detection_by_tracker): fix funcArgNamesDifferent

perception/radar_tracks_msgs_converter/src/radar_tracks_msgs_converter_node.cpp
```
for (auto & object : objects.objects) {
^
perception/radar_tracks_msgs_converter/src/radar_tracks_msgs_converter_node.cpp:227:15: style: Variable 'radar_track' can be declared as reference to const [constVariableReference]
for (auto & radar_track : radar_data_->tracks) {
^
```
- Link
None.
None.
None.
=> fix(radar_tracks_msgs_converter): fix constVariableReference

planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/config/out_of_lane.param.yaml, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/filter_predicted_objects.cpp, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_module.cpp, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/types.hpp, planning/motion_velocity_planner/autoware_motion_velocity_planner_node/src/node.cpp
Add an option to ignore objects coming from behind the ego vehicle in the `out_of_lane` module.
- Required launch PR: https://github.com/autowarefoundation/autoware_launch/pull/1062
ROSBag
Psim
None.
None.
None.
=> feat(out_of_lane): ignore objects coming from behind ego

planning/autoware_velocity_smoother/src/node.cpp
```
planning/autoware_velocity_smoother/src/node.cpp:1082:45: style: Parameter 'pt' can be declared as reference to const [constParameterReference]
points.begin(), points.end(), [](auto & pt) { return pt.longitudinal_velocity_mps < 0; });
^
```
- Link
None.
None.
None.
=> fix(autoware_velocity_smoother): fix constParameterReference

planning/autoware_velocity_smoother/src/trajectory_utils.cpp
```
planning/autoware_velocity_smoother/src/trajectory_utils.cpp:232:15: style: Variable 'tp' can be declared as reference to const [constVariableReference]
for (auto & tp : trajectory) {
^
planning/autoware_velocity_smoother/src/trajectory_utils.cpp:243:15: style: Variable 'tp' can be declared as reference to const [constVariableReference]
for (auto & tp : trajectory) {
^
planning/autoware_velocity_smoother/src/trajectory_utils.cpp:437:15: style: Variable 'it' can be declared as reference to const [constVariableReference]
for (auto & it : jerk_profile) {
^
planning/autoware_velocity_smoother/src/trajectory_utils.cpp:547:15: style: Variable 'it' can be declared as reference to const [constVariableReference]
for (auto & it : …
```
=> fix(autoware_velocity_smoother): fix constVariableReference

control/autoware_lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker.cpp
```
control/autoware_lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker.cpp:335:23: style: Local variable 'p' shadows outer variable [shadowVariable]
for (const auto & p : poly) {
^
```
- Link
None.
None.
None.
=> fix(autoware_lane_departure_checker): fix shadowVariable

perception/probabilistic_occupancy_grid_map/lib/costmap_2d/occupancy_grid_map_fixed.cpp, perception/probabilistic_occupancy_grid_map/lib/costmap_2d/occupancy_grid_map_projective.cpp, perception/probabilistic_occupancy_grid_map/lib/fusion_policy/fusion_policy.cpp
```
perception/probabilistic_occupancy_grid_map/lib/costmap_2d/occupancy_grid_map_fixed.cpp:163:12: style: Variable 'raw_pointcloud_angle_bin' can be declared as reference to const [constVariableReference]
auto & raw_pointcloud_angle_bin = raw_pointcloud_angle_bins.at(bin_index);
^
perception/probabilistic_occupancy_grid_map/lib/costmap_2d/occupancy_grid_map_fixed.cpp:178:12: style: Variable 'obstacle_pointcloud_angle_bin' can be declared as reference to const [constVariableReference]
auto & obstacle_pointcloud_angle_bin = obstacle_pointcloud_angle_bins.at(bin_index);
^
perception/probabilistic_occupancy_grid_map/lib/costmap_2d/occupancy_grid_map_fixed.cpp:179:12: style: Variable 'raw_pointcloud_angle_bin' can be declared as …
```
=> fix(probabilistic_occupancy_grid_map): fix constVariableReference

system/diagnostic_graph_aggregator/src/common/graph/config.cpp
```
system/diagnostic_graph_aggregator/src/common/graph/config.cpp:256:36: style: Parameter 'config' can be declared as reference to const [constParameterReference]
void topological_sort(FileConfig & config)
^
```
- Link
None.
None.
None.
=> fix(diagnostic_graph_aggregator): fix constParameterReference

perception/autoware_object_velocity_splitter/src/object_velocity_splitter_node.cpp, perception/autoware_object_velocity_splitter/src/object_velocity_splitter_node.hpp
```
perception/object_velocity_splitter/src/object_velocity_splitter_node.cpp:68:82: style: inconclusive: Function 'onObjects' argument 1 names different: declaration 'msg' definition 'objects_data_'. [funcArgNamesDifferent]
void ObjectVelocitySplitterNode::onObjects(const DetectedObjects::ConstSharedPtr objects_data_)
^
```
- Link
None.
None.
None.
=> fix(autoware_object_velocity_splitter): fix funcArgNamesDifferent

perception/autoware_radar_object_clustering/src/radar_object_clustering_node.cpp, perception/autoware_radar_object_clustering/src/radar_object_clustering_node.hpp
```
perception/radar_object_clustering/src/radar_object_clustering_node.cpp:94:81: style: inconclusive: Function 'onObjects' argument 1 names different: declaration 'msg' definition 'objects_data_'. [funcArgNamesDifferent]
void RadarObjectClusteringNode::onObjects(const DetectedObjects::ConstSharedPtr objects_data_)
^
```
- Link
None.
None.
None.
=> fix(autoware_radar_object_clustering): fix funcArgNamesDifferent

perception/lidar_apollo_instance_segmentation/src/debugger.cpp, perception/lidar_apollo_instance_segmentation/src/detector.cpp
```
perception/lidar_apollo_instance_segmentation/src/debugger.cpp:87:17: style: Local variable 'i' shadows outer variable [shadowVariable]
for (size_t i = 0; i < object_pointcloud.size(); i++) {
^
```
Using range-based for loop.
- Link
None.
None.
None.
=> fix(lidar_apollo_instance_segmentation): fix shadowVariable

planning/autoware_obstacle_stop_planner/src/adaptive_cruise_control.hpp
```
planning/autoware_obstacle_stop_planner/src/adaptive_cruise_control.cpp:203:49: style: inconclusive: Function 'insertAdaptiveCruiseVelocity' argument 7 names different: declaration 'current_velocity_ptr' definition 'current_odometry_ptr'. [funcArgNamesDifferent]
const nav_msgs::msg::Odometry::ConstSharedPtr current_odometry_ptr, bool * need_to_stop,
^
```
- Link
None.
None.
None.
=> fix(autoware_obstacle_stop_planner): fix funcArgNamesDifferent

.cppcheck_suppressions
`constVariableReference` warnings are completely removed!!
You can find it here https://github.com/autowarefoundation/autoware.universe/actions/runs/10050440664
- Link
None.
None.
None.
=> chore(ci): remove constVariableReference from cppcheck suppressions

sensing/autoware_pointcloud_preprocessor/src/downsample_filter/robin_hood.h
revert this PR https://github.com/autowarefoundation/autoware.universe/pull/8139
- [TIER IV INTERNAL](https://star4.slack.com/archives/C4P0NSMB5/p1721700502159959)
None.
None.
None.
=> fix(autoware_pointcloud_preprocessor): revert increase_size() in robin_hood

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/utils.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp
Whenever there are vehicles parked in the target lane, we want to delay lane change as long as possible. Currently, the feature in implemented in the path generation. However, once the path is approved, delay lane change check is no longer performed.
This PR adds delay lane change after path is approved.
The passParkedVehicle function is also refactored, as the return boolean value do not properly correspond to the function name.
Before PR:
https://github.com/user-attachments/assets/6d24448c-6651-4483-8abc-8d021b062b83
After PR:
Lane change is cancelled, and it will be executed after front-most parked vehicle.
https://github.com/user-attachments/assets/6a01d369-2473-403a-841a-efd5ba2c9961
- [TIER IV internal link](https://tier4.atlassian.net/browse/RT1-6955)
- PSIM
- …
=> fix(lane_change): delay lane change cancel

.github/sync-files.yaml, .github/workflows/build-and-test-daily-arm64.yaml, .github/workflows/build-and-test-daily.yaml, .github/workflows/build-and-test-differential-arm64.yaml, .github/workflows/build-and-test-differential.yaml, .github/workflows/build-and-test.yaml
This PR updates the tag names of the docker images used in the GitHub Actions workflow, based on corrections from the PR https://github.com/autowarefoundation/autoware/pull/4961.
https://github.com/orgs/autowarefoundation/discussions/4661#discussioncomment-9995806
https://github.com/autowarefoundation/autoware.universe/actions/runs/10054982444?pr=7952
None.
None.
None.
=> feat(ci): update `autoware`'s image tag

planning/autoware_obstacle_cruise_planner/include/autoware/obstacle_cruise_planner/node.hpp, planning/autoware_obstacle_cruise_planner/include/autoware/obstacle_cruise_planner/type_alias.hpp, planning/autoware_obstacle_cruise_planner/src/node.cpp, planning/autoware_velocity_smoother/include/autoware/velocity_smoother/node.hpp, planning/autoware_velocity_smoother/src/node.cpp
Currently, the message type of the processing time published by the velocity_smoother and obstacle_cruise_planner was Float32Stamped although the processing_time_checker.py which received the topics thought they were Float64Stamped.
Previously, the current settings worked as expected, but recently it doesn't for some reason.
This PR fixed the issue.
psim
None.
None.
None.
=> fix(velocity_smoother, obstacle_cruise_planner ): float type of processing time was wrong

sensing/vehicle_velocity_converter/include/vehicle_velocity_converter/vehicle_velocity_converter.hpp, sensing/vehicle_velocity_converter/src/vehicle_velocity_converter.cpp
This PR applies some suggestions from the linter to `sensing/vehicle_velocity_converter`.
Fixed:
- change function/method
- removed
- unused var
- explicit default destructor
- Link
Checked with clang-tidy (v14.0.0) and cppcheck (v2.14.1).
Use `.cppcheck_suppressions` for suppressing some notation from cppcheck.
<details>
```
#!/bin/bash
set -eux
TARGET_DIR=$1
exit 1
fi
set +eux
set -eux
fdfind -e cpp …
```
=> refactor(vehicle_velocity_converter): apply static analysis

control/autoware_mpc_lateral_controller/src/mpc.cpp
In this [PR](https://github.com/autowarefoundation/autoware.universe/pull/5576), predicted path calculated using the Frenet coordinate system were added for debug purpose, but they couldn't be visualized in rviz due to missing header information. 
added the necessary header information with following modification to resolve this issue.
```
frenet_clipped.header.stamp = m_clock->now();
frenet_clipped.header.frame_id = "map";
```
tested in psim and confirmed visualization
None.
=> fix(autoware_mpc_lateral_controller): add timestamp and frame ID to published trajectory

control/autoware_pid_longitudinal_controller/include/autoware/pid_longitudinal_controller/pid_longitudinal_controller.hpp, control/autoware_pid_longitudinal_controller/param/longitudinal_controller_defaults.param.yaml, control/autoware_pid_longitudinal_controller/src/pid_longitudinal_controller.cpp, control/autoware_trajectory_follower_node/param/longitudinal/pid.param.yaml
This PR re-organize diff limit structure to achieve proper handling of diff limit when the state is changed.
Creep down problems on slopes will be fixed by this PR and https://github.com/autowarefoundation/autoware.universe/pull/7720.
In the new structure raw_ctrl_cmd denotes acceleration and ctrl_cmd denotes pedal position.
Before
After
launch PR: https://github.com/autowarefoundation/autoware_launch/pull/1052
psim, tier4 internal tests and vehicle tests
None.
some of parameters are newly defined and deleted
None.
=> feat(pid_longitudinal_controller): re-organize diff limit structure and fix state change condition

perception/autoware_map_based_prediction/include/map_based_prediction/map_based_prediction_node.hpp, perception/autoware_map_based_prediction/src/map_based_prediction_node.cpp
- https://tier4.atlassian.net/browse/RT0-32279
see the pic
None.
None.
None.
=> feat(map_based_prediction): add time_keeper

build_depends.repos, localization/ndt_scan_matcher/src/map_update_module.cpp, localization/ndt_scan_matcher/test/stub_pcd_loader.hpp, map/map_height_fitter/src/map_height_fitter.cpp, map/map_loader/src/pointcloud_map_loader/differential_map_loader_module.cpp, map/map_loader/src/pointcloud_map_loader/differential_map_loader_module.hpp, map/map_loader/src/pointcloud_map_loader/partial_map_loader_module.cpp, map/map_loader/src/pointcloud_map_loader/partial_map_loader_module.hpp, map/map_loader/src/pointcloud_map_loader/selected_map_loader_module.cpp, map/map_loader/src/pointcloud_map_loader/selected_map_loader_module.hpp, map/map_loader/test/test_differential_map_loader_module.cpp, map/map_loader/test/test_partial_map_loader_module.cpp, perception/autoware_compare_map_segmentation/src/distance_based_compare_map_filter/node.hpp, perception/autoware_compare_map_segmentation/src/voxel_distance_based_compare_map_filter/node.hpp, perception/autoware_compare_map_segmentation/src/voxel_grid_map_loader/voxel_grid_map_loader.cpp, perception/autoware_compare_map_segmentation/src/voxel_grid_map_loader/voxel_grid_map_loader.hpp, perception/elevation_map_loader/include/elevation_map_loader/elevation_map_loader_node.hpp, perception/elevation_map_loader/src/elevation_map_loader_node.cpp
This reverts commit 8ea7de77760cd995c8e653dd85a7a832c3970950.
This is a breaking change to autoware_msgs API and since autoware_msgs started to do version control, we should wait until autoware_msgs releases a new version with the new API.
- Link
None.
None.
None.
=> revert: revert "refactor(autoware_map_msgs): modify pcd metadata msg (#7852)"

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/README.md, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/scene.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/data_structs.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/utils.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp
This PR aims to fix object filtering when dealing with objects ahead of terminal point.
Terminal point is where lane change is perform  with the minimum distance either at the terminal lane or near goal.
The end of current lanes will be the last possible lane where ego can perform lane change. We can call this as terminal lane. As shown in the following diagram
Any lanes ahead of the of terminal lane is consider ahead terminal.
Similar to if the terminal lane is within goal route section, then anything after goal is consider ahead terminal.
In some case, object after lane change end pose is still considered as target lane object, even though it is ahead of terminal lane. Note the cyan square indicating target lane objects
https://github.com/user-attachments/assets/be755147-1b4b-4246-b56b-5 …
=> fix(lane_change): filtering object ahead of terminal

perception/autoware_multi_object_tracker/include/autoware/multi_object_tracker/association/solver/ssp.hpp, perception/autoware_multi_object_tracker/lib/association/successive_shortest_path/ssp.cpp, perception/autoware_object_merger/include/autoware/object_merger/association/solver/ssp.hpp, perception/autoware_object_merger/src/association/solver/successive_shortest_path.cpp, perception/autoware_radar_object_tracker/include/autoware_radar_object_tracker/association/solver/ssp.hpp, perception/autoware_radar_object_tracker/src/association/ssp/successive_shortest_path.cpp, perception/autoware_tracking_object_merger/include/autoware/tracking_object_merger/association/solver/ssp.hpp, perception/autoware_tracking_object_merger/src/association/solver/successive_shortest_path.cpp
This is a fix based on cppcheck warnings (other packages has the same warnings)
```
perception/autoware_multi_object_tracker/lib/association/successive_shortest_path/ssp.cpp:72:7: style: Condition 'sparse_cost' is always true [knownConditionTrueFalse]
if (sparse_cost) {
^
perception/autoware_multi_object_tracker/lib/association/successive_shortest_path/ssp.cpp:53:22: note: Assignment 'sparse_cost=true', assigned value is 1
bool sparse_cost = true;
^
perception/autoware_multi_object_tracker/lib/association/successive_shortest_path/ssp.cpp:63:24: note: Assuming condition is false
if (cost.size() == 0 || cost.at(0).size() == 0) {
^
perception/autoware_multi_object_tracker/lib/association/successive_shortest_path/ssp.cpp:72:7: note: Condition 'sparse_cost' is always true
if (sparse_cost) {
^ …
```
=> fix(multi_object_tracker, object_merger, radar_object_tracker, tracking_object_merger): fix knownConditionTrueFalse warnings

planning/behavior_path_planner/autoware_behavior_path_planner/config/drivable_area_expansion.param.yaml, planning/behavior_path_planner/autoware_behavior_path_planner/src/behavior_path_planner_node.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/drivable_area_expansion/parameters.hpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/drivable_area_expansion/drivable_area_expansion.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/test/test_drivable_area_expansion.cpp
The dynamic drivable area expansion allow making the drivable area large enough for the vehicle to pass.
Previously, it was only able to modify the existing bound points, "pushing" them away to make the drivable area bigger. This could cause issues when the bounds of the drivable area have very few points.
With this PR, we add some bound points to ensure the drivable area can correctly be expanded.
Requires https://github.com/autowarefoundation/autoware_launch/pull/1092
- Evaluator: [TIER IV internal link](https://evaluation.tier4.jp/evaluation/reports/87a23d35-873d-524d-b222-796591637862?project_id=prd_jt)
None.
None.
None.
=> fix(behavior_path_planner_common): enable drivable area expansion even with few bound points

.cppcheck_suppressions
Removed `knownConditionTrueFalse` and `shadowVariable`
cppcheck-daily result:
https://github.com/autowarefoundation/autoware.universe/actions/runs/10103517226/job/27941024243
None.
None.
None.
=> chore(ci): reduce unnecessary cppcheck suppressions

planning/autoware_surround_obstacle_checker/src/node.cpp
```
planning/autoware_surround_obstacle_checker/src/node.cpp:72:21: performance: Function parameter 'no_start_reason' should be passed by const reference. [passedByValue]
const std::string no_start_reason, const geometry_msgs::msg::Pose & stop_pose)
^
```
- Link
None.
None.
None.
=> fix(autoware_surround_obstacle_checker): fix passedByValue

planning/autoware_path_smoother/include/autoware/path_smoother/utils/trajectory_utils.hpp, planning/autoware_path_smoother/src/utils/trajectory_utils.cpp
```
planning/autoware_path_smoother/src/utils/trajectory_utils.cpp:53:38: performance: Function parameter 'traj_points' should be passed by const reference. [passedByValue]
const std::vector<TrajectoryPoint> traj_points, const double interval)
^
planning/autoware_path_smoother/src/utils/trajectory_utils.cpp:65:38: performance: Function parameter 'traj_points' should be passed by const reference. [passedByValue]
const std::vector<TrajectoryPoint> traj_points, const double interval)
^
```
- Link
None.
None.
None.
=> fix(autoware_path_smoother): fix passedByValue

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/utils.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp
```
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp:530:36: performance: Function parameter 'original_drivable_lanes' should be passed by const reference. [passedByValue]
const std::vector<DrivableLanes> original_drivable_lanes, const RouteHandler & route_handler,
^
```
- Link
None.
None.
None.
=> fix(autoware_behavior_path_lane_change_module): fix passedByValue

evaluator/perception_online_evaluator/include/perception_online_evaluator/utils/marker_utils.hpp, evaluator/perception_online_evaluator/src/utils/marker_utils.cpp
This is a fix based on cppcheck passedByValue warnings
```
autoware.universe/evaluator/perception_online_evaluator/src/utils/marker_utils.cpp:79:28: performance: Function parameter 'points' should be passed by const reference. [passedByValue]
const std::vector<Point> points, const std::string & ns, const int32_t id, const float r,
^
autoware.universe/evaluator/perception_online_evaluator/src/utils/marker_utils.cpp:96:27: performance: Function parameter 'poses' should be passed by const reference. [passedByValue]
const std::vector<Pose> poses, const std::string & ns, const int32_t id, const float r,
^
autoware.universe/evaluator/perception_online_evaluator/src/utils/marker_utils.cpp:113:27: performance: Function parameter 'poses1' should be passed by const reference. [passedByValue]
const …
```
=> fix(perception_online_evaluator): passedByValue

planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/marker_utils/utils.hpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/path_utils.hpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/src/marker_utils/utils.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_utils.cpp
```
planning/behavior_path_planner/autoware_behavior_path_planner_common/src/marker_utils/utils.cpp:82:28: performance: Function parameter 'points' should be passed by const reference. [passedByValue]
const std::vector<Point> points, const std::string & ns, const int32_t id, const float r,
^
planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_utils.cpp:379:58: performance: Function parameter 'indices' should be passed by const reference. [passedByValue]
const PathWithLaneId & path, const std::vector<size_t> indices)
^
planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_utils.cpp:448:23: performance: Function parameter 'base_s' should be passed by const …
```
=> fix(autoware_behavior_path_planner_common): fix passedByValue

planning/behavior_velocity_planner/autoware_behavior_velocity_planner/src/planner_manager.cpp
```
planning/behavior_velocity_planner/autoware_behavior_velocity_planner/src/planner_manager.cpp:38:21: performance: Function parameter 'stop_reason' should be passed by const reference. [passedByValue]
const std::string stop_reason, const geometry_msgs::msg::Pose & stop_pose)
^
```
- Link
None.
None.
None.
=> fix(autoware_behavior_velocity_planner): fix passedByValue

planning/sampling_based_planner/autoware_path_sampler/include/autoware_path_sampler/utils/trajectory_utils.hpp, planning/sampling_based_planner/autoware_path_sampler/src/utils/trajectory_utils.cpp
```
planning/sampling_based_planner/autoware_path_sampler/src/utils/trajectory_utils.cpp:62:38: performance: Function parameter 'traj_points' should be passed by const reference. [passedByValue]
const std::vector<TrajectoryPoint> traj_points, const double interval)
^
planning/sampling_based_planner/autoware_path_sampler/src/utils/trajectory_utils.cpp:74:38: performance: Function parameter 'traj_points' should be passed by const reference. [passedByValue]
const std::vector<TrajectoryPoint> traj_points, const double interval)
^
```
- Link
None.
None.
None.
=> fix(autoware_path_sampler): fix passedByValue

perception/autoware_compare_map_segmentation/src/compare_elevation_map_filter/node.cpp
```
perception/autoware_compare_map_segmentation/src/compare_elevation_map_filter/node.cpp:77:16: style: Redundant initialization for 'output_frame'. The initialized value is overwritten before it is read. [redundantInitialization]
output_frame = elevation_map_.getFrameId();
^
perception/autoware_compare_map_segmentation/src/compare_elevation_map_filter/node.cpp:75:28: note: output_frame is initialized
std::string output_frame = map_frame_;
^
perception/autoware_compare_map_segmentation/src/compare_elevation_map_filter/node.cpp:77:16: note: output_frame is overwritten
output_frame = elevation_map_.getFrameId();
^
```
- Link
None.
None.
None.
=> fix(autoware_compare_map_segmentation): fix redundantInitialization warning

planning/autoware_rtc_interface/include/autoware/rtc_interface/rtc_interface.hpp, planning/autoware_rtc_interface/src/rtc_interface.cpp
Current rtc interface could not judge whether cooperateStatus was force deactivated or not.
This PR enables to judge force deactivation (ex. deactivation from human operators).
[TIER IV internal test](https://evaluation.tier4.jp/evaluation/reports/2ab7653e-934b-51d5-b94e-05e2d10d3664?project_id=prd_jt)
None.
None.
None.
=> feat(rtc_inteface): add function to check force deactivate

planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/occluded_crosswalk.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/occluded_crosswalk.hpp, planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
```
planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/occluded_crosswalk.cpp:89:29: performance: Function parameter 'velocity_thresholds' should be passed by const reference. [passedByValue]
const std::vector<double> velocity_thresholds, const double inflate_size)
^
planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp:148:48: performance: Function parameter 'stop_factor_points' should be passed by const reference. [passedByValue]
const std::vector<geometry_msgs::msg::Point> stop_factor_points = {})
^
```
- Link
None.
None.
None.
=> fix(autoware_behavior_velocity_crosswalk_module): fix passedByValue

evaluator/autoware_control_evaluator/launch/control_evaluator.launch.xml, evaluator/autoware_planning_evaluator/launch/planning_evaluator.launch.xml, evaluator/perception_online_evaluator/launch/perception_online_evaluator.launch.xml, launch/tier4_control_launch/launch/control.launch.xml, launch/tier4_simulator_launch/launch/simulator.launch.xml
/diagnostic/* topic name is confusing because theare are /diagnostics/* topics.
and in the future, we plan to separate metrics (just calculate value) and diagnostics (compare with threshould).
- Link
- https://star4.slack.com/archives/C03QW0GU6P7/p1720616595278849
- https://star4.slack.com/archives/C03QW0GU6P7/p1721702345525949?thread_ts=1721700599.221729&cid=C03QW0GU6P7
2024/07/23 https://evaluation.tier4.jp/evaluation/reports/fda048c3-d0c1-549c-91e6-9a7444741bb8/?project_id=prd_jt
None.
None.
None.
=> feat(evalautor): rename evaluator diag topics

perception/autoware_radar_object_tracker/src/tracker/model/constant_turn_rate_motion_tracker.cpp, perception/autoware_radar_object_tracker/src/tracker/model/linear_motion_tracker.cpp
```
perception/autoware_radar_object_tracker/src/tracker/model/constant_turn_rate_motion_tracker.cpp:287:15: style: Redundant initialization for 'Q_xy_global'. The initialized value is overwritten before it is read. [redundantInitialization]
Q_xy_global = R * Q_xy_local * R.transpose();
^
perception/autoware_radar_object_tracker/src/tracker/model/constant_turn_rate_motion_tracker.cpp:283:31: note: Q_xy_global is initialized
Eigen::MatrixXd Q_xy_global = Eigen::MatrixXd::Zero(2, 2);
^
perception/autoware_radar_object_tracker/src/tracker/model/constant_turn_rate_motion_tracker.cpp:287:15: note: Q_xy_global is overwritten
Q_xy_global = R * Q_xy_local * R.transpose();
^ …
```
=> fix(autoware_radar_object_tracker): fix redundantInitialization

perception/autoware_multi_object_tracker/src/debugger/debug_object.cpp, perception/autoware_multi_object_tracker/src/debugger/debug_object.hpp
```
perception/autoware_multi_object_tracker/src/debugger/debug_object.cpp:54:58: performance: Function parameter 'frame_id' should be passed by const reference. [passedByValue]
TrackerObjectDebugger::TrackerObjectDebugger(std::string frame_id)
^
perception/autoware_multi_object_tracker/src/debugger/debug_object.cpp:176:46: performance: Function parameter 'object_data_groups' should be passed by const reference. [passedByValue]
const std::vector<std::vector<ObjectData>> object_data_groups,
^
perception/autoware_multi_object_tracker/src/debugger/debug_object.hpp:99:48: performance: Function parameter 'object_data_groups' should be passed by const reference. [passedByValue]
const std::vector<std::vector<ObjectData>> object_data_groups, …
```
=> fix(autoware_multi_object_tracker): fix passedByValue

perception/autoware_object_merger/src/object_association_merger_node.cpp
```
perception/autoware_object_merger/src/object_association_merger_node.cpp:39:25: performance: Function parameter 'distance_threshold_map' should be passed by const reference. [passedByValue]
std::map<int, double> distance_threshold_map,
^
perception/autoware_object_merger/src/object_association_merger_node.cpp:40:31: performance: Function parameter 'generalized_iou_threshold_map' should be passed by const reference. [passedByValue]
const std::map<int, double> generalized_iou_threshold_map)
^
```
- Link
None.
None.
None.
=> fix(autoware_object_merger): fix passedByValue

perception/autoware_image_projection_based_fusion/include/autoware/image_projection_based_fusion/utils/utils.hpp, perception/autoware_image_projection_based_fusion/src/utils/utils.cpp
```
perception/image_projection_based_fusion/src/utils/utils.cpp:121:29: performance: Function parameter 'clusters_data_size' should be passed by const reference. [passedByValue]
const std::vector<size_t> clusters_data_size, const PointCloud2 & in_cloud,
^
```
- Link
None.
None.
None.
=> fix(autoware_image_projection_based_fusion): fix passedByValue

perception/autoware_compare_map_segmentation/src/voxel_grid_map_loader/voxel_grid_map_loader.hpp
```
perception/compare_map_segmentation/src/voxel_grid_map_loader/voxel_grid_map_loader.hpp:227:30: performance: Function parameter 'map_cell_ids_to_remove' should be passed by const reference. [passedByValue]
std::vector<std::string> map_cell_ids_to_remove)
^
perception/compare_map_segmentation/src/voxel_grid_map_loader/voxel_grid_map_loader.hpp:274:47: performance: Function parameter 'map_cell_id_to_remove' should be passed by const reference. [passedByValue]
inline void removeMapCell(const std::string map_cell_id_to_remove)
^
```
- Link
None.
None.
None.
=> fix(autoware_compare_map_segmentation): fix passedByValue

sensing/autoware_image_diagnostics/src/image_diagnostics_node.cpp
This is a fix based on cppcheck `redundantInitialization` and `unreadVariable` warnings
```
sensing/autoware_image_diagnostics/src/image_diagnostics_node.cpp:54:11: style: Redundant initialization for 'level'. The initialized value is overwritten before it is read. [redundantInitialization]
level = DiagnosticStatusWrapper::STALE;
^
sensing/autoware_image_diagnostics/src/image_diagnostics_node.cpp:52:14: note: level is initialized
auto level = DiagnosticStatusWrapper::OK;
^
sensing/autoware_image_diagnostics/src/image_diagnostics_node.cpp:54:11: note: level is overwritten
level = DiagnosticStatusWrapper::STALE;
^
sensing/autoware_image_diagnostics/src/image_diagnostics_node.cpp:104:29: style: Variable 'region_freq_average' is assigned a value that is never used. [unreadVariable]
float …
```
=> fix(autoware_image_diagnostics): fix cppcheck warnings

sensing/autoware_pointcloud_preprocessor/src/blockage_diag/blockage_diag_nodelet.cpp
```
sensing/autoware_pointcloud_preprocessor/src/blockage_diag/blockage_diag_nodelet.cpp:113:11: style: Redundant initialization for 'level'. The initialized value is overwritten before it is read. [redundantInitialization]
level = DiagnosticStatus::STALE;
^
sensing/autoware_pointcloud_preprocessor/src/blockage_diag/blockage_diag_nodelet.cpp:110:14: note: level is initialized
auto level = DiagnosticStatus::OK;
^
sensing/autoware_pointcloud_preprocessor/src/blockage_diag/blockage_diag_nodelet.cpp:113:11: note: level is overwritten
level = DiagnosticStatus::STALE;
^
sensing/autoware_pointcloud_preprocessor/src/blockage_diag/blockage_diag_nodelet.cpp:144:11: style: Redundant initialization for 'level'. The initialized value is …
```
=> fix(autoware_pointcloud_preprocessor): fix redundantInitialization

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/freespace_pull_over.cpp, planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/freespace_pull_out.cpp
add error handling when freespace planning can not find path.
https://github.com/autowarefoundation/autoware.universe/pull/8068
```
[openscenario_interpreter_node-3] [component_container_mt-33] terminate called after throwing an instance of 'std::logic_error'
[openscenario_interpreter_node-3] [component_container_mt-33]   what():  HA* failed to find path to goal
[openscenario_interpreter_node-3] [component_container_mt-33] *** Aborted at 1722248354 (unix time) try "date -d @1722248354" if you are using GNU date ***
```
- Link
wip: 2024/07/29 https://evaluation.tier4.jp/evaluation/reports/5e0d0571-2e37-5845-956e-62dc4f7dd810/?project_id=prd_jt
None.
None.
None.
=> fix(start/goal_planner): fix freespace planning error handling

perception/autoware_detected_object_validation/src/lanelet_filter/lanelet_filter.cpp, perception/autoware_detected_object_validation/src/lanelet_filter/lanelet_filter.hpp
This PR is for speeding up the lanelet filtering process.
This PR will reduce the number of loops by using the inner R-tree of intersected lanelets.
Using the [TimeKeeper](https://github.com/autowarefoundation/autoware.universe/tree/main/common/autoware_universe_utils), I checked the bottleneck of lanelet filter node. The main bottleneck was the for-loop for the filtering for the objects that have no bounding box.
Example of worst cases.
Before this PR
```Text
objectCallback: 136.19 [ms]
├── getConvexHull: 0.35 [ms]
├── getIntersectedLanelets: 1.62 [ms]
├── filterObject: 0.00 [ms]
├── filterObject: 0.00 [ms]
├── filterObject: 0.00 [ms]
├── filterObject: 0.00 [ms]
├── filterObject: 0.00 [ms]
├── filterObject: 0.00 [ms]
├── filterObject: 0.00 [ms]
├── filterObject: 0.00 [ms]
├── …
```
=> perf(autoware_detected_object_validation): reduce lanelet_filter processing time 

planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/config/out_of_lane.param.yaml, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/calculate_slowdown_points.cpp, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/calculate_slowdown_points.hpp, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_module.cpp, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/types.hpp
In the `out_of_lane` module, the buffer distance to keep between the lane and the ego vehicle was only considering longitudinal distance. This PR also consider the lateral distance to properly keep the desired buffer distance.
The following video shows the new impact of the buffer distance parameter. On the right I dynamically update the parameter value (from `0.0` at first up to `5.0` m) and on the left you can see the distance increase between the stop point and the lane with the collision.
https://github.com/autowarefoundation/autoware.universe/assets/78338830/29d73561-c464-40dc-8409-a74489306a3d
Requires https://github.com/autowarefoundation/autoware_launch/pull/1098
Psim
None.
None.
None.
=> feat(out_of_lane): also apply lat buffer between the lane and stop pose

common/qp_interface/include/qp_interface/osqp_interface.hpp, common/qp_interface/include/qp_interface/proxqp_interface.hpp, common/qp_interface/src/osqp_interface.cpp, common/qp_interface/src/proxqp_interface.cpp, common/qp_interface/test/test_osqp_interface.cpp, common/qp_interface/test/test_proxqp_interface.cpp, planning/autoware_velocity_smoother/include/autoware/velocity_smoother/smoother/jerk_filtered_smoother.hpp, planning/autoware_velocity_smoother/package.xml, planning/autoware_velocity_smoother/src/smoother/jerk_filtered_smoother.cpp
Use ProxQP instead of OSQPfor the velocity optimization.
Enabling warm start makes several scenarios fail due to the optimization failure as follows, so the warm start is disabled.
https://evaluation.tier4.jp/evaluation/reports/76156fc6-7529-5edf-b8f8-de8589118b37?project_id=prd_jt
scenario test: https://evaluation.tier4.jp/evaluation/reports/6b10df3c-2ef3-5b69-9955-aee37d8b6c2b?project_id=prd_jt
psim
**Before (with OSQP)** (with warm start)
```
onCurrentTrajectory: 56.20 [ms]
├── calcExternalVelocityLimit: 0.00 [ms]
├── updateDataForExternalVelocityLimit: 0.01 [ms]
└── calcTrajectoryVelocity: 55.86 [ms]
├── applyExternalVelocityLimit: 0.01 [ms]
├── applyStopApproachingVelocity: 0.00 [ms]
└── smoothVelocity: 55.84 [ms]
├── calcInitialMotion: 0.00 [ms]
├── …
```
=> perf(velocity_smoother): use ProxQP for faster optimization

localization/ndt_scan_matcher/config/ndt_scan_matcher.param.yaml, localization/ndt_scan_matcher/schema/sub/covariance_covariance_estimation.json
Change the default parameter values ​​to improve the accuracy of online covariance estimation in NDT.
- https://github.com/autowarefoundation/autoware_launch/pull/1096
Driving Log Replayer is executed for 28 data.
For data with an error of 50 cm or less, the performance is almost the same as when the covariance is fixed.
As for other data with large errors, it is expected that there will be large fluctuations due to some degree of randomness.
None.
None.
None.
=> perf(ndt_scan_matcher): change the temperature of multi_ndt_score to 0.05

localization/autoware_landmark_based_localizer/autoware_ar_tag_based_localizer/src/ar_tag_based_localizer.cpp
Several publishers/subscribers were specified with QoS as transient_local and depth=10.
Since they handle only the most recent data, so depth=10 is unnecessary.
This PR optimizes the QoS by reducing the depth to 1.
- nothing
```
map_path:=$HOME/Maps/nishishinjuku \
vehicle_model:=sample_vehicle \
sensor_model:=awsim_sensor_kit \
pose_source:=artag
```
[rosbag&map](https://docs.google.com/uc?export=download&id=17ppdMKi4IC8J_2-_9nyYv-LAfW0M1re5)
This rosbag link is quated from [Driving Log Replayer Tutorial](https://tier4.github.io/driving_log_replayer/quick_start/setup/#set-up-resources)
None.
None.
None.
=> perf(autoware_ar_tag_based_localizer): remove unnecessary pub/sub depth for transient_local

control/autoware_lane_departure_checker/include/autoware/lane_departure_checker/lane_departure_checker.hpp, control/autoware_lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker.cpp, planning/behavior_path_planner/autoware_behavior_path_start_planner_module/include/autoware/behavior_path_start_planner_module/freespace_pull_out.hpp, planning/behavior_path_planner/autoware_behavior_path_start_planner_module/include/autoware/behavior_path_start_planner_module/geometric_pull_out.hpp, planning/behavior_path_planner/autoware_behavior_path_start_planner_module/include/autoware/behavior_path_start_planner_module/pull_out_planner_base.hpp, planning/behavior_path_planner/autoware_behavior_path_start_planner_module/include/autoware/behavior_path_start_planner_module/shift_pull_out.hpp, planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/freespace_pull_out.cpp, planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/geometric_pull_out.cpp, planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/shift_pull_out.cpp, planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/start_planner_module.cpp
Added a time_keeper to start_planner to track the processing time.
The following is the result where there is a front parked vehicle.
```
start_planner=>run: 41.71 [ms]
├── updateData: 0.04 [ms]
└── planWaitingApproval: 41.56 [ms]
├── updatePullOutStatus: 36.69 [ms]
│   ├── calcBackwardPathFromStartPose: 1.37 [ms]
│   ├── searchPullOutStartPoseCandidates: 1.81 [ms]
│   │   ├── filterStopObjectsInPullOutLanes: 0.17 [ms]
│   │   └── filterStopObjectsInPullOutLanes: 1.03 [ms]
│   └── planWithPriority: 33.13 [ms]
│       ├── determinePriorityOrder: 0.00 [ms]
│       └── findPullOutPaths: 33.12 [ms]
│           ├── calcPullOutPaths: 4.09 [ms]
│           ├── get safe path: 11.02 [ms]
│           │   ├── checkPathWillLeaveLane: 0.50 [ms]
│           │   │   └── …
```
=> feat(start_planner): add time_keeper

perception/autoware_tensorrt_classifier/src/tensorrt_classifier.cpp
```
perception/tensorrt_classifier/src/tensorrt_classifier.cpp:57:65: performance: Function parameter 'filename' should be passed by const reference. [passedByValue]
std::vector<std::string> loadListFromTextFile(const std::string filename)
^
```
- Link
None.
None.
None.
=> fix(autoware_tensorrt_classifier): fix passedByValue

perception/autoware_traffic_light_fine_detector/src/traffic_light_fine_detector_node.cpp
```
perception/traffic_light_fine_detector/src/nodelet.cpp:51:67: performance: Function parameter 'double_vector' should be passed by const reference. [passedByValue]
inline std::vector<float> toFloatVector(const std::vector<double> double_vector)
^
```
- Link
None.
None.
None.
=> fix(autoware_traffic_light_fine_detector): fix passedByValue

localization/yabloc/yabloc_common/src/ground_server/ground_server_core.cpp, localization/yabloc/yabloc_common/src/ll2_decomposer/ll2_decomposer_core.cpp
Several publishers/subscribers were specified with QoS as `transient_loca`l and `depth=10`.
Since they handle only  the most recent data, so `depth=10` is unnecessary.
This PR optimizes the QoS by reducing the depth to 1.
- nothing
```
map_path:=$HOME/Maps/nishishinjuku \
vehicle_model:=sample_vehicle \
sensor_model:=awsim_sensor_kit \
pose_source:=yabloc
```
[rosbag&map](https://docs.google.com/uc?export=download&id=17ppdMKi4IC8J_2-_9nyYv-LAfW0M1re5)
This rosbag link is quated from [Driving Log Replayer Tutorial](https://tier4.github.io/driving_log_replayer/quick_start/setup/#set-up-resources)
```
cd autoware/src/universe/autoware.universe/localization/yabloc
grep transient_local . -r 
```
then, the followings …
=> perf(yabloc_common): remove unnecessary pub/sub depth for transient_local

perception/autoware_traffic_light_visualization/config/traffic_light_visualization.param.yaml, perception/autoware_traffic_light_visualization/launch/traffic_light_roi_visualizer.launch.xml, perception/autoware_traffic_light_visualization/schema/traffic_light_visualization.schema.json, perception/autoware_traffic_light_visualization/src/traffic_light_roi_visualizer/node.cpp, perception/autoware_traffic_light_visualization/src/traffic_light_roi_visualizer/node.hpp
Adding an option to use normal image publisher instead of image transport in traffic light roi visualizer.
Originally, the traffic_light_roi_visualizer used image_transport to simultaneously publish raw images and compressed images (especially compressed images for internal logging).
1. `traffic_light_roi_visualizer` is usually running on nvidia/cuda devices.
2. `image_transport` by default uses CPU for image compression.
3. We have new packages to conduct image compression with GPU or NVEncoder.
Adding an optional argument in the launch file, with a default behavior of preserving the original codes.
If we provide with `use_image_transport=false`, it will not use image_tranport and just output raw images.
https://github.com/tier4/ros2_v4l2_camera/pull/14
For now, it was tested with bag …
=> feat(traffic_light_roi_visualizer): add an option to use normal publisher instead of image tranport in traffic light roi visualizer

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/config/static_obstacle_avoidance.param.yaml, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/data_structs.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/parameter_helper.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/scene.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/schema/static_obstacle_avoidance.schema.json, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/manager.cpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp
Previously the static obstacle avoidance continuously activated even when the shift point was force deactivated by human operation via RTC. 
This PR enables force deactivation when yield maneuver could be applied, and after a certain time (this is parameterized) the avoidance would reactivate.
Please merge [this PR](https://github.com/autowarefoundation/autoware_launch/pull/1101) first.
Before:
[Can't cancel](https://github.com/user-attachments/assets/53fb4361-9c8d-4b53-9f0e-6e00bbbfc9b1)
After:
[Duration time 2 second](https://github.com/user-attachments/assets/71f87f3e-0aa2-4904-83d2-349ed090b8d2)
[Duration time 10 second](https://github.com/user-attachments/assets/be528dad-42e8-4a6f-a4f4-483f0bbf03a0)
No degrade in [TIER IV internal scenario …
=> feat(static_obstacle_avoidance): force deactivation

perception/autoware_detected_object_validation/src/obstacle_pointcloud/obstacle_pointcloud_validator.hpp
This is a fix based on cppcheck functionConst warnings.
```
obstacle_pointcloud/obstacle_pointcloud_validator.hpp:68:46: style: inconclusive: Technically the member function 'autoware::detected_object_validation::obstacle_pointcloud::Validator::getDebugPointCloudWithinObject' can be const. [functionConst]
inline pcl::PointCloud<pcl::PointXYZ>::Ptr getDebugPointCloudWithinObject()
^
```
- Link
None.
None.
None.
=> fix(autoware_detected_object_validation): fix functionConst

system/system_diagnostic_monitor/config/autoware-psim.yaml
Enable emergency stop for AEB module
- Link
None.
None.
None.
=> feat(autonomous_emergency_braking): enable AEB emergency stop

perception/autoware_lidar_centerpoint/include/autoware/lidar_centerpoint/postprocess/postprocess_kernel.hpp, perception/autoware_lidar_centerpoint/lib/postprocess/postprocess_kernel.cu
CUDA 12.5 makes device vectors works with CUDA target only by default. Before this PR it works, but it shouldn't. As maintainer says _no Thrust header can be included in a host-only TU_.
- https://github.com/autowarefoundation/autoware.universe/issues/8219
None.
None.
None.
=> fix(autoware_lidar_centerpoint): place device vector in CUDA device system

perception/autoware_lidar_transfusion/include/autoware/lidar_transfusion/postprocess/postprocess_kernel.hpp, perception/autoware_lidar_transfusion/lib/postprocess/postprocess_kernel.cu
Same as https://github.com/autowarefoundation/autoware.universe/pull/8272
- https://github.com/autowarefoundation/autoware.universe/issues/8219
None.
None.
None.
=> fix(autoware_lidar_transfusion): place device vector in CUDA device system

planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/object_manager.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/object_manager.hpp, planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection.hpp
```
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/object_manager.cpp:76:58: style: inconclusive: Function 'initialize' argument 1 names different: declaration 'predicted_object' definition 'object'. [funcArgNamesDifferent]
const autoware_perception_msgs::msg::PredictedObject & object,
^
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/object_manager.cpp:77:40: style: inconclusive: Function 'initialize' argument 2 names different: declaration 'attention_lanelet_opt' definition 'attention_lanelet_opt_'. [funcArgNamesDifferent]
std::optional<lanelet::ConstLanelet> attention_lanelet_opt_,
^
planning/behavior_velocity_planner/autoware_behavior_velocity_inte …
```
=> fix(autoware_behavior_velocity_intersection_module): fix funcArgNamesDifferent

perception/autoware_ground_segmentation/src/scan_ground_filter/node.hpp
```
perception/autoware_ground_segmentation/src/scan_ground_filter/node.hpp:131:11: style: inconclusive: Technically the member function 'autoware::ground_segmentation::ScanGroundFilterComponent::PointsCentroid::getAverageHeight' can be const. [functionConst]
float getAverageHeight() { return height_avg; }
^
perception/autoware_ground_segmentation/src/scan_ground_filter/node.hpp:133:11: style: inconclusive: Technically the member function 'autoware::ground_segmentation::ScanGroundFilterComponent::PointsCentroid::getAverageRadius' can be const. [functionConst]
float getAverageRadius() { return radius_avg; }
^
perception/autoware_ground_segmentation/src/scan_ground_filter/node.hpp:135:11: style: inconclusive: Technically the member …
```
=> fix(autoware_ground_segmentation): fix functionConst

perception/autoware_radar_fusion_to_detected_object/src/include/radar_fusion_to_detected_object.hpp, perception/autoware_radar_fusion_to_detected_object/src/radar_fusion_to_detected_object.cpp
```
perception/autoware_radar_fusion_to_detected_object/src/include/radar_fusion_to_detected_object.hpp:101:23: style: inconclusive: Technically the member function 'autoware::radar_fusion_to_detected_object::RadarFusionToDetectedObject::estimateTwist' can be const. [functionConst]
TwistWithCovariance estimateTwist(
^
perception/autoware_radar_fusion_to_detected_object/src/include/radar_fusion_to_detected_object.hpp:103:8: style: inconclusive: Technically the member function 'autoware::radar_fusion_to_detected_object::RadarFusionToDetectedObject::isQualified' can be const. [functionConst]
bool isQualified(
^
```
- Link
None.
None.
None.
=> fix(autoware_radar_fusion_to_detected_object): fix functionConst

planning/autoware_freespace_planning_algorithms/include/autoware/freespace_planning_algorithms/astar_search.hpp, planning/autoware_freespace_planning_algorithms/src/astar_search.cpp
```
planning/autoware_freespace_planning_algorithms/src/astar_search.cpp:158:10: style: inconclusive: Technically the member function 'autoware::freespace_planning_algorithms::setCollisionFreeDistanceMap::CompareEntry::operator()' can be const. [functionConst]
bool operator()(const Entry & a, const Entry & b) { return a.second > b.second; }
^
```
- Link
None.
None.
None.
=> fix(autoware_freespace_planning_algorithms): fix functionConst

planning/behavior_velocity_planner/autoware_behavior_velocity_run_out_module/src/debug.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_run_out_module/src/debug.hpp
```
planning/behavior_velocity_planner/autoware_behavior_velocity_run_out_module/src/debug.hpp:129:40: style: inconclusive: Technically the member function 'autoware::behavior_velocity_planner::RunOutDebug::createVisualizationMarkerArrayFromDebugData' can be const. [functionConst]
visualization_msgs::msg::MarkerArray createVisualizationMarkerArrayFromDebugData(
^
```
- Link
None.
None.
None.
=> fix(autoware_behavior_velocity_run_out_module): fix functionConst

launch/tier4_perception_launch/launch/traffic_light_recognition/traffic_light_node_container.launch.py
Set `use_image_transport` in autoware.universe's launch. That value was made by [this PR](https://github.com/autowarefoundation/autoware.universe/pull/8157)
None
I checked this PR on DLR's traffic light recognition. (I could see `debug/roi`)
None.
None.
None.
=> fix(tier4_perception_launch): set `use_image_transport` in launch

planning/autoware_velocity_smoother/include/autoware/velocity_smoother/smoother/analytical_jerk_constrained_smoother/velocity_planning_utils.hpp, planning/autoware_velocity_smoother/src/smoother/analytical_jerk_constrained_smoother/velocity_planning_utils.cpp
```
planning/autoware_velocity_smoother/src/smoother/analytical_jerk_constrained_smoother/velocity_planning_utils.cpp:274:89: performance: Function parameter 'times' should be passed by const reference. [passedByValue]
double v0, double a0, double jerk_acc, double jerk_dec, int type, std::vector<double> times,
^
```
- Link
None.
None.
None.
=> fix(autoware_velocity_smoother): fix passedByValue

control/autoware_autonomous_emergency_braking/config/autonomous_emergency_braking.param.yaml, control/autoware_autonomous_emergency_braking/include/autoware/autonomous_emergency_braking/node.hpp, control/autoware_autonomous_emergency_braking/src/node.cpp
This PR separates AEB module markers into info markers (stop wall) and debug markers (rest), the intention is to enable the AEB stop wall being visible by default. 
Furthermore, this PR also adds the ability to toggle on and off autoware/state topic requirement for simulation, which can be useful to turn off when performing simulation tests。
- Link
PSim
None.
None.
None.
=> feat(autonomous_emergency_braking): add info marker and override for state

common/autoware_perception_rviz_plugin/include/autoware_perception_rviz_plugin/object_detection/object_polygon_detail.hpp, common/autoware_perception_rviz_plugin/src/object_detection/object_polygon_detail.cpp
```
common/autoware_perception_rviz_plugin/src/object_detection/object_polygon_detail.cpp:462:21: performance: Function parameter 'label' should be passed by const reference. [passedByValue]
const std::string label, const std_msgs::msg::ColorRGBA & color_rgba)
^
```
- Link
None.
None.
None.
=> fix(autoware_perception_rviz_plugin): fix passedByValue

planning/autoware_obstacle_stop_planner/src/adaptive_cruise_control.cpp, planning/autoware_obstacle_stop_planner/src/adaptive_cruise_control.hpp, planning/autoware_obstacle_stop_planner/src/planner_utils.cpp, planning/autoware_obstacle_stop_planner/src/planner_utils.hpp
```
planning/autoware_obstacle_stop_planner/src/adaptive_cruise_control.cpp:751:90: performance: Function parameter 'vel_que' should be passed by const reference. [passedByValue]
double AdaptiveCruiseController::getMedianVel(const std::vector<nav_msgs::msg::Odometry> vel_que)
^
planning/autoware_obstacle_stop_planner/src/adaptive_cruise_control.hpp:186:66: performance: Function parameter 'vel_que' should be passed by const reference. [passedByValue]
double getMedianVel(const std::vector<nav_msgs::msg::Odometry> vel_que);
^
planning/autoware_obstacle_stop_planner/src/planner_utils.hpp:125:55: performance: Function parameter 'stop_reason' should be passed by const reference. [passedByValue]
DiagnosticStatus makeStopReasonDiag(const …
```
=> fix(autoware_obstacle_stop_planner): fix passedByValue

control/autoware_pure_pursuit/src/autoware_pure_pursuit/autoware_pure_pursuit_lateral_controller.cpp, control/autoware_pure_pursuit/src/autoware_pure_pursuit_core/interpolate.cpp
This is a fix based on cppcheck `redundantInitialization` and `variableScope` warnings
```
control/autoware_pure_pursuit/src/autoware_pure_pursuit/autoware_pure_pursuit_lateral_controller.cpp:455:24: style: Redundant initialization for 'lookahead_distance'. The initialized value is overwritten before it is read. [redundantInitialization]
lookahead_distance = calcLookaheadDistance(
^
control/autoware_pure_pursuit/src/autoware_pure_pursuit/autoware_pure_pursuit_lateral_controller.cpp:453:29: note: lookahead_distance is initialized
double lookahead_distance = min_lookahead_distance;
^
control/autoware_pure_pursuit/src/autoware_pure_pursuit/autoware_pure_pursuit_lateral_controller.cpp:455:24: note: lookahead_distance is overwritten
lookahead_distance = calcLookaheadDistance(
^ …
```
=> fix(autoware_pure_pursuit): fix redundantInitialization redundantInitialization

system/diagnostic_graph_aggregator/src/common/graph/graph.cpp, system/diagnostic_graph_aggregator/src/common/graph/graph.hpp
```
system/diagnostic_graph_aggregator/src/common/graph/graph.hpp:34:8: style: inconclusive: Technically the member function 'diagnostic_graph_aggregator::Graph::update' can be const. [functionConst]
void update(const rclcpp::Time & stamp);
^
```
- Link
None.
None.
None.
=> fix(diagnostic_graph_aggregator): fix functionConst

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/README.md, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/config/lane_change.param.yaml, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/data_structs.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/utils.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/manager.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp
⚠️ Require this PR to be merged together (https://github.com/autowarefoundation/autoware_launch/pull/1087)
Current lane change finish judge requires both of the following condition
1. Ego vehicle drive pass the end pose, and
2. Ego vehicle is near target lane center line.
However, in situation when lc is running simultaneously with other module especially avoidance module, it will be difficult to pass both condition at the same time. Furthermore, passing both situation is unnecessary.
Before PR, the following simulation will not cause lane change to complete. The video is after PR is made.
https://github.com/autowarefoundation/autoware.universe/assets/93502286/37a1684d-c883-4b39-ad53-181859d6f041
- Link
None.
None.
| Change type   | Parameter Name | Type     | Default …
=> fix(lane_change): relax finish judge

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/README.md, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/config/lane_change.param.yaml, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/data_structs.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/manager.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp
Available RSS parameters is too conservative for parked vehicle.
In this PR, RSS parameters for parked vehicle is separated to relax the criteria.
https://github.com/autowarefoundation/autoware_launch/pull/1104
1. With PSIM
2. [TIER IV internal link](https://evaluation.tier4.jp/evaluation/reports/b68f2a5a-fea3-5be2-bffc-bc9cf05b3e6f?project_id=prd_jt)
None.
None.
|:--------------|:---------------|:---------|:--------------|:------------------|
| Added | `safety_check.parked.expected_front_deceleration`    | `double` | `-1.0`         | The front object's maximum deceleration when the front vehicle perform sudden braking. |
| Added | `safety_check.parked.expected_rear_deceleration`   | `double` | `-2.0` …
=> feat(lane_change): use different rss param to deal with parked vehicle

sensing/autoware_pointcloud_preprocessor/src/downsample_filter/robin_hood.h
```
sensing/pointcloud_preprocessor/src/downsample_filter/robin_hood.h:1935:40: performance: inconclusive: Function parameter 'position' should be passed by const reference. [passedByValue]
iterator emplace_hint(const_iterator position, Args &&... args)
^
sensing/pointcloud_preprocessor/src/downsample_filter/robin_hood.h:1954:39: performance: inconclusive: Function parameter 'hint' should be passed by const reference. [passedByValue]
iterator try_emplace(const_iterator hint, const key_type & key, Args &&... args)
^
sensing/pointcloud_preprocessor/src/downsample_filter/robin_hood.h:1961:39: performance: inconclusive: Function parameter 'hint' should be passed by const reference. [passedByValue]
iterator try_emplace(const_iterator hint, …
```
=> fix(autoware_pointcloud_preprocessor): fix passedByValue

perception/autoware_probabilistic_occupancy_grid_map/lib/fusion_policy/fusion_policy.cpp
```
perception/autoware_probabilistic_occupancy_grid_map/lib/fusion_policy/fusion_policy.cpp:205:10: style: inconclusive: Technically the member function 'autoware::occupancy_grid_map::fusion_policy::dempster_shafer_fusion::dempsterShaferOccupancy::calcK' can be const. [functionConst]
double calcK(const dempsterShaferOccupancy & other)
^
perception/autoware_probabilistic_occupancy_grid_map/lib/fusion_policy/fusion_policy.cpp:210:10: style: inconclusive: Technically the member function 'autoware::occupancy_grid_map::fusion_policy::dempster_shafer_fusion::dempsterShaferOccupancy::calcOccupied' can be const. [functionConst]
double calcOccupied(const dempsterShaferOccupancy & other)
^ …
```
=> fix(autoware_probabilistic_occupancy_grid_map): fix functionConst

sensing/autoware_pointcloud_preprocessor/src/downsample_filter/robin_hood.h
```
sensing/autoware_pointcloud_preprocessor/src/downsample_filter/robin_hood.h:1137:10: style: inconclusive: Technically the member function 'robin_hood::detail::Table::DataNode::destroyDoNotDeallocate' can be const. [functionConst]
void destroyDoNotDeallocate() noexcept { mData->~value_type(); }
^
```
- Link
None.
None.
None.
=> fix(autoware_pointcloud_preprocessor): fix functionConst

control/autoware_vehicle_cmd_gate/src/marker_helper.hpp, control/autoware_vehicle_cmd_gate/src/vehicle_cmd_filter.cpp, control/autoware_vehicle_cmd_gate/src/vehicle_cmd_filter.hpp
This is a fix based on cppcheck passedByValue warnings.
```
control/autoware_vehicle_cmd_gate/src/vehicle_cmd_filter.cpp:43:47: performance: Function parameter 'v' should be passed by const reference. [passedByValue]
void VehicleCmdFilter::setSteerLim(LimitArray v)
^
control/autoware_vehicle_cmd_gate/src/vehicle_cmd_filter.cpp:49:51: performance: Function parameter 'v' should be passed by const reference. [passedByValue]
void VehicleCmdFilter::setSteerRateLim(LimitArray v)
^
control/autoware_vehicle_cmd_gate/src/vehicle_cmd_filter.cpp:55:48: performance: Function parameter 'v' should be passed by const reference. [passedByValue]
void VehicleCmdFilter::setLonAccLim(LimitArray v)
^
control/autoware_vehicle_cmd_gate/src/vehicle_cmd_filter.cpp:61:49: performance: Function parameter 'v' should …
```
=> fix(autoware_vehicle_cmd_gate): fix passedByValue

control/autoware_vehicle_cmd_gate/src/vehicle_cmd_filter.cpp
```
control/autoware_vehicle_cmd_gate/src/vehicle_cmd_filter.cpp:23:19: warning: Member variable 'VehicleCmdFilter::param_' is not initialized in the constructor. [uninitMemberVar]
VehicleCmdFilter::VehicleCmdFilter()
^
```
- Link
None.
None.
None.
=> fix(autoware_vehicle_cmd_gate): fix uninitMemberVar

planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/src/scene.cpp
```
planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/src/scene.cpp:39:22: warning: Member variable 'DetectionAreaModule::debug_data_' is not initialized in the constructor. [uninitMemberVar]
DetectionAreaModule::DetectionAreaModule(
^
```
- Link
None.
None.
None.
=> fix(autoware_behavior_velocity_detection_area_module): fix uninitMemberVar

planning/behavior_velocity_planner/autoware_behavior_velocity_speed_bump_module/src/scene.cpp
```
planning/behavior_velocity_planner/autoware_behavior_velocity_speed_bump_module/src/scene.cpp:30:18: warning: Member variable 'SpeedBumpModule::debug_data_' is not initialized in the constructor. [uninitMemberVar]
SpeedBumpModule::SpeedBumpModule(
^
```
- Link
None.
None.
None.
=> fix(autoware_behavior_velocity_speed_bump_module): fix uninitMemberVar

planning/behavior_velocity_planner/autoware_behavior_velocity_stop_line_module/src/scene.cpp
```
planning/behavior_velocity_planner/autoware_behavior_velocity_stop_line_module/src/scene.cpp:29:17: warning: Member variable 'StopLineModule::debug_data_' is not initialized in the constructor. [uninitMemberVar]
StopLineModule::StopLineModule(
^
```
- Link
None.
None.
None.
=> fix(autoware_behavior_velocity_stop_line_module): fix uninitMemberVar

planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/scene.cpp
```
planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/scene.cpp:164:21: warning: Member variable 'TrafficLightModule::debug_data_' is not initialized in the constructor. [uninitMemberVar]
TrafficLightModule::TrafficLightModule(
^
```
- Link
None.
None.
None.
=> fix(autoware_behavior_velocity_traffic_light_module): fix uninitMemberVar

planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/object_manager.hpp
```
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/object_manager.hpp:251:3: style: inconclusive: Technically the member function 'autoware::behavior_velocity_planner::ObjectInfoManager::getObjectsMap' can be const. [functionConst]
getObjectsMap()
^
```
- Link
None.
None.
None.
=> fix(autoware_behavior_velocity_intersection_module): fix functionConst

planning/autoware_obstacle_stop_planner/src/adaptive_cruise_control.cpp, planning/autoware_obstacle_stop_planner/src/adaptive_cruise_control.hpp
```
planning/autoware_obstacle_stop_planner/src/adaptive_cruise_control.hpp:207:10: style: inconclusive: Technically the member function 'autoware::motion_planning::AdaptiveCruiseController::calcTargetVelocity_P' can be const. [functionConst]
double calcTargetVelocity_P(const double target_dist, const double current_dist);
^
```
- Link
None.
None.
None.
=> fix(autoware_obstacle_stop_planner): fix functionConst

planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/src/parameters.hpp
```
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/src/parameters.hpp:55:3: warning: Member variable 'ObstacleParameters::filter_envelope' is not initialized in the constructor. [uninitMemberVar]
ObstacleParameters() = default;
^
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/src/parameters.hpp:55:3: warning: Member variable 'ObstacleParameters::ignore_on_path' is not initialized in the constructor. [uninitMemberVar]
ObstacleParameters() = default;
^
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/src/parameters.hpp:55:3: warning: Member variable 'ObstacleParameters::ignore_extra_distance' is not …
```
=> fix(autoware_motion_velocity_obstacle_velocity_limiter_module): fix uninitMemberVar

system/diagnostic_graph_aggregator/src/common/graph/config.hpp
```
system/diagnostic_graph_aggregator/src/common/graph/config.hpp:51:12: warning: Member variable 'UnitConfig::index' is not initialized in the constructor. [uninitMemberVar]
explicit UnitConfig(const TreeData & data) : data(data) {}
^
```
- Link
None.
None.
None.
=> fix(diagnostic_graph_aggregator): fix uninitMemberVar

perception/autoware_probabilistic_occupancy_grid_map/lib/costmap_2d/occupancy_grid_map_fixed.cpp
```
perception/autoware_probabilistic_occupancy_grid_map/lib/costmap_2d/occupancy_grid_map_fixed.cpp:79:5: warning: Member variable 'BinInfo::range' is not initialized in the constructor. [uninitMemberVar]
BinInfo() = default;
^
perception/autoware_probabilistic_occupancy_grid_map/lib/costmap_2d/occupancy_grid_map_fixed.cpp:79:5: warning: Member variable 'BinInfo::wx' is not initialized in the constructor. [uninitMemberVar]
BinInfo() = default;
^
perception/autoware_probabilistic_occupancy_grid_map/lib/costmap_2d/occupancy_grid_map_fixed.cpp:79:5: warning: Member variable 'BinInfo::wy' is not initialized in the constructor. [uninitMemberVar]
BinInfo() = default;
^
```
- Link
None.
None.
None.
=> fix(autoware_probabilistic_occupancy_grid_map): fix uninitMemberVar

perception/autoware_traffic_light_visualization/src/traffic_light_map_visualizer/node.cpp
```
perception/traffic_light_visualization/src/traffic_light_map_visualizer/node.cpp:43:52: performance: Function parameter 'attr_str' should be passed by const reference. [passedByValue]
const lanelet::ConstPoint3d p, const std::string attr_str, const std::string value_str)
^
perception/traffic_light_visualization/src/traffic_light_map_visualizer/node.cpp:43:80: performance: Function parameter 'value_str' should be passed by const reference. [passedByValue]
const lanelet::ConstPoint3d p, const std::string attr_str, const std::string value_str)
^
perception/traffic_light_visualization/src/traffic_light_map_visualizer/node.cpp:54:88: performance: Function parameter 'ns' should be passed by const reference. [passedByValue] …
```
=> fix(autoware_traffic_light_visualization): fix passedByValue

perception/autoware_multi_object_tracker/src/multi_object_tracker_node.cpp, perception/autoware_multi_object_tracker/src/multi_object_tracker_node.hpp
Revert logic of latency reduction. 
If CPU usage is high, the process could not be triggered in time. As result, the output is less than incoming messages. 
The main process and message publish is back to periodic timer trigger.
revert of https://github.com/autowarefoundation/autoware.universe/pull/6710
- Link
[TIER IV INTERNAL](https://evaluation.tier4.jp/evaluation/reports/8c63904c-81d3-5e5a-a026-df23d6cbef64?project_id=prd_jt)
None.
None.
None.
=> fix(autoware_multi_object_tracker): revert latency reduction logic and bring back to timer trigger

.github/workflows/build-and-test-daily.yaml, .github/workflows/build-and-test-differential.yaml, .github/workflows/build-and-test.yaml
This modifies build-and-test-differential workflow to be running on self-hosted machines for cuda containers in order to avoid disk space issue.
[- Link
](https://github.com/autowarefoundation/autoware.universe/issues/8328)
I'm testing within CI against this PR here: https://github.com/autowarefoundation/autoware.universe/pull/8329.
None.
None.
None.
=> ci: use self-hosted machine for build-and-test-differential-cuda

perception/autoware_ground_segmentation/src/scan_ground_filter/node.hpp
```
perception/autoware_ground_segmentation/src/scan_ground_filter/node.hpp:93:5: warning: Member variable 'PointsCentroid::height_max' is not initialized in the constructor. [uninitMemberVar]
PointsCentroid()
^
perception/autoware_ground_segmentation/src/scan_ground_filter/node.hpp:93:5: warning: Member variable 'PointsCentroid::height_min' is not initialized in the constructor. [uninitMemberVar]
PointsCentroid()
^
perception/autoware_ground_segmentation/src/scan_ground_filter/node.hpp:93:5: warning: Member variable 'PointsCentroid::grid_id' is not initialized in the constructor. [uninitMemberVar]
PointsCentroid()
^
```
- Link
None.
None.
None.
=> fix(autoware_ground_segmentation): fix uninitMemberVar

perception/autoware_compare_map_segmentation/src/voxel_grid_map_loader/voxel_grid_map_loader.hpp
```
perception/autoware_compare_map_segmentation/src/voxel_grid_map_loader/voxel_grid_map_loader.cpp:19:21: warning: Member variable 'VoxelGridMapLoader::voxel_leaf_size_z_' is not initialized in the constructor. [uninitMemberVar]
VoxelGridMapLoader::VoxelGridMapLoader(
^
```
- Link
None.
None.
None.
=> fix(autoware_compare_map_segmentation): fix uninitMemberVar

planning/autoware_freespace_planner/test/test_freespace_planner_node_interface.cpp
Some tests in the `autoware_freespace_planner` package are randomly failing (both in the CI and locally).
This PR disable them so that they do not bother other PRs. A proper fix will be made later.
- Link
None.
None.
None.
=> fix(freespace_planner): disable randomly failing tests

vehicle/autoware_accel_brake_map_calibrator/src/accel_brake_map_calibrator_node.cpp
```
vehicle/autoware_accel_brake_map_calibrator/src/accel_brake_map_calibrator_node.cpp:1335:11: style: Redundant initialization for 'level'. The initialized value is overwritten before it is read. [redundantInitialization]
level = DiagStatus::OK;
^
vehicle/autoware_accel_brake_map_calibrator/src/accel_brake_map_calibrator_node.cpp:1329:16: note: level is initialized
int8_t level = DiagStatus::OK;
^
vehicle/autoware_accel_brake_map_calibrator/src/accel_brake_map_calibrator_node.cpp:1335:11: note: level is overwritten
level = DiagStatus::OK;
^
```
- Link
None.
None.
None.
=> fix(autoware_accel_brake_map_calibrator): fix redundantInitialization

.cppcheck_suppressions
remove `redundantInitialization`
See cppcheck-daily https://github.com/autowarefoundation/autoware.universe/actions/runs/10258481893
None.
None.
None.
=> chore(ci): remove unnecessary redundantInitialization cppcheck suppression

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/shift_line_generator.cpp
```
updateData: 1535.61 [ms]                                                                                                                                                                                                                                                                                                                                                                                                        
├── fillFundamentalData: 3.39 [ms] …
```
=> fix(static_obstacle_avoidance): remove invalid small shift lines

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp
I found a bug: this module generates avoidance path for stopped vehicle even if there is opposite lane. In this case, we assume that it's NOT a parked vehicle and ego doesn't have to avoid it.
In this PR, I fixed the logic so that this module can check not only same direction lanes but also opposite lanes.
- Link
None.
None.
None.
=> fix(static_obstacle_avoidance): check opposite lane

codecov.yaml
Currently, Codecov displays the coverage of test files, but I believe the coverage of the tests themselves is unnecessary. With this setting, we can exclude files under test/** from the coverage report.
Same settings is tested in [here](https://github.com/yhisaki/ros2-unit-test-sample).
None.
None.
None.
=> chore(codecov): ignore test directory in codecov

perception/autoware_traffic_light_occlusion_predictor/src/occlusion_predictor.cpp, perception/autoware_traffic_light_occlusion_predictor/src/occlusion_predictor.hpp
```
perception/autoware_traffic_light_occlusion_predictor/src/occlusion_predictor.hpp:74:8: style: inconclusive: Technically the member function 'autoware::traffic_light::CloudOcclusionPredictor::filterCloud' can be const. [functionConst]
void filterCloud(
^
```
- Link
None.
None.
None.
=> fix(autoware_traffic_light_occlusion_predictor): fix functionConst

.github/CODEOWNERS, common/.pages, common/autoware_path_distance_calculator/CMakeLists.txt, common/autoware_path_distance_calculator/Readme.md, common/autoware_path_distance_calculator/launch/path_distance_calculator.launch.xml, common/autoware_path_distance_calculator/package.xml, common/autoware_path_distance_calculator/src/path_distance_calculator.cpp, common/autoware_path_distance_calculator/src/path_distance_calculator.hpp, launch/tier4_autoware_api_launch/launch/deprecated_api.launch.xml, launch/tier4_autoware_api_launch/package.xml
prefix package and namespace with autoware
None.
None.
None.
=> refactor(autoware_path_distance_calculator): prefix package and namespace with autoware

common/autoware_path_distance_calculator/launch/path_distance_calculator.launch.xml
Related to https://github.com/autowarefoundation/autoware.universe/pull/8085.
This PR added autoware prefix to the executable in the launcher.
- Link
I confirmed the launcher works.
- Before
```shell
$ ros2 launch autoware_path_distance_calculator path_distance_calculator.launch.xml 
[INFO] [launch]: All log files can be found below /home/ktro2828/.ros/log/2024-08-07-09-15-56-427441-ktro2828-desktop-1632096
[ERROR] [launch]: Caught exception in launch (see debug for traceback): executable 'path_distance_calculator_node' not found on the libexec directory '/home/ktro2828/workspace/pilot-auto/install/autoware_path_distance_calculator/lib/autoware_path_distance_calculator' 
```
- After
```shell
$ ros2 launch …
```
=> fix: add autoware prefix

perception/autoware_traffic_light_classifier/src/traffic_light_classifier_node.cpp
Even the previous fix https://github.com/autowarefoundation/autoware.universe/pull/7461, similar issue has occurred.
```
[component_container_mt-61]   what():  OpenCV(4.5.4) ./modules/imgproc/src/resize.cpp:4051: error: (-215:Assertion failed) !ssize.empty() in function 'resize'
[component_container_mt-61]   what():  OpenCV(4.5.4) ./modules/imgproc/src/resize.cpp:4051: error: (-215:Assertion failed) !ssize.empty() in function 'resize'
[component_container_mt-61] 
[component_container_mt-61] 
[component_container_mt-61] *** Aborted at 1718866324 (unix time) try "date -d @1718866324" if you are using GNU date ***
[component_container_mt-61] terminate called recursively
[component_container_mt-61] terminate called recursively
[component_container_mt-61] terminate called recursively …
```
=> fix(traffic_light_classifier): fix zero size roi bug

control/autoware_vehicle_cmd_gate/src/adapi_pause_interface.cpp, control/autoware_vehicle_cmd_gate/src/adapi_pause_interface.hpp, control/autoware_vehicle_cmd_gate/src/vehicle_cmd_filter.hpp
This is a fix based on cppcheck constFunction warnings.
```
adapi_pause_interface.hpp:38:8: style: inconclusive: Technically the member function 'autoware::vehicle_cmd_gate::AdapiPauseInterface::is_paused' can be const. [functionConst]
bool is_paused();
^
vehicle_cmd_filter.hpp:78:11: style: inconclusive: Technically the member function 'autoware::vehicle_cmd_gate::VehicleCmdFilter::getPrevCmd' can be const. [functionConst]
Control getPrevCmd() { return prev_cmd_; }
^
```
- Link
None.
None.
None.
=> fix(autoware_vehicle_cmd_gate): fix functionConst

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/CMakeLists.txt, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/calculation.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/calculation.cpp
Lane change module evaluates the distance from preparation start to lane changing end at later phase.
Hence, if prepare path's lengths exceed distance to lane change terminal start, there will be unnecessary checks and computation before the evaluation.
This PR aims to fix this by skipping path computation if the prepare segment length exceed ego current distance to terminal start.
This PR also add `computation.hpp/cpp` to avoid `utils.hpp/cpp` file from having too many number of lines 
```
[DEBUG 1722854092.480406897] [lane_change.NORMAL]: Reject: Prepare length exceed distance to terminal start. prep_len: 8.00000,  ego dist to terminal start: 7.83372 (getLaneChangePaths() at /home/zulfaqar/autoware/pilot-auto/src/autoware/universe/planning/behavior_path_planner/autoware_behavior_path_lan …
```
=> fix(lane_change): skip path computation if len exceed dist to terminal start

perception/autoware_multi_object_tracker/src/debugger/debugger.cpp, perception/autoware_multi_object_tracker/src/debugger/debugger.hpp, perception/autoware_multi_object_tracker/src/processor/input_manager.hpp
```
perception/autoware_multi_object_tracker/src/debugger/debugger.hpp:94:8: style: inconclusive: Technically the member function 'autoware::multi_object_tracker::TrackerDebugger::checkDelay' can be const. [functionConst]
void checkDelay(diagnostic_updater::DiagnosticStatusWrapper & stat);
^
perception/autoware_multi_object_tracker/src/processor/input_manager.hpp:63:8: style: inconclusive: Technically the member function 'autoware::multi_object_tracker::InputStream::getNames' can be const. [functionConst]
void getNames(std::string & long_name, std::string & short_name)
^
```
- Link
None.
None.
None.
=> fix(autoware_multi_object_tracker): fix functionConst

localization/autoware_twist2accel/src/twist2accel.hpp
```
localization/autoware_twist2accel/src/twist2accel.cpp:29:54: style: inconclusive: Function 'Twist2Accel' argument 1 names different: declaration 'options' definition 'node_options'. [funcArgNamesDifferent]
Twist2Accel::Twist2Accel(const rclcpp::NodeOptions & node_options)
^
```
- Link
None.
None.
None.
=> fix(autoware_twist2accel): fix funcArgNamesDifferent

perception/autoware_traffic_light_classifier/src/classifier/cnn_classifier.cpp, perception/autoware_traffic_light_classifier/src/classifier/cnn_classifier.hpp
```
perception/autoware_traffic_light_classifier/src/classifier/cnn_classifier.cpp:198:52: performance: Function parameter 'label' should be passed by const reference. [passedByValue]
bool CNNClassifier::isColorLabel(const std::string label)
^
```
- Link
None.
None.
None.
=> fix(autoware_traffic_light_classifier): fix passedByValue

.cppcheck_suppressions
removed `funcArgNamesDifferent` and `passedByValue` suppressions
cppcheck-daily CI https://github.com/autowarefoundation/autoware.universe/actions/runs/10293740093/job/28490598879
None.
None.
None.
=> chore(ci): remove funcArgNamesDifferent and passedByValue suppressions

perception/autoware_map_based_prediction/include/map_based_prediction/map_based_prediction_node.hpp, perception/autoware_map_based_prediction/src/map_based_prediction_node.cpp
instead of searching from all LineStrings, create an articulated fence layer
https://star4.slack.com/archives/C03S84LDJGG/p1723084187292029
worst processing time for a rosbag changed from 
- 21.59ms, 23.53ms, 26.68ms
to
- 21.86ms, 22.16ms, 23.39ms
None.
None.
None.
=> perf(map_based_prediction): create a fence LineString layer and use rtree query

perception/autoware_map_based_prediction/src/map_based_prediction_node.cpp
CPU usage of the map based prediction is high.
One of the reason is to using spline interpolation in predicted path conversion.
1. using linear interpolation
2. simplify quaternion calculation only for yaw
In the worst cases, `convertPathType` is increasing. Therefore, this part should be improved.
- Link
Another performance improvement PR https://github.com/autowarefoundation/autoware.universe/pull/8388
Tested in a local environment and the relative performance was measured using modified [autoware_debug_tool](https://github.com/autowarefoundation/autoware_tools/pull/92).
With the linear interpolation, the average time is reduced from 0.41 to 0.28 [ms] avg..
* before
```
100.00% objectsCallback: total 110.49 [ms], avg. 110.49 [ms], run count: 1
├── 0.01% …
```
=> perf(map_based_prediction): use linear interpolation for path conversion

perception/autoware_traffic_light_classifier/src/traffic_light_classifier_node.cpp
This PR solves the problem that the traffic light system monitor outputs WARNING.
The WARNING was caused by the node not always outputting a topic.
https://github.com/autowarefoundation/autoware.universe/pull/7608
Tested on actual vehicle
None.
None.
None.
=> fix(traffic_light_classifier): fix traffic light monitor warning

perception/autoware_elevation_map_loader/src/elevation_map_loader_node.hpp
This is a fix based on cppcheck functionConst warnings.
```
elevation_map_loader_node.hpp:48:8: style: inconclusive: Technically the member function 'autoware::elevation_map_loader::DataManager::isInitialized' can be const. [functionConst]
bool isInitialized()
^
```
- Link
None.
None.
None.
=> fix(autoware_elevation_map_loader): fix functionConst

perception/autoware_map_based_prediction/src/map_based_prediction_node.cpp
This reverts commit 147403f1765346be9c5a3273552d86133298a899.
- Link
https://github.com/autowarefoundation/autoware.universe/pull/8400
None.
None.
None.
=> revert(map_based_prediction): use linear interpolation for path conversion

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/data_structs.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/utils.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp
Rework lane changing length check.
Current method is a little bit confusing, since we're using s_start and s_end.
This method aims to help improve the readability and reuse calculate distance to terminal end function.
Also current method doesn't check if the lane change end point is in between target neighbor, and this potentially caused lane changing path to be longer than expected and may cause unnecessary checks as well.
This PR methods ensures that the lane changing distance remains sufficient and the lane changing path remains in between target neighbor.
Required PR: https://github.com/autowarefoundation/autoware.universe/pull/8359
- Link
using PSIM
None.
None.
None.
=> fix(lane_change): skip generating path if lane changing path is too long

planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_safety_checker/objects_filtering.cpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp
Since the process of yaw deviation check is heavy, I fixed it in order to check object within/without target lane first.
The `postProcess()` function is automatically called in **[this](https://github.com/autowarefoundation/autoware.universe/blob/7f96352a42062a97090acc27d40a6377e3513dfc/planning/behavior_path_planner/autoware_behavior_path_planner/src/planner_manager.cpp#L749)** line.
Don't use heavy process `calcSignedArcLength()`.
- Link
None.
None.
None.
=> perf(static_obstacle_avoidance): improve logic to reduce computational cost

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/config/lane_change.param.yaml, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/data_structs.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/manager.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp
**Current behavior:**
The number of lane change  samples increases as ego vehicle approaches terminal start, due to the greater number of longitudinal acceleration samples.
The increase in lane change samples also leads to higher computational costs, as each sample generates a candidate path and undergoes various validations.
**Proposed behavior:**
Each lane change sample is computed based on the corresponding longitudinal acceleration sample.
As the ego vehicle approaches the terminal start, the distance differences between each lane change sample become smaller. 
In this case, if the distance difference is small and the previous path is unsafe, it's likely that the new path with a small distance difference will also be unsafe. Therefore, it is feasible to skip generating paths with …
=> fix(lane_change): skip generating path if longitudinal distance difference is less than threshold

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/scene.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/base_class.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/data_structs.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/debug_structs.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/markers.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/utils.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/interface.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/markers.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp
Separate lane change target objects to front and back in the filtering function  to avoid redoing the front/back check in the isLaneChangePathSafe function
- Link
None.
None.
None.
=> refactor(lane_change): separate leading and trailing objects

perception/autoware_map_based_prediction/src/map_based_prediction_node.cpp
improve orientation calculation and resample converted path with linear interpolation
Simplify the calculation of the orientation for each pose in the convertPathType function by directly calculating the sine and cosine of half the yaw angle. This improves efficiency and readability. Also, improve the resampling of the converted path by using linear interpolation for better performance.
- Link
original https://github.com/autowarefoundation/autoware.universe/pull/8400
revert of original https://github.com/autowarefoundation/autoware.universe/pull/8417
Tested under [TIER IV Cloud](https://evaluation.tier4.jp/evaluation/reports/968c582d-9b4f-521c-b3cc-6a9252af1720?project_id=prd_jt)
None.
None.
None.
=> perf(autoware_map_based_prediction): improve orientation calculation and resample converted path

planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/filter_predicted_objects.cpp, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/filter_predicted_objects.hpp, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/lanelets_selection.cpp, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_module.cpp, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/types.hpp, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/test/test_filter_predicted_objects.cpp
Improve performance of the out_of_lane module by using rtree for efficient spatial queries.
Psim and rosbag replay.
None.
None.
None.
=> perf(out_of_lane): use rtree to get stop lines and trajectory lanelets

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp
Add a rule to avoid merging/deviating vehicle on adjacent lane. If the overhang distance is less than threshold, this module avoids merging/deviationg vehicle.
- Link
None.
None.
None.
=> fix(static_obstacle_avoidance): change avoidance condition

control/autoware_lane_departure_checker/include/autoware/lane_departure_checker/lane_departure_checker.hpp
related to https://github.com/autowarefoundation/autoware.universe/pull/8449, better to set initial value for when forgetting set in user side.
- Link
none
None.
None.
None.
=> fix(lane_departure_checker): fix uninitialized variables

.cppcheck_suppressions
Removed `functionConst` and `unusedStructMember`
cppcheck-daily: https://github.com/autowarefoundation/autoware.universe/actions/runs/10379234302/job/28737042332
None.
None.
None.
=> ci(cppcheck): remove unnecessary suppressions

perception/autoware_map_based_prediction/src/map_based_prediction_node.cpp
improve performance by optimizing transform loading part.
1. remove unused transforms
2. make transform loading only when it is necessary, avoid waiting time for tf
https://github.com/autowarefoundation/autoware.universe/pull/8388 
https://github.com/autowarefoundation/autoware.universe/pull/8400 
https://github.com/autowarefoundation/autoware.universe/pull/8403 
https://github.com/autowarefoundation/autoware.universe/pull/8406
- Link
Tested under a local environment.
improved runtime (average)
15.97 [ms] -> 15.24 [ms]
None.
None.
None.
=> perf(map_based_prediction): improve world to map transform calculation

launch/tier4_simulator_launch/launch/simulator.launch.xml
This is the PR to follow up on the launch side PR https://github.com/autowarefoundation/autoware_launch/pull/1106.
For more details, please see the launch PR
This PR is a part of the following issue.
https://github.com/autowarefoundation/autoware_launch/issues/1100
psim and scenario_sim 
None.
None.
None.
=> feat(psim)!: change a setting parameter type from bool to string

sensing/autoware_pointcloud_preprocessor/src/distortion_corrector/distortion_corrector.cpp
```
sensing/autoware_pointcloud_preprocessor/src/distortion_corrector/distortion_corrector.cpp:222:10: style: The scope of the variable 'global_point_stamp' can be reduced. [variableScope]
double global_point_stamp;
^
```
- Link
None.
None.
None.
=> fix(autoware_pointcloud_preprocessor): fix variableScope

perception/autoware_map_based_prediction/src/map_based_prediction_node.cpp
Fix bug in autoware_map_based_prediction. Details are described in [internal slack](https://star4.slack.com/archives/C03QW0GU6P7/p1723603495769929).
- Link
Tested on psim.
None.
None.
None.
=> fix(autoware_map_based_prediction): use surrounding_crosswalks instead of external_surrounding_crosswalks

perception/autoware_map_based_prediction/config/map_based_prediction.param.yaml, perception/autoware_map_based_prediction/include/map_based_prediction/map_based_prediction_node.hpp, perception/autoware_map_based_prediction/include/map_based_prediction/path_generator.hpp, perception/autoware_map_based_prediction/src/map_based_prediction_node.cpp, perception/autoware_map_based_prediction/src/path_generator.cpp
1. Implementing the time keeper by pointer.
a. Can be implemented to sub-module by passing the pointer of the time keeper
b. enable or disable the measurement
2. Add configuration for on/off debug message processes
a. If the debugging process is heavy/not-needed, it can be turned off.
This PR do not contain any logic change.
- Link
This PR should be merged first. 
https://github.com/autowarefoundation/autoware_launch/pull/1118
Tested in a local recompute environment. 
None.
None.
None.
=> refactor(autoware_map_based_prediction): map based pred time keeper ptr

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp
Insert stop point while lane change returns prev_module_output in ModuleStatus::RUNNING mode.
No stop point is inserted and ego failed to decelerate/stop
https://github.com/user-attachments/assets/53d8815e-fe1c-4c94-a426-7fa32d487ca3
Stop point is inserted and ego able to decelerate
https://github.com/user-attachments/assets/5ee3464e-d9e2-4f62-bd5e-45378c5b1aba
- [TIER IV internal link](https://star4.slack.com/archives/C074CCKN35E/p1723601310650599)
None.
None.
None.
=> fix(lane_change): fix invalid doesn't have stop point

perception/autoware_map_based_prediction/src/map_based_prediction_node.cpp
Multiple places were found where `boost::geometry::within(...)` was used immediately after `auto [dist, lanelet] = lanelet::geometry::findNearest(...)` (especially in places using `withinLanelet`). However, since `dist` being 0 and `boost::geometry::within(...)` returning true are equivalent, the redundant processing was eliminated.
https://wandbox.org/permlink/u3KhRExZACGjSf5Z
This change slightly improves performance.
*before*
```
objectsCallback: total 7.75 [ms], avg. 7.75 [ms], run count: 1
├── trafficSignalsCallback: total 0.00 [ms], avg. 0.00 [ms], run count: 1
├── removeStaleTrafficLightInfo: total 0.00 [ms], avg. 0.00 [ms], run count: 1
├── updateObjectData: total 0.00 [ms], avg. 0.00 [ms], run count: 19
├── getCurrentLanelets: total 1.17 [ms], avg. …
```
=> perf(autoware_map_based_prediction): enhance speed by removing unnecessary calculation

perception/autoware_multi_object_tracker/src/multi_object_tracker_node.cpp
Fix a bug that the object is not published when the option `enable_delay_compensation` is false.
Caused by PR https://github.com/tier4/autoware.universe/pull/1436
- Link
None.
None.
None.
=> fix(autoware_multi_object_tracker): enable trigger publish when delay_compensation is false

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/scene.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/base_class.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/calculation.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/interface.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/calculation.cpp
Lane change module will cancel unsafe path unless ego has passed terminal start point.
However, as ego vehicle approaching terminal end, cancelling lane change path might result in difficulties in re-attempting lane change.
This PR aims to fix this, by not cancelling lane change if ego has already near terminal start.
None
- Link
None.
None.
None.
=> fix(lane_change): do not cancel when approaching terminal start

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp
When filtering  lane change target objects, the objects that is close to target lanes' bound is considered as target objects. This is to prevent ego from lane change too near to the object. However, if the object is not moving, we don't really need to consider them as the target object.
https://github.com/user-attachments/assets/b43c0da5-de38-4d80-82ff-67628d6ef968
https://github.com/user-attachments/assets/5631fe31-0d5b-4e07-ac45-6a769657401e
- Link
None.
None.
None.
=> fix(lane_change): moving object is filtered in the extended target lanes

planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/src/parameters.hpp
This is a fix based on cppcheck functionStatic warnings.
Since each function clearly changes its member variables, it is assumed to be a false positive for cppcheck.
I believe the reason for the false positive is that the function mechanism itself does not depend on the member variables.
```
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/src/parameters.hpp:73:8: performance: inconclusive: Technically the member function 'autoware::motion_velocity_planner::obstacle_velocity_limiter::ObstacleParameters::updateType' can be static (but you may consider moving to unnamed namespace). [functionStatic]
bool updateType(const rclcpp::Logger & logger, const std::string & type)
^
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_lim …
```
=> fix(autoware_motion_velocity_obstacle_velocity_limiter_module): fix functionStatic

common/perception_utils/CMakeLists.txt, common/perception_utils/include/perception_utils/run_length_encoder.hpp, common/perception_utils/package.xml, common/perception_utils/src/run_length_encoder.cpp, perception/autoware_tensorrt_yolox/CMakeLists.txt, perception/autoware_tensorrt_yolox/package.xml, perception/autoware_tensorrt_yolox/src/tensorrt_yolox_node.cpp
- This to move out run_length compression in `utils` from `tensorrt_yolox` to avoid `cuda`, `cudnn` [required during CI build](https://github.com/autowarefoundation/autoware.universe/actions/runs/10312758044/job/28548491995?pr=7909) when it is used in other package such as `image_projection_based_fusion`. 
- There no change in algorimth.
- Link
None.
None.
None.
=> refactor(tensorrt_yolox): move utils into perception_utils

perception/autoware_detected_object_validation/src/obstacle_pointcloud/debugger.hpp
This is a fix based on cppcheck functionStatic warnings
Since this function internally calls another function and updates member variables within it, it was decided that it would be better to call it using an instance. Therefore, I have suppressed the warning with a comment.
```
perception/autoware_detected_object_validation/src/obstacle_pointcloud/debugger.hpp:69:8: performance: inconclusive: Technically the member function 'autoware::detected_object_validation::obstacle_pointcloud::Debugger::addNeighborPointcloud' can be static (but you may consider moving to unnamed namespace). [functionStatic]
void addNeighborPointcloud(const pcl::PointCloud<pcl::PointXY>::Ptr & input)
^
```
- Link
None.
None.
None.
=> fix(autoware_detected_object_validation): fix functionStatic

.cppcheck_suppressions
Removed `functionStatic`
cppcheck-daily: https://github.com/autowarefoundation/autoware.universe/actions/runs/10412741448/job/28839018963
=> ci(cppcheck): remove unnecessary functionStatic suppression

perception/autoware_multi_object_tracker/schema/input_channels.schema.json
add missing default values to fix https://autowarefoundation.github.io/autoware.universe/main/perception/autoware_multi_object_tracker/
- Link
https://github.com/autowarefoundation/autoware.universe/pull/8179
None.
None.
None.
=> docs(autoware_multi_object_tracker): update input_channels schema with default values

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_module.hpp
Reduced computational cost just a little bit. Reduced unnecessary recursive locks.
- Link
None.
None.
None.
=> perf(goal_planner): reduce unnecessary recursive lock guard

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/scene.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/base_class.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/interface.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp
calls to `filterObjects` are made during both before and after RTC approval.
At the same time, it is also called during stop point insertion.
As filtering objects consumes processing time, in time PR, the filterObject is done only once, and the result is assigned to a member variable in lane change module.
- Link
PSIM.
[TIER IV internal link](https://evaluation.tier4.jp/evaluation/reports/1773ad9b-f7ac-5da3-bd04-ed8aa14d72e1?project_id=prd_jt)
None.
None.
None.
=> refactor(lane_change): update filtered objects only once

planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/path_safety_checker/safety_check.hpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_safety_checker/safety_check.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/test/test_safety_check.cpp
Replace redundant polygon creation with the already created polygon as input.
- Link
[TIER IV internal link](https://evaluation.tier4.jp/evaluation/reports/3a660fc7-c751-5dec-80d1-19f5b6085d49?page=1&project_id=prd_jt)
None.
None.
None.
=> refactor(safety_checker): remove redundant polygon creation

planning/autoware_mission_planner/src/lanelet2_plugins/default_planner.hpp
This is a fix based on cppcheck noConstructor warnings.
```
planning/autoware_mission_planner/src/lanelet2_plugins/default_planner.hpp:44:1: style: The class 'DefaultPlanner' does not declare a constructor although it has private member variables which likely require initialization. [noConstructor]
class DefaultPlanner : public mission_planner::PlannerPlugin
^
```
In `is_graph_ready_(false)`, `param_()`, and `node_(nullptr)`, initialization is done with reference to `void DefaultPlanner::initialize_common`. `route_handler_()` uses the `class RouteHandler_()` uses the default constructor of `class RouteHandler_() `for initialization.
- Link
None.
None.
None.
=> fix(autoware_mission_planner): fix noConstructor

common/perception_utils/CMakeLists.txt
This PR aims to fix `symbol lookup error` on a node (`autoware_tensorrt_yolox`), which uses the dynamic link library generated from `perception_util` package
This issue seems happen after merging https://github.com/autowarefoundation/autoware.universe/pull/8435
- Link
```bash
ros2 launch autoware_tensorrt_yolox yolox.launch.xml
```
And subscribe the result of the yolox by:
```bash
ros2 run rqt_image_view rqt_image_view
```
None.
None.
None.
=> fix(perception_utils): install library after build

launch/tier4_simulator_launch/launch/simulator.launch.xml, simulator/simple_planning_simulator/include/simple_planning_simulator/simple_planning_simulator_core.hpp, simulator/simple_planning_simulator/launch/simple_planning_simulator.launch.py, simulator/simple_planning_simulator/src/simple_planning_simulator/simple_planning_simulator_core.cpp
This PR is a part of the following issue:
https://github.com/autowarefoundation/autoware_launch/issues/1100
This PR allows localization and simple_planning_simulator to support launching the localization module in psim.
launch PR: https://github.com/autowarefoundation/autoware_launch/pull/1094
For more details, please see the launch PR and the issue page.
psim tests and scenario simulator
None.
=> feat(psim)!: preapre settings to launch localization modules on psim

planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/src/utilization/path_utilization.cpp
```
planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/src/utilization/path_utilization.cpp:56:23: style: The scope of the variable 'x' can be reduced. [variableScope]
std::vector<double> x;
^
planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/src/utilization/path_utilization.cpp:57:23: style: The scope of the variable 'y' can be reduced. [variableScope]
std::vector<double> y;
^
planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/src/utilization/path_utilization.cpp:58:23: style: The scope of the variable 'z' can be reduced. [variableScope]
std::vector<double> z;
^
planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/src/utilization/pat …
```
=> fix(autoware_behavior_velocity_planner_common): fix variableScope

planning/autoware_velocity_smoother/src/smoother/analytical_jerk_constrained_smoother/analytical_jerk_constrained_smoother.cpp
```
planning/autoware_velocity_smoother/src/smoother/analytical_jerk_constrained_smoother/analytical_jerk_constrained_smoother.cpp:538:8: style: The scope of the variable 'is_enough_dist' can be reduced. [variableScope]
bool is_enough_dist = false;
^
planning/autoware_velocity_smoother/src/smoother/analytical_jerk_constrained_smoother/analytical_jerk_constrained_smoother.cpp:539:10: style: The scope of the variable 'stop_dist' can be reduced. [variableScope]
double stop_dist;
^
```
- Link
None.
None.
None.
=> fix(autoware_velocity_smoother): fix variableScope

planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/utils.cpp
```
planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/utils.cpp:286:10: style: The scope of the variable 'min_dist' can be reduced. [variableScope]
double min_dist = std::numeric_limits<double>::max();
^
```
- Link
None.
None.
None.
=> fix(autoware_behavior_path_planner_common): fix variableScope

.github/README.md, .github/workflows/build-and-test-daily-arm64.yaml, .github/workflows/build-and-test-differential-arm64.yaml, .github/workflows/build-and-test-differential.yaml, .github/workflows/build-and-test.yaml, sensing/autoware_pointcloud_preprocessor/include/autoware/pointcloud_preprocessor/filter.hpp
Following:
- https://docs.aws.amazon.com/codebuild/latest/userguide/action-runner.html
[Relevant machines:](https://aws.amazon.com/codebuild/pricing/)
| Instance Type    | Memory | vCPUs | Price per Minute |
|------------------|--------|-------|----------------|
| arm1.large       | 16 GiB | 8     | $0.015         |
| general1.medium  | 7 GB   | 4     | $0.01          |
| general1.large   | 15 GB  | 8     | $0.02          |
| general1.xlarge  | 72 GiB | 36    | $0.0798        |
- all tests will use `total cpu count - 1` cores to build, to allow runner to function.
- right now the taskset cpu count is provided manually, can be made into a simple workflow step in the future
- otherwise machines lose connection
- we make use of `taskset` from GNU coreutils for this job
- ~~**build-and-test** …
=> ci: use aws codebuild

perception/autoware_ground_segmentation/config/ground_segmentation.param.yaml, perception/autoware_ground_segmentation/launch/scan_ground_filter.launch.py
- To fix missing parameters error: 
```
ubuntu22:~/autoware$ ros2 launch autoware_ground_segmentation scan_ground_filter.launch.py 
[INFO] [launch]: All log files can be found below /home/autoware/.ros/log/2024-08-20-20-50-28-074447-npc2201009-ubuntu22-95182
...
rclcpp_components::NodeFactoryTemplate<autoware::ground_segmentation::ScanGroundFilterComponent>
[component_container-1] [ERROR] [1724154628.708955855] [scan_ground_filter_container]: Component constructor threw an exception: Statically typed parameter 'low_priority_region_x' must be initialized.
[ERROR] [launch_ros.actions.load_composable_nodes]: Failed to load node 'scan_ground_filter' of type 'autoware::ground_segmentation::ScanGroundFilterComponent' in container …
```
=> fix(ground_segmentation): missing default parameters ERROR

simulator/dummy_perception_publisher/src/node.cpp
Predicting object path utilizes object orientation availability. 
Simulating objects with the orientation availability of `SIGN_UNKNOWN` is more useful.
Before
After
- Link
None.
None.
None.
=> feat(dummy_perception_publisher): modify orientation availability of dummy objects 

tools/reaction_analyzer/src/utils.cpp
```
tools/reaction_analyzer/src/utils.cpp:225:10: style: The scope of the variable 'current_distance' can be reduced. [variableScope]
double current_distance = 0.0;
^
```
- Link
None.
None.
None.
=> fix(reaction_analyzer): fix variableScope

.cppcheck_suppressions
Removed `virtualCallInConstructor` suppression
Check 2024-08-21 cppcheck-daily workflow
https://github.com/autowarefoundation/autoware.universe/actions/workflows/cppcheck-daily.yaml
None.
None.
None.
=> ci(cppcheck): remove unnecessary virtualCallInConstructor suppression

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/README.md, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/config/goal_planner.param.yaml, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_module.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/util.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/util.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/path_safety_checker/safety_check.hpp
Before:
We had done a collision check using footprints for all candidate paths and gave higher priority to those with larger margins.
Then, for those with high priority, we again checked the hard margin and confirmed that sufficient distance had been secured.
After:
For candidate paths, check whether the goal is safe and sufficient distance is secured, and delete those that do not meet the requirements. Calculate rough margins for candidate routes and sort. The rough distance is the longest distance when the object and ego are rotated. (see https://github.com/autowarefoundation/autoware.universe/pull/8464 for details)
After that, we check if hard margin can be secured for the sorted objects in order. Also, pull over paths take -5ms each to copy, so index is used whenever possible.
depends …
=> perf(goal_planner): faster path sorting and selection 

.cppcheck_suppressions
Removed `variableScope` suppression
cppcheck-daily: https://github.com/autowarefoundation/autoware.universe/actions/runs/10482276050/job/29033123546
None.
None.
None.
=> ci(cppcheck): remove unnecessary variableScope suppression

.github/labeler.yaml
This PR is to prepare functionality that does not execute `build-and-test-differential (humble, -cuda)` for PRs related to packages that are not related to cuda.
The label `tag:require-cuda-build-and-test` is applied only to `perception/**/*`, `sensing/**/*`, `common/cuda_utils/**/*`, and `common/tensorrt_common/**/*`.
The functionality to skip cuda build using this PR is implemented in the following:
https://github.com/autowarefoundation/autoware.universe/pull/8547
None.
None.
None.
=> ci(labeler): tag packages that require cuda

evaluator/autoware_planning_evaluator/include/autoware/planning_evaluator/planning_evaluator_node.hpp, planning/motion_velocity_planner/autoware_motion_velocity_planner_node/launch/motion_velocity_planner.launch.xml, planning/motion_velocity_planner/autoware_motion_velocity_planner_node/src/node.cpp, planning/motion_velocity_planner/autoware_motion_velocity_planner_node/src/node.hpp, planning/motion_velocity_planner/autoware_motion_velocity_planner_node/src/planner_manager.cpp, planning/motion_velocity_planner/autoware_motion_velocity_planner_node/src/planner_manager.hpp
This PR adds a publisher in `motion_velocity_planner` to publish diagnostics as what [this PR](https://github.com/autowarefoundation/autoware.universe/pull/7960) did for `cruise_planner`.
The published diagnostics contain information that shows which module (DynamicObstacleStopModule; OutOfLaneModule; ObstacleVelocityLimiterModule) made what decision (stop; slow_down). An example is as follows:
```bash
$ ros2 topic echo /diagnostics
---
header:
stamp:
sec: 1723713886
nanosec: 559327470
frame_id: map
status:
- level: "\0"
name: autoware::motion_velocity_planner::OutOfLaneModule.stop
message: ''
values:
- key: decision
value: none
- level: "\0"
name: autoware::motion_velocity_planner::OutOfLaneModule.slow_down
message: ''
values:
- key: decision
value: …
```
=> feat(motion_velocity_planner,planning_evaluator): add  stop, slow_down diags

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp
The targets object was not added to the member variable `registered_objects_`, so the envelope polygon for the target object was updated with a single shot polygon. This PR will fix the above problem by adding the target objects into  `registered_objects_` appropriately.
None
[TIER IV internal test](https://evaluation.tier4.jp/evaluation/reports/3959d9b3-f390-5e97-acf8-35841e62d97d?project_id=prd_jt)
None.
None.
None.
=> fix(static_obstacle_avoidance): target object sorting

common/tier4_adapi_rviz_plugin/src/state_panel.cpp, common/tier4_state_rviz_plugin/src/autoware_state_panel.cpp
　Fixed `tier4_planning::msgs::msg::VelocityLimit` type topic from the Rviz plugin was not given a timestamp.
None.
None.
None.
None.
=> feat(tier4_adapi_rviz_plugin, tier4_state_rviz_plugin): set timestamp to velocity_limit msg from rviz panels

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/config/static_obstacle_avoidance.param.yaml, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/data_structs.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/parameter_helper.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/type_alias.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/utils.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/schema/static_obstacle_avoidance.schema.json, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/manager.cpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp
When the tracking accuracy is low the target object's envelope polygon becomes large. This large envelope polygon remains even when the tracking accuracy becomes high. This tends to happen when the target object is detected from a far distance; once an unnecessary large sized envelope polygon is created the target object could not be avoided as shown in the movie below.
[Before](https://github.com/user-attachments/assets/cf630b2a-504a-49c1-96b0-1e19a38c7ab0)
This PR updates the envelope polygon by considering the pose covariance.  
https://github.com/autowarefoundation/autoware_launch/pull/1130
PSim + ROSbag
[After](https://github.com/user-attachments/assets/f790cb42-ee29-4432-bef5-c3448860a936)
[TIER IV internal test](https://evaluation.tier4.jp/evaluation/reports/a77becac-0c48-5c6c-ab1b- …
=> feat(static_obstacle_avoidance): update envelope polygon creation method

evaluator/perception_online_evaluator/include/perception_online_evaluator/metrics/deviation_metrics.hpp, evaluator/perception_online_evaluator/src/metrics/deviation_metrics.cpp
```
evaluator/perception_online_evaluator/src/metrics/deviation_metrics.cpp:50:0: style: The function 'calcPredictedPathDeviation' is never used. [unusedFunction]
std::vector<double> calcPredictedPathDeviation(
^
```
- Link
None.
None.
None.
=> fix(perception_online_evaluator): fix unusedFunction

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/config/lane_change.param.yaml, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/data_structs.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/manager.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp
Rename parameter to a more expressive name
https://github.com/autowarefoundation/autoware_launch/pull/1125
- Link
None.
None.
| Version | Parameter Name   | Type     | Default Value | Description       |
|:--------|:-----------------|:---------|:--------------|:------------------|
| Old     | `prepare_segment_ignore_object_velocity_thresh` | `double` | `0.1`         | Param description |
| New     | `stopped_object_velocity_threshold` | `double` | `1.0`         | Param description |
None.
=> refactor(lane_change): rename prepare_segment_ignore_object_velocity_thresh

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/README.md, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/config/lane_change.param.yaml, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/scene.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/data_structs.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/utils.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/manager.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp
If the vehicle in front of the ego vehicle slows down after executing a lane change, it is judged to be unsafe and may be canceled.
In reality, this type of cancellation is considered unnecessary because following the vehicle in front does not make the lane change unsafe.
To deal with such situations, safety judgments are made using several deceleration patterns when making a cancellation decision.
Only when all deceleration patterns are judged to be unsafe, the cancellation should be performed.
PR for launcher : https://github.com/autowarefoundation/autoware_launch/pull/1068
- Link
- [TIER IV internal link](https://tier4.atlassian.net/browse/RT1-6762)
Before:
https://github.com/autowarefoundation/autoware.universe/assets/10190493/ef701791-9b72-45a0-910 …
=> feat(lane_change): consider deceleration in safety check for cancel

.github/workflows/build-and-test-differential.yaml
This PR is to prevent the execution of build-and-test-differential (humble, -cuda) for PRs related to packages that are not cuda-related.
For PRs that do not have the tag:require-cuda-build-and-test label, all steps within build-and-test-differential (humble, -cuda) will be skipped.
This PR reflects the advice of https://github.com/autowarefoundation/autoware.universe/pull/8547. 
The setting of this action works well in https://github.com/autowarefoundation/autoware.universe/actions/runs/10488733741/job/29051839562?pr=8562.
This PR should be merged after https://github.com/autowarefoundation/autoware.universe/pull/8555 is merged.
None.
None.
=> feat(build-and-test-differential): skip cuda build when tag:require-cuda-build-and-test is not attached

control/autoware_pure_pursuit/include/autoware/pure_pursuit/util/planning_utils.hpp, control/autoware_pure_pursuit/src/autoware_pure_pursuit_core/planning_utils.cpp
```
control/autoware_pure_pursuit/src/autoware_pure_pursuit_core/planning_utils.cpp:53:0: style: The function 'calcDistance2D' is never used. [unusedFunction]
double calcDistance2D(const geometry_msgs::msg::Point & p, const geometry_msgs::msg::Point & q)
^
control/autoware_pure_pursuit/src/autoware_pure_pursuit_core/planning_utils.cpp:174:0: style: The function 'isDirectionForward' is never used. [unusedFunction]
bool isDirectionForward(
^
control/autoware_pure_pursuit/src/autoware_pure_pursuit_core/planning_utils.cpp:180:0: style: The function 'isDirectionForward' is never used. [unusedFunction]
bool isDirectionForward(
^
```
- Link
None.
None.
None.
=> fix(autoware_pure_pursuit): fix unusedFunction

perception/autoware_lidar_centerpoint/lib/utils.cpp
It is used in `.cu` files and is suppressed in the comments.
```
perception/autoware_lidar_centerpoint/lib/utils.cpp:22:0: style: The function 'divup' is never used. [unusedFunction]
std::size_t divup(const std::size_t a, const std::size_t b)
^
```
- Link
None.
None.
None.
=> fix(autoware_lidar_centerpoint): fix unusedFunction

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp
With delay lane change, ego will start changing lane only when it is beside the last parked object.
We would like to start changing lanes earlier, so we want to find this point while delaying lane change.
Delay lane change is activated instead of safety check
https://github.com/user-attachments/assets/568f2fa3-864c-45cf-b155-f1fcf08c21e9
Safety check is activated instead of delay lane change.
https://github.com/user-attachments/assets/bb7f7ae4-6cb9-4de9-b032-ba2b631033ad
- Link
1. PSIM
2. [TIER IV internal link](https://evaluation.tier4.jp/evaluation/reports/d4326584-6e6d-5a51-bc39-f4c3f29d0c8a?project_id=prd_jt)
None.
None.
None.
=> feat(lane_change): fix delay logic that caused timing to be late

control/autoware_autonomous_emergency_braking/src/node.cpp
This PR allows the AEB module to work when at least one type of path (IMU or MPC based) is available (and use_imu_path and use_predicted_path parameter are both true). A warning message is printed if one of the path types is missing, but the AEB can still operate an issue emergency stops using the remaining path type. 
https://github.com/user-attachments/assets/a214f2d8-d783-45ec-90be-26c356678080
- Link
PSim
None.
None.
None.
=> feat(autonomous_emergency_braking): enable aeb with only one req path

vehicle/autoware_raw_vehicle_cmd_converter/config/raw_vehicle_cmd_converter.param.yaml
same reason to https://github.com/autowarefoundation/autoware_launch/pull/1132
----
disable actuation to steering by defalut.
this is new feature introduced in https://github.com/autowarefoundation/autoware.universe/pull/8504
but many user don't kwnow the details.
In practice, the description config is called, and this launcher config is often not used, but for now it defaults to false.
- Link
this config in universe is just example not affect the behavior
None.
None.
None.
=> feat(raw_vehicle_cmd_converter): disable actuation to steering

perception/autoware_image_projection_based_fusion/include/autoware/image_projection_based_fusion/utils/utils.hpp, perception/autoware_image_projection_based_fusion/src/utils/utils.cpp
```
perception/autoware_image_projection_based_fusion/src/utils/utils.cpp:51:0: style: The function 'convertCluster2FeatureObject' is never used. [unusedFunction]
void convertCluster2FeatureObject(
^
perception/autoware_image_projection_based_fusion/src/utils/utils.cpp:177:0: style: The function 'addShapeAndKinematic' is never used. [unusedFunction]
void addShapeAndKinematic(
^
perception/autoware_image_projection_based_fusion/src/utils/utils.cpp:264:0: style: The function 'getClosestPoint' is never used. [unusedFunction]
pcl::PointXYZ getClosestPoint(const pcl::PointCloud<pcl::PointXYZ> & cluster)
^
```
- Link
None.
None.
None.
=> fix(autoware_image_projection_based_fusion): fix unusedFunction

control/control_performance_analysis/include/control_performance_analysis/control_performance_analysis_utils.hpp, control/control_performance_analysis/src/control_performance_analysis_utils.cpp
```
control/control_performance_analysis/src/control_performance_analysis_utils.cpp:28:0: style: The function 'triangleArea' is never used. [unusedFunction]
double triangleArea(
^
```
- Link
None.
None.
None.
=> fix(control_performance_analysis): fix unusedFunction

perception/autoware_traffic_light_fine_detector/src/traffic_light_fine_detector_node.cpp
```
perception/autoware_traffic_light_fine_detector/src/traffic_light_fine_detector_node.cpp:52:0: style: The function 'toFloatVector' is never used. [unusedFunction]
inline std::vector<float> toFloatVector(const std::vector<double> & double_vector)
^
```
- Link
None.
None.
None.
=> fix(autoware_traffic_light_fine_detector): fix unusedFunction

localization/ekf_localizer/include/ekf_localizer/ekf_localizer.hpp, localization/ekf_localizer/src/ekf_localizer.cpp
The variable dev_ in Simple1DFilter is being treated as variance, not standard deviation. 
So, I have renamed `dev` to `var` in the Simple1DFilter class
- Link
Lsim works
None.
None.
None.
=> refactor(ekf_localizer): rename dev to var in the Simple1DFilter class

planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
This PR fixes finding front and back point logic in [findEgoPassageDirectionAlongPath](https://github.com/autowarefoundation/autoware.universe/blob/bbc85252a5ebf6ea9cd901b536f051c5bd57cff2/planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp#L595-L625) function
closes https://github.com/autowarefoundation/autoware.universe/issues/8458
- https://github.com/autowarefoundation/autoware.universe/issues/8458
with psim
None.
None.
None.
=> fix(crosswalk): fix findEgoPassageDirectionAlongPath finding front and back point logic

launch/tier4_map_launch/launch/map.launch.xml
related to : https://github.com/autowarefoundation/autoware.universe/pull/8422
this error happens in my environment.
```
[ERROR] [launch_ros.actions.load_composable_nodes]: Failed to load node 'vector_map_tf_generator' of type 'VectorMapTFGeneratorNode' in container '/map/map_container': Could not find requested resource in ament index
```
- Link
psim
None.
None.
None.
=> fix(map_tf_genrator): fix map launch prefix

simulator/simple_planning_simulator/include/simple_planning_simulator/vehicle_model/sim_model_delay_steer_acc_geared_wo_fall_guard.hpp, simulator/simple_planning_simulator/src/simple_planning_simulator/vehicle_model/sim_model_delay_steer_acc_geared_wo_fall_guard.cpp
A recently added vehicle model sim_model_delay_steer_acc_geared_wo_fall_guard has a bug that publish the input acc_cmd as the current acceleration. https://github.com/autowarefoundation/autoware.universe/pull/7651
This PR fix this issue.
psim
I know the zero division line is newly added by this PR.
None.
None.
=> fix(simple_planning_simulator): fix acc output for the model sim_model_delay_steer_acc_geared_wo_fall_guard

control/autoware_autonomous_emergency_braking/include/autoware/autonomous_emergency_braking/node.hpp, control/autoware_autonomous_emergency_braking/src/node.cpp
In current OSS Autoware there is a visual bug that makes it so the rss distance is always 0. This is caused because the RSS distance is calculated AFTER the debug marker is published, this PR fixes the problem by calculating the distance first (which is saved on the collision_data_keeper_ member class) and then, using that data to publish the debug info.
- Link
PSim
None.
None.
None.
=> fix(autonomous_emergency_braking): fix debug marker visual bug

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp
these functions are called in `void GoalPlannerModule::onTimer()` which is in not in main thread. so remove time_keeper from these functions.
- Link
not tested 
None.
None.
None.
=> fix(goal_planner): remove time keeper in non main thread

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/interface.cpp
In this previous PR https://github.com/autowarefoundation/autoware.universe/pull/7436, some conditions were added so that the state will transit from `RUNNING` to `FAILURE`. The module itself would transit to the appropriate state however, the RTC cooperateStatus would not be updated. In this PR I have resolved this problem by calling the `updateRTCStatus` function by providing the `FAILURE` status.
https://github.com/autowarefoundation/autoware.universe/pull/7436
https://evaluation.tier4.jp/evaluation/reports/1f0f0af5-d1b1-579a-890b-be2aa856e208?project_id=prd_jt
None.
None.
None.
=> fix(lane_change): update rtc status for some failure condition

planning/autoware_freespace_planner/src/autoware_freespace_planner/freespace_planner_node.cpp
Freespace planner node spams the message `Waiting for occupancy grid` when parking scenario is not active.
Update input data and check data availability only when parking scenario is active.
None.
PSIM
None.
None.
None.
=> fix(freespace_planner): fix free space planner spamming message

localization/ekf_localizer/include/ekf_localizer/ekf_localizer.hpp, localization/ekf_localizer/src/ekf_localizer.cpp
In the ekf_localizer node,  there is a strange way of writing for tf_listener , so I fixed it.
- Link
Lsim works
None.
None.
None.
=> refactor(ekf_localizer): fix tf2 listener

localization/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp
The timestamp of `/initialpose3d` was always set to 0, so I investigated the cause and made the necessary fixes.
- Link
Lsim works.
and check the timestamp of `/initialpose3d`.
```
ros2 topic echo /initialpose3d --field header
```
None.
None.
None.
=> fix(ndt_scan_matcher): fix timestamp in service_ndt_align func

localization/ekf_localizer/config/ekf_localizer.param.yaml, localization/ekf_localizer/schema/sub/simple_1d_filter_parameters.sub_schema.json
In [this PR](https://github.com/autowarefoundation/autoware.universe/pull/8576
), since the squared value is now set, like
```
roll_filter_.set_proc_var(params_.roll_filter_proc_dev * params_.roll_filter_proc_dev);
```
So the parameter value has been adjusted by taking the square root.
- Link
test with https://github.com/autowarefoundation/autoware_launch/pull/1140
None.
None.
=> fix(ekf_localizer): change roll, pitch proc dev

common/traffic_light_utils/include/traffic_light_utils/traffic_light_utils.hpp, common/traffic_light_utils/src/traffic_light_utils.cpp, common/traffic_light_utils/test/test_traffic_light_utils.cpp
```
common/traffic_light_utils/src/traffic_light_utils.cpp:20:0: style: The function 'isRoiValid' is never used. [unusedFunction]
bool isRoiValid(
^
common/traffic_light_utils/src/traffic_light_utils.cpp:31:0: style: The function 'setRoiInvalid' is never used. [unusedFunction]
void setRoiInvalid(tier4_perception_msgs::msg::TrafficLightRoi & roi)
^
common/traffic_light_utils/src/traffic_light_utils.cpp:36:0: style: The function 'isSignalUnknown' is never used. [unusedFunction]
bool isSignalUnknown(const tier4_perception_msgs::msg::TrafficLight & signal)
^
```
- Link
None.
None.
None.
=> fix(traffic_light_utils): fix unusedFunction

perception/autoware_image_projection_based_fusion/src/pointpainting_fusion/node.cpp
Solve cpp warn check. Related to https://github.com/autowarefoundation/autoware.universe/pull/8354.
- Link
None.
None.
None.
=> fix(image_projection_based_fusion): remove unused variable

common/autoware_universe_utils/include/autoware/universe_utils/system/time_keeper.hpp, common/autoware_universe_utils/src/system/time_keeper.cpp, common/autoware_universe_utils/test/src/system/test_time_keeper.cpp
In the current implementation, if we use time_keeper in different threads, it may cause an error and lead to termination.
In this PR, we check the thread_id before creating the ProcessingTimeNode, and if the thread_id does not match the root node, we discard creating downstream of the node.
- [TIER IV Internal Slack](https://star4.slack.com/archives/C04ATE0264Q/p1724647801437319)
By unit testing.
None.
None.
None.
=> feat(autoware_universe_utils): add thread_id check to time_keeper

perception/autoware_tracking_object_merger/include/autoware/tracking_object_merger/utils/utils.hpp, perception/autoware_tracking_object_merger/src/utils/utils.cpp
```
perception/autoware_tracking_object_merger/src/utils/utils.cpp:301:0: style: The function 'objectsYawIsReverted' is never used. [unusedFunction]
bool objectsYawIsReverted(const TrackedObject & main_obj, const TrackedObject & sub_obj)
^
perception/autoware_tracking_object_merger/src/utils/utils.cpp:413:0: style: The function 'probabilityMerger' is never used. [unusedFunction]
float probabilityMerger(const float main_prob, const float sub_prob, const MergePolicy policy)
^
perception/autoware_tracking_object_merger/src/utils/utils.cpp:428:0: style: The function 'shapeMerger' is never used. [unusedFunction]
autoware_perception_msgs::msg::Shape shapeMerger(
^
```
- Link
None.
None.
None.
=> fix(autoware_tracking_object_merger): fix unusedFunction

simulator/simple_planning_simulator/test/test_simple_planning_simulator.cpp
just add print values in test.
```
1:  vehicle model = ACTUATION_CMD, conversion_type = steer_map
1:
1: isOnForward: dx: 3.68665, forward_thr: 1
1: isOnBackward: dx: -5.6944, backward_thr: -1
1: isOnForwardLeft: dx: 1.50116, forward_thr: 1, dy: 3.5285, left_thr: 0.1
1: isOnBackwardRight: dx: -3.79643, backward_thr: -1, dy: -2.40294, right_thr: -0.1
1: [       OK ] TestForEachVehicleModelTrue/TestSimplePlanningSimulator.TestIdealSteerVel/1 (7615 ms)
1: [ RUN      ] TestForEachVehicleModelTrue/TestSimplePlanningSimulator.TestIdealSteerVel/2
1:
```
currently, actual and expected values are printed only when tests fail.
It is hard to debug by comparing the success and failure cases.
ex) In follwing test only `-cuda` option failed, but we could not compare the one without `-cuda` …
=> feat(simple_planning_simulator): print actual and expected value in test

perception/autoware_probabilistic_occupancy_grid_map/include/autoware/probabilistic_occupancy_grid_map/utils/utils.hpp, perception/autoware_probabilistic_occupancy_grid_map/lib/utils/utils.cpp, perception/autoware_probabilistic_occupancy_grid_map/src/fusion/synchronized_grid_map_fusion_node.cpp, perception/autoware_probabilistic_occupancy_grid_map/src/fusion/synchronized_grid_map_fusion_node.hpp
```
perception/autoware_probabilistic_occupancy_grid_map/lib/utils/utils.cpp:199:0: style: The function 'getApproximateOccupancyState' is never used. [unusedFunction]
unsigned char getApproximateOccupancyState(const unsigned char & value)
^
perception/autoware_probabilistic_occupancy_grid_map/src/fusion/synchronized_grid_map_fusion_node.cpp:372:0: style: The function 'OccupancyGridMsgToCostmap2D' is never used. [unusedFunction]
nav2_costmap_2d::Costmap2D GridMapFusionNode::OccupancyGridMsgToCostmap2D(
^
perception/autoware_probabilistic_occupancy_grid_map/src/fusion/synchronized_grid_map_fusion_node.cpp:377:0: style: The function 'updateGridMap' is never used. [unusedFunction]
void GridMapFusionNode::updateGridMap(
^
```
**Parent …
=> fix(autoware_probabilistic_occupancy_grid_map): fix unusedFunction

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/util.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/shift_pull_over.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/util.cpp
When extending a path, if the end of the original target path contains 0 velocity, then 0 velocity remains in the middle of the extended_path. This causes more stuck before the goal.
This issue was observed when the goal planner was activated after the LC was activated, for example.
```
// NOTE: The previous module may insert a zero velocity at the end of the path, so remove it by
// setting remove_connected_zero_velocity=true. Inserting a velocity of 0 into the goal is the
// role of the goal planner, and the intermediate zero velocity after extension is unnecessary.
```
before
after
- Link
- https://tier4.atlassian.net/browse/RT0-31696
- psim
- 2024/08/21 https://evaluation.tier4.jp/evaluation/reports/fbeded6b-7456-58ba-a6af-a39e9288b3f0/?project_id=p …
=> fix(goal_planner): fix zero velocity in middle of path

common/tier4_localization_rviz_plugin/src/pose_history/pose_history_display.cpp
```
common/tier4_localization_rviz_plugin/src/pose_history/pose_history_display.cpp:53:0: style: The function 'onEnable' is never used. [unusedFunction]
void PoseHistory::onEnable()
^
common/tier4_localization_rviz_plugin/src/pose_history/pose_history_display.cpp:58:0: style: The function 'onDisable' is never used. [unusedFunction]
void PoseHistory::onDisable()
^
```
- Link
None.
None.
None.
=> fix(tier4_localization_rviz_plugin): fix unusedFunction

localization/ekf_localizer/include/ekf_localizer/ekf_localizer.hpp, localization/ekf_localizer/src/ekf_localizer.cpp
Currently, `proc_cov_*_d_` are calculated in ekf_module.cpp.
https://github.com/autowarefoundation/autoware.universe/blob/a64566ee7437075c75f30d128940dd4823e9d27a/localization/ekf_localizer/src/ekf_module.cpp#L182-L195
So we can remove these variables from EKFLocalizer.
I have confirmed that logging_simulator with AWSIM GT rosbag works well and the mean error is almost the same as before.
None.
None.
None.
=> refactor(ekf_localizer): removed proc_cov_*_d_ from EKFLocalizer

planning/autoware_mission_planner/src/mission_planner/arrival_checker.cpp, planning/autoware_mission_planner/src/mission_planner/arrival_checker.hpp
```
planning/autoware_mission_planner/src/mission_planner/arrival_checker.cpp:46:0: style: The function 'modify_goal' is never used. [unusedFunction]
void ArrivalChecker::modify_goal(const PoseWithUuidStamped & modified_goal)
^
```
- Link
None.
None.
None.
=> fix(autoware_mission_planner): fix unusedFunction

planning/autoware_costmap_generator/include/autoware_costmap_generator/object_map_utils.hpp, planning/autoware_costmap_generator/nodes/autoware_costmap_generator/object_map_utils.cpp
```
planning/autoware_costmap_generator/nodes/autoware_costmap_generator/object_map_utils.cpp:40:0: style: The function 'PublishGridMap' is never used. [unusedFunction]
void PublishGridMap(
^
planning/autoware_costmap_generator/nodes/autoware_costmap_generator/object_map_utils.cpp:48:0: style: The function 'PublishOccupancyGrid' is never used. [unusedFunction]
void PublishOccupancyGrid(
^
```
- Link
None.
None.
None.
=> fix(autoware_costmap_generator): fix unusedFunction

planning/autoware_path_optimizer/include/autoware/path_optimizer/utils/trajectory_utils.hpp, planning/autoware_path_optimizer/src/utils/trajectory_utils.cpp
```
planning/autoware_path_optimizer/src/utils/trajectory_utils.cpp:100:0: style: The function 'compensateLastPose' is never used. [unusedFunction]
void compensateLastPose(
^
```
- Link
None.
None.
None.
=> fix(autoware_path_optimizer): fix unusedFunction

planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/shift_pull_out.cpp
There was some redundant calculation in the `ShiftPullOut::calcPullOutPaths`. This PR removes the redundant calculation outside the for loop and decreases the calculation time.　Below is an example of the processing time.
Before:
```
100.00% planWaitingApproval: total 110.06 [ms], avg. 7.34 [ms], run count: 15
├── 95.95% updatePullOutStatus: total 105.60 [ms], avg. 7.04 [ms], run count: 15
│   ├── 0.12% calcBackwardPathFromStartPose: total 0.13 [ms], avg. 0.13 [ms], run count: 1
│   ├── 0.10% searchPullOutStartPoseCandidates: total 0.11 [ms], avg. 0.11 [ms], run count: 1
│   │   ├── 0.04% filterStopObjectsInPullOutLanes: total 0.04 [ms], avg. 0.02 [ms], run count: 2
│   │   └── 0.06% rest: 0.06 [ms]
│   ├── 95.66% planWithPriority: total 105.28 [ms], avg. 105.28 [ms], run count: 1
│   │ …
```
=> refactor(start_planner): remove redundant calculation in shift pull out 

planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_module.hpp
=> fix(out_of_lane): fix noConstructor cppcheck warning

planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/src/obstacle_velocity_limiter.cpp, planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/src/obstacle_velocity_limiter.hpp, planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/src/obstacle_velocity_limiter_module.cpp, planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/src/obstacle_velocity_limiter_module.hpp, planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/src/parameters.hpp, planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/src/trajectory_preprocessing.cpp, planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/src/trajectory_preprocessing.hpp, planning/motion_velocity_planner/autoware_motion_velocity_planner_node/src/node.cpp
Fix the `obstacle_velocity_limiter` adding virtual walls at each slowdown point. Now a wall is added only the first slowdown of an interval.
Also moved the check to prevent increasing the trajectory velocity to the node side.
- Link
Psim
None.
None.
None.
=> fix(obstacle_velocity_limiter): more stable virtual wall

.cppcheck_suppressions
Removed `noConstructor` suppression
cppcheck-daily: https://github.com/autowarefoundation/autoware.universe/actions/runs/10592983966/job/29353484882
None.
None.
None.
=> ci(cppcheck): remove unnecessary noConstructor suppression

planning/behavior_path_planner/autoware_behavior_path_dynamic_obstacle_avoidance_module/src/scene.cpp
```
planning/behavior_path_planner/autoware_behavior_path_dynamic_obstacle_avoidance_module/src/scene.cpp:182:0: style: The function 'calcDiffAngleBetweenPaths' is never used. [unusedFunction]
[[maybe_unused]] double calcDiffAngleBetweenPaths(
^
```
- Link
None.
None.
None.
=> fix(autoware_behavior_path_dynamic_obstacle_avoidance_module): fix unusedFunction

planning/behavior_path_planner/autoware_behavior_path_side_shift_module/include/autoware/behavior_path_side_shift_module/utils.hpp, planning/behavior_path_planner/autoware_behavior_path_side_shift_module/src/utils.cpp
```
planning/behavior_path_planner/autoware_behavior_path_side_shift_module/src/utils.cpp:56:0: style: The function 'getStartAvoidPose' is never used. [unusedFunction]
bool getStartAvoidPose(
^
planning/behavior_path_planner/autoware_behavior_path_side_shift_module/src/utils.cpp:89:0: style: The function 'transformToGrid' is never used. [unusedFunction]
Point transformToGrid(
^
```
- Link
None.
None.
None.
=> fix(autoware_behavior_path_side_shift_module): fix unusedFunction

planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/path_utils.hpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/utils.hpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/src/marker_utils/utils.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/drivable_area_expansion/static_drivable_area.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/parking_departure/utils.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_utils.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/utils.cpp
```
planning/behavior_path_planner/autoware_behavior_path_planner_common/src/marker_utils/utils.cpp:344:0: style: The function 'createDrivableLanesMarkerArray' is never used. [unusedFunction]
MarkerArray createDrivableLanesMarkerArray(
^
planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/drivable_area_expansion/static_drivable_area.cpp:625:0: style: The function 'calcCenterOfGeometry' is never used. [unusedFunction]
[[maybe_unused]] geometry_msgs::msg::Point calcCenterOfGeometry(const Polygon2d & obj_poly)
^
planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/parking_departure/utils.cpp:107:0: style: The function 'updateSafetyCheckTargetObjectsData' is never used. …
```
=> fix(autoware_behavior_path_planner_common): fix unusedFunction

planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/include/autoware/behavior_velocity_crosswalk_module/util.hpp, planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/util.cpp
```
planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/util.cpp:108:0: style: The function 'checkRegulatoryElementExistence' is never used. [unusedFunction]
bool checkRegulatoryElementExistence(const lanelet::LaneletMapPtr & lanelet_map_ptr)
^
```
- Link
None.
None.
None.
=> fix(autoware_behavior_velocity_crosswalk_module): fix unusedFunction

tools/reaction_analyzer/include/subscriber.hpp, tools/reaction_analyzer/include/topic_publisher.hpp
When I ran the following commands today, I got a lot of ros-humble-related updates.
```
sudo apt update
sudo apt -y upgrade
```
After that, when I built autoware, I started getting the following errors.
```
In file included from /home/shintarosakoda/autoware/src/universe/autoware.universe/tools/reaction_analyzer/include/reaction_analyzer_node.hpp:19,
from /home/shintarosakoda/autoware/src/universe/autoware.universe/tools/reaction_analyzer/src/reaction_analyzer_node.cpp:15:
/home/shintarosakoda/autoware/src/universe/autoware.universe/tools/reaction_analyzer/include/subscriber.hpp:19:10: fatal error: tf2_eigen/tf2_eigen/tf2_eigen.hpp: そのようなファイルやディレクトリはありません
19 | #include <tf2_eigen/tf2_eigen/tf2_eigen.hpp>
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gmake[2]: *** …
```
=> fix(reaction_analyzer): fix include hierarchy of tf2_eigen

sensing/autoware_pointcloud_preprocessor/src/downsample_filter/faster_voxel_grid_downsample_filter.cpp
Fixes compilation error on Jazzy:
error: ‘FLT_MAX’ was not declared in this scope
=> fix(autoware_pointcloud_preprocessor): resolve issue with FLT_MAX not declared on Jazzy

vehicle/autoware_raw_vehicle_cmd_converter/src/node.cpp
In https://github.com/autowarefoundation/autoware.universe/pull/8588, we introduced new parameter, but it is hard to modify all the prameter file for many vehicles. so set false by default to keep the previous behavior with out parameter file modification.
- Link
None.
None.
None.
=> feat(raw_vehicle_cmd_converter): set convert_actuation_to_steering_status false by default

planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/CMakeLists.txt, planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/scripts/dilemma_zone_plotter.py
Added a script to plot dilemma zone.
[Screencast from 2024年08月27日 12時16分49秒.webm](https://github.com/user-attachments/assets/d0befae7-079a-4ce2-9d3c-f1fa8409ea32)
None.
None.
None.
=> feat(traffic_light): add dilemma_zone_plotter.py

sensing/autoware_pointcloud_preprocessor/src/downsample_filter/robin_hood.h
```
sensing/autoware_pointcloud_preprocessor/src/downsample_filter/robin_hood.h:344:0: style: The function 'rotr' is never used. [unusedFunction]
T rotr(T x, unsigned k)
^
sensing/autoware_pointcloud_preprocessor/src/downsample_filter/robin_hood.h:1935:0: style: The function 'emplace_hint' is never used. [unusedFunction]
iterator emplace_hint(const const_iterator & position, Args &&... args)
^
sensing/autoware_pointcloud_preprocessor/src/downsample_filter/robin_hood.h:2180:0: style: The function 'rehash' is never used. [unusedFunction]
void rehash(size_t c)
^
sensing/autoware_pointcloud_preprocessor/src/downsample_filter/robin_hood.h:2196:0: style: The function 'compact' is never used. [unusedFunction]
void compact()
^ …
```
=> fix(autoware_pointcloud_preprocessor): fix unusedFunction

common/tier4_state_rviz_plugin/src/custom_container.cpp, common/tier4_state_rviz_plugin/src/custom_icon_label.cpp, common/tier4_state_rviz_plugin/src/custom_label.cpp, common/tier4_state_rviz_plugin/src/custom_segmented_button.cpp, common/tier4_state_rviz_plugin/src/custom_segmented_button_item.cpp, common/tier4_state_rviz_plugin/src/custom_slider.cpp, common/tier4_state_rviz_plugin/src/custom_toggle_switch.cpp
Added a warning suppression comment in a previous PR, but corrected it because it had added an extra one as well.
```
common/tier4_state_rviz_plugin/src/custom_container.cpp:44:0: information: Unmatched suppression: unusedFunction [unmatchedSuppression]
QSize CustomContainer::minimumSizeHint() const
^
common/tier4_state_rviz_plugin/src/custom_icon_label.cpp:54:0: information: Unmatched suppression: unusedFunction [unmatchedSuppression]
QSize CustomIconLabel::minimumSizeHint() const
^
common/tier4_state_rviz_plugin/src/custom_icon_label.cpp:60:0: information: Unmatched suppression: unusedFunction [unmatchedSuppression]
void CustomIconLabel::paintEvent(QPaintEvent *)
^
common/tier4_state_rviz_plugin/src/custom_label.cpp:50:0: …
```
=> fix(tier4_state_rviz_plugin): fix unmatchedSuppression

common/autoware_perception_rviz_plugin/src/object_detection/object_polygon_detail.cpp
Replace path marker from circle to triangle. 
It may reduce rendering load and adds information of its direction.
Before
After
- Link
None.
None.
None.
=> feat(autoware_perception_rviz_plugin): rviz predicted path mark as triangle

simulator/simple_planning_simulator/src/simple_planning_simulator/vehicle_model/sim_model_delay_steer_acc_geared_wo_fall_guard.cpp
fix stopping behavior issue
In the previous code, when the vehicle velocity is smaller than dead_band velocity, the vehicle do not stop with enough brake.
Currently, stop processing is done within update().
scenario sim tell me this problem, and I tested in psim
None.
<!-- ⬇️🔴
None.
=> fix(simple_planning_simulator): delete velocity dead band for brake

launch/tier4_localization_launch/launch/localization.launch.xml, launch/tier4_localization_launch/launch/pose_twist_fusion_filter/pose_twist_fusion_filter.launch.xml
Enable to set the `param_path` of `stop filter.param.yaml`.
Especially expected to get from autoware_launch.
**This PR has to work and be merged with https://github.com/autowarefoundation/autoware_launch/pull/1145 together.**
1. Checked that [rosbag replay tutorial](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/rosbag-replay-simulation/) works.
2. Checked that `ros2 param dump /localization/pose_twist_fusion_filter/stop_filter` return the following. When I changed `vx_threshold` to 1.1.
```
/localization/pose_twist_fusion_filter/stop_filter:
qos_overrides:
/clock:
subscription:
depth: 1
durability: volatile
history: keep_last
reliability: best_effort
/parameter_events:
publisher:
depth: 1000
durability: volatile
history: …
```
=> chore(stop_filter): extract stop_filter.param.yaml to autoware_launch

perception/autoware_ground_segmentation/package.xml
Required for `Jazzy` compilation
=> fix(ground-segmentation): missing ament_index_cpp dependency

perception/autoware_multi_object_tracker/src/multi_object_tracker_node.cpp, perception/autoware_multi_object_tracker/src/multi_object_tracker_node.hpp
Reduce latency of the multi object tracker caused by periodic trigger of the process.
First implementation
https://github.com/autowarefoundation/autoware.universe/pull/6710
Revert of the first implementation
https://github.com/autowarefoundation/autoware.universe/pull/8277
https://github.com/autowarefoundation/autoware.universe/pull/8484
The multi-object-tracker adds 50ms of latency. The latency was increased from 2-5ms to 15-60ms.
The latency is changing on each test. 
The reason of additional latency is due to the phase difference between the detected object (after detection and merge) and the multi object tracker timer. The phase delay is determined at the launch time and it is random.
Bringing back high frequency checker of publish timing. 
1. The previous implementation checked the …
=> feat(autoware_multi_object_tracker): reduce trigger latency

planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_collisions.cpp, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_collisions.hpp, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_module.cpp
This PR fixes a major bug where the rtree was built with indexes to a vector whose elements were then filtered, causing access to invalid memory in some part of the code.
The fix simply filters the elements before using them to build the rtree.
- Link
Psim
None.
None.
None.
=> fix(out_of_lane): fix a bug with the rtree reference deleted nodes

control/autoware_lane_departure_checker/include/autoware/lane_departure_checker/lane_departure_checker.hpp, control/autoware_lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker.cpp, planning/behavior_path_planner/autoware_behavior_path_planner/src/planner_manager.cpp, planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/shift_pull_out.cpp
The `ShiftPullOut::plan()` function in start planner, checks if a candidate path is safe by using the lane departure module. As the number of candidate path grows, the lane departure check would be called multiple times, which leads to large computational cost calling. This is due to calling the boost::geometry functions several times, as seen below:
```
100.00% planWaitingApproval: total 92.69 [ms], avg. 5.79 [ms], run count: 16
├── 91.30% updatePullOutStatus: total 84.62 [ms], avg. 5.29 [ms], run count: 16
│   ├── 0.20% calcBackwardPathFromStartPose: total 0.19 [ms], avg. 0.19 [ms], run count: 1
│   ├── 0.14% searchPullOutStartPoseCandidates: total 0.13 [ms], avg. 0.13 [ms], run count: 1
│   │   ├── 0.04% filterStopObjectsInPullOutLanes: total 0.04 [ms], …
```
=> refactor(start_planner, lane_departure_checker): remove redundant calculation in fuseLaneletPolygon

control/autoware_autonomous_emergency_braking/include/autoware/autonomous_emergency_braking/node.hpp, control/autoware_autonomous_emergency_braking/src/node.cpp
This PR adds the timekeeper to the main functions of the AEB module to ease debugging when looking for performance bottlenecks.
- Link
PSim
Example
`
ros2 topic echo /control/autonomous_emergency_braking/debug/processing_time_detail_ms
nodes:
- id: 1
name: checkCollision
processing_time: 23.268
parent_id: 0
comment: ''
- id: 2
name: onPointCloud
processing_time: 0.855
parent_id: 1
comment: ''
- id: 3
name: has_collision_imu_path
processing_time: 0.002
parent_id: 1
comment: ''
- id: 4
name: has_collision_mpc_path
processing_time: 0.001
parent_id: 1
comment: ''
- id: 5
name: generateEgoPath
processing_time: 0.011
parent_id: 1
comment: ''
- id: 6
name: generatePathFootprint
processing_time: 0.269
parent_id: 1
comment: ''
- id: 7
name: generatePathFootprint
processing_time: …
=> feat(autonomous_emergency_braking): add timekeeper to AEB

common/tier4_planning_rviz_plugin/src/tools/jsk_overlay_utils.cpp, common/tier4_planning_rviz_plugin/src/tools/jsk_overlay_utils.hpp
```
common/tier4_planning_rviz_plugin/src/tools/jsk_overlay_utils.cpp:65:0: style: The function 'getPixelBuffer' is never used. [unusedFunction]
Ogre::HardwarePixelBufferSharedPtr ScopedPixelBuffer::getPixelBuffer()
^
```
- Link
None.
None.
None.
=> fix(tier4_planning_rviz_plugin): fix unusedFunction

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/pull_over_planner/freespace_pull_over.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/pull_over_planner/geometric_pull_over.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/pull_over_planner/pull_over_planner_base.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/pull_over_planner/shift_pull_over.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/freespace_pull_over.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/geometric_pull_over.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/shift_pull_over.cpp
depends https://github.com/autowarefoundation/autoware.universe/pull/8696
- added const to members
- planner_data and previous_module_output do not need to be member, so pass as arguments
- Link
refactoring
https://evaluation.tier4.jp/evaluation/reports/772f4aa3-227d-521c-819c-57d9c1118635?project_id=prd_jt
None.
None.
None.
=> refactor(goal_planner): remove unnecessary member from pull_over_planner

launch/tier4_perception_launch/launch/object_recognition/detection/detector/tracker_based_detector.launch.xml
In the previous update for the `autoware_` prefix, the launch namespace of `detection_by_tracker` also set to have the prefix `autoware_`, which should not be changed.
Since the namespace is set to `autoware_detection_by_tracker`, debug topics are under it.
Fortunately, the architecture (output of the detection_by_tracker) does not changed.
https://github.com/autowarefoundation/autoware.universe/issues/7998
- Link
None.
None.
None.
=> fix(tier4_perception_launch): launch namespace of `detection_by_tracker`

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_module.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/pull_over_planner/freespace_pull_over.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/pull_over_planner/geometric_pull_over.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/pull_over_planner/pull_over_planner_base.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/pull_over_planner/shift_pull_over.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/freespace_pull_over.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/geometric_pull_over.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/shift_pull_over.cpp
depends https://github.com/autowarefoundation/autoware.universe/pull/8697
- Link
logically no issue because the removed variable is never used
https://evaluation.tier4.jp/evaluation/reports/772f4aa3-227d-521c-819c-57d9c1118635?project_id=prd_jt
None.
None.
None.
=> refactor(goal_planner): remove unnecessary member from PreviousPullOverData

planning/behavior_path_planner/autoware_behavior_path_avoidance_by_lane_change_module/src/interface.cpp, planning/behavior_path_planner/autoware_behavior_path_avoidance_by_lane_change_module/src/interface.hpp, planning/behavior_path_planner/autoware_behavior_path_avoidance_by_lane_change_module/src/manager.cpp, planning/behavior_path_planner/autoware_behavior_path_dynamic_obstacle_avoidance_module/include/autoware/behavior_path_dynamic_obstacle_avoidance_module/manager.hpp, planning/behavior_path_planner/autoware_behavior_path_dynamic_obstacle_avoidance_module/include/autoware/behavior_path_dynamic_obstacle_avoidance_module/scene.hpp, planning/behavior_path_planner/autoware_behavior_path_dynamic_obstacle_avoidance_module/src/scene.cpp, planning/behavior_path_planner/autoware_behavior_path_external_request_lane_change_module/src/manager.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_module.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/manager.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/interface.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/interface.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/manager.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/interface/scene_module_interface.hpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/interface/scene_module_manager_interface.hpp, planning/behavior_path_planner/autoware_behavior_path_sampling_planner_module/include/autoware/behavior_path_sampling_planner_module/manager.hpp, planning/behavior_path_planner/autoware_behavior_path_sampling_planner_module/include/autoware/behavior_path_sampling_planner_module/sampling_planner_module.hpp, planning/behavior_path_planner/autoware_behavior_path_sampling_planner_module/src/sampling_planner_module.cpp, planning/behavior_path_planner/autoware_behavior_path_side_shift_module/include/autoware/behavior_path_side_shift_module/manager.hpp, planning/behavior_path_planner/autoware_behavior_path_side_shift_module/include/autoware/behavior_path_side_shift_module/scene.hpp, planning/behavior_path_planner/autoware_behavior_path_side_shift_module/src/scene.cpp, planning/behavior_path_planner/autoware_behavior_path_start_planner_module/include/autoware/behavior_path_start_planner_module/manager.hpp, planning/behavior_path_planner/autoware_behavior_path_start_planner_module/include/autoware/behavior_path_start_planner_module/start_planner_module.hpp, planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/start_planner_module.cpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/manager.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/scene.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp
pass steering factor interface's pointer to scene module in order to redule frequency of constructing `SteeringFactorInterface` and calling `create_publisher().`.
- Link
None.
None.
None.
=> fix(bpp): use common steering factor interface for same scene modules

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/manager.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/manager.cpp
initialize parameters using static function for portability
- Link
goal_planner works
None.
None.
None.
=> refactor(goal_planner): initialize parameter with free function

.github/workflows/cppcheck-weekly.yaml
Changed cppcheck-all from daily to weekly (on Monday morning).
This is because the critical warnings from cppcheck is now reduced to almost 0, and thus no need to run cppcheck-all so frequently.
Autoware Discussion: https://github.com/orgs/autowarefoundation/discussions/4827#discussioncomment-10472639
None.
None.
None.
=> ci(cppcheck): change all cppcheck from daily to weekly

.github/workflows/cppcheck-weekly.yaml
Sorry I forgot to fix the workflow name in https://github.com/autowarefoundation/autoware.universe/pull/8713.
This is a fix of it.
- Link
None.
None.
None.
=> ci(cppcheck): fix workflow name

localization/ndt_scan_matcher/CMakeLists.txt, localization/ndt_scan_matcher/include/ndt_scan_matcher/hyper_parameters.hpp, localization/ndt_scan_matcher/include/ndt_scan_matcher/map_update_module.hpp, localization/ndt_scan_matcher/include/ndt_scan_matcher/ndt_scan_matcher_core.hpp, localization/ndt_scan_matcher/include/ndt_scan_matcher/particle.hpp, localization/ndt_scan_matcher/src/map_update_module.cpp, localization/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp, localization/ndt_scan_matcher/src/particle.cpp, localization/ndt_scan_matcher/test/test_fixture.hpp
Add `namespace autoware::ndt_scan_marcher::` to ndt_scan_marcher package.
I have confirmed autoware with [autoware_tools](https://github.com/autowarefoundation/autoware_tools) and [localization_evaluation_tools (TIER IV INTERNAL)](https://github.com/tier4/localization_evaluator_tools) can be built.
None.
None.
None.
=> refactor(ndt_scan_marcher): add namespace "autoware::ndt_scan_matcher::"

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/helper.hpp
There is a bug to use wrong parameter. It should use `min_prepare_time` instead of `min_prepare_distance`.
- [TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT0-32307)
None.
None.
None.
=> fix(static_obstacle_avoidance): use wrong parameter

planning/autoware_obstacle_stop_planner/src/debug_marker.hpp
```
planning/autoware_obstacle_stop_planner/src/debug_marker.hpp:81:0: style: The function 'getValuesIdx' is never used. [unusedFunction]
static int getValuesIdx(const TYPE type) { return static_cast<int>(type); }
^
```
- Link
None.
None.
None.
=> fix(autoware_obstacle_stop_planner): fix unusedFunction

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/shift_line_generator.cpp
Since this process generated invalid shift line whose relative longitudinal distance was ZERO, I added applySmallShiftFilter in https://github.com/autowarefoundation/autoware.universe/pull/8344. But I think there is simpler way to fix the issue.
```c++
for (size_t i = 0; i < sorted.size() - 1; ++i) {
if (sorted.at(i + 1).start_longitudinal < sorted.at(i).end_longitudinal) {
continue;
}
const auto new_line = fill(sorted.at(i), sorted.at(i + 1), generateUUID());
ret.push_back(new_line);
debug.step1_front_shift_line.push_back(new_line);
}
```
None.
None.
None.
=> fix(static_obstacle_avoidance): change implementation the logic to remove invalid small shift lines

common/autoware_universe_utils/src/system/backtrace.cpp
```
common/autoware_universe_utils/src/system/backtrace.cpp:29:0: style: The function 'print_backtrace' is never used. [unusedFunction]
void print_backtrace()
^
```
- Link
None.
None.
None.
=> fix(autoware_universe_utils): fix unusedFunction

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp
```
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp:96:0: style: The function 'findFirstNearestSegmentIndex' is never used. [unusedFunction]
size_t findFirstNearestSegmentIndex(const T & points, const geometry_msgs::msg::Point & point)
^
```
This function was removed because it is only used in the readme and not used on the actual code.
The readme is a separate package and has been fixed in a #8733 
- #8733 
- Link
None.
None.
None.
=> fix(autoware_behavior_path_static_obstacle_avoidance_module): fix unusedFunction

planning/sampling_based_planner/autoware_path_sampler/include/autoware_path_sampler/utils/trajectory_utils.hpp, planning/sampling_based_planner/autoware_path_sampler/src/utils/trajectory_utils.cpp
```
planning/sampling_based_planner/autoware_path_sampler/src/utils/trajectory_utils.cpp:38:0: style: The function 'compensateLastPose' is never used. [unusedFunction]
void compensateLastPose(
^
```
- Link
None.
None.
None.
=> fix(autoware_path_sampler): fix unusedFunction

control/autoware_autonomous_emergency_braking/src/node.cpp
tf_buffer_.lookupTransform seems to be a costly operation that significantly slows down AEB processing time. 
As measured with timekeeper: 
[timekeeper_with_lookup_stamp.txt](https://github.com/user-attachments/files/16845540/timekeeper_with_lookup_stamp.txt)
Peak processing time: > 31 ms
With this PR, we ask the AEB to use directly the latest transform from map to base link, dramatically speeding up the process: 
[timekeeper_no_lookup_stamp.txt](https://github.com/user-attachments/files/16845550/timekeeper_no_lookup_stamp.txt)
Peak processing time: 5.54 ms
- Link
PSim
None.
None.
None.
=> feat(autonomous_emergency_braking): increase aeb speed by getting last transform

planning/autoware_mission_planner/src/lanelet2_plugins/default_planner.cpp, planning/autoware_mission_planner/src/lanelet2_plugins/default_planner.hpp, planning/autoware_mission_planner/src/lanelet2_plugins/utility_functions.cpp, planning/autoware_mission_planner/src/lanelet2_plugins/utility_functions.hpp
This PR fixes an issue occurring when path lanelets overlap, causing `combine_lanelets_with_shoulder()` to generate a self-intersecting polygon which can result in goal poses being wrongfully rejected.
In this PR, we modify the logic to not use the `combine_lanelets_with_shoulder()` function.
- Link
- [TIER IV interval link](https://evaluation.tier4.jp/evaluation/reports/400707a9-0b3c-591d-8715-7080510143e2?project_id=prd_jt)
None.
None.
None.
=> fix(mission_planner): improve condition to check if the goal is within the lane

sensing/autoware_pointcloud_preprocessor/src/distortion_corrector/distortion_corrector.cpp
This PR instantiates the DistortionCorrector template so that when linking against it the symbols can be found.
- Link https://github.com/autowarefoundation/autoware.universe/issues/8742
Built Autoware from source in the buildfarm.
None.
None.
None.
=> fix(autoware_pointcloud_preprocessor): instantiate templates so that the symbols exist when linking

perception/autoware_shape_estimation/include/autoware/shape_estimation/tensorrt_shape_estimator.hpp
While building `autoware_shape_estimation`, I got the following error:
```shell
Starting >>> autoware_shape_estimation                                                                                                                                                        
--- stderr: autoware_shape_estimation                                                                                                                                                         
CUDA found, including CUDA-specific sources
/usr/bin/ld: libautoware_shape_estimation.so: undefined reference to `autoware::shape_estimation::TrtShapeEstimator::~TrtShapeEstimator()'
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/test_autoware_shape_estimation.dir/build.make:830: test_autoware_shape_estimation] …
```
=> fix(autoware_shape_estimation): resolve undefined reference to `~TrtShapeEstimator()`

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_module.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_searcher.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_searcher_base.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/util.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_searcher.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/util.cpp
The current algorithm expands the pull over lane only outward and extracts objects in it. In this case, if an object exists without overlapping the narrow shoulder lane, the object is not extracted. For example, since the object does not overlap the shoulder lane at 8509, it is not included in the collision check. As a result, the route is generated ignoring the object, and it gets stuck.
In this PR, pull over lanes are expanded inward so that objects can be extracted regardless of the width of the lane. The length to be expanded is determined by the goal search area. the extraction plygon is the sky blue one.
psim
https://evaluation.tier4.jp/evaluation/reports/41bd57af-9931-5c32-ae12-bbb927ad0dd8?project_id=prd_jt&state=failed
4133/4136
baseline: …
=> feat(goal_planner): extend pull over lanes inward to extract objects

perception/autoware_compare_map_segmentation/src/distance_based_compare_map_filter/node.cpp
In current compare map, we use following code to compare distance and its threshold.
```cpp
if (nn_distances[0] <= distance_threshold) {
```
However, `nn_distances` from `radiusKsearch` in PCL is said to be **suqared distance**. [c.f. documents](https://pointclouds.org/documentation/classpcl_1_1search_1_1_kd_tree.html#a20501b588a7971de1dbe92a634deafc5).
This PR fix this issue by squaring the distance threshold.
- Confirmed in slack discussion: https://star4.slack.com/archives/C076ZGRC15X/p1725369477014509?thread_ts=1725345541.550159&cid=C076ZGRC15X
None.
None.
None.
=> fix(compare_map_segmentation): use squared distance to compare threshold

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/debug.cpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/shift_line_generator.cpp
There is a issue that the avoidance module did wrong avoidable/unavoidable judgement even after it decided to avoid. I found this was caused by the logic to check longitudinal distance, and the module judged it was not avoidable because there was not enough longitudinal distance when the ego got close to avoidance target object.
https://github.com/user-attachments/assets/693c3e24-c33c-4020-9f06-a02e805efa16
In this PR, I fixed the logic to ignore object if the module generates avoidance path for it.
```c++
const auto is_approved = [this](const auto & object) {
return (helper_->getShift(object.getPosition()) > 0.0 && isOnRight(object)) ||
(helper_->getShift(object.getPosition()) < 0.0 && !isOnRight(object));
};
```
- Link …
=> fix(static_obstacle_avoidance): ignore objects which has already been decided to avoid

control/autoware_pid_longitudinal_controller/src/pid_longitudinal_controller.cpp
fix the same point error related to https://github.com/autowarefoundation/autoware.universe/pull/4712
A rosbag that cause the problem fixed by this pr 
psim and tier4 internal test
None.
None.
None.
=> fix(pid_longitudinal_controller): fix the same point error

common/autoware_motion_utils/README.md
Since `findFirstNearestSegmentIndex` was deleted in #8732  , it became necessary to make it consistent.
Therefore, the section for calculating the length of the path/trajectory between specified points was deleted.
The `findFirstNearestSegmentIndex` is not used in the actual code.
- #8732 
None.
None.
None.
=> fix(autoware_motion_utils): fix unusedFunction

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/utils.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp
```
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp:241:0: style: The function 'getTargetPreferredLanes' is never used. [unusedFunction]
lanelet::ConstLanelets getTargetPreferredLanes(
^
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp:672:0: style: The function 'calcLateralBufferForFiltering' is never used. [unusedFunction]
double calcLateralBufferForFiltering(const double vehicle_width, const double lateral_buffer)
^
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp:677:0: style: The function 'getStrDirection' is never used. [unusedFunction]
std::string getStrDirection(const std::string & name, const …
```
=> fix(autoware_behavior_path_lane_change_module): fix unusedFunction

planning/behavior_path_planner/autoware_behavior_path_dynamic_obstacle_avoidance_module/config/dynamic_obstacle_avoidance.param.yaml, planning/behavior_path_planner/autoware_behavior_path_dynamic_obstacle_avoidance_module/include/autoware/behavior_path_dynamic_obstacle_avoidance_module/scene.hpp, planning/behavior_path_planner/autoware_behavior_path_dynamic_obstacle_avoidance_module/package.xml, planning/behavior_path_planner/autoware_behavior_path_dynamic_obstacle_avoidance_module/src/manager.cpp, planning/behavior_path_planner/autoware_behavior_path_dynamic_obstacle_avoidance_module/src/scene.cpp
fixes: https://github.com/autowarefoundation/autoware.universe/issues/7690
**Parent Issue:** https://github.com/autowarefoundation/autoware.universe/issues/7634
Must merged: https://github.com/autowarefoundation/autoware_launch/pull/1133
https://github.com/user-attachments/assets/48275d67-a09d-43e7-9597-c870d1ee7463
None.
| Parameter Name   |    Type     | Default Value     | Description       |
|:-------------------------|:------------  |:--------------------- |:------------------|
| `expand_drivable_area`     | `bool`    | `false`  | expand drivable area while avoiding |
None.
=> feat(autoware_behavior_path_dynamic_obstacle_avoidance): expand drivable area

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/util.cpp
fix https://github.com/autowarefoundation/autoware.universe/pull/8714
especially when bound has only two points, polygon can be created correctly
before
after
psim 
2024/09/05 https://evaluation.tier4.jp/evaluation/reports/ea173245-3b3b-5acc-880d-b783123747af/?project_id=prd_jt
fix [UC-v3-F-04-00003_005_case01_cmn_general:10](https://evaluation.tier4.jp/evaluation/reports/aeae0a22-cbcb-5754-a3e9-17d549db4cac/tests/ab6433f0-a6fb-5dac-82ef-f50dc063b6db/a5efc36f-9fb6-52fe-a27e-497c9a008a64/1733ce2c-6301-5426-a3ba-da95feb94a04?project_id=prd_jt&state=failed)
before
after
None.
None.
None.
=> fix(goal_planner): fix object extraction area

control/autoware_pure_pursuit/launch/pure_pursuit.launch.xml
This PR fixes a package name referenced by the pure_pursuit.launch.xml.
- https://github.com/autowarefoundation/autoware.universe/issues/8686
Tested locally by running `ros2 run autoware_pure_pursuit pure_pursuit.launch.xml`
None.
None.
None.
=> fix(pure_pursuit): add autoware_ prefix in launch file

common/tier4_state_rviz_plugin/src/custom_button.cpp
Improve drop shadow effect by editing the blur radius and offset to be more center aligned
- https://github.com/autowarefoundation/autoware_launch/pull/1017#issuecomment-2331374583
=> refactor(custom_button): improve drop shadow effect

planning/autoware_surround_obstacle_checker/src/debug_marker.cpp, planning/autoware_surround_obstacle_checker/src/debug_marker.hpp
```
planning/autoware_surround_obstacle_checker/src/debug_marker.cpp:239:0: style: The function 'updateFootprintMargin' is never used. [unusedFunction]
void SurroundObstacleCheckerDebugNode::updateFootprintMargin(
^
```
- Link
None.
None.
None.
=> fix(autoware_surround_obstacle_checker): fix unusedFunction

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/util.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/util.cpp
```
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/util.cpp:277:0: style: The function 'extractStaticObjectsInExpandedPullOverLanes' is never used. [unusedFunction]
PredictedObjects extractStaticObjectsInExpandedPullOverLanes(
^
```
- Link
None.
None.
None.
=> fix(autoware_behavior_path_goal_planner_module): fix unusedFunction

planning/behavior_velocity_planner/autoware_behavior_velocity_run_out_module/src/debug.hpp
```
planning/behavior_velocity_planner/autoware_behavior_velocity_run_out_module/src/debug.hpp:57:0: style: The function 'getValuesIdx' is never used. [unusedFunction]
static int getValuesIdx(const TYPE type) { return static_cast<int>(type); }
^
```
- Link
None.
None.
None.
=> fix(autoware_behavior_velocity_run_out_module): fix unusedFunction

control/autoware_autonomous_emergency_braking/include/autoware/autonomous_emergency_braking/node.hpp, control/autoware_autonomous_emergency_braking/include/autoware/autonomous_emergency_braking/utils.hpp, control/autoware_autonomous_emergency_braking/src/node.cpp, control/autoware_autonomous_emergency_braking/src/utils.cpp, control/autoware_autonomous_emergency_braking/test/test.cpp
This PR refactors the AEB code to speed up processing time. Clustering and path-based pointcloud cropping are done once per iteration instead of twice. Some other changes are done to increase speed. 
Comparison using driving log replayer: 
before
[aeb_times.txt](https://github.com/user-attachments/files/16887045/aeb_times.txt)
times higher than 70 ms:
`processing_time: 89.683
processing_time: 74.601
processing_time: 82.908
processing_time: 87.936
processing_time: 93.321
processing_time: 89.623
processing_time: 119.028
processing_time: 99.281
processing_time: 85.516
processing_time: 72.685
processing_time: 85.565
processing_time: 93.702
processing_time: 87.082
processing_time: 72.67
processing_time: 107.033
processing_time: 95.981
processing_time: 73.572
processing_time: 97.633 …
=> feat(autonomous_emergency_braking): speed up aeb

perception/autoware_map_based_prediction/src/path_generator.cpp
A performance analysis of the `map_based_prediction` with [VTune](https://www.intel.com/content/www/us/en/developer/tools/oneapi/vtune-profiler.html) was performed. The generated frame graph is below.
For example, you see `std::pow` accounts for 50% of the `generateFrenetPath` function's processing time.
Replacing `std::pow` with a simple multiplier reduces the computation time of this function from `2.2` ms to `0.6` ms for 1000 calculations. This is the PR.
(The function is called for each combination of "the number of objects" and "the number of predicted paths".)
None
- I visually confirmed that the prediction is working correctly in psim.
None.
None.
None.
=> perf(autoware_map_based_prediction): replace pow

perception/autoware_compare_map_segmentation/src/voxel_grid_map_loader/voxel_grid_map_loader.hpp
```
perception/autoware_compare_map_segmentation/src/voxel_grid_map_loader/voxel_grid_map_loader.hpp:39:0: style: The function 'distance3D' is never used. [unusedFunction]
double distance3D(const T p1, const U p2)
^
```
- Link
None.
None.
None.
=> fix(autoware_compare_map_segmentation): fix unusedFunction

common/autoware_motion_utils/src/resample/resample.cpp, common/autoware_motion_utils/test/src/resample/test_resample.cpp
This PR modifies the resampling of longitudinal_velocity_mps.
The algorithm has been updated to handle data points with embedded zero values differently. For example, when interpolating a sequence like [10, 10, 10, 0, 10, 0, 0, 0], the new algorithm will first transform the data to [10, 10, 10, 0, 0, 0, 0, 0] by setting all values after the first zero point to zero. Interpolation is then performed on this modified sequence.
When interpolating sequences like [10, 10, 10, 0, 10, 0, 0, 0] using zero-order hold, there were cases where the middle zero point was ignored due to the parameters of the zero-order hold. This resulted in interpolations like [10, 10, 10, 10, 10, 0, 0, 0], where the middle point that should have been zero was not.
This issue led to a bug in [this …
=> feat(autoware_motion_utils): set zero velocity after stop in resample trajectory

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/debug.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/scene.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/debug.cpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp
Fix bug which caused delay of turning on signal when the ego returns original lane after avoiding. This module outputs turn signal per shift lines but sometimes they include the one whose shift length is small. In original implementation, this module didn't output turn signal for such a shift line. Additionally, since this module only checked front (=nearest) shift line, it may ignore return shift line unexpectedly.
In this PR, I fixed the logic to remove small shift line at first.
```c++
const auto itr =
std::remove_if(shift_lines.begin(), shift_lines.end(), [&, this](const auto & s) {
const auto threshold = planner_data_->parameters.turn_signal_shift_length_threshold;
return std::abs(s.start_shift_length - s.end_shift_length) < threshold ||
is_ignore_signal(s.id);
}); …
```
=> fix(static_obstacle_avoidance): improve turn signal output timing when the ego returns original lane

perception/autoware_map_based_prediction/include/map_based_prediction/map_based_prediction_node.hpp, perception/autoware_map_based_prediction/include/map_based_prediction/path_generator.hpp, perception/autoware_map_based_prediction/src/map_based_prediction_node.cpp, perception/autoware_map_based_prediction/src/path_generator.cpp
1. Add backlash within lanelet when predict paths. (Background: Small bikes are tend to drive side within the lane. However, the predictor yields the paths always to the center of the lane.)
* Before : The target path is to center line position of the target lanelet.
* After : The target path allows offset if the momentum (lateral position + 0.5 * lateral velocity * lateral_duration) is within the backlash width. The backlash width is determined by the path width - the object width. The bias is modeled by a continuous function.
Before
https://github.com/user-attachments/assets/ecfebfdf-47da-4fc3-bb44-e57bc71a9cca
https://github.com/user-attachments/assets/84b1d6b9-be35-4f28-8c25-df0b9eb479f9
After
https://github.com/user-attachments/assets/c4ca2ebd-44a5-429d-8877-2644bc9a8457 …
=> feat(autoware_map_based_prediction): improve frenet path generation

map/autoware_map_projection_loader/src/load_info_from_lanelet2_map.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_searcher.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_searcher.cpp
depends https://github.com/autowarefoundation/autoware.universe/pull/8777
- Link
just add new function
None.
None.
None.
=> feat(goal_planner): add getBusStopAreaPolygons

planning/autoware_obstacle_cruise_planner/config/obstacle_cruise_planner.param.yaml, planning/autoware_path_optimizer/config/path_optimizer.param.yaml, planning/autoware_path_smoother/config/elastic_band_smoother.param.yaml, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/config/out_of_lane.param.yaml
This PR aligns the parameters in **_motion planning packages_**. …
=> fix(motion_planning): align the parameters with launcher

planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/config/crosswalk.param.yaml, planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/config/intersection.param.yaml, planning/behavior_velocity_planner/autoware_behavior_velocity_occlusion_spot_module/config/occlusion_spot.param.yaml, planning/behavior_velocity_planner/autoware_behavior_velocity_run_out_module/config/run_out.param.yaml
This PR aligns the parameters in **_behavior velocity planner_**. …
=> fix(behavior_velocity_planner): align the parameters with launcher

planning/behavior_path_planner/autoware_behavior_path_dynamic_obstacle_avoidance_module/config/dynamic_obstacle_avoidance.param.yaml, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/config/goal_planner.param.yaml, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/config/lane_change.param.yaml, planning/behavior_path_planner/autoware_behavior_path_planner/config/behavior_path_planner.param.yaml, planning/behavior_path_planner/autoware_behavior_path_planner/config/drivable_area_expansion.param.yaml, planning/behavior_path_planner/autoware_behavior_path_planner/config/scene_module_manager.param.yaml, planning/behavior_path_planner/autoware_behavior_path_sampling_planner_module/config/sampling_planner.param.yaml, planning/behavior_path_planner/autoware_behavior_path_start_planner_module/config/start_planner.param.yaml, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/config/static_obstacle_avoidance.param.yaml
This PR aligns the parameters in **_behavior path planner_**. …
=> fix(autoware_behavior_path_planner): align the parameters with launcher

map/autoware_map_projection_loader/src/load_info_from_lanelet2_map.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/CMakeLists.txt, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/config/goal_planner.param.yaml, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_parameters.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_searcher.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/util.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/package.xml, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_searcher.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/manager.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/util.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/test/test_util.cpp
depends https://github.com/autowarefoundation/autoware.universe/pull/8794
launcher PR: https://github.com/autowarefoundation/autoware_launch/pull/1156
- [CompanyName internal link](https://tier4.atlassian.net/browse/RT1-4047)
None.
None.
None.
=> feat(goal_planner):  dense goal candidate sampling in BusStopArea

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/README.md, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp
change pull over request statasu
- before: The ego vehilc is in the same lane sequence as the goal.
- after: The terminal of the current path is in the same lane sequence as the goal. (while LC)
https://github.com/user-attachments/assets/517ad29a-666a-4917-90d4-d2975d372ebf
- Link
psim
https://evaluation.tier4.jp/evaluation/reports/e3ddffe2-dc9f-5770-8db8-d39caed6741f?project_id=prd_jt
None.
None.
None.
=> feat(goal_planner): execute goal planner if previous module path terminal is pull over neighboring lane

perception/autoware_ground_segmentation/config/ground_segmentation.param.yaml, perception/autoware_ground_segmentation/config/ransac_ground_filter.param.yaml, perception/autoware_ground_segmentation/config/ray_ground_filter.param.yaml, perception/autoware_ground_segmentation/config/scan_ground_filter.param.yaml, perception/autoware_ground_segmentation/package.xml, perception/autoware_ground_segmentation/src/ransac_ground_filter/node.cpp, perception/autoware_ground_segmentation/src/ransac_ground_filter/node.hpp, perception/autoware_ground_segmentation/src/ray_ground_filter/node.cpp, perception/autoware_ground_segmentation/src/ray_ground_filter/node.hpp, perception/autoware_ground_segmentation/src/scan_ground_filter/node.cpp, perception/autoware_ground_segmentation/src/scan_ground_filter/node.hpp, perception/autoware_ground_segmentation/test/test_ransac_ground_filter.cpp, perception/autoware_ground_segmentation/test/test_ray_ground_filter.cpp, perception/autoware_ground_segmentation/test/test_scan_ground_filter.cpp
This PR will add time keeper feature for `ground_segmentation`.
The time tracking is set only for relatively long processing time functions/methods.
You need to modified the parameter file `ground_segmentation.param.yaml` in `autoware_launch` to run in autoware.
- https://github.com/autowarefoundation/autoware_launch/pull/1134
---
Sample output (updated from original comment)
```Text
- scan_ground_filter
100.00% faster_filter: total 3706.36 [ms], avg. 18.53 [ms], run count: 200
├── 67.09% convertPointcloudGridScan: total 2486.72 [ms], avg. 12.43 [ms], run count: 200
│   ├── 50.49% scan: total 1871.41 [ms], avg. 9.36 [ms], run count: 200
│   ├── 16.53% sort: total 612.49 [ms], avg. 3.06 [ms], run count: 200
│   └── 0.08% rest: 2.82 [ms]
├── 28.57% classifyPointCloudGridScan: total 1059.02 …
```
=> feat(ground_segmentation): add time_keeper

perception/autoware_lidar_centerpoint/include/autoware/lidar_centerpoint/cuda_utils.hpp, perception/autoware_lidar_centerpoint/include/autoware/lidar_centerpoint/network/tensorrt_wrapper.hpp, perception/autoware_lidar_centerpoint/include/autoware/lidar_centerpoint/preprocess/pointcloud_densification.hpp, perception/autoware_lidar_centerpoint/include/autoware/lidar_centerpoint/preprocess/preprocess_kernel.hpp, perception/autoware_lidar_centerpoint/lib/network/tensorrt_wrapper.cpp, perception/autoware_lidar_centerpoint/lib/preprocess/preprocess_kernel.cu, perception/autoware_lidar_centerpoint/lib/preprocess/voxel_generator.cpp
Use `std::size_t` instead of `size_t`
Build works
None.
None.
None.
=> refactor(autoware_lidar_centerpoint): use std::size_t instead of size_t

common/tier4_camera_view_rviz_plugin/src/bird_eye_view_tool.cpp, common/tier4_camera_view_rviz_plugin/src/third_person_view_tool.cpp
Prevention against future CI changes.
```
common/tier4_camera_view_rviz_plugin/src/bird_eye_view_tool.cpp:54:18: warning: Member variable 'BirdEyeViewTool::m_sceneNode' is not initialized in the constructor. [uninitMemberVar]
BirdEyeViewTool::BirdEyeViewTool()
^
common/tier4_camera_view_rviz_plugin/src/bird_eye_view_tool.cpp:54:18: warning: Member variable 'BirdEyeViewTool::m_fly_mode' is not initialized in the constructor. [uninitMemberVar]
BirdEyeViewTool::BirdEyeViewTool()
^
common/tier4_camera_view_rviz_plugin/src/bird_eye_view_tool.cpp:54:18: warning: Member variable 'BirdEyeViewTool::m_left_hand_mode' is not initialized in the constructor. [uninitMemberVar]
BirdEyeViewTool::BirdEyeViewTool()
^ …
```
=> fix(tier4_camera_view_rviz_plugin): fix uninitMemberVar

common/tier4_localization_rviz_plugin/src/pose_history/pose_history_display.cpp, common/tier4_localization_rviz_plugin/src/pose_history/pose_history_display.hpp, common/tier4_localization_rviz_plugin/src/pose_history_footprint/display.cpp, common/tier4_localization_rviz_plugin/src/pose_history_footprint/display.hpp, common/tier4_localization_rviz_plugin/src/pose_with_covariance_history/pose_with_covariance_history_display.cpp, common/tier4_localization_rviz_plugin/src/pose_with_covariance_history/pose_with_covariance_history_display.hpp
This PR applies some suggestions from the linter to `tier4_localization_rviz_plugin`.
Fixed:
- add initialization to uninitialized variable
suppressed:
- cppcheck unusedFunction
- redundant access specifier (readability-redundant-access-specifiers)
- redundant private specifier in class definition
- e.g. https://github.com/autowarefoundation/autoware.universe/blob/0cee96143239e16ead4a464d83662bca7a5aef1e/common/tier4_localization_rviz_plugin/src/pose_with_covariance_history/pose_with_covariance_history_display.hpp#L65-L68
- removing the regular `private`  will lead to `Error: Not a signal or slot declaration` from Qt.
- added `// NOLINT`  for suppression
- Link
Checked with clang-tidy (v14.0.0) and cppcheck (v2.14.1).
Use …
=> refactor(tier4_localization_rviz_plugin): apply static analysis

common/autoware_test_utils/src/autoware_test_utils.cpp
This is a fix based on cppcheck unusedFunction warnings
```
common/autoware_test_utils/src/autoware_test_utils.cpp:270:0: style: The function 'spinSomeNodes' is never used. [unusedFunction]
void spinSomeNodes(
^
```
- Link
None.
None.
None.
=> fix(autoware_test_utils): fix unusedFunction

common/tier4_state_rviz_plugin/src/autoware_state_panel.cpp
This is a fix based on cppcheck shadowVariable warnings.
```
common/tier4_state_rviz_plugin/src/autoware_state_panel.cpp:702:15: style: Local variable 'state' shadows outer variable [shadowVariable]
IconState state;
^
common/tier4_state_rviz_plugin/src/autoware_state_panel.cpp:703:12: style: Local variable 'bgColor' shadows outer variable [shadowVariable]
QColor bgColor;
^
```
- Link
None.
None.
None.
=> fix(tier4_state_rviz_plugin): fix shadowVariable

common/tier4_state_rviz_plugin/src/autoware_state_panel.cpp
This is a fix based on cppcheck constVariablePointer warnings.
```
common/tier4_state_rviz_plugin/src/autoware_state_panel.cpp:174:19: style: Variable 'button' can be declared as pointer to const [constVariablePointer]
QPushButton * button = qobject_cast<QPushButton *>(abstractButton);
^
```
- Link
None.
None.
None.
=> fix(tier4_state_rviz_plugin): fix constVariablePointer

localization/ndt_scan_matcher/src/ndt_scan_matcher_core.cpp
I improved the error message in pose interpolation in the ndt_scan_matcher.
The logging_simulator works well, and the mean error is almost the same as before.
None.
None.
None.
=> fix(ndt_scan_matcher): improve error message in ndt_scan_matcher

common/tier4_localization_rviz_plugin/src/pose_history_footprint/display.cpp
This is a fix based on cppcheck constVariableReference warnings.
```
common/tier4_localization_rviz_plugin/src/pose_history_footprint/display.cpp:214:15: style: Variable 'point_idx' can be declared as reference to const [constVariableReference]
for (auto & point_idx : history_) {
^
```
- Link
None.
None.
None.
=> fix(tier4_localization_rviz_plugin): fix constVariableReference

perception/autoware_cluster_merger/launch/cluster_merger.launch.xml, perception/autoware_cluster_merger/src/cluster_merger_node.cpp, perception/autoware_cluster_merger/src/cluster_merger_node.hpp
- This PR:
- Removes some unused variables
- Unify topic name for[ node testing PR](https://github.com/autowarefoundation/autoware.universe/pull/8810).
- Link
None.
None.
None.
=> refactor(cluster_merger): remove unused variable and rename topic

perception/autoware_lidar_transfusion/include/autoware/lidar_transfusion/cuda_utils.hpp, perception/autoware_lidar_transfusion/include/autoware/lidar_transfusion/network/network_trt.hpp, perception/autoware_lidar_transfusion/include/autoware/lidar_transfusion/preprocess/pointcloud_densification.hpp, perception/autoware_lidar_transfusion/include/autoware/lidar_transfusion/preprocess/preprocess_kernel.hpp, perception/autoware_lidar_transfusion/include/autoware/lidar_transfusion/preprocess/voxel_generator.hpp, perception/autoware_lidar_transfusion/include/autoware/lidar_transfusion/transfusion_trt.hpp, perception/autoware_lidar_transfusion/lib/preprocess/preprocess_kernel.cu, perception/autoware_lidar_transfusion/lib/transfusion_trt.cpp
shuffled points before feeding them to the model to avoid voxels filling with highly correlated points
Inference time:
After this PR: 9.69ms
Before this PR: 8.49 ms
- Link
Related thread
- [TIER IV](https://star4.slack.com/archives/C03S84LDJGG/p1725614367350419)
Used the X2 data from the thread and a reference bag from XX1.
Tested both centerpoint (the model from x2 and the standard model) and transfusion
None.
None.
None.
=> feat(autoware_lidar_transfusion): shuffled points before feeding them to the model

planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/manager.cpp
This is a fix based on cppcheck virtualCallInConstructor warnings.
```
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/manager.hpp:72:16: style: Virtual function 'getModuleName' is called from constructor 'MergeFromPrivateModuleManager(rclcpp::Node&node)' at line 474. Dynamic binding is not used. [virtualCallInConstructor]
const char * getModuleName() override { return "merge_from_private"; }
^
```
- Link
None.
None.
None.
=> fix(autoware_behavior_velocity_intersection_module): fix virtualCallInConstructor

planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/manager.cpp
This is a fix based on cppcheck unreadVariable warnings.
```
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/manager.cpp:330:32: style: Variable 'location' is assigned a value that is never used. [unreadVariable]
const std::string location = ll.attributeOr("location", "else");
^
```
- Link
None.
None.
None.
=> fix(autoware_behavior_velocity_intersection_module): fix unreadVariable

simulator/tier4_dummy_object_rviz_plugin/src/tools/delete_all_objects.cpp
```
simulator/tier4_dummy_object_rviz_plugin/src/tools/delete_all_objects.cpp:81:0: style: The function 'onPoseSet' is never used. [unusedFunction]
void DeleteAllObjectsTool::onPoseSet(
^
```
- Link
None.
None.
None.
=> fix(tier4_dummy_object_rviz_plugin): fix unusedFunction

common/tier4_state_rviz_plugin/src/include/autoware_state_panel.hpp, simulator/tier4_dummy_object_rviz_plugin/src/tools/delete_all_objects.cpp
I have tested and confirmed this, but would like to know if it is being used.
```
common/tier4_state_rviz_plugin/src/include/autoware_state_panel.hpp:226:0: style: The function 'updateCustomLabel' is never used. [unusedFunction]
static void updateCustomLabel(
^
common/tier4_state_rviz_plugin/src/include/autoware_state_panel.hpp:232:0: style: The function 'updateButton' is never used. [unusedFunction]
static void updateButton(QPushButton * button, QString text, QString style_sheet)
^
```
- Link
Confirm that the planning simulation works.
Confirm that print debugging is not used.
Confirm that the build passes.
None.
None.
None.
=> fix(tier4_state_rviz_plugin): fix unusedFunction

planning/autoware_external_velocity_limit_selector/CMakeLists.txt, planning/autoware_external_velocity_limit_selector/include/autoware/external_velocity_limit_selector/external_velocity_limit_selector_node.hpp, planning/autoware_external_velocity_limit_selector/package.xml, planning/autoware_external_velocity_limit_selector/param/external_velocity_limit_selector_parameters.yaml, planning/autoware_external_velocity_limit_selector/src/external_velocity_limit_selector_node.cpp
This PR enables external_velocity_limit_selector to handle parameters using [generate_parameter_library](https://github.com/PickNikRobotics/generate_parameter_library).
Psim
[Screencast from 2024年09月10日 15時17分23秒.webm](https://github.com/user-attachments/assets/56a73fc0-3b0f-41d5-a537-2ca2ede88a64)
Evaluator: https://evaluation.tier4.jp/evaluation/reports/ed62fc35-1ece-581a-ba66-03fad335a207?project_id=prd_jt
None.
None.
None.
=> feat(external_velocity_limit_selector): integrate generate_parameter_library

control/autoware_autonomous_emergency_braking/config/autonomous_emergency_braking.param.yaml, control/autoware_control_validator/config/control_validator.param.yaml, control/autoware_lane_departure_checker/config/lane_departure_checker.param.yaml, control/autoware_trajectory_follower_node/param/lateral/mpc.param.yaml, control/autoware_trajectory_follower_node/param/longitudinal/pid.param.yaml, control/autoware_vehicle_cmd_gate/config/vehicle_cmd_gate.param.yaml, control/obstacle_collision_checker/config/obstacle_collision_checker.param.yaml
This PR aligns the parameters in **_control packages_**.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main …
=> fix(control): align the parameters with launcher

planning/autoware_costmap_generator/config/costmap_generator.param.yaml, planning/autoware_freespace_planner/config/freespace_planner.param.yaml, planning/autoware_obstacle_stop_planner/config/common.param.yaml, planning/autoware_obstacle_stop_planner/config/obstacle_stop_planner.param.yaml, planning/autoware_obstacle_stop_planner/schema/obstacle_stop_planner.schema.json, planning/autoware_static_centerline_generator/config/common.param.yaml, planning/autoware_surround_obstacle_checker/config/surround_obstacle_checker.param.yaml
This PR aligns the parameters in **_other planning packages_**. …
=> fix(other_planning_packages): align the parameters with launcher

planning/autoware_mission_planner/README.md, planning/autoware_mission_planner/config/mission_planner.param.yaml, planning/autoware_mission_planner/src/mission_planner/mission_planner.cpp, planning/autoware_mission_planner/src/mission_planner/mission_planner.hpp
add option to prevent rerouting in autonomous driving mode
set true by default.
if false, reroute fails. if true, only safe reroute is allowed.
- Link
psim
set `false`
https://github.com/user-attachments/assets/6655a9d1-d3d8-4b57-8047-2861de81240c
2024/09/04 https://evaluation.tier4.jp/evaluation/reports/00d52220-01c8-5767-ae65-97fd3f71150c/?project_id=prd_jt
None.
None.
None.
=> feat(mission_planner): add option to prevent rerouting in autonomous driving mode

planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/debug.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection.hpp, planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/util.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/util.hpp
```
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/debug.cpp:162:0: style: The function 'createPointMarkerArray' is never used. [unusedFunction]
[[maybe_unused]] visualization_msgs::msg::Marker createPointMarkerArray(
^
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection.hpp:330:0: style: The function 'getAssociativeIds' is never used. [unusedFunction]
const std::set<lanelet::Id> & getAssociativeIds() const { return associative_ids_; }
^
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection.hpp:332:0: style: The function 'getOcclusionUUID' is never used. [unusedFunction]
UUID …
```
=> fix(autoware_behavior_velocity_intersection_module): fix unusedFunction

common/tier4_adapi_rviz_plugin/src/state_panel.cpp
```
common/tier4_adapi_rviz_plugin/src/state_panel.cpp:29:0: style: The function 'Bool2String' is never used. [unusedFunction]
inline std::string Bool2String(const bool var)
^
```
- Link
None.
None.
None.
=> fix(tier4_adapi_rviz_plugin): fix unusedFunction

perception/autoware_object_merger/config/object_association_merger.param.yaml
The default value of the merger priority was out of the enum range.
Fixed the default value to the explained mode `PriorityMode::Confidence = 2`.
- Link
None.
None.
None.
=> fix(autoware_object_merger): default merger priority within enum range

control/autoware_autonomous_emergency_braking/include/autoware/autonomous_emergency_braking/node.hpp, control/autoware_autonomous_emergency_braking/include/autoware/autonomous_emergency_braking/utils.hpp, control/autoware_autonomous_emergency_braking/src/node.cpp, control/autoware_autonomous_emergency_braking/src/utils.cpp, control/autoware_autonomous_emergency_braking/test/test.cpp
This PR adds a debug marker for the convex hulls created by the AEB, which can help debugging and tuning point cloud parameters for the module. 
Example
- Link
PSim
None.
None.
None.
=> feat(autonomous_emergency_braking): add markers showing aeb convex hull polygons for debugging purposes

planning/autoware_rtc_interface/src/rtc_interface.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/interface.cpp
A new filed `tier4_rtc_msgs/State state` was introduced in the rt cooperate status previously. This field is used to observe the state transition of the rtc message. However, inappropriate state transition could be occurred since there was no limitation in the rtc interface module.
In this PR, I have checked the state transition inside the `updateCooperateStatus` function.
Additionally, the RTC state transition is fixed in the lane change module.
The cooperateState status would transit to failure when the module can only transit to FAILURE.
Being specific, it should not transit to FAILED inside `planWaitingApproval` function, although the lane change module status could be kept `WAITING_APPROVAL` due to `canTransitFailureState` function. …
=> feat(rtc_interface, lane_change): check state transition for cooperate status

system/autoware_component_monitor/package.xml
This PR adds two more maintainers to the `autoware_component_monitor` package.
- https://github.com/autowarefoundation/autoware.universe/issues/8866
The package can be built with the package.xml changes.
None.
None.
None.
=> chore(autoware_component_monitor): add maintainers

planning/autoware_costmap_generator/CMakeLists.txt, planning/autoware_costmap_generator/include/autoware_costmap_generator/costmap_generator.hpp, planning/autoware_costmap_generator/nodes/autoware_costmap_generator/costmap_generator_node.cpp, planning/autoware_costmap_generator/package.xml, planning/autoware_costmap_generator/param/costmap_generator_node_parameters.yaml
This PR enables costmap_generator to handle parameters using [generate_parameter_library](https://github.com/PickNikRobotics/generate_parameter_library).
Psim
Evaluator: https://evaluation.tier4.jp/evaluation/reports/e9343e43-03e0-577b-90b9-659ce867bd4d?project_id=prd_jt
The node `costmap_generator` does not have dynamic parameters.
None.
None.
=> feat(costmap_generator): integrate generate_parameter_library

planning/motion_velocity_planner/autoware_motion_velocity_planner_node/src/node.cpp, planning/motion_velocity_planner/autoware_motion_velocity_planner_node/src/node.hpp
- Link
Tested along with https://github.com/autowarefoundation/autoware.universe/pull/8870 and https://github.com/autowarefoundation/autoware.universe/pull/8798
- [TIER IV evaluator](https://evaluation.tier4.jp/evaluation/reports/b1ba3d8c-840a-5009-b4c6-e791023593eb?project_id=prd_jt): all pass.
-  [TIER IV evaluator (processing time)](https://evaluation.tier4.jp/evaluation/reports/ed032970-c8f7-544d-b48a-6cd1740a200f?project_id=prd_jt): 4134/4144.
Psim and evaluator
None.
None.
None.
=> perf(motion_velocity_planner): fix heavy resampling and transform lookup

planning/autoware_velocity_smoother/src/smoother/analytical_jerk_constrained_smoother/velocity_planning_utils.cpp
Some debug logging of the `analytical_jerk_constrained_smoother` can take a lot of time (I observed up to 20ms when running locally), even when debug logging is disabled.
I have not found a nice solution so this PR simply removes the logging code.
- Link
None.
None.
None.
=> perf(motion_velocity_smoother): remove some heavy debug logging

planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/README.md, planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/config/crosswalk.param.yaml, planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/manager.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp
This PR updates the algorithm for calculating the stop position for pedestrians.
Except for the exceptional behavior, the updated algorithm is as follows
1. select the nearest stop position from the map and the pedestrians
2. modify or select the stop position, taking acceleration and limit safety margin distance into account.
3. check if the selected stopping point is appropriate for the braking distance.
launch PR: https://github.com/autowarefoundation/autoware_launch/pull/1162
None.
None.
None.
=> feat(crosswalk)!: update stop position caluculation

planning/behavior_path_planner/autoware_behavior_path_planner/src/behavior_path_planner_node.cpp
This is a fix based on cppcheck syntaxError warnings.
```
planning/behavior_path_planner/autoware_behavior_path_planner/src/behavior_path_planner_node.cpp:71:67: error: syntax error: { . size [syntaxError]
std::vector<std::vector<std::string>> slot_configuration{slots.size()};
^
```
- Link
None.
None.
None.
=> fix(autoware_behavior_path_planner): fix syntaxError

planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/src/scene.cpp
Sometimes, a lot of messages are shown by following code. I fixed the log level to debug.
```c++
RCLCPP_INFO(logger_, "object ttc is %f", ttc);
```
- Link
None.
None.
None.
=> fix(blind_spot): hide debug information

planning/autoware_rtc_interface/src/rtc_interface.cpp
In the previous PR, the below state transition was not allowed.
- FAILED -> FAILED
- SUCCESS -> SUCCESS
This PR allows the above state transition.
https://github.com/autowarefoundation/autoware.universe/pull/8855
None.
None.
None.
=> fix(rtc_interface): update cooperateStatus state transition

simulator/autoware_carla_interface/CMakeLists.txt, simulator/autoware_carla_interface/setup.py
`carla_interface` attempts to access the `ROS_VERSION` environment variable, but it is not available at build time
This PR removes code that accesses `ROS_VERSION` as it's not being currently used anywhere.
- Link
https://github.com/autowarefoundation/autoware-deb-packages/issues/97
None.
None.
None.
=> fix: removed access to unused ROS_VERSION environment variable.

planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/manager.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/src/scene_module_interface.cpp
Fix following errors.
```
[WARN 1726569408.484871194] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner.RTCInterface[crosswalk]]: [updateCooperateStatus] uuid : 2e724f3abb0e7ab455bc829c9b6e834b cannot transit from RUNNING to WAITING_FOR_EXECUTION
...
[WARN 1726569444.580775651] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner.RTCInterface[intersection_occlusion]]: [updateCooperateStatus]  Cannot register RUNNING as initial state
```
- Link
None.
None.
None.
=> fix(bvp): fix rtc state update logic

common/autoware_overlay_rviz_plugin/autoware_overlay_rviz_plugin/src/speed_limit_display.cpp, common/tier4_state_rviz_plugin/src/autoware_state_panel.cpp, common/tier4_state_rviz_plugin/src/custom_button.cpp, common/tier4_state_rviz_plugin/src/custom_segmented_button_item.cpp, common/tier4_state_rviz_plugin/src/custom_slider.cpp, common/tier4_state_rviz_plugin/src/custom_toggle_switch.cpp, common/tier4_state_rviz_plugin/src/include/custom_button.hpp, common/tier4_state_rviz_plugin/src/include/custom_segmented_button_item.hpp, common/tier4_state_rviz_plugin/src/include/custom_toggle_switch.hpp, common/tier4_state_rviz_plugin/src/include/material_colors.hpp
Some minimal updates to the style to correct the look overall according to the qt5ct PR as well
- Related Issue:
- https://github.com/autowarefoundation/autoware/issues/4534
None.
None.
None.
=> style: update state panel plugin

planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/interface/scene_module_interface.hpp
Fix rtc state transition error for behavior_path_planner modules.
Specifically, the following warning would be fixed.
```
[component_container_mt-33] [WARN] [1726603502.777678240] [planning.scenario_planning.lane_driving.behavior_planning.behavior_path_planner.RTCInterface[goal_planner]]: [updateCooperateStatus]  Cannot register RUNNING as initial state
```
- https://github.com/autowarefoundation/autoware.universe/pull/8883
- https://github.com/autowarefoundation/autoware.universe/pull/8855
None.
None.
None.
=> fix(behavior_path_planner): fix rtc state update logic

launch/tier4_planning_launch/launch/scenario_planning/parking.launch.xml, planning/autoware_costmap_generator/include/autoware_costmap_generator/costmap_generator.hpp, planning/autoware_costmap_generator/nodes/autoware_costmap_generator/costmap_generator_node.cpp, planning/autoware_costmap_generator/nodes/autoware_costmap_generator/object_map_utils.cpp, planning/autoware_costmap_generator/package.xml
This PR attempt to fix some rare performance issue with the `costmap_generator` by preventing the transform lookup from waiting up to 1s.
The timekeeper is also added to make performance issues easier to understand in the future.
- [TIER IV JIRA link](https://tier4.atlassian.net/browse/RT0-33246)
None.
None.
None.
=> perf(costmap_generator): prevent long transform lookup and add timekeeper

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/scene.hpp
Fix rtc state transition error for static_obstacle_avoidance module.
There was a problem that the same UUID was used for candidates shift line, although the cooperateStatus has been changed to FAILED.
```
[WARN] [1726619093.498740895] [planning.scenario_planning.lane_driving.behavior_planning.behavior_path_planner.RTCInterface[static_obstacle_avoidance_left]]: [updateCooperateStatus] uuid : 8c50d0b80d2539be7fc496c00e153d7a cannot transit from FAILED to WAITING_FOR_EXECUTION
```
This happens when `removeCandidateRTCStatus` function is once called, and the candidate is re-registered in the next period.
This PR generates a new UUID once the `removeCandidateRTCStatus` function is called.
- https://github.com/autowarefoundation/autoware.universe/pull/8883
- …
=> fix(static_obstacle_avoidance): update UUID when candidate shift is empty

common/autoware_perception_rviz_plugin/src/object_detection/object_polygon_detail.cpp
This is a fix based on cppcheck unusedFunction warnings.
`get_2d_shape_marker_ptr` was suppressed because it is used in the template function `get_shape_marker_ptr`, which is used in other packages.
```
common/autoware_perception_rviz_plugin/src/object_detection/object_polygon_detail.cpp:541:0: style: The function 'get_2d_shape_marker_ptr' is never used. [unusedFunction]
visualization_msgs::msg::Marker::SharedPtr get_2d_shape_marker_ptr(
^
```
- Link
None.
None.
None.
=> fix(autoware_perception_rviz_plugin): fix unusedFunction

planning/behavior_path_planner/autoware_behavior_path_start_planner_module/config/start_planner.param.yaml, vehicle/autoware_raw_vehicle_cmd_converter/config/raw_vehicle_cmd_converter.param.yaml
align parameter in the yaml file to the [autoware_launch](https://github.com/autowarefoundation/autoware_launch)
No testing.
None.
None.
None.
=> refactor(start_planner,raw_vechile_cmd_converter): align parameter with autoware_launch's parameter

common/interpolation/include/interpolation/spline_interpolation.hpp, common/interpolation/package.xml, common/interpolation/src/spline_interpolation.cpp, common/interpolation/test/src/test_spline_interpolation.cpp, common/interpolation/test/src/test_spline_interpolation_points_2d.cpp
Fixed a bug in the coefficient calculation of spline interpolation.
- [TIERIV internal link](https://tier4.atlassian.net/browse/AEAP-1689)
https://evaluation.tier4.jp/evaluation/reports/1e862479-c0b9-5432-9b06-ca8817bb99f1?project_id=prd_jt
None.
None.
None.
=> fix(interpolation): fix bug of interpolation

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/interface.cpp
The following WARNING appears when the lane change module `plan()' function is called at it's first time.
```
[WARN] [1726626143.864958038] [planning.scenario_planning.lane_driving.behavior_planning.behavior_path_planner.RTCInterface[lane_change_right]]: [isForceActivated] uuid : cad0dcbfaf3c176c142900e225f85ae5 is not found
[WARN] [1726626143.864981280] [planning.scenario_planning.lane_driving.behavior_planning.behavior_path_planner.RTCInterface[lane_change_right]]: [updateCooperateStatus]  Cannot register RUNNING as initial state
```
This PR solves the warnings by checking whether the uuid is registered or not.
If the uuid is not registered the cooperateStatus state is set to WAITING_FOR_EXECUTION and the force activation is not checked.
- …
=> fix(lane_change): set initail rtc state properly

common/autoware_universe_utils/include/autoware/universe_utils/geometry/ear_clipping.hpp, common/autoware_universe_utils/src/geometry/ear_clipping.cpp
Refactor the triangulation function to use `std::vector` instead of raw pointer.
- Link
Random and Unit tested.
None.
None.
None.
=> refactor(universe_utils): remove raw pointers from the triangulation function

planning/motion_velocity_planner/autoware_motion_velocity_planner_common/test/test_collision_checker.cpp
Disable a test in `autoware_motion_velocity_planner_common` that is randomly failing and can bother other PRs.
- Link
None.
None.
None.
=> fix(motion_velocity_planner): disable randomly failing test

planning/behavior_path_planner/autoware_behavior_path_avoidance_by_lane_change_module/config/avoidance_by_lane_change.param.yaml, planning/behavior_path_planner/autoware_behavior_path_avoidance_by_lane_change_module/src/manager.cpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/data_structs.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp
Removes unused variables in static_obstacle_avoidance module and avoidance_by_lane_change moduel.
https://github.com/autowarefoundation/autoware_launch/pull/1176
None.
| Change type   | Parameter Name | 
|:--------------|:---------------|
| Removed | `car.execute_num`   |
| Removed | `truck.execute_num`   |
| Removed | `bus.execute_num`   |
| Removed | `trailer.execute_num`   |
| Removed | `unknown.execute_num`   | 
| Removed | `bicycle.execute_num`   | 
| Removed | `motorcycle.execute_num`   | 
| Removed | `pedestrian.execute_num`   | 
None.
=> fix(static_obstacle_avoidance, avoidance_by_lane_change): remove unused variable

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/config/lane_change.param.yaml, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/data_structs.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/utils.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/manager.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp
Currently, LC path does not guarantee that ego vehicle is within target lane boundaries at all times during LC maneuver. Specifically for larger vehicles (such as bus or trucks), it is more likely that the vehicle frame exceeds the target lane boundary into the next lane during the maneuver, which can result in an unsafe interaction with other vehicles on the road.
This PR adds a safety check for LC candidate path to ensure ego footprint maintains a safe distance from the target lane far boundary for all path points.
If a candidate path does not satisfy the condition it will still be added as a valid path, but will not be considered a safe path.
[autoware_launch PR](https://github.com/autowarefoundation/autoware_launch/pull/1157)
PSIM.
None.
| Change type   | Parameter Name | Type     | …
=> feat(lane_change): add checks to ensure the edge of vehicle do not exceed target lane boundary when changing lanes

simulator/simple_planning_simulator/src/simple_planning_simulator/vehicle_model/sim_model_delay_steer_acc_geared.cpp, simulator/simple_planning_simulator/src/simple_planning_simulator/vehicle_model/sim_model_delay_steer_acc_geared_wo_fall_guard.cpp
Remove unnecessary lines containing only semicolon.
https://github.com/autowarefoundation/autoware.universe/blob/6465aafcfd2073beb61b2e32b71a48ba0f66811f/simulator/simple_planning_simulator/src/simple_planning_simulator/vehicle_model/sim_model_delay_steer_acc_geared.cpp#L69-L73
https://github.com/autowarefoundation/autoware.universe/blob/6465aafcfd2073beb61b2e32b71a48ba0f66811f/simulator/simple_planning_simulator/src/simple_planning_simulator/vehicle_model/sim_model_delay_steer_acc_geared_wo_fall_guard.cpp#L69-L73
None.
build succeeded.
None.
None.
None.
=> chore(simple_planning_simulator): remove unnecessary lines

control/autoware_autonomous_emergency_braking/include/autoware/autonomous_emergency_braking/node.hpp, control/autoware_autonomous_emergency_braking/include/autoware/autonomous_emergency_braking/utils.hpp, control/autoware_autonomous_emergency_braking/src/node.cpp, control/autoware_autonomous_emergency_braking/src/utils.cpp
This PR makes the convex hull markers 3D to facilitate PC clustering parameter tuning
- Link
PSim
None.
None.
None.
=> feat(autonomous_emergency_braking): make hull markers 3d

.github/actions/build-and-test-differential/action.yaml, .github/workflows/build-and-test.yaml, sensing/autoware_gnss_poser/src/gnss_poser_node.cpp
Right now ccache stats are not correct because it accumulates over time.
> https://linux.die.net/man/1/ccache
> 
> ```
> -z, --zero-stats
> Zero the cache statistics (but not the configured limits).
> ```
This command will reset it before the build. So we can get to know the real stats after build.
None.
None.
None.
=> ci(build-and-test): reset ccache stats before build

perception/autoware_image_projection_based_fusion/src/roi_cluster_fusion/node.cpp
The roi cluster fusion updates cluster classification from the roi to the cluster.
However, the existence probability was not updated.
This PR adds the existence probability update from the roi to the cluster.
- Link
None.
None.
None.
=> fix(autoware_image_projection_based_fusion): roi cluster fusion has no existence probability update

perception/perception_utils/CMakeLists.txt, perception/perception_utils/package.xml, perception/perception_utils/test/test_utils.cpp
- Add unit test to make sure the output image after apply `run_lenth_encoder` and `run_length_decoder` is the same with the input image 
- Link
None.
None.
None.
=> chore(perception_utils): add unit test

vehicle/autoware_raw_vehicle_cmd_converter/src/accel_map.cpp, vehicle/autoware_raw_vehicle_cmd_converter/src/brake_map.cpp, vehicle/autoware_raw_vehicle_cmd_converter/src/csv_loader.cpp, vehicle/autoware_raw_vehicle_cmd_converter/src/pid.cpp, vehicle/autoware_raw_vehicle_cmd_converter/src/steer_map.cpp, vehicle/autoware_raw_vehicle_cmd_converter/test/test_autoware_raw_vehicle_cmd_converter.cpp
This PR adds test to cover more lines inside the raw_vehicle_cmd_converter package.
Also refactor src/include according to clang-tidy
```
100% tests passed, 0 tests failed out of 5
Label Time Summary:
copyright     =   0.42 sec*proc (1 test)
cppcheck      =   0.14 sec*proc (1 test)
gtest         =   0.09 sec*proc (1 test)
lint_cmake    =   0.12 sec*proc (1 test)
linter        =   1.42 sec*proc (4 tests)
xmllint       =   0.74 sec*proc (1 test)
Total Test time (real) =   1.52 sec
---
Finished <<< autoware_raw_vehicle_cmd_converter [3.08s]
Summary: 1 package finished [3.89s]
```
None.
None.
None.
=> test(raw_vehicle_cmd_converter): add tests

common/tier4_camera_view_rviz_plugin/src/bird_eye_view_controller.cpp
Due to a modification to cppcheck's CI, comment suppression is no longer required for items that previously generated warnings.
```
common/tier4_camera_view_rviz_plugin/src/bird_eye_view_controller.cpp:103:0: information: Unmatched suppression: unusedFunction [unmatchedSuppression]
void BirdEyeViewController::handleMouseEvent(rviz_common::ViewportMouseEvent & event)
^
```
- Link
None.
None.
None.
=> fix(tier4_camera_view_rviz_plugin): fix unmatchedSuppression

common/autoware_universe_utils/include/autoware/universe_utils/geometry/alt_geometry.hpp, common/autoware_universe_utils/src/geometry/alt_geometry.cpp, common/autoware_universe_utils/test/src/geometry/test_alt_geometry.cpp
This PR enables to support non-convex polygons and adds the following and some utility functions to reduce dependence on Boost.Geometry.
|Boost.Geometry <br> (`boost::geometry`)|alternative <br> (`autoware::universe_utils`)|supported types|
|----|----|----|
|`envelope()`|`envelope()`|polygon|
|`simplify()`|`simplify()`|line (point list)|
Notes:
- Polygons **do have** closing points (i.e. the last vertex in the list should match the first, as any polygon given is considered to be closed).
- https://github.com/autowarefoundation/autoware.universe/issues/8128
```
colcon test --packages-select autoware_universe_utils
```
None.
None.
None.
=> feat(autoware_universe_utils): reduce dependence on Boost.Geometry

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp
Inside `fillAvoidanceTargetObjects` function, `filterTargetObjects` and `updateRoadShoulderDistance` are called sequentially.
Both function calls `getRoadShoulderDistance` function, which is relatively time consuming (refer to figure).
The `updateRoadShoulderDistance` function updates the target object's distance to road shoulder (`to_road_shoulder_distance`) and avoidance margin (`avoid_margin`) according to the clip object information.
However, this calculation would be redundant if there is no clip objects.
This PR will resolve the above problem. 
None.
None.
None.
=> fix(static_obstacle_avoidance): remove redundant calculation

planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
Currently, after the backward path go over the default stop line, the crosswalk module do not treat as ego is yielding, 
This PR change this behavior with the assumption that default stop pose is null only if the ego has passed the default stop pose.
https://github.com/autowarefoundation/autoware.universe/pull/8853
tier4 internal tests
None.
None.
None.
=> fix(crosswalk): change exceptional handling

simulator/simple_planning_simulator/include/simple_planning_simulator/vehicle_model/sim_model_delay_steer_map_acc_geared.hpp, simulator/simple_planning_simulator/src/simple_planning_simulator/utils/csv_loader.cpp, simulator/simple_planning_simulator/src/simple_planning_simulator/vehicle_model/sim_model_actuation_cmd.cpp, vehicle/autoware_raw_vehicle_cmd_converter/src/accel_map.cpp, vehicle/autoware_raw_vehicle_cmd_converter/src/brake_map.cpp, vehicle/autoware_raw_vehicle_cmd_converter/src/csv_loader.cpp, vehicle/autoware_raw_vehicle_cmd_converter/src/steer_map.cpp
Both the `simple_planning_simulator` and `autoware_raw_vehicle_cmd_converter` package has a CSV loader class.
As a member function they have `getRowIndex` and `getColumnIndex`.
However, the `getRowIndex` seems to read index for columns, and the `getColumnIndex` seems to read index for rows.
These functions have been swapped in this PR.
Furthermore, some refactoring was made based on clang tidy.
None
Was able to drive autonomously in PSim.
Parameters were changed as below:
`simulator_model.param.yaml`
```
/**:
simulated_frame_id: "base_link"
origin_frame_id: "map"
vehicle_model_type: "ACTUATION_CMD"
initialize_source: "INITIAL_POSE_TOPIC"
timer_sampling_time_ms: 25
add_measurement_noise: False
enable_road_slope_simulation: True
vel_lim: 50.0
vel_rate_lim: 7.0
steer_lim: …
```
=> fix(simple_planning_simulator, raw_vehicle_cmd_converter): swap row index and column index for csv loader 

perception/autoware_detected_object_feature_remover/CMakeLists.txt, perception/autoware_detected_object_feature_remover/package.xml, perception/autoware_detected_object_feature_remover/test/test_detected_object_feature_remover_node.cpp
Add unit testing for `DetectedObjectFeatureRemover`.
- Link
None.
None.
None.
=> test(autoware_detected_object_feature_remover): add unit testing for the node

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/util.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_searcher.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/util.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/test/test_util.cpp
Check to see if the goal footprint fits in the lane with the goal  searcher.
yellow lanes are for lane departure check
- before: pull over lane and current lane
- after: pull over lane and the same segment
- internal ticket :https://tier4.atlassian.net/browse/RT0-31696
- psim
- 2024/09/10 https://evaluation.tier4.jp/evaluation/reports/e13e23cb-0404-5bba-858a-398b77bdc320/?project_id=prd_jt
- unit test
- evaluator
2024/09/11 https://evaluation.tier4.jp/evaluation/reports/9f6d71af-0ee5-598b-95d0-2e90e82c811e/?project_id=prd_jt
2024/09/26 https://evaluation.tier4.jp/evaluation/reports/ea55e52a-002c-5fd0-b87f-8d750378c461/?project_id=prd_jt
3871/3871
None.
None.
None.
=> feat(goal_planner): use neighboring lane of pull over lane to check goal footprint

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp
Function `isSatisfiedWithCommonCondition` is called for each object.
However, inside this function there was calculation (specifically route handler based calculation) irrelevant to object information.
In this PR I have replaced some calculation outside the for loop.  
None
None.
None.
None.
=> refactor(static_obstacle_avoidance): move route handler based calculation outside loop

common/autoware_universe_utils/include/autoware/universe_utils/geometry/alt_geometry.hpp, common/autoware_universe_utils/include/autoware/universe_utils/geometry/ear_clipping.hpp, common/autoware_universe_utils/src/geometry/alt_geometry.cpp, common/autoware_universe_utils/src/geometry/ear_clipping.cpp, common/autoware_universe_utils/src/ros/marker_helper.cpp
This PR eliminates `autoware::universe_utils::triangulate()`'s dependence on Boost.Geometry.
- https://github.com/autowarefoundation/autoware.universe/issues/8128
```
colcon test --packages-select autoware_universe_utils --event-handlers console_cohesion+
```
gives the following result:
```
1: [ RUN      ] geometry.intersectPolygonWithHoles
1: [       OK ] geometry.intersectPolygonWithHoles (0 ms)
1: [ RUN      ] geometry.intersectConcavePolygonRand
1: polygons_nb = 500, vertices = 4, 236652 / 250000 pairs with intersects
1: 	Intersect:
1: 		Boost::geometry = 175.75 ms
1: 		GJK = 40.57 ms
1: 		SAT = 52.92 ms
1: 	No Intersect:
1: 		Boost::geometry = 17.93 ms
1: 		GJK = 4.80 ms
1: 		SAT = 3.44 ms
1: 	Total:
1: 		Triangulation = 0.63 ms
1: polygons_nb = 500, vertices = 5, …
```
=> refactor(universe_utils): eliminate dependence on Boost.Geometry

perception/lidar_centerpoint/package.xml
Hotfix to awsim-stable branch
https://github.com/autowarefoundation/autoware.universe/pull/3824
x
We confirmed that the build of autoware successed
None.
None.
None.
=> build(iron): add missing dependencies for centerpoint (#3824)

common/autoware_overlay_rviz_plugin/autoware_overlay_rviz_plugin/src/speed_display.cpp
On AWSIM (VPP reports reverse speed as negative) to keep showing speed as a positive value just added a std::abs on the value received
None.
None.
None.
=> fix(speed_display): always show speed positive and depend on gear for negatives

perception/autoware_multi_object_tracker/lib/tracker/motion_model/bicycle_motion_model.cpp, perception/autoware_multi_object_tracker/lib/tracker/motion_model/ctrv_motion_model.cpp
The Kalman filter update for yaw should be limited. The innovation should occur to the small side of the angle difference.
The innovation value `fixed_yaw` was calculated but not used.
This PR is to implement the range-limited innovation `fixed_yaw`.
- Link
None.
None.
None.
=> fix(autoware_multi_object_tracker): update yaw with range-limited innovation

planning/behavior_path_planner/autoware_behavior_path_avoidance_by_lane_change_module/src/scene.cpp, planning/behavior_path_planner/autoware_behavior_path_avoidance_by_lane_change_module/src/scene.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/scene.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/base_class.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/calculation.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/data_structs.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/utils.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/interface.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/calculation.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp
This PR adds TransientData to standardize commonly used values in the lane change module, such as the current lanes' buffer and the distance to the terminal start and end. The goal is to ensure consistency when calculating limits and lengths.
- https://github.com/autowarefoundation/autoware.universe/pull/8849 → 8849 has caused some degradation in the Evaluator, so it has been set to draft for the time being. 8954 is a subset of 8849 and has no scenario failures.
- PSIM
- Evaluator: [TIER IV internal link](https://evaluation.tier4.jp/evaluation/reports/b1ac9431-b48b-5c7d-b6c7-a1ea6f8854e1?project_id=prd_jt)
None.
None.
None.
=> refactor(lane_change): add TransientData to store commonly used lane change-related variables.

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/utils.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp
Before abort path is computed, lane change module check if the remaining distance is sufficient to re-attempt lane change.
Using the following  image as example
The total remaining distance should be
```
abort start distance + abort distance + min stopping dist + min dist buffer <= dist to terminal
```
The current computation only
```
abort distance + min dist buffer <= dist to terminal
```
which is incorrect.
This PR aims to fix the incorrect  computation.
- [TIER IV internal link](https://star4.slack.com/archives/C04HK9T2E0N/p1727415580962899?thread_ts=1727381189.356109&cid=C04HK9T2E0N)
- [TIER IV Internal link](https://tier4.atlassian.net/browse/RT1-7991)
- [Evaluator](https://evaluation.tier4.jp/evaluation/reports/bf054099-496a-52e7-8291-955797e8b13c?project_id=prd_jt)
None.
None. …
=> fix(lane_change): fix abort distance enough check

perception/autoware_map_based_prediction/src/path_generator.cpp
The previous update of the `map_based_prediction` had multiple function changes of path generation algorithms.
One of them was `searchProperStartingRefPathIndex`, which finds a proper reference path position to generate natural path.
In case of the `lateral_duration` was too short to reach the reference path point, the path tend to be generated unnaturally.
Planning simulator (PSIM)
condition: simulated car with speed of 1.5 m/s. (which makes the fixed `lateral_duration` short to reach the reference path point.
Before 
After
https://github.com/autowarefoundation/autoware.universe/pull/8602
https://github.com/autowarefoundation/autoware.universe/pull/8811
Tested in PSIM
None.
None.
None.
=> fix(autoware_map_based_prediction): adjust lateral duration when object is behind reference path

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp
updating path during not decided status caseus freespace planning cancel.
In this PR, when freespace planning stop lane parking path update.
before
https://github.com/user-attachments/assets/d5e08d99-db33-471a-a74c-d13a2f1f51ad
after
https://github.com/user-attachments/assets/a23e4f29-acb1-433a-a553-820d2013322d
- Link
psim
2024/09/27 https://evaluation.tier4.jp/evaluation/reports/6b782f80-be1a-5495-84f2-92f4314a972f/?project_id=prd_jt
2024/09/27 https://evaluation.tier4.jp/evaluation/reports/1c24e789-e846-58a4-8a75-7ab696289e7c/?project_id=prd_jt
None.
None.
None.
=> fix(goal_planner): fix freespace planning chattering

perception/autoware_lidar_centerpoint/lib/ros_utils.cpp
The centerpoint velocity is in the world_frame_id. The object message velocity is based on its object's pose. 
This PR is fixing the implementation of the velocity conversion to follow those definition.
The yaw rate (rotation speed) is not obtained, so set it as zero.
Before
Yaw rate (Red circle) are shown as a large or none.
Velocity(Red stick) heads to its bounding box (Blue box) orientation, which is not always true.
After
The bounding box orientation and the velocity vector is not always the same direction, but it is as the inference result.
Yaw rates are zero.
- Link
None.
None.
None.
=> fix(autoware_lidar_centerpoint): convert object's velocity to follow its definition

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/path_safety_checker/path_safety_checker_parameters.hpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/src/marker_utils/utils.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_safety_checker/objects_filtering.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_safety_checker/safety_check.cpp, planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/start_planner_module.cpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp
`ExtendedPredictedObject` contains several `msg` that is not being used anywhere.
Furthermore, available member variable, classification, can be be directly instantiated.
This PR also adds 2 new member variables, `initial_polygon` and `dist_from_ego`. The module owners are expected to refactor their own module so that we dont have to call `createPolygon` so often.
- Link
None.
None.
None.
=> refactor(bpp): simplify ExtendedPredictedObject and add new member variables

common/autoware_universe_utils/src/ros/marker_helper.cpp
```
common/autoware_universe_utils/src/ros/marker_helper.cpp:20:0: information: Unmatched suppression: unusedFunction [unmatchedSuppression]
visualization_msgs::msg::Marker createDefaultMarker(
^
common/autoware_universe_utils/src/ros/marker_helper.cpp:45:0: information: Unmatched suppression: unusedFunction [unmatchedSuppression]
visualization_msgs::msg::Marker createDeletedDefaultMarker(
^
common/autoware_universe_utils/src/ros/marker_helper.cpp:59:0: information: Unmatched suppression: unusedFunction [unmatchedSuppression]
void appendMarkerArray(
^
```
- Link
None.
None.
None.
=> fix(autoware_universe_utils): fix unmatchedSuppression

localization/autoware_pose_covariance_modifier/README.md
The line breaks appear to be incorrect in mermaid chart. This PR fixes this problem.
Refactor line breaks ``` \n ``` with ```<br/>```
Note:  Also updated dead links:
- (../../localization/ndt_scan_matcher)  -->  (../../localization/autoware_ndt_scan_matcher)
-  (../../localization/ekf_localizer) --> (../../localization/autoware_ekf_localizer).
- Link
None.
None.
None.
=> docs(autoware_pose_cov_modifier): fix line breaks and dead links

common/autoware_universe_utils/test/src/geometry/test_alt_geometry.cpp, common/autoware_universe_utils/test/src/geometry/test_geometry.cpp
This PR avoids tests of `autoware_universe_utils` package from timing out.
```
colcon test --packages-select autoware_universe_utils --event-handlers console_cohesion+
```
Before:
```
Label Time Summary:
copyright     =   3.87 sec*proc (1 test)
cppcheck      =   0.16 sec*proc (1 test)
gtest         =  48.97 sec*proc (1 test)
lint_cmake    =   0.15 sec*proc (1 test)
linter        =   5.05 sec*proc (4 tests)
xmllint       =   0.87 sec*proc (1 test)
Total Test time (real) =  54.03 sec
```
After:
```
Label Time Summary:
copyright     =   3.56 sec*proc (1 test)
cppcheck      =   0.14 sec*proc (1 test)
gtest         =  14.69 sec*proc (1 test)
lint_cmake    =   0.14 sec*proc (1 test)
linter        =   4.90 sec*proc (4 tests)
xmllint       =   1.06 sec*proc (1 test)
Total Test time (real) = …
```
=> fix(universe_utils): avoid test timeout

control/autoware_autonomous_emergency_braking/src/node.cpp
Some sanity checks for empty paths/vectors
- Link
PSim
None.
None.
None.
=> feat(autonomous_emergency_braking): add sanity chackes

perception/autoware_lidar_centerpoint/include/autoware/lidar_centerpoint/ros_utils.hpp, perception/autoware_lidar_centerpoint/lib/ros_utils.cpp, perception/autoware_lidar_centerpoint/test/test_ros_utils.cpp
Fix the twist covariance converter considering the twist covariance matrix is based on the object coordinate.
Before
The twist (velocity) estimation of the centerpoint is based on the base_link frame. The covariance is also the same.
In the shown case, a vehicle in front has velocity negative Y direction to the ego vehicle, and the covariance of the velocity is large in Y direction.
However, the twist covariance is directly inserted to Y coordinate of the object message, and it showed large twist covariance in lateral object velocity.
After
The twist covariance is translated to the object coordinate, which is by its definition. 
As result, the twist covariance is oriented in Y direction to the ego vehicle, as expected.
NOTE: There is not inference of covariance of XY and YX. The …
=> fix(autoware_lidar_centerpoint): fix twist covariance orientation

planning/behavior_path_planner/autoware_behavior_path_avoidance_by_lane_change_module/src/interface.cpp, planning/behavior_path_planner/autoware_behavior_path_avoidance_by_lane_change_module/src/manager.cpp
```
planning/behavior_path_planner/autoware_behavior_path_avoidance_by_lane_change_module/src/interface.cpp:48:0: information: Unmatched suppression: unusedFunction [unmatchedSuppression]
bool AvoidanceByLaneChangeInterface::isExecutionRequested() const
^
planning/behavior_path_planner/autoware_behavior_path_avoidance_by_lane_change_module/src/interface.cpp:55:0: information: Unmatched suppression: unusedFunction [unmatchedSuppression]
void AvoidanceByLaneChangeInterface::processOnEntry()
^
planning/behavior_path_planner/autoware_behavior_path_avoidance_by_lane_change_module/src/manager.cpp:190:0: information: Unmatched suppression: unusedFunction [unmatchedSuppression]
SMIPtr …
```
=> fix(autoware_behavior_path_avoidance_by_lane_change_module): fix unmatchedSuppression

planning/behavior_path_planner/autoware_behavior_path_planner_common/src/turn_signal_decider.cpp
When ego vehicle stops in the lane with turn_direction right or left, blinker turns off because of the following implementation.
```
const auto requires_turn_signal = [&](const auto & lane_attribute) {
constexpr double stop_velocity_threshold = 0.1;
return (
lane_attribute == "right" || lane_attribute == "left" ||
(lane_attribute == "straight" && current_vel < stop_velocity_threshold));
};
```
The expected behavior for the scene is the keep turning on when the ego vehicle is on the lane with turn_direction is right or left.
So changed so that keep turning on blinker in this PR.
- [TIERIV INTERNAL TICKET LINK](https://tier4.atlassian.net/browse/RT0-33633)
None.
None.
=> feat(autoware_behavior_path_planner_common): disable feature of turning off blinker at low velocity

planning/autoware_mission_planner/src/lanelet2_plugins/default_planner.cpp, planning/autoware_mission_planner/src/lanelet2_plugins/utility_functions.cpp, planning/autoware_mission_planner/src/lanelet2_plugins/utility_functions.hpp
move anonymous functions to utility  for unit test:  https://github.com/autowarefoundation/autoware.universe/pull/9011
- Link
None.
None.
None.
=> refactor(mission_planner): move anonymous functions to utils and add namespace

perception/autoware_multi_object_tracker/CMakeLists.txt, perception/autoware_multi_object_tracker/include/autoware/multi_object_tracker/object_model/object_model.hpp, perception/autoware_multi_object_tracker/include/autoware/multi_object_tracker/tracker/model/bicycle_tracker.hpp, perception/autoware_multi_object_tracker/include/autoware/multi_object_tracker/tracker/model/big_vehicle_tracker.hpp, perception/autoware_multi_object_tracker/include/autoware/multi_object_tracker/tracker/model/normal_vehicle_tracker.hpp, perception/autoware_multi_object_tracker/include/autoware/multi_object_tracker/tracker/model/pedestrian_tracker.hpp, perception/autoware_multi_object_tracker/include/autoware/multi_object_tracker/tracker/motion_model/bicycle_motion_model.hpp, perception/autoware_multi_object_tracker/include/autoware/multi_object_tracker/tracker/motion_model/ctrv_motion_model.hpp, perception/autoware_multi_object_tracker/include/autoware/multi_object_tracker/tracker/motion_model/cv_motion_model.hpp, perception/autoware_multi_object_tracker/include/autoware/multi_object_tracker/uncertainty/uncertainty_processor.hpp, perception/autoware_multi_object_tracker/lib/tracker/model/bicycle_tracker.cpp, perception/autoware_multi_object_tracker/lib/tracker/model/big_vehicle_tracker.cpp, perception/autoware_multi_object_tracker/lib/tracker/model/normal_vehicle_tracker.cpp, perception/autoware_multi_object_tracker/lib/tracker/model/pedestrian_tracker.cpp, perception/autoware_multi_object_tracker/lib/tracker/motion_model/bicycle_motion_model.cpp, perception/autoware_multi_object_tracker/lib/tracker/motion_model/ctrv_motion_model.cpp, perception/autoware_multi_object_tracker/lib/tracker/motion_model/cv_motion_model.cpp, perception/autoware_multi_object_tracker/lib/uncertainty/uncertainty_processor.cpp, perception/autoware_multi_object_tracker/src/multi_object_tracker_node.cpp, perception/autoware_multi_object_tracker/src/multi_object_tracker_node.hpp
1. The detected object covariance matrix is modeled if the incoming detectedObject does not have one.
This PR separates the covariance matrix modeling part out from the trackers.
2. Initial values of the tracker was defined by a initialization function, which is inefficient. The initial values were defined from the initializer.
This PR does not have behavioral change.
- Link
Tested in the [TIER IV CLOUD](https://evaluation.tier4.jp/evaluation/reports/a2aab07d-0743-5e7f-b710-3966356b8761?project_id=prd_jt)
None.
None.
None.
=> refactor(autoware_multi_object_tracker): separate detected object covariance modeling

launch/tier4_control_launch/launch/control.launch.xml
This PR fixes AEB predicted object input topic.
- Link https://github.com/autowarefoundation/autoware.universe/issues/9008
None.
None.
None.
=> fix(tier4_control_launch): fix aeb input predicted object topic name

planning/autoware_mission_planner/CMakeLists.txt, planning/autoware_mission_planner/test/test_utility_functions.cpp
Line Coverage 0.0% -> 96.1%
before
after
depends https://github.com/autowarefoundation/autoware.universe/pull/9012
- Link
None.
None.
None.
=> test(mission_planner): add unit tests of utility functions

perception/autoware_multi_object_tracker/include/autoware/multi_object_tracker/tracker/motion_model/bicycle_motion_model.hpp, perception/autoware_multi_object_tracker/include/autoware/multi_object_tracker/tracker/motion_model/ctrv_motion_model.hpp, perception/autoware_multi_object_tracker/lib/tracker/motion_model/bicycle_motion_model.cpp, perception/autoware_multi_object_tracker/lib/tracker/motion_model/ctrv_motion_model.cpp
Revert the tracker orientation when the velocity exceed the maximum reverse velocity
The tracking object orientation is determined by the initial object orientation.
If the initial object yaw was reversed (180 deg rotated), and the object moves forward, the object is tracked as reversed direction.
This mismatch can cause yaw instability in case of the bicycle motion model.
- Before
The screenshot shows trackedObjects. Triangles of the bounding box corners indicates front of the object. 
The right object heads left upper side but its velocity is right bottom side. This shows the object is reversed motion. 
If the detector has high confidence of its headings, this situation can be trusted. But, the current lidar-based detection has high error rate on its headings.
Considering the current …
=> feat(autoware_multi_object_tracker): set maximum reverse velocity to bicycle and crtv motion models

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/decision_state.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_module.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/pull_over_planner_base.cpp
- due to a mistake, the curvature of parking_path was calculated from full_path, which caused massive "[WARN 1727950663.638648154] [goal_planner_util]: path.points.size() != curvatures.size() in checkObjectsCollision(). judge as non collision" error
- the time DecidingState started was not properly updated
- transition from NOT_DECIDED to DECIDING was inactivated by mistake
- 
- https://evaluation.tier4.jp/evaluation/reports/58a47f88-1f99-50dd-acdf-910a2227a75f?project_id=prd_jt
- https://evaluation.tier4.jp/evaluation/reports/51a8cf14-f91a-5b30-876f-663435e9a095?project_id=prd_jt
None.
None.
None.
=> fix(goal_planner): fix parking_path curvature and DecidingState transition

planning/behavior_path_planner/autoware_behavior_path_avoidance_by_lane_change_module/package.xml, planning/behavior_path_planner/autoware_behavior_path_external_request_lane_change_module/package.xml
update maintainers of avoidance_by_lane_change and external_request_lane_change
None.
N/A
None.
None.
None.
=> chore(avoidance_by_lane_change, external_request_lane_change): add maintainers

planning/autoware_path_optimizer/src/mpt_optimizer.cpp
add warn msg
- Link
only github ci
None.
None.
None.
=> chore(path_optimizer): add warn msg for exceptional behavior

launch/tier4_perception_launch/launch/object_recognition/detection/filter/pointcloud_map_filter.launch.py
- Remove duplicated parameters declaration in launch.py files to avoid maintenance cost. 
- Link
None.
None.
None.
=> refactor(tier4_perception_launch): remove duplicated parameter declaration

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/path_safety_checker/objects_filtering.hpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_safety_checker/objects_filtering.cpp, planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/start_planner_module.cpp
Function `filterObjectsByVelocity` has an argument `remove_above_threshold` which is used to ignore the upper limit or not.
The upper velocity limit would be ignored when the value is `false` and it might lead to misunderstanding.
This PR swaps the condition, by ignoring the upper velocity limit when `remove_above_threshold` is `true`.
None
None.
None.
None.
=> fix(behavior_path_planner_common): swap boolean for filterObjectsByVelocity

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/pull_over_planner/freespace_pull_over.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/pull_over_planner/geometric_pull_over.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/pull_over_planner/pull_over_planner_base.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/pull_over_planner/shift_pull_over.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/freespace_pull_over.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/geometric_pull_over.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/pull_over_planner_base.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/shift_pull_over.cpp
depends https://github.com/autowarefoundation/autoware.universe/pull/8994
-
- https://evaluation.tier4.jp/evaluation/reports/8b73230c-35fd-5f0f-8dc6-45da66abcd7b?project_id=prd_jt
None.
None.
None.
=> refactor(goal planner): hold modified_goal in PullOverPath ,copy modified goal once from background thread

planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/manager.cpp
In the intersection module, member variable `rtc_enabled_` was not set appropriately. 
This functions sets the `rtc_enabled_` according to the RTC interface.
https://github.com/autowarefoundation/autoware.universe/pull/5697
None.
None.
None.
=> fix(intersection): set RTC enable

codecov.yaml
additional for for https://github.com/autowarefoundation/autoware.universe/pull/9030, because it removed the changes made by https://github.com/autowarefoundation/autoware.universe/pull/9028
- Link
None.
None.
None.
=> chore(codecov): fix perception component

planning/autoware_surround_obstacle_checker/CMakeLists.txt, planning/autoware_surround_obstacle_checker/package.xml, planning/autoware_surround_obstacle_checker/src/node.cpp, planning/autoware_surround_obstacle_checker/src/node.hpp, planning/autoware_surround_obstacle_checker/test/test_surround_obstacle_checker.cpp
=> test(surround_obstacle_checker): add unit tests

common/tier4_planning_rviz_plugin/include/tier4_planning_rviz_plugin/path/display_base.hpp
Updating the style of the path/trajectory display plugin
- https://www.youtube.com/playlist?list=PL97OXOB9UA-gSyZWr3VVn4dNnBtt0lqTp
Just run the planning sim demo.
We don't need to modify autoware_launch rviz config file because the defaults are set in the plugin.
New parameters are added:
- property_min_color_("Min Velocity Color", QColor("`#3F2EE3`"), "", &property_path_view_)
- property_mid_color_("Mid Velocity Color", QColor("`#208AAE`"), "", &property_path_view_)
- property_max_color_("Max Velocity Color", QColor("`#00E678`"), "", &property_path_view_)
- property_fade_out_distance_{"Fade Out Distance", 0.0, "[m]", &property_path_view_}
None.
=> feat(tier4_planning_rviz_plugin): set path colors from rviz and add fade_out feature

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/scene.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/base_class.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/utils.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/utils.hpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/utils.cpp
Refactor get_lane_change_lanes function.
Two utilities functions are added;
1. to_geom_msg_pose which will create pose from lanelet points
2. is_mandatory_lane_change which list the lane change type for mandatory lane change
- Link
Compile autoware and run psim
None.
None.
None.
=> refactor(lane_change): refactor get_lane_change_lanes function

control/autoware_mpc_lateral_controller/src/vehicle_model/vehicle_model_bicycle_kinematics.cpp
fix calculation method of predicted trajectory.
As a premise, the MPC optimization result considers a first-order delay applied to the ideal steering angle calculated based on the path curvature.
The original method for calculating the predicted path was as follows:
```
// update state in the world coordinate
const auto updateState = [&](
const Eigen::VectorXd & state_w, const Eigen::MatrixXd & input,
const double dt, const double velocity) {
const auto yaw = state_w(2);
const auto steer = state_w(3);
const auto desired_steer = input(0);
Eigen::VectorXd dstate = Eigen::VectorXd::Zero(4);
dstate(0) = velocity * std::cos(yaw);
dstate(1) = velocity * std::sin(yaw);
dstate(2) = velocity * std::tan(steer) / m_wheelbase;
dstate(3) = -(steer - desired_steer) / m_steer_tau;
// Note: don't do …
```
=> fix(autoware_mpc_lateral_controller): fix calculation method of predicted trajectory

planning/autoware_mission_planner/test/test_lanelet2_plugins_default_planner.cpp
add test of default_planner
line converage is
- mission planner 75.4 %
- lanelet2_plugins 86.1 %
before
after
planned route is like
- Link
unit tests
None.
None.
None.
=> test(mission_planner): add test of default_planner

planning/autoware_obstacle_cruise_planner/config/obstacle_cruise_planner.param.yaml, planning/autoware_obstacle_cruise_planner/include/autoware/obstacle_cruise_planner/common_structs.hpp, planning/autoware_obstacle_cruise_planner/include/autoware/obstacle_cruise_planner/node.hpp, planning/autoware_obstacle_cruise_planner/include/autoware/obstacle_cruise_planner/polygon_utils.hpp, planning/autoware_obstacle_cruise_planner/src/node.cpp, planning/autoware_obstacle_cruise_planner/src/polygon_utils.cpp
- To increase the response capacity of the `obstacle_cruise_planner` within the scope of Dense-Urban ODD, we want it to be sensitive to dynamic objects approaching from outside Ego's path and stop if there is a collision risk, as mentioned in the issue.
- Avoiding unnecessary stopping of Ego in the presence of transient objects that do not pose a risk of collision. To solve these problems and provide a more human-like autonomous driving experience, we needed to improve the stop behavior of the `obstacle_cruise_planner`.
- We want to improve the cruising behavior for the outside obstacle. If another vehicle in the side lanes is approaching Ego's trajectory, cruise planning starts too late. 
**Improvement on filtering:**
In `obstacle_cruise_planner`, all the `PredictedObjects` were filtered …
=> feat(obstacle_cruise_planner): improve stop and cruise behavior for cut-in & out

perception/autoware_lidar_transfusion/lib/postprocess/postprocess_kernel.cu, perception/autoware_lidar_transfusion/lib/ros_utils.cpp
We found that the 3d bounding boxes were rotated by 90 degrees for transfusion
=> feat(autoware_lidar _ransfusion): fix 3d bounding box orientation

planning/behavior_path_planner/autoware_behavior_path_planner_common/CMakeLists.txt, planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/drivable_area_expansion/footprints.hpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/package.xml, planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/drivable_area_expansion/footprints.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/test/test_footprints.cpp
Add unit test for `autoware_behavior_path_planner_common/src/utils/drivable_area_expansion/footprints.cpp`.
Coclon test
```
1: [----------] 3 tests from FootprintTest
1: [ RUN      ] FootprintTest.translate_polygon
1: [       OK ] FootprintTest.translate_polygon (0 ms)
1: [ RUN      ] FootprintTest.create_footprint
1: [       OK ] FootprintTest.create_footprint (0 ms)
1: [ RUN      ] FootprintTest.create_object_footprints
1: [       OK ] FootprintTest.create_object_footprints (0 ms)
1: [----------] 3 tests from FootprintTest (0 ms total)
```
None.
None.
None.
=> test(bpp_common): add test for footprint

planning/behavior_path_planner/autoware_behavior_path_planner/test/test_utils.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/CMakeLists.txt, planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/utils.hpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/utils.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/test/test_utils.cpp
- Add unit test for object related function in `behavior_path_planner_common module/utils/utils.cpp`.
- Change some function name to snake case. (Applied to functions only used inside the utils.cpp)
Colcon test
```
1: [ RUN      ] BehaviorPathPlanningUtilTest.l2Norm
1: [       OK ] BehaviorPathPlanningUtilTest.l2Norm (0 ms)
1: [ RUN      ] BehaviorPathPlanningUtilTest.checkCollisionBetweenPathFootprintsAndObjects
1: [       OK ] BehaviorPathPlanningUtilTest.checkCollisionBetweenPathFootprintsAndObjects (0 ms)
1: [ RUN      ] BehaviorPathPlanningUtilTest.checkCollisionBetweenFootprintAndObjects
1: [       OK ] BehaviorPathPlanningUtilTest.checkCollisionBetweenFootprintAndObjects (0 ms)
1: [ RUN      ] BehaviorPathPlanningUtilTest.calcLateralDistanceFromEgoToObject
1: [       OK ] …
```
=> test(bpp_common): add test for object related functions

planning/behavior_path_planner/autoware_behavior_path_planner_common/CMakeLists.txt, planning/behavior_path_planner/autoware_behavior_path_planner_common/test/test_parking_departure_utils.cpp
Add unit test for `behavior_path_planner_common module/utils/parking_departure/utils.cpp`.
Colcon test
```
3: [==========] Running 7 tests from 1 test suite.
3: [----------] Global test environment set-up.
3: [----------] 7 tests from BehaviorPathPlanningParkingDepartureUtil
3: [ RUN      ] BehaviorPathPlanningParkingDepartureUtil.calcFeasibleDecelDistance
3: [       OK ] BehaviorPathPlanningParkingDepartureUtil.calcFeasibleDecelDistance (0 ms)
3: [ RUN      ] BehaviorPathPlanningParkingDepartureUtil.modifyVelocityByDirection
3: [       OK ] BehaviorPathPlanningParkingDepartureUtil.modifyVelocityByDirection (0 ms)
3: [ RUN      ] BehaviorPathPlanningParkingDepartureUtil.updatePathProperty
3: [       OK ] BehaviorPathPlanningParkingDepartureUtil.updatePathProperty (0 ms)
3: [ RUN      ] …
```
=> test(bpp_common): add test for parking departure utils

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_module.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/pull_over_planner/pull_over_planner_base.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/thread_data.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp
depends
- https://github.com/autowarefoundation/autoware.universe/pull/8994
- https://github.com/autowarefoundation/autoware.universe/pull/9006
- https://tier4.atlassian.net/browse/RT1-7966
- https://evaluation.tier4.jp/evaluation/reports/12476487-bc54-5b1c-9e24-c43206fb17e2?page_size=50&project_id=prd_jt
None.
None.
None.
=> refactor(goal_planner): remove modified_goal in ThreadDafeData

perception/autoware_lidar_transfusion/include/autoware/lidar_transfusion/utils.hpp, perception/autoware_lidar_transfusion/lib/network/network_trt.cpp
When making minor architectural changes to onnx checkpoints, we found that the tensorrt IO tensor order changed, which results in the current code failing because the order of tensors is fixed in current code.
https://github.com/autowarefoundation/autoware.universe/blob/c2438fd2841bce7792be4bc57e88edbe6b34276d/perception/autoware_lidar_transfusion/include/autoware/lidar_transfusion/utils.hpp#L39
It seems that the tensor output order of the optimized tensorrt engine can be different from onnx IO order, but the tensor names match the onnx IO names. So, it is better to use the names from trt engine API to find the IO tensor positions. 
We also found out that the current deployed models have faulty output names i.e the names of dir_cls_pred0 and bbox_pred0 are swapped, so they do not work …
=> fix(autoware_lidar_transfusion): set tensor names by matching with predefined values.

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_module.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/thread_data.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp
depends https://github.com/autowarefoundation/autoware.universe/pull/9063
- https://tier4.atlassian.net/browse/RT1-7966
- https://evaluation.tier4.jp/evaluation/reports/fc9ed895-a2d8-53b1-889c-b09d1b4bffc4?project_id=prd_jt
None.
None.
None.
=> refactor(goal_planner): remove prev_data / last_path_idx_time from ThreadSafeData

planning/behavior_path_planner/autoware_behavior_path_planner_common/CMakeLists.txt, planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/occupancy_grid_based_collision_detector/occupancy_grid_based_collision_detector.hpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/occupancy_grid_based_collision_detector/occupancy_grid_based_collision_detector.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/test/test_occupancy_grid_based_collision_detector.cpp
- Add unit test for `behavior_path_planner_common module/utils/occupancy_grid_based_collision_detector`.
- Add doxygen
- Change some function name to snake case. (Applied to functions only used inside the file)
- Delete unused function
Colcon test
```
3: [==========] Running 6 tests from 1 test suite.
3: [----------] Global test environment set-up.
3: [----------] 6 tests from OccupancyGridBasedCollisionDetectorTest
3: [ RUN      ] OccupancyGridBasedCollisionDetectorTest.discretize_angle
3: [       OK ] OccupancyGridBasedCollisionDetectorTest.discretize_angle (0 ms)
3: [ RUN      ] OccupancyGridBasedCollisionDetectorTest.pose2index
3: [       OK ] OccupancyGridBasedCollisionDetectorTest.pose2index (0 ms)
3: [ RUN      ] OccupancyGridBasedCollisionDetectorTest.index2pose
3: [       OK ] …
```
=> test(bpp_common): add test for occupancy grid based collision detector

planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
If the crosswalk width is narrow than sparse_resample_interval, which is had coded as 4.0m, passing direction calculation may failed because idx1 == idx2 is satisfied.
This PR fix this issue, and now both of the same directional objects and the opposite directional objects are ignored as a crosswalk user.
https://github.com/autowarefoundation/autoware.universe/pull/5849
scenario tests
None.
None.
None.
=> fix(crosswalk): fix passing direction calclation for the objects

control/autoware_autonomous_emergency_braking/include/autoware/autonomous_emergency_braking/node.hpp, control/autoware_autonomous_emergency_braking/src/node.cpp
modified the AEB to publish virtual walls in a format that matches the virtual stop walls from the planning module. 
If other package in control module inserts stop line, I expect this topic's visual control is placed under the new VirtualWall directory.
The PR for the changes on the autoware_launch side is [here](https://github.com/autowarefoundation/autoware_launch/pull/1187).
run psim
original display
updated display
None.
None.
<!-- ⬇️🔴
=> refactor(autoware_autonomous_emergency_braking): rename info_marker_publisher to virtual_wall_publisher

common/autoware_osqp_interface/CMakeLists.txt, common/autoware_osqp_interface/design/osqp_interface-design.md, common/autoware_osqp_interface/include/autoware/osqp_interface/csc_matrix_conv.hpp, common/autoware_osqp_interface/include/autoware/osqp_interface/osqp_interface.hpp, common/autoware_osqp_interface/include/autoware/osqp_interface/visibility_control.hpp, common/autoware_osqp_interface/package.xml, common/autoware_osqp_interface/src/csc_matrix_conv.cpp, common/autoware_osqp_interface/src/osqp_interface.cpp, common/autoware_osqp_interface/test/test_csc_matrix_conv.cpp, common/autoware_osqp_interface/test/test_osqp_interface.cpp, control/autoware_mpc_lateral_controller/include/autoware/mpc_lateral_controller/qp_solver/qp_solver_osqp.hpp, control/autoware_mpc_lateral_controller/package.xml, control/autoware_trajectory_follower_base/package.xml, planning/autoware_obstacle_cruise_planner/include/autoware/obstacle_cruise_planner/optimization_based_planner/velocity_optimizer.hpp, planning/autoware_obstacle_cruise_planner/package.xml, planning/autoware_path_optimizer/include/autoware/path_optimizer/mpt_optimizer.hpp, planning/autoware_path_optimizer/package.xml, planning/autoware_path_optimizer/src/mpt_optimizer.cpp, planning/autoware_path_smoother/include/autoware/path_smoother/elastic_band.hpp, planning/autoware_path_smoother/package.xml, planning/autoware_path_smoother/src/elastic_band.cpp, planning/autoware_static_centerline_generator/package.xml, planning/autoware_velocity_smoother/include/autoware/velocity_smoother/node.hpp, planning/autoware_velocity_smoother/include/autoware/velocity_smoother/smoother/l2_pseudo_jerk_smoother.hpp, planning/autoware_velocity_smoother/include/autoware/velocity_smoother/smoother/linf_pseudo_jerk_smoother.hpp, planning/autoware_velocity_smoother/package.xml
Added `autoware` prefix to `osqp_interface`
None.
None.
None.
=> refactor(osqp_interface): added autoware prefix to osqp_interface

planning/autoware_freespace_planner/CMakeLists.txt, planning/autoware_freespace_planner/include/autoware/freespace_planner/utils.hpp, planning/autoware_freespace_planner/src/autoware_freespace_planner/freespace_planner_node.cpp, planning/autoware_freespace_planner/src/autoware_freespace_planner/utils.cpp
All functions used in freespace planner are declared and defined withing freespace_planner node header and source file.
For better organization and to simplify unit testing this PR moves relevant functions in separate utils files and put the function under util namespace within freespace planner namespace.
None.
- Build successfully.
None.
None.
None.
=> refactor(freespace_planner): move functions to utils

planning/behavior_path_planner/autoware_behavior_path_planner_common/CMakeLists.txt, planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/path_safety_checker/objects_filtering.hpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_safety_checker/objects_filtering.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/test/test_objects_filtering.cpp
Add test for `behavior_path_planner_common module/utils/path_safety_checker/objects_filtering.cpp`.
Functions that doesn't take lanelet (route handler) as arguments are first implemented.
Also, a small refactor was made for `velocity_filter` function inside namespace `autoware::behavior_path_planner::utils::path_safety_checker::filter`.
Colcon test
```
2: [----------] 9 tests from BehaviorPathPlanningObjectsFiltering
2: [ RUN      ] BehaviorPathPlanningObjectsFiltering.velocity_filter
2: [       OK ] BehaviorPathPlanningObjectsFiltering.velocity_filter (0 ms)
2: [ RUN      ] BehaviorPathPlanningObjectsFiltering.position_filter
2: [       OK ] BehaviorPathPlanningObjectsFiltering.position_filter (0 ms)
2: [ RUN      ] BehaviorPathPlanningObjectsFiltering.is_within_circle
2: [       OK ] …
```
=> test(bpp_common): add test for objects filtering except for lanelet using functions

launch/tier4_perception_launch/launch/object_recognition/detection/filter/pointcloud_map_filter.launch.py, perception/autoware_compare_map_segmentation/config/distance_based_compare_map_filter.param.yaml, perception/autoware_compare_map_segmentation/config/voxel_based_approximate_compare_map_filter.param.yaml, perception/autoware_compare_map_segmentation/config/voxel_based_compare_map_filter.param.yaml, perception/autoware_compare_map_segmentation/config/voxel_distance_based_compare_map_filter.param.yaml, perception/autoware_compare_map_segmentation/schema/distance_based_compare_map_filter.schema.json, perception/autoware_compare_map_segmentation/schema/voxel_based_approximate_compare_map_filter.schema.json, perception/autoware_compare_map_segmentation/schema/voxel_based_compare_map_filter.schema.json, perception/autoware_compare_map_segmentation/schema/voxel_distance_based_compare_map_filter.schema.json, perception/autoware_compare_map_segmentation/src/voxel_grid_map_loader/voxel_grid_map_loader.cpp, perception/autoware_compare_map_segmentation/src/voxel_grid_map_loader/voxel_grid_map_loader.hpp
- This PR will limit autoware to use split map pointcloud for `dynamic_map_loader` in `compare_map_segmentation`. Otherwise, ERROR message will be output as below
```
[component_container_mt-1] [ERROR] [1728371768.729818629] [perception.object_recognition.detection.voxel_based_compare_map_filter]: Map was not split or split map grid size is too large. Split map with grid size smaller than 100.000000
```
- This PR should be merged after PR: https://github.com/autowarefoundation/autoware_launch/pull/1184
- [TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT1-4938)
- Link
None.
None.
None.
=> fix(compare_map_segmentation): throw runtime error when using non-split map pointcloud for DynamicMapLoader

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/scene.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/calculation.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/utils.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp
Simple refactoring to reduce clang-tidy warnings.
- Link
None.
None.
None.
=> refactor(lane_change): reducing clang-tidy warnings

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/helper.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp
Sometimes, the avoidance module inserted stop point even when the ego overran the dead line to avoid/return manuever.
In this PR, I fixed logic not to insert stop point if the ego exceeds stop  line in order to prevent stuck.
Additionally, I fixed not to insert stop point on dead line for return maneuver if it's in following condition:
- there is no new shift line.
- return shift line is NOT feasible.
- ticket: [TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT0-33610)
https://github.com/user-attachments/assets/5130c5e6-9eb8-4812-9d3a-7e6f5df7381c
None.
None.
None.
=> fix(avoidance): don't insert stop line if the ego can't avoid or return

simulator/autoware_carla_interface/setup.py
This PR resolves the colcon warning and errors in the `autoware_carla_interface` package:
- Renamed the resource file to `autoware_carla_interface` for proper ROS 2 package indexing.
- Added missing `__init__.py` files for Python package recognition, which previously caused the following error: 
`package init file 'src/autoware_carla_interface/__init__.py' not found (or not a regular file)`.
- Fixed the warning: 
`WARNING:colcon.colcon_ros.task.ament_python.build: Package 'autoware_carla_interface' doesn't explicitly install a marker in the package index`.
- Link (if applicable)
Build and colcon test for the `autoware_carla_interface` module, verifying that the marker warning and colcon errors are resolved.
None.
None.
None.
=> fix(autoware_carla_interface): resolve init file error and colcon marker warning

perception/autoware_ground_segmentation/src/scan_ground_filter/node.cpp, perception/autoware_ground_segmentation/src/scan_ground_filter/node.hpp
The scan ground algorithm has a checker that the point is above the height from the ground line. The ground line is calculated from previous grid points. 
This PR implements the linear least square method for the ground line fitting. This implementation reduces impact of noisy lidar points. 
- Link
* evaluator
[TIER IV Cloud](https://evaluation.tier4.jp/evaluation/reports/fee16f15-6f03-5bd6-8b57-de798dc171ae?project_id=prd_jt)
* computing time: Computing time difference is negligible.
Before
```
🌲 Total Processing Time Tree 🌲
100.00% faster_filter: total 9441.63 [ms], avg. 16.86 [ms], run count: 560
├── 78.64% convertPointcloudGridScan: total 7425.25 [ms], avg. 13.26 [ms], run count: 560
│   ├── 56.39% azimuth_angle_grouping: total 5323.95 [ms], avg. 9.51 [ms], run …
```
=> feat(autoware_ground_segmentation): implementing linear least square fitting for local gradient calculation

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/CMakeLists.txt, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/manager.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/base_class.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/manager.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/test/test_lane_change_scene.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/interface/scene_module_manager_interface.hpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/utils.cpp
Add simple test for normal lane change class.
- Link
None.
None.
None.
=> feat(lane_change): add unit test for normal lane change class (RT1-7970)

common/autoware_test_utils/include/autoware_test_utils/autoware_test_utils.hpp, common/autoware_test_utils/src/autoware_test_utils.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/test/test_utils.cpp
Some test require `PathWithLaneId` as input, so this PR adds a simple path generator.
None
Build and colcon test for behavior_path_planner_common module.
None.
None.
None.
=> feat(test_utils): add simple path with lane id generator

planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection.cpp
Pass-judge handling was not implemented for red/arrow-signal case. This causes the vehicle to react to the NPCs on the entire attention area if the signal changed to blue while passing the intersection.
- https://tier4.atlassian.net/browse/RT0-33896
the pass judge line does not turn red
https://github.com/user-attachments/assets/73141b80-396c-4483-86a5-ca289b2f87bb
the pass judge line turns red
https://github.com/user-attachments/assets/35b42515-5ab7-41d7-bc92-8e09f024c34f
None.
None.
None.
=> fix(intersection): handle pass judge after red/arrow-signal to ignore NPCs after the signal changed to green again

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_module.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/thread_data.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp
move last_previous_module_output from ThreadSafeData to GoalPlannerData because it is only used in `onTimer` calculation
- Link
https://evaluation.tier4.jp/evaluation/reports/4458f31f-bb44-5493-958d-4bea4c7443bb?project_id=prd_jt&state=failed
None.
None.
None.
=> refactor(goal_planner): move last_previous_module_output_path out of ThreadSafeData

planning/behavior_path_planner/autoware_behavior_path_planner_common/CMakeLists.txt, planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/path_utils.hpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_utils.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/test/test_path_utils.cpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp
- Add unit test for behavior_path_planner_common module `/utils/path_utils.cpp`
- Remove unnecessary function
Colcon build
```
1: [----------] 10 tests from BehaviorPathPlanningPathUtilTest
1: [ RUN      ] BehaviorPathPlanningPathUtilTest.calcPathArcLengthArray
1: [       OK ] BehaviorPathPlanningPathUtilTest.calcPathArcLengthArray (0 ms)
1: [ RUN      ] BehaviorPathPlanningPathUtilTest.resamplePathWithSpline
1: [       OK ] BehaviorPathPlanningPathUtilTest.resamplePathWithSpline (0 ms)
1: [ RUN      ] BehaviorPathPlanningPathUtilTest.getIdxByArclength
1: [       OK ] BehaviorPathPlanningPathUtilTest.getIdxByArclength (0 ms)
1: [ RUN      ] BehaviorPathPlanningPathUtilTest.clipPathLength
1: [       OK ] BehaviorPathPlanningPathUtilTest.clipPathLength (0 ms)
1: [ RUN      ] …
```
=> test(bpp_common): add test for path utils

planning/behavior_velocity_planner/autoware_behavior_velocity_virtual_traffic_light_module/CMakeLists.txt, planning/behavior_velocity_planner/autoware_behavior_velocity_virtual_traffic_light_module/src/scene.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_virtual_traffic_light_module/src/utils.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_virtual_traffic_light_module/src/utils.hpp
move some functions to utils for unit tests
- https://github.com/autowarefoundation/autoware.universe/pull/9107
2024/10/17 https://evaluation.tier4.jp/evaluation/reports/12a8ef10-d489-5d4e-bcba-cb48a51df2ad/?project_id=prd_jt
None.
None.
None.
=> refactor(virtual_traffic_light): move to utils for unit test

launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.xml, planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/include/autoware/behavior_velocity_crosswalk_module/util.hpp, planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/debug.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/occluded_crosswalk.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/occluded_crosswalk.hpp, planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
Fix a mistake in the detection range calculation.
- Before: detection range (`m`) = time for ego to reach the crosswalk (`s`) _divided_ by occluded object velocity (`m/s`).
- seconds divided by meters per seconds --> second squared per meter :warning:
- After: detection range (`m`) = time for ego to reach the crosswalk (`s`) _multiplied_ by occluded object velocity (`m/s`).
- seconds multiplied by meters per seconds --> meters. :heavy_check_mark: 
Also do a small refactoring and add some markers to visualize the occlusion detection area
- Link
None.
None.
None.
=> fix(crosswalk): fix occlusion detection range calculation and add debug markers

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp
I found a wrong implementation of envelope polygon update logic. It seemed that object's envelope polygon was updated even when the latest observed data was more acculate than previous one.
- Link
None.
None.
None.
=> fix(utils): fix envelope polygon update logic

planning/autoware_mission_planner/src/mission_planner/mission_planner.cpp
Looks like an implementation error.
If we do not return, an emtpy route may be set.
- Link
2024/10/21 https://evaluation.tier4.jp/evaluation/reports/d8006304-00be-5558-9c86-1576794020f1/?project_id=prd_jt
None.
None.
None.
=> fix(mission_planner): return without change_route if new route is empty 

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/type_alias.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/utils.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/package.xml, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/test/test_utils.cpp
Line coverage is increase from 33.5% to 50.5%.
- Link
None.
None.
None.
=> test(static_obstacle_avoidance): add unit test for utils functions

common/autoware_test_utils/include/autoware_test_utils/mock_data_parser.hpp, common/autoware_test_utils/src/autoware_test_utils.cpp, common/autoware_test_utils/src/mock_data_parser.cpp, common/autoware_test_utils/test/test_mock_data_parser.cpp, common/autoware_test_utils/test_data/path_with_lane_id_parser_test.yaml, planning/autoware_route_handler/test/test_route_handler.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/test/test_lane_change_scene.cpp
Some test might require path as input, so this PR adds a parser, so that user can use path for unit testing.
- Link
Build and test, and not unit test failure observed.
None.
None.
None.
=> feat(autoware_test_utils): add path with lane id parser

control/autoware_control_validator/README.md, control/autoware_control_validator/config/control_validator.param.yaml, control/autoware_control_validator/include/autoware/control_validator/control_validator.hpp, control/autoware_control_validator/msg/ControlValidatorStatus.msg, control/autoware_control_validator/package.xml, control/autoware_control_validator/src/control_validator.cpp
This PR add holding function and LPF for the velocity check.
in additon, velocity check is separated to two diags to trigger different MRM behavior.
launch PR: https://github.com/autowarefoundation/autoware_launch/pull/1193
- Link
tier4 internal tests
None.
None.
None.
=> feat(control_validator): add hold and lpf

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/CMakeLists.txt, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/examples/plot_map.cpp
=> chore(goal_planner): compare sampled/filtered candidate paths on plot

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp
suppress unnessesary warn message.
```
module doesn't have return shift line.
```
- Related PR: https://github.com/autowarefoundation/autoware.universe/pull/9089
None.
None.
None.
=> fix(static_obstacle_avoidance): suppress unnecessary warning

launch/tier4_map_launch/launch/map.launch.xml
The default value  of parameter `use_intra_process` is `false` in package [tier4_map_launch](https://github.com/autowarefoundation/autoware.universe/blob/ae24913390600d95b3194f7e3ddf43ac823261ce/launch/tier4_map_launch/launch/map.launch.xml#L15), but if set it to true, there will be an error. That's because map component uses [transient_local](https://github.com/autowarefoundation/autoware.universe/blob/main/map/map_loader/src/lanelet2_map_loader/lanelet2_map_loader_node.cpp#L130C75-L130C90), so it may not be possible to set use_intra_process=true. 
To avoid unnecessary errors, delete parameter `use_intra_process`.
**Parent Issue:** [issue 9117](https://github.com/autowarefoundation/autoware.universe/issues/9117)
Build successful.
None.
| Change type   | Parameter Name | Type     | …
=> fix(tier4_map_launch): remove parameter use_intra_process

vehicle/autoware_external_cmd_converter/CMakeLists.txt, vehicle/autoware_external_cmd_converter/config/test_external_cmd_converter.param.yaml, vehicle/autoware_external_cmd_converter/include/autoware_external_cmd_converter/node.hpp, vehicle/autoware_external_cmd_converter/package.xml, vehicle/autoware_external_cmd_converter/src/node.cpp, vehicle/autoware_external_cmd_converter/tests/test_external_cmd_converter.cpp
Add tests to increase test  coverage of external cmd converter
- Link
None.
None.
None.
=> feat(autoware_external_cmd_converter): add ext cmd converter tests

planning/behavior_velocity_planner/autoware_behavior_velocity_virtual_traffic_light_module/CMakeLists.txt, planning/behavior_velocity_planner/autoware_behavior_velocity_virtual_traffic_light_module/package.xml, planning/behavior_velocity_planner/autoware_behavior_velocity_virtual_traffic_light_module/test/test_utils.cpp
add unit tests for utils
- Link
unit test
```
5: [==========] Running 9 tests from 1 test suite.
5: [----------] Global test environment set-up.
5: [----------] 9 tests from VirtualTrafficLightTest
5: [ RUN      ] VirtualTrafficLightTest.CreateKeyValue
5: [       OK ] VirtualTrafficLightTest.CreateKeyValue (0 ms)
5: [ RUN      ] VirtualTrafficLightTest.ToAutowarePoints
5: [       OK ] VirtualTrafficLightTest.ToAutowarePoints (0 ms)
5: [ RUN      ] VirtualTrafficLightTest.CalcCenter
5: [       OK ] VirtualTrafficLightTest.CalcCenter (0 ms)
5: [ RUN      ] VirtualTrafficLightTest.CalcHeadPose
5: [       OK ] VirtualTrafficLightTest.CalcHeadPose (0 ms)
5: [ RUN      ] VirtualTrafficLightTest.ConvertToGeomPoint
5: [       OK ] VirtualTrafficLightTest.ConvertToGeomPoint (0 …
```
=> test(virtual_traffic_light): add unit tests for utils

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/drivable_area_expansion/static_drivable_area.cpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/util.cpp
Fix to not read invalid lanelet-map polygon layer ID. Add checking for invalid ID.
e.g. 1
```
'1724991158.7707169 [component_container_mt-35]     @     0x762a335f24d6 google::(anonymous namespace)::FailureSignalHandler()',
'1724991158.7741981 [component_container_mt-35]     @     0x762a32a42520 (unknown)',
'1724991158.7773001 [component_container_mt-35]     @     0x762a32a969fc pthread_kill',
'1724991158.7798305 [component_container_mt-35]     @     0x762a32a42476 raise',
'1724991158.7822514 [component_container_mt-35]     @     0x762a32a287f3 abort',
'1724991158.7848880 [component_container_mt-35]     @     0x762a32ea2b9e (unknown)',
'1724991158.7884953 [component_container_mt-35]     @     0x762a32eae20c (unknown)',
'1724991158.7907829 [component_container_mt-35]     @ …
```
=> fix(behavior_path_planner, behavior_velocity_planner): fix to not read invalid ID

perception/autoware_image_projection_based_fusion/src/pointpainting_fusion/node.cpp
Projected 2d point has 1.0 of depth
https://github.com/autowarefoundation/autoware.universe/pull/7053
- Link
None.
None.
None.
=> fix(autoware_image_projection_based_fusion): pointpainting bug fix for point projection

planning/behavior_path_planner/autoware_behavior_path_start_planner_module/config/start_planner.param.yaml
Update params to match launch after this is merged: https://github.com/autowarefoundation/autoware_launch/pull/1198
- Link
None.
None.
None.
=> feat(start_planner): update param to match launch

perception/autoware_map_based_prediction/include/map_based_prediction/map_based_prediction_node.hpp, perception/autoware_map_based_prediction/src/map_based_prediction_node.cpp
1. Refactoring lanelet path prediction part and the PosePath conversion part.
2. LRUCache implementation is changed from LaneletPaths to LaneletPath, which can improve the performance.
This PR does not include any logic changes.
[TIER IV INTERNAL](https://tier4.atlassian.net/browse/RT1-8214)
- Link
* [TIER IV Cloud](https://evaluation.tier4.jp/evaluation/reports/c83a4d75-3368-580c-8d75-d5cd931fe5b2?project_id=prd_jt)  814/814
* processing time
```
🌲 Total Processing Time Tree 🌲
100.00% objectsCallback: total 2805.00 [ms], avg. 5.99 [ms], run count: 468
├── 0.08% trafficSignalsCallback: total 2.18 [ms], avg. 0.00 [ms], run count: 468
├── 0.02% updateObjectData: total 0.69 [ms], avg. 0.00 [ms], run count: 6604
├── 36.16% getCurrentLanelets: total 1014.19 [ms], avg. 0.15 …
```
=> refactor(autoware_map_based_prediction): refactoring lanelet path prediction and pose path conversion

planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/traffic_light_utils.cpp
We should add guard to prevent accessing nullopt.
- Link
None.
None.
None.
=> fix(traffic_light_utils): prevent accessing nullopt

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/CMakeLists.txt, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/examples/plot_map.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_module.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/util.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_searcher.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/util.cpp
fix the goal pose orientation same as the pose of closest pose on reference path to the ego footprint's front heading
- https://tier4.atlassian.net/browse/RT1-7456
https://evaluation.tier4.jp/evaluation/reports/a55c06d7-9aec-5e8b-9f4d-b4b9dfc90799?project_id=prd_jt
None.
None.
None.
=> feat(goal_planner): align vehicle footprint heading parallel to parking side lane boundary

common/autoware_test_utils/include/autoware_test_utils/mock_data_parser.hpp, common/autoware_test_utils/src/mock_data_parser.cpp, common/autoware_test_utils/test/test_mock_data_parser.cpp
add parser mainly for 
- geometry_msgs
- nav_msgs
- Link
None.
None.
None.
=> feat(autoware_test_utils): add parser for geometry_msgs and others

control/autoware_collision_detector/CMakeLists.txt, control/autoware_collision_detector/README.md, control/autoware_collision_detector/config/collision_detector.param.yaml, control/autoware_collision_detector/include/autoware/collision_detector/node.hpp, control/autoware_collision_detector/launch/collision_detector.launch.xml, control/autoware_collision_detector/package.xml, control/autoware_collision_detector/src/node.cpp
This PR contains the initial implementation of the autoware_collision_detector.
Please refer to this [issue](https://github.com/autowarefoundation/autoware.universe/issues/9145) for further information.
- https://github.com/autowarefoundation/autoware.universe/issues/9145
Colcon build is successful 
Launch files for control would be changed in a different PR
| Name                                           | Type                                                   | Description                                                        |
| ---------------------------------------------- | ------------------------------------------------------ | ------------------------------------------------------------------ |
| `/perception/obstacle_segmentation/pointcloud` | …
=> feat(collision_detector): add autoware_collision_detector

launch/tier4_planning_launch/launch/scenario_planning/parking.launch.xml, planning/autoware_costmap_generator/include/autoware_costmap_generator/costmap_generator.hpp, planning/autoware_costmap_generator/include/autoware_costmap_generator/object_map_utils.hpp, planning/autoware_costmap_generator/include/autoware_costmap_generator/objects_to_costmap.hpp, planning/autoware_costmap_generator/nodes/autoware_costmap_generator/costmap_generator_node.cpp, planning/autoware_costmap_generator/nodes/autoware_costmap_generator/object_map_utils.cpp, planning/autoware_costmap_generator/nodes/autoware_costmap_generator/objects_to_costmap.cpp, planning/autoware_costmap_generator/package.xml
Decrease runtime from 20ms (with 30ms spikes) to 8ms (with 10ms spikes) in my local tests.
The resulting costmap is slightly different but.
| Current | With this PR |
| - | - |
| ![main_occ_grid](https://github.com/user-attachments/assets/6ae13cae-fe85-42d3-ad12-13c2b6903db7) | ![PR_occ_grid](https://github.com/user-attachments/assets/491600b8-2bfd-4ccf-ae3b-a8c5dfa216ec) |
- [TIER IV internal link](https://tier4.atlassian.net/browse/RT1-8233)
Psim
None.
None.
None.
=> perf(costmap_generator): manual blurring and fill polygons without OpenCV

common/autoware_test_utils/src/autoware_test_utils.cpp
Due to [this commit](https://github.com/autowarefoundation/autoware.universe/commit/20ebe9d4375e1349f75e45a0a471fcfb80258d72), `get_absolute_path_to_route` is now used and cppcheck suppression is no more necessary.
```
<error id="unmatchedSuppression" severity="information" msg="Unmatched suppression: unusedFunction" verbose="Unmatched suppression: unusedFunction">
<location file="common/autoware_test_utils/src/autoware_test_utils.cpp" line="143" column="0"/>
</error>
```
This is detected by `cppcheck-weekly` workflow
- this week: https://github.com/autowarefoundation/autoware.universe/actions/runs/11544993073
- last week: https://github.com/autowarefoundation/autoware.universe/actions/runs/11430819148
No
None.
None.
None.
=> fix(autoware_test_utils): remove unnecessary cppcheck suppression

.github/workflows/build-and-test-differential-arm64.yaml, .github/workflows/build-and-test-differential.yaml, .github/workflows/build-and-test.yaml
Due to codebuild machines possibly running out of memory, this PR attempts to reduce cores used by colcon build to indirectly reduce the memory usage.
- https://github.com/autowarefoundation/autoware.universe/issues/9088
Failed CIs:
- https://github.com/autowarefoundation/autoware.universe/actions/runs/11549889824/job/32143784165
- https://github.com/autowarefoundation/autoware.universe/actions/runs/11345527037
None.
None.
CI will run slower but more stable.
=> ci(build-and-test): reduce cores used by colcon build

common/autoware_motion_utils/include/autoware/motion_utils/trajectory_container/interpolator.hpp, common/autoware_motion_utils/include/autoware/motion_utils/trajectory_container/interpolator/detail/interpolator_mixin.hpp, common/autoware_motion_utils/include/autoware/motion_utils/trajectory_container/interpolator/spherical_linear.hpp, common/autoware_motion_utils/src/trajectory_container/interpolator/spherical_linear.cpp, common/autoware_motion_utils/test/src/trajectory_container/test_interpolator.cpp
Add spherical linear interpolator to trajectory container's interpolator.
- Link
None.
None.
None.
=> feat(autoware_motion_utils): add spherical linear interpolator

planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/decision_result.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/decision_result.hpp, planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection.cpp
- Link
see the attached image
None.
None.
None.
=> chore(intersection): print RTC status in diagnostic debug message

planning/autoware_costmap_generator/nodes/autoware_costmap_generator/object_map_utils.cpp, planning/autoware_costmap_generator/nodes/autoware_costmap_generator/objects_to_costmap.cpp
- https://github.com/autowarefoundation/autoware.universe/pull/9170 changed the include from `autoware_grid_map_utils/...` to `autoware/grid_map_utils`.
- https://github.com/autowarefoundation/autoware.universe/pull/9160 added includes in the old format.
So the current Autoware will not build and this PR fixes the issue.
- Link
None.
None.
None.
=> fix(costmap_generator): fix include for grid_map_utils

planning/behavior_path_planner/autoware_behavior_path_planner/include/autoware/behavior_path_planner/planner_manager.hpp, planning/behavior_path_planner/autoware_behavior_path_planner/src/behavior_path_planner_node.cpp, planning/behavior_path_planner/autoware_behavior_path_planner/src/planner_manager.cpp
suppress reseting root lanelet. 
root lanelet is not updated when 
- receiving same uuid route (e.g. rerouting with modifiled goal ) 
- failing getting closest lanelet while any approved module is running
- Link
2024/10/21 https://evaluation.tier4.jp/evaluation/reports/698116ac-225c-5427-9e03-ada876229a76/?project_id=prd_jt
before
https://github.com/user-attachments/assets/5a39cb7c-9be7-4653-9422-895437bf5c6e
after
https://github.com/user-attachments/assets/d545b28a-a039-4f87-8d72-49d33b7718f7
https://github.com/user-attachments/assets/77476e44-8c3b-47d5-ac71-b95f7bce8614
I also checked that root lanelet update when lc -> pull over 
https://github.com/user-attachments/assets/b29869f1-8978-41f6-9d00-730cbe47182a
None.
None.
None.
=> fix(behavior_path_planner): suppress reseting root lanelet

planning/autoware_mission_planner/src/mission_planner/mission_planner.cpp, planning/autoware_mission_planner/src/mission_planner/mission_planner.hpp, planning/autoware_route_handler/src/route_handler.cpp
Rerouting from the current ego position during a run is a potential source of bugs, as it is necessary to be aware of cases where the planner's internally maintained lanes are no longer included in the route.
Rerouting with modifed goal assumes a slight modification near the goal lane. It is assumed that ego and goal are at least an extension of current_route. Therefore, the start pose of current_route is used as the start pose. This prevents the route from being shortened by rerouting.
- https://github.com/autowarefoundation/autoware.universe/pull/8238
- https://github.com/autowarefoundation/autoware.universe/pull/9129
- https://tier4.atlassian.net/browse/RT1-7972
psim
2024/10/28 [Evaluator](https://evaluation.tier4.jp/evaluation/reports/bb5cf5a7-aa4f-5d45-8a39-a19fbbc6 …
=> feat(mission_planner): reroute with current route start pose when triggered by modifed goal

perception/autoware_traffic_light_arbiter/test/test_node.cpp
Fix build error in autoware_traffic_light_arbiter package.
https://github.com/autowarefoundation/autoware.universe/pull/8747#
https://github.com/autowarefoundation/autoware.universe/issues/9187
Colcon build in local PC
```
Starting >>> autoware_traffic_light_arbiter
Finished <<< autoware_traffic_light_arbiter [14.8s]                       
Summary: 1 package finished [16.4s]
```
None.
None.
None.
=> fix(autoware_traffic_light_arbiter): fix build error

planning/autoware_route_handler/src/route_handler.cpp
This is a fix of warnings from the new version of cppcheck
```
planning/autoware_route_handler/src/route_handler.cpp:1929:39: style: Unused variable: candidate_paths [unusedVariable]
std::vector<lanelet::ConstLanelets> candidate_paths;
^
```
- Link
None.
None.
None.
=> fix(autoware_route_handler): fix cppcheck unusedVariable

common/autoware_point_types/include/autoware/point_types/types.hpp, common/autoware_point_types/test/test_point_types.cpp, localization/autoware_landmark_based_localizer/autoware_lidar_marker_localizer/src/lidar_marker_localizer.cpp, perception/autoware_compare_map_segmentation/test/test_distance_based_compare_map_filter.cpp, perception/autoware_compare_map_segmentation/test/test_voxel_based_approximate_compare_map_filter.cpp, perception/autoware_compare_map_segmentation/test/test_voxel_based_compare_map_filter.cpp, perception/autoware_compare_map_segmentation/test/test_voxel_distance_based_compare_map_filter.cpp, perception/autoware_euclidean_cluster/test/test_voxel_grid_based_euclidean_cluster.cpp, perception/autoware_image_projection_based_fusion/src/pointpainting_fusion/node.cpp, perception/autoware_image_projection_based_fusion/test/test_utils.cpp, perception/autoware_lidar_transfusion/include/autoware/lidar_transfusion/preprocess/voxel_generator.hpp, perception/autoware_lidar_transfusion/include/autoware/lidar_transfusion/ros_utils.hpp, perception/autoware_lidar_transfusion/test/test_voxel_generator.cpp, perception/autoware_raindrop_cluster_filter/test/test_low_intensity_cluster_filter.cpp, sensing/autoware_pointcloud_preprocessor/include/autoware/pointcloud_preprocessor/concatenate_data/concatenate_and_time_sync_nodelet.hpp, sensing/autoware_pointcloud_preprocessor/include/autoware/pointcloud_preprocessor/concatenate_data/concatenate_pointclouds.hpp, sensing/autoware_pointcloud_preprocessor/include/autoware/pointcloud_preprocessor/outlier_filter/ring_outlier_filter_node.hpp, sensing/autoware_pointcloud_preprocessor/include/autoware/pointcloud_preprocessor/time_synchronizer/time_synchronizer_node.hpp, sensing/autoware_pointcloud_preprocessor/src/blockage_diag/blockage_diag_node.cpp, sensing/autoware_pointcloud_preprocessor/src/concatenate_data/concatenate_and_time_sync_nodelet.cpp, sensing/autoware_pointcloud_preprocessor/src/concatenate_data/concatenate_pointclouds.cpp, sensing/autoware_pointcloud_preprocessor/src/outlier_filter/dual_return_outlier_filter_node.cpp, sensing/autoware_pointcloud_preprocessor/src/outlier_filter/ring_outlier_filter_node.cpp, sensing/autoware_pointcloud_preprocessor/src/time_synchronizer/time_synchronizer_node.cpp, sensing/autoware_pointcloud_preprocessor/src/utility/memory.cpp
prefix namespace with autoware
None.
None.
None.
=> refactor(autoware_point_types): prefix namespace with autoware::point_types

planning/autoware_rtc_interface/CMakeLists.txt, planning/autoware_rtc_interface/include/autoware/rtc_interface/rtc_interface.hpp, planning/autoware_rtc_interface/package.xml, planning/autoware_rtc_interface/src/rtc_interface.cpp, planning/autoware_rtc_interface/test/test_rtc_interface.cpp
A new field `requested` was implemented in the `tier4_rtc_msgs`.
This PR modify the functions inside the rtc_interface taking into account of the new msg field.
Details are below:
- `updateCooperateStatus`: take `requested` as argument and set the default value to false (since most module won't use the requested field)
- `isActivated`: consider the state of requested field
- `isForceActivated`: consider the state of requested field
Furthermore, some refactoring and basic unit test were implemented.
https://github.com/tier4/tier4_autoware_msgs/pull/148
https://github.com/orgs/autowarefoundation/discussions/4978
None.
None.
None.
=> feat(rtc_interface): add requested field

control/autoware_mpc_lateral_controller/src/mpc_utils.cpp
Fix a bug where the trajectory yaw values were incorrectly calculated inside the MPC controller.
When interpolating, we need the yaw values to not "loop" (e.g., `3.14 + epsilon` = `-3.14`). These values were calculated but not used, so this PR simply uses the non-looping values for interpolation.
- Link
None.
None.
None.
=> fix(mpc_lateral_controller): correctly resample the MPC trajectory yaws

planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/traffic_light_utils.cpp
Prevent accessing nullopt in calcDistanceToRedTrafficLight stopline
- Link
None.
None.
None.
=> fix(bpp): prevent accessing nullopt

common/autoware_test_utils/include/autoware_test_utils/mock_data_parser.hpp, common/autoware_test_utils/src/mock_data_parser.cpp, common/autoware_test_utils/test/test_mock_data_parser.cpp
check diff for this PR here: https://github.com/tier4/autoware.universe/compare/feat/autoware_test_utils/autoware-msgs...tier4:autoware.universe:feat/autoware_test_utils/traffic-light-msgs
depends https://github.com/autowarefoundation/autoware.universe/pull/9176, https://github.com/autowarefoundation/autoware.universe/pull/9174
- Link
None.
None.
None.
=> feat(autoware_test_utils): add traffic light msgs parser

planning/autoware_rtc_interface/src/rtc_interface.cpp, planning/autoware_rtc_interface/test/test_rtc_interface.cpp
The `requested` field was not updated, when the uuid was updated (it was updated when it was once registered).
This PR fixes the problem.
https://github.com/autowarefoundation/autoware.universe/pull/9202
None.
None.
None.
=> fix(rtc_interface): update requested field for every cooperateStatus state

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/data_structs.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/helper.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/scene.hpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp
This PR would enable operator request via `rtc_interface` for ambiguous objects.
A new variable `request_operator` is introduced in `AvoidancePlanningData` which would be used to update the cooperate status msg in the `rtc_interface`.
https://github.com/autowarefoundation/autoware.universe/pull/9202
[Screencast from 2024年10月31日 13時03分09秒.webm](https://github.com/user-attachments/assets/36debac6-b90d-4171-855f-07e77afd81aa)
The TIER IV internal evaluator would be successful by merging https://github.com/autowarefoundation/autoware.universe/pull/9211 first.
None.
None.
=> feat(static_obstacle_avoidance): operator request for ambiguous vehicle

system/diagnostic_graph_utils/src/lib/graph.cpp
Fix diagnostic_graph_utils to reset graph when new one is received.
- [TIER IV internal link](https://star4.slack.com/archives/C02JA4Y1U80/p1728532439187839?thread_ts=1725868536.633829&cid=C02JA4Y1U80)
1. Run `ros2 launch diagnostic_graph_aggregator example-main.launch.xml`
2. Run `ros2 component standalone autoware_default_adapi autoware::default_adapi::DiagnosticsNode 
3. Run `ros2 topic echo --no-arr /api/system/diagnostics/status`
4. Restart step 1
5. Check array size of step 3 is not increased
None.
None.
None.
=> fix(diagnostic_graph_utils): reset graph when new one is received

localization/autoware_ndt_scan_matcher/test/test_fixture.hpp
This pull request addresses the error at https://github.com/autowarefoundation/autoware.universe/actions/runs/11608940793.
* The test time is reduced from `1min 25s` to around `23s` in a local machine.
* The test is passed 100 times.
None.
None.
None.
=> fix(autoware_ndt_scan_matcher): reduce initial_pose_estimation.particles_num from 200 to 100 on tests

launch/tier4_control_launch/launch/control.launch.xml
Add collision detector package in control launch.
Github issue: https://github.com/autowarefoundation/autoware.universe/issues/9145
Autoware launch: https://github.com/autowarefoundation/autoware_launch/pull/1205
[Screencast from 2024年11月01日 14時27分07秒.webm](https://github.com/user-attachments/assets/b3a8b76d-cb7e-423d-a312-ac56b38fb0ab)
None.
None.
None.
=> feat(control_launch): add collision detector in launch

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/path_safety_checker/safety_check.hpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_safety_checker/safety_check.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/test/test_safety_check.cpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp
Add unit test for behavior_path_planner_common package, especially for `safety_check.cpp` in the utils directory.
The coverage is increased.
None
Colon build
```
4: [==========] Running 23 tests from 3 test suites.
4: [----------] Global test environment set-up.
4: [----------] 11 tests from BehaviorPathPlanningSafetyUtilsTest
4: [ RUN      ] BehaviorPathPlanningSafetyUtilsTest.isTargetObjectOncoming
4: [       OK ] BehaviorPathPlanningSafetyUtilsTest.isTargetObjectOncoming (0 ms)
4: [ RUN      ] BehaviorPathPlanningSafetyUtilsTest.isTargetObjectFront
4: [       OK ] BehaviorPathPlanningSafetyUtilsTest.isTargetObjectFront (0 ms)
4: [ RUN      ] BehaviorPathPlanningSafetyUtilsTest.createExtendedEgoPolygon
4: [       OK ] BehaviorPathPlanningSafetyUtilsTest.createExtendedEgoPolygon (0 ms) …
```
=> test(bpp_common): add unit test for safety check

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/manager.cpp
This is a fix based on cppcheck
```
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/manager.cpp:548:23: style: Variable 'ns' is assigned a value that is never used. [unreadVariable]
const std::string ns = base_ns + "pull_over.parallel_parking.";
^
```
- Link
None.
None.
None.
=> fix(autoware_behavior_path_goal_planner_module): fix cppcheck unreadVariable

perception/autoware_image_projection_based_fusion/src/roi_pointcloud_fusion/node.cpp
This is a fix based on clang-tidy bugprone-misplaced-widening-cast error.
Other errors also exist, but they are not corrected at this time because of their low severity.
`max_cluster_size` is always assumed to be positive numbers.
Also, `cluster.point_step` is always a positive number because it is of type uint32.
```
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_image_projection_based_fusion/src/roi_pointcloud_fusion/node.cpp:154:39: error: either cast from 'int' to 'size_t' (aka 'unsigned long') is ineffective, or there is loss of precision before the conversion [bugprone-misplaced-widening-cast,-warnings-as-errors]
if (clusters_data_size.at(i) >= static_cast<size_t>(max_cluster_size_ * point_step)) {
^
```
- Link
None.
None.
None.
=> fix(autoware_image_projection_based_fusion): fix bugprone-misplaced-widening-cast

perception/autoware_euclidean_cluster/lib/voxel_grid_based_euclidean_cluster.cpp
This is a fix based on clang-tidy `bugprone-misplaced-widening-cast` error.
Other errors also exist, but they are not corrected at this time because of their low severity.
`max_cluster_size` is always assumed to be positive numbers.
Also, `cluster.point_step` is always a positive number because it is of type uint32.
```
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_euclidean_cluster/lib/voxel_grid_based_euclidean_cluster.cpp:120:31: error: either cast from 'int' to 'std::size_t' (aka 'unsigned long') is ineffective, or there is loss of precision before the conversion [bugprone-misplaced-widening-cast,-warnings-as-errors]
if (cluster_data_size > std::size_t(max_cluster_size_ * point_step)) {
^
```
- Link
None.
None.
None.
=> fix(autoware_euclidean_cluster): fix bugprone-misplaced-widening-cast

perception/autoware_compare_map_segmentation/src/voxel_grid_map_loader/voxel_grid_map_loader.hpp
This is a fix based on cppcheck warning
```
perception/autoware_compare_map_segmentation/src/voxel_grid_map_loader/voxel_grid_map_loader.hpp:212:17: style: Variable 'kv' can be declared as reference to const [constVariableReference]
for (auto & kv : current_voxel_grid_dict_) {
^
```
And made some optimization in `getCurrentMapIDs`
- Link
None.
None.
None.
=> fix(autoware_compare_map_segmentation): fix cppcheck constVariableReference

planning/autoware_freespace_planning_algorithms/scripts/bind/astar_search_pybind.cpp
This is a fix based on clang-tidy `bugprone-unused-raii` error.
```
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/autoware_freespace_planning_algorithms/scripts/bind/astar_search_pybind.cpp:174:3: error: object destroyed immediately after creation; did you mean to name the object? [bugprone-unused-raii,-warnings-as-errors]
py::class_<freespace_planning_algorithms::AbstractPlanningAlgorithm>(
^
give_me_a_name
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/autoware_freespace_planning_algorithms/scripts/bind/astar_search_pybind.cpp:176:3: error: object destroyed immediately after creation; did you mean to name the object? [bugprone-unused-raii,-warnings-as-errors]
py::class_<
^
```
- Link
None.
None.
None.
=> fix(autoware_freespace_planning_algorithms): fix bugprone-unused-raii

perception/autoware_map_based_prediction/include/map_based_prediction/map_based_prediction_node.hpp, perception/autoware_map_based_prediction/src/map_based_prediction_node.cpp
divide `objectsCallback` because it is too big
next items:
- divide `MapBasedPredictionNode::getPredictionForVehicleObject`
- others
- Link
- https://evaluation.tier4.jp/evaluation/reports/a3d152ce-4215-5c87-ad2b-cca37e6341ac?project_id=prd_jt
- 
None.
None.
None.
=> refactor(map_based_prediction): divide objectsCallback

perception/autoware_map_based_prediction/include/map_based_prediction/data_structure.hpp, perception/autoware_map_based_prediction/include/map_based_prediction/map_based_prediction_node.hpp, perception/autoware_map_based_prediction/include/map_based_prediction/utils.hpp, perception/autoware_map_based_prediction/src/map_based_prediction_node.cpp, perception/autoware_map_based_prediction/src/utils.cpp
depends https://github.com/autowarefoundation/autoware.universe/pull/9219, see the diff below
https://github.com/tier4/autoware.universe/compare/refactor/mbp-obj-callback...tier4:autoware.universe:refactor/mbp-move-memfn-to-util?expand=1
- Link
- https://evaluation.tier4.jp/evaluation/reports/a3d152ce-4215-5c87-ad2b-cca37e6341ac?project_id=prd_jt
- 
None.
None.
None.
=> refactor(map_based_prediction): move member functions to utils

perception/autoware_probabilistic_occupancy_grid_map/lib/updater/binary_bayes_filter_updater.cpp
This is a fix based on clang-tidy `bugprone-incorrect-roundings` error.
```
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_probabilistic_occupancy_grid_map/lib/updater/binary_bayes_filter_updater.cpp:66:14: error: casting (double + 0.5) to integer leads to incorrect rounding; consider using lround (#include <cmath>) instead [bugprone-incorrect-roundings,-warnings-as-errors]
std::max(static_cast<unsigned char>(po_hat * 255.f + 0.5f), static_cast<unsigned char>(1)),
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_probabilistic_occupancy_grid_map/lib/updater/binary_bayes_filter_updater.cpp:66:41: error: casting (double + 0.5) to integer leads to incorrect rounding; consider using lround (#include <cmath>) instead …
```
=> fix(autoware_probabilistic_occupancy_grid_map): fix bugprone-incorrect-roundings

planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp
vehicle stop checker, which is a utility class to check ego behavior, has subscriber and callback function. Currently, crosswalk module uses it.
On the other hand, `planner_data` of behavior velocity planner has already had function to check if the ego is stopping or not.
Additionally, this redundant implementation may cause data race in multithread.
```
[component_container_mt-34] *** Aborted at 1730424553 (unix time) try "date -d @1730424553" if you are using GNU date ***
[component_container_mt-34] PC: @                0x0 (unknown)
[component_container_mt-34] *** SIGSEGV (@0xa8) received by PID 3375 (TID 0x7f9722ffd640) from PID 168; stack trace: ***
[component_container_mt-34]     @     0x7f972805e046 (unknown)
[component_container_mt-34]     @     0x7f974bbf5520 (unknown) …
```
=> fix(crosswalk): don't use vehicle stop checker to remove unnecessary callback

perception/autoware_image_projection_based_fusion/config/fusion_common.param.yaml, perception/autoware_image_projection_based_fusion/include/autoware/image_projection_based_fusion/fusion_node.hpp, perception/autoware_image_projection_based_fusion/include/autoware/image_projection_based_fusion/utils/utils.hpp, perception/autoware_image_projection_based_fusion/src/fusion_node.cpp, perception/autoware_image_projection_based_fusion/src/pointpainting_fusion/node.cpp, perception/autoware_image_projection_based_fusion/src/roi_cluster_fusion/node.cpp, perception/autoware_image_projection_based_fusion/src/roi_detected_object_fusion/node.cpp, perception/autoware_image_projection_based_fusion/src/roi_pointcloud_fusion/node.cpp, perception/autoware_image_projection_based_fusion/src/segmentation_pointcloud_fusion/node.cpp, perception/autoware_image_projection_based_fusion/src/utils/utils.cpp
Add option `point_project_to_unrectified_image` to switch whether if the point project considers lens distortion or not.
This PR will be merged after PR https://github.com/autowarefoundation/autoware_launch/pull/1207 is merged.
Lens distortion consideration https://github.com/autowarefoundation/autoware.universe/pull/7053
[TIER IV INTERNAL](https://evaluation.tier4.jp/evaluation/reports/5782913c-b246-5dfb-b332-396a797952f4?project_id=prd_jt)
None.
None.
None.
=> fix(autoware_image_projection_based_fusion): make optional to consider lens distortion in the point projection

localization/autoware_ekf_localizer/config/ekf_localizer.param.yaml, localization/autoware_ekf_localizer/include/autoware/ekf_localizer/ekf_localizer.hpp, localization/autoware_ekf_localizer/include/autoware/ekf_localizer/hyper_parameters.hpp, localization/autoware_ekf_localizer/schema/sub/node.sub_schema.json, localization/autoware_ekf_localizer/src/ekf_localizer.cpp
Currently, `autoware_ekf_localizer` has two timers: one for the Kalman filter and another for publishing the tf. The latter is unnecessary, and moreover, it's better to publish the same pose in the Kalman filter's timer callback.
Therefore, this pull request removes `timer_tf_` and related code and a parameter.
None.
None.
|:--------------|:---------------|:---------|:--------------|:------------------|
| Removed | `publish_tf`   | `bool` | `true`         | Whether to publish tf |
None.
=> fix(autoware_ekf_localizer): remove `timer_tf_`

planning/autoware_rtc_interface/package.xml
`package.xml` is missing an entry for `autoware_cmake`
None.
None.
None.
=> fix(autoware_rtc_interface): fix dependency

control/autoware_autonomous_emergency_braking/src/node.cpp
This PR solves an issue that makes the AEB IMU path consider objects outside of the IMU path. The fix checks the arc length of the objects against the path to determine if it should be considered for collision checking or not.
Before: 
Points that are in front of IMU path are being considered for collision checking
After:
https://github.com/user-attachments/assets/617fb13b-0cae-41d9-832d-78826fe91c63
- Link
None.
None.
None.
=> fix(autonomous_emergency_braking): solve issue with arc length

perception/autoware_lidar_apollo_instance_segmentation/src/log_table.cpp
This is a fix based on cppcheck warning
```
perception/autoware_lidar_apollo_instance_segmentation/src/log_table.cpp:29:46: style: Floating-point cast causes loss of precision. [suspiciousFloatingPointCast]
data[i] = std::log1p(static_cast<float>(i / 10.0));
^
perception/autoware_lidar_apollo_instance_segmentation/src/log_table.cpp:47:37: style: Floating-point cast causes loss of precision. [suspiciousFloatingPointCast]
return std::log(static_cast<float>(1.0 + num));
^
```
- Link
None.
None.
None.
=> fix(autoware_lidar_apollo_instance_segmentation): fix cppcheck suspiciousFloatingPointCast

planning/behavior_path_planner/autoware_behavior_path_sampling_planner_module/src/sampling_planner_module.cpp
This is a fix of warnings from the new version of cppcheck
```
planning/behavior_path_planner/autoware_behavior_path_sampling_planner_module/src/sampling_planner_module.cpp:250:21: style: Unused variable: hard_constraints_results [unusedVariable]
std::vector<bool> hard_constraints_results;
^
planning/behavior_path_planner/autoware_behavior_path_sampling_planner_module/src/sampling_planner_module.cpp:595:34: style: Unused variable: hard_constraints_results_full [unusedVariable]
std::vector<std::vector<bool>> hard_constraints_results_full;
^
planning/behavior_path_planner/autoware_behavior_path_sampling_planner_module/src/sampling_planner_module.cpp:600:23: style: Variable 'hard_constraints_results' is assigned a value that is never used. [unreadVariable]
std::vector<bool> …
```
=> fix(autoware_behavior_path_sampling_planner_module): fix cppcheck unusedVariable

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/README.md, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/config/lane_change.param.yaml, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/scene.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/data_structs.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/utils.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/manager.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp
When performing a lane change after an intersection, nearby vehicle might attempt to overtake the ego vehicle. Although simulations may suggest the maneuver is safe, real world testing shows it can feel unsafe. This is particularly true in intersections, where surrounding vehicle often exhibits significant speed variations and unpredictable behavior.
The image below illustrates  such a scenario.
In this situation, rear vehicle may either stop abruptly or accelerate suddenly, making it challenging for the safety check to produce reliable result.
This PR addresses the issue by making the lane change module adopt a more conservative approach near intersection.
If the ego vehicle is within an intersection and currently in a turn lane, the lane change module will output an invalid path. …
=> fix(lane_change): enable cancel when ego in turn direction lane

planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/calculate_slowdown_points.cpp, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/calculate_slowdown_points.hpp, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/filter_predicted_objects.cpp, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/footprint.cpp, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_collisions.cpp, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_module.cpp, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_module.hpp, planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/types.hpp
Fix bugs where the raw trajectory (which can start behind ego) was used instead of the filtered one (which always starts in front of ego).
Similarly, fix the incorrect use of the `first_ego_trajectory_idx` which is calculated on the raw trajectory but was used with the filtered trajectory.
Finally, fix the time measurements to keep using the last stop pose.
- Link
None.
None.
None.
=> fix(out_of_lane): correct calculations of the stop pose

common/autoware_overlay_rviz_plugin/autoware_overlay_rviz_plugin/package.xml, common/tier4_state_rviz_plugin/package.xml, common/tier4_vehicle_rviz_plugin/package.xml
This PR add / modify dependencies written in package.xml.
The changed dependencies are almost about ament_index_cpp.
Jazzy has a build error due to not having a dependency on ament_index_cpp.
We have found similar errors in other ROS packages and have confirmed that they are not specific to the author's environment.
Reference: https://github.com/autowarefoundation/autoware.universe/issues/7598
Base pull request: https://github.com/autowarefoundation/autoware.universe/pull/7600
colcon test passed.
This PR does not change the behavior of Autoware.
None.
None.
None.
=> fix: missing dependency in common components

system/dummy_diag_publisher/include/dummy_diag_publisher/dummy_diag_publisher_core.hpp, system/dummy_diag_publisher/src/dummy_diag_publisher_core.cpp
cherry-pick the following tier4 side PRs
https://github.com/tier4/autoware.universe/pull/1414
https://github.com/tier4/autoware.universe/pull/1415
- Prevent to publish the diag as own node name.
- delete param callback because it is not working well with this node design
https://github.com/tier4/autoware.universe/pull/1272
https://github.com/tier4/autoware.universe/pull/1414
https://github.com/tier4/autoware.universe/pull/1415
- Link
psim 
`ros2 topic echo /diagnostics | grep dummy_diag -C 10`
```
header:
stamp:
sec: 1730969604
nanosec: 53702128
frame_id: ''
status:
- level: "\0"
name: 'node: field'
message: OK
hardware_id: dummy_diag
values: []
```
None.
None.
None.
=> fix(dummy_diag_publisher): not use diagnostic_updater and param callback

planning/behavior_path_planner/autoware_behavior_path_planner_common/CMakeLists.txt, planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/path_shifter/path_shifter.hpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_shifter/path_shifter.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/test/test_path_shifter.cpp
This PR adds unit tests for `utils/path_shifter` in `behavior_path_planner_common` package.
Also some function name is changed to snake_case.
Colcon test
```
6: [----------] 8 tests from PathShifterTest (1 ms total)
6: 
6: [----------] Global test environment tear-down
6: [==========] 8 tests from 1 test suite ran. (1 ms total)
6: [  PASSED  ] 8 tests.
```
None.
None.
None.
=> test(behavior_path_planner_common): add unit test for path shifter

common/autoware_trajectory/examples/example_trajectory_path_point.cpp, common/autoware_trajectory/include/autoware/trajectory/detail/interpolated_array.hpp, common/autoware_trajectory/test/test_trajectory_container.cpp
Change interface of InterpolatedArray.
```cpp
trajectory->longitudinal_velocity_mps(3.0, 5.0) = 0.0;
```
```cpp
trajectory->longitudinal_velocity_mps.range(3.0, 5.0).set(0.0);
```
- [TIER IV Slack Link](https://star4.slack.com/archives/C03QW0GU6P7/p1731033224610229)
None.
None.
None.
=> feat(autoware_trajectory): change interface of InterpolatedArray

planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/README.md, planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/config/detection_area.param.yaml, planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/src/manager.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/src/scene.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/src/scene.hpp
This PR add a new feature to decide GO/STOP until the ego has velocity.
https://github.com/autowarefoundation/autoware_launch/pull/1216
psim and tier4 internal tests.
None.
None.
=> feat(detection_area)!: add retruction feature

control/autoware_vehicle_cmd_gate/src/vehicle_cmd_gate.cpp, control/autoware_vehicle_cmd_gate/src/vehicle_cmd_gate.hpp
Fix an issue where the processing time was incorrectly measured and published multiple times.
- Link
None.
None.
None.
=> fix(vehicle_cmd_gate): fix processing time measurement

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/data_structs.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/utils.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp
Refactor lanes polygon members by removing  std::optional.
It is unnecessary to use std::optional, since we can use `empty()` to check the type's validity.
- Link
None.
None.
None.
=> refactor(lane_change): remove std::optional from lanes polygon

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/data_structs.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/utils.hpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp, planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp
Reverts autowarefoundation/autoware.universe#9267
It seems that due to the changes in autowarefoundation/autoware.universe#9267, the `autoware_behavior_path_lane_change_module` is causing build errors, which has broken `autoware.universe`. 
@zulfaqar-azmi-t4 Please address this issue. In the meantime, I have created this revert PR.
https://github.com/autowarefoundation/autoware.universe/actions/runs/11739742637/job/32704854017#step:13:30725
```
/__w/autoware.universe/autoware.universe/planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp: In lambda function:
/__w/autoware.universe/autoware.universe/planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp:1315:88: error: 'class lanelet::BasicPolygon2d' has no member …
```
=> refactor(lane_change): revert "remove std::optional from lanes polygon"

planning/autoware_freespace_planning_algorithms/src/astar_search.cpp
This is a fix based on cppcheck warning `unusedFunction`
```
planning/autoware_freespace_planning_algorithms/src/astar_search.cpp:51:0: style: The function 'setYaw' is never used. [unusedFunction]
void setYaw(geometry_msgs::msg::Quaternion * orientation, const double yaw)
^
```
- Link
None.
None.
None.
=> fix(/autoware_freespace_planning_algorithms): fix cppcheck unusedFunction

planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/start_planner_module.cpp
This is just to avoid the cppcheck warning `unreadVariable`
```
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/start_planner_module.cpp:459:14: style: Variable 'ego_is_merging_from_the_left' is assigned a value that is never used. [unreadVariable]
const bool ego_is_merging_from_the_left = (starting_pose_lateral_offset > 0.0);
^
```
- Link
None.
None.
None.
=> fix(autoware_behavior_path_start_planner_module): fix cppcheck unreadVariable

localization/autoware_ndt_scan_matcher/include/autoware/ndt_scan_matcher/ndt_omp/estimate_covariance.hpp, localization/autoware_ndt_scan_matcher/src/ndt_omp/estimate_covariance.cpp
This is a fix based on cppcheck warning unusedFunction
```
localization/autoware_ndt_scan_matcher/src/ndt_omp/estimate_covariance.cpp:106:0: style: The function 'find_rotation_matrix_aligning_covariance_to_principal_axes' is never used. [unusedFunction]
Eigen::Matrix2d find_rotation_matrix_aligning_covariance_to_principal_axes(
^
```
- Link
None.
None.
None.
=> fix(autoware_ndt_scan_matcher): fix cppcheck unusedFunction

control/autoware_pure_pursuit/include/autoware/pure_pursuit/util/planning_utils.hpp, control/autoware_pure_pursuit/src/autoware_pure_pursuit_core/planning_utils.cpp
This is a fix based on cppcheck warning `unusedFunction`
```
control/autoware_pure_pursuit/src/autoware_pure_pursuit_core/planning_utils.cpp:168:0: style: The function 'isInPolygon' is never used. [unusedFunction]
bool isInPolygon(
^
```
- Link
None.
None.
None.
=> fix(autoware_pure_pursuit): fix cppcheck unusedFunction

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp
In case of multiple lane change scenario, LC module fails to generate a valid candidate path when ego reaches terminal start point.
https://github.com/user-attachments/assets/cdf713b4-1e9c-4de5-a14b-52ed47faeb9f
This happens due to incorrect computation of the maximum lane changing length threshold, resulting in an infeasible value which cannot be satisfied.
This PR fixes the issue by removing the unnecessary reduction of the available length for lane changing. Behavior after the fix is shown below.
https://github.com/user-attachments/assets/d1f2595a-fff6-45bf-9760-74e38fcd4c99
None.
- PSIM.
- [TIER IV Internal Evaluator](https://evaluation.tier4.jp/evaluation/reports/ffe11e75-ed96-513f-92f5-a7bd9288988b?project_id=prd_jt)
None.
None.
LC module can generate valid candidate path at …
=> fix(lane_change): correct computation of maximum lane changing length threshold

system/autoware_default_adapi/src/planning.cpp
I confirmed that several pieces of information were missing from the `/api/planning/steering_factors` topic output from this package, because while the topic names under `/planning/steering_factor/*` had been changed, the corresponding topic names in autoware_default_adapi (the receiving side) had not been updated.
This PR addresses the topic name changes.
- Link
Although I've added some topics to subscribe to, there is information that is not yet included in the /api/planning/steering_factors topic. I believe this is an issue on the publisher's side of /planning/steering_factor/*. I plan to set up the system so that the information can be output once the publishing side addresses these topics in the future. 
If you have any concerns about this approach, please let me …
=> fix(autoware_default_adapi): change subscribing steering factor topic name for obstacle avoidance and lane changes

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp
Lane change path is not properly extended in multiple lane change case.
This has caused the stop point to not be inserted correctly, as shown in the following two videos.
https://github.com/user-attachments/assets/d313afb5-47d7-4611-9fb9-56b1c725dbdc
https://github.com/user-attachments/assets/b5adfee3-75fb-4c64-9839-16634b03f1d7
This PR aims to fix this by removing ego position check and properly extending path is there's no next lane.
https://github.com/user-attachments/assets/0afca695-78db-40c4-a269-c713b05f7fc0
https://github.com/user-attachments/assets/ae7cf59a-ccd1-4de3-970b-6c9c65bf3f3a
- Link
1. PSIM
2. Evaluator: TBA
None.
None.
None.
=> fix(lane_change): extending lane change path for multiple lane change (RT1-8427)

planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_safety_checker/safety_check.cpp
need to use `intersects` instead of `overlaps` to handle `whithin` case.
https://wandbox.org/permlink/NMQ7Tb1Ya3J4TsYM
```
#include <boost/geometry.hpp>
#include <boost/geometry/geometries/polygon.hpp>
#include <iostream>
int main() {
using Point = boost::geometry::model::d2::point_xy<double>;
using Polygon = boost::geometry::model::polygon<Point>;
Polygon polygonA;
boost::geometry::append(polygonA, Point(1.0, 1.0));
boost::geometry::append(polygonA, Point(1.0, 2.0));
boost::geometry::append(polygonA, Point(2.0, 2.0));
boost::geometry::append(polygonA, Point(2.0, 1.0));
boost::geometry::append(polygonA, Point(1.0, 1.0)); // Close the polygon
Polygon polygonB;
boost::geometry::append(polygonB, Point(0.0, 0.0));
boost::geometry::append(polygonB, Point(0.0, 3.0)); …
```
=> fix(behavior_path_planner_common): use boost intersects instead of overlaps

.github/sync-files.yaml, .github/workflows/build-and-test-daily-arm64.yaml, .github/workflows/build-and-test-daily.yaml, .github/workflows/build-and-test-differential-arm64.yaml, .github/workflows/build-and-test-differential.yaml, .github/workflows/build-and-test.yaml
This PR is a revision of #9096, changing it to use the development container images instead of the runtime container images.
> CUDA CI might not work as expected.
> 
> In build-and-test CUDA workflow I see packages are not being built properly due to missing libraries e.g. [here](https://github.com/autowarefoundation/autoware.universe/actions/runs/11366699702/job/31617666596#step:13:15438). This is because previous images had an [issue](https://github.com/autowarefoundation/autoware/issues/5219), which is already [fixed](https://github.com/autowarefoundation/autoware/pull/5332). This fix applies for already [changed](https://github.com/autowarefoundation/autoware/pull/5201) image tags. Currently CI operates on [deprecated](https://github.com/autowarefoundation/autoware.universe/actions/run …
=> ci(.github): update image tags

.github/CODEOWNERS, perception/autoware_crosswalk_traffic_light_estimator/package.xml, perception/autoware_traffic_light_arbiter/package.xml, perception/autoware_traffic_light_classifier/package.xml, perception/autoware_traffic_light_fine_detector/package.xml, perception/autoware_traffic_light_map_based_detector/package.xml, perception/autoware_traffic_light_multi_camera_fusion/package.xml, perception/autoware_traffic_light_occlusion_predictor/package.xml, perception/autoware_traffic_light_visualization/package.xml
This PR add maintainer `Masato Saeki` masato.saeki@tier4.jp
Added packages is below:
- `autoware_traffic_light_map_based_detector`
- `autoware_traffic_light_fine_detector`
- `autoware_traffic_light_classifier`
- `autoware_traffic_light_multi_camera_fusion`
- `autoware_traffic_light_occlusion_predictor`
- `autoware_traffic_light_arbiter`
- `autoware_traffic_light_visualization`
- `autoware_crosswalk_traffic_light_estimator`
- Link
None.
None.
None.
=> chore(autoware_traffic_light*): add maintainer

perception/autoware_detected_object_validation/src/obstacle_pointcloud/obstacle_pointcloud_validator.cpp
This is a fix based on clang-tidy `bugprone-incorrect-roundings` error.
```
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_detected_object_validation/src/obstacle_pointcloud/obstacle_pointcloud_validator.cpp:57:5: error: casting (double + 0.5) to integer leads to incorrect rounding; consider using lround (#include <cmath>) instead [bugprone-incorrect-roundings,-warnings-as-errors]
static_cast<size_t>(
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_detected_object_validation/src/obstacle_pointcloud/obstacle_pointcloud_validator.cpp:58:7: error: casting (double + 0.5) to integer leads to incorrect rounding; consider using lround (#include <cmath>) instead [bugprone-incorrect-roundings,-warnings-as-errors] …
```
=> fix(autoware_detected_object_validation): fix bugprone-incorrect-roundings

common/autoware_test_utils/README.md, common/autoware_test_utils/config/test_vehicle_info.param.yaml
If we specify custom vehicle_model/sensor_model in generating test yaml file, it causes confusion with the vehicle_info in autoware_test_utils in reproducing the same scene.
- Link
None.
None.
None.
=> feat(autoware_test_utils): use sample_vehicle/sample_sensor_kit

localization/autoware_ndt_scan_matcher/include/autoware/ndt_scan_matcher/ndt_omp/multi_voxel_grid_covariance_omp.h, localization/autoware_ndt_scan_matcher/src/ndt_omp/multi_voxel_grid_covariance_omp_impl.hpp
By investigating the memory usage during scan matching, I found that the memory consumption was dominated by `std::vector<MultiVoxelGridCovariance<pcl::PointXYZ>::Leaf>` in addition to the map itself. 
The following figure shows the memory usage when executing autoware's `ndt_scan_matcher` with `sample-map-rosbag`. The bottom area corresponds to `std::vector<MultiVoxelGridCovariance<pcl::PointXYZ>::Leaf>` (7.9MB).
The struct `Leaf` contains three `Eigen::Matrix3d`, and `sizeof(Leaf)` is 288, so having this for each voxel may consumes a lot of memory with large maps.
In this PR, I propose to remove `evecs_` (`Eigen::Matrix3d`) and `evals_` (`Eigen::Vector3d`) from `Leaf`. These variables are only used to calculate `cov_` and not be used directly. This will reduce `sizeof(Leaf)` from 288 to …
=> perf(autoware_ndt_scan_matcher): remove evecs_, evals_ of Leaf for memory efficiency

control/autoware_autonomous_emergency_braking/package.xml, control/autoware_control_validator/package.xml, control/autoware_trajectory_follower_node/package.xml, control/autoware_vehicle_cmd_gate/package.xml
This PR add / modify dependencies written in package.xml.
The changed dependencies are almost about ament_index_cpp.
Jazzy has a build error due to not having a dependency on ament_index_cpp.
We have found similar errors in other ROS packages and have confirmed that they are not specific to the author's environment.
Reference: https://github.com/autowarefoundation/autoware.universe/issues/7598
Base pull request: https://github.com/autowarefoundation/autoware.universe/pull/7600
colcon test passed.
This PR does not change the behavior of Autoware.
None.
None.
None.
=> fix(control): missing dependency in control components

evaluator/autoware_control_evaluator/test/test_control_evaluator_node.cpp
Line coverage is increased to 56.4 %.
- Link
None.
None.
None.
=> test(autoware_control_evaluator): add unit test for utils autoware_control_evaluator

control/autoware_collision_detector/include/autoware/collision_detector/node.hpp, control/autoware_collision_detector/src/node.cpp, launch/tier4_control_launch/launch/control.launch.xml
The collision detection published some error information when the vehicle position was not set in PSim.
```
[component_container_mt-39] [ERROR 1731399700.354588656] [control.collision_detector] filterObjects(): Failed to get transform from object frame to base_link:(L185)
```
This was caused due to not finding a connection between 'base_link' and 'map'.
This PR adds a subscriber for ego vehicle odometry information, and skips the process when the odometry information is not published.
As the `collision_detector` package is to be merged into the `surround_obstacle_checker` packages, subscribing the odometry information would not be a big issue, since the `surround_obstacle_checker`  is already subscribing this information.
None
None
| Change type   | Topic Type      | Topic Name    | …
=> fix(collision_detector): skip process when odometry is not published

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/path_safety_checker/safety_check.hpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_safety_checker/safety_check.cpp
change ego predicted path for safety check path from ego -> only parking path
previously path from current ego pose is used for safety check. this is too long and tend to judge unsafe.
it is enogh for this module to check only pull over parth 
before
after
internal : https://tier4.atlassian.net/browse/RT1-8296
psim
2024/11/11 https://evaluation.tier4.jp/evaluation/reports/4596e2eb-379e-53c0-9b0e-1d081123faef/?project_id=prd_jt
~/pilot-auto (feat/parking_path_safety $%)
None.
None.
None.
=> feat(goal_planner): safety check with only parking path

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_module.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_searcher.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_searcher_base.hpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp, planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_searcher.cpp
`referance_goal_pose` in GoalSearcher does not need to be saved as a state. So pass then in the  caller side using GoalSearcher.
- Link
- https://evaluation.tier4.jp/evaluation/reports/c515d86c-910d-55e8-86c7-74f2f74c2ce8?project_id=prd_jt
- https://evaluation.tier4.jp/evaluation/reports/e1c8650a-f0d7-57b1-a0f2-83b58e079f62?project_id=prd_jt
None.
None.
None.
=> refactor(goal_planner): remove reference_goal_pose getter/setter

control/autoware_lane_departure_checker/include/autoware/lane_departure_checker/lane_departure_checker.hpp, control/autoware_lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker.cpp, planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/shift_pull_out.cpp
This PR speeds up the start planner by re-using lanelet polygons instead of creating a whole new polygon every time we crop points. 
- Link
Degradation tests: https://evaluation.tier4.jp/evaluation/reports/40689d30-ea4d-55d3-8fab-3ad3a6328eab?project_id=prd_jt (100% passed)
PSim
Processing time (Before PR): 
Processing time (with PR): 
Peak time reduced from ~200ms to 18ms
None.
None.
None.
=> feat(start_planner, lane_departure_checker): speed up by updating polygons

common/autoware_trajectory/src/pose.cpp
fix bug of autoware_trajectory/pose.cpp
- Link
None.
None.
None.
=> fix(autoware_trajectory): fix bug of autoware_trajectory

common/autoware_trajectory/include/autoware/trajectory/path_point.hpp, common/autoware_trajectory/include/autoware/trajectory/path_point_with_lane_id.hpp, common/autoware_trajectory/include/autoware/trajectory/point.hpp, common/autoware_trajectory/include/autoware/trajectory/pose.hpp
change default value of min_points
- Link
None.
None.
None.
=> feat(autoware_trajectory): change default value of min_points

common/.pages
This PR fixes links in the `.pages` file to point to the correct paths after packages have been renamed to include the `autoware_` prefix.
- Link
None.
None.
None.
=> docs: fix links to design documents

planning/autoware_costmap_generator/README.md, planning/autoware_costmap_generator/config/costmap_generator.param.yaml, planning/autoware_costmap_generator/include/autoware/costmap_generator/costmap_generator.hpp, planning/autoware_costmap_generator/src/costmap_generator.cpp
Fix how the lidar height min/max thresholds are used in the `costmap_generator`.
They were originally designed to be thresholds relative to the lidar frame. However, they are compared to points converted to the costmap frame (`map` by default).
Since the lidar frame is not easily available in the `costmap_generator`, the PR changes the parameters to represent thresholds in the vehicle frame (`base_link` by default) and correctly converts the thresholds to the costmap frame.
Launch PR to update the parameters: https://github.com/autowarefoundation/autoware_launch/pull/1225
Using the sample map which has a z value of around 19m.
- Run the planning simulation with `perception/enable_object_recognition:=false`.
- Set the ego pose inside the parking area.
- Visualize the costmap.
- Place a bus …
=> fix(costmap_generator): use vehicle frame for lidar height thresholds

simulator/tier4_dummy_object_rviz_plugin/package.xml
`tier4_dummy_object_rviz_plugin` uses Boost, but it hasn't been declared as a dependency in `package.xml`
https://github.com/autowarefoundation/autoware-deb-packages/actions/runs/11663346804/job/32471666820?pr=101
None.
None.
None.
=> fix(tier4_dummy_object_rviz_plugin): fix missing dependency

planning/behavior_velocity_planner/autoware_behavior_velocity_run_out_module/src/scene.cpp, system/autoware_default_adapi/src/planning.cpp
Set velocity factor when run out module inserts stop point.
- Link
Psim
None.
None.
None.
=> fix(run_out): output velocity factor

planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/src/scene.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_no_stopping_area_module/src/scene_no_stopping_area.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_planner/src/planner_manager.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/include/autoware/behavior_velocity_planner_common/plugin_interface.hpp, planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/include/autoware/behavior_velocity_planner_common/plugin_wrapper.hpp, planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/include/autoware/behavior_velocity_planner_common/scene_module_interface.hpp, planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/src/scene_module_interface.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_stop_line_module/src/scene.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/manager.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/scene.cpp
Previously, we stored the first stopping point on the path in the variable `SceneModuleInterface::first_stop_path_point_index_`. However, we plan to replace this with a class that handles paths continuously in the future by using [autoware_trajectory](https://github.com/autowarefoundation/autoware.universe/tree/main/common/autoware_trajectory). In this case, the current method of directly handling path point indices should be replaced with a method that handles distances from the path's starting point.
In this PR, instead of using the variable `SceneModuleInterface::first_stop_path_point_index_`, we now manage the first_stop_path_point using the variable `SceneModuleInterface::first_stop_path_point_distance_`. `SceneModuleInterface::first_stop_path_point_distance_` represents the distance …
=> feat(behavior_velocity_planner): replace first_stop_path_point_index

system/mrm_handler/include/mrm_handler/mrm_handler_core.hpp, system/mrm_handler/launch/mrm_handler.launch.xml, system/mrm_handler/src/mrm_handler/mrm_handler_core.cpp
Originally, the emergency_holding function that the system_error_monitor had was moved to the mrm_handler. However, the mrm_handler does not publish the emergency_holding state, so the emergency_holding in the hazard_status published by the hazard_status_converter is not updated.
This PR add emergency holding publisher which is publish a value of `is_emergency_holding_` .
- [CompanyName internal link](https://star4.slack.com/archives/C017VB9UG1L/p1729675438504999)
Related PR
[test/update-emergency-holding-state](https://github.com/TetsuKawa/autoware/tree/test/update-emergency-holding-state) is include This PR, https://github.com/autowarefoundation/autoware.universe/pull/9287 and https://github.com/tier4/tier4_autoware_msgs/pull/153.
[Screencast from 2024年11月11日 …
=> feat(mrm_handler): mrm handler publish emergecy holding

control/autoware_mpc_lateral_controller/include/autoware/mpc_lateral_controller/mpc.hpp, control/autoware_mpc_lateral_controller/include/autoware/mpc_lateral_controller/mpc_lateral_controller.hpp, control/autoware_mpc_lateral_controller/src/mpc.cpp, control/autoware_mpc_lateral_controller/src/mpc_lateral_controller.cpp, control/autoware_mpc_lateral_controller/test/test_mpc.cpp, control/autoware_pid_longitudinal_controller/src/pid_longitudinal_controller.cpp, control/autoware_trajectory_follower_base/include/autoware/trajectory_follower_base/control_horizon.hpp, control/autoware_trajectory_follower_base/include/autoware/trajectory_follower_base/lateral_controller_base.hpp, control/autoware_trajectory_follower_base/include/autoware/trajectory_follower_base/longitudinal_controller_base.hpp, control/autoware_trajectory_follower_node/README.md, control/autoware_trajectory_follower_node/include/autoware/trajectory_follower_node/controller_node.hpp, control/autoware_trajectory_follower_node/src/controller_node.cpp
It was previously agreed that autoware_msgs should include control horizon. However, until now the msgs has not been used.
https://github.com/autowarefoundation/autoware_msgs/pull/11
In this PR, publish control horizon topic as experimental one. 
Although this is an informal interface, it is a useful topic for users who want to maximize control performance in vehicular nodes.
If the longitudinal and lateral time steps are different, calculate the greatest common divisor time step and align the sizes with zero-order hold.
If one size is 1, repeat to match the other size.
https://github.com/autowarefoundation/autoware_msgs/pull/11
- Link
internal slack: https://star4.slack.com/archives/C4P0NSMB5/p1731572458828639
- psim
- unit test
- 2024/11/14 …
=> feat(trajectory_follower): publsih control horzion

planning/autoware_freespace_planner/src/autoware_freespace_planner/utils.cpp, planning/autoware_freespace_planner/test/test_freespace_planner_utils.cpp
`is_near_target` function only considers longitudinal deviation which can cause wrong behavior in some cases like below.
Instead it should consider the entire pose deviation including lateral and orientation as well to give the correct behavior as shown below.
None.
- PSIM
None.
None.
None.
=> fix(freespace_planner): fix is near target check

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp, planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp
This PR contains 2 changes which are 
- moves redundant calculations in for loop inside `getRoadShoulderDistance` function
-  change calculation method inside `extendBackwardLength` function. As `autoware::motion_utils::calcSignedArcLength` is called several times, it would be be better to accumulate the length using `autoware::universe_utils::calcDistance2d`
Furthermore,  parts are refactored according to clang-tidy warnings.
None
None.
None.
None.
=> refactor(static obstacle avoidance): remove redundant calculation

common/autoware_motion_utils/include/autoware/motion_utils/factor/velocity_factor_interface.hpp, common/autoware_motion_utils/src/factor/velocity_factor_interface.cpp, common/autoware_trajectory/include/autoware/trajectory/detail/utils.hpp, common/autoware_trajectory/src/detail/util.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_stop_line_module/package.xml, planning/behavior_velocity_planner/autoware_behavior_velocity_stop_line_module/src/debug.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_stop_line_module/src/manager.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_stop_line_module/src/manager.hpp, planning/behavior_velocity_planner/autoware_behavior_velocity_stop_line_module/src/scene.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_stop_line_module/src/scene.hpp
Previously, paths represented by discrete points were manipulated using `autoware_motion_utils`. However, we plan to replace this with a class that handles paths continuously in the future by using [autoware_trajectory](https://github.com/autowarefoundation/autoware.universe/tree/main/common/autoware_trajectory).
In this PR, we implemented this replacement for behavior_velocity_stop_line.
https://github.com/autowarefoundation/autoware.universe/pull/9296
- Evaluator
- https://evaluation.tier4.jp/evaluation/reports/9ce08fa5-0662-58c7-8541-276b4eeeb921?project_id=prd_jt
- psim
https://github.com/user-attachments/assets/857cb79e-6687-4ad8-8af8-788f9a7797f0
None.
None.
None.
=> feat(behavior_velocity_stop_line): replace autoware_motion_utils to autoware_trajectory

common/autoware_test_utils/include/autoware_test_utils/autoware_test_utils.hpp, common/autoware_test_utils/src/autoware_test_utils.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/CMakeLists.txt, planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/drivable_area_expansion/static_drivable_area.hpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/drivable_area_expansion/static_drivable_area.cpp, planning/behavior_path_planner/autoware_behavior_path_planner_common/test/test_static_drivable_area.cpp
Add tests for some of the static drivable area functions.
- Link
None.
None.
None.
=> test(bpp_common): add tests for the static drivable area

planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/manager.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp, planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp
The current crosswalk module has a feature to handle wide width crosswalk.
However, such use cases are rare against our maintenance cost. 
Therefore, I propose to delete this function.
launch PR: https://github.com/autowarefoundation/autoware_launch/pull/1233
=> chore(crosswalk)!: delete wide crosswalk corresponding function

planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/CMakeLists.txt
To suppress the following error from clang-tidy, we include opencv as a system header.
```
/home/hisaki/workspace/clang-tidy-ci/autoware/src/universe/autoware.universe/planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection_occlusion.cpp:307:43: warning: use of a signed integer operand with a binary bitwise operator [hicpp-signed-bitwise]
occlusion_mask = cv::Mat(width, height, CV_8UC1, cv::Scalar(0));
^
/usr/include/opencv4/opencv2/core/hal/interface.h:88:17: note: expanded from macro 'CV_8UC1'
#define CV_8UC1 CV_MAKETYPE(CV_8U,1)
^~~~~~~~~~~~~~~~~~~~
/usr/include/opencv4/opencv2/core/hal/interface.h:85:32: note: expanded from macro 'CV_MAKETYPE'
#define CV_MAKETYPE(depth,cn) (CV_MAT_DEPTH(depth) + (((cn)-1) << CV_CN_SHIFT)) …
```
=> chore(autoware_behavior_velocity_intersection_module): include opencv as system

planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_safety_checker/safety_check.cpp
The collision pose is update at every iteration.
This has caused us to get inaccurate collision information when viewing the debug marker.
The important part is for us to know where the collision first happens.
The position shown is the **last collided pose**.
The position shown is the **first collided pose**.
- Link
None.
None.
None.
=> fix(bpp): update collided polygon pose only once
