planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/scene.hpp

Currently the static obstacle avoidance module with transit from `IDLE` to `RUNNING` for it's initial state transition. Ideally the module should check safety before it executes the avoidance maneuver. Thus the initial state transition is modified to `IDLE` to `WAITING_FOR_APPROVAL` in this PR.
None
None.
None.
None.

fix(static_obstacle_avoidance): override setInitState

---

perception/autoware_traffic_light_visualization/CMakeLists.txt

To suppress the following error from clang-tidy, we include opencv as a system header.
```
Error while processing /home/hisaki/workspace/clang-tidy-ci/autoware/src/universe/autoware.universe/perception/autoware_traffic_light_visualization/src/traffic_light_roi_visualizer/shape_draw.cpp.
/usr/include/opencv4/opencv2/core/cuda.inl.hpp:105:9: error: '_Atomic' is a C11 extension [clang-diagnostic-c11-extensions]
CV_XADD(refcount, 1);
^
/usr/include/opencv4/opencv2/core/cvdef.h:670:60: note: expanded from macro 'CV_XADD'
^
/usr/include/opencv4/opencv2/core/cuda.inl.hpp:487:9: error: '_Atomic' is a C11 extension [clang-diagnostic-c11-extensions]
CV_XADD(refcount, 1);
^
/usr/include/opencv4/opencv2/core/cvdef.h:670:60: note: expanded from macro 'CV_XADD'
^ …
```

chore(autoware_traffic_light_visualization): include opencv as system

---

common/autoware_motion_utils/include/autoware/motion_utils/factor/steering_factor_interface.hpp
common/autoware_motion_utils/src/factor/steering_factor_interface.cpp
planning/behavior_path_planner/autoware_behavior_path_planner/include/autoware/behavior_path_planner/behavior_path_planner_node.hpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/CMakeLists.txt
planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/interface/scene_module_interface.hpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/interface/scene_module_manager_interface.hpp

Move steering factor interface to `autoware_motion_utils` from bpp package so that the other modules can use it.
- Link
None.
None.
None.

refactor(factor): move steering factor interface to motion utils

---

perception/autoware_traffic_light_multi_camera_fusion/package.xml
perception/autoware_traffic_light_multi_camera_fusion/src/traffic_light_multi_camera_fusion_node.cpp
perception/autoware_traffic_light_multi_camera_fusion/src/traffic_light_multi_camera_fusion_node.hpp

Fixed clang-tidy errors.
- Link
None.
None.
None.

feat(autoware_traffic_light_multi_camera_fusion): resolve clang-tidy error

---

planning/behavior_path_planner/autoware_behavior_path_planner/src/planner_manager.cpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/interface/scene_module_interface.hpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/interface/scene_module_manager_interface.hpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/src/interface/scene_module_manager_interface.cpp
system/autoware_default_adapi/src/planning.cpp

Some of behavior path planner modules inserts stop points but no one outputs velocity factor.
In this PR, I added interface to publish velocity factor topic.
- Link
None.
None.
None.

feat(bpp): add velocity interface

---

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/interface.cpp

Outputs velocity factor when this module modifies path velocity.
None.
None.
None.

feat(lane_change): output velocity factor

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp

Outputs velocity factor when this module modifies path velocity.
None.
None.
None.

feat(goal_planner): output velocity factor

---

system/mrm_comfortable_stop_operator/include/mrm_comfortable_stop_operator/mrm_comfortable_stop_operator_core.hpp
system/mrm_comfortable_stop_operator/package.xml
system/mrm_comfortable_stop_operator/src/mrm_comfortable_stop_operator/mrm_comfortable_stop_operator_core.cpp

Add updateParam to facilitate comfortable stop param tuning and avoid relaunching autoware to test new params 
Note: I did not add the option to change the Hz of the module since I believe that might cause some troubles and it is best to not change it while Autoware is running
- Link
PSim
https://github.com/user-attachments/assets/5f8f4841-b9c2-462e-8ef6-7190ab0fea22
None.
None.
None.

feat(mrm_comfortable_stop_operator): add updateParam for mrm comfortable stop

---

common/tier4_state_rviz_plugin/src/velocity_steering_factors_panel.cpp

Sort table col by distance.
- Link
Psim
None.
None.
None.

fix(factors_panel): sort by distance to stop/decel or point where it starts moving the steering

---

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/data_structs.hpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/helper.hpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/utils.hpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp

This PR removes redundant calculation of lanelet related funtions, by adding substituting the result in  `AvoidancePlanningData` .
Especially the below two results are tackled in this Pr.
- `getClosestLanelet`
- `calcDistanceToRedTrafficLight`
- `isAllowedGoalModification`
None
None.
None.
None.

perf(static_obstacle_avoidance): remove redundant calculation related to lanelet functions

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_module.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/thread_data.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp

depends https://github.com/autowarefoundation/autoware.universe/pull/9270 ,the diff is below
https://github.com/tier4/autoware.universe/compare/tier4:autoware.universe:refactor/goal-candidate...refactor/goal-candidate2
once goal_candidates are generated at main thread, they remain at the same positions, and only safety information is updated, keeping the same number. so GoalPlannerModule owns the goal_candidate and set it once to GoalPlannerData.
- main-thread --> GoalPlannerData
- Link
- https://evaluation.tier4.jp/evaluation/reports/40474d60-717f-50c7-be4a-680a0e13b906?project_id=prd_jt
None.
None.
None.

feat(goal_planner): move goal_candidates from ThreadSafeData to GoalPlannerData

---

perception/perception_utils/CMakeLists.txt

This PR changes to install `perception_utils`'s include directory to solve the following problem.
https://github.com/autowarefoundation/autoware/actions/runs/11883993784/job/33111547398?pr=5446#step:5:16248
```
#94 80.89 --- stderr: autoware_tensorrt_yolox
#94 80.89 /autoware/src/universe/autoware.universe/perception/autoware_tensorrt_yolox/src/tensorrt_yolox_node.cpp:18:10: fatal error: perception_utils/run_length_encoder.hpp: No such file or directory
#94 80.89    18 | #include "perception_utils/run_length_encoder.hpp"
#94 80.89       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#94 80.89 compilation terminated.
#94 80.89 gmake[2]: *** [CMakeFiles/autoware_tensorrt_yolox_node.dir/build.make:76: CMakeFiles/autoware_tensorrt_yolox_node.dir/src/tensorrt_yolox_node.cpp.o] Error 1 …
```

chore(perception_utils): install include directory

---

launch/tier4_control_launch/launch/control.launch.xml

Use preset.yaml to control which modules to launch for control modules just as how planning modules are launched.
autoware_launch PR: https://github.com/autowarefoundation/autoware_launch/pull/1237
Psim, [Evaluator](https://evaluation.tier4.jp/evaluation/reports/67e201f0-a840-52de-b3d0-e6d64f9d14f8?project_id=prd_jt).
None.
None.
None.

feat(tier4_control_launch): use preset.yaml to control which modules to launch for control modules

---

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp

Currently `route_handler->getClosestLaneletWithinRoute` was used to calculate the closest lanelet. To decrease the processing time, the functions to obtain the closest lanelet is changed to `lanelet::utils::query::getClosestLanelet`.
https://github.com/autowarefoundation/autoware.universe/pull/9355
None.
None.
None.

perf(static_obstacle_avoidance): use lanelet::utils instead of route handle for closest lanelet

---

localization/autoware_pose_estimator_arbiter/src/shared_data.hpp
localization/yabloc/yabloc_pose_initializer/CMakeLists.txt

Include opencv as a system header.
This solves the following clang-tidy diagnostic error.
```
clang-tidy-14 --use-color -p=build/ /home/veqcc/work/autoware/src/universe/autoware.universe/localization/yabloc/yabloc_pose_initializer/src/camera/semantic_segmentation.cpp
/usr/include/opencv4/opencv2/flann/index_testing.h:249:11: error: variable 'p1' set but not used [clang-diagnostic-unused-but-set-variable]
float p1;
^
1 error generated.
Error while processing /home/veqcc/work/autoware/src/universe/autoware.universe/localization/yabloc/yabloc_pose_initializer/src/camera/semantic_segmentation.cpp.
Found compiler error(s).
```
- Link
None.
None.
None.

fix(yabloc_pose_initializer): include opencv as system

---

localization/autoware_pose_estimator_arbiter/src/shared_data.hpp

Added `functional` include.
This solves the following clang-tidy error
```
/home/veqcc/work/autoware/src/universe/autoware.universe/localization/autoware_pose_estimator_arbiter/src/shared_data.hpp:43:32: error: invalid range expression of type 'const auto'; no viable 'begin' function available [clang-diagnostic-error]
for (const auto & callback : callbacks_) {
^ ~~~~~~~~~~
/home/veqcc/work/autoware/src/universe/autoware.universe/localization/autoware_pose_estimator_arbiter/src/shared_data.hpp:43:34: error: use of undeclared identifier 'callbacks_'; did you mean 'callback'? [clang-diagnostic-error]
for (const auto & callback : callbacks_) {
^
/home/veqcc/work/autoware/src/universe/autoware.universe/localization/autoware_pose_estimator_arbiter/src/shared_data.hpp:43:23: note: 'callback' …
```

fix(autoware_pose_estimator_arbiter): add missing include

---

control/autoware_trajectory_follower_node/src/controller_node.cpp

Use string format.
This solves the following clang-tidy error
```
clang-tidy-14 --use-color -p=build/ /home/veqcc/work/autoware/src/universe/autoware.universe/control/autoware_trajectory_follower_node/src/controller_node.cpp
/home/veqcc/work/autoware/src/universe/autoware.universe/control/autoware_trajectory_follower_node/src/controller_node.cpp:146:73: error: format string is not a string literal (potentially insecure) [clang-diagnostic-format-security]
RCLCPP_INFO_THROTTLE(get_logger(), clock, logger_throttle_interval, msg.c_str());
^
/opt/ros/humble/include/rclcpp/rclcpp/logging.hpp:671:7: note: expanded from macro 'RCLCPP_INFO_THROTTLE'
__VA_ARGS__); \
^~~~~~~~~~~
/opt/ros/humble/include/rcutils/rcutils/logging_macros.h:680:5: note: expanded from macro …
```

fix(autoware_trajectory_follower_node): fix clang-diagnostic-format-security

---

control/autoware_control_validator/include/autoware/control_validator/control_validator.hpp

Removed unnecessary `is_velocity_valid_` variable.
This solves the following clang-tidy error
```
autoware/src/universe/autoware.universe/control/autoware_control_validator/include/autoware/control_validator/control_validator.hpp:152:8: error: private field 'is_velocity_valid_' is not used [clang-diagnostic-unused-private-field]
bool is_velocity_valid_{true};
^
```
- Link
None.
None.
None.

fix(autoware_control_validator): fix clang-diagnostic-unused-private-field

---

control/control_performance_analysis/src/control_performance_analysis_core.cpp

Removed unnecessary `move`.
This solves the following clang-tidy error
```
autoware/src/universe/autoware.universe/control/control_performance_analysis/src/control_performance_analysis_core.cpp:339:9: error: moving a temporary object prevents copy elision [clang-diagnostic-pessimizing-move]
std::move(std::make_unique<msg::DrivingMonitorStamped>(driving_status_vars));
^
/home/veqcc/work/autoware/src/universe/autoware.universe/control/control_performance_analysis/src/control_performance_analysis_core.cpp:339:9: note: remove std::move call here
std::move(std::make_unique<msg::DrivingMonitorStamped>(driving_status_vars));
^~~~~~~~~~  
```
- Link
None.
None.
None.

fix(control_performance_analysis): clang-diagnostic-pessimizing-move

---

control/autoware_control_validator/src/control_validator.cpp
control/autoware_lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker_node.cpp
control/autoware_mpc_lateral_controller/README.md

The empty predicted trajectory is intended when the MPC is in an emergency such as too large deviation from the planning trajectory.
Based on this specification, I changed the logger level of the error/warn messages for the predicted trajectory since they fill the terminal.
None.
None.
None.

feat: suppress warning/error of the empty predicted trajectory by MPC

---

control/autoware_mpc_lateral_controller/src/mpc.cpp

Fixed the following cppcheck `variableScope` warning
```
control/autoware_mpc_lateral_controller/src/mpc.cpp:514:9: style: The scope of the variable 'idx_x_i_prev' can be reduced. [variableScope]
int idx_x_i_prev = (i - 1) * DIM_X;
^
```
- Link
None.
None.
None.

fix(autoware_mpc_lateral_controller): fix variableScope

---

control/autoware_mpc_lateral_controller/CMakeLists.txt
control/autoware_mpc_lateral_controller/include/autoware/mpc_lateral_controller/mpc.hpp
control/autoware_mpc_lateral_controller/include/autoware/mpc_lateral_controller/mpc_lateral_controller.hpp
control/autoware_mpc_lateral_controller/src/mpc.cpp
control/autoware_mpc_lateral_controller/src/mpc_lateral_controller.cpp
control/autoware_mpc_lateral_controller/test/test_mpc.cpp
control/autoware_trajectory_follower_node/src/controller_node.cpp

Suppress the too-frequent MPC's warning which fills the terminal.
Instead, set a diag with a detailed reason, and show it on the terminal once as follows.
unit test passed perfectly, and psim worked as expected.
None.
None.
None.

feat(mpc_lateral_controller): suppress rclcpp_warning/error

---

planning/autoware_obstacle_stop_planner/src/adaptive_cruise_control.cpp
planning/autoware_obstacle_stop_planner/src/adaptive_cruise_control.hpp
planning/autoware_obstacle_stop_planner/src/debug_marker.hpp

Fixed the following cppcheck warnings
```
planning/autoware_obstacle_stop_planner/src/adaptive_cruise_control.hpp:206:10: style: inconclusive: Technically the member function 'autoware::motion_planning::AdaptiveCruiseController::calcThreshDistToForwardObstacle' can be const. [functionConst]
double calcThreshDistToForwardObstacle(const double current_vel, const double obj_vel);
^
planning/autoware_obstacle_stop_planner/src/adaptive_cruise_control.cpp:575:34: note: Technically the member function 'autoware::motion_planning::AdaptiveCruiseController::calcThreshDistToForwardObstacle' can be const.
double AdaptiveCruiseController::calcThreshDistToForwardObstacle(
^
planning/autoware_obstacle_stop_planner/src/adaptive_cruise_control.hpp:206:10: note: Technically the member function …
```

fix(autoware_obstacle_stop_planner): fix cppcheck warnings

---

planning/autoware_costmap_generator/include/autoware/costmap_generator/utils/points_to_costmap.hpp

```
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/autoware_costmap_generator/include/autoware/costmap_generator/utils/points_to_costmap.hpp:82:10: error: private field 'y_cell_size_' is not used [clang-diagnostic-unused-private-field]
double y_cell_size_;
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/autoware_costmap_generator/include/autoware/costmap_generator/utils/points_to_costmap.hpp:83:10: error: private field 'x_cell_size_' is not used [clang-diagnostic-unused-private-field]
double x_cell_size_;
^
```
- Link
None.
None.
None.

fix(autoware_costmap_generator): fix clang-diagnostic-unused-private-field

---

planning/autoware_obstacle_cruise_planner/include/autoware/obstacle_cruise_planner/planner_interface.hpp

This is a fix based on clang-tidy `clang-diagnostic-defaulted-function-deleted` error.
```
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/autoware_obstacle_cruise_planner/include/autoware/obstacle_cruise_planner/planner_interface.hpp:69:3: error: explicitly defaulted default constructor is implicitly deleted [clang-diagnostic-defaulted-function-deleted]
PlannerInterface() = default;
^
```
- Link
None.
None.
None.

fix(autoware_obstacle_cruise_planner): fix clang-diagnostic-defaulted-function-deleted

---

planning/autoware_freespace_planning_algorithms/include/autoware/freespace_planning_algorithms/rrtstar.hpp
planning/autoware_freespace_planning_algorithms/src/rrtstar.cpp

```
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/autoware_freespace_planning_algorithms/include/autoware/freespace_planning_algorithms/rrtstar.hpp:72:22: error: private field 'original_vehicle_shape_' is not used [clang-diagnostic-unused-private-field]
const VehicleShape original_vehicle_shape_;
^
```
- Link
None.
None.
None.

fix(autoware_freespace_planning_algorithms): fix clang-diagnostic-unused-private-field

---

planning/autoware_surround_obstacle_checker/src/debug_marker.cpp
planning/autoware_surround_obstacle_checker/src/debug_marker.hpp
planning/autoware_surround_obstacle_checker/src/node.cpp

```
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/autoware_surround_obstacle_checker/src/debug_marker.hpp:80:10: error: private field 'base_link2front_' is not used [clang-diagnostic-unused-private-field]
double base_link2front_;
^
```
- Link
None.
None.
None.

fix(autoware_surround_obstacle_checker): fix clang-diagnostic-unused-private-field

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_module.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/thread_data.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp

remove static_target_objects and dynamic_target_objects from ThreadSafeData because there is no need to share
- Link
- https://evaluation.tier4.jp/evaluation/reports/4afa22b2-fbc1-50f0-801c-b2064c3b77b0?project_id=prd_jt
None.
None.
None.

feat(goal_planner): remove unnecessary member from ThreadSafeData

---

planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/manager.cpp

This is a fix based on clang-tidy `clang-diagnostic-unused-lambda-capture` error.
```
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/manager.cpp:363:11: error: lambda capture 'this' is not used [clang-diagnostic-unused-lambda-capture]
return [this, lane_set](const std::shared_ptr<SceneModuleInterface> & scene_module) {
^~~~~
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/manager.cpp:558:11: error: lambda capture 'this' is not used [clang-diagnostic-unused-lambda-capture]
return [this, lane_set](const std::shared_ptr<SceneModuleInterface> & scene_module) {
^~~~~
```
- Link …

fix(autoware_behavior_velocity_intersection_module): fix clang-diagnostic-unused-lambda-capture

---

planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection.cpp

This is a fix based on clang-tidy `clang-diagnostic-unused-parameter` error.
```
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection.cpp:493:13: error: unused parameter 'result' [clang-diagnostic-unused-parameter]
const T & result, const tier4_planning_msgs::msg::PathWithLaneId & path, bool * default_safety,
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection.cpp:493:70: error: unused parameter 'path' [clang-diagnostic-unused-parameter]
const T & result, const tier4_planning_msgs::msg::PathWithLaneId & path, bool * default_safety,
^ …
```

fix(autoware_behavior_velocity_intersection_module): fix clang-diagnostic-unused-parameter

---

planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_utils.cpp

Rather than interpolating orientation, a smooth path can be generated by calculating the azimuth angle for the interpolated position.
before: 
after #9361:
after #9362 
- Link
2024/11/18 https://evaluation.tier4.jp/evaluation/reports/a8e2f04f-8566-5840-9c91-8ca2acc36dc2/?project_id=prd_jt
None.
None.
None.

feat(behavior_path_planner_common): use azimuth for interpolatePose

---

planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/drivable_area_expansion/static_drivable_area.cpp

In this PR, we check if the same point has already been inserted.
This fixed path distortion caused by duplicated points.
before
after
t4 internal ticket : https://tier4.atlassian.net/browse/RT1-4810
psim
2024/11/18 https://evaluation.tier4.jp/evaluation/reports/b3906a49-741b-5fc5-a388-13fcd3419152/?project_id=prd_jt
None.
None.
None.

fix(behavior_path_planner_common): prevent duplicated point insertion in cutOverlappedLanes

---

planning/behavior_velocity_planner/autoware_behavior_velocity_run_out_module/src/manager.cpp

This is a fix based on clang-tidy `clang-diagnostic-unused-lambda-capture` error.
Because it is an overriding function, it is not possible to remove arguments that are no longer needed.
Therefore, suppressed by [[maybe_unused]].
```
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/behavior_velocity_planner/autoware_behavior_velocity_run_out_module/src/manager.cpp:166:7: error: lambda capture 'path' is not used [clang-diagnostic-unused-lambda-capture]
[&path]([[maybe_unused]] const std::shared_ptr<SceneModuleInterface> & scene_module) -> bool {
~^~~~
```
- Link
None.
None.
None.

fix(autoware_behavior_velocity_run_out_module): fix clang-diagnostic-unused-lambda-capture

---

planning/behavior_velocity_planner/autoware_behavior_velocity_walkway_module/src/manager.cpp

This is a fix based on clang-tidy `clang-diagnostic-unused-lambda-capture` error.
```
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/behavior_velocity_planner/autoware_behavior_velocity_walkway_module/src/manager.cpp:48:31: error: lambda capture 'path' is not used [clang-diagnostic-unused-lambda-capture]
const auto launch = [this, &path](const auto & lanelet, const auto & use_regulatory_element) {
~~~^~~~
```
- Link
None.
None.
None.

fix(autoware_behavior_velocity_walkway_module): fix clang-diagnostic-unused-lambda-capture

---

planning/behavior_velocity_planner/autoware_behavior_velocity_planner/src/node.cpp

This is a fix based on clang-tidy `clang-diagnostic-format-security` error.
```
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/behavior_velocity_planner/autoware_behavior_velocity_planner/src/node.cpp:236:73: error: format string is not a string literal (potentially insecure) [clang-diagnostic-format-security]
RCLCPP_INFO_THROTTLE(get_logger(), clock, logger_throttle_interval, msg.c_str());
^
/opt/ros/humble/include/rclcpp/rclcpp/logging.hpp:671:7: note: expanded from macro 'RCLCPP_INFO_THROTTLE'
__VA_ARGS__); \
^~~~~~~~~~~
/opt/ros/humble/include/rcutils/rcutils/logging_macros.h:680:5: note: expanded from macro 'RCUTILS_LOG_INFO_THROTTLE_NAMED'
__VA_ARGS__)
^~~~~~~~~~~
/opt/ros/humble/include/rcutils/rcutils/logging_macros.h:79:64: note: expanded from macro …
```

fix(autoware_behavior_velocity_planner): fix clang-diagnostic-format-security

---

planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/pull_out_planner_base.cpp

This is a fix based on clang-tidy `clang-diagnostic-unused-variable` error.
```
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/pull_out_planner_base.cpp:29:16: error: unused variable 'vehicle_footprint' [clang-diagnostic-unused-variable]
const auto & vehicle_footprint = vehicle_info_.createFootprint();
^
```
- Link
None.
None.
None.

fix(autoware_behavior_path_start_planner_module): fix clang-diagnostic-unused-variable

---

planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/src/decisions.cpp

This is a fix based on clang-tidy `clang-diagnostic-unused-parameter` error.
```
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/src/decisions.cpp:27:63: error: unused parameter 'path' [clang-diagnostic-unused-parameter]
const T &, const tier4_planning_msgs::msg::PathWithLaneId & path)
^
```
- Link
None.
None.
None.

fix(autoware_behavior_velocity_blind_spot_module): fix clang-diagnostic-unused-parameter

---

control/autoware_pid_longitudinal_controller/CMakeLists.txt
control/autoware_pid_longitudinal_controller/include/autoware/pid_longitudinal_controller/pid_longitudinal_controller.hpp
control/autoware_pid_longitudinal_controller/package.xml
control/autoware_pid_longitudinal_controller/src/pid_longitudinal_controller.cpp

Suppress the too-frequent MPC's warning which fills the terminal.
Instead, set a diag with a detailed reason, and show it on the terminal once as follows.
unit test passed perfectly, and psim worked as expected.
None.
None.
None.

feat(pid_longitudinal_controller): suppress rclcpp_warning/error

---

evaluator/autoware_planning_evaluator/package.xml
evaluator/kinematic_evaluator/package.xml
evaluator/localization_evaluator/package.xml
evaluator/perception_online_evaluator/package.xml

This PR add / modify dependencies written in package.xml.
The changed dependencies are almost about ament_index_cpp.
Jazzy has a build error due to not having a dependency on ament_index_cpp.
We have found similar errors in other ROS packages and have confirmed that they are not specific to the author's environment.
Reference: https://github.com/autowarefoundation/autoware.universe/issues/7598
Base pull request: https://github.com/autowarefoundation/autoware.universe/pull/7600
colcon test passed.
This PR does not change the behavior of Autoware.
None.
None.
None.

fix(evaluator): missing dependency in evaluator components

---

build_depends.repos

Change autoware_adapi_msgs version to pre-release branch to evaluate features in the next release.
https://github.com/autowarefoundation/autoware/pull/5459
https://github.com/autowarefoundation/autoware.universe/pull/9359
Check build passes.
None.
None.
None.

feat(build_depends.repos): change autoware_adapi_msgs version

---

planning/autoware_obstacle_cruise_planner/include/autoware/obstacle_cruise_planner/utils.hpp
planning/autoware_obstacle_cruise_planner/src/pid_based_planner/pid_based_planner.cpp
planning/autoware_obstacle_cruise_planner/src/planner_interface.cpp
planning/autoware_obstacle_cruise_planner/src/utils.cpp

I fixed logic so that this planner outputs velocity factor during adaptive cruising.
:warning: Please merge following PR at first. (NOTE: I added new planning behavior in order to distinguish adaptive cruise behavior from obstacle stop.)
- https://github.com/autowarefoundation/autoware_adapi_msgs/pull/67
https://github.com/user-attachments/assets/0b81193e-73b5-4c3e-ad13-25b2341cd416
- Link
None.
None.
None.

feat(obstacle_cruise_planner): outputs velocity factor when the ego follows front vehicle.

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/shift_pull_over.cpp

If the same pose is inserted for points with different lateral positions, it will not be smooth when interpolating with splines. It would be smoother if the same posture is not inserted.
before: 
after #9361:
- Link
psim
2024/11/21 https://evaluation.tier4.jp/evaluation/reports/583046b1-fc82-5428-aef1-fa550491afab/?project_id=prd_jt
None.
None.
None.

feat(goal_planner): do not insert shift end pose on pull over lane to path

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/pull_over_planner/shift_pull_over.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/shift_pull_over.cpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/parking_departure/geometric_parallel_parking.hpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/parking_departure/geometric_parallel_parking.cpp

This PR is just renaming variables
goal planner supports pull over on road_lane not only shoulder_lane(subtype: road_shoulder).
so, pull_over_lane for the variable name.
pull_over_lanes means both road_lanes and shoulder_lanes
- Link
2024/11/21 https://evaluation.tier4.jp/evaluation/reports/64f8a2e9-8987-5182-add7-7aee9d1b2722/?project_id=prd_jt
None.
None.
None.

refactor(goal_planner): rename shoulder_lane to pull_over_lane

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/geometric_pull_over.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/shift_pull_over.cpp

use departure_check_lane ( introduced in https://github.com/autowarefoundation/autoware.universe/pull/8716 ) for shift/geoetric planner too.
currently pull over path with large vehicle is sometimes judged as invalid with lanedeparture check.
lane departure_check_lane is as follow. 
---
yellow lanes are for lane departure check
- before: pull over lane and current lane
- after: pull over lane and the same segment
- https://github.com/autowarefoundation/autoware.universe/pull/8716
2024/11/21 https://evaluation.tier4.jp/evaluation/reports/03a71a48-7d44-536e-8020-34c7e9ed2dbf/?project_id=prd_jt
2024/11/21 https://evaluation.tier4.jp/evaluation/reports/2619a5e5-c10d-554e-9aed-3b8cb1536fb8/?project_id=prd_jt
2024/11/21 https://evaluation.tier4.jp/evaluation/reports/52631ab7-e143-5606-9c28-04f30c …

fix(goal_planner): use departure_check_lane for path

---

localization/autoware_ndt_scan_matcher/include/autoware/ndt_scan_matcher/ndt_omp/multi_voxel_grid_covariance_omp.h
localization/autoware_ndt_scan_matcher/include/autoware/ndt_scan_matcher/ndt_omp/multigrid_ndt_omp.h

Fixed cppcheck `unusedFunction` warnings
```
localization/autoware_ndt_scan_matcher/include/autoware/ndt_scan_matcher/ndt_omp/multi_voxel_grid_covariance_omp.h:177:0: style: The function 'getCov' is never used. [unusedFunction]
const Eigen::Matrix3d & getCov() const { return (cov_); }
^
localization/autoware_ndt_scan_matcher/include/autoware/ndt_scan_matcher/ndt_omp/multi_voxel_grid_covariance_omp.h:197:0: style: The function 'getPointCount' is never used. [unusedFunction]
int getPointCount() const { return (nr_points_); }
^
localization/autoware_ndt_scan_matcher/include/autoware/ndt_scan_matcher/ndt_omp/multi_voxel_grid_covariance_omp.h:355:0: style: The function 'apply_filter_thread' is never used. [unusedFunction]
inline bool apply_filter_thread(int tid, GridNodeType & node)
^ …
```

fix(autoware_ndt_scan_matcher): remove unsed functions

---

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/scene.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/base_class.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/data_structs.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/debug_structs.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/markers.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/utils.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/package.xml
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/markers.cpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/path_safety_checker/objects_filtering.hpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_safety_checker/objects_filtering.cpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/test/test_objects_filtering.cpp

There are two goal to this PR.
1. to update ego to obj distance to the extended object
2. to separate objects based on its behavior in the lanes, i.e. stopped, moving, or if it within expanded lane.
[TIER IV Internal Link](https://evaluation.tier4.jp/evaluation/reports/d5cb0ace-fb9c-5974-81fb-c3445c5188fa?project_id=prd_jt)
None.
None.
None.

refactor(lane_change): separate target lane leading based on obj behavior

---

common/autoware_perception_rviz_plugin/src/object_detection/object_polygon_detail.cpp

Fix bounding box rendering under the following condition.
- orientation_availability: SIGN_UNKNOWN
- Polygon Type: 2d
Before
After
- Link
None.
None.
None.

fix(autoware_perception_rviz_plugin): fix orientation indication rendering fix

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp

fix(goal_planner)!: remove stop reason

---

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp

fix(avoidance)!: remove stop reason

---

planning/behavior_path_planner/autoware_behavior_path_planner/README.md
planning/behavior_path_planner/autoware_behavior_path_planner/include/autoware/behavior_path_planner/behavior_path_planner_node.hpp
planning/behavior_path_planner/autoware_behavior_path_planner/include/autoware/behavior_path_planner/planner_manager.hpp
planning/behavior_path_planner/autoware_behavior_path_planner/launch/behavior_path_planner.launch.xml
planning/behavior_path_planner/autoware_behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/interface/scene_module_interface.hpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/src/interface/scene_module_interface.cpp

- Link
Please confirm that this module doesn't output stop reason.
```
/planning/scenario_planning/status/stop_reasons
```
After this PR, this module only outputs velocity/steering factors.
None.
None.

fix(bpp)!: remove stop reason

---

control/autoware_smart_mpc_trajectory_follower/CMakeLists.txt

Suppressed `clang-diagnostic-ignored-optimization-argument` by ignoring GCC specific compiler optimization.
```
error: optimization flag '-fno-fat-lto-objects' is not supported [clang-diagnostic-ignored-optimization-argument]
```
- Link
None.
None.
None.

fix(autoware_smart_mpc_trajectory_follower): fix clang-diagnostic-ignored-optimization-argument

---

common/autoware_pyplot/package.xml

The `autoware_pyplot` package is missing this dependency for building Python extensions.
- https://github.com/autowarefoundation/autoware-deb-packages/actions/runs/12008076761/job/33470071770?pr=103
None.
None.
None.

fix(autoware_pyplot): fix missing python3-dev dependency

---

planning/autoware_surround_obstacle_checker/README.md
planning/autoware_surround_obstacle_checker/launch/surround_obstacle_checker.launch.xml
planning/autoware_surround_obstacle_checker/src/debug_marker.cpp
planning/autoware_surround_obstacle_checker/src/debug_marker.hpp
planning/autoware_surround_obstacle_checker/src/node.cpp
planning/autoware_surround_obstacle_checker/src/node.hpp
planning/autoware_surround_obstacle_checker/surround_obstacle_checker-design.ja.md

- Link
Please confirm that this module doesn't output stop reason.
```
/planning/scenario_planning/status/stop_reasons
```
None.
After this PR, this module only outputs velocity factors.
None.

fix(surround_obstacle_checker)!: remove stop reason

---

planning/autoware_obstacle_cruise_planner/README.md
planning/autoware_obstacle_cruise_planner/include/autoware/obstacle_cruise_planner/planner_interface.hpp
planning/autoware_obstacle_cruise_planner/include/autoware/obstacle_cruise_planner/type_alias.hpp
planning/autoware_obstacle_cruise_planner/launch/obstacle_cruise_planner.launch.xml
planning/autoware_obstacle_cruise_planner/src/planner_interface.cpp

- Link
Please confirm that this module doesn't output stop reason.
```
/planning/scenario_planning/status/stop_reasons
```
None.
After this PR, this module only outputs velocity factors.
None.

fix(obstacle_cruise_planner)!: remove stop reason

---

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/interface.hpp

This is a fix based on clang-tidy `clang-diagnostic-overloaded-virtual` error.
```
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/interface.hpp:108:8: error: 'autoware::behavior_path_planner::LaneChangeInterface::updateRTCStatus' hides overloaded virtual function [clang-diagnostic-overloaded-virtual]
void updateRTCStatus(
^
```
- Link
None.
None.
None.

fix(autoware_behavior_path_lane_change_module): fix clang-diagnostic-overloaded-virtual

---

perception/autoware_lidar_centerpoint/include/autoware/lidar_centerpoint/node.hpp

```
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_lidar_centerpoint/include/autoware/lidar_centerpoint/node.hpp:54:9: error: private field 'score_threshold_' is not used [clang-diagnostic-unused-private-field]
float score_threshold_{0.0};
^
```
- Link
None.
None.
None.

fix(autoware_lidar_centerpoint): fix clang-diagnostic-unused-private-field

---

perception/autoware_image_projection_based_fusion/include/autoware/image_projection_based_fusion/roi_detected_object_fusion/node.hpp

This is a fix based on clang-tidy `clang-diagnostic-inconsistent-missing-override` error.
```
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_image_projection_based_fusion/include/autoware/image_projection_based_fusion/roi_detected_object_fusion/node.hpp:60:8: error: 'out_of_scope' overrides a member function but is not marked 'override' [clang-diagnostic-inconsistent-missing-override]
bool out_of_scope(const DetectedObject & obj);
^
```
- Link
None.
None.
None.

fix(autoware_image_projection_based_fusion): fix clang-diagnostic-inconsistent-missing-override

---

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/calculation.cpp

This is a fix based on clang-tidy `clang-diagnostic-error` error.
```
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/calculation.cpp:361:9: error: reference to local binding 'max_accel' declared in enclosing function 'autoware::behavior_path_planner::utils::lane_change::calculation::calc_lon_acceleration_samples' [clang-diagnostic-error]
if (max_accel < 0.0 || transient_data.is_ego_stuck) return true;
^
```
- Link
None.
None.
None.

fix(autoware_behavior_path_lane_change_module): fix clang-diagnostic-error

---

common/autoware_trajectory/src/path_point.cpp
common/autoware_trajectory/src/path_point_with_lane_id.cpp
common/autoware_trajectory/src/pose.cpp

fix `autoware_trajectory`'s crop bug.
- [TIER IV Slack Link](https://star4.slack.com/archives/C0575HP7NJG/p1732610098859539?thread_ts=1732579300.286229&cid=C0575HP7NJG)
None.
None.
None.

fix(autoware_trajectory): autoware_trajectory bug

---

planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/utils.hpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/utils.cpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/test/test_utils.cpp

Added unit test for `/autoware_behavior_path_planner_common/src/utils/utils.cpp`.
None
Colcon test
```
1: [----------] Global test environment set-up.
1: [----------] 22 tests from BehaviorPathPlanningUtilTest
1: [ RUN      ] BehaviorPathPlanningUtilTest.l2Norm
1: [       OK ] BehaviorPathPlanningUtilTest.l2Norm (73 ms)
1: [ RUN      ] BehaviorPathPlanningUtilTest.checkCollisionBetweenPathFootprintsAndObjects
1: [       OK ] BehaviorPathPlanningUtilTest.checkCollisionBetweenPathFootprintsAndObjects (71 ms)
1: [ RUN      ] BehaviorPathPlanningUtilTest.checkCollisionBetweenFootprintAndObjects
1: [       OK ] BehaviorPathPlanningUtilTest.checkCollisionBetweenFootprintAndObjects (69 ms)
1: [ RUN      ] BehaviorPathPlanningUtilTest.calcLateralDistanceFromEgoToObject
1: [       OK ] …
```

test(bpp_common): add unit test for utils

---

launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.xml
planning/autoware_static_centerline_generator/test/test_static_centerline_generator.test.py
planning/behavior_velocity_planner/autoware_behavior_velocity_planner/config/behavior_velocity_planner.param.yaml
planning/behavior_velocity_planner/autoware_behavior_velocity_planner/launch/behavior_velocity_planner.launch.xml
planning/behavior_velocity_planner/autoware_behavior_velocity_planner/schema/behavior_velocity_planner.schema.json
planning/behavior_velocity_planner/autoware_behavior_velocity_planner/test/src/test_node_interface.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/CMakeLists.txt
planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/config/behavior_velocity_planner_common.param.yaml
planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/schema/behavior_velocity_planner_common.schema.json
planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/scripts/dilemma_zone_plotter.py

Previously, `behaviour_velocity_planner/config/behaviour_velocity_planner.param.yaml` was used in `autoware_behaviour_velocity_planner` and `autoware_behaviour_velocity_planner_common`.
In this PR, `behaviour_velocity_planner.param.yaml` is split into `behaviour_velocity_planner.param.yaml` and `behaviour_velocity_planner_common.param.yaml`. `behaviour_velocity_planner.param.yaml` is only used in `behaviour_velocity_planner` and `behaviour_velocity_planner_common.param.yaml`  is only used in `behaviour_velocity_planner_common` .
- Before
<details><summary>behavior_velocity_planner/config/behavior_velocity_planner.param.yaml</summary>
```yaml
/**:
forward_path_length: 1000.0
backward_path_length: 5.0
behavior_output_path_interval: 1.0
stop_line_extend_length: 5.0 …
```

refactor(autoware_behavior_velocity_planner_common,autoware_behavior_velocity_planner): separate param files

---

planning/autoware_path_optimizer/src/node.cpp

under certain conditions, the onPath method of the path optimizer will spam an error related to the time keeper. This PR solves the issue: 
Before: 
https://github.com/user-attachments/assets/08f4f8d7-028f-4bae-a375-1eca32a00116
After:
https://github.com/user-attachments/assets/13131c5d-1fad-4952-adc8-c3401a7f808c
- Link
Psim
None.
None.
None.

fix(path_optimizer): solve issue with time keeper

---

common/autoware_component_interface_tools/CMakeLists.txt
common/autoware_component_interface_tools/src/service_log_checker.cpp
common/autoware_component_interface_tools/src/service_log_checker.hpp
common/autoware_traffic_light_recognition_marker_publisher/CMakeLists.txt
common/autoware_traffic_light_recognition_marker_publisher/src/traffic_light_recognition_marker_publisher.cpp
common/autoware_traffic_light_recognition_marker_publisher/src/traffic_light_recognition_marker_publisher.hpp

I noticed that the plugins were missing namespaces, this PR adds namespaces in the code and in the plugin definitions in CMake.
None.
None.
None.

fix: fix missing namespaces in C++ code

---

planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/start_planner_module.cpp

Current start planner uses CurrentLanes to calculate the path's shift length and decide if the turn signal should be activated and if it should be the left or right turn signal. 
However, this method disregards the previous lanelets, which might cause the shift length's sign to change when the ego enters a new lanelet. 
In the following example, the left turn signal is wrongly activated.
[Screencast from 2024年10月18日 15時24分50秒.webm](https://github.com/user-attachments/assets/99ac2300-49e2-411d-8702-fca980c555d6)
By using the extended CurrentLanes instead, this issue is solved: 
https://github.com/user-attachments/assets/6cbfe315-0b7f-44ea-a047-80b1bdd1aa6f
ticket:  ([TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT0-33950))
- Link
PSim
None.
None.
None.

fix(start_planner): use extended current lanes to fix turn signal issue

---

perception/autoware_lidar_transfusion/include/autoware/lidar_transfusion/lidar_transfusion_node.hpp

```
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_lidar_transfusion/include/autoware/lidar_transfusion/lidar_transfusion_node.hpp:58:9: error: private field 'score_threshold_' is not used [clang-diagnostic-unused-private-field]
float score_threshold_{0.0};
^
```
- Link
None.
None.
None.

fix(autoware_lidar_transfusion): fix clang-diagnostic-unused-private-field

---

perception/autoware_tracking_object_merger/src/association/data_association.cpp

This is a fix based on clang-tidy `clang-diagnostic-sign-conversion` error.
```
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_tracking_object_merger/src/association/data_association.cpp:97:46: error: implicit conversion changes signedness: 'Eigen::Index' (aka 'long') to 'std::vector::size_type' (aka 'unsigned long') [clang-diagnostic-sign-conversion]
std::vector<std::vector<double>> score(src.rows());
~~~~~ ~~~~^~~~~~
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_tracking_object_merger/src/association/data_association.cpp:99:14: error: implicit conversion changes signedness: 'int' to 'std::vector::size_type' (aka 'unsigned long') [clang-diagnostic-sign-conversion]
score.at(row).resize(src.cols());
~~ ^~~ …
```

fix(autoware_tracking_object_merger): fix clang-diagnostic-sign-conversion

---

perception/autoware_multi_object_tracker/src/debugger/debug_object.hpp
perception/autoware_multi_object_tracker/src/processor/input_manager.hpp

```
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_multi_object_tracker/src/debugger/debug_object.hpp:80:11: error: private field 'marker_id_' is not used [clang-diagnostic-unused-private-field]
int32_t marker_id_ = 0;
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_multi_object_tracker/src/processor/input_manager.hpp:91:10: error: private field 'expected_interval_' is not used [clang-diagnostic-unused-private-field]
double expected_interval_{};
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_multi_object_tracker/src/processor/input_manager.hpp:133:10: error: private field 'target_latency_' is not used …
```

fix(autoware_multi_object_tracker): fix clang-diagnostic-unused-private-field

---

system/autoware_processing_time_checker/src/processing_time_checker.cpp

There are a lot of following warnings in each PR.
```
Check warning on line 55 in system/autoware_processing_time_checker/src/processing_time_checker.cpp
GitHub Actions
/ spell-check-differential
Unknown word (enouh)
```
- Link
None.
None.
None.

fix(autoware_processing_time_checker): fix typo

---

perception/autoware_elevation_map_loader/src/elevation_map_loader_node.cpp

This is a fix based on clang-tidy `clang-diagnostic-format-security` error.
```
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_elevation_map_loader/src/elevation_map_loader_node.cpp:151:40: error: format string is not a string literal (potentially insecure) [clang-diagnostic-format-security]
RCLCPP_ERROR(this->get_logger(), e.what());
^
/opt/ros/humble/include/rclcpp/rclcpp/logging.hpp:1407:7: note: expanded from macro 'RCLCPP_ERROR'
__VA_ARGS__); \
^~~~~~~~~~~
/opt/ros/humble/include/rcutils/rcutils/logging_macros.h:1004:5: note: expanded from macro 'RCUTILS_LOG_ERROR_NAMED'
__VA_ARGS__)
^~~~~~~~~~~
/opt/ros/humble/include/rcutils/rcutils/logging_macros.h:79:64: note: expanded from macro 'RCUTILS_LOG_COND_NAMED'
rcutils_log(&__rcutils_logging_location, …
```

fix(autoware_elevation_map_loader): fix clang-diagnostic-format-security

---

planning/autoware_mission_planner/src/mission_planner/mission_planner.cpp
planning/autoware_mission_planner/src/mission_planner/mission_planner.hpp

Fix a bug where initialization was completed after setting the route and the state was overwritten. 
- [TIER IV internal link](https://star4.slack.com/archives/CBX6XHKA4/p1732255264072239?thread_ts=1729579139.622729&cid=CBX6XHKA4)
[TIER IV internal link](https://star4.slack.com/archives/CBX6XHKA4/p1732767456781819?thread_ts=1729579139.622729&cid=CBX6XHKA4)
If the timer period is too fast, you will not be able to test it manually, so set the check_initialization timer to 10 seconds, for example.
new behavior
1. send route button (failed)
2. initialize pose
3. set goal (failed)
4. wait and initialization done (state=UNSET)
5. set goal (state=SET)
old behavior
1. send route button (state=UNSET)
2. initialize pose
3. set goal (state=SET)
4. wait and initialization done …

fix(mission_planner): fix initialization after route set

---

perception/autoware_tensorrt_common/include/autoware/tensorrt_common/tensorrt_common.hpp

```
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_tensorrt_common/include/autoware/tensorrt_common/tensorrt_common.hpp:225:18: error: private field 'input_dims_' is not used [clang-diagnostic-unused-private-field]
nvinfer1::Dims input_dims_;
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_tensorrt_common/include/autoware/tensorrt_common/tensorrt_common.hpp:226:18: error: private field 'output_dims_' is not used [clang-diagnostic-unused-private-field]
nvinfer1::Dims output_dims_;
^
```
- Link
None.
None.
None.

fix(autoware_tensorrt_common): fix clang-diagnostic-unused-private-field

---

control/autoware_autonomous_emergency_braking/include/autoware/autonomous_emergency_braking/utils.hpp
control/autoware_autonomous_emergency_braking/src/node.cpp
control/autoware_autonomous_emergency_braking/src/utils.cpp
control/autoware_autonomous_emergency_braking/test/test.cpp

I moved some functions to utility functions in a util file. No logic changes were made.
- Link
None.
None.
None.

refactor(autoware_autonomous_emergency_braking): add getObjectOnPathData and getLongitudinalOffset functions

---

evaluator/autoware_planning_evaluator/README.md
evaluator/autoware_planning_evaluator/config/planning_evaluator.param.yaml
evaluator/autoware_planning_evaluator/include/autoware/planning_evaluator/motion_evaluator_node.hpp
evaluator/autoware_planning_evaluator/include/autoware/planning_evaluator/planning_evaluator_node.hpp
evaluator/autoware_planning_evaluator/launch/motion_evaluator.launch.xml
evaluator/autoware_planning_evaluator/launch/planning_evaluator.launch.xml
evaluator/autoware_planning_evaluator/package.xml
evaluator/autoware_planning_evaluator/schema/autoware_planning_evaluator.schema.json
evaluator/autoware_planning_evaluator/src/motion_evaluator_node.cpp
evaluator/autoware_planning_evaluator/src/planning_evaluator_node.cpp
evaluator/autoware_planning_evaluator/test/test_planning_evaluator_node.cpp

Add a bool parameter `output_metrics`, if it's true, the planning_evaluator node writes the statics of the metrics measured during its lifetime to `<ros2_logging_directory>/autoware_metrics/<node_name>-<time_stamp>.json` when shut down.
This feature will be used to collect and analyze test results in real vehicle tests and evaluator tests.
- Link
Psim with `output_metrics=true`:
```bash
$ cat /home/temkeikem/.ros/log/autoware_metrics/autoware_planning_evaluator-2024-11-26-19-00-31.json 
{
"acceleration/count": 285,
"acceleration/description": "Trajectory_acceleration[m/s²]",
"acceleration/max": 1.0012520551681519,
"acceleration/mean": 0.234304107391435,
"acceleration/min": -0.9976022839546204,
"yaw_deviation/count": 285,
"yaw_deviation/description": "Yaw_deviation[rad]", …
```

feat(planning_evaluator): add a trigger to choice whether to output metrics to log folder

---

perception/autoware_lidar_centerpoint/include/autoware/lidar_centerpoint/preprocess/voxel_generator.hpp

This is a fix based on clang-tidy `clang-diagnostic-delete-abstract-non-virtual-dtor` error.
```
/usr/include/c++/11/bits/unique_ptr.h:85:2: error: delete called on 'autoware::lidar_centerpoint::VoxelGeneratorTemplate' that is abstract but has non-virtual destructor [clang-diagnostic-delete-abstract-non-virtual-dtor]
delete __ptr;
^
/usr/include/c++/11/bits/unique_ptr.h:361:4: note: in instantiation of member function 'std::default_delete<autoware::lidar_centerpoint::VoxelGeneratorTemplate>::operator()' requested here
get_deleter()(std::move(__ptr));
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_lidar_centerpoint/lib/centerpoint_trt.cpp:34:17: note: in instantiation of member function 'std::unique_ptr<autoware::lidar_centerpoint::VoxelGeneratorTemplate>: …
```

fix(autoware_lidar_centerpoint): fix clang-diagnostic-delete-abstract-non-virtual-dtor

---

perception/autoware_image_projection_based_fusion/CMakeLists.txt
perception/autoware_image_projection_based_fusion/include/autoware/image_projection_based_fusion/debugger.hpp
perception/autoware_image_projection_based_fusion/src/debugger.cpp

The following PR was mistakenly assumed to be in use but was deleted as it was not actually being utilized.
```
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_image_projection_based_fusion/include/autoware/image_projection_based_fusion/debugger.hpp:59:18: error: private field 'node_ptr_' is not used [clang-diagnostic-unused-private-field]
rclcpp::Node * node_ptr_;
^
```
- #9473 
None.
None.
None.

fix(autoware_image_projection_based_fusion): fix clang-diagnostic-unused-private-field

---

perception/autoware_tensorrt_classifier/include/autoware/tensorrt_classifier/calibrator.hpp
perception/autoware_tensorrt_classifier/include/autoware/tensorrt_classifier/tensorrt_classifier.hpp

This is a fix based on clang-tidy errors.
```
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_tensorrt_classifier/include/autoware/tensorrt_classifier/calibrator.hpp:273:10: error: 'getQuantile' overrides a member function but is not marked 'override' [clang-diagnostic-inconsistent-missing-override]
double getQuantile() const noexcept
^
/usr/include/x86_64-linux-gnu/NvInfer.h:8412:20: note: overridden virtual function is here
virtual double getQuantile() const noexcept = 0;
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_tensorrt_classifier/include/autoware/tensorrt_classifier/calibrator.hpp:279:10: error: 'getRegressionCutoff' overrides a member function but is not marked 'override' …
```

fix(autoware_tensorrt_classifier): fix clang errors

---

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/utils.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp

the current ego predicted path velocity doesn’t have any maximum limit put into it.
However, it should have limit, since for each lane change path, there is prepare velocity and lane changing velocity assigned to it.
With the current computation, the velocity might exceed prepare velocity and lane changing velocity.
The polygon is longer.
The size of the polygon is reduced.
- Link
1. PSIM
2. Internal evaluator [TIER IV Internal link](https://evaluation.tier4.jp/evaluation/reports/f9399ae5-e5a8-5cf0-ad5f-b9fb34fc1dad?project_id=prd_jt)
None.
None.
None.

fix(lane_change): cap ego's predicted path velocity (RT1-8505)

---

perception/autoware_traffic_light_visualization/src/traffic_light_roi_visualizer/node.cpp
perception/autoware_traffic_light_visualization/src/traffic_light_roi_visualizer/shape_draw.cpp

This PR fixes the following issue: https://github.com/autowarefoundation/autoware.universe/issues/7924
- Link
The rough roi of unknown traffic light is shown in white.
The error message resulted by the undetected traffic lights is fixed, so that it will not flood the terminal.
https://github.com/autowarefoundation/autoware.universe/pull/5934
Previously, it was required to output the signal message as long as the rough roi exists. 
I'm afraid there exists some misunderstanding here, as a result `has_correspond_traffic_signal` and `has_correspond_roi` at [ this part ](https://github.com/autowarefoundation/autoware.universe/blob/main/perception/autoware_traffic_light_visualization/src/traffic_light_roi_visualizer/node.cpp#L208-L225) will always be True.
None.
None.

fix(traffic_light_roi_visualizer): show unknown results correctly

---

perception/autoware_bytetrack/lib/include/byte_tracker.h

This is a fix based on clang-tidy `clang-diagnostic-implicit-const-int-float-conversion` error.
```
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_bytetrack/lib/include/byte_tracker.h:86:77: error: implicit conversion from 'long' to 'float' changes value from 9223372036854775807 to 9223372036854775808 [clang-diagnostic-implicit-const-int-float-conversion]
std::vector<int> & colsol, bool extend_cost = false, float cost_limit = LONG_MAX,
~ ^
```
- Link
None.
None.
None.

fix(autoware_bytetrack): fix clang-diagnostic-implicit-const-int-float-conversion

---

planning/autoware_external_velocity_limit_selector/include/autoware/external_velocity_limit_selector/external_velocity_limit_selector_node.hpp
planning/autoware_external_velocity_limit_selector/src/external_velocity_limit_selector_node.cpp
planning/autoware_velocity_smoother/include/autoware/velocity_smoother/node.hpp
planning/autoware_velocity_smoother/include/autoware/velocity_smoother/smoother/smoother_base.hpp
planning/autoware_velocity_smoother/src/node.cpp
planning/autoware_velocity_smoother/src/smoother/smoother_base.cpp

Currently the smoother's constraint (max_acceleration, min_acceleration, max_jerk, min_jerk) was set constantly in velocity_smoother. 
Furthermore, the external velocity limit just considered the min_acceleration, and not the max_acceleration.
This made it impossible to achieve quick acceleration when needed.
For example, when turning right or left at an intersection, if an oncoming vehicle is close to the ego vehicle, it is necessary to quickly leave the intersection.
This PR, changes the smoother's max_acceleration and max_jerk constraint whenever it is requested from the external velocity limiter.
The acceleration request is only applied when there is only accelerations requests only. This is considered inside the external_velocity_limit_selector.
- …

feat(velocity_smoother, external_velocity_limit_selector): enable stronger acceleration when requested

---

perception/autoware_ground_segmentation/src/scan_ground_filter/node.hpp

This is a fix based on clang-tidy `clang-diagnostic-inconsistent-missing-override` error.
```
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_ground_segmentation/src/scan_ground_filter/node.hpp:159:16: error: 'faster_filter' overrides a member function but is not marked 'override' [clang-diagnostic-inconsistent-missing-override]
virtual void faster_filter(
^
/home/emb4/autoware/autoware/install/autoware_pointcloud_preprocessor/include/autoware_pointcloud_preprocessor/autoware/pointcloud_preprocessor/filter.hpp:194:16: note: overridden virtual function is here
virtual void faster_filter(
^
```
- Link
None.
None.
None.

fix(autoware_ground_segmentation): fix clang-diagnostic-inconsistent-missing-override

---

evaluator/autoware_control_evaluator/src/control_evaluator_node.cpp

Fixed a bug that `goal_lateal_deviation` became `lateral_deviation` when echoing `/control/control_evaluator/metrics`.
https://github.com/autowarefoundation/autoware.universe/pull/9478/files#diff-843ce11499d139e51e783a5e2e016da0976dbd01ffc8a809c50b22db177f3dedR235
- Link
Before
After
None.
None.
None.

fix(control_evaluator): correct goal_lateal_deviation

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_module.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp

for achieving https://github.com/autowarefoundation/autoware.universe/pull/9514
some member functions do not need to be member function, so move them to free functions,
- Link
- [evaluator](https://evaluation.tier4.jp/evaluation/reports/a0aa5d2b-101d-56eb-89a6-6d4c2889e10c?project_id=prd_jt&state=failed)
None.
None.
None.

refactor(goal_planner): move unnecessary member functions

---

.cspell.json
common/autoware_trajectory/include/autoware/trajectory/point.hpp
common/autoware_trajectory/test/test_trajectory_container.cpp
control/autoware_trajectory_follower_node/config/plot_juggler_trajectory_follower.xml
perception/autoware_shape_estimation/lib/tensorrt_shape_estimator.cpp
planning/autoware_costmap_generator/src/costmap_generator.cpp
planning/autoware_freespace_planning_algorithms/test/src/test_freespace_planning_algorithms.cpp
planning/autoware_path_smoother/src/elastic_band.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection_prepare_data.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/test/test_util.cpp
planning/sampling_based_planner/autoware_sampler_common/test/test_transform.cpp
simulator/autoware_carla_interface/README.md

Now that we have moved the dictionaries into autowarefoundation and added basic common dictionaries, let's make this check required again.
This PR fixes the spelling errors found in the following daily workflow:
❌ https://github.com/autowarefoundation/autoware.universe/actions/runs/12076804289/job/33678713106#step:3:60
This PR won't change any logic, it's a documentation and renaming-refactor based.
Basic CI.
And will run it against the spell checker to see if there are any errors left:
✅ [It has passed!](https://github.com/autowarefoundation/autoware.universe/actions/runs/12089382974/job/33714587421)
The PR is very simple, even if there are lots of packages modified, the changes are very narrow scoped.
None.
None.

refactor: correct spelling

---

common/tier4_state_rviz_plugin/package.xml
common/tier4_state_rviz_plugin/src/include/velocity_steering_factors_panel.hpp
common/tier4_state_rviz_plugin/src/velocity_steering_factors_panel.cpp

This PR adds an abrupt deceleration checking feature to `VelocitySteeringFactorsPanel`.
If the minimum distance required to stop under the specified jerk and acceleration limit is greater than the distance to the stop point, abrupt deceleration is detected.
Psim
[Screencast from 2024年11月29日 19時36分39秒.webm](https://github.com/user-attachments/assets/03d68688-e5a7-40c2-b0bb-53bf924e83b1)
None.
None.
None.

feat(tier4_state_rviz_plugin): check for abrupt deceleration

---

planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/include/autoware/behavior_velocity_blind_spot_module/manager.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/include/autoware/behavior_velocity_blind_spot_module/scene.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/package.xml
planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/src/debug.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/src/decisions.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/src/manager.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/src/scene.cpp

just moved header files to include/ for add unit testing & added maintainer
- Link
build passes
None.
None.
None.

chore(blind_spot): divide headers to include/

---

planning/behavior_path_planner/autoware_behavior_path_side_shift_module/include/autoware/behavior_path_side_shift_module/scene.hpp
planning/behavior_path_planner/autoware_behavior_path_side_shift_module/include/autoware/behavior_path_side_shift_module/utils.hpp
planning/behavior_path_planner/autoware_behavior_path_side_shift_module/src/scene.cpp
planning/behavior_path_planner/autoware_behavior_path_side_shift_module/src/utils.cpp

This PR includes minor refactoring changes to improve testability and prepare the side shift module for unit testing implementation. The changes are minimal and do not affect the core functionality.
- Moved `getClosestShiftLength()` from `SideShiftModule` class to utility functions
- Added proper documentation for utility functions using Doxygen style comments
- Replaced `isAlmostZero()` utility function with direct `std::fabs()` comparisons using a threshold constant
- Added null check for empty shifted path in plan() method to prevent potential crashes
- Removed redundant null check in setOrientation() as the pointer parameter validation is handled at a higher level
run psim
None.
None.
None.

refactor(autoware_behavior_path_side_shift_module): refactor shift length retrieval and improve path orientation handling

---

common/autoware_test_utils/include/autoware_test_utils/mock_data_parser.hpp
common/autoware_test_utils/src/autoware_test_utils.cpp
common/autoware_test_utils/src/mock_data_parser.cpp
common/autoware_test_utils/test/test_mock_data_parser.cpp
planning/autoware_planning_test_manager/src/autoware_planning_test_manager.cpp
planning/autoware_route_handler/test/test_route_handler.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/test/test_lane_change_scene.cpp

It is possible the the parser function is being used incorrectly, which will return in correct results.
This PR refactor the function to return optional instead.
- Link
None.
None.
None.

refactor(test_utils): return parser as optional

---

.clang-tidy-ignore

Now perception modules are also clang-tidy warning free!!
I have tested it locally.
- Link
None.
None.
None.

ci(clang-tidy): enable clang-tidy checks in perception

---

.cspell.json

This PR adds `libtensorrt` word to `cspell.json, file.
This word used in https://github.com/autowarefoundation/autoware.universe/pull/8165.
We decided to add this word to the local directory instead of Autoware dictionary because it has limited usage and is not a common term.
None
None
None

chore(cspell): add new word `libtensorrt` to `cspell.json`

---

control/control_performance_analysis/README.md

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions#about-writing-mathematical-expressions
This will sacrifice from the maintainability a bit but make it better and more professional for rendered output.
Rendered beautifully in the documentation page too:
https://autowarefoundation.github.io/autoware.universe/pr-9552/control/control_performance_analysis/#outputs
**Related PR:**
- https://github.com/autowarefoundation/autoware.universe/pull/8949
None.
None.
None.

docs(control_performance_analysis): utilize mathjax syntax in readme

---

perception/autoware_radar_crossing_objects_noise_filter/README.md
perception/autoware_radar_object_clustering/README.md
planning/autoware_path_optimizer/docs/mpt.md

Small quality of life fixes for the documentation.
This fixes the formatting styles of these documentation files.
**Related PR:**
- https://github.com/autowarefoundation/autoware.universe/pull/8949
See the deploy-docs links below:
- https://github.com/autowarefoundation/autoware.universe/pull/9555#issuecomment-2514714372
None.
None.
None.

docs: update the list styles

---

perception/autoware_ground_segmentation/src/scan_ground_filter/grid.hpp

Fixed cppcheck `unusedFunction` warning
```
perception/autoware_ground_segmentation/src/scan_ground_filter/grid.hpp:117:0: style: The function 'getPointNum' is never used. [unusedFunction]
inline int getPointNum() const { return static_cast<int>(point_list_.size()); }
```
- Link
None.
None.
None.

fix(autoware_ground_segmentation): remove unused function

---

planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/CMakeLists.txt
planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/include/autoware/behavior_velocity_blind_spot_module/scene.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/include/autoware/behavior_velocity_blind_spot_module/util.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/src/manager.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/src/scene.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/src/util.cpp

move the member functions outside of class for adding unti tests
- Link
- https://evaluation.tier4.jp/evaluation/reports/b859777f-1178-529d-a003-78c85bda315f?project_id=prd_jt
None.
None.
None.

refactor(blind_spot): move util functions outside of class

---

perception/autoware_map_based_prediction/src/map_based_prediction_node.cpp

Fixes issue with non-related msg type.
- https://github.com/autowarefoundation/autoware.universe/issues/9549
None.
None.
None.

fix(autoware_map_based_prediction): msg namespace

---

simulator/autoware_carla_interface/setup.py

This PR fixes an issue where the `autoware_carla_interface` package failed to include the "modules" submodule in the release package. This omission caused the following runtime error in the official `universe-cuda` Docker image:
`ModuleNotFoundError: No module named 'autoware_carla_interface.modules'`
The fix involves updating `setup.py` to:
- Use `find_packages(where="src")` to automatically detect and include the "modules" subpackage.
- Correct paths in `data_files` to comply with ROS 2 packaging conventions.
This ensures that the `autoware_carla_interface` module is properly packaged and resolves the runtime error.
None
- Built a Docker image based on this commit.
- Verified the `autoware_carla_interface` module connects to CARLA Simulator without the …

fix(autoware_carla_interface): include "modules" submodule in release package and update setup.py

---

planning/autoware_obstacle_stop_planner/README.md
planning/autoware_obstacle_stop_planner/launch/obstacle_stop_planner.launch.xml
planning/autoware_obstacle_stop_planner/src/debug_marker.cpp
planning/autoware_obstacle_stop_planner/src/debug_marker.hpp

- Link
Please confirm that this module doesn't output stop reason.
```
/planning/scenario_planning/status/stop_reasons
```
After this PR, this module only outputs velocity factors.
None.
None.

fix(obstacle_stop_planner): remove stop reason

---

control/autoware_autonomous_emergency_braking/src/node.cpp
control/autoware_autonomous_emergency_braking/src/utils.cpp
control/autoware_autonomous_emergency_braking/test/test.cpp
control/autoware_collision_detector/src/node.cpp
control/autoware_control_validator/src/control_validator.cpp
control/autoware_control_validator/test/test_control_validator.cpp
control/autoware_lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker.cpp
control/autoware_lane_departure_checker/src/lane_departure_checker_node/utils.cpp
control/autoware_lane_departure_checker/test/test_calc_max_search_length_for_boundaries.cpp
control/autoware_lane_departure_checker/test/test_calc_trajectory_deviation.cpp
control/autoware_lane_departure_checker/test/test_create_vehicle_footprints.cpp
control/autoware_lane_departure_checker/test/test_resample_trajectory.cpp
control/autoware_mpc_lateral_controller/src/lowpass_filter.cpp
control/autoware_mpc_lateral_controller/src/mpc.cpp
control/autoware_mpc_lateral_controller/src/mpc_trajectory.cpp
control/autoware_mpc_lateral_controller/src/mpc_utils.cpp
control/autoware_obstacle_collision_checker/test/test_obstacle_collision_checker.cpp
control/autoware_operation_mode_transition_manager/src/data.cpp
control/autoware_operation_mode_transition_manager/src/node.cpp
control/autoware_operation_mode_transition_manager/src/state.cpp
control/autoware_pid_longitudinal_controller/src/longitudinal_controller_utils.cpp
control/autoware_pure_pursuit/src/autoware_pure_pursuit/autoware_pure_pursuit_lateral_controller.cpp
control/autoware_pure_pursuit/src/autoware_pure_pursuit_core/interpolate.cpp
control/autoware_smart_mpc_trajectory_follower/autoware_smart_mpc_trajectory_follower/src/proxima_calc.cpp
control/autoware_trajectory_follower_node/test/test_controller_node.cpp
control/autoware_vehicle_cmd_gate/src/vehicle_cmd_filter.cpp
control/autoware_vehicle_cmd_gate/test/src/test_filter_in_vehicle_cmd_gate_node.cpp
control/control_performance_analysis/src/control_performance_analysis_core.cpp
control/predicted_path_checker/src/predicted_path_checker_node/collision_checker.cpp
control/predicted_path_checker/src/predicted_path_checker_node/utils.cpp

fix(cpplint): include what you use - control

---

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/README.md
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/config/lane_change.param.yaml
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/calculation.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/parameters.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/manager.cpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/calculation.cpp

Currently when generating candidate lane change paths, we sample multiple longitudinal acceleration values, however for values below 0.0 (decelerating), it is only applied to the prepare phase, while min acceleration for lane changing phase is limited to 0.0, meaning we assume no deceleration during lane changing phase. And this behavior is not configurable.
Sometimes this assumption can result in not finding a safe candidate path near the terminal, specifically when there is a leading target lane object.
It is better to allow some deceleration during lane changing phase when approaching terminal to increase the chances of finding a safe candidate path.
Modified function `calc_lane_changing_acceleration`:
- IF sampled longitudinal acceleration is negative, AND ego is near terminal, THEN …

feat(lane_changing): improve computation of lane changing acceleration

---

control/autoware_lane_departure_checker/include/autoware/lane_departure_checker/lane_departure_checker.hpp
control/autoware_lane_departure_checker/include/autoware/lane_departure_checker/utils.hpp
control/autoware_lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker.cpp
control/autoware_lane_departure_checker/src/lane_departure_checker_node/utils.cpp

minor refactoring changes to improve testability and prepare the lane_departure_checker module for unit testing implementation. The changes are minimal and do not affect the core functionality.
- Moved `createVehiclePassingAreas()`, `getCandidateLanelets()` and `createVehiclePassingAreas()`  from `LaneDepartureChecker` class to utility functions
- Added proper documentation for utility functions using Doxygen style comments
- Add proper handling for edge cases in `createVehiclePassingAreas`
- Handle empty input vector
- Handle single footprint case
- Pre-reserve vector capacity for better performance
- Link
run psim
None.
None.
None.

refactor(lane_departure_checker): move member functions to util functions

---

perception/autoware_bytetrack/lib/include/lapjv.h

This code block is unreachable unless the header is modified by hand and recompiled.
This PR removes that.
As part of:
This weird macro heavy code snippet was confusing the static analysis tool.
It uses `printf` function yet doesn't include `<cstdio>`. Even if I include it, because of the conditional structure, the cpplint wasn't able to recognize it.
So I decided to remove it since it is not used anyways.
Basic CI.
None.
None.

feat(bytetrack): remove unreachable code block from lapjv.h

---

planning/autoware_costmap_generator/include/autoware/costmap_generator/costmap_generator.hpp
planning/autoware_costmap_generator/src/costmap_generator.cpp
planning/autoware_scenario_selector/src/node.cpp

In parking scenario, ego can sometimes get stuck when navigating close to freespace area boundary. This happens due to the inconsistency of costmap evaluation at the boundaries.
As shown below, Initially freespace generates a valid trajectory, but as ego moves the costmap evaluation fluctuates, and the endpoint of the forward trajectory becomes invalid, and freespace fails to generate a new trajectory.
https://github.com/user-attachments/assets/713a458d-c164-497b-87d5-f1dd5c5452bd
Another issue is, when ego is stuck for sometime in parking scenario, it will attempt to switch to lane driving (feature added in this [previous PR](https://github.com/autowarefoundation/autoware.universe/pull/8348)), However the logic for switching to lane driving doesn't guarantee ego pose is proper enough to …

feat(costmap_generator, scenario_selector): improve freespace planning stability

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp

improve log message and change log level.
- use throttle 5000ms to prevent too many same messages
- use info if it is not so serious or affect acutual vehicle behavior 
- Link
build
None.
None.
None.

refactor(goal_planner): improve log message and change level

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/util.cpp

https://github.com/autowarefoundation/autoware.universe/pull/9423  does not check the opposing lane. The avoidance module may cause the ego to enter the opposing lane, but at this time, the current lane departure check  logic of goal planner judges candidate paths invalid.
In this PR, it checks the opposing lane too
before
after
https://github.com/user-attachments/assets/bbc0e706-1b00-4b9c-b232-a2f7fc3fa68e
- Link
psim
2024/11/28 https://evaluation.tier4.jp/evaluation/reports/317acd96-acdc-5002-97d1-d1c5fa3067d8/?project_id=prd_jt
https://evaluation.tier4.jp/evaluation/reports/ee27e182-2a8b-5ae5-8159-854a2bad205a?project_id=prd_jt&state=failed
None.
None.
None.

feat(goal_planner): check opposite lane for lane departure_check

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_module.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp

in https://github.com/autowarefoundation/autoware.universe/pull/9522, time duration threshould is used for velocity check mistakenly.
- Link
psim with [scenario](https://evaluation.tier4.jp/evaluation/reports/53ab00d7-2644-5f98-9c0c-809b1b9b9f0e/tests/8bb4cf42-67d4-5d44-9137-e8d09b5793e5/9a60cdd1-dc7b-54c6-b80b-913c688b8916/46048113-55a7-5efe-a71d-92886a1b6761?project_id=prd_jt&state=failed#)
2024/12/06 https://evaluation.tier4.jp/evaluation/reports/ede3fa66-17c1-590b-999d-3f21a2284947/?project_id=prd_jt
None.
None.
None.

fix(goal_planner): fix isStopped judgement

---

planning/behavior_velocity_planner/autoware_behavior_velocity_stop_line_module/src/scene.cpp

Removed cppcheck warning `unusedFunction` for `getCenterOfStopLine`
```
planning/behavior_velocity_planner/autoware_behavior_velocity_stop_line_module/src/scene.cpp:29:0: style: The function 'getCenterOfStopLine' is never used. [unusedFunction]
geometry_msgs::msg::Point getCenterOfStopLine(const lanelet::ConstLineString3d & stop_line)
^
```
- Link
None.
None.
None.

fix(autoware_behavior_velocity_stop_line_module): remove unused function

---

perception/autoware_image_projection_based_fusion/src/roi_detected_object_fusion/node.cpp

1. eliminate misuse of `std::numeric_limits<double>::min()`
2. fix roi range up to the image edges
- Link [TIER IV INTERNAL](https://star4.slack.com/archives/CTEJP8L4T/p1732608837719329)
Objects at the edges are fused without issue.
It will be merged after https://github.com/autowarefoundation/autoware.universe/pull/9505 is merged and the build issue is resolved.
None.
None.

fix(autoware_image_projection_based_fusion): detected object roi box projection fix

---

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/utils.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/path_safety_checker/objects_filtering.hpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_safety_checker/objects_filtering.cpp

If there’s object that crosses predicted target lanes but it is not in target lane or target preceding lane, then the object will be treated as other lane object and will be ignored.
This PR aims to fix this.
The following video shows the use case.
If the object is not in cyan lane (current) or blue (target preceding), then it will be considered as others object (purple cube).
https://github.com/user-attachments/assets/40cbb71d-a3eb-48a0-9530-113d8e255a3e
Object is now considered as target lane leading object (cyan cube)
https://github.com/user-attachments/assets/f781f984-6249-4c6f-8baa-56300dba6993
- Link
1. PSIM
2. Internal evaluator: [TIER IV Internal link](https://evaluation.tier4.jp/evaluation/reports/2e106800-248c-5576-8f53-37c0f5a710b0?project_id=prd_jt)
None. …

fix(lane_change): check obj predicted path when filtering

---

system/diagnostic_graph_utils/launch/logging.launch.xml
system/diagnostic_graph_utils/package.xml
system/diagnostic_graph_utils/src/node/logging.cpp
system/diagnostic_graph_utils/src/node/logging.hpp

The diag_graph_utils's output to the terminal is a bit too frequent to fill the whole terminal screen.
Instead of the output to the terminal, this PR makes the diag_graph_utils publish the string message of the error diag graph so that the Rviz can visualize it as follows.
psim worked well
None.
None.
None.

feat(diagnostic_graph_utils): publish error graph instead of the terminal log

---

.github/workflows/build-and-test-daily.yaml
.github/workflows/build-and-test.yaml

It seems I forgot to add ccache to the daily, It uses the cache now. (Doesn't update it, since it runs daily, no need).
This PR makes:
- `build-and-test.yaml`
- `build-and-test-daily.yaml`
workflows use the self hosted machines.
For now, they will use the `ovh-runner-01`
Specs:
```yaml
OS: Ubuntu 22.04 jammy
Kernel: x86_64 Linux 5.15.0-126-generic
Disk: 5.0G / 429G (2%)
CPU: Intel Xeon D-2141I @ 16x 3GHz [28.0°C]
RAM: 3978MiB / 31754MiB
```
They can also use `leo-copper` since it covers the same labels too.
- https://github.com/autowarefoundation/autoware.universe/issues/9088
- [build-and-test-daily (humble)](https://github.com/autowarefoundation/autoware.universe/actions/runs/12255199589/job/34187745128) - leo-copper
- [build-and-test-daily (humble, …

ci(build-and-test): use self hosted X64 and add ccache to -daily

---

planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/data_manager.hpp

I don't know why this header include, but I had a compiling error on it.
The modified code is same as other usage of the `rclcpp/clock.hpp` file in the repo elsewhere, like [#include <rclcpp/clock.hpp>](https://github.com/autowarefoundation/autoware.universe/blob/c89f8636cd76d4e0092375133eb69ae903aef3a2/planning/behavior_velocity_virtual_traffic_light_module/src/scene.hpp#L22)
Compile the code
[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contrib …

build(behavior_path_planner_common): fix #include <rclcpp/clock.hpp>

---

perception/autoware_image_projection_based_fusion/src/fusion_node.cpp

Currently, nodes in the image_projection_based_fusion package are restricted to subscribe up to 8 roi messages maximum.
Remove this magic number because it does not have any concrete necessity.
Adding launcher to subscribe more than 8 camera topics.
None.
None.
None.

feat: remove max rois limit in the image projection based fusion

---

perception/autoware_image_projection_based_fusion/config/pointpainting.param.yaml
perception/autoware_image_projection_based_fusion/docs/pointpainting-fusion.md
perception/autoware_image_projection_based_fusion/schema/pointpainting.schema.json
perception/autoware_image_projection_based_fusion/src/pointpainting_fusion/node.cpp
perception/autoware_lidar_centerpoint/README.md
perception/autoware_lidar_centerpoint/config/centerpoint.param.yaml
perception/autoware_lidar_centerpoint/config/centerpoint_sigma.param.yaml
perception/autoware_lidar_centerpoint/config/centerpoint_tiny.param.yaml
perception/autoware_lidar_centerpoint/include/autoware/lidar_centerpoint/postprocess/non_maximum_suppression.hpp
perception/autoware_lidar_centerpoint/lib/postprocess/non_maximum_suppression.cpp
perception/autoware_lidar_centerpoint/schema/centerpoint.schemal.json
perception/autoware_lidar_centerpoint/src/node.cpp
perception/autoware_lidar_centerpoint/test/test_nms.cpp

1. fix non-maximum suppression target decision logic
Before: If both of the object class are in the target label, caluclate IoU. If not, check distance and calculate IoU if the distance is less than a threshold.
After: If the label pair is not the same and one of them is pedestrian, do not suppress. Then, check distance and calcuclate IoU only if the distance is within a threshold.
2. optimize non-maximum suppression search range
Keep the squared value of the distance threshold.
3. remove NMS type
Since there is no other NMS option, remove the logic and parameter to select NMS type.
NMS PR: https://github.com/autowarefoundation/autoware.universe/pull/1935
Issue: 
- pedestrian near a car is not detected https://github.com/autowarefoundation/autoware.universe/issues/7563 
Performance test …

fix(lidar_centerpoint): non-maximum suppression target decision logic

---

perception/autoware_lidar_transfusion/config/transfusion.param.yaml
perception/autoware_lidar_transfusion/include/autoware/lidar_transfusion/postprocess/non_maximum_suppression.hpp
perception/autoware_lidar_transfusion/lib/postprocess/non_maximum_suppression.cpp
perception/autoware_lidar_transfusion/schema/transfusion.schema.dummy.json
perception/autoware_lidar_transfusion/src/lidar_transfusion_node.cpp
perception/autoware_lidar_transfusion/test/test_nms.cpp

Implement same fix of PR https://github.com/autowarefoundation/autoware.universe/pull/9595
1.  fix non-maximum suppression target decision logic
Before: If both of the object class are in the target label, caluclate IoU. If not, check distance and calculate IoU if the distance is less than a threshold.
After: If the label pair is not the same and one of them is pedestrian, do not suppress. Then, check distance and calcuclate IoU only if the distance is within a threshold.
2.  optimize non-maximum suppression search range
Keep the squared value of the distance threshold.
3.  remove NMS type
Since there is no other NMS option, remove the logic and parameter to select NMS type.
- Link
None.
None.
None.

fix(autoware_lidar_transfusion): non-maximum suppression target decision logic

---

planning/autoware_obstacle_cruise_planner/include/autoware/obstacle_cruise_planner/common_structs.hpp
planning/autoware_obstacle_cruise_planner/include/autoware/obstacle_cruise_planner/node.hpp
planning/autoware_obstacle_cruise_planner/package.xml
planning/autoware_obstacle_cruise_planner/src/node.cpp
planning/autoware_obstacle_cruise_planner/src/pid_based_planner/pid_based_planner.cpp
planning/autoware_obstacle_cruise_planner/src/utils.cpp

This PR consists of the following changes.
1. To distinguish the cruise and the yield by rviz, extra stings are added to the cruise virtual walls
2. To recognize the yield behavior by rviz, objects of interest marker is added to the corresponding stopped object
3. Virtual wall topic names are aligned
4. WARN messages for the case of failing time interpolation of the objects are suppressed by published as DEBUG
launch PR: https://github.com/autowarefoundation/autoware_launch/pull/1264
- Link
psim
None.
None.
None.

refactor(obstacle_cruise_planner)!: refactor rviz and terminal info

---

system/duplicated_node_checker/src/duplicated_node_checker_core.cpp

Currently, when there are duplicated nodes, we cannot see the node name unless we run `rqt_runtime_monitor` or something, which makes the debuggability quite low.
The duplicated_node_checker node will show the following message with the duplicated node name on the terminal.
```
[duplicated_node_checker_node-3] [WARN 1733839043.581189550] [system.duplicated_node_checker]: /perception/object_recognition/prediction/map_based_prediction node is duplicated. (produceDiagnostics():70)
```
It worked on the planning simulator.
None.
None.
None.

feat(duplicated_node_checker): show the node name on the terminal

---

common/autoware_vehicle_info_utils/include/autoware_vehicle_info_utils/vehicle_info.hpp
common/autoware_vehicle_info_utils/src/vehicle_info.cpp
planning/autoware_static_centerline_generator/launch/static_centerline_generator.launch.xml
planning/autoware_static_centerline_generator/package.xml
planning/autoware_static_centerline_generator/src/static_centerline_generator_node.cpp

Several bug fixes including
- fix package dependency
- use discontinuous curvature calculation instead of spline interpolation which is more robust to the trajectory's interval length
- show steer angle instead of curvature which is easy to understand
unit test passed.
None.
None.
None.

fix(static_centerline_generator): several bug fixes

---

launch/tier4_perception_launch/launch/object_recognition/tracking/tracking.launch.xml
launch/tier4_perception_launch/launch/perception.launch.xml

The object detection channels in the `tracking.launch.xml` file have been updated to use the lidar detection model type.
Implementing changes by PR https://github.com/autowarefoundation/autoware.universe/pull/9003
This PR do not contain logic change.
- Link
set parameters as following
* `use_multi_channel_tracker_merger` true
* `lidar_detection_model` centerpoint/centerpoint_tiny
None.
None.
None.

fix(tier4_perception_launch): update multi-channel subscribing channel name to lidar_detection_model_type

---

common/autoware_test_utils/include/autoware_test_utils/autoware_test_utils.hpp
common/autoware_test_utils/src/autoware_test_utils.cpp
planning/autoware_planning_test_manager/include/autoware_planning_test_manager/autoware_planning_test_manager_utils.hpp

- Add optional parameters to `makeMapBinMsg` function to allow specifying custom package name and map filename
- Update documentation for `makeMapBinMsg` to reflect new parameters
- Add optional parameters to `createPoseFromLaneID` and `makeBehaviorRouteFromLaneId` to support custom map loading
- Set default values to maintain backward compatibility (`package_name=""`, `map_filename="lanelet2_map.osm"`)
This change is necessary to use a different map than the default one when calling the function `makeBehaviorRouteFromLaneId` to generate a route.
- Link
None.
None.
None.

refactor(autoware_test_utils): enhance makeMapBinMsg to accept package name and map filename parameters

---

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/utils.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp

When the lanes are short, the preceding lane might overlap with the current lanes, as shown in the video below.
This could potentially affect the safety check results. To avoid this, we should remove the overlapping lane.
Preceding lanes (Dark blue lanes) overlap current lanes. 
https://github.com/user-attachments/assets/d9dd7c51-4609-4be3-8d6c-c561d1582aae
Preceding lanes no longer overlaps current lanes.
https://github.com/user-attachments/assets/24a0bb3d-e4b8-4408-914d-feec7ffbb0c9
- Link
None.
None.
None.

fix(lane_change): remove overlapping preceding lanes

---

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/base_class.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/interface.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/manager.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/scene.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/structs/data.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/structs/debug.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/structs/parameters.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/structs/path.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/calculation.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/markers.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/utils.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/markers.cpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/test/test_lane_change_scene.cpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/test/test_lane_change_utils.cpp

Move `utils/**_structs.hpp` to `structs\**.hpp`
Move `utils/parameters.hpp` to `structs\parameters.hpp`
Move `utils/base_class.hpp` to `base_class.hpp`
- None
Build Autoware.
None.
None.
None.

refactor(lane_change): separate structs to different folders

---

launch/tier4_simulator_launch/launch/simulator.launch.xml

Related to PR https://github.com/autowarefoundation/autoware.universe/pull/9624, fix the simulator launch.
Add missing configuration to the tracking.launch.
- Link
None.
None.
None.

fix(tier4_simulator_launch): add missing argument of tracking launch to simulator launch

---

visualization/tier4_state_rviz_plugin/src/custom_container.cpp
visualization/tier4_state_rviz_plugin/src/custom_icon_label.cpp
visualization/tier4_state_rviz_plugin/src/custom_segmented_button.cpp
visualization/tier4_state_rviz_plugin/src/custom_segmented_button_item.cpp

This is a fix based on clang-tidy `bugprone-integer-division` error.
```
/home/emb4/autoware/autoware/src/universe/autoware.universe/visualization/tier4_state_rviz_plugin/src/custom_container.cpp:54:31: error: result of integer division used in a floating point context; possible loss of precision [bugprone-integer-division,-warnings-as-errors]
path.addRoundedRect(rect(), height() / 2, height() / 2);  // Use height for rounded corners
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/visualization/tier4_state_rviz_plugin/src/custom_container.cpp:54:45: error: result of integer division used in a floating point context; possible loss of precision [bugprone-integer-division,-warnings-as-errors]
path.addRoundedRect(rect(), height() / 2, height() / 2);  // Use height for rounded …
```

fix(tier4_state_rviz_plugin): fix bugprone-integer-division

---

control/autoware_pid_longitudinal_controller/src/smooth_stop.cpp

```
/home/emb4/autoware/autoware/src/universe/autoware.universe/control/autoware_pid_longitudinal_controller/src/smooth_stop.cpp:143:79: error: repeated branch in conditional chain [bugprone-branch-clone,-warnings-as-errors]
if (time_to_stop && *time_to_stop > m_params.weak_stop_time + delay_time) {
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/control/autoware_pid_longitudinal_controller/src/smooth_stop.cpp:145:6: note: end of the original
} else if (!time_to_stop && is_fast_vel) {
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/control/autoware_pid_longitudinal_controller/src/smooth_stop.cpp:145:46: note: clone 1 starts here
} else if (!time_to_stop && is_fast_vel) {
^
```
- …

fix(autoware_pid_longitudinal_controller): fix bugprone-branch-clone

---

.github/workflows/build-and-test.yaml

Since this workflow circularly uses and updates the build cache used by all the other sub-jobs, it should run sequentially to avoid breaking the buffer integrity.
And since it only runs for already merged commits, it doesn't block any other task.
And removing the workflow_dispatch execution, since that also makes the buffer unusable due to [**Restrictions for accessing a cache**](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache). It is advised to use build-and-test-daily for such testing, since it does pretty much the same thing, but without updating the cache.
Since it is relatively simple, https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/ …

ci(build-and-test): set concurrency to sequential and remove workflow_dispatch

---

planning/autoware_freespace_planning_algorithms/CMakeLists.txt

This test is flaky due to varying times it can take.
It randomly fails due to timeout. The default timeout for a single gtest is 60 seconds.
On my machine, this test took `30.61` seconds:
`1/6 Test #1: autoware_freespace_planning_algorithms-test ...   Passed   30.61 sec`
([Ryzen 5900X](https://www.amd.com/en/products/processors/desktops/ryzen/5000-series/amd-ryzen-9-5900x.html))
But [on the runner, it can take `49.78` seconds.](https://github.com/autowarefoundation/autoware.universe/actions/runs/12294031204/job/34307969122#step:17:17337):
`1/6 Test #1: autoware_freespace_planning_algorithms-test ...   Passed   49.78 sec`
([Xeon D-2141I](https://www.intel.com/content/www/us/en/products/sku/136430/intel-xeon-d2141i-processor-11m-cache-2-20-ghz/specifications.html))
Or it can fail due to …

build(autoware_freespace_planning_algorithms): increase test timeout to 2 mins

---

planning/behavior_path_planner/autoware_behavior_path_start_planner_module/CMakeLists.txt
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/include/autoware/behavior_path_start_planner_module/geometric_pull_out.hpp
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/pull_out_planner_base.cpp
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/test/test_geometric_pull_out.cpp

1. Added test environment for `autoware_behavior_path_start_planner_module`
2. Added `TestGeometricPullOut` as a friend class to `GeometricPullOut` class
- Enabled access to private members from the test class
3. Added null check for dynamic objects in `PullOutPlannerBase::isPullOutPathCollided` method
- Returns `false` when `dynamic_objects` is null
- Prevents crashes in situations where dynamic objects do not exist
- Link
run colcon test with following command
```
colcon test --event-handlers console_cohesion+ --packages-select autoware_behavior_path_start_planner_module
```
get the success result
```
1: [----------] Global test environment set-up.
1: [----------] 1 test from TestGeometricPullOut
1: [ RUN      ] TestGeometricPullOut.GenerateValidGeometricPullOutPath
1: …
```

test(autoware_behavior_path_start_planner_module): add unit tests for geometric shift pull out planner

---

localization/autoware_stop_filter/src/stop_filter.cpp

This is a fix based on clang-tidy `bugprone-reserved-identifier` error.
```
/home/emb4/autoware/autoware/src/universe/autoware.universe/localization/autoware_stop_filter/src/stop_filter.cpp:25:26: error: declaration uses identifier '_1', which is reserved in the global namespace; cannot be fixed automatically [bugprone-reserved-identifier,-warnings-as-errors]
using std::placeholders::_1;
^
```
- Link
None.
None.
None.

fix(autoware_stop_filter): fix bugprone-reserved-identifier

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/CMakeLists.txt
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_module.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/thread_data.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/geometric_pull_over.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/shift_pull_over.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/thread_data.cpp

Currently `thread_safe_data_` member variable is accessed from many member functions. This structure is not healthy because there are other possible not thread-safe member variables, and numerous number of call to lock() is very insufficient.
After this PR, there are 3 agents
- goal_planner_module
- LaneParkingPlannerThread
- FreespaceParkingThread
Lock the `lane_parking_mutex_`, and
- prepare the `LaneParkingRequest` member
- copy the `LaneParkingResponse` to local scope
Lock the `freespace_parking_mutex_`, and
- prepare the `FreespaceParkingRequest` member
- copy the `FreespaceParkingResponse` to local scope
Lock the `lane_parking_mutex_` which is shared with goal_planner_module via reference, and
- copy `LaneParkingResponse` to local scope
After computation,
Lock the …

feat(goal_planner): divide Planners to isolated threads

---

perception/autoware_lidar_centerpoint/lib/preprocess/preprocess_kernel.cu

Alternative solution of PR https://github.com/autowarefoundation/autoware.universe/pull/9583
1. exchange x and y to process in a row-major order
2. flip x axis direction to process front to back
- Link
The following visualization is to show filled voxel distribution. Configurations are as follwing.
- input high-density lidar point cloud
-  score_threshold: 0.01
-  max_voxel_size: 40000
-  point_cloud_range: [-121.6, -76.8, -3.0, 121.6, 76.8, 5.0]
Then lower score object will be shown (due to the lower score_threshold), indirectly visualize where the voxel is filled.
None.
None.
None.

feat(autoware_lidar_centerpoint): process front voxels first

---

perception/autoware_multi_object_tracker/config/multi_object_tracker_node.param.yaml
perception/autoware_multi_object_tracker/schema/multi_object_tracker_node.schema.json
perception/autoware_multi_object_tracker/src/multi_object_tracker_node.cpp
perception/autoware_multi_object_tracker/src/processor/processor.cpp
perception/autoware_multi_object_tracker/src/processor/processor.hpp

Extracted `autoware_multi_object_tracker` parameters from source code, refactored parameters declaration and enabled setting `confident_count_threshold` for each classification label separately. 
* Extracted tracker-specific parameters: `tracker_lifetime`, `min_known_object_removal_iou`, `min_unknown_object_removal_iou`, `distance_threshold`, and `confident_count_threshold` to the `multi_object_tracker_node.param.yaml` configuration file.
* Introduced `TrackerProcessorConfig` struct to encapsulate tracker-related parameters and refactored the `TrackerProcessor` class to use this struct for initialization.
* Updated the `TrackerProcessor` methods to use the new configuration struct, including `createNewTracker`, `removeOldTracker`, `removeOverlappedTracker`, and `isConfidentTracker`. …

refactor(autoware_multi_object_tracker): add configurable tracker parameters

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_module.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/pull_over_planner/freespace_pull_over.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/freespace_pull_over.cpp

depends https://github.com/autowarefoundation/autoware.universe/pull/9514
- https://evaluation.tier4.jp/evaluation/reports/c158543d-cfbc-589a-9b97-234fd80ed4f4?project_id=prd_jt
- https://evaluation.tier4.jp/evaluation/reports/372080f8-e1f2-5dca-a6af-0b2a90e1e2e0?project_id=prd_jt
None.
None.
None.

perf(goal_planner): remove unnecessary call to setMap on freespace planning

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_module.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp

divide pull over path candidates sort functionality to a utility function.
- https://tier4.atlassian.net/browse/RT1-8337
- https://evaluation.tier4.jp/evaluation/reports/c158543d-cfbc-589a-9b97-234fd80ed4f4?project_id=prd_jt
- https://evaluation.tier4.jp/evaluation/reports/372080f8-e1f2-5dca-a6af-0b2a90e1e2e0?project_id=prd_jt
None.
None.
None.

refactor(goal_planner): divide sort function

---

perception/autoware_multi_object_tracker/lib/tracker/model/bicycle_tracker.cpp
perception/autoware_multi_object_tracker/lib/tracker/motion_model/bicycle_motion_model.cpp
perception/autoware_multi_object_tracker/src/processor/input_manager.cpp

This is a fix based on clang-tidy `bugprone-branch-clone` and `bugprone-reserved-identifier` error.
```
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_multi_object_tracker/lib/tracker/model/bicycle_tracker.cpp:211:43: error: repeated branch in conditional chain [bugprone-branch-clone,-warnings-as-errors]
object.shape.dimensions.z > size_max) {
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_multi_object_tracker/lib/tracker/model/bicycle_tracker.cpp:213:4: note: end of the original
} else if (
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_multi_object_tracker/lib/tracker/model/bicycle_tracker.cpp:215:43: note: clone 1 starts here
object.shape.dimensions.z < size_min) {
^ …
```

fix(autoware_multi_object_tracker): fix bugprone-errors

---

planning/autoware_costmap_generator/src/costmap_generator.cpp

Suppress this error.
```
[component_container_mt-35] [ERROR] [1734317356.286407477] [planning.scenario_planning.parking.costmap_generator]: Could not find a connection between 'map' and 'base_link' because they are not part of the same tree.Tf has two or more unconnected trees.
```
- Link
None.
None.
None.

chore(autoware_costmap_generator): suppress Could not find a connection between 'map' and 'base_link'

---

perception/autoware_radar_tracks_msgs_converter/src/radar_tracks_msgs_converter_node.cpp

This is a fix based on clang-tidy `bugprone-reserved-identifier` error.
```
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_radar_tracks_msgs_converter/src/radar_tracks_msgs_converter_node.cpp:37:26: error: declaration uses identifier '_1', which is reserved in the global namespace; cannot be fixed automatically [bugprone-reserved-identifier,-warnings-as-errors]
using std::placeholders::_1;
^
```
- Link
None.
None.
None.

fix(autoware_radar_tracks_msgs_converter): fix bugprone-reserved-identifier

---

control/autoware_pid_longitudinal_controller/include/autoware/pid_longitudinal_controller/debug_values.hpp
control/autoware_pid_longitudinal_controller/include/autoware/pid_longitudinal_controller/pid_longitudinal_controller.hpp
control/autoware_pid_longitudinal_controller/src/pid_longitudinal_controller.cpp

This PR updates the slope compensation feature _trajectory_adaptive_, which use localization pitch when the vehicle velocity is slow.
1. Adopt rate limit filter to prevent the large jerk when switching the pitch source while running
2. Updates enumerate names of DebugValues to comply with the _trajectory_adaptive_
launch PR: https://github.com/autowarefoundation/autoware_launch/pull/1276
None.
None.
None.

feat(pid_longitudinal_controller): update trajectory_adaptive; add debug_values, adopt rate limit fillter

---

common/autoware_pyplot/CMakeLists.txt
common/autoware_test_utils/include/autoware_test_utils/visualization.hpp
common/autoware_test_utils/package.xml

- add autoware_test_utils/visualization.hpp for plotting 
Examples:
see the images in this PR: https://github.com/autowarefoundation/autoware.universe/pull/9597
- Link
None.
None.
None.

feat(autoware_test_utils): add visualization

---

perception/autoware_shape_estimation/lib/corrector/utils.cpp

No branches were exactly the same; similar branches existed.
In this case, the process would be difficult to understand if summarized, so it was suppressed with a comment.
```
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_shape_estimation/lib/corrector/utils.cpp:166:3: error: repeated branch in conditional chain [bugprone-branch-clone,-warnings-as-errors]
{
^
```
- Link
None.
None.
None.

fix(autoware_shape_estimation): fix bugprone-branch-clone

---

perception/autoware_tracking_object_merger/src/utils/utils.cpp

```
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_tracking_object_merger/src/utils/utils.cpp:101:79: error: repeated branch in conditional chain [bugprone-branch-clone,-warnings-as-errors]
} else if (shape1.type == autoware_perception_msgs::msg::Shape::CYLINDER) {
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_tracking_object_merger/src/utils/utils.cpp:103:6: note: end of the original
} else if (shape1.type == autoware_perception_msgs::msg::Shape::POLYGON) {
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_tracking_object_merger/src/utils/utils.cpp:103:78: note: clone 1 starts here
} else if (shape1.type == …
```

fix(autoware_tracking_object_merger): fix bugprone-branch-clone

---

perception/autoware_traffic_light_visualization/src/traffic_light_map_visualizer/node.cpp

Since it was originally suppressed by NOLINT, this error is also suppressed by NOLINT.
```
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_traffic_light_visualization/src/traffic_light_map_visualizer/node.cpp:172:88: error: repeated branch in conditional chain [bugprone-branch-clone,-warnings-as-errors]
elem.color == autoware_perception_msgs::msg::TrafficLightElement::RED) {
^
```
- Link
None.
None.
None.

fix(autoware_traffic_light_visualization): fix bugprone-branch-clone

---

planning/autoware_costmap_generator/src/utils/objects_to_costmap.cpp

```
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/autoware_costmap_generator/src/utils/objects_to_costmap.cpp:203:89: error: repeated branch in conditional chain [bugprone-branch-clone,-warnings-as-errors]
} else if (object.shape.type == autoware_perception_msgs::msg::Shape::BOUNDING_BOX) {
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/autoware_costmap_generator/src/utils/objects_to_costmap.cpp:205:6: note: end of the original
} else if (object.shape.type == autoware_perception_msgs::msg::Shape::CYLINDER) {
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/autoware_costmap_generator/src/utils/objects_to_costmap.cpp:205:85: note: clone 1 starts here
} else …
```

fix(autoware_costmap_generator): fix bugprone-branch-clone

---

perception/autoware_detected_object_validation/config/obstacle_pointcloud_based_validator.param.yaml
perception/autoware_detected_object_validation/schema/obstacle_pointcloud_based_validator.schema.json
perception/autoware_detected_object_validation/src/obstacle_pointcloud/obstacle_pointcloud_validator.cpp
perception/autoware_detected_object_validation/src/obstacle_pointcloud/obstacle_pointcloud_validator.hpp

A set of detected objects is validated by the obstacle pointcloud, which is the result of a rule-based detection `ground segmentation`.
In far ranges, however, it is difficult to separate non-ground obstacle since reflection of ground in far range is very week or absent due to the shallow angle.
A parameter `validate_max_distance_m` is added to not validate object far than this parameter.
Launcher PR https://github.com/autowarefoundation/autoware_launch/pull/1277
[TIER IV INTERNAL](https://evaluation.tier4.jp/evaluation/reports/23555364-8459-5d70-a6ae-66a328a44a02?project_id=prd_jt)
* ground segmentation setting : change parameters to make obstacle pointcloud less in far distance (for test purpose)
- global_slope_max_angle_deg: 30.0
- local_slope_max_angle_deg: 30.0
- …

feat(autoware_detected_object_validation): set validate distance in the obstacle pointcloud based validator 

---

perception/autoware_probabilistic_occupancy_grid_map/lib/costmap_2d/occupancy_grid_map_fixed.cpp
perception/autoware_probabilistic_occupancy_grid_map/lib/costmap_2d/occupancy_grid_map_projective.cpp

```
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_probabilistic_occupancy_grid_map/lib/costmap_2d/occupancy_grid_map_fixed.cpp:147:64: error: repeated branch in conditional chain [bugprone-branch-clone,-warnings-as-errors]
if (raw_pointcloud_angle_bins.at(angle_bin_index).empty()) {
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_probabilistic_occupancy_grid_map/lib/costmap_2d/occupancy_grid_map_fixed.cpp:149:6: note: end of the original
} else if (range > raw_pointcloud_angle_bins.at(angle_bin_index).back().range) {
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_probabilistic_occupancy_grid_map/lib/costmap_2d/occupancy_grid …
```

fix(autoware_probabilistic_occupancy_grid_map): fix bugprone-branch-clone

---

sensing/autoware_pointcloud_preprocessor/src/downsample_filter/pickup_based_voxel_grid_downsample_filter_node.cpp

Previously pickup-based downsampler, which is used in the default downsampler for the perception input, only copies x,y,z attribute and do not copy other one like intensity. This leads to cause some perception issue.
This PR fix this problem by copying all attributes.
Just build and tested with sample bag file(WIP).
None.
None.
None.

fix: enable to copy all information in pickup based pointcloud downsampler

---

control/autoware_pid_longitudinal_controller/config/autoware_pid_longitudinal_controller.param.yaml
control/autoware_pid_longitudinal_controller/include/autoware/pid_longitudinal_controller/pid_longitudinal_controller.hpp
control/autoware_pid_longitudinal_controller/media/LongitudinalControllerStateTransition.drawio.svg
control/autoware_pid_longitudinal_controller/schema/autoware_pid_longitudinal_controller.schema.json
control/autoware_pid_longitudinal_controller/src/pid_longitudinal_controller.cpp
control/autoware_trajectory_follower_node/test/test_controller_node.cpp

Currently, several nodes have a translational/rotational deviation checker.
Among them, the control_validator should be responsible for it, so I removed it from the pid_longiudinal_controller.
psim worked.
None.
None.
None.

feat(pid_longitudinal_controller): remove trans/rot deviation validation since the control_validator has the same feature

---

control/autoware_pid_longitudinal_controller/include/autoware/pid_longitudinal_controller/pid_longitudinal_controller.hpp
control/autoware_pid_longitudinal_controller/src/pid_longitudinal_controller.cpp

This PR added a virtual wall when the pid_longitudinal_controller is in an emergency as follows.
psim worked.
None.
None.
None.

feat(pid_longitudinal_controller): add virtual wall for dry steering and emergency

---

control/autoware_mpc_lateral_controller/README.md
control/autoware_mpc_lateral_controller/include/autoware/mpc_lateral_controller/mpc.hpp
control/autoware_mpc_lateral_controller/param/lateral_controller_defaults.param.yaml
control/autoware_mpc_lateral_controller/src/mpc.cpp
control/autoware_mpc_lateral_controller/src/mpc_lateral_controller.cpp
control/autoware_mpc_lateral_controller/test/test_mpc.cpp

Same PR of the following PR for mpc_lateral_controller
https://github.com/autowarefoundation/autoware.universe/pull/9675
psim worked.
None.
None.
None.

feat(mpc_lateral_controller): remove trans/rot deviation validation since the control_validator has the same feature

---

common/autoware_motion_utils/include/autoware/motion_utils/factor/planning_factor_interface.hpp
common/autoware_motion_utils/src/factor/planing_factor_interface.cpp

Add planning factor interface to make it easier for developper to output `PlaninningFactor.msg`.
- https://github.com/tier4/tier4_autoware_msgs/pull/155
None.
None.
None.

feat(motion_utils): add planning factor interface

---

control/autoware_mpc_lateral_controller/include/autoware/mpc_lateral_controller/mpc.hpp
control/autoware_mpc_lateral_controller/src/mpc_lateral_controller.cpp

In certain situations steering command can become unstable when Ego is stopped.
`mpc_lateral_controller` has logic to detect when Ego is in stopped state and stabilize steering command.
The logic for stopped state check considers:
- Ego velocity is below threshold
- Target velocity is below threshold
- Steering is converged
However the target velocity check only considers the velocity at the trajectory point closest to the Ego base. In some cases stop can be executed before stop point, and velocity controller will not start if distance from Ego to stop point is less than 0.5. So the velocity at the nearest trajectory point to base can be greater than zero even when Ego is stopped.
To fix that, this PR modifies the target velocity check to consider the velocities of trajectory points …

fix(mpc_lateral_controller): prevent unstable steering command while stopped

---

perception/autoware_tensorrt_common/src/tensorrt_common.cpp

This is a fix based on clang-tidy `bugprone-integer-division` error.
```
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_tensorrt_common/src/tensorrt_common.cpp:314:43: error: result of integer division used in a floating point context; possible loss of precision [bugprone-integer-division,-warnings-as-errors]
float gflops = (2 * num_weights) * (dim_in.d[3] / stride * dim_in.d[2] / stride / 1e9);
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_tensorrt_common/src/tensorrt_common.cpp:339:22: error: result of integer division used in a floating point context; possible loss of precision [bugprone-integer-division,-warnings-as-errors]
float gflops = dim_in.d[1] * dim_window.d[0] / dim_stride.d[0] * dim_window.d[1] /
^
``` …

fix(autoware_tensorrt_common): fix bugprone-integer-division

---

planning/autoware_freespace_planning_algorithms/src/abstract_algorithm.cpp
planning/autoware_freespace_planning_algorithms/src/astar_search.cpp

This is a fix based on clang-tidy `bugprone-signed-char-misuse` and `bugprone-integer-division` error.
```
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/autoware_freespace_planning_algorithms/src/abstract_algorithm.cpp:118:22: error: 'signed char' to 'const int' conversion; consider casting to 'unsigned char' first. [bugprone-signed-char-misuse,-warnings-as-errors]
const int cost = costmap_.data[i];
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/autoware_freespace_planning_algorithms/src/astar_search.cpp:391:11: error: result of integer division used in a floating point context; possible loss of precision [bugprone-integer-division,-warnings-as-errors]
(abs(steering_index) / planner_common_param_.turning_steps);
^
```
- Link …

fix(autoware_freespace_planning_algorithms): fix bugprone-errors

---

planning/autoware_path_smoother/src/elastic_band.cpp

```
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/autoware_path_smoother/src/elastic_band.cpp:56:44: error: repeated branch in conditional chain [bugprone-branch-clone,-warnings-as-errors]
if (r == 0 || r == num_points - 1) {
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/autoware_path_smoother/src/elastic_band.cpp:58:10: note: end of the original
} else if (c == 0 || c == num_points - 1) {
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/autoware_path_smoother/src/elastic_band.cpp:58:51: note: clone 1 starts here
} else if (c == 0 || c == num_points - 1) {
^
```
- Link
None.
None.
None.

fix(autoware_path_smoother): fix bugprone-branch-clone

---

planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/drivable_area_expansion/static_drivable_area.cpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/occupancy_grid_based_collision_detector/occupancy_grid_based_collision_detector.cpp

This is a fix based on clang-tidy `bugprone-branch-clone` and `bugprone-signed-char-misuse` error.
```
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/drivable_area_expansion/static_drivable_area.cpp:1130:21: error: repeated branch in conditional chain [bugprone-branch-clone,-warnings-as-errors]
if (!polygon) {
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/drivable_area_expansion/static_drivable_area.cpp:1132:8: note: end of the original
} else if (polygon.value().id() != current_polygon.value().id()) {
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/behavior_path_planner/autoware_beh …
```

fix(autoware_behavior_path_planner_common): fix bugprone-errors

---

control/autoware_pid_longitudinal_controller/README.md
control/autoware_pid_longitudinal_controller/config/autoware_pid_longitudinal_controller.param.yaml
control/autoware_pid_longitudinal_controller/include/autoware/pid_longitudinal_controller/pid_longitudinal_controller.hpp
control/autoware_pid_longitudinal_controller/src/pid_longitudinal_controller.cpp

This PR provides a new compensation mode trajectory_goal_adaptive.
Road slope estimation from trajectory is works well only if the rest trajectory length is longer than wheel base length.
Only this situation, the new mode use pose estimation ptich.
https://github.com/autowarefoundation/autoware_launch/pull/1288
None.
None.
None.

feat(pid_longitudinal_controller): add new slope compensation mode trajectory_goal_adaptive

---

perception/autoware_bytetrack/lib/src/lapjv.cpp

This is a fix based on clang-tidy `bugprone-reserved-identifier` error.
```
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_bytetrack/lib/src/lapjv.cpp:47:7: error: declaration uses identifier '_ccrrt_dense', which is reserved in the global namespace [bugprone-reserved-identifier,-warnings-as-errors]
int_t _ccrrt_dense(
^~~~~~~~~~~~
ccrrt_dense
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_bytetrack/lib/src/lapjv.cpp:111:7: error: declaration uses identifier '_carr_dense', which is reserved in the global namespace [bugprone-reserved-identifier,-warnings-as-errors]
int_t _carr_dense(
^~~~~~~~~~~
carr_dense
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_bytetrack/lib/src/lapjv.cpp:184:8: …
```

fix(autoware_bytetrack): fix bugprone-reserved-identifier

---

common/autoware_motion_utils/test/src/trajectory/benchmark_calcLateralOffset.cpp

Fixed clang compiler error
```
--- stderr: autoware_motion_utils                                
/home/veqcc/work/autoware/src/universe/autoware.universe/common/autoware_motion_utils/test/src/trajectory/benchmark_calcLateralOffset.cpp:29:18: error: unused variable 'epsilon' [-Werror,-Wunused-const-variable]
constexpr double epsilon = 1e-6;
^
1 error generated.
gmake[2]: *** [CMakeFiles/test_autoware_motion_utils.dir/build.make:132: CMakeFiles/test_autoware_motion_utils.dir/test/src/trajectory/benchmark_calcLateralOffset.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:185: CMakeFiles/test_autoware_motion_utils.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
```
- Link
build and test
None.
None.
None.

fix(autoware_motion_utils): remove clang compiler error

---

vehicle/autoware_raw_vehicle_cmd_converter/CMakeLists.txt

fix build-and-test-daily error which mentioned in 
https://github.com/autowarefoundation/autoware.universe/pull/8782#discussion_r1895007089
- Link
None.
None.
None.

fix(raw_veihicle_converter): fix too long line

---

common/autoware_universe_utils/test/src/math/test_trigonometry.cpp

This PR fixes a bug in random float value generations in autoware_unvierse_utils.
When I was fixing clang compiler warning,
```
$ colcon build --packages-select autoware_universe_utils
Starting >>> autoware_universe_utils
--- stderr: autoware_universe_utils                             
/home/veqcc/work/autoware/src/universe/autoware.universe/common/autoware_universe_utils/test/src/math/test_trigonometry.cpp:66:49: error: implicit conversion from 'int' to 'float' changes value from 2147483647 to 2147483648 [-Werror,-Wimplicit-const-int-float-conversion]
float x = static_cast<float>(std::rand()) / RAND_MAX * 20.0 - 10.0;
~ ^~~~~~~~
/usr/include/stdlib.h:87:18: note: expanded from macro 'RAND_MAX'
#define RAND_MAX        2147483647
^~~~~~~~~~
```
I found that the way random values are …

fix(autoware_universe_utils): fix bug in test

---

planning/behavior_velocity_planner/autoware_behavior_velocity_run_out_module/src/scene.cpp

Suppressed in comments so that the meaning of the branch is clear.
```
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/behavior_velocity_planner/autoware_behavior_velocity_run_out_module/src/scene.cpp:814:5: error: switch has 2 consecutive identical branches [bugprone-branch-clone,-warnings-as-errors]
case State::GO: {
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/behavior_velocity_planner/autoware_behavior_velocity_run_out_module/src/scene.cpp:822:6: note: last of these clones ends here
}
^
```
- Link
None.
None.
None.

fix(autoware_behavior_velocity_run_out_module): fix bugprone-branch-clone

---

sensing/autoware_image_transport_decompressor/src/image_transport_decompressor.cpp

```
/home/emb4/autoware/autoware/src/universe/autoware.universe/sensing/autoware_image_transport_decompressor/src/image_transport_decompressor.cpp:110:48: error: repeated branch in conditional chain [bugprone-branch-clone,-warnings-as-errors]
if (encoding_ == std::string("default")) {
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/sensing/autoware_image_transport_decompressor/src/image_transport_decompressor.cpp:112:8: note: end of the original
} else if (encoding_ == std::string("rgb8")) {
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/sensing/autoware_image_transport_decompressor/src/image_transport_decompressor.cpp:116:14: note: clone 1 starts here
} else {
^
```
- Link …

fix(autoware_image_transport_decompressor): fix bugprone-branch-clone

---

common/autoware_interpolation/test/src/test_interpolation_utils.cpp

Fixed clang complier error
```
--- stderr: autoware_interpolation                               
/home/veqcc/work/autoware/src/universe/autoware.universe/common/autoware_interpolation/test/src/test_interpolation_utils.cpp:21:18: error: unused variable 'epsilon' [-Werror,-Wunused-const-variable]
constexpr double epsilon = 1e-6;
^
1 error generated.
gmake[2]: *** [CMakeFiles/test_interpolation.dir/build.make:90: CMakeFiles/test_interpolation.dir/test/src/test_interpolation_utils.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:185: CMakeFiles/test_interpolation.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< autoware_interpolation [0.92s, exited with code 2]
```
- Link
build and test
```
$ colcon build --symlink-install --cmake-args …
```

fix(autoware_interpolation): remove clang compiler error

---

evaluator/autoware_planning_evaluator/src/motion_evaluator_node.cpp
evaluator/autoware_planning_evaluator/src/planning_evaluator_node.cpp

```
/home/emb4/autoware/autoware/src/universe/autoware.universe/evaluator/autoware_planning_evaluator/src/motion_evaluator_node.cpp:48:22: error: an exception may be thrown in function '~MotionEvaluatorNode' which should not throw exceptions [bugprone-exception-escape,-warnings-as-errors]
MotionEvaluatorNode::~MotionEvaluatorNode()
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/evaluator/autoware_planning_evaluator/src/planning_evaluator_node.cpp:71:24: error: an exception may be thrown in function '~PlanningEvaluatorNode' which should not throw exceptions [bugprone-exception-escape,-warnings-as-errors]
PlanningEvaluatorNode::~PlanningEvaluatorNode()
^
```
- Link
None.
None.
None.

fix(autoware_planning_evaluator): fix bugprone-exception-escape

---

sensing/autoware_image_diagnostics/src/image_diagnostics_node.cpp

```
/home/emb4/autoware/autoware/src/universe/autoware.universe/sensing/autoware_image_diagnostics/src/image_diagnostics_node.cpp:174:63: error: repeated branch in conditional chain [bugprone-branch-clone,-warnings-as-errors]
} else if (region_state_vec[j] == Image_State::LOW_VIS) {
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/sensing/autoware_image_diagnostics/src/image_diagnostics_node.cpp:178:8: note: end of the original
} else if (region_state_vec[j] == Image_State::BACKLIGHT) {
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/sensing/autoware_image_diagnostics/src/image_diagnostics_node.cpp:178:65: note: clone 1 starts here
} else if (region_state_vec[j] == Image_State::BACKLIGHT) {
^
``` …

fix(autoware_image_diagnostics): fix bugprone-branch-clone

---

perception/autoware_image_projection_based_fusion/CMakeLists.txt
perception/autoware_image_projection_based_fusion/README.md
perception/autoware_image_projection_based_fusion/config/fusion_common.param.yaml
perception/autoware_image_projection_based_fusion/include/autoware/image_projection_based_fusion/camera_projection.hpp
perception/autoware_image_projection_based_fusion/include/autoware/image_projection_based_fusion/fusion_node.hpp
perception/autoware_image_projection_based_fusion/include/autoware/image_projection_based_fusion/pointpainting_fusion/node.hpp
perception/autoware_image_projection_based_fusion/include/autoware/image_projection_based_fusion/roi_cluster_fusion/node.hpp
perception/autoware_image_projection_based_fusion/include/autoware/image_projection_based_fusion/roi_detected_object_fusion/node.hpp
perception/autoware_image_projection_based_fusion/include/autoware/image_projection_based_fusion/roi_pointcloud_fusion/node.hpp
perception/autoware_image_projection_based_fusion/include/autoware/image_projection_based_fusion/segmentation_pointcloud_fusion/node.hpp
perception/autoware_image_projection_based_fusion/include/autoware/image_projection_based_fusion/utils/utils.hpp
perception/autoware_image_projection_based_fusion/schema/fusion_common.schema.json
perception/autoware_image_projection_based_fusion/src/camera_projection.cpp
perception/autoware_image_projection_based_fusion/src/fusion_node.cpp
perception/autoware_image_projection_based_fusion/src/pointpainting_fusion/node.cpp
perception/autoware_image_projection_based_fusion/src/roi_cluster_fusion/node.cpp
perception/autoware_image_projection_based_fusion/src/roi_detected_object_fusion/node.cpp
perception/autoware_image_projection_based_fusion/src/roi_pointcloud_fusion/node.cpp
perception/autoware_image_projection_based_fusion/src/segmentation_pointcloud_fusion/node.cpp
perception/autoware_image_projection_based_fusion/src/utils/utils.cpp

This PR introduces a caching feature for calculating raw image projections (unrectifyPoint).
This PR must merged with https://github.com/autowarefoundation/autoware_launch/pull/1275
It introduces the CameraProjection class to handle the related processes. The cache is computed based on specific grid centers, and the projected points are represented using these grid centers. These grid centers are determined by `approximation_grid_cell_width` and `approximation_grid_cell_height`.
Pre-cached result will be simply stored in an array and all grid cells on the image will be pre-computed.
For example, when approximation_grid_cell_\* is set to 1.0 pixel, the grid centers will be created as shown in the following image:
***Note that edge pixels ((w, \*), (\*, h)) will be rounded to fall outside …

feat(image_projection_based_fusion): add cache for camera projection

---

planning/autoware_path_optimizer/include/autoware/path_optimizer/type_alias.hpp
planning/autoware_path_optimizer/package.xml
planning/autoware_path_smoother/include/autoware/path_smoother/type_alias.hpp
planning/autoware_path_smoother/package.xml
planning/sampling_based_planner/autoware_path_sampler/include/autoware_path_sampler/type_alias.hpp
planning/sampling_based_planner/autoware_path_sampler/package.xml

Run the following command, and manually add `autoware_internal_debug_msgs` in the package.xml
```
find ./ -type f -exec sed -i -e 's/tier4_debug_msgs::msg::StringStamped/autoware_internal_debug_msgs::msg::StringStamped/g' {} \;
find ./ -type f -exec sed -i -e 's/tier4_debug_msgs\/msg\/string_stamped/autoware_internal_debug_msgs\/msg\/string_stamped/g' {} \;
```
None.
None.
None.

feat(motion_planning): use StringStamped in autoware_internal_debug_msgs

---

planning/motion_velocity_planner/autoware_motion_velocity_dynamic_obstacle_stop_module/src/dynamic_obstacle_stop_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/src/obstacle_velocity_limiter_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/plugin_module_interface.hpp
planning/motion_velocity_planner/autoware_motion_velocity_planner_common/package.xml
planning/motion_velocity_planner/autoware_motion_velocity_planner_node/package.xml
planning/motion_velocity_planner/autoware_motion_velocity_planner_node/src/node.cpp
planning/motion_velocity_planner/autoware_motion_velocity_planner_node/src/node.hpp

Run the following command, and manually add autoware_internal_debug_msgs in the package.xml
```
find ./ -type f -exec sed -i -e 's/tier4_debug_msgs::msg::Float64Stamped/autoware_internal_debug_msgs::msg::Float64Stamped/g' {} \;
find ./ -type f -exec sed -i -e 's/tier4_debug_msgs\/msg\/float64_stamped/autoware_internal_debug_msgs\/msg\/float64_stamped/g' {} \;
```
None.
None.
None.

feat(motion_velocity_planner): use Float64Stamped in autoware_internal_debug_msgs

---

system/diagnostic_graph_utils/package.xml
system/diagnostic_graph_utils/src/node/logging.cpp
system/diagnostic_graph_utils/src/node/logging.hpp

Run the following command, and manually add `autoware_internal_debug_msgs` in the package.xml
```
find ./ -type f -exec sed -i -e 's/tier4_debug_msgs::msg::StringStamped/autoware_internal_debug_msgs::msg::StringStamped/g' {} \;
find ./ -type f -exec sed -i -e 's/tier4_debug_msgs\/msg\/string_stamped/autoware_internal_debug_msgs\/msg\/string_stamped/g' {} \;
```
None.
None.
None.

feat(diagnostic_graph_utils): use StringStamped in autoware_internal_debug_msgs

---

planning/autoware_velocity_smoother/include/autoware/velocity_smoother/node.hpp
planning/autoware_velocity_smoother/package.xml

Use autoware internal stamped messages in velocity smoother
None.
None.
None.

feat(velocity_smoother): use autoware internal Stamped messages

---

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/calculation.cpp

When the prepare metrics are computed, if the ego velocity is lower than the lane-changing velocity, the returned prepare duration becomes abnormally short, even when the ego vehicle is far from the terminal stop.
In the following video, the prepare distance is less than 1m.
https://github.com/user-attachments/assets/0abc6453-bf89-4598-8080-d903ef7e48c7
In above video, current_velocity is somewhere less than min_lc_velocity, and the following is computed
```
(min_lc_velocity - current_velocity) / max_acc;
```
the small discrepancy resulted in very short duration.
The solution is to compare the computation with parameterized `min_prepare_duration`
https://github.com/user-attachments/assets/fae6266e-a198-44d6-8c45-16ca1a0d66c4
[TIER IV Internal …

fix(lane_change): fix prepare length too short at low speed (RT1-8909)

---

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/CMakeLists.txt
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/base_class.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/scene.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/structs/data.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/path.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/utils.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/path.cpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/test/test_lane_change_scene.cpp

Move candidate path generator/constructor-related function to `utils/path.hpp/cpp`.
If we planning  on adding new path generation functions, utils.hpp/cpp file might be overcrowded. So for maintainability purpose, it is better to isolate these functions.
- Link
[TIER IV Internal link](https://evaluation.tier4.jp/evaluation/reports/2745c429-ad26-5514-bc32-8541f7466775?project_id=prd_jt)
None.
None.
None.

refactor(lane_change): separate path-related function to utils/path

---

system/diagnostic_graph_aggregator/test/src/test2.cpp

Remove unused message alias.
https://github.com/tier4/tier4_autoware_msgs/pull/145
Check if the build passes.
None.
None.
None.

fix(diagnostic_graph_aggregator): remove unused message alias

---

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/markers.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/markers.cpp

Adds path metrics along valid paths' visualization.
https://github.com/user-attachments/assets/61d42394-80dd-4cf4-9c1c-3b77364e185f
Visualization can be turn on and off separately.
- Link
None.
None.
None.

fix(lane_change): add metrics to valid paths visualization

---

perception/autoware_tensorrt_classifier/src/tensorrt_classifier.cpp

```
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_tensorrt_classifier/src/tensorrt_classifier.cpp:194:16: error: an exception may be thrown in function '~TrtClassifier' which should not throw exceptions [bugprone-exception-escape,-warnings-as-errors]
TrtClassifier::~TrtClassifier()
^
```
- Link
None.
None.
None.

fix(autoware_tensorrt_classifier): fix bugprone-exception-escape

---

perception/autoware_tensorrt_yolox/src/tensorrt_yolox.cpp

```
/home/emb4/autoware/autoware/src/universe/autoware.universe/perception/autoware_tensorrt_yolox/src/tensorrt_yolox.cpp:342:11: error: an exception may be thrown in function '~TrtYoloX' which should not throw exceptions [bugprone-exception-escape,-warnings-as-errors]
TrtYoloX::~TrtYoloX()
^
```
- Link
None.
None.
None.

fix(autoware_tensorrt_yolox): fix bugprone-exception-escape

---

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/shift_line_generator.cpp

```
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp:236:35: error: repeated branch in conditional chain [bugprone-branch-clone,-warnings-as-errors]
if (!not_use_adjacent_lane) {
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp:240:8: note: end of the original
} else if (red_signal_lane_itr->id() != lanelet.id()) {
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp:240:61: note: clone 1 starts …
```

fix(autoware_behavior_path_static_obstacle_avoidance_module): fix bugprone-branch-clone

---

system/autoware_default_adapi/src/utils/route_conversion.cpp

In the case of `switch-case`, it is difficult to understand if the conditions are summarized, so a comment is used to suppress errors.
```
/home/emb4/autoware/autoware/src/universe/autoware.universe/system/autoware_default_adapi/src/utils/route_conversion.cpp:118:7: error: switch has 3 consecutive identical branches [bugprone-branch-clone,-warnings-as-errors]
case InternalState::INITIALIZING: return ExternalState::UNSET;
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/system/autoware_default_adapi/src/utils/route_conversion.cpp:120:68: note: last of these clones ends here
case InternalState::ROUTING:      return ExternalState::UNSET;
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/system/autoware_d …
```

fix(autoware_default_adapi): fix bugprone-branch-clone

---

planning/autoware_route_handler/src/route_handler.cpp

```
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/autoware_route_handler/src/route_handler.cpp:1161:38: error: an exception may be thrown in function 'getAllLeftSharedLinestringLanelets' which should not throw exceptions [bugprone-exception-escape,-warnings-as-errors]
lanelet::ConstLanelets RouteHandler::getAllLeftSharedLinestringLanelets(
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/autoware_route_handler/src/route_handler.cpp:1196:38: error: an exception may be thrown in function 'getAllRightSharedLinestringLanelets' which should not throw exceptions [bugprone-exception-escape,-warnings-as-errors]
lanelet::ConstLanelets RouteHandler::getAllRightSharedLinestringLanelets( …
```

fix(autoware_route_handler): fix bugprone-exception-escape

---

planning/motion_velocity_planner/autoware_motion_velocity_dynamic_obstacle_stop_module/package.xml
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/package.xml
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/package.xml
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_module.hpp
planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/planner_data.hpp
planning/motion_velocity_planner/autoware_motion_velocity_planner_common/package.xml
planning/motion_velocity_planner/autoware_motion_velocity_planner_node/package.xml
planning/motion_velocity_planner/autoware_motion_velocity_planner_node/src/node.cpp

remove unnecessary tier4_planning_msgs dependency in motion_velocity_planner
- Link
None.
None.
None.

feat(motion_velocity_planner): remove unnecessary tier4_planning_msgs dependency

---

perception/autoware_multi_object_tracker/README.md
perception/autoware_multi_object_tracker/schema/multi_object_tracker_node.schema.json

Fix error of https://autowarefoundation.github.io/autoware.universe/main/perception/autoware_multi_object_tracker/ 
- Link
Documentation generation is confirmed by the following local generation method.
https://autowarefoundation.github.io/autoware-documentation/main/contributing/documentation-guidelines/#2-running-an-mkdocs-server-in-your-local-environment
None.
None.
None.

chore(autoware_multi_object_tracker): fix autoware univserse documentation page

---

common/autoware_universe_utils/include/autoware/universe_utils/ros/debug_traits.hpp
common/autoware_universe_utils/package.xml
planning/behavior_path_planner/autoware_behavior_path_planner/include/autoware/behavior_path_planner/planner_manager.hpp
planning/behavior_path_planner/autoware_behavior_path_planner/package.xml

Use stamped message in autoware_internal_debug_msgs in behavior_path_planner
None.
None.
None.

feat(behavior_path_planner): use autoware internal stamped messages

---

planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/benchmarks/collision_checker_benchmark.cpp

```
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/benchmarks/collision_checker_benchmark.cpp:56:5: error: an exception may be thrown in function 'main' which should not throw exceptions [bugprone-exception-escape,-warnings-as-errors]
int main()
^
```
- Link
None.
None.
None.

fix(autoware_motion_velocity_obstacle_velocity_limiter_module): fix bugprone-exception-escape

---

system/autoware_processing_time_checker/src/processing_time_checker.cpp

```
/home/emb4/autoware/autoware/src/universe/autoware.universe/system/autoware_processing_time_checker/src/processing_time_checker.cpp:100:24: error: an exception may be thrown in function '~ProcessingTimeChecker' which should not throw exceptions [bugprone-exception-escape,-warnings-as-errors]
ProcessingTimeChecker::~ProcessingTimeChecker()
^
```
- Link
None.
None.
None.

fix(autoware_processing_time_checker): fix bugprone-exception-escape

---

planning/autoware_objects_of_interest_marker_interface/src/objects_of_interest_marker_interface.cpp

```
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/autoware_objects_of_interest_marker_interface/src/objects_of_interest_marker_interface.cpp:85:5: error: switch has 2 consecutive identical branches [bugprone-branch-clone,-warnings-as-errors]
case ColorName::GRAY:
^
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/autoware_objects_of_interest_marker_interface/src/objects_of_interest_marker_interface.cpp:88:38: note: last of these clones ends here
return coloring::getGray(alpha);
^
```
- Link
None.
None.
None.

fix(autoware_objects_of_interest_marker_interface): fix bugprone-branch-clone

---

planning/autoware_planning_test_manager/include/autoware_planning_test_manager/autoware_planning_test_manager_utils.hpp
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/include/autoware/behavior_path_start_planner_module/shift_pull_out.hpp
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/test/test_shift_pull_out.cpp

original [pr](https://github.com/autowarefoundation/autoware.universe/pull/9661) 
1. Added test environment for `autoware_behavior_path_start_planner_module`
2. Added `TestShiftPullOut` as a friend class to `ShiftPullOut` class
- Enabled access to private members from the test class
- Link
run colcon test with following command
```
colcon test --event-handlers console_cohesion+ --packages-select autoware_behavior_path_start_planner_module
```
get the success result
```
1: [----------] 1 test from TestShiftPullOut
1: [ RUN      ] TestShiftPullOut.GenerateValidShiftPullOutPath
1: [INFO] [route_handler]: getMainLanelets: lanelet_sequence = [ids: 4618 4635 ] (getMainLanelets:2025)
1: primitive: 4618
1: preferred_primitive id : 4618
1: primitive: 4635
1: primitive: 7787
1: …
```

test(autoware_behavior_path_start_planner_module): add unit tests for shift shift pull out planner

---

planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/package.xml
planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/scripts/time_to_collision_plotter.py
planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/package.xml
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/scripts/ttc.py
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection_collision.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/include/autoware/behavior_velocity_planner_common/scene_module_interface.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/package.xml
planning/behavior_velocity_planner/autoware_behavior_velocity_run_out_module/package.xml
planning/behavior_velocity_planner/autoware_behavior_velocity_run_out_module/src/debug.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_run_out_module/src/debug.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_run_out_module/src/scene.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_run_out_module/src/utils.hpp

Run the following command, and manually add `autoware_internal_debug_msgs` in the package.xml
```
find ./ -type f -exec sed -i -e 's/tier4_debug_msgs\/msg\/string_stamped/autoware_internal_debug_msgs\/msg\/string_stamped/g' {} \;
find ./ -type f -exec sed -i -e 's/tier4_debug_msgs::msg::StringStamped/autoware_internal_debug_msgs::msg::StringStamped/g' {} \;
find ./ -type f -exec sed -i -e 's/tier4_debug_msgs\/msg\/float64_stamped/autoware_internal_debug_msgs\/msg\/float64_stamped/g' {} \;
find ./ -type f -exec sed -i -e 's/tier4_debug_msgs::msg::Float64Stamped/autoware_internal_debug_msgs::msg::Float64Stamped/g' {} \;
find ./ -type f -exec sed -i -e 's/tier4_debug_msgs\/msg\/float32_stamped/autoware_internal_debug_msgs\/msg\/float32_stamped/g' {} \;
find ./ -type f -exec sed -i -e …
```

feat(behavior_velocity_planner): use XXXStamped in autoware_internal_debug_msgs

---

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/structs/debug.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/package.xml
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/markers.cpp

Replacing `ostringstream` to `fmt::format` for text marker.
- Link
Build success.
Check lane change debug marker in PSIM.
None.
None.
None.

refactor(lane_change): replace sstream to fmt for marker's text

---

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/shift_line_generator.cpp

Adds missing optional check for red_signal.
Fix https://github.com/autowarefoundation/autoware.universe/pull/9701
- Link
https://evaluation.tier4.jp/evaluation/reports/faee1737-fe4c-5005-9bf3-f01eabd33f56?project_id=prd_jt
None.
None.
None.

fix(static_avoidance): add optional check

---

planning/behavior_velocity_planner/autoware_behavior_velocity_planner/CMakeLists.txt
planning/behavior_velocity_planner/autoware_behavior_velocity_planner/include/autoware/behavior_velocity_planner/node.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_planner/include/autoware/behavior_velocity_planner/planner_manager.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_planner/include/autoware/behavior_velocity_planner/test_utils.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_planner/package.xml
planning/behavior_velocity_planner/autoware_behavior_velocity_planner/src/node.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_planner/src/planner_manager.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_planner/src/test_utils.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_planner/test/test_node_interface.cpp

Currently, due to the node test, the behavior_velocity_planner depends on the plugin packages, which is unexpected because we introduced the ROS2's pluginlib so that the node will node depend on the plugin packages.
Referring to the the structure of the behavior_path_planner's node test, this PR changed the structure of the behavior_velocity_planner's node test.
https://github.com/autowarefoundation/autoware.universe/blob/main/planning/behavior_path_planner/autoware_behavior_path_planner/test/test_autoware_behavior_path_planner_node_interface.cpp
The node test in the plugin packages will be added by the succeeding PRs.
- Link
None.
None.
None.

refactor(behavior_velocity_planner): independent of plugin packages

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/package.xml
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/package.xml

add missing dependency of freespace_planning_algorithms in behavior_path_planner
- Link
None.
None.
None.

fix(behavior_path_planner): add freespace_planning_algorithms dependency

---

build_depends.repos

Updated the version of autoware_internal_msgs in build_depends.repos based on https://github.com/autowarefoundation/autoware/pull/5612
- Link
None.
None.
None.

feat(build_depends.repos): update version of autoware_internal_msgs

---

common/autoware_universe_utils/include/autoware/universe_utils/ros/diagnostics_interface.hpp
common/autoware_universe_utils/src/ros/diagnostics_interface.cpp
common/autoware_universe_utils/test/src/ros/test_diagnostics_interface.cpp
localization/autoware_gyro_odometer/src/gyro_odometer_core.cpp
localization/autoware_gyro_odometer/src/gyro_odometer_core.hpp
localization/autoware_landmark_based_localizer/autoware_lidar_marker_localizer/src/lidar_marker_localizer.cpp
localization/autoware_landmark_based_localizer/autoware_lidar_marker_localizer/src/lidar_marker_localizer.hpp
localization/autoware_localization_error_monitor/src/localization_error_monitor.cpp
localization/autoware_localization_error_monitor/src/localization_error_monitor.hpp
localization/autoware_ndt_scan_matcher/include/autoware/ndt_scan_matcher/map_update_module.hpp
localization/autoware_ndt_scan_matcher/include/autoware/ndt_scan_matcher/ndt_scan_matcher_core.hpp
localization/autoware_ndt_scan_matcher/src/map_update_module.cpp
localization/autoware_ndt_scan_matcher/src/ndt_scan_matcher_core.cpp
localization/autoware_pose_initializer/src/pose_initializer_core.cpp
localization/autoware_pose_initializer/src/pose_initializer_core.hpp

I mistakenly named the object "DiagnosticInterface", but would be better to name it "DiagnosticsInterface". Currently the name of the class is inconsistent with the file name as well.
None
Tested with logging_simulator that the localization starts without any failure. Also confirmed that the diagnostics messages are published from localization nodes.
None.
None.
None.

refactor(autoware_universe_utils): add missing 's' in the class of diagnostics_interface

---

planning/autoware_static_centerline_generator/src/main.cpp

```
/home/emb4/autoware/autoware/src/universe/autoware.universe/planning/autoware_static_centerline_generator/src/main.cpp:20:5: error: an exception may be thrown in function 'main' which should not throw exceptions [bugprone-exception-escape,-warnings-as-errors]
int main(int argc, char * argv[])
^
```
- Link
None.
None.
None.

fix(autoware_static_centerline_generator): fix bugprone-exception-escape

---

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/structs/debug.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/markers.cpp

Display candidate path sampling metrics for prepare phase and lane changing phase on rviz to help with debugging.
None.
- PSIM
None.
None.
None.

feat(lane_change): add text display for candidate path sampling metrics

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/examples/plot_map_case1.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/examples/plot_map_case2.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/fixed_goal_planner_base.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_module.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/pull_over_planner/bezier_pull_over.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/pull_over_planner/freespace_pull_over.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/pull_over_planner/geometric_pull_over.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/pull_over_planner/pull_over_planner_base.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/pull_over_planner/shift_pull_over.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/thread_data.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/bezier_pull_over.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/freespace_pull_over.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/geometric_pull_over.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/shift_pull_over.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/thread_data.cpp

- rename `previous_module_output` to `upstream_module_output`
- save `last_upsream_module_output` in LaneParkingPlanner as the upsream_module_output used for generating pull over path candidates
- Link
- https://evaluation.tier4.jp/evaluation/reports/695b64fd-6cdb-579f-af19-1e5304b804a9?project_id=prd_jt
- base: https://evaluation.tier4.jp/evaluation/reports/68884626-8bf7-5005-b5d5-7fefa9a878f8?project_id=prd_jt
None.
None.
None.

fix(goal_planner): fix usage of last_previous_module_output

---

planning/motion_velocity_planner/autoware_motion_velocity_dynamic_obstacle_stop_module/src/dynamic_obstacle_stop_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_dynamic_obstacle_stop_module/src/object_filtering.cpp
planning/motion_velocity_planner/autoware_motion_velocity_dynamic_obstacle_stop_module/src/object_filtering.hpp
planning/motion_velocity_planner/autoware_motion_velocity_dynamic_obstacle_stop_module/test/test_object_filtering.cpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/src/obstacle_velocity_limiter.cpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/src/obstacle_velocity_limiter.hpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/src/obstacle_velocity_limiter_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/src/obstacles.cpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/src/obstacles.hpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/test/test_collision_distance.cpp
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/filter_predicted_objects.cpp
planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/planner_data.hpp
planning/motion_velocity_planner/autoware_motion_velocity_planner_node/src/node.cpp

This PR defines Object/Pointcloud structures in Planner so that each structure can have pre-processed information as follows.
- Object
- distance to ego's trajectory
- longitudinal velocity relative to ego's trajectory
- Pointcoud
- clustered results
The motivation of these structures is to reducing the computational cost by performing the pre-process for the predicted objects and pointcloud.
In the latter PR, the pre-processed data will be added to these structures.
psim worked well.
TIER IV internal scenario tests: https://evaluation.tier4.jp/evaluation/reports/43edba84-bbc4-5ed0-9ede-bcc74ad90c16?project_id=prd_jt
None.
None.
None.

feat(motion_velocity_planner): introduce Object/Pointcloud structure in PlannerData

---

planning/behavior_velocity_planner/autoware_behavior_velocity_planner/include/autoware/behavior_velocity_planner/node.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_planner/package.xml
planning/behavior_velocity_planner/autoware_behavior_velocity_planner/src/node.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_planner/src/test_utils.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/include/autoware/behavior_velocity_planner_common/planner_data.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/include/autoware/behavior_velocity_planner_common/scene_module_interface.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/package.xml
planning/behavior_velocity_planner/autoware_behavior_velocity_virtual_traffic_light_module/src/manager.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_virtual_traffic_light_module/src/manager.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_virtual_traffic_light_module/src/scene.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_virtual_traffic_light_module/src/scene.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_virtual_traffic_light_module/test/test_node_interface.cpp

Currently, the virtual traffic light's variables in the `behavior_velocity_planner/behavior_velocity_planner_common` are very specific to the `behavior_velocity_virtual_traffic_light_module` and do not need to be shared in other modules.
Therefore, this PR moved the implementation related to the virtual traffic light from the `behavior_velocity_planner/behavior_velocity_planner_common` to the `behavior_velocity_virtual_traffic_light_module`.
The unit test passed.
The psim worked as expected.
None.
None.
None.

feat(behavior_velocity_planner): remove virtual traffic light dependency from behavior_velocity_planner and behavior_velocity_planner_common

---

planning/behavior_velocity_planner/autoware_behavior_velocity_stop_line_module/docs/node_and_segment.drawio.svg

Fixes a subject-verb agreement error in an SVG file in [Stop Line documentation](https://autowarefoundation.github.io/autoware.universe/main/planning/behavior_velocity_planner/autoware_behavior_velocity_stop_line_module/).
@yhisaki Please review this pull request when you have time.

fix(planning): corrects typo in svg

---

planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/benchmarks/collision_checker_benchmark.cpp

The last `cppcheck-weekly` CI detected something wrong in `autoware_motion_velocity_obstacle_velocity_limiter_module`.
https://github.com/autowarefoundation/autoware.universe/actions/runs/12624163932
I decided to ignore `benchmarks` directories instead of fixing the warnings.
Thus, I removed cppcheck-related suppressions from `autoware_motion_velocity_obstacle_velocity_limiter_module/benchmarks/`
`benchmarks` directories will be ignored by cppcheck with the following PR
https://github.com/autowarefoundation/autoware.universe/pull/9842
None.
None.
None.

fix(autoware_motion_velocity_obstacle_velocity_limiter_module): remove cppcheck suppressions

---

perception/autoware_image_projection_based_fusion/include/autoware/image_projection_based_fusion/fusion_node.hpp
perception/autoware_image_projection_based_fusion/src/fusion_node.cpp

Since [callback group](https://docs.ros.org/en/foxy/How-To-Guides/Using-callback-groups.html) is not set in the `autoware_image_projection_based_fusion`, all the callbacks are in a same group.
Therefore, the mutex is not necessary.
This PR do not contain any logic change.
- Link
Tested in a local environment.
lidar_detection_model: pointpainting
tested
* pointpainting fusion
* roi cluster fusion
* roi detected-object fusion
* roi pointcloud fusion
not tested
* segment pointcloud fusion
None.
None.
None.

fix(image_projection_based_fusion): remove mutex

---

visualization/autoware_overlay_rviz_plugin/autoware_string_stamped_overlay_rviz_plugin/package.xml

I fixed the version described in `autoware_string_stamped_overlay_rviz_plugin` to the latest version (0.40.0).
This change is necessary to generate changelog and bump version.
- Link
None.
None.
None.

chore(autoware_string_stamped_overlay_rviz_plugin): fix version in package.xml

---

localization/autoware_twist2accel/package.xml
localization/autoware_twist2accel/src/twist2accel.hpp

I merged https://github.com/autowarefoundation/autoware.universe/pull/9868, but I realize now that `autoware_internal_debug_msgs` is not used in `autoware_twist2accel`. So this pull request removes that dependency.
None.
None.
None.
None.

chore(autoware_twist2accel): remove an unused dependency

---

localization/autoware_pose2twist/README.md
localization/autoware_pose2twist/package.xml
localization/autoware_pose2twist/src/pose2twist_core.cpp
localization/autoware_pose2twist/src/pose2twist_core.hpp

None.
None.
| Version | Topic Type      | Topic Name        | Message Type        | Description       |
|:--------|:----------------|:------------------|:--------------------|:------------------|
| Old     | Pub | `linear_x` | `tier4_debug_msgs::msg::Float32Stamped` | linear-x field of the output twist. |
| New     | Pub | `linear_x` | `autoware_internal_debug_msgs::msg::Float32Stamped` | linear-x field of the output twist. |
| Old     | Pub | `angular_z` | `tier4_debug_msgs::msg::Float32Stamped` | angular-z field of the output twist. |
| New     | Pub | `angular_z` | `autoware_internal_debug_msgs::msg::Float32Stamped` | angular-z field of the output twist. |
None.

feat: tier4_debug_msgs changed to autoware_internal_debug_msgs in files localization/autoware_pose2twist

---

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/interface.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/structs/data.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/structs/debug.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/markers.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/interface.cpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/markers.cpp

Refactoring `canTransitToFailState` function. Reduce similar computation, and reduce nested loop. Also added debug marker for visualizing state and the transitioning reason.
- Link
1. PSIM
2. [TIER IV Internal link](https://evaluation.tier4.jp/evaluation/reports/e0c293da-51e9-5058-8dff-83ef20c83ca4?project_id=prd_jt)
None.
None.
None.

refactor(lane_change): refactor transit failure function

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_module.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp

There was a lateral shift when the goal planner pathway started.
To reduce it, the value of lateral_deviation_thresh was changed from 0.3 to 0.1.
and minor refactroing by unifying similar functions
[TIER IV Internal link](https://star4.slack.com/archives/C03QW0GU6P7/p1735016420151249?Thread_ts=1735016349.347359&cid=C03QW0GU6P7)
Scenairo test in PSIM (I looked at the `/planning/planning_evaluator/metrics/lateral_tajectory_displacement_local/max`)
https://github.com/user-attachments/assets/90867f09-fb3b-4700-aa90-61b0b8934028
None.
None.
None.

feat(goal_planner): update lateral_deviation_thresh from `0.3` to `0.1`

---

evaluator/autoware_planning_evaluator/src/metrics/deviation_metrics.cpp

Changed lateral_trajectory_displacement to absolute value.
This is to make it easier to determine when testing(TIER IV Internal use case).
* https://github.com/autowarefoundation/autoware.universe/pull/9674
- Link
None.
None.
None.

fix(planning_evaluator): update lateral_trajectory_displacement to absolute value

---

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/scene.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/structs/debug.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/markers.cpp

for each metrics sample in the debug table, append the corresponding candidate path index, as shown below.
None.
- PSIM
None.
None.
None.

feat(lane_change): append candidate path index to metric debug table

---

simulator/learning_based_vehicle_model/src/interconnected_model.cpp

This is a fix based on clang-tidy clang-diagnostic-delete-abstract-non-virtual-dtor error.
```
Command: clang-tidy-14 -p build/learning_based_vehicle_model --header-filter=/home/hisaki/workspace/clang-tidy-ci/autoware/src/universe/autoware.universe/simulator/learning_based_vehicle_model/.* --config-file=.clang-tidy-ci /home/hisaki/workspace/clang-tidy-ci/autoware/src/universe/autoware.universe/simulator/learning_based_vehicle_model/src/interconnected_model.cpp
2 errors generated.
Error while processing /home/hisaki/workspace/clang-tidy-ci/autoware/src/universe/autoware.universe/simulator/learning_based_vehicle_model/src/interconnected_model.cpp.
Found compiler error(s).
/usr/lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/unique_ptr.h:95:2: error: delete called on …
```

fix(learning_based_vehicle_model): fix clang-diagnostic-delete-abstract-non-virtual-dtor

---

planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/include/autoware/behavior_velocity_planner_common/scene_module_interface.hpp

This PR fix unregister process problem of behavior_velocity_plannner modules which introduced by https://github.com/autowarefoundation/autoware.universe/pull/9212
By the above PR, The variable `registered_module_id_set_` for RTC-independent modules was not being cleared.
This PR fix this issue.
None.
None.
None.

fix(behavior_velocity_planner_common): fix unregister process

---

planning/autoware_mission_planner/README.md

previously there was a mistake that odometry input was not included in README.md. Fixed that.
**Note**: Confirm the [contribution guidelines](https://autowarefoundation.github.io/autoware-documentation/main/contributing/) before submitting a pull request.
Click the `Preview` tab and select a PR template:
- [Standard change](?expand=1&template=standard-change.md)
- [Small change](?expand=1&template=small-change.md)
**Do NOT send a PR with this description.**

docs: added odometry input in README.md

---

perception/autoware_tensorrt_yolox/launch/multiple_yolox.launch.xml
perception/autoware_tensorrt_yolox/launch/yolox_s_plus_opt.launch.xml

When use `multiple_yolox.launch.xml` launch many `tensorrt_yolox` node, the names of these nodes are same.
**Solution:**
Adding two parameters `yolox_node_name` and `image_transport_decompressor_node_name` for node name in `yolox_s_plus_opt.launch.xml` and explicitly assign them in `multiple_yolox.launch.xml`.
[9146](https://github.com/autowarefoundation/autoware.universe/issues/9146)
Run the following command for testing:
`ros2 launch autoware_tensorrt_yolox multiple_yolox.launch.xml`
`ros2 node list`
None.
None.
None.

fix(autoware_tensorrt_yolox): modify tensorrt_yolox_node name

---

planning/autoware_external_velocity_limit_selector/CMakeLists.txt
planning/autoware_external_velocity_limit_selector/package.xml
planning/autoware_external_velocity_limit_selector/src/external_velocity_limit_selector_node.cpp
planning/autoware_external_velocity_limit_selector/test/test_external_velocity_limit_selector_node_launch.py

Add a node test to the `autoware_external_velocity_limit_selector` package.
- Link
None.
None.
None.

test(external_velocity_limit_selector): add node test

---

planning/autoware_remaining_distance_time_calculator/CMakeLists.txt
planning/autoware_remaining_distance_time_calculator/package.xml
planning/autoware_remaining_distance_time_calculator/param/remaining_distance_time_calculator_parameters.yaml
planning/autoware_remaining_distance_time_calculator/src/remaining_distance_time_calculator_node.cpp
planning/autoware_remaining_distance_time_calculator/src/remaining_distance_time_calculator_node.hpp

This PR enables remaining_distance_time_calculator to handle parameters using [generate_parameter_library](https://github.com/PickNikRobotics/generate_parameter_library).
Psim
Evaluator: https://evaluation.tier4.jp/evaluation/reports/51089edf-cf82-58b3-b7c9-c571753ad766?project_id=prd_jt
The node `remaining_distance_time_calculator` does not have dynamic parameters.
None.
None.

feat(remaining_distance_time_calculator): integrate generate_parameter_library

---

system/dummy_infrastructure/src/dummy_infrastructure_node/dummy_infrastructure_node.cpp

This is a duplicate of https://github.com/autowarefoundation/autoware.universe/pull/9727.
I recreated it since the original author finished contract with TIER IV and couldn't sync the PR with the latest main to pass CI.
- Link
None.
None.
None.

fix(dummy_infrastructure): fix bugprone-reserved-identifier

---

planning/autoware_costmap_generator/include/autoware/costmap_generator/costmap_generator.hpp
planning/autoware_costmap_generator/src/costmap_generator.cpp

…es planning/autoware_costmap_generator
- Link
None.
None.
None.

feat(autoware_costmap_generator): tier4_debug_msgs changed to autoware_internal-debug_msgs in autoware_costmap_generator

---

planning/autoware_surround_obstacle_checker/src/node.cpp
planning/autoware_surround_obstacle_checker/src/node.hpp

…es  planning/autoware_surround_obstacle_checker
- Link
None.
None.
None.

feat(autoware_surround_obstacle_checker): tier4_debug_msgs changed to autoware_internal_debug_msgs in autoware_surround_obstacle_checker

---

planning/autoware_freespace_planner/include/autoware/freespace_planner/freespace_planner_node.hpp
planning/autoware_freespace_planner/src/autoware_freespace_planner/freespace_planner_node.cpp

…es  planning/autoware_freespace_planner
- Link
None.
None.
None.

feat(autoware_freespace_planner): tier4_debug_msgs changed to autoware_internal_debug_msgs in autoware_freespace_planner

---

planning/autoware_scenario_selector/include/autoware/scenario_selector/node.hpp
planning/autoware_scenario_selector/src/node.cpp

…es  planning/autoware_scenario_selector
- Link
None.
None.
None.

feat(autoware_scenario_selector): tier4_debug_msgs changed to autoware_internal_debug_msgs in autoware_scenario_selector

---

sensing/autoware_image_diagnostics/README.md
sensing/autoware_image_diagnostics/package.xml
sensing/autoware_image_diagnostics/src/image_diagnostics_node.cpp
sensing/autoware_image_diagnostics/src/image_diagnostics_node.hpp

…es sensing/autoware_image_diagnostics
- Link
None.
None.
None.

feat(autoware_image_diagnostics): tier4_debug_msgs changed to autoware_internal_debug_msgs in autoware_image_diagnostics

---

perception/autoware_traffic_light_multi_camera_fusion/README.md

Modify README.
- modify explanation
- add topic type
- add parameter
- Link
None.
None.
None.

chore(autoware_traffic_light_multi_camera_fusion): modify docs

---

system/mrm_handler/src/mrm_handler/mrm_handler_core.cpp

This PR simplifies the choice of hazard commands in mrm_handler.
This also fixes clang-tidy bugprone-branch-clone warning.
https://github.com/autowarefoundation/autoware.universe/pull/9729
None.
None.
None.

fix(mrm_handler): simplify hazard command choice

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/geometric_pull_over.cpp

geometric pull over was broken with https://github.com/autowarefoundation/autoware.universe/pull/9832
parameter setting is missing 
- Link
psim 
geometric pull over works
2025/01/16 https://evaluation.tier4.jp/evaluation/reports/5cc00185-60bd-5c1b-a93f-9fecf555346a/?project_id=prd_jt
None.
None.
None.

fix(goal_planner): fix geometric pull over

---

control/autoware_pid_longitudinal_controller/README.md
control/autoware_trajectory_follower_node/param/lateral/mpc.param.yaml
control/autoware_trajectory_follower_node/param/longitudinal/pid.param.yaml
planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/config/crosswalk.param.yaml
planning/behavior_velocity_planner/autoware_behavior_velocity_stop_line_module/README.md

Removed unnecessary parameters which are not used
- Link
None.
None.
None.

fix: remove unnecessary parameters

---

planning/behavior_path_planner/autoware_behavior_path_start_planner_module/test/test_freespace_pull_out.cpp

Temporarily disable the test due to its flakiness.
The CI check is failing in this [PR](https://github.com/autowarefoundation/autoware.universe/pull/9927).
- Link
None.
None.
None.

test(start_planner): disable GenerateValidFreespacePullOutPath test

---

common/autoware_motion_utils/include/autoware/motion_utils/marker/marker_helper.hpp
common/autoware_motion_utils/include/autoware/motion_utils/marker/virtual_wall_marker_creator.hpp
common/autoware_motion_utils/src/marker/marker_helper.cpp
common/autoware_motion_utils/src/marker/virtual_wall_marker_creator.cpp

add
- "detail" field: illustrates the detailed reason of the module decision in the parenthesis ()
- `pass` type: emphasize that the module intentionally goes (does not stop) on its own decision as white arrow
like the "intersection" marker in the pic
- Link
see the description
None.
None.
None.

feat(motion_utils): add detail and pass type to VirtualWall

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/geometric_pull_over.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/shift_pull_over.cpp
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/geometric_pull_out.cpp
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/shift_pull_out.cpp

Fixes a bug in LaneDepartureChecker parameter initialization where only `footprint_extra_margin` needed to be updated.
Changes the initialization pattern to properly update only the `footprint_extra_margin` parameter.
- Link
Confirmed that setting a sufficiently large value for `lane_departure_check_expansion_margin` prevents path generation from goal_planner module when setting goals near the lane edges.
None.
None.
None.

fix(start_planner, goal_planner): refactor lane departure checker initialization

---

perception/autoware_map_based_prediction/src/predictor_vru.cpp

In `PredictorVru::setLaneletMap`, it will always accumulate the crosswalk or walkways lanelets when map gets updated.
It may work trouble-free with the current implementation in the current Autoware architecture, where the map is provided only once.
But in multiple map case (loading map like mapA -> mapB -> mapA -> ... for moving between 2 regions), it may potentially cause some extra latency since it will 
linear scan the lanelets for each targeted objects: https://github.com/autowarefoundation/autoware_lanelet2_extension/blob/c8ff315d21fc2e62329a7272e3d49edfa88fc57e/autoware_lanelet2_extension/lib/query.cpp#L885
- Link
Checked the logging simulator using the sample ROS bag.
None.
None.
None.

fix(map_based_prediction): fix unintentional accumulation of lanelets

---

perception/autoware_traffic_light_map_based_detector/README.md

Modify README.
- modify explanation
- fix topic type
- add parameter
- Link
None.
None.
None.

chore(autoware_traffic_light_map_based_detector): modify docs

---

planning/autoware_planning_validator/include/autoware/planning_validator/planning_validator.hpp

…es planning/autoware_planning_validator
- Link
None.
None.
None.

feat(autoware_planning_validator)!: tier4_debug_msgs changed to autoware_internal_debug_msgs in autoware_planning_validator

---

sensing/autoware_imu_corrector/src/gyro_bias_estimator.cpp

Publishing rate to /diagnostics from gyro_bias_estimator is set by `diagnostics_updater_interval_sec` and `setPeriod()`
However when gyro bias is updated, gyro_bias_estimator publish with `force_update() `and `setPeriod()` is executed again.
Removed `force_update() `and `setPeriod()` in gyro_bias_estimator timer callback.
- [TIERIV INTERNAL LINK](https://tier4.atlassian.net/browse/RT2-2025)
/diagnostics contents and publishing rate was checked by following procedure.
```
~/autoware$ ros2 run autoware_imu_corrector gyro_bias_estimator_node --ros-args -r /gyro_bias_validator/input/imu_raw:=/sensing/imu/tamagawa/imu_raw -r /gyro_bias_validator/input/odom:=/localization/kinematic_state --params-file sensing/autoware_imu_corrector/config/gyro_bias_estimator.param.yaml …
```

fix(imu_corrector): remove non-periodic publish to /diagnostics topic

---

planning/autoware_obstacle_stop_planner/test/test_autoware_obstacle_stop_planner_node_interface.cpp
planning/autoware_planning_test_manager/include/autoware_planning_test_manager/autoware_planning_test_manager.hpp
planning/autoware_planning_test_manager/package.xml
planning/autoware_planning_test_manager/src/autoware_planning_test_manager.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_virtual_traffic_light_module/test/test_node_interface.cpp

VirtualTrafficLightState and ExpandStopRange are very specific message types for the planner package (behavior_velocity_virtual_traffic_light and obstacle_stop_planner respectively).
Currently, the autoware_planning_test_manager package, which is a common package,  depends on these specific messages, which is unexpected.
This PR removed the dependency by moving the code from the autoware_planning_test_manager package to the specific planner package.
unit test passed.
None.
None.
None.

feat(autoware_planning_test_manager): remove dependency of VirtualTrafficLightState and ExpandStopRange

---

common/autoware_test_utils/package.xml
planning/autoware_planning_test_manager/include/autoware_planning_test_manager/autoware_planning_test_manager.hpp
planning/autoware_planning_test_manager/package.xml
planning/autoware_planning_test_manager/src/autoware_planning_test_manager.cpp
planning/behavior_path_planner/autoware_behavior_path_planner/src/test_utils.cpp

depends on https://github.com/autowarefoundation/autoware.universe/pull/9963
LateralOffset is a very specific message type for the behavior_path_side_shift_module/behavior_path_planner packages.
Currently, the autoware_planning_test_manager package, which is a common package, depends on this specific message, which is unexpected.
This PR removed the dependency by moving the code from the autoware_planning_test_manager package to the specific planner package.
Unit test passed.
None.
None.
None.

feat(autoware_planning_test_manager): remove dependency of tier4_planning_msgs::msg::LateralOffset

---

system/dummy_diag_publisher/include/dummy_diag_publisher/dummy_diag_publisher_core.hpp
system/dummy_diag_publisher/package.xml
system/dummy_diag_publisher/src/dummy_diag_publisher_core.cpp

This PR adds param set function as described in the README and refactor slightly.
- add `param_callback_handle_` and `onSetParams`.
- delete unnecessary dependency packages.
- add `const`.
- [TIRE IV internal link](https://star4.slack.com/archives/C0657FNJ5EG/p1734588501562049)
1. `$ ros2 launch dummy_diag_publisher dummy_diag_publisher.launch.xml `
2. `$ ros2 param set /dummy_diag_publisher dummy_diag_empty.is_active true` or `false`
3. `$ ros2 param set /dummy_diag_publisher dummy_diag_empty.status "Error"`, `Warn`, `OK`
4. confirm by `ros2 topic echo /diagnostics` or rqt_runtime_monitor
[Screencast from 2025年01月18日 11時49分20秒.webm](https://github.com/user-attachments/assets/f905ff0d-804a-49d1-a372-39a4bfe5e27f)
(in addition)
1. `$ ros2 launch autoware_launch …

feat(dummy_diag_publisher): update param setting

---

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/README.md

Revising and adding description to object filtering
- Link
None.
None.
None.

docs(lane_change): object filtering description

---

planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/include/autoware/behavior_velocity_crosswalk_module/util.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/debug.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp

1. add pass marker 
2. suppress frequent message
https://github.com/autowarefoundation/autoware.universe/pull/9940
- Link
None.
None.
None.

feat(crosswalk): add pass marker

---

planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp

This PR port the same direction ignore block to set CollisionState::IGNORE properly
feature PR: https://github.com/autowarefoundation/autoware.universe/pull/5849
- Link
None.
None.
None.

chore(crosswalk): port the same direction ignore block

---

planning/sampling_based_planner/autoware_path_sampler/package.xml

…es planning/sampling_based_planner
- Link
None.
None.
None.

feat(sampling_based_planner)!: tier4_debug_msgs changed to autoware_internal_debug_msgs in sampling_based_planner

---

launch/tier4_perception_launch/launch/object_recognition/detection/detector/camera_lidar_detector.launch.xml

- To avoid duplication of `roi_pointcloud_fusion` and `roi_cluster_fusion` on unknown objects
- Roi_based_cluster pipeline
|---|---|
|![image](https://github.com/user-attachments/assets/b8a3f209-ccab-4144-9ae5-0f187e8e27cc) |![image](https://github.com/user-attachments/assets/e13d0045-6f3d-4b72-8df8-422bc6135eaf) |
- Link
- Run `logging_simulator` with diffrent options of 'use_roi_based_cluster and `use_low_intensity_cluster_filter` and confirmed that perception model output predict/objects as disired.
- `use_roi_based_cluster:=true`, `use_low_intensity_cluster_filter:=true`:
- `use_roi_based_cluster:=true`, `use_low_intensity_cluster_filter:=false`:
- `use_roi_based_cluster:=false`, `use_low_intensity_cluster_filter:=false`:
- …

fix(tier4_perception_launch): rearrange roi based cluster pipeline

---

planning/autoware_obstacle_stop_planner/package.xml
planning/autoware_obstacle_stop_planner/src/adaptive_cruise_control.cpp
planning/autoware_obstacle_stop_planner/src/adaptive_cruise_control.hpp
planning/autoware_obstacle_stop_planner/src/debug_marker.hpp
planning/autoware_obstacle_stop_planner/src/node.hpp

…es planning/autoware_obstacle_stop_planner
- Link
None.
None.
None.

feat(autoware_obstacle_stop_planner)!: tier4_debug_msgs changed to autoware_internal_debug_msgs in autoware_obstacle_stop_planner

---

planning/autoware_obstacle_cruise_planner/include/autoware/obstacle_cruise_planner/pid_based_planner/cruise_planning_debug_info.hpp
planning/autoware_obstacle_cruise_planner/include/autoware/obstacle_cruise_planner/stop_planning_debug_info.hpp
planning/autoware_obstacle_cruise_planner/include/autoware/obstacle_cruise_planner/type_alias.hpp
planning/autoware_obstacle_cruise_planner/package.xml

…es planning/autoware_obstacle_cruise_planner
- Link
None.
None.
None.

feat(autoware_obstacle_cruise_planner)!: tier4_debug_msgs changed to autoware_internal_debug_msgs in autoware_obstacle_cruise_planner

---

planning/autoware_path_optimizer/include/autoware/path_optimizer/type_alias.hpp
planning/autoware_path_optimizer/package.xml
planning/autoware_path_optimizer/scripts/calculation_time_plotter.py

…es planning/autoware_path_optimizer
- Link
None.
None.
None.

feat(autoware_path_optimizer)!: tier4_debug_msgs changed to autoware-internal_debug_msgs in autoware_path_optimizer

---

control/autoware_pure_pursuit/include/autoware/pure_pursuit/autoware_pure_pursuit_lateral_controller.hpp
control/autoware_pure_pursuit/package.xml
control/autoware_pure_pursuit/src/autoware_pure_pursuit/autoware_pure_pursuit_lateral_controller.cpp

…es control/autoware_pure_pursuit
- Link
None.
None.
None.

feat(autoware_pure_pursuit)!: tier4_debug_msgs changed to autoware_internal_debug_msgs in autoware_pure_pursuit

---

planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp

Change the time to judge the pedestrian's unwillingness to cross because he/she does not walk even the ego is yielding. 
Before: the time when the pedestrian is stopped
After: the time when both of the pedestrian and the ego are stopped
[Screencast from 2025年01月20日 19時08分40秒.webm](https://github.com/user-attachments/assets/e023a292-bad5-445d-8c0d-3d9e9c6ecf1a)
- Link
None.
None.
None.

feat(crosswalk): update judgle time against the stopped objects

---

common/autoware_goal_distance_calculator/Readme.md
common/autoware_goal_distance_calculator/include/autoware/goal_distance_calculator/goal_distance_calculator_node.hpp
common/autoware_goal_distance_calculator/package.xml
common/autoware_goal_distance_calculator/src/goal_distance_calculator_node.cpp

I have changed the tier4_debug_msgs to autoware_internal_debug_msgs by package 
None.
None.
None.

feat(autoware_goal_distance_calculator)!:  tier4_debug_msgs to autoware_internal_debug_msgs for autoware_goal_distance_calculator

---

launch/tier4_system_launch/launch/system.launch.xml

This PR replace dummy_diag_publisher to autoware_diag_publisher.
**Other PR**
https://github.com/TetsuKawa/autoware.universe/tree/test/add-autoware-prefix-to-dummy-diag-publisher , which merged this branch and https://github.com/autowarefoundation/autoware.universe/pull/9946, was testd.
1. ``$ ros2 launch autoware_launch planning_simulator.launch.xml map_path:=$HOME/autoware_map/sample-map-planning vehicle_model:=sample_vehicle sensor_model:=sample_sensor_kit``
2. ros2 node list | grep dummy_diag_publisher
3. `$ ros2 param set /dummy_diag_publisher "topic_state_monitor_pointcloud_map: map_topic_status".is_active true` or `false`
4. `$ ros2 param set /dummy_diag_publisher "topic_state_monitor_pointcloud_map: map_topic_status".status "Error"`, `Warn` or `OK`
[Screencast from 2025年01月18日 …

fix(tier4_system_launch): add autoware prefix to dummy diag publisher launcher

---

control/autoware_vehicle_cmd_gate/package.xml
control/autoware_vehicle_cmd_gate/src/vehicle_cmd_gate.cpp
control/autoware_vehicle_cmd_gate/src/vehicle_cmd_gate.hpp

feat(autoware_vehicle_cmd_gate)!: tier4-debug_msgs changed to autoware_internal_debug_msgs in autoware_vehicle_cmd_gate

---

planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/debug.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection.hpp

visualize "too late to stop" text if it turned out dangerous because of late detection
- Link
visualization 
None.
None.
None.

feat(intersection): add wall marker for too late detect objects

---

perception/autoware_detected_object_validation/CMakeLists.txt
perception/autoware_detected_object_validation/config/object_lanelet_filter.param.yaml
perception/autoware_detected_object_validation/object-lanelet-filter.md
perception/autoware_detected_object_validation/schema/object_lanelet_filter.schema.json
perception/autoware_detected_object_validation/src/lanelet_filter/lanelet_filter.cpp
perception/autoware_detected_object_validation/src/lanelet_filter/lanelet_filter.hpp
perception/autoware_detected_object_validation/test/lanelet_filter/test_lanelet_filter.cpp
perception/autoware_detected_object_validation/test/test_lanelet_utils.hpp

Add height filter in lanelet filter.
This filter is based on z axis comparison between ego base_link and not considering lanelet slope.
I think we should use lane information for future, but currently it will be helpful in some feature such as radar filter.
- Link
Add node test. You can test it with 
```
colcon test --packages-select autoware_detected_object_validation --event-handlers console_direct
+ --return-code-on-test-failure
```
Test case is like following:
sorry I had typo:
- `filtered` means the objects will be remained
- `remained` means the objects will be filtered out 
None.
None.
None.

feat(autoware_detected_object_validation): add height filter in lanelet filtering

---

launch/tier4_perception_launch/launch/perception.launch.xml
launch/tier4_simulator_launch/launch/simulator.launch.xml
launch/tier4_system_launch/launch/system.launch.xml

This PR fixes the missing changes for the following PRs made by me. Sorry for bothering you due to the bug, ... .
- https://github.com/autowarefoundation/autoware.universe/pull/9956
- https://github.com/autowarefoundation/autoware.universe/pull/9970
**The tests are ongoing.**
Module level tests are performed in the following PRs (same as above).
- https://github.com/autowarefoundation/autoware.universe/pull/9956
- https://github.com/autowarefoundation/autoware.universe/pull/9970
I'm now investigating if there is no any missing fixes by using following command.
```
grep -R perception_online_evaluator ./
grep -R duplicated_node_checker ./
```
None.
Launching the Autoware nodes via `tier4_perception_launch` and `tier4_system_launch` will succeed.

fix(launch): fix missing changes for launch

---

planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/interface/scene_module_interface.hpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/path_safety_checker/safety_check.hpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_safety_checker/safety_check.cpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/scene.hpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp

Calculate and output safety factor for `static_obstacle_avdoiance` module. This information can be visualized by PlaningFactorRvizPlugin which was merged in https://github.com/autowarefoundation/autoware.universe/pull/9999.
- https://github.com/autowarefoundation/autoware.universe/pull/9999
None.
None.
None.

feat(static_obstacle_avoidance): output safety factor

---

perception/autoware_tracking_object_merger/src/decorative_tracker_merger_node.cpp

…es  perception/autoware_tracking_object_merger
Test are done in the following TIER IV internal evaluator:
https://evaluation.ci.tier4.jp/evaluation/reports/bfc0e074-207b-5ece-83e5-fb769f6f7272?project_id=prd_jt
https://evaluation.ci.tier4.jp/evaluation/reports/4df9332b-024e-5907-ada9-fbbcb8c20b3d?project_id=prd_jt
https://evaluation.ci.tier4.jp/evaluation/reports/ce1a0892-d8aa-5729-b25d-6d2d57bea034?project_id=prd_jt
None.
|  Topic Type      | Topic Name        | Old Message Type | New Message Type        | …

feat(autoware_tracking_object_merger)!: tier4_debug_msgs changed to autoware_internal_debug_msgs in autoware_tracking_object_merger

---

perception/autoware_traffic_light_fine_detector/README.md
perception/autoware_traffic_light_fine_detector/package.xml
perception/autoware_traffic_light_fine_detector/src/traffic_light_fine_detector_node.cpp
perception/autoware_traffic_light_fine_detector/src/traffic_light_fine_detector_node.hpp

…es traffic_light_fine_detector
Test are done in the following TIER IV internal evaluator:
https://evaluation.ci.tier4.jp/evaluation/reports/bfc0e074-207b-5ece-83e5-fb769f6f7272?project_id=prd_jt
https://evaluation.ci.tier4.jp/evaluation/reports/4df9332b-024e-5907-ada9-fbbcb8c20b3d?project_id=prd_jt
https://evaluation.ci.tier4.jp/evaluation/reports/ce1a0892-d8aa-5729-b25d-6d2d57bea034?project_id=prd_jt
None.
| Version | Topic Type      | Topic Name        | Message Type              |
|:--------|:----------------|:------------------|:--------------------|
| Old     | Pub | …

feat(traffic_light_fine_detector)!: tier4_debug_msgs changed to autoware_internal_debug_msgs in traffic_light_fine_detector

---

perception/autoware_tensorrt_yolox/package.xml
perception/autoware_tensorrt_yolox/src/tensorrt_yolox_node.cpp

Test are done in the following TIER IV internal evaluator:
https://evaluation.ci.tier4.jp/evaluation/reports/bfc0e074-207b-5ece-83e5-fb769f6f7272?project_id=prd_jt
https://evaluation.ci.tier4.jp/evaluation/reports/4df9332b-024e-5907-ada9-fbbcb8c20b3d?project_id=prd_jt
https://evaluation.ci.tier4.jp/evaluation/reports/ce1a0892-d8aa-5729-b25d-6d2d57bea034?project_id=prd_jt
https://github.com/autowarefoundation/autoware.universe/pull/9898#issuecomment-2608947790
None.
|  Topic Type      | Topic Name        | Old Message Type | New Message Type        | …

feat(autoware_tensorrt_yolox)!: tier4_debug_msgs changed to autoware_internal_debug_msgs in autoware_tensorrt_yolox

---

perception/autoware_image_projection_based_fusion/package.xml
perception/autoware_image_projection_based_fusion/src/fusion_node.cpp

…es perception/autoware_image_projection_based_fusion
Test are done in the following TIER IV internal evaluator:
https://evaluation.ci.tier4.jp/evaluation/reports/bfc0e074-207b-5ece-83e5-fb769f6f7272?project_id=prd_jt
https://evaluation.ci.tier4.jp/evaluation/reports/4df9332b-024e-5907-ada9-fbbcb8c20b3d?project_id=prd_jt
https://evaluation.ci.tier4.jp/evaluation/reports/ce1a0892-d8aa-5729-b25d-6d2d57bea034?project_id=prd_jt
AWSIM Test: https://github.com/autowarefoundation/autoware.universe/pull/9877#issuecomment-2608910505
None.
|  Topic Type      | Topic Name        | Old Message Type …

feat(autoware_image_projection_based_fusion)!: tier4_debug-msgs changed to autoware_internal_debug_msgs in autoware_image_projection_based_fusion

---

evaluator/autoware_control_evaluator/include/autoware/control_evaluator/control_evaluator_node.hpp
evaluator/autoware_control_evaluator/include/autoware/control_evaluator/metrics/metric.hpp
evaluator/autoware_control_evaluator/include/autoware/control_evaluator/metrics/metrics_utils.hpp
evaluator/autoware_control_evaluator/launch/control_evaluator.launch.xml
evaluator/autoware_control_evaluator/package.xml
evaluator/autoware_control_evaluator/src/control_evaluator_node.cpp

- Add the metrics `steering_angle`, `steering_rate`, and `steering_acceleration`, which take info from `/vehicle/status/steering_status` as inputs.
```
{Metric::steering_angle, "Steering angle[rad]"},
{Metric::steering_rate, "Steering angle rate[rad/s]"},
{Metric::steering_acceleration, "Steering angle acceleration[rad/s^2]"},
```
- By the new metrics, I observed that steering_acc is very unstable, possibly due to a potential problem with the controller not limiting it.
- Here is a sample in Psim with statistics. [Uploading Screencast from 2025年01月22日 17時58分10秒.webm…]()
- statistic results:
```json
{
"goal_lateral_deviation/count": 4066,
"goal_lateral_deviation/description": "Lateral deviation from the goal point[m]",
"goal_lateral_deviation/max": 71.57552209610769, …
```

feat(autoware_control_evaluator): add new steering metrics

---

launch/tier4_simulator_launch/launch/simulator.launch.xml

Fixes a wrong package name bug.
Now the test is ongoing on the evaluator as [this](https://evaluation.tier4.jp/evaluation/reports/0deef618-22c5-51ec-9492-f23f17aa19dd?project_id=prd_jt).

fix(tier4_simulator_launch): fix a wrong package name: `fault_injection` => `autoware_fault_injection` 

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/util.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/util.cpp

move some functions as utility function 
for minimizing diff for this PR https://github.com/autowarefoundation/autoware.universe/pull/10005
- Link
https://evaluation.tier4.jp/evaluation/reports/aea0f58b-8b1b-5001-9025-f043b4902dd3?project_id=prd_jt
None.
None.
None.

refactor(goal_planner): divide extract_dynamic_object/is_goal_in_lanes util function

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp

due to  https://github.com/autowarefoundation/autoware.universe/pull/9829, the waiting approval path is cut to original goal, but this is intended for ARC_BACKWARD.
when using ARC_BACKWARD, the start pose of parking is after goal pose, so the path should be generated to the start pose
before
stuck with arc_backward
after
works with arc_backward
no problem with shift too
- Link
psim
2025/01/24 https://evaluation.tier4.jp/evaluation/reports/bfe6f4b8-3f63-5172-aa67-3f143be862fe/?project_id=prd_jt
2025/01/24 https://evaluation.tier4.jp/evaluation/reports/ea06eaa1-6799-57a1-8092-42af4ffcd901/?project_id=prd_jt
2025/01/25 https://evaluation.tier4.jp/evaluation/reports/613f7ab0-7524-5f50-ab18-e6ef11d26fd0/?project_id=prd_jt
None.
None.
None.

fix(goal_planner): fix waiting approval path of backward parking

---

planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/docs/ttc_vs_ttv.svg

fix rebase miss in https://github.com/autowarefoundation/autoware.universe/pull/10025
- Link
None.
None.
None.

docs(crosswalk): fix file add miss

---

planning/behavior_path_planner/autoware_behavior_path_planner/include/autoware/behavior_path_planner/behavior_path_planner_node.hpp
planning/behavior_path_planner/autoware_behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/interface/scene_module_visitor.hpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/src/interface/scene_module_visitor.cpp
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/include/autoware/behavior_path_start_planner_module/data_structs.hpp
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/include/autoware/behavior_path_start_planner_module/start_planner_module.hpp
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/start_planner_module.cpp

This PR adds a debug publisher and a structured table for the start planner's evaluation results. 
- Added a debug publisher to output a string table for evaluation results.   
- Reorganized the debug output so that all candidate evaluations and p are consolidated into a single table, reducing console output.  
- Link
run planning_simulator
plugin name: autoware_string_stamped_rviz_plugin
topic name: `/planning/scenario_planning/lane_driving/behavior_planning/behavior_path_planner/debug/start_planner_evaluation_table/start_planner_evaluation_table`
The path generation is executed from top to bottom. When a path generation fails, the reason (such as lane departure or collision) is written in the cell. When it succeeds, "success" is displayed and trajectory serch is …

feat(start_planner): visualize planner evaluation table in rviz

---

simulator/autoware_simple_planning_simulator/include/autoware/simple_planning_simulator/vehicle_model/sim_model_delay_steer_vel.hpp
simulator/autoware_simple_planning_simulator/src/simple_planning_simulator/vehicle_model/sim_model_delay_steer_vel.cpp

Currently, the **vel input** control is used to calculate the acc state. However, the input values can fluctuate, sometimes resulting in a large acc state.
In this PR, I’ve changed the calculation method so that the acc state is now based on the **vel state**, which is computed using a first-order lag filter.
before 
after
https://tier4.atlassian.net/browse/RT1-9039
- Link
- print the acc value in scenario simulator v2
- 96/98([2025/01/14](https://evaluation.tier4.jp/evaluation/reports/948cae29-225e-5196-84f2-7219c4002e76/?project_id=prd_jt)) -> 64/98([2025/01/15](https://evaluation.tier4.jp/evaluation/reports/ba6e34c5-38d5-55c9-9bc3-a75f91218c80/?project_id=prd_jt)) (degraded!! introduce acc fail condition) -> 
96/98 …

feat(simple_planning_simulator): change acc state calculation of SimModelDelaySteerVel

---

planning/autoware_path_optimizer/src/utils/geometry_utils.cpp

Below code can cause zero division because the vector is zero.
https://github.com/autowarefoundation/autoware.universe/blob/fc763acd1f1cdcda1358976a963da5f367e61bb6/planning/autoware_path_optimizer/src/utils/geometry_utils.cpp#L53-L54
- Link
- https://evaluation.tier4.jp/evaluation/reports/cf85a61a-237c-578c-b86f-87bf1e884e2b?project_id=prd_jt&state=failed
All fail cases are from simulator
None.
None.
None.

fix(path_optimizer): fix possible zero division

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_module.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp

make parameters and other related member variables const
NOTE: parameter update is disabled.
- Link
None.
None.
None.

refactor(goal_planner): make parameters const

---

planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/start_planner_module.cpp

Output safety factor with object_of_interest information for start_planner module output.  
This information can be visualized by PlaningFactorRvizPlugin which was merged in https://github.com/autowarefoundation/autoware.universe/pull/9999.
- Link
run psim and confimred markers are visualized for objects that act as stopping factors.
None.
None.
None.

feat(start_planner): output object_of_interest 

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_module.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_searcher.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_searcher_base.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/thread_data.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_searcher.cpp

enable bus_stop_area goal search and bezier search if `use_bus_stop_area =  true` and the goal position is inside a bus stop area
- https://evaluation.tier4.jp/evaluation/reports/f5639bb5-d83a-5bf1-99b3-9b293abff95f?project_id=prd_jt
- 
- Link
None.
None.
None.

fix(goal_planner): check usage of bus_stop_area by goal_pose

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp

fix contaminated rebase miss in https://github.com/autowarefoundation/autoware.universe/pull/10049
- Link
None.
None.
None.

fix(goal_planner): fix goal_searcher assert

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/config/goal_planner.param.yaml
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_parameters.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/decision_state.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_searcher.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/manager.cpp

depends: https://github.com/autowarefoundation/autoware.universe/pull/10049
launcher PR: https://github.com/autowarefoundation/autoware_launch/pull/1318
https://tier4.atlassian.net/browse/RT1-6895
- https://evaluation.tier4.jp/evaluation/reports/8e03bb7d-df42-5616-927c-cd4b52faaffa?project_id=prd_jt&state=failed
- 
None.
None.
None.

refactor(goal_planner): remove use_object_recognition because it is default

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/README.md
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/decision_state.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/manager.cpp

goal_planner never works without PredictedObject, so enable_safety_check is treated as true.
depends https://github.com/autowarefoundation/autoware.universe/pull/10050
- Link
Psim works
None.
None.
None.

refactor(goal_planner): remove enable_safety_check because it is default

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/decision_state.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/decision_state.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp

goal_planner sends `updateRTCStatus` if it was able to find a stable safe path from the generated candidates (DECIDED status), and before `updateRTCStatus` `isActivated()` is null because goal_planner RTC entry itself does not exist. And after `updateRTCStatus` goal_planner RTC entry begins to exist but it remains DECIDED forever, so `isActivated()` in `transit_state` does not make sense at all by definition.
depends https://github.com/autowarefoundation/autoware.universe/pull/10052
- Link
- https://evaluation.tier4.jp/evaluation/reports/f5b3c49c-2065-53bb-b091-5e4261a9a83c?project_id=prd_jt
None.
None.
None.

feat(goal_planner): do not use isActivated() in deciding state transition

---

planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/README.md
planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/config/traffic_light.param.yaml
planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/manager.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/scene.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/scene.hpp

To address the issue in the traffic_light module where the vehicle abruptly stops the moment the light changes from amber to green without performing a pass judge when the speed is below 2.0 m/s, we will adjust the speed threshold.
At the same time, the threshold for performing pass judge has been parameterized, considering potential requests to adjust it.
[TIERIV internal link] https://tier4.atlassian.net/browse/RT0-33895
We confirmed an improvement in the sudden deceleration behavior using the rosbag-based logging_simulator, where sudden deceleration had previously been occurring.
None.
None.
Improvements:
Enables pass judge to be applied even at low speeds (1.0 ~ 2.0 m/s), preventing unnecessary stops when the light changes from amber to green.
Ensures smoother driving and reduces …

feat(autoware_behavior_velocity_traffic_light_module): adjust velocity threshold for ensure stop at yellow light

---

map/autoware_map_height_fitter/CMakeLists.txt

This package fails to build with the autoware_utils 1.1.0.
(This package depends on autoware_utils via autoware_lanelet2_extension)
Since autoware_utils is now depending on pcl as well, it overwrites some of PCL related CMAKE variables.
In order to only import intended modules, PCL should be included after calling autoware_package().
- https://github.com/autowarefoundation/autoware/pull/5700
* checkout 1.1.0 for autoware_utils
* build autoware
I have tested locally that the build passes without an error.
None.
None.
None.

fix(autoware_map_height_fitter): find PCL package after autoware_package() is called

---

launch/tier4_perception_launch/launch/traffic_light_recognition/traffic_light.launch.xml

This PR add the lacked params caused by https://github.com/autowarefoundation/autoware.universe/pull/9994
- Link
I have checked DLRv2 in local pc
None.
None.
None.

fix(traffic_light.launch.xml): add lacked params

---

sensing/autoware_radar_tracks_noise_filter/launch/radar_tracks_noise_filter.launch.xml

This PR fix the syntax error in launch file caused by https://github.com/autowarefoundation/autoware.universe/pull/9992.
- Link
```ros2 launch autoware_radar_tracks_noise_filter radar_tracks_noise_filter.launch.xml```
and
```ros2 launch autoware_launch logging_simulator.launch.xml sensing:=true ...```
None.
None.
None.

fix(radar_tracks_noise_filter): fix launch file

---

common/autoware_universe_utils/test/src/math/test_trigonometry.cpp

PR #9710 made the random numbers used in the `trigonometry_opencv_fast_atan2` test _random_, but introduced made the test non-reproducible. 
The common wisdom is to initialize all random number generators used in unit tests with a fixed seed, so the same numbers are generated across test runs.
This PR does that for the abovementioned test.
- #9710 
Printing x/y similar to #9710. Note how before this PR, the values change across runs, whereas with this PR they stay constant (reproducible).
Before:
```
x=-7.54321    y=1.59532
x=-1.60106    y=-9.32045
x=2.97877     y=-3.35861
x=-1.19224    y=8.64908
x=-0.808514   y=-0.856808
x=5.27276     y=5.93498
```
After: 
```
x=6.29447     y=-7.29046
x=8.11584     y=6.70017
x=-7.46026    y=9.37736
x=6.29447     y=-7.29046
x=8.11584     y=6.70017 …
```

test(autoware_universe_utils): make opencv_fast_atan2 test reproducible

---

planning/motion_velocity_planner/autoware_motion_velocity_planner_common_universe/package.xml
planning/motion_velocity_planner/autoware_motion_velocity_planner_common_universe/src/utils.cpp

The calculation of calc_possible_min_dist_from_obj_to_traj_poly was wrong, and this PR fixed the issue.
planning simulator & scenario tests
None.
None.
None.

fix(motion_velocity_planner_common): fix the calc_possible_min_dist_from_obj_to_traj_poly calculation

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp

depends https://github.com/autowarefoundation/autoware.universe/pull/10066
- Link
- https://evaluation.tier4.jp/evaluation/reports/fbca7ff2-c6a7-5a1f-93c8-b5af843a1c63?project_id=prd_jt
4 failed cases are caused by `undefined reference to...`, so they are ignorable
None.
None.
None.

refactor(goal_planner): fix updateData continuation condition

---

perception/autoware_probabilistic_occupancy_grid_map/include/autoware/probabilistic_occupancy_grid_map/costmap_2d/occupancy_grid_map_base.hpp
perception/autoware_probabilistic_occupancy_grid_map/include/autoware/probabilistic_occupancy_grid_map/utils/cuda_pointcloud.hpp
perception/autoware_probabilistic_occupancy_grid_map/lib/costmap_2d/occupancy_grid_map_base.cpp
perception/autoware_probabilistic_occupancy_grid_map/lib/costmap_2d/occupancy_grid_map_fixed.cpp
perception/autoware_probabilistic_occupancy_grid_map/lib/updater/binary_bayes_filter_updater.cpp
perception/autoware_probabilistic_occupancy_grid_map/lib/updater/log_odds_bayes_filter_updater.cpp
perception/autoware_probabilistic_occupancy_grid_map/src/pointcloud_based_occupancy_grid_map/pointcloud_based_occupancy_grid_map_node.cpp
perception/autoware_probabilistic_occupancy_grid_map/src/pointcloud_based_occupancy_grid_map/pointcloud_based_occupancy_grid_map_node.hpp

Through a better use of the data and streams, this PR decreases the processing time from 8ms to 4ms when using the full concatenated pointcloud
- Link
None.
None.
None.

feat(autoware_probabilistic_occupancy_grid_map): improved data handling on the ogm

---

planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/drivable_area_expansion/static_drivable_area.cpp

improve the `getOverlappedLaneletId` to early return
- Link
- https://evaluation.tier4.jp/evaluation/reports/41d4c96b-2121-5d10-8f17-dff2701358d2?project_id=prd_jt
None.
None.
None.

perf(behavior_path_planner): improve getOverlappedLaneletId

---

perception/autoware_traffic_light_selector/src/traffic_light_selector_node.cpp
perception/autoware_traffic_light_selector/src/traffic_light_selector_node.hpp

add camera_info into message_filter.
If we do not add it, have to handle with mutex to be thread safe. And subscribe topics have same timestamp, So It is efficienfy to subscribe together.
- Link
I checked this PR on my local PC and merging below PR.
- https://github.com/autowarefoundation/autoware.universe/pull/9731
- https://github.com/autowarefoundation/autoware_launch/pull/1310
None.
None.
None.

fix(autoware_traffic_light_selector): add camera_info into message_filter

---

launch/tier4_perception_launch/launch/obstacle_segmentation/ground_segmentation/ground_segmentation.launch.py
launch/tier4_perception_launch/launch/perception.launch.xml

set pipeline junction parameter `use_single_frame_filter` and `use_time_series_filter`, set proper input topic name for the Occupancy grid map module
https://github.com/autowarefoundation/autoware_launch/pull/1327
- Link 
tested in a local environment with logging-simulator.
option combinations of (use_single_frame_filter=false, use_time_series_filter= false), ( use_single_frame_filter=false, use_time_series_filter=true)
When use_single_frame_filter is true, elevation map is needed. However, it is too heavy in large scale maps, and could not be tested.
None.
Parameter change
use_time_series_filter -> use_obstacle_segmentation_time_series_filter
use_single_frame_filter -> use_obstacle_segmentation_single_frame_filter
the parameters moved from config file in the …

fix(ground_segmentation): bring junction parameter from param file to launch argument 

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_searcher.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_searcher.cpp

While planPullOverAsCandidate with before DECIDED status, ensure goal_planner to insert stop pose anyway even if there are not path candidates (therefore no closest_start_pose).
https://github.com/user-attachments/assets/9c845a42-4de9-4191-b538-b6aefb30b2a9
- https://tier4.atlassian.net/browse/RT0-32952
- Link
- https://evaluation.tier4.jp/evaluation/reports/b3bc1f54-6d3c-5ff4-adcd-a39ba42ac3d3?project_id=prd_jt
None.
None.
None.

feat(goal_planner): ensure stop while path candidates are empty

---

perception/autoware_probabilistic_occupancy_grid_map/lib/updater/binary_bayes_filter_updater.cpp

As per the title :bow: 
Addressed [TIER IV INTERNAL LINK](https://star4.slack.com/archives/C076ZGRC15X/p1739320384217569)
- Link
None.
None.
None.

chore(autoware_probabilistic_occupancy_grid_map): fixed cuda use on non-cuda settings

---

perception/autoware_image_projection_based_fusion/src/pointpainting_fusion/node.cpp

Before
In [this line](https://github.com/tier4/autoware.universe/blob/79dc610ee36432aa6ad4522376a7561fec27d908/perception/image_projection_based_fusion/src/pointpainting_fusion/node.cpp#L239), the point cloud filtering process for out-of-range points increments output variables (such as "iter_painted_x") at the same time as "iter_x".
However, in the following process, these output variables are used until "j", which is the size of points within the range.
As a result, data is stored at indices beyond "j", leading to incorrect index access.
After
I modified the timing of the increments for "iter_painted_x" so that points within the range are stored correctly until "j".
- Link
[TIER IV INTERNAL LINK](https://star4.slack.com/archives/C076ZGRC15X/p1739289211379129?thread_ts=1 …

fix(autoware_image_projection_based_fusion): modify incorrect index access in pointcloud filtering for out-of-range points

---

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/path.cpp

fix lane change end pose not connected to goal when frenet planner is used
- [feat(lane_change): improve the calculation of the target lateral velocity in Frenet frame #10078](https://github.com/autowarefoundation/autoware.universe/pull/10078)
None.
None.
None.

fix(lane_change): fix end pose not connected to goal (RT1-9247)

---

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/path.cpp

This PR makes the lane change paths generated in Frenet frame smoother.
The previous calculation did not work as expected, and the new calculation simply assumes a constant acceleration over the whole lane change duration, starting from a 0 lateral velocity and targeting some positive lateral velocity calculated as the lateral distance to travel divided by the lane change duration.
|--------|--------|
| ![lc1](https://github.com/user-attachments/assets/b207bbbc-bfad-4034-b414-16eb6df93bce) | ![lc_fixed1](https://github.com/user-attachments/assets/2c868234-5148-43cf-9240-779671f88f3a) |
|![lc2](https://github.com/user-attachments/assets/eda9b86f-383f-4205-8fe7-e12261f9be2d)  | ![lc_fixed2](https://github.com/user-attachments/assets/1994dc57-7cf0-422a-b927-d1ec60f73647) …

feat(lane_change): improve the calculation of the target lateral velocity in Frenet frame

---

planning/autoware_route_handler/src/route_handler.cpp

Previously, to identify whether the lanelet is the same or not, we compare the address. But what we want to compare is not the address, but the lanelet id. So I fix it inside the `exists` function.
- Link
None.
None.
None.

fix(autoware_route_handler): fix a bug of route_handler

---

planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/package.xml

Remove the unnecessary dependency of motion_velocity_obstacle_stop_module
- Link
None.
None.
None.

chore(motion_velocity_obstacle_stop_module): remove unnecessary dependency

---

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp

This PR removes the unnecessary string literal around `__func__` in the stop_watch_.toc() call which causes an exception. 
String literals around __func__ in stop_watch_.toc() cause an exception, which leads to the ego vehicle getting stuck, even when the path is safe.
**Before:**
[Simulation-Before](https://youtu.be/aQGI6OZZit8)
**After:**
[Simulation-After](https://youtu.be/OgNysYXzH08)
None.
None.
None.

fix(lane_change): remove string literals from stopwatch toc

---

planning/motion_velocity_planner/autoware_motion_velocity_planner_node_universe/package.xml

fix `grid_map_core/eigen_plugins/FunctorsPlugin.hpp: No such file or directory` by recent apt updates
- Link
build passes on local
None.
None.
None.

chore(motion_velocity_planner_universe): fix build depends

---

mkdocs.yaml

**Resolves:**
- https://github.com/autowarefoundation/autoware.universe/issues/10126
**Co-PR:**
- https://github.com/autowarefoundation/sync-file-templates/pull/30
Related:
- [Prefix packages with autoware_ #4097](https://github.com/orgs/autowarefoundation/discussions/4097#discussioncomment-10260260)
- https://squidfunk.github.io/mkdocs-material/plugins/search/#config.separator
Follow: https://autowarefoundation.github.io/autoware-documentation/main/contributing/documentation-guidelines/#2-running-an-mkdocs-server-in-your-local-environment
1. `cd`  into autoware.universe folder
2. `python3 -m pip install -U $(curl -fsSL https://raw.githubusercontent.com/autowarefoundation/autoware-github-actions/main/deploy-docs/mkdocs-requirements.txt)`
3. `mkdocs serve`
I will also update the origin of …

feat(mkdocs.yaml): update the separator characters

---

sensing/autoware_pointcloud_preprocessor/schema/pickup_based_voxel_grid_downsample_filter_node.schema.json
sensing/autoware_pointcloud_preprocessor/src/downsample_filter/pickup_based_voxel_grid_downsample_filter_node.cpp

Fix crash in the `PickupBasedVoxelGridDownsampleFilterComponent` when processing empty point cloud data.
Additionally, add 0 validation
This PR includes
- Added early return for empty point cloud input to prevent potential memory access violations
- Added validation for voxel size parameters that shuts down the node if invalid values (≤ 0) are detected
We have encountered the following issue:
```
1739414563.6835113 [ERROR] [component_container_mt-1]: process has died [pid 440086, exit code -8, cmd '/home/autoware/pilot-auto.xx1/install/rclcpp_components/lib/rclcpp_components/component_container_mt --ros-args -r __node:=pointcloud_container -r __ns:=/ -p use_sim_time:=False -p wheel_radius:=0.31 -p wheel_width:=0.18 -p wheel_base:=2.75 -p wheel_tread:=1.485 -p front_overhang:=0.8 -p …
```

fix(autoware_pointcloud_preprocessor): empty input validation

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/geometric_pull_over.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/shift_pull_over.cpp

currently the parking path point interval  for lane departure check is `center_line_path_interval: 1.0`
depending on resampled points sometimes departure can not be detected especialy cureve lane.
(footrpint in this image is not the exact path used for lane departure check. this is behavior path output.)
this is just workaround but in this PR, resample path interval for lane departure check accuracy.
todo: Implement lane departure detection that does not depend on the footprint
- Link
psim
2025/02/03 https://evaluation.tier4.jp/evaluation/reports/71aaf71c-79ae-5e67-a543-cef7922ab219/?project_id=prd_jt
2025/02/03 https://evaluation.tier4.jp/evaluation/reports/df5389ba-1355-5c2a-a221-bc9f9dfed558/?project_id=prd_jt
None.
None.
None.

feat(goal_planner): resample path interval for lane departure check accuracy

---

planning/autoware_route_handler/src/route_handler.cpp

when finding the new shortest paths between checkpoints while rerouting, currently current closest preferred lanelet is prioritized among other lanelets on the same position and it is used only if the position is on that closest preferred lanelet.
This policy should also be applied so that even if ego is not on any preferred lanelet, closest non-preferred route lanelet is searched instead to make the route continuous.
- https://tier4.atlassian.net/browse/RT1-9109
- Link
- https://evaluation.tier4.jp/evaluation/reports/2e299d7a-083d-5c21-8642-32931ff6981d?project_id=prd_jt
None.
None.
None.

fix(route_handler): use non-preferred route segment even if checkpoint is not on preferred lanelet at best

---

map/autoware_map_projection_loader/src/load_info_from_lanelet2_map.cpp

Previously, when autoware_map_projection_loader failed to load a map file, it did not show the details of the error. In this PR I have added the codes to show the errors.
None.
None.
None.

chore(autoware_map_projection_loader): show map error details

---

.github/actions/combine-repos-action/README.md
.github/actions/combine-repos-action/action.yaml
.github/actions/combine-repos-action/combine-repos.py
.github/sync-files.yaml
.github/workflows/build-and-test-daily-arm64.yaml
.github/workflows/build-and-test-daily.yaml
.github/workflows/build-and-test-differential-arm64.yaml
.github/workflows/build-and-test-differential.yaml
.github/workflows/build-and-test.yaml
.github/workflows/check-build-depends.yaml
build_depends_humble.repos
build_depends_nightly.repos

**Related Issue:**
- https://github.com/autowarefoundation/autoware/issues/5792
**Humble counterpart:**
- https://github.com/autowarefoundation/autoware.universe/pull/10146
`build_depends.repos` file is used for pulling the dependencies of this repository while building it, currently used by CI.
With the introduction of [`autoware-nightly.repos`](https://github.com/autowarefoundation/autoware/blob/cad73fb1a431937e674bfeb067a9e1dbab99840f/autoware-nightly.repos)  and pinning of the versions in [`autoware.repos`](https://github.com/autowarefoundation/autoware/blob/cad73fb1a431937e674bfeb067a9e1dbab99840f/autoware.repos), the management of this file became a bit complicated.
This repository has 2 branches: `main` and `humble`. This PR introduces the following configuration for both these: …

ci(build-depends.repos): separate repos for humble and nightly

---

.github/actions/combine-repos-action/README.md
.github/actions/combine-repos-action/action.yaml
.github/actions/combine-repos-action/combine-repos.py
.github/sync-files.yaml
.github/workflows/build-and-test-daily-arm64.yaml
.github/workflows/build-and-test-daily.yaml
.github/workflows/build-and-test-differential-arm64.yaml
.github/workflows/build-and-test-differential.yaml
.github/workflows/build-and-test.yaml
.github/workflows/check-build-depends.yaml
build_depends_humble.repos
build_depends_nightly.repos
planning/motion_velocity_planner/autoware_motion_velocity_planner_node_universe/package.xml

- hotfix https://github.com/autowarefoundation/autoware.universe/pull/10122
- https://github.com/autowarefoundation/autoware/issues/5792
None.
None.
None.

chore(motion_velocity_planner_universe): fix build depends (#10122)

---

launch/tier4_perception_launch/launch/perception.launch.xml
launch/tier4_perception_launch/launch/traffic_light_recognition/traffic_light.launch.xml
perception/autoware_traffic_light_multi_camera_fusion/config/traffic_light_multi_camera_fusion.param.yaml
perception/autoware_traffic_light_multi_camera_fusion/launch/traffic_light_multi_camera_fusion.launch.xml
perception/autoware_traffic_light_multi_camera_fusion/schema/traffic_light_multi_camera_fusion.schema.json

PR for launcher: https://github.com/autowarefoundation/autoware_launch/pull/1331
Currently, the parameters for `traffic_light_multi_camera_fusion` are [hardcoded in the launch file](https://github.com/autowarefoundation/autoware.universe/blob/b4d9155fbe78aaf35f976af808b2ca62d1727d1f/launch/tier4_perception_launch/launch/traffic_light_recognition/traffic_light.launch.xml#L61-L62), preventing modifications from the launch file.
To resolve this issue, I modified it to read parameters from a YAML file in `autoware_launch`.
- Link
I modified the parameters in  like this,
**tier4_perception_component.launch.xml**
```xml
<arg name="all_traffic_light_camera" default="[camera4, camera5, camera6, camera7]" description="choose camera which use for traffic light recognition"/>
``` …

chore(traffic_light_multi_camera_fusion): read parameters from yaml file

---

sensing/autoware_radar_scan_to_pointcloud2/config/radar_scan_to_pointcloud2.param.yaml
sensing/autoware_radar_scan_to_pointcloud2/schema/radar_scan_to_pointcloud2.schema.json
sensing/autoware_radar_scan_to_pointcloud2/src/radar_scan_to_pointcloud2_node.cpp
sensing/autoware_radar_scan_to_pointcloud2/src/radar_scan_to_pointcloud2_node.hpp

Use SensorDataQoS for subscriber and publisher.
- https://github.com/autowarefoundation/autoware.universe/issues/10155
Tested with a bag file which includes ARS 548 RadarScan data via the following launch:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<launch>
<push-ros-namespace namespace="radar_cloud"/>
<group>
<group>
<push-ros-namespace namespace="radarscan_filtering"/>
<include file="$(find-pkg-share radar_scan_to_pointcloud2)/launch/radar_scan_to_pointcloud2.launch.xml">
<arg name="input/radar" value="/sensing/radar/front/scan_raw"/>
<arg name="output/amplitude_pointcloud" value="raw/output/amplitude_pointcloud"/>
<arg name="output/doppler_pointcloud" value="raw/output/doppler_pointcloud"/>
</include>
</group>
</group>
<launch>
```
Used the same QoS setting as …

fix(autoware_radar_scan_to_pointcloud2): use sensor data qos

---

launch/tier4_perception_launch/launch/traffic_light_recognition/traffic_light.launch.xml

Fix following error.
```
[ERROR] [launch]: Caught exception in launch (see debug for traceback): launch configuration 'traffic_light_multi_camera_fusion_param_path' does not exist
```
None
Launch planning simulation.
None.
None.
None.

fix(tier4_perception_launch): add missing parameter for planning simulation

---

sensing/autoware_radar_threshold_filter/config/radar_threshold_filter.param.yaml
sensing/autoware_radar_threshold_filter/src/radar_threshold_filter_node.cpp
sensing/autoware_radar_threshold_filter/src/radar_threshold_filter_node.hpp
sensing/autoware_radar_threshold_filter/test/radar_threshold_filter/test_radar_threshold_filter.cpp

Use SensorDataQoS for subscriber and publisher.
- https://github.com/autowarefoundation/autoware.universe/issues/10155
Tested with a bag file which includes ARS 548 RadarScan data via the following launch:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<launch>
<push-ros-namespace namespace="radar_cloud"/>
<group>
<group>
<push-ros-namespace namespace="radarscan_filtering"/>
<include
file="$(find-pkg-share radar_threshold_filter)/launch/radar_threshold_filter.launch.xml">
<arg name="input/radar" value="/sensing/radar/front/scan_raw"/>
<arg name="output/radar" value="output/threshold_filtered_radar"/>
</include>
</group>
</group>
<launch>
```
Used the same QoS setting as pointcloud_preprocessor:
- https://github.com/autowarefoundation/autoware.universe/blob/c9aa4093433f4e57 …

fix(autoware_radar_threshold_filter): use sensor data qos

---

planning/autoware_route_handler/package.xml
planning/autoware_route_handler/src/route_handler.cpp
planning/autoware_route_handler/test/test_route_handler.cpp

This PR replace autoware_universe_utils with autoware_utils in autoware_route_handler as a preparation for porting to Autoware Core.
- https://github.com/autowarefoundation/autoware.core/issues/190
https://evaluation.ci.tier4.jp/evaluation/reports/66ed5349-c25c-5022-b15f-103d0d026273?project_id=prd_jt
None.
None.
None.

feat: replace autoware_universe_utils with autoware_utils in autoware_route_handler

---

common/autoware_universe_utils/include/autoware/universe_utils/geometry/boost_geometry.hpp
common/autoware_universe_utils/package.xml
common/autoware_vehicle_info_utils/include/autoware_vehicle_info_utils/vehicle_info.hpp
common/autoware_vehicle_info_utils/package.xml
common/autoware_vehicle_info_utils/src/vehicle_info.cpp
control/autoware_collision_detector/package.xml
control/autoware_lane_departure_checker/src/lane_departure_checker_node/lane_departure_checker_node.cpp
control/autoware_lane_departure_checker/src/lane_departure_checker_node/utils.cpp
control/autoware_obstacle_collision_checker/include/autoware/obstacle_collision_checker/obstacle_collision_checker.hpp
control/autoware_obstacle_collision_checker/src/debug.cpp
evaluator/autoware_control_evaluator/include/autoware/control_evaluator/control_evaluator_node.hpp
evaluator/autoware_control_evaluator/src/control_evaluator_node.cpp
evaluator/autoware_perception_online_evaluator/include/autoware/perception_online_evaluator/utils/marker_utils.hpp
evaluator/autoware_perception_online_evaluator/src/utils/marker_utils.cpp
planning/autoware_mission_planner_universe/src/lanelet2_plugins/default_planner.cpp
planning/autoware_mission_planner_universe/src/lanelet2_plugins/default_planner.hpp
planning/autoware_obstacle_cruise_planner/include/autoware/obstacle_cruise_planner/type_alias.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_searcher.cpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/utils.cpp
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/start_planner_module.cpp

This PR replaces autoware_universe_utils with autoware_utils in autoware_vehicle_info_utils as preparation of porting to Autoware Core.
This also includes the following modification in order to pass the build CI:
* make autoware::universe_utils::Point2d and autoware_utils::Point2d compatible https://github.com/autowarefoundation/autoware.universe/pull/10167/commits/59f8629459ee50870d21dddfb3b3317b86b89aea
* modify packages that depend on autoware_universe_utils via autoware_vehicle_info_utils to make sure that they independently include autoware_unvierse_utils headers. https://github.com/autowarefoundation/autoware.universe/pull/10167/commits/439a97940ff44507de762271be63ec584233f621
- https://github.com/autowarefoundation/autoware.core/issues/131
** Related PRs **
- …

feat(autoware_vehicle_info_utils): replace autoware_universe_utils with autoware_utils

---

planning/autoware_mission_planner_universe/src/lanelet2_plugins/default_planner.cpp

In addition to this PR https://github.com/autowarefoundation/autoware.universe/pull/8760, if the goal is just on the very beginning of a lanelet, ego's goal footprint becomes outside of the ego_lanes. To avoid this, I added previous lanelet of closest_goal_lanelet as well.
- Link
- https://evaluation.tier4.jp/evaluation/reports/7f55984f-52be-5218-bd44-c119159844aa?project_id=prd_jt
None.
None.
None.

feat(mission_planner): tolerate goal footprint being inside the previous lanelets of closest lanelet

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_searcher.cpp

in curved lanes, align the goal candidate pose so that the vehicle center becomes parallel to the pull over lane boundary on the parking side
depends https://github.com/autowarefoundation/autoware.universe/pull/10179
- Link
- https://evaluation.tier4.jp/evaluation/reports/257d6f6e-65f2-5780-9ae2-a23e0cc60249?project_id=prd_jt
None.
None.
None.

feat(goal_planner): align vehicle center to be parallel to lane boundary

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp

bundle the code in planPulloverAsOutput and setOutput() to refactor planPulloverAsCandidate
- Link
- https://evaluation.tier4.jp/evaluation/reports/5e47c8a0-3a5c-5f24-ba62-8e7325ecabab?project_id=prd_jt 
- https://evaluation.tier4.jp/evaluation/reports/c49b2f74-3790-5db6-a76b-7fd8fe18eae7?project_id=prd_jt 
None.
None.
None.

refactor(goal_planner): refactor planPullOverAsCandidate

---

common/autoware_object_recognition_utils/package.xml
common/autoware_traffic_light_utils/package.xml
evaluator/autoware_perception_online_evaluator/package.xml
launch/tier4_perception_launch/package.xml
perception/autoware_cluster_merger/package.xml
perception/autoware_crosswalk_traffic_light_estimator/package.xml
perception/autoware_detected_object_validation/package.xml
perception/autoware_ground_segmentation/package.xml
perception/autoware_image_projection_based_fusion/package.xml
perception/autoware_object_velocity_splitter/package.xml
perception/autoware_radar_crossing_objects_noise_filter/package.xml
perception/autoware_radar_fusion_to_detected_object/package.xml
perception/autoware_radar_object_clustering/package.xml
perception/autoware_radar_tracks_msgs_converter/package.xml
perception/autoware_simple_object_merger/package.xml
perception/autoware_tensorrt_classifier/package.xml
perception/autoware_traffic_light_arbiter/package.xml
perception/autoware_traffic_light_classifier/package.xml
perception/autoware_traffic_light_fine_detector/package.xml
perception/autoware_traffic_light_map_based_detector/package.xml
perception/autoware_traffic_light_multi_camera_fusion/package.xml
perception/autoware_traffic_light_occlusion_predictor/package.xml
perception/perception_utils/package.xml
sensing/autoware_pointcloud_preprocessor/package.xml
sensing/autoware_radar_scan_to_pointcloud2/package.xml
sensing/autoware_radar_static_pointcloud_filter/package.xml
sensing/autoware_radar_threshold_filter/package.xml
sensing/autoware_radar_tracks_noise_filter/package.xml
visualization/autoware_perception_rviz_plugin/package.xml

Remove Miura from the maintainer list.
Add Yoshi-san as the new maintainer.
https://github.com/autowarefoundation/autoware_launch/pull/1328
No test
None.
None.
None.

chore: refine maintainer list

---

planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/config/obstacle_slow_down.param.yaml
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/src/obstacle_slow_down_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/src/obstacle_slow_down_module.hpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/src/parameters.hpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/src/types.hpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/config/obstacle_stop.param.yaml
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/obstacle_stop_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/obstacle_stop_module.hpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/parameters.hpp
planning/motion_velocity_planner/autoware_motion_velocity_planner_common_universe/include/autoware/motion_velocity_planner_common_universe/planner_data.hpp
planning/motion_velocity_planner/autoware_motion_velocity_planner_common_universe/include/autoware/motion_velocity_planner_common_universe/utils.hpp
planning/motion_velocity_planner/autoware_motion_velocity_planner_common_universe/src/utils.cpp

https://tier4.atlassian.net/jira/software/c/projects/RT0/boards/438?assignee=712020%3A794ae440-77c4-4b7e-9a5a-a2cb085494fb&quickFilter=771&selectedIssue=RT1-9227&sprint=631
Results in https://tier4.atlassian.net/wiki/spaces/~712020794ae44077c44b7e9a5aa2cb085494fb/pages/3549299486/Point+Cloud+Handling+in+motion_velocity_planner+module
None.
None.
None.

feat(autoware_motion_velocity_obstacle_<stop/slow_down>_module): brings Point Cloud handling to this module

---

.github/workflows/build-test-tidy-pr.yaml

I have modified build-test-tidy-pr workflow to use AWs Code Build for build-and-test-differential-cuda in [this PR](https://github.com/autowarefoundation/autoware.universe/pull/10198), but I have forgotten to update the runner for clang-tidy-differential-cuda. 
This PR modifies the clang-tidy-differential-cuda to use AWS Code Build to avoid space disk issue
- [Link](https://github.com/autowarefoundation/autoware.universe/pull/10198)
None.
None.
None.

ci: use Code Build for clang-tidy-differential-cuda

---

launch/tier4_perception_launch/launch/object_recognition/detection/detection.launch.xml
launch/tier4_perception_launch/launch/object_recognition/detection/detector/camera_lidar_detector.launch.xml
launch/tier4_perception_launch/launch/object_recognition/detection/merger/camera_lidar_merger.launch.xml
launch/tier4_perception_launch/launch/object_recognition/detection/merger/camera_lidar_radar_merger.launch.xml
launch/tier4_perception_launch/launch/object_recognition/detection/merger/lidar_merger.launch.xml

1. Re-order so-called "objects_validation" process after lidar ml detector.
- Before
[Lider-ML detector] -> [roi detected object fusion] -> [object validator] -> [merger] 
- After
[Lider-ML detector] -> [object validator] -> [roi detected object fusion] -> [merger] 
This change do not induce the documentation diagram change.
https://github.com/autowarefoundation/autoware-documentation/blob/main/docs/design/autoware-architecture/perception/image/reference-implementaion-perception-diagram.drawio.svg
2. Refactoring camera-lidar detector.launch.xml
No logical changes introduced in this PR.
- Link
TIER IV INTERNAL
[test 1 check various mode combinations](https://evaluation.tier4.jp/evaluation/reports/d016a942-2654-5ec9-8282-e57a94c8c5af?project_id=prd_jt)
[test 2 performance …

chore(tier4_perception_launch): re-order objects_validation process after lidar ml detector

---

control/autoware_trajectory_follower_node/src/controller_node.cpp
control/autoware_vehicle_cmd_gate/src/vehicle_cmd_gate.cpp
planning/behavior_path_planner/autoware_behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_planner/src/node.cpp

I add small modification so that we can measure planning and control component latency.
- Fix the place where check the current time in `behavior_path_planner_node.cpp` and `controller_node.cpp`.
- Change code to use stamp of recieved topic in `behavior_velocity_planner.cpp` and `vehicle_cmd_gate.cpp`.
None.
Psim.
Please check component interface topic and confirm they have same time stamp which are published by `behavior_path_planner` or `trajectory_follower_node`.
Interface:
- PLANING: `/planning/scenario_planning/trajectory`
- CONTROL: `/control/command/control_cmd`
FYI: publishing unique timestamp makes it easier to check the all module inherit published timestamp.
```patch
diff --git a/planning/behavior_path_planner/autoware_behavior_path_planner/src/behavior_path_pl …
```

fix(planning, control): reuse stamp of subscribed topic to measure component latency

---

control/autoware_lane_departure_checker/src/lane_departure_checker_node/utils.cpp
control/autoware_lane_departure_checker/test/test_resample_trajectory.cpp

Fixed a bug in the resampleTrajectory function where the `prev_point` was being updated even when a trajectory point was not added to the resampled trajectory. This caused incorrect distance calculations and potentially led to trajectory points being improperly filtered.
- [TIERIV internal link](https://tier4.atlassian.net/browse/RT0-35625)
- run planning simulator 
green point: resampled points
behavior before the change:
https://github.com/user-attachments/assets/54df6b88-f6bb-42fd-8933-c506f03d8123
behvior after the change:
https://github.com/user-attachments/assets/dafb7948-3be1-48c5-85e2-7ead8f94bf15
- add unit test to detect bug in the original implementation
original code fails as follows
```
1: [ RUN      ] …
```

fix(lane_departure_checker): fix trajectory resampling logic to keep given interval

---

system/autoware_dummy_infrastructure/config/dummy_infrastructure.param.yaml
system/autoware_dummy_infrastructure/include/autoware/dummy_infrastructure/dummy_infrastructure_node.hpp
system/autoware_dummy_infrastructure/launch/dummy_infrastructure.launch.xml
system/autoware_dummy_infrastructure/package.xml
system/autoware_dummy_infrastructure/schema/dummy_infrastructure.schema.json
system/autoware_dummy_infrastructure/src/dummy_infrastructure_node/dummy_infrastructure_node.cpp

Add new mode to approve when ego stops at stop line. This is useful for scenario test
fisrt time
https://github.com/user-attachments/assets/128d05e3-8224-4dc1-b993-01376b0449b7
after second time for same id
https://github.com/user-attachments/assets/0f47bc03-6e45-49eb-a8b9-42919f9a83be
scenario test
https://github.com/user-attachments/assets/dfd16c1f-2c5f-46ab-8bd2-5f74cfe7bd66
- Link
- psim
- auto mode
- rqt manual mode 
- scenario test local
- `webauto ci scenario run --project-id autoware_dev --scenario-id 9e0b5757-5c7a-428e-8348-5fdfb639d467`
-  2025/03/05 https://evaluation.tier4.jp/evaluation/reports/2cf8ee00-63af-59e1-992e-a696ed9bbd9d/?project_id=prd_jt
None.
None.
None.

feat(dummy_infrastructure): auto approval when ego stops at stop line

---

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp

Bug: The ego couldn't keep stopping in front of the avoidance target during yielding. This issue was caused by https://github.com/autowarefoundation/autoware.universe/pull/9089.
The purpose of https://github.com/autowarefoundation/autoware.universe/pull/9089 was removing stop line and preventing stuck when the ego obiously overrun the stop line. But it removed stop line even when it stopped properly since threre is no buffer.
https://github.com/user-attachments/assets/7867533b-d786-46a4-9b14-3dd18357b706
- https://github.com/autowarefoundation/autoware.universe/pull/9089
Ego keeps stopping during yielding.
https://github.com/user-attachments/assets/bc59896d-a08e-4330-960f-370e6ce0e5a6
None.
None.
None.

fix(static_obstacle_avoidance): ego doesn't keep stopping in unsafe condition

---

control/autoware_control_validator/config/control_validator.param.yaml
control/autoware_control_validator/include/autoware/control_validator/control_validator.hpp
control/autoware_control_validator/msg/ControlValidatorStatus.msg
control/autoware_control_validator/package.xml
control/autoware_control_validator/src/control_validator.cpp
launch/tier4_control_launch/launch/control.launch.xml

:warning: Please review and approve https://github.com/autowarefoundation/autoware_launch/pull/1349 first.
I added a feature to calculate control component latency and to publish error diagnostic if it is larger than threshold.
- Link
None.
Add new field to publish current latency.
```patch
diff --git a/control/autoware_control_validator/msg/ControlValidatorStatus.msg b/control/autoware_control_validator/msg/ControlValidatorStatus.msg
index 5db179f5a9..c40f160510 100644
--- a/control/autoware_control_validator/msg/ControlValidatorStatus.msg
+++ b/control/autoware_control_validator/msg/ControlValidatorStatus.msg
@@ -4,10 +4,12 @@ builtin_interfaces/Time stamp
bool is_valid_max_distance_deviation
bool is_rolling_back
bool is_over_velocity
+bool is_valid_latency
float64 …
```

feat(control_validator): add diag to check control component latency

---

planning/behavior_velocity_planner/autoware_behavior_velocity_stop_line_module/src/scene.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/manager.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/scene.cpp

Fixed the issue that
- PlanningFactor distance value of stopline is negative
- PlanningFactor distance value of traffic_light does not appear
- https://tier4.atlassian.net/browse/RT0-35448?focusedCommentId=210107
See the attached video in the ticket
https://evaluation.tier4.jp/evaluation/reports/b7b812c4-d000-5be2-9f9a-b2c6a8f349be?project_id=prd_jt
None.
None.
None.

fix(stopline, traffic_light): fix planning factor distance value

---

planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/obstacle_stop_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/obstacle_stop_module.hpp

Currently when handling point cloud points in the obstacle stop module, we do not consider the bumper length of the vehicle, causing the vehicle to brake late.
- Link
https://tier4.atlassian.net/browse/RT1-9428
Simulation result attached to ticket.
None.
None.
None.

fix(obstacle_stop): accounting for vehicle bumper length when handling point-cloud stop points

---

planning/motion_velocity_planner/autoware_motion_velocity_dynamic_obstacle_stop_module/src/dynamic_obstacle_stop_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_dynamic_obstacle_stop_module/src/dynamic_obstacle_stop_module.hpp

Currently, the processing time for the `dynamic_obstacle_stop` may not be published if we do an early return in case the input trajectory does not have enough point.
With this PR, the processing time is always published.
Psim
None.
None.

fix(dynamic_obstacle_stop): publish processing time when early return

---

control/autoware_control_validator/README.md
control/autoware_control_validator/config/control_validator.param.yaml
control/autoware_control_validator/include/autoware/control_validator/control_validator.hpp
control/autoware_control_validator/msg/ControlValidatorStatus.msg
control/autoware_control_validator/src/control_validator.cpp

add overrun stop point check 
[Screencast from 2025年03月04日 17時57分27秒.webm](https://github.com/user-attachments/assets/906ca190-f95b-45b7-a910-f01b8d20f6c7)
This feature is similar to the EMERGENCY status in the pid_longitudinal_controller, but it plays a different role.
launch PR: https://github.com/autowarefoundation/autoware_launch/pull/1346
None.
None.
None.

feat(control_validator)!: add overrun check

---

planning/behavior_path_planner/autoware_behavior_path_planner/config/drivable_area_expansion.param.yaml
planning/behavior_path_planner/autoware_behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/docs/behavior_path_planner_drivable_area_design.md
planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/drivable_area_expansion/parameters.hpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/drivable_area_expansion/footprints.cpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/test/test_drivable_area_expansion.cpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/test/test_footprints.cpp

Drivable area expansion has the option to avoid expanding in the path of dynamic objects. However this feature is disabled by default as it can be unstable and put too much restriction on Ego motion around corners and tight turns.
At tight turns drivable area is expanded considerably specially in case of large Ego vehicle, and Ego can exceed its current lane boundaries, as a result there is a higher chance of collision if there are nearby obstacles and the point of turning, like shown in the image below.
To address this, this PR modifies the drivable area expansion to able to avoid static objects explicitly without having to avoid all dynamic objects.
The following image shows the behavior with and without this feature.
- [Launcher …

feat(behavior_path_planner_common): modify drivable area expansion to be able to avoid static objects

---

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/interface.cpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/test/test_lane_change_scene.cpp

There is an issue of LC planning factor showing large negative values as shown below.
This is caused by:
1- Incorrect activation of LC module when Ego is on preferred lane
2- Incorrect call to `LaneChangeInterface::plan()` function while LC is still in IDLE state
3- Incorrect setting of stop point on target lane when not necessary
This PR resolves the above 3 points.
- [TIER IV internal link](https://star4.slack.com/archives/CEV8XMJBV/p1739763007593809)
- PSIM
None.
None.
None.

fix(lane_change_module): fix planning factor issue

---

planning/autoware_mission_planner_universe/CMakeLists.txt

Not sure why it occurs only when we move this package out.
But fixes:
- https://github.com/autowarefoundation/autoware.core/pull/201#issuecomment-2716840238
Does anybody have any idea why it happens?
Build.

fix(autoware_mission_planner_universe): add explicit test dependency

---

common/autoware_universe_utils/src/geometry/alt_geometry.cpp
common/autoware_universe_utils/test/src/geometry/test_alt_geometry.cpp

This PR fixes the procedure in `covered_by()` and `within()` functions to check if the given point is on any edge of the given polygon.
internal: https://star4.slack.com/archives/C0575HP7NJG/p1741675912882399
```
colcon test --packages-select autoware_universe_utils --event-handlers console_cohesion+
```
Benchmark results with 100 randomly generated polygons with 9 vertices:
|function|Boost|alternative|
|---|---|---|
|`covered_by()`|14.29ms|10.38ms|
|`within()`|47.20ms|1.63ms|
None.
None.
None.

fix(autoware_universe_utils): fix procedure to check if point is on edge

---

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/scene.hpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp

The static obstacle avoidance module outputs chattterd turn signal command. (repeat LEF/RIGHT and DISABEL by high frequesncy.)
https://github.com/user-attachments/assets/a87ea265-30b2-4c32-9897-60bef1e4cbee
I fixed the issue in this PR. This issue caused by unexpected erase of ignore turn signal info.
- [TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT1-9230)
https://github.com/user-attachments/assets/aef2701a-656a-478a-a7e6-058bd7cb5124
None.
None.
None.

fix(static_obstacle_avoidance): turn signal chattering

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/util.cpp

When creating departure_check_lane for the search function in goal_searcher. If the inner lane is opposite, it should be inverted before generating the new lane. Otherwise, the generated polygon for departure_check_lane can not be used with "within" function.
**Before PR**
[Link](https://youtu.be/7AyDrwKAs5M)
**After PR**
[Link](https://youtu.be/P8heUlGxtbg)
- https://github.com/autowarefoundation/autoware.universe/issues/10206
PSim
None.
None.
None.

fix(goal_planner): invert lane boundary of neighbor opposite lanelets when generating departure check lane

---

perception/autoware_image_projection_based_fusion/launch/segmentation_pointcloud_fusion.launch.xml

- Fix typo in  "segmentation_pointcloud_fusion.launch.xml".
- Link
None.
None.
None.

fix(segmentation_pointcloud_fusion): fix typo of defaut camera info topic

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_module.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_searcher.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_searcher.cpp

even if the flag `use_bus_stop_area` is true, if there are no BusStopArea polygons on the designated pull over lanes, fallback to normal mode and pull over on normal road shoulder lanes.
- Link
tested with `use_bus_stop_area` = true.
shift planner works
bezier planner works
None.
None.
None.

fix(goal_planner): ignore use bus_stop_area flag if there are no BusStopArea on the pull over lanes

---

planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/package.xml
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/src/obstacle_slow_down_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/src/obstacle_slow_down_module.hpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/package.xml
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/obstacle_stop_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/obstacle_stop_module.hpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/parameters.hpp

The obstacle_stop and obstacle_slow_down modules **without point cloud** were very heavy since the point cloud processing was not skipped.
This PR returns early without the point cloud processing when the point cloud is disabled.
TODO: With another PR, the heavy calculation of the point cloud processing should be handled.
before:
```
100.00% plan: total 90.28 [ms], avg. 90.28 [ms], run count: 1
├── 6.85% filter_stop_obstacle_for_predicted_object: total 6.18 [ms], avg. 6.18 [ms], run count: 1
│   ├── 6.84% for_each_object: total 6.18 [ms], avg. 1.54 [ms], run count: 4
│   │   ├── 3.26% get_decimated_traj_polys: total 2.94 [ms], avg. 2.94 [ms], run count: 1
│   │   ├── 3.31% get_dist_to_traj_poly: total 2.99 [ms], avg. 2.99 [ms], run count: 1
│   │   ├── 0.01% …
```

fix(obstacle stop/slow_down): early return without point cloud

---

planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/config/obstacle_stop.param.yaml
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/obstacle_stop_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/parameters.hpp

Currently, `max_lat_margin_against_unknown` is used for the point cloud.
For the users who use not the predicted object but the point cloud for the obstacle stop and slow_down, it's a bit confusing that not `max_lat_margin` but `max_lat_margin_against_unknown` is used.
Therefore, this PR modifies as follows
- use `max_lat_margin` for the point cloud
- rename `max_lat_margin_against_unknown` to `max_lat_margin_against_predicted_object_unknown`.
planning simulator worked well
None.
None.
None.

fix(obstacle_stop): use max_lat_margin_against_unknown only for predicted object

---

perception/autoware_multi_object_tracker/lib/object_model/shapes.cpp
perception/autoware_multi_object_tracker/lib/tracker/model/unknown_tracker.cpp
perception/autoware_multi_object_tracker/src/processor/input_manager.cpp

Object shape process for polygon shape (generally for unknown object) should be processed after the object is transformed to world coordinate. 
This PR fixes [the previous PR ](https://github.com/autowarefoundation/autoware.universe/pull/10203)the polygon process before the transform.
BUG
https://github.com/user-attachments/assets/91b5d8c6-59fc-4524-9d11-b3674543f87d
Additionally, fix a bug to fit bounding box to the polygon.
- Link
None.
None.
None.

fix(autoware_multi_object_tracker): unknown object orientation

---

planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/src/decisions.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/src/scene.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_merge_from_private_road.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_no_drivable_lane_module/src/scene.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_no_stopping_area_module/src/scene_no_stopping_area.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_run_out_module/src/scene.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_stop_line_module/src/scene.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/scene.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_virtual_traffic_light_module/src/scene.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_walkway_module/src/scene_walkway.cpp

All behavior veloicty modules set redundant control point if the module made stop decision.
```patch
diff --git a/planning/behavior_velocity_planner/autoware_behavior_velocity_walkway_module/src/scene_walkway.cpp b/planning/behavior_velocity_planner/autoware_behavior_velocity_walkway_module/src/scene_walkway.cpp
index 4d8651d05c..827655daa2 100644
--- a/planning/behavior_velocity_planner/autoware_behavior_velocity_walkway_module/src/scene_walkway.cpp
+++ b/planning/behavior_velocity_planner/autoware_behavior_velocity_walkway_module/src/scene_walkway.cpp
@@ -123,7 +123,7 @@ bool WalkwayModule::modifyPathVelocity(PathWithLaneId * path)
/* get stop point and stop factor */
planning_factor_interface_->add(
-      path->points, planner_data_->current_odometry->pose, stop_pose.value(), …
```

fix(behavior_velocity_planner): planning factor integration

---

control/autoware_mpc_lateral_controller/src/qp_solver/qp_solver_osqp.cpp
planning/autoware_obstacle_cruise_planner/src/optimization_based_planner/velocity_optimizer.cpp
planning/autoware_path_optimizer/include/autoware/path_optimizer/mpt_optimizer.hpp
planning/autoware_path_optimizer/include/autoware/path_optimizer/node.hpp
planning/autoware_path_optimizer/include/autoware/path_optimizer/state_equation_generator.hpp
planning/autoware_path_optimizer/include/autoware/path_optimizer/utils/conditional_timer.hpp
planning/autoware_path_optimizer/src/mpt_optimizer.cpp
planning/autoware_path_optimizer/src/node.cpp
planning/autoware_path_smoother/src/elastic_band.cpp
planning/autoware_velocity_smoother/src/smoother/l2_pseudo_jerk_smoother.cpp
planning/autoware_velocity_smoother/src/smoother/linf_pseudo_jerk_smoother.cpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_cruise_module/src/optimization_based_planner/velocity_optimizer.cpp
system/autoware_system_diagnostic_monitor/config/planning.yaml

Returns the smoothed_points trajectory fed into MPT when the latter fails, triggers an emergency stop MRM after 3s.
- [Link](https://tier4.atlassian.net/browse/RT1-9515)
None.
None.
None.

feat(path_optimizer): additional failure logging and failure mode handling

---

planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_safety_checker/safety_check.cpp

Set safety condition properly in safety check utils.
None.
I confirmed the flag is_safe became false when I put dummy vehicle near the lane change path in Psim.
None.
None.
None.

fix(safety_check): set safety condition properly

---

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp

1. The error occurred because unnecessary shift lines were excluded before target_shift_line was selected.
2. There were duplicate processes excluding small shifts in scene.cpp and turn_signal_decider.cpp.
- [Slack Link](https://star4.slack.com/archives/C04HK9T2E0N/p1742176350312149?thread_ts=1742155919.679659&cid=C04HK9T2E0N)
- [Evaluator](https://evaluation.tier4.jp/evaluation/reports/0db01e96-59e4-5103-a1a0-d42fb25a4f5a?project_id=prd_jt)
None.
None.
None.

fix(autoware_behavior_path_static_obstacle_avoidance_module): blinker bug in static obstacle avoidance

---

control/autoware_lane_departure_checker/include/autoware/lane_departure_checker/lane_departure_checker_node.hpp

For `LaneDepartureCheckerNode` class, 
In #7358  , the implementation of the callback function has been removed, but the declaration has not.
https://github.com/autowarefoundation/autoware_universe/pull/7358
None.
None.
None.

refactor(control): remove unimplemented function declarations

---

planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/config/crosswalk.param.yaml
planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/manager.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/scene_crosswalk.hpp

- The feature is implemented to consider and do not ignore objects if they are on the crosswalk when the crosswalk pedestrian traffic light is red.
- Enabled/Disabled by `consider_obj_on_crosswalk_on_red_light` parameter
:exclamation: Should be merged after [autoware_launch PR](https://github.com/autowarefoundation/autoware_launch/pull/1374) is merged
**Before**:
https://github.com/user-attachments/assets/256a77f9-08ee-4855-9fa6-9da21c182967
**After**:
https://github.com/user-attachments/assets/39893996-f68e-4878-8c7d-a3e87f06ab85
- Link
None.
None.
None.

feat(crosswalk_module): consider objects on crosswalk when pedestrian traffic light is red

---

perception/autoware_image_projection_based_fusion/src/roi_pointcloud_fusion/node.cpp
perception/autoware_image_projection_based_fusion/src/segmentation_pointcloud_fusion/node.cpp

- Add camera FOV checking before processing pointcloud fusion for `roi_pointcloud_fusion` and `segmentation_pointcloud_fusion` nodes
- Link
None.
None.
None.

fix(image_projection_based_fusion): add outside of FOV checking

---

perception/autoware_image_projection_based_fusion/config/roi_pointcloud_fusion.param.yaml
perception/autoware_image_projection_based_fusion/include/autoware/image_projection_based_fusion/roi_pointcloud_fusion/node.hpp
perception/autoware_image_projection_based_fusion/include/autoware/image_projection_based_fusion/utils/geometry.hpp
perception/autoware_image_projection_based_fusion/schema/roi_pointcloud_fusion.schema.json
perception/autoware_image_projection_based_fusion/src/roi_pointcloud_fusion/node.cpp
perception/autoware_image_projection_based_fusion/src/utils/geometry.cpp

- Add a parameter in `roi_pointcloud_fusion` to adjust ROI when matching with pointcloud for fusion.
- Need merge after https://github.com/autowarefoundation/autoware_launch/pull/1376
- [TIER IV Internal Link](https://tier4.atlassian.net/browse/RT1-9645)
None.
None.
None.

fix(roi_pointcloud_fusion): add roi scale factor param

---

launch/tier4_perception_launch/launch/object_recognition/detection/detector/camera_lidar_detector.launch.xml
perception/autoware_image_projection_based_fusion/launch/roi_pointcloud_fusion.launch.xml

- To add roi_pointcloud_fusion node into `/pointcloud_container`
Before: 
```
/pointcloud_container
1  /perception/obstacle_segmentation/crop_box_filter
2  /perception/occupancy_grid_map/raw_pc_downsample_filter
4  /perception/object_recognition/detection/centerpoint/lidar_centerpoint
5  /perception/object_recognition/detection/voxel_grid_downsample_filter
6  /perception/obstacle_segmentation/common_ground_filter
7  /perception/occupancy_grid_map/obstacle_pc_downsample_filter
8  /perception/object_recognition/detection/voxel_based_compare_map_filter
9  /perception/occupancy_grid_map/occupancy_grid_map_node
```
After: 
```
/pointcloud_container
1  /perception/obstacle_segmentation/crop_box_filter
2  /perception/occupancy_grid_map/raw_pc_downsample_filter
3 …
```

fix(roi_pointcloud_fusion): merge into pointcloud container

---

perception/autoware_image_projection_based_fusion/launch/roi_pointcloud_fusion.launch.xml

The current launcher was creating a new container with the same name as the `pointcloud_container`.
It effectively make nodes being load twice or in different containers.
Additionally, the new container is not a multithreaded one :sweat_smile:  (thanks to this at least I was able to find the source)
- Link
None.
None.
None.

fix(autoware_image_projection_based_fusion): unintended new container behavior

---

sensing/autoware_radar_static_pointcloud_filter/config/radar_static_pointcloud_filter.param.yaml
sensing/autoware_radar_static_pointcloud_filter/package.xml
sensing/autoware_radar_static_pointcloud_filter/schema/radar_static_pointcloud_filter.schema.json
sensing/autoware_radar_static_pointcloud_filter/src/radar_static_pointcloud_filter_node.cpp
sensing/autoware_radar_static_pointcloud_filter/src/radar_static_pointcloud_filter_node.hpp

The `autoware_radar_static_pointcloud_filter` package lacks some dependencies inside package.xml, a necessary header file wasn't included, and couldn't subscribe to input topic because of the wrong QoS setting.
This PR adds dependencies and fixes QoS profiles.
- https://github.com/autowarefoundation/autoware_universe/issues/10155
Tested with a bag file which includes ARS 548 RadarScan data via the following launch:
```xml
<?xml version="1.0"?>
<launch>
<arg name="container_name" default="radar_scan_filter" />
<arg name="radar_threshold_filter_param_path" default="$(find-pkg-share autoware_radar_threshold_filter)/config/radar_threshold_filter.param.yaml" />
<arg name="radar_scan_to_pointcloud2_param_path" default="$(find-pkg-share …
```

fix(autoware_radar_static_pointcloud_filter): add dependencies and use correct qos

---

control/autoware_control_validator/include/autoware/control_validator/control_validator.hpp
control/autoware_control_validator/src/control_validator.cpp
control/autoware_control_validator/test/test_control_validator.cpp

fix sign miss in https://github.com/autowarefoundation/autoware_universe/pull/10326/
commits/9d2c834fff208d4a977bde96882ad5b6a94b0876
increase cut off velocity
add code tests
https://github.com/autowarefoundation/autoware_universe/pull/10326
does not judge as error with current params including stop/start on slope(12.5%)
[Screencast from 2025年03月26日 17時24分09秒.webm](https://github.com/user-attachments/assets/f76f848f-600f-4e28-a906-4dfe1f1c8a03)
detect error if `acc_time_delay: 1.1` in simulator_model.param.yaml
[Screencast from 2025年03月26日 17時24分09秒.webm](https://github.com/user-attachments/assets/1864b151-34a5-4e4a-9e25-b0b514a97dc3)
tier4 scenario test was passed
https://evaluation.tier4.jp/evaluation/reports/eae98895-960f-5841-9981-afebd1a0553a?project_id=prd_jt
None.
None.
None.

fix(control_validator): fix sign miss and add code test

---

perception/autoware_compare_map_segmentation/src/voxel_grid_map_loader/voxel_grid_map_loader.cpp

Fix the bug which comes from [this change](https://github.com/autowarefoundation/autoware_universe/pull/10222/files#diff-6fcc7c77ce6950930e74d4badcd339667191e227f50b9eeb68ba4e6a53754fdaL408-R432) in https://github.com/autowarefoundation/autoware_universe/pull/10222
dynamic_map_loader stopped working because last_updated_position_ was being updated every time.
This was found by @KYabuuchi @zusizusi thank you.
- [TIER IV INTERNAL](https://tier4.atlassian.net/browse/RT0-35928)
lsim
None.
None.
None.

fix(compare_map_segmentation): last map update logic

---

perception/autoware_map_based_prediction/config/map_based_prediction.param.yaml
perception/autoware_map_based_prediction/include/map_based_prediction/map_based_prediction_node.hpp
perception/autoware_map_based_prediction/src/map_based_prediction_node.cpp

This PR introduces diagnostics handler to warn when the processing time exceed a threshold value.
- Parameter update in `autoware_launch`: https://github.com/autowarefoundation/autoware_launch/pull/1362
[Screencast from 03-18-2025 04:30:02 PM.webm](https://github.com/user-attachments/assets/66c25dd8-77c7-46b1-966f-6b843e9cbb6f)
[TIER IV INTERNAL LINK](https://evaluation.ci.tier4.jp/evaluation/reports/17102d51-5559-59b2-b142-9d0a0ad25eac?project_id=prd_jt)
None.
|:--------------|:---------------|:---------|:--------------|:------------------|
| Added | `processing_time_tolerance_ms`   | `double` | `500.0`         | If the processing exceeds this value, diagnostics publishes  warning.|
None.

feat(map_based_prediction): add diagnostic handler to warn the processing time excess

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/README.md
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/config/goal_planner.param.yaml
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/manager.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/geometric_pull_over.cpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/parking_departure/geometric_parallel_parking.hpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/parking_departure/geometric_parallel_parking.cpp
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/README.md
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/config/start_planner.param.yaml
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/data_structs.cpp
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/geometric_pull_out.cpp
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/manager.cpp

**https://github.com/autowarefoundation/autoware_launch/pull/1368 should be merged first.**
The maximum steering angle of the vehicle is defined in vehicle_info, and the planning/control modules reference this value. However, the start/goal planner defines its own parameters, so when the vehicle is changed, these parameters need to be modified individually.
Since it's difficult to consistently remember to implement these changes, and parameters may not be properly tuned, modify the system to reference the values from vehicle_info.
Based on past experience, the maximum steering angle is often not fully achieved, so a margin is necessary. manage this margin by introducing a coefficient parameter.
---
Additionally, though unrelated to this PR, there is unnecessary parameters that exist, …

feat(start/goal_planner): use common max steer angle parameter from vehicle_info

---

control/autoware_control_validator/include/autoware/control_validator/control_validator.hpp
control/autoware_control_validator/src/control_validator.cpp

Currently, invalid_count is incremented in both `on_predicted_trajectory()` and `on_control_cmd()` , this cause invalid_count increase in double speed.
This PR fixes this issue.
https://github.com/autowarefoundation/autoware_universe/pull/10240
engage available in psim
DLR test for control_validator
https://tier4.atlassian.net/wiki/spaces/PCPT/pages/3458434691/DLR+control-validator
tier4 scenario tests https://evaluation.tier4.jp/evaluation/reports/02608764-80dd-52fc-ba72-23e2afdf33ff?project_id=prd_jt&state=failed
None.
None.
None.

fix(control validator): combine callback functions to fix error count increment bug

---

system/autoware_default_adapi/src/compatibility/autoware_state.cpp
system/autoware_default_adapi/src/compatibility/autoware_state.hpp

Log the autoware state change.
```
AutowareState: Initializing => WaitingForRoute
```
- [TIER IV internal link](https://star4.slack.com/archives/C4P0NSMB5/p1742992518950999)
Use planning simulation and check if the autoware state change log is displayed.
None.
None.
None.

feat(autoware_default_adapi): log autoware state change

---

system/autoware_default_adapi/launch/default_adapi.launch.py

Disable launching the sample API server by default as the port may conflict with other services.
- [TIER IV internal link](https://star4.slack.com/archives/CJVHMJDJ7/p1742811292471779?thread_ts=1742356407.140849&cid=CJVHMJDJ7)
Check if the vehicle drives in planning simulator.
None.
None.
None.

feat(autoware_default_adapi): disable sample web server

---

perception/autoware_crosswalk_traffic_light_estimator/src/node.cpp

There is a problem that the crosswalk traffic light estimator drops out when a pedestrian signal is received with V2I signal coordination.
This problem is caused by a process in crosswalk_traffic_light_estimator that accesses elements without checking for the presence of signal recognition results.
Accessing an element without checking its value even when it is empty causes a segmentation fault.
This PR solves the problem by adding a process that prevents the result of signal recognition from being referenced in an empty state.
- [TIER IV internal link](https://tier4.atlassian.net/browse/RT0-34969) 
- [Evaluator](https://evaluation.ci.tier4.jp/evaluation/reports/c913655e-2855-5a2b-ae65-8a983ce3cde3?project_id=prd_jt)
- PSIM
None.
None.
None.

fix(autoware_crosswalk_traffic_light_estimator): add process that guard access to empty elements

---

perception/autoware_tensorrt_common/include/autoware/tensorrt_common/tensorrt_common.hpp
perception/autoware_tensorrt_common/src/tensorrt_common.cpp

Rebuilds engine if cached engine file was build with different version of TensorRT.
TensorRT does not expose API for checking engine before deserialization (at least I couldn't find).
Source of implementation: https://github.com/NVIDIA/TensorRT/issues/3073#issuecomment-1599934548
- Link
None.
None.
None.

feat(autoware_tenssort_common): validate TensorRT engine version for cached engine

---

planning/motion_velocity_planner/autoware_motion_velocity_obstacle_cruise_module/src/obstacle_cruise_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/src/obstacle_slow_down_module.cpp

Fix the topic names that were inconsistent in motion_velocity_obstacle_xxx_modules.
simple planning simulator worked.
None.
None.
None.

fix(motion_velocity_obstacle_xxx_module): fix debug topic name

---

visualization/tier4_planning_rviz_plugin/include/tier4_planning_rviz_plugin/path/display.hpp
visualization/tier4_planning_rviz_plugin/include/tier4_planning_rviz_plugin/path/display_base.hpp

Add visualization of the `time_from_start`  field of the `Trajectory` message.
- Link
Psim
None.
None.
None.

feat(tier4_planning_rviz_plugin): add time from start text to Trajectory

---

control/autoware_predicted_path_checker/src/predicted_path_checker_node/predicted_path_checker_node.cpp
planning/motion_velocity_planner/autoware_motion_velocity_dynamic_obstacle_stop_module/src/dynamic_obstacle_stop_module.cpp

There are currently build issues that can occur because the output of `removeOverlapPoints` is marked `[[no_discard]]` but is discarded.
```
error: ignoring return value of 'T autoware::motion_utils::removeOverlapPoints(const T&, size_t) [with T = std::vector<autoware_planning_msgs::msg::TrajectoryPoint_<std::allocator<void> > >; size_t = long unsigned int]', declared with attribute 'nodiscard' [-Werror=unused-result]
126 |   autoware::motion_utils::removeOverlapPoints(ego_data.trajectory);
|                   
```
This PR fixes the issue in 2 packages.
- Link
Psim
None.
None.
None.

fix(pred_path_checker,dyn_obstacle_stop): use output of removeOverlaps

---

planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/config/detection_area.param.yaml
planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/package.xml
planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/src/manager.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/src/manager.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/src/scene.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/src/scene.hpp

Make it possible to use RTC for detection area module.
:warning: Review https://github.com/autowarefoundation/autoware_launch/pull/1383 at first.
Don't use RTC (Ego stops at stop line only when there are obstacles within detection area)
https://github.com/user-attachments/assets/080a380e-3f3b-47ee-8903-d87cc8f62bd2
Use RTC (Ego stops at stop line of detection area regardless of obstacle existance.)
https://github.com/user-attachments/assets/7abc94fd-f653-4ba6-b570-a53f54de522d
- https://github.com/autowarefoundation/autoware_universe/pull/9802
None.
None.
None.

fix(detection_area): integrate RTC feature

---

visualization/autoware_overlay_rviz_plugin/autoware_overlay_rviz_plugin/include/signal_display.hpp
visualization/autoware_overlay_rviz_plugin/autoware_overlay_rviz_plugin/include/turn_signals_display.hpp
visualization/autoware_overlay_rviz_plugin/autoware_overlay_rviz_plugin/src/signal_display.cpp
visualization/autoware_overlay_rviz_plugin/autoware_overlay_rviz_plugin/src/turn_signals_display.cpp

Currently, the display of turn_signal is blinking. However the blinking feature makes difficult to debug planning modules.  This PR removes the blinking feature.
**before** (x3)
https://github.com/user-attachments/assets/f3f774f7-02b2-4e6a-8755-e01e4ab2208f
**after** (x3)
https://github.com/user-attachments/assets/c1093eda-58c0-4a59-8b25-ba7f33b0329c
- Link
None.
None.
None.

feat(autoware_overlay_rviz_plugin)!: add static blinking option for turn_signal

---

control/autoware_control_validator/src/utils.cpp

This PR fixes a memory-related crash in the control_validator component that occurs when processing large trajectories. The crash was happening in the align_trajectory_with_reference_trajectory function, specifically when using the convertToTrajectory function.
```
1743052338.5723131 [ERROR] [component_container_mt-116]: process has died [pid 4199, exit code -6, cmd '/home/autoware/pilot-auto.xx1/install/rclcpp_components/lib/rclcpp_components/component_container_mt --ros-args -r __node:=control_check_container -r __ns:=/control -p use_sim_time:=False -p wheel_radius:=0.31 -p wheel_width:=0.18 -p wheel_base:=2.75 -p wheel_tread:=1.485 -p front_overhang:=0.8 -p rear_overhang:=0.85 -p left_overhang:=0.105 -p right_overhang:=0.105 -p vehicle_height:=2.5 -p max_steer_angle:=0.55']. …
```

fix(control_validator): memory-related crash when processing large trajectories

---

common/autoware_agnocast_wrapper/cmake/agnocast_wrapper_config_extras.cmake

A build error occurs when this CMake script is used by a user of this package.
- Link
None.
None.
None.

fix(autoware_agnocast_wrapper): invalid comment out

---

common/autoware_agnocast_wrapper/include/autoware/agnocast_wrapper/autoware_agnocast_wrapper.hpp

Fixed invalid include for `polling_subscriber.hpp`
- Link
The include path changed from v0.41.2.
None.
None.

fix(agnocast_wrapper): fix invalid include

---

perception/autoware_multi_object_tracker/config/multi_object_tracker_node.param.yaml
perception/autoware_multi_object_tracker/schema/multi_object_tracker_node.schema.json
perception/autoware_multi_object_tracker/src/debugger/debugger.cpp
perception/autoware_multi_object_tracker/src/debugger/debugger.hpp
perception/autoware_multi_object_tracker/src/multi_object_tracker_node.cpp
perception/autoware_multi_object_tracker/src/multi_object_tracker_node.hpp

Launcher PR
https://github.com/autowarefoundation/autoware_launch/pull/1378
- Link
Tested by running logging simulator
OK:
Warning &Error:
https://github.com/user-attachments/assets/10af0573-4cb9-4806-876e-77699ee27fa1
None.
None.
None.

feat(multi_object_tracker): add diagnostics warning when extrapolation time exceeds limit with latency guarantee enabled

---

simulator/autoware_simple_planning_simulator/src/simple_planning_simulator/simple_planning_simulator_core.cpp

The `TurnIndicatorsReport` msg has not `TurnIndicatorsCommand::NO_COMMAND`(0), but has only `TurnIndicatorsReport::DISABLE`(1). The simple_planning_simulator didn't convert this message properly.
This PR fixed this small bug.
- Link
PR for scenario_simulator: https://github.com/tier4/scenario_simulator_v2/pull/1558
Psim:
None.
None.
None.

fix(simple_planning_simulator): fix a small turn_signal bug

---

common/autoware_agnocast_wrapper/include/autoware/agnocast_wrapper/autoware_agnocast_wrapper.hpp

This fixes the interface of `AUTOWARE_POLLING_SUBSCRIBER` macro.
- Link
Local build is done correctly.
None.
None.
None.

fix(autoware_agnocast_wrapper): typename in AUTOWARE_POLLING_SUBSCRIBER macro

---

common/autoware_agnocast_wrapper/CMakeLists.txt
common/autoware_agnocast_wrapper/package.xml

When a package (ex: autoware_pointcloud_preprocessor) uses `autoware_agnocast_wrapper`, it fails to build:
```
--- stderr: autoware_pointcloud_preprocessor                                   
In file included from /home/veqcc/work/latest_autoware/src/universe/autoware_universe/sensing/autoware_pointcloud_preprocessor/include/autoware/pointcloud_preprocessor/filter.hpp:57,
from /home/veqcc/work/latest_autoware/src/universe/autoware_universe/sensing/autoware_pointcloud_preprocessor/src/filter.cpp:52:
/home/veqcc/work/latest_autoware/install/autoware_agnocast_wrapper/include/autoware/agnocast_wrapper/autoware_agnocast_wrapper.hpp:19:10: fatal error: agnocast/agnocast.hpp: No such file or directory
19 | #include <agnocast/agnocast.hpp>
|          ^~~~~~~~~~~~~~~~~~~~~~~
```
This is because the …

fix(agnocast_wrapper): fix build error

---

system/autoware_default_adapi/src/interface.cpp
system/autoware_default_adapi/test/node/interface_version.py

Release AD API v1.8.0. See [release note page](https://github.com/isamu-takagi/autoware-documentation/blob/feat/adapi-v1.8.0/docs/design/autoware-interfaces/ad-api/release.md) for details.
https://github.com/autowarefoundation/autoware-documentation/pull/658
None
None.
None.
None.

feat(autoware_default_adapi): release adapi v1.8.0

---

.github/sync-files.yaml
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/util.cpp

This PR resolves a critical issue in the `getBackwardPath` function where a segmentation fault occurs when route_handler.getCenterLinePath() returns an empty path.
- Added an early return when the backward path is empty
- Prevents undefined behavior when trying to access elements of an empty container
- Resolves the node crash issue observed in real vehicle experiment
- [TIER IV internal link](https://tier4.atlassian.net/browse/RT0-35983)
None.
None.
None.

fix(start_planner): fix segmentation fault when generating backward path

---

sensing/autoware_pointcloud_preprocessor/package.xml

Used here: https://github.com/autowarefoundation/autoware_universe/blob/main/sensing/autoware_pointcloud_preprocessor/src/pointcloud_densifier/pointcloud_densifier_node.cpp#L20
None.
None.
None.

fix: missing dependency on tf2_sensor_msgs

---

common/autoware_agnocast_wrapper/include/autoware/agnocast_wrapper/autoware_agnocast_wrapper.hpp

Separated `AUTOWARE_MESSAGE_PTR` and `ALLOCATE_OUTPUT_MESSAGE` into unique and shared ones.
- Link
None.
None.
None.

fix(agnocast_wrapper): separate message ptr types into unique and shared

---

planning/autoware_planning_validator/include/autoware/planning_validator/utils.hpp
planning/autoware_planning_validator/src/utils.cpp

In the calculation of lateral acceleration, original implementation was assuming uniform motion, but since acceleration is actually given at each point of the trajectory, changed to calculations based on the assumption of uniformly accelerated motion.
- run psim and driving a route of several kilometers, confirming that values are properly measured and no errors occur.
https://github.com/user-attachments/assets/9dad693d-0f62-41bc-b9be-127f6612de68
None.
None.
None.

feat(planning_validator): improve lateral acc calculation

---

build_depends_humble.repos
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/include/autoware/behavior_path_start_planner_module/start_planner_module.hpp
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/start_planner_module.cpp

closes https://github.com/autowarefoundation/autoware.universe/issues/10237
:exclamation: **Should be merged after** https://github.com/autowarefoundation/autoware_lanelet2_extension/pull/49 **is merged**
:question: What this PR changes:
- `start_planner` does not consider "waypoints" attribute (custom centerline)  assigned to the lanelet but calculated centerline when it judges whether ego is in the middle of the road or not
Instead I propose it is more convenient to query if ego is on the centerline (custom or calculated) whether [use_waypoints](https://github.com/autowarefoundation/autoware_launch/blob/c97fd6203be0b81b8cc4f4548161eca4418a6d66/autoware_launch/config/map/lanelet2_map_loader.param.yaml#L5) : `true` or [use_waypoints](https://github.com/autowarefoundation/autoware_launch/bl …

fix(start_planner): use waypoints as centerline if available

---

control/autoware_control_validator/include/autoware/control_validator/control_validator.hpp
control/autoware_control_validator/src/control_validator.cpp
control/autoware_control_validator/test/test_control_validator.cpp

Initially, control_validator was implemented as a single-function validator.
However, it has since grown significantly to incorporate five distinct detection capabilities, each with a high independence.
This historical evolution has led to the current implementation of autoware_control_validator becoming somewhat complex and causing some warning issues.
For example, I have identified the following issues:
- The node member variable LowpassFilter1d `vehicle_vel_` is used in both the velocity_validator and overrun_validator, even though access to this variable is sensitive.
- In the `ControlValidator::validate()` function, both the local variable `reference_trajectory` and the global `current_reference_trajectory` are accessed, despite them being references to the same underlying data.
This …

refactor(control validaor): refactor control_validator

---

launch/tier4_simulator_launch/launch/simulator.launch.xml

Remove the dependency on autoware_launch from tier4_simulator_launch.
Related to https://github.com/autowarefoundation/autoware_launch/pull/1392.
- https://github.com/autowarefoundation/autoware_universe/pull/10404#discussion_r2030570800
1. Checkout https://github.com/autowarefoundation/autoware_launch/pull/1392
2. Run planning simulator and drive in autonomous mode.
None.
None.
None.

feat(tier4_simulator_launch): remove exec_depend on autoware_launch

---

build_depends_humble.repos
visualization/tier4_traffic_light_rviz_plugin/CMakeLists.txt

This PR reflects in `autoware_universe` the workaround applied in `autoware_cmake` to address the issue in `autoware_lanelet2_extension` version 0.7.0.
- https://github.com/autowarefoundation/autoware_universe/issues/10410
- https://github.com/autowarefoundation/autoware_cmake/pull/24
- https://github.com/autowarefoundation/autoware/pull/6007
None.
None.
None.

fix(build_depends_humble.repos): update `autoware_cmake` to address #10410

---

sensing/autoware_pointcloud_preprocessor/include/autoware/pointcloud_preprocessor/pointcloud_densifier/pointcloud_densifier_node.hpp

Locally build fails, so I just added the includes that seemed to be missing
- Link
None.
None.
None.

fix(pointcloud_preprocessor): added missing includes

---

perception/autoware_compare_map_segmentation/src/voxel_based_compare_map_filter/node.hpp

Build failed locally so I just added the seemingly missing includes
- Link
None.
None.
None.

fix(autoware_compare_map_segmentation): missing includes

---

perception/autoware_lidar_transfusion/config/transfusion_common.param.yaml
perception/autoware_lidar_transfusion/include/autoware/lidar_transfusion/lidar_transfusion_node.hpp
perception/autoware_lidar_transfusion/launch/lidar_transfusion.launch.xml
perception/autoware_lidar_transfusion/schema/transfusion_common.schema.json
perception/autoware_lidar_transfusion/src/lidar_transfusion_node.cpp

This PR adds processing time diagnostics.
If the processing time exceeds `max_allowed_processing_time_ms`, a warning topic will be published.
Consecutive delays will be also checked.
If the difference of two timestamp (current and last in-time processed timestamp) is larger than `max_acceptable_consecutive_delay_ms`, it will determine as an error state.
If the new processing time is below the `max_allowed_processing_time_ms`, it will update the timestamp of last in-time processed case.
- Link
Tested by checking the rqt_runtime_monitor.
Run rqt_runtime_monitor by
```sh
ros2 run rqt_runtime_monitor rqt_runtime_monitor
```
None.
None.
None.

feat(lidar_transfusion): add diagnostics for processing time

---

perception/autoware_multi_object_tracker/config/multi_object_tracker_node.param.yaml
perception/autoware_multi_object_tracker/include/autoware/multi_object_tracker/odometry.hpp
perception/autoware_multi_object_tracker/lib/odometry.cpp
perception/autoware_multi_object_tracker/schema/multi_object_tracker_node.schema.json
perception/autoware_multi_object_tracker/src/multi_object_tracker_node.cpp

Solves https://github.com/autowarefoundation/autoware_universe/issues/10427.
Related PR: https://github.com/autowarefoundation/autoware_launch/pull/1397.
- Link
None.
None.
None.

feat(autoware_multi_object_tracker): vehicle's ego frame as a parameter

---

planning/autoware_path_optimizer/src/node.cpp

When applying the input velocity to the output of MPT, the initial pose of the output of MPT is used to trim the input trajectory. In certain cases when  there is a sharp U-turn, depending on the width of the adjacent, opposing lane into which Ego is turning into, the initial pose of the output trajectory may be mapped to a point in the opposing lane - leading to incorrect input velocity application.
This PR adds a yaw-thresholded closest-distance point search step to ensure that this doesn't occur and also trims the output of MPT to start from the current ego pose so that the initial pose of the MPT output will always map to a point within the current lane.
https://tier4.atlassian.net/browse/RT0-35764
Evaluator: …

fix(autoware_path_optimizer): incorrect application of input velocity due to badly mapping output trajectory to input trajectory

---

evaluator/autoware_control_evaluator/include/autoware/control_evaluator/control_evaluator_node.hpp
evaluator/autoware_control_evaluator/include/autoware/control_evaluator/metrics/metric.hpp
evaluator/autoware_control_evaluator/src/control_evaluator_node.cpp
evaluator/autoware_control_evaluator/test/test_control_evaluator_node.cpp

This PR fixes 3 bugs about metric JSON outputs.
- The `vel`, `acc`, and `jark` statistics were not output to the JSON.
- The `GoalDeviation` metrics are now only counted when the ego stops near the stop line.
- Output `StopDeviation` metrics.
https://tier4.atlassian.net/browse/RT1-9859
Psim
None.
The original metric names of published  `vel`, `acc`, and `jark` are changed:
`kinematic_state/vel`-> `velocity`
`kinematic_state/acc`-> `acceleration`
`kinematic_state/jerk`-> `jerk`
Before:
After:
None.

fix(control_evaluator): fix bugs about output_metrics

---

perception/autoware_radar_object_tracker/config/radar_object_tracker.param.yaml
perception/autoware_radar_object_tracker/src/radar_object_tracker_node.cpp
perception/autoware_radar_object_tracker/src/radar_object_tracker_node.hpp

This PR adds a diagnostic to radar_object_tracker to check the radar topic arrives within a specified period.
`radar_data_stale_threshold_ms` will determine radar topic input is alive.
If the duration since last process time exceeds `radar_data_stale_threshold_ms`, it will send a warning.
This must merge with https://github.com/autowarefoundation/autoware_launch/pull/1399
- Link
Tested by checking the rqt_runtime_monitor.
Run rqt_runtime_monitor by
```sh
ros2 run rqt_runtime_monitor rqt_runtime_monitor
```
None.
None.
None.

feat(radar_object_tracker): add diagnostics for checking radar input status

---

evaluator/autoware_planning_evaluator/src/planning_evaluator_node.cpp

This PR makes a small change to record modified_goal related output_metrics only when the ego stops close to the goal. 
- Link
Psim
None.
None.
None.

chore(autoware_planning_evaluator): record goal_stop_deviation only when ego stop

---

common/autoware_universe_utils/include/autoware/universe_utils/geometry/geometry.hpp
common/autoware_universe_utils/src/geometry/geometry.cpp

Add 2 convenience functions when working with `autoware_universe_utils::Point2d` to convert to `Point` message or efficiently calculate segment intersections.
- Link
None.
None.
None.

feat(autoware_universe_utils): add intersect and getPoint for Point2d type

---

planning/autoware_planning_validator/README.md
planning/autoware_planning_validator/config/planning_validator.param.yaml
planning/autoware_planning_validator/include/autoware/planning_validator/parameters.hpp
planning/autoware_planning_validator/src/planning_validator.cpp
planning/autoware_planning_validator/test/src/test_planning_validator_helper.cpp

parameter change https://github.com/autowarefoundation/autoware_launch/pull/1402 should be merged first
- Split steering and steering_rate into separate ValidityCheck parameters
- Implemented consistent brace initialization `{}` for all parameters
- run psim
- set steering rate threshold as very small value and detect error with following message 
```
[planning_validator_node-36] [ERROR 1744369637.232292726] [planning.planning_validator]: Caution! Invalid Trajectory published. (publishTrajectory():271)
[planning_validator_node-36] [WARN 1744369637.232379583] [planning.planning_validator]: planning trajectory expected steering angle rate is too high!! (operator()():713)
``` 
None.
None.
None.

refactor(planning_validator): separate validation check for steering and steering rate

---

perception/autoware_multi_object_tracker/lib/tracker/motion_model/bicycle_motion_model.cpp

When a bicycle motion model tracker gets update with velocity and without yaw, the tracker couldn't get update.
It turns out that there is a bug on the renovation vector has wring dimension size.
- Before
```c++
// update state, with velocity
constexpr int DIM_Y = 4;
// update state
Eigen::MatrixXd Y(DIM_Y, 1);
Y << x, y, vel;
```
- after
```c++
// update state, with velocity
constexpr int DIM_Y = 3;
// update state
Eigen::MatrixXd Y(DIM_Y, 1);
Y << x, y, vel;
```
- Link
None.
None.
None.

fix(autoware_multi_object_tracker): fix bicycle renovation vector dimension

---

control/autoware_control_validator/README.md
control/autoware_control_validator/config/control_validator.param.yaml
control/autoware_control_validator/include/autoware/control_validator/control_validator.hpp
control/autoware_control_validator/msg/ControlValidatorStatus.msg
control/autoware_control_validator/src/control_validator.cpp

To guarantee DO NOT overrun the stop points or the goal point, this PR adds a new validation fetature.
The node publish error diag for the cases which the ego will overrun the stop points even if the ego decelerate by assumed deceleration value.
https://github.com/autowarefoundation/autoware_universe/pull/10422/files#diff-492e13c1cee80cc9825bff55dc294565ae2382b5e117a5f7f0cc03512280b08fR126-R127
https://github.com/autowarefoundation/autoware_launch/pull/1394
- Link
With connnecting MRM,
- engage available in psim 
- tier4 internal DLR tests
- tier4 internal scenario tests
None.
None.
<
None.

feat(control_validator): add over run estimation feature

---

.github/sync-files.yaml
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/config/out_of_lane.param.yaml
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_module.hpp
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/types.hpp

Currently, in `out_of_lane_module`, when a collision is detected and a stop pose is computed. The stop pose will remain as long as a collision is detected within the `min_duration` value, even if the new detected collision is far away from the original inserted stop pose. Which can, in certain situations, result in unnecessary stopping behavior.
This PR addresses issue by introducing a distance threshold for preserving the previous stop pose. If a collision is detected within a threshold distance from the previous stop pose, then the stop pose is kept and the timer is reset.
[Launcher PR](https://github.com/autowarefoundation/autoware_launch/pull/1404)
- PSIM.
- [TIER IV Internal Evaluator](https://evaluation.tier4.jp/evaluation/reports/6ee6f5dd-c993-5a46-a290-85d244ff840c?project_id=prd_j …

feat(out_of_lane): revise logic for using previous stop pose

---

.github/sync-files.yaml
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/config/out_of_lane.param.yaml
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_collisions.cpp
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_collisions.hpp
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/types.hpp

Currently `out_of_lane_module` uses one `ttc.threshold` value to check for collision and insert a stop point. If the measured ttc value is close to the threshold value and varies between iterations, it could result in a flickering stop decision.
This PR addressed the issue by introducing a second threshold value `ttc.release_threshold` for hysteresis. At first `ttc.threshold` is used to detect a collision and insert a stop pose. Then `ttc.release_threshold` is used to check for collisions to determine if the stop pose should be kept or can be released.
[Launcher PR](https://github.com/autowarefoundation/autoware_launch/pull/1404)
- PSIM
- [TIER IV Internal Evaluator](https://evaluation.tier4.jp/evaluation/reports/6ee6f5dd-c993-5a46-a290-85d244ff840c?project_id=prd_jt)
None.
None.
| Change …

feat(out_of_lane): add ttc threshold for releasing stop decision

---

perception/autoware_multi_object_tracker/lib/association/association.cpp
perception/autoware_multi_object_tracker/lib/uncertainty/uncertainty_processor.cpp

Add  required headers. https://github.com/autowarefoundation/autoware_core/pull/385 revealed this issue.
https://github.com/autowarefoundation/autoware_core/pull/385 
Check if the universe build passes.
None.
None.
None.

fix(multi_object_tracker): add required headers

---

planning/autoware_planning_validator/package.xml

This PR fixes building the `autoware_planning_validator` package by adding the `angles` dependency.
- https://github.com/autowarefoundation/autoware-deb-packages/issues/140
None.
None.
None.

build(autoware_planning_validator): fix missing angles dependency

---

planning/autoware_path_optimizer/package.xml

This PR fixes a missing dependency in the `autoware_path_optimizer` package.
- https://github.com/autowarefoundation/autoware-deb-packages/issues/139
None.
None.
None.

build(autoware_path_optimizer): fix missing diagnostic_updater dependency

---

perception/autoware_radar_object_tracker/package.xml

This PR fixes the missing diagnostic_updater dependecy for autoware_radar_object_tracker
- https://github.com/autowarefoundation/autoware-deb-packages/issues/142
None.
None.
None.

build(autoware_radar_object_tracker): fix missing diagnostic_updater dependency

---

perception/autoware_image_projection_based_fusion/launch/pointpainting_fusion.launch.xml

This PR adds missing parameter `common_param_path` to use pointpainting when not use container. Caused by https://github.com/autowarefoundation/autoware_universe/pull/10397
- Link
https://evaluation.ci.tier4.jp/evaluation/reports/5968877a-f3ae-52ea-bce3-aaeeac420201?project_id=prd_jt
None.
None.
None.

fix(autoware_image_projection_based_fusion): add missing params `common_param_path` when not use container

---

.github/workflows/build-and-test-differential-arm64.yaml
.github/workflows/build-and-test-differential.yaml
.github/workflows/build-and-test-packages-above-differential.yaml
.github/workflows/check-build-depends.yaml
.github/workflows/clang-tidy-differential.yaml

Current implementation of build testing workflow has hard coding conditions.
To be robust with branch name changing, I fixed the conditions in workflow files.
- Link
https://github.com/autowarefoundation/autoware_universe/actions/runs/14529930679/job/40767929231?pr=10502
None.
None.
None.

ci: fix conditions of prepare build_depends.repos file (main branch)

---

system/autoware_system_monitor/src/process_monitor/process_monitor.cpp

fix sompile issue
compile using colcon with latest autoware main branch code, i got an error like below
it seems that the author want to set value '\0' to the last element of the vector to use it as a terminator
i look through the code make sure there is null pointor protection code serveral lines before, so i modify the last element access method by a tiny fix
- Link
1. using AWF official docker
2. clone the latest main branch code
3. compile the entier autoware with " colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release --symlink-install"
4. no error occours any more
None.
None.
None.

fix(autoware_system_monitor): quick fix for autoware_system_monitor

---

planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/config/obstacle_slow_down.param.yaml
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/src/obstacle_slow_down_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/src/parameters.hpp

universe changes for https://github.com/autowarefoundation/autoware_core/pull/377
Removes point-cloud clustering for autoware_obstacle_stop and autoware_obstacle_slowdown.
- https://tier4.atlassian.net/browse/RT1-9554
Evaluator: https://evaluation.tier4.jp/evaluation/reports/1eb4e631-9375-5403-a5e7-0b19c4f963a6/?page=1&project_id=prd_jt (All Pass)
None.
None.
None.

feat(autoware_motion_velocity_planner): point-cloud clustering optimization

---

planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/src/util.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/test/test_util.cpp

extend the attention area if there is a next staright lanelet.
https://tier4.atlassian.net/browse/RT0-35865?focusedCommentId=214005
- https://evaluation.tier4.jp/evaluation/reports/dca91b8e-633a-5b4c-a9a9-ffdb649b2285?project_id=prd_jt
None.
None.
None.

feat(blind_spot): extend attention area to straight lanelet

---

control/autoware_operation_mode_transition_manager/package.xml
control/autoware_operation_mode_transition_manager/src/node.cpp
control/autoware_operation_mode_transition_manager/src/node.hpp
control/autoware_operation_mode_transition_manager/src/state.cpp
control/autoware_operation_mode_transition_manager/src/state.hpp

The package has a lot of unnecessary member variables which decreases the maintainability and readability.
This PR eliminates the member variables as much as possible.
can transit the operation mode on the simple planning simulator
None.
None.
None.

refactor(operation_mode_transition_manager): less member variable

---

planning/behavior_velocity_planner/autoware_behavior_velocity_virtual_traffic_light_module/src/utils.hpp

avoid the usage of duplicated function
https://github.com/autowarefoundation/autoware_core/pull/429
- https://evaluation.tier4.jp/evaluation/reports/e6b5c106-3b3e-52e4-8f5d-e1a2e87a96b7?project_id=prd_jt
None.
None.
None.

refactor(virtual_traffic_light, QC): replace checkCollision with autoware_utils_geometry

---

planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/package.xml

To fix the build error in autoware_core
https://github.com/autowarefoundation/autoware_core/actions/runs/14606864551/job/40977525485?pr=429
- Link
None.
None.
None.

chore(motion_velocity_run_out): add diagnostic_updater for dependency resolve

---

launch/tier4_simulator_launch/launch/simulator.launch.xml

This PR remove params of traffic_light_selector.
https://github.com/autowarefoundation/autoware_universe/pull/10352
- Link
None.
None.
None.

chore(simulator.launch): remove params of traffic_light_selector

---

perception/autoware_image_projection_based_fusion/src/camera_projection.cpp

Based on cppcheck `redundantAssignment` warning
```
perception/autoware_image_projection_based_fusion/src/camera_projection.cpp:83:39: style: Variable 'y_bottom' is assigned an expression that holds the same value. [redundantAssignment]
if (ray_bottom_left.y < y_bottom.y) y_bottom = ray_bottom_left;
^
perception/autoware_image_projection_based_fusion/src/camera_projection.cpp:71:24: note: y_bottom is assigned 'ray_bottom_left' here.
cv::Point3d y_bottom = ray_bottom_left;
^
perception/autoware_image_projection_based_fusion/src/camera_projection.cpp:83:39: note: Variable 'y_bottom' is assigned an expression that holds the same value.
if (ray_bottom_left.y < y_bottom.y) y_bottom = ray_bottom_left;
^
```
I think the initial value of `y_bottom` is wrong.
- Link
None.
None. …

fix(image_projection_based_fusion): fix redundantAssignment warning

---

localization/autoware_gyro_odometer/package.xml
localization/autoware_gyro_odometer/src/gyro_odometer_core.cpp
localization/autoware_gyro_odometer/src/gyro_odometer_core.hpp

This PR fixes the include headers of `autoware_utils` to follow the current package style (`autoware_utils_*`) for `gyro_odometer` package.
- https://github.com/autowarefoundation/autoware_universe/issues/10482
Checked the behavior with the sample rosbag and confirmed it works as expected.
None.
None.
None.

fix(autoware_gyro_odometer): fix deprecated autoware_utils header

---

localization/autoware_ndt_scan_matcher/include/autoware/ndt_scan_matcher/map_update_module.hpp
localization/autoware_ndt_scan_matcher/include/autoware/ndt_scan_matcher/ndt_scan_matcher_core.hpp
localization/autoware_ndt_scan_matcher/package.xml
localization/autoware_ndt_scan_matcher/src/ndt_scan_matcher_core.cpp

This PR fixes the include headers of `autoware_utils` to follow the current package style (`autoware_utils_*`) for autoware_ndt_scan_matcher package.
- https://github.com/autowarefoundation/autoware_universe/issues/10489 
None.
None.
None.

fix(autoware_ndt_scan_matcher): fix deprecated autoware_utils header

---

perception/autoware_multi_object_tracker/src/processor/input_manager.hpp

Based on cppcheck `unusedFunction` warning
```
perception/autoware_multi_object_tracker/src/processor/input_manager.hpp:99:0: style: The function 'isChannelSpawnEnabled' is never used. [unusedFunction]
bool isChannelSpawnEnabled(const uint & index) const
^
```
- Link
None.
None.
None.

fix(multi_object_tracker): remove unused function isChannelSpawnEnabled

---

launch/tier4_perception_launch/launch/object_recognition/detection/detection.launch.xml
launch/tier4_perception_launch/launch/object_recognition/tracking/tracking.launch.xml
launch/tier4_perception_launch/launch/perception.launch.xml

We accept a list of perception modes.
However, when the user selects a nonexistent one it would display no error.
This PR forces the perception mode to be an element of the list or fail the launch
- Link
Autoware launchs
None.
None.
None.

chore(tier4_perception_launch): enforce valid perception modes

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/util.cpp

this PR is one of the ones to remove the usage of `getLaneletSequence()` with `only_route_lanes = false`
- https://github.com/autowarefoundation/autoware_core/pull/431
- https://evaluation.tier4.jp/evaluation/reports/c891c69f-30ca-5707-9d6a-7b0abce78e13?project_id=prd_jt
None.
None.
None.

refactor(goal_planner): do not use only_route_lanes = false

---

planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/src/collisions.cpp

In some environments `tf2/utils.hpp` does not exist which causes the package build to fail.
This PR switched to using `tf2/utils.h`.
- Link
None.
None.
None.

fix(motion_velocity_planner/run_out): fix tf2 include (.hpp->.h)

---

planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/include/autoware/behavior_velocity_blind_spot_module/manager.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/manager.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/src/manager.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/manager.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_no_drivable_lane_module/src/manager.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_no_stopping_area_module/src/manager.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_occlusion_spot_module/src/manager.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_run_out_module/src/manager.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_speed_bump_module/src/manager.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_template_module/src/manager.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/manager.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_virtual_traffic_light_module/src/manager.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_walkway_module/src/manager.hpp

Universe changes for https://github.com/autowarefoundation/autoware_core/pull/433
- Link
planning simulator worked.
None.
None.
None.

feat(behavior_velocity_planner): only wait for the required subscriptions

---

perception/autoware_bevfusion/CMakeLists.txt

Fix build failure when using ninja.
The error was caused by using `$(...)` instead of `${...}` for a CMake variable, which breaks Ninja builds.
- Link
Build  success.
None.
None.
None.

fix(autoware_bevfusion): build error when using ninja-build tool

---

localization/autoware_ndt_scan_matcher/include/autoware/ndt_scan_matcher/hyper_parameters.hpp
localization/autoware_ndt_scan_matcher/include/autoware/ndt_scan_matcher/ndt_omp/multigrid_ndt_omp.h
localization/autoware_ndt_scan_matcher/include/autoware/ndt_scan_matcher/ndt_omp/ndt_struct.hpp

There is an implicit conversion error in the code. In struct NdtParams [resolution](https://github.com/autowarefoundation/autoware_universe/blob/65c834c77e8b2f36f746f20e1cb1db9e6b620a04/localization/autoware_ndt_scan_matcher/include/autoware/ndt_scan_matcher/ndt_omp/ndt_struct.hpp#L94) is double, and [VoxelGrid setLeafSize (const Eigen::Vector4f &leaf_size)](https://github.com/PointCloudLibrary/pcl/blob/f36a69a5e89953708990c4669317f989d532cf08/filters/include/pcl/filters/voxel_grid.h#L221) takes floats. 
https://github.com/autowarefoundation/autoware_universe/blob/65c834c77e8b2f36f746f20e1cb1db9e6b620a04/localization/autoware_ndt_scan_matcher/include/autoware/ndt_scan_matcher/ndt_omp/ndt_struct.hpp#L94
https://github.com/PointCloudLibrary/pcl/blob/f36a69a5e89953708990c4669317f989d532cf08/f …

fix(ndt_scan_matcher): implicit double to float conversion

---

sensing/autoware_radar_threshold_filter/README.md
sensing/autoware_radar_threshold_filter/schema/radar_threshold_filter.schema.json

…ME file
- Implement the ROS Node configuration layout described in [Autoware Foundation Discussion #3371](https://github.com/orgs/autowarefoundation/discussions/3371) for the (autoware_cluster_merger)
- Remove duplication of parameter declaration between the source code and the parameter file.
- Remove the default value from the source code to ensure all parameter values are passed from the parameter files.
- Use types that match those returned from declare_parameter() to prevent confusion and potential coding errors.
- Move the default parameter file to a standardized location. Use the JSON Schema for that.
- Create the schema
- Link
Successfully build using colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release --packages-up-to …

feat(radar_threshold_filter): add schema file for radar_threshold_filter and upadted the README file

---

planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/src/scene.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/src/utils.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/src/utils.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/test/test_utils.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection_prepare_data.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_no_stopping_area_module/src/scene_no_stopping_area.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_no_stopping_area_module/src/utils.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_no_stopping_area_module/src/utils.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_no_stopping_area_module/test/test_utils.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/scene.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/utils.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/utils.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/test/test_utils.cpp

This PR makes `behavior_velocity_planner` modules to extend the stop line to intersect the path bounds.
See https://github.com/autowarefoundation/autoware_core/pull/367 for details.
This PR and https://github.com/autowarefoundation/autoware_core/pull/367 must be merged at the same time.
Internal Ticket link : https://tier4.atlassian.net/browse/RT1-9244
None.
None.
None.

feat(behavior_velocity_planner): extend stop line to path bound

---

perception/autoware_probabilistic_occupancy_grid_map/include/autoware/probabilistic_occupancy_grid_map/costmap_2d/occupancy_grid_map_base.hpp
perception/autoware_probabilistic_occupancy_grid_map/lib/costmap_2d/occupancy_grid_map_base.cpp

The first iteration was printing errors due to the delta poses between the null pose and the first pose being to big.
However, for the first iteration, the update routine is not needed (the map is empty), so I just skipped it
- Link
Tested that the error disappeared with this PR
None.
None.
None.

fix(autoware_probabilistic_occupancy_grid_map): skipped first iteration

---

sensing/autoware_pointcloud_preprocessor/config/ring_outlier_filter_node.param.yaml
sensing/autoware_pointcloud_preprocessor/include/autoware/pointcloud_preprocessor/outlier_filter/ring_outlier_filter_node.hpp
sensing/autoware_pointcloud_preprocessor/schema/ring_outlier_filter_node.schema.json
sensing/autoware_pointcloud_preprocessor/src/outlier_filter/ring_outlier_filter_node.cpp

This PR updates parameter for filtering out outliers:
- Set `object_length_threshold = 0.05` as a default value.
- Remove process to check the number of points inside of cluster.
- PR to update `aip_launcher`: https://github.com/tier4/aip_launcher/pull/438
[TIER IV INTERNAL EVALUATOR RESULT](https://evaluation.ci.tier4.jp/evaluation/reports/40cb0f7c-4b19-5977-9b3e-b5a34079d7de?project_id=prd_jt)
None.
None.
None.

feat(ring_outlier_filter): update filtering parameter and process

---

planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_module.cpp

Convert calls of `RCLCPP_WARN` into `RCLCPP_WARN_THROTTLE` to prevent the `out_of_lane` module from spamming the logs with WARN messages.
- Link
None.
None.
None.

fix(out_of_lane): throttle log message to avoid spamming the logs

---

planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/src/objects_filtering.cpp
planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/src/objects_filtering.hpp

Based on cppcheck `unusedFunction` warning
```
<error id="unusedFunction" severity="style" msg="The function &apos;get_first_intersecting_segment_idx&apos; is never used." verbose="The function &apos;get_first_intersecting_segment_idx&apos; is never used." cwe="561">
<location file="planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/src/objects_filtering.cpp" line="175" column="0"/>
<symbol>get_first_intersecting_segment_idx</symbol>
</error>
```
- Link
None.
None.
None.

fix(motion_velocity_planner): remove unused function

---

perception/autoware_probabilistic_occupancy_grid_map/lib/costmap_2d/occupancy_grid_map_base.cpp

Fixes issue with delayed OGM output.
- Link
None.
None.
None.

fix(autoware_probabilistic_occupancy_grid_map): incorrect placement of updateOrigin init call check

---

perception/autoware_radar_object_tracker/include/autoware_radar_object_tracker/utils/radar_object_tracker_utils.hpp
perception/autoware_radar_object_tracker/package.xml
perception/autoware_radar_object_tracker/src/association/data_association.cpp
perception/autoware_radar_object_tracker/src/tracker/model/constant_turn_rate_motion_tracker.cpp
perception/autoware_radar_object_tracker/src/tracker/model/linear_motion_tracker.cpp
perception/autoware_radar_object_tracker/src/utils/radar_object_tracker_utils.cpp

~Fix namespace error referring autoware_utils.~  Adaptation to autoware_utils porting design.
Project version: according to autoware-nightly.repos
https://github.com/autowarefoundation/autoware_universe/issues/10469
None.
None.
None.

feat(autoware_radar_object_tracker): adaptation to autoware_utils

---

perception/autoware_compare_map_segmentation/src/voxel_based_compare_map_filter/node.cpp

When the filtered pointcloud is empty, we expect to publish the empty message.
Fix a check of the output data, and split in the case the output message is a normal empty message.
- Link
- [TIER IV internal link](https://star4.slack.com/archives/C03S84LDJGG/p1745981452114449)
None.
None.
None.

fix(autoware_compare_map_segmentation): handle empty output point cloud 

---

planning/autoware_external_velocity_limit_selector/package.xml

This pull request includes a minor update to the `package.xml` file for the `autoware_external_velocity_limit_selector` package. The change involves removing Shinnosuke Hirakawa as a maintainer for the package.
- None
None.
None.
None.

chore(autoware_external_velocity_limit_selector): update code owner

---

build_depends_humble.repos

- https://github.com/autowarefoundation/autoware_universe/pull/10576 with this PR, we have merged this commit: https://github.com/autowarefoundation/autoware_universe/commit/5c5561fce7277243b748d3807ff6aca6930a29cd
- With that commit, the Autoware was able to compile and run with those versions.
- With this PR, I'm bringing those changes to also to the main branch to keep things consistent and changes minimal between the branches.
**Changes:**
- This Universe tag required to update Autoware Core from `0.3.0` ➡️ `1.1.0` due to many moved packages.
- autoware_lanelet2_extension: `0.7.0` ➡️ `0.7.1`
- autoware_adapi_msgs: `e62ea6fdb9ee50e49c7642c77e85250cb15b8e80` ➡️ `12287684e096a02d279299a7e6cb44740fc34467` (current main HEAD)
- We should make a proper release for this some time.
- …

build: update build_depends_humble.repos for 0.44.1 release

---

sensing/autoware_radar_objects_adapter/config/radar_objects_adapter.param.yaml
sensing/autoware_radar_objects_adapter/include/autoware/radar_objects_adapter/radar_objects_adapter.hpp
sensing/autoware_radar_objects_adapter/launch/radar_objects_adapter.launch.xml
sensing/autoware_radar_objects_adapter/schema/radar_objects_adapter.schema.json
sensing/autoware_radar_objects_adapter/src/radar_objects_adapter.cpp
sensing/autoware_radar_objects_adapter/src/radar_objects_adapter.hpp

feat(autoware_radar_objects_adapter): add publisher for tracks with uuid

---

control/autoware_control_validator/include/autoware/control_validator/control_validator.hpp
control/autoware_control_validator/include/autoware/control_validator/debug_marker.hpp
control/autoware_control_validator/src/control_validator.cpp
control/autoware_control_validator/src/debug_marker.cpp
control/autoware_control_validator/test/test_control_validator.cpp

- ~~Added common velocity and acceleration filters to ControlValidator class~~
- Added detailed error message generation for virtual wall display
- Updated tests to match new interfaces while maintaining test coverage
None.
None.
None.

refactor(control_validator): visualize stop reason to virtual wall

---

localization/yabloc/yabloc_common/package.xml
localization/yabloc/yabloc_common/src/ll2_decomposer/ll2_decomposer_core.cpp

This PR fixes the include headers of `autoware_utils` to follow the current package style (`autoware_utils_*`) for `yabloc_common` package.
- https://github.com/autowarefoundation/autoware_universe/issues/10484
None.
None.
None.

fix(yabloc_common): fix deprecated autoware_utils header

---

localization/yabloc/yabloc_particle_filter/package.xml
localization/yabloc/yabloc_particle_filter/src/camera_corrector/camera_particle_corrector_core.cpp
localization/yabloc/yabloc_particle_filter/src/ll2_cost_map/hierarchical_cost_map.cpp

This PR fixes the include headers of `autoware_utils` to follow the current package style (`autoware_utils_*`) for `yabloc_particle_filter` package.
- https://github.com/autowarefoundation/autoware_universe/issues/10485
None.
None.
None.

fix(yabloc_particle_filter): fix deprecated autoware_utils header

---

localization/autoware_pose_estimator_arbiter/example_rule/src/switch_rule/pcd_map_based_rule.cpp
localization/autoware_pose_estimator_arbiter/package.xml
localization/autoware_pose_estimator_arbiter/src/pose_estimator_arbiter.hpp
localization/autoware_pose_estimator_arbiter/src/pose_estimator_arbiter_core.cpp

This PR fixes the include headers of autoware_utils to follow the current package style (autoware_utils_*) for autoware_pose_estimator_arbiter package.
- https://github.com/autowarefoundation/autoware_universe/issues/10488
None.
None.
None.

fix(autoware_pose_estimator_arbiter): fix deprecated autoware_utils header

---

planning/motion_velocity_planner/autoware_motion_velocity_dynamic_obstacle_stop_module/src/dynamic_obstacle_stop_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/src/run_out_module.cpp

This PR adds a header `autoware_utils/ros/published_time_publisher.hpp` since the change in https://github.com/autowarefoundation/autoware_core/pull/445 makes the header to be missing (it was included from other files).
- Link
None.
None.
None.

fix(motion_velocity_planner): add missing header

---

planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_merge_from_private_road.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_no_drivable_lane_module/src/scene.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_occlusion_spot_module/src/scene_occlusion_spot.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_rtc_interface/include/autoware/behavior_velocity_rtc_interface/scene_module_interface_with_rtc.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_run_out_module/src/scene.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_speed_bump_module/src/scene.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_template_module/src/scene.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_virtual_traffic_light_module/src/scene.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_virtual_traffic_light_module/src/utils.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_walkway_module/src/scene_walkway.hpp

This PR add autoware_utils headers of `geometry.hpp`, `time_keeper.hpp` since the change in https://github.com/autowarefoundation/autoware_core/pull/441 makes the header to be missing (it was included from other files).
- Link
None.
None.
None.

fix(behavior_velocity_planner): add missing header

---

planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp

This PR adds a header `autoware_utils/geometry/boost_polygon_utils.hpp` since the change in [this PR](https://github.com/autowarefoundation/autoware_core/pull/448) makes the header to be missing (it was included from other files).
- Link
None.
None.
None.

fix(behavior_velocity_crosswalk_module): add missing header 

---

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/config/static_obstacle_avoidance.param.yaml
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/data_structs.hpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/parameter_helper.hpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/schema/static_obstacle_avoidance.schema.json
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp

This pull request adds a flag to wait for operator approval when the ego vehicle needs to use the opposite lane. This change enhances the safety of the static obstacle avoidance feature by ensuring that entering the oncoming lane is done with operator confirmation.
```yaml
detection_reliability: "reliable"
```
This feature is particularly important in urban areas or on roads with heavy traffic. By requiring operator approval before entering the opposite lane, the system ensures safer operation and minimizes potential disruptions to surrounding traffic.
:warning: Please approve following PR at first.
- https://github.com/autowarefoundation/autoware_launch/pull/1431
https://github.com/user-attachments/assets/0eb959e9-d382-4714-ae77-02f5dfb61a96
None.
None.
None.

feat(static_obstacle_avoidance): add flag to wait approval when the ego uses opposite lane

---

perception/autoware_probabilistic_occupancy_grid_map/include/autoware/probabilistic_occupancy_grid_map/utils/cuda_pointcloud.hpp

I added the condition of `point_step > 0` to avoid the error caused by division by zero.
This is the glog dumped when `PointcloudBasedOccupancyGridMapNode` died with the error.
```
[component_container_mt-1] *** Aborted at 1746763152 (unix time) try "date -d @1746763152" if you are using GNU date ***
[component_container_mt-1] PC: @                0x0 (unknown)
[component_container_mt-1] *** SIGFPE (@0x7f5c1cd228c7) received by PID 375013 (TID 0x7f5cf0ff1640) from PID 483535047; stack trace: ***
[component_container_mt-1]     @     0x7f5d124404d6 google::(anonymous namespace)::FailureSignalHandler()
[component_container_mt-1]     @     0x7f5d11842520 (unknown)
[component_container_mt-1]     @     0x7f5c1cd228c7 CudaPointCloud2::fromROSMsgAsync()
[component_container_mt-1]     @ …
```

fix(autoware_probabilistic_occupancy_grid_map): fix to avoid division by zero

---

common/autoware_adapi_specs/include/autoware/adapi_specs/fail_safe.hpp
system/autoware_default_adapi/CMakeLists.txt
system/autoware_default_adapi/config/default_adapi.param.yaml
system/autoware_default_adapi/launch/default_adapi.launch.py
system/autoware_default_adapi/package.xml
system/autoware_default_adapi/src/mrm_request.cpp
system/autoware_default_adapi/src/mrm_request.hpp

**This PR depends on https://github.com/autowarefoundation/autoware_adapi_msgs/pull/91**
The MRM request API implementation publishes `/diagnostics`. MRM is triggered by this diagnostics.
- [MRM request API](https://autowarefoundation.github.io/autoware-documentation/main/design/autoware-interfaces/ad-api/features/fail-safe/#mrm-request)
- https://github.com/autowarefoundation/autoware/issues/3096
1. Launch planning simulation.
2. Change mode to autonomous.
3. Execute this command and check that the MRM is operating.
```
ros2 service call /api/fail_safe/mrm_request/send autoware_adapi_v1_msgs/srv/SendMrmRequest "{request: {strategy: 2}}"
````
4. Execute this command and check that the MRM is canceled.
```
ros2 service call /api/fail_safe/mrm_request/send …
```

feat(default_adapi): add mrm request api

---

system/autoware_default_adapi/config/default_adapi.param.yaml
system/autoware_default_adapi/package.xml
system/autoware_default_adapi/src/localization.cpp
system/autoware_default_adapi/src/localization.hpp
system/autoware_default_adapi/src/routing.cpp
system/autoware_default_adapi/src/routing.hpp

Publish routing and localization state diagnostics.
This replaces [component_state_diagnostics](https://github.com/autowarefoundation/autoware_universe/blob/main/system/autoware_system_diagnostic_monitor/script/component_state_diagnostics.py) script in system_diagnostic_monitor package.
https://github.com/autowarefoundation/autoware_launch/pull/1417
Check that the vehicle drives in autonomous mode using simple planning simulator.
None.
None.
None.

feat(default_adapi): add state diagnostics

---

perception/autoware_probabilistic_occupancy_grid_map/config/multi_lidar_pointcloud_based_occupancy_grid_map.param.yaml

New parameters were added in this PR https://github.com/autowarefoundation/autoware_universe/pull/10280 , but the parameter file for multi_lidar was not updated.
Before this PR, occupancy_grid_map_nodes were dying due to lack of parameters when started in `multi_lidar` mode. This PR fixes that.
* autoware_launch PR: https://github.com/autowarefoundation/autoware_launch/pull/1426
I have confirmed that the node works well by logging_simulator.launch.xml with[ tutorial rosbags.](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/rosbag-replay-simulation/)
```
map_path:=$HOME/autoware_map/sample-map-rosbag \
vehicle_model:=sample_vehicle \
sensor_model:=sample_sensor_kit \ …
```

fix(probabilistic_occupancy_grid_map): add missing parameter for multi-lidar

---

planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/package.xml
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/filter_predicted_objects.cpp
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/filter_predicted_objects.hpp

This PR fixes an issue with the current `out_of_lane`  module where an object's predicted path can contain "gaps" between successive footprint, causing collision detection to become inaccurate.
This PR add resampling of the predicted path to ensure no gaps in the predicted path.
| Current :-1: | With this PR :+1: |
| --- | --- |
| <video src="https://github.com/user-attachments/assets/081f038e-34b7-408f-a780-66e570e4ff84" /> | <video src="https://github.com/user-attachments/assets/6b0da037-1b6e-4709-ba87-02fc5d3cf27e" /> |
https://tier4.atlassian.net/browse/RT1-10111
- Link
Psim and perception reproducer
None.
None.
None.

feat(out_of_lane): resample object predicted paths to prevent empty gaps

---

planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/src/obstacle_slow_down_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/src/obstacle_slow_down_module.hpp

pointcloud clusters too far from the footprint of the vehicle are considered to be obstructive and slow-down and stop modules are triggered unnecessarily.
This PR is for the universe changes.
https://tier4.atlassian.net/browse/RT1-10023
Result in Ticket
None.
None.
None.

fix(autoware_motion_velocity_obstacle_slow_down_module): fix for mishandling lateral-distance

---

localization/autoware_pose_initializer/package.xml
localization/autoware_pose_initializer/src/pose_initializer_core.cpp
localization/autoware_pose_initializer/src/pose_initializer_core.hpp

This PR fixes the include headers of autoware_utils to follow the current package style (autoware_utils_*) for autoware_pose_initializer package.
- https://github.com/autowarefoundation/autoware_universe/issues/10492
None.
None.
None.

fix(autoware_pose_initializer): fix deprecated autoware_utils header

---

planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/src/scene.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_no_stopping_area_module/src/scene_no_stopping_area.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_virtual_traffic_light_module/src/scene.cpp

- Detection Area Module: Now considers connected lanelets when creating stop points and dead line points
- No Stopping Area Module: Explicitly passes current lane ID when creating stop points
- Virtual Traffic Light Module: Takes connected lane IDs into account when finding collision segments
- Link
- [CommonScenario_Future:5](https://evaluation.tier4.jp/evaluation/reports/19203a51-fab3-5e97-b138-5629179a146d?project_id=prd_jt)
- [CommonScenario_Basic:8](https://evaluation.tier4.jp/evaluation/reports/c65c5c74-c266-5b2f-b0d4-a5d0cd1e1ac8?project_id=prd_jt)
None.
None.
None.

fix(detection_area_module,virtual_traffic_light,no_stopping_area): support overlap lane

---

sensing/autoware_pointcloud_preprocessor/src/concatenate_data/combine_cloud_handler.cpp

In the current concatenation implementation, it is possible for a point cloud that is not compatible with the `XYZIRC` format to be published when only point cloud topics with zero points is received — even if the input empty point clouds have fields compatible with `XYZIRC`.
For example, this condition can occur shortly after the sensors starts up, when only some of the LiDAR sensors are active.
If a topic that is not `XYZIRC`-compatible is published from the concatenation node, some subsequent nodes may output a large number of log messages like the example below.
```
[ERROR 1747041202.864305347] [localization.util.crop_box_filter_measurement_range]: The pointcloud layout is not compatible with PointXYZIRCAEDT or PointXYZIRC. Aborting
[ERROR 1747041202.864633111] …
```

fix(autoware_pointcloud_preprocessor): combine_cloud_handler always set XYZIRC

---

common/autoware_traffic_light_utils/src/traffic_light_utils.cpp

This PR gets to delete if condition and wrong comment.
- `// the default value is -1, which means to not set confidence` is wrong because default value is 0 in  numeric type ros msg (and that value does not set -1 in autoware_traffic_light_classifier).
- https://design.ros2.org/articles/interface_definition.html
- if condition `if (confidence > 0)` does not need because of avobe description. And `setSignalUnknown` is only used in autoware_traffic_light_occlusion_predictor. But in this package, it is used as if confidence 0.0 can be set. (actually it is not set as 0.0 now.)
- Link
I have checked this PR works(as traffic light recognition) on my local pc.
None.
None.
None.

fix(traffic_light_utils): remove condition in `setSignalUnknown`

---

sensing/autoware_cuda_pointcloud_preprocessor/CMakeLists.txt

feat(autoware_cuda_pointcloud_preprocessor): added target architectures for the cuda pointcloud preprocessor

---

visualization/tier4_planning_rviz_plugin/include/tier4_planning_rviz_plugin/path/display.hpp

When the size of trajectory points changes from the positive value to 0, the rviz node died due to the tier4_planning_rviz_plugin to visualize the trajectory.
```
[rviz2-4] terminate called after throwing an instance of 'std::out_of_range'
[rviz2-4]   what():  vector::_M_range_check: __n (which is 18446744073709551615) >= this->size() (which is 7)
[ERROR] [rviz2-4]: process has died [pid 1405070, exit code -6, cmd '/opt/ros/humble/lib/rviz2/rviz2 -d /home/takayuki/pilot-auto/install/autoware_static_centerline_generator/share/autoware_static_centerline_generator/rviz/static_centerline_generator.rviz --ros-args -r __node:=rviz2 -p use_sim_time:=False -p wheel_radius:=0.258 -p wheel_width:=0.145 -p wheel_base:=1.335 -p wheel_tread:=0.955 -p front_overhang:=0.53 -p rear_overhang:=0.375 -p …
```

fix(tier4_planning_rviz_plugin): handle empty trajectory

---

visualization/tier4_planning_rviz_plugin/CMakeLists.txt
visualization/tier4_planning_rviz_plugin/include/tier4_planning_rviz_plugin/path/display.hpp
visualization/tier4_planning_rviz_plugin/include/tier4_planning_rviz_plugin/path/display_base.hpp
visualization/tier4_planning_rviz_plugin/package.xml
visualization/tier4_planning_rviz_plugin/src/path/display.cpp

When the rviz is directly not via autoware.launch.xml, since glog is not included in the tier4_planning_rviz_plugin, when the rviz process dies, there is no information of glog for the debugging.
This PR introduces the glog in the path visualization of the tier4_planning_rviz_plugin package.
- Link
None.
None.
None.

feat(tier4_planning_rviz_plugin): add glog in the path visualization

---

planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/package.xml
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/scripts/ttc.py
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/debug.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection_collision.cpp

If the object is at relatively high speed, the object polygons may get sparse and cause inaccuracy in collision checking.
https://tier4.atlassian.net/browse/RT0-36216
- https://evaluation.tier4.jp/evaluation/reports/0e35cacd-436d-5f7e-bfbc-849aa9db2f2a?project_id=prd_jt
None.
None.
None.

fix(intersection): interpolate object polygons precisely

---

control/autoware_collision_detector/README.md
control/autoware_collision_detector/config/collision_detector.param.yaml
control/autoware_collision_detector/include/autoware/collision_detector/debug.hpp
control/autoware_collision_detector/include/autoware/collision_detector/node.hpp
control/autoware_collision_detector/src/node.cpp

Required launch PR: https://github.com/autowarefoundation/autoware_launch/pull/1443
- Link
- [TIER IV internal link](https://tier4.atlassian.net/browse/L4P-173)
Psim
I visualize the new debug markers.
- We can see the ego footprint used for collision detection and with the new option the polygon does not extend behind the rear axle.
- When the diagnostic of the `collision_detector` is in the `ERROR` state, the footprint turns red. Otherwise it is green.
In the following video, we can see that once the ego footprint overlaps the object footprint, the footprint becomes red (`ERROR` diagnostic) and becomes extended by the hysteresis. After the obstacle disappear, it takes some time for the diagnostic to go back to the normal state (footprint goes back to …

feat(collision_detector): time buffer and ignore behind rear axle

---

planning/behavior_path_planner/autoware_behavior_path_planner/config/scene_module_manager.param.yaml

It seems `enable_module` is no longer used.
Original PR: https://github.com/autowarefoundation/autoware.universe/pull/6131
Depending PR: https://github.com/autowarefoundation/autoware_launch/pull/990

fix(bpp): remove unnecessary enable_module in sampling_planner

---

planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/parking_departure/geometric_parallel_parking.cpp

Modify the weird path generation of geometric parallel parking. The alpha calculation was wrong and must be computed according to forward or backward parking.
Moreover, this PR includes modification of a useless boundary check (check for the opposite side of the shoulder). 
Before
After
- N/A
- [plot_map](https://github.com/tier4/autoware.universe/blob/tier4/main/planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/examples/plot_map.cpp) as shown in above Pictures. 
- Evaluator: https://evaluation.tier4.jp/evaluation/reports/33c8c0c1-e59c-52b0-8a71-5325f4f7cc07?project_id=prd_jt
None.
None.
None.

fix(autoware_behavior_path_planner_common): modify geometric parallel parking path planning

---

common/autoware_component_interface_specs_universe/include/autoware/component_interface_specs_universe/localization.hpp
common/autoware_component_interface_specs_universe/package.xml
localization/autoware_ndt_scan_matcher/README.md
localization/autoware_ndt_scan_matcher/include/autoware/ndt_scan_matcher/ndt_scan_matcher_core.hpp
localization/autoware_ndt_scan_matcher/package.xml
localization/autoware_ndt_scan_matcher/src/ndt_scan_matcher_core.cpp
localization/autoware_ndt_scan_matcher/test/stub_initialpose_client.hpp
localization/autoware_pose_initializer/README.md
localization/autoware_pose_initializer/package.xml
localization/autoware_pose_initializer/src/localization_module.hpp
localization/yabloc/yabloc_pose_initializer/README.md
localization/yabloc/yabloc_pose_initializer/include/yabloc_pose_initializer/camera/camera_pose_initializer.hpp
localization/yabloc/yabloc_pose_initializer/package.xml
map/autoware_map_height_fitter/package.xml
map/autoware_map_height_fitter/src/map_height_fitter_node.cpp
system/autoware_default_adapi/src/utils/localization_conversion.cpp
system/autoware_default_adapi/src/utils/localization_conversion.hpp

in order to port ndt-scan-matcher to autoware.core, we have to replace tier4 related dependency with autoware dependency
- Link https://github.com/autowarefoundation/autoware_core/issues/454
1. colcon build with entier autoware -- `colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release --symlink-install`
2. using AWSIM‘s pointcloud and gnss for input, using rviz for visual checking that auto-localization-initialize and continus localization using ndt works
2.1  in terminal 1 launch AWSIM and use `ros2 topic list` to confirm that the pointcloud and gnss topic exist 
2.2  in terminal 2 source autoware workspace first, then type `ros2 launch autoware_launch e2e_simulator.launch.xml vehicle_model:=sample_vehicle sensor_model:=awsim_sensor_kit map_path:=<your mapfile location>` …

feat(localization): replace tier4_localization_msgs used by ndt_align_srv with autoware_internal_localization_msgs

---

perception/autoware_ground_segmentation/src/scan_ground_filter/grid_ground_filter.cpp

`global_slope_max_angle_deg` has been implemented in threshold of local slope, which is not intended.
Fix this to use `local_slope_max_angle_deg`.
- Link
None.
None.
None.

fix(autoware_ground_segmentation): correct slope threshold global to local

---

control/autoware_vehicle_cmd_gate/README.md
control/autoware_vehicle_cmd_gate/launch/vehicle_cmd_gate.launch.xml
control/autoware_vehicle_cmd_gate/src/vehicle_cmd_gate.cpp
control/autoware_vehicle_cmd_gate/src/vehicle_cmd_gate.hpp
launch/tier4_control_launch/launch/control.launch.xml
system/autoware_mrm_handler/README.md
system/autoware_mrm_handler/config/mrm_handler.param.yaml
system/autoware_mrm_handler/include/autoware/mrm_handler/mrm_handler_core.hpp
system/autoware_mrm_handler/launch/mrm_handler.launch.xml
system/autoware_mrm_handler/schema/mrm_handler.schema.json
system/autoware_mrm_handler/src/mrm_handler/mrm_handler_core.cpp

MRM handler doesn't send turn indicators message and during MRM emergency the `vehicle_cmd_gate` node sending annoying log every 100~200ms:
```
The operation mode is changed, but the TurnIndicatorsCommand is not received yet:
```
This MR fixes that.
It was tested on carla simulator after force invoking _out of lane_ from MRM handler.
None.
Topic `/system/emergency/turn_indicators_cmd` has added (from MRM Handler to Vehicle Cmd Gate).
| Change type   | Topic Type      | Topic Name    | Message Type        | Description       |
|:--------------|:----------------|:--------------|:--------------------|:------------------|
| Added | Sub | `~/input/emergency/turn_indicators_cmd` | `autoware_vehicle_msgs::msg::TurnIndicatorsCommand`   | Sub to Vehicle Cmd Gate  |
| Added | Pub | …

fix(autoware_mrm_handler): add emergency turn indicators

---

.github/workflows/build-and-test-reusable.yaml

Uploading codecov files takes too long **(21 mins)** on the self hosted machine and its time is more valuable since it has so many cores.
So this sequential low cpu requiring task can be offloaded to github public runners.
build-and-test run:
- https://github.com/autowarefoundation/autoware_universe/actions/runs/15026621945/job/42228865629
build-and-test-daily run:
- https://github.com/autowarefoundation/autoware_universe/actions/runs/14985413918/job/42098339475
- Tested here:
- https://github.com/autowarefoundation/autoware_universe/actions/runs/15135662117
For some reason this same job is (or at least used to be when we still could fit autoware in public runners) faster on github public runners and codebuild. But slower on the ovh machines.
Yet uploading first to github artifacts and …

ci(build-and-test-daily): offload uploading coverage to public runners

---

control/autoware_mpc_lateral_controller/include/autoware/mpc_lateral_controller/mpc_lateral_controller.hpp
control/autoware_mpc_lateral_controller/src/mpc_lateral_controller.cpp

Adds info messages to help explain why the ego won't move in certain occasions. 
This PR also adds [[nodiscard]] to certain functions as clangd suggested.
- Link
PSim: 
These messages are printed: 
[component_container_mt-29] [INFO] [1747971734.594982594] [control.trajectory_follower.controller_node_exe.lateral_controller]: steering is not converged.
None.
None.
None.

feat: mpc info throttle msgs

---

planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/src/parameters.hpp

keys of `object_type_specific_param_map` are `label.label + moving or static` instead of `label.label`
Hence the deafult value is always returned.
This PR fix this issue.
https://evaluation.tier4.jp/evaluation/reports/70477d43-83c6-5eb9-9b4f-a79e7c005456?project_id=prd_jt
None.

fix(obstacle_slow_down_module): fix object type specified params bug

---

planning/motion_velocity_planner/autoware_motion_velocity_obstacle_cruise_module/src/obstacle_cruise_module.cpp

Adds behaviour to the obstacle stop module so that the ego-vehicle yields to on-coming vehicles
- https://tier4.atlassian.net/browse/RT1-9226
**Design Document:**
https://tier4.atlassian.net/wiki/spaces/~712020794ae44077c44b7e9a5aa2cb085494fb/pages/3565782422/Slowing+Down+for+Opposing+Traffic
- [CompanyName internal link]()
⬆️🟢 -->
None.
None.
None.

feat(obstacle_stop_module): maintain larger stop distance for opposing traffic

---

common/autoware_universe_utils/include/autoware/universe_utils/ros/marker_helper.hpp
common/autoware_universe_utils/src/ros/marker_helper.cpp

Removed `createDeletedDefaultMarker` based on cppcheck warning
```
common/autoware_universe_utils/src/ros/marker_helper.cpp:45:0: style: The function 'createDeletedDefaultMarker' is never used. [unusedFunction]
visualization_msgs::msg::Marker createDeletedDefaultMarker(
^
```
- Link
None.
None.
None.

fix(autoware_universe_utils): remove unused function

---

planning/sampling_based_planner/autoware_frenet_planner/src/frenet_planner/frenet_planner.cpp

Removed unnecessary suppression for `generateTrajectories`
```
planning/sampling_based_planner/autoware_frenet_planner/src/frenet_planner/frenet_planner.cpp:38:0: information: Unmatched suppression: unusedFunction [unmatchedSuppression]
std::vector<Trajectory> generateTrajectories(
^
```
- Link
None.
None.
None.

fix(sampling_based_planner): remove unmatched suppression

---

planning/autoware_path_optimizer/src/node.cpp

When MPT optimization fails but there is no timeout, `std::move(*mpt_traj)` is executed. But when `mpt_traj` is `std::nullopt`, it will  results in undefined behavior. :cry:
I would like to fix this.
Here is an example stacktrace of undefined behavior.
```
[component_container_mt-36] [WARN 1747301824.459061255] [osqp_interface]: [MPT] Optimization failed due to solved inaccurate                                                                                                                                                                                                                                                                                                             
[component_container_mt-36] [WARN 1747301824.459088904] [planning.scenario_planning.lane_driving.motion_planning.path …
```

fix(path_optimizer): undefined behavior when optimizer failure

---

perception/autoware_map_based_prediction/src/predictor_vru.cpp

In the multi-object-tracker, it allows reversed movement with limited velocity.
https://github.com/autowarefoundation/autoware_universe/blob/cb28435a5c662001bec28f01af102a8472ae28ea/perception/autoware_multi_object_tracker/include/autoware/multi_object_tracker/tracker/motion_model/ctrv_motion_model.hpp#L55
In the object tracker, it allows reversed velocity until 1.38 m/s
For the vehicle motion prediction, the object is treated to move only forward.
https://github.com/autowarefoundation/autoware_universe/blob/cb28435a5c662001bec28f01af102a8472ae28ea/perception/autoware_map_based_prediction/src/map_based_prediction_node.cpp#L790-L792
However, this kind of implementation is not implied to VRU (pedestrians, bicycles).
This PR adjusts object orientation to answer planning engineers' request. …

fix(autoware_map_based_prediction): reverse vru object if it has negative vx

---

planning/autoware_mission_planner_universe/src/mission_planner/mission_planner.cpp

print route state when set_route fails
- Link
psim
check follwoing in terminal
```
const auto message = fmt::format("state_.state: {}", routeStateToString(state_.state));
RCLCPP_INFO(get_logger(), message.c_str());
```
None.
None.
None.

feat(mission_planner): print route state when set_route fails

---

build_depends_humble.repos

This PR updates autoware_msgs from 1.7.0 to 1.8.0 .
I am trying to adopt new autoware_msgs in https://github.com/autowarefoundation/autoware_universe/pull/10652 . But it is impossible to pass CI because autoware_msgs's version is 1.7.0 . So I think need to update autoware_msgs.
Note : https://github.com/autowarefoundation/autoware/pull/6164
- Link
None.
None.
None.

chore(build_depends_humble.repos): update autoware_msgs

---

planning/motion_velocity_planner/autoware_motion_velocity_dynamic_obstacle_stop_module/src/dynamic_obstacle_stop_module.hpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_cruise_module/src/obstacle_cruise_module.hpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/src/obstacle_slow_down_module.hpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_velocity_limiter_module/src/obstacle_velocity_limiter_module.hpp
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_module.hpp
planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/src/run_out_module.hpp

**Needs to be merged with: https://github.com/autowarefoundation/autoware_core/pull/505**
Currently autoware_motion_velocity_planner waits for all topics (predicted_objects, no_ground_pointcloud, occupancy_grid, and traffic_light) from Perception Module although it may not need to wait for them depending on the loaded plugins.
This changes the design of motion_velocity_planner so that it will ask to each loaded plugins for required topics that needs to be subscribed and only wait for required topics.
This is similar modification that we made to behavior_velocity_planner in [this PR
](https://github.com/autowarefoundation/autoware_universe/pull/10546)
- https://github.com/autowarefoundation/autoware_core/pull/505
- https://github.com/autowarefoundation/autoware_universe/pull/10546
* I have …

feat(autoware_motion_velocity_planner): only wait for required subscriptions

---

planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/src/run_out_module.cpp

Fix crashes that can occur when the calculate times along the ego trajectory are decreasing.
- [TIER IV internal link](https://tier4.atlassian.net/browse/RT0-37423)
Psim
None.
None.
None.

fix(run_out): guard against decreasing ego trajectory times

---

sensing/autoware_cuda_pointcloud_preprocessor/config/cuda_pointcloud_preprocessor.param.yaml
sensing/autoware_cuda_pointcloud_preprocessor/include/autoware/cuda_pointcloud_preprocessor/outlier_kernels.hpp
sensing/autoware_cuda_pointcloud_preprocessor/include/autoware/cuda_pointcloud_preprocessor/types.hpp
sensing/autoware_cuda_pointcloud_preprocessor/schema/cuda_pointcloud_preprocessor.schema.json
sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_pointcloud_preprocessor/cuda_pointcloud_preprocessor.cu
sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_pointcloud_preprocessor/cuda_pointcloud_preprocessor_node.cpp
sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_pointcloud_preprocessor/outlier_kernels.cu

This PR relates to https://github.com/autowarefoundation/autoware_universe/pull/10537, and contains the following changes:
- Modify default value of `object_length_threshold = 0.05`
- Remove process checking the number of points inside cluster and `num_points_threshold`.
- Link
Uploading without_cuda.mp4…
None.
None.
None.

feat(cuda_pointcloud_preprocessor): update filtering parameter and process

---

planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/package.xml

Add @mkquda as maintainer of the run_out module for the motion_velocity_planner. He will then also become codeowner of the package.
- Link
None.
None.
None.

chore(run_out): add Alqudah Mohammad as maintainer

---

control/autoware_pid_longitudinal_controller/src/pid_longitudinal_controller.cpp

Fixed a bug in resetting the previous value for the difference filter.
The design diagram is here: https://github.com/autowarefoundation/autoware_universe/pull/7718
However, a different variable was being reset in the implementation.
engage and stop available in psim
None.
None.
None.

fix(pid_longitudinal_controller): fix reseting the prev value

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/util.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/util.cpp

Currently debug_objects_extraction_polygon(blue polygon) is not published. Fixed this issue in this PR.
- Link
psim
None.
None.
None.

fix(goal_planner): publish debug_objects_extraction_polygon

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/README.md
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/config/goal_planner.param.yaml
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_parameters.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/decision_state.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/manager.cpp

currently check_collision_duration of path_decision_state_controller is harcoded. 
this paremter is Duration to check collision before transition from DECIDING to DECIDED
in this PR make this paramters.
- Link
with
```
path_decision_state_controller:
check_collision_duration: 5.0  # Duration to check collision before transition from DECIDING to DECIDED
```
2025/06/05 https://evaluation.tier4.jp/evaluation/reports/173d8952-39fc-5336-b629-7899a7720e2d/?project_id=prd_jt
3945/3946
None.
None.
None.

feat(goal_planner): add param of path_decision_state_controller.check_collision_duration

---

planning/behavior_velocity_planner/autoware_behavior_velocity_detection_area_module/src/scene.cpp

In https://github.com/autowarefoundation/autoware_universe/pull/9087 args for calcJudgeLineDistWithAccLimit were mistaken.
- Link
build
None.
None.
None.

fix(detection_area): fix args for calcJudgeLineDistWithAccLimit

---

perception/autoware_multi_object_tracker/lib/object_model/types.cpp

Previous PR https://github.com/autowarefoundation/autoware_universe/pull/10744 contains area calculation cache.
The function getArea had a bug on area calculation.
- before
```c++
return shape.dimensions.x * shape.dimensions.x * M_PI;
```
- after
```c++
return shape.dimensions.x * shape.dimensions.x * M_PI * 0.25;
```
- Link
None.
None.
None.

fix(multi_object_tracker): correct area calculation for cylinder shape in getArea function

---

simulator/autoware_simple_planning_simulator/package.xml
simulator/autoware_simple_planning_simulator/src/simple_planning_simulator/simple_planning_simulator_core.cpp

This PR fixes the include headers of autoware_utils to follow the current package style (autoware_utils_*) for autoware_simple_planning_simulator package.
- https://github.com/autowarefoundation/autoware_universe/issues/10470
None.
None.
None.

fix(autoware_simple_planning_simulator ): fix deprecated autoware_utils header

---

sensing/autoware_pointcloud_preprocessor/include/autoware/pointcloud_preprocessor/concatenate_data/concatenate_and_time_sync_node.ipp

Due to lack of response I created the PR anyhow.
#10591
Compilation
None.
None.
None.

fix: #10591

---

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp

Modified the condition for inserting a deceleration point in the `StaticObstacleAvoidanceModule`.
Previously, a deceleration point was inserted if the target velocity was below the ego speed plus a buffer.
Now, the condition checks whether the target velocity plus the buffer is less than the ego speed.
This adjustment ensures the vehicle continues to decelerate according to an appropriate deceleration profile, preventing premature termination of deceleration.
- Link
https://github.com/user-attachments/assets/fce5d665-2fe8-4823-8e0e-763c30057f63
[TIER IV INTERNAL LINK](https://evaluation.tier4.jp/evaluation/reports/tables/new?catalog_id=095ae8b3-a23b-4a08-8674-10a681449693&job_id=656a8049-4a1a-543a-a9f9-ede32db701a3&project_id=prd_jt&suite_id=741e8e2d-c181-469e-a2c8-430586 …

fix(static_obstacle_avoidance): fix slow down logic

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/decision_state.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_module.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/util.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/decision_state.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/util.cpp

If upstream module like avoidance and lane_change inserted a stopline during their execution, and goal_planner's thread started candidate generation, goal_planner may keep using the upstream_module path that contains stopline.
Thus, while such stopline exists, goal_planner does not transit to DECIDING, and keep re-generating candidates.
- https://tier4.atlassian.net/browse/RT0-35455
- https://evaluation.tier4.jp/evaluation/reports/c11b5a0c-75d7-5f3f-89eb-6f82a4743a5e?project_id=prd_jt
None.
None.
None.

feat(goal_planner): check previous module's stopline when regenerate candidates

---

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp

Modified the updateMarker function in the StaticObstacleAvoidanceModule to append the debug markers generated by createDebugMarkerArray instead of overwriting the existing debug_marker_. This ensures that multiple sources of debug information can be accumulated consistently, improving the visibility and traceability of debug data during static obstacle avoidance processing.
- Link
- Psim
None.
None.
None.

fix(static_obstacle_avoidance): debug marker is not published properly

---

common/autoware_boundary_departure_checker/package.xml

Adds @Kotakku and @maxime-clem as the maintainer for the `boundary_departure_checker`'s module.
- Link
None.
None.
None.

chore(boundary_departure_checker): add maintainer

---

planning/planning_validator/autoware_planning_validator/README.md
planning/planning_validator/autoware_planning_validator_trajectory_checker/src/trajectory_checker.cpp
planning/planning_validator/autoware_planning_validator_trajectory_checker/test/test_trajectory_checker_diag.cpp

Distance deviation was incorrectly calculated as Euclidian distance from the nearest trajectory _point_ instead of lateral distance from nearest segment.
This PR fixes that.
Example impact:
| --- | --- |
| ![image](https://github.com/user-attachments/assets/5a0781d0-dbad-415a-b233-4faffabbc750) | ![image](https://github.com/user-attachments/assets/99938dc1-8686-4b85-95cb-78e71d33b37d) |
- [TIER IV internal link](https://tier4.atlassian.net/browse/RT1-10026)
Psim
Perception reproducer
None.
None.
None.

fix(planning_validator): fix the lateral distance calculation

---

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/config/static_obstacle_avoidance.param.yaml
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/data_structs.hpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/scene.hpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/utils.hpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/schema/static_obstacle_avoidance.schema.json
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/manager.cpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp

Until now, move_time was used to classify objects as UNSTABLE. In this PR, I changed it to use the first time classified as UNKNOWN instead of move_time. By doing so, we made it more robust against perception noise.
- https://github.com/autowarefoundation/autoware_launch/pull/1492
- https://evaluation.tier4.jp/evaluation/reports/362d34b8-3034-54e2-b7e8-f48f7d1bac59/tests/f9b42ba6-bd36-561e-adc6-7768c2ef7b49?project_id=prd_jt&state=failed
viewers
None.
None.
None.

fix(autoware_static_obstacle_avoidance): fix classification method of unstable object

---

system/autoware_processing_time_checker/package.xml
system/autoware_processing_time_checker/src/digestible.hpp
system/autoware_processing_time_checker/src/processing_time_checker.cpp
system/autoware_processing_time_checker/src/processing_time_checker.hpp

Output the 99th and 95th percentiles of processing time statistics.
This PR reimplemented https://github.com/autowarefoundation/autoware_universe/pull/10769 without updating autoware_utils, based on the discussion [here](https://star4.slack.com/archives/C4P0NSMB5/p1749784526240699?thread_ts=1749182597.397049&cid=C4P0NSMB5)
- Link
run Psim and check the outputted json:
```json
{
"elastic_band_smoother/count": 211,
"elastic_band_smoother/description": "processing time of elastic_band_smoother[ms]",
"elastic_band_smoother/max": 2.802000045776367,
"elastic_band_smoother/mean": 1.1689620842865858,
"elastic_band_smoother/min": 0.7749999761581421,
"elastic_band_smoother/percentile_95": 1.9900000095367432,
"elastic_band_smoother/percentile_99": 2.4839999675750732, …
```

feat(processing_time_checker): output 99th and 95th percentile of processing time statics

---

planning/planning_validator/autoware_planning_validator/include/autoware/planning_validator/debug_marker.hpp
planning/planning_validator/autoware_planning_validator/launch/planning_validator.launch.xml
planning/planning_validator/autoware_planning_validator/msg/PlanningValidatorStatus.msg
planning/planning_validator/autoware_planning_validator/src/debug_marker.cpp
planning/planning_validator/autoware_planning_validator/src/node.cpp
planning/planning_validator/autoware_planning_validator_rear_collision_checker/CMakeLists.txt
planning/planning_validator/autoware_planning_validator_rear_collision_checker/config/rear_collision_checker.param.yaml
planning/planning_validator/autoware_planning_validator_rear_collision_checker/package.xml
planning/planning_validator/autoware_planning_validator_rear_collision_checker/param/rear_collision_checker_node_parameters.yaml
planning/planning_validator/autoware_planning_validator_rear_collision_checker/plugins.xml
planning/planning_validator/autoware_planning_validator_rear_collision_checker/src/rear_collision_checker.cpp
planning/planning_validator/autoware_planning_validator_rear_collision_checker/src/rear_collision_checker.hpp
planning/planning_validator/autoware_planning_validator_rear_collision_checker/src/structs.hpp
planning/planning_validator/autoware_planning_validator_rear_collision_checker/src/utils.cpp
planning/planning_validator/autoware_planning_validator_rear_collision_checker/src/utils.hpp

This update introduces a new plugin called rear_collision_checker, which is responsible for detecting potential rear-end collisions based on predicted object motion and the ego vehicle's planned trajectory. The plugin is specifically designed to enhance safety when the vehicle is about to change lanes or merge into an adjacent lane, where rear-approaching vehicles may pose a threat. Key features include:
LIDAR-based obstacle detection: Directly analyzes raw point cloud data to identify rear-approaching objects not yet recognized by perception.
Nearest-point velocity estimation: Calculates relative velocity of closest rear obstacle points for more accurate collision prediction.
RSS-based risk metrics: Computes collision risk using estimated velocity and spatial-temporal proximity.
Dynamic …

feat(planning_validator): implement a collision detection feature for rearward objects of the vehicle

---

perception/autoware_image_projection_based_fusion/launch/segmentation_pointcloud_fusion.launch.py

This PR resolves that `segmentation_pointcloud_fusion` could not be launched with `debug_mode` enabled.
- Nothing
I have confirmed that the node does not crash when launched with `segmentation_based_filter` and `debug_mode` enabled.
> `image_topic_name` is only referenced when `debug_mode` is set to true.
```
sed -i '26s/.*/    debug_mode: true/' src/launcher/autoware_launch/autoware_launch/config/perception/object_recognition/detection/image_projection_based_fusion/fusion_common.param.yaml
map_path:=$HOME/autoware_map/sample-map-rosbag/ \
vehicle_model:=sample_vehicle \
sensor_model:=sample_sensor_kit \
use_image_segmentation_based_filter:=true \
perception_mode:=camera_lidar_fusion
```
Before this PR, …

fix(segmentation_pointcloud_fusion): add missing context 

---

planning/behavior_velocity_planner/autoware_behavior_velocity_virtual_traffic_light_module/src/manager.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_virtual_traffic_light_module/src/scene.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_virtual_traffic_light_module/src/scene.hpp

- Add module state, module ID, Regulatory Element ID, Lane ID, Start/Stop/End Line ID to log message
- Print state transition and remarkable events
1) ego passes start_line
> [component_container_mt-34] [INFO 1749815272.230217083] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner.virtual_traffic_light_module.intersection_coordination_9971.state: NONE]: [Module ID: 43][Reg: 9972][Lane: 43][Line: 9965, 9962, 9945] State transition: NONE -> REQUESTING as vehicle is before start line (ID: 9965)
2) no instrument message is received
> [component_container_mt-34] [INFO 1749815302.430467509] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner.virtual_traffic_light_module.intersection_coordination_9971.state: REQUESTING]: [Module …

feat(virtual_traffic_light): improve log message

---

common/autoware_traffic_light_utils/include/autoware/traffic_light_utils/traffic_light_utils.hpp
common/autoware_traffic_light_utils/src/traffic_light_utils.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/config/traffic_light.param.yaml
planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/manager.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/scene.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/scene.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/utils.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/utils.hpp

This function uses the predicted time when the signal color will change, as provided by V2I.
Even if the current signal is GREEN, if it is predicted to change to RED in a few seconds and you cannot cross the stop line before it changes to RED, it is better to plan to stop.
In this PR, I introduced a function that determines whether it is possible to stop at the stop line based on the time remaining until RED when V2I is enabled, and plans to stop if it is not possible to pass.
[V2I.webm](https://github.com/user-attachments/assets/285731c2-7a1c-4fc4-8acc-36b816d1f441)
- https://github.com/autowarefoundation/autoware_launch/pull/1482
- https://github.com/tier4/vehicle2infrastructure/pull/140
I tested it using psim and my own script. The attached video shows the test results.
<details> …

feat(autoware_behavior_velocity_traffic_light_module): add v2i

---

common/autoware_component_interface_specs_universe/include/autoware/component_interface_specs_universe/localization.hpp
common/autoware_component_interface_specs_universe/package.xml
system/autoware_default_adapi_universe/src/utils/localization_conversion.cpp
system/autoware_default_adapi_universe/src/utils/localization_conversion.hpp

This replaces autoware_internal_localization_msgs with autoware_localization_msgs to treat it as component interface.
This is required to use this interface from AD API.
This means that the topic will have stricter version control after this modification.
This should be merged with https://github.com/autowarefoundation/autoware_core/pull/542
- [Link](https://github.com/autowarefoundation/autoware_core/issues/541)
I have tested with AWSIM that localization works even after the interface change
None.
| Version | Topic Type      | Topic Name        | Message Type        | Description       |
|:--------|:----------------|:------------------|:--------------------|:------------------|
| Old     | Service | `/localization/initialize` | …

feat!: replace autoware_internal_localization_msgs with autoware_localization_msgs for InitializeLocalization service

---

planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection_collision.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection_prepare_data.cpp

`generatePathLanelets` generate a Lanelet which 
- start from ego position
- end at the exit of the intersection
from the given `path`.
Previous implementation was passing `interpolated_path` as `path` but `closest_idx` was the index for not interpolated path.
I fixed to pass `closest_idx_ip`, which is the `closest_idx` for `inrterpolated_path`.
https://github.com/autowarefoundation/autoware_launch/pull/1501
see the videos in https://github.com/autowarefoundation/autoware_launch/pull/1501
https://evaluation.tier4.jp/evaluation/reports/28f21a85-06b8-50ad-8b45-7db47595373c?project_id=prd_jt
None.
None.
None.

fix(intersection): fix path lanelets generation

---

launch/tier4_autoware_api_launch/launch/deprecated_api.launch.xml
launch/tier4_autoware_api_launch/package.xml

This is one of the steps of https://github.com/autowarefoundation/autoware/issues/3096.
To remove tier4 api adaptor, we are refactoring our API.
Related to https://github.com/tier4/tier4_ad_api_adaptor/pull/153
- https://github.com/autowarefoundation/autoware/issues/3096
Launch planning simulation with `launch_deprecated_api:=true` option.
None.
None.
None.

feat(tier4_autoware_api_launch): add tier4 api to replace old api

---

sensing/autoware_pointcloud_preprocessor/include/autoware/pointcloud_preprocessor/blockage_diag/blockage_diag_node.hpp
sensing/autoware_pointcloud_preprocessor/src/blockage_diag/blockage_diag_node.cpp

This PR is the first step to enable blockage mask input from sensors that have blockage detection.
The PR splits up the `filter` function into its logical steps, and cleans up some duplicated and/or verbose code along the way.
Dust detection is largely left untouched for now as the LiDAR blockage input does not interact with it in any special way.
The output of both before and after this PR seems to be exactly the same:
<table>
<tr>
<th>Before</th>
<td>
https://github.com/user-attachments/assets/c7a0472d-9d4c-4839-8d4a-85cd3c0f0c55
</td>
</tr>
<tr>
<th>After</th>
<td>
https://github.com/user-attachments/assets/71bcad3e-30e4-48af-afe6-66c1e6d424c9
</td>
</tr>
</table>
None.
None.
None.

refactor(blockage_diag): split up `filter` function, add doc comments

---

common/autoware_boundary_departure_checker/include/autoware/boundary_departure_checker/boundary_departure_checker.hpp
common/autoware_boundary_departure_checker/src/boundary_departure_checker_abnormality.cpp
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/boundary_departure_prevention_module.cpp

Fix minor namespace and adds time keeper
- Link
1. PSIM. Run autoware and test boundary departure.
2. Run
```
ros2 topic echo /planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/debug/boundary_departure_prevention/processing_time_ms
```
3. In another terminal, run
```
ros2 topic echo /planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/debug/processing_time_detail_ms/boundary_departure_prevention
```
None.
None.
None.

fix(boundary_departure_prevention): add processing time/time keeper

---

system/autoware_command_mode_decider/package.xml
system/autoware_command_mode_decider/src/command_mode_decider_base.hpp
system/autoware_command_mode_decider_plugins/src/command_mode_decider.cpp

Apply message change by https://github.com/autowarefoundation/autoware_universe/pull/10842.
(Ideally it should be changed to reference the specs package.)
https://github.com/autowarefoundation/autoware_universe/pull/10842
Launch planning simulation with use_control_command_gate option and https://github.com/autowarefoundation/autoware_launch/pull/1332
None.
None.
None.

feat(command_mode_decider): reflect message porting

---

planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/debug.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/scene.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_traffic_light_module/src/scene.hpp

When inserting a stop even if the signal is green, the following message is displayed.
[Screencast from 06-20-2025 04:33:19 PM.webm](https://github.com/user-attachments/assets/77df4b90-edd4-4e92-a6a3-81c70ce03ce3)
- Link
None.
None.
None.

feat(autoware_behavior_velocity_traffic_light_module): enhance rviz for v2i

---

visualization/tier4_state_rviz_plugin/src/autoware_state_panel.cpp

Show the original value when the state is unknown.
None
Launch RViz.
```
rviz2 -d src/launcher/autoware_launch/autoware_launch/rviz/autoware.rviz
```
Check unknown state using following commands
```
ros2 topic pub /api/routing/state autoware_adapi_v1_msgs/msg/RouteState "{state: 111}"
ros2 topic pub /api/localization/initialization_state autoware_adapi_v1_msgs/msg/LocalizationInitializationState "{state: 222}"
ros2 topic pub /api/fail_safe/mrm_state autoware_adapi_v1_msgs/msg/MrmState "{state: 333, behavior: 444}"
```
None.
None.
None.

feat(tier4_state_rviz_plugin): display unknown value

---

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp

This PR fixes the comparator of `ranges::sort()` to ensure it follows strict weak ordering.
- Link
None.
None.
None.

fix(lane_change): fix code to prevent node crash

---

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/config/static_obstacle_avoidance.param.yaml
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/data_structs.hpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/helper.hpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/parameter_helper.hpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/schema/static_obstacle_avoidance.schema.json
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/manager.cpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/shift_line_generator.cpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/test/test_utils.cpp

This PR introduces support for separately configuring the minimum lateral jerk constraints used during:
- Obstacle avoidance
- Returning to the original lane
Previously, the min_jerk_values parameter applied a single jerk constraint for both phases. In real-world driving, however, the dynamic characteristics required for avoiding an obstacle and smoothly returning to the lane can differ. This PR resolves that limitation by separating the parameters and applying each one appropriately in the planning logic.
```yaml
min_jerk_values:
avoid:  [0.2, 0.2, 0.2]  # Used during obstacle avoidance
return: [0.2, 0.2, 0.2]  # Used when returning to original lane
```
https://github.com/user-attachments/assets/89f83f8c-3024-488c-afe9-aeb919849bdc
```yaml
min_jerk_values:
avoid:  [0.2, 0.2, 0.2]  # Used …
```

feat(static_obstacle_avoidance): support separate lateral jerk constraints for avoidance and return maneuvers

---

control/autoware_control_validator/README.md
control/autoware_control_validator/config/control_validator.param.yaml
control/autoware_control_validator/include/autoware/control_validator/control_validator.hpp
control/autoware_control_validator/msg/ControlValidatorStatus.msg
control/autoware_control_validator/src/control_validator.cpp

Add a 2nd threshold for the `yaw_deviation` metric allowing publishing of a warning instead of an error.
Requires the launch PR: https://github.com/autowarefoundation/autoware_launch/pull/1508
- [TIER IV internal link](https://tier4.atlassian.net/browse/RT1-10098)
Psim
Example with default parameters (threshold of `0.5` for `WARN` and `1.0` for `ERROR`).
https://github.com/user-attachments/assets/6050ad79-92a3-4219-b454-3b93eef4d6c7
None.
None.
None.

feat(control_validator): 2 thresholds for the yaw deviation (warn/error)

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/decision_state.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_planner_module.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/pull_over_planner/pull_over_planner_base.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/thread_data.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/util.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/decision_state.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/bezier_pull_over.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/geometric_pull_over.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/pull_over_planner/shift_pull_over.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/thread_data.cpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/util.cpp

If lane_change is running when goal_planner's thread is generating path candidates, lane_change can suddenly swerve the path. If ego is still driving on the preferred_lanelets before swerving, and goal_planner still happened to be IDLE, syncWithThreads() is not triggered, thus the backgroud thread keeps using old reference path, which is aligned on the old preferred lanelets. This is problematic when pull over planners process "previous_module_path" w.r.t reference path.
To deal with this issue:
1. added the flag `lane_change_status_changed_` to goal_planner to signal background thread
2. each planner use `get_reference_lanelets_for_pullover` instead of `getPullOverLanes`
- https://tier4.atlassian.net/browse/RT0-35453
- https://evaluation.tier4.jp/evaluation/reports/7fdf2fc0-e7b0-51ba-b36a …

feat(goal_planner): check pull over lane crossing validity when triggering candidate generation thread

---

control/autoware_mpc_lateral_controller/src/mpc_utils.cpp

update `time_from_start` variable in MPC's predicted trajectory.
- Link
- [TIER IV internal link](https://evaluation.tier4.jp/evaluation/reports/878125e8-60db-59e5-9ebe-890b526a680b?project_id=prd_jt)
None.
None.
None.

fix(mpc): update time from start in the predicted trajectory

---

perception/autoware_multi_object_tracker/include/autoware/multi_object_tracker/object_model/object_model.hpp
perception/autoware_multi_object_tracker/lib/association/association.cpp

This is the previous analysis report about this tuning 
- [TIER IV INTERNAL](https://tier4.atlassian.net/wiki/spaces/CT/pages/3573875165/SP)
Since the threshold has already been changed, the performance may not differ much. However, theoretically, this change is more reasonable and helps avoid deviations from the original performance.
Previous tuning: https://github.com/autowarefoundation/autoware_universe/pull/10648
- Link
- [TIER IV INTERNAL](https://evaluation.tier4.jp/evaluation/reports/a80db83b-4282-5ee2-89cc-e5d30c7fa80b?project_id=prd_jt)
None.
None.
None.

feat(multi_object_tracker):  parameters tuned for mahalanobis distance

---

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp

**Avoidance of iterator invalidation**
When you call `push_back` on a `std::vector`, it may reallocate its internal storage, which invalidates all existing iterators and references into that vector. By switching to index‐based access (`lanes[i]`) inside a loop that re-evaluates `lanes.size()` each iteration, you obtain each element directly from the vector’s current storage. This ensures you never hold onto a stale iterator or reference, so your code remains correct even if the vector grows and moves its data.
- Link
None.
None.
None.

fix(static_obstacle_avoidance): fix coding error

---

system/autoware_diagnostic_graph_aggregator/package.xml
system/autoware_diagnostic_graph_aggregator/src/common/graph/graph.cpp
system/autoware_diagnostic_graph_aggregator/src/common/graph/graph.hpp
system/autoware_diagnostic_graph_aggregator/src/common/graph/levels.cpp
system/autoware_diagnostic_graph_aggregator/src/common/graph/levels.hpp
system/autoware_diagnostic_graph_aggregator/src/common/graph/nodes.cpp
system/autoware_diagnostic_graph_aggregator/src/common/graph/nodes.hpp
system/autoware_diagnostic_graph_aggregator/src/node/aggregator.cpp
system/autoware_diagnostic_graph_aggregator/src/node/aggregator.hpp
system/autoware_diagnostic_graph_aggregator/test/src/test_levels.cpp
system/autoware_diagnostic_graph_aggregator/test/src/tests/timeline.cpp
system/autoware_diagnostic_graph_aggregator/test/src/tests/timeline.hpp

Add initializing flag that prevents error of diagnostic unit with latch settings during initialization.
- [TIER IV internal link](https://tier4.atlassian.net/wiki/spaces/AIP/pages/3790963545/2025-06-27)
Add latch settings to diagnostic graph.
Launch aggregator.
Set initializing flag to true and check latch level.
```
ros2 service call /<node-name>/set_initializing std_srvs/srv/SetBool "data: true"
```
None.
None.
None.

feat(diagnostic_graph_aggregator): add initializing flag

---

control/autoware_control_command_gate/CMakeLists.txt
control/autoware_control_command_gate/config/default.param.yaml
control/autoware_control_command_gate/package.xml
control/autoware_control_command_gate/src/command/compatibility.cpp
control/autoware_control_command_gate/src/command/compatibility.hpp
control/autoware_control_command_gate/src/command/compatibility/adapi_pause_interface.cpp
control/autoware_control_command_gate/src/command/compatibility/adapi_pause_interface.hpp
control/autoware_control_command_gate/src/command/filter.hpp
control/autoware_control_command_gate/src/command/source.hpp
control/autoware_control_command_gate/src/control_command_gate.cpp
control/autoware_control_command_gate/src/control_command_gate.hpp

Add pause interface for compatibility with vehicle_cmd_gate.
- [TIER IV internal link](https://star4.slack.com/archives/C0657FNJ5EG/p1750752185453049)
Check motion state on rviz plugin.
None.
None.
None.

fix(control_command_gate): fix for pause interface 

---

planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/intersection_stoplines.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection_prepare_data.cpp

If sudden collision is detected after ego passed default stopline, current module inserts stopline at current position. This causes `will overrun` MRM because such braking is impossible. the stopline is inserted ahead of ego by braking distance after this PR (collision_stopline).
intersection stopline appears just in front of ego (at [00:08])
https://github.com/user-attachments/assets/a8ec8ec6-d688-4a9d-9239-59635b70b1d1
intersection stopline appears a bit ahead of ego
https://github.com/user-attachments/assets/258aacd1-5ed2-455c-a9ff-c26c877d737a
https://tier4.atlassian.net/browse/RT1-10480
https://evaluation.tier4.jp/evaluation/reports/1374ee58-5ce8-5cb5-95c5-89448e791f17?project_id=prd_jt
https://evaluation.tier4.jp/evaluation/reports/9325a091-648e-5b28-b44b-5f3babad8511?project_id=prd_ …

feat(intersection): adjust collision stopline position to be ahead of ego by braking distance

---

planning/.pages

Add the `motion_velocity_planner`'s `run_out` module to the documentation page of the planning pages.
None.
None.
None.

docs(motion_velocity_planner): add the run_out module to the planning pages

---

perception/autoware_image_projection_based_fusion/src/fusion_matching_strategy.cpp
perception/autoware_image_projection_based_fusion/src/fusion_node.cpp

- To allow some fusion_node use the number of camera less than the number of camera availabe from sensing.
- [TIER IV Internal Link](https://star4.slack.com/archives/CRUE57C30/p1751596295840199?thread_ts=1751587293.599969&cid=CRUE57C30)
- Tested with logging-simulator when `approximate_camera_projection`, `point_project_to_unrectified_image`, `rois_timestamp_offsets` size are setup 9, while [image_number=6](https://github.com/autowarefoundation/autoware_universe/blob/fd22133897b536155004c27d9b0a71bffb0fb3e7/launch/tier4_perception_launch/launch/perception.launch.xml#L116)
```
autoware@npc2201009-ubuntu22:~/autoware.proj$ ros2 node info /perception/object_recognition/detection/clustering/camera_lidar_fusion/roi_cluster_fusion …
```

fix(image_projection_based_fusion): loosen rois_number check

---

visualization/tier4_state_rviz_plugin/src/include/velocity_steering_factors_panel.hpp
visualization/tier4_state_rviz_plugin/src/velocity_steering_factors_panel.cpp

This PR enables to save and load the configuration of `VelocitySteeringFactorsPanel`.
Currently the jerk and the deceleration limit for abrupt deceleration checking feature are covered.
Psim
None.
None.
None.

feat(tier4_state_rviz_plugin): save & load config of VelocitySteeringFactorsPanel

---

perception/autoware_simple_object_merger/include/autoware/simple_object_merger/simple_object_merger_base.hpp
perception/autoware_simple_object_merger/src/simple_detected_object_merger_node.cpp
perception/autoware_simple_object_merger/src/simple_tracked_object_merger_node.cpp

When tf is not obtained properly, the transform becomes null pointer.
https://github.com/autowarefoundation/autoware_universe/blob/4d0d0ec40afb827eb87d0a3ca23e4760ced6bbc4/common/autoware_universe_utils/include/autoware/universe_utils/ros/transform_listener.hpp#L60-L75
This PR is to handle this exemption properly.
- if the target frame is the same as the input frame, skip the transform process
- if the obtained transform is nullptr, skip the process
- Link
None.
None.
None.

fix(simple object merger): handle when tf could not get properly

---

planning/planning_validator/autoware_planning_validator/README.md
planning/planning_validator/autoware_planning_validator/src/node.cpp
planning/planning_validator/autoware_planning_validator/src/utils.cpp
planning/planning_validator/autoware_planning_validator_trajectory_checker/src/trajectory_checker.cpp

When `trajectory_checker` detects a "critical" error, then the appropriate behavior should be executed as specified by planning validator configs.
Currently if `trajectory_checker` detects another "noncritical" error simultaneously, the expected behavior might be overriden by the diagnostics published for the "noncritical" error.
This PR addresses the issue by using one common `is_critical_error_` flag for the trajectory diagnostics update instead of using a separate flag for each error type. Doing so will ensure that the handling method of critical error is prioritized in case multiple errors are detected at the same time
None.
- PSIM.
- [Internal TIER IV Evaluator](https://evaluation.tier4.jp/evaluation/reports/626a9dcf-9f23-564f-8ec6-fee5ee192e21?project_id=prd_jt)
None.
None.
None.

fix(planning_validator): fix conflict between trajectory shift and distance deviation checks

---

launch/tier4_perception_launch/launch/object_recognition/detection/detection.launch.xml

https://github.com/autowarefoundation/autoware_universe/pull/10916 disabled radar detected object pipeline when `use_radar_tracking_fusion` is true. However, the detected object pipeline is used in some modes.
- multi channel MOT (`use_multi_channel_tracker_merger` is true) : Multi object tracker only supports detected objects (at this moment)
- Lidar Radar mode (`perception_mode` is lidar_radar_fusion) : `radar_object_fusion_to_detected_object` only supports detected objects
- Link
None.
None.
None.

fix(perception): update radar detection logic for multi-channel support

---

control/autoware_control_validator/src/control_validator.cpp

This PR adds a safeguard to prevent division by zero in the `LateralJerkValidator::validate` function.  
If the time difference `dt` is zero or extremely small, the calculation is skipped to ensure numerical stability.
- Link
- [BASIC SCENARIOS](https://evaluation.tier4.jp/evaluation/reports/7be1f2e8-64c6-5f4a-9838-c7986224ec55?project_id=prd_jt)
- [FUNC VERIFICATION SCENARIOS](https://evaluation.tier4.jp/evaluation/reports/65acb71c-6039-50b7-b30a-6889e2eca3c6?project_id=prd_jt)
- [DLR SCENARIOS](https://evaluation.tier4.jp/evaluation/reports/37e8d792-20bf-50a3-a8bb-6a58be6e7ad9?project_id=prd_jt)
None.
None.
None.

fix(autoware_control_validator): prevent division by zero in time calculation

---

planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/turn_signal_decider.hpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/package.xml
planning/behavior_path_planner/autoware_behavior_path_planner_common/src/turn_signal_decider.cpp

When avoidance is performed using only the zebra zone, it is not necessary to output a turn signal. Previously, if there were no lanelets on either side of the current lanelet, it was assumed that a zebra zone was being used, and the turn signal was not output. However, this logic caused the turn signal not to be output even when there were neither adjacent lanelets nor zebra zones. In this PR, the logic has been updated to explicitly check for the presence of zebra zones on either side, and the turn signal is now suppressed only when avoidance is performed solely using zebra zones.
[turn_signal_before.webm](https://github.com/user-attachments/assets/601c5672-3a81-45ef-9b0f-501256597496)
[Screencast from 07-07-2025 05:13:16 PM.webm](https://github.com/user-attachments/assets/e7f989f2-4058- …

feat(behavior_path_planner_common): ignore the turn signals when using the zebra zone

---

control/autoware_control_validator/include/autoware/control_validator/control_validator.hpp
control/autoware_control_validator/src/control_validator.cpp
control/autoware_control_validator/test/test_control_validator.cpp

This PR improves the robustness of the trajectory validation logic in the control validator module.
- The maximum lateral deviation check now compares the predicted trajectory not only with the current reference trajectory, but also with the previous cycle's reference trajectory if the threshold is exceeded.
- The previous reference trajectory is only stored if its timestamp is different from the current one.
- The reason for this logic is that the predicted trajectory of the current cycle may have been generated based on the previous cycle's reference trajectory, not the current one.
These changes help prevent false positives in trajectory deviation detection due to timing mismatches between reference and predicted trajectories.
- [TIERIV internal …

feat(control_validator): enhance trajectory validation with previous reference trajectory

---

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/data_structs.hpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/utils.hpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp
planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/test/test_utils.cpp

This PR introduces a curvature-based safety margin to improve obstacle avoidance behavior, particularly on high-curvature paths. A new field `curvature_based_margin` is added to `ObjectData`, which represents an extra lateral buffer to prevent the front of the ego vehicle from approaching too closely to roadside obstacles. This margin is calculated using a newly implemented function `calc_curvature_based_margin`, which evaluates the lateral offset between the vehicle's front corner and the path centerline across the object's longitudinal range. To support this, another utility function `calc_front_corner_offsets` computes the lateral distances of the front corners along the path. By incorporating this additional margin into the avoidance logic, the system can generate safer trajectories …

fix(static_obstacle_avoidance): ensure sufficient avoidance margin on high-curvature paths for parked vehicle avoidance

---

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/utils.cpp

This pull request modifies the logic of the isWithinLanes function to improve its robustness on curved paths.
Previously, the check used the vehicle's full footprint, including its front corners. On sharp curves, this could result in a part of the footprint protruding beyond the lane boundary, causing isWithinLanes to return false even when the vehicle is reasonably within the drivable area.
To address this issue, the check has been updated to use only a line segment connecting the left and right sides of the vehicle's base_link (i.e., a line orthogonal to the vehicle's longitudinal axis), instead of the full footprint. This provides a more conservative and stable representation of the vehicle's lane occupancy, especially on curved trajectories.
This PR solves the following issue.
- …

fix(behavior_path_static_obstacle_avoidance_module): fix isWithinLanes

---

launch/tier4_system_launch/launch/system.launch.xml

Enable to remap diag reset service from autoware_launch files.
This PR is necessary for redundant configuration.
- [TIER IV internal link](https://star4.slack.com/archives/C0657FNJ5EG/p1750246110031379?thread_ts=1750126461.095959&cid=C0657FNJ5EG)
- Confirmed build succeeded
- Real minibus testing
None.
None.
None.

feat(tier4_system_launch): add arg for diag reset remapping

---

system/autoware_system_monitor/CHANGELOG.rst

This PR fixes the URL in the CHANGELOG file to point to the autowarefoundation upstream repo instead of a fork.
None.
None.
None.

fix: use autowarefoundation for CHANGELOG instead of youtalk fork

---

planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/boundary_departure_prevention_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/boundary_departure_prevention_module.hpp

When autoware is disengaged, the ego's predicted path behavior is undefined. As shown in the following video. This has caused boundary departure to produce false positive results. 
https://github.com/user-attachments/assets/04c90345-1859-4d63-8a31-b41ab46886bb
This PR aims to disable boundary departure during autonomous mode.
- Link
[TIER IV Internal link](https://evaluation.tier4.jp/evaluation/reports/d61a3b50-35f4-55c8-9e6d-98208e8f050d?project_id=prd_jt)
[TIER IV Internal link](https://evaluation.tier4.jp/evaluation/reports/13151cef-ce80-5dd8-8abf-2da4f1234b6d?project_id=prd_jt)
[TIER IV Internal link](https://evaluation.tier4.jp/evaluation/reports/315b4896-33fc-5d29-9676-261c8205c57c?project_id=prd_jt)
None.
None.
None.

fix(boundary_departure): disable when autoware disengaged

---

planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/boundary_departure_prevention_module.cpp

Add logging to so that the output can be monitored with TIER IV tools.
- Link
None.
None.
None.

chore(boundary_departure): add logging for monitoring

---

planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/calculate_slowdown_points.cpp
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/debug.cpp
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/footprint.cpp
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/footprint.hpp

In order to avoid detecting out of lane collisions that are unavoidable, this PR cuts the trajectory footprints that are behind the current ego front.
| --- | --- |
|<video src="https://github.com/user-attachments/assets/4d160355-9e48-4bd3-bf4c-d682dd148377"/> | <video src="https://github.com/user-attachments/assets/3c60bfda-efca-4021-a85c-72bcbf251784"/> |
- [TIER IV JIRA](https://tier4.atlassian.net/browse/RT1-10493)
Psim, rosbag, and evaluator
- [TIER IV Evaluator](https://evaluation.tier4.jp/evaluation/reports/d17a5846-24dc-57ef-a8ee-8fc197924ca3?project_id=prd_jt) : no degradation.
None.
None.
Remove some possible false positives with the `out_of_lane` module.

feat(out_of_lane): cut trajectory footprints behind the current ego front

---

system/autoware_system_monitor/CHANGELOG.rst

The change log for "autoware_system_monitor" about v0.44.0 was missing though performance improvement for process_monitor had been introduced in the version.
The cause of the missing log is unknown. Maybe it was because the merging was made just before the versioning operation.
This PR adds the missing ticket link to the v0.44.0 log line in autoware_system_monitor/CHANGELOG.rst.
- None.
- Just an addition of text comment. No need to test it
None.
None.
None.

fix(autoware_system_monitor): fix a ticket link in CHANGELOG.rst (about v0.44.0)

---

launch/tier4_localization_launch/launch/localization.launch.xml
launch/tier4_localization_launch/launch/pose_twist_fusion_filter/pose_twist_fusion_filter.launch.xml

This PR revises the launch configuration for `pose_instability_detector` so that parameters of `pose_instability_detector`can be defined in autoware_launch, and the node will read parameters from `autoware_launch/config` not the one in the own package by default. 
None
**Merge this PR after** https://github.com/autowarefoundation/autoware_launch/pull/1547
None.
`pose_instability_detector` will read parameters from the one in `autoware_launch/config` when launched from autoware_launch

feat(autoware_pose_instability_detector): make pose_instability_detector configurable in autoware_launch

---

perception/autoware_tensorrt_plugins/package.xml

This PR adds a dependency to tenssort_cmake_module, which is being used in the CMakeLists.txt file, but not declared in package.xml
- https://github.com/autowarefoundation/autoware-deb-packages/issues/168
None.
None.
None.

build: fix missing tensorrt_cmake_module dependency

---

perception/autoware_multi_object_tracker/src/processor/processor.cpp

Bug fix of data association matrix > max_dist_matrix usage for tracker pruning.
- Link
None.
None.
None.

fix(multi_object_tracker): correct index usage of association matrix

---

sensing/autoware_cuda_utils/CMakeLists.txt
sensing/autoware_cuda_utils/include/autoware/cuda_utils/cuda_gtest_utils.hpp
sensing/autoware_cuda_utils/package.xml
sensing/autoware_cuda_utils/test/test_cuda_check_error.cu
sensing/autoware_cuda_utils/test/test_cuda_unique_ptr.cu
sensing/autoware_cuda_utils/test/test_cuda_utils.cu
sensing/autoware_cuda_utils/test/test_main.cpp
sensing/autoware_cuda_utils/test/test_stream_unique_ptr.cu

After coming to the sad realization in #10997 that our CI currently has no GPUs and thus cannot execute CUDA unit tests, I implemented a minimal set of helpers to run CUDA tests if a GPU is available, while skipping if there is not.
The helpers are in `autoware/cuda_utils/cuda_gtest_utils.hpp` and consist of:
* the `bool is_cuda_runtime_available()` function
* the `SKIP_TEST_IF_CUDA_UNAVAILABLE()` for use with individual test cases
* the `class CudaTest : public ::testing::Test` class to use as the base class for a suite of CUDA-related tests
I also moved the non-thrust unit tests from #10997 to here since they are unrelated to that PR, and serve as validation for the gtest utils implemented here.
Unit tests do not use `ament_add_gtest` directly, as CUDA code would be compiled with a C++ …

test(cuda_utils): add unit tests, CUDA test helpers that skip if no CUDA device is available

---

planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/README.md
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/config/out_of_lane.param.yaml
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_collisions.cpp
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_collisions.hpp
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/types.hpp

Add a parameter to make the dynamic object footprints wider, making it more likely to detect `out_of_lane` collisions.
Required launch PR: https://github.com/autowarefoundation/autoware_launch/pull/1537
- [TIER IV internal link](https://tier4.atlassian.net/browse/RT0-37954)
Psim
Rosbags
None.
None.
|:--------------|:---------------|:---------|:--------------|:------------------|
| Added | `objects.extra_width`   | `double` | `1.0`         | [m] extra width around detected objects, making it more likely to detect an out of lane collision |
Can tune the `out_of_lane` collision detection.

feat(out_of_lane): add objects.extra_width parameter

---

planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/boundary_departure_prevention_module.cpp

reduce logging level
- Link
None.
None.
None.

refactor(boundary_departure): reduce autonomous mode logging level

---

sensing/autoware_cuda_utils/CMakeLists.txt
sensing/autoware_cuda_utils/include/autoware/cuda_utils/thrust_utils.hpp
sensing/autoware_cuda_utils/test/test_thrust_utils.cu

Add functions that facilitate the use of Thrust on specific CUDA streams.
This PR is a prerequisite for the thrust-on-stream performance optimization for `autoware_cuda_pointcloud_preprocessor`.
This PR adds the following:
* a `autoware/cuda_utils/thrust_utils.hpp` header
* a `thrust_on_stream(stream)` function to get a Thrust execution policy that executes on the stream
* a `thrust_stream` namespace containing convenient wrappers around `thrust::fill`, `thrust::count` etc. that take a `stream` argument
* unit tests for the above functionality
```c++
thrust::fill(thrust_on_stream(my_stream), decive_vec.begin(), device_vec.end(), 42.0);
thrust_stream::fill(decive_vec.begin(), device_vec.end(), 42.0, my_stream);
thrust_stream::fill(device_vec, 42.0, my_stream);
// The same APIs exist for …
```

feat(autoware_cuda_utils): add thrust utils

---

perception/autoware_radar_tracks_msgs_converter/src/radar_tracks_msgs_converter_node.cpp

Related https://tier4.atlassian.net/browse/RT0-37772 and https://star4.slack.com/archives/C076ZGRC15X/p1752711671288259.
(TIER IV internal link)
It enforce to this node to publish topic even if objects number is 0 so that the latter process can properly work.
- Link
None.
None.
None.

fix(radar_tracks_objects_converter): publish topic even if objects array is empty

---

planning/planning_validator/autoware_planning_validator_rear_collision_checker/config/rear_collision_checker.param.yaml
planning/planning_validator/autoware_planning_validator_rear_collision_checker/param/rear_collision_checker_node_parameters.yaml
planning/planning_validator/autoware_planning_validator_rear_collision_checker/src/rear_collision_checker.cpp
planning/planning_validator/autoware_planning_validator_rear_collision_checker/src/utils.cpp

This PR includes two functional improvements.
First, a new parameter named `lookahead_time` was introduced to allow more intuitive configuration of the collision detection start timing. Previously, it was difficult to adjust how far ahead collisions should be predicted, which sometimes resulted in delayed transitions to MRM just before a potential collision, as shown in the video below.
```yaml
adjacent_lane:
lookahead_time: 4.0                         # [s]
```
| BEFORE | AFTER |
| --- | --- |
|  <video src="https://github.com/user-attachments/assets/8779f5e4-ad20-4266-932a-460b055e8673"/> |  <video src="https://github.com/user-attachments/assets/171a5b6e-b88c-439d-a9d8-e950af121cd9"/> |
Second, the collision detection logic was extended to include objects located in front of the ego …

feat(rear_collision_checker): improve collision detection logic

---

planning/planning_validator/autoware_planning_validator/include/autoware/planning_validator/types.hpp
planning/planning_validator/autoware_planning_validator/src/node.cpp

This PR adds initialization of all validation status flags to true to prevent unnecessary error messages.
Previously, when certain plugins were not launched via the preset file, uninitialized status flags could lead to misleading error outputs.
With this change, it has been confirmed that no such errors appear even when arbitrary plugins are disabled in the preset configuration.
- [TIER IV INTERNAL LINK](https://star4.slack.com/archives/C03QU7K50D8/p1752714228502499)
None.
None.
None.

fix(planning_validator): suppress unnecessary error messages

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/default_fixed_goal_planner.cpp
planning/behavior_path_planner/autoware_behavior_path_planner/include/autoware/behavior_path_planner/behavior_path_planner_node.hpp
planning/behavior_path_planner/autoware_behavior_path_planner/src/behavior_path_planner_node.cpp
planning/behavior_path_planner/autoware_behavior_path_planner/src/planner_manager.cpp

When smoothly connecting the goal to the rest of the path, the `goal_planner` removes some path points prior to the goal. When the path is turning just before the goal, this leads to the curve of the path being lost and can cause issues in the drivable area expansion feature (see https://github.com/autowarefoundation/autoware_universe/issues/9844).
This PR fixes the issue by resampling the path before generating the drivable area, instead of after.
- https://github.com/autowarefoundation/autoware_universe/issues/9844
Psim
Evaluator [TIER IV INTERNAL LINK](https://evaluation.tier4.jp/evaluation/reports/39c542db-2ecf-5ded-9d84-7508f3d20d20?project_id=prd_jt)
None.
None.
None.

fix(behavior_path_planner): resample the path before generating the drivable area

---

planning/autoware_diffusion_planner/config/diffusion_planner.param.yaml
planning/autoware_diffusion_planner/launch/diffusion_planner.launch.xml

The launch sequence is currently disabled, so no runtime issues were expected. However, it was failing due to incorrect parameters. This PR fixes those parameter errors.
```
[ERROR] [launch]: Caught exception in launch (see debug for traceback): launch configuration 'artifact_dir' does not exist
[WARNING] [launch_ros.actions.load_composable_nodes]: Abandoning wait for the '/system/mrm_comfortable_stop_operator/mrm_comfortable_stop_operator_container/_container/load_node'
service, due to shutdown.
Future exception was never retrieved
future: <Future finished exception=InvalidHandle('cannot use Destroyable because destruction was requested')>
Traceback (most recent call last):
File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, …
```

fix(diffusion_planner): modify unread parameters

---

planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/freespace_pull_out.cpp
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/geometric_pull_out.cpp
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/shift_pull_out.cpp
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/start_planner_module.cpp
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/util.cpp

This PR replaces `getArcCoordinates()` with `getArcCoordinatesOnEgoCenterline()` to support lanelets which has custom centerlines
- https://github.com/autowarefoundation/autoware_universe/issues/10963
- https://github.com/autowarefoundation/autoware_lanelet2_extension/pull/49 is used
- [[PR check][Lexus][FuncVerificationScenario_Basic] planning test](https://evaluation.tier4.jp/evaluation/reports/18b5a58b-4241-55e4-a8f4-540b35c5884c?project_id=prd_jt)
- [[PR check][Lexus][ControlDLRCommon_Basic] DLR test](https://evaluation.tier4.jp/evaluation/reports/b4d75763-b44f-5737-92aa-96c03e0ea4a3?project_id=prd_jt)
- [[PR check][Lexus][CommonScenario_Basic] planning test](https://evaluation.tier4.jp/evaluation/reports/3556abf3-47c4-57dd-b485-68cb26e006ab?project_id=prd_jt)
None. …

feat(start_planner_module): replace getArcCoordinates with getArcCoordinatesOnEgoCenterline

---

planning/planning_validator/autoware_planning_validator_intersection_collision_checker/include/autoware/planning_validator_intersection_collision_checker/types.hpp

minor fix to use parameterized value instead of a static constexpr
- Link
None.
None.
None.

fix(intersection_collision_checker): use parameter instead of static constexpr

---

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/include/autoware/behavior_path_static_obstacle_avoidance_module/parameter_helper.hpp

This PR fixes a bug where the `unstable_classification_time` parameter was not being loaded in the static obstacle avoidance module, despite being defined in the parameter structure. This oversight prevented the module from properly utilizing the unstable classification handling functionality.
- Added parameter loading for the existing `unstable_classification_time` parameter in the `getParameter` function
- Link
- https://evaluation.tier4.jp/evaluation/reports/78ecf951-b0bd-5646-82e2-5ecd76e163d8?project_id=prd_jt
- https://evaluation.tier4.jp/evaluation/reports/3a7dc916-0685-5567-8aa2-0f91ae5e3515?project_id=prd_jt
- https://evaluation.tier4.jp/evaluation/reports/e99537cb-3692-547d-a9f7-0eb555ed89b6?project_id=prd_jt
None.
None.
None.

fix(static_obstacle_avoidance): load missing unstable classification parameter

---

planning/behavior_path_planner/autoware_behavior_path_static_obstacle_avoidance_module/src/scene.cpp

This PR updates the logic that checks for the existence of adjacent lanes during obstacle avoidance.
Previously, the system checked whether adjacent lanes (left or right) existed for all current lanelets. However, this is unnecessary and may lead to incorrect results, especially when the route includes branches or merges beyond the avoidance target.
With this update, the adjacent lane existence check is limited to the range of lanelets between the ego vehicle and the last avoidance target object. This refinement ensures that lane departure detection during avoidance is based only on the relevant portion of the route.
:information_source: **This change does not affect the intended behavior of the system**, as the adjacent lane check is only adjusted to reflect the necessary scope for …

fix(static_obstacle_avoidance): correct lane departure check during obstacle avoidance

---

perception/autoware_map_based_prediction/README.md
perception/autoware_map_based_prediction/config/map_based_prediction.param.yaml
perception/autoware_map_based_prediction/include/map_based_prediction/data_structure.hpp
perception/autoware_map_based_prediction/include/map_based_prediction/predictor_vru.hpp
perception/autoware_map_based_prediction/schema/map_based_prediction.schema.json
perception/autoware_map_based_prediction/src/map_based_prediction_node.cpp
perception/autoware_map_based_prediction/src/predictor_vru.cpp

This PR improves the robustness of crossing intention estimation against noise in velocity and pose estimation.
Previously, small fluctuations in perceived object velocity or orientation could cause the estimated intention to switch frequently, leading to unstable behavior near crosswalks.
To address this, a time-based filtering mechanism was introduced. The intention is now only judged as true or false if the corresponding condition has persisted for a specified duration.
`crossing_intention_duration` defines how long the system must continuously detect a crossing intention before accepting it.
`no_crossing_intention_duration` defines how long the system must continuously detect the absence of intention before clearing it.
As a result, the intention estimation becomes more stable and …

feat(map_based_prediction): prevent predicted path from chattering under noisy pose and velocity estimation

---

perception/autoware_traffic_light_classifier/src/classifier/cnn_classifier.cpp
perception/autoware_traffic_light_classifier/src/traffic_light_classifier_node.cpp

This PR moves `rclcpp::shutdown();` from child to parent to avoid `rclcpp::exceptions::RCLError` when use `build_only:=true`.
- Link
I checked no error like `rclcpp::exceptions::RCLError` when finish building tensorRT.
```
TLC=traffic_light_classifier && ros2 launch autoware_${TLC} car_${TLC}.launch.xml   model_path:=$HOME/autoware_data/${TLC}/${TLC}_mobilenetv2_batch_6.onnx   label_path:=$HOME/autoware_data/${TLC}/lamp_labels.txt   build_only:=true
TLC=traffic_light_classifier && ros2 launch autoware_${TLC} pedestrian_${TLC}.launch.xml   model_path:=$HOME/autoware_data/${TLC}/ped_${TLC}_mobilenetv2_batch_6.onnx   label_name:=$HOME/autoware_data/${TLC}/lamp_labels_ped.txt  build_only:=true
```
Run on Evaluator.
https://evaluation.ci.tier4.jp/evaluation/reports/a9a66508-bb …

feat(autoware_traffic_light_classifier): move `rclcpp::shutdown();` from child to parent to avoid `rclcpp::exceptions::RCLError`

---

planning/autoware_diffusion_planner/README.md

- README in `autoware_diffusion_planner` package has the obsolete information, so remove it and update with correct information.
None.
This PR includes the changes only with docs. So I did not run any tests.
None.
None.
None.

docs(autoware_diffusion_planner): remove obsolete information

---

planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/calculate_slowdown_points.cpp
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/calculate_slowdown_points.hpp
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_collisions.cpp
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_collisions.hpp
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_module.hpp
planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/types.hpp

Refactor the code of the `out_of_lane` module to record the objects that cause a collision. This information is then used to populate the `SafetyFactorArray` of the planning factor published by the module.
- Link
None.
None.
None.

feat(out_of_lane): add safety factors to the published planning factor

---

sensing/autoware_cuda_pointcloud_preprocessor/include/autoware/cuda_pointcloud_preprocessor/cuda_pointcloud_preprocessor.hpp
sensing/autoware_cuda_pointcloud_preprocessor/include/autoware/cuda_pointcloud_preprocessor/organize_kernels.hpp
sensing/autoware_cuda_pointcloud_preprocessor/include/autoware/cuda_pointcloud_preprocessor/types.hpp
sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_pointcloud_preprocessor/cuda_pointcloud_preprocessor.cu
sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_pointcloud_preprocessor/organize_kernels.cu

This PR replaces all `thrust::` algorithm calls with their `thrust_stream::` equivalents that were introduced in #10997.
Thrust executes algorithms operating on device vectors on the process's default stream by default, and `thrust_stream` ensures execution on the stream the user provided.
Since Autoware CUDA Pointcloud Preprocessor is using CUDA Blackboard which requires all GPU data pub/sub to be done in one process, multiple CUDA-based nodes are commonly launched into the same node container (= process).
Thus, nodes triggering a sync on the default stream might cause delays and inefficiencies for other nodes in the container.
This PR reduces the `39.2%` default stream utilization to just `0.3%` -- a 130x improvement :innocent: 
- Link
Ran on software version [TIER IV …

perf(autoware_cuda_pointcloud_preprocessor): execute thrust operations on the node's own CUDA stream

---

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/interface.cpp

If force activation request is received when there is no valid lc path, LC module state will be left hanging in RUNNING state and cannot properly transition to FAILURE.
This PR fixes this issue by confirming there is a valid path when force activation request is received. If there is no valid path, the request is ignored and a warning msg is displayed.
- Link
- PSIM
None.
None.
None.

fix(lane_change): properly handle force activation when there is no valid LC path

---

planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/CMakeLists.txt
planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/config/run_out.param.yaml
planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/schema/run_out.schema.json
planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/src/debug.hpp
planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/src/parameters.hpp
planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/src/run_out_module.cpp

The `run_out` module debug markers can be too heavy and cause performance issues.
This PR adds parameters to enable or disable the publishing of some debug markers.
Launch PR: https://github.com/autowarefoundation/autoware_launch/pull/1580
- Link
Using the following scene with many objects/collisions:
Using `ros2 topic bw /planning/scenario_planning/lane_driving/motion_planning/motion_velocity_planner/run_out/debug_markers` to evaluate the size of the debug markers message.
| Enabled debug markers | Message size |
| --- | --- |
| None | 0.24 KB |
| All | 460 KB |
| `ego_footprint` |53.74 KB |
| `objects` | 190 KB |
| `collisions` | 6.38 KB |
| `decisions` | 1.28 KB |
| `filtering_data` |210 KB |
None.
None.
| Change type   | Parameter Name | Type     | Default Value | …

feat(run_out): add parameters to select which debug markers to publish

---

planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/clothoid_pull_out.cpp

There are too many unnecessary error messages in terminal, so I change the log level to stop unwanted messages from appearing in the terminal.
- Link
build success
None.
None.
None.

refactor(clothoid_pull_out): change log level from WARN to DEBUG/INFO

---

common/autoware_boundary_departure_checker/include/autoware/boundary_departure_checker/data_structs.hpp
common/autoware_boundary_departure_checker/include/autoware/boundary_departure_checker/parameters.hpp
common/autoware_boundary_departure_checker/include/autoware/boundary_departure_checker/utils.hpp
common/autoware_boundary_departure_checker/src/boundary_departure_checker_abnormality.cpp
common/autoware_boundary_departure_checker/src/utils.cpp
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/config/boundary_departure_prevention.param.yaml
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/schema/boundary_departure_prevention.schema.json
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/boundary_departure_prevention_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/parameters.hpp
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/utils.cpp
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/utils.hpp

The PR aims to fix issues with merging closeby departure points and departure intervals.
Close-by points scatter
https://github.com/user-attachments/assets/eb5fce33-ac1d-4a65-bf82-fbfc03310b0d
Merging nearby points
Result
https://github.com/user-attachments/assets/e6b4d752-497a-4cf5-b138-a7377c50362d
Departure points is grouped together
Example
But if the point is inline, it is not merged. So this PR aims to fix this as well
- Link
[CommonBasic](https://evaluation.tier4.jp/evaluation/reports/2b2e8dbf-69d2-5499-aed0-72b44ac3ab3f?project_id=prd_jt)
[FuncVerification](https://evaluation.tier4.jp/evaluation/reports/f513573d-a156-5342-9631-f769edd6ea42?project_id=prd_jt)
[CommonDLR](https://evaluation.tier4.jp/evaluation/reports/c1437ce6-a2a0-5c12-9c56-b9acf19fe882?project_id= …

fix(boundary_departure): merging multiple close by departure points

---

control/autoware_trajectory_follower_node/include/autoware/trajectory_follower_node/controller_node.hpp
control/autoware_trajectory_follower_node/test/test_controller_node.cpp
planning/autoware_mission_planner_universe/src/mission_planner/mission_planner.cpp
planning/autoware_scenario_selector/src/node.cpp

This PR changes all subscriptions of `/system/operation_mode/state` to `transient_local` to keep its setting the same as the publisher.
Without this fixing PR, the scenario tests will randomly fail with the error ([example failure case](https://evaluation.tier4.jp/evaluation/reports/9829997d-4d97-51af-8ed7-09a64e8d04f1/tests/3b97a871-478a-5e12-bec8-0edec0585d3d/7e4482ad-6414-5632-973c-6985ac16ff9e/d97615d1-bd52-5e9a-af4b-89dea3640ec2?failure_cause_labels=SimulationError%3AAutowareError&project_id=prd_jt)):
```
Simulation error [AutowareError]: Simulator waited for the Autoware state to transition to WAITING_FOR_ENGAGE, but time is up. The current Autoware state is PLANNING
```
fixing PR of autoware_core: https://github.com/autowarefoundation/autoware_core/pull/598
fixing PR of …

fix(autoware_trajectory_follower, autoware_mission_planner_universe, autoware_scenario_selector): use transient_local for operation_mode_state

---

control/autoware_operation_mode_transition_manager/src/state.cpp

This PR will fix a problem: for bool isModeChangeAvailable(), when `check_engage_condition_` is set as `false`, it will return `true` before `enable_engage_on_driving_`  is checked.
So, even if `enable_engage_on_driving_` is set as `false`, the vehicle can be engaged when the vehicle is driving. It is dangerous.
I made a change in this PR.
The condition of `enable_engage_on_driving_` will be checked before `check_engage_condition_`. 
https://tier4.atlassian.net/browse/RT0-38624
None.
None.
None.
None.

fix(operation_mode_transition_manager): modify the engage condition

---

perception/autoware_image_projection_based_fusion/src/fusion_node.cpp

- The `Camera projector` quite  takes time for initialization when [point_project_to_unrectified_image](https://github.com/autowarefoundation/autoware_universe/blob/e9d43e45ca477ec70e58421be59cebf867f11f5e/perception/autoware_image_projection_based_fusion/config/fusion_common.param.yaml#L12) are enable. 
- This PR will add the initializing status log at 1Hz until the initialization is completed.
- [TIER IV internal link](https://star4.slack.com/archives/C03S84LDJGG/p1753748259794539?thread_ts=1753747231.813589&cid=C03S84LDJGG) 
- Run `logging_simulator`. I tested with `point_project_to_unrectified_image: [false, false, false, true, false, true]`
- Play a rosbag to publish `camera_info` topics
- Confirm the initializing status is logged.
``` …
```

chore(image_projection_based_fusion): add initializing status log

---

system/autoware_system_monitor/include/system_monitor/net_monitor/net_monitor.hpp
system/autoware_system_monitor/src/net_monitor/net_monitor.cpp

- The System Monitor currently measures system resource statuses and publishes the results mainly to the /diagnostics topic. However, due to the complex structure of the /diagnostics message, extracting specific information (e.g., memory usage) can be expensive for external tools or monitoring systems.
- To make system resource status more easily accessible, the measured data should be published to a dedicated topic.  This enables external resource monitoring tools to access system resource statuses without parsing diagnostic arrays
- This PR introduces a feature to publish network status
**This PR needs the following PR**
- https://github.com/tier4/tier4_autoware_msgs/pull/187
- [TIER IV internal link](https://tier4.atlassian.net/browse/RT0-38268)
- This PR is one of …

feat(autoware_system_monitor): publish network_status

---

control/autoware_control_validator/src/control_validator.cpp
planning/planning_validator/autoware_planning_validator/include/autoware/planning_validator/types.hpp

The trajectory validation was previously outputting an ERROR status even when no trajectory had been published from upstream modules.
However, it is inappropriate to judge the trajectory as invalid before any trajectory has been received.
This update changes the behavior so that the validation result remains OK until a trajectory is actually subscribed.
Note: The absence of a published trajectory is expected to be detected and reported by a separate diagnostic.
- Link
None.
None.
None.

fix(planning_validator): init validation status

---

system/autoware_system_monitor/include/system_monitor/cpu_monitor/cpu_monitor_base.hpp
system/autoware_system_monitor/include/system_monitor/cpu_monitor/intel_cpu_monitor.hpp
system/autoware_system_monitor/include/system_monitor/cpu_monitor/raspi_cpu_monitor.hpp
system/autoware_system_monitor/src/cpu_monitor/cpu_monitor_base.cpp
system/autoware_system_monitor/src/cpu_monitor/intel_cpu_monitor.cpp
system/autoware_system_monitor/src/cpu_monitor/raspi_cpu_monitor.cpp

- The System Monitor currently measures system resource statuses and publishes the results mainly to the /diagnostics topic. However, due to the complex structure of the /diagnostics message, extracting specific information (e.g., memory usage) can be expensive for external tools or monitoring systems.
- To make system resource status more easily accessible, the measured data should be published to a dedicated topic.  This enables external resource monitoring tools to access system resource statuses without parsing diagnostic arrays
- This PR introduces a feature to publish CPU temperature data 
**This PR needs the following PR**
- https://github.com/tier4/tier4_autoware_msgs/pull/187
- [TIER IV internal link](https://tier4.atlassian.net/browse/RT0-38268)
- This PR is …

feat(autoware_system_monitor): publish cpu_temperature

---

system/autoware_system_monitor/include/system_monitor/hdd_monitor/hdd_monitor.hpp
system/autoware_system_monitor/src/hdd_monitor/hdd_monitor.cpp

- The System Monitor currently measures system resource statuses and publishes the results mainly to the /diagnostics topic. However, due to the complex structure of the /diagnostics message, extracting specific information (e.g., memory usage) can be expensive for external tools or monitoring systems.
- To make system resource status more easily accessible, the measured data should be published to a dedicated topic.  This enables external resource monitoring tools to access system resource statuses without parsing diagnostic arrays
- This PR introduces a feature to publish HDD status
**This PR needs the following PR**
- https://github.com/tier4/tier4_autoware_msgs/pull/187
- [TIER IV internal link](https://tier4.atlassian.net/browse/RT0-38268)
- This PR is one of the …

feat(autoware_system_monitor): publish hdd_status

---

evaluator/autoware_control_evaluator/config/control_evaluator.param.yaml
evaluator/autoware_control_evaluator/include/autoware/control_evaluator/control_evaluator_node.hpp
evaluator/autoware_control_evaluator/schema/autoware_control_evaluator.schema.json
evaluator/autoware_control_evaluator/src/control_evaluator_node.cpp

Add an option to accumulate `output_metrics` only when the ego is moving
- Link
Psim
Evaluators: https://github.com/tier4/auto-evaluator/actions/runs/16794062288
- https://evaluation.tier4.jp/evaluation/reports/bec20f55-2328-5427-a0ec-74911a2d2568/?project_id=prd_jt
- https://evaluation.tier4.jp/evaluation/reports/22adae36-ede4-57b4-9c00-31e5333fdac6/?project_id=prd_jt
- https://evaluation.tier4.jp/evaluation/reports/06532098-91f7-5837-99ac-842e7e36b5f1/?project_id=prd_jt
None.
None.
None.

feat(control_evaluator): add option to output_metrics only when ego is moving

---

planning/autoware_surround_obstacle_checker/CMakeLists.txt
planning/autoware_surround_obstacle_checker/package.xml
planning/autoware_surround_obstacle_checker/src/debug_marker.cpp
planning/autoware_surround_obstacle_checker/src/debug_marker.hpp
planning/autoware_surround_obstacle_checker/src/node.cpp
planning/autoware_surround_obstacle_checker/src/node.hpp
planning/autoware_surround_obstacle_checker/src/type_alias.hpp
planning/autoware_surround_obstacle_checker/src/types.hpp
planning/autoware_surround_obstacle_checker/test/test_planning_factor.cpp

Modified the node to output the position of the surrounding obstacle as a safety factor when the vehicle continues to stop due to the presence of an obstacle.
for dynamic object
```
header:
stamp:
sec: 1754471033
nanosec: 672960685
frame_id: map
factors:
- module: surround_obstacle_checker
is_driving_forward: true
control_points:
- pose:
position:
x: 65807.20236144973
y: 722.58775493961
z: 755.2288120813373
orientation:
x: -0.007346690804710143
y: -0.010259139380741078
z: -0.5821745060128938
w: 0.8129659407023333
velocity: 0.0
shift_length: 0.0
distance: 0.0
behavior: 3
detail: ''
safety_factors:
header:
stamp:
sec: 1754471033
nanosec: 672953167
frame_id: map
factors:
- type: 2
object_id:
uuid:
- 141
- 249
- 27
- 225
- 52
- 227
- 106
- 128
- 195
- 117
- 67
- 45
- 42
- 26
- 249
- 168 …
```

feat(surround_obstacle_checker): add safety factors to the published planning factor

---

.github/workflows/build-test-tidy-pr.yaml

This pull request makes a minor update to the build and test workflow configuration by including the `planning/autoware_diffusion_planner` directory in the list of files that trigger the workflow.
- https://github.com/autowarefoundation/autoware_universe/pull/11147
None.
None.
None.

ci(autoware_diffusion_planner): add planning/autoware_diffusion_planner/**

---

planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/slow_down_interpolator.cpp
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/slow_down_interpolator.hpp
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/utils.cpp

Previously only comfortable-based and  sudden-based deceleration profiles are accepted. However, due to to this, it has caused several sudden deceleration problem.
To fix this, this PR calculated feasible acceleration if comfortable decel is not possible.
- Link
TBA
None.
None.
None.

fix(boundary_departure): gradual slow down with feasible profile

---

planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/boundary_departure_prevention_module.cpp

Add check if type exist in `diagnostic_output` before checking its content. 
- Link
Build and test autoware.
None.
None.
None.

refactor(boundary_departure): check output exist and matches type for diagnostic level

---

control/autoware_mpc_lateral_controller/include/autoware/mpc_lateral_controller/mpc_utils.hpp
control/autoware_mpc_lateral_controller/src/mpc.cpp
control/autoware_mpc_lateral_controller/src/mpc_utils.cpp

This PR populates the `front_wheel_angle_rad` field of the MPC predicted trajectory message.
Needed for https://github.com/autowarefoundation/autoware_universe/pull/11130
- Link
None.
None.
None.

feat(mpc_lateral_controller): publish the wheel angle in the predicted trajectory

---

planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp

This PR fixes an issue in the stop point calculation during restart suppression, which occurs when the next stop position is within a configured threshold and the vehicle should remain stopped instead of restarting. Previously, the inserted stop point was calculated directly from the ego pose without projecting it onto the path, causing the planned trajectory to become distorted. The fix projects the ego position onto the path using `calcSignedArcLength` and `calcLongitudinalOffsetPose`, ensuring the stop point lies exactly on the path and preventing path deformation while maintaining the intended restart suppression behavior.
| BEFORE | AFTER |
| --- | --- |
|  <video src="https://github.com/user-attachments/assets/cf48a7ec-f679-4a08-a82d-b99e069d504f"/> |  <video …

fix(crosswalk): fix: incorrect inserted stop point calculation for restart suppression

---

system/autoware_command_mode_decider_plugins/src/command_mode_decider.cpp
system/autoware_command_mode_decider_plugins/src/command_mode_decider.hpp

Fixed an issue where mode switch condition was checked even when the mode was continued.
- https://github.com/tier4/autoware_universe/pull/2271
Check the MRM is not activated when switching to autonomous mode.
None.
None.
None.

fix(command_mode_decider): fix mode continuation condition

---

planning/autoware_diffusion_planner/include/autoware/diffusion_planner/diffusion_planner_node.hpp
planning/autoware_diffusion_planner/include/autoware/diffusion_planner/preprocessing/lane_segments.hpp
planning/autoware_diffusion_planner/src/diffusion_planner_node.cpp
planning/autoware_diffusion_planner/src/preprocessing/lane_segments.cpp

This PR refactors the diffusion planner's lane segment processing by simplifying the API and consolidating data extraction logic. The changes focus on improving code organization and reducing complexity in the lane segment handling.
- Simplified the `transform_and_select_rows` method to directly return processed data vectors instead of intermediate matrices
- Consolidated lane tensor data extraction logic into the main processing method
- Removed unused utility functions and type aliases to reduce code complexity
run diffusion_planner
```bash
on_timer         11.7 ± 3.5 msec
create_input_data        3.4 ± 0.9 msec
do_inference_trt         7.0 ± 2.5 msec
```
None.
None.
None.

refactor(diffusion_planner): fix `transform_and_select_rows`

---

planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/config/boundary_departure_prevention.param.yaml
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/schema/boundary_departure_prevention.schema.json
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/boundary_departure_prevention_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/boundary_departure_prevention_module.hpp
planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/parameters.hpp

Adding off time buffer to clear critical departure points.
Before:
Critical departure points persist despite critical departure no longer detected.
https://github.com/user-attachments/assets/cdfd19df-2a98-4290-91c6-16f6c5cc4f7a
After:
Critical departure points cleared once critical departure no longer detected.
https://github.com/user-attachments/assets/26afe413-225b-4bbf-add4-1f9519c3df1e
Corresponding launcher: https://github.com/autowarefoundation/autoware_launch/pull/1606
- Link
https://evaluation.tier4.jp/evaluation/reports/004344b3-3901-5051-8533-e54e4212b773?project_id=prd_jt
https://evaluation.tier4.jp/evaluation/reports/56cb3142-e974-5975-bd57-75a4752b7367?project_id=prd_jt
https://evaluation.tier4.jp/evaluation/reports/17a0c33f-e8f3-554c-8eb7-5c8f14b30fea?projec …

fix(boundary_departure): critical departure not cleared

---

planning/autoware_diffusion_planner/src/conversion/lanelet.cpp

Removed unused function based on cppcheck
```
planning/autoware_diffusion_planner/src/conversion/lanelet.cpp:35:14: style: The function 'euclidean_distance' is never used. [unusedFunction]
inline float euclidean_distance(const LanePoint & p1, const LanePoint & p2)
^
```
- Link
None.
None.
None.

fix(autoware_diffusion_planner): remove unused function

---

planning/motion_velocity_planner/autoware_motion_velocity_boundary_departure_prevention_module/src/boundary_departure_prevention_module.cpp

Support additional parameters for dynamic reconfiguration for boundary departure.
- Link
Build and run autoware, and test changing parameters around.
None.
None.
None.

feat(boundary_departure): support addition parameters for dynamic reconfiguration 

---

system/autoware_command_mode_decider/src/command_mode_decider_base.cpp

Removed unused function based on cppcheck
```
system/autoware_command_mode_decider/src/command_mode_decider_base.cpp:27:6: style: The function 'logging_mode_change' is never used. [unusedFunction]
void logging_mode_change(
^
```
- Link
None.
None.
None.

fix(autoware_command_mode_decider): remove unused function

---

planning/behavior_path_planner/autoware_behavior_path_start_planner_module/include/autoware/behavior_path_start_planner_module/util.hpp
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/util.cpp

Removed an unused function
```
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/util.cpp:203:21: style: The function 'calc_curvature_from_points' is never used. [unusedFunction]
std::vector<double> calc_curvature_from_points(
^
```
- Link
None.
None.
None.

fix(behavior_path_planner): remove unused function

---

common/autoware_boundary_departure_checker/include/autoware/boundary_departure_checker/utils.hpp
common/autoware_boundary_departure_checker/src/utils.cpp

Removed an unused function
```
common/autoware_boundary_departure_checker/src/utils.cpp:611:8: style: The function 'compute_braking_distance' is never used. [unusedFunction]
double compute_braking_distance(
^
```
- Link
None.
None.
None.

fix(autoware_boundary_departure_checker): remove unused function

---

visualization/tier4_planning_factor_rviz_plugin/src/planning_factor_rviz_plugin.hpp

Removed unused function
```
visualization/tier4_planning_factor_rviz_plugin/src/planning_factor_rviz_plugin.hpp:87:8: style: The function 'delete_marker' is never used. [unusedFunction]
void delete_marker(rviz_default_plugins::displays::MarkerID marker_id)
^
```
- Link
None.
None.
None.

fix(tier4_planning_factor_rviz_plugin): remove unused function

---

planning/behavior_path_planner/autoware_behavior_path_bidirectional_traffic_module/include/autoware/behavior_path_bidirectional_traffic_module/utils.hpp
planning/behavior_path_planner/autoware_behavior_path_bidirectional_traffic_module/src/utils.cpp

Removed unused function
```
planning/behavior_path_planner/autoware_behavior_path_bidirectional_traffic_module/src/utils.cpp:72:24: style: The function 'filter_intersection_lanelets' is never used. [unusedFunction]
lanelet::ConstLanelets filter_intersection_lanelets(const lanelet::ConstLanelets & all_lanelets)
^
```
- Link
None.
None.
None.

fix(autoware_behavior_path_bidirectional_traffic_module): remove unused function

---

control/autoware_control_command_gate/src/common/control_command_filter.cpp

Fixed `ignoredReturnValue` warning by cppcheck
```
control/autoware_control_command_gate/src/common/control_command_filter.cpp:140:10: warning: Return value of function std::clamp() is not used. [ignoredReturnValue]
std::clamp(input.lateral.steering_tire_angle, -M_PI_2f, M_PI_2f);
^
```
See https://github.com/autowarefoundation/autoware_universe/blob/d15567798f40a0041858dc8970f4f0c426882079/control/autoware_vehicle_cmd_gate/src/vehicle_cmd_filter.cpp#L129-L146
- Link
None.
None.
None.

fix(autoware_control_command_gate): solve ignoredReturnValue warning

---

common/autoware_boundary_departure_checker/package.xml

This adds missing dependency to magic_enum for autoware_boundary_departure_checker package which is used in https://github.com/autowarefoundation/autoware_universe/blob/63a591c657aed45c22584b23afc1667a4323fd3b/common/autoware_boundary_departure_checker/include/autoware/boundary_departure_checker/data_structs.hpp#L26
None.
None.
None.

fix(autoware_boundary_departure_checker): add missing dependency to magic_enum

---

planning/behavior_path_planner/autoware_behavior_path_start_planner_module/include/autoware/behavior_path_start_planner_module/util.hpp
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/util.cpp

Removed an unused fuction
```
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/util.cpp:163:21: style: The function 'calc_curvature_from_trajectory' is never used. [unusedFunction]
std::vector<double> calc_curvature_from_trajectory(
^
```
- Link
None.
None.
None.

fix(autoware_behavior_path_start_planner_module): remove unused function

---

planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/src/util.cpp

Removed an unused fuction
```
planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/src/util.cpp:232:38: style: The function 'sibling_straight_lanelet' is never used. [unusedFunction]
std::optional<lanelet::ConstLanelet> sibling_straight_lanelet(
^
```
- Link
None.
None.
None.

fix(autoware_behavior_velocity_blind_spot_module): remove unused function

---

planning/behavior_path_planner/autoware_behavior_path_planner_common/src/interface/scene_module_manager_interface.cpp

Fixed the namespace of the topic for processing time debug information to align that of bvp.
NOTE: When I check the logpacker configuration file, the bpp processing time isn’t recorded in the rosbag when using the previous namespace.
- [X2 logpacker config (TIER IV INTERNAL LINK)](http://github.com/tier4/pilot-auto.x2/blob/main/ansible/playbooks/templates/logpacker/logpacker_config_x2.yaml.jinja2)
- [XX1 logpacker config (TIER IV INTRENAL LINK)](https://github.com/tier4/pilot-auto.xx1/blob/main/ansible/playbooks/templates/logpacker/logpacker_config.yaml.jinja2)
- Link
Psim
None.
| Version | Topic Type | Topic Name | Message Type | Description |
|:--------|:-----------|:-----------|:--------------|:------------|
| Old | Pub | …

fix(bpp): namespace of the processing time topic

---

planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/config/blind_spot.param.yaml
planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/include/autoware/behavior_velocity_blind_spot_module/parameter.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/src/parameter.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/src/scene.cpp

add the flag to `detect_non_vru` since previous blind_spot module did not react to them
https://github.com/autowarefoundation/autoware_launch/pull/1612
https://tier4.atlassian.net/browse/RT0-38916
- https://evaluation.tier4.jp/evaluation/reports/9bd05859-a240-5b75-afc5-e0b7be6484cd?project_id=prd_jt
- https://evaluation.tier4.jp/evaluation/reports/e9fc319e-324a-5520-95e1-e4cd64335667?project_id=prd_jt
- https://evaluation.tier4.jp/evaluation/reports/f824b442-c02e-5582-b80a-cb877237d48e?project_id=prd_jt
None.
None.
None.

feat(blind_spot): add the flag to ignore non vru

---

vehicle/autoware_accel_brake_map_calibrator/launch/accel_brake_map_calibrator.launch.xml

remove output suffix from accel_brake_map_calibrator's output topic
- Link
None.
None.
None.

chore(accel_brake_map_calibrator): change output topic name of accel_brake_map_calibrator

---

planning/autoware_diffusion_planner/include/autoware/diffusion_planner/conversion/agent.hpp
planning/autoware_diffusion_planner/src/conversion/agent.cpp

This PR fixes the order of width and length parameters in the diffusion planner to match the original implementation from the upstream repository.
- Original Diffusion Planner
- https://github.com/ZhengYinan-AIR/Diffusion-Planner/blob/5659e494250523a603902e1c3dca0651d2e4c6fa/diffusion_planner/data_process/agent_process.py#L252-L253
- tier4/DiffusionPlanner
- https://github.com/tier4/Diffusion-Planner/blob/bb38c7215fba922c7fbd02919f0c46663af15792/ros_scripts/parse_rosbag.py#L184-L185
run diffusion planner
See https://github.com/autowarefoundation/autoware_universe/pull/11110
None.
None.
None.

fix(diffusion_planner): change the order of width and length

---

launch/tier4_control_launch/launch/control.launch.xml
launch/tier4_planning_launch/launch/planning.launch.xml
launch/tier4_planning_launch/launch/scenario_planning/lane_driving.launch.xml
launch/tier4_planning_launch/launch/scenario_planning/lane_driving/behavior_planning/behavior_planning.launch.xml
launch/tier4_planning_launch/launch/scenario_planning/lane_driving/motion_planning/motion_planning.launch.xml
launch/tier4_planning_launch/launch/scenario_planning/parking.launch.xml
planning/planning_validator/autoware_planning_validator/launch/planning_validator.launch.xml

This PR parameterizes perception-related topic names in Autoware launch files. It replaces hardcoded topic names `/perception/object_recognition/objects` and `/perception/obstacle_segmentation/pointcloud` with configurable arguments, enabling dynamic topic name configuration based on perception filter usage.
- Link
None.
| Version | Topic Type | Topic Name                                                 | Message Type                                      | Description                                           |
| :------ | :--------- | :--------------------------------------------------------- | :------------------------------------------------ | :---------------------------------------------------- |
| Old     | Sub        | `/perception/object_recognition/objects` …

refactor(launch):  topic remapping for object recognition and point cloud input to planning/control module

---

perception/autoware_multi_object_tracker/include/autoware/multi_object_tracker/tracker/model/tracker_base.hpp
perception/autoware_multi_object_tracker/lib/tracker/model/pass_through_tracker.cpp
perception/autoware_multi_object_tracker/lib/tracker/model/tracker_base.cpp
perception/autoware_multi_object_tracker/lib/tracker/model/unknown_tracker.cpp
perception/autoware_multi_object_tracker/src/processor/processor.cpp

isConfident is a method to determine whether the tracker is confident enough to be used for the following purpose.
- merge trackers
- publish
When extrapolation time is long (only when `enable_delay_compensation` is true), the position covariance becomes larger.
To make a fair and stable outcome, the function is enabled to choose given time, depends on its purpose.
- specific time (for merge trackers)
- last tracker time + constant interval (for publish)
The constant interval is used to consider motion (velocity) uncertainty into the position uncertainty.
Related with PR https://github.com/autowarefoundation/autoware_universe/pull/11230
This test is over https://github.com/autowarefoundation/autoware_universe/pull/11230
Before
https://github.com/user-attachments/assets/4d7fca0d-c890-472c-a …

fix(autoware_multi_object_tracker): update isConfident method signature and logic for time handling

---

perception/autoware_multi_object_tracker/include/autoware/multi_object_tracker/tracker/motion_model/bicycle_motion_model.hpp
perception/autoware_multi_object_tracker/lib/tracker/motion_model/bicycle_motion_model.cpp

After https://github.com/autowarefoundation/autoware_universe/pull/11230, detected object and the tracked object position is shifted.
This is due to a faulty implementation of object center position calculation from the tracker state vector.
Before fix
Red: detected object
Blue: tracked object
- Link
tested by planning simulator
After fix
None.
None.
None.

fix(multi object tracker): bug fix of object position from tracker state vector

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/include/autoware/behavior_path_goal_planner_module/goal_searcher.hpp
planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/goal_planner_module.cpp

if the flag `bus_stop_area.use_bus_stop_area` is true, the objects overlapping with the designated bus_stop_area are ignore in goal_planner, to delegate the stopping feature to obstacle_stop
https://github.com/user-attachments/assets/3c77f1c4-b645-4c58-87b9-5ff39d872cb9
https://tier4.atlassian.net/browse/RT0-38852
- https://evaluation.tier4.jp/evaluation/reports/50a59408-4c69-5df3-92c5-264159ec6718?project_id=prd_jt
- https://evaluation.tier4.jp/evaluation/reports/66ae64d3-ce26-59bd-932c-5c707eb0ea29?project_id=prd_jt
- https://evaluation.tier4.jp/evaluation/reports/e8bc3d48-716f-559a-b589-68fcde6057c7?project_id=prd_jt
None.
None.
None.

feat(goal_planner): ignore parked object in bus_stop

---

planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/include/autoware/behavior_velocity_blind_spot_module/scene.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/include/autoware/behavior_velocity_blind_spot_module/util.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/src/scene.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/src/util.cpp

The blind spot module currently slows down the vehicle whenever an object overlaps with the attention area.
This can result in false positives when an object’s width is larger than the available lateral clearance.
VRUs (pedestrians, bicycles, motorcycles): Their size is generally small, and they have more flexibility to squeeze through narrow gaps. Prediction noise may also cause their detected size to fluctuate, but this is acceptable. The current logic continues to handle VRUs as before.
Non-VRUs (e.g., cars): Their maneuverability is limited and they cannot realistically pass through gaps smaller than their width, which leads to unnecessary stop in the current approach.
This PR updates the blind spot check only for non-VRUs by comparing the lateral clearance with the object’s width.
If …

fix(blind_spot): filter non-vru based on lateral clearance

---

planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/include/autoware/behavior_velocity_blind_spot_module/util.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/src/scene.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_blind_spot_module/src/util.cpp

cut `virtual_blind_lane_boundary_after_turning` and ``virtual_ego_straight_path_after_turning` so that it doesn't exceed intersection lanelet's boundary.
|:---:|:----:|
|  <img width="2243" height="752" alt="image" src="https://github.com/user-attachments/assets/3651cedd-3fde-4d87-a349-701bbd93eb0b" /> |  <img width="2251" height="492" alt="image" src="https://github.com/user-attachments/assets/2bc3c868-d70a-4690-8ee6-44f34775bfdf" /> |
| <img width="1040" height="1469" alt="image" src="https://github.com/user-attachments/assets/d4303362-bc55-4277-ad8b-ce7685f14536" />    | <img width="937" height="1008" alt="image" src="https://github.com/user-attachments/assets/439a6c56-0a5f-4ca5-b1bb-6178bc3c8c05" /> |
| <img width="1919" height="933" alt="image" …

fix(blind_spot): cut virtual blind lines up to intersection lanelet's bound

---

planning/behavior_path_planner/autoware_behavior_path_start_planner_module/README.md
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/config/start_planner.param.yaml
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/include/autoware/behavior_path_start_planner_module/data_structs.hpp
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/clothoid_pull_out.cpp
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/data_structs.cpp
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/manager.cpp
planning/behavior_path_planner/autoware_behavior_path_start_planner_module/src/start_planner_module.cpp

parameter change [PR](https://github.com/autowarefoundation/autoware_launch/pull/1621) should be merged together
This PR fixes an issue where the clothoid pull-out functionality was incorrectly using `shift_collision_check_distance_from_end` parameter for collision checking, and adds a dedicated parameter `clothoid_collision_check_distance_from_end` for proper configuration.
- Added the new dedicated parameter `clothoid_collision_check_distance_from_end` to configuration files, data structures, and parameter handling
- Adjusted the default `ignore_object_velocity_threshold` from 1.0 to 0.25 m/s for more sensitive object detection(default value was updated in autoware_launch repository before)
- Link
- run psim
None.
None.
| Change type | Parameter Name …

fix(start_planner): clothoid collision check offset parameter

---

planning/planning_validator/autoware_planning_validator_rear_collision_checker/src/utils.cpp

In the previous implementation, collision checking was triggered even when the path behind the ego deviated into an adjacent lane, although such cases should not require detection. This was because the logic relied on index-based checks to determine whether trajectory points were located behind the ego, which sometimes caused unnecessary collision detection due to discretization errors. In this PR, the distance between each point and the ego is calculated as a continuous value, and collision detection is now performed only when a deviation into an adjacent lane occurs in front of the ego’s front. This refinement eliminates false detections caused by index-based errors and ensures more accurate behavior.
For example, as shown in the video, the system incorrectly focused on the left side …

fix(rear_collision_checker): correct deviation judgment logic from current driving lane

---

planning/autoware_trajectory_optimizer/src/trajectory_optimizer.cpp
planning/autoware_trajectory_optimizer/src/utils.cpp

Changes warning and error messages in the optimizer to be of throttle type as to not pollute the terminal excessively.
- Link
PSim
None.
None.
None.

fix(autoware_trajectory_optimizer): reduce excessive optimizer logging

---

localization/autoware_pose_instability_detector/config/pose_instability_detector.param.yaml
localization/autoware_pose_instability_detector/include/autoware/pose_instability_detector/pose_instability_detector.hpp
localization/autoware_pose_instability_detector/schema/pose_instability_detector.schema.json
localization/autoware_pose_instability_detector/src/pose_instability_detector.cpp

This PR adds a new parameter `enable_validation` to the pose_instability_detector so that the validation can be toggled by each dimension (x, y, z, roll, pitch and yaw).
This feature is added so that the instability checking for roll and pitch is not reliable for some vehicles.
Changes to autoware_launch: https://github.com/autowarefoundation/autoware_launch/pull/1630
Checked that the `rqt_runtime_monitor` looks like this
Checked that the `ros2 param dump /localization/pose_twist_fusion_filter/pose_instability_detector` looks like this
Checked that `colcon test` passes.
This PR should me merged with https://github.com/autowarefoundation/autoware_launch/pull/1630.
Below `enable_validation` …

feat(pose_instability_detector): make pose_instability_detector filtered by dimensions

---

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/README.md
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/config/lane_change.param.yaml
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/scene.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/structs/parameters.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/manager.cpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/path_safety_checker/safety_check.hpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/path_safety_checker/safety_check.cpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/test/test_safety_check.cpp

1. Currently, the safety check is disabled during the prepare phase, except in cases such as when the ego is in turn-direction lanes or intersections. When disabled, the first few seconds of safety checks are skipped.
- This is usually not an issue if both vehicles are moving. However, if the ego is stopped while the target vehicle is moving, the skipped safety checks can create a potential near-miss situation, since the initial seconds are incorrectly considered “safe.”
- This PR fixes the issue by enabling the safety check during the prepare phase.
3. Previously, the prepare phase reused the same RSS parameters as the lane change phase. This made lane changes difficult to execute, as the extended ego polygon (both laterally and longitudinally) frequently overlapped during preparation.
- …

feat(bpp, lane_change): enable prepare phase check even when ego is preparing

---

planning/autoware_diffusion_planner/include/autoware/diffusion_planner/dimensions.hpp
planning/autoware_diffusion_planner/include/autoware/diffusion_planner/preprocessing/lane_segments.hpp
planning/autoware_diffusion_planner/src/preprocessing/lane_segments.cpp

This PR refactors the diffusion planner to use the `lane_segments_` member variable directly instead of extracting data from the matrix representation, improving code clarity and reducing redundant data storage.
- Store lane segments as a member variable and access segment properties directly from the original data structure
- Remove redundant storage of speed limit, lane ID, and turn direction in the matrix representation
- Update matrix dimension constants to reflect the reduced data storage requirements
* Before
* create_input_data        1.0 ± 0.4 msec
* After
* create_input_data        1.0 ± 0.5 msec
None.
None.
None.

refactor(diffusion_planner): fix to use `lane_segments_`

---

system/autoware_pipeline_latency_monitor/src/pipeline_latency_monitor_node.cpp

Negative latency warning messages like 
```
Negative latency value detected: -75.329322, treating as 0.0
```
are being output periodically and cluttering the terminal output. This change suppresses WARN-level logging when negative values are calculated to reduce log noise.
- Link
None.
None.
None.

refactor(pipeline_latency_monitor): change log level from WARN to DEBUG for negative latency values

---

planning/autoware_rtc_interface/README.md
planning/autoware_rtc_interface/include/autoware/rtc_interface/rtc_interface.hpp
planning/autoware_rtc_interface/src/rtc_interface.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/README.md
planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/manager.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/README.md
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/manager.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_rtc_interface/include/autoware/behavior_velocity_rtc_interface/scene_module_interface_with_rtc.hpp

This PR enables the use of lanelet attributes to force some modules to use the manual RTC mode when going through the corresponding lanelet.
https://github.com/user-attachments/assets/a675d168-35b9-4206-bb9d-afe34e5c5400
- [TIER IV internal link](https://tier4.atlassian.net/browse/RT1-10926)
None.
None.
None.

feat(RTC, behavior_velocity_planner): set manual RTC via the lanelet map

---

planning/autoware_diffusion_planner/include/autoware/diffusion_planner/conversion/lanelet.hpp

Fix the following error in debug build:
```bash
/usr/bin/ld: libautoware_diffusion_planner_component.so: undefined reference to `autoware::diffusion_planner::LaneSegment::TURN_DIRECTION_LEFT'
/usr/bin/ld: libautoware_diffusion_planner_component.so: undefined reference to `autoware::diffusion_planner::LaneSegment::TURN_DIRECTION_STRAIGHT'
/usr/bin/ld: libautoware_diffusion_planner_component.so: undefined reference to `autoware::diffusion_planner::LaneSegment::TURN_DIRECTION_RIGHT'
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/test_diffusion_planner.dir/build.make:1045: test_diffusion_planner] エラー 1
gmake[1]: *** [CMakeFiles/Makefile2:213: CMakeFiles/test_diffusion_planner.dir/all] エラー 2
gmake: *** [Makefile:146: all] エラー 2
---
Failed   <<< autoware_diffusion_planner …
```

fix(diffusion_planner): fixed `const` to `constexpr`

---

.github/workflows/build-and-test-daily.yaml
.github/workflows/build-and-test-differential-arm64.yaml

This updates the workflows for arm64 to use GitHub hosted runners instead of self-hosted runners since we are no longer using self-hosted runners.
- https://github.com/autowarefoundation/autoware_universe/issues/11334
https://github.com/autowarefoundation/autoware_universe/actions/runs/17765450327
None.
None.
None.

ci: use github hosted runner for arm

---

planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/config/obstacle_slow_down.param.yaml
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/src/obstacle_slow_down_module.cpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/src/obstacle_slow_down_module.hpp
planning/motion_velocity_planner/autoware_motion_velocity_obstacle_slow_down_module/src/parameters.hpp

Added a lateral distance offset feature for curves.
For more details, please refer to the same feature in the obstacle_stop module: https://github.com/autowarefoundation/autoware_core/pull/619
launch: https://github.com/autowarefoundation/autoware_launch/pull/1638
obstacle_stop: https://github.com/autowarefoundation/autoware_core/pull/619
tier4 scenario test
psim with the paremeters, `medium_bus`, `wheel_off_track_scale: 1.0`
depends to https://github.com/autowarefoundation/autoware_core/pull/628
None.
None.

feat(obstacle_slow_down): add curve margin feature

---

planning/planning_validator/autoware_planning_validator/include/autoware/planning_validator/node.hpp
planning/planning_validator/autoware_planning_validator_trajectory_checker/test/test_trajectory_checker_diag.cpp

This PR updates the QoS settings for the operational mode state subscriber in the autoware planning validator. 
This change is necessary because the publisher side is configured with `transient_local` QoS settings, requiring the subscriber to use matching QoS configuration for proper communication.
- Link
None.
None.
None.

fix(planning_validator): update QoS settings for operational mode state subscriber

---

evaluator/autoware_control_evaluator/include/autoware/control_evaluator/control_evaluator_node.hpp
evaluator/autoware_control_evaluator/include/autoware/control_evaluator/metrics/metric.hpp
evaluator/autoware_control_evaluator/src/control_evaluator_node.cpp

Publish lateral_acceleration from control_evaluator
topic `ros2 topic echo /control/control_evaluator/metrics`:
```
---
stamp:
sec: 1758681871
nanosec: 336141463
metric_array:
- name: velocity
unit: ''
value: '3.428018'
- name: acceleration
unit: ''
value: '-0.200566'
- name: lateral_acceleration_abs
unit: ''
value: '0.862711'
...
```
output json:
```
{
...
"lateral_acceleration_abs/count": 292,
"lateral_acceleration_abs/description": "Lateral acceleration[m/s^2]",
"lateral_acceleration_abs/max": 0.9575651791075276,
"lateral_acceleration_abs/mean": 0.24934301433476605,
"lateral_acceleration_abs/min": 0.0,
...
}
```
- Link
Psim
None.
None.
None.

feat(control_evaluator): add lateral_acceleration_abs metric

---

sensing/autoware_cuda_pointcloud_preprocessor/include/autoware/cuda_pointcloud_preprocessor/cuda_pointcloud_preprocessor_node.hpp
sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_pointcloud_preprocessor/cuda_pointcloud_preprocessor_node.cpp

This PR fixes an issue where distortion-corrected pointclouds appear in an unexpected region.
The root cause of the issue lies in precision loss on timestamp comparison if two timestamps are close on a micro- or nanosecond level. This PR resolves this issue by expressing timestamps in nanoseconds using `std::uint64_t` instead of expressing them in seconds using `double`.
- [TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT0-39571)
- Download rosbag:
```bash
webauto data rosbag pull --project-id x2_dev \
--environment-id 5fd46b47-f1a2-48e0-aeaa-75cd9c68197d \
--rosbag-id 0e2e1965-317d-4c51-af0c-256e201e66a6 \
--target-dir ${TARGET_DIR}
```
- Generate a rosbag that contains the topics required for  logging simulator
- Nebula workspace needs to be `source`d for …

fix(cuda_pointcloud_preprocessor): use uint64_t and nanoseconds to prevent potential precision loss

---

planning/behavior_path_planner/autoware_behavior_path_goal_planner_module/src/default_fixed_goal_planner.cpp
planning/behavior_path_planner/autoware_behavior_path_planner/test/test_utils.cpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/include/autoware/behavior_path_planner_common/utils/utils.hpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/src/utils/utils.cpp
planning/behavior_path_planner/autoware_behavior_path_planner_common/test/test_utils.cpp

This PR improves the smoothness of the goal planner's path.
-  additional waypoints have been added to prevent the path from making sharp turns right before reaching the goal.
- longer bbackwward path is now retained, preventing sudden path changes (https://github.com/autowarefoundation/autoware_launch/pull/1645).
- [CommonScenario_Basic](https://evaluation.tier4.jp/evaluation/reports/09ce0158-03b8-5020-b830-97900fd397ed?project_id=prd_jt)
- [FuncVerificationScenario_Basic](https://evaluation.tier4.jp/evaluation/reports/28bb6548-9af6-5aba-b158-2f15c87713bb?project_id=prd_jt)
- [ControlDLRCommon_Basic](https://evaluation.tier4.jp/evaluation/reports/d6cabbd7-4bd9-5865-af13-6d65c1c1c75b?project_id=prd_jt)
None.
None.
None.

fix(goal_planner): smooth goal connection for goal_planner

---

planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/README.md
planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/schema/run_out.schema.json
planning/motion_velocity_planner/autoware_motion_velocity_run_out_module/src/map_data.cpp

The `run_out` module uses parameters to define map geometries (linestring, polygon, lanelets) that can be used to filter the predicted paths or collisions used by the module.
Previously, polygons could only be selected based on their `type`. This PR adds a way to also define their `subtype`.
- [TIER IV internal link](https://tier4.atlassian.net/browse/RT0-39491)
Psim after adding an item in the `polygon_types` parameter in the format `type.subtype` (e.g., `area.vegetation`).
None.
None.
None.

feat(run_out): support specifying polygon subtypes for map filtering

---

simulator/autoware_carla_interface/src/autoware_carla_interface/carla_ros.py

This PR fixes spell-check CI error by replacing `ROS2` to `ROS 2`.
- Link
None.
None.
None.

chore(carla-interface): fix spell-check

---

planning/autoware_freespace_planner/src/autoware_freespace_planner/utils.cpp

This is a recreation of https://github.com/autowarefoundation/autoware_universe/pull/7859.
I have made some updates to avoid repeating calculation of `th_stopped_velocity_mps * th_stopped_velocity_mps` compared  to the original PR.
https://github.com/autowarefoundation/autoware_universe/issues/7834
None.
None.
None.

feat(autoware_freespace_planner): utilize all 3 components of velocity

---

planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/include/autoware/behavior_velocity_intersection_module/decision_result.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/include/autoware/behavior_velocity_intersection_module/intersection_stoplines.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/include/autoware/behavior_velocity_intersection_module/scene_intersection.hpp
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection_collision.cpp
planning/behavior_velocity_planner/autoware_behavior_velocity_intersection_module/src/scene_intersection_prepare_data.cpp

In order to avoid "will_overrun" diagnosis, the planner needs to memorize stop position and keep inserting the position.
Following PRs
- https://github.com/autowarefoundation/autoware_universe/pull/10900
- https://github.com/autowarefoundation/autoware_universe/pull/11247
are problematic because
- if stopline moves dynamically according to current barking_distance, the controller's tracking to expected stopline degrades
- even if previous stopline is hold, actual stop position is inserted at the point closeset to it, causing some error for the desired stop position and making that stop line position moves a bit depending on the interpolation result in each cycle.
In the future subsequent PR,
- once stop position is commanded, it is memorized.
- when generating IntersectionStopLine, …

feat(intersection): revert stop position calculation as before temporarily

---

planning/autoware_diffusion_planner/src/postprocessing/postprocessing_utils.cpp

This PR adds logic to propagate the last smoothed velocity to remaining trajectory points. The issue was that the last few trajectory points weren't having their velocities properly set after the velocity smoothing window operation.
https://github.com/user-attachments/assets/dc072a49-f5d7-42d0-a71b-8b2ece00a930
https://github.com/user-attachments/assets/0229d1a3-fae1-4b73-8605-e901940b2404
None.
None.
None.

fix(diffusion_planner): fix remaining velocity

---

planning/behavior_path_planner/autoware_behavior_path_lane_change_module/README.md
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/scene.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/structs/data.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/include/autoware/behavior_path_lane_change_module/utils/utils.hpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/scene.cpp
planning/behavior_path_planner/autoware_behavior_path_lane_change_module/src/utils/utils.cpp

Stopping object behind ego vehicle is ignored during safety check. This sometimes create an issue if object temporarily stops beside ego vehicle, as shown in the following video, where there is a split moment while the object is not moving, the object classification turned purple, meaning it is not treated as target lane object.
https://github.com/user-attachments/assets/bbea15e7-47a4-4d99-b5d4-ce10a5b14b35
This PR aims to fix this by considering the object as stopping object if it overlaps with ego side.
|:-:|:-:|
| <img width="1497" height="891" alt="before" src="https://github.com/user-attachments/assets/307d4c25-2a83-4b43-b6c1-142eac0b3423" /> | <img width="1497" height="894" alt="after" src="https://github.com/user-attachments/assets/35beb61d-3a7a-40cd-93d7-b58ca673 …

fix(lane_change): include stopping object beside ego as target

---

planning/motion_velocity_planner/autoware_motion_velocity_out_of_lane_module/src/out_of_lane_module.cpp

This PR adds a check to make sure the `out_of_lane` module does not output an unfeasible stop point.
When it is too late to avoid the `out_of_lane` collision, ego will keep driving instead of generating an unfeasible stop.
- [TIER IV internal link](https://tier4.atlassian.net/browse/RT0-39670)
Psim + Reproducer
None.
None.
None.

fix(out_of_lane): ensure the calculated stop pose is feasible

---

localization/autoware_pose_instability_detector/config/pose_instability_detector.param.yaml
localization/autoware_pose_instability_detector/schema/pose_instability_detector.schema.json

The pose_instability_detector detects position jump of vehicles and its threshold is calculated based on the parameters.
The parameter `pose_estimator_vertical_tolerance` manages the jump of the z coordinates but the current default value `0.11` is too small when we consider bumpy roads. This PR relieves it to `0.5` meters.
Autoware will read the parameters in the autoware_launch. The PR below is the corresponding one to this PR.
https://github.com/autowarefoundation/autoware_launch/pull/1667
None.
| Version | Parameter Name   | Type     | Default Value | Description       |
|:--------|:-----------------|:---------|:--------------|:------------------|
| Old     | `pose_estimator_vertical_tolerance` | `double` | **`0.11`**         | Tolerance of pose difference in the z coordinates |
| New …

chore: relieve pose_estimator_lateral_tolerance to 0.5
